### ISSUE TITLE
Disable team building controls in controllers

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1156]
I'm writing this up separately from #1116 so it doesn't have to wait around or grow too huge.

The idea would be to expand on #1116 and make sure if a UI control was missed, the controller itself won't allow forbidden actions based on SeasonToggles.

**Comment by Allicolyer** [comment]
@stenington we would like to close this card out. Do you think it's still relevant?

**Comment by stenington** [comment]
So I'll explain what this card was getting at, and then let you decide.

This is a clunky analogy but pretend you have some piece of machinery that you do not want turned on right now, and it's plugged into an outlet that can be turned on from 3 different light switches in the room. One way to try to prevent people from turning the machine on is to go around and cover up all the light switches that control that outlet. But let's say you cover up 2 but forget to cover up the 3rd... someone might come along and flip that switch and accidentally turn on the machine that you don't want turned on right now. A more secure way to make sure it's not going to be turned on is to cover up the light switches AND unplug it from the wall. Now if you forget a switch, it still won't turn on.

So in this analogy, the light switches are like buttons or links in the UI, and the machine is some backend feature, like sending team invites or whatever. We were going around hiding all the buttons, but I was suggesting that we also make the code check for the setting and refuse to do the action according to the season toggles as well.

**Comment by Allicolyer** [comment]
Hey @stenington! Thank you for this quick response. This is a good analogy. I think we should keep these technical debt tickets around. They can inform us as we continue to improve the dashboards and other things on the site.
