### ISSUE TITLE
Removing membership from team

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1174]
@Allicolyer raised the question of whether users should ever be prevented from removing themselves from a team. I had the same question. My only hesitation against allowing it is whether someone will end up clicking the button out of curiosity and then not be able to add themselves back. We saw people leave RPEs after the events had ended and such things that didn't make any sense from a season point of view, which messes up our data a little bit.

**Comment by Allicolyer** [comment]
closed due to a discussion during a sprint
