### ISSUE TITLE
Expand RA features: Enable missing participant search

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1180]
When RAs are planning their events, they cannot always find the judges, students, or teams that should appear in their region.

They are locked into location-based data that is only (maybe) correctly saved that matches their location data.

One simple solution is to allow an RA to search all users and amend their location data.

QA:

- An RA can now search all users by name / email
- They can edit the user's location data
- They can only get one result at a time with correctly spelled search input

**Comment by kmorton2017** [comment]
Extra space after participant name prevents results from showing up

**Comment by joemsak** [comment]
This should now be fixed
