### ISSUE TITLE
Team / Submission public pages - keep private unless students opt-in

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1202]
maggie
[11:00 AM] 
the pages are public, but there was concern from our team that because we never explicitly asked for consent from the girls to make their pages public, we shouldn't share on the website or on social media. (We're pushing to change this for next season so we can share all pages!) However, because we got consent from the finalists to share their work, I think we could add links to their pages -- @amy or @madhavi do you have thoughts?

madhavi 
[11:02 AM] 
Yes, we can't share public versions of all teams yet. Next year, we will have an opt out option for all team to check if they don't want us to share their work. For the finalists, we have asked for their consent to share these before WP, so we can only link their submissions only.

**Comment by Allicolyer** [comment]
Some updates on this as on February 2019:

I am not aware of any updates in the "opt out" system for public pages. I do not see a place for RAs and admins to access public pages.

Published URLs of submissions still exist, and this is what we were using as public pages in 2017: https://technovation-qa.herokuapp.com/student/published_team_submissions/heres-a-name-by-student-union#/

You must be logged in to your account to visit your public page. As of right now, public pages are not functional. Sometimes fundraising stresses that they really need them for fundraising purposes.

**Comment by rsgonzal** [comment]
Do we use/have a use for these? @ophelieh @ksrebecca

**Comment by ksrebecca** [comment]
This is a big nice to have that we've talked about a couple of times in the product call I think? If I recall correctly it's been linked to our conversations about students being able to see their past work in a sort of portfolio so they can 1) see how they've grown and 2) could share with others if needed. I would say it's probably linked to our seasonality discussion if we want to reopen that at some point.

**Comment by ophelieh** [comment]
If it is something they can opt-in (it shouldn't be automatic for the page to be public), I think that would be awesome but we would need some special language due to the European laws. But like Rebecca said - it's a nice to have more than a need.
