### ISSUE TITLE
X Archive off old data

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1207]
~Must add datetime(last_logged_in_at) to accounts and track it during SignIn.(account)~

See if we can save space on the production database and reduce costs
Let's archive off users who haven't returned in 2 seasons

Archive off HonorCodeAgreements

Archive off voided parental consents

Archive off voided consent waivers

Archive off all data related to old accounts who haven't logged in

Archive off all soft-deleted records from last season

Archive off stale signup attempts (updated_at > some threshold)

**Comment by hellafitz** [comment]
@stenington is this still relevant and/or useful as a reminder?
