### ISSUE TITLE
RAs, mentors -- merge duplicate accounts

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1253]
Some RAs have mentor accounts through a separate email, most likely with the + trick.

Find these accounts and merge the profiles

**Comment by joemsak** [comment]
comments with sensitive data deleted

**Comment by kmorton2017** [comment]
Merge Nezha's Larhissi's RA account (currently nezha290799@gmail.com) under larhrissi.nezha@gmail.com.

**Comment by joemsak** [comment]
Closing in favor of #1353
