### ISSUE TITLE
Back button sometimes reloads page

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1274]
This was seen while demoing some pages. The student team page, for example, will just reload when clicking the back button.

I don't think it's turbolinks, I think it's because in `tabs.js` [this line](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/assets/javascripts/tabs.js#L79) should be using [history.replaceState()](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method). I'm not sure if we need to shim it as well for older browsers.

**Comment by joemsak** [comment]
This has been fixed
