### ISSUE TITLE
Display bug on chosen-select for location form at 1024px

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1285]
Strange display bug here. It's still a select box but doesn't look like one. Widening the screen makes the style return.

![uploads/520be76c-b26a-49d8-b6a8-4eada8663102/Screen Shot 2017-09-21 at 9.20.03 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F520be76c-b26a-49d8-b6a8-4eada8663102%2FScreen+Shot+2017-09-21+at+9.20.03+AM.png)

**Comment by Allicolyer** [comment]
@joemsak closing this out since we changed the location selection process.
