### ISSUE TITLE
Survey pop up changes

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1305]
@madhavitechnovation to provide desired behavior details

* Show the modal popup if the person has been signed up for 2 or more weeks
* Let them close it 
* Don't pop up again for 2 more weeks from the time it was closed
* Let them close it
* Bother them ONE more time, in 2 weeks
* Let them close it forever

QA:

READ ALL THE NOTES AND STEPS FIRST AND MESSAGE JOE ON SLACK IF YOU'RE CONFUSED

Notes:

 ---- Do not worry about where the survey link goes, it is just a test on QA, and I set the link to google.com

---- the staff can set the survey link to any URL they want

---- feel free to login as the admin on QA and test this yourself, but it is not part of this card!

1. Sign up as a brand new student or mentor
2. Make sure you've seen your dashboard
3. Verify the modal did NOT pop up on you
4. Message Joe on slack
5. Tell him you're ready to test the 2 week reminders, and give him your new account's email
6. Joe will change your data to make your account appear 2 weeks older
7. Reload the dashboard when Joe says it's ready
8. Verify the modal pops up
9. Close the modal
10. Reload the dashboard
11. Verify the modal does NOT pop up

12. Repeat steps 4-11
13. Repeat steps 4-7 (your account's "reminded_at date" will be set to 2 weeks ago)
14. Verify that you do not get the pop up a 3rd time

**Comment by ophelieh** [comment]
@joemsak Works great! :)
