### ISSUE TITLE
RA viewing user activity - prototype

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1326]
Track:

- Updated profile

- Updated team information

- Consent / BG check stuff

- Joined a team
- Was invited
-- approved / declined

- Sent a request to join
-- was approved / was declined

- Team found a mentor

- Added a Mentor / Judge profile

- Logging in activity

- Team submission tracking (next sprint)

- Generate more ideas together once we've seen it

**Comment by kmorton2017** [comment]
I like the information that's included on my side bar, particularly draws my attention to students who have been inactive. the one drawback is that the page looks a little crowded now and the graphs are much smaller.

**Comment by joemsak** [comment]
@kmorton2017 bumping the font-size of the labels up will squish the pie charts even smaller, unfortunately. I am not in full control of the library we're using to display data in charts, so please be aware I may not be able to address every concern. 

The size of the charts naturally have to be smaller to allow for another column to show the user activity feed. I do agree the dashboard feels visually busier and I will be thinking of ways to improve that, which may eventually lead to the charts having more space to be bigger, but I really can't say at this time. I'm not a visual designer by trade and have to do these things through trial and error over longer periods of time and multiple iterations

**Comment by madhavitechnovation** [comment]
I think this card is good. I feel this is huge improvement for RAs from last season...this information will be super helpful for them. Agree with Katie that we can make some improvements on the fonts, look and feel but I think we can roll this out and work on any improvements later. The huge value of this UI is the helpful information that RAs will see.
