### ISSUE TITLE
Mentor onboarding checklist (similar to student season checklist)

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1341]
From a comment by @kmorton2017 on another ticket:

I'm wondering if we can make [the onboarding steps] more apparent to mentors? Similarly, have a progress bar that students have on the righthand side. Or have a message that says you will be unsearchable until you complete all of these steps (something along those lines).

**Comment by Allicolyer** [comment]
closing due to wizard style onboarding updates
