### ISSUE TITLE
ONGOING RA TASKS

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1353]
Import new RAs from Katie's spreadsheet
Remove unapproved RAs from Katie's spreadsheet
Merge duplicate RA / Mentor accounts

This task doesn't have a definite end date

**Comment by kmorton2017** [comment]
Merge RA/Mentor accounts for Daniela Abasi under danielad@sfu.ca

**Comment by joemsak** [comment]
@kmorton2017 Done https://my.technovationchallenge.org/admin/participants/22002

**Comment by kmorton2017** [comment]
I am not sure if you saw this but it looks like nezha's acct hasn't been merged yet. can you merge RA/Mentor accounts for Nezha Larhissi under larhrissi.nezha@gmail.com?

**Comment by joemsak** [comment]
@kmorton2017 done https://my.technovationchallenge.org/admin/participants/36003

**Comment by joemsak** [comment]
@kmorton2017 you can now do all of these tasks easily in the Admin UI
