### ISSUE TITLE
RA Participant Data Filters

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1355]
Search participants by:

* Team Division
* Parental Consent
* Consent waiver
* Background check

**Comment by kmorton2017** [comment]
1) it's difficult to search for students regardless of season (ie if they were past participants and I'm trying to find them again). 
2)  searching for multiple seasons could be confusing because it is an AND feature not an OR feature

**Comment by kmorton2017** [comment]
If i search for "unmatched mentors"  it gives me a list of both unmatched mentors AND students. this happens vice versa, if i search for unmatched students, it will give me both in the search results.

**Comment by kmorton2017** [comment]
searched for Parental Consent on file (10)  and No Parental Consent (13) on file in SF. This does not equal the total number of students in SF which is 34.

**Comment by joemsak** [comment]
@kmorton2017 The counting on parental consent should now be fixed :)

**Comment by joemsak** [comment]
I'm splitting our unmatched mentors bug into a separate card cos it's a bigger bug

**Comment by joemsak** [comment]
The AND vs. OR feature is now fixed such that it uses OR, which seems more intuitive, both for the Season and Profile Type filters

**Comment by kmorton2017** [comment]
when i search for "jennifer john" she comes up on the 2nd page of the search results when students such as "ada johnson" come up first.

**Comment by kmorton2017** [comment]
i don't think the counting has been fixed. i search for students without parental consent in california (68) and with parental consent (89) and this does not equal the total number of students in california (222).

**Comment by kmorton2017** [comment]
from what i understand, if i want to search for a student within any season, i would type in 2018, 2017, etc. this would be the OR feature. 

what if i only want to see students who are returning AND who have done both seasons to download this list? essentially i wondering about both use cases AND, OR.

**Comment by joemsak** [comment]
@kmorton2017 I will split the AND/OR option to another card, as it is a bigger feature requiring UI design

I will write some tests and work on the counting error today. I reproduced it, and verify your report.

I will see if I can improve the relevancy sorting of searches that have stronger matches. It's a bit of an advanced topic for me and I don't know off hand where to start with enabling it in the software we're using, but I will do some research and see if I can find an existing technique that I am simply not familiar with.

Obviously, relevancy sorting does exist, we've all seen it on other sites, and last year's search engine supported it. Last year's search engine, though, was expensive and overkill for our needs, and the code to configure it was difficult for me to learn, memorize, and understand, and therefore was buggy (as you recall, with email search for example) due to my inability to code with it correctly.

I will see what our basic database tech can do, because that's what is powering the search and filtering now,  and I hope to find some existing utilities I can take advantage of to achieve relevancy sorting.

**Comment by kmorton2017** [comment]
sounds good! re: relevancy of sorting, i consider this is a "nice to have" but not top priority. at the end of the day you can still find the user!

**Comment by joemsak** [comment]
Sure Katie, I understand, and I would honestly upgrade the improved sorting to "better to have" so I will make a card and study our tech today
