### ISSUE TITLE
RA Teams pages (basic copy of Participant data)

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1357]
This card will split into smaller cards

Team search filters:
* Division
* Matched with a mentor
* City, State (always assume for all tables)
* Are all students eligible to compete?

**Comment by kmorton2017** [comment]
are there any action items for QA on this card?

**Comment by joemsak** [comment]
@kmorton2017 yes, please give a similar review as has been done for the participants section
