### ISSUE TITLE
RA Internal comments about participants

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1358]
Options:

- An internal feed on the participant's page?
-OR-
- A link to 'Notes' in the participants submenu?
---- 

Show recent notes (or snippets of longer notes) on the dashboard

**Comment by Allicolyer** [comment]
Conclusion: This could be a lot of work. We don't have a good way of doing it now. Each RA needs a way to mark something different for students. There might also be safety concerns.
