### ISSUE TITLE
RA Resource Links

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1361]
See comments below for expected links in the Resources section

**Comment by kmorton2017** [comment]
Need to add RA Resources on the dashboard (similar to student/mentor feel): 

RA Resource Page
RA Handbook
Parental Consent PDF 
Curriculum Link
Submission Guidelines
Judging Rubric

**Comment by joemsak** [comment]
@kmorton2017 (or @madhavitechnovation if Katie is busy now with her upcoming trip)

Could you please give me the links to these resources? Thanks!
I don't know the URLs for these:
RA Resource Page
RA Handbook
Parental Consent PDF

If the PDF isn't hosted anywhere, I can host it on our app, just attach the file here. Thanks!

**Comment by audsbodin** [comment]
http://technovationchallenge.org/ra-resources/

**Comment by madhavitechnovation** [comment]
Parental consent form is available here as a pdf to download: https://iridescentsupport.zendesk.com/hc/en-us/articles/115002731034-How-do-I-submit-the-consent-forms-#article-comments

RA Handbook: https://iridescentlearning.atavist.com/technovation-ra-handbook

The link Audra provided above is for the R resource page.

Let us know if anything else is missing.

Thanks!

**Comment by kmorton2017** [comment]
FAQ/Rules -https://iridescentsupport.zendesk.com/hc/en-us/categories/115000091348-Technovation

**Comment by ophelieh** [comment]
Every link goes to the right page and works. Just one thing, would it be possible to have the PDF directly download from the "Download the PDF" link? I can send you the PDF via email.

**Comment by joemsak** [comment]
Yes please, that is also what I would prefer, I just went with the URL I was given

**Comment by joemsak** [comment]
@ophelieh never mind I found the PDF url and updated the link

**Comment by ophelieh** [comment]
Looks great! :)
