### ISSUE TITLE
Admins: detect foreign language activity and alert via email / dashboard

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1362]

**Comment by Allicolyer** [comment]
Conclusion: RPEs leave feedback in other languages on purpose. Judging would be confusing. This card is probably about detecting foreign languages for submissions.

This would be a dream future feature for submissions. If we could detect submissions in other languages that would really help some teams. This would require a good API, so we need to do research and we also need pay for an API.
