### ISSUE TITLE
RA City / State search bug

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1363]
Admin/RA participants - search by city (or state) doesn't appear to be working correctly

**Comment by joemsak** [comment]
The problem is with foreign states / cities ... they need to be translated.

I will need RAs to help me detect specific ones

**Comment by kmorton2017** [comment]
when I try and search for United States--State--Students, I get both mentors and student search results

**Comment by joemsak** [comment]
The students/mentors bug has been fixed, please check and let me know

Yes, RAs can already search by city but they must first pick a state and only search one state, otherwise the city field doesn't know which options to be pre-populated with

**Comment by kmorton2017** [comment]
ok thanks!
