### ISSUE TITLE
Admins: Invite Users

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1364]
Invite Users by email and which profile type to sign up as
They get an email with a special link
It takes them to the form for their profile type
They fill it in with a password, it signs them up and logs them in

QA:
READ ALL STEPS CAREFULLY BEFORE STARTING
MESSAGE JOE ON SLACK IF YOU ARE CONFUSED *BEFORE* YOU START

- Log in to https://technovation-qa.herokuapp.com as the Admin
  - We HIGHLY recommend you log in as the admin in a private browser window!

---

- Go to "Invite users" - it's a smaller link in the navigation

- Invite yourself via email as each type of profile
  - Remember to use the + trick to enable multiple accounts on the same email inbox
  - Verify that you cannot create new invites for the same email twice
  - Verify that you cannot create an invite for an email that already exists on a participant's 
account
  - Verify that you have the option to Re-Send the invite email, and go ahead and do so
  - Verify you get another email when you hit Re-Send

---

- From a NON-PRIVATE browser window of your email inbox:
  - Open the link to sign up in your email

---

- Verify that the Admin UI of user invitations https://technovation-qa.herokuapp.com/admin/user_invitations shows your invitation as "opened" and you cannot re-send it
  - Remember to do this in the same private browser window as mentioned above!

---

- Verify that you can sign up as each type of profile

---

- Go back to the Admin UI of user invitations as mentioned above
  - Verify that your signed up accounts now show their invites as registered with a link to your participant details page for the Admin, and you cannot re-send the invitation

**Comment by joemsak** [comment]
@kmorton2017  Could you please QA this one? You're going to be the primary user of this feature

**Comment by kmorton2017** [comment]
Verified all steps. Created accounts for all users.

Note: when I register as a new RA it asks for my location on the dashboard. But when I go to My Location to change it, it says I have to contact admin support which could be confusing. Not high priority-minor.

**Comment by joemsak** [comment]
@kmorton2017 Is it enough for now that they can do it from the dashboard prompt?

**Comment by joemsak** [comment]
@kmorton2017 never mind, I have space to fix it today ... fixing now
