### ISSUE TITLE
Student & Mentor welcome email updates

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1365]
Add the link to the student slack shared invite URL, with a call to action to join, and a reminder that under 13 cannot sign up

`*Please note that under our Terms of Service, anyone under the age of 13 is not permitted to use Slack.`

Update the mentor welcome email to anticipate a slack invitation, instead of using the request URL

`Accept your invitation to join the Slack community (it will be a separate email).`

**Comment by ophelieh** [comment]
Student welcome email: looks good. I just noticed that there is no link to the FAQ at the bottom of the email. It might not be intuitive to everyone to check the bottom of the page on their dashboard. 

![uploads/ba723b0d-8e23-45e8-b894-68f919f3d94d/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fba723b0d-8e23-45e8-b894-68f919f3d94d%2Fimage.png)

Mentor Welcome Email: looks good. It's just missing my Slack handle. :) @ophelie

**Comment by joemsak** [comment]
@ophelieh thank you for your QA, the emails have been updated!

**Comment by ophelieh** [comment]
@joemsak It all looks great. :) And sorry for not responding sooner, I did not realize I was supposed to. :(
