### ISSUE TITLE
Investigate survey monkey features for help in tracking respondants

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1366]
This card will not go through QA

Staff is discussing my recommendations based on my research

- Set a custom end page (this is per collector link, not per survey)
- The end page is ready and tested on the platform, to track on someone's account that they took the survey

- Try an email collector link

  - Export custom CSV from Admin UI:
    - City, State, Country, School/Company, Age, Profile Type
    - Import to Survey Monkey contacts
    - Send an email collector link

- Try an email collector link and web collector link, compare results
  - Possibly submit custom variables to the web collector link, to avoid them filling in the same data on the survey that we already collected on the site

**Comment by joemsak** [comment]
@madhavitechnovation @ophelieh here is the card around our survey monkey discussion around my findings today

**Comment by ophelieh** [comment]
@joemsak Thank you! :)
