### ISSUE TITLE
RA/Admin Team filter: "teams with/without mentors"

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1370]
Login as the admin
Go to Teams
Verify that you can search by teams with or without mentors

---

Go to Participants
Find an RA
Login as the RA
Verify the same steps above for RAs

**Comment by ophelieh** [comment]
Teams: 
- when I selected "Yes, has a mentor" + "yes, has students": I get teams with only mentors and no students (in the division column it shows - none assigned yet)+ teams with students and mentors. 
- when I select "yes, has a mentor" + "no students matched yet": I get 0 teams, even though with the above combination, it showed me teams with no students. 
- when I select "no mentor matched yet" + "yes, has students": I get 0 teams. 
- when I don't select anything: I get  448 teams. 
- when I select "yes, has students": I get 991 teams. Looks like each team shows multiple times depending on the number of students in the team. 
- when I select "yes, has mentors": I get all the teams with mentors, including teams with no students.

**Comment by ophelieh** [comment]
Participants (logged in a Jean Weiss): 
same as above (except with the number of teams in that region)

**Comment by joemsak** [comment]
hey @ophelieh thank you for your QA!

I have updated the code, can you do another test and let me know if it is behaving better? Thanks!

**Comment by ophelieh** [comment]
@joemsak Works great now! :)
