### ISSUE TITLE
Fix relevancy sorting of name / email matches, if easily possible

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1372]
QA-

Perform a search by name or email
Verify that stronger matches sort to the top

Error tolerance: try not to nitpick too small about the exact results. If you feel you found what you wanted easily and sorted well enough, that should pass this card. We don't have super fine tuning abilities on the search algorithm.

**Comment by ophelieh** [comment]
Works great with both name or email. Stronger matches sort to the top.

**Comment by Allicolyer** [comment]
Hey Joe this looks good! I just reopened it for a demo with Jennifer
