### ISSUE TITLE
RA Intro: Choose nearest RA through geocoding

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1374]
If an RA is not found in your state (and you're international) then choose the nearest RA through geocoding, rather than the first one in your country that the Database finds

QA:
READ ALL THE STEPS CAREFULLY FIRST *BEFORE DOING ANYTHING*
ASK JOE VIA SLACK IF THIS IS CONFUSING *BEFORE YOU START*

- Login to QA as the Admin and invite yourself to the site twice as an RA
  - Remember the + email trick to make 2 different accounts

---

- Sign one RA up (pay attention to which email is which) in another country, such as canada, on the west coast
- Fill in your introduction summary

---

- Sign the other RA up in the same country, but more in the middle or on the east coast/border
- Fill in your introduction summary

---

- Sign up a new student or mentor account, or login as one you already have
- Set your location to a spot close to one of the RAs, but NOT in the same state/province, pick one next to theirs
- Verify your dashboard shows that RA's intro
- Change your location to a state next to the other RA
- Verify your dashboard shows that RA's intro

**Comment by ophelieh** [comment]
Everything worked for me.
