### ISSUE TITLE
Admin: Finding permitted students from previous seasons

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1377]
Voiding parental consents is not the way to go
Tie them to a season

- Login as admin
- Go to participants
- Filter by profile type students
  - season 2017
  - "Has parental consent"

- It should yield data, if there is any on QA

Let joe know on slack if there is no data on QA

**Comment by Allicolyer** [comment]
Hey Joe!

On QA there are 35 accounts for students from 2017. When I select "has parental consent" only one appears and when I select "no parental consent" zero appear.

**Comment by Allicolyer** [comment]
Hey Joe!


I tested out some admin filters. 

<ol>
<li>For students "has parental consent" does not seem to work. </li>
<li>For mentors the fields in "team matching" filter always returns zero even if the mentor is on a team. </li>
</ol>

**Comment by joemsak** [comment]
@Allicolyer Both the issues you found should be fixed on QA now

QA data isn't that great to begin with, but I think I was able to clear it up

**Comment by Allicolyer** [comment]
@joemsak this looks good now. Should most of the students not be consented for the 2017 season?

**Comment by joemsak** [comment]
@Allicolyer that’s right i had to create one because QA doesnt have the
right data for the migration to backfill the past data. i already tested
with production data and it worked
-- 
Joe Sak
Technovation Web Development

Slack name: @joemsak

US, Text only
+1 (312) 945-6317

Mexico Voice & Text / Whatsapp / Telegram
+52 1 33 23 10 69 05

**Comment by Allicolyer** [comment]
Okay looks good then!
