### ISSUE TITLE
Insert data into survey link custom variables

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1378]
Survey links will come with custom variables

name, email, age, city, state, country

They will be in the URL like this:

`example.com/?name=[name_value]&age=[age_value]...etc`

Format them on page load so they're filled in dynamically

`example.com?name=Susie&20Smith&age=13...etc`

QA:

* Copy the web link collector from the student and/or mentor surveymonkey survey
* Login as the Admin on QA (admin@admin.com is the email and password on QA)
* Go to Content & Settings
* Add the survey link for students and/or mentors
* Login as a student and/or mentor (depending on which survey link(s) you set)
* Ensure the student and/or mentor has set their location
* Verify that the survey link appears at the top left of the dashboard
* Verify that the URL to the survey has the custom variables filled in with your info
  * Right click the link and click "Inspect"
  * The `href` of the link should show the survey monkey url with your information in the parameters
    * `name=YOUR NAME&email=your@email.com&age=YOUR AGE...etc`
  * OR you can hover over the link and note the URL in the bottom left corner of your web browser

**Comment by ophelieh** [comment]
For mentors, the link appears on the top right but the link contains all the custom variables. 
![uploads/3257598c-f7da-44a7-a4dc-f5705b082c6a/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3257598c-f7da-44a7-a4dc-f5705b082c6a%2Fimage.png)

For students, it appears on the top left. :) Link contains all the custom variables.
