### ISSUE TITLE
Mentor > My Teams

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1380]
Start by shaping up the "Mentor > My Teams" page

Keep in mind this is most likely the page where they will see the progress of each of their teams' submissions, so leave room for that

They need to see each team they're on, and have a call to action to START or HELP EDIT each submission

If the submission is started, then there will be some progress indication, such as a progress bar or a checklist  (I don't know specifically, you tell me)

This page will get gnarly for mentors on a lot of teams, so let's make sure it's easy to scan, and easy to decide what to do next:

* Manage a team
* Start a submission
* Edit a submission
* Check the progress of a submission (this should be scannable on the page, not a second required click)
* Preview how the submission will look to judges
* Publish and share the public submission page on social media (or opt-out of having a public page)

**Comment by monicagragg** [comment]
@joemsak tested this and was able to see my three teams and was able to
- start their submission
- make edits
- see the progress (on the left)

I was not able to
- publish and share the public submission page on social media because I don't see where that is an option.

**Comment by joemsak** [comment]
Thank you @monicagragg however this card is not in the test column and the card for sharing a public page is still in To Do

**Comment by joemsak** [comment]
Closing in favor of the smaller, split cards
