### ISSUE TITLE
Need a submission page

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1381]
Submission requirements the same as last year, except SDG(?) is gone.

Teams still submitting source code.

Don't want to allow links for submissions, just direct uploads (except YouTube links).

Technical checklist is now Code checklist.

http://technovationchallenge.org/submission-guidelines/

**Comment by Allicolyer** [comment]
Hey Joe!

Here is the list of submission requirements and where they are found in the curriculum. Not all of the requirements really have a clear curriculum unit associated with them.
<ol>
<li>Team Photo and Summary: Found in <a href="http://technovationchallenge.org/curriculum/buildateam/"> build a team </a></li>
<li>App Name and Description: Found in <a href="http://technovationchallenge.org/curriculum/ideation/"> ideation </a></li>
<li> Code Checklist: Found code units 1-5 </li>
<li>Screenshots</li>
<li>Source Code: Found in <a href="http://technovationchallenge.org/curriculum/code-6/"> code 6 </a></li>
<li>Business Plan: Found in <a href="http://technovationchallenge.org/curriculum/business-4/"> business 4 </a></li>
<li>Pitch Video: Found in <a href="http://technovationchallenge.org/curriculum/pitch-1/"> pitch 1 </a></li>
<li>Demo Video: Found in <a 
href="http://technovationchallenge.org/curriculum/pitch-2/"> pitch 2</a></li>
<li>Pitch Presentation: Found in <a href="http://technovationchallenge.org/curriculum/pitch-3/"> pitch 3 </a></li>
</ol>

Also with source code we need to know what development platform they used. If they used App Inventor we need to ask those questions about what their login and name of their app is.

Thanks Joe!

**Comment by joemsak** [comment]
Closing in favor of smaller focused cards that have been split off of this one
