### ISSUE TITLE
Button to "send" your final submission

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1384]
Not sure what happens, is it frozen? 

It's a "feel good" button for people to feel more sure they have submitted. It's an opportunity to let them know if they're somehow ineligible. 

Email confirmation would be nice. 

Mentor or students can click it, everyone gets an email.

**Comment by Allicolyer** [comment]
Hey Joe. This works great. The button works and becomes available when teams have submitted the minimum requirements for submission. If you delete an important deliverable, the submission is "unpublished". I got a nice email about completing my submission. I see that the public pages that are shown afterwards are still a WIP.

Date corrections from yesterday:

Submission Deadline: April 25th
First round of Judging: May 1st - May 20th

**Comment by joemsak** [comment]
Thanks @Allicolyer! Try again in 10 minutes for the corrected dates in the email ... just make a change to your submission and you get the option to submit it again

**Comment by Allicolyer** [comment]
The dates are correct now.

**Comment by Allicolyer** [comment]
This looks great @joemsak
