### ISSUE TITLE
Submission honor code

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1385]
Signed when they start the submission.

Just one "signature" for the team.

Should show who's official, who's pending, give some options to tweak the team makeup.

**Comment by joemsak** [comment]
@madhavitechnovation @Allicolyer Do we have copy for this year's submission honor code?

**Comment by madhavitechnovation** [comment]
Not yet, Joe. I can draft up something and share by Monday morning.

**Comment by joemsak** [comment]
@madhavitechnovation We are still awaiting content, thanks!

**Comment by madhavitechnovation** [comment]
https://docs.google.com/document/d/1ysP2Tafc3qayF9eeGr-w6Mcl25vQRhA33kgTnUfAa_4/edit

**Comment by joemsak** [comment]
@madhavitechnovation We don't have a signature box for this step from last year. Are you requesting me to add one? It's most likely not a complex change

**Comment by madhavitechnovation** [comment]
@joemsak I'd prefer either a checkbox or a signature box....whichever is easier. My idea is not to have this as a statement but as something that they actively commit to by signing or checking a box. Let me know if that helps.

**Comment by Allicolyer** [comment]
Hey @joemsak if I click "start now" without checking off the honor code, I get an error.

**Comment by joemsak** [comment]
Good catch, I'll have to fix that bug and then shape up how it looks when it shows the validation message ... will be back in test tomorrow

**Comment by Allicolyer** [comment]
thanks joe!

**Comment by joemsak** [comment]
@Allicolyer I have updated the code so that the validation error appears if you don't check the box

**Comment by Allicolyer** [comment]
@joemsak It looks good.
