### ISSUE TITLE
Admins can view public submission pages

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1387]
Nice to have an "opt out" as well.

Maybe don't link source code.

These are useful for fundraising.

**Comment by Allicolyer** [comment]
@amyiridescent, @madhavitechnovation, you can check this out

![uploads/5f88adb8-728b-4b06-a2b3-5d2931f3b82f/Screen Shot 2018-05-31 at 3.07.08 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5f88adb8-728b-4b06-a2b3-5d2931f3b82f%2FScreen+Shot+2018-05-31+at+3.07.08+PM.png)

**Comment by amyiridescent** [comment]
So this feature to "open public page" exist for Admins and RAs? 
We need to remove this feature for RAs. It falls under the same GNPR law in EU. I am not sure if we are allowed to allow RAs to create these links and share it with others. For the semi finalists teams from the EU, we already collected explicit "opt in" consent ....

**Comment by joemsak** [comment]
@amyiridescent we can't simply remove this link out from under RAs because a handful of them were asking about what happened to these links, because they use them for fundraising and marketing the regional program

Can you cite the specific aspects of GDPR that apply to these pages? And can you explain in further detail how the GDPR laws can apply to restricting RAs from access to these URLS, but not us?

**Comment by amyiridescent** [comment]
We technically need specific "opt in" language when we share their names, images, or videos for all EU students and mentors. I think unless we are going to build a part on the platform for them to give us specific consent (and for minors it will have to come from their parents), we should not share their submission via public links. For the semifinalists, we emailed them ahead of time to get email consent. But for all EU submissions, it will be impossible. 

Also, I am not sure when girls share their youtube link, if Youtube consent form protects us from sharing the link with others. I have asked a lawyer this question but don't have an answer yet. 

We will update our privacy policy and parental consent form for next year to have this included but for this year, **I strongly recommend that we don't allow this public link option**. You can have the RAs email Katie or Madhavi if they have questions or concerns. They will have to ask teams for permission before they use their videos or information in any way moving forward which they can do directly without us.

**Comment by joemsak** [comment]
I would love to build in some more "opt-in" and clearly designed features to our platform to give our users full control over their data and any public pages.

I've also been thinking about a UI for parental controls and better communication with parents about what information we have in our database and who can see it

**Comment by joemsak** [comment]
my main gripe about taking away the public URL from RAs is that we shouldn't have it either, for the same argument. and as I mentioned, RAs started asking me why the URLs went away this season

**Comment by amyiridescent** [comment]
We will mostly only use it for finalist AND we will get explicit permission from them first before we share the public page... That has been communicated to fundraising team.

**Comment by joemsak** [comment]
okay that makes sense. so I would ask to have @kmorton2017 communicate with RAs about this issue so they don't wonder about the link being taken away

**Comment by madhavitechnovation** [comment]
For this year, we can explain to the RAs that with changes in privacy law, we need to add additional checks like 'opt in' in 2019. I am sure they will agree with this...they will not want to share out submissions if we don't have explicit permission. RAs can reach out to girls girls directly and share their pitch videos for fundraising conversations for this season.

**Comment by joemsak** [comment]
I also think that we need to have a discussion on RAs and data security,
best practices, etc because they have raw user data in CSV files on their
personal computers

One RA emailed an entire list of people without using a newsletter service
or the BCC field, which resulted in one malicious user picking up all those
emails and spamming people

Joe Sak
Technovation Web Development

SMS
+1 (312) 945-6317

**Comment by madhavitechnovation** [comment]
I agree Joe. I was just talking with Katie about adding data and user privacy guidelines to the MOU with RAs moving forward.

**Comment by joemsak** [comment]
Some sort of standardized training and certification could be nice. Also a
goal of mine of course is to eliminate the need that anyone should ever
have to export raw CSV and make their own excel apps :)

Joe Sak
Technovation Web Development

SMS
+1 (312) 945-6317

**Comment by amyiridescent** [comment]
"Also a
goal of mine of course is to eliminate the need that anyone should ever
have to export raw CSV and make their own excel apps :)" 

THIS IS MUSIC TO MY EARS!!! :)

**Comment by joemsak** [comment]
Yeh I've always considered the CSV exports to be a stop-gap solution
because I knew that I couldn't build everything that's needed in the UI in
the first couple versions of the app

Joe Sak
Technovation Web Development

SMS
+1 (312) 945-6317

**Comment by joemsak** [comment]
The link is removed for RAs now

**Comment by kmorton2017** [comment]
i confirm that i can see the public page as an admin.

**Comment by Allicolyer** [comment]
Thank you @kmorton2017 !

**Comment by Allicolyer** [comment]
@amyiridescent I am going to close this discussion.
