### ISSUE TITLE
Admin needs ability to view / search / filter team submissions

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1391]
Login as Admin

- Verify that you can search, filter, export, and view submissions
- Note! Edit is not functioning yet, and has a separate card!

**Comment by kmorton2017** [comment]
I can only see results by season and country. i am unable to search or filter for any teams or search criteria.

I confirm that i can export and view submissions.

**Comment by joemsak** [comment]
@Allicolyer let's pair together soon on improving the search filters (or try it out yourself!)

**Comment by kmorton2017** [comment]
see my comment on RA search features for ideas on filters
