### ISSUE TITLE
Identify and link each piece with its corresponding curriculum pages

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1393]
See #1381

**Comment by joemsak** [comment]
Team Photo and Summary: Found in build a team
App Name and Description: Found in ideation
Code Checklist: Found code units 1-5
Screenshots
Source Code: Found in code 6
Business Plan: Found in business 4
Pitch Video: Found in pitch 1
Demo Video: Found in pitch 2
Pitch Presentation: Found in pitch 3

**Comment by Allicolyer** [comment]
I could not do pitch presentation for now since no view exists for it yet

**Comment by kmorton2017** [comment]
What do you think about adding the code planning link to the screenshots one? that seems to be the only deliverable that doesn't have a link @allicolyer

**Comment by Allicolyer** [comment]
@kmorton2017 I like that idea! I'll add it.

**Comment by Allicolyer** [comment]
@joemsak just sent you a pull request to add the code debugging unit to the screenshots.

**Comment by Allicolyer** [comment]
@joemsak this should be good to go. I'll close the card.
