### ISSUE TITLE
Allow Youku Videos to be uploaded for pitch and demo videos

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1402]
https://www.youku.com/

**Comment by Allicolyer** [comment]
Hey @joemsak I am having trouble embedding a link from youku.

**Comment by joemsak** [comment]
@Allicolyer I noted that the URL you used didn't work, however I found that it was also not a valid URL, youku gives a 404 error when trying to use it. I'm not sure where you got the URL

HOWEVER:
I have updated the code to detect the ID in the URL and embed it anyway. Resubmitting for QA

**Comment by joemsak** [comment]
@Allicolyer please also note I cannot find any documentation online about how to disable autoplay on the embedded youku videos, we might have to live with it

**Comment by Allicolyer** [comment]
@joemsak this is working now

**Comment by Allicolyer** [comment]
This is very cool! Thanks @joemsak!! I updated the submission guidelines to include Youku videos.
