### ISSUE TITLE
Record submission Activity

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1408]
QA:

* Ensure that you have an RA and student or mentor in the same region
* Login as the mentor or student
* Create or edit a team submission
* Login as the RA in the same region
* Verify that the submission activity was tracked

**Comment by ophelieh** [comment]
@joemsak It works great! I logged in a student and created a team and a team description.

**Comment by joemsak** [comment]
@ophelieh Hmm... can you make sure that you actually worked on a team submission? This story is about submission activity, not team activity. Thank you though for jumping on to QA this

**Comment by ophelieh** [comment]
Hi @joemsak ! Here is what I got: 

*When I log in as the RA, I am able to see the submission changes, but is there a reason we decided not to specify what part of the submission was done? 

One possible issue I've noticed: 

*When I click on the student's name or mentor name, I can go to their profile but when I click on the team's name I get an error message. 

![uploads/cea19340-6e16-48e4-8b25-33240a57e657/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fcea19340-6e16-48e4-8b25-33240a57e657%2Fimage.png)

**Comment by Allicolyer** [comment]
Hey @joemsak !

I tested it out with two teams in the region of ra@ra.com. For one of the teams, I was able to see that a new submission was started and updated. 

For the other team, the submission was already created. When I update it, the submission activity does not show up. Other activities show up for this team, such as updating their profile.

Here's some feedback on the activity searching. It is strange that a "submission created" or "submission updated" is an account activity, not a team activity. Maybe to fix this, the activities filter will change based on the "type" selected? Otherwise I'm not sure if it make sense to filter activities by "account" or "team".

Overall this is looking good

**Comment by joemsak** [comment]
Hmmm yeah let me take this back and re-do it as tracking against the team and see if that works nicer

**Comment by joemsak** [comment]
@Allicolyer resubmitting this for QA ... it's still not perfect ... I'd like to figure out how to track the actual piece that was updated... I'm sure it's possible but it's not obvious

**Comment by Allicolyer** [comment]
hmm @joemsak I am still not seeing submission activity show up for every team in the RA's region. In particular, the submission activity for the account student@student.com does not show up in the activity tracker, however other activity for this team does.

**Comment by Allicolyer** [comment]
Also it looks like the submission activity works for everything except for the code checklist

**Comment by joemsak** [comment]
You guys got me, I tried to get away with making the view link to the team while still tracking against each user ... will take it back to the drawing board ;)

**Comment by joemsak** [comment]
@Allicolyer @ophelieh I am resubmitting this for QA based on all your feedback

**Comment by joemsak** [comment]
Note: I had to delete all the QA activity so it could work correctly with the changes -- this will not be necessary for production as production doesnt have any existing submission activity in the DB

**Comment by Allicolyer** [comment]
@joemsak this is working very well now.

**Comment by Allicolyer** [comment]
hey @joemsak I just noticed that there is a type of submission activity that doesn't have a name. It just says "[Team] updated their ..."

I can do more investigating to figure out which type of submission activity does this.


![uploads/4d3ee907-f16b-40b4-a86e-f762051f51af/Screen Shot 2018-02-02 at 11.01.09 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4d3ee907-f16b-40b4-a86e-f762051f51af%2FScreen+Shot+2018-02-02+at+11.01.09+AM.png)
