### ISSUE TITLE
Update screenshots UX

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1411]
And vice versa

**Comment by Allicolyer** [comment]
Hey Joe! 

This works very well. Here are some things I noticed:

If you are at the max number of screenshots, and delete one, the uploader prompts you to upload one more but won't actually let you do it until you refresh the page

Awkward wording:

If you are at the max number of screenshots, the uploaded says "drag and drop up to 0 screenshots here, or upload 0 screenshots"

The words "Sort your screenshots in the order that you want the judges to see them:" stay on the screen even after I have deleted all screenshots

**Comment by joemsak** [comment]
Thanks @Allicolyer yep that's where it's at right now, still trying to work out those awkward moments :)

**Comment by joemsak** [comment]
@Allicolyer Resubmitting this for QA, the only awkward bit left is that it still can't change the max files to upload after uploading and then removing files. But if you reload the page and remove a file, it DOES update the max files allowed. Dropzonejs is *really* hard to work with

**Comment by madhavitechnovation** [comment]
I faced some challenges with this:

1. My machine hung-up 3 times while I was trying to upload and this could just be me, so not a huge issue. Just wanted to share.

2. When I hit X on the screenshots in the main panel, it gave me a prompt, Are you sure? But when I clicked "remove this file" on the left bar, I did not get that prompt. The screenshot was removed sometimes and sometimes it just stayed.

3. Are we allowing a maximum of 5? Which should be fine but given that machine crashed and removed files using the left tab...I was able to upload 7 screenshots. Even my dashboard said, your team has 7 screenshots.

**Comment by joemsak** [comment]
@Allicolyer @madhavitechnovation I am resubmitting this for QA. I rewrote the UI completely today. I got rid of the drag and drop feature because it was making things really difficult. You can still select more than one file at a time in the file chooser with the SHIFT or COMMAND (macOS) (or CTRL in Windows) keys

**Comment by Allicolyer** [comment]
@joemsak this worked for one of my accounts to upload and rearrange screenshots in real time. 

However after I clicked "submit for judging" and went to make changes to my screenshots,  I am got stuck on this screen indefinitely. 

![uploads/49f1fef7-bbba-48e7-8738-37848e126145/Screen Shot 2018-01-23 at 2.54.09 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F49f1fef7-bbba-48e7-8738-37848e126145%2FScreen+Shot+2018-01-23+at+2.54.09+PM.png)

I also got stuck on this screen for another account that had previously submitted for judging.

**Comment by joemsak** [comment]
@Allicolyer this should be fixed now

**Comment by Allicolyer** [comment]
@joemsak this looks good now!

**Comment by Allicolyer** [comment]
@joemsak one last thing I noted -- the screenshots seem to be lower resolution when they are on the "public page" than they were when I uploaded them.

**Comment by Allicolyer** [comment]
@joemsak actually I am uploading really small files and then looking at them pretty big on my screen. My bad!
