### ISSUE TITLE
Future ideas (2019)

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1414]
(later)

Mentors can indicate that they are educators or industry professionals
- While signing up easier, existing mentors requires UI/UX changes

Ask for mentors availability in terms of time and travel distance / or meeting points

Teams list time availability as well, and geographical areas to meet

RA internal notes have come up again

**Comment by Allicolyer** [comment]
Conclusion: Just make a suggestion that mentors put it in their bio. More complex, add a field to bio (meeting places, availability ect.)
