### ISSUE TITLE
Judge dashboard join slack link

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1415]
QA -

Sign up as a judge (find and use the global signup URL in Admin - Invite Users)
Verify the slack signup URL is in the sidebar

**Comment by monicagragg** [comment]
@joemsak here is the Slack invitation for Judges

https://join.slack.com/t/technovationjudges/shared_invite/enQtMzEzMTM3MjUwNzI2LWEwNzdkMzEwYzkwM2ZkZjA3MTAxYzRjNTAxOGFlZDUzOGYzNWQyMTA1NTQ3NjAwYjc3Nzg3MzY3Y2ZlZjBiZTU
