### ISSUE TITLE
RAs assign judges to RPEs

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1417]
QA:

- Ensure you have some judges on your email address who are not also mentors
- Log in as an RA
- Create an event if you dont have one
- Verify you can add your judge accounts to your event
- Verify that judges who are mentors do not appear in the search
- Verify that your search will go out of your region if it can't find results in your region first
- Verify you can invite a brand new judge by entering a new email address

**Comment by kmorton2017** [comment]
make the judge name clickable

**Comment by joemsak** [comment]
Thank you @kmorton2017 Please take another look at this today

**Comment by kmorton2017** [comment]
yep it looks fine. one minor suggestion:

on the judge profile, under "Training Completed?"

Can you write "No" instead and delete the "..." and ":( "

**Comment by kmorton2017** [comment]
also, i tried to invite a mentor to be a judge for the RPE. katie+mentor1@iridescentlearning.org

Is this because this individual is a mentor and cannot be invited to be a judge for an event?

**Comment by joemsak** [comment]
@kmorton2017 that is a good point and I need to rework the search to find mentors, which would then invite them to login at the judge dashboard (same thing as 'switching to judge mode')

**Comment by joemsak** [comment]
@kmorton2017 @ophelieh this should be ready for QA again

**Comment by kmorton2017** [comment]
when i tried to remove a judge from the event, it signed me out. when i logged back in again i got a 404 error. I will try replicating again to see if it happens

**Comment by kmorton2017** [comment]
also i think we discussed this on slack, but it could be confusing since we didnt' record it on huboard. but mentors should not be allowed to be in-person judges.

what RA's would like to do tho is have the ability to add mentors (who did not actually end up mentoring) to their event as a judge. this seems very customized and relevant to jean/rachel. i think we discussed doing this on a case by case basis

**Comment by joemsak** [comment]
@kmorton2017 I can have the server return judges who are mentors but not on teams. Would that work?

**Comment by joemsak** [comment]
@kmorton2017 can you let me know if my last comment works for you? Thanks!

**Comment by kmorton2017** [comment]
i tried to add 2 different mentors and it wouldnt let me so everything looks good
