### ISSUE TITLE
RA / Admin UI Add ‘team(s)’ & mentor bio (yes / no) to participant columns / export

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1419]
As an Admin, and as an RA:

- Go to participants
- Select from 'more columns'

-- Team name(s)
----- This column returns data only for students and mentors, otherwise returns a "-"

-- Filled out bio?
----- Only for mentors, otherwise you see "-"

- Verify that the correct information appears in the web view and in the exported file

**Comment by ophelieh** [comment]
Hi @joemsak ! 

As an admin and an RA, everything works and looks great. :) I like how it automatically adds some search options like city, profile type, depending on what you are searching.

**Comment by Allicolyer** [comment]
This looks good Joe.
