### ISSUE TITLE
 RA UI bug: add mentor / student to teams doesn’t limit the list to the region

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1420]
QA:

Login as an Admin
- Go to Participants
- Find a student or mentor
---- If a student, student must not be on a team
- Go to the bottom to add to a team
- Verify you see all the teams in this list

Login as an RA
- Go to Participants
- Find a student or mentor
---- If a student, student must not be on a team
- Go to the bottom to add to a team
- Verify you see only the teams from your region in this list

**Comment by ophelieh** [comment]
Hi @joemsak ! It all looks great! :) 

Admin:
* Student - when not on a team, I can see the whole list of available teams
* Mentor - can see list of teams for mentors already on a team or not on a team 

RA: 
Works great for both mentors and students

I noticed that even when a mentor is already part of a certain team (say "Skittles and M&M's"), you still see that team is the droplist. Is that normal?

**Comment by joemsak** [comment]
Yeah I dont think it's the end of the world, the RA or admin is only going to use that UI, rarely, with a certain team name in mind
