### ISSUE TITLE
Admin UI ONLY: Filter mentors with pending invitations to join teams

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1422]
---

**Comment by Allicolyer** [comment]
@joemsak this is still needed for the end of the year

**Comment by joemsak** [comment]
@Allicolyer to confirm, we don't want this filter option available to RAs?

**Comment by joemsak** [comment]
@Allicolyer just to be more up front, my concern is restricting it to Admins complicates the UI by adding another filter select, whereas currently if it's okay for RAs to have this filter, I can just add it to the existing Team matching filter selection

**Comment by Allicolyer** [comment]
@kmorton2017 do you think it is ok for RAs to have this feature? I think it is.

**Comment by kmorton2017** [comment]
yes it is fine for RAs to have this feature.

**Comment by Allicolyer** [comment]
@joemsak did you address Katie's point?

**Comment by Allicolyer** [comment]
@joemsak actually never mind I don't think there are supposed to be X's on these filters

**Comment by Allicolyer** [comment]
@amyiridescent could you QA this?

1. Send a request from a mentor account to join a team 
2. Do not accept the request
3. Make sure that admin gets filtered correctly from the Admin UI

1. Send a request from a team to a mentor
2. Do not accept the request
3. Make sure that admin gets filtered correctly from the Admin UI

**Comment by joemsak** [comment]
@amyiridescent when you get that error, the screenshot you gave is not very helpful. Instead, can you please type out the steps the dev team should take to try and reproduce the error?

**Comment by amyiridescent** [comment]
@joemsak i know i know. I didn't get a chance to finish responding last night. I think the error comes when I put in a fake SSN. Alli gave me a number I should use instead and that cleared the error. Meant to update this thread when I got home last night. :)

**Comment by joemsak** [comment]
@Allicolyer are there any outstanding action items for this card?

**Comment by Allicolyer** [comment]
@amyiridescent I can finish QAing :) 

@joemsak right now please remove the "made with code" as an option to how they heard about us. Thank you @amyiridescent for catching that.

**Comment by joemsak** [comment]
Okay, that seems unrelated to this card though. Should we add a new card?

Joe Sak
Technovation Web Development

SMS
+1 (312) 945-6317

**Comment by Allicolyer** [comment]
Hey @joemsak my mentor with a pending join request is now showing up in the filter. Both the team and the mentor are registered to the 2018 season.

Mentor account email: alli+m2@iridescentlearning.org

![uploads/0f6fbcfb-a4a0-4576-aebb-0f2b0b31dcb3/Screen Shot 2018-07-11 at 5.40.46 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0f6fbcfb-a4a0-4576-aebb-0f2b0b31dcb3%2FScreen+Shot+2018-07-11+at+5.40.46+PM.png)

![uploads/05a8413f-294f-4800-9e33-1703e8c726b1/Screen Shot 2018-07-11 at 5.41.20 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F05a8413f-294f-4800-9e33-1703e8c726b1%2FScreen+Shot+2018-07-11+at+5.41.20+PM.png)

**Comment by Allicolyer** [comment]
@joemsak I wasn't able to get this to work ... can you look into it?

**Comment by joemsak** [comment]
@Allicolyer your mentor has a pending join request, not an invite. Would you like me to expand the scope to include mentors with pending join requests too?

**Comment by kmorton2017** [comment]
i confirm that i was able to see my mentor in the "mentors with pending invitation" filter.

I think adding join requests to the filter would be helpful as well. 

Another unrelated question for another card--is there a way that we could streamline the dashboard ? for example, when I login as Buffy,  I see 3 separate call to actions:

-Team invitation
- Register a Team
-Join a team

I think that team invitations and "join a team" may confuse people (i always have to remind myself of the difference between the two.

**Comment by joemsak** [comment]
@kmorton2017 @Allicolyer thank you, the filter has already been expanded to include mentors with pending join requests

Katie, thanks for your notes, we agree that the dashboards need UI/UX design updates and we have cards in the backlog for it. Please try to keep any notes you come up with, that are outside of the acceptance criteria of the cards you're QA'ing, to bring with you for future sprint meetings so that we can keep the comments focused on the work needed to complete each well-defined card

**Comment by Allicolyer** [comment]
@joemsak this works now.

@kmorton2017 there is no way to tell which mentors have a pending join request and which have a pending invite. Is this something that program team needs?

**Comment by joemsak** [comment]
@Allicolyer I'm pretty sure she was just echoing you that the filter should include both

**Comment by Allicolyer** [comment]
getting clarity from program team about this filter

**Comment by Allicolyer** [comment]
@joemsak I have clarity about this from the program staff.  It is not as helpful to the program team if these join requests and invites are lumped together since: 
<ul>
<li>pending join requests - identifies mentors who are struggling to find a team </li>
<li>pending invites - identifies inactive mentors</li>
</ul>

The idea case would be to separate these two things into separate filters in the dropdown. Should we create a separate card for that?

**Comment by Allicolyer** [comment]
@joemsak did you see my comments?

**Comment by joemsak** [comment]
Thanks @Allicolyer! Please check on QA today

**Comment by Allicolyer** [comment]
This is great and it works well. Thanks Joe.
