### ISSUE TITLE
Create a late registration link for students and mentors

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1430]
This card is to create a token URL to register students and mentors after the registration deadline has passed. This should be and "invite only" feature used by admins.

**Comment by joemsak** [comment]
We already have the same feature we had last year: Admins can invite people via email

**Comment by joemsak** [comment]
Moving to backlog: wasn't discussed in sprint planning, cannot go into To-Do without negotiation with the dev team

**Comment by kmorton2017** [comment]
sorry about this! i can delete this card. just to confirm, students/mentors can still sign up using the invite link after march 7th?
