### ISSUE TITLE
Judges - - Custom link that records their training completion

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1434]
@monicagragg here is the URL that you can configure the judge training to redirect to when it's finished

https://my.technovationchallenge.org/judge/training_completion

It will make sure they are logged in and then record that they completed the training in our data

---

QA -

Verify that this URL takes you to your judge dashboard

https://technovation-qa.herokuapp.com/judge/training_completion

---If you are not logged in, it should ask you to sign in
  --- login as a judge and verify you go to the dashboard

**Comment by ophelieh** [comment]
Hi @joemsak ! It works good, when not logged in it asks you to log in and when you are logged in it brings you to the dashboard. 

The only thing I noticed was the broken image. 
![uploads/7686c05e-fb8a-44ec-ab9a-da680b5a2e91/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7686c05e-fb8a-44ec-ab9a-da680b5a2e91%2Fimage.png)
