### ISSUE TITLE
Judge onboarding steps

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1435]
- Must complete online training
- Must sign a commitment form

- Please answer:

- Industry, skills, degree

--- Question for @monicagragg or @madhavitechnovation - is "Industry" a pre defined list for judges to pick from that you will provide, or a free form text input for the judge to fill in as they please?

- Would you like to join the virtual Judge committee

QA:
NOTE - The "complete training" link will simply mark you as completing the training. This is for QA only. On production, we are expecting the judge training site set up by @monicagragg to redirect the judges to the completed training URL, which will do the same thing.

- Find and use the judge signup URL in Admin > Invite Users
- Sign up as a judge
- Verify you have steps to complete:
-- Your location
-- Judge training (see note above)
-- Commitment form (copy is still pending, but form should work)
-- Survey questions
----- I've decided to make this form completely optional, so yes, you can fill in all, any, or none of the fields, but you must at least visit this form and save it for it to mark your completion

**Comment by joemsak** [comment]
@madhavitechnovation or @monicagragg will the judge commitment form replace the consent waiver, or not? Also is there copy for that yet?

**Comment by joemsak** [comment]
@monicagragg do you have a link for the judge training site yet? I'll need that asap - thanks!

**Comment by monicagragg** [comment]
Hi @joemsak 
Thanks for asking,

1) Can we please make the industry question science, technology, engineering, math, or other?

2) I think it's good to combine the consent waiver with judge commitment. @madhavitechnovation what do you think? There is no copy yet. When do you need it by?

3) Here is the link to the judge training: https://iridescentlearning.atavist.com/technovation-judge-training

**Comment by joemsak** [comment]
Notes: - Combine consent + commitment -- judges will see special version with commitment copy -- awaiting copy from @monicagragg

**Comment by kmorton2017** [comment]
All of QA steps worked for me

**Comment by joemsak** [comment]
@kmorton2017 Great thank you - I now await commitment form copy from @monicagragg and confirmation from @monicagragg that the atavist judge training site will redirect judges to the completion URL when they finish it

**Comment by monicagragg** [comment]
Hi @joemsak, sorry this is very late. We could not find the consent form. Here it is. https://docs.google.com/document/d/1Fknkd8Li97hnGwgIBYng--CH_uYZlTiWlLDsaDyk_lU/edit#

I am also confirming that the judge training on Atavist will redirect judges to the completion URL.

**Comment by joemsak** [comment]
@monicagragg this looks like it's the consent form. Is there brand new copy for a commitment form? We already have the consent form on the site, but in talking about judge onboarding, you and @madhavitechnovation mentioned that judges will see additional copy for something called a commitment form. Is that still the case, or no?

Could you please demonstrate the atavist training to us at the next sprint planning? Thanks!

**Comment by monicagragg** [comment]
Hi @joemsak Yes, it is the consent form. Alli and Madhavi could not find the Google doc verison.

The commitment form will now be separate and will be text that is placed above the link that redirects them to the platform. We made this decision because the consent literature was very legal, and the commitment form is more about being a good judge. 

Yes, I will be happy to demonstrate at the sprint session!
