### ISSUE TITLE
RAs assign teams to RPEs

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1436]
QA:

- Ensure you have teams who have started their submissions, and are not attending an event
- Login as the RA
- Create an event if you dont have one
- Verify you can add teams in the division(s) specified by the event
- Verify you cannot add teams which are attending an event
- Verify you cannot add teams which did not start a submission
- Verify you cannot add teams out of the division of the event
- Verify you can search for teams out of your region if your search does not find any in your region first

**Comment by kmorton2017** [comment]
a few thoughts:

1) when you add a team, can you make their team name clickable? for example, i added a team that was "not qualified" but I was unclear why. Can you redirect each team to their submission page? Otherwise i'd have to navigate to the submissions page and search for them. 

2)  maybe next to the "not qualified" section you can add a little question mark. when you hover over the question mark, it could say something like "this team is not qualified because they have not finished their submission yet and are ineligible for judging"

**Comment by joemsak** [comment]
Thanks @kmorton2017 these are all good points ... it's ready for you to take another look.

**Comment by ophelieh** [comment]
Hi @joemsak everything works great except for not being able to select a team attending an event. 

I was able to do so by not saving my selected teams and add teams to another event. Once I saved my selected teams, it allowed me to have the same team in two events. However, if I do save my selected teams, then I cannot add that team to another event. 

![uploads/b80b5ea1-158c-4324-8297-d72505f9bdc9/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb80b5ea1-158c-4324-8297-d72505f9bdc9%2Fimage.png)

**Comment by joemsak** [comment]
Good find @ophelieh thank you :)

**Comment by joemsak** [comment]
@ophelieh your feedback was that you could add 2 teams before saving but not add the same team to another event after saving one -- i am making it so you should not be able to select the same team for 2 events, whether you saved or not

**Comment by ophelieh** [comment]
Hi @joemsak I'm still able to add the same team to multiple events (3 here) if I'm not saving first. 

![uploads/e0e9d4a1-c447-41c6-a30f-0d6f1b8a3877/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe0e9d4a1-c447-41c6-a30f-0d6f1b8a3877%2Fimage.png)

**Comment by joemsak** [comment]
@ophelieh can you refresh the page and try that again? i just tried on QA and I couldn't do it. Maybe you had an outdated version of the page open, I'm not sure

**Comment by ophelieh** [comment]
I must have. It works great now! :)

**Comment by kmorton2017** [comment]
i tried to add a team to my event. there are only 3 teams in my region. it says that 

"There are no more teams available to add to your event. Teams must not be attending other events, and must have started their submission.You can try searching for teams that are not in your region, but are close enough to travel to your event."

I logged in as this team to double check, and I can't see if I'm attending an event. 

How does a team attending an event see this on their dashboard?

**Comment by joemsak** [comment]
@kmorton2017 we are working on the teams and judges seeing their selected event in another card

I'm not sure what your question about the 3 teams and the "no teams" messaging. Are your 3 teams not attending any other events, and have they started their submission? The `ra@ra.com` test account may have added your teams to their event, as it is possible to search for teams and judges out of region if your query doesn't match within your own region (this is to make things easier for an RA like Rachel who invites people over state lines)
