### ISSUE TITLE
Student/Mentor workflow: Review your submission

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1437]
QA:

- Do these steps both as a mentor and as a student who are on a team:

- Complete your submission to the point where you get the button to review and submit
- Go through the review process
- Verify information is accurate, links work, it looks nice, etc
- Verify when you finish the workflow, your teammates get emails
- Verify you can still make edits after submitting
- Verify that if you make an edit, you can go through the review workflow again

**Comment by ophelieh** [comment]
As a student I was unable to try it out, I keep getting an error message 
![uploads/78c541e6-cc85-4d29-90c9-7a624dcb9a16/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F78c541e6-cc85-4d29-90c9-7a624dcb9a16%2Fimage.png)

I'll try as a mentor next

**Comment by ophelieh** [comment]
Hi Joe! It works great for a student. For a mentor, I made some edits to a submission, then when I tried to submit again, I was brought back to my dashboard with the below message. Not sure if that's normal. 


![uploads/0a95bb42-750c-4fc1-b278-2dbc25cbfba5/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0a95bb42-750c-4fc1-b278-2dbc25cbfba5%2Fimage.png)

**Comment by joemsak** [comment]
@ophelieh please try this as the mentor once more. thanks!

**Comment by ophelieh** [comment]
It works great!
