### ISSUE TITLE
Block judge training link on their dashboard until it's ready

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1443]
Judge training will be ready in Mid-March

QA:

- Sign up as a new judge
--- As the Admin, find the judge sign up URL in "Invite Users"
- Verify that the dashboard gives you a note about judge training being available later

**Comment by ophelieh** [comment]
Hi Joe! I logged in a judge. I did not see any notes about training being available later, and when I click on the training, it brings me here - https://iridescentlearning.atavist.com/technovation-judge-training.

**Comment by joemsak** [comment]
@ophelieh oops you're right - please check again

**Comment by ophelieh** [comment]
Looks good. But could we switch the sentences around (with the training deadline one last)? It feels weird to have a deadline and then say but wait it's not open yet. 

Also, could we edit this: "Please come back in mid-March when we announce the opening of the training site." --- I'm not clear on what the training site is. Will judges have access to a special platform or is it just a training book?

**Comment by joemsak** [comment]
@ophelieh  please take another look thanks!

**Comment by ophelieh** [comment]
Looks good! Will we announce the opening on the training via email or just on the platform?

**Comment by joemsak** [comment]
I assume by email but you should ask @madhavitechnovation @monicagragg or @kmorton2017
