### ISSUE TITLE
RPE date range should be May 1 - 20

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1444]
QA:

- Login as an RA
- Go to create or edit an Event
- Verify that the date field allows you to choose from May 1 thru May 20

**Comment by ophelieh** [comment]
You can only select dates from May 1 to 20th. :) 

But, I think I found a couple things that stood out. 

* I had previously added an address to my event, then removed it, then clicked save changes and now it's stuck
![uploads/7aabef1b-4e4e-4fbc-9275-4eb600b9dd50/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7aabef1b-4e4e-4fbc-9275-4eb600b9dd50%2Fimage.png)
I then pressed cancel. Went back to edit the event, but the "save changes" button is still not clickable. I then refreshed the page, which brought me back to the event dashboard and that seemed to fix it. 

* After saving an event with name, location, and date, I went back in then removed the date. I was able to save the changes and the new date showing is now today's date. 
![uploads/62417bc7-de99-461b-8fc6-a5f66d2b57cd/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F62417bc7-de99-461b-8fc6-a5f66d2b57cd%2Fimage.png)

**Comment by joemsak** [comment]
@ophelieh nice finds thank you and please check again today

**Comment by ophelieh** [comment]
Works great!
