### ISSUE TITLE
Teams attending live events must upload pitch presentation slides

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1453]
QA:

- Ensure you have a student AND mentor account on a team

- Login as the RA in the same region as your team
- Add your team to an event
- Logout

- Login as the student
- Verify that your team submission allows you to upload your pitch presentation

- Login as the mentor
- Verify that your team submission allows you to upload your pitch presentation

----- PLEASE NOTE: we are not showing the event the team has been assigned to YET-- that is still a work in progress and we plan to release this plus that and the RA event attendance management all at once. Be on the lookout for all of that on QA later.

**Comment by ophelieh** [comment]
Works great!
