### ISSUE TITLE
Winners of OFFICIAL live events: automatic rank to SF

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1455]
Assign winners of official live events as Semifinalists automatically

-- Rules of inclusion
-- Events without rooms:
----- Highest scoring team in each division, per 10 teams
-------- Ex: 10 teams = highest score wins
                   11-20 teams = 2 highest scores win
                    21-30 teams = 3 highest scores win, etc

-- Events WITH rooms:
--- highest scoring team in each room

**Comment by Allicolyer** [comment]
@joemsak let me check in with Katie and see if she still wants this -- I know there has been difficulty with getting scores at RPEs

**Comment by kmorton2017** [comment]
i think that we decided against this due to the challenges of getting judges to submit scores on time and unique cases that are relatively common

**Comment by Allicolyer** [comment]
@kmorton2017 thank you for clarifying!
