### ISSUE TITLE
Enable RAs to remove team members

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1458]
QA-

- Login as an RA
- Find any team
- Verify you can remove students
- Verify you can remove mentors

**Comment by ophelieh** [comment]
I can remove both, but some of the time it shows me the below message (it still removes the person though). 


![uploads/ac4dde25-b010-4699-b781-bb77a6b6cf97/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fac4dde25-b010-4699-b781-bb77a6b6cf97%2Fimage.png)

**Comment by joemsak** [comment]
@ophelieh when you see that 404 not found page, did you first get a confirmation to remove the person you selected? My guess is the JS isn't fully loading in those instances, and not getting the confirmation box would be a sign of that.

**Comment by ophelieh** [comment]
I did receive a confirmation message before the error message.

**Comment by joemsak** [comment]
Okay, I have another hypothesis about this - were you removing students from teams that are not in our region, by chance?

**Comment by ophelieh** [comment]
@joemsak I'm pretty sure I was.

**Comment by joemsak** [comment]
@ophelieh okay QA should be updated now to support removing members from out of region teams - RAs can view out of region teams if they have a mentor in their region which is on virtual teams in other regions

**Comment by ophelieh** [comment]
Hi @joemsak! I just tried removing a student outside of the region (RA is in LA, the student was in Bay area) and I got the error message again. When I remove someone from the RAs region, I do not get the error message.

**Comment by joemsak** [comment]
@ophelieh regions are not that small. the bay area is in your region if you're in LA. Your region is the entire state of california

that being said can you please spell out exactly the steps you're taking to test this so I can figure it out? thanks

**Comment by ophelieh** [comment]
Right, I keep forgetting that.

**Comment by ophelieh** [comment]
I've tried multiple teams and it seems to be working fine now. :)
