### ISSUE TITLE
Print-friendly judge scores

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1461]
QA

As the Admin -
- Ensure that Event Selection is enabled, via Content & Settings

As an RA-
- Ensure an event exists with enough teams (15) to assign judges
- Assign more than one judge to more than one team
-- 3 judges would be ideal, but at least 2 must be used
-- Ensure there is some overlap of assigned teams, but not *total* overlap, just for the sake of testing accuracy
-- Ensure you can login as each judge

As the Admin-
- Enable Judging Quarterfinals

As each judge-
- Complete some scores

As the RA-
- Verify you can go to the print view
- Verify each group of judges with overlap of teams is grouped together
-- separated by a cover page
- Verify when you go to print (you can print to PDF or use the browser's print preview) that:
--- Each cover page is its own page
--- Each judge's page is its own page
--- Each judge has all their scores together, not separated by other judges
--- Each group is correct: judges and teams listed after the cover page are those teams and judges

**Comment by Allicolyer** [comment]
We discussed yesterday that really long comments can just be cut off in the print friendly view

**Comment by joemsak** [comment]
Update: Comments would not fit to keep everything one one page per score. Had to cut them

**Comment by RRios00** [comment]
Initiating team management took a very long time. The wheel wouldn’t stop spinning and I had to restart the screen a few times.
![uploads/04d8ac6a-b1ba-4659-b64a-81fa9597b69a/Screen Shot 2018-04-17 at 4.04.20 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F04d8ac6a-b1ba-4659-b64a-81fa9597b69a%2FScreen+Shot+2018-04-17+at+4.04.20+PM.png)

**Comment by joemsak** [comment]
@ruby probably event selection isn't enabled by the admin

You should use the event that already has enough teams, "Ruby's Coffee House"

**Comment by kmorton2017** [comment]
i had added Old Timer to  Ruby's Coffee House, and assigned teams to this judge. i signed out and back in again and the judge is not showing up anymore.
