### ISSUE TITLE
RPE selection / viewing for students

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1462]
QA:

- Ensure as the ADMIN, that selecting a regional pitch event is enabled

- Ensure you have a team with a submission, in the same region as an RA who has created an event open to that team's division 
-- create as many as you wish to make the list longer
-- create at least one outside of the team's division, to verify it does not appear for the team to select

- Verify you can select one event for your team to attend
- Verify, as a student, you cannot change this

- Also, verify that if an RA adds a team to their event, the students on that team see it as their selected event, and cannot change it

- Verify that a team that hasn't started submitting cannot select an event

**Comment by ophelieh** [comment]
Everything works great!

**Comment by Allicolyer** [comment]
@ophelieh which do you prefer?

![uploads/d000f65f-19a2-411f-beb5-6efd9145c4df/Screen Shot 2018-03-20 at 10.08.53 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd000f65f-19a2-411f-beb5-6efd9145c4df%2FScreen+Shot+2018-03-20+at+10.08.53+AM.png)

![uploads/9fce92fc-0dc4-4ab6-b183-d463a7f01f9f/Screen Shot 2018-03-20 at 10.09.04 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9fce92fc-0dc4-4ab6-b183-d463a7f01f9f%2FScreen+Shot+2018-03-20+at+10.09.04+AM.png)

**Comment by Allicolyer** [comment]
@ophelieh I am going to do the second one for now.

**Comment by ophelieh** [comment]
Hi @Allicolyer ! Sorry, I am just now catching up on email. I like both, the second one might be less confusing though. :)

**Comment by Allicolyer** [comment]
@ophelieh That's great! I went with the second one

**Comment by ophelieh** [comment]
:)

**Comment by joemsak** [comment]
@ophelieh can we get an approval or more feedback on this? thanks!

**Comment by ophelieh** [comment]
Hey @joemsak, all I see when logging in as a student right now is this:

![uploads/ed20f9e5-ffc7-47eb-9c76-6800d15e0d38/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fed20f9e5-ffc7-47eb-9c76-6800d15e0d38%2Fimage.png)

So I am unable to recheck this QA at this time.

**Comment by joemsak** [comment]
@ophelieh please re-read the QA instructions a bit more closely. thanks!

**Comment by kmorton2017** [comment]
@ophelieh as an admin you need to make sure that judging is turned off. The Team submissions are editable feature, and the ability to select events needs to be turned on. 

I like the text that says '"your team needs to start a submission before selection an event."
