### ISSUE TITLE
Regional Event selection for mentors

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1464]
QA:

- Ensure as the ADMIN, that selecting a regional pitch event is enabled

- Ensure you have a team with a mentor and a submission, in the same region as an RA who has created an event open to that team's division

-- create as many events as you wish to make the list longer
-- create at least one outside of the team's division, to verify it does not appear for the team to select

- Login as the mentor on the team
- Verify you can select one event for your teams to attend

- Verify, as a mentor, you cannot change this

- Also, verify that if an RA adds a team to their event, the mentors on that team see it as their selected event, and cannot change it

- Verify that a team that hasn't started submitting cannot select an event

**Comment by ophelieh** [comment]
Works great!
