### ISSUE TITLE
Rate limiting scores

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1472]
Flag scores of judges who finish a new score in 10 minutes or less, twice in a row, for admin review

Virtual judges only

Warn the judges with timers - first warning is a 5 min. cooldown. 2nd warning is 20 min. 

helpful text to explain what's going on

3rd strike - blocked with support email CTA

Notify staff with email

**Comment by Allicolyer** [comment]
Conclusion: This is a UX anti pattern.
