### ISSUE TITLE
Admin / RA Teams UI: Filter by teams with all onboarded students (or some still onboarding)

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1491]
As an Admin and an RA

Verify you can filter teams which have all their students onboarded or not

This determines which teams will be able to submit for judging

**Comment by kmorton2017** [comment]
I can filter teams by ones which students are on-boarded or not. 
However, the count appears wrong. The total on admin is 44 teams. But the count is 23 onboarded and 7 not onboarded=30. 

I can't remove the filter and the columns do not have x's to remove them.

**Comment by joemsak** [comment]
Thanks Katie. I updated the team onboarded students filter with another option for "No, has no students" which should clarify the counting error. "Some students onboarding" only reports teams which have students, hence the discrepancy.

The UI bug with the 'X' reported in all these tickets will be resolved in a new ticket, as the same bug affects them all

**Comment by ophelieh** [comment]
Admin & RA: works great for most teams

For other teams (ex: plant lovers, over the rainbow) it takes me here: 
![uploads/29160b2e-cce4-4a81-82b6-b2711306d582/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F29160b2e-cce4-4a81-82b6-b2711306d582%2Fimage.png)

**Comment by RRios00** [comment]
I get the same issue as Ophelie. There’s an issue seeing the other teams.

**Comment by joemsak** [comment]
Thank you @ophelieh and @rrios00 I believe this is a case of faulty QA data, the students on those teams don't have accounts. it might be about time to wipe QA and start from scratch
