### ISSUE TITLE
Remove 'Code Checklist' from the Judging UI

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1493]
Staff has decided not to show the code checklist during judging

QA:

As a judge, ensure "Review Submission" and "Technical" do not show the Code Checklist answers, but only a message that the team automatically earned X points for it

**Comment by Allicolyer** [comment]
👍

**Comment by ophelieh** [comment]
Looks great! On another note, the "Overall Impression" page is not working properly. As you scroll down the Overall Comment box scrolls down too. 


![uploads/19f577fd-4d96-4303-b473-35808f2521e9/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F19f577fd-4d96-4303-b473-35808f2521e9%2Fimage.png)

**Comment by kmorton2017** [comment]
Can we make the source code link blue so its more intuitive to click?

can we add "Code Checklist" as a titel above the "____ automatically earned 10 points for their code checklist" text?

**Comment by joemsak** [comment]
@kmorton2017 I added the title, and making the link blue won't look good on the mulberry background so I instead added a 'code' icon to match the style of the pitch and demo video link so that it's consistent
