### ISSUE TITLE
Submission CSV

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1497]
Create a CSV download for admins that includes this information for submissions.

- App Name
- App Description
- Pitch Video Link
- Demo Video Link
- Source Code (y/n)
- Business Plan (y/n)
- Code Checklist Points

Needed for fundraising purposes.

**Comment by Allicolyer** [comment]
@amyiridescent do we still need this?

**Comment by amyiridescent** [comment]
nope. Joe already built this report on the platform.
