### ISSUE TITLE
Create 'semi-finals' judges

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1502]
Only judges who have judged 5 or more submissions will become 'semi-finals' judging

**Comment by Allicolyer** [comment]
@joemsak are you aware of this? Do you want to chat about it?

**Comment by joemsak** [comment]
Okay I think it makes sense. Only enable judging for people with 5 or more QF scores from this year

**Comment by Allicolyer** [comment]
@joemsak so Amy and Madhavi are going to make sure we really this feature -- we might not have enough judges who qualified. I will update you with what they say.
