### ISSUE TITLE
Live Event Judges can be Virtual Semifinal Judges

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1508]

**Comment by joemsak** [comment]
Just try these scenarios on QA (you might want to ask about 3 people from the last judging QA round to come back)

- As admin Set judging to SF
- Ensure some submissions are marked as Semifinalists

- Judge who had assigned teams can do virtual judging
- Judge who was at an event (or multiple events) without assigned teams can do virtual judging
- Virtual judge from QF can do virtual judging

**Comment by ophelieh** [comment]
All judges are able to score semi-finalist no matter if they were at live events or virtual judges. 

The only thing I noticed is regarding score, but that might be part of another ticket.

**Comment by Allicolyer** [comment]
Thank you for the super fast QA @ophelieh!

**Comment by kmorton2017** [comment]
Judge with unassigned teams at an RPE-confirm that I can see semifinalist teams.

**Comment by kmorton2017** [comment]
I think I'm a little confused about something. Under the "Manage your Scores" section, am I able to edit previous scores given in the quarterfinals?

I am logged in as Joe Mason. I'm not sure, but I think he has completed scores for the quarterfinals. But I don't see them. I also don't know if the finished scores refers to ALL finished scores or just semifinals. 

![uploads/12c96130-354c-4699-adee-f060e5b155b2/Screen Shot 2018-05-24 at 10.30.13 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F12c96130-354c-4699-adee-f060e5b155b2%2FScreen+Shot+2018-05-24+at+10.30.13+AM.png)

**Comment by Allicolyer** [comment]
@kmorton2017 thank you! So you should be able to click on "quarterfinals" to see your scores from quarterfinals. Let me know if that works.

**Comment by Allicolyer** [comment]
@kmorton2017 There is a new card for this now
