### ISSUE TITLE
Moving teams to semi-finals

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1510]
QA needed:

1. In the admin, change a few teams to semifinalists (remember which ones)
2. Change the judging round to semifinals
3. Log in as a virtual judge (make sure you are not a mentor for any teams) and make sure you can judge the semifinalists that you selected.

Use this if you do not have a virtual judge account:
email: alli+m3@iridescentlearning.org
password: alli+m3@iridescentlearning.org

**Comment by ophelieh** [comment]
Hi Alli, I actually tested this without realizing it. It works great! :)

**Comment by kmorton2017** [comment]
I confirm that I saw the new semifinalist teams California Coders and Katie Team 1. 

However, it looks like there may be something wrong with the count? 

For example: 
Ophelie2 has 3 incomplete scores and 0 complete on the scores page. When i click on view, it says that she actually has 1 complete -Sabrina Spellman and 3 incomplete. 

So the complete score for this team is not being reflected on the score page.

**Comment by ophelieh** [comment]
@kmorton2017 From what I deducted, the complete score is for the quarterfinals that's why it doesn't show on the score page.

**Comment by kmorton2017** [comment]
one question-are mentors not able to judge during the semifinals? i saw that you specified to login as a judge only account @Allicolyer

**Comment by Allicolyer** [comment]
@kmorton2017 mentors can judge during semifinals. It is possible that the submissions that are semi-finalists can't be seen by the mentors because they have a team in same region or division.

**Comment by kmorton2017** [comment]
got it. I think that was the case with the mentor I logged in as and the available submissions to review. ^

**Comment by Allicolyer** [comment]
Thank you @kmorton2017 !

**Comment by Allicolyer** [comment]
@ophelieh and @kmorton2017 I have created a new card about improving the admin UI for viewing scores.
