### ISSUE TITLE
Remove event details from Judge Dashboards for Semfinals

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1512]
For virtual judges from Round 1 - we might want to remove the text about pitch event (see below) on their dashboard as it could get confusing.
![uploads/e844d05f-a6dc-486e-927e-0354988f3feb/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f70726f642e6875626f6172642e636f6d2f75706c6f61647325324631363737663537382d376239382d343836642d626362642d643334616239386633366463253246696d6167652e706e67.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe844d05f-a6dc-486e-927e-0354988f3feb%2F68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f70726f642e6875626f6172642e636f6d2f75706c6f61647325324631363737663537382d376239382d343836642d626362642d643334616239386633366463253246696d6167652e706e67.png)

**Comment by Allicolyer** [comment]
@ophelieh we addressed your comment :) you can check it out.

**Comment by ophelieh** [comment]
Looks good Alli! :)

**Comment by Allicolyer** [comment]
Thanks @ophelieh!
