### ISSUE TITLE
Students view certificates

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1514]
QA Instructions:

As admin, set scores / certs enabled

1. Students with more than 50% of their submission complete a certificate of participation:
<ul>
<li>username: alli+s4@iridescentlearning.org
</li><li>
password: alli+s4@iridescentlearning.org
</li>
</ul>

2. Quarterfinalists students get a certificate of completion:

<ul>
<li>username: alli+s10@iridescentlearning.org
</li><li>
password: alli+s10@iridescentlearning.org
</li>
Also please try 
<li>username: student@student.com
</li><li>
password: student@student.com
</li>
</ul>

3. Semifinalists students get a semifinalists certificate INSTEAD of a certificate of completion:

<ul>
<li>username: alli+s3@iridescentlearning.org
</li><li>
password: alli+s3@iridescentlearning.org
</li>
</ul>

**Comment by Allicolyer** [comment]
@joemsak Asking about certs is in progress

**Comment by Allicolyer** [comment]
1. Students with more than 50% of their submission complete get this certificate of participation:
https://www.dropbox.com/s/wxoxi91zd97cety/CertificateofParticipation_2018-digital.pdf?dl=0

2. Quarterfinalists students get this certificate of completion:
https://www.dropbox.com/s/cy17yktogrgc6ri/CertificateofCompletion_2018-digital.pdf?dl=0

3. Semifinalists students get the semifinalists certificate INSTEAD of the certificate of completion:
https://www.dropbox.com/s/vm7r9p8it2lycoo/CertificateofSemifinalists_2018-digital.pdf?dl=0

4. RPE student winners get this certificate AND a semifinalist certificate: https://www.dropbox.com/s/i3pet2q4keyguih/CertificateofRPEWinners_2018-digital.pdf?dl=0

**Comment by Allicolyer** [comment]
actually @RRios00 it doesn't look like the certificate of completion was made for students. Could you make one for students. It can have the same language of the participation certificate. Maybe something like:

"in recognition of your completion of the 2018 Technovation season"

thank you :)

**Comment by joemsak** [comment]
@Allicolyer thinking about this some more .... is it the case that ONLY event winners become semifinalists? So if I check if a semifinalist has a live event attached, can I assume they are an RPE winner?

**Comment by joemsak** [comment]
@Allicolyer can I get confirmation on the questions above today? Thanks!

**Comment by joemsak** [comment]
oh okay so I think the certs for students stuff is ready then!

**Comment by Allicolyer** [comment]
@kmorton2017 and @monicagragg could you guys QA this? There are instructions about how to QA it at the top of the card.

**Comment by kmorton2017** [comment]
i am a bit confused on the student@student.com login page

is this a team that was at an RPE but did not receive scores? i did not see a certificate of completion for this student.

otherwise everything works as its intended to with the use cases.

**Comment by Allicolyer** [comment]
@kmorton2017 you are right about student@student.com. Thank you for catching this!

@joemsak students who attended an RPE but did not get scores (judges did not put them in) are not getting a certificate on the platform. Can you fix this?

**Comment by joemsak** [comment]
@Allicolyer @kmorton2017 thank you for catching this! It should be fixed now.

**Comment by ophelieh** [comment]
@Allicolyer Not sure how easy/hard is it to change the text on the certificates, but I feel that on the participation certificate replacing "throughout the..." by "in the..." would make the sentence flow better. 


![uploads/78313e0f-9006-4bd7-b1c3-edec735e020e/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F78313e0f-9006-4bd7-b1c3-edec735e020e%2Fimage.png)


Also, for student@student.com, it seems to be missing the text about why they do not have a score. 

Finally, the tab says "Certificates" but from what I see, students only receive 1 certificate. Could we drop the S from certificate on this page - https://technovation-qa.herokuapp.com/student/scores#!certificates 
![uploads/c0b2fdf7-0c7b-42c4-a22d-a5b5572b1fb3/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc0b2fdf7-0c7b-42c4-a22d-a5b5572b1fb3%2Fimage.png)

as well as on the dashboard - https://technovation-qa.herokuapp.com/student/dashboard 

![uploads/7e57cce2-fffb-499f-ab89-3591363901c5/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7e57cce2-fffb-499f-ab89-3591363901c5%2Fimage.png)

**Comment by joemsak** [comment]
Oh oops this requested text change in the participation certificate also goes to @RRios00 :)

**Comment by joemsak** [comment]
The participation certificate now has a the request change in the text

**Comment by ophelieh** [comment]
Looks good! Thanks!

**Comment by Allicolyer** [comment]
Thank you @ophelieh !
