### ISSUE TITLE
Mentors view certificates

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1515]
QA instructions

- As admin, set scores / certs enabled
- Log in as each of the following

Mentor on many teams:
username: alli+m1@iridescentlearning.org
password: alli+m1@iridescentlearning.org

Mentor on no teams
username: alli+m2@iridescentlearning.org
password: alli+m2@iridescentlearning.org

**Comment by Allicolyer** [comment]
asking program team in progress

**Comment by Allicolyer** [comment]
1. All mentors matched with a team get a certificate of mentoring
https://www.dropbox.com/s/3zsp6vhgt6qu58f/CertificateofMentor_2018.pdf?dl=0

2. Mentors who have a semifinalist team get a certificate of mentoring AND a certificate of semifinalist
https://www.dropbox.com/s/vm7r9p8it2lycoo/CertificateofSemifinalists_2018-digital.pdf?dl=0

**Comment by joemsak** [comment]
@Allicolyer this is ready on QA today - it seems to me the mentor receives one certificate for each team, so a download link is available in each team 'box' 

also don't forget, scores/certs have to be enabled, and just test a mentor with a team, a mentor with multiple teams, and a mentor with no teams. thanks!

**Comment by Allicolyer** [comment]
@ophelieh and @monicagragg could you both QA this card? There are instructions on how to QA at the top.

**Comment by joemsak** [comment]
The certificate language change for the mentor appreciation one would go to @RRios00 however the other requested change for students goes to me (just a difference in how the files are structured)

@Allicolyer @madhavitechnovation @ophelieh what do you think we should show to a mentor without any teams, when scores are open?

**Comment by RRios00** [comment]
Everything looks great! But is the "Open your certificate" button supposed to be on all panels? 


![uploads/a835b718-8309-4493-8808-494ae2208e09/screencapture-technovation-qa-herokuapp-mentor-dashboard-2018-06-14-14_40_48 (1).png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa835b718-8309-4493-8808-494ae2208e09%2Fscreencapture-technovation-qa-herokuapp-mentor-dashboard-2018-06-14-14_40_48+%281%29.png)

**Comment by joemsak** [comment]
Yes, it's one certificate per team. But actually @ophelie is asking for
some tiny text changes on the mentor and student certificates. Check both
cards I tagged you in and let me know when they're updated

Joe Sak
Technovation Web Development

SMS
+1 (312) 945-6317

**Comment by ophelieh** [comment]
That sounds great @Allicolyer !

**Comment by joemsak** [comment]
@Allicolyer could I get the links needed for the copy? Thanks!

**Comment by Allicolyer** [comment]
@joemsak 
Link to finalists page - http://technovationchallenge.org/season-results
Link to newsletter - https://confirmsubscription.com/h/d/15B1DBF38F40C405

**Comment by Allicolyer** [comment]
@joemsak could you style this slightly nicer? :) I think it could use a line break between the first two sentences and perhaps a header.  I think the header could be "Thank you". 


![uploads/56da8007-64e5-4964-8ab3-93d4eb11db85/Screen Shot 2018-06-21 at 5.31.06 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F56da8007-64e5-4964-8ab3-93d4eb11db85%2FScreen+Shot+2018-06-21+at+5.31.06+PM.png)

**Comment by joemsak** [comment]
Done
