### ISSUE TITLE
Remove pitch presentation upload field for scores and semifinals

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1516]
Remove pitch presentation upload fields for both mentors and students during scores and semifinals

![uploads/fdc6ab18-aadf-42de-921d-859ca4382068/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f70726f642e6875626f6172642e636f6d2f75706c6f61647325324632353130303261392d336132652d343338392d623063642d646332653636633133336236253246696d6167652e706e67.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffdc6ab18-aadf-42de-921d-859ca4382068%2F68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f70726f642e6875626f6172642e636f6d2f75706c6f61647325324632353130303261392d336132652d343338392d623063642d646332653636633133336236253246696d6167652e706e67.png)

**Comment by joemsak** [comment]
or just turn judging off after the QF date (may 22)

**Comment by kmorton2017** [comment]
I did not see a field to upload pitch presentations.
I was able to see my certificate.

**Comment by Allicolyer** [comment]
:thumbsup: Thank you @kmorton2017 !
