### ISSUE TITLE
Judges view certificates

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1517]
QA Instructions:

As admin, set scores / certs enabled

Judges who completed on boarded and graded at least one submission get this general judge certificate:
<ul>
<li>Username: judge@judge.com </li>
<li>Password:  judge@judge.com </li>
</ul>

Also try 

<ul>
<li>Username: judge2@judge.com </li>
<li>Password:  judge2@judge.com </li>
</ul>

Judges who completed at least 5 scores get the certified judge certificate: 

<ul>
<li>Username: alli+j8@iridescentlearning.org</li>
<li>Password: alli+j8@iridescentlearning.org </li>
</ul>

Judges who completed between 6-10 scores get the head judge certificate:

<ul>
<li>Username: alli+j9@iridescentlearning.org</li>
<li>Password: alli+j9@iridescentlearning.org</li>
</ul>

Judges who completed 10 or more submissions get the judge advisor certificate:

@joemsak  please help me set up this QA scenario

RPE JUDGES:

All judges get the Head Judge certificate regardless of how many submissions they judged:

<ul>
<li>Username: alli+j4@iridescentlearning.org</li>
<li>Password: alli+j4@iridescentlearning.org</li>
</ul>

Also try 

<ul>
<li>Username: alli+j5@iridescentlearning.org</li>
<li>Password: alli+j5@iridescentlearning.org</li>
</ul>

RPE judges who graded more than 10 submissions get the judge advisor certificate:

@joemsak  please help me set up this QA scenario

**Comment by Allicolyer** [comment]
@RRios00 Hey Ruby!

We need to create one more judge certificate. It will be a general judge certificate for those who completed less 5 submissions.

**Comment by RRios00** [comment]
Hey @Allicolyer ! 
The Certified Judge, Head Judge, and Judge Advisory are in the Digital Distribution folder in the DropBox. I will put the General Judge certificate there.

**Comment by Allicolyer** [comment]
Thanks @RRios00 !

**Comment by RRios00** [comment]
@Allicolyer It's been upload

**Comment by Allicolyer** [comment]
hey @RRios00! Instead of "general judge" can you change it to just call them "judges". Also it still says "certified judge" at the bottom of the certificate.

**Comment by RRios00** [comment]
Judge color certificates have been changed from dullest to brightest to indicate proper judge level. 

![uploads/20122d06-fd65-4c5d-9631-669330fed85f/JudgeCertificateView.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F20122d06-fd65-4c5d-9631-669330fed85f%2FJudgeCertificateView.png)

..


*Judge: 1 score
	tc-judge-icon.svg
	Certificate-Judge_2018.pdf
	https://drive.google.com/file/d/1vg-9cEP9J-Q1ZgSshn7ikTYJWv2tf0hR/view?usp=sharing

*Certified Judge : 5 scores
	tc-certified-judge-icon.svg
	Certificate-CertifiedJudge_2018.pdf
	 https://drive.google.com/file/d/1GV3BFjmpcLZJ7C8nmgoLe4QwVkiTDHaF/view?usp=sharing

*Head Judge : 6-10 scores
	tc-head-judge-icon.svg
	Certificate-HeadJudge_2018.pdf
	https://drive.google.com/file/d/1UWJ8G_FEGzYLhn8FhBlOfoR2iy3QXj4E/view?usp=sharing

*Judge Advisor : 11+ scores
	tc-judge-advisor-icon.svg
	Certificate-JudgeAdvisor_2018.pdf
	https://drive.google.com/file/d/1IW8szBiP9yOqdwMy-O8jTxTY0pUxJgOV/view?usp=sharing


![uploads/9f156e27-8d45-40be-831b-844565944449/JudgeCertificateView-Panel-02.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9f156e27-8d45-40be-831b-844565944449%2FJudgeCertificateView-Panel-02.png)

Not sure if the message for the judges should change.

**Comment by joemsak** [comment]
@Allicolyer does an RPE judge get a head judge AND advisor for 10 or more, or just judge advisor?

**Comment by joemsak** [comment]
This ought to be ready for QA now

**Comment by Allicolyer** [comment]
@joemsak an RPE judge gets just advisor

**Comment by Allicolyer** [comment]
Hey @monicagragg please QA this one on Monday. Instructions are at the top of the card.

**Comment by monicagragg** [comment]
Hi, I logged into each scenario provided at the top and took a screenshot of each certificate 
![screenshot 2018-06-18 12 28 24](https://user-images.githubusercontent.com/14184210/41549425-d197401a-72f3-11e8-86ee-9a672dec918a.jpg)
![screenshot 2018-06-18 12 29 03](https://user-images.githubusercontent.com/14184210/41549426-d1a37326-72f3-11e8-91b0-0451c1bd8707.jpg)
![screenshot 2018-06-18 12 29 36](https://user-images.githubusercontent.com/14184210/41549427-d1d39088-72f3-11e8-81ff-b63ca232b0ac.jpg)
![screenshot 2018-06-18 12 30 00](https://user-images.githubusercontent.com/14184210/41549428-d1e0d82e-72f3-11e8-9847-0a12a08a4fdc.jpg)
![screenshot 2018-06-18 12 31 40](https://user-images.githubusercontent.com/14184210/41549429-d1efb920-72f3-11e8-9f82-c39978709c9d.jpg)
![screenshot 2018-06-18 12 32 04](https://user-images.githubusercontent.com/14184210/41549430-d1fb28f0-72f3-11e8-97b7-cd4bdb21a8c6.jpg)

**Comment by Allicolyer** [comment]
@monicagragg do all the certificates look correct to you?

**Comment by Allicolyer** [comment]
Hey @monicagragg we are looking to close this card by EOD. Do all the certificates look correct to you, do you need any changes?

Thank you!

**Comment by monicagragg** [comment]
We're missing Judge Adviser

**Comment by Allicolyer** [comment]
@monicagragg yes please see card #1539

**Comment by Allicolyer** [comment]
@joemsak can we add some text for a judge who is not getting a certificate? I think the text that we used for mentors should work.

"Thank you for your participation in the 2018 Technovation season. Check out the finalists [link to finalists page]. The 2019 season will open in the Fall. Sign up for our newsletter to stay in the loop about important dates and updates [link to newsletter]."

**Comment by joemsak** [comment]
Done.

Language changed a bit for judges and mentors as I believe that "check out" and "stay in the loop" might not easily translate for people

**Comment by Allicolyer** [comment]
yes looks good joe! Running it by Ophelie on Slack for final approval from program staff.

**Comment by Allicolyer** [comment]
approved
