### ISSUE TITLE
Improve Admin Score CSV

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1518]
Comments from Amy:

1. When you export the CSV, I am not sure which round of scores it is pulling. Maybe it is a mix? If so, it will be good to have a column for "contest rank".
2. Can we also have a export file for average scores for semi final round?

**Comment by joemsak** [comment]
1. It will now obey the filter, and have the contest rank column

2. I need more information on what this means specifically. Can I have a concrete example?

**Comment by joemsak** [comment]
Sorry, had a bug, will put back in test when bugs gone and I have tested it on QA

**Comment by joemsak** [comment]
Okay seems to work to me now

**Comment by joemsak** [comment]
Also for the next deploy (20 min from this comment) you should get helpful database ID columns for easier debugging with me Alli or mike: 

id	team_id	team_submission_id	judge_account_id

**Comment by amyiridescent** [comment]
So it looks like you can't download a csv with quarter finals AND semi finals at the same time. That is fine. We just need to make sure we select a filter for "rounds" before downloading.

**Comment by Allicolyer** [comment]
@amyiridescent is everything else okay?

**Comment by amyiridescent** [comment]
Yes ma'am

**Comment by Allicolyer** [comment]
:+1:
