### ISSUE TITLE
Add "rank" as one of the outputs for the submission CSV

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1519]
Admins need to see the "rank" of a team as a quarterfinalist or semifinalists on the submission CSV

**Comment by Allicolyer** [comment]
@amyiridescent could you check this out :)?

**Comment by amyiridescent** [comment]
Looks good. One question: Can this also be added to the saved search on live site? For "Complete, All fields" saved search option. Thanks

**Comment by joemsak** [comment]
Saved searches are custom made by users. Just delete the existing saved
search and create a new one with the correct fields

Joe Sak
Technovation Web Development

SMS
+1 (312) 945-6317

**Comment by Allicolyer** [comment]
@amyiridescent is this good to go with that answer?

**Comment by amyiridescent** [comment]
@joemsak got it. I didn't realize I can edit the saved search you created for me. 
@Allicolyer Yeap. Good to go. :)

**Comment by joemsak** [comment]
I didn't create the saved searches, someone else must have

Joe Sak
Technovation Web Development

SMS
+1 (312) 945-6317

**Comment by Allicolyer** [comment]
:thumbsup:
