### ISSUE TITLE
Investigate how a complete score could have "0" for pitch

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1525]
It appears that this judge was able to give "0" for pitch. When I logged in as the judge it appears that they did not select anything. The score is marked as complete.

https://my.technovationchallenge.org/admin/scores/15733

**Comment by joemsak** [comment]
@Allicolyer  @adrichey is already investigating thanks!

**Comment by adrichey** [comment]
Potentially closed by: https://github.com/Iridescent-CM/technovation-app/pull/1526

**Comment by joemsak** [comment]
@Allicolyer have you seen any 0's in the scores since this possible fix? Thanks!

**Comment by adrichey** [comment]
@Allicolyer I was going through the backlog just now and I think we should be able to close this. Does this appear to still be an issue?

**Comment by Allicolyer** [comment]
Thanks @adrichey !
