### ISSUE TITLE
Admin Editability: Judge Certificates 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1535]
Admins need a way to update judge certificates that are incorrect and have them live at the same URL they are at now.  

We need a way to update:
- Name on the certificate
- Type of certificate (head judge, judge advisor, ect.)

Do you have any solutions around how we could do this? We will need this by mid next week.

**Comment by joemsak** [comment]
@Allicolyer @madhavitechnovation @amyiridescent is there a reason you wouldn't just change the person's name on their account so that the certificate generates the correct name from their account? I'm just trying to learn more about that particular requirement

**Comment by joemsak** [comment]
QA:

Ensure you can login as a judge that qualifies for any kind of judging certificate

As the admin, enable certificates and scores

As the judge, verify that you can download the correct type of automatic certificate

As the admin, find your judge and change the certificate

As the judge again, verify that this change is reflected in your certificate and badge

Please do not override the judge to non-judge certificate types, this is the simplest UI that can produced on such short notice, so we should trust our own staff to select certificate types that make sense for the account. Also, this select box ONLY appears for Admins and ONLY when looking at judge profiles

**Comment by Allicolyer** [comment]
@monicagragg can you please QA this? Joe has instructions right above.

**Comment by monicagragg** [comment]
1) As an admin, I was able to change the certificate type (see screenshot) 
![screenshot 2018-06-18 17 34 23](https://user-images.githubusercontent.com/14184210/41563746-8d2c4454-731e-11e8-9e10-9ec395aaa121.jpg)

2) As a judge, I was able to log in and download my certificate (attached).
[2018-general_judge-7-.pdf](https://github.com/Iridescent-CM/technovation-app/files/2113067/2018-general_judge-7-.pdf)

3) The change in certificate was reflected (attached0
[2018-judge_advisor-7-.pdf](https://github.com/Iridescent-CM/technovation-app/files/2113076/2018-judge_advisor-7-.pdf)

I don't know what this means, "As the admin, enable certificates and scores"

**Comment by Allicolyer** [comment]
Thank you @monicagragg!

**Comment by Allicolyer** [comment]
@monicagragg "As the admin, enable certificates and scores" means to change the season toggles as an admin so that scores and certificates are "turned on".

**Comment by Allicolyer** [comment]
@joemsak I will QA this too and then we can close it.

**Comment by Allicolyer** [comment]
@joemsak this works great.

 One thing I noticed is that if I change the name of the judge, the certificate does not update. I can, however, force it to update by change the judge's rank to something else and then change it back, which might be good enough functionality for now.

**Comment by joemsak** [comment]
No, you're right, I should clear out their certificates if a name change is detected. Ready for QA again

**Comment by Allicolyer** [comment]
@joemsak will QA today

**Comment by Allicolyer** [comment]
Thanks Joe. This works great.
