### ISSUE TITLE
Judges who graded more than 10 submissions get Judge Advisor certificate

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1539]
Applies to RPE & Virtual judges both

Joe is setting up the data on QA

**Comment by joemsak** [comment]
@Allicolyer to QA:

login as the admin and verify:

a judge with email live@judge-advisor.com is attending the 'seeded advisor event'
(search judges by event name)
and has 11 scores
and is marked as a judge advisor in the judge level dropdown

a judge with email virtual@judge-advisor.com is a virtual judge
(search virtual judges)
and has 11 scores
and is marked as a judge advisor in the judge level dropdown

login as each judge
email: virtual@judge-advisor.com
password: virtual@judge-advisor.com

email: live@judge-advisor.com
password: live@judge-advisor.com

complete the onboarding steps for each judge
verify the correct certificate and badge (judge advisor)

**Comment by Allicolyer** [comment]
@monicagragg can you please QA this? Thank you!

**Comment by Allicolyer** [comment]
Hey @monicagragg are you able to QA this by EOD? 

Thank you!

**Comment by Allicolyer** [comment]
@joemsak amazing! Thanks for help setting this up.
