### ISSUE TITLE
Add judge rank to judge CSV export

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1546]
Add judge rank to the judge CSV export. For example "General Judge, Certified Judge, Head Judge, Judge Advisor, ect".

Judges with 0 scores should have nothing listed in that column

**Comment by Allicolyer** [comment]
@joemsak is it possible to have this by Monday?

**Comment by joemsak** [comment]
Should be ready on QA in 20 minutes or so

**Comment by Allicolyer** [comment]
@monicagragg this feature is available for you to use on Monday
