### ISSUE TITLE
Individual Admin Accounts

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1548]
New Admin page: "Admins"

You invite new people via name and email

An email is sent to that person with a special token link
The link takes them to create their password
The password must be at least 20 characters
New Admins cannot access anything until they create a password

Admins can delete other admins
If only one admin is left, there is no delete option

Once an admin has created a valid password, the special email link will no longer work
(logout and try the email link again)

Other profile types and the general public cannot access the following URLs:
/admin/admins
/admin/admins/new
/admin/signup

This is all already functioning on QA as described above

**Comment by joemsak** [comment]
@Allicolyer the work on this card is already done and everything described is ready for QA

**Comment by Allicolyer** [comment]
@madhavitechnovation can you QA this?

**Comment by Allicolyer** [comment]
@amyiridescent can you QA this?

**Comment by amyiridescent** [comment]
Looks good to me. I assume season toggle has been reset on staging but I assume the access of my personal admin is the same as for info@ log in.

**Comment by Allicolyer** [comment]
Thank you @madhavitechnovation. I think one of us would be in charge of inviting people to be admins. Also most of us do not have other accounts on production (except maybe you and Katie)

**Comment by joemsak** [comment]
Are there any action items remaining for me?

**Comment by joemsak** [comment]
@Allicolyer @amyiridescent @madhavitechnovation this card seems ready and we just need to roll out the invites to key staff members so that I can remove the generic info@ login

**Comment by kmorton2017** [comment]
can someone invite me to be an admin so i can QA this? @joemsak @Allicolyer

**Comment by joemsak** [comment]
@kmorton2017 on QA, there will always be an `admin@admin.com` login

**Comment by Allicolyer** [comment]
@joemsak this works great. @kmorton2017 I am going to close this card.
