### ISSUE TITLE
Look into using mailgun to validate emails

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1550]
Concerns:
- If we don’t know that it is really their email, they won’t get our email updates throughout the season.

**Comment by joemsak** [comment]
I think what we can do here is speed up the signup process by detecting a truly valid email address with this service.

I'm not very concerned with the idea that people would waste their own time by putting in someone else's email address; if that really is happening it's almost certainly statistically zero. I would choose not to prioritize a secondary activation email feature for now.

The mailgun API can detect if an email address is real based on a handful of different technical factors, and they can even detect if the email address was created with one of those fake inbox services. I have my doubts that our users are either savvy enough or interested in using such services, though. Still, the API protects us there anyway, without extra work.

Further more, as a reminder for myself and @adrichey we need to ensure the validation component is usable on profile email edit pages (user and admin)

**Comment by joemsak** [comment]
We can also explore other mailgun API endpoints for detecting suppressed emails to let the participant know we detected an issue

**Comment by joemsak** [comment]
@adrichey for me and you http://mailgun-documentation.readthedocs.io/en/latest/api-email-validation.html#example

Would be good to use the 'did you mean' feature

Also use the domain property to look for `edu` and strongly remind people that school email often blocks us and if they insist on using it, they should ask their IT Admin to ensure our domain will not be blocked

**Comment by joemsak** [comment]
Email events can be configured to POST to custom webhooks on our application

http://mailgun-documentation.readthedocs.io/en/latest/user_manual.html#webhooks

This would be for a separate card about detecting and reporting email issues, though, if we wish to prioritize such a feature in future sprints

**Comment by joemsak** [comment]
@Allicolyer for your notes, I would like to have this part finished in preparation for the wizard-style onboarding

**Comment by joemsak** [comment]
@Allicolyer @amyiridescent @madhavitechnovation the research part is done, I'd like to discuss adding this feature into the updates we want to make to signing up (the wizard style we discussed)

**Comment by Allicolyer** [comment]
@joemsak was there anything left to discuss after today?

**Comment by joemsak** [comment]
nope, gonna attempt to roll it into the new wizard screens
