### ISSUE TITLE
Make mentor e-book mandatory as a part of onboarding

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1556]
As a mentor
Registering for the current season (returning or new mentor, please test both)
If I register before the date that training is available
I should not be required to complete the training

If I register on or after the date that training is available
I should be required to complete that training

QA NOTES:
* Clicking the training goes directly to marking the training as complete (for QA only!)
* This card now covers the cosmetic changes and copy that the mentor should see
* You must work with a developer to change the "required training date"
* To register 'before the training is available,' ask the developer to set the required training date to the future
* To register 'on or after the training is available,' ask the developer to set the required training date to today
* Ask the developer for a login for a "returning mentor" to do the two before/after training date tests, as well
* Cards have been added for covering the completion of that training actually having an affect on admin / RA searches, students searching for mentors, and the mentor being onboarded and being able to join teams - please limit your testing scope to the criteria written above the notes, with  the notes in mind. Thanks!

**LOGIN FOR PAST MENTOR**
amy+past-mentor@iridescentlearning.org (password is also the email)

* you must let me know to reset this account back into the past every time you're testing as a returning mentor logging in

**Comment by Allicolyer** [comment]
@amyiridescent we are blocked on this issue.

**Comment by Allicolyer** [comment]
@joemsak Amy and I are wondering what some different options are for making this mandatory. We know we used atavist last year to make the judge training mandatory. Could we use google slides in the same way?

**Comment by joemsak** [comment]
Well, before we discuss implementation, my initial feeling is that it's very late in development to introduce mandatory onboarding steps to mentors and students, we are less than 2 weeks from opening registration.

**Comment by amyiridescent** [comment]
@joemsak I understand this is late but I believe I have mentioned this previously that this change will be coming up.... we need to find a way to actually train these mentors that we claim to train. I know I am developing this training last minute but I hope you understand that I am trying to wear my hat along with 2 other people's hats right now. :(

Can you borrow code from the judge training we did last year?

**Comment by joemsak** [comment]
It's true you mentioned it but until it becomes a finalized card that is discussed and accepted by the dev team in a sprint planning, we are not committing to it or prioritizing it, therefore this is a very late time to have the discussion if you're expecting it to be Oct 1 ready. We talked registration requirements in June / July sprints.

It's not a question of "borrowing code" - the change to what it means to be an onboarded mentor changes more than just an extra step in their dashboard UI. I'm happy to discuss the card and make it ready for a future sprint but if the expectation is an October 1 live date, it becomes a high risk story that we don't have sufficient time to design and test, and we will have to trade off other cards to save for a future sprint.

**Comment by amyiridescent** [comment]
Ok here is my compromise. 

Can we tackle in October? I know we will have some mentors sign up when we open in Oct 1st but we can manually email them to take the training (and I know some won't, but we don't get too many people signed up during the first few weeks so it might not be a problem.) I understand it is a tight timeline to deploy this by Oct 1st but this is the fastest I am able to get to this. 

The thing we probably need to think about is if mentors sign up before this training is deployed, will that information have to be stored differently than for mentors who create accounts AFTER training is deployed. Do you anticipate any issues with that if we deploy this later?

**Comment by joemsak** [comment]
If mentors join teams, changing their status to not being onboarded (because of the addition of a new step) would hide their teams from them until they finish their onboarding

I dont think this is a huge deal, the same thing happens if they change their email (a box with info about their changed email blocks their dashboard until they use the confirmation email)

And yes, I am always fine with any story coming up in future sprints, as that is the process we're trying to stick to to manage the chaos ;-P

**Comment by joemsak** [comment]
Of course, in the case where a mentor joined a team and then never did the training, how long should we wait until we kick them off the team? We'd want to design warnings in the UI and maybe a reminder email to let them know they'll be removed from the team if they don't finish the new training

**Comment by amyiridescent** [comment]
Lets definitely add this to the next sprint. 

I think for those mentors who will get onboard between Oct 1 and "post training deployment" it might be nice for something to remind them to take the training the next time they come back onto the platform. Do you think we need to make it so they get dropped from the team? 

There are a few countries like Australia and Germany who ran the program during the summer and will be registering in October to submit their submissions. For those mentors, it might not make sense to force them to do the trainings right now as their season just ended. Let me think through this a bit more before the next sprint. 

**Question for @joemsak **: Can the training be a google presentation? It will have a unique URL and set for public view. Will that work for the "can't move on unless open link" magic you built for the judge training? Just need to know before I finalize the training. Thanks.

**Comment by amyiridescent** [comment]
I am up for pre-planning sprints exercise on this topic. Let me know what I need to get ready before we can do that.. I am going to focus on putting all the training materials into the slide deck but let me know what the next steps are.

**Comment by amyiridescent** [comment]
From Joe: 
#1556 Test plan
In this testing session, you will perform your actions as two kinds of mentors:
1. Sign up as a new mentor
Log in as a returning mentor from a past season
Past mentor account login: amy+past-mentor@iridescentlearning.org (password is same)
Test a new mentor before the training date is available:
Tell Joe to set the training date to a day in the future
2. Sign up as a new mentor with your email address (use the + trick as needed)
Verify that you are not required to take the training
Log out
Test a new mentor on or after the training date is available:
Tell Joe to set the training date to today
3. Sign up as a new mentor
Verify that you are required to take the training
Log out
Test a returning mentor before the training date is available:
Tell Joe to set the training date to the future
Login as the past mentor
Verify that you do not have to take the training
Logout
4. Test a returning mentor on or after the training date is available:
Tell Joe to set the training date to today, and to reset the past mentor
Login as the past mentor
Verify that you are required to take the training
Log out

**Comment by amyiridescent** [comment]
1. As new mentor BEFORE training date, I am not required to take the training. 
3. As returning mentor BEFORE training date, it asks me to sign the consent waiver but not required to be background check or update personal statement. I can request to join a team or start a team. I can do all of this WITHOUT taking the training. 

Will do 2 & 4 after training data is reset.

**Comment by joemsak** [comment]
![uploads/a3301344-b4c1-4696-89cd-b49c0deddb97/Screen Shot 2018-10-03 at 2.53.44 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa3301344-b4c1-4696-89cd-b49c0deddb97%2FScreen+Shot+2018-10-03+at+2.53.44+PM.png)

**Comment by amyiridescent** [comment]
4. For a returning mentor AFTER training date, it does not let me join a team without doing training. 

![uploads/dd86de28-ca9c-4b45-8fb3-181b1491f4bd/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdd86de28-ca9c-4b45-8fb3-181b1491f4bd%2Fimage.png)

So then I click on "mentor training" (where the mentor training link will live in the future), a green pop up shows up saying "thanks you for completing the consent waiver". Does that text need to change?

**Comment by amyiridescent** [comment]
Ok case #2 is fine also. I just had to do the background check. 

![uploads/673a553a-09a2-438c-8cb0-be0eb5a62c0f/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F673a553a-09a2-438c-8cb0-be0eb5a62c0f%2Fimage.png)
