### ISSUE TITLE
Add mentor registration fields

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1558]
Educator, Industry mentor or Parent

**Comment by Allicolyer** [comment]
@kmorton2017 could you check this feature out and let me know what you think?

**Comment by kmorton2017** [comment]
looks good!

**Comment by joemsak** [comment]
@kmorton2017 thank you for your feedback, @Allicolyer Katie's suggestion, if we want to go forward with it, would be a separate card, thanks!

**Comment by Allicolyer** [comment]
@kmorton2017 thanks!

**Comment by Allicolyer** [comment]
@kmorton2017 good catches thank you!

**Comment by joemsak** [comment]
@Allicolyer @amyiridescent @madhavitechnovation @kmorton2017 

I never got an answer to this question:

What about former students converting to a mentor? Should we add a type for them? "Former Technovation student" or something?

**Comment by madhavitechnovation** [comment]
Yes @joemsak we should add Technovation student Alumni to the list. It will be great to collect this data.

**Comment by joemsak** [comment]
Alright, for ESL sensitivity, I am thinking to use "Past Technovation student"
