### ISSUE TITLE
Sign-up date and time for Admins and RAs in CSV download

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1559]
Make it easier to see which accounts are newest.

**Comment by joemsak** [comment]
@Allicolyer this column option is already present under "more columns" as "Signed up"

**Comment by Allicolyer** [comment]
@kmorton2017 could you QA this?

**Comment by kmorton2017** [comment]
I am having trouble downloading the CSV file. nothing happens.  there is no pop up that says "your file is ready!" with the green download button

**Comment by joemsak** [comment]
@kmorton2017 thank you so much for helping me find this error. The CSV notices should be working once again.

**Comment by Allicolyer** [comment]
Thanks @kmorton2017 !

**Comment by Allicolyer** [comment]
@joemsak this works.

**Comment by Allicolyer** [comment]
@joemsak Katie is out this week so I will close out this card.
