### ISSUE TITLE
See new students and returning students on their profiles

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1560]
Admins and RAs want to see who is a returning students when viewing a student's profile.

**Comment by joemsak** [comment]
@Allicolyer please split the change to the Filtering UI to its own card

**Comment by Allicolyer** [comment]
@kmorton2017 what do you think? Here is what admins and RAs see when viewing a student's profile. They will also be able to filter new and returning students, but that is still in the works.


![uploads/fe697f7c-b642-46bb-929e-cabed49671f4/Screen Shot 2018-06-29 at 10.43.58 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffe697f7c-b642-46bb-929e-cabed49671f4%2FScreen+Shot+2018-06-29+at+10.43.58+AM.png)


![uploads/2135844f-e270-4042-86f9-39a1226263b7/Screen Shot 2018-06-29 at 11.04.19 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2135844f-e270-4042-86f9-39a1226263b7%2FScreen+Shot+2018-06-29+at+11.04.19+AM.png)


![uploads/6ac09bdf-7c0c-4efd-8504-7815f44a3e6c/Screen Shot 2018-06-29 at 10.52.09 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6ac09bdf-7c0c-4efd-8504-7815f44a3e6c%2FScreen+Shot+2018-06-29+at+10.52.09+AM.png)

**Comment by kmorton2017** [comment]
I might like to see it as a field under their age. I think if you scan a student's profile quickly you may miss it if its under their picture in smaller font

**Comment by joemsak** [comment]
@kmorton2017 thank you, we will probably make some more updates to the design this summer, so for now I will only move the seasons part under age as requested. Moving to the other column is actually not as straightforward, as each type of profile has their own unique data listed there, with the common data fields on the left side

**Comment by joemsak** [comment]
@kmorton2017 thank you for helping with QA, please take another look

**Comment by Allicolyer** [comment]
@ophelieh could you QA this? As an admin go to the participants page and view the following students. 

Current student:
student@student.com

Past student (make sure you are also looking for participants in the 2017 season):
past@student.com

Returning student:
returning@student.com

**Comment by ophelieh** [comment]
Looks good! I do like Katie's idea of moving the location to the next column, but you mentioned some edits to the design later this summer.

**Comment by Allicolyer** [comment]
@ophelieh thank you!
