### ISSUE TITLE
Ability to see top countries in terms of registrations,submissions etc. 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1561]
We would like to see this as a pie chart on main admin dashboards

**Comment by joemsak** [comment]
Really exciting stuff is happening in service of this card :)

**Comment by adrichey** [comment]
Here is a preview of the bar chart that will summarize the top country data for students, mentors, and judges:
![uploads/7be08fdc-b376-48cd-a2aa-1f7bde832f80/Screen Shot 2018-07-10 at 12.35.39 PM (2).png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7be08fdc-b376-48cd-a2aa-1f7bde832f80%2FScreen+Shot+2018-07-10+at+12.35.39+PM+%282%29.png)

**Comment by adrichey** [comment]
Work for this has been wrapped for the time being. The acceptance criteria for this card was pretty sparse, so I winged it in terms of what the chart data would look like with Joe's input. We now have a base in place to build upon for any metrics we want to see in a bar or pie chart. I have implemented a Top Countries section in the admin dashboard section that displays the top countries in terms of student, mentor, and judge totals. We can add other charts that we think of as time goes on with the new infrastructure in place.

**Comment by Allicolyer** [comment]
Thank you @adrichey! This looks great. One things I noticed is that the order of the countries keeps switching each time I click on the countries tab.

![uploads/c5e85457-9cfd-451e-909b-c313f3f9cf00/Screen Shot 2018-07-11 at 11.44.07 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc5e85457-9cfd-451e-909b-c313f3f9cf00%2FScreen+Shot+2018-07-11+at+11.44.07+AM.png) 

![uploads/afa65bdd-63a2-481d-b8df-0941b6de375d/Screen Shot 2018-07-11 at 11.44.01 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fafa65bdd-63a2-481d-b8df-0941b6de375d%2FScreen+Shot+2018-07-11+at+11.44.01+AM.png)

**Comment by Allicolyer** [comment]
@amyiridescent and @madhavitechnovation you will both really like this, can you QA this card?

**Comment by adrichey** [comment]
Weird. I will look into that switch. I am not sure what would be causing that. But I can work on a fix today.

**Comment by adrichey** [comment]
I figured out the issue. The datasets didn't have zero values in places where they were necessary. I have submitted a PR for that for @joemsak to review.

**Comment by joemsak** [comment]
@Allicolyer are there any outstanding issues for this card?

**Comment by kmorton2017** [comment]
Looks good! What's the max # of countries it will show @adrichey ?  from your screenshot i looks like 10?

**Comment by joemsak** [comment]
@kmorton2017 right now it shows up to 10. maybe in the future we can add filters and controls to these charts

**Comment by Allicolyer** [comment]
@amyiridescent @madhavitechnovation do either of you have any comment about this?

**Comment by amyiridescent** [comment]
So right now I only see the charts for # registered users. Is it safe for me to assume, we will be able to see this for submissions also? I also am assuming these numbers are of these users that completed onboarding, is that true?

**Comment by joemsak** [comment]
Good point @amyiridescent alan and i will reconvene tomorrow to discuss how to filter the chart between participants, submissions and leaving us open to future options that staff may wish to select

as for the numbers, they are scoped on all users, not just onboarded ones

**Comment by joemsak** [comment]
@Allicolyer @amyiridescent I think we'd better consider splitting the ability to filter the types of data (from participants to submissions to "etc") into another card, I will need Alan to help me work as a pair through some of the more complex code and logic for the new registration wizard

**Comment by Allicolyer** [comment]
@joemsak let's bring this up during the sprints to see what graphs we would like to build.
