### ISSUE TITLE
Create auto-fill for top company sign ups

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1562]
Program team to give us a list of top companys that mentors and judges sign up from.

**Comment by Allicolyer** [comment]
@madhavitechnovation could your provide us with a list of top companies that mentors and judges sign up from?

**Comment by madhavitechnovation** [comment]
Salesforce, Adobe, Gogle, uber, Samsung, oracle, AECOM, HARMAN, Microsoft, Accenture, Bank of America.

I hope we can add more tot he list, if we have new partners, correct?

**Comment by adrichey** [comment]
Work for this has been completed. We have implemented an input that allows you to either select from a list of top companies or add your own company that isn't in the list. @madhavitechnovation editing the list of top companies is very straightforward and won't break anything if we ever need to add or remove one from the list as it is done in one place.

**Comment by Allicolyer** [comment]
@joemsak @adrichey will this auto fill based on IP addresses or is this just a dropdown list for signup?

**Comment by Allicolyer** [comment]
@adrichey I noticed something unexpected about this text box for Company name. If you start typing something, you must also hit enter for it to save any characters you typed. If you click out of the box or click tab it will not save the characters you've typed.

**Comment by adrichey** [comment]
@Allicolyer This will not fill based on IP addresses for this iteration. I would suggest that we save that piece of functionality for an improvement card later on. The component we implemented is called vue-select, and it requires that enter key press or a click on the drop down as it functions similarly to `<select>` element rather than a standard input.

**Comment by Allicolyer** [comment]
okay great!
