### ISSUE TITLE
XFilter UI for Admins and RAs to see who is a returning students 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1565]
Admins and RAs want to easily filter who is a returning and who is a new student

**Comment by joemsak** [comment]
Can currently filter by multiple seasons, change to "match all" instead of the default "match any" and scope profile types down to "student"

We could stand to improve the UI to make such a feature a bit more obvious? Easier to use? We certainly dont have a "only this season" filter
