### ISSUE TITLE
Change Region to a better word

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1568]
Katie will get back to us about the most appropriate word.

**Comment by Allicolyer** [comment]
@kmorton2017 I added this card so let me know when we have progress with this. You can check in here or on slack. If we won't have progress on this for a while, let me know!

**Comment by joemsak** [comment]
Decided: Country / Territory

**Comment by joemsak** [comment]
@Allicolyer this work has been rolled into card #1586

**Comment by Allicolyer** [comment]
Thanks @joemsak I can close out this card.
