### ISSUE TITLE
New mentors should not be able to switch to judge mode

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1571]
Mentors should not be able to switch to judge mode. 

It is possible we will want his feature again when judge registration opens  but is is also possible program team will not want mentors to be judges this year.

**Comment by joemsak** [comment]
This card needs some more discussion. We had the 'switch to judge mode' link blocked behind an Admin enabling/disabling judge signups and then early on in the season, before opening up judge signups in general, staff decided that mentors should be able to switch at that time in order to be prepared for when judge registration opened.

**Comment by joemsak** [comment]
* new mentors, or mentors who do not already have judge profiles, should not be able to switch to judge mode

* existing judges should be able to switch

**Comment by Allicolyer** [comment]
Thank you @joemsak for this. 

@madhavitechnovation  can you QA this?

<ol>
<li>Log in as a mentor with existing judge profile:  mentor@mentor.com 
<ul>
<li> Ensure that they can switch to judge mode </li>
</ul></li>
<li>Create a new mentor 
<ul>
<li>ensure that they cannot switch to judge mode</li>
</ul></li>
</ol>

**Comment by Allicolyer** [comment]
@kmorton2017 could you QA this?

<ol>
<li>Log in as a mentor with existing judge profile:  mentor@mentor.com 
<ul>
<li> Ensure that they can switch to judge mode </li>
</ul></li>
<li>Create a new mentor 
<ul>
<li>ensure that they cannot switch to judge mode</li>
</ul></li>
</ol>

**Comment by madhavitechnovation** [comment]
@Allicolyer this works fine. When I created a new mentor account, i did not an option to move to judging.

**Comment by Allicolyer** [comment]
Thanks @madhavitechnovation !
