### ISSUE TITLE
Add 'Past Technovation student' to mentor types

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1583]
When mentors choose their type (industry professional, teacher, parent...) we are adding another option for past students who are converting to a mentor account.

**Comment by Allicolyer** [comment]
@ophelieh could you QA this?

1. As a admin, turn on registration for mentors. 
2. Create a new mentor account, see that this option is available  as a "type"
3. Log in as an admin and make sure the new mentor is properly labeled as a "past TC student"

**Comment by ophelieh** [comment]
Looks good! If I was to log in through my student account though, would I be able to turn it into a mentor account? Or would I need to create a new account as a mentor?

**Comment by joemsak** [comment]
@ophelieh @Allicolyer currently, students have to be converted by a mentor or RA. we can discuss the option of a self-serve feature in a future sprint

**Comment by kmorton2017** [comment]
hi everyone, wasn't sure to put this. but i noticed on the mentor profile it provides info on the QF Scores, SF Scores and Judge Level/Certificate. Is it possible to hide this info? I think it clutters the page info a bit and is not relevant for the mentor profile until the  judging starts.

**Comment by joemsak** [comment]
@Allicolyer seems like this card is complete and verified

@kmorton2017 Thanks for your thoughts on the Admin UI. We will want to record these issues in separate sprints so please bring them to future meetings. It's good that QA'ing one thing brings up ideas about other things, but please try to keep the card focused on its acceptance criteria, and bring any extra ideas, thoughts, and notes that you come up with to the next sprint planning.

**Comment by ophelieh** [comment]
Sounds good @joemsak. Thanks!
