### ISSUE TITLE
Improve location form

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1586]
Convert to a vue component

Have it auto-filled with IP-based location result

Show the user a list of results if their input yields multiple Geocoder results

User confirms correct location

This same component will be used in several places:

* Registration wizard
* My account -> change location
* RA / Admin -> Change a user's location
* Create a team -> set location
* Team -> change location
* RA / Admin -> change a team's location
* ??? others?

**Comment by joemsak** [comment]
@Allicolyer 

Adding or changing your location should now be easier, as the system will give people a list of options if their input produces multiple results

Also, new people will have their (non-identifying) location already guessed due to their IP address, so please try signing up as a new person.

Try this chrome extension to fake your IP to another location while signing up
https://chrome.google.com/webstore/detail/anonymox/icpklikeghomkemdellmmkoifgfbakio?hl=en

Please also try different location inputs of various troublesome spots such as Catalonia, Hong Kong, and Palestine.

This form should work as a:

Student changing their own location
Student changing their team's location
Mentor changing their own location
Mentor changing their team's location
Judge changing their own location
Admin changing anyone's location
Admin changing any team's location

This form will be included as a step in the updated registration wizard which is still in progress, so that people have a chance to confirm the location we guessed from their IP address

**Comment by Allicolyer** [comment]
@ophelieh could you QA this?

**Comment by ophelieh** [comment]
Hi @Allicolyer & @joemsak it all works great! 

The only thing I noticed is when I tried to change locations for participants and teams as an admin, I have to click on "Confirm" twice otherwise nothing happens.

**Comment by joemsak** [comment]
Thanks @ophelieh I will be actually be working on improving that button as part of the registration wizard work, since the same component needs to be usable during sign up and needs to "confirm" to another context

**Comment by Allicolyer** [comment]
@joemsak I am having issues what that chrome extension. I cannot access any websites when it is on.

**Comment by Allicolyer** [comment]
@joemsak I cannot get the form to ever give me a list of best matches, even when I am entering vague information into the form.

**Comment by joemsak** [comment]
@Allicolyer I have been looking around for a solution to setting up an IP proxy to test different locations and coming up empty handed. We'll just have to ask other staff in various locations to visit QA and sign up a new user and verify they got their location set by default 

As for the vague info can you give me examples of input you tried, what you expected, and what you got? It would actually speed up the QA feedback process a bit if you could keep in mind to do that in general. Thanks!

**Comment by joemsak** [comment]
Just an extra note that if other staff test on QA: if they have visited QA before it would be better if they do it in an incognito browser to avoid any potential issues with the cookie history (this is a friendlier alternative to just clearing all your cookies which would also work. it's also possible to remove only the cookies of a specific site but would require more involved instruction)

Our users will be fine because this is a brand new cookie not yet introduced to production

Thanks!

**Comment by kmorton2017** [comment]
my location was set by default to Colorado when Im in SF. (used Google Chrome) I will try doing incognito browser. 

![uploads/77ae37cf-a61a-4d36-91b2-cb422453cd0e/Screen Shot 2018-08-15 at 11.51.15 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F77ae37cf-a61a-4d36-91b2-cb422453cd0e%2FScreen+Shot+2018-08-15+at+11.51.15+AM.png)

**Comment by kmorton2017** [comment]
On the incognito browser, I faced the same issue where it was automatically set to Colorado. In this case I tried setting my location to Jerusalem which is part of both Palestine and Israel. It registered as Irsael. 


![uploads/b9fe0244-6051-4c29-8382-f80eeb844857/no prompting.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb9fe0244-6051-4c29-8382-f80eeb844857%2Fno+prompting.gif)

**Comment by Allicolyer** [comment]
Thank you @kmorton2017 !

**Comment by kmorton2017** [comment]
I reproduced the location error with student account katie+s6@iridescentlearning.org

1) My location was showing up as San Francisco, CA during the registration process. 
2) I created my location as Washington (city) District of Columbia (state/province). 
3) I confirmed my location and proceeded through registration. 
4) I created a team--Wildcats.
5) My team location was showing up as San Francisco. 
6) I double checked my student location and it never changed to Washington D.C. (even though I confirmed it as DC during registration). 
7) I changed it again to Washington D.C. 
8) My team location never reflected these changes and stayed San Francisco.  I am the only member on this team.

**Comment by joemsak** [comment]
okay @kmorton2017 these steps are perfect thank you!

step 8 is technically expected current behavior of the system, but the results of 1-6 are not expected

thank you again

**Comment by joemsak** [comment]
so so sooooo close on this, just passing tests after lots of code fixes!!!

**Comment by joemsak** [comment]
@kmorton2017 you may be able to try this again in 20 min

**Comment by kmorton2017** [comment]
can we reword this? It says: please choose the correct territory. Since Israel is a country I think we should just say "please choose the correct location." 


![uploads/94c5270c-e1cb-4a3e-8485-66c5a25722d3/Screen Shot 2018-08-28 at 2.58.28 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F94c5270c-e1cb-4a3e-8485-66c5a25722d3%2FScreen+Shot+2018-08-28+at+2.58.28+PM.png)

**Comment by kmorton2017** [comment]
just saw that the wizard card was closed so wasn't sure where to leave some feedback! 

it looks like the character limit was not counting for the mentor personal summary. It never changed from zero.

looks like the bug with the location and team location was fixed and they are both displaying as my confirmed location. yay

i invited a student to join a team. when i opened the invitation as the student, it says "you are on the team: Null Team" is it supposed to say that?

uploads/39046c0c-dd85-46cf-b2c5-c5646db20b45/Screen Shot 2018-09-07 at 4.07.57 PM.png

**Comment by joemsak** [comment]
character counter bug has a card and may now be fixed
NullTeam is going to become another car

Is this one closed then?

@Allicolyer @kmorton2017 thanks!

**Comment by kmorton2017** [comment]
somethingn odd happened when i was going through my location. 

I tried to change my location to Tel Aviv.
When I filled it out and confirmed, it did not update my location.

![uploads/463f4f3a-8232-411a-8f6b-697e609dbd57/Screen Shot 2018-09-07 at 3.59.57 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F463f4f3a-8232-411a-8f6b-697e609dbd57%2FScreen+Shot+2018-09-07+at+3.59.57+PM.png)

**Comment by joemsak** [comment]
hi again @kmorton2017 thank you so much for your diligent QA. we have indeed found that some of the logic was a bit twisted in the code, preventing a save. we finally wrote some more confident tests around the behavior and are ready for you to QA once again

**Comment by kmorton2017** [comment]
my student account is Lama Hussein. Her location is confirmed as Gaza, Palestine. I went to "my team" and location. Her team location is showing up as San Francisco. When I tried to change it, it won't let me. I keep pressing the "next" button but nothing happens.

**Comment by joemsak** [comment]
@kmorton2017 you should find this ready to test again this afternoon, for the team pages

**Comment by kmorton2017** [comment]
looks like this bug is resolved. i was able to do the following successfully:

1) change participant location 
2) change team location 

I do have a question about this page though. Is there a reason why students who sign up in Israel are always prompted with this? also can we please change the copy to say "please select the correct location" instead of territory? 
![uploads/b974ad17-121d-4f50-9867-ef574c0cfb6f/Screen Shot 2018-09-24 at 9.54.45 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb974ad17-121d-4f50-9867-ef574c0cfb6f%2FScreen+Shot+2018-09-24+at+9.54.45+AM.png)

**Comment by joemsak** [comment]
I have set the logic so that every "Israel" result gives the user a choice,
since "Palestine" will never come automatically from the map results

It says "territory" because they are choosing the correct country between
the two radio buttons, and we decided as a team that territory is the most
neutral word instead of "country" or "region"

I have asked @adrichey to help adjust the form so that choosing between
Israel and Palestine happens after performing a search, and not while the
user types. Also remember the form will already be filled in when people
use this page, not typing in the information manually unless the guess is
wrong.

**Comment by kmorton2017** [comment]
thanks for explaining more! so complicated :( 

yeah country/territory is the most appropriate when initially signing up and remains correct.
 but if its asking you to choose between a territory or country like on this specific page, can we say "please choose the correct location?" 

what will happen when alan changes the form? sorry maybe we can just touch base on the sprint because im not understanding well.

**Comment by joemsak** [comment]
I really feel like we are hyper focusing on a language issue that isn't a
high priority stacked against other issues we need to have ready by EOD
tomorrow

I was saying that the change from a text field to two radio buttons should
not happen when the user types in "Israel" themselves, and that I would
prefer the form only provides that choice if "Israel" came back from search
results. But again, even this is not a high priority use-case when stacked
up against other issues that need to be done by EOD tomorrow

Can we call this card good enough for Oct 1?

**Comment by kmorton2017** [comment]
that's totally fine. dont mean to pull us into the weeds and recognize that there are higher priority things to focus on. it's good enough.

**Comment by Allicolyer** [comment]
Thanks @kmorton2017!

**Comment by joemsak** [comment]
@kmorton2017 thank you for your flexibility as we approach our go-live date :)

We could certainly create 2 new cards based on your remaining issues here for prioritizing and scheduling in a future sprint

However, I think before deciding on the priority, that we need to decide as a team how we want to handle Defect Priority in general. For a short explanation of terms, Defect Priority is about setting clear policies for prioritizing bugs based on severity and user impact. I linked an article for more info in the qa slack channel. Thanks again!

**Comment by Allicolyer** [comment]
I will close out this card for now. Further issues about location can be added to the "to discuss" column
