### ISSUE TITLE
Returning students and mentors should see scores from previous seasons

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1590]

**Comment by stenington** [comment]
Adding some notes from a discussion: What we could start thinking about is having some way to "archive" a summary of the teams' scores at the end of one season, and making that summary available to them as they go on to the next season. 

The difficulty with doing something more robust is that as we tweak things year to year, we would start having to maintain a lot of legacy code for the system to be able to display past years. But if we export a summary to some static format (like a pdf or some relatively straightforward text or html format) then all we have to maintain is a way to link a team to their past season summaries, which is a little easier.
