### ISSUE TITLE
Students who converted to mentors should see scores and certificates from 2018

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1594]
Students who convert to mentors still want to see their scores and certificates from when they were students. Then they won't need to contact us to get those things.

**Comment by stenington** [comment]
I assume when a student becomes a mentor under the same account, the mentor screens take over and the student loses access to things they saw as a student. This card I think is saying that some aspects of the stuff they saw as a student should be preserved?
