### ISSUE TITLE
Three part wizard onboarding UI

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1614]
Three part UI for mentors students and judges

Part 1: Having an account
Part 2: Onboarding your account
Part 3: Team Building
Part 4: CTA for what to do next

Joe, Alan and Ruby will have a meeting after WP to discuss.

**Comment by joemsak** [comment]
Hey @Allicolyer I'd like to close this card in favor of us working together to find the smaller cards in QA to cover the smaller specific details

What do you think?

Thanks!

**Comment by joemsak** [comment]
@Allicolyer I think in the spirit of shutting down vague cards and the fact we closed the other one too, in favor of finding bugs for new cards, I'm going to put this card to rest. Thanks!
