### ISSUE TITLE
XSorting student’s mentor search based on when they were last active on the site

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1618]
Sorting search based on when someone was last active on the site. Most active mentors will show up closer to the top. 

Students will be able to see when mentors were last active.

**Comment by Allicolyer** [comment]
We would ideally like to have this ready by January

**Comment by hellafitz** [comment]
@bagomer how interested in this are you? It's an idea from long ago but it relates to mentor search.

**Comment by bagomer** [comment]
It sounds helpful, but I would rank it pretty low on my interest scale
