### ISSUE TITLE
Send mentor welcome email from "mailer@"

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1623]
When a mentor signs up, the mentor welcome email is from Monica, who is leaving at end of August. Will need updated copy.

cc @Allicolyer for next sprint meeting

**Comment by Allicolyer** [comment]
thanks joe!

**Comment by Allicolyer** [comment]
We are in the progress of updating the copy.

@kmorton2017 can you tell us who the mentor welcome email should come "from" this season? Perhaps just "support@" or "info@"?

**Comment by joemsak** [comment]
@kmorton2017 @Allicolyer if it's not going to be personalized then it will be our standard `mailer@` that all other email comes from, which has an auto-responder set up, in case they reply to these emails, explaining how to use our system emails (which often have stylized buttons to click to take action) and how to contact support

**Comment by Allicolyer** [comment]
I think that's okay. What do you think @kmorton2017 ?

**Comment by kmorton2017** [comment]
it will not be personalized. it should be the standard mailer@ address and their contact is the support@address

**Comment by joemsak** [comment]
okay @kmorton2017 and @Allicolyer it's no problem thank you

Also the content of the email is referencing her as well. Do you have a copy of that or do you need the latest version?

**Comment by kmorton2017** [comment]
alli gave us the copy of the emails. i have started tracking changes on the doc for all copy in emails.  i think we can close this card (as long as update it to @mailer ) because it is related to #1647.
