### ISSUE TITLE
Outdated Copy

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1629]
This error page shows outdated links to curriculum. We should fix these and maybe look for other error pages with outdated info.

![uploads/0b429502-c5ef-4c92-b260-c792c23c4f08/Screen Shot 2018-08-21 at 11.05.15 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0b429502-c5ef-4c92-b260-c792c23c4f08%2FScreen+Shot+2018-08-21+at+11.05.15+AM.png)

**Comment by Allicolyer** [comment]
Outdated information sign up page as well -- says October 18th should be October 1st

**Comment by Allicolyer** [comment]
@joemsak could you fix this. 

1. Please remove the Technovatoin Challenge Primer. Change "2017 Technovation Curriculum" to just say "Technovation Curriculum". You can keep the same link.

**Comment by Allicolyer** [comment]
Hi @joemsak -- how do I navigate to the 504 error page?

**Comment by joemsak** [comment]
Oh sorry @Allicolyer I assumed you must have had a way to see that page already

https://technovation-qa.herokuapp.com/server_error.html

**Comment by Allicolyer** [comment]
Thanks Joe!

Since it says "here are some links", could you add the technovation blog underneath the curriculum?

https://technovationchallenge.org/blog/

Thanks!

**Comment by joemsak** [comment]
@Allicolyer will be there soon just trying to fix test failures on the QA deploy, it's finally deploying, check in 10 minutes
