### ISSUE TITLE
Admin View: Connect the team submission to the team page

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1634]
Make it easy to find the team submission by linking it on the team page. 

After this passes QA we will decide if we would also like to see the submission progress on the team page or if linking the team submission is enough.

**Comment by joemsak** [comment]
hey @Allicolyer I'm gonna have to ask that we trade this card out of this sprint in order to do whatever work we will decide on today for the mentor training situation. All the other cards should be good to go on QA now (except email copy, but we will still do that too) Thanks!

**Comment by joemsak** [comment]
@Allicolyer no worries, the sprint still had enough room for this card, picking it up now

**Comment by amyiridescent** [comment]
I am not a 100% certain how to QA this or what this exactly was trying to solve but this is what I did. 

As admin, I went to teams, I picked a team, and on their team page, I do see the submission progress bar under "debugging information". When I click on the name of the app, I can see the full submissions. 

![uploads/7a1a13fe-adef-4433-a899-70f5798cdaeb/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7a1a13fe-adef-4433-a899-70f5798cdaeb%2Fimage.png)

I think this is what this ticket is aiming to do. But I am not sure if we want this information under "debugging information". Do RAs have ability to see this and also edit team's submissions?

**Comment by joemsak** [comment]
@amyiridescent the scope of this card was to connect it to the admin page with the link and progress - if you're concerned about whether an RA can see it or edit submissions, you should log in on QA as an RA and investigate that. Then, if you want something changed, you must submit a new feature request

**Comment by ophelieh** [comment]
Looks good as an admin and RA.
