### ISSUE TITLE
Need RA introduction on student & mentor dashboard

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1639]
Acceptance:

- If an RA is present in a student or mentor's region, their program introduction appears as a dropdown item in the top left corner

- If no RA is present, or the RA has not entered an introduction, the student/mentor will see the default dashboard title with the survey link (survey link must be configured by the admin)

- The RA may now specify a Program Name, otherwise their own name will appear on the dashboard. Technovation recommends that RAs fill in the program name

- If there are 2 or more RAs in the same region, the student/mentor will see the introduction for the geographically closest RA

**Comment by kmorton2017** [comment]
confirm that as a mentor i see the name of my RA (if they did not put in a program name) 
Once the name of the program was updated, I saw Technovation Palestine. 

I suggest that instead of "program name" you put "chapter name" 

Some RA's may just write "technovation."

**Comment by joemsak** [comment]
@kmorton2017 Thanks Katie, we should take possible confusion points like this and ensure @ophelieh can incorporate them into some RA training materials and webinars

**Comment by Allicolyer** [comment]
I think this looks good.
