### ISSUE TITLE
XAdmins deleting a specific profile type

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1641]
Throughout the season we may come into cases where a participant needs to be deleted who has different profiles. For example, an RA may become inactive but wants to remain involved as a mentor. Currently, admins can only "delete" a participant. It would be nice to be able to delete a specific profile type.

**Comment by Allicolyer** [comment]
Hey @kmorton2017 I am going to add this as a "wishlist feature".

**Comment by kmorton2017** [comment]
Sure no problem.
