### ISSUE TITLE
Admins need to update survey link 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1646]
By October 1st, staff needs to update the survey link. We are currently still linking to the post survey.

**Comment by Allicolyer** [comment]
@amyiridescent and @madhavitechnovation this is a reminder to do this. Please let me know if you need a reminder for how to update the survey.

**Comment by madhavitechnovation** [comment]
@Allicolyer assessment team will work on the questions and we will update this. Quick question: in addition to survey monkey questionnaire, is it possible to have 4-5 pop-up questions spread through the season? We are trying to see if we can get more responses by spreading out some critical questions on the platform.

**Comment by Allicolyer** [comment]
@madhavitechnovation I think that is a feature that is in the icebox. Let's bring it up to work on it next sprint.

**Comment by kmorton2017** [comment]
we will not have the survey link be ready by oct. 1st. is it possible to disable it until the pre-survey links are ready to go live? (i think thats an admin capability right?)

**Comment by joemsak** [comment]
I have removed the existing survey link settings for now (yes @kmorton2017 this is something an admin can do, but i did it just now anyway)

**Comment by joemsak** [comment]
Any action left for this card?

**Comment by adrichey** [comment]
Just following up since it has been about a week. Is there anything left to do for this card?

**Comment by amyiridescent** [comment]
@kmorton2017 Do we have the final survey links and has that been passed onto dev team? thx

**Comment by joemsak** [comment]
Dev team doesn't need the links, staff can enter the information themselves

**Comment by Allicolyer** [comment]
Katie and I are doing this tomorrow.

**Comment by Allicolyer** [comment]
@joemsak it looks like the staff is going to need some help setting up some variables for Survey Monkey. Do you have some time to talk next week about this?

**Comment by joemsak** [comment]
Absolutely! Just send a meeting invite to me at work@joesak.com and I am sure I will be available
