### ISSUE TITLE
Add point count to code checklist

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1652]
Add parentheses to code checklist to see how many points you currently have if you already started it and saved your work.

**Comment by adrichey** [comment]
![uploads/94bde08d-51cb-418f-a29a-d273c36d378f/Screen Shot 2018-09-10 at 4.07.00 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F94bde08d-51cb-418f-a29a-d273c36d378f%2FScreen+Shot+2018-09-10+at+4.07.00+PM.png)

@Allicolyer Are you referring to this link? I have the work done on a branch, but I want to confirm that this is the only spot we need the count before I create a pull request this morning. Thanks!

**Comment by Allicolyer** [comment]
Hey Alan! I think that works.

**Comment by kmorton2017** [comment]
Cool I can see the parantheses now.
