### ISSUE TITLE
Admin: link student and mentor's old certificates on their profile view (older than 2018)

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1653]
Add a way for admins to access certificates older than 2018 for mentors and students.

**Comment by kmorton2017** [comment]
am i supposed to be able to click this? as an admin I went to Allison Old Student and tried to click on "Open your Certificate'

**Comment by adrichey** [comment]
This has been addressed in pull request #1711. Once that pull request is deployed to QA, I will move this ticket to the test column.

**Comment by ophelieh** [comment]
Seems to be working, but it's taking a long time to generate so I can't tell if it opens the right certificate. Will need to be retested. 
![uploads/7bf2eba8-39e2-4e36-bf5b-eef6f51d2138/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7bf2eba8-39e2-4e36-bf5b-eef6f51d2138%2Fimage.png)

**Comment by joemsak** [comment]
@ophelieh the QA server has had 3 or more deploys back to back, it's probably just been rebooting right in that moment.

**Comment by joemsak** [comment]
The link works now, but for past teams, the certificate is wrong

https://technovation-qa.herokuapp.com/admin/participants/11#/

I propose that supporting certificates before 2018 season can wait and is not critical for Oct 1

**Comment by joemsak** [comment]
@Allicolyer is this card still something you want to prioritize, or could it wait until users actually make requests for older certificates? I think that supporting older certificates will require collaboration with the wider staff due to needing assets for the old seasons. Thank you!
