### ISSUE TITLE
Are the terms of use good to go?

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1654]
@amyiridescent for your information, these are the <a href="http://iridescentlearning.org/terms-of-use/"> terms of use </a> that are currently linked. Do they need to be updated? If so, this should be taken care of by Oct. 1st.

**Comment by amyiridescent** [comment]
Yeap this is still good to use. Lawyers are reviewing them and if there are updates, we will update this on the wordpress site so we don't have to change the link on the platform site.
