### ISSUE TITLE
Change the development platform options

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1656]
Change development platform options to:

1. App Inventor
2. Thunkable
3. Java
4. Swift or XCode
5. Android Studio
6. Other

**Comment by adrichey** [comment]
@Allicolyer I am not sold on having both "Java" and "Java and Android studio" because it makes Java a little redundant. Perhaps we could leave it off entirely? Or if they really get confused without it being there, maybe we could put some text about IDEs somewhere. Or just put Android Studio in parentheses next to Java. It's a tough call.

**Comment by Allicolyer** [comment]
So I guess the problem is that people think "android studio" is a programming language. Here are the most popular app development platforms from 2018:

App Inventor 2: 1698
Other - Thunkable: 90
Java: 83
Swift or XCode: 63
Other - Android Studio: 42

Both Android Studio and Thunkable were write-ins last year. You can also write C++ code in Android studio. Maybe it make sense to give people the ability to pick more than 1?

As for "App Inventor 2" I think option 2 makes sense - to rename it "App Inventor".

**Comment by joemsak** [comment]
Thank you, Alli! Whatever you ultimately design on Android Studio, renaming it won't be an issue, so I'll put this work up to QA now for your review. Cheers!

**Comment by kmorton2017** [comment]
just checking to see if there was a decision made @allicolyer

**Comment by Allicolyer** [comment]
@kmorton2017 I have not :(

**Comment by Allicolyer** [comment]
@joemsak Let's go with Alan's suggestions:

1. App Inventor
2. Thunkable
3. Android Studio or Java
4. Swift or XCode
5. Other

**Comment by joemsak** [comment]
@Allicolyer okay, just keep in mind your *existing* QA data may not be correct once I make this change, but it will not affect production data (because I am now only changing the new options that you'd had a chance to use on QA, but hasn't been live yet)

**Comment by joemsak** [comment]
@Allicolyer this should be ready again

**Comment by Allicolyer** [comment]
looks good! thanks Joe
