### ISSUE TITLE
Collect Thunkable account information

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1657]
Mirror what we have for App Inventor:

1. Ask people for their Thunkable email 
2. Ask people for the name of their project

**Comment by joemsak** [comment]
@Allicolyer I seem to recall this isn't finalized yet. Is that right? If so, should we have this in backlog until it's ready and been discussed in a sprint planning?

**Comment by Allicolyer** [comment]
Hey Joe! I will have an answer later today.

**Comment by joemsak** [comment]
This should not pose a problem for development

**Comment by Allicolyer** [comment]
After talking to Thunable -- to uniquely identify projects, they need

1. Ask people for their Thunkable email
2. Ask people for the shareable URL: https://x.thunkable.com/copy/47d800b3aa47590210ad662249e63dd4

**Comment by Allicolyer** [comment]
no it is not the same for Thunkable. We also do not need the project name for Thunkable. Just the email account and the shareable link.

**Comment by joemsak** [comment]
Thanks @Allicolyer -- could I get you to make sure your most up to date acceptance criteria is in the top-most original description/comment of the card? That's why I was asking about information that we're not actually collecting. Thanks!

**Comment by joemsak** [comment]
and still asking: Would you like a card to validate the App inventor project name not to have spaces?

**Comment by joemsak** [comment]
Also this should be ready for QA

**Comment by Allicolyer** [comment]
@joemsak that would be a nice to have

**Comment by joemsak** [comment]
@Allicolyer I made a card in discussion https://huboard.com/Iridescent-CM/technovation-app#/issues/363696502

**Comment by Allicolyer** [comment]
it looks good. Thanks Joe.
