### ISSUE TITLE
Validation for App Inventor project names

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1658]
Do not allow spaces in the App Inventor project names.
![uploads/3f766377-3a90-4a69-8bec-b844d77d98ca/Screen Shot 2018-09-04 at 10.55.50 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3f766377-3a90-4a69-8bec-b844d77d98ca%2FScreen+Shot+2018-09-04+at+10.55.50+AM.png)

Thunkable allows spaces, App Inventor does not. This will allow for easier data cleaning at the end of the season.

**Comment by joemsak** [comment]
Ready on QA today!

**Comment by kmorton2017** [comment]
It did not allow me to have spaces. I was however allowed to use symbols.

**Comment by joemsak** [comment]
@kmorton2017 whups, you are right, I overlooked that requirement in the screenshots

**Comment by kmorton2017** [comment]
yep looks good. i'm unable to use symbols now. can you add "no spaces" in the little red box that pops up when it's incorrect?

**Comment by joemsak** [comment]
the validation says "can only have letters, numbers, and underscores"

I think that should be enough for someone if they try to use a space since
spaces aren't in the list of what's allowed

**Comment by ophelieh** [comment]
Looks good! I tested with all kinds of characters and spaces.
