### ISSUE TITLE
Business Plan -- copy update

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1659]
Change Text: "If your team has put one together, that is awesome! Hold on to it for your own records and be extremely proud!"

"If your team has put one together, that is awesome! Hold onto your work and incorporate your business plan in your pitch presentation.” 

@kmorton2017 I like this text update -- however this might be confusing if the team is not going to an RPE and does not have to make a pitch presentation. Here is my suggestion:

"If your team has put one together, that is awesome! Hold onto your work and incorporate it <strike>your business plan </strike> into your pitch <strike>presentation</strike>.” 

Final: 
If your team has put one together, that is awesome! Hold onto your work and incorporate it into your pitch.

**Comment by kmorton2017** [comment]
I like that idea--good point. Thanks for suggesting that change.

**Comment by Allicolyer** [comment]
This looks good. Thanks @adrichey !
