### ISSUE TITLE
Update copy around presentation slides

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1660]
Update copy around presentation slides -- 
“Check with your Regional Ambassador when these are due”

@kmorton2017 can you confirm that you want this to be the final wording?

**Comment by Allicolyer** [comment]
Additionally would you like to change this copy?

“Your team is not set to attend a live regional pitch event. In March and April, Regional Ambassadors will invite teams to pitch at a live event.If your team is invited, then you will be required to upload your pitch presentation slides here. (pitching at a live regional event is not required)”

**Comment by kmorton2017** [comment]
See my notes below:
Update copy around presentation slides -- “Contact your Regional Ambassador for the due date.”

“Your team is not set to attend a live Regional Pitch Event. In the spring, Regional Ambassadors will invite teams to pitch at a live event. If you attend, then you will be required to upload your pitch presentation slides here. (Pitching at a live Regional Pitch Event is not required.)”

**Comment by adrichey** [comment]
@kmorton2017 and @Allicolyer is this ready to begin being worked on? I want to make sure before I pick it up. Thanks!

**Comment by Allicolyer** [comment]
@adrichey yes -- use Katie's edits

**Comment by adrichey** [comment]
@kmorton2017 @Allicolyer I have made the updates in a feature branch, but I don't want to merge that work into QA until I get approval on where the text "Contact your Regional Ambassador for the due date." should appear. Right now, there is no text in that section to replace, so I want to make sure I am adding it to the right spot. I can get that text in very quickly once I have a response on this. Thanks!

**Comment by kmorton2017** [comment]
Hi Alan, 

When you click on "presentation slides" on the submission list, you should see this list. 

"Your team is not set to attend a live Regional Pitch Event. In the spring, Regional Ambassadors will invite teams to pitch at a live event. If you attend, then you will be required to upload your pitch presentation slides here.  Contact your Regional Ambassador for the due date. (Pitching at a live Regional Pitch Event is not required.)”

**Comment by adrichey** [comment]
Thank you @kmorton2017! I will get that updated today.

**Comment by kmorton2017** [comment]
Looks good @adrichey
