### ISSUE TITLE
Fix Source Code Redirect

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1661]
After uploading source code, the site redirects users out of the submission page and back to their dashboards.

**Comment by adrichey** [comment]
Pull request to address this issue has been merged into QA branch. Once the code goes through CircleCI and deploys to QA, I will move this to test.

**Comment by Allicolyer** [comment]
Hey @adrichey I still got redirected to the dashboard after updating my source code

**Comment by adrichey** [comment]
@Allicolyer It looks like the code was not deployed to QA properly. It works locally, but I have confirmed that QA is still broken. I will need to talk to @joemsak about this when he returns on Tuesday (9/11/2018). I am not familiar with our deployment pipeline and I don't feel comfortable attempting a deployment until he returns and can walk me through it.

**Comment by Allicolyer** [comment]
okay thanks Alan!

**Comment by adrichey** [comment]
@Allicolyer It must have been a hiccup as the code is deployed and working this morning. You can test this again whenever you have time.

**Comment by Allicolyer** [comment]
this works well now. Thanks Alan!
