### ISSUE TITLE
Difficulties changing location during sign up

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1663]
There have been difficulties changing the location during sign up. Here is when the bug occurred:

1. Sign up a new user
2. Change the location to something different than the location that has auto populated
3. Finish signing up
4. Check profile details to see that the location has not been changed from the original location

**Comment by joemsak** [comment]
@Allicolyer Hey Alli! This issue is 20 days old, could you verify if this card is still relevant? Thanks!
