### ISSUE TITLE
Next button does not work on this screen

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1666]
![uploads/8943382a-de13-43c5-8e6f-89f5a5d1d4b7/Screen Shot 2018-08-29 at 5.25.22 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8943382a-de13-43c5-8e6f-89f5a5d1d4b7%2FScreen+Shot+2018-08-29+at+5.25.22+PM.png)

**Comment by joemsak** [comment]
This button should now appear disabled after you're signed up, and will indicate when it has saved your changes (it saves when you stop typing for half a second)

**Comment by joemsak** [comment]
@Allicolyer this has been updated now

**Comment by kmorton2017** [comment]
confirmed that i do not see next button.

**Comment by joemsak** [comment]
@kmorton2017 thanks, however there is more behavior here. you should see a friendly message while making any changes in this form, that your changes are saved.

**Comment by joemsak** [comment]
also please confirm that the registration UI still does show a "Next" button (when you  are signing up)

**Comment by kmorton2017** [comment]
yeah i see a message that says " your changes have been saved."

**Comment by kmorton2017** [comment]
everything seems fine with the Next button working

**Comment by Allicolyer** [comment]
thanks @kmorton2017 !
