### ISSUE TITLE
Character counter not working when filling in Mentor Bio / Personal Summary

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1667]
This is relevant to PR #1649

**Comment by adrichey** [comment]
Work for this has been completed in the following PR: https://github.com/Iridescent-CM/technovation-app/pull/1675

Once that has been reviewed, merged, and deployed, I will move this card into QA ready.

**Comment by adrichey** [comment]
This card is ready for QA. @joemsak may want to mark this as closed since he will be able to test this using his wizard conversion work.

**Comment by joemsak** [comment]
@adrichey I'm not able to verify this on my local machine

**Comment by kmorton2017** [comment]
this looks fine now.

**Comment by Allicolyer** [comment]
thank you @kmorton2017!
