### ISSUE TITLE
Location form remembers an old location of my computer 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1669]
Location from remembers an old location of my computer even upon refreshing. @joemsak Is this the expected behavior?

![uploads/d70b0033-3d60-4c7d-b273-fcfaa85a2cea/Screen Shot 2018-09-06 at 9.46.34 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd70b0033-3d60-4c7d-b273-fcfaa85a2cea%2FScreen+Shot+2018-09-06+at+9.46.34+AM.png)

**Comment by joemsak** [comment]
hey @Allicolyer how long ago were you there and had you visited QA on that computer when you were there?

**Comment by Allicolyer** [comment]
August 27th

**Comment by Allicolyer** [comment]
and yes

**Comment by joemsak** [comment]
Okay so it's completely "by design" that it works this way, which is to say, our system does not account for the person starting the signup in one location and finishing it in a significantly different one

is that alright?

thank you Alli!

**Comment by joemsak** [comment]
hmmm, shoot, let me clarify a bit more.

the system stored your location in a cookie in NY and it is still using that cookie to figure out where you are

HOWEVER

i just realized, it should detect a new IP and try to make a new location... now I'm not sure anymore, haha. sorry. thanks alli, we can look into it more if necessary though it may be a very on the edge case

**Comment by joemsak** [comment]
@Allicolyer it's possible today's update fixes this issue, just make sure you don't delete your cookies and you can continue to test it until it's fixed (if that becomes a to-do card)

**Comment by Allicolyer** [comment]
@joemsak it updated my location today! Also this was not a case when I started sign up in one location and finished it in another. I was making a brand new account.

However it seems to be cleared up today so I will close this card!
