### ISSUE TITLE
Issues with my email when creating an account

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1670]
The form doesn't like my email today. I know the iridescent emails are unique but some mentors may also have unique domain names:

![uploads/a2445fd2-f115-4dd6-95a9-ff9c0c8dc7f3/Screen Shot 2018-09-06 at 9.51.30 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa2445fd2-f115-4dd6-95a9-ff9c0c8dc7f3%2FScreen+Shot+2018-09-06+at+9.51.30+AM.png)

![uploads/560619e4-c1a5-41cd-8f06-c30184f41625/Screen Shot 2018-09-06 at 9.51.41 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F560619e4-c1a5-41cd-8f06-c30184f41625%2FScreen+Shot+2018-09-06+at+9.51.41+AM.png)

![uploads/476ee1e6-2bd9-451e-96be-787057ec7822/Screen Shot 2018-09-06 at 9.51.52 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F476ee1e6-2bd9-451e-96be-787057ec7822%2FScreen+Shot+2018-09-06+at+9.51.52+AM.png)

**Comment by Allicolyer** [comment]
@adrichey was there any change that would have sparked this?

**Comment by adrichey** [comment]
@Allicolyer Nothing should have changed to invalidate those as far as I know. Tagging @joemsak for his visibility since the email validation comes from the back-end side of things and he might have more insight.

**Comment by Allicolyer** [comment]
It seems to work a little better in incognito:

![uploads/f9c3b6df-d316-4d71-b132-dde668cfe16d/Screen Shot 2018-09-06 at 10.58.45 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff9c3b6df-d316-4d71-b132-dde668cfe16d%2FScreen+Shot+2018-09-06+at+10.58.45+AM.png)

However, this is a real hotmail email address that I own.

![uploads/6b866671-44f3-4cdb-bd82-a154e1dae737/Screen Shot 2018-09-06 at 10.57.43 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6b866671-44f3-4cdb-bd82-a154e1dae737%2FScreen+Shot+2018-09-06+at+10.57.43+AM.png)

**Comment by Allicolyer** [comment]
Okay I did get it to work in the regular browser for my mentor account. I'm not sure what the issue was, but this is something we should definitely note for customer support in a few weeks.

![uploads/64b4dad8-f188-4332-b6b2-e37bbf7361a5/Screen Shot 2018-09-06 at 11.00.56 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F64b4dad8-f188-4332-b6b2-e37bbf7361a5%2FScreen+Shot+2018-09-06+at+11.00.56+AM.png)

**Comment by joemsak** [comment]
@Allicolyer mailgun seems to have recently made some changes to their validation API response which may be breaking the form right now (great....) I think it may be fixed in a coming release to QA, let me get back to you

**Comment by joemsak** [comment]
@Allicolyer I just saw that `allisjunk@hotmail.com` works fine on my local, so QA should update soon, will notify asap

**Comment by Allicolyer** [comment]
it seems to be cleared up today. Thanks Joe!
