### ISSUE TITLE
Student dashboard lists "submission guidelines" twice

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1679]
![uploads/2c5fa8c9-b056-4fef-a479-574701b81308/Screen Shot 2018-09-12 at 10.36.35 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2c5fa8c9-b056-4fef-a479-574701b81308%2FScreen+Shot+2018-09-12+at+10.36.35+AM.png)

**Comment by kmorton2017** [comment]
i don't see this anymore. it's only listed once.

**Comment by Allicolyer** [comment]
thanks Katie!
