### ISSUE TITLE
Bug when trying to join a team

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1688]
1. I am logged in as alli+m5@iridescentlearning.org. 
2. I am trying to join team "Hollaback Girls"
3. I get an error each time and am unable to join the team

![uploads/154fd74f-5d35-40fa-82dc-a2f9e470c107/team-join-error.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F154fd74f-5d35-40fa-82dc-a2f9e470c107%2Fteam-join-error.gif)

**Comment by Allicolyer** [comment]
@adrichey do you know what may have caused this?

**Comment by adrichey** [comment]
Honestly, not sure @Allicolyer. I can try to take a look at your account and the settings and try to reproduce it. This is a new one to me. I will test that and get back to you.

**Comment by adrichey** [comment]
@Allicolyer It looks like I get a different message, when I attempt this with the QA database locally. I am going to dig around and see why this is happening. I am not sure if this logic is intended or not and need to do more research.

@joemsak Does this look familiar off the top of your head?

![screen shot 2018-09-19 at 3 02 21 pm 2](https://user-images.githubusercontent.com/1534554/45778149-6fc42880-bc1d-11e8-9534-3444c9290c45.png)

**Comment by joemsak** [comment]
@adrichey @Allicolyer Hey hey I saw this error come in to my email and I fixed it, hence Alan's version of the screen :)

**Comment by joemsak** [comment]
oh wait, sorry  never mind! well that is why alan sees that screen but the problem isn't fixed!

**Comment by adrichey** [comment]
@Allicolyer This appears to be working as intended. I am not sure why you got that "Uh, oh" message before, but now you are getting the "It appears that the person who sent this request may have deleted it" message, which is correct. If you log in as an admin and search for the team, you can see that the request for that user appears as deleted, so that request text should be correct.

**Comment by joemsak** [comment]
@adrichey she got the error because the template for the "deleted" case didn't exist, hence my comments here :)

**Comment by adrichey** [comment]
Ah, got it. Thanks @joemsak! Didn't see your response until refreshing the page.

**Comment by Allicolyer** [comment]
Hey @joemsak and @adrichey I am trying to QA this but I am getting this message:


![uploads/5f8dd486-f512-4c1f-9110-d759a5ac0996/Screen Shot 2018-09-25 at 9.30.51 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5f8dd486-f512-4c1f-9110-d759a5ac0996%2FScreen+Shot+2018-09-25+at+9.30.51+AM.png)

However, I checked the season toggles, and team building is on:

![uploads/8639acef-2de7-475c-b582-30de732c610b/Screen Shot 2018-09-25 at 9.31.08 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8639acef-2de7-475c-b582-30de732c610b%2FScreen+Shot+2018-09-25+at+9.31.08+AM.png)

**Comment by adrichey** [comment]
I will work on that bug as I address the copy in the student sections @Allicolyer.

**Comment by Allicolyer** [comment]
Account used: alli+m5@iridescentlearning.org

**Comment by Allicolyer** [comment]
This is not happening with other accounts so I don't think it's a huge bug -- maybe some weird stuff happened to this account

**Comment by Allicolyer** [comment]
great thanks Joe!

**Comment by joemsak** [comment]
@kmorton2017 I checked the team debugging info as an admin and confirm that this team has disabled their visibility to mentors searching for teams

**Comment by joemsak** [comment]
@kmorton2017 so if you could either test this card with another team or enable that team's visibility to mentors, that would be the next step to push this card through QA

**Comment by kmorton2017** [comment]
you were right about the team Hong Kong's Awesome Team. 

However, Fun Times Team IS enabled for mentors to find it. I am unable to see it as available teams near me.

**Comment by joemsak** [comment]
Okay thanks katie, could I get you to test the scope of this card though?
Try to make a join request with a team that you can find. If this is
another bug, it's another card

**Comment by kmorton2017** [comment]
yes i was able to request to join Hong Kong's Awesome Team. As a student I approved this join request.

**Comment by joemsak** [comment]
okay and as a mentor could you verify that you could still go find more  teams after sending out a join request?

**Comment by kmorton2017** [comment]
i could still go and find more teams "anywhere." 

I was not able to find more teams "near me" although Fun Times is located in my region.

**Comment by joemsak** [comment]
That's fine, as long as you had the button to go there, that was alli's
last bug
