### ISSUE TITLE
Thunkable no longer allows .aia file downloads

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1690]
Thunkable only makes source code shareable through a link -- you can no longer download the .aia file, only the .apk. 

Most of our judges test out source code by running .aia files in App Inventor. It is much easier for them to  do this than to download the .apk onto an emulator or a real phone.

Since we are moving away from exclusively App Inventor this year and are opening ourselves up to more development platforms, should we start asking people to upload .apk files and showing judges how to properly test .apk files?

@madhavitechnovation and @joemsak do you have any thoughts?

**Comment by joemsak** [comment]
We would want to provide clear and easy instructions. App Inventor's instructions are kinda sub par. I'm open it though, of course.
