### ISSUE TITLE
Build friendly landing page

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1693]
Ruby has delivered final design and assets for the landing page

**Comment by kmorton2017** [comment]
looks great!

**Comment by joemsak** [comment]
@Allicolyer no problem, easily fixable with our existing reflex css :)

**Comment by joemsak** [comment]
@Allicolyer this is ready again

**Comment by kmorton2017** [comment]
looks good on mobile

**Comment by Allicolyer** [comment]
yes looks great now
