### ISSUE TITLE
Admin: link judge's old certificates on their profile view

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1694]
As an admin
I can access the link to a judge's past certificates starting in 2018 on their profile

**Comment by Allicolyer** [comment]
@joemsak would it be possible to tackle this card?

**Comment by joemsak** [comment]
@Allicolyer can you explain more for me, what you mean by "tackle this card"? Do you mean to do work on it, or to write AC? Maybe both? I can't work on this card until it has clear and defined AC. Thank you!

**Comment by Allicolyer** [comment]
@joemsak. Okay I wrote out some AC. Would it be possible to do some work on this card?

**Comment by Allicolyer** [comment]
sure

**Comment by joemsak** [comment]
Okay, thank you Alli!
