### ISSUE TITLE
Location form not redirecting properly in admin

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1695]
To reproduce:
1. Log in as admin
2. Browse to Participants section in admin dashboard
3. Click View on a participant in the table
4. Click Edit Location
5. Fill out the location and click Next
6. Attempt to click Confirm

Expected behavior:
In step 6 above, you should be redirected back to the participant view page.

Actual Behavior:
Confirm click doesn't redirect and appears to be broken. Location is saved, but it is not apparent.

**Comment by adrichey** [comment]
Will be addressed once pull request #1697 is merged.

**Comment by Allicolyer** [comment]
This is working now. Thanks Alan.
