### ISSUE TITLE
Allow Thunkable URLs for source code

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1696]
Here is an examples of a Thunkable URLs

https://x.thunkable.com/copy/47d800b3aa47590210ad662249e63dd4

Acceptance Criteria:
- When the submission development platform is selected as Thunkable:
-- Collect the thunkable information (already done)
-- Auto-fill the source code with the thunkable URL

- When the submission development platform isn't selected yet, but students/mentors go to set their source code:
-- Display selection for development platform, so that if they choose Thunkable, the source code upload becomes the URL field

**Comment by joemsak** [comment]
@Allicolyer this actually should be automatically done as part of the development platform step, so we should discuss the user workflow we expect in this case. Thanks!

**Comment by Allicolyer** [comment]
Hey Joe,

Could we still have it in two places? It could auto-populate or something but for the sake of the Oct 1st deadline I would like to keep the workflow the same.

I am worried because some Australian teams have used Thunkable and want to submit on Oct 1st. We could ask them to wait but it would be nice to just have everything ready.

**Comment by joemsak** [comment]
Sure, yeah, that's an option I was thinking of: just mark the source code as done and filled in

**Comment by Allicolyer** [comment]
sure!

**Comment by Allicolyer** [comment]
Hey @joemsak I'm worried we making this too complicated. Tell me if this is easier:

What if we don't collect the source code in the development platform section. We can just collected the email address and then use what they put into source code as the URL. If they enter an .apk or something weird we will just have to accept that we lost that datapoint.

**Comment by joemsak** [comment]
@Allicolyer can you help me understand this part?

"and then use what they put into source code as the URL"

The thing is, to enable the URL we have to change the field from a file upload field to a text field. We have to know they're using Thunkable first to enable the switch to this other field type. That is why I am proposing that, if they navigate to the source code piece, and have not selected a development platform, we present them with that selection. Then if they pick Thunkable, the file upload field goes away and the URL field will fill in both options at once.

**Comment by Allicolyer** [comment]
ah okay I understand now. I think that your acceptance criteria works then

**Comment by joemsak** [comment]
okay, @Allicolyer, thank you for thinking it through with me! let me know if you have any other thoughts

**Comment by joemsak** [comment]
@Allicolyer Another quick note for you, I will be adding validation to the thunkable URL field to match the example you gave

**Comment by kmorton2017** [comment]
hi all! i am a little confused on the back and forth on this card and the other one. this is what happened when i  chose thunkable. tell me if this is the expected behavior:

1) went to development platform and selected Thunkable
2) was prompted to put in the email address of my thunkable account
3) was prompted to put my shareable URL 
4) source code section was automatically populated with my URL. 

on a different note, if i changed my development platform to Java or Swift, and  then re-selected Thunkable as my field, it saved my previous URL. this is fine with me. i was just letting you know if you select thunkable as a platform, then choose a different one, then re-select thunkable it will have your link ready.

**Comment by Allicolyer** [comment]
Hey Joe,

This seems to be work well.

Here's one thing I found odd is that

1. I click on source code without first having a development platform. 
2. I fill out of development platform.
3. I get redirected to the "code" section. I would have guess it would next prompt me to enter my source code.



![uploads/85f7e6ef-600a-4262-80b9-476af60ec83b/2018-09-26 17_57_15.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F85f7e6ef-600a-4262-80b9-476af60ec83b%2F2018-09-26+17_57_15.gif)

**Comment by joemsak** [comment]
Don't know if this is such a bad thing, from the GIF, it seems like it was
easy enough to continue forward on your own

It's at least not a show-stopping issue. With two days of development left
I'd like us all to focus on show-stopping and critical, high priority issues

**Comment by joemsak** [comment]
@kmorton2017 everything you described is expected behavior, thanks!

**Comment by Allicolyer** [comment]
@kmorton2017 thanks!

**Comment by Allicolyer** [comment]
I think we can close this since we have card #1709
