### ISSUE TITLE
Add helper copy for student dashboard sections

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1700]
On the student dashboard for a freshly created student, if I browse to “Submit your project”, “Judging”, or “Scores & Feedback” in the dashboard, I get a blank white screen with no information. This differs from the mentor dashboard, where it has information about what needs to be completed in order to unlock those sections.

*Expected behavior*
If I browse to “Submit your project”, “Judging”, or “Scores & Feedback” in the dashboard, I get text that mirrors that of the mentor dashboard for those sections informing the user that additional time or steps are needed to unlock that section.

*Actual behavior*
if I browse to “Submit your project”, “Judging”, or “Scores & Feedback” in the dashboard, I get a blank white screen with no information.

For the copy text, we can just use what is already in place for mentors.

**Comment by Allicolyer** [comment]
I see the copy

**Comment by Allicolyer** [comment]
this looks good! Thanks Alan.
