### ISSUE TITLE
Submissions Development Platform: Validate "App Inventor" project name not to have spaces

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1702]
The development platform option for App Inventor prompts the user to enter their email and project name

Validate the project name field so that it cannot save if it has spaces in it (App Inventor project names cannot contain spaces)

**Comment by Allicolyer** [comment]
hey Joe! why is this a discussion?

**Comment by joemsak** [comment]
Just leaving it up to you for scheduling it

**Comment by joemsak** [comment]
Dupe of #1658, should close
