### ISSUE TITLE
Student Dashboard: show 'Submit Your Project' as complete when the submission is complete

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1704]
When a student visits their dashboard, they see the menu on the right side
The menu had indicators for which steps of the season they have completed
The "Submit Your Project" step is not changing to a completed status
Change the menu item to display the green checkmark when the submission is complete

Note: mentors are a more complex step because they could have multiple submissions, so that should be a separate card

**Comment by kmorton2017** [comment]
Originally, when my submission was complete it was showing as a black checkmark on my browser. I submitted my project for judging.

HOWEVER, 

I  deleted deliverables, changed deliverables (for example removed link to demo video, added new link, deleted screenshots, added screenshots) and navigated away from the "my submission page." Although my submission is now complete (after removing/adding items) my "Submit Your Project" step on my dashboard menu is blank. There should be a check mark.

**Comment by joemsak** [comment]
@kmorton2017 the black check mark is normal, it is the 'active' state of the menu, meaning you are on that page

Also, your submission is not complete if you changed it and then did not re-submit it
