### ISSUE TITLE
Submission Dates--Copy

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1705]
On the "My Team's Submission Page" the italicized text says" even after submitting, you will be able to make changes until April 25th."

The date should be April 23rd.

**Comment by adrichey** [comment]
@kmorton2017 This should automatically change over once we change the season deadline date on the back-end. @joemsak Can we flip that switch now?

**Comment by joemsak** [comment]
@adrichey actually this particular date is hardcoded :)

**Comment by madhavitechnovation** [comment]
so @joemsak how will we make this change?

**Comment by joemsak** [comment]
@madhavitechnovation you don't. i did. it's done, please verify that the dates are correct

**Comment by madhavitechnovation** [comment]
Thanks @joemsak it looks good. I checked with Katie and she is fine not to have 2019. So this card is all good.
