### ISSUE TITLE
20/21 Registration form required fields could benefit from validation [5?,?,?]

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1707]
While working on #1691, @kmorton2017 brought up the following points:

"Also, another thing to consider: i got confused as a mentor signing up because i thought i filled in all the required fields on the basic profile page. however i mistakenly did not fill out "as a mentor you may call me...." and it took me a while to figure out why i couldn't press next. is there a way to draw attention to the user when they forget a required field?"

We should discuss this and begin creating cards for it if it becomes a priority. I see this as being a multi-step process.

1. We mark the fields that are required with an asterisk or something to denote that they are required.
2. We rework the next button to not be disabled, but rather trigger validation. If everything is valid, we move to the next step, if not, the user stays in the current step. If invalid, the fields they didn't fill in are highlighted to be completed.

Once we have a discussion around these cards, we can create cards for the work and get acceptance criteria created. So no work is necessary on this yet in my opinion. I just didn't want this request to get lost in the shuffle. Thanks! :)

**Comment by Allicolyer** [comment]
Hey @adrichey I am going to move this into the icebox and give it the label wishlist. This seems like something that would be good to revisit during the registration sprint next season.

**Comment by adrichey** [comment]
Sounds good.

**Comment by hellafitz** [comment]
@rsgonzal notes that we have an existing "*" UI pattern on CM that could be used as reference.

**Comment by hellafitz** [comment]
We think this is a Vue issue and a can o' worms. Hold off for now.
