### ISSUE TITLE
Update thunkable URL validation: the subdomain is always "x"

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1709]
Example:

https://x.thunkable.com/copy/47d800b3aa47590210ad662249e63dd4

Only URLS that look like that should work, the only part that should be different is the last part after the last "/"

**Comment by kmorton2017** [comment]
the example URL did not work in the field "WHAT IS THE SHAREABLE URL OF YOUR THUNKABLE PROJECT?"

it shows as invalid.

**Comment by joemsak** [comment]
@kmorton2017 what happened with your original comment saying it was invalid? I ran the URL through my tests and they passed

**Comment by kmorton2017** [comment]
it was doing a weird thing at first where i would copy/paste the link and another https:// was added on in front (making it two https://) 

i wasn't sure if it was my error with copy/pasting too fast. i have been unable to replicate so i think it was my own error.

**Comment by joemsak** [comment]
@kmorton2017 okay thanks for clarifying - i have updated the test for this URL and the validation (and the https thing) and it passed, so yeah I'm not sure either
