### ISSUE TITLE
Screenshot uploader needs to validate type of files

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1714]
As a student
When I try to upload a screenshot
And I try to upload a file type that is not .gif, .jpg, .jpeg, or .png
Then the site should show me a friendly validation message
And the files should not be uploading (or uploaded)

As a mentor
When I try to upload a screenshot
And I try to upload a file type that is not .gif, .jpg, .jpeg, or .png
Then the site should show me a friendly validation message
And the files should not be uploading (or uploaded)

**Comment by amyiridescent** [comment]
I get the warning sign. As student & mentor 

![uploads/ce9b3970-22dd-4604-941f-1650249d366e/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fce9b3970-22dd-4604-941f-1650249d366e%2Fimage.png)
