### ISSUE TITLE
Setup QA Data for RA Multiple Region exploration

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1715]
THIS CARD IS BEING TESTED BY @ophelieh as part of #1716 - if there is any issue with the RA accounts themselves, she should report them here

The QA database should be set with two RA accounts:

One RA account is based in Maryland, Virginia, and Washington DC
The second RA account is based in Hong Kong and China

Joe to provide login details on card #1716

**Comment by kmorton2017** [comment]
i would like to change this if possible for one RA account based in Maryland, Virginia and Washington DC. instead of Massachussetts/Rhode Island. 

This is a more complicated use case but occurred in real life.

**Comment by amyiridescent** [comment]
@kmorton2017 you might need to QA this one. :)

**Comment by joemsak** [comment]
Actually it's @ophelie

**Comment by joemsak** [comment]
hi @ophelieh you mentioned you are working on #1716 - is it safe to close this card then, as I assume the logins are working as expected? Thank you!

**Comment by Allicolyer** [comment]
Hey @ophelieh is there anything left to do here?

**Comment by ophelieh** [comment]
Yes, so far I was only able to explore participants. I still have Teams, Judges, Submissions. I am hoping to work on this a little this afternoon and tomorrow.

**Comment by joemsak** [comment]
Okay, it sounds like as far as this card is concerned, you can login with the accounts provided. The card for exploratory QA is #1716 @Allicolyer I think you can feel free to close this one, but do let me know if there is something else I haven't considered or explained clearly enough. Thank you!
