### ISSUE TITLE
Exploratatory testing on QA for multiple-region RAs

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1716]
Note: you will need to sign up various students/mentors/judges, set up teams, and create submissions to test the data in multiple locations

As an RA in 3 regions: Maryland, DC, and Virginia
login/password: ophelie+ra-maryland@iridescentlearning.org

Please test the search functionalities of:
Participants, Teams, Judges, Submissions
Report what does not work as you expect it to
Please test that the Events page shows events in both of your regions

As an RA in 2 regions: Hong Kong & China
login/password: ophelie+ra-hongkong@iridescentlearning.org

Please test the search functionalities of:
Participants, Teams, Judges, Submissions
Report what does not work as you expect it to
Please test that the Events page shows events in both of your regions

**Comment by joemsak** [comment]
@kmorton2017 @ophelieh the login info has been set up and posted in this card - remember this is EXPLORATORY QA, so you are reporting what we will work on in the next sprint - please use Alli's templates from previous exploratory QA - it should be easy to find in your email or google drive

**Comment by joemsak** [comment]
Hey @ophelieh since you're active on huboard lately, I just want to remind you of this card, where you can log in as the RAs and check if you can search / filter the data of multiple regions as you might expect to be able to (reminder: You will need to set up some participant / team / submission data in the regions you're testing) -- and to let you know I fully expect you to find some issues here and there, and you can actually keep all of your notes for the next sprint meeting, as this card is simply meant to explore QA in prep for the next batch of work. Thank you!

**Comment by ophelieh** [comment]
@joemsak I started working on that yesterday, but then emails took over. I will make sure to get it done as soon as possible, hopefully, tomorrow!

**Comment by joemsak** [comment]
@ophelieh you know what, I bet creating / listing Events will need some work for sure, so be sure to explore that - i think event locations are set automatically by the RA's primary region and I suppose we'll need to support RAs with secondary regions to select the region for the event

**Comment by ophelieh** [comment]
Hi Joe,

For the RA in 3 regions (Maryland, DC, Virginia):

- I created a student in Washington DC - Cathy McFluffy
I cannot see that student on the RA dashboard. 
On the student dashboard, I see the RA from Los Angeles - Neil Degrasse Tyson.

- I created a student in Richmond, Virginia - Anna Taboo
I cannot see that student on the RA dashboard. 
On the student dashboard, I see the RA from Los Angeles - Neil Degrasse Tyson.

- I created a student in Baltimore, MD - Saddie Maldy
I can see her on the RA dashboard 
On the mentor dashboard, I see the RA from that region

- I created a mentor in Millersville, Maryland - Han Solo
I can see him on the RA dashboard 
On the mentor dashboard, I see the RA from that region

So far, it seems I can only see students and mentors in my state. Unfortunately, that's all I have time for today, but I will work on it more Monday.

**Comment by Allicolyer** [comment]
@joemsak can you set up these accounts?

**Comment by joemsak** [comment]
sure can, will notify you and @ophelieh when it is done

**Comment by joemsak** [comment]
Hmm, it seems @ophelieh was able to create the data she needs to do her testing. Is that accurate, Ophelie? Is there any specific data you would prefer that I create for you? (Teams, Submissions, Events, something else that I'm missing?)

also, I think there's been a miscommunication about the goal of this card. It is for exploratory testing to create more cards later in a future sprint. I did recommend that a template similar to the one Alli created in the past for submissions be used for recording all the findings, but I think it's fine if the team just wants to use Ophelie's comments as the basis for the next sprint planning. I just want to reiterate: the feedback given here will not be worked on in this card, and we need to create new cards for each discreet, related portion of Ophelie's feedback.

If there is something about this that I need to explain better, please do not hesitate to ask me.

Thanks!

**Comment by stenington** [comment]
This card seems pretty stale to me. It sounds like exploratory QA was done and there would be work to do to support multiple-region RAs. Can someone write up a feature request with details on how that would need to work? @ophelieh @kmorton2017 @Allicolyer

**Comment by ophelieh** [comment]
I'm happy to take a stab at it this week @stenington.

**Comment by adrichey** [comment]
@Allicolyer, @ophelieh and @kmorton2017 Do any of you know what remains for this ticket? It looks like we might need to create new tickets based on the exploratory QA done previously, so I want to make sure that we have created those so that we can get this ticket closed. Thanks!

**Comment by ophelieh** [comment]
So far I only tested the participants' aspect, which showed that we have some work to do. 

I haven't tested Teams, Judges, Events, or Submissions. I could plan on doing that Monday morning.

**Comment by Allicolyer** [comment]
Conclusion:

This needs a lot more work. It would require complicating the location form and trying to get more information out of it. Whenever we are trying to match a student and an RA we are using latitude and longitude of the closest RA. 

This would require an entire re-write of how we handle RA assignments. We probably don't want to work on this mid-season since it might affect everyone. 

We would prefer to focus on getting the location form stable first, before doing anything major like this.

**Comment by ophelieh** [comment]
I agree and I wouldn't want the location to get messed up again. I'll add it in the notes for next season.
