### ISSUE TITLE
Discuss submissions charts

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1717]
Discuss submissions charts to be implemented at a later date for the admin dashboard.

Known charts that we need:
- Top 10 countries in terms of number registered girls
- Top 10 countries number of completed submissions in terms of countries

We will discuss other potential charts and admin filters that will help with data analysis.

Acceptance criteria:
Alan and Katie to discuss these charts and create any specific cards with concrete acceptance criteria for each of them and put them in the Icebox.

**Comment by kmorton2017** [comment]
Admin dashboard: 
In addition to mentor and student pie graphs, could we have a pie graph with the total # of complete vs. incomplete # of submissions? This could be modeled after the student pie graph "with parental consent vs. no parental consent." 

Top countries tab: 
Submissions per country should show top 10 countries. Each country's bar should show the total # of submissions with a break down of complete and incomplete. (similar to how the current top countries' graph shows students, mentors and judge breakdown. The complete/incomplete submissions for each country could be clickable. 
 
Student Registrations per country should show the top 10 countries. Each country's bar should show the total # of student registrations with a break down of parental consent vs. no parental consent. Those with parental consent and those without parental consent could be clickable and take you to the participant page.

**Comment by joemsak** [comment]
@Allicolyer could I get you to do a quick test for me? Just @ me here so I can make sure the correct email is receiving notifications. Thank you!

**Comment by joemsak** [comment]
@Allicolyer scratch that, I got a notification in the correct inbox in another ticket. Thank you!

**Comment by Allicolyer** [comment]
okay great! Thanks @joemsak
