### ISSUE TITLE
Source code file validation

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1718]
As a student

Make sure your development platform is not set to Thunkable
When I try to upload source code
And I try to upload a file type that is not .aia or .zip or .apk 
Then the site should show me a friendly validation message
And the files should not be uploading (or uploaded)

If I upload .aia or .zip or .apk  it will work

As a mentor -- 

Make sure your development platform is not set to Thunkable
When I try to upload a screenshot
And I try to upload a file type that is not .aia or .zip or .aok
Then the site should show me a friendly validation message
And the files should not be uploading (or uploaded)

If I upload .aia or .zip or .apk  it will work

**Comment by ophelieh** [comment]
As a mentor and student, when choosing a file to upload I am unable to see any file that's not .aia or .zip or .apk.
