### ISSUE TITLE
Find Scenarios where RA/Admin search is difficult 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1723]
Admin/RA search for submissions is very difficult

-- Please document pain points here

**Comment by Allicolyer** [comment]
@ophelieh  and @kmorton2017 would you mind if I schedule some time for us to do this?

**Comment by ophelieh** [comment]
Not at all! We have some availability Thursday, Friday or Monday.

**Comment by kmorton2017** [comment]
Found a sample pain point. I was on the Submissions page looking for a team called "The Pinks and Purples"

I could not remember the full name so I searched purple but appeared in the search.
