### ISSUE TITLE
Submissions Demo Video: Add a review step

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1725]
As a student
With a submission
When I go to add my Demo Video URL (youtube, vimeo,  or youku)
And I click Save
I should see an intermediary review step
With the video embedded in the page
And a message imploring me to check that the video is working
So that I can verify if it is working properly
And I should be able to click "back" and re-do it
Or click "Save" and move on

As a mentor
With a submission
When I go to add my Demo Video URL (youtube, vimeo,  or youku)
And I click Save
I should see an intermediary review step
With the video embedded in the page
And a message imploring me to check that the video is working
So that I can verify if it is working properly
And I should be able to click "back" and re-do it
Or click "Save" and move on

**Comment by ophelieh** [comment]
As a mentor - Works great. 
As a student - I uploaded a vimeo link but omitted a couple of numbers. It did not show me the big red error message as it happened to be the link to another video. It did show me that the video was set to private. I then changed the numbers again and this time it told me "video does not exist". 

Either way, it works. :)
