### ISSUE TITLE
Submissions Pitch Video: Add a review step

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1726]
As a student
With a submission
When I go to add my Pitch Video URL (youtube, vimeo, or youku)
And I click Save
I should see an intermediary review step
With the video embedded in the page
And a message imploring me to check that the video is working
So that I can verify if it is working properly
And I should be able to click "back" and re-do it
Or click "Save" and move on

As a mentor
With a submission
When I go to add my Pitch Video URL (youtube, vimeo, or youku)
And I click Save
I should see an intermediary review step
With the video embedded in the page
And a message imploring me to check that the video is working
So that I can verify if it is working properly
And I should be able to click "back" and re-do it
Or click "Save" and move on

**Comment by ophelieh** [comment]
That's awesome! :)

**Comment by kmorton2017** [comment]
Update copy (minor edits) for both pitch video and demo video submission: 

"Review the area above this message. If there is a problem with viewing your video, you should GO BACK and fix the pitch video link."

**Comment by joemsak** [comment]
@kmorton2017 the text should now be updated

**Comment by amyiridescent** [comment]
Text is updated. ("P" in pitch video is upper case but that is fine. :) )
