### ISSUE TITLE
Add submit button to dashboard

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1727]
As a student
With a submission
Once I complete my submission
But I have not submitted it for judging
When I go to my dashboard
I see a button to submit my submission for judging
When I click the button 
I am taken to the review submission page

As a mentor
With at least one team 
With a submission
Once I complete my submission
But I have not submitted it for judging
When I go to my dashboard
I see a button to submit that team's submission for judging
When I click the button 
I am taken to the review submission page

**Comment by ophelieh** [comment]
As a student - submit button works as expected
As a mentor - submit button works as expected

** Note when I was testing this card, the Submission pages were not working properly (see bug #1775).

**Comment by joemsak** [comment]
Okay, @ophelieh thank you so very much for taking the time to report the bug, and using the template! Once we have decided together as a team on a defect priority matrix (here is just one example, you are welcome to find others, https://www.softwaretestinghelp.com/how-to-set-defect-priority-and-severity-with-defect-triage-process/) we will be able to prioritize it accordingly. You may close the ticket if you approve it as passing the acceptance criteria. Thank you!
