### ISSUE TITLE
Uploading an unsupported business plan file for submissions is difficult to remove

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1728]
As a student
With a submission
When I go to upload a business plan, but use an unsupported file
The broken file should be easy to remove without anything in the way of the remove link

As a mentor
With a submission
When I go to upload a business plan, but use an unsupported file
The broken file should be easy to remove without anything in the way of the remove link

**Comment by amyiridescent** [comment]
@joemsak I don't know how to QA this. So I am trying to replace the .docx file already uploaded under business plan to test this. 

![uploads/75c3f77c-fc57-411d-98a5-6ae0ec58a1b8/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F75c3f77c-fc57-411d-98a5-6ae0ec58a1b8%2Fimage.png)

But the file uploader will only show me doc and pdf files as options to be uploaded. So I can not try to upload a movie or image file or anything else to see if this work. Any thoughts on how I can test this?

**Comment by amyiridescent** [comment]
Ok actually, I tried to drag and drop a ppt file and it worked. 

![uploads/b85bdf6f-4a69-4cfa-a542-b9cceb5b236b/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb85bdf6f-4a69-4cfa-a542-b9cceb5b236b%2Fimage.png)

I can easily remove the wrong file format by hitting remove file.
