### ISSUE TITLE
RA participant search bug

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1732]
Original report by @kmorton2017 on slack: 

I am an RA in Jersualem, Palestine. There are 2 students and a team based in Bethlehem. Neither the participants nor the team or submission is showing up on my dashboard

---

Acceptance Criteria:

As an approved RA

When I search participants
I should get all results for participants in my same region

When I search teams
I should get all results for teams in my same region

For an RA in the US, my region is my state
For all other RAs, my region is my country

**Comment by joemsak** [comment]
@kmorton2017 @ophelieh I have run through several tests on this issue and I wrote an automatic update for the existing data so that it fixes the issue. I hope you come to the same conclusion!

**Comment by kmorton2017** [comment]
please test using katie+ra2@iridescentlearning.org 

You should see the following mentors:
Bart Simpson
Rawan
Hamzeh

Students:
Lama Hussein
Miriam Al-Qrinawi

Teams:
Kitaab

Submissions:
Kitaab

**Comment by joemsak** [comment]
@kmorton2017 bart simpson is located in missouri, I cannot confirm that it is expected for this mentor to appear in palestine participant results

**Comment by kmorton2017** [comment]
edited out bart simpson. he is located in missouri. sorry

**Comment by adrichey** [comment]
I had changed Bart Simpson previously when testing another location form ticket earlier in the sprint. Sorry about that. I had to test in a non-local environment to confirm code was deployed as I wanted to test networking logs.

**Comment by ophelieh** [comment]
Logged in as katie+ra2@iridescentlearning.org - I am able to see all mentors, students, teams and submissions

**Comment by ophelieh** [comment]
When creating a new student in Palestine, I can see the RA Milo and when logging in as the RA, I can see the new student. Anything else I should be testing out for this card?

**Comment by adrichey** [comment]
I believe that should cover it @ophelieh. Can @kmorton2017 or @joemsak confirm?

**Comment by kmorton2017** [comment]
no that's it.
