### ISSUE TITLE
Configure the end of the mentor ebook site to take the mentor to the "completed training" URL

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1734]
As a mentor
When I visit the ebook training
And I make it to the final slide
Then I should see a link instructing me to click through
So that my training step will be marked as completed

As a Technovation staff member (most likely Amy)
I should get this URL from technovation dev team (most likely joe)

As a staff member (amy)
I should give the public starting URL for the training site to Joe

**Comment by amyiridescent** [comment]
Thanks @joemsak I am going to use the TESTING link into presentation now. Can we leave this ticket open until we put in the live link later? Thx.

**Comment by joemsak** [comment]
Wait another 5 to 10 minutes before trying the URL, the code is still
uploading (we usually say deploying) to QA right now

Thanks!
