### ISSUE TITLE
Email input validation is erasing input

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1736]
The email input field in registration is erasing input on slow network connections.

To reproduce:
1. Fill out registration forms until you get to the Sign In step.
2. Type an email address repeated very quickly, erasing and inputting text, watching for characters to disappear.

Expected behavior:
Text typed at whatever speed is not erased from the email input.

Developer note: This is due to a race condition. The Vuex store action is calling an axios endpoint, and the validation logic is doing the same. If the validation call finishes before (after?) the saveEmail commit, then the text has the potential to be erased.

**Comment by adrichey** [comment]
This will most likely need to be tested at a high priority and cherry-picked into production so that people are not running to this while signing up.

**Comment by ophelieh** [comment]
Works great now! Tried typing quickly, slowly and deleting then retyping. No issues. :)

**Comment by amyiridescent** [comment]
@ophelieh If you are happy with this ticket, can you close it? thx
