### ISSUE TITLE
Admin Dashboard bug in top countries chart: country names not displayed

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1738]
As an admin
When I log in to the dashboard
I should be able to see the Top Countries chart
And I should see each bar labeled with the full country name

**Comment by amyiridescent** [comment]
Ok. I am not sure if this is working. On QA, this is what I see under "top countries". 

![uploads/cbd0c6e9-8ec7-40a4-a69e-f04f27d2d483/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fcbd0c6e9-8ec7-40a4-a69e-f04f27d2d483%2Fimage.png)

But when I check the countries of all participants for 2019 season, it does show that there are some from Hong Kong and India registered. Maybe the labels on the columns are incorrect?

**Comment by joemsak** [comment]
@amyiridescent the data was right but the labels were wrong - I ran some more tests and figured out the issue there. It's back on QA today

**Comment by ophelieh** [comment]
Looks great!
