### ISSUE TITLE
XPast Season Filters are not working correctly with the Matched with team filter [20,13,1.54]

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1739]
I am logged in as an admin.

I went to participants--Mentors-->signed consent form
It is only showing 11 accounts
I am only searching 2018 season results. The 2018 filter is on. 

I expected there to be a complete list of 2018 season mentors with signed consent forms appearing (probably 3,000-5,000 results)

**Desktop (please complete the following information):**
 - OS: X El Capitan, Version 10.11.6
 - Browser--Chrome

**Comment by kmorton2017** [comment]
This is a related issue. 

I am logged in as an admin. I went to Participants--Mentors--Season 2018-->Matched with a team. 

Only 10 accounts were found. I expected there to be a complete list of 2018 season mentors matched with teams appearing. 

OS: X El Capitan, Version 10.11.6
Browser--Chrome

**Comment by Allicolyer** [comment]
@adrichey This is still an issue. After playing around with it, I suspect that the "matched with a team" filter finds participants that are matched with teams registered to the 2019 season. 

@kmorton2017 is this something that is very important to fix? Could you give us a sense of the urgency here. Is there any data reporting that will need this filter to work properly?

**Comment by ophelieh** [comment]
@kmorton2017

**Comment by stenington** [comment]
I can confirm that it's reporting mentors matched with "current teams", meaning teams registered in the current season.

**Comment by hellafitz** [comment]
In other words: you can only search for the current year (if you want accurate results).
