### ISSUE TITLE
Mentor dashboard UI: Background check is complete, not required for US mentor who has not submitted

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1740]
Mentor dashboard UI: Background check is shown as complete, and not required for a US mentor who has not submitted one

**To Reproduce**
1. register as a mentor in the US
2. See that the background check is marked complete and says not required at this time

**Expected behavior**
I expected it to say I must submit one, because I am from the US and I haven't done it yet

**Desktop (please complete the following information):**
As an admin, you can debug this info from any account's name on production if you want, mine is "Technovation Staff Test by joe"

**Comment by joemsak** [comment]
@adrichey we dont have defect priority policies yet, but this one seems high enough to patch up, if you think you could return to coding by looking at this one? i'm not 100% sure but I think it should all be getters/store logic. Let me know right away if you need rails/ruby support.

**Comment by adrichey** [comment]
I believe the logic is in the front-end. I will get started on this and let you know if I get caught up somewhere.

**Comment by amyiridescent** [comment]
As a new US mentor, it is telling me the background check is required. 

![uploads/a0824d8e-8434-453b-bc2c-d6d62397ec6e/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa0824d8e-8434-453b-bc2c-d6d62397ec6e%2Fimage.png)

Is this how I should test this ticket? @adrichey

**Comment by amyiridescent** [comment]
![uploads/9a7a222f-1a8e-4f7b-86dd-4221c569f323/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9a7a222f-1a8e-4f7b-86dd-4221c569f323%2Fimage.png)

**Comment by joemsak** [comment]
looks correct @amyiridescent can we close?

**Comment by amyiridescent** [comment]
yes sir.
