### ISSUE TITLE
Dashboard header UI: avatar is showing the old kitten missing placeholder instead of the new default random icons

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1741]
**Describe the bug**
When I visit the dashboard (mentor and student)
My profile picture shows up as the old kittens from 2017
Even though my real avatar is one I uploaded or a randomly assigned icon during sign up

**To Reproduce**
1. Sign up as a new mentor
( not confirmed: if a returning mentor logging in has this bug, or if any students have this bug)

2. look at the header, see a kitten avatar next to your name
3. click on My Profile
4. See that your profile image (also called an avatar) is one of our random icons

**Expected behavior**
I expected to see the random icon or my own uploaded photo as the avatar on the header on my dashboard

**Comment by ophelieh** [comment]
I am in the process of working on this card (I'll finish later today). Just wanted to note that as I am creating a new mentor profile, it is deleting my information if I stop typing (at least in last name). Also, if I don't select a company from the droplist, it doesn't record my company name unless I press enter.

**Comment by ophelieh** [comment]
Right. Let me do that!

**Comment by ophelieh** [comment]
Signed up as a new mentor - random avatar is what I saw next to my name when first logging in and on my profile.

**Comment by joemsak** [comment]
Great! Thank you, @ophelieh! If you could close the cards (as the tester you are permitted to do that) that would be a great final step to the QA task. Cheers!
