### ISSUE TITLE
Mentor training 1556 addendum: ensure it affects 'onboarding' status (scope, etc)

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1742]
Admin/RA feature in AC deleted, doesn't exist

As a student
On a team
When I search for a mentor
The results do not include mentors who have not completed the training
They do include mentors who registered for the season before the training requirement date, 
  even if they didn't complete the training

Test Plan:

1. Tell Joe to set the QA training date to tomorrow (or the future, doesnt matter)

2. Sign up as a mentor and do everything EXCEPT the training (use a memorable name)

    a. tip: sign up outside the US to skip the background check

3. Log out

4-7 deleted, feature doesn't exist

8. Login as the student (student@student.com)
9. Create a team if you are not on one
10. Go to search for mentors
11. Verify that you can find your mentor by name when searching anywhere
12. Log out

13. Tell joe to change the training date to today

14-19 deleted, feature doesn't exist

20. Login as the student (student@student.com)
21. Create a team if you are not on one
22. Go to search for mentors
23. Verify that you cannot find your mentor by name when searching anywhere
24. Log out

25. Log in as the mentor
26. Complete the training
27. Log out

28-30 deleted, feature doesn't exist

31. Log in as the student
32. Go to search for mentors
33. Confirm you can find your account now 
(assuming you did ALL onboarding steps!)

**Comment by amyiridescent** [comment]
On step 8. Where can I filter for onboarded mentors only? I see the option for Judges... but not for mentors. 

![uploads/6dfeac5d-b451-44b0-9858-3ea6dc8fad26/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6dfeac5d-b451-44b0-9858-3ea6dc8fad26%2Fimage.png)

**Comment by amyiridescent** [comment]
YES. All interaction between student and mentor did work for all these steps. (There was a few seconds lag between mentor completing training and student being able to see that mentor but it did work.)

**Comment by amyiridescent** [comment]
@joemsak as long as I don't need to test this as an admin, this ticket is good to go.

**Comment by joemsak** [comment]
ok

**Comment by joemsak** [comment]
okay @amyiridescent thanks please close the cards when they pass QA
