### ISSUE TITLE
Mentor training 1556 addendum: Onboarding status affected by training completion

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1743]
As a mentor
When I have not completed the training
And I registered for the season (signed up, or logged in again from the past - please test both) 
  * on or after the training requirement date

Then I must complete that training
In order to access:

 *  creating a team
 *  joining a team
 *  searching for teams
 *  responding to invites from teams
 *  making join requests (asking to join teams)

If I have registered for the season (signed up, or logging in again from the past - please test both)
 *  before the training requirement date

And I have not completed the training
Then I can still access the items listed above
And I can still take the training if I want to

**Comment by amyiridescent** [comment]
As a new mentor signing up before the training requirement date, I still see the mentor training as an option on the dashboard. And when clicking on the "mentor training" this pops up. 

![uploads/eba97460-5166-4d56-90fb-2d46c7c4966c/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feba97460-5166-4d56-90fb-2d46c7c4966c%2Fimage.png)
And I can still ask to join a team. 

Will test first scenario after I get the training date changed.

**Comment by amyiridescent** [comment]
Ignore earlier comment. It was a bug with background check which is being addressed already. This ticket is good to go.
