### ISSUE TITLE
Mentor Background Check --Foreign Born in the US

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1744]
This is a question from Zendesk that we also got last year: 

"I wanted to submit my data for the background check but I don’t own an SSN number nor US drivers license. I am currently studying in the US and would love to act as a mentor."

What is the best way we can move forward with this?

Should we change use their home country for the background check and mentor on-boarding, and once that is complete, change back to the United States so they can be matched with local teams? Let us know if this feasible from an admin/software point of view.

@adrichey @joemsak

**Comment by Allicolyer** [comment]
@kmorton2017 do you still want to discuss this further?

Here is my input:

I think it would be better for them to put their home country. They can search for teams near where they live using the search filter. It will not work for them to change their country back to the US after onboarding -- the site will ask for a background check again.

**Comment by kmorton2017** [comment]
Got it. That makes sense Alli. It only affects <10 mentors (rough estimate based on those who reach out to Zendesk).
