### ISSUE TITLE
Developers to fix Google form script for Bug Report form

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1746]
Script for bug report form is not working :(

https://gist.github.com/bmcbride/62600e48274961819084

Script: https://script.google.com/a/iridescentlearning.org/macros/d/MbHLZZyxSlQQjRYO9Q814EOvuoh0XTmry/edit?uiv=2&mid=ACjPJvHvhjhUisTn6ejDzK4c_rfDFlZ5QeGbK2mu5PgfCzmhvWmv60DnENW2bO727qoxpyF_lMnwkeFhoOEfb_LHolvVXT9wfFlKWW_ctDifP9WXP6r-QF2I50izKmvKFfr0VnlM2AhuTg

**Comment by adrichey** [comment]
@joemsak Has there been any movement on this at all? I saw that Katie had asked about hooking up a form to post directly to GitHub so things weren't lost. I was wondering if I should take a crack at this as a result.

**Comment by joemsak** [comment]
@adrichey hey thanks for checking into this. no, there hasn't been any movement on it. I was hoping to get some help from you, in fact :) Do you need a screensharing session to get oriented on how it's supposed to work, what I've done so far, and what the errors are? Thanks!

**Comment by adrichey** [comment]
I have my notes from before when we had spoken about this previously @joemsak, so I should be able to poke around with it knowing that information. I will let you know if I run into any hurdles.

**Comment by joemsak** [comment]
Okay thank you Alan! I am here if need be

**Comment by joemsak** [comment]
Oh and by the way I would really love to know what the solution was, if you find it. Thanks!

**Comment by adrichey** [comment]
This has been completed. The following Github issue was created using the Technovation Bug Report Google Form. After I filled out the Google Form, this issue showed up with the `bug` label: https://github.com/Iridescent-CM/technovation-app/issues/1822.

This should now be ready for testing!

@joemsak The fix was basically that you were using the e.values which is a Google Sheets thing, and not a Forms thing. You can view the corrected script by looking at it in the Google Form, and get a feel for the object I am using here: https://developers.google.com/apps-script/guides/triggers/events#form-submit_4.

**Comment by adrichey** [comment]
@Allicolyer Let me know if you need assistance testing!

To test:
1. Go to the Technovation Bug Report Form (https://docs.google.com/forms/d/e/1FAIpQLSfbbAeQrNyf4_xbaOjULkD6MWLhPYxcxBBgS2UqNrD4zz45Eg/viewform) and submit a bug, filling out all fields.
2. Browse to the Technovation Challenge Github Repo issues section and confirm that your bug appears in this list: https://github.com/Iridescent-CM/technovation-app/issues. The title of the issue should match what you put in the "Describe this bug" field on the Google Form.

**Comment by joemsak** [comment]
Wow, awesome! Thank you! Yeah you know what, I did follow instructions that required google sheets, which is no longer true with latest version of google forms. Problem was, people commenting in the gist I found said "just" to use the script as I was trying to use it and that it "worked for them" welp - thank you again!

**Comment by kmorton2017** [comment]
do ophelie and i need to test this card?

**Comment by joemsak** [comment]
For what it's worth, I confirm that the bug I'm working on came directly
from the google form

**Comment by adrichey** [comment]
I think this should be good to go. Since Joe is currently working on an issue that came from the form and confirms it works, I am okay with calling this good.
