### ISSUE TITLE
Mentors take training on dashboard (embedded google slides)

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1750]
As a mentor
I can take the training on the dashboard
And I can complete my training on the final slide

**Comment by ophelieh** [comment]
It seems I get the old training - https://iridescentlearning.atavist.com/technovation-mentor-training. 

Does one of us need to update the link?

**Comment by joemsak** [comment]
You're opening the old training link in the resources menu - we should remove that - try the mentor training link in the team building menu

**Comment by kmorton2017** [comment]
When I got to the end of the training, I pressed "Push this button" and got a "sorry we couldn't find that page" message

**Comment by joemsak** [comment]
@kmorton2017 that is because @amyiridescent didn't update the URL to the testing URL (and now she SHOULD NOT DO THAT anymore because we plan to go live) so just change the host of the URL you went to from the live site to the QA site host

**Comment by joemsak** [comment]
seems like we all agree this is working, and the URL was already tested in another card. @amyiridescent can you confirm that the last slide only has ONE link and it's to the LIVE url?

**Comment by amyiridescent** [comment]
Yes I checked and it should be good.
