### ISSUE TITLE
CSV File add registration date

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1781]
Can we add a field on the CSV file for the participant's registration date and last sign in? This will help eliminate confusion for RA's and admins on newly registered participants and allow admin users to easily keep track of new participants.

@ophelieh @joemsak

**Comment by joemsak** [comment]
Hi @kmorton2017 thank you for your request - have you had a chance to bookmark this link for new feature requests? 

https://github.com/Iridescent-CM/technovation-app/issues/new?template=feature_request.md

Please edit your request, copy this template into it, and fill it out and follow the final instruction. Thank you!
