### ISSUE TITLE
Unable to delete an Admin from admin/admins

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1783]
**Describe the bug**
While on the Admins page (where Admins manage the admin accounts - what a mouthful this issue is) if you go to delete an existing one, the site shows page not found

**To Reproduce**
1. Login as an admin
2. Go to "Admins"
3. Add one if one does not exist
4. Click to delete them
5. See page not found

**Expected behavior**
I expected the page to reload with the account gone from the list, and a message saying it was deleted

**Screenshots**
None

**Desktop (please complete the following information):**
OS X Mojave
Firefox latest

**Smartphone (please complete the following information):**
None

**Deliverable**
- Fix this bug
- Open a PR

**Deployment Steps**
- Do not deploy

**Comment by Allicolyer** [comment]
This bug still exists as of January.

**Comment by Allicolyer** [comment]
I would say this is a pretty low priority. It would be nice to delete admins but it's not super pressing.

**Comment by viviancan** [comment]
tested locally - working. Will rebase and merge to QA

**Comment by rsgonzal** [comment]
This works! Love that I can delete and resend an admin invite.
