### ISSUE TITLE
Convert student to mentor button is not working

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#1784]
**Describe the bug**
As an admin, I try to convert a student to a mentor. It tells me that the student is now a mentor, but the student still shows as a student. Profile doesn't convert. 

**To Reproduce**
1. Go to 'Participant', look up 'Dasha Tabunshchyk' 
2. Click on 'Convert to a mentor' 
3. Click on 'Yes, do it'
4. See message confirming she is now a mentor
5. Go to her profile - she is still a student. 

**Expected behavior**
When clicking 'convert to mentor', the student should become a mentor. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32206421/47089596-cbff7580-d1e6-11e8-917d-313b98122457.png)

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser chrome
 - Version 69.0.3497.100 

**Additional context**
I have tried logging in and out, and tried internet explorer.

**Comment by ophelieh** [comment]
Thank you!!

**Comment by joemsak** [comment]
This is ready now but keep in mind the student must be at least 14 for the button to appear and work

thanks!

**Comment by kmorton2017** [comment]
does this need tested or no because it was a bug?

**Comment by Allicolyer** [comment]
@ophelieh could you test this? Thank you!

**Comment by ophelieh** [comment]
The button works now! :) However, if the student was already in a team, that student still shows in the team as a student. I don't see this case really happening, but wanted to note it here. 


![uploads/9ba69277-d46b-4f73-bdf1-d01cf2563966/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9ba69277-d46b-4f73-bdf1-d01cf2563966%2Fimage.png)


![uploads/efa09fdb-243f-4400-9a02-a10d587af980/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fefa09fdb-243f-4400-9a02-a10d587af980%2Fimage.png)

Thank you!

**Comment by joemsak** [comment]
Okay @ophelieh thank you. If you think a bug should be filed, please let me know

**Comment by Allicolyer** [comment]
Thank you @ophelieh !
