### ISSUE TITLE
Adding CSV file

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1787]
RA's and admins often struggle with determining which participants are new as they track sign ups. The current CSV file does not allow you to view the registration date or last login. Sometimes RA's create their own separate registration process to keep better track of this information which is not ideal. 

Can we add a field on the CSV file for the participant's registration date and last sign in? This will help eliminate confusion for RA's and admins on newly registered participants and allow admin users to easily keep track of new participants.

**Comment by Allicolyer** [comment]
I believe we have discussed these things

- Sign up date does exist.
- Last Login date does not exist, but returning? does.

@kmorton2017 let me know if those two things are good enough here.

**Comment by adrichey** [comment]
Actually, we have a last logged in date in the database, but it only tracks when they sign in, and most of our users stay logged in for extremely long periods of time, so it may still not be particularly helpful.

**Comment by Allicolyer** [comment]
@adrichey thanks for the update. 

 @kmorton2017 can you let us know if this is enough to solve your problem?

**Comment by kmorton2017** [comment]
sign up date is sufficient. the inactivity logs on ra dashboards are very helpful.
