### ISSUE TITLE
Filtering for Mentors

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1788]
I would like to have the ability to go to the participants page for mentors and filter by:

Mentor Industry (ie parent, teacher, etc.)
Mentor Company

This will allow us to easily see how many educators we have, mentors from a specific company etc for data collection. 
An alternative is adding the mentor industry as a column to easily sort information (since company is already available for columns).

**Comment by ophelieh** [comment]
@Allicolyer @adrichey As an add on to that (might need a different ticket or might already be a ticket), would it be possible to add some sort of disclaimer under Company when mentors register so they know to press 'Enter' to validate their company if it isn't in the drop-down list? 

Something like: If your company is not part of the options, type the name of your company then press 'Enter'"

Thank you and let me know if I need to create a different ticket

**Comment by adrichey** [comment]
@ophelieh I think we should create another ticket for that second piece since it is in a different section of the UI and not really related to this work. I will create that now and link to this issue.

**Comment by adrichey** [comment]
Created #1921 to address your addition @ophelieh.

**Comment by Allicolyer** [comment]
@kmorton2017 since admins can already filter mentors by their company, I am changing this ticket to reflect the request that admins want a way to filter by Mentor Industry (ie parent, teacher, etc.).

**Comment by Allicolyer** [comment]
Actually created a new ticket #1954
