### ISSUE TITLE
Students cannot create accounts using @qq.com emails

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1790]
Students cannot create accounts with @qq.com emails. This will affect approx. 200 accounts, or around 1% of our users.

Acceptance criteria
As a student
I can create an account with a @qq.com email

![uploads/8279e7a0-237b-4dce-991a-23910f011e60/unnamed.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8279e7a0-237b-4dce-991a-23910f011e60%2Funnamed.png)

**Comment by joemsak** [comment]
hi @Allicolyer can you please send me a short list of some actual emails that  people are trying to validate? Is the one in the screenshot a real one?

It seems that plenty of people are signing up with a qq.com email address, and I can *sometimes* get the one in your screenshot to work and sometimes not. I would just like a confirmed short list of real emails that actually should work so that I can test them on mailgun's validation test page

Pending that, we may have to escalate this issue directly to mailgun support

**Comment by Allicolyer** [comment]
Hey Joe 

Here are some real emails:

1455872389@qq.com
szjuliet@qq.com
972447885@qq.com
2672824978@qq.com
1285423999@qq.com
pengmengyangmmwy@qq.com

**Comment by joemsak** [comment]
Excellent! Thank you! I will follow up with you as soon as I can with my findings and the next steps being taken.

**Comment by joemsak** [comment]
@Allicolyer @amyiridescent I ran a few of these addresses through Mailgun's testing form and they come back as not valid. So, I have created a support ticket on your behalf with mailgun: https://app.mailgun.com/app/support/869604

**Comment by joemsak** [comment]
Oops, I should have added: Please let me know if you'd like me to deal with this issue in any other way in the meantime. For example, I mentioned that we could bypass the validation and allow anything @qq.com - I would recommend not to take this route, and to wait on official support from mailgun, but I will defer the decision to you. Thank you!

**Comment by Allicolyer** [comment]
Okay we can wait for support.Thanks Joe!

**Comment by joemsak** [comment]
Hi everyone - in the interest of keeping you all informed, I am updating this ticket to say that I am still waiting for a response from Mailgun.

**Comment by Allicolyer** [comment]
Thanks @joemsak !

**Comment by joemsak** [comment]
Good morning @Allicolyer and @amyiridescent - Mailgun has verified there is a bug on their side and they have created a report for their dev team to fix it, but cannot give an ETA on when we can expect that to be fixed.

Let me know what is the next plan of action that you expect from me, and I will do so. Thank you!

**Comment by amyiridescent** [comment]
Is there something that we can do right now to manually approve these email addresses while Mailgun addresses the bug? Or will that cause issues later once the bug has been fixed?

**Comment by joemsak** [comment]
If you recall in my comments above, we can bypass validation by detecting `@qq.com` in the email address and letting it look "valid" to the code that's doing the check.

**Comment by joemsak** [comment]
Confirmed in 11-5 sprint planning: bypass validation for qq.com emails

**Comment by Allicolyer** [comment]
@ophelieh could you QA this?

**Comment by kmorton2017** [comment]
i tested all but one email as a student. I tested one as a mentor (2675138206@qq.com). 
i also tested out some of these addresses as a +1@qq.com in the parent email. it said an email was sent to the parent.

all 3 use cases worked fine (student, mentor, parent)

**Comment by Allicolyer** [comment]
Thank you @kmorton2017 and @ophelieh
