### ISSUE TITLE
Admins cannot see which mentors have completed their onboard

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1791]
Acceptance Criteria:

As an admin
I can view a mentor's profile
and see if they have completed their mentor training or not

As an RA
I can view a mentor's profile
and see if they have completed their mentor training or not

**Comment by joemsak** [comment]
@Allicolyer do you also want the admin to be able to filter the search by a mentor who has completed training? If so, simply update the acceptance criteria and I will be happy to include that. Thanks!

**Comment by joemsak** [comment]
@Allicolyer Also, I just realized, do you want this on the RA view too? Again, if so, just update the AC and I will happily include it in the work for this card.

**Comment by Allicolyer** [comment]
@joemsak yes that makes sense! I can write another card for the filtering and I'll add the RA acceptance criteria here.

**Comment by Allicolyer** [comment]
Can you merge it to QA? Thanks!

**Comment by joemsak** [comment]
I will do that now and I will move the card to test when QA is updated. Thank you Alli!

**Comment by Allicolyer** [comment]
Hey Joe!

This works as expected. However I am having a hard time testing this card since I can't complete the mentor training using the link that is in the presentation. I takes you to the production site.

**Comment by kmorton2017** [comment]
yes this performs as expected for both use cases.
