### ISSUE TITLE
Password reset/changing email

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1794]
Several participants emailing Zendesk are reporting problems with the following. Could we double check that everything is running ok with these two features?

1) Resetting password (Ticket #6022, #5969, #5951)
2) Creating a new email address  (#6015)

**Comment by Allicolyer** [comment]
Hey @kmorton2017! Could you put the details of what is not working here?

**Comment by kmorton2017** [comment]
@alli this is most likely because of the current bug we are addressing in #1843

**Comment by Allicolyer** [comment]
This card seems stale.
