### ISSUE TITLE
Removing member from a team 

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1798]
**Describe the bug**
I tried to remove Momoka Nakamura from team Bloomers but received a "sorry we couldn't find this page" message. 

**To Reproduce**
1. Go to  Momoka Nakamura's profile. #/
2. Click on her team Bloomer
3. Remove this member
4. See "sorry" message

**Desktop (please complete the following information):**
 - OS X El Capitan, Version 10.11.6
 - Chrome

**Comment by kmorton2017** [comment]
When I went back to Momoka's profile I saw that she was no longer on Bloomer.

**Comment by Allicolyer** [comment]
Hey @kmorton2017 since this seems to be resolved, I will close this card.

**Comment by Allicolyer** [comment]
This might be a bigger issue with removing students from teams. I will test to see if I can reproduce.
