### ISSUE TITLE
Generate Certificate

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1799]
**Describe the bug**
I went to a student account  (anifiona@yahoo.com) to generate her 2018 certificate. When I opened it, it said 2017. She participated in 2017 and 2018 but the 2017 certificate was the only one that was opening for both seasons. 

**To Reproduce**
1. Go to https://my.technovationchallenge.org/admin/participants/26346#/
2. Click on "Open your Certificate" for 2018 season
4. See 2017 certificate

**Expected behavior**
Since she was a semifinalist, I would expect to see her 2018 certificate of completion and a semifinalist certificate. Instead I only saw her 2017 certificate.

**Desktop (please complete the following information):**
 - OS El Capitan 10.11.6
 - Chrome
 - Version  70.0.3538.77

**Comment by Allicolyer** [comment]
@kmorton2017 We have a lot of issues with certificates right now. I don't think we're really ever be in a position to fix certificates from past seasons. However, we are hoping to build a more sustainable system for 2019.

In the meantime here is our suggested method of getting certificates to past participants who ask for them:

Here is a [Dropbox folder of certificates](https://www.dropbox.com/sh/x2xd50oq9tu6t69/AACfPuGK4XYYGTo_J2Zn1nQHa/Digital%20Distribution?dl=0&subfolder_nav_tracking=1). They are editable PDFs. Download the one you need, fill it out with her information and send it to her as an attachment. Make sure when you send it back to her it is no longer editable. You can do this by exporting it as a PDF (using preview on your mac) after you have filled it out. Let me know if you have any questions.
