### ISSUE TITLE
Update RPE new event form date picker to use 2019 dates

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1802]
**Describe the bug**
As an RA, visit /regional_ambassador/events. When attempting to select an event date using the Date field date picker, only May 2018 dates are available for selection. We need to update this picker for the 2019 season dates.

**To Reproduce**
1. Log in as an RA. Go to the Events section of the dasboard (/regional_ambassador/events).
2. Click on '+ Add an event'
3. Click on the Date field.
4. Observe that only May 2018 dates are selectable in the date picker.

**Expected behavior**
Dates for the 2019 season are available for selection. Need to get these dates from @Allicolyer or @kmorton2017.

**Screenshots**
See comments for a screenshot.

**Desktop**
 - OS: Mac OS X High Sierra
 - Browser: Chrome
 - Version: 70

**Comment by adrichey** [comment]
<img width="1068" alt="screen shot 2018-11-05 at 10 33 16 am" src="https://user-images.githubusercontent.com/1534554/48012405-8815d700-e0e7-11e8-959f-49f9ee11fbfa.png">

**Comment by adrichey** [comment]
This is blocked until I have dates for what the datepicker range needs to be set to. Thanks!

**Comment by Allicolyer** [comment]
@adrichey I will get those for you

**Comment by Allicolyer** [comment]
Hey Alan,

Regional Pitch events can be held on any day starting April 27th 2019 and ending June 2nd 2019.

**Comment by adrichey** [comment]
Thank you @Allicolyer! I will work on getting that dropdown updated soon.

**Comment by Allicolyer** [comment]
Hey @adrichey ! This looks great and is working as expected.

Is there anyway to fix this issue? When the date picker opens up, I am in the month of April. All the dates in May are "grayed out" , so for instance, it looks like I can't select May 4th. However, If I change the month to May, I can now see that these dates are not grayed out. I can see this being confusing fro some of our RAs. 

![uploads/948196af-522f-4b19-90d8-1225fb3739b1/Screen Shot 2018-11-19 at 9.30.01 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F948196af-522f-4b19-90d8-1225fb3739b1%2FScreen+Shot+2018-11-19+at+9.30.01+AM.png)

**Comment by adrichey** [comment]
@Allicolyer I suppose I could make the styles for those valid May dates when viewing April a little darker. You can see a slight color variation between the disabled dates in April and the enabled dates in May on the April calendar, though they are slight. I can toy around with that color saturation a bit and see if I can make it more obvious. How does that sound?

**Comment by Allicolyer** [comment]
That sounds great! Thank you @adrichey!

**Comment by adrichey** [comment]
@Allicolyer This should be ready for testing once again. I darkened up those valid dates. Hopefully that is enough contrast.

**Comment by Allicolyer** [comment]
Hey @adrichey this looks great!
