### ISSUE TITLE
Header is cutting off content on the scores sections for submissions

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1805]
**Describe the bug**
Header is cutting off content on the scores sections for submissions.

**To Reproduce**
1. Log in as a Judge able to score a submission.
2. Browse to a submission to begin scoring.
3. Notice that the header now cuts off the content (white navigation bar with the scores).

**Expected behavior**
Header does not cut off the content on the page.

**Comment by adrichey** [comment]
When there are no more submissions to judge, no message is showing (just a blank screen). The message that should normally appear is under the header.

**Comment by Allicolyer** [comment]
Thank you @adrichey! This is working well now.
