### ISSUE TITLE
Activity tracking for presentation slides just says “updated their”

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1806]
As a student
on a team
who has started a submission
and is attending an RPE
I update my presentation slide

Then as an RA
I can log in and see this activity in their activity tracking

Currently, the activity tracking for presentation slides just says “updated their...”

Needed for events. Absolute deadline is in March.

**Comment by adrichey** [comment]
Pull request for this has been created: #1885.

**Comment by adrichey** [comment]
This is now ready for testing!

**Comment by nickiredescent** [comment]
Tested and works!

**Comment by Allicolyer** [comment]
Awesome thanks @nickiredescent !!
