### ISSUE TITLE
Outdated dates and copy the judge dashboard

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1808]
Here are some examples 

<ul>
<li>Quarterfinals judging begins on May 1st, 2018.</li>
<li>
Revise & review your finished scores until May 20th (US/Pacific time)
</li>
<li>
When you finish a score it says: You can review your score and make changes through May 20th (US/Pacific time)
</li><li>
For semifinals it says: Revise & review your finished scores until June 17th (US/Pacific time)
</li>
</ul>

Needed for Judging. Absolute deadline is in April.

**Comment by Allicolyer** [comment]
Problem:

Dates are hard-coded onto platform. 
Question: should this be a staff setting to decide which dates get displayed?

**Comment by joemsak** [comment]
This work is dependent on #1810 and when the admins can change the copy settings for dates, then these dates should be fixed with this dynamic solution

**Comment by adrichey** [comment]
@Allicolyer can you please supply the dates that we need to change and what they need to be changed to in order to complete the work on this ticket?

**Comment by joemsak** [comment]
@adrichey I think possibly `ImportantDates` has been updated (or should be) to reflect these new dates - and then of course, `ImportantDates` right now is based on ENV vars but could be based on redis/db Admin Settings if that other feature is worked on instead - possibly removing `ImporantDates` in favor of a new API in `SeasonToggles` - totally up to you in the end, though

**Comment by adrichey** [comment]
Noted. Thanks Joe. I think we are holding off on #1810 for now in favor of other things, so I think this will just use `ImportantDates` when we do the fix for this.

**Comment by Allicolyer** [comment]
Here are the updates dates

<ul>
<li>Quarterfinals judging begins on April 27th, 2019.</li>
<li>Revise & review your finished scores until May 20th</li>
<li>For semifinals it should say: Revise & review your finished scores until June 17th (US/Pacific time)</li>
</ul>

Actually the only date that changed is the start date of quarterfinals.

**Comment by adrichey** [comment]
This is now ready for testing! Thanks for the feedback that unblocked this ticket, @Allicolyer!

**Comment by kmorton2017** [comment]
@Allicolyer can i talk to you off huboard on key dates? i want to make sure copy isn't confusing for judges this year since we are doing things a bit differently with virtual judging vs. RPE's this year.

**Comment by adrichey** [comment]
If you need me to update any of these dates after your discussion, please
let me know. I can work with you all. :)

**Comment by Allicolyer** [comment]
sure @kmorton2017 please let me know when you want to talk.

**Comment by Allicolyer** [comment]
@kmorton2017 I am going to close this card for now, and we can schedule a time to go through the dates on the platform.
