### ISSUE TITLE
XConfigure all "copy-based" dates in Admin Settings

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1810]
As an admin
When I go to Content & Settings
Then I should be able to set the following dates:

https://docs.google.com/spreadsheets/d/1dpBRY98aZztg5R5PRhe5IazqbYPX-sT0GOVWLhoYvK8/edit#gid=944257961

And the setting of these dates *only* affects the copy on pages and emails
In other words, changing these settings will not make these things happen automatically

As the admin
I expect to find each date in its relevant panel
Example: Submission deadline will be in the "Submissions" panel

**Comment by Allicolyer** [comment]
I just added the spreadsheet that shows all the important calendar dates. I think this is a cool feature that we should tackle after we have gotten all the event bugs sorted out.

**Comment by rsgonzal** [comment]
Closing, similar to #2685
