### ISSUE TITLE
Reviewing a submission after completing it, for Thunkable submissions

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1812]
As a student or mentor
On a team
With a submission
Which has its Development Platform option set to "Thunkable"
When I complete and submit the submission
Then I should see the "reviewable" version of it
And in the 'Source Code' portion
I should see a link to the Thunkable project
And it should open in a new window

**Comment by kmorton2017** [comment]
is there a test URL we can use for a Thunkable project?

**Comment by Allicolyer** [comment]
this works! thanks!
