### ISSUE TITLE
Suspicious Scores has a 500 error and is not showing up 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1813]
Suspicious Scores has a 500 error and is not showing up 

1. As an admin, turn on Quarterfinals Judging
2. Log in as an on-boarded judge who is not a mentor and who has not already judged any teams
3. Judge and submission and give the lowest score possible
4. Log in as as admin and confirm that the score did not show up under "suspicious scores"

I would expect this score to show up under "suspicious scores" but it does not. Instead it appears that the "suspicious scores" are just loading forever.

Needed for Judging. Absolute deadline is in April.

![uploads/bf92aaa2-71e7-4a69-8994-c0e86d405c92/Screen Shot 2018-11-05 at 4.31.22 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbf92aaa2-71e7-4a69-8994-c0e86d405c92%2FScreen+Shot+2018-11-05+at+4.31.22+PM.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome

**Comment by adrichey** [comment]
I have a fix for this. So after speaking with @Allicolyer we have decided to pull this into the To Do column. I should have a pull request in for this today.

**Comment by adrichey** [comment]
This is now complete and ready for QA!

**Comment by Allicolyer** [comment]
@nickiredescent thank you for the throughout QA! We should look into some of these discrepancies for the scoring sprint.
