### ISSUE TITLE
Mentor Certificates do not work on their dashbaord

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1814]
The mentor certificates do not work on the mentor dashboards.

1. As an admin, turn on scores and certificate
2. Log in as a mentor who has at least one team with a complete submission
3. Try get your certificate
4. Your certificate will not load

![uploads/f2e278ff-92e5-466f-b602-a648707f25ac/Screen Shot 2018-11-05 at 3.58.44 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff2e278ff-92e5-466f-b602-a648707f25ac%2FScreen+Shot+2018-11-05+at+3.58.44+PM.png)

![uploads/2d530d19-e978-44ef-8746-8b42296bce1d/Screen Shot 2018-11-05 at 3.58.48 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2d530d19-e978-44ef-8746-8b42296bce1d%2FScreen+Shot+2018-11-05+at+3.58.48+PM.png)

 - OS: MacOS Mojave
 - Browser: Chrome)

**Comment by kmorton2017** [comment]
I am able to load my certificate as a mentor.
