### ISSUE TITLE
On the judge dashboard there is contradicting text when certificates are available.

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1815]
On the judge dashboard there is contradicting text when certificates are available.

“Online Judging
You are currently set to judge submissions online.

You may be expecting an invitation to a live event from a Regional Ambassador. In that case, just wait for the email. Most judges are online and will not attend a live event.

Quarterfinals judging begins on May 1st, 2018.”

**Comment by adrichey** [comment]
@Allicolyer can you please supply the date when quarterfinals judging will begin to unblock this ticket? Thanks a ton!

**Comment by Allicolyer** [comment]
Quarterfinals Judging begins on April 27th

**Comment by adrichey** [comment]
This is now ready for testing! Thanks for the feedback that unblocked this ticket, @Allicolyer!

**Comment by Allicolyer** [comment]
Hey @KaiLokken can you test this card?

Here's how to test. 

Go to https://technovation-qa.herokuapp.com/
Log in as a judge: judge@judge.com
Confirm that you see "Quarterfinals Judging begins on April 27th" on your dashboard.
April 27th is the correct date and May 1st is the incorrect data. Confirm you don't see May 1st anywhere on the dashboard.

Thank you!

**Comment by adrichey** [comment]
@KaiLokken If you are unable to submit a comment here on Huboard, you should be able to click the #1815 beside the title on this card to be taken to Github. You may be able to comment there. Thanks for testing this!

**Comment by Allicolyer** [comment]
Awesome thank you @KaiLokken!
