### ISSUE TITLE
Mentors who have not completed their mentor training are still searchable

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1816]
Mentors who have not completed their mentor training are still searchable

1.Find a mentor who has not completed their mentor training 
2.Go to a student account who is on a team
2. Search for the mentor who has not completed their mentor training
3. Send an invite for them to join your team.

Mentors who have not completed their training should not be searchable by students since they should not be considered fully on-boarded.

![screen shot 2018-11-05 at 3 52 32 pm](https://user-images.githubusercontent.com/11083917/48034464-5f580680-e114-11e8-9bb6-19f3df9a6e71.png)
![screen shot 2018-11-05 at 4 01 20 pm](https://user-images.githubusercontent.com/11083917/48034471-61ba6080-e114-11e8-99ae-d10d3755cd22.png)

 - OS: MacOS Mojave
 - Chrome

**Comment by Allicolyer** [comment]
@kmorton2017 I believe this is a bug. Can you confirm if it is?

**Comment by joemsak** [comment]
@Allicolyer can you confirm the sign up date of these mentors? Mentors who signed up before the training was available are not required to complete it

**Comment by joemsak** [comment]
@kmorton2017 I can fix the searchability bug pretty easily, what would you like me to do if any mentors have gotten invites or have already joined teams? That could be a pretty bad experience for the users, to have mentors / invites suddenly go missing. Let me know what you want. In the meantime, I'm putting in a pull request to Alan for the searchability fix, which not only fixes the logic but also includes a database update to fix existing accounts.

**Comment by Allicolyer** [comment]
Thanks @joemsak this is now working as expected.

Let's honor all invitations already sent and just apply this logic to new invitations

**Comment by Allicolyer** [comment]
@joemsak let me know if you need any more information here.

**Comment by joemsak** [comment]
I don't think so, sounds like it's good to go

**Comment by Allicolyer** [comment]
@joemsak do you need another card written out to honor any old invitations?
