### ISSUE TITLE
RA creating event: Time select is broken

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1826]
**Describe the bug**
As an RA when I am creating a new event, and go to select start / end times, there is no menu to pick from times

**To Reproduce**
1. Login as an approved RA
2. Click on "Events"
3. Add a new event
4. Focus the mouse in the start / end time fields
5. See that no menu appears to pick times

**Expected behavior**
I expected a dropdown menu to select standardized times

**Comment by adrichey** [comment]
@joemsak I can address this issue. What format should the time be in when it comes to the backend? 24-hour time (17:00), for example.

**Comment by joemsak** [comment]
Hey Alan, thanks for taking an interest in this bug. For what it's worth, since it's brand new and wasn't discussed in sprint planning, I'm not sure what the priority would be for it just yet, but I will leave that decision up to everyone else. ANYWAY to answer your question regardless, the menu was previously working with 24 hour time. It's my belief that you ought to find existing code that simply isn't executing properly.

**Comment by adrichey** [comment]
Noted! I will talk to Alli and see if we can make some time for this soon. I will take a look into the previous functionality soon. Thanks for making this card and putting visibility on this!

**Comment by joemsak** [comment]
Sure thing, I discovered it while trying to fix the critical bug :)

**Comment by adrichey** [comment]
After speaking with @Allicolyer we have decided to pull this into the sprint. Beginning work now. :)

**Comment by Allicolyer** [comment]
@adrichey this is working great.

1. If I try to make my event start after it ends, the time picker will adjust itself. 
2. The times I select get converted to 24 hour time. 

@kmorton2017 Could you check this out? I know that most of our RAs probably don't use AM & PM, but I think this is a good solution.

**Comment by adrichey** [comment]
@Allicolyer and @kmorton2017 I can also set the time pickers to 24-hour time if that works better. Let me know if that is desired and I can do that!

**Comment by joemsak** [comment]
Just a note in support of 24 hour time, I won't say which RA but when we had AM/PM time, one of our RAs picked their times in the very early morning when they meant to pick them in the afternoon, so I would advocate for 24 hour time

**Comment by Allicolyer** [comment]
Thanks @joemsak! I think @kmorton2017 and @ophelieh should make the final call!

**Comment by ophelieh** [comment]
I would recommend the 24 hour time as only a few countries actually use the AM/PM time. 

Thank you @joemsak @adrichey @Allicolyer!

**Comment by Allicolyer** [comment]
Thanks @ophelieh. @adrichey Could you put the time pickers to 24 hours?

**Comment by adrichey** [comment]
@Allicolyer Done! This is once again ready for testing.

**Comment by Allicolyer** [comment]
@adrichey this looks great!

**Comment by Allicolyer** [comment]
I still see AM/PM in the top summary bar:

![uploads/95347556-e98f-4c43-98f3-00f18910957e/Screen Shot 2018-11-26 at 5.21.05 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F95347556-e98f-4c43-98f3-00f18910957e%2FScreen+Shot+2018-11-26+at+5.21.05+PM.png)

**Comment by adrichey** [comment]
@Allicolyer The acceptance criteria doesn't cover that section. Can we create another ticket for that update? That way I can focus on getting a production release out sometime this week (hopefully).

**Comment by adrichey** [comment]
@Allicolyer Actually, I am going to knock that out. It is a really simple fix and I have time to get it done tonight. :slightly_smiling_face:

**Comment by Allicolyer** [comment]
Thanks @adrichey :) checking it out now

**Comment by Allicolyer** [comment]
Works great now! Thank you @adrichey !
