### ISSUE TITLE
QA Bug --Removing self from team

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1828]
**Describe the bug**
I am logged in as katie+s1@iridescentlearning.org on QA which is a student account.
I received a sorry page after trying to remove myself from a team on QA. I am the only member on this team. 

**To Reproduce**
1. Go to "My team"
2. Click on '"Remove this team member" 
3. See Sorry page

**Expected behavior**
I expected to be able to remove myself from a team. 

**Desktop (please complete the following information):**
 - OS:X El Capitan Version 10.11.6
 - Chrome Version  70.0.3538.77

**Comment by Allicolyer** [comment]
Hey @kmorton2017. Thanks for spotting this. I see a scenario where you might need this to work is when a student wants to join another team but cannot unless they leave their current one.

How common do you think this scenario is? Would it be okay to focus on this next season?

**Comment by Allicolyer** [comment]
@kmorton2017 I could not reproduce this error.

**Comment by Allicolyer** [comment]
When I leave a team as the only member, I can no longer find that team to rejoin. I can also no longer find that team in the admin or RA views.
