### ISSUE TITLE
As an RA I cannot save teams or judges that I invite to my event

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1831]
**Describe the bug**
As an RA I can select a team to add to my event, but I can't save them

**To Reproduce**
1. Log in as Ra@ra.com
2. Click on Events
3. Find an event and click on 'manage teams'
4. Invite a team and try to click 'save teams'
5. Nothing happens 
6. When the page is refreshed the teams have not been added

**Expected behavior**
I expect to be able to add the teams and judges.

**Screenshots**
![screen shot 2018-11-08 at 10 19 32 am](https://user-images.githubusercontent.com/11083917/48219259-e689c200-e340-11e8-9c72-5ea5c1ba0202.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome

**Comment by adrichey** [comment]
I believe I have a fix for this. Assigning to myself and beginning work.

**Comment by Allicolyer** [comment]
@adrichey this is working great now! I will test it out futher to find more bugs and then file more bug reports.
