### ISSUE TITLE
As an RA, I cannot select more than one team to add to an event

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1832]
**Describe the bug**

**To Reproduce**
1. Log in as an RA
2. Click on events
3. Click on 'manage teams'
4. Select a team to add to your event
5. Once one team is select the other options disappear and I cannot 'unselect' that team
6. I am are unable to select another team to add to the event or 'unselect' the team, even if I close and reopen the 'manage teams' menu 

**Expected behavior**
I would expect to be able to select more than one team at a time to add to my event.

**Screenshots**
![events-add-teams](https://user-images.githubusercontent.com/11083917/48219673-f81f9980-e341-11e8-92b8-e85079704bbf.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome

**Comment by adrichey** [comment]
I believe I have a fix for this. Assigning to myself and beginning work.

**Comment by Allicolyer** [comment]
@adrichey this works now! Thank you!
