### ISSUE TITLE
On a team page,  make pending students clickable to view their profile pages

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1837]
**Is your feature request related to a problem? Please describe.**
Admins cannot click on a pending student's or mentor's profile from a team page

**Describe the solution you'd like**
Admins would like to be able to click on a pending students and mentor from their team pages, if their profile exists.

![screen shot 2018-11-08 at 11 13 52 am](https://user-images.githubusercontent.com/11083917/48221631-716dbb00-e347-11e8-9cb6-ac79a2da5275.png)

**Acceptance Criteria**

As an admin
I can go to a team page
Which has a pending student who is not fully on-boarded
And click on the student's name to visit their profile page

As an admin
I can go to a team page
which has a pending mentor who is not fully on-boarded
and click on the mentor's name to visit their profile page

The only caveat here is when the student has not even registered their email yet. In that case no student profile exists, so their name should not be clickable.

Pending students are students who are on teams, but have not finished all of their onboarding steps.

**Comment by Allicolyer** [comment]
@adrichey I updated the acceptance criteria with a caveat.

**Comment by adrichey** [comment]
Thanks @Allicolyer! That is helpful.

**Comment by adrichey** [comment]
This is now ready for testing!

**Comment by Allicolyer** [comment]
Thank you @adrichey. Would you be able to add this for RAs too? Should I make a new card for that or should we keep it on this card?

**Comment by adrichey** [comment]
This is also available for RAs, so you should be able to test that functionality now @Allicolyer. :slightly_smiling_face:
