### ISSUE TITLE
XUI Fix: Profile picture is displayed as a square

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#1838]
**Describe the bug**
I tried uploading a logo for one of our RAs and in the preview, it shows the whole logo then when it saves, the logo is cut. 

**To Reproduce**
1. Go to 'Amy Sailor' 
2. Click on 'Log in as Amy Sailor'
3. Click on 'My account' 
4. Click on 'Change Image' 
5. Upload the attached logo
![wislogo](https://user-images.githubusercontent.com/32206421/48221675-53f51d00-e358-11e8-8682-f589dbea93ea.jpg)
6. Click 'it looks good, take me back'
7. See cut logo. 

**Expected behavior**
Full logo appears. 

**Screenshots**

![image](https://user-images.githubusercontent.com/32206421/48221707-67a08380-e358-11e8-86ae-54b0d7d78983.png)
![image](https://user-images.githubusercontent.com/32206421/48221759-8868d900-e358-11e8-9320-b7f84822d7c5.png)

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser chrome
 - Version 70.0.3538.77

**Comment by Allicolyer** [comment]
Hey @ophelieh. This is because our site displays the profile picture as a square. This doesn't mean that the profile picture is getting cut, just that our site will display it in a square frame.

How important is this to fix. Would you be okay moving this to the icebox as a future UI fix?

**Comment by hellafitz** [comment]
We could grey out anything outside of the square area of the image that the platform will display
