### ISSUE TITLE
Link Team Page to Submission Page

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1839]
**Is your feature request related to a problem? Please describe.**
Admins would like the team page to be easily found from the team's submission page

**Describe the solution you'd like**
Admins would like the team name to be clickable on the team's submission page. The link should lead to the team's page

![screen shot 2018-11-08 at 11 17 01 am](https://user-images.githubusercontent.com/11083917/48221875-0ec8ef00-e348-11e8-8691-2e653f9befbc.png)

**Acceptance Criteria**

As an admin
I can view a team's submission page
On that page I can click on the team's name
and it will link me to the team's page

**Comment by adrichey** [comment]
This is ready for QA!

**Comment by Allicolyer** [comment]
Thank you @adrichey. Would you be able to add this for RAs too? Should I make a new card for that or should we keep it on this card?

**Comment by adrichey** [comment]
This is also available for RAs, so you should be able to test that functionality now @Allicolyer. Usually when a feature is rolled out for admins, it gets rolled out for RAs as well, but in the future if you could put that on the card as well, I would appreciate it. Thanks!
