### ISSUE TITLE
Add fields to collect for survey

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1846]
Hi @kmorton2017 and @ophelieh, can you tell me if this is all the fields that we need to collect for the pre-survey?

First and Last Name,
*School
City 
State / Providence
Country
Email Address
*Team Name

The ones that have a star* are the ones that Joe and Alan need to add functionality for. Are there any other new fields that you need this year?

**Comment by ophelieh** [comment]
Looks right to me. We could possibly add age. This could tell if age makes a difference in filling out the survey or not.

**Comment by kmorton2017** [comment]
@Allicolyer just noticed a typo it should be "State / Province"

For mentors it should gather: 
First and Last Name,
**Company**
City
State / Province
Country
Email Address
*Team Name

**Comment by kmorton2017** [comment]
@alli just checking in to see if there is an update here! @joemsak

**Comment by Allicolyer** [comment]
Hi @kmorton2017 and @ophelieh! We can move this into to-do. Do we want to collect age?

**Comment by ophelieh** [comment]
Yes, please! @Allicolyer :) 

Thank you!!!!

**Comment by Allicolyer** [comment]
Hey @joemsak can you work on this ASAP? The program team needs the following fields added to the student and mentor surveys:

Student Survey:
<ul>
<li> Team Name </li>
<li> Age </li>
<li> School </li>
</ul>

Mentor Survey:
<ul>
<li> Team Names </li>
<li> Company Name </li>
</ul>

**Comment by adrichey** [comment]
@joemsak This would actually take priority over the location form. @Allicolyer and I spoke this morning and since this is a more straightforward fix and needs to be in our next production release -- which I have planned for this week once this is done -- it takes priority. Thanks in advance for being flexible on this. :slightly_smiling_face:

**Comment by joemsak** [comment]
No prob, I will get on it once I return from the dentist. Got half my mouth
feelling like there’s a baseball in it right now haha


-- 
Joseph M. Sak
+1 312 945 6317
+52 1 33 23 10 69 05
work@joesak.com

**Comment by joemsak** [comment]
@Allicolyer can you please tell me how each of those variables are named in survey monkey?

**Comment by joemsak** [comment]
@Allicolyer Actually, let me amend my request: make sure all the variables are set as we walked through before, create the web collector URL and copy that into this card. That will be the most accurate representation of what the software should expect to replace with real data

**Comment by adrichey** [comment]
@Allicolyer and @joemsak I just poked around on Survey Monkey since Alli is out for the afternoon. I think we are still missing the `Age` field on the Student survey and the Mentor survey has not been updated with any of the fields in Alli's previous comment. I think we will need someone to update those forms and produce that collector URL. I am not sure if that responsibility falls on Alli, @ophelieh or @kmorton2017. But if I can help in any way, I would be glad to. I just need some guidance on how Survey Monkey works.

**Comment by adrichey** [comment]
@joemsak I think I found the student collector URL. The custom fields are in there. Let me know if anything is missing from this, or if it is what you need. I will look into the mentor piece next.

https://www.surveymonkey.com/r/HFHWZGY?name=[name_value]&school=[school_value]&city=[city_value]&state=[state_value]&country=[country_value]&email=[email_value]&team=[team_value]&age=[age_value]

Tagging @Allicolyer @kmorton2017 @ophelieh for visbility.

**Comment by joemsak** [comment]
Hey @adrichey nice work, thank you! Yes that URL looks like it has all the variables as outlined in this card.

**Comment by adrichey** [comment]
Great! Glad that works for you @joemsak. It looks like the mentor survey doesn't have a collector, nor the additional `Team Names` or `Company Names` custom variables set up. So I am going to lean on our awesome program staff to get you that information. Hopefully @Allicolyer @ophelieh or @kmorton2017 can assist on that front soon. :slightly_smiling_face:

**Comment by joemsak** [comment]
Good call @adrichey in the meantime check PR #1865 for the work done so far (not ready for merge)

**Comment by adrichey** [comment]
Marking as blocked until we can get the mentor variables and the collector set up.

**Comment by kmorton2017** [comment]
Hi Everyone! 

I edited the mentor survey. Thanks for making sure we are on top of everything. Here is the web collector URL for mentors:  https://www.surveymonkey.com/r/Z9M7RZD?email=[email_value]&country=[country_value]&state=[state_value]&name=[name_value]&city=[city_value]&age=[age_value]

Do I need to change the custom variables on survey monkey for both surveys after I have the exact names from the backend from you?

**Comment by adrichey** [comment]
@kmorton2017 I believe we still need to add the following custom variables/fields to the survey form:

- Team Names
- Company Name

If we can get those added, then you should be able to send the collector to us again with those fields added to the URL. Once we have that we can wrap up the back-end. Unless you no longer need the team names or company name, in which case we can finish the work with what you have sent us here.

**Comment by Allicolyer** [comment]
Thanks @kmorton2017!

- For students I added team and age. 
- For mentors I added company and team for mentors, and removed age. 

He @adrichey! Here are some updated links

**Student:**
https://www.surveymonkey.com/r/ZYBG3WD?name=[name_value]&school=[school_value]&city=[city_value]&state=[state_value]&country=[country_value]&email=[email_value]&team=[team_value]&age=[age_value]

**Mentor: **
https://www.surveymonkey.com/r/Z9M7RZD?email=[email_value]&country=[country_value]&state=[state_value]&name=[name_value]&city=[city_value]&company=[company_value]&team=[team_value]

**Comment by kmorton2017** [comment]
Hi Guys, 

Just to confirm, all of the survey questions on the form now match the criteria. What I have a question about is naming the custom variables. On my end on survey monkey, I need to name each custom variable in the "logic" section. See screenshots for an example. (FYI here is a survey monkey article i've been referencing as a program person--you guys have probably already seen it: https://help.surveymonkey.com/articles/en_US/kb/What-are-custom-variables-and-how-do-I-use-them

Can you confirm the exact names of the variables? I think this what is in the brackets before the value, but want to double check. Ie email, country, state, name, city, company, team. I will need to make it matches exactly b/c it is case sensitive.

![uploads/27de436f-df8e-49cc-afda-05bd75084a9d/Screen Shot 2018-11-28 at 5.46.02 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F27de436f-df8e-49cc-afda-05bd75084a9d%2FScreen+Shot+2018-11-28+at+5.46.02+PM.png)

![uploads/4186ee14-b941-4991-8950-5d85c3404ccf/Screen Shot 2018-11-28 at 5.46.09 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4186ee14-b941-4991-8950-5d85c3404ccf%2FScreen+Shot+2018-11-28+at+5.46.09+PM.png)

**Comment by adrichey** [comment]
Hi @kmorton2017! I went in and edited the variable names to what they should be according to the collector URLs @Allicolyer posted in this thread yesterday (Thank you for getting those collector links to us @Allicolyer!). So we should be good to go! But for your records, here are the variable names:

- **Label / Variable Name**
- EmailAddress / email
- Country / country
- StateProvince / state
- FirstandLastName / name
- CityTown / city
- Company / company
- TeamName / team

You can change the Labels for these custom variables, but the variable names need to stay the same for our platform logic to work correct. Thanks for working on that! Let me know if you have any questions, but I don't think there is anything left to do here. 🙂 

@joemsak this should give you what you need to finish this work. Let us know if you need anything else:

**Student:**
https://www.surveymonkey.com/r/ZYBG3WD?name=[name_value]&school=[school_value]&city=[city_value]&state=[state_value]&country=[country_value]&email=[email_value]&team=[team_value]&age=[age_value]

**Mentor:**
https://www.surveymonkey.com/r/Z9M7RZD?email=[email_value]&country=[country_value]&state=[state_value]&name=[name_value]&city=[city_value]&company=[company_value]&team=[team_value]

**Comment by Allicolyer** [comment]
Thank you @adrichey. @kmorton2017 would you have time to test this with me today?

**Comment by kmorton2017** [comment]
A few initial findings: 
- The copy should be the same for both mentors and students. right now it also says "post survey". The correct text should say: (Help us improve! TAKE THE PRE-PROGRAM SURVEY!) for both mentors and students.
- The survey says it's closed. But on survey monkey it is listed as open and collecting responses for both mentors and students.

Other questions:
 Is it possible to feature the link more prominently-- Ie in the green header "Hey Welcome back! "  I think i remember it being posted there last year.

**Comment by joemsak** [comment]
@kmorton2017 the copy is something admins can control, and there is logic for a modal popup which should come up once 2 weeks after the link / text has changed and again in 2 weeks if the person hasn't completed the survey. You're also supposed to be configuring your surveys to redirect to the survey completion URL at the end when the person finishes it.

**Comment by joemsak** [comment]
changing the survey does not change the links, however those questions are for survey monkey, not the technovation dev team

**Comment by joemsak** [comment]
also, don't quote me on the exact logic of when the modal appears as staff has requested it to be changed a number of times and I can't remember off the top of my head - you can try looking back through closed issues or meeting notes to find out what was most recently discussed and agreed by staff

**Comment by Allicolyer** [comment]
@adrichey and @joemsak so Katie and I just QAed this. Everything is working as expected with the variable collectors and this is good to go.

**Comment by adrichey** [comment]
Awesome! Thanks to you both for taking time out of our hectic schedules to QA this, @Allicolyer and @kmorton2017! Alli, do you want to leave this open for now and I can let you know when I am done pushing this up to production so you can do any configuration on production that needs to happen? Or can we close this now? As soon as I get the go ahead from you, I will cut our production release this morning.

**Comment by Allicolyer** [comment]
I think we can close this now. Thank you @adrichey
