### ISSUE TITLE
Update the registration age verification to 10 by WPE

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1849]
**Is your feature request related to a problem? Please describe.**
RA's are having trouble signing up their girls who will be 10 by World Pitch. Right now, the application logic is such that if a student is 9 years old at the time of registration, they cannot sign up. @ophelieh has asked that we instead check that the student will be 10 by World Pitch in order to register as a student.

**Describe the solution you'd like**
If a student is 9 years old now, but will be 10 by World Pitch, they should be able to sign up as a student. Right now, if they are 9 years old and 10 by World Pitch, they cannot sign up.

**Comment by adrichey** [comment]
After talking with @ophelieh this appears to be a high priority. @Allicolyer how do you feel about pulling this into the current sprint? I feel like we should get this into production soon since it is affecting sign ups. But I also don't want to completely overload QA.

**Comment by ophelieh** [comment]
Hi @adrichey and @Allicolyer! What is the status on this? As more and more people are registering, we are getting more tickets about girls not being able to register if they are 9 at the moment.

**Comment by adrichey** [comment]
I can fix this very quickly as soon as we bring it into a sprint. @Allicolyer can I go ahead and pull this in now to start work on it?

**Comment by ophelieh** [comment]
Perfect! :)

**Comment by adrichey** [comment]
This is now ready for testing!

**Comment by ophelieh** [comment]
@nickiredescent @KaiLokken Please test this card

**Comment by adrichey** [comment]
@nickiredescent I will look into that error. Moving this back to the In Progress column.

**Comment by adrichey** [comment]
This is ready for testing again. Thanks for being so thorough Nick!

**Comment by nickiredescent** [comment]
Tested. I am able to input August 1st, 2009 as my birthdate and hte platform gives me expected feedback and lets me proceed. Thanks for your hard work!
