### ISSUE TITLE
RA: Link to the submission page does not work the team page when accessing the team page from an event

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1854]
**Describe the bug**
Link to the submission page does not work the team page when accessing the team page from an event

**To Reproduce**
1. Log in as an RA
2. Click on one of the teams attending an event
3. On the team page, scroll down to the submission
4. Get an error when you click on the link to the submission

**Expected behavior**
I would expect to be linked to the submission page.

**Screenshots**

![view-submission](https://user-images.githubusercontent.com/11083917/48726039-faf07900-ebe2-11e8-9e55-2faeeed06614.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome

**Additional Information**

The submission page works when it is accessed from the team page through the team menu.

**Comment by Allicolyer** [comment]
@joemsak and @adrichey would this be easy to fix?

**Comment by Allicolyer** [comment]
Hey @joemsak and @adrichey I tried this again today and it did not work, I was still redirected to the home page with a "you don't have permission to go there" message.

**Comment by adrichey** [comment]
I am also seeing that error message. I will look into that today @Allicolyer.

**Comment by adrichey** [comment]
This code works for me locally, so I am assuming that it didn't get deployed to QA properly. There are also tests written around this that passed, so my guess is that the code just hasn't been deployed properly, or that there is a caching issue. Continuing to investigate, but I don't think any new code needs to be written.

**Comment by adrichey** [comment]
Turns out it didn't get deployed yesterday to QA. I have deployed that manually. This is once again ready for testing. Thanks!

**Comment by Allicolyer** [comment]
Thanks Alan! It's working great now!
