### ISSUE TITLE
RPEs - The print event rooster button leads to a blank PDF

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1856]
**Describe the bug**
The print event rooster button leads to a blank PDF

**To Reproduce**
1. Log in as an RA
2. Create an event
3. Invite teams and judges to your event
4. Click "print for live event"
5. Click "print your event rooster"
6. Download the event rooster as a PDF PDF and see that it is blank

**Expected behavior**
I would expect to see an event rooster instead of a blank page

**Screenshots**
![screen shot 2018-11-19 at 10 43 07 am](https://user-images.githubusercontent.com/11083917/48727748-ef538100-ebe7-11e8-8bbe-33615b62aab9.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome

**Comment by Allicolyer** [comment]
@adrichey would you be able to look into this?

**Comment by joemsak** [comment]
@Allicolyer have the teams you invited completed their submissions? also, i think this printout is only for when an RA assigns judges specifically to teams, so make sure you have 15 (i think it's 15, might be 10) teams with assigned judges
