### ISSUE TITLE
Need a way to complete mentor training on QA

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1858]
Hi @joemsak and @adrichey !

When creating new mentor accounts, there isn't a way to complete the mentor training on QA. This makes it hard to create new accounts and test them. Could you help create a work around for us?

**Comment by joemsak** [comment]
Visit this URL manually while logged in as the mentor

http://technovation-qa.herokuapp.com/mentor/training_completion

This question has actually come up repeatedly, so again I will suggest all testers add this URL to their bookmarks.

**Comment by Allicolyer** [comment]
Thanks Joe!
