### ISSUE TITLE
Better database pooling configuration options

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1861]
**Is your feature request related to a problem? Please describe.**
The problem is that Heroku imposes a hard limit on the number of database connections we can have, but as we fiddle with `WEB_CONCURRENCY` or the number of dynos or things like that, we can end up configuring our software to think it's allowed to have more connections than it really is.

When that happens, you start to see `could not obtain a connection from the pool within 5.000 seconds (waited 5.001 seconds); all pooled connections were in use` errors popping up, which doubly sucks because now a whole bunch of web requests are sitting for 5+ seconds searching for a free connection and things can slow down even more.

The end result is a bunch of timeouts, dropped requests, and 500 errors, which the usual scaling methods won't solve.

**Describe the solution you'd like**
I'd like the pool size in both `config/database.yml` and `config/initializers/sidekiq.rb` to be controlled through environment variables. `DB_POOL_SIZE` and `SIDEKIQ_DB_POOL_SIZE` would be fine as names, for example.

**Describe alternatives you've considered**
We could get fancy and try to calculate reasonable pool sizes based on `WEB_CONCURRENCY` and 
`RAILS_MAX_THREADS` but... meh. Probably easier to just control it directly.

**Additional context**
![Pools can be dangerous](https://media.giphy.com/media/LlPGmmhr0GcKs/giphy.gif)

**Label**
You MUST use the label menu to add 'Feature request' and '0 - To Discuss' as a label

**Comment by adrichey** [comment]
@stenington do we need to update our production environment variables once this code makes it to production?

**Comment by adrichey** [comment]
I am currently deploying this configuration options code to production. Pending a successfully run on CI, I will update the configuration variables in our Heroku production settings and close this ticket.

**Comment by adrichey** [comment]
I have updated the Heroku variables according to the suggestions that @stenington provided previously. I am going to close this ticket as a result. I will monitor Airbrake and Heroku for potential issues with these changes. Thanks for all of your work on this, Mike!

**Comment by stenington** [comment]
🎉 

On Heroku, we should see Memory Usage creeping back up to the 1GB threshold, but Postgres connections shouldn't surpass the 40 connection limit. Maybe keeping half an eye on Sidekiq to make sure it's not bottle-necking on db connections or something would also be good.

**Comment by stenington** [comment]
I just changed `SIDEKIQ_DB_POOL_SIZE` to 9 because we started to see connection problems from sidekiq jobs.

**Comment by adrichey** [comment]
Awesome. Thank you Mike.
