### ISSUE TITLE
Deleting an Admin

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1867]
Madhavi (madhavi+admin@iridescentlearning.org)
is still listed as an admin on my.technovationchallenge.org. I tried to delete her but get a "Sorry this page does not exist" message.

FYI it says that she has a temporary password and has never logged in. I am not sure if this relates to the bug or not. 

**Describe the solution you'd like**
I would like to be able to delete Madhavi.

**Comment by joemsak** [comment]
This is already a reported bug

https://github.com/Iridescent-CM/technovation-app/issues/1783

Katie, if you could, I would like for you to please search the open issues reporting a bug, and also I will remind you again to please use the full bug report template, and please do not skip the following sections:

"Describe the bug" - please try to use more than one sentence
"What steps to take to reproduce the bug" - this part is crucial as devs can write tests and QA testers can verify the steps
"What did you expect to happen" - also great for tests and QA testers so everyone knows what the verified correct behavior is
