### ISSUE TITLE
Initial test run fails in new dev environment

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1872]
**Describe the bug**
While following the README, running `rake` produces test failures not seen in existing dev environments. I think it comes down to needing to have assets precompiled.

**To Reproduce**
1. `rake assets:clobber`
2. `rake`

**Expected behavior**
My expectation is that tests will pass if I have followed the instructions correctly. If precompilation of assets is necessary for tests, I would expect that `rake` would handle that or that it would be part of the README.

**Additional context**
Additionally, the default task defined in `Rakefile` does not seem to be the task run with `rake`, which was a red herring as I was trying to figure this out.

**Comment by stenington** [comment]
I'm wrong, the default task in `Rakefile` is run, although rspec tests are being run some other way (probably from `rspec-rails`?). The `bin/rspec` part fails with `/Users/mlarsson/.asdf/installs/ruby/2.5.1/bin/rake: No such file or directory - bin/rspec`

**Comment by Allicolyer** [comment]
Hey @stenington can you give us a sense of how urgent this is?
