### ISSUE TITLE
Remove Onboarded Judges filter in admin and RA Participants page

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1874]
**Describe the bug**
The Onboarded Judges filter doesn't work as expected if Judge isn't selected as a profile type, but rather than fixing we can remove the filter since there's a separate Judges page with an Onboarded filter.

**To Reproduce**
If you want to reproduce the error:
1. Go to the admin or RA Participants page
2. Select "Yes, fully onboarded" under the "Onboarded Judges" filter
3. Click Search
4. See error page

**Expected behavior**
The expectation is that the filter would automatically narrow the profile type down to Judges, but this filter isn't necessary on this page (suggestion from @Allicolyer)

**Comment by Allicolyer** [comment]
@kmorton2017 and @ophelieh it might make sense to pull this card into this sprint. What do you think?

**Comment by ophelieh** [comment]
I agree!

**Comment by adrichey** [comment]
@Allicolyer @ophelieh and @kmorton2017 the way the filters work is that you have to add a profile type to any of the filters. So you have to select Judge profiles for Onboarded Judges, Mentor profiles for Onboarded Mentors, etc. So this is working as intended. I think if we want to improve the way the filters work, that can be discussed, but I think that removing this would remove functionality that people are actually using if they understand the filters correctly.

**Comment by Allicolyer** [comment]
Thank you for that information @adrichey. I think it's good that we just note this so that if any RAs any issues we can help them.
