### ISSUE TITLE
RAs can create events without a date

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1894]
**Describe the bug**
As an RA I can create an event without choosing a date, the date will default to today's date
**To Reproduce**
1. Log in as an RA
2. Create an event without choose a date
3. Save your event
4. Your event has today's date

**Expected behavior**
We would expect an error message and we should not be able to save the event

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version 70

**Additional Information**

It seems that the validation might show up after the fact. If I edit the event, save it, and then click on create a new event, I get a weird error here:

![screen shot 2018-12-17 at 11 21 09 am](https://user-images.githubusercontent.com/11083917/50109945-f0c79780-01ed-11e9-9dd0-b1b860c19abc.png)

**Comment by nickiredescent** [comment]
Date input is required again before saving the event.

![image](https://user-images.githubusercontent.com/45576078/50304510-fec32580-0444-11e9-827f-f696bab5a140.png)

**Comment by Allicolyer** [comment]
Thank you @nickiredescent !
