### ISSUE TITLE
Change EventBrite URL label text

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1895]
Change the label for the Eventbrite URL field to just say "Event URL (optional)"

**Comment by adrichey** [comment]
I have put in a pull request for Mike to review. I went ahead and changed our database variables to reflect this change as well, so I want his eyes on my work before I merge that into QA since it is the first time I am doing this sort of thing. :slightly_smiling_face:

**Comment by adrichey** [comment]
This is now ready for testing!

**Comment by Allicolyer** [comment]
Looks great! Thanks @adrichey!
