### ISSUE TITLE
Change Helper Text for deleting an event

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1896]
Helper message currently says "Regional pitch event was successfully destroyed." 

Change them message to be more user friendly and to say "Regional pitch event was successfully deleted."

To test:
1. Log in as an RA: ra@ra.com
2. Create an event
3. Delete the event
4. Read the helper text, make sure it doesn't say "destroyed", but instead "deleted"

**Comment by Allicolyer** [comment]
@nickiredescent could you test this?

**Comment by nickiredescent** [comment]
Tested and nothing was destroyed.
![image](https://user-images.githubusercontent.com/45576078/50184992-74a38180-02cb-11e9-9bbc-dc59703db740.png)

**Comment by Allicolyer** [comment]
Thanks @nickiredescent !
