### ISSUE TITLE
RPE Summary Text is awkward

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1898]
After I create an event, the text is awkward. The headers alternate from top to bottom and some of them don't make a lot of sense.

How could we improve this UI to be more user-friendly and symmetrical? 

![uploads/02dff443-18a4-4119-904c-7efc977f67dd/Screen Shot 2018-12-13 at 2.07.15 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F02dff443-18a4-4119-904c-7efc977f67dd%2FScreen+Shot+2018-12-13+at+2.07.15+PM.png)

Suggestions:

**Comment by Allicolyer** [comment]
@adrichey since we didn't make any progress on this, I think we should put it into the icebox. This is a UI fix.

**Comment by adrichey** [comment]
Marking as closed as this was addressed in another update.
