### ISSUE TITLE
Events look awkward on Judge Dashboard

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1900]
A judge who is assigned to an event sees the event on their dashboard. The UI needs some improvement, the event might need some sort of wrapper or div.

In addition, for a judge who is not fully on-boarded, the judge profile required steps should appear above the RPE details. The RPE details should stylistically match the on-boarding steps.

To test: 
1. Log in as a judge who is attending an event and who is not fully on-boarded
2. Make sure the required steps appear above the RPE Details
3. Make sure the RPE Details look nice and stylistically match the on-boarding steps, even once on-boarded ins completed.

![uploads/3851ee28-6683-48d4-87af-0f93d428acc8/Screen Shot 2018-12-13 at 2.17.23 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3851ee28-6683-48d4-87af-0f93d428acc8%2FScreen+Shot+2018-12-13+at+2.17.23+PM.png)

**Comment by nickiredescent** [comment]
Tested and works. 
When inviting the judge, the invite-er was also notified that the judge has not completed the on-boarding process.
The Required Steps appeared and stayed above the RPE Details.
Overall, it was clear and simple.

**Comment by Allicolyer** [comment]
Thanks for testing Nick! :)
