### ISSUE TITLE
Judges invited by email to an event need to complete at least 1 on-boarding item before seeing RPE details

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1901]
As an invited by email judge to an event, I had to complete at least one of my on-boarding pieces before I could see the event which is a little bit awkward. It appears once you do that.

@ophelieh can you weigh in here? Do you think judges should complete all of their on-boarding before seeing the event? Alli and Alan both think you should see the event from the start, even if you have no on-boarding pieces.

**Comment by ophelieh** [comment]
Hi @Allicolyer! I agree with both of you, I think the judge (especially one invited to an event) should be able to see the event right away. They will need to complete onboarding before being able to score the teams, so they will be prompted to do that eventually.

**Comment by adrichey** [comment]
@Allicolyer I am unable to replicate this bug on my local. I think I may have inadvertently fixed this when I reorganized the layout for #1900. Can you retest this and let me know if it still acts up for you? I don't think anything else is left to be done here, but I can tweak things if you can give me steps to reproduce any weirdness you get when trying to view events without any boarding steps completed. Thanks! :slightly_smiling_face:

**Comment by nickiredescent** [comment]
I was able to view events and event details before finishing the onboarding process as a judge.

![image](https://user-images.githubusercontent.com/45576078/50305333-5bbfdb00-0447-11e9-9ddb-4f9caa82cfea.png)

**Comment by Allicolyer** [comment]
Hey @adrichey I can also no longer reproduce this bug -- I tested with two different accounts, so I think we're good to go!

@nickiredescent thank you for testing!
