### ISSUE TITLE
Typo - for judge on-boarding the “L” in location is uppercase

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1902]
Typo - The “L” in location is uppercase here: 

![uploads/67335b62-cdbf-4139-a35a-f276f6cfc315/Screen Shot 2018-12-13 at 2.19.38 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F67335b62-cdbf-4139-a35a-f276f6cfc315%2FScreen+Shot+2018-12-13+at+2.19.38+PM.png)

**Comment by nickiredescent** [comment]
The "l" properly knows its standing in the world.
![image](https://user-images.githubusercontent.com/45576078/50186379-72432680-02cf-11e9-8f8e-55b875c1abb4.png)

**Comment by adrichey** [comment]
@nickiredescent Your QA comments are on point. 😆

**Comment by Allicolyer** [comment]
:laughing: I love it
