### ISSUE TITLE
 Is this judge survey still relevant?

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1903]
@ophelieh @kmorton2017 This is required for judge on-boarding. Do you want to to update these questions, is it even still relevant? Did we use this data in anyway last year?

![uploads/73b2e387-4bec-4f9e-8f9e-d09c1cb184e2/Screen Shot 2018-12-13 at 2.23.25 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F73b2e387-4bec-4f9e-8f9e-d09c1cb184e2%2FScreen+Shot+2018-12-13+at+2.23.25+PM.png)

**Comment by ophelieh** [comment]
That's a great question. I am not sure. @amyiridescent do you know? 

Do we ask for their company name? I can't remember.

**Comment by Allicolyer** [comment]
Hey Ophelie! I scheduled some time on Thursday for You, Katie, Alan and I to figure this out.

**Comment by amyiridescent** [comment]
Hi Guys, so I don't think we did much with this data last year but it will be helpful. Can we please add company name as one of the questions? That will help so much with end of year reporting to companies on judge recruitment. 

Also, just to be clear, students won't see this information regarding the judges when they see the scores. Right?

**Comment by ophelieh** [comment]
@Allicolyer Great! Talk to you Thursday. :)

**Comment by Allicolyer** [comment]
Hey @amyiridescent  we already collect their company name when they sign up, and no students will not see this information.

We have decided to remove the virtual judge committee checkbox and leave this survey as is until there is a good reason to remove it.
