### ISSUE TITLE
Multiple team invites creates a buggy UI on the student dashboard [8,x,x]

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1908]
**Describe the bug**
More than one team invite looks buggy on the student dashboard

**To Reproduce**
1.Make sure team-building is turned on in the admin
2. Log in as a student account who has multiple team invites

![screen shot 2018-12-17 at 11 35 37 am](https://user-images.githubusercontent.com/11083917/50306974-db4fa900-044b-11e9-8ba3-4dfe55af3baf.png)

**Comment by hellafitz** [comment]
@ophelieh is this still a problem?

**Comment by rsgonzal** [comment]
This is still a problem! It shows multiple buttons when they have multiple invites, but they all go to the same place. There should only be one button at all times in each of these two sections. Maybe even just one button for both?

**Comment by hellafitz** [comment]
We think this'll be addressed by the redesign (separate ticket)
