### ISSUE TITLE
Mentor Training filter not working in Admin UI

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1910]
**Describe the bug**
When the `Mentor training (mentors only)` filter is used in the Participants page within the Admin UI, it works on its own but errors out when any other mentor filter is selected (`Consent waiver (mentors only)` or `Background check (mentors only)` for example).

**To Reproduce**
1. Log in as an Admin
2. Click on Participants
3. Select "Training complete or not required" in `Mentor training (mentors only)` drop-down
4. Click Search
5. Observe that the filter works fine
6. Select "Training complete or not required" in `Mentor training (mentors only)` drop-down; select "Clear (US only) or not required (International)" in `Background check (mentors only)` drop-down
7. Observe "Uh-oh, something's went wrong" message

**Expected behavior**
In step 7 in the steps to reproduce above, you should see the correct results in the participants table.

**Additional context**
Details of error:
ActiveRecord::StatementInvalid in Admin::Participants#index 
PG::DuplicateAlias: ERROR:  table name "mentor_profiles" specified more than once

**Comment by adrichey** [comment]
@Allicolyer here is that ticket we found earlier during our meeting. Just FYI. 🙂

**Comment by KaiLokken** [comment]
Tested it. Did not receive the "Uh-oh, something's went wrong" message. It produced the results: "Training complete or not required" in Mentor training (mentors only) drop-down; select "Clear (US only) or not required (International)" in Background check (mentors only) drop-down
![image 12-21-18 at 11 16 am](https://user-images.githubusercontent.com/45576084/50359594-27fdb780-0512-11e9-9744-1a7e41f688de.jpg)

**Comment by Allicolyer** [comment]
Awesome thank you @KaiLokken !
