### ISSUE TITLE
Add columns to CSVs that RAs genearate for events

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1914]
RAs can generate CSV reports for people attending their events. Here are some columns that we would like to add to those exports to help make them more useful

**Team CSV**
- Add a column for the email information for team members (students and mentors) 
- Add a column of city/state info for team location 
- Add parent emails for team members 

**Judge CSV**
- Add the company that the judge is from
- If the judge has any assigned teams - add number of assigned teams and the team names (this might require a split card)

**Comment by adrichey** [comment]
@Allicolyer can you elaborate on what this means? I am confused by the wording. Maybe I am missing something.

"If the judge has any assigned teams - add number of assigned teams and the team names (this might require a split card)"

**Comment by Allicolyer** [comment]
Hey @adrichey!

So RAs can assign teams to judges. This means that the team will appear on the judge's dashboard and the judge will only be able to judge these teams.

Let me know if you want me to walk through what this feature is and how it works

**Comment by adrichey** [comment]
@Allicolyer I would love that walk through. Or if you can give me general steps in this ticket, that works too. Whichever you prefer. I am not seeing how to do that as an RA upon first glance, so some guidance would be nice.

**Comment by adrichey** [comment]
This is now ready for testing!

**Comment by ophelieh** [comment]
Hi @nickiredescent @KaiLokken for this one you will need to log in as an. You can use ra@ra.com

**Comment by adrichey** [comment]
@KaiLokken The way you assign teams to a judge is a little weird. Basically, you need to add more than ten teams to an event, then add a judge to the event. From there, you will get a new button beside the team or judge name on either view where you can assign a judge to a team. That should then enable that CSV. I have time after 2pm PT to show you how to do this. In the meantime, you may want to create several teams for the Los Angeles area to us with testing. Thanks!

**Comment by ophelieh** [comment]
@KaiLokken Could you retest today?
