### ISSUE TITLE
Add mentor training CSV column to participants page.

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1916]
Admins need a mentor training CSV column added to the participant page. The column should say "yes" or "no" depending on if the mentor completed the training. This will complete the full set of granular on-boarding filters which are:

- Parental consent 
- consent waiver 
- background check
- mentor training 

@kmorton2017 and @adrichey  what do you think the filter should say if not training is required? I think we should put an n/a, which will align with the logic we used for the debugging information.

**Comment by adrichey** [comment]
I believe it makes sense to have "N/A" in that column if the training is not required. That is a good call!

**Comment by adrichey** [comment]
This is now ready for testing!

**Comment by kmorton2017** [comment]
i confirm that i was able to see the mentor training column and the "yes/no" responses on the participant page. I was able to download the csv file with the mentor training column visible.
