### ISSUE TITLE
Prevent students from sending parental consent to existing accounts

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1917]
**Is your feature request related to a problem? Please describe.**
This feature came up while addressing #1893. It has happened multiple times that parents create an account for their daughter and then the daughter also creates an account and then sends the parental consent form to the account created by the parent via email.

**Describe the solution you'd like**
When the student attempts to send the consent form to their parent via email, we should check to see that the email address isn't currently in the system for another account, and return an error message if does.

**Acceptance Criteria**
1. Create an account that you will attempt to send a parental consent form to. Make note of its email address. This is the "parent" account.
2. Create a new student account or log in as a student who hasn't sent a parental consent form yet. This is the "student" account.
3. Send a parental consent request to the parent account from the student account.
4. You should receive an error notice at this point saying that the email account exists in the system and you must enter a different email address.

**Comment by adrichey** [comment]
@Allicolyer What should the copy look like in step 4 of the acceptance criteria above. Can you also review the acceptance criteria for accuracy? Thanks!

**Comment by Allicolyer** [comment]
Hey Alan! This looks great!

Let's have the error message say

"This email address is already in use by another student account. Please enter a different email address."

**Comment by adrichey** [comment]
@Allicolyer and @ophelieh it looks like this check already takes place for Students. A student cannot send a parental consent email to an account with a related student profile. They can however send one to someone who is a mentor/judge/RA. Is that okay? Or do we want to stop them from sending a parental consent to **any** existing account in the system. Could there ever be a case where we have a parent mentor that signs for their child's consent? I am wondering how we should handle this. It seems like a rare case, so I want to make sure I proceed properly. If you could get back to me this soon I would appreciate it!

**Comment by ophelieh** [comment]
HI @adrichey! I thought I had responded. Some mentors are parents, so it is ok if the parent email matches another account as long as it is not a student account.

I hope that makes sense

**Comment by adrichey** [comment]
@ophelieh Okay. Then in that case there is no code change that needs to go into place for this, so we can close this ticket. I am going to close this ticket as a result. We can reopen it later or create another ticket if that logic needs to change. Thanks!
