### ISSUE TITLE
New RAs cannot save their initial location

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1918]
**Describe the bug**
For a newly invited Regional Ambassador, the location form is broken. RA's should be able to set their initial location, but cannot do so currently. They receive an error message when trying to submit the location form: "We're sorry, but we cannot find a region with that information."

**To Reproduce**
1. As an admin, go to Invite users in the Admin dashboard
2. Select Regional Ambassador under Profile Type and fill out the Email field. **Use an email address you have access to that is not currently a user**
3. Click Send Invitation to invite said user
4. Click the Confirm Email Address button in the email you receive to create your RA account
5. Fill out the form to sign up as a new RA
6. Once you are logged into the RA dashboard, click My Account in the sidebar navigation
7. Click Location in the right-hand navigation
8. Click set your location
9. Fill out the location fields (City, State, Country) and click Next
10. Observe that you receive the following message: "We're sorry, but we cannot find a region with that information."

**Expected behavior**
In step 10 of the steps to reproduce above, you would instead get to the location confirmation page where you can click "Confirm" and be redirected back to the location page of your RA profile with it saving your location properly.

Please note that this can only be done once, and after that an admin will have to change it. You will see the following message on the page where you set your location previously once you have set it:
"Regional Ambassadors cannot edit their own location.
Contact help@technovationchallenge.org if you need to make a change."

**Additional Context**
First reported by @ophelieh when several new RAs couldn't set their locations on their initial log in. Also referenced in #1878.

**Comment by adrichey** [comment]
@Allicolyer this bug has been reported by multiple RAs and is causing issues for all new RAs who sign up this season, so I have pulled it into the sprint. Tagging @ophelieh for visibility.

**Comment by adrichey** [comment]
@ophelieh this is now ready for QA testing! Thanks!

**Comment by kmorton2017** [comment]
I confirm that Steps 1-9 happened as expected. I was able to navigate to the location screen. HOWEVER, I typed in United States in the country field and pressed enter. It immediately asked me to confirm that my location was Independence, Kansas. I needed to navigate back and edit to get my correct location. 

This did not happen with an international RA sign up.

**Comment by adrichey** [comment]
That is probably due to browser behavior that occurs when hitting enter. Usually hitting enter will submit a form, so that is actually most likely intended @kmorton2017.

**Comment by ophelieh** [comment]
I was able to set the location as a new RA. However, I tried to set myself as an RA in Bethlehem in Palestine and it set me to the US - which I know is related to another ticket. 

I created a second and was able to properly set my location as Madrid, Spain. 

It's all good to go. Thank you!
