### ISSUE TITLE
Editing welcome message on user dashboards [8,?,?]

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1920]
Last year, admins were able to edit the notices section to display messages to users at key points in the year. Here are some examples of messages that we need to prominently share with users on their dashboard at various points in the season:

Jan-March: Share Your Thoughts! Take the Pre-Survey
April: Start Your Submission! Deadline: April 23, 2019 @ 5:00 PDT
May: Take the Post-Survey!

**Describe the solution you'd like**
I would like the ability to edit the green banner as an admin. Instead of the standard "Hey Welcome Back" message it could display a key notice. Right now, even if I edit the Notices section for Students and Mentors it does not change on the student/mentor dashboard. The only Notices section that is editable, is the Judges. If you edit the Notices section for judges, they will see it on their dashboard  on the right hand side in large font.

**Describe alternatives you've considered**
If we do not change the green banner, then students/mentors will still be able to access the surveys under the "More Information" section which can be easy to miss. This could decrease the number of users who take the survey.

**Additional context**
Open to any suggestions! Just trying to make prominent key action items throughout the season on dashboards.

**Label**

**Comment by Allicolyer** [comment]
Hey @kmorton2017 Is it alright if I put this in the icebox as something to revisit during registration next season? This is an awesome idea but requires UI work on the dashboards.

**Comment by kmorton2017** [comment]
that's fine we can revisit during registration next sprint.

**Comment by stenington** [comment]
@kmorton2017 I don't see a problem with doing this. I'm thinking it would show the configured message if there is one, or "Hey! Welcome back!" if there isn't one.

**Comment by stenington** [comment]
<img width="936" alt="Screen Shot 2020-07-30 at 4 41 47 PM" src="https://user-images.githubusercontent.com/55319/88972429-8446c280-d283-11ea-92e5-92b43a53f13a.png">

**Comment by hellafitz** [comment]
Note: this is separate from the Dashboard Notices, which are having some problems showing up in some circumstances
