### ISSUE TITLE
Judge Training link is broken

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1935]
**Describe the bug**
The judge training link should be this one: https://iridescentlearning.atavist.com/technovation-judge-training

**To Reproduce**
1. Log in as a judge
2. Click on the judge training link 
3. Make sure the link is correct

**Comment by Allicolyer** [comment]
We might change the link this year.

**Comment by adrichey** [comment]
@Allicolyer I am going to go ahead and complete this ticket with the link in the description. Should we need to update the link later on, we can address that in another ticket. :)

**Comment by nickiredescent** [comment]
Tested, the link leads to https://iridescentlearning.atavist.com/technovation-judge-training

**Comment by ophelieh** [comment]
Link works.

**Comment by Allicolyer** [comment]
Thanks @adrichey!

**Comment by Allicolyer** [comment]
Works great!
