### ISSUE TITLE
Judging Negative Sentiment Detector

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1936]
**Is your feature request related to a problem? Please describe.**
The negative sentiment detector was very buggy and expensive last year. We introduced it to help with negative comments and bad words, but it caused a lot of problems. For instance, it was overall buggy and caused some confusion. It also cost us a lot in API costs.

**Some possible solutions**

1. Removing it completely: This will take some work. It also puts us back at square 1 for controlling bad comments. 
2. Only running the check with the judge presses the button. This will help remove the some of the costs and some of the bugs. There might be potential problems with confusion with the UI

**Questions**

1. Were curse words really ever a problem? I think the word counter really helps with comments and eliminating one word comments.

Alan is going to do some digging to figure out how much work it would be to remove it completely.  It sounds like program team wants to remove it.

**Comment by adrichey** [comment]
@Allicolyer @ophelieh @kmorton2017 It is a pretty decent level of effort to get this done, but the code would be much more simple afterward if we were to remove the functionality, so I am okay with tackling this during this sprint. Additionally, tackling this **before** #1941 would make that development effort far easier.

**Comment by ophelieh** [comment]
If you are comfortable with removing it, then I would say let's do it! 

I feel like it caused more issues than anything last year. It is true that we will have nothing to monitor negative feedback, but I don't know how much it actually did. 

If @kmorton2017 also agrees, I think we can move forward with this.

**Comment by kmorton2017** [comment]
Yes move forward with removing the judge sentiment detector for detecting negative words.

**Comment by adrichey** [comment]
Awesome. I will try to get to this once we work through what is currently in the To Do column. I think this is doable. @stenington this is a front-end ticket that I am rather familiar with, so I will tackle this one.

**Comment by adrichey** [comment]
Something to note once this work has been completed is that we will no longer be using Algorithmia for TC after this code is removed. @stenington are you using that service for CM? If not, we may want to delete that account, or at the very least, regenerate the current API key.

**Comment by stenington** [comment]
@adrichey Nope, CM doesn't use Algorithmia.

**Comment by adrichey** [comment]
This is now ready for testing.

**Comment by ophelieh** [comment]
@nickiredescent Could you test this today as well? Basically, as a judge, you should be able to enter any word and nothing happens. 

Thanks!

**Comment by nickiredescent** [comment]
Tested, the negative sentiment detector is no longer there. The message about keeping the feedback "less than 20% negative" is still around. Not sure if the wording of that should be changed. "Remember to give positive and constructive feedback!" for example.

**Comment by adrichey** [comment]
@nickiredescent That will be removed shortly. There is a conversation on #1941 about this very thing. I will let you know when that has been removed so that you can take another look.

**Comment by adrichey** [comment]
@nickiredescent that text is now removed and the 40 word count text is now located under the word counter. You can take another pass at this now. Thanks!

**Comment by ophelieh** [comment]
Looks good!
