### ISSUE TITLE
Reduce number of words required per  comment 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1941]
Reduce the number of words required in each comment section.

@kmorton2017 and @ophelieh how many words would like you to set to?

**Acceptance Criteria**
1. As an admin, turn judging on
2. Log in as a judge
3. Judge a submission
4. Make sure that the number of words required is correct

**Comment by Allicolyer** [comment]
@RRios00 Would you have a recommendation on this? Any design principle we can follow? Our audience is telling us that 40 words is too long.

**Comment by RRios00** [comment]
I would say following the Twitter character limit of 140 or 280 characters is safe since these standards are common practice now.

**Comment by Allicolyer** [comment]
Thanks @RRios00, so the average tweet is around 55 words. I think part of our problem is that we do not count 1 or 2 letter words as part of our 40 word minimum.

**Comment by ophelieh** [comment]
Could we switch it to characters instead? And it be 200? This would include 1 or 2 letter words. 
@adrichey

**Comment by adrichey** [comment]
@Allicolyer @ophelieh and @kmorton2017, while it seems like a pretty easy fix, switching from words to characters would be a larger development effort unless we tackle #1936 first. The word count is a huge part of our sentiment and profanity analysis functionality, so I would want to address that ticket before this one. If we aren't going to be tackling #1936, then I would probably want to avoid switching to a character limit and stick with a smaller word count for the time being. Thoughts?

**Comment by ophelieh** [comment]
Ohh that makes a lot of sense! 

If it is easier to keep a word count, that's totally fine. We just want to make sure1 and 2 letter words are counted towards the total number of words. :)

**Comment by adrichey** [comment]
@ophelieh Making that code recognize one and two letter words is a low level of effort on my end. That works as well.

**Comment by ophelieh** [comment]
Perfect! Let's do that then. :) 

Thank you both!

**Comment by adrichey** [comment]
@ophelieh Just to confirm, the solution to this is to start counting one and two letter words, and leave all other functionality in place. Is that correct?

**Comment by kmorton2017** [comment]
yes switch to recognizing 1-2 letter words as part of the word count.

**Comment by ophelieh** [comment]
Correct. I think that just doing that would help a lot. Once we do that, when we do QA, we might want to add something about what the person thinks about the number of words and maybe reduce it based on feedback, IF that works for you. Otherwise, we can just keep the number of words the same.

**Comment by adrichey** [comment]
@ophelieh Of course, I am okay with reassessing this later on if we find the word count is still to high. We can create another ticket for that work and prioritize it if it still feels like too much. :)

**Comment by ophelieh** [comment]
Awesome! :)

**Comment by ophelieh** [comment]
@jessicabryan  & @nickiredescent Could you both test this today or tomorrow? 

To test you will need to:
- log in as a judge, 
- get a submission, 
- write feedback 
- see if it is counting 1 and 2 letter words (I, be...) 
- tell us if you think 40 words is too much


Thank you!

**Comment by adrichey** [comment]
Just found an issue with this card while doing the sentiment detector work. Please refrain from testing until the fix is deployed to QA. Thanks!

**Comment by adrichey** [comment]
This is once again ready for testing! Sorry for the delay. :)

**Comment by ophelieh** [comment]
No worries. All ready @nickiredescent @jessicabryan

**Comment by nickiredescent** [comment]
Tested. 

Single/double letter words registered. Random characters also were counted as words (I could submit "e" 50 times). 

I think 40 words is fine, considering the number of times judges would need to do this, this should help with burn out while still providing valuable and meaningful feedback. I felt I could say generic stuff and get up to 30, but I'd need to at least think of something relevant to hit the 40 word minimum.

I could only trigger a single prohibited word (let's just take my word on it that I tried a lot of them).  On a side note, the negativity restriction seems to work in that I could not proceed until my comment was less than 20% negative.

Not sure if relevant, but Non-Roman characters do not count at all (Chinese, Arabic, Hebrew, etc).

**Comment by nickiredescent** [comment]
Never mind, the prohibited word trigger was just slow. It's working.

**Comment by adrichey** [comment]
@nickiredescent that prohibited word functionality will be removed with #1936 which should be rolling out today, so some of that slowness will be alleviated soon. Thanks!

**Comment by ophelieh** [comment]
We might want to change where the note about 40 words is written. I didn't even see it at first. 

![uploads/806dedd4-1bbe-42b1-abd9-eb6a14d28cdb/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F806dedd4-1bbe-42b1-abd9-eb6a14d28cdb%2Fimage.png)

Could we put it after the highlighted portion? 

Also, we need to remove the portion about negativity (see my beautiful circling).

**Comment by ophelieh** [comment]
Other than that it works great. 40 words isn't too hard and forces you to actually think through your feedback and not just write generic things.

**Comment by ophelieh** [comment]
One last thing, I noticed it counts numbers. Not sure if we want it to do that.

**Comment by adrichey** [comment]
@ophelieh I will make those changes and let you know when this is ready for testing once again. Thanks! As for not counting numbers, I think we should leave those in and counting toward the count. It is a decent amount of effort to filter those out and we have always counted numbers in the past. Hopefully that is okay! I will move the required word count and remove the negativity text now in any case.

**Comment by ophelieh** [comment]
Totally fine. :)

**Comment by adrichey** [comment]
@ophelieh In order to keep the code simple and to keep the word count helper text closer to the actual count, I moved the helper text to the spot where you see "0 prohibited words" in your screenshot above. I will let you know when this is deployed to QA for testing, and hopefully you will find that works for you.

**Comment by adrichey** [comment]
This is once again ready for testing @ophelieh! Thanks again for your feedback.

**Comment by ophelieh** [comment]
Looks great. Thanks Alan!
