### ISSUE TITLE
All mentors need to be able to to switch to be judges

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1942]
**Description**
Program team has confirmed that all mentors are allowed to be judges in 2019. Mentors who have created a profile this year do not have a button to switch to judge mode. Mentors who already made judge profiles in past years do have that button to switch to judge mode.

**Solution**
We need new mentors who signed up into 2019 to also have the ability to create a judge profile and switch to judge mode. 

**Acceptance Criteria**

1. Sign up as a new mentor on the platform
2. Finish your profile
3. Confirm you can switch to be a judge

**Comment by adrichey** [comment]
After talking to @Allicolyer I want to expand on the scope of this work. Mentors should always have a "Switch to judge mode" link; Judges have the inverse version of this where they have a "Switch to mentor mode" link that logs them in as a mentor. When that "Switch to judge mode" link is clicked, a judge profile should be created and they should be switched to judge mode.

**Comment by Allicolyer** [comment]
@nickiredescent can you test this?

**Comment by nickiredescent** [comment]
Tested and confirmed that as a mentor, I can be whatever I set my mind to (a judge).

**Comment by adrichey** [comment]
Thanks @nickiredescent!
