### ISSUE TITLE
RAs should not see scores from virtual judging until scores are released 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1944]
**Is your feature request related to a problem? Please describe.**
RAs can see scores from virtual judging in real time, before we have formally released scores to the public. This caused many customer service problems last year. RAs either complain to us about what they are seeing or tell the girls what their scores are.

- RAs should see scores from events
- RAs should *not* see virtual scores
- RAs should see virtual scores once scores are released

**Possible Solutions**

- Alan can link this to the season toggle. RAs will only see virtual scores once this season toggle is on.
- Link it to the scores and certificates toggle
- RAs never see virtual scores -- why would they ever need this anyway? (not recommended)
- Leave it how it is and improve messaging when RAs complain. Tell them we are working on score issues and will get around to it soon. 

**Other things to consider**
- Filters on RA score page might need to change
- Seeing scores from past seasons.

**Comment by kmorton2017** [comment]
update from meeting 02/08: do not prioritize this

**Comment by stenington** [comment]
I know this was de-prioritized, but I'm going to see if I can do it while waiting for the results of judging exploratory QA.

**Comment by stenington** [comment]
I believe these are the two places, along with the CSV download, that RAs would see scores: the scores page and score details page.

![technovation-qa herokuapp com_regional_ambassador_scores](https://user-images.githubusercontent.com/55319/53362687-b7f02100-3908-11e9-9b4c-4fd3b1d268a1.png)

![technovation-qa herokuapp com_regional_ambassador_score_details_59](https://user-images.githubusercontent.com/55319/53362686-b7f02100-3908-11e9-80a9-05ae35c15079.png)

What I can look in to doing is for RAs only, filtering down the teams shown and hiding various parts of pages or columns until scores are made accessible by changing the admin setting. While scores are not generally accessible, the scores page would:
* only show teams attending official RPEs
* not show any semifinals columns

and the score details page would:
* not show sections related to semi-finals

After scores are made available, the RAs would essentially see what admins see (but limited to teams in their region of course).

**Comment by stenington** [comment]
@adrichey can you give me a gut-check on whether the proposed solution above would fix this issue?

**Comment by adrichey** [comment]
I believe that sounds like a good solution, Mike. That was essentially what I had proposed with Alli when this ticket was created. That we basically lock things down for RAs based on whether the Score & Certs Available toggle was turned on.

I am going to tag @ophelieh and @kmorton2017 for one of them to look at the solution as well.

**Comment by ophelieh** [comment]
Seems like a good solution to me as well. Thank you @stenington and @adrichey

**Comment by ophelieh** [comment]
**Scenario 1**
As an admin, set judging mode. Set quarterfinals then finals. 
For each round, log in as an RA and check that you: 
* Can see scores from events
* Cannot see virtual scores

**Scenario 2**
As an admin change settings to Scores and Certificates. Log in as an RA and check that you can now see all scores 

@nickiredescent @kmorton2017 Could both of you test this? Thank you!

**Comment by nickiredescent** [comment]
Scenario 1
Works fine when Quarterfinals are on.
When Semifinals are on, I am still and only seeing quarter final scores (the list is the same, only teams who attended my event)
Also attached screenshot's team quarterfinal average score is at 0 for some reason.

![image](https://user-images.githubusercontent.com/45576078/53533751-e3157480-3ab0-11e9-82a6-40966be0c61f.png)

Scenario 2
As an RA, I am able to see all scores, Semifinal averages are also shown. Semifinal scores are shown in score details.

**Comment by stenington** [comment]
@ophelieh @nickiredescent I understood this one a little differently. My understanding was that for an RA:
* when **Content & Settings > Scores & Certificates > Scores & Certificates accessible** is off, RAs should only see live event QF team scores, and they shouldn't see any semifinals columns or data on the details page
* when **Content & Settings > Scores & Certificates > Scores & Certificates accessible** is on, RAs can choose to see quarterfinals or semifinals team scores, and they can see semifinals columns and data on the details page

Admins on the other hand should be able to see all QF and SF data as it comes in.

I think one un-intuitive thing I've done is that RAs can both quarterfinals and semifinals in the **Round:** selector at all times, but it will force it back to quarterfinals if **Scores & Certificates accessible** is not on. I know that's weird user experience, but that's what it was already doing and it's all I could figure out how to do quickly. We could work on improving that later though.

So my recommended QA would be something more like:

**With Scores & Certificates accessible off**

*RA*
1. Log in as an RA
2. Confirm that only teams at live events in the quarterfinals show
3. Confirm that trying to select *semifinals* as the round forces it back to *quarterfinals* after running the search (the crappy UX we can work to improve on later)
4. Confirm that semifinals columns aren't available on the search page
5. Confirm that semifinals data doesn't appear on the details page

*Admin*
1. Log in as an Admin
2. Confirm that live and virtual quarterfinals teams show
3. Confirm that you can select semifinals and see semifinals teams
4. Confirm that you can see semifinals columns
5. Confirm that you can see semifinals data on the details page

**With Scores & Certificates accessible on**

*RA*
1. Log in as an RA (which should now behave like the previous admin scenario)
2. Confirm that live and virtual quarterfinals teams show
3. Confirm that you can select semifinals and see semifinals teams
4. Confirm that you can see semifinals columns
5. Confirm that you can see semifinals data on the details page

**Comment by ophelieh** [comment]
@nickiredescent Could you re-test with the scenarios mentioned by Mike? 

Thank you!

**Comment by ophelieh** [comment]
@KaiLokken If you have some time today or tomorrow could you also test this? See the last comment from Mike. 

Thank you!

**Comment by KaiLokken** [comment]
With Scores & Certificates accessible off
_RA_

1. Log in as an RA-Logged in as Big Bird RA
2. Confirm that only teams at live events in the quarterfinals show
_-Confirmed, only teams at live events in the quarterfinals show_
3. Confirm that trying to select _semifinals_ as the round forces it back to _quarterfinals_ after running the search (the crappy UX we can work to improve on later)
_-Confirmed, it forced it back to quarterfinals_
4. Confirm that semifinals columns aren't available on the search page
_-Confirmed, semifinals columns were not available on search page_
5. Confirm that semifinals data doesn't appear on the details page
_-confirmed, no semifinals data appears_

_Admin_

1. Log in as an Admin
2. Confirm that live and virtual quarterfinals teams show
_-it shows quarterfinals AND semifinals teams/scores for both live and virtual, even though the round is designated as quarterfinals_
3. Confirm that you can select semifinals and see semifinals teams
_-when i select semifinals as the round, semifinals teams do not show up for live event scores- only for virtual scores_
4. Confirm that you can see semifinals columns
_-confirmed, semifinals range pops up under more columns_
5. Confirm that you can see semifinals data on the details page
_-I can see semifinal and quarterfinal data_ 

**With Scores & Certificates accessible on**

_RA_: _Same responses as above/Admin_

1. Log in as an RA (which should now behave like the previous admin scenario)
2. Confirm that live and virtual quarterfinals teams show
3. Confirm that you can select semifinals and see semifinals teams
4. Confirm that you can see semifinals columns
5. Confirm that you can see semifinals data on the details page

**Comment by stenington** [comment]
> it shows quarterfinals AND semifinals teams/scores for both live and virtual, even though the round is designated as quarterfinals

Yeah, the page is confusing, and it doesn't help that our test data is set up in a way that can't happen for real in that some teams only have semifinals scores. So here's how I understand the page. Let's look at team Hotdogs.

They have 2 QF scores, and 1 SF score:

![technovation-qa herokuapp com_admin_score_details_23](https://user-images.githubusercontent.com/55319/53651989-d3637080-3c15-11e9-99c4-907fad2365ae.png)

So if I look at them with **round=quarterfinals**, I see this:

![screen shot 2019-03-01 at 11 31 57 am](https://user-images.githubusercontent.com/55319/53652067-f726b680-3c15-11e9-914b-9b4a0cb63c03.png)

Contest rank says semifinalist because Hotdogs is a semifinalist team, but the Complete scores/Incomplete scores columns are referring to **QF scores only** on this page. Their QF and SF average is shown, presumably because it's useful when viewing semifinals scores to know how the teams did in the quarterfinals, but that's a guess.

So now if I choose **round=semifinals** I see:

![screen shot 2019-03-01 at 11 32 08 am](https://user-images.githubusercontent.com/55319/53652191-47057d80-3c16-11e9-9097-c55bbf769e21.png)

Only 1 complete score, because they only had 1 complete semifinals score. Again many of the other columns don't change.

> when i select semifinals as the round, semifinals teams do not show up for live event scores- only for virtual scores

I don't think there are live events in the semifinals, I think semifinals are all virtual, right?

**Comment by ophelieh** [comment]
Thank you @KaiLokken for testing and @stenington for the feedback.

"it shows quarterfinals AND semifinals teams/scores for both live and virtual, even though the round is designated as quarterfinals"
* this will not be a problem is "real life" as when we are in quarterfinals there will not be any semifinals scores unlike on QA. 

"when i select semifinals as the round, semifinals teams do not show up for live event scores- only for virtual scores"
* Live events are only for quarterfinals. 

Just tested it as well. Looks great! Thank you. :)
