### ISSUE TITLE
Ajax calls error reporting research

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1945]
**Description**
We would like to take a look at judging Ajax Calls to make sure error reporting (to user and to us) exists when they fail

**Solution**
Make sure user gets feedback when Ajax calls fail. Additionally, report failures to Airbrake.

**Additional Info**
Two bugs from last year inspired us to write this card

- Judges were unable to select numbers in some cases
- Some judges experienced loading issues with the first submission judged

**Comment by adrichey** [comment]
This is a developer testable ticket. I will be testing this shortly and will close it if things look okay on the platform.

**Comment by adrichey** [comment]
This has been tested on QA. I was able to receive an Airbrake notification without issue and it was labeled properly within Airbrake. I have added testing notes here: https://docs.google.com/document/d/1rs0zQBWeV3XxGq9NHVWGCTMSXnsKOLWtrDSH_6R89mI/edit?usp=sharing
