### ISSUE TITLE
Students with @alumno.fomento.edu email cannot create accounts

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#1952]
**Describe the bug**
Students with the email ending with  **@alumno.fomento.edu**  cannot sign up on the platform. (this is a similar issue to students unable to create accounts with their @qq.com email - see ticket #1790). 

**To Reproduce**
1. Create a student account with NAME@alumno.fomento.edu
2. You cannot sign up

**Expected behavior**
All students are able to sign up with their school email. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32206421/51860590-c8a87980-22ff-11e9-855a-2801ef031a52.png)

_Note: I chose priority 2 because it affects users trying to create accounts, but doesn't impact too many users._ 

Thank you!

**Comment by adrichey** [comment]
@ophelieh this is now ready for testing on QA. Once this is tested, I will cut another production release once the QA column is clear. I will try to get that done as soon as possible. Thanks!

**Comment by ophelieh** [comment]
Works great. Thanks @adrichey !
