### ISSUE TITLE
Ability to filter mentors by their industry (ie parent, teacher, etc.) [13,5,2.6]

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1954]
**Is your feature request related to a problem? Please describe.**
Admins would like the ability to filter mentors by their industry, parent, educator, industry professional. This is needed for grant reporting.

@kmorton2017 can you tell us how important this is? Is it okay to get to this next season?

**Comment by kmorton2017** [comment]
it would be ideal if we could get to this feature by june 1st. we need to submit a report to salesforce with the # of educators. 

right now amy's csv files/data clips are sufficient in the short-term, but it would make it a lot easier to have this feature built!

as an admin i would like the ability to go to the participant's page and use a filter for Mentor Industry to select: "Industry Professional, Parent, Educator, or Past Technovation Student"

tagging @ophelieh for visibility and @adrichey for sprint planning

**Comment by rsgonzal** [comment]
This is a filtering issue on the admin

**Comment by hellafitz** [comment]
@ophelieh is there any specific timing for when you'd like this data now?

**Comment by ophelieh** [comment]
Hi Matt! I think anytime by November would be optimal. Do you think that's doable?

**Comment by stenington** [comment]
I've added a "Mentor Type" filter on the Participants page, and an optional "Mentor type" column. I don't have a specific QA proposal for this one, other than asking the program team to take a look and let us know if this accomplishes what they need.

**Comment by rsgonzal** [comment]
Mackenzie and Ophelie took a look and it fulfills their needs
