### ISSUE TITLE
Static Page that contains Thunkable's promo code

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1956]
**Problem**

Thunkable wants a way to guarantee a person using their promo code has a Technovation account. Right now their promo code is in our curriculum, and our curriculum is an open web page. You can see that here: https://technovationchallenge.org/curriculum/coding-1/#act2

**Some Solutions**
1. Send the promo code in an email 
- this will create an insane headache when people cannot find our welcome email
2. Put the promo on a static page on requires a log in to our Rails app. Put a link to the static page in place of the image of the promo code is is now. 
- I think this is the best option.
3. Put the promo code under the "helpful links" menu on people's dashboard.
- I think this will also be really hard for people to find and also doesn't really make sense.

@adrichey, I can discuss this with you tomorrow. Thunkable's developer, Paul, also offered to code up the static page himself and create a pull request on our app. I know you have mentioned that you are open to people doing that, I wasn't sure how serious you were though :)

**Comment by Allicolyer** [comment]
1. On the submission page, if you choose Thunkable it will display the promo code
2. Static Page - figure out where this would live in the app.

Alan needs: Exact text that should be on the static page and where we want to link it

**Comment by kmorton2017** [comment]
Static Page Text will be the following: 

1. Go to https://x.thunkable.com/event/5bc11dbb1c9d440000725286
2.  Log in with your gmail account. If you don’t have one, you should make one now.
3. Type in the code in this picture: 

This code will give you a free trial of Thunkable PRO. Thunkable PRO allows you to create private projects, that way you can keep your apps secret during the Technovation Challenge. If you decide not to purchase Thunkable PRO, no worries, just please note that your apps will become public after the competition.

![uploads/99d218ec-1689-40e7-82d5-7fd60e711217/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F99d218ec-1689-40e7-82d5-7fd60e711217%2Fimage.png)

@adrichey let me know if you would like me to provide the word press text changes here

**Comment by adrichey** [comment]
The proposed solution for this is to create a static information page within the platform with the copy Katie referenced previously. This page will only be accessible if the user is signed in. On the WordPress site, we will remove the promo code and add a link to the static information page within the platform. When a user clicks this link, they will be prompted to log in if they have not already done so, and will then be redirected to the promo code information page.

Additionally, if a student or mentor hits the submission Source Code Upload page, if they select Thunkable as their project, they will see the link to the information page with the promo code there as well. This way we have visibility to that page from both the WordPress and platform side of things.

@kmorton2017 or @ophelieh should we display this link for the Thunkable Classic option in the submission source code upload step as well even though they won't be using Thunkable Pro? That functionality will be in place before this (See #1939 for details).

**Comment by adrichey** [comment]
This is ready for testing. The way you get to the informational page is by visiting: https://technovation-qa.herokuapp.com/general_info/get_started_with_thunkable. You can also get to the page by selecting Thunkable as your development platform (see first screenshot below).

![uploads/ba24be14-ad55-4473-a71b-ca6794f1b0e7/link_to_thunkable_page.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fba24be14-ad55-4473-a71b-ca6794f1b0e7%2Flink_to_thunkable_page.png)

![uploads/7998afb1-d8ab-47ee-8d79-e0bf7411f91f/get_started_with_thunkable.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7998afb1-d8ab-47ee-8d79-e0bf7411f91f%2Fget_started_with_thunkable.png)

Please note that this ticket has a WordPress component that has not been completed yet. That will be addressed by #1981 after this has been deployed to production.

**Comment by ophelieh** [comment]
@KaiLokken Could you test this today or tomorrow? 

Thank you!

**Comment by kmorton2017** [comment]
i confirm that i was able to access this splash page from the link you provided. Using the "go back" button I was able to navigate back the dashboard. 

I am also able to view the code in the development platform section.
