### ISSUE TITLE
Improve Admin UI for Teams view

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1960]
**Is your feature request related to a problem? Please describe.**
Right now, the sticky-cols functionality for the team roster views in the admin panel is jarring. When loaded, if the content is larger than the side navigation when viewing a team, the content gets cut-off and is hidden behind the other debugging information on that page.

**Describe the solution you'd like**
I would like to see the CSS of all of the panels match (having a slight drop shadow and consistent spacing), and also not have the content covered up upon initial load.

**Additional context**
Developer note: Let's just remove the sticky-cols on this page. They don't work well with the tabs having such dynamic content and there are alternatives should we want to bring that functionality back at some point.

**Screenshots**
![screen shot 2019-02-01 at 3 11 28 pm 2](https://user-images.githubusercontent.com/1534554/52150019-3fad7d00-2634-11e9-8072-a609b6749ee9.png)

**Comment by adrichey** [comment]
Dev note: Addressed by #1958.

**Comment by nickiredescent** [comment]
Tested, viewing teams is clean. I have no observed overlapping panels. 

![uploads/d31ae160-1a4b-4e81-a618-f51c224d8766/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd31ae160-1a4b-4e81-a618-f51c224d8766%2Fimage.png)

**Comment by adrichey** [comment]
@nickiredescent Thanks for testing!
