### ISSUE TITLE
Participant seeing a Blank Account

### ISSUE THREAD

**Issue by nickiredescent** [Iridescent-CM/technovation-app#1961]
**Describe the bug**
A user on our platform is encountering an issue where their dashboard is blank. This could be due to email switching done in the process of creating the account. Here is a link to a google doc with the user's information: [link](https://docs.google.com/document/d/1yANf_dNX4-QPZ-SYIAepEtyRjIe_bWbuemsW6W2B_tY/edit?usp=sharing)

**To Reproduce**
1. Log into affected participant's account
2. Observe that the dashboard has no clickable options.

**Comment by Allicolyer** [comment]
Also thanks Nick!

**Comment by adrichey** [comment]
I looked into this a bit this morning and something more is going on here than just the parental consent. I think we might have some broken logic somewhere. I pulled the production data, removed the student's parental consent, and the bug remains. I will update this once I have made more progress.

**Comment by adrichey** [comment]
I have found the issue. There is a problem with the logic block for email confirmations in the UI so it isn't displaying the way it should. I will let you know once the fix is deployed to QA for testing. For now, I would recommend that you tell the user that they must confirm their email account via the email we sent them when they made that change, @nickiredescent. They will not be able to access anything until they have done so.

**Comment by adrichey** [comment]
This is now ready for testing.

**Comment by nickiredescent** [comment]
Tested and works.

Created accounts recreating the scenario to the best of my knowledge. When changing the emails associated with the accounts, both profile types produced a screen where I could not proceed until the new email was confirmed. I also received all confirmation emails. Upon confirmation, the accounts could be used as normal.

![image](https://user-images.githubusercontent.com/45576078/52230488-5b9b6380-286c-11e9-9770-6135dd3f4412.png)

Thanks so much for looking into this!

**Comment by adrichey** [comment]
@nickiredescent Great! Thanks for testing this. I will roll this out to production as soon as we can get through the rest of the Test column on Huboard. Marking this as closed.
