### ISSUE TITLE
XAdmin Searching for Unmatched Mentors in CA

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1966]
**Describe the bug**
I am having trouble finding mentors from California that are unmatched.

**To Reproduce**

1. Go to Participant page
2. Click 2019 season
3. Click on Profile Type--Mentor. Use United States, and California as location filters.
4. Use Team Matching (Unmatched) filter
5. Select Company name as column. 
6. Sort company name by ascending order. 
7. Get error message

**Expected behavior**
I would like to see a list of all unmatched mentors from 2019 who are from California. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser Chrome
 - Version 71.0.3578.98

**Comment by hellafitz** [comment]
@rsgonzal can you clarify what's problematic? Do we need another way to display the results? What do you recommend?

**Comment by rsgonzal** [comment]
You get the results, but you can't sort by company name for some reason. You can sort by other columns.

**Comment by rsgonzal** [comment]
Closing, entire search could use an upgrade
