### ISSUE TITLE
Make all judging dates configurable 

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1971]
**Description**

Some dates that describe when judging rounds start and stop are hard-coded in the app. This is a potential problem because exploratory QA of judging was conducted outside of these dates, and so it wouldn't not have fully simulated what the actual judging season looks like, despite being able to toggle quarterfinals and semifinals judging through the admin.

**Solution**

Instead of hard-coding dates in `app/technovation/season_toggles/judging_round_toggles.rb`, do the following:

* change `ImportantDates` to read these dates from the environment
* adjust `current_round_deadline` to use the appropriate `ImportantDates` date instead of tacking on 2 days in the case of quarterfinals for live events
* introduce a new `ImportantDates` element that replaces the `ImportantDates.semifinals_judging_ends + 3.days` found in `_between_rounds.en.html.erb`

As a first step, this will let us do another round of exploratory QA fully simulating what judging could look like. 

**Additional Info**

There will still be an implicit contract that the platform be switched into and out of various judging rounds in a way that lines up with the dates configured in the environment. This isn't ideal for transparency of how to configure and administrate the app, but if we can document those connections as we do exploratory QA again, that should be sufficient for this year.

**Comment by adrichey** [comment]
Thank you for creating this ticket, Mike.

**Comment by stenington** [comment]
@adrichey Do you feel any particular QA is needed here? I think the exploratory QA happening now is evidence that this change is working, right?

**Comment by adrichey** [comment]
@stenington I am okay with calling this good. My main thing was that I wanted to make sure that I could get to the between rounds screen using the dates, which I was able to reproduce. So in my opinion, this can be closed. I updated the production dates to match those confirmed by Katie as well. So I will close this.
