### ISSUE TITLE
Update TC site to reflect Thunkable info page changes

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1981]
**Is your feature request related to a problem? Please describe.**
This is a follow up ticket to #1956.

**Describe the solution you'd like**
We need to link to https://my.technovationchallenge.org/general_info/get_started_with_thunkable instead of displaying the promo code information on the following page of our TC website: https://technovationchallenge.org/curriculum/coding-1/#act2

**Additional context**
See #1956 for more details. This work must be done **_after_** #1956 is deployed to production.

**Comment by kmorton2017** [comment]
just want to check in and see if this can be pushed to the to do column since 1956 is deployed!

**Comment by adrichey** [comment]
@kmorton2017 the test column needs to be completely clear in order for me to deploy to production, so this code is not live. We have a lot going out this release and exploratory QA has been holding us back. I will move this conversation to Slack this morning.

**Comment by adrichey** [comment]
This WordPress work has been completed and can be found here: https://technovationchallenge.org/curriculum/coding-1/#act2

**Comment by kmorton2017** [comment]
can we do the following? the below is approved by our partners at Thunkable:

- remove 1 and 2 since those are redundant (same text is on the static page already) and could be confusing

- change #3 to say : visit the following link to receive a promo code for Thunkable PRO: https://my.technovationchallenge.org/general_info/get_started_with_thunkable/

**Comment by adrichey** [comment]
@kmorton2017 I didn't have time to get to this today. I will work on this once I get back on Tuesday. If it needs to be done before then, Maggie should be able to make those changes to that page for you.

**Comment by adrichey** [comment]
This is once again ready for testing @kmorton2017

**Comment by ophelieh** [comment]
@nickiredescent and @kmorton2017 Could you test this? 

Thank you!

**Comment by nickiredescent** [comment]
Tested. The link shows in the curriculum and can only be followed if I log into the platform.
