### ISSUE TITLE
Bug: Copying/Pasting Email into Development platform [1,1,1]

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1983]
**Describe the bug**
I've been encountering some issues with the development platform component of the submissions. It appears that if I copy and paste an email address into the development platform field, it marks it as invalid. Specifically, this field: WHAT IS THE GMAIL ADDRESS OF THE APP INVENTOR ACCOUNT THAT YOUR TEAM IS USING?

**To Reproduce**
1. Go to the "development platform" part of the submission.
2. Choose App Inventor or Thunkable as your development platform
3. Type in a name for your project.
4. Copy/paste email.
5. Get a message that the email is invalid and the name of the project is invalid.

**Expected behavior**
I would expect to be able to copy/paste an email without any issues. Granted, many users may not be copying/pasting emails like we do on QA but it could surprise some users. 

**Screenshots**
See gif.
![mentor submission](https://user-images.githubusercontent.com/32206427/52752280-17643d80-2fa7-11e9-9a82-d1bd09e9fb27.gif)

**Desktop (please complete the following information):**
 - OS: Mojave, version 10.14.2
 - Browser Chrome
 - Version 72.0.3626.96

**Comment by stenington** [comment]
My hypothesis is that the email pasted has a space character at the end that isn't being stripped.
