### ISSUE TITLE
Code Checklist-Paper Prototype and Pseudocode 

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1984]
**Describe the bug**
I tried to upload a file called "paper-prototype" into the prototype section of the code checklist. I also tried to upload a file called "pseudocode" into the pseudocode section of the checklist. The first time it happened, it selected a random screenshot on my computer for both (see thunkable logo). I tried again to choose the correct file for both the prototype and pseudocode sections. This time, the same file (pseudocode) appeared for both. 

**To Reproduce**
1. Start a submission.
2. Click on code checklist.
3. Scroll down to paper prototype and select a file. 
4. Scroll down to flowchart or pseudocode and select a file 
5. See the same image appear for both.

**Expected behavior**
I would expect these to be different images for the prototype and flowchart or pseudocode sections. 

**Screenshots**
![flowchart or pseudocode](https://user-images.githubusercontent.com/32206427/52810655-e556e800-3047-11e9-8dab-0b3e9dd4f88c.gif)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Macbook Air 
 - OS: OS Mojave
 - Browser Chrome
 - Version 10.14.2

**Additional context**

**Label**
You MUST use the label menu to add 'bug' and '0 - To discuss' as a label
(do *not* choose a bug priority label, devs will do that according to the Defect Priority matrix)

**Comment by kmorton2017** [comment]
@ophelieh  @adrichey @stenington this same issue was brought up by a user today on zendesk.(Text below)  Since we are encouraging students to start submitting, can we move this into the to do column? 

We seem to be having problems with uploading our flowchart and paper prototype. We originally had a paper prototype and flowchart uploaded. We then uploaded a better version we had created of our paper prototype which had for some reason uploaded in the flowchart area as well. When I went into the code checklist today it says for both the flowchart and the paper prototype 'Unprocessed uploads'. When I tried to re-upload our flowchart and paper prototype it wouldn't work. Your help would be greatly appreciated.

**Comment by ophelieh** [comment]
@stenington or @adrichey Would you be able to look into this? 

Thank you!

**Comment by stenington** [comment]
I can start looking at this one.

**Comment by adrichey** [comment]
Thanks for getting to this @stenington. Sorry, email got away from me today.

**Comment by adrichey** [comment]
There have been some Airbrake JS errors today around this area. I am not sure if they are directly related, but it might be a good idea to check there when you start this @stenington.

**Comment by stenington** [comment]
Acceptance criteria:
1. Start a submission.
2. Click on code checklist.
3. Scroll down to paper prototype and select a file.
4. Scroll down to flowchart or pseudocode and select a different file
5. Click Save checklist
6. Click on code checklist.
5. Confirm that the correct images uploaded in the correct spots.

**Comment by ophelieh** [comment]
@kmorton2017 and @nickiredescent  Could you both test this today or tomorrow? 

Thank you!

**Comment by nickiredescent** [comment]
Tested. The uploaded pictures are appearing in the correct places for me.
