### ISSUE TITLE
Admin Events Page - Seeing the Wrong Number of teams

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#1985]
**Describe the bug**
As an admin, when I look at an event, I can see the numbers of teams. However, when I click on that event, sometimes the number of teams is different than on the main page. 

**To Reproduce**
1. Go to 'Events'
2. Look at team count
3. Click on 'View' under Action
3. Look at number of teams 
4. See actual number of teams 

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/32206421/52869117-902fda80-310a-11e9-86da-a11c0902cf28.png)

![image](https://user-images.githubusercontent.com/32206421/52869144-9d4cc980-310a-11e9-9490-63f37220fd1a.png)

![image](https://user-images.githubusercontent.com/32206421/52869172-accc1280-310a-11e9-8de0-6fa23dd93fc7.png)

**Comment by stenington** [comment]
Ok, this should be fixed. QA suggestions:

1. Go to 'Events'
2. Look at team count
3. Click on 'View' under Action
4. Look at number of teams
5. Confirm that the two counts match
6. Remove a team
7. Confirm that the team count updates correctly
8. Add a team back
9. Confirm that the team count updates correctly

**Comment by kmorton2017** [comment]
i wasn't able to do steps 8 and 9 with exploratory QA settings enabled (cannot add teams back with these settings) , but i was able to do 1-8 and confirm that the count updated

**Comment by stenington** [comment]
RAs can add teams even when judging is enabled, can't they? I know teams or mentors can't add themselves, but I believe RAs can change their event teams and judges at any time.

**Comment by kmorton2017** [comment]
hmmm it was telling me there were . no more teams left for me to add even tho there were definitely LA teams i could add to my event

**Comment by stenington** [comment]
Oh, okay, let me look in to that @kmorton2017. I was working locally, not on staging, so let me see if there's an explanation for that.

**Comment by stenington** [comment]
@kmorton2017 I don't see anywhere obvious that the season toggles would be preventing you from adding teams back. Which event and which team was it?

**Comment by ophelieh** [comment]
This works great! Thank you! :)
