### ISSUE TITLE
Force users to enter a location and data agreement

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1987]
Right now, users who have been invited to the platform without going through the registration form do not have to enter a location or adhere to the data agreement when they log in. After speaking with Katie and Ophelie, it is desirable to have all users fill out the data agreement and enter a location for data collection and event/workshop matching purposes.

**Proposed Solution**

We create a route guard on the platform when the user logs in and visits any page.
- If they don’t have a data agreement on file, we reroute them to the data agreement form so that they are forced to agree before they can continue.
  - We display some informational text on the data agreement form that tells them that they need to have the agreement on file before they can continue using the application as normal.
- Once they have a data agreement on file, if they don’t have a city/country on file, we reroute them to the location form so that they are forced to enter a location.
  - We display some informational text on the location form that tells them that they need to have a location on file before they can continue using the application as normal.
- Once they fill out the data agreement enter a location, they can route to other places on the platform as usual.

**Notes**
- The preferred deadline for this is March 20th, with April 1st at latest.
- @ophelieh and @kmorton2017 will provide copy for the message on the location form to the end-users.

**Acceptance Criteria For Testing**

@adrichey will provide testing accounts for these scenarios. Reach out to him before testing.

Scenario 1 - Data agreement missing, location present
1. Log in as a user without a data agreement, but location present (Alan to provide account)
2. Attempt to click links or navigate to different sections of the platform
3. You should be rerouted to the data agreement form and receive a message about why you must agree to the terms
4. Read the data agreement terms and check the agreement checkbox; submit the form
5. Confirm that you can now use the application as normal now that you have a data agreement on file and a location is present

Scenario 2 - Data agreement present, location missing
1. Log in as a user without a location (city and country present), that has agreed to the terms (Alan to provide account)
2. Attempt to click links or navigate to different sections of the platform
3. You should be rerouted to the location form and receive a message about why you must enter a location
4. Enter a location
5. Confirm that you can now use the application as normal now that your location is present

Scenario 3 - Data agreement missing, location missing
1. Log in as a user without a data agreement or location data (Alan to provide account)
2. Attempt to click links or navigate to different sections of the platform
3. You should be rerouted to the data agreement form and receive a message about why you must agree to the terms
4. Read the data agreement terms and check the agreement checkbox; submit the form
5. Attempt to click links or navigate to different sections of the platform
6. You should be rerouted to the location form and receive a message about why you must enter a location
7. Enter a location
8. Confirm that you can now use the application as normal now that your location is present and you have agreed to the terms of use

**Comment by adrichey** [comment]
Marking as blocked since we need copy.

**Comment by ophelieh** [comment]
Hi @adrichey! Here is the text Katie and I agreed on: "You have been brought to this page because your location is missing. After you enter your location, you will be brought back to your dashboard. Thank you!"

**Comment by adrichey** [comment]
Awesome! Thank you both for putting that together! I will mark this as being unblocked.

**Comment by adrichey** [comment]
This is also an issue for accounts without a data agreement. So the proposed solution needs to be expanded to cover accounts without a data agreement.

If the end-user doesn't have a data agreement, they should be rerouted to a form with the data agreement checkbox and information and not be able to continue until they have agreed to that.

From here they will be redirected to the dashboard if they have a location. If not, they will be redirected to the location form and will not be able to navigate away until they have filled that out.

**Comment by adrichey** [comment]
@kmorton2017 and @ophelieh, can you please let me know if this copy is okay to display for the end-user who needs to agree to the terms for to use the site?

"You have been brought to this page because you must agree to the data use terms before participating in Technovation. After you agree to these terms, you will be brought back to your dashboard. Thank you!"

**Comment by ophelieh** [comment]
Perfect. Thank you @adrichey

**Comment by adrichey** [comment]
@ophelieh @kmorton2017 and @amyiridescent, do we need to force RAs to agree to the data use agreement terms? I am forcing mentors, students, and judges to agree right now, but since RAs don't sign up in the same way as our other users, do we need this?

**Comment by amyiridescent** [comment]
I think there might be language regarding this in the RA agreement then sign. @ophelieh can you confirm? If it is already on the agreement they sign, I don't think we need to force it again on the platform.

**Comment by ophelieh** [comment]
It is included in the MOU so @adrichey you don't need to worry about the RAs. :) Thanks for checking!

**Comment by adrichey** [comment]
This is now ready for testing. I have created three accounts to test this with:
- alan+missinglocationandterms@iridescentlearning.org
- alan+missinglocation@iridescentlearning.org
- alan+missingterms@iridescentlearning.org

For alan+missinglocationandterms@iridescentlearning.org:
1. Log in as the user (Do not log in through admin, please see our QA Slack channel for passwords)
2. Assert that you are brought to the terms agreement form and cannot leave until you either log out, or agree to the terms
3. Assert that after you agree to the terms, you are brought to the location form and cannot leave until you either log out, or save your location
4. Assert that once terms agreement and location are filled out, you can use the site as normal

For alan+missinglocation@iridescentlearning.org:
1. Log in as the user (Do not log in through admin, please see our QA Slack channel for passwords)
3. Assert that you are brought to the location form and cannot leave until you either log out, or save your location
4. Assert that once the location has been filled out, you can use the site as normal

For alan+missingterms@iridescentlearning.org:
1. Log in as the user (Do not log in through admin, please see our QA Slack channel for passwords)
2. Assert that you are brought to the terms agreement form and cannot leave until you either log out, or agree to the terms
4. Assert that once terms agreement has been agreed to, you can use the site as normal

**Comment by ophelieh** [comment]
@nickiredescent and @KaiLokken Could you both test this today or tomorrow? 

Thank you!

**Comment by nickiredescent** [comment]
Tested. All accounts work as described. 
alan+missinglocationandterms@iridescentlearning.org
 - works as intended; I cannot proceed without agreeing to the terms and then inputting my location data. Message appears to inform me why I cannot proceed to my account.

alan+missinglocation@iridescentlearning.org
 - works as intended; I cannot proceed without inputting my location data. Message appears to inform me why I cannot proceed to my account.

alan+missingterms@iridescentlearning.org
 - works as intended; I cannot proceed without agreeing to the terms Message appears to inform me why I cannot proceed to my account.

**Comment by KaiLokken** [comment]
Tested it- I think that since Nick tested it first, the first two email addresses went directly to the account. The last email address, I had to complete the parent consent form before it would allow access to the account.

**Comment by ophelieh** [comment]
Great. Thank you both! :)
