### ISSUE TITLE
Receiving "team not fully onboarded" warning even though all members have completed their registration

### ISSUE THREAD

**Issue by nickiredescent** [Iridescent-CM/technovation-app#1989]
**Describe the bug**
A team is receiving a warning that they are not qualified to compete because a student has not completed their registration. However, no student name is listed and every member has completed their onboarding. Further information can be seen in [this doc](https://docs.google.com/document/d/12I4fsYk4vu4z60wjAZX774KToIAufa3GFC6EnPp0CvU/edit?usp=sharing).

**To Reproduce**
1. Log in as any of the affected students on the team.
2. Navigate to "My Team's Submission"
3. Observe the warning that appears on the side bar.

**Expected behavior**
A fully onboarded team should not be seeing this error.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by adrichey** [comment]
@nickiredescent this has been fixed for that team. For some reason, the team's "all students onboarded" flag did not get set properly. I simply had to make a change to the team's summary, save, and then revert that change and save again to get that flag updated. They are good to go now.

**Comment by adrichey** [comment]
@nickiredescent I will close this ticket once you have had a chance to look at that team again and confirm that the fix worked. This is ready for testing.

**Comment by nickiredescent** [comment]
Thanks @adrichey ! I've notified the team, this ticket can be closed now.
