### ISSUE TITLE
Scores & Feeback shows up as disabled, despite being enabled in dashboard

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1993]
**Describe the bug**
Once Scores and Certificates have been enabled in the Admin UI, students and mentors should have access to that section on their dashboard. Right now, they have access once that feature has been turned on, but it shows up as being disabled and displays an incorrect tooltip when visiting that section on a mentor or student profile. Please see screenshot below.

**To Reproduce**
1. Log in as an Admin
2. Under Content & Settings, enable scores and certificates
3. Log in as a mentor that received a score during judging
4. Notice that the Scores & Feedback navigation link is disabled and shows a tooltip, but that you can still click through to view the scores

Repeat steps 3 & 4 as a student.

**Expected behavior**
In step 4 above, you should see Scores & Feedback as being enabled.

**Screenshots**
![screen shot 2019-02-25 at 11 45 19 am 2](https://user-images.githubusercontent.com/1534554/53357463-95074200-38f3-11e9-9b7f-dc7f495d7aba.png)

**Comment by stenington** [comment]
I'm unassigning myself and leaving this one for @adrichey. I'd need to learn vuex and vue-router, and then the specifics of how TC uses those tools, and he already knows that stuff.

**Comment by adrichey** [comment]
Pull request opened and assigned to @stenington: #2023.

**Comment by ophelieh** [comment]
@nickiredescent  and @KaiLokken Could you test this today or tomorrow? Thank you!

**Comment by KaiLokken** [comment]
Worked as expected for mentor. Will test for student, now.
![Image 3-14-19 at 9 17 AM](https://user-images.githubusercontent.com/45576084/54373244-25ef5480-463a-11e9-801d-96b08e9e66cb.jpg)

**Comment by nickiredescent** [comment]
Tested. Can also confirm that both student and mentors are working as expected. There is no "This feature is disabled text" appearing.

**Comment by KaiLokken** [comment]
Student: I was able to to access my own score and cert for the quarterfinals.  the Scores & Feedback navigation link is disabled and shows a tooltip. 
<img width="1409" alt="Screen Shot 2019-03-14 at 9 23 59 AM" src="https://user-images.githubusercontent.com/45576084/54373688-f42abd80-463a-11e9-9af7-9d926f5fd32b.png">

<img width="1335" alt="Screen Shot 2019-03-14 at 9 20 46 AM" src="https://user-images.githubusercontent.com/45576084/54373566-b5950300-463a-11e9-83e3-2e93a20ec9b7.png">

**Comment by adrichey** [comment]
@KaiLokken I believe they are accessible since Scores & Certificates are turned on in the admin. I think I might be confused as your comment says "navigation link is disabled and shows a tooltip" but the screenshot shows otherwise.

**Comment by adrichey** [comment]
I spoke with @KaiLokken earlier and it sounds like she was confused by my screenshot and that things are working as intended. Kai, can you confirm this so that we may mark this as closed?

**Comment by KaiLokken** [comment]
@adrichey Works as intended!
