### ISSUE TITLE
Remove General Judge certificate

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2001]
Is your feature request related to a problem? Please describe.

We will only have 3 types of certificates this season: 
* Certified Judge - Review at least 5 submissions
* Head Judge - Review 6-10 submissions
* Judge Advisor - Review more than 10 submissions

Acceptance Criteria
Part 1

* Turn on judging in the admin (admin@admin.com)
* Log in as a judge
* Judge less 3 submissions

Part 2

* Turn on scores and certificates in the admin
* Log in as the judge you used in part 1
* Check that you do NOT get a certificate
* Log in as an admin
* Confirm that there is no judging certificate available

**Comment by stenington** [comment]
@ophelieh Are we just removing the certificate, or the certificate and the badge? What do you want this screen to look like after this ticket is done? 

![screencapture-localhost-3000-judge-dashboard-2019-03-19-15_06_44](https://user-images.githubusercontent.com/55319/54634504-bd98dc80-4a58-11e9-9dad-d50373d50b45.png)

**Comment by ophelieh** [comment]
Hi Mike! 

We want to remove both, basically, we are getting rid of General Judges. So anyone who judges under 5 submissions doesn't get a certificate or badge.

**Comment by adrichey** [comment]
@ophelieh and @stenington How do we envision this working for judges that have received certificates in the past? Should I remove General Judge certificates entirely, removing them for people who have received them previously? Or do we leave certificates in place if a judge received them previously and limit the general judge functionality to the 2019 season onward? The latter leaves code in place that is basically just going to be skipped for every year going forward, and the former means lost certificates. I am thinking the latter makes more sense from a data posterity perspective, but I thought I would get you input in case either of you had a more specific idea about this in mind.

**Comment by stenington** [comment]
@adrichey the lazy solution here is probably to leave `general_judge` in the certificate types and just make `gets_general_judge_certificate?` return false like [`gets_rpe_winner_certificate?`](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/technovation/determine_certificates.rb#L165) does.

Removing it completely will actually remove the ability to search for past general judge certificates, which we don't necessarily want. Figuring out how to robustly handle certificate changes like this from year to year is out of scope right now though.

**Comment by stenington** [comment]
Ha, I think I was answering your question as you were typing it @adrichey. I say leave it in place but just default it to never issue. Figuring out how to handle certificates changing throughout seasons is a much bigger problem I think.

**Comment by adrichey** [comment]
That is great haha. I was thinking the same thing. Okay. I will approach it from that angle then. Thanks!

**Comment by adrichey** [comment]
This work has been completed. Previously generated tickets will still be searchable and available. 2019 general judge certificates are no longer a thing.

**Comment by ophelieh** [comment]
@ophelieh to test

**Comment by ophelieh** [comment]
This works great. Checked a judge who only had one score and did not see a certificate. 

Even if this won't happen, I just wanted to mention that judge - Hamzeh Rimawi - who was a General judge for 2019 before we made the change, is still receiving a General judge certificate.

![uploads/098f371a-c1cc-483e-8e3f-290e2c7660a7/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F098f371a-c1cc-483e-8e3f-290e2c7660a7%2Fimage.png)

One thing that I noticed (doesn't belong in that ticket, but wanted to write it down somewhere). 

This mentor received a participation certificate - https://technovation-qa.herokuapp.com/admin/participants/100#/


![uploads/8f20f658-5165-4167-8d5d-59b44bd7aa78/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8f20f658-5165-4167-8d5d-59b44bd7aa78%2Fimage.png)

**Comment by stenington** [comment]
Yeah, @ophelieh it's important for you to know that this change won't try to fix any certificates that have already been generated. So the Participation certificate and the General Judge certificate you see there may be from messy staging data, or may actually also be related to the bug found in #2057. 

But when this gets to production, I don't think 2019 users should have any certificates already generated, so it'll probably be cleaner there than staging is.

**Comment by adrichey** [comment]
@ophelieh That issue you received where a mentor earned a participation certificate when they shouldn't have should be fixed by the code Mike mentioned in the comments above. So this should be good to go now.

**Comment by ophelieh** [comment]
Ok great. Thank you!
