### ISSUE TITLE
Edit size/remove trophy on admin UI (for judges only) 

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2003]
**Describe the bug**
Trophy on judge profile in admin UI is huge and needs to be resized and/or removed.

**To Reproduce**
1. Go to a judge profile
2. Scroll down to the bottom of the page
3. See the oversized trophy

**Expected behavior**
The trophy is proportional to the page or removed

**Screenshots**
![image](https://user-images.githubusercontent.com/32206421/53603471-3d790880-3b77-11e9-88ac-e6c9b2049d63.png)

**Comment by adrichey** [comment]
Stale ticket to be addressed when #2052 is complete. Closing the ticket.
