### ISSUE TITLE
Update certificate templates for mentors, students, judges

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2004]
Need to update PDF certificates for:
* mentors - pending
* students - pending
* judges - https://www.dropbox.com/sh/mm2wdk84d1kk2d2/AAAb556-firnrw5X7fs_43eZa?dl=0

**Acceptance Criteria**

Scenario 1 - Students
* Step 1 Log in as a student who did not complete submission - you should see a "participation certificate"
* Step 2 Log in as a student who completed a submission but did not make it to semifinals - should see a "completion certificate"
* Step 3 Log in as a student who moved to semifinals - should see a "semifinals" certificate
* Step 4 Log in as a student who did not start a submission - should not see a certificate

Scenario 2 - Mentors
* Step 1 Log in as a mentor not part of any team - should not see a certificate
* Step 2 Log in as a mentor for a team who did not start a submission - should not see a certificate
* Step 3 Log in as a mentor for a team that started a submission but did not submit - should see a "mentor appreciation" certificate
* Step 4 Log in as a mentor for a team that submitted but did not make it to semifinals - should see a "mentor appreciation" certificate
* Step 5 Log in as a mentor for multiple teams with various degrees of submission - should see a "mentor appreciation" certificate
* Step 6 Log in as a mentor for a team that made it to semifinals - should see a "mentor appreciation" certificate
* Step 7 Log in as a mentor who is also a judge and did not review any submission or less than 5 - based on the steps above, should either not see a certificate or see a "mentor appreciation" certificate
* Step 8 Log in as a mentor who is a judge and reviewed at least 5 submissions - should see appropriate judge certificate (5 submissions - certified judge, 6 to 10 - head judge, 11+ - judge advisor) and mentor certificate

Scenario 3 - Judges 
* Step 1 Log in as a judge who is not a mentor and judged less than 5 submissions - should not see a certificate
* Step 2 Log in as a judge who is not a mentor and judged 5 submissions - should see "certified judge" certificate
* Step 3 Log in as a judge who is not a mentor and judged 6 to 10 submissions - should see "head judge" certificate
* Step 4 Log in as a judge who is not a mentor and judged 11+ submissions - should see  "judge advisor" certificate
* Step 5 Log is as a judge who is also a mentor and reviewed at least 5 submissions - should see appropriate judge and mentor certificates

Scenario 4 - Admin
Log in as an admin and make sure that you see all the right certificates from above for students, mentors, and judges

**Comment by adrichey** [comment]
Tagging @RRios00 on this. Ruby, I believe you were working on 2019 templates for certificates already. Can you give us insight into your progress on that? Thanks!

**Comment by adrichey** [comment]
Update: Ruby is finalizing designs now and will link them here once they are done.

**Comment by RRios00** [comment]
Hi Alan, thank you for your patience! 
Here are the completed and approved certificates.

<a href="https://www.dropbox.com/s/6jfiho4k4hja4cn/Certificate-Mentoring_2019.pdf?dl=0">Certificate of Mentoring</a> 

<a href="https://www.dropbox.com/s/wgdyievl1uh6ixo/Certificate-Participation_2019.pdf?dl=0">Certificate of Participation</a> 

<a href="https://www.dropbox.com/s/00csuq3f0e09hva/Certificate-ParticipantCompletion_2019.pdf?dl=0">Certificate of Completion</a>

<a href="https://www.dropbox.com/s/gjkhf66iprpxdzl/Certificate-Semifinalist_2019.pdf?dl=0">Semifinalist Certificate</a>

<a href="https://www.dropbox.com/s/ivgcbol1tscd4ug/Certificate-RegionalPitchEventWinner_2019.pdf?dl=0">RPE Winner Certificate</a>

 <a href="https://www.dropbox.com/s/ivgcbol1tscd4ug/Certificate-RegionalPitchEventWinner_2019.pdf?dl=0">RPE Winner Certificate</a>

 <a href="https://www.dropbox.com/s/7ks5ql1w5jy4iz7/Certified-Judge-Certificate_2019.pdf?dl=0">Certified Judge Certificate</a>

 <a href="https://www.dropbox.com/s/lcj4un67biwy2g9/Head-Judge-Certificate_2019.pdf?dl=0">Head Judge Certificate</a>

  <a href="https://www.dropbox.com/s/38suaiaj5uito89/Judge-Advisor-Certificate_2019.pdf?dl=0">Judge Advisor</a>

**Comment by adrichey** [comment]
Thank you @RRios00! I appreciate all of your work on this. I will get to work on uploading these templates now @ophelieh.

**Comment by adrichey** [comment]
@RRios00 and @ophelieh It looks like the mentor appreciation certificate is not working as intended. I think this is because the text box underneath the Full Name field only allows for one line of text. I think we will want to expand this text box to allow for multiple lines, similar to how the Completion certificate text box works. Hopefully that makes sense.

Here you can see the problematic generated PDF (team name is very long and causes other text to be cut off):
[2019-mentor_appreciation-276-92(1).pdf](https://github.com/Iridescent-CM/technovation-app/files/3045439/2019-mentor_appreciation-276-92.1.pdf)

**Comment by adrichey** [comment]
@RRios00 Additionally, could you change all of the "First Name Last Name" combinations to "Full Name" 
(without quotation marks)? That would be helpful so we don't have to change our code for the edge cases. Thank you!

**Comment by RRios00** [comment]
@adrichey I've changed all the certificates to "Full Name" (with out the quotation marks) and @ophelieh  the copy of the RPE certificate.

<a href="https://www.dropbox.com/s/6qy6gbafk80grnb/CertificateofMentor_2019.pdf?dl=0">Certificate of Mentoring</a> 

<a href="https://www.dropbox.com/s/u0auk1s36f6mvqn/Certificate-Participation_2019.pdf?dl=0">Certificate of Participation</a> 

<a href="https://www.dropbox.com/s/zql3ey05xbccrb6/Certificate-ParticipantCompletion_2019.pdf?dl=0">Certificate of Completion</a>

<a href="https://www.dropbox.com/s/wh3gi3v0m3acpwh/Certificate-Semifinalist_2019.pdf?dl=0">Semifinalist Certificate</a>

<a href="https://www.dropbox.com/s/nwcge10trdxahss/CertificateofRPEWinners_2019.pdf?dl=0">RPE Winner Certificate</a>

 <a href="https://www.dropbox.com/s/4hvahymox3xa5cr/Certified-Judge-Certificate_2019.pdf?dl=0">Certified Judge Certificate</a>

 <a href="https://www.dropbox.com/s/845uemz2uvrwa6j/Head-Judge-Certificate_2019.pdf?dl=0">Head Judge Certificate</a>

  <a href="https://www.dropbox.com/s/e65pgy2tr2lqk6h/Judge-Advisor-Certificate_2019.pdf?dl=0">Judge Advisor</a>

**Comment by adrichey** [comment]
Thanks Ruby! I will give those a shot and let you know if anything else needs tweaking.

**Comment by adrichey** [comment]
**QA Testing Steps**

Perform the following steps for each of the following certificates:
- <a href="https://www.dropbox.com/s/6qy6gbafk80grnb/CertificateofMentor_2019.pdf?dl=0">Mentor Appreciation</a> 
- <a href="https://www.dropbox.com/s/u0auk1s36f6mvqn/Certificate-Participation_2019.pdf?dl=0">Participation</a> 
- <a href="https://www.dropbox.com/s/zql3ey05xbccrb6/Certificate-ParticipantCompletion_2019.pdf?dl=0">Completion</a>
- <a href="https://www.dropbox.com/s/wh3gi3v0m3acpwh/Certificate-Semifinalist_2019.pdf?dl=0">Semifinalist</a>
- <a href="https://www.dropbox.com/s/4hvahymox3xa5cr/Certified-Judge-Certificate_2019.pdf?dl=0">Certified Judge</a>
- <a href="https://www.dropbox.com/s/845uemz2uvrwa6j/Head-Judge-Certificate_2019.pdf?dl=0">Head Judge</a>
- <a href="https://www.dropbox.com/s/e65pgy2tr2lqk6h/Judge-Advisor-Certificate_2019.pdf?dl=0">Judge Advisor</a>

1. Log in as an Admin.
2. Browse to the Participants and select a student/mentor/judge account that corresponds to the certificate you are looking at currently.
3. While viewing the user, scroll down to 2019 Certificates -> Manually award certificates.
4. Award the user the certificate you are currently attempting to confirm using the drop-downs.
5. Open the corresponding certificate above and make sure that the text in the template has been replaced with the account information.
6. Confirm that the text in the generated certificate is not editable.

**Comment by adrichey** [comment]
This is now ready for testing using the above steps.

**Comment by ophelieh** [comment]
@KaiLokken and @nickiredescent Could you both test? Feel free to split the work. Thank you!

**Comment by nickiredescent** [comment]
Tested for all certificate types. All are working as described and are not editable.

**Comment by ophelieh** [comment]
@nickiredescent Do you remember which people you tested that on? Thanks!

**Comment by nickiredescent** [comment]
I tested a few. I remember for sure using jjj as one of the judges and
"example student" as one of the students

**Comment by ophelieh** [comment]
ok thanks.
