### ISSUE TITLE
Certificate Override - Can break account 

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2005]
**Describe the bug**
Certificate overrides: You can break an account by giving them a bad certificate override type such as mentor appreciation.

For Judge Judy, alli+j7@iridescentlearning.org, I gave a judge only a mentor appreciation certificate and it breaks the account (you cannot view or log in at all).

Developer note: The fix is to manually remove the override on the account in the database (override_certificate_type set to NULL)

**Possible Solutions**
Lock down the list of what you can change a judge certificate to be and limit to only be judge certificates
Fix the bug that to check if certificate needs are met after the switch so it doesn’t lock out the user from accessing their account and prevent us from removing override in UI.

**To Reproduce**
1. Log in as a  judge
2. Override certificate
3. Open certificate

Tested -  Mentor on multiple teams who is also a judge (buffy the vampire slayer)
* Overrode mentor certificate, to give her a judge certificate (sorry cannot remember which one). 
* Then clicked on 3 different mentor certificates, received an error message.
* Tried to override certificate back to mentor one and corrupted account. 
* Now i cannot click on her profile anymore.

**Expected behavior**
Overriding a certificate does not change anything but the certificate. 

**Screenshots**

![image](https://user-images.githubusercontent.com/32206421/53604789-1b818500-3b7b-11e9-8c6e-54484635c55f.png) - When trying to open certificate

![image](https://user-images.githubusercontent.com/32206421/53604868-571c4f00-3b7b-11e9-836a-8398cf0828b8.png) - When trying to open "Buffy's" profile

**Comment by stenington** [comment]
Can we document the actual use case here for overriding certificates? Is it only the judge certificates that need overriding, or do student and mentor certificates sometimes need to be forced to something different? @ophelieh do you know?

**Comment by stenington** [comment]
Oh, I just read the potential solutions more carefully, it sounds like this is only relevant for judges?

> Lock down the list of what you can change a judge certificate to be and limit to only be judge certificates

**Comment by ophelieh** [comment]
I believe so. @kmorton2017 ?

**Comment by adrichey** [comment]
Stale ticket to be addressed when #2061 is complete. Closing the ticket.
