### ISSUE TITLE
 UI - Make sure titles are consistent - every profile should say “open certificate” 

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2006]
User - One thing to note is that on production it says “generate certificate” and not “open certificate.” I think it is fine to use “open certificate” on the button.

* Mentors and judges have different titles.
* Mentor and judge buttons should both be rounded buttons for consistency, judge buttons are rectangles right now. Judge buttons also have a large amount of whitespace around them.

Developer Note: CertificateButton.vue is one spot that is working correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/32206421/53605214-66e86300-3b7c-11e9-8152-0bac90f64f61.png)

![image](https://user-images.githubusercontent.com/32206421/53605226-79629c80-3b7c-11e9-8c37-7f5ff7479eeb.png)

**Comment by adrichey** [comment]
Stale ticket to be addressed when #2057, #2060 and #2061 complete. Closing the ticket.
