### ISSUE TITLE
UI - Edit box location on admin view of mentor/judge profile

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2007]
**Describe the bug**
After the large trophy there is a box which says what team the mentor is on. This should be in the mentor section of their profile, rather than after the trophy. See below. 

![image](https://user-images.githubusercontent.com/32206421/53605434-1faea200-3b7d-11e9-8483-7459d6d19fd4.png)

**To Reproduce**
1. Log in as a judge who is also a mentor
2. Scroll down, see team names at the bottom 

**Expected behavior**
The mentor section of the judge profile should be above the trophy 

** Acceptance Criteria** 

* Step 1 As an admin, turn on scores and certificates
* Step 2 Find a judge who is also a mentor
* Step 3 The mentor's teams should show above the certificates

**Comment by stenington** [comment]
Technical note: [the same code](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/views/admin/participants/show.html.erb#L174) is used to show teams for both mentors and students but moving that block up to [line 154](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/views/admin/participants/show.html.erb#L154) before the judge debugging partial should look better for mentors without affecting students, I think.

**Comment by adrichey** [comment]
Stale ticket to be addressed when #2057, #2060 and #2061 complete. Closing the ticket.
