### ISSUE TITLE
UI - Consolidate Certificate location

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2008]
**Describe the bug**
There are currently 2 locations to open certificates, which can lead to confusion on admin side. 

Example: https://technovation-qa.herokuapp.com/admin/participants/93#/

* This person has correct mentor certificates for 2018 in the Certificates box with the white background. They also have a 2019 certificate that should show up as a mentor certificate as well as they are a mentor on that team, but it shows up as a judge certificate.
* Below this section we have two more certificate buttons. One for 2018 that is correctly displaying a judge certificate, and one for 2019 that is a judge certificate as well.
* I believe the first section with the white background should be for student/mentor certificates only, and the section below is judges.

Solution: We should consolidate the certificates boxes and display all mentor certificates for all teams the mentor participated in AND ALSO display the judge certificate for the season as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/32206421/53651082-8da1aa80-3c0b-11e9-8138-7a4eab05daf8.png)

**Comment by stenington** [comment]
Technical note: mentor certificates are displayed as part of the `_mentor_debugging` partial, whereas the code displaying judge certificates and badges lives right in the `show` template. I think the solution here is to move the mentor certificate code out of the debugging partial and group it with the judge certificate/badge code, probably where the judge certificate/badge code currently is.

**Comment by adrichey** [comment]
Stale ticket to be addressed when #2057, #2060 and #2061 complete. Closing the ticket.
