### ISSUE TITLE
Dashboard for admin/RAs does not work as expected

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2009]
**Describe the bug**
When clicking on the student or mentor pie, admin/RA is brought to an error page. 

**To Reproduce**
1. As an admin go to Dashboard
2. Click on any of the information in the student or mentor pies

**Expected behavior**
When clicking on either of the pies, I should see the appropriate information. For example students with parental consent on file. 

Note - this error might be caused by the filters we changed on the participants' page. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32206421/53651961-66e47380-3c0d-11e9-98a3-439cfb585e91.png)

![image](https://user-images.githubusercontent.com/32206421/53651840-24bb3200-3c0d-11e9-9270-0cd6c33dd0ce.png)

**Comment by ophelieh** [comment]
Hi @stenington! Could you look into this when you get a chance?

**Comment by stenington** [comment]
Sure @ophelieh, I'll start on it today.

**Comment by stenington** [comment]
@ophelieh It looks like ticket #1915 asked for the parental consent filter to be removed, which is part of the reason why the graph links are now broken. So I have some options on how to solve this:

* bring back the parental consent filter, including adding it back to the participants page
* bring back the parental consent filter, but try not to show it on the participants page (it only gets used when linking from the graph)
* update the graph to show onboarded vs. not onboarded, since that's what #1915 was asking to replace those filters with

What would be your preference for me to look in to?

**Comment by stenington** [comment]
Oh, since mentors are broken too I guess the options are basically the same as above, but with the background check and consent waiver filters as well as parental consent.

**Comment by ophelieh** [comment]
Hi @stenington I think option 3 (_update the graph to show onboarded vs. not onboarded, since that's what #1915 was asking to replace those filters with_) might make the most sense, especially for consistency. That might also make the mentor graph a little cleaner and if people want more detail they can use the "more columns" on the participants' page.

**Comment by stenington** [comment]
@ophelieh or @kmorton2017 As I'm doing this ticket and working on the mentor part, I'm finding some conflicting definitions of what it means for a mentor to be onboarded. Can you help clarify? 

One source says they have to have:
* email confirmed
* training complete or not required
* consent signed
* background check complete, if US
* their bio isn't blank
* their type isn't blank (Industry professional, Educator, Parent, Past Technovation student)

Another source just says:
* email confirmed
* training complete or not required
* background check complete, if US

And a third says:
* email confirmed
* training complete or not required
* background check complete, if US
* their bio isn't blank

Can you tell me which one would be the best to use?

**Comment by ophelieh** [comment]
haha, of course, we would have 3 different ways of doing it... 

I feel like the first one might be the most accurate, as from what I remember they are not able to join a team unless all those things are done.

**Comment by kmorton2017** [comment]
i wasnt aware that the type couldn't be blank, BUT i agree it should be the first case you mentioned.  this is the most comprehensive and true.

**Comment by stenington** [comment]
Ok thanks! I'll try to standardize towards the first definition.

**Comment by stenington** [comment]
This is headed to staging.

@kmorton2017 @ophelieh How much QA do you want to do here? At the easy end, someone can just check that clicking the pie chart links you to a page that makes sense. At the more thorough end of the spectrum, we can get into lots of specific data scenarios and checking whether students and mentors are correctly categorized as onboarded or not. 

How important is it for that data to be accurate? Are there specific scenarios you want to check on?

**Comment by ophelieh** [comment]
I just tested this and it seems to work great. I like how it selects the filters for us and we can still have the "more columns" information to see what is still missing from the profile. I tested mentors and it worked great. 

@kmorton2017 Could you test this as well?
