### ISSUE TITLE
Admin - Judges getting wrong certificate

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2011]
**Describe the bug**
In some cases, judges receive the wrong certificate. Example - a virtual judge that reviewed 2 submissions should be a general judge (as of last year, this year they wouldn't receive a certificate) but received a certified certificate.

See video - https://drive.google.com/file/d/1uF0dW_gJOL5fbjpWpWFskq05OfD8D9FH/view

Note: This might actually get fixed when we upload the new certificates and remove the general judge certificate. 

** Expected Behavior**
The judge sees the right certificate. 
* If only reviews 1 to 4 submissions - does not get certificate
* If reviews 5 submissions - receives certfied judge certificate
* If reviews 6 to 10 submissions - receives head judge certificate
* If reviews 11+ submissions - received advisor judge certificate

**Comment by adrichey** [comment]
Stale ticket to be addressed when #2057, #2059, #2060 and #2061 complete. Closing the ticket.
