### ISSUE TITLE
Admin (bug) - Issue with mentor vs judge certificate

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2012]
**Describe the bug**
Right now, when a judge is also a mentor, as an admin when we open their mentor certificate - it shows either the judge certificate or the team certificate. 

See gif - https://drive.google.com/file/d/1W_vtOPKG8Wx4dV3hjQjYKv3H6e4w2YXC/view

**Expected behavior**
As an admin when clicking on the mentor portion of the certificates, we should only see the mentoring certificates. And when clicking on the judge portion of the certificates, we should only see the judge certificate.

**Comment by adrichey** [comment]
Stale ticket to be addressed when #2057, #2059, #2060 and #2061 complete. Closing the ticket.
