### ISSUE TITLE
Make Overall Impression UI match that of other scoring steps

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2016]
**Is your feature request related to a problem? Please describe.**
The Overall Impression page when scoring a submission as a judge looks different than the other scoring steps (see Ideation) and requires the judge to scroll all the way down and back up to put in their comments.

**Describe the solution you'd like**
The look and feel of the Overall Impression page should match that of the Ideation step.

**Additional context**
Here is a gif of the current Overall Impression page:
![overall_impression](https://user-images.githubusercontent.com/1534554/53753662-694a0600-3e77-11e9-990f-caecfe052371.gif)

Here is the Ideation page (what it needs to look like):
![ideation](https://user-images.githubusercontent.com/1534554/53753692-7a931280-3e77-11e9-803c-34db44512f79.gif)

**Comment by ophelieh** [comment]
@nickiredescent Could you test this? Thanks!

**Comment by nickiredescent** [comment]
#2016
Tested. Can confirm that the Overall Impression Page and other judging sections have similar design styles. Can also confirm that looking at team "Barbacoa is delicious" this early makes me hungry.

**Comment by adrichey** [comment]
Time to hit up Chipotle @nickiredescent! Thanks!
