### ISSUE TITLE
Admin scores page counts mismatched

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2017]
**Describe the bug**
Pretty minor but on the admin side, looking at the list of semifinals scored, it says “5 submissions scored” but also “Exports 6 semifinal scores”. I guess the count for export also includes the header line?

![pasted image 0](https://user-images.githubusercontent.com/55319/53753726-f42efe80-3e7f-11e9-9d57-d8bcdcf63a15.png)

**Comment by stenington** [comment]
I wrote this issue up as reported in exploratory QA, but when I go to the admin here's what I see:

![screen shot 2019-03-04 at 1 15 59 pm](https://user-images.githubusercontent.com/55319/53753791-1e80bc00-3e80-11e9-99d9-2335cae4fc53.png)

What's happening is the first number is the number of **submissions**, which can have more than one score, and the second number is the actual **number of scores**.

This page used to export one line per score, but now exports one line per submission, so I do think the text here should be updated to say "Exports X scored submissions" where the number matches the "X submissions scored" number.

Does that sound good @ophelieh?

**Comment by ophelieh** [comment]
That makes sense and that works for me. Thank you!

**Comment by stenington** [comment]
QA steps:

1. Log in as admin
2. Go to scores
3. Confirm that the message below the Search button and the message above the Export button make sense together and show the same count

**Comment by ophelieh** [comment]
@nickiredescent Could you test this? Thank you!

**Comment by nickiredescent** [comment]
Tested.

The number of submissions scored and number to export show the same count. Changing search filters and exporting csv's also show the correct count.

**Comment by ophelieh** [comment]
Perfect. Thanks Nick!
