### ISSUE TITLE
Update Judging dashboard copy

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2018]
**Describe the bug**
We need to update the Online Judging information box text to display the correct start and end dates for quarterfinals judging. We need to replace the text "Quarterfinals judging begins on April 27, 2019", with "Quarterfinals judging begins on April 27 and ends on June 2, 2019".

**To Reproduce**
1. Log in as a judge
2. Navigate to your dashboard
3. Observe the text "Quarterfinals judging begins on April 27, 2019" in the Online Judging section

**Expected behavior**
In step 3 above, the copy should read, "Quarterfinals judging begins on April 27 and ends on June 2, 2019."

**Screenshots**
![screen shot 2019-03-04 at 12 21 24 pm 2](https://user-images.githubusercontent.com/1534554/53754118-9814ac00-3e78-11e9-9be2-9075e56cc0b1.png)

**Comment by ophelieh** [comment]
@nickiredescent Could you test this? 

Thank you!

**Comment by nickiredescent** [comment]
Tested and I can see the text as a virtual judge.
