### ISSUE TITLE
We need to update all of the dates/copy for judging to their actual dates

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2020]
**Describe the bug**
Recently we did exploratory QA, which changed the dates and copy of quarterfinals and semifinals throughout the system. We need to update the environment variables so that the dates reflect the actual calendar dates found on the master calendar. Once we have updated the dates, we need to confirm that the copy in various spots throughout the UI is correct for the season.

**Places to confirm that copy/dates are correct**
Judge dashboard:
![screen shot 2019-03-04 at 12 21 24 pm 2](https://user-images.githubusercontent.com/1534554/53754618-17ef4600-3e7a-11e9-8403-7f3202668b5a.png)

Judge dashboard, attending RPE:
![screen shot 2019-03-04 at 12 41 28 pm 2](https://user-images.githubusercontent.com/1534554/53754994-12463000-3e7b-11e9-9f84-a72b4bd0dc57.png)

Between rounds (may need a developer to test this one):
![screen shot 2019-02-22 at 11 13 35 am 2](https://user-images.githubusercontent.com/1534554/53754652-35bcab00-3e7a-11e9-8c85-a3ebbcf600a3.png)

**Comment by adrichey** [comment]
@ophelieh @kmorton2017 @KaiLokken @nickiredescent Let me know if I missed any spots for copy in the UI. I think this covers everything that was mentioned in the exploratory QA.

**Comment by ophelieh** [comment]
Hi Alan, looks good to me! 

One thing to note is that we will need to update the number of countries and submissions for the between rounds text 
![image](https://user-images.githubusercontent.com/32206421/53820443-6875aa80-3f31-11e9-855a-f5835756ee99.png)

Thanks!

**Comment by adrichey** [comment]
@ophelieh if you can get me those numbers, I can update those numbers as I address these other spots.

**Comment by ophelieh** [comment]
We won't have that until later. Maybe we should start a new ticket for that one.

**Comment by adrichey** [comment]
I think an additional ticket sounds like a good idea Ophelie, we can just keep the scope of this one to the stuff in the screenshots in the ticket description in that case. Thanks!

**Comment by ophelieh** [comment]
Done. See ticket #2029
