### ISSUE TITLE
Update copy for judge in between rounds 

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2029]
Update number of teams and countries in the first sentence. @kmorton2017  or @ophelieh to provide text when have it. 

![53754652-35bcab00-3e7a-11e9-8c85-a3ebbcf600a3](https://user-images.githubusercontent.com/32206421/54059158-c5859080-41bd-11e9-941a-680357d35259.png)

**Comment by adrichey** [comment]
@kmorton2017 and @ophelieh can you get us numbers for this ticket so that we can update that text? Thanks!

**Comment by ophelieh** [comment]
Hi @adrichey We won't have those until submission closes, we can give them to you on the 24th. Does that work?

**Comment by adrichey** [comment]
Yep, that is fine @ophelieh. I will move this to the backlog in the mean time then!

**Comment by ophelieh** [comment]
Perfect. Thanks!

**Comment by ophelieh** [comment]
@kmorton2017 and @ophelieh to review copy

**Comment by stenington** [comment]
@kmorton2017 and @ophelieh can I get a status update on this one? Seems like it might need to get addressed this week if changes need to be made.

**Comment by ophelieh** [comment]
I can get this to you by end of the day today.

**Comment by ophelieh** [comment]
"If you had time to judge, we sincerely thank you for helping us support almost 2,000 in 57 countries. [...]"

**Comment by kmorton2017** [comment]
Yes that looks right to me. Can we hyperlink our judge resource page?

View our Judge Resource page (https://technovationchallenge.org/judge-resources/)  for more information.

**Comment by ophelieh** [comment]
Great idea Katie! @stenington This is now all ready to go. 

The resource page sentence should be at the bottom unless you think another spot would be better.

**Comment by ophelieh** [comment]
@nickiredescent Can you test this? I will also take a look. Thanks!

**Comment by ophelieh** [comment]
Looks good. There are a couple of small things that need to be updated. Didn't catch it before. And honestly, I don't really get the difference between Advisor and Adviser so I guess we should just go with Advisor. 

We should put periods on the highlighted sentences and change the s to and S for semifinals on the right column. 

Also, could the judge resource page open in a different tab? Looks great otherwise. :) 

![uploads/5c7878b6-85ee-4278-a5c2-b683a01a8b6f/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5c7878b6-85ee-4278-a5c2-b683a01a8b6f%2Fimage.png)


Thank you!

**Comment by nickiredescent** [comment]
I agree with Ophelie, the page overall looks good.
![image](https://user-images.githubusercontent.com/45576078/58670777-1d332400-82f5-11e9-92ca-b18050282dda.png)
Should probably use a comma after the bold, not a period as suggested.
Overall, the difference between adviser and advisor is really minor, but we should keep it consistent.

**Comment by stenington** [comment]
Ok, those changes are on staging!
