### ISSUE TITLE
Let judges see all their events on the dashboard

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2038]
**Is your feature request related to a problem? Please describe.**
Judges can be assigned to judge multiple events, but only see one event on their dashboard.

**Describe the solution you'd like**
Show them all of the events they have been assigned to on their dashboard.

**Additional context**
Judges being in multiple events is something the platform allows, but handles poorly. We're going to work on improving it, knowing that some bugs may be lurking until we can completely convert the logic to handle multiple events. (This is as opposed to trying to fix that all at once, which seems too daunting.)

**Comment by stenington** [comment]
This ticket should include a bit of a survey of the codebase, and begin `TODO`ing or otherwise deprecating code that assumes a judge is in only one event.

**Comment by stenington** [comment]
Nope disregard the previous comment, at a glance there are some bits that are too scary to handle that way. I'm opening a ticket for an initial conversion of single-event to multi-event, even though it may not be perfect.

**Comment by stenington** [comment]
QA steps:

1. log in as an RA with two events (or create them)
2. add the same judge to both events
3. log in as a different RA with an event
4. add the same judge to an event
5. log in as the judge
6. confirm the "Regional Pitch Events" section of your dashboard shows all 3 events

**Comment by ophelieh** [comment]
@kmorton2017 and @KaiLokken Could you test this? Thank you!

**Comment by KaiLokken** [comment]
Tested it. It worked as expected.

**Comment by ophelieh** [comment]
@nickiredescent Could you test this?
