### ISSUE TITLE
Platform wrongly assumes judges are in one event

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2039]
The platform allows judges to be put into multiple events, but was written assuming that's impossible. The problem is that we don't want to have to wait to discover all the bugs this will cause the hard way, so this ticket is about digging through the codebase a bit and starting to fix things that way.

**Comment by stenington** [comment]
Find lurking bugs and either fix or `TODO` or otherwise deprecate them in the code.

**Comment by stenington** [comment]
#2038 has a testable scenario, this one less so. @adrichey any particular testing you think we should do here? I think maybe it's a combo of #2038 QA and then just keeping an eye out for bugs around judges in multiple events in general.

**Comment by adrichey** [comment]
Honestly, I think that might be the way to go. Use #2038 QA steps and then monitor. I think we have to address issues as they come up for the most part since there are so many spots that weren't fleshed out for this feature. One thing we might want to think about on this would be to implement daily backups so that if bugs come up and scores get removed or something, we have the ability to restore them if need be. I would feel safer monitoring with that in place.

**Comment by stenington** [comment]
I believe we have a daily backup running, `heroku pg:backups:schedules -a technovation` to see the schedule. `heroku pg:backups -a technovation` does show gaps, but I wonder if it can detect that the data didn't actually change during that time?

**Comment by adrichey** [comment]
Yeah, I saw those gaps, hence the question. Didn't even think to check the schedule. I will look into those backups more to confirm.

**Comment by adrichey** [comment]
QA steps:
- log in as an RA with two events (or create them)
- add the same judge to both events
- log in as a different RA with an event
- add the same judge to an event
- log in as the judge
- confirm the "Regional Pitch Events" section of your dashboard shows all 3 events
- confirm that you can "View details" of each event separately

**Comment by nickiredescent** [comment]
Tested. It seems to work but something's odd. Details below:

- RAs with events used to test: Neil Degrasse Tyson, Jade Green, Hong Kong RA.
     - All have different events with capacity to add a new judge.
     - Assigned John Jonah Jameson to various events by each judge.
           - Neil assigned 2 events
           - Jade Green assigned 2 events
           - HK RA assigned 1 event
- Logged in as JJJ to view events and details
     - Can confirm I am able to view every event I was added to on my dashboard.
     - Can view details of each event except for those assigned by Jade Green. Clicking on "View Details" brings me to the "uh oh something's wrong" page. Unsure why this is the case.

**Comment by stenington** [comment]
Ok, thanks @nickiredescent! I will look at that error.

**Comment by stenington** [comment]
@nickiredescent It turns out the bug would happen when a judge tried to view an event that was at capacity, which in this case was the Jade Green event. A fix is on the way to staging now and should be there soon for retesting.

**Comment by nickiredescent** [comment]
Tested. I've assigned other judges to full capacity events and was able to view details of the events.
