### ISSUE TITLE
RPE team cap prevents addition of judges too

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2040]
**Describe the bug**
If an RPE is at its team cap, you cannot add more judges.

**To Reproduce**
1. Log in as an RA with events
2. Find or create and event with a team cap, and add teams until at the cap
3. Try to add a judge
4. Selecting a judge will be prevented, and the checkbox tool tip says you have reached the team cap

**Expected behavior**
The team cap should only apply to teams.

**Comment by ophelieh** [comment]
@KaiLokken and @nickiredescent Could you test this? Merci!

**Comment by ophelieh** [comment]
From Kai: Tested it. I was not able to add any more teams after hitting the team cap. I was able to add a judge to the event.
