### ISSUE TITLE
Remove RPE live event cards if judging for the season has finished

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2048]
**Is your feature request related to a problem? Please describe.**
The event card still shows even when certificates are turned on. We want to hide RPEs after judging is over. It would be outdated at this point in the season. See screenshot below.

**Describe the solution you'd like**
When judging is turned off for the season after judging is closed, we should hide any live event RPE cards from the judge dashboards.

**Screenshot**
![Screen Shot 2019-03-04 at 12 41 28 PM (2)](https://user-images.githubusercontent.com/1534554/54708738-0791c900-4b12-11e9-93af-f706436342ce.png)

**Comment by stenington** [comment]
@adrichey Was the judging round set to **Off** or **Finished**? Finished should hide them. You basically get a blank screen (https://github.com/Iridescent-CM/technovation-app/issues/2025#issuecomment-474590652)

**Comment by adrichey** [comment]
Yep, that is what was going on. Closing the ticket as this is not an issue.
