### ISSUE TITLE
Remove judge badges from dashboard and admin UI

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2052]
**Is your feature request related to a problem? Please describe.**
Last year, we had judge badges in addition to the certificates that they received. Now the program team wishes to remove that feature.

**Describe the solution you'd like**
We would like to remove the judge badges from the judge dashboards, and also the admin participants UI.

**Notes**
We will probably want to rethink the judge dashboard UI, or get another SVG image to take the place of the badge as it will be jarring from a UI perspective. Tagging @RRios00 since this might cause her extra work.

There is also text on the between rounds page for judges that references badges.

We will want to make sure that the program team removes any references to badges from emails that are sent out and remove any references to badges from our WordPress sites as well.

**Screenshots**
Here is an example of a badge:
<img width="386" alt="Screen Shot 2019-03-21 at 11 13 50 AM" src="https://user-images.githubusercontent.com/1534554/54780306-6412e800-4be7-11e9-9607-32e93d5a96dd.png">

Dashboard example that should be removed:
<img width="1271" alt="Screen Shot 2019-03-21 at 11 23 49 AM" src="https://user-images.githubusercontent.com/1534554/54780316-6b39f600-4be7-11e9-8597-581ea02dbcac.png">

Admin UI example:
![Mar-21-2019 14-42-48](https://user-images.githubusercontent.com/1534554/54780407-ab00dd80-4be7-11e9-9192-48868a458c35.gif)

**Comment by adrichey** [comment]
@ophelieh and @kmorton2017 here is the ticket for removing the badges this year. Question, do we want badges from 2018 to still appear for judges, or should we hide those as well?

**Comment by ophelieh** [comment]
We can remove all of them. I don't believe they were even used last year.

**Comment by adrichey** [comment]
This is now ready for testing.

**Comment by ophelieh** [comment]
@KaiLokken and @nickiredescent Could you both test this? 

Thank you!

**Comment by nickiredescent** [comment]
Tested. Can confirm that my judge dashboard no longer shows the badge of great honor. It is also not visible on the admin UI.

Judging set to **off.**
![image](https://user-images.githubusercontent.com/45576078/55253859-ace42580-5213-11e9-965e-5cbd75c94ab0.png)

Judging set to **finished.**
![image](https://user-images.githubusercontent.com/45576078/55253891-bf5e5f00-5213-11e9-8f25-0f25ae63aa70.png)

**Comment by KaiLokken** [comment]
Tested it. With "judging finished", the same message appeared as with Nick's account.
<img width="1412" alt="Screen Shot 2019-03-29 at 1 02 52 PM" src="https://user-images.githubusercontent.com/45576084/55259542-30f1d980-5223-11e9-9d6b-23606facb51e.png">

**Comment by ophelieh** [comment]
Thank you both!
