### ISSUE TITLE
No thank you page for judges in Finished Stage

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2053]
**Describe the bug**
Once we close judging, there isn't any thank you page. It's just blank.

![image](https://user-images.githubusercontent.com/32206421/54790106-fb396900-4c02-11e9-8af6-d25dd25b4833.png)

**Expected behavior**
It would be nice to have a sort of thank you page after judging is in the "finished" phase. 

Something along the lines of "Thank you for your help scoring and giving valuable feedback to Technovation teams. Your judging certificate will be available June 24th. Thank you again for helping girls lead the change. See you next season!"

**Comment by adrichey** [comment]
@ophelieh Should we pull this in now since it will pop up for our end users this season and might be jarring? I can just add that text to their dashboard for now. It won't take long to knock that out.

**Comment by ophelieh** [comment]
Works for me! Thank you!

**Comment by adrichey** [comment]
This is now ready for testing.

Testing Scenario 1:
1. As an admin, turn Judging round to "Finished", make sure that "Scores & Certificates Accessible" is left unchecked and save these settings.
2. Log in as a Judge account.
3. Confirm that a message is displayed informing the user that certificates will be available on June 24th.

Testing Scenario 2:
1. As an admin, turn Judging round to "Finished", make sure that "Scores & Certificates Accessible" is checked. Save these settings.
2. Log in as a Judge account.
3. Confirm that the blank box does not appear and that there is either a certificate available for the user, or that a message is displayed in the absence of a certificate.

**Comment by ophelieh** [comment]
Hi @KaiLokken and @nickiredescent Could you test this? 

Merci! :)

**Comment by nickiredescent** [comment]
Tested the scenarios. 
Can confirm that Scenario 1 provides a message saying that certificates will be available June 24th.
Can confirm that Scenario 2 has either a certificate available or if no certificate is available, a message is displayed.
