### ISSUE TITLE
Admin scores page round selection doesn't handle new rounds

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2054]
**Describe the bug**
If you put the platform into "between rounds" or "finished" for the judging round and try to view the scores page, it errors out. 

**To Reproduce**
1. As an admin, go to Content & Settings > Judging
2. Select Finished
3. Review and save the setting
4. Click on Scores in the nav menu
5. See the error

**Expected behavior**
You should see the scores page with quarterfinals selected as the round

**Comment by stenington** [comment]
[This block of code](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/controllers/admin/scores_controller.rb#L34) is the culprit, I think.

**Comment by stenington** [comment]
QA steps:

1. log in as admin
2. set Judging Round to "Finished"
3. click Scores in nav menu
4. confirm the scores page loads without error

**Comment by ophelieh** [comment]
@nickiredescent and @kmorton2017 Could you both test this please?

**Comment by nickiredescent** [comment]
Tested. Can confirm that the score page is loading correctly when either the "Between Rounds" or "Finished" status is turned on.

**Comment by stenington** [comment]
I just noticed this bug exists on the scores export page too. 😭 

I'm knocking this back into "In progress" to fix that page as well.

**Comment by stenington** [comment]
QA steps for second fix (same thing but with Scores export page):

1. log in as admin
2. set Judging Round to "Finished"
3. click "Scores export" in nav menu
4. confirm the scores export page loads without error

**Comment by nickiredescent** [comment]
Tested. Can confirm that the "Score export" page loads without error. Could be just me, the page loads a bit slowly, especially when I switch to quarterfinal scores.

**Comment by ophelieh** [comment]
@kmorton2017 Could you test both of those steps? Merci! :)

**Comment by kmorton2017** [comment]
Confirm that the scores page loads without error.
Confirm that the scores export page loads without error. I agree with Nick though, the scores export page was slower to load though.

**Comment by stenington** [comment]
Ok, it looks like it might be slow because the country column hits the Google API, and while our API requests are being rejected that slows things down pretty badly.
