### ISSUE TITLE
Remove on-demand generation of season certificates

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2056]
This ticket gets us started on a transition from on-demand certificate generation to batch generation, which we're expecting to be easier to write and less buggy.

This ticket's work includes:
* pulling out FillPdfs calls from controllers or other places it's called on-demand right now
* stop using the CertificateButton Vue app in favor of querying in the controller and rendering what's found
* ~add logging where appropriate for unexpected data scenarios, e.g. pulling up two certificates where you would only expect one~ 
    * not sure this one is appropriate, it may make more sense as part of a defensive certificate generation strategy

**Comment by stenington** [comment]
@adrichey I don't feel like this ticket needs QA by itself. It's the groundwork for a bunch of other tickets that will all get QA'd so I think we're better off moving on to those tickets. What do you think?

**Comment by adrichey** [comment]
I think you are correct. My assumption on this work would be that it would be a developer ticket that would be closed on pull request. I feel like the new UI and functionality will cover the actual QA testing.

**Comment by kmorton2017** [comment]
are there any action items for the program team on this ticket @adrichey and @stenington

**Comment by adrichey** [comment]
@kmorton2017 No, this is basically all "under the hood" work. I will go ahead and close it since this work is now on QA and other work we are doing is dependent on it. Thanks!
