### ISSUE TITLE
Certificates: Implement certificates datagrid in the Admin UI

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2057]
**Is your feature request related to a problem? Please describe.**
We need to build a new datagrid page in the admin UI so that any certificates existing in the system can be searched for, downloaded, or deleted.

**Describe the solution you'd like**
This will function similarly to the Participants page view in the admin UI where we can view information about various student, mentor, and judge accounts in the system. It will add a Certificates menu item in the right-hand sidebar navigation for Admin accounts on their dashboard. This will lead to a page similar to Participants which contains a table (datagrid) featuring all certificates in the system, sortable by season and account type for all accounts in the system.

**Acceptance Criteria**
1. Log in as an admin user
2. Browse to the "Certificates" option in the right-hand side-bar navigation
3. Make sure that you can view certificates for our end-users by clicking the PDF icon in the table
4. Assert that certificates for judges, mentors, and students all appear and can be downloaded
5. Test to make sure that filters can be applied to the datagrid to filter the table data down

**Comment by stenington** [comment]
I'm not sure what the acceptance criteria is here, although I did notice that the datagrid should probably include the user's first and last name, as that's what ends up on the certificate.

**Comment by adrichey** [comment]
I will update the description with acceptance criteria now.

**Comment by kmorton2017** [comment]
I confirm that I am able to view and download all certificates from this page. Quick reminder that the RPE winner filter is not needed since RPE winners receive the same semifinalist certificate as everyone else.

**Comment by stenington** [comment]
Yeah, good catch @kmorton2017. I'm going to change the filter to only show values that are already in the database.

**Comment by kmorton2017** [comment]
let me know if this ticket is ready to close out or you need it to be tested again!

**Comment by stenington** [comment]
@kmorton2017 Can you just look at the available filters one more time and confirm they make sense to you? RPE winner shouldn't be in there anymore.

**Comment by ophelieh** [comment]
@ophelieh to check

**Comment by ophelieh** [comment]
Everything works great, but the RPE winner certificate is still there. 

![uploads/9d8997f6-f1a3-4dc0-bdbc-56eaa7ef9070/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9d8997f6-f1a3-4dc0-bdbc-56eaa7ef9070%2Fimage.png)

**Comment by adrichey** [comment]
Ah, it looks like you uncovered an actual bug with the code @ophelieh. The issue is that the certificate types got renumbered in our application, but not in the database. @stenington or I will need to address this tomorrow.

@stenington let me know when you have had a chance to look at this and either one of us can implement the solution once we have agreed upon a fix.

**Comment by adrichey** [comment]
Quick follow up for devs. This appears to be happening in: `app/constants/certificate_types.rb`.

**Comment by adrichey** [comment]
Beginning work on this again. Will try to get this done asap.

**Comment by adrichey** [comment]
@ophelieh This bug has been fixed and you should be able to see the correct certificates again. This is once again ready for testing. Thanks!

**Comment by ophelieh** [comment]
Looks good now! :)
