### ISSUE TITLE
Certificates: Create a rake task to generate all certificates for the season

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2059]
**Is your feature request related to a problem? Please describe.**
We want to generate ALL of the appropriate certificates for the season after semifinals ends but before we turn on certificates and scores availability for our end users.

**Describe the solution you'd like**
This will be a rake task that generates a batch of `Jobs` that will handle `Certificate` generation using `FillPdfs`. The rake task should only generate certificates for the 2019 season, but should be implemented in such a way that we can pass flags to the rake task so it can be run for different seasons, and have a flag so that we can limit the amount of jobs that are generated for testing purposes. For example, we can limit the task to only kick off jobs for the first ten records found.

**Comment by stenington** [comment]
@adrichey Can you help me think through QA on this one? It will take some collaboration with the dev team because we'll need to run the rake task by hand. I was thinking something like the following:

1. Developer deletes all of this year's certificates
2. Developer runs one of the rake tasks to generate this year's certificates
3. QA team use Certificates admin page to look through and try to verify the results

Point 3 is deliberately vague; I don't think we need to look at every user in QA, but it would be nice to cover one user per type of certificate at least. What do you think?

**Comment by adrichey** [comment]
@stenington I think that makes sense. I think we will want to go through and set up a scenario for each certificate type. Including General Judge, even though that functionality will be removed soon. Actually, I am almost wondering if we should wait to run this until after we remove General Judge? That might give us a more realistic testing example.

So the test cases in Step 3 become:

- General Judge: Judge account with <= 4 scores (optional, dependent on the assumption that this will be tested before #2001 is in place).
- Certified Judge: Judge account with 5 scores.
- Head Judge: Judge account with between 6 and 10 scores.
- Judge Advisor: Judge account with 11 scores.
- Completion: Student account on a team with a complete submission and that was a quarterfinalist.
- Mentor Appreciation: Mentor account that is not a judge on a team.
- Participation: Student account on a team with an incomplete submission (between 50 and 100% complete).
- Semifinalist: Student account on a team with a submission that made it to the semifinals.

**Comment by stenington** [comment]
I agree about waiting until General Judge is gone. I would also add the test case of

* Judge + Mentor Appreciation: a Judge who qualified for a judge certificate and qualified for 1+ mentor certificates (make sure they received all)

**Comment by stenington** [comment]
Here's a doc where I parse the rake task output a bit to help guide QA: https://docs.google.com/document/d/1oGqMcUb-Xu3QO6q1UU24QNCx1lvcYOtVN93igwOWV54/edit#

**Comment by adrichey** [comment]
To test:
1. Log in as an admin
2. Open the above Google Doc.
3. Pick one or two accounts from each section.
4. On the Participants view in the Admin UI, make sure that those users received the certificate indicated in the section you are looking at.

Do this for the following certificates:
- Certified Judge
- Head Judge
- Judge Advisor
- Completion
- Mentor Appreciation
- Participation

**Comment by stenington** [comment]
I would add in step 4 that you confirm the user you chose **should** receive that certificate.

**Comment by stenington** [comment]
Also, we caught 1 bug while setting up data. Students who have become mentors received both student and mentor certificates when they should only get the mentor one.

**Comment by nickiredescent** [comment]
Can confirm that this works as described. I randomly selected 2-3 participants of each list and checked for their certificate receipt. Certificates were found and they were the appropriate certificate for each participants.

**Comment by stenington** [comment]
https://github.com/Iridescent-CM/technovation-app/pull/2092 fixes the student/mentor bug. I will regenerate certificates for these users only and confirm they just get the mentor certs.

**Comment by stenington** [comment]
Ok, I confirmed that account ophelie+s2@iridescentlearning.org on staging went from showing a student and mentor cert to just the mentor cert, as expected.

**Comment by ophelieh** [comment]
Awesome! Thank you, everyone! :)
