### ISSUE TITLE
Certificates: Add certificate section to admin UI participant pages

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2060]
**Is your feature request related to a problem? Please describe.**
We need to add a certificates section when viewing a participant in the admin UI.

**Describe the solution you'd like**
This section should appear when you click on a student, mentor, or judge in the Participants section of the admin UI. This section should display what certificate(s) the user has and give the admin user the ability to download the generated certificate.

**Additional context**
This does not give the admin user the ability to modify the certificate(s) in any way; it is purely informational so that they can access certificates that have been generated. The ability to generate a new certificate will come in a future ticket to be linked later.

**Comment by adrichey** [comment]
Ability to generate a certificate in this view will come in the work for #2061.

**Comment by adrichey** [comment]
This is ready for testing.

**Comment by ophelieh** [comment]
@nickiredescent and @kmorton2017 Could you both test this? Thanks!

**Comment by kmorton2017** [comment]
I confirm that I can see the Certificate Section on the Participant's profile for student, mentors, and judges.
