### ISSUE TITLE
Certificates: Add ability to generate certificates for a participant

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2061]
**Is your feature request related to a problem? Please describe.**
Add the ability for an admin user to generate a different certificate for an end user on a Participant's page.

**Describe the solution you'd like**
After clicking on an account in the Participants page datagrid in the admin UI, you should see a certificates section (created in #2060) where you can both view currently generated certificates for a user, and have the ability to generate a new certificate. An admin user should get drop-down selectors in order choose the type of account they are generating a certificate for (student, mentor, or judge), what team the certificate should be generated for in the cases of mentor and student, and what type of certificate they should be receiving. There will also be a button to generate the certificate using the drop-down input. Here is a list of combinations that should be available (please note that these may change before QA ready):

- Student
  - No profile type selector
  - Team drop-down should only have one option, the team they are on for the season
  - Should have a drop-down to select a certificate type: Participation, Completion, Semifinalist
- Mentor
  - Should have a team selector to pick from a list of all teams they were on this season
  - Certificate type selector should be available but only have an option for Mentor Appreciation
  - Profile type selector should be present and able to flip between mentor and judge if they have both profiles
- Judge
  - No team selector
  - Certificate type selector should be available with the following options: Certified Judge, Head Judge, and Judge Advisor
  - Profile type selector should be present and able to flip between mentor and judge if they have both profiles

**Additional context**
This work should happen after the work for #2060 has been completed.

**Comment by stenington** [comment]
QA steps:

For each of the following types of users (**Student**, **Mentor**, **Judge**, **Judge & Mentor**) do the following:

1. log in as an admin
2. look up the user in the **Participants** page
3. scroll down to the **2019 Certificates** section
4. confirm the appropriate controls are available for the profile type in the **Manually award certificate** section, e.g. student has student certificate, mentor has mentor certificate, etc.
5. use the controls to create a certificate
6. confirm the certificate appears in the **2019 Certificates** section (note you may have to wait and refresh the page if the certificate doesn't immediately appear)

**Comment by ophelieh** [comment]
@KaiLokken & @nickiredescent Could you test this for student, judge, and judge & mentors

**Comment by nickiredescent** [comment]
Tested. Can confirm that certificate generation works as described for all participants listed.

**Comment by adrichey** [comment]
Thank you @nickiredescent! I will mark this as closed in that case.
