### ISSUE TITLE
Certificates: Make sure judge Certificates for mentor/judges don’t have teams

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2062]
Right now, judge certificates take a team parameter in our `FillPdfs/Certificates` code. We should ensure that Certificates generated for judge profiles that have both a judge and mentor profile associated with the account don't have a team attached to them.

**This is a developer ticket that can be closed on pull request approval and deployment to staging/QA.**

**Comment by adrichey** [comment]
@stenington I am having a little trouble conceptualizing where the fix for this ticket needs to be. I was going to put a check for the judge profile in the `FillPdfs` initialize function, the `CertificateJob` perform function, and `CertificateRecipient` initialize function. But then I realized that mentors will still need a team passed in, so I am debating on how this check should work. Because a judge that is also a mentor could potentially be on a team, I am going back and forth on how this logic should work and where it should appear. Can you provide some insight on how you envisioned this working when we talked about this ticket previously?

**Comment by adrichey** [comment]
@stenington sounds good. I have moved this to To Do in that case. Thanks!

**Comment by stenington** [comment]
Resolved by #2078
