### ISSUE TITLE
Add Cisco option to school/company name drop down

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2066]
**Describe the solution you'd like**
@kmorton2017 has asked that we add a Cisco team to the school/company name drop-down for mentors and judges. They are signing up a specific team and it will help with tracking purposes this season. Katie will provide the exact text that for the drop-down as it won't be just "Cisco" but rather a specific internal team for their organization.

**Additional context**
This has to be done by April 1st. It is a tight deadline, so it will need to go out as a hotfix.

**Acceptance Criteria**
When viewing the School/Company Name drop-down when signing up as a mentor and judge, you receive an option for Cisco in the list. Katie will comment on this ticket with the exact text.

**Comment by kmorton2017** [comment]
Cisco Customer Experience (CX)

**Comment by adrichey** [comment]
Awesome, thanks Katie. I will have this done quickly.

**Comment by adrichey** [comment]
@kmorton2017 This is ready for testing now. Once approved, I will hotfix this into production since it is necessary for April 1st.

**Comment by kmorton2017** [comment]
I confirm that I see this as a company listed while registering.

**Comment by adrichey** [comment]
Great! I am hotfixing this to production now.

**Comment by adrichey** [comment]
This has been hotfixed to production. Closing the ticket.
