### ISSUE TITLE
Add student names and mentor names columns to submissions datagrid

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2091]
An RA has requested that a column for student names and a column for mentor names be added to the submissions datagrid, which will help in preparing event certificates.

**Comment by stenington** [comment]
QA:

1. Log in as RA
2. Go to Submission page
3. Add student names and mentor names as "More columns"
4. click Search
5. Confirm that student names and mentor names show in results
6. Confirm for a team or two that the correct student and mentor names are showing

**Comment by ophelieh** [comment]
@nickiredescent could you test this? Thanks!

**Comment by nickiredescent** [comment]
Tested. Can confirm that there are column settings for mentor and student names and that searching with them also produces their names in the search results. There name displayed in the search results are correct.
