### ISSUE TITLE
Duplicate emails allowed in accounts table by DB index [5,5,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2093]
**Describe the bug**
Every now and then, we get duplicate Accounts in the system that then prevent the person from accessing either one. The strange thing is that they have the same email address which I thought would be prevented by a unique index in the database itself. It turns out [this change](https://github.com/Iridescent-CM/technovation-app/commit/d2526f0fa7250871c28cf3a7117379c0842e065a) removed the unique index and made it only apply for deleted accounts. I don't understand why, but I'm guessing it was a mistake, and should only apply for non-deleted accounts. (I can understand that once they're deleted, we don't care if emails are unique any more.)

**To Reproduce**
This is difficult to reproduce in full, but I suppose we could very that direct insert into the accounts table fails if the email is the same as another non-deleted account.

**Expected behavior**
The index should prevent duplicate emails for non-deleted accounts, if that somehow slips past the other Rails validation in place.

**Comment by stenington** [comment]
There are currently 23 accounts we will have to de-dupe before a fix for this could be put in place.

**Comment by adrichey** [comment]
Thank you for finding this. I have encountered the duplicates on occasion before, and I have just been manually fixing them as I couldn't locate how they were getting in.

**Comment by stenington** [comment]
@kmorton2017 @ophelieh My proposal here would be to delete all but 1 duplicate for each account with duplicates. There's not a ton of them, so I can try to check each to see if one has more information than the others, but by and large I think having a duplicate prevents the user from getting very far so they should basically be the same.

I can just go ahead and do this with your approval, but my question is whether or not you want a list of the accounts to do any communication with those users? We could email saying we had detected a problem and fixed it, or we can just go ahead and fix it quietly. I think that decision is up to you!

**Comment by ophelieh** [comment]
Hi Mike! Thanks for bringing this up. It seems that when there are duplicate accounts, users are stuck and cannot move forward with their account. Keeping just one account sounds good to me, that's what we've been doing so far and it seems to work. :) 

It would be great to get a list, if that's not too much work, but that would be more for us in case a user reaches out to us. 

Thank you!!!

**Comment by stenington** [comment]
Ok! I can keep a list of duplicate accounts, not a problem.

**Comment by stenington** [comment]
Notes for myself:

I think the plan here is:

1. wait until after the next deployment
2. remove the unique index on deleted account email addresses
3. deploy
4. look up duplicate accounts with [this dataclip](https://dataclips.heroku.com/zcnsnrabmblbnvctxzcwhhuzmzmx-TC-account-duplicates)
5. for each, note the email address
6. use the id with the older last login to `Account.find(<id>).destroy` through the console (soft delete)
7. when all duplicates are fixed, add a new migration to create a new index like `add_index :accounts, :email, unique: true, where: "deleted_at IS NULL"`
8. deploy

After that, we should not see duplicate accounts being created.

**Comment by stenington** [comment]
I'm putting this back in the icebox; it should be done ideally prior to the start of next season though.

**Comment by stenington** [comment]
On top of this, it looks like we should remove the unique index on email with `WHERE deleted_at IS NOT NULL`, as that doesn't let us delete a user if an already deleted user had that email address, which doesn't make sense to me.

**Comment by stenington** [comment]
This is on its way to staging. There's no good way I know of to reliably cause the sort of duplicate account creation we're trying to prevent, but I wrote an automated test for it that passed, so that might have to serve as our QA.
