### ISSUE TITLE
Unable to change the images submitted for Paper Prototype and Flowchart

### ISSUE THREAD

**Issue by nickiredescent** [Iridescent-CM/technovation-app#2098]
**Describe the bug**
As a student working on their submission, I am unable to change the image submission for the Paper Prototype and Flowchart section.

**To Reproduce**
1. Log in as a student who is able to begin submissions.
2. Navigate to "Code Checklist"
3. Under the "Pictures of your process" section, attempt to change the images by clicking the "Replace with a file from your computer" button.
4. Once a new picture has been uploaded, click on "Save Checklist", this brings you back to the main submission page.
5. Click on "Code Checklist" again and observe that the images have not changed to the one you've uploaded.

**Expected behavior**
I expect the pictures I upload to save and display.

**Desktop (please complete the following information):**
 - OS: macOS version 10.12.6
 - Chrome
 - Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by stenington** [comment]
I think what's happening here is that the new images are getting uploaded, but the old image is cached in the browser and continues to be shown until the cache expires, which does not happen quickly.

One way to confirm this is to follow the steps above but add step 6:
6. [Refresh your browser cache](https://www.refreshyourcache.com/en/home/) and see that now the newly uploaded image is shown as expected.

As for a long-term fix, I think the answer is to change the cache control headers on our S3 uploads. Right now we're caching aggressively, but I think we might be better off turning off caching and relying on etags to keep the file transfer overhead down. That way if the content of an S3 resource changes (even if the url doesn't) it will be refreshed.

**Comment by stenington** [comment]
QA steps:

1. Log in as a student who is able to begin submissions.
2. Navigate to "Code Checklist"
3. Under the "Pictures of your process" section, if no images have yet been uploaded, select an image for each, click "Save checklist", and then navigate back to the Code Checklist
4. Under the "Pictures of your process" section, attempt to change both the paper prototype and flowchart or pseudocode images by clicking the "Replace with a file from your computer" button.
5. Once a new picture has been uploaded, click on "Save Checklist", this brings you back to the main submission page.
6. Click on "Code Checklist" again and observe that the images you've uploaded are shown.

**Comment by stenington** [comment]
As extra QA, I made sure I had an account on staging where I was experiencing the caching problem before deployment as well, and the deployment fixed it for that account. But I'd still like someone to do the above steps and double-check it for me. Thanks!

**Comment by ophelieh** [comment]
@KaiLokken Could you test this today?

**Comment by KaiLokken** [comment]
Tested it. Worked as expected. The newly uploaded images were shown.
