### ISSUE TITLE
Mentors with judge profiles cannot be added to events

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2099]
**Describe the bug**
People who have a dual profile (mentor/judge) cannot be added to events even if they are not mentoring a team this season. 

In the event tab, you cannot find mentor-judges when trying to add judges to your event. See error message. 

![image](https://user-images.githubusercontent.com/32206421/56315630-d2cb5e80-611d-11e9-87a4-4a73bf2c4227.png)

**Expected behavior**
As an admin or RA, you can add a mentor-judge to an event if that mentor is not on a team this season.

**Comment by stenington** [comment]
@ophelieh Just double-checking: would you have any concerns about a mentor-judge being added to an event as a judge, and then choosing to join a team as a mentor after that?

**Comment by ophelieh** [comment]
I don't think this would happen as submissions are due Tuesday and then mentors won't be able to join teams.

**Comment by stenington** [comment]
What about future seasons?

**Comment by ophelieh** [comment]
For future seasons, I guess if the mentor decides to mentor a team after signing up as a judge at an event, it would drop him/her from the event. If that's doable. 

Another way, would be having a mentor who signed up as a judge for an event not be able to add teams anymore.

What do you think is best?

**Comment by stenington** [comment]
I'm not sure, maybe it's best to rely on RAs to choose their judges carefully and let them choose mentors as judges if they want to? If a mentor was really determined to also judge at an event they could just create a second account so it's not like the way the platform works now is foolproof. What do you think about removing any restrictions on judges also having mentor accounts whether they're on teams or not?

**Comment by ophelieh** [comment]
Touche!

From what I have heard in the past, there has been some shady things going on with judges, so I would recommend keeping the restriction on mentors on teams, but if @kmorton2017 feels like we could remove the restriction altogether, then I am fine with that. 

I just don't want us to end up with a case of an RA is not being "fair" and allowing mentors on teams to be judges. But then again, they could be mentoring a team and not be registered on the platform so... I don't think any of our solutions would be foolproof. And I realize that I'm not being very helpful right now...

**Comment by stenington** [comment]
#2111 is the short-term fix ticket. Putting this one in the icebox for the long-term fix.
