### ISSUE TITLE
Fix copy on judge scoring page

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#2101]
I notice that the copy on the left hand side needs updated because there is a typo. "Even after finishing a score you have until to make changes." 

This is the text I see during the QF. It should say: "Even after finishing a score you have until June 2nd to make changes." 

![Screen Shot 2019-04-17 at 2 52 18 PM](https://user-images.githubusercontent.com/32206427/56323671-7ff3a600-6121-11e9-8835-a7cd054fc0a4.png)

**Comment by stenington** [comment]
QA:

1. log in as a judge
2. start a score
3. confirm the message in the sidebar is correct

@kmorton2017 I just noticed it looks like this right now (I have the date configured as April 10):

![Screen Shot 2019-04-19 at 10 36 45 AM](https://user-images.githubusercontent.com/55319/56428932-214c3a80-628f-11e9-877f-08e07ffffd19.png)

Do you think the **(US/Pacific time)** makes sense to leave, or should I drop that?

**Comment by ophelieh** [comment]
I feel like that makes sense, especially for countries who are a day ahead or behind. It kinda sets the expectation but I don't think it would hurt anything to remove it either. @kmorton2017 what do you think? 

Tested it. Works as expected.

**Comment by kmorton2017** [comment]
confirm. Leave as US/Pacific time.
