### ISSUE TITLE
Create live/virtual judge filter for 2019 season

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2103]
**Describe the bug**
At this time, we have no way of telling if a judge from the 2019 season is a live or virtual judge. 

Two possible solutions: 
* Add live/virtual filter on the “participants’ page” for judges
* Filter judges by year on the “judges” tab

**Expected behavior**
We can filter judges to see which ones are attending a live event and which ones are virtual judges.

**Comment by stenington** [comment]
The PR adds a few things:

As an admin, on the **Participants** page:
* There's now a **Virtual or Live** filter
* There's now a **Virtual or live** option under **More Columns**
* Also, selecting an option from the **Virtual or Live** filter or from the **Onboarded Judges** filter without first selecting Judge as a **Profile Type** should no longer cause an error!

On the **Judges** page:
* There's now a **Season** filter that lets you choose one or more seasons.

For QA, I would suggest at a minimum we:

1. log in as an admin
2. go to **Participants**
3. select **Virtual or live** under **More columns** and click "Search"
4. make sure the results make sense
5. filter by **Virtual judges** and click "Search"
6. make sure the results seem to make sense
7. filter by **Live judges** and click "Search"
8. make sure the results seem to make sense

1. log in as an admin
2. go to **Judges**
3. select **2019** as the season and search
4. confirm you get judges
5. deselect 2019, select a past season and search
6. confirm you get no judges (staging has no past season judge accounts)

**Comment by ophelieh** [comment]
@kmorton2017 @KaiLokken Can you both test this? Thank you!

**Comment by KaiLokken** [comment]
Situation 1: TESTED IT
-It worked as expected once applying the "filter by virtual judges" or "filter by live judges"

log in as an admin
go to Participants
select Virtual or live under More columns and click "Search"
make sure the results make sense-IT INCLUDED ALL PARTICIPANTS (i.e. STUDENTS) 
filter by Virtual judges and click "Search"
make sure the results seem to make sense-WORKED AS EXPECTED
filter by Live judges and click "Search"
make sure the results seem to make sense-WORKED AS EXPECTED

Will now test Situation 2

**Comment by KaiLokken** [comment]
Situation 2: Tested it. 
33 judges for 2019 season. 
10 judges for 2018 season
Zero judges for 2015-2017 season

**Comment by kmorton2017** [comment]
Situation 1: 

I think the reason why Kai got all participants in her search results is because she did not select "judges" as a profile type. I selected judges as a profile type and only saw judge accounts. 

Comments: 
- I would like the ability to sort by ascending/descending on my screen view. Currently when I add "Virtual or live" as a column I am not able to do so. 

Situation 2: 
I confirm what Kai said. I am able to see 10 judges from 2018.

**Comment by stenington** [comment]
@kmorton2017 I don't think I can give you sorting on the "Virtual or live" column. Sorting relies on the database to do the ordering of records, but virtual or live is not stored in the database directly, it's something we calculate once we've pulled their profile data out of the database. Sorry!

**Comment by kmorton2017** [comment]
No worries. We can always sort it on spreadsheet. thanks!
