### ISSUE TITLE
Thunkable share url help text

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2105]
The share url has to be [generated a certain way](https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-source-code-from-a-Thunkable-X-project-), but many users are trying to put in the project url. Details being hashed out in Slack.

**Comment by kmorton2017** [comment]
The help text is not appearing for me yet. 

![uploads/05ec7836-e172-43a7-a632-c694e230fb30/Screen Shot 2019-04-19 at 2.48.13 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F05ec7836-e172-43a7-a632-c694e230fb30%2FScreen+Shot+2019-04-19+at+2.48.13+PM.png)

**Comment by amyiridescent** [comment]
Me either. I don't see the help text that should appear. I changed the platform away from thunkable and back to thunkable and only see the one blue box...

**Comment by stenington** [comment]
Yeah you're both too fast today! I moved the ticket into test before it was technically on QA. Tests are running, then it will auto-deploy. There will be a message in #dev-robots once that happens.

**Comment by stenington** [comment]
Also apparently I wrote my QA steps in the wrong spot:

QA:

1. log in as a student
2. edit your submission
3. select Thunkable as your development platform
4. confirm you have help text for finding your shareable URL, and the link works

**Comment by stenington** [comment]
Ok it just deployed!

**Comment by amyiridescent** [comment]
Yeap I see it now when I select Thunkable as a platform. But not when i select other platforms (including Thunkable classic.) The "this article" link takes me to the correct zendesk ticket. 

![uploads/46bdfd98-cb6f-4cbb-8cb9-0106ca47b4d5/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F46bdfd98-cb6f-4cbb-8cb9-0106ca47b4d5%2Fimage.png)
