### ISSUE TITLE
RAs should not be able to switch to judge [8,2,4]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2107]
> An RA account is unable to switch into judge mode. The flow is RA account> click mentor mode> click "switch to judge mode"> "Uh oh, something went wrong". 

It appears that we explicitly don't auto-create judge accounts for RAs, but then the link to switch doesn't work unless they already have a judge profile.

**Comment by stenington** [comment]
@ophelieh @kmorton2017 I wrote this one up on behalf of Mackenzie last week, but I'm not 100% clear on the request here. Do we need a way for RAs to switch to judge mode in their account? Are there any special considerations I need to know about with RAs being judges, or do you think the system handles that already?

**Comment by stenington** [comment]
We will handle individually cases manually for now, this ticket is going in the icebox as a reminder for a long-term fix to be prioritized later.

**Comment by stenington** [comment]
The current recommendation is that RAs should never be judges, and we would enforce that on the platform and message it out to participants.

**Comment by stenington** [comment]
I think the work here just amounts to hiding the "Switch to judge" button if `current_mentor.is_an_ambassador?` is true.

**Comment by stenington** [comment]
It looks like RAs logged in to their RA dashboards always have a "Mentor mode" link, and optionally have a "Judge mode" link **only if they have a judge profile**. The problem was that any RA, even one without a judge profile, could switch to their mentor dashboard and then see a "Switch to Judge mode" link, and try to become a judge that way.

This year, the decision is that RAs shouldn't judge at all. This ticket focuses on the RA > Mentor > Judge path, but I wonder if we want to hide the "Judge mode" link from the RA dashboard as well, just in case some RAs already have judge profiles? @rsgonzal or @ophelieh what do you think?

**Comment by stenington** [comment]
Looks like 55 current RAs also have judge profiles, so I'm guessing we should disable that button so they cannot switch to judge mode this year.

**Comment by ophelieh** [comment]
@stenington That works for me!

**Comment by rsgonzal** [comment]
Looks like Ophelie approved! So all good :)

**Comment by stenington** [comment]
## Context for QA:

There are two relevant pieces of config: `ENABLE_SWITCH_TO_JUDGE` and `ENABLE_RA_SWITCH_TO_JUDGE`. 

When `ENABLE_SWITCH_TO_JUDGE` is turned on...
* mentors (who are not also RAs) should be able to switch to the judge dashboard from the mentor dashboard
* RAs should not be able to switch to the judge dashboard from either the RA dashboard or the mentor dashboard

When `ENABLE_RA_SWITCH_TO_JUDGE` is turned on...
* mentors should not be able to switch to the judge dashboard from the mentor dashboard
* RAs *who already have judge profiles* should be able to switch to the judge dashboard from the RA dashboard and from the mentor dashboard
* RAs who do not already have a judge profile set up should not be able to switch to the judge dashboard from either location

When both are off...
* nobody should be able to switch to the judge dashboard from any other dashboards

The key thing we're trying to enforce here for this season is that
1. mentors can be judges
2. RAs cannot be judges, *even with a judge profile*

so those would be the critical QA scenarios. 

## QA Scenarios

### Mentors

With `ENABLE_SWITCH_TO_JUDGE` off...
1. log in as a mentor
2. make sure you do not have a link to switch to judging on the dashboard

With `ENABLE_SWITCH_TO_JUDGE` on...
1. log in as a mentor
2. make sure you have a "Switch to judge mode" link
3. click the link
4. make sure you're now on the judging dashboard

### RAs

With `ENABLE_SWITCH_TO_JUDGE` off and `ENABLE_RA_SWITCH_TO_JUDGE` off...
1. log in as an RA without a judge profile
2. make sure you do not have a link to switch to judging on the RA dashboard
3. click the link to switch to mentoring
4. make sure you're on the mentor dashboard, but do not have a link to switch to judging

Repeat for an RA with a judge profile:
1. log in as an RA with a judge profile
2. make sure you do not have a link to switch to judging on the RA dashboard
3. click the link to switch to mentoring
4. make sure you're on the mentor dashboard, but do not have a link to switch to judging

With `ENABLE_SWITCH_TO_JUDGE` on and `ENABLE_RA_SWITCH_TO_JUDGE` on...
1. log in as an RA without a judge profile
2. make sure you do not have a link to switch to judging on the RA dashboard
3. click the link to switch to mentoring
4. make sure you're on the mentor dashboard, but do not have a link to switch to judging

Repeat for an RA with a judge profile:
1. log in as an RA with a judge profile
2. make sure you do not have a link to switch to judging on the RA dashboard
3. click the link to switch to mentoring
4. make sure you're on the mentor dashboard, but do not have a link to switch to judging

### Less crucial RA scenario that we don't plan to use this year

With `ENABLE_RA_SWITCH_TO_JUDGE` on...
1. log in as an RA without a judge profile
2. make sure you do not have a link to switch to judging on the RA dashboard
3. click the link to switch to mentoring
4. make sure you're on the mentor dashboard, but do not have a link to switch to judging

Repeat for an RA with a judge profile:
1. log in as an RA with a judge profile
2. make sure you have a link to switch to judging on the RA dashboard
3. click the link, and confirm you're on the judge dashboard
4. switch back to RA mode
5. click the link to switch to mentoring
6. make sure you're on the mentor dashboard, and you have a link to switch to judging
7. click the link, and make sure you're on the judge dashboard

**Comment by shaunxp20** [comment]
Awesome QA steps/write up! Thanks for that @stenington! 💯 

I'm testing this on the QA environment, I think I'm doing something wrong! I tried setting `ENABLE_SWITCH_TO_JUDGE` to both `false` and `0`, but when I log in as a mentor I still see the "Switch to judge mode" link. 🤔 😕

**Comment by stenington** [comment]
Oh, sorry @shaunxp20. The convention I use with ENV parameters is that 1 is "true" and ~~the empty string or~~ deleting the config altogether is "false". Both `false` and `0` would just be pulled from the environment as strings and not evaluated further, and since non-empty strings are truthy, they would still be turning that config on.

And actually, I just realized that Ruby considers empty strings to be truthy (whereas Python does not) so in fact, the only option here is to delete the `ENV` parameter you're wanting to turn off.

**Comment by shaunxp20** [comment]
Ah, that totally makes sense! Thanks @stenington! 🙇 

I deleted the ENV and it's working as expected! 👍 

I'm wondering that's something we should document - how to turn off features and maybe a master list of our ENVS; and/or making true/false work as values. Anywho, just some random thoughts. 😃 👍

**Comment by stenington** [comment]
Yep, open to all of those ideas. I believe it is actually documented somewhere, but I'm not sure where at this point, and I don't think we have a single "source of truth" for these things. Was there somewhere specific you looked that could be updated? The README or something?

And I'm open to more sophisticated processing of environment parameters, with the caveat that when we did more sophisticated processing in the CM project, we had problems with e.g. a typo like `ture` being considered false, while the person who typed it pulled their hair out wondering why the app wasn't doing what they just configured it to do. I would suggest we could fail fast on unexpected input, but that gets a little scary in production where I would arguably rather have the config not take if I make a typo rather than blowing up the whole app (although I think I could be convinced that failing fast, even in production, would be beneficial).

But yeah, I also stumbled over `ENV` configuration early on, I've just gotten inured to it at this point.

**Comment by shaunxp20** [comment]
> Was there somewhere specific you looked that could be updated? The README or something?

I looked in the README for what it has for ENV related stuff, there isn't much. Not sure where else to look. 🤷‍♂ 😊 Anywho, I'll make a note for myself to update the README at least.

>  we had problems with e.g. a typo like ture being considered false

It's a bummer that you can't have a select field in the Heroku GUI instead of a free-form text field for the ENV values.

On a side note, I stumbled upon this library/gem (not sure if it's worth switching, just throwing it out there):
https://github.com/fnando/env_vars

This is what is says about booleans: 

> Any of yes, true or 1 is considered as true. Any other value will be coerced to false.

Not sure how often we need to do it, but that would solve the problem of having to delete an ENV to disable a feature. 🤷‍♂ 🤔  🌲 🚶‍♀ 🌞

**Comment by shaunxp20** [comment]
Any tips on how to find an RA that's also a judge? I logged in as an admin to try to find one, but I can't seem to find the RA field/value to search by. 😕 🙈 😂

**Comment by shaunxp20** [comment]
I think I figured out a workaround, I used the admin feature to convert the RA account to a judge-only account, and was able to test that way! 👍 Think I'm good for now! 😄

**Comment by shaunxp20** [comment]
> With ENABLE_SWITCH_TO_JUDGE on and ENABLE_RA_SWITCH_TO_JUDGE on...
> 
>     log in as an RA without a judge profile
>     make sure you do not have a link to switch to judging on the RA dashboard
>     click the link to switch to mentoring
>     make sure you're on the mentor dashboard, but do not have a link to switch to judging
> 
> Repeat for an RA with a judge profile:
> 
>     log in as an RA with a judge profile
>     make sure you do not have a link to switch to judging on the RA dashboard
>     click the link to switch to mentoring
>     make sure you're on the mentor dashboard, but do not have a link to switch to judging
> 

I think I might be missing something on the `Repeat for an RA with a judge profile:` steps. If both `ENABLE_SWITCH_TO_JUDGE` and `ENABLE_RA_SWITCH_TO_JUDGE` are enabled, shouldn't an RA with a judge profile see the switch to judging link? 🤔 😕 🤕 😀

**Comment by stenington** [comment]
Updated the QA steps to say "ENABLE_SWITCH_TO_JUDGE on and ENABLE_RA_SWITCH_TO_JUDGE **off**..." which is what that case should have been. Good catch!

**Comment by shaunxp20** [comment]
Not exhaustive, but here are all the test scenarios I did:

||ENABLE_SWITCH_TO_JUDGE|ENABLE_RA_SWITCH_TO_JUDGE|
|-|------------------------------|-----------------------------------|
Mentor|Disabled|Disabled|
Mentor|Enabled|Disabled|
Mentor|Disabled|Enabled|
RA w/ judge profile|Disabled|Disabled|
RA w/ judge profile|Disabled|Enabled|
RA w/ judge profile|Enabled|Disabled|
RA as mentor w/ judge profile|Enabled|Enabled
RA as mentor w/ judge profile|Disabled|Enabled
RA as mentor w/ judge profile|Disabled|Disabled
RA w/o judge profile|Disabled|Disabled|
RA w/o judge profile|Enabled|Enabled|

From what I could tell everything is behaving as expected. 👍 😅 

And just a side note, the "RA w/o judge profile" scenarios I did from the impersonation feature in the admin area.

Also, another side note, something I wish I would have caught in code review, it would have been nice if `ENABLE_SWITCH_TO_JUDGE` was renamed to `ENABLE_MENTOR_SWITCH_TO_JUDGE`, anywho, #random-banter #just-quibbling #stinking-up-the-joint 😂 🤣 😀

**Comment by stenington** [comment]
Yeah I agree that variable naming would have been better. It could still be done! What do you think @rsgonzal?

**Comment by rsgonzal** [comment]
I do think `ENABLE_MENTOR_SWITCH_TO_JUDGE` would be more clear, but the way it's listed now makes sense to me too!

Question about this account: roxana+666admin@iridescentlearning.org
It looks like it was a student? and a mentor? Whatever it is, I see the switch to judge link, but then get an error. Not sure when I created that account or got into that situation, so it may not be relevant? 🤷‍♀

**Comment by rsgonzal** [comment]
This mentor account also sees the link but can't switch, i get the following page -mackenzie+2m@iridescentlearning.org

![Screen Shot 2020-01-21 at 2 21 35 PM](https://user-images.githubusercontent.com/22801026/72848478-889d7d80-3c59-11ea-8b6e-4f40acef118e.png)

**Comment by rsgonzal** [comment]
All other scenarios I tried, check out. 

Looks like it's just these two weird accounts I happened to login as.

**Comment by stenington** [comment]
> Question about this account: roxana+666admin@iridescentlearning.org

Yep, looks like that account has both a student profile and mentor profile. We have about 60 of those in production, 26 of those in the 2020 season. I think we saw problems with student/mentor combo accounts last year, and if I'm remembering correctly we began asking students who wanted to be mentors to create new accounts. I think there's a lot of logic in the platform assuming that a user will never be both a student and a mentor, so updating it to make that work right would be a lot of effort.

I opened #2354 to continue this convo if needed.

> This mentor account also sees the link but can't switch, i get the following page -mackenzie+2m@iridescentlearning.org

Ok, the error here seems to be that when you click the link, the judge profile isn't automatically getting created. @rsgonzal Can you try by logging in directly as that user, and not by switching to them from an admin account? I believe if you're logged in as an admin and pretending to be a mentor, the automatic judge creation code doesn't work.

**Comment by rsgonzal** [comment]
I wasn't able to change Mackenzie's password, but I created a new mentor account and creating the judge profile worked.
