### ISSUE TITLE
Code checklist max score problem

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2110]
**Describe the bug**
In the code checklist, the points calculation for Mobile Features is slightly broken. The points tally on the right can show scores like 4/2, 6/2, etc. 

*The actual score does not seem to count more than 2, just the displayed number.*

**To Reproduce**
1. Go to the code checklist page
2. Select a mobile feature and provide an explanation.
3. Save
4. Go back to the checklist
5. Select another mobile feature, provide an explanation
6. Notice you now have 4/2 points according to this page

**Expected behavior**
@ophelieh Can you help me here? Is it that the user should be able to select many mobile features but the score should never exceed 2/2, or is it that after selecting one they should not be able to select more?

**Screenshots**
![Screen Shot 2019-04-22 at 11 11 59 AM](https://user-images.githubusercontent.com/55319/56507488-725a6980-64ef-11e9-8660-48de8495e0ed.png)

**Comment by stenington** [comment]
An additional note: what the UI does right now is after you've selected one, it realizes you've hit the max 2/2 points and doesn't let you select more. I'm wondering if that's wrong and teams should be able to select as many as they want, but the score should never go beyond 2.

**Comment by ophelieh** [comment]
**Expected Behavior**
Teams should be able to select more than one mobile feature, but the score should max at 2 points. 

We might need to rework the wording for next year. 

Thank you!

**Comment by stenington** [comment]
Putting this in the icebox. It's good to fix, but a bit late for it to matter this year.

**Comment by rsgonzal** [comment]
we've removed the technical checklist!
