### ISSUE TITLE
Allow mentors to be RPE judges

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2111]
**Describe the solution you'd like**
This is the short-term fix for #2099. Right now we want to allow mentors to be RPE judges. Next season, we'd like it to be okay for RPE judges to have mentored in the past, but they shouldn't currently be mentoring any teams.

**Comment by stenington** [comment]
QA:

1. Log in as an RA
2. Go to Judges page
3. Select "Yes, is also a mentor" from **Has Mentor Profile** filter
4. Search
5. Make note of 1 or 2 of these judge/mentor profiles
6. Navigate to an event
7. Click "Add Judges"
8. Search for mentor/judge  
9. Confirm they appear in the search results and can be added to the event

**Comment by ophelieh** [comment]
@KaiLokken Can you test this one?

**Comment by KaiLokken** [comment]
Tested it. Worked as expected. Was able to add the mentors/judges for all of the events.
