### ISSUE TITLE
Make thunkable share URLs editable in admin

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2113]

**Comment by stenington** [comment]
QA:

1. log in as admin
2. find a submission using Thunkable
3. edit submission
4. change the values for Thunkable email and url
5. save
6. edit again to verify the new values you chose were saved

**Comment by ophelieh** [comment]
@KaiLokken and @kmorton2017 Can you both test this?

**Comment by KaiLokken** [comment]
Tested it. Worked as expected. All changes (new url, new email address, app description) saved.

**Comment by ophelieh** [comment]
This works great but only the x.thunkable.com/copy/abc123 type link works. I tried - x.thunkable.com/project/abc123 and it said it was invalid. Also, is it possible to show the link once it is saved? RAs do not have the option to edit submissions, which is the only way to see the link as of now. Thanks!

**Comment by stenington** [comment]
Oh, sure. It will show like this if the development platform is Thunkable:
![Screen Shot 2019-04-23 at 4 11 35 PM](https://user-images.githubusercontent.com/55319/56612489-8206aa80-65e2-11e9-947d-c242e8c39e3f.png)

**Comment by ophelieh** [comment]
Perfect. Thanks!

**Comment by stenington** [comment]
@ophelieh Ok you should now see that in staging. Can you confirm it shows up as an RA?

**Comment by ophelieh** [comment]
Checking now.

**Comment by ophelieh** [comment]
As an admin - I can see the link but it spills over 
![image](https://user-images.githubusercontent.com/32206421/56613938-5fbe5e00-65dd-11e9-803d-74a013f81508.png)
 https://technovation-qa.herokuapp.com/admin/team_submissions/refugee-help-by-segovia-princesses#/

**Comment by stenington** [comment]
Oh yeah, you're right. RAs have a totally separate template. I'll update that too.

**Comment by stenington** [comment]
Ok @ophelieh! RAs should have the info now too, and both RA and admin screens should wrap long urls:

![Screen Shot 2019-04-23 at 5 27 45 PM](https://user-images.githubusercontent.com/55319/56617160-1fff7280-65ed-11e9-8089-cd884d746adf.png)
![Screen Shot 2019-04-23 at 5 27 21 PM](https://user-images.githubusercontent.com/55319/56617162-21309f80-65ed-11e9-982c-bb3e83b43e75.png)

**Comment by ophelieh** [comment]
Perfect. @nickiredescent Can you help me test this?

**Comment by nickiredescent** [comment]
Tested.
As both an admin and as an RA I am amble to see the Thunkable Project URL, with the text formatting to wrap around the white box.

Thanks @stenington!

**Comment by ophelieh** [comment]
Works great! All ready to go. Thank you both!
