### ISSUE TITLE
Allow both Thunkable share and project URLs

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2115]
Allow links of both forms `x.thunkable.com/copy/abc123` and `x.thunkable.com/projects/abc123`

**Comment by stenington** [comment]
QA:

1. log in as a student or mentor on a team with a submission
2. edit the submission development platform
3. choose Thunkable and enter a project url 
4. confirm that the url saves
5. enter a Thunkable share url
6. confirm the url saves

**Comment by ophelieh** [comment]
@KaiLokken can you test this?

**Comment by ophelieh** [comment]
Hi @stenington The share URL works for me but not the project URL.

**Comment by stenington** [comment]
@ophelieh Can you give me the full url you tried to enter? From the part I can see, the URL you entered should be valid.

**Comment by ophelieh** [comment]
https://x.thunkable.com/projects/5c49237b6951551e3fc1f18c/Screen1/designer

**Comment by ophelieh** [comment]
![image](https://user-images.githubusercontent.com/32206421/56611391-44e8eb00-65d7-11e9-9920-147ca3c2030e.png)

**Comment by stenington** [comment]
Oh ok, I didn't know it should allow extra path segments like `/Screen1/designer`, it only allows up to `https://x.thunkable.com/projects/5c49237b6951551e3fc1f18c` right now. I can fix that.

**Comment by ophelieh** [comment]
Could also be looking like this - https://x.thunkable.com/projects/5bcd159416e056ddc91447a3/share/blocks depending on which window they are on when they share the link.

**Comment by ophelieh** [comment]
This is the designer link for that team as well so you can see the different types of links - https://x.thunkable.com/projects/5bcd159416e056ddc91447a3/Screen1/designer

**Comment by stenington** [comment]
Ok! I'm basically going to open it up so that anything after `copy/abc123` or `projects/abc123` is allowed. So both examples above would be considered valid.

**Comment by stenington** [comment]
@amyiridescent says this ticket is not needed, just confirming here that we're going back to just the `copy/abc123` format @ophelieh?

**Comment by KaiLokken** [comment]
Tested it. But, had Thunkable generate its own link. the generated link worked and saved properly.

**Comment by ophelieh** [comment]
Hi @stenington Yup we are. Sorry about the extra work!
