### ISSUE TITLE
Google Analytics is included in all environments [5,5,1.0; it-05 *,2,*]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2117]
**Describe the bug**
Google Analytics sends data from all environments to the same account, which muddies production analytics data.

**Expected behavior**
Dev, staging, and tests would either not send analytics or send them to a different ID.

**Comment by hellafitz** [comment]
Rec: Staging should track w/ a separate ID. Test and Dev don't need to track.

**Comment by stenington** [comment]
@rsgonzal This one is also ready to discuss QA

**Comment by hellafitz** [comment]
Convince ourselves Staging tracks to a separate ID (that doesn't yet exist and has to be created), AND that product tracks to the old ID after deployment.

Remaining work: set up a new ID for Staging. Configure Staging to use that ID. 

QA plan: 
- Open Google Analytics to Real Time dashboard for Staging. Navigate around and make sure you show up. 
- Open GA to the Real Time dash for Production (after Deployment). Navigate around and make sure you show up.

**Comment by stenington** [comment]
Config has been set in staging and production. Staging page hits track in the correct realtime analytics section. This is done, with the caveat that we need the final sanity check after deployment.
