### ISSUE TITLE
RPE Teams Adding Presentation Slides to their Submission

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#2119]
In previous years, if a team selected a Regional Pitch Event to attend, they were able to upload their presentation slides after the submission deadline. 

Currently, the platform does not allow teams to do so. Can we investigate the code from previous years to see how this was made possible? 

**Describe the solution you'd like**
Teams who are attending a Regional Pitch Event should be able to upload their Presentation Slides at any point from April 27-June 2nd. 

**Describe alternatives you've considered**
If we do not implement a software solution, we will need to tell RA's to manually collect this from all teams. 

**Additional context**
Perhaps the dashboard could have a section that says "upload your presentation slides here" if they are attending a Regional Pitch Event. 

![Screen Shot 2019-04-25 at 4 38 34 PM](https://user-images.githubusercontent.com/32206427/56774698-adbb9900-6778-11e9-9372-90589075ee83.png)

**Comment by stenington** [comment]
Here's a ticket from last year with a screenshot that I think gives a hint of what the feature looked like: https://github.com/Iridescent-CM/technovation-app/issues/1516

Note that that's the old non-Vue dashboard. I doubt the current version of the dashboard ever had this ability, so I don't think there's old code we can resurrect. I think we have to build the feature new, but if I stumble on something that indicates otherwise I'll update this ticket.

As a new feature, putting it on the submission part of the student dashboard works for me. I'll take a look at doing that.

**Comment by kmorton2017** [comment]
hi @stenington so i did some recon and it turns out our largest events do indeed rely on the platform to have teams upload their presentations. i checked in with a few of our largest events and they are giving them a deadline of May 7th and may 12th to upload their presentation. do you think this is a doable feature to build out in time? let me know !

@ophelieh

**Comment by stenington** [comment]
There are a whole handful of possible scenarios to test here. I think the main ones would be:

1. As a student during submissions
    * make sure you can build your submission as usual. 
2. As a student during quarterfinals
    * on a team in an RPE
        * make sure you can edit your presentation slides
        * make sure you can't edit the rest of your submission
    * on a team in virtual judging
        * make sure the dashboard looks fine (doesn't show you the presentation slides stuff)
3. As a student after quarterfinals
    * on a team that was in an RPE, make sure the dashboard stops letting you edit your pitch presentation

**Comment by ophelieh** [comment]
Everything works great! One thing I have noticed though is that during quarterfinals I can't see which event I am registered for.

**Comment by stenington** [comment]
Yeah @ophelieh I noticed that too, I don't think the dashboard is very effective at certain times of the season. I think that would be a good discussion to have for next season, but I didn't address it here to keep the scope of the change as small as possible to be able to do it quickly.

**Comment by ophelieh** [comment]
Makes sense. I'll add it to our list for next year. :) 

Thank you!
