### ISSUE TITLE
Add Judge Resource Page to Judge Dashboard

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#2120]
Can we add the Word Press site for judges to their dashboard? 

![Screen Shot 2019-04-25 at 4 45 14 PM](https://user-images.githubusercontent.com/32206427/56774940-9f21b180-6779-11e9-8095-ed0ee9ee66ef.png)

 Under Judge Resources, it can say "View our Resource Page" and hyperlink to http://technovation.staging.wpengine.com/judge-resources/ Note this is still on word press staging.

**Describe alternatives you've considered**
If we do not add this to the dashboard, we will post it each week in emails and on slack.

**Comment by kmorton2017** [comment]
This is the live page: https://technovationchallenge.org/judge-resources/

**Comment by stenington** [comment]
QA:
1. log in as a judge
2. locate "Judge resources"
3. follow new link, confirm it goes to production Wordpress page

**Comment by kmorton2017** [comment]
Confirmed.
