### ISSUE TITLE
Deleting a judge's account + scores

### ISSUE THREAD

**Issue by KaiLokken** [Iridescent-CM/technovation-app#2123]
Hello!
Problematic judges: 
- Does deleting a judge's account automatically delete all of the judge's scores?
- Or, do you need to separately delete the judge's scores? Then, delete the judge's account.
- Is it possible to: 
1. Keep some of the judge's scores,
2. Delete the other scores,
3. Then, delete the judge's account

Thanks!

**Comment by stenington** [comment]
Hi @KaiLokken! Deleting a judge profile will delete all their scores as well. You do not have to do that separately. 

I don't believe you can delete a judge account but keep some of their scores around. The score model is linked to the judge model in the codebase, so you can't have a score without a judge who created it.
