### ISSUE TITLE
New score very slow for some virtual judges

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2124]
Some virtual judges are trying to get scores and getting stuck at the spinner.

This is a combo of taking too long to find a score, and our UI not communicating errors, because the request times out before the backend is providing a response.

**Comment by stenington** [comment]
Here's what I have for error messaging. It could probably be improved, but it's "Error encountered while finding a submission. Please try again or contact support." as a starting point.

![tooslow](https://user-images.githubusercontent.com/55319/56925126-96dcb580-6a9c-11e9-890b-f93fefb39f9c.gif)

**Comment by stenington** [comment]
Let me know if a different message would be better. Otherwise...

QA: 

I don't think it's going to be possible to force a timeout to see the error message, so I think we may just have to settle for:

1. log in as a virtual judge
2. click "Start new score"
3. confirm that you get a submission to score

On production I can New Relic and Heroku metrics to see if it looks like response times improve at all. The hope is that people in general **do not** see the new error message, because the code can run fast enough to finish in time to prevent that.

**Comment by kmorton2017** [comment]
i am able to start and score a new submission
