### ISSUE TITLE
Incomplete video submissions can be published [8,8,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2131]
**Describe the bug**
An incomplete submission can be published by following a certain sequence of steps

**To Reproduce**
1. Go to a submission that is complete except for the demo video
2. Begin adding the demo video link
3. Click Next
4. Click the button to publish on the right, do not click Save first

**Expected behavior**
I think two things should be expected: 
1. I can't publish until the submission is actually complete (on the backend, not just in the frontend)
2. If I do manage to attempt to publish, a final completeness check should be made and the submission should be rejected in the above case with an error message

**Screenshots**
![bug](https://user-images.githubusercontent.com/55319/57024181-fbfdeb80-6c01-11e9-8650-25b396e7738e.gif)

**Comment by stenington** [comment]
This bug is the cause of #2129 I think

**Comment by hellafitz** [comment]
Wait to see what the program team recommends in terms of video submission changes. Also informed by Vue tech debt investigation.

**Comment by stenington** [comment]
@rsgonzal @hellafitz This ticket is another that we probably want the program team to look at and prioritize. I believe it caused a snafu last year around submissions time, and we probably want to address it with the pitch video this year ahead of time.

**Comment by rsgonzal** [comment]
Thanks, Mike! Will add to list.

**Comment by stenington** [comment]
Note in the animated gif above that the sequence is something like...

**With a submission that only needs a demo video to be complete**
1. click "Demo video"
2. enter a link
3. click "Next"
4. notice "Demo video" checkbox is now checked, and "Review and submit" button is now enabled

What we want is to have the user click **Save** before showing them that their project can be submitted.

QA:

**With a submission that only needs a demo video to be complete**
1. click "Demo video"
2. enter a link
3. click "Next"
4. confirm "Demo video" checkbox is still not checked, and "Submit for judging" button is still disabled
5. click "Save"
6. confirm "Demo video" checkbox is now checked, and "Review and submit" button is enabled
7. click "Review and submit"
8. confirm that demo video is there

**Comment by rsgonzal** [comment]
I went through this one and looks good. Waiting for feedback from program team.

**Comment by ophelieh** [comment]
Note - All the students on your team first need to be fully onboarded in order to see the "submit for judging". Otherwise, you will see this. 
![uploads/deefa6a8-5a2f-4810-b0f4-4aa4d0ccbd83/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdeefa6a8-5a2f-4810-b0f4-4aa4d0ccbd83%2Fimage.png)

Tested - works as expected.

**Comment by ophelieh** [comment]
Side note - The email confirmation has the wrong judging opening date. 

 
![uploads/17467312-d6dd-4f6c-b453-3e1805e64017/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F17467312-d6dd-4f6c-b453-3e1805e64017%2Fimage.png)


It now should read April 23. Than you!

**Comment by stenington** [comment]
Thanks for catching that @ophelieh, @rsgonzal is changing config to correct that date.

**Comment by devincdillon** [comment]
I did the steps that Roxana suggested and they worked as she said they would.

Noting that I don't understand exactly what I was checking for so can't really flag if anything is weird.
