### ISSUE TITLE
Suspending a judge

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2135]
**Is your feature request related to a problem? Please describe.**
We need to be able to suspend some judge accounts. Currently we have an extreme measure to prevent certain accounts from creating judge profiles, but it's unwieldy as an ongoing tool for managing judge suspensions.

**Describe the solution you'd like**
In order to keep scope extremely small, it would be acceptable at this point for judge suspension to have to happen through the rails console or something similar, but we should be able to flag a judge as suspended which prevents them from creating or editing scores further. Deleting existing scores is out of scope for this feature and can happen separately.

**Describe alternatives you've considered**
Other options include the blocklist, or simply changing passwords (which is more of a deterrent than actual suspension).

**Additional context**

**Label**
You MUST use the label menu to add 'Feature request' and '0 - To Discuss' as a label

**Comment by stenington** [comment]
Here's what my proposed change would look like for both live and virtual judges:

![suspension2](https://user-images.githubusercontent.com/55319/57311267-4c20f600-70b9-11e9-9c7e-ecf75ec08d03.gif)
![suspension1](https://user-images.githubusercontent.com/55319/57311268-4c20f600-70b9-11e9-9fef-3726fe46c0d7.gif)

**Comment by amyiridescent** [comment]
Hey Mike, Just so I am super clear. I am assuming the following are the steps. I also have one modification request. 

1. Kai contacts you with the judge email or ID number on the judge we need to suspend. (After she has gone through multiple warnings and probably deletion of some of their scores.)
2. You on the back end "suspend" their account so they can't take on new scores or edit ones they have already judged. 
3. The above is the dashboard these judges will see when they log in. 

Modification: In the message "Your judge account has been suspended." Can you include something that says if you have questions, please email (our zendesk email address). 

Question: Is this "suspension" irreversible?

**Comment by stenington** [comment]
> In the message "Your judge account has been suspended." Can you include something that says if you have questions, please email (our zendesk email address).

Sure!

> Is this "suspension" irreversible?

Yes, it's a true/false value stored on their profile that we can change back to un-suspend.

**Comment by ophelieh** [comment]
Looks good to me, I agree with Amy. We shouldWhat do you think @KaiLokken

**Comment by KaiLokken** [comment]
This looks amazing!!! Agree with both Ophelie and Amy. Great job, Mike. Thanks for your help!

**Comment by stenington** [comment]
I've added a little bit to the admin to help identify suspended judges as well

![Screen Shot 2019-05-07 at 2 02 11 PM](https://user-images.githubusercontent.com/55319/57323975-ddea2c80-70d4-11e9-8260-c110fe165a85.png)
![Screen Shot 2019-05-07 at 2 32 47 PM](https://user-images.githubusercontent.com/55319/57324031-04a86300-70d5-11e9-830d-bf0af6fbc874.png)
![Screen Shot 2019-05-07 at 2 01 53 PM](https://user-images.githubusercontent.com/55319/57323976-ddea2c80-70d4-11e9-9633-917e80e71c93.png)
![Screen Shot 2019-05-07 at 2 01 41 PM](https://user-images.githubusercontent.com/55319/57323977-de82c300-70d4-11e9-96f2-35ef8c653983.png)

**Comment by KaiLokken** [comment]
Looks great! Just want to confirm:
1) if the judge is suspended, then the judge will receive the error message 
AND
2) as, an admin, we can look up suspended judges
Thanks!

**Comment by stenington** [comment]
@KaiLokken Yeah, correct.

When this deploys, I will set up a live judge and a virtual judge, suspend them, and make a note of which judges I set up here for testing. I'll write up some suggested QA steps as well.

**Comment by KaiLokken** [comment]
Great! Thanks!

**Comment by stenington** [comment]
Okay, 3 new users. Password is the email address:
* Suspended Judge `suspended@judge.com`
* Suspended Live-Judge `alsosuspended@judge.com`
* Another Suspended `anothersuspended@judge.com`

All are judge accounts that have been suspended. The first two have 1 complete score and 1 score in progress, the third has not started anything.

**Suggested QA:**
1. log in as `suspended@judge.com`
2. under "Manage your scores" click "Finished scores"
3. click "Review" next to finished score
4. make sure you get suspension notice and cannot review the score
5. go back to dashboard
6. under "Complete your score in progress" click "Resume" next to score
7. make sure you get suspension notice and cannot resume the score

1. log in as `anothersuspended@judge.com`
2. under "You are ready to start a new score" click "Start a new score"
3. make sure you get the suspension notice and cannot start the score

1. log in as `alsosuspended@judge.com`
2. under "Complete your score in progress" click "Resume"
3. make sure you get the suspension notice and cannot resume
4. under "Manage your scores", click "Review", "Resume", and "Start"
5. make sure each time you get the notice and can't do anything

1. log in as an admin
2. go to the Participants section
3. check the "Suspended Judges" filter, make sure you can filter by suspended, not suspended, or don't care
4. add the "Suspended" column and make sure the values shown make sense for different types of users: suspended judges, not suspended judges, non-judges
5. look up a suspended judge and view their profile
6. make sure under "Profile debugging" they show as suspended
7. look up a non-suspended judge
8 make sure under "Profile debugging" they show up as not suspeded

1. log in as an RA
2. make sure you cannot see the "Suspended Judges" filter or "Suspended" column 
3. notice that if you view a judge, you **can** see if they are suspended or not

Note: for the RA case, I really wasn't sure if RAs should have this feature or not so right now they have sort of a funny blend. Let me know if that needs to be changed.

**Comment by ophelieh** [comment]
I am going to test this, but @KaiLokken could you also check it out as you are in charge of scores? :) Thank you!

**Comment by ophelieh** [comment]
Hi @stenington Everything works as expected! :) 

For RAs, we do not want them to be able to see if a judge is suspended. On the profile debugging, it should NOT show if a judge is suspended. Thank you!!

**Comment by stenington** [comment]
Ok, I'll work on that change tomorrow. Thanks @ophelieh!

**Comment by stenington** [comment]
Ok, so follow-up QA:

1. log in as an RA with a suspended judge in your region
2. make sure you cannot see the "Suspended Judges" filter or "Suspended" column
3. View a suspended judge, make sure you cannot see that they are suspended in the debugging section

**Comment by kmorton2017** [comment]
This is correct. I cannot see these items as an RA with a suspended judge in my region.
