### ISSUE TITLE
Showing students their RPE during judging

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2136]
**Is your feature request related to a problem? Please describe.**
The student dashboard is confusing for students during judging. The "Pitching Events" menu item goes back to disabled, saying "This feature will open later in the season" and the submissions section just says "Submitting your project is not available right now."

We recently added the ability for students in live event teams to edit their presentation slides with a link from the "Submit your project" page (which is already weird design, but gets the job done) but nowhere can these teams see the event they are scheduled to attend.

**Describe the solution you'd like**
Ideally the "Pitching Events" menu item should not be disabled, and could show RPE info, although code-wise that seems like a big change. A short-term solution is maybe to show RPE info alongside the link to edit presentation slides. 

![screencapture-localhost-3000-student-dashboard-2019-05-07-12_00_25](https://user-images.githubusercontent.com/55319/57314528-ceacb400-70bf-11e9-9ba6-bad7ba7717f8.png)

**Comment by ophelieh** [comment]
This looks great! Could we expand that to mentors as well? 

Thank you!

**Comment by stenington** [comment]
@ophelieh Not in the same way, no. Mentors have a different dashboard so it would require a different solution.

**Comment by KaiLokken** [comment]
It would be great to show the RPE info when the student logs in. Even the short-term solution, showing it by the link to edit presentation slides, would be REALLY helpful. Thanks!

**Comment by ophelieh** [comment]
ohhhh It can't never easy, can it? 

Let's just go with the students than for now. Thank you!

**Comment by stenington** [comment]
Ok! I'll do students first and then take a look at using something similar for mentors if possible. I can open that as a new ticket later.

**Comment by stenington** [comment]
QA:

1. log in as student in an RPE, make sure correct RPE info appears
2. log in as student not in an RPE, make sure dashboard loads without RPE info

**Comment by ophelieh** [comment]
Works great! Thank you!
