### ISSUE TITLE
Showing mentors their teams' RPEs during judging

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2140]
**Is your feature request related to a problem? Please describe.**
Similar to #2136, it would be more useful to mentors to be able to log in and see their teams' RPEs and be able to edit presentation slides than to just have the "submitting not available" message they have now.

**Describe the solution you'd like**
Maybe we can take the basic solution from #2136 and show similar controls, repeated once for each team in an RPE?

**Describe alternatives you've considered**
I think ideally the submission and RPE tabs would be reworked to show useful information depending on the phase of the season, but that's a more substantial amount of code to change.

**Comment by stenington** [comment]
![localhost_3000_mentor_dashboard](https://user-images.githubusercontent.com/55319/57385275-2874b300-7180-11e9-8899-bdccd8ab8598.png)

**Comment by stenington** [comment]
@ophelieh Take a look at this when you have a chance and let me know what you think.

**Comment by ophelieh** [comment]
I like this! Looks great. Thank you! :)

**Comment by stenington** [comment]
Suggested QA:

**With the platform in QFs**
1. log in as an RA with multiple teams in live events
2. make sure the correct RPE info is displayed for each team
3. make sure each team's slides are editable through the "Edit presentation slides" link
4. log in as an RA with no live event teams
5. make sure their dashboard does not show the "Regional Events" section

**With the platfrom in SFs**
1. log in as an RA with teams in live events
2. make sure RPE info no longer shows like it did in QFs

**Comment by ophelieh** [comment]
@nickiredescent and @KaiLokken Could you both test this today or tomorrow?

Thank you!

**Comment by nickiredescent** [comment]
I believe the steps were meant to log in as a mentor. I did the QA under this assumption.
I can confirm that mentors are able to edit their teams' presentation slides with Quarterfinals enabled.
I can confirm that mentors are not able to edit their teams' presentation slides with Semifinals enabled.
This is working as intended.

Minor note
![image](https://user-images.githubusercontent.com/45576078/57654504-2b5d1280-7589-11e9-8975-1eb0bfa98d14.png)
"Regional Events" highlights when I hover over it, it links to the page I'm currently on (this page simply shows me the team's slides and an option to change the upload).  It's not a super useful link, but again, minor thing. The main functionality is working great.

**Comment by stenington** [comment]
Yes, correct! This is as a mentor, let me fix that in my previous comment.

And yeah, the page is a bit weird. It's basically the full submission editing page pared back to just the presentation slides. That left nav area makes *a lot* more sense when the whole submission is editable.

**Comment by ophelieh** [comment]
Looks great and works as expected. Thanks Mike!
