### ISSUE TITLE
See deleted scores as an admin

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2146]
**Is your feature request related to a problem? Please describe.**
We're doing a certain amount of hand-curation of scores, which includes deleting scores or restoring scores that were deleted for the wrong reasons. Right now when a score is deleted, it essentially disappears from the platform from an admin's point of view. 

**Describe the solution you'd like**
I think the *Scores export* page could include an option to show deleted scores, so there's at least some basic way for admins to see them without having to consult a separate spreadsheet or ask a developer to look them up through e.g. the Rails console.

**Comment by stenington** [comment]
Here's what this could look like. You could either include deleted scores with the non-deleted, or choose deleted-only. A new column would be added to the end of the list to show the yes/no deleted status. (Hopefully that doesn't mess up the spreadsheets this data feeds into?)

![Screen Shot 2019-05-14 at 4 29 39 PM](https://user-images.githubusercontent.com/55319/57730038-92e89000-7665-11e9-9101-de1f5a638488.png)

![Screen Shot 2019-05-14 at 4 30 05 PM](https://user-images.githubusercontent.com/55319/57730035-91b76300-7665-11e9-8b28-6801a1b91095.png)

**Comment by stenington** [comment]
@amyiridescent @kmorton2017 We had discussed adding something like this after the dev weekly call. Does this seem worth doing?

**Comment by amyiridescent** [comment]
I think it will be helpful for the team who are fielding questions from judges. Let me know if you need me to QA things. And I can help @KaiLokken update the spreadsheet she is using if needed. :)

**Comment by KaiLokken** [comment]
Checked it out. Looks great and will be very useful. I downloaded the csv and the deleted column was included. Played around with the "Deleted" filter at the top. Everything worked! Thanks, Mike!
