### ISSUE TITLE
Additional filters to "Scores" page

### ISSUE THREAD

**Issue by amyiridescent** [Iridescent-CM/technovation-app#2148]
Can I get a country & division filters added to the "scores" page on admin? It will help a great deal when we are picking semi-finalists. 

![uploads/16e7c436-ab90-465b-ab46-c8118edb8c5b/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F16e7c436-ab90-465b-ab46-c8118edb8c5b%2Fimage.png)

**Comment by stenington** [comment]
I see a division and a country filter already there. Am I not understanding the request or did you not see them @amyiridescent?

**Comment by amyiridescent** [comment]
Whoops. I meant "Additional columns" not filters... Sorry!

**Comment by stenington** [comment]
Division is already under "More columns", but do you want it made a default column? And do you want country as "More columns" or to always show? I think with the location normalization stuff we're still doing, it'll slow down the page a little so there's a technical argument for putting it as an optional column, but if you pretty much always need it when referencing this page, I'll just make it default.

**Comment by amyiridescent** [comment]
Well first of all I am blind... because I could not see the "Division" column. Sigh.  For location, additional column is totally fine. I will only need it when we are selecting semi finalists :)

**Comment by kmorton2017** [comment]
@KaiLokken can you test this

**Comment by KaiLokken** [comment]
Tested it. Worked as expected.Both country and state showed up under "More Columns". Pulled the csv, and the country and state columns were included.
