### ISSUE TITLE
Survey Collector--Set Up Variables

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#2149]
We need to set up custom variables for the Survey Monkey post-survey on the platform. We do this to cut down on the time/effort on behalf of participants. When they open the survey from the platform, they won't need to put in redundant info that is already collected from registration. In order to pair responses and see before/after results, we need to ensure that the post survey is also collecting this info. [Click here](https://github.com/Iridescent-CM/technovation-app/issues/1846) for the original ticket. 

**For students, this should be:** 

Email
First and Last Name
School
City
State/Province
Country
Team
Age

**For mentors this should be:**
Email 
First and Last Name
Company
City
State/Province
Country
Team Name

Then, I believe that either you or I need to edit the custom variable section of Survey Monkey for each survey to exactly match what you name the variables on the back end. Reference article here: https://help.surveymonkey.com/articles/en_US/kb/What-are-custom-variables-and-how-do-I-use-them

Afterwards, we will need to make sure the post-survey web link pops up on the dashboards of users AND it collects the respondents' info correctly. 

@stenington @amyiridescent

**Comment by stenington** [comment]
@kmorton2017 Here are the custom variables it looks like the platform currently understands:
* `[email_value]`
* `[country_value]`
* `[state_value]`
* `[name_value]`
* `[city_value]`
* `[age_value]`
* `[school_value]`
* `[company_value]`
* `[team_value]`

So if you set a survey link containing any of those, they should be correctly filled in for the user being shown the link.

Does that get you what you need, or are there changes we still need to make?

**Comment by kmorton2017** [comment]
Ok great that looks good. I will set up a QA Test scenario for making sure that the survey responses are being collected.
