### ISSUE TITLE
Mentors who are too young to be judges can judge

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2152]
**Describe the bug**
We have mentors who are under 18 and should not be able to judge, but they can click the button to switch to their judge profile and judge submissions.

**To Reproduce**
1. Go to a mentor account that is underage for being a judge
2. Click on the link to switch to judging

**Expected behavior**
Not sure, it should probably show an error or not show the link?

**Additional context**
This was discovered in the 2019 season after some of these judges had scored several submissions. We ended up suspending all underage judge accounts, although that doesn't prevent further mentors in this situation from becoming judges.

**Comment by hellafitz** [comment]
There's some broader sentiment that mentors shouldn't be judges. Discuss that with program team. In the past we've needed to recruit additional judges fast and this has been one route. That decision doesn't have to hold up this fix in the meantime.

**Comment by rsgonzal** [comment]
I just signed up using the judging link as a 17 year old. I was allowed to judge.

Looks like we say judges need to be 21: https://iridescentsupport.zendesk.com/hc/en-us/articles/360036011914-Rules-for-Judges

**Comment by hellafitz** [comment]
Updated scope: Stop underage judges from signing up (21 is the official rule).

**Comment by hellafitz** [comment]
Reassess for next season (context: CET will have more experience with the potential issue, and it's currently possible to view Judge age and suspend them, and their scores, using the Admin)

**Comment by hellafitz** [comment]
@stenington to update on how to pull this

**Comment by stenington** [comment]
Log in as admin, go to **Judges**, choose the current season in **Season**, and add **Age, Complete Quarterfinals Scores, and Complete Semifinals Scores** as **More Columns**, and click Search. Then sort Age by ascending order.

**Comment by hellafitz** [comment]
Reported as an ongoing issue by Kate in the Feature Request spreadsheet on 7/16/20

**Comment by rsgonzal** [comment]
The team doesn't escalate as an issue everytime we discuss, closing.
