### ISSUE TITLE
XTC.org: change boxes from grey to color when a role is selected

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2159]
https://technovationchallenge.org/get-started/

Problem: when I click on a box other than Judge I expect the grey box I click on to become color, and the color Judge box to go grey. That doesn't happen. 

![uploads/47f7e3bb-9455-44c6-96cf-cbf57c0a12a6/Screenshot 2019-07-23 13.50.36.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F47f7e3bb-9455-44c6-96cf-cbf57c0a12a6%2FScreenshot+2019-07-23+13.50.36.png)

Optional spinoff: Additional UI work could be done to make it more clear that these boxes trigger drop-downs with more information.

**Comment by stenington** [comment]
I'm willing to work on this type of ticket if desired, but just calling out that this is a page on the Wordpress site, not the submissions platform. The upshot is that it would probably take me a little bit of time to get oriented to the code over there, since I wasn't involved in creating it.
