### ISSUE TITLE
Switch from Mailgun to Mandrill [13,8,1.6]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2163]
We'd like to consolidate services and send transactional emails currently going through Mailgun through Mandrill instead. This will entail comparing services and confirming that Mandrill is a functional replacement for Mailgun, then properly configuring Mandrill and the platform to send emails.

**Comment by hellafitz** [comment]
Context: Mail Clients 2019 doc https://docs.google.com/document/d/1fBol5jmQVCXSvh556UFpXIDKfjhHyDQi6lCeeVuMSp4/edit

**Comment by hellafitz** [comment]
hope is to consolidate services and maybe save some money

**Comment by hellafitz** [comment]
Open Q: is there a dependency on having MailChimp set up with our Campaign Monitor emails (#2162)? Or on having general MailChimp configuration in place before this can be done?

**Comment by stenington** [comment]
I don't believe there's any dependency on Mailchimp to do this ticket. 

One issue that's come up is a difference in the overall pattern of sending emails that the two platforms use. 

For TF, the template is stored **in Mandrill** and the app just provides a few variables to fill in on the Mandrill side. (And actually, you can use the Mailchimp WYSIWYG email builder to build the template and then export that to Mandrill.)

For TG, the template is stored **in the source code** and the app sends across the entire email to be sent. 

The Mandrill API has different calls two support these two usages, so I should be clear that I'm considering the work in this ticket to be switching from Mailgun to Mandrill **without** changing the overall pattern, so after this ticket TG emails would still be in the source code. Moving all those templates into Mandrill (where the program team can more easily access and edit them) is not part of this ticket in my understanding of it.

**Comment by stenington** [comment]
Digging into the code a bit, I found that we use our Mailgun account for a second purpose: email verification. This ticket can still be done as defined, but afterwards we will still be using our Mailgun account for email verification so we won't yet be able to cancel that account.

**Comment by stenington** [comment]
So this ends up just being a config change from Mailgun to Mandrill's SMTP settings. In Mandrill, it looks like setting up a new key with send and send-raw permissions lets that key be used as the SMTP password.

**Comment by stenington** [comment]
Suggested QA:
* do something on staging that would send an email
* confirm receipt of the email
* let me know the email address you used and the action, and I will confirm it shows up in Mandrill logs and not Mailgun logs

**Comment by stenington** [comment]
Ok, confirmed that emails to these addresses are in Mandrill, none in Mailgun. 👍

**Comment by stenington** [comment]
Deployment here involves creating a new API key in Mandrill, and setting `MAIL_ADDRESS`, `MAIL_PASSWORD`, and `MAIL_USER` appropriately in production. This doesn't have to be timed with a code deployment, but we may as well do them together I think.
