### ISSUE TITLE
Replace Campaign Monitor w/ Mandrill by TG Season Start

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2164]
Currently my.technovationchallenge.org uses Campaign Monitor to collect and send emails. Replace that service with Mandrill (part of MailChimp, and what CM uses) to consolidate. 

myTC flow automatically adds users to "participant lists" as subscribers in Campaign Monitor. (we would like to keep this functionality if possible). This needs to be recreated in MailChimp before getting rid of Campaign Monitor

Mail Services reference doc: https://docs.google.com/document/d/1fBol5jmQVCXSvh556UFpXIDKfjhHyDQi6lCeeVuMSp4/edit#

**Comment by stenington** [comment]
More accurately, my.technovationchallenge.org uses Campaign Monitor for mailing list signup, and Mailgun to send emails. Those would be replaced with Mailchimp and Mandrill respectively. I've got #2163 and #2162 open for those, so we can close those or this one as a dupe I think.

**Comment by hellafitz** [comment]
This is a soft but recommended deadline. We can buy ourselves an additional several months if needed but if it's not done by start of reg, we'll need to give @mjaris an export of user email addresses to import into Mandrill.

**Comment by hellafitz** [comment]
closing since we've split this one off
