### ISSUE TITLE
Epic: Upgrade libraries to resolve security alerts [100,100,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2166]
GitHub has identified several security alerts in this project, it would be best to upgrade the relevant libraries to address all issues: https://github.com/Iridescent-CM/technovation-app/network/alerts

**Comment by hellafitz** [comment]
- make sure it's safe to use the updated libraries 
- update the libraries

**Comment by hellafitz** [comment]
Context: Comp Effort 5 is for the optimistic scenario (do all the ones that are pretty easy, leave the others). If it turns out to be much harder, flag that and we'll create a new ticket.

**Comment by stenington** [comment]
It turns out I can't do much here with an effort estimate of 5. There are dependencies to carefully untangle, and testing will either be "do everything and look for breakages" or I'll have to hunt through the app for where libraries are specifically used and check if it's covered with automated tests. I'd put this project at a 40, and it'll only get worse if we wait.

**Comment by stenington** [comment]
I tried to update to rails 5.2 and hit a snag where we're targeting a fork of `simple_form` aimed specifically at rails 5.1. 

In general, we have some dependencies where we've forked the main project, and others where it's not our fork but we're targeting a specific branch instead of a versioned release. That's a skeleton in our closet that I wasn't expecting, and I think a first step here is understanding the motivations behind all of that, and determining whether we need to continue to maintain a fork or whether we can go back to the main project. That would be for:

* textacular
* simple_form
* country_state_select
* city-state
* heroku-deflater

**Comment by stenington** [comment]
`textacular` still needs the patch we're maintaining in a fork, and it's not a straightforward merge to get the latest changes from their main branch. However I believe we can go to 5.2 with our current fork (but not 6).

**Comment by stenington** [comment]
I found this article in the process of dealing with these upgrades: https://thoughtbot.com/blog/keep-your-gems-up-to-date It mentions planning to upgrade your gems weekly or monthly, which I don't think is going to be realistic for us, but just to give a sense of what advice in this space looks like.

**Comment by hellafitz** [comment]
webpacker updated, onto dependent libraries

**Comment by stenington** [comment]
Looks like the upgrade fixed all of the javascript security alerts! 😵 (For now.)

We're currently down to 2 alerts, 1 for geocoder and 1 for puma.

**Comment by hellafitz** [comment]
@stenington good to close this one?

**Comment by stenington** [comment]
No, we have 4 open alerts right now. 2 js, 2 ruby.

**Comment by shaunxp20** [comment]
I'm going to close this issue, all of the existing security alerts for TG are being addressed in #2834. 👍 We can open new issues for the new ones that come in. 🐦🌵🏜️ 🌞
