### ISSUE TITLE
Seasonality for KPIs [20,20,1.0] 

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2170]
Collecting accurate data for Technovation's 5-year KPIs requires tracking various users and user groups across seasons.

This ticket is to investigate the current status of "Seasonality" or what passes for it on CM, and scope a set of backend improvements that would allow us to build user or admin-facing features on top, incorporating multiple season years. KPI tracking would be one (or really several) examples.

Here are the draft KPIs for reference: https://docs.google.com/spreadsheets/d/1SepphKeLcXtwON_WrHUptVPI24INlSkMOHJZSbhxyNQ/edit#gid=2019824350

We think that an Events Database may be the best way forward for separately KPI-type data from app data. It would create a separate database / log tracking platform(s) activity. For example, Keen.io

Steps
- Look at the draft KPIs and identify ones that apply to the platforms
- Research event databases (is this viable to track the relevant KPIs? What's a ballpark budget?)
- Present Amy w/ a lightweight decision (go/go no on more detailed investigation i.e. is there money available for this such that we should invest more time in specifics?)

**Comment by stenington** [comment]
I'm starting to think of this as basically a series of ETL problems (extract, transform, load) where we want to pull some key indicators out of various app databases or 3rd party platforms, transform those indicators into a more concise statement of what we care about, then load that into one central place which becomes the point of reference for tracking progress against KPIs.

A tool like keen.io (or segment.io, which seems to be somewhat of a similar thing) somewhat fit that bill, but may not be particularly helpful in the 3rd party scenario. Plus, if what we're really talking about is doing some ETL thing only **once per season** to track final participation and completion, those tools are probably over-powered for that. We should consider setting aside time to do it manually with some simple handwritten tools to start. 

I think the next steps are:
* do a more detailed review of the KPIs
* start thinking about the E of ETL for each KPI: can it be fully automated? partially automated? are we stuck doing it manually?
* then try to assess how much bang for the buck introducing a keen-like tool would give us

**Comment by hellafitz** [comment]
Something like Awardforce wouldn't automatically integrate with an events database. We could export some data and find ways to load that data into the events database. If we're ok with some manual import/data cleaning, then it's viable.

Cost estimates
Keen: $150/month for 1M events and 2000 queries (next level up is $750/month). Visualization and reporting tools built in. https://keen.io/pricing/
Segment: $120/month or custom, depending on volume. Might require a second service for things like visualization or reporting. https://segment.com/pricing/
DIY: not viable for us

Present to Amy: idea was presented today. Cost and funder receptivity are still unknown.
