### ISSUE TITLE
Investigate our Vue technical debt [13,20,0.65]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2171]
We have a number of Vue-related tickets in the Icebox and Product Backlog. Look into how big the underlying problem is by familiarizing yourself with current Vue implementation.

**Comment by stenington** [comment]
Start by doing the Vue and VueX tutorials or understanding basic docs and then try to compare what we have against anything gleaned there.

**Comment by stenington** [comment]
I wrote up #2173 as discussed, and I'm considering this one complete for the time being.
