### ISSUE TITLE
Implement business plan submission messaging updates [13,2,6.5]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2175]
Update the copy for the business plan submission section, using text from the Program team. Needs to be in place by the time we open submissions.

Program team described this change in Basecamp thread as, "FIVE page business plan (instead of behemoth thing) - We are not changing how platform works, changing messaging. This change is confirmed."

Needed input to start: new copy from the TG Program Team

As a senior division participant, I want to know the correct details of what I need to submit for the business plan element of my entry, so that my entry can be accepted. 

As an admin, I want to communicate the details of what needs to be submitted for the business plan element, so that participants don't make complaints to me. 

Related: There will almost certainly be changes to the business plan section of the curriculum. We don't expect any dev tasks there but it might be worth confirming at a later date.

**Comment by hellafitz** [comment]
@devincdillon what's the plan for getting this information finalized? looking for an eta on when it'll be ready for us to implement. Thanks!

**Comment by devincdillon** [comment]
Hey Matt! Yes, okay so again I don't know exactly what the page looks like or what comes before/after this so let me know if it feels off. I'm pretty sure only senior division teams see this (like, a junior team won't have the option to upload a business plan, so I'm not going to clearly say "Senior Teams only").

Also, I'm attaching a picture of what it says now - currently, it says we accept .doc .docx and pdf. However, the team reports a lot of problems with Google docs being uploaded and set to private (this could be a mandela effect thing or something fixed for last season but not the ones before so they are misremembering). Anyways, can someone confirm if we do allow google docs? If yes, I need to have clear messaging about privacy settings. If no, I'll just create copy for a pdf

![image](https://user-images.githubusercontent.com/9745827/67026238-5ec24100-f0d5-11e9-8d72-2401f17099ef.png)

**Comment by stenington** [comment]
To me, the most likely scenario for private Google docs being a problem would be if we accepted links instead of files, but here it looks like we're only accepting files. It's still possible someone might upload a password-protected document or something, but I'm guessing that's not what people are remembering. 

I see commits in the commit history referencing a remote file url for the business plan back in 2017, so maybe that suggests that we used to accept urls to Google docs?

**Comment by devincdillon** [comment]
Okay - looks like team is mis-remembering. Here is the copy:

"Submit your 5 page business plan. **If you can, submit a PDF file**. We also accept .doc and .docx files."

**Comment by rsgonzal** [comment]
Confirmed with @devincdillon that the text to be changed is the the highlighted blue text in the screenshot

**Comment by stenington** [comment]
QA here is pretty simple:

1. log in as a senior division student
2. on your dashboard click "Your business plan" under "Business"
3. confirm the new help text


<img width="640" alt="Screen Shot 2019-11-19 at 4 50 36 PM" src="https://user-images.githubusercontent.com/55319/69189653-bbf24d80-0aec-11ea-852a-87f4707377ab.png">

**Comment by nickiredescent** [comment]
Can confirm that the business plan help box is working. Can also confirm that it will only let me upload the specified file types.
