### ISSUE TITLE
Implement source code submission messaging updates [13,5,2.6]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2176]
Update the messaging for what participants need to submit in terms of source code, using copy from the Program Team (will need to get that from them). 

Context: we decided not to introduce actual restrictions on what file formats we accept - rather we're going to try "strong messaging."

Program team described this change in Basecamp thread as, "Source code - you must submit [still], but we are messaging that we only accept the top 5 languages from last year - Thunkable, App Inventor, Thunkable Classic, SWIFT or Java. We are not changing platform (it technically accepts all, but we are focusing messaging and support on these things). This change is confirmed."

**Comment by hellafitz** [comment]
@devincdillon please update on eta for this final copy (to the extent possible)

**Comment by devincdillon** [comment]
hi Matt,

I can't really see the context of where this is going on the page, but I think it's okay. Tell me if this feels off:

"Submit your source code link or file. Only App Inventor, Thunkable, Thunkable Classic, Java or Swift are allowed. **If you used App Inventor, only .aia NOT .apk files are allowed.** Learn more about how to submit your source code [here](https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-)"

**Comment by stenington** [comment]
The user flow currently forces the user to pick a development platform from a dropdown first, and then secondarily shows an upload widget if appropriate. But, for example, if a user selects Thunkable they are prompted for their project url and **not** shown a field where they could upload anything.

I think we need to factor in that interplay between choosing a development platform and uploading source code when figuring this one out. Right now the dropdown looks like this, so maybe we're just talking about getting rid of the "Other" option?

![Screen Shot 2019-10-21 at 12 40 59 PM](https://user-images.githubusercontent.com/55319/67224819-0f934d80-f400-11e9-9226-3afe04b737bb.png)

If I select a dev platform where uploading is allowed, the source code screen looks like this:
![Screen Shot 2019-10-21 at 12 41 37 PM](https://user-images.githubusercontent.com/55319/67224873-2afe5880-f400-11e9-9b39-36857c821964.png)

**Comment by devincdillon** [comment]
Hi Mike,

Thank you for that:

- agree with remove the "other" option
- on the app inventor page - can we ensure it says **we only accept .aia files**
- on the swift and java pages it's fine to say we accept, .zip, .aia and .apk 

- can we change the copy and link referenced "get some help making your source code..." to "Help for submitting your source code is [here](https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-)"

**Comment by stenington** [comment]
I'm looking more closely at the code, and it looks like **we do restrict file type** for source code uploads. The upload dialog only accepts .zip, .aia, or .apk, so for instance a user can't upload a .pdf or .jpg file here, at least not without zipping it or just changing the extension.

So given that we already restrict the file extensions a user may upload, should I make the dialog only accept .aia for App Inventor? Can .aia's get large? Would it need to accept both .zip and .aia?

**Comment by devincdillon** [comment]
For app inventor, I think we should restrict to .aia.

@amyiridescent do you see any issues with that restriction?

**Comment by amyiridescent** [comment]
So for Thunkable Classic they should turn in a .aia file also. (Thunkable will be a web link)

We should keep the .zip file open available since without is Swift and Java submissions won't be able to submit the source code. 

I haven't seen a case of .aia file getting too large...

**Comment by rsgonzal** [comment]
From talking with Amy, it seems like we can just remove the .apk option for all of them.

**Comment by stenington** [comment]
So I think I'm seeing a request for 2 changes on this screen:

<img src="https://user-images.githubusercontent.com/55319/67224873-2afe5880-f400-11e9-9b39-36857c821964.png">

1. We say "File types allowed: *.zip or *.aia" and we only allow zip and aia
2. We change the copy and link referenced "get some help making your source code..." to "Help for submitting your source code is [here](https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-)"

@rsgonzal Is that correct?

**Comment by rsgonzal** [comment]
This looks right to me, I would add:

3. Remove the drop-down option of 'Other' when choosing a development platform

**Comment by stenington** [comment]
Good call, updated the list above.

**Comment by stenington** [comment]
QA: 

1. log in as a student
2. start a submission if needed and navigate to the **Source code** portion
3. confirm we say "File types allowed: *.zip or *.aia" and we only allow zip and aia
4. confirm help text says "Help for submitting your source code is here" with correct link
5. navigate to the **Development platform** submission section
6. confirm the drop down does not contain "Other" as an option

@rsgonzal any other steps you can think of?

**Comment by rsgonzal** [comment]
Steps look good!

We do only accept zip and aia, checked apk, pdfs, docs
Help text looks right to me
There's no option for 'other'

Only issues i saw:
- File types allowed says "aiak"
![Screen Shot 2019-12-09 at 7 36 47 PM](https://user-images.githubusercontent.com/22801026/70493172-a05edf00-1abb-11ea-98c4-78b78966e509.png)

- Screen for after it uploads says we accept other formats. Is this used for any other uploads?
![Screen Shot 2019-12-09 at 8 00 05 PM](https://user-images.githubusercontent.com/22801026/70494409-0cdbdd00-1ac0-11ea-887f-4b2c4c018870.png)

**Comment by stenington** [comment]
Fixing the typo now. It looks like the uploads page also handles pitch presentations.

**Comment by devincdillon** [comment]
Logged in as student and followed the steps - all is working as I expect it to. 



![]()
