### ISSUE TITLE
Spike: Implication of removing code checklist and technical checklist from submission (goal W 9/11) [13,13,1.0]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2178]
Submission changes need to be communicated to external partners, so before we decide on a go/no-go Program team has asked for dev to investigate the implications of removing the code checklist for submission.

This ticket would ideally be completed by Friday 9/6.

Tasks:

- Investigate the platform ramifications of this change
- scope the work required to implement
- communicate to Product Team the findings, so Devin can be informed asap

Relevant 8/28 TG Product meeting notes https://docs.google.com/document/d/14Dx9FCS6UUn6g_nMh1bBJOO998AOqM7fET83s2hXUjo/edit#bookmark=id.gflrgn2wwrk0

Remove code checklist
- Remove whole concept of code checklist on platform
- Doesn’t currently appear to judges bc it’s automatically incorporated into scoring algorithm
- If its very difficult to change, how about changing point allocation?

Context: 
- staff don’t see value here, if easy to simplify then take it out
- Kids from underserved areas often have less functional apps but have learned a ton. Including this gives them points that have the effect of improving their scores.
- Original intention was to confirm kids were using the coding curriculum (but we don’t think it really serves that purpose) → was meant to be a learning outcome assessment tool 
- RAs and mentors don’t like that it’s just honor based
- MIT and Thunkable can now pull out much of the data (e.g. 80% of apps did XYZ)

**Comment by stenington** [comment]
Should the title read "of removing code checklist"?

**Comment by rsgonzal** [comment]
YES. Thanks, Mike!

**Comment by hellafitz** [comment]
Amy: Judges may see something very small on the Summary page (at end, once they've already judged the submission).

UX/UI implications:
- When teams get their scores
- On public submission pages

**Comment by hellafitz** [comment]
Both Code Checklist and Technical Checklist are in scope here. Two parts:
1) Code Checklist: They tell you if they built specific things into their app (checklist, Y/N, honor-based responses)
2) Technical Checklist: Upload section where content (e.g. flowchart) is automatically checked - also shows up on Judging side of platform (confirm)

**Comment by hellafitz** [comment]
Initial Tasks
- Take some screenshots, figure out where specific elements show up
- Find in the code
- Untangle implications
- scope each
- ...

**Comment by stenington** [comment]
## Code checklist screen
This is the stuff we'd be getting rid of, so **no more technical components section, no more flow chart upload, no more paper prototype upload**. Screenshots are uploaded outside of the checklist, so those would still be uploaded. The checklist only counts the number of them.

🚩 **Decision 1**: is that the correct scope of what to remove?

![screencapture-localhost-3000-student-team-submission-sections-no-name-yet-by-all-star-team-2019-09-06-09_12_34](https://user-images.githubusercontent.com/55319/64431808-24529680-d089-11e9-89fc-75f9549c8d39.png)

## Scoring

The code checklist gives a score out of 10. Presumably we would just lower the total possible score by 10 points after removing the checklist.

🚩 **Decision 2**: is that the correct scoring adjustment?

---
The rest of the screens show places where we would remove navigation items, filters, text, etc. related to the code checklist. Presumably they get removed without replacement.

🚩 **Decision 3**: is that the correct approach to updating the UI?

## Student/Mentor
![Screen Shot 2019-09-06 at 9 12 06 AM](https://user-images.githubusercontent.com/55319/64431535-a9897b80-d088-11e9-8b61-724cd1bcefbd.png)
![Screen Shot 2019-09-06 at 9 12 11 AM](https://user-images.githubusercontent.com/55319/64431537-a9897b80-d088-11e9-9a17-610165280da2.png)
![Screen Shot 2019-09-06 at 9 15 55 AM](https://user-images.githubusercontent.com/55319/64431539-aa221200-d088-11e9-841c-f1a97b08d4cc.png)

## Judge
![Screen Shot 2019-09-06 at 9 16 46 AM](https://user-images.githubusercontent.com/55319/64431540-aa221200-d088-11e9-9786-aa315b6856e7.png)
![Screen Shot 2019-09-06 at 9 21 40 AM](https://user-images.githubusercontent.com/55319/64431543-aa221200-d088-11e9-9453-f8ab2385e13a.png)

## Admin/RA
![Screen Shot 2019-09-06 at 9 18 40 AM](https://user-images.githubusercontent.com/55319/64431541-aa221200-d088-11e9-840b-1ecfaaa09f62.png)
![Screen Shot 2019-09-06 at 9 18 50 AM](https://user-images.githubusercontent.com/55319/64431542-aa221200-d088-11e9-90f0-9a3326a4cec2.png)

![Screen Shot 2019-09-06 at 9 24 02 AM](https://user-images.githubusercontent.com/55319/64431544-aa221200-d088-11e9-9c7f-d21682176651.png)
![Screen Shot 2019-09-06 at 9 22 25 AM](https://user-images.githubusercontent.com/55319/64431545-aa221200-d088-11e9-818d-312453da268c.png)

## Past seasons

This change entails the same decision about handling past season data as #2177 discussed [in this comment](https://github.com/Iridescent-CM/technovation-app/issues/2177#issuecomment-528423106). Given the timeframe, we would not be able to remove the code checklist/technical checklist pieces this year but keep that they were a part of past seasons in the codebase.

🚩 **Decision 4**: Can we live with one of the options laid out in the other ticket? Both tickets have to pick the same option.

**Comment by stenington** [comment]
First three decision points confirmed, and option 2 selected in video ticket where past submissions would be removed from the platform, but not past teams.

**Comment by stenington** [comment]
Similarly to #2177 this change is a go, and tickets #2187 and #2192 contain the required work to complete it. Same caveat about prioritization: once the program team commits to this work and updates the curriculum, the relevant tickets need to receive enough priority to get done in a timely fashion.

**Comment by rsgonzal** [comment]
@stenington have a question from the team - does that mean that the teams will no longer be uploading a flowchart or pseudocode?

**Comment by stenington** [comment]
@rsgonzal That was how I understood the discussion, yes. No flowchart, no pseudocode.
