### ISSUE TITLE
Update content of automatic emails sent from platform [13,5,2.6]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2179]
Email content doc (current vs updates) https://docs.google.com/document/d/1NUqsJVrKDsgZ16t5wjVBrQDD8et6j9Y3VQWrIoEpHXc/edit#

Nick is responsible for content updates. We think he has a 10/1 delivery deadline but aren't sure.

An incomplete list of emails to update
- student welcome
- mentor welcome
- (...)

Further reference: TG Launch List (see "Automatic Emails are updated" task, https://docs.google.com/spreadsheets/d/1MyOZPdGlVz86Mix6lert7egevwB7z8FDprb9Hip3k7U/edit#gid=1013015707

**Comment by hellafitz** [comment]
@rsgonzal to follow up with Nick before it-06 to update timeline and content list

**Comment by rsgonzal** [comment]
Listing out the emails to update, will include the folder they're found in and the page from [this doc](https://docs.google.com/document/d/1NUqsJVrKDsgZ16t5wjVBrQDD8et6j9Y3VQWrIoEpHXc/edit#heading=h.99o8m2qtxxid) to find updated text.

Account_mailer
- [ ] Background check cleared (3)
- [ ] Confirm next steps (6)

Parent_mailer
- [ ] Consent Notice (51)
- [ ] Thank you for signing (54)

Registration_mailer
- [ ] Welcome mentors (62) - still has unanswered questions
- [ ] Welcome email to students (67)

**Comment by stenington** [comment]
QA: 

For each email listed above, do whatever causes it to be sent, then confirm the copy in the email. I did not click resolve on the suggested changes in the doc to make it easier to see the changes that were requested. There are also some places in that doc where I left a comment asking if "Technovation" should be "Technovation Girls" in the copy, so make sure to confirm whatever version is in the email you receive is the one you want.

**Comment by mdancho** [comment]
All of these 6 are working perfectly :+1: Text for mentor facing parts are all good to go.

**Comment by nickiredescent** [comment]
A couple of changes noted in the doc. Missed a few "Technovations" and didn't add the "Girls"

**Other Notes:**
Consent Waiver for mentors is out of date (references Iridescent).
Associated URL: [https://technovation-qa.herokuapp.com/mentor/dashboard#/consent-waiver]( https://technovation-qa.herokuapp.com/mentor/dashboard#/consent-waiver
)

**Comment by stenington** [comment]
Thanks @nickiredescent! The consent waiver will be fixed in #2203. I'll fix the additional spots you marked and get that on staging soon.

**Comment by nickiredescent** [comment]
thanks for making the changes. I've triggered those emails again and they all look good.

**Comment by rsgonzal** [comment]
this one looks ready to go!
