### ISSUE TITLE
Check on TG map (around 10/1) [3,1,3]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2182]
Follow up on #2309 by checking if the map on technovationchallenge.org is still working. Rebuild it as necessary, making a new ticket for that work if it's a significant task.

**Comment by hellafitz** [comment]
map is working as of 9/17

**Comment by rsgonzal** [comment]
![uploads/1f8ce189-a2e1-46f2-896f-80deff16d842/Screen Shot 2019-10-02 at 4.49.53 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1f8ce189-a2e1-46f2-896f-80deff16d842%2FScreen+Shot+2019-10-02+at+4.49.53+PM.png)

If we're talking about this map, it seems to be working!

**Comment by rsgonzal** [comment]
![uploads/74531c0c-fbe4-4f08-9179-5aee8949c858/Screen Shot 2019-10-02 at 4.52.29 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F74531c0c-fbe4-4f08-9179-5aee8949c858%2FScreen+Shot+2019-10-02+at+4.52.29+PM.png)
This map is also working.

**Comment by stenington** [comment]
@rsgonzal cool, since we could never find an owner for the account that was going to be closed, we were guessing at what might break. I'd say this ticket is done.
