### ISSUE TITLE
Archival plan prior to submission requirement changes

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2187]
#2177 and #2178 propose changes to submission requirements that necessitate removing old submissions from the platform at this time. We know we want to keep much of that data around in some other form, so this ticket is about designing a plan for doing that.

**Comment by stenington** [comment]
Other tables referencing `team_submission_id`:
* `business_plans`
* `pitch_presentations`
* `screenshots`
* `submission_scores`
* `technical_checklists`

So between this ticket and #2178 we'd be talking about removing submissions (including business plans, pitch presentations, screenshots, and technical checklists) and removing past scores as well.

**Comment by stenington** [comment]
I think we should approach this in two ways:
1. ask Amy to collect all the spreadsheets she would want to have prior to this change, whether those are admin exports, dataclip exports, or manually generated things. Those will be the first source of historical data for this past season.
2. archive off a DB backup, along with a .env file and the current commit SHA (753ec34b0e660690df8e8395afaf96e4adf212c9) so we have a plausible way of digging deeper into past season data if we absolutely need to.

**Comment by stenington** [comment]
@rsgonzal to take the first stab at working out an archival plan with @amyiridescent

**Comment by amyiridescent** [comment]
@stenington I am working on this. I might need your help with one more dataclip. Or you can teach me how to edit it. :) I will like to modify this data clip (https://data.heroku.com/dataclips/bjbpcmaurdxgdscmxtrkqwjyudkw) to pull all judge comments for 2019 season. Can we also have an output column for "rounds"? Let me know if I am being clear. Thanks!

**Comment by stenington** [comment]
@amyiridescent Okay, it's now for 2019 with a "Judging Round" column.

**Comment by amyiridescent** [comment]
Thanks Mike. :) Here is what I got. I think this is all we need but let me run it by team real quick. 
https://docs.google.com/document/d/1AJJH9Hq7s7HRQ726w3MkK0fgYbM2_1RxdQx1kpwqIHM/edit
