### ISSUE TITLE
Update resource links on RA dashboard [8,2,4]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2189]
Links are not up to date on RA dashboard and need to be updated prior to launch.

Ophelie is in charge of updates:

Currently linked:

- RA Resource Page
[See our complete resources for you](http://technovationchallenge.org/ra-resources/)

- RA Handbook
[Read the RA Handbook
](https://iridescentlearning.atavist.com/technovation-ra-handbook)

- FAQ & Rules
[See the FAQ & Rules
](https://iridescentsupport.zendesk.com/hc/en-us/categories/115000091348-Technovation)

- Curriculum
[Open the Technovation Curriculum
](https://www.technovationchallenge.org/curriculum-intro/registered)

- Parental Consent PDF
[Download the PDF
](https://iridescentsupport.zendesk.com/hc/en-us/article_attachments/360018888234/2019_Technovation_Parent_Consent_Form.pdf)

- Submission Guide
[Read the Submission Guidelines
](https://www.technovationchallenge.org/submission-guidelines/)

- Judging Rubric
[See the Judging Rubric
](https://www.technovationchallenge.org/judging-rubric/)
![Screen Shot 2019-09-11 at 12 53 20 AM](https://user-images.githubusercontent.com/22801026/64678515-95e66800-d42e-11e9-88a4-8397ccb98196.png)

**Comment by ophelieh** [comment]
Hi Roxana,

Could we change things a little and have it broken down this way: 

**RA Resources**
- [Curriculum](https://technovationchallenge.org/curriculum-intro/registered/)
- [RA resource page](https://technovationchallenge.org/ra-resources/)
- [RA Handbook](https://iridescentlearning.atavist.com/technovation-ra-handbook)
- Parental Consent PDF --- _this is the only one we need to update as far as link (in progress)_


**FAQs & Rules**
- [How do teams submit?](https://iridescentsupport.zendesk.com/hc/en-us/sections/115000630314-Submission)
- [Submissions Guidelines](https://technovationchallenge.org/submission-guidelines/)
- [How will team’s app be judged?](https://iridescentsupport.zendesk.com/hc/en-us/sections/115000250428-Judging-Pitching-and-Results)
- [Judging Rubric](https://technovationchallenge.org/curriculum/judging-rubric/)

**Comment by rsgonzal** [comment]
Hey Ophelie! Thanks for the links - Is this what you would like it to look like?

![uploads/f33a6437-d599-4f3f-877b-b2703537cd29/Screen Shot 2019-09-16 at 1.41.15 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff33a6437-d599-4f3f-877b-b2703537cd29%2FScreen+Shot+2019-09-16+at+1.41.15+AM.png)

**Comment by ophelieh** [comment]
Hi Roxana,

Looks great! For the top portion, we could even just call it "Resources". Thanks!

**Comment by rsgonzal** [comment]
Updated image
![uploads/a7bfdb2e-8713-4054-9829-12694fee8831/Screen Shot 2019-09-17 at 1.57.29 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa7bfdb2e-8713-4054-9829-12694fee8831%2FScreen+Shot+2019-09-17+at+1.57.29+PM.png)

Links:
- Curriculum https://technovationchallenge.org/curriculum-intro/registered/
- RA resource page https://technovationchallenge.org/ra-resources/
- RA Handbook https://iridescentlearning.atavist.com/technovation-ra-handbook
- Parental Consent PDF (not ready)

- How do teams submit? https://iridescentsupport.zendesk.com/hc/en-us/sections/115000630314-Submission
- Submissions Guidelines https://technovationchallenge.org/submission-guidelines/
- How will team’s app be judged? https://iridescentsupport.zendesk.com/hc/en-us/sections/115000250428-Judging-Pitching-and-Results
- Judging Rubric https://technovationchallenge.org/curriculum/judging-rubric/

**Comment by hellafitz** [comment]
Capitalization should be as consistent as possible. For example, in Resources, it should be "RA Resource Page"

**Comment by rsgonzal** [comment]
Thanks, Matt! Updated the text above.

The tab name should Probably be capitalized as well

**Comment by stenington** [comment]
![Screen Shot 2019-09-19 at 11 51 24 AM](https://user-images.githubusercontent.com/55319/65260331-39411800-dad4-11e9-9a9f-2ace8b496e3a.png)

Is this acceptable for the list styling? I would rather reuse existing styles than create a new style definition for this one place, and this is what a bare `<ul>` looks like.

**Comment by stenington** [comment]
QA:

1. log in as an RA
2. go to the *RA resources* tab
3. confirm that the page styling works for you
4. confirm that each link and link text is correct

**Comment by rsgonzal** [comment]
@ophelieh would you mind testing this one by Wednesday to see if everyone looks and works ok?

**Comment by ophelieh** [comment]
Looks great and all works except the link to the consent form - https://iridescentsupport.zendesk.com/hc/en-us/article_attachments/360018888234/2019_Technovation_Parent_Consent_Form.pdf

**Comment by stenington** [comment]
Oh, sorry about that @ophelieh! Forgot to update that config. It should be correct now.

**Comment by rsgonzal** [comment]
here is the new PDF link: https://iridescentsupport.zendesk.com/hc/article_attachments/360046540354/2020_Technovation_Parent_Consent_Form.pdf

**Comment by stenington** [comment]
Ok, updated.

**Comment by rsgonzal** [comment]
link has been updated!

**Comment by ophelieh** [comment]
Perfect! :) Thank you guys. :)
