### ISSUE TITLE
Mentor sign up "school or company name" field seems to bias people towards bad data [20,?,?]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2195]
When a mentor is signing up, we ask them to provide their school or company name. The problem is that the actual form field looks like a dropdown you need to select a value from when actually it's a free text field with autocomplete. This seems to be biasing people to choose a company they don't work for instead of providing us with the name of their actual school or company.

For historical context, my recollection is that the autocomplete was added because free text had too much variation. For example, "Company X" employees might type 
* Company X
* company x
* Co. X

and so forth, which made querying for "mentors who signed up from Company X" a guessing game in the admin.

Notice that there is already explanatory text saying 
>  If your company is not part of the options, type the name of your company then press "Enter" or "Tab"

Clearly that's not sufficient given the bad data from last season and the experience of our own team members going through mentor sign up for the first time.

I do also notice that the field behaves more like a dropdown than an autocomplete box, and that may be what's misleading people. Many autocomplete fields require you to begin typing before providing autocompletions, and sometimes they even require a certain number of characters before beginning to autocomplete. They also often provide visual clues, like bolding the part of the autocompletion that matches what you've typed. 

[Here's an article](https://baymard.com/blog/autocomplete-design) discussing 8 such design patterns for autocomplete fields that we may want to try to follow more closely. Maybe if we de-emphasize the dropdown aspect people will realize they are expected to enter text, but will also be nudged to pick a pre-existing option where appropriate that will result in cleaner data. 

### Typing a company that autocompletes
![intended2](https://user-images.githubusercontent.com/55319/64821913-defb0100-d581-11e9-9467-a807e72f8c9c.gif)
### Typing a company we don't know about
![intended](https://user-images.githubusercontent.com/55319/64821914-df939780-d581-11e9-9e85-63100de1b77d.gif)
### Treating it like a dropdown
![nonintended](https://user-images.githubusercontent.com/55319/64821915-df939780-d581-11e9-95d6-1c311c8347c0.gif)

**Comment by stenington** [comment]
Discussed with @hellafitz and @rsgonzal and we're potentially pursuing 2 paths:
1. What does it look like if we go back to having this field be free text? What sorts of accommodations do we need to normalize the (presumably) messy data we'd get?
2. What are the technical implications of trying to do a more traditional autocomplete solution?

**Comment by stenington** [comment]
Here are some examples from a rough analysis:

I pulled the school or company names from mentor profiles with no additional filtering or normalization. Below are the top three values, the count of profiles with exactly that value, and the count of other profiles that had a value that is plausibly equal to the value listed, with the caveat that not all values are necessarily equal, nor are all plausible variations necessarily accounted for.

This is intended as a back-of-the-envelope sort of investigation to give a starting point for discussion.

| Company or school name | Exact Count | Additional Count | Variations seen |
| --- | --- | --- | -- |
| Google | 477 | 44 | 24 |
| Salesforce | 357 | 58 | 21 |
| Adobe | 329 | 189 | 45 |

**Comment by rsgonzal** [comment]
Asked Amy about the open field option:
- When we had an open field for free text, people had a lot of typos so it was hard to clean up the data. But that year it was not a required field so that might have contributed to bad data
- It got a little confusing with things like Google and "Google India". 
- But right now, it feels like a free text field might just be better

She also offered up another solution
Since we do ask mentors to self identify as educator or professional or alumni, is it possible to make this question customizable?
- If someone selects "educator," they will be asked "what school or organizations do you work at?" instead of "what company do you work at?".  
- It might help us have better data and also be able to separate out data from different groups.

**Comment by hellafitz** [comment]
created #2208 for plain text solution and #2209 for autocomplete option. closing this ticket out.
