### ISSUE TITLE
Remove Project Workbook from dropdown on Student Dashboard [2,1,2]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2196]
The Project workbook is no longer being shared with students. Remove the text and link under it from the dropdown.

![uploads/50e9d763-548a-41a2-a3e8-08c06ea72827/Screen Shot 2019-09-15 at 10.47.50 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F50e9d763-548a-41a2-a3e8-08c06ea72827%2FScreen+Shot+2019-09-15+at+10.47.50+PM.png)

**Comment by stenington** [comment]
QA:

1. log in as a student
2. confirm that the "More information" dropdown does not contain the project workbook header and link

**Comment by rsgonzal** [comment]
@devincdillon this is ready to be tested, could you please take a look? thanks!

**Comment by devincdillon** [comment]
Confirming that I went to staging site, logged in as student, and could not see the curriculum workbook :)
