### ISSUE TITLE
Update submission deadline on Platform [3,3,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2197]
Found this tag in emails and I assume it's used in other places
`<%= @season_submission_deadline %>`

Currently it is set to April 23rd, should be April 13th for current season

**Comment by stenington** [comment]
Looks like this date gets hardcoded as a string. The quickest option is to just update that string, but with a little more effort we could put ourselves in a better position to update this for future seasons without a code deployment.

**Comment by hellafitz** [comment]
do this as config (reassess for full admin interface control down the road)

**Comment by stenington** [comment]
The main change to QA is:

1. register as a student
2. receive the welcome email
3. confirm that the season submission deadline is correct, given how staging is configured

The submission deadline shows up in a variety of other places as well, and those places should also be showing the configured date correctly. I don't know if QAing those places is in or out of scope on this ticket though. It seems like there are a handful of places in the student dashboard that show the submission deadline, but those places probably aren't visible until submissions have opened.

**Comment by rsgonzal** [comment]
It would probably be a good idea to double check those places. I could open submissions in staging so it shows

**Comment by stenington** [comment]
Ok, so here are a handful of places I can see it showing up:

* scoring sidebar
<img width="961" alt="Screen Shot 2019-09-20 at 9 43 40 AM" src="https://user-images.githubusercontent.com/55319/65331676-3bb27900-db8b-11e9-83e6-c66304a79487.png">
* published app page
<img width="961" alt="Screen Shot 2019-09-20 at 9 38 01 AM" src="https://user-images.githubusercontent.com/55319/65331677-3bb27900-db8b-11e9-9cc7-3799f9327aae.png">
* app review page
<img width="961" alt="Screen Shot 2019-09-20 at 9 37 46 AM" src="https://user-images.githubusercontent.com/55319/65331678-3bb27900-db8b-11e9-9c73-f7a6944e01f2.png">
* submissions page sidebar
<img width="961" alt="Screen Shot 2019-09-20 at 9 37 01 AM" src="https://user-images.githubusercontent.com/55319/65331679-3bb27900-db8b-11e9-8bd4-26012baf5e13.png">

**Comment by rsgonzal** [comment]
In the email, this is set to April 13th, 2019
Wrong year! This can be changed through config?

**Comment by stenington** [comment]
Also just noticed that the date on the judging screen might not make sense.

**Comment by stenington** [comment]
@rsgonzal Okay, false alarm on that judge page. It is pulling in a different date that I just happened to set to the same date as the submission deadline in my environment. 🤦‍♂ I removed that screenshot from the previous comment.

**Comment by stenington** [comment]
And I did add config for the submission deadline year, which is set on staging to 2020 (`DATES_SUBMISSION_DEADLINE_YEAR`), so the email should have the correct year now @rsgonzal

**Comment by rsgonzal** [comment]
All places look good now!
