### ISSUE TITLE
Update timeline URL on platform [3,2,1.5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2198]
Found this tag in emails and I assume it's used in other places
`@timeline_url `

Current link is broken - waiting on confirmation to where it should link to

**Comment by rsgonzal** [comment]
Timeline URL: https://infograph.venngage.com/ps/bAAeKGLlsk/2019-technovation-important-dates-and-milestones

**Comment by stenington** [comment]
Note for later: this link shows up in the mentor welcome and student welcome emails.

**Comment by stenington** [comment]
QA:

1. sign up as a mentor
2. receive welcome email
3. confirm the timeline link is correct

1. sign up as a student
2. receive welcome email
3. confirm the timeline link is correct

**Comment by mdancho** [comment]
The mentor timeline link is correct

**Comment by nickiredescent** [comment]
Can confirm that both the Mentor and Student welcome emails have linked to the correct timeline.
