### ISSUE TITLE
Update Honor Code on student dashboard [2,2,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2200]
Edits to the honor code which shows up right before girls start submitting on the platform
https://docs.google.com/document/d/1NUqsJVrKDsgZ16t5wjVBrQDD8et6j9Y3VQWrIoEpHXc/edit#heading=h.d9r2f2l02xjl
Page 104

**Comment by stenington** [comment]
Minor edits were made to the honor code. To see these for QA:

1. create a new student user or find one who hasn't started a submission
2. do what's needed to be able to see the "Begin your submission" button on the "Submit your project" part of the student dashboard
3. click the "Begin your submission" button 
4. read and confirm that the 2020 honor code is correct

**Comment by mdancho** [comment]
Honor code looks correct. One minor spacing error is between 2020 and Technovation girls: By indicating that you agree and signing below, you promise that all elements of your team’s **2020Technovation** Girls submission were created solely by the students on your 2020 Technovation team.

**Comment by stenington** [comment]
@mdancho good eye! I will fix it.

**Comment by ophelieh** [comment]
Noticed the same as Mackenzie. Everything else looks good. :) 
![image](https://user-images.githubusercontent.com/32206421/69583512-b25f5e80-0fa0-11ea-8e41-198528944fa5.png)

**Comment by stenington** [comment]
@ophelieh @mdancho Okay, whitespace should be fixed if you want to confirm. Thanks!

**Comment by ophelieh** [comment]
Looks good! :)
