### ISSUE TITLE
Update parent consent form [8,3,2.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2202]
Parent consent needs to be updated in a few places. Updated text can be found: https://docs.google.com/document/d/1c_H7TJn_KSgU9v5VaioXOS_VcTwNYHsxxz-tvj1slUs/edit

- Student dashboard: https://technovation-qa.herokuapp.com/student/dashboard#/parental-consent
Step 1 links to a download
replace link with: https://iridescentsupport.zendesk.com/hc/en-us/article_attachments/360046318154/2020_Technovation_Parent_Consent_Form_final.pdf
- Parents get [emailed a link](https://mandrillapp.com/track/click/30787762/technovation-qa.herokuapp.com?p=eyJzIjoiSVJ6dzBpNzEzX1NFbWF2Snljbkx4UlRqMV9vIiwidiI6MSwicCI6IntcInVcIjozMDc4Nzc2MixcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RlY2hub3ZhdGlvbi1xYS5oZXJva3VhcHAuY29tXFxcL3BhcmVudGFsX2NvbnNlbnRcXFwvZWRpdD90b2tlbj1LYzFlTUdhRllYVXlOdUVoQXh6V0pic3ZcIixcImlkXCI6XCI3OTUwODM1MTY4NjQ0YzlhOTM0YThiNmViYWExNDgxOFwiLFwidXJsX2lkc1wiOltcImQ5ODFlMTExM2QwMmMzYzlkYjY2OGY0ZjM1NmY3MWJmODYwMDU0ODJcIl19In0) to the consent form that takes them to the consent form on the dashboard (do not include the signature lines)

![uploads/78d4e3bb-f03c-416b-b236-a500f1a4422b/Screen Shot 2019-09-18 at 11.29.33 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F78d4e3bb-f03c-416b-b236-a500f1a4422b%2FScreen+Shot+2019-09-18+at+11.29.33+AM.png)

Need to confirm with Amy/Devin it's ready

**Comment by hellafitz** [comment]
@rsgonzal please check before planning, if possible

**Comment by rsgonzal** [comment]
This one is ready

**Comment by stenington** [comment]
@rsgonzal I don't understand your comment about not including the signature lines for the version the parent signs. Can you clarify what you mean?

**Comment by stenington** [comment]
The pdf provided has two item 5's, which I assume we should fix?

Also, I asked a question in the doc that I'll re-ask here: The code for the parental consent page uses the email defined as `HELP_EMAIL` for the entire site, which on production is currently help@technovationchallenge.org Do you want the entire site to use support@technovationchallenge.org wherever HELP_EMAIL is referenced, or do you just want that changed on the parental consent page?

**Comment by stenington** [comment]
@rsgonzal Meant to tag you in the previous comment

**Comment by stenington** [comment]
This is what the bottom of the page looks like when the parents see it. It doesn't have the same signature lines, but it has form fields for electronically signing:

![Screen Shot 2019-09-20 at 2 07 25 PM](https://user-images.githubusercontent.com/55319/65348887-2bf95b80-dbb0-11e9-8106-028d0a45de9f.png)

**Comment by stenington** [comment]
It looks like help@technovationchallenge.org is an alias of support@technovationchallenge.org in that Google Apps account, so they should be interchangeable as far as I can tell. So my plan unless I hear otherwise here will be to update the config such that `HELP_EMAIL=support@technovationchallenge.org` for production and staging.

**Comment by rsgonzal** [comment]
Yes! I think this is a great solution!

**Comment by stenington** [comment]
QA:

1. sign up as a student
2. confirm the downloadable parental consent is correct
3. enter a parent email address that you're able to check
4. receive the email and follow the link
5. confirm that the parental consent signing page is correct

**Comment by rsgonzal** [comment]
Here is the updated PDF: https://iridescentsupport.zendesk.com/hc/article_attachments/360046540354/2020_Technovation_Parent_Consent_Form.pdf

**Comment by stenington** [comment]
Updated on staging.
