### ISSUE TITLE
Update Volunteer Agreement on Mentor Dashboard [8,3,2.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2203]
Updated text can be found here: https://docs.google.com/document/d/1wersU4YbM7NvHU2IqkSfJyYZOxPb0b2K7S0KZVBSono/edit#heading=h.1not9tfvzdli

Linked from this page:https://technovation-qa.herokuapp.com/mentor/dashboard#/consent-waiver

Need to confirm with Amy/Devin it's ready

**Comment by rsgonzal** [comment]
Confirmed this is ready

**Comment by mdancho** [comment]
Confirmed the agreement is updated on the mentor dashboard and text looks good!

**Comment by rsgonzal** [comment]
looks great!
