### ISSUE TITLE
Update mentor orientation URL [5,2,2.5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2204]
Found this tag in emails and I assume it's used in other places
`@orientation_url`

Current link is broken, replace with: https://infograph.venngage.com/pl/6bzOhyG16fc

**Comment by stenington** [comment]
After discussion with @rsgonzal it's probably more useful to have links like this directly in the template rather than pulled into this kind of variable.

**Comment by stenington** [comment]
Note for later: this shows up in the mentor welcome

**Comment by stenington** [comment]
QA:

1. sign up as a mentor
2. receive welcome email
3. confirm the orientation link is correct

**Comment by mdancho** [comment]
The orientation link is correct
