### ISSUE TITLE
Update Mentor training on dashboard [8,3,2.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2205]
The mentor training on the mentor dashboard is outdated. Embedded link needs to be replaced.

Location: https://technovation-qa.herokuapp.com/mentor/dashboard#/mentor-training

New powerpoint link: MISSING

**Comment by hellafitz** [comment]
@rsgonzal make sure the final slide (with a link that marks the user as having completed the training) is preserved in the new version

**Comment by mdancho** [comment]
Hi guys! Here is the link to the powerpoint, we will be making edits until monday but the link shouldnt change. Thanks for noting that ^^ @hellafitz, the last slide needs the same link that they can click to mark the user has completed the training. 

https://docs.google.com/presentation/d/1C4rE7FMFgWShx3vzWOhuBPwl-MHoO6QjRGPyAdyi5n4/edit?usp=sharing

**Comment by rsgonzal** [comment]
Hey @mdancho i think you need to change the sharing settings on this to make it public. Opened it up in incognito and it's asking me to sign in.

**Comment by hellafitz** [comment]
Link is now accessible

**Comment by stenington** [comment]
The final button should link to https://my.technovationchallenge.org/mentor/training_completion

**Comment by hellafitz** [comment]
@stenington, Mac says that, according to Amy, once the PPT is "published" and then embedded into the platform, we can give her the click link that she can add to the last slide. Does that sound right?

**Comment by stenington** [comment]
@mdancho Looks like that link doesn't work for embedding. I believe these are the steps to publish it for embedding:
1. Open a file in Google Docs, Sheets, or Slides.
2. At the top, click File and then Publish to the web.
3. In the window that appears, click Embed.
4. Choose a publishing option:
    * Spreadsheet: Choose to publish the entire spreadsheet or individual sheets.
    * Presentation: Choose a presentation size and how quickly to change the slides.
5. Click Publish.
6. Copy the HTML in the text box and paste it into your site or blog.

You can also give me edit access and I can try doing this. It's possible that if you continue editing after publishing, those changes won't appear without us doing this again but I'm not sure.

**Comment by mdancho** [comment]
Thanks Mike. I've published the presentation, this is the link from the textbox: <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQXVdICLjRstNdDdl-UXdpYIhw3zlNfaWgUFEeKx2B3NuR7aVWXpFKNwEINOF7boIdXLhnyzZ8esbPA/embed?start=true&loop=false&delayms=60000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

**Comment by rsgonzal** [comment]
@stenington is this meant to be in test? still seeing old training.

**Comment by stenington** [comment]
Looks like I got ahead of myself, tests failed and it hadn’t hit staging yet.

**Comment by stenington** [comment]
@rsgonzal fixed

**Comment by mdancho** [comment]
Works brilliantly, thanks all!

**Comment by rsgonzal** [comment]
looks great!
