### ISSUE TITLE
Change "School or company name" field back to a free text field [13,5,2.6]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2208]
Coming from #2195, we want to remove the filterable dropdown option that doesn't seem to be working well, and change the "School or company name" field during sign up to a free text field. It should be a required field as well, if it isn't already.

**Comment by stenington** [comment]
@rsgonzal if we're going to change the help text associated with the field, we can do that in this ticket.

**Comment by stenington** [comment]
Once this goes to staging, my recommended QA would be:

For each of the following ways to sign up, 
1. sign up
2. confirm that the school/company name field is a plain text box
3. make note of the school or company name you enter.

Do this for the following ways to sign up:
* Mentor through the "Sign up" button
* Student through the "Sign up" button
* Mentor from an admin invite
* Student from an admin invite
* Judge from an admin invite
* Judge from admin signup link
* RA from an admin invite

Then
1. log in as an admin
2. go to the participants tab
3. add "School name" and "Company name" as additional columns 
4. find the users you created and confirm each of them has the school or company name you entered

**Comment by rsgonzal** [comment]
Help text update from @mdancho : Please write your school or company name in the field below.

**Comment by rsgonzal** [comment]
@mdancho would you be able to QA this by Friday? Let me know if you have any questions!

**Comment by stenington** [comment]
@rsgonzal I'm second-guessing the help text. 

Firstly, it looks like there are 3 different ways the same field is labelled:
1. **Organization/company name** for RAs
2. **School or company name** for Mentors or Judges
3. **School name** for Students

It's easy enough to adapt the help text for each, e.g. "Please write your organization/company name in the field below." so that would be one option. But we don't label other fields (e.g. first name, last name, job title) similarly and we expect users to know what to do, so is redundant help text needed on just this one field?

If yes, then let me know how you want the help text to look for the 3 variations of the field labels.

## Screenshots of different sign up screens
**RA invitation**
![Screen Shot 2019-09-25 at 4 30 42 PM](https://user-images.githubusercontent.com/55319/65637307-f68aae80-dfb1-11e9-8fe5-73f01531ccf9.png)

**Judge link/invitation**
![Screen Shot 2019-09-25 at 4 29 54 PM](https://user-images.githubusercontent.com/55319/65637309-f68aae80-dfb1-11e9-9687-d9efefa6889d.png)

**Mentor invitation**
![Screen Shot 2019-09-25 at 4 29 29 PM](https://user-images.githubusercontent.com/55319/65637310-f7234500-dfb1-11e9-8f2a-698b39723622.png)

**Student invitation**
![Screen Shot 2019-09-25 at 4 29 03 PM](https://user-images.githubusercontent.com/55319/65637311-f7234500-dfb1-11e9-9698-5aecf3f4a0f2.png)

**Mentor sign up wizard**
<img width="961" alt="Screen Shot 2019-09-25 at 4 27 53 PM" src="https://user-images.githubusercontent.com/55319/65637312-f7234500-dfb1-11e9-8ac4-04f1557a449a.png">

**Student sign up wizard**
<img width="961" alt="Screen Shot 2019-09-25 at 4 27 42 PM" src="https://user-images.githubusercontent.com/55319/65637313-f7234500-dfb1-11e9-9bea-9a983790658a.png">

**Comment by rsgonzal** [comment]
You're right, considering what it says I don't think it's necessary. Let's do without.

**Comment by stenington** [comment]
Okay, so then this is ready for QA. Pulling down the recommended steps from the comments above:

Recommended QA would be:

For each of the following ways to sign up, 
1. sign up
2. confirm that the school/company name field is a plain text box
3. make note of the school or company name you enter.

Do this for the following ways to sign up:
* Mentor through the "Sign up" button
* Student through the "Sign up" button
* Mentor from an admin invite
* Student from an admin invite
* Judge from an admin invite
* Judge from admin signup link
* RA from an admin invite

Then
1. log in as an admin
2. go to the participants tab
3. add "School name" and "Company name" as additional columns 
4. find the users you created and confirm each of them has the school or company name you entered

**Comment by mdancho** [comment]
Tested all accounts and they all work! However, most answers are categorized under the company name unless the word school/academy appears in the school title. 
![uploads/e79b2045-7705-4306-a9c9-08a3ffb358fe/Screen Shot 2019-09-27 at 1.58.02 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe79b2045-7705-4306-a9c9-08a3ffb358fe%2FScreen+Shot+2019-09-27+at+1.58.02+PM.png)

**Comment by stenington** [comment]
Yeah I believe that `School name` only has a value for a student, and `Company name` holds the school or company name for all other user types.
