### ISSUE TITLE
Spike: Implement Branding Changes to TC.org

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2226]
Needs more details

**Comment by hellafitz** [comment]
@rsgonzal please update ticket w/ email info from Kristen and co.

**Comment by hellafitz** [comment]
Mike hasn't worked on the code of this platform before so there is some amount of startup costs / extra decision-making.

**Comment by rsgonzal** [comment]
Marketing team needs help editing the style sheets for technovationchallenge.org
@mjaris can make certain changes, need to coordinate timing with her to implement everything together

Mockups: https://www.dropbox.com/sh/mxuemjr05p7dc9m/AABkDhuL1s-B1PYJLbllEY98a?dl=0
Markup of changes that need dev support: https://projects.invisionapp.com/freehand/document/1UH7p91GC
Branding Guidelines: https://www.dropbox.com/s/3ceu29p1de4hwwb/Technovation%20Brand%20Guidelines%202019.pdf?dl=0

New typfaces
- Poppins: https://fonts.google.com/specimen/Poppins
- Rubik: https://fonts.google.com/specimen/Rubik+Mono+One

Colors:
- Energetic Blue
PMS 2195C
C 98 M 40 Y 0 K 0 R 0 G 118 B 207
- Magenta
PMS 226C
C 0 M 100 Y 2 K 0 R 208 G 0 B 111
- Gold
PMS 1235C
C 0 M 31 Y 98 K 0
R 255 G 184 B 28
- Dark Blue
PMS 282C
C 100 M 90 Y 13 K 68
R 4 G 30 B 66
- Bright Blue
PMS 2985C
C 60 M 0 Y 3 K 0
R 91 G 194 B 231
- Green
PMS 361C
C 77 M 0 Y 100 K 0 R 67 G 176 B 42
- Orange
PMS 2018C
C 0 M 58 Y 95 K 0 R 255 G 117 B 0

Adding screenshots:

![uploads/aa516436-2b99-47fd-8036-96c6ff3e905b/Screen Shot 2019-10-04 at 1.13.19 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Faa516436-2b99-47fd-8036-96c6ff3e905b%2FScreen+Shot+2019-10-04+at+1.13.19+PM.png)

![uploads/9bb8af65-f928-4378-b36d-ad3de0a7f959/Screen Shot 2019-10-04 at 12.46.44 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9bb8af65-f928-4378-b36d-ad3de0a7f959%2FScreen+Shot+2019-10-04+at+12.46.44+PM.png)

![uploads/7f48bae2-765d-48f8-96ea-2c88953d3155/Screen Shot 2019-10-04 at 12.43.20 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7f48bae2-765d-48f8-96ea-2c88953d3155%2FScreen+Shot+2019-10-04+at+12.43.20+PM.png)

![uploads/daa8e516-287d-4829-ae1b-c6fa46c058cd/Screen Shot 2019-10-04 at 12.42.22 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdaa8e516-287d-4829-ae1b-c6fa46c058cd%2FScreen+Shot+2019-10-04+at+12.42.22+PM.png)

![uploads/726e6956-ed56-445d-96de-2d484020fe62/Screen Shot 2019-10-04 at 1.32.53 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F726e6956-ed56-445d-96de-2d484020fe62%2FScreen+Shot+2019-10-04+at+1.32.53+PM.png)

**Comment by Allicolyer** [comment]
Hey, so I started investigating what it will take to make these changes.

1. The styling edits need to be made to SASS files and then compiled into CSS: wp-content/themes/technovation/sass
2. New fonts can be added to this folder and updated in SASS: wp-content/themes/technovation/fonts
3. Curriculum listing edits need to be made to the Page Builder Custom Modules: wp-content/plugins/technovation-custom-modules/curriculum-listing/css/
4. Preset button colors can be changed in the theme: wp-content/themes/technovation/fl-builder/modules/button/includes/frontend.css.php


Still to do:

- Need more investigation into changing page builder custom modules and if I need to compile the CSS 
- Need to access staging site with FTP 
- My local environment only partially works, I would like to get it fully up and running before making changes to make sure there are no unintended things that go wrong
- Need to set up a SASS compiler, I think I'll use Koala
 
Questions:

1.  The theme colors for our site are defined as SASS variables. We could just update these variables to our new theme colors.  Updating the theme colors is more sustainable, but would change colors in other places across the site

**Comment by stenington** [comment]
Cool, thanks for writing this up @Allicolyer!

I agree that it would be worth getting your local environment fully up and running if possible, having parity between environments tends to reduce headaches in my experience. 

I think it would also be worth exploring the option of using git instead of FTP to manage changes to staging. I think technovationchallenge.org is using "legacy" staging, so [this would be the guide](https://wpengine.com/support/using-git-on-sites-with-legacy-staging/) to look at. But if that feels like too much of a rabbit hole, then don't worry about it. I like that using git would give us a change history, whereas FTP would not.

**Comment by mjaris** [comment]
Hey all -- I agree with @Allicolyer that updating the existing theme colors to the new theme colors by changing the variables is probably the best. I do think it's going to make things look awful so if we could just coordinate the day we make that change I'll clear most of my schedule so that I can focus on making tweaks/updates to our big pages as quickly as possible. 

Do you also want a little map for which colors should become which, Alli? (ie, 42880 = 43b20a)?

**Comment by Allicolyer** [comment]
@stenington I think git would be the way to go. we can use this repo: [https://github.com/Iridescent-CM/technovation-wp](https://github.com/Iridescent-CM/technovation-wp/)

@mjaris sure that like a good plan! Here's the current theme:

```
/* green */
$clr-1: #28a880;
$clr-1-lt: #59bf93;
$clr-1-dk: #00643f;

/* red */
$clr-2: #7d324d;
$clr-2-lt: #903d53;
$clr-2-dk: #52082d;

/* purple */
$clr-3: #6e466b;
$clr-3-lt: #895e85;
$clr-3-dk: #411b41;

/* blue */
$clr-4: #01aaac;
$clr-4-lt: #4cc1c6;
$clr-4-dk: #016667;

/* light gray */
$clr-5: #cccccc;
$clr-5-lt: #ebebeb;
$clr-5-dk: #878787;

/* dark gray */
$clr-6: #444444;
$clr-6-lt: #666666;
$clr-6-dk: #323232;

/* yellow */
$clr-7: #e9e46f;
$clr-7-dk: #c1c320;
```

**Comment by mjaris** [comment]
Thanks @Allicolyer! 

Here's the conversion chart (I think we can lose the light/dark versions and just have 7 colors, but if that's a red flag let me know and I can work with Audra to pull tints)-- also let me know if there's a better way to format :) 

/* green */
$clr-1: #28a880; -> #0076cf (blue)
$clr-1-lt: #59bf93;
$clr-1-dk: #00643f;


/* red */
$clr-2: #7d324d; -> #43b02a (green)
$clr-2-lt: #903d53;
$clr-2-dk: #52082d;

/* purple */
$clr-3: #6e466b; -> #ec0089 (pink)
$clr-3-lt: #895e85;
$clr-3-dk: #411b41;

/* blue */
$clr-4: #01aaac; -> #5be2e7 (light blue)
$clr-4-lt: #4cc1c6;
$clr-4-dk: #016667;

/* light gray */
$clr-5: #cccccc; -> #ffffff (white)
$clr-5-lt: #ebebeb;
$clr-5-dk: #878787;

/* dark gray */ 
$clr-6: #444444; -> #041e42 (dark blue)
$clr-6-lt: #666666;
$clr-6-dk: #323232;

/* yellow */ 
$clr-7: #e9e46f; -> #ffb81c (gold)
$clr-7-dk: #c1c320;

**Comment by Allicolyer** [comment]
Thanks for being so quick Maggie! This format looks good!

I think in general it's good to keep the tints and shades.  If we remove the tints and shades and replace them with other colors we will probably get some really ugly looking pages. I'm not sure how many places the tints and shades are being used in, but I can do some investigating if you want.   

Alright, so according to this theme blue is the primary color and green is the secondary color for Technovation Girls?

**Comment by Allicolyer** [comment]
Documenting some problems and solutions I encountered to get my local dev environment to work.

**Problem**: Database was too large to be uploaded through phpMyAdmin: 
**Solution**: Modified the maximum upload file size by editing the PHP config file. `/Applications/MAMP/bin/php/php7.3.8/conf/php.ini`

**Problem**: phpMyAdmin times out when trying to upload large database files
**Solution** : Needed to use [MySQL CLI](https://dev.mysql.com/doc/refman/5.5/en/mysql.html) to upload database .

1. `mysql -h 127.0.0.1 -P 8889 -u root -proot`
2. `create database foo;`
3. `use foo;` 
4. `source mysql.sql;

Problem: Needed to update site URL
Solution: Add these lines to wp-config.hp
```
define( 'WP_SITEURL', 'http://localhost:8888/t-girls/' );
define( 'WP_HOME', 'http://localhost:8888/t-girls/' );
```

**Problem**: Site could not connect to database.
**Solution**: Update database in wp-config.php to localhost:8889 using this line: `define( 'DB_HOST', '127.0.0.1:8889' );`

**Problem**:  When trying to access wp-admin, the site was forcing a redirect to `https` causing an SSL error.
**Solution**: Remove these all lines forcing SSL from wp-config.php
```
define( 'WPE_FORCE_SSL_LOGIN', true );
define( 'FORCE_SSL_LOGIN', true );
/*SSLSTART*/ if ( isset($_SERVER['HTTP_X_WPE_SSL']) && $_SERVER['HTTP_X_WPE_SSL'] ) $_SERVER['HTTPS'] = 'on'; /*SSLEND*/
```

**Problem**:  URLs for pages other than the home page did not work, throwing a 404 error.
**Solution**: In the wp-admin panel, click on settings --> permalinks. Don't change anything and click "save changes".
