### ISSUE TITLE
Add location to registration page for RAs [5,5,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2227]
It is not intuitive for RAs to fill out their location after they complete the registration process. Last season, a few RAs were concerned about not seeing any participants and it was because their location was not entered.

They do not immediately see it in their dashboard and have to go to "My Account"
![uploads/740f0729-fbb8-401a-a43f-b2af6352ac92/Screen Shot 2019-09-26 at 3.40.48 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F740f0729-fbb8-401a-a43f-b2af6352ac92%2FScreen+Shot+2019-09-26+at+3.40.48+AM.png)

![uploads/f02e912f-f0ab-4fab-8196-8d90b69b1edc/Screen Shot 2019-09-26 at 3.42.41 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff02e912f-f0ab-4fab-8196-8d90b69b1edc%2FScreen+Shot+2019-09-26+at+3.42.41+AM.png)

It is only a problem with new RAs though, Ophelie can create a video to explain the process for them to sign up. 

https://drive.google.com/file/d/1Vs5-cmLxYllWRtDK6451CDsfDHYipqgB/view

**Comment by stenington** [comment]
The best way to handle this ticket is probably to present RAs with the same location interrupt screen that judges and mentors get, which will ensure they've inputted their location before they're able to use the site. Another ticket should be opened outlining the difference between the sign up wizard and the invitation-based signup pages, and a suggestion for a path forward there.

**Comment by stenington** [comment]
I think step 1 here is doing a run-through of RA sign up and seeing if it feels good enough for now. If so, I can think through if there's any more formal QA that should be done.

**Comment by ophelieh** [comment]
Hi! This works great for this season. :) 

Could we potentially change the message when asking for the location or is that the same for all profile types? I'm just worried it might cause confusion. This is very minor. 
![uploads/6f6635c4-8a8d-4e86-bd18-0ff42b85525e/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6f6635c4-8a8d-4e86-bd18-0ff42b85525e%2Fimage.png)


Very minor as well - I noticed that the invitation I receive says I need to confirm my email, but then it brings me to confirm your detail page and doesn't mention that my email was confirmed. 

![uploads/1f0b379f-e2b0-4078-bb02-51cd85f040f1/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1f0b379f-e2b0-4078-bb02-51cd85f040f1%2Fimage.png)


![uploads/bad33f44-9cfb-4b1d-84cf-8c44a40a4387/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbad33f44-9cfb-4b1d-84cf-8c44a40a4387%2Fimage.png)

Thank you!!!

**Comment by stenington** [comment]
@ophelieh Thanks for QAing!

The page asking for the location does potentially handle all account types, and it can be shown for new users or returning users, if they don't have good location data stored for some reason. But even so, I feel like we could simplify the message shown on that page to something that works better for everyone. Are you concerned they'll be confused by being told their location is missing? Or that we say we'll bring them to their dashboard?

On the "Confirm your RA details" page, I believe we could add a message that would show up in the green area:

![Screen Shot 2019-10-09 at 4 47 08 PM](https://user-images.githubusercontent.com/55319/66519043-7df91700-eab4-11e9-8e10-cfb18fa15e4b.png)

Something like "Thank you for confirming your email address"? What would be good?

**Comment by ophelieh** [comment]
I agree with simplifying the language on the location page. And my concern is about them being confused that they are told their location is missing when they weren't asked for it before that point. 

Could we say something like: "Please enter your location to access your dashboard. Thank you!"? 

For the RA confirmation page, "Thank you for confirming your email address" would be great! :) 

Thank you!!!

**Comment by stenington** [comment]
@ophelieh these changes should be on staging now, can you run through it once more and confirm for me? Thanks!

**Comment by ophelieh** [comment]
Hi Mike! Everything looks great! :) Thanks.
