### ISSUE TITLE
Misc ‘New Season’ Bug Support [8,13,0.62]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2229]
TG Platform will consider 10/1 the new season so weird bugs may show up 10/1-2. This ticket is for tracking that activity. Associated tickets may be split off for particular pieces of work.

**Comment by hellafitz** [comment]
Work consists of monitoring and triaging related bugs from 10/2-10/9.

Related bugs may include:
- dates that don't roll over
- admins reporting that they can't access past data now that the new season has started
- new season registration workflow errors (inc. people signing up to Campaign Monitor instead of MailChimp since the transition won't have been completed 100%)

**Comment by stenington** [comment]
First bug: tests started failing because they're looking for 2020 certificate pdf templates that don't exist.

**Comment by stenington** [comment]
Also old 2019 dates in config now cause test failures.

**Comment by stenington** [comment]
Collecting full and/or quick fixes in PR #2233

**Comment by rsgonzal** [comment]
@stenington awkward date switch and season not open yet
![image (8)](https://user-images.githubusercontent.com/22801026/66147422-aae49000-e5c3-11e9-874e-c3830e9f2344.png)

**Comment by stenington** [comment]
From Devin:
> While downloading 2019 registrations, I took a peak at 2020 student registrations and encountered a few unexpected things:
> 
>    we have 19 signed up, which I think Roxana was saying was happening when people had previous accounts and finished registering or something
    What I'm potentially concerned about is that I had the "fully onboarded" feature on, but then I looked into a few of the student profiles and they did not have their consents signed (screenshot attached)

**Comment by stenington** [comment]
@rsgonzal If we can get a quick-fix out for this page, can you mark where you'd want "Technovation" to become "Technovation Girls" as well? Would it be everywhere, or are there some places on that page where leaving it as "Technovation" is appropriate?

**Comment by stenington** [comment]
Also @rsgonzal I looked into the onboarding problem Devin saw, and it raises red flags for me. It looks like two things are happening:
1. there's an `onboarded` flag on the student profiles that looks like it was calculated and set last year that probably needs to be reset to false somehow to force the platform to recalculate (not 100% sure on that)
2. we probably need to either delete or void last year's parental consent forms to force users to obtain a new one this year

**Comment by rsgonzal** [comment]
Just saw this! Marked the places on last page here: https://docs.google.com/document/d/1NUqsJVrKDsgZ16t5wjVBrQDD8et6j9Y3VQWrIoEpHXc/edit#

I just left one Technovation

**Comment by stenington** [comment]
Flagging here that before we close this, we may want to open new tickets about the work that would need to happen to avoid encountering these exact bugs again in 1 years time.

**Comment by stenington** [comment]
Manual actions needed on season rollover:
* update configured dates to be current for the upcoming season, or tests fail
* copy last season's certificates folder for the current season, or tests fail
  * but don't forget to eventually update those templates, or dates may be wrong
* cached `onboarded` values need to be reset
* training completion dates need to be reset

Automatic actions on season rollover:
* consent waivers need to be reset (currently through a scheduled job)
* parental consents need to be reset (they include seasonality in the code base and become voided when not in the current season)

Other issues to address:
* the "Registration is currently closed" page has hard-coded dates that need to be kept current, or it needs to be updated to do something smarter
  * previously it would show the next season roll-over, but the mistake was made this year of not matching that up with the actual registration open date
* returning users can log in at any time, and can register for the new season prior to registration being open if the season rollover happens earlier than opening
* returning users can be registered for the prior season after it has occurred when logging in to check on the upcoming season

Some of those manual actions can be converted to automatic actions, although it would still be good to have a checklist item somewhere that we use next year to confirm that the correct things happened. 

I think we might also want to consider making `RegisterToCurrentSeasonJob` obey the admin settings and not register users logging in for the first time if the proper registration flag isn't turned on. I think that would help mitigate some of the weirdness around synchronizing the roll-over date with the actual registration opening date, although we may need to take some care thinking through what users should see when they log in in such a scenario.
