### ISSUE TITLE
Misc ‘Reg Opening’ Bug Support [13,8,1.63]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2230]
TG registration opens on 10/10 and we expect misc bugs to get reported once that happens. This ticket is for tracking that activity. Associated tickets may be split off for particular pieces of work. 

Note: Effort estimate doesn't include fixing bigger bugs, and a new ticket will be created for support that happens after it-07.

**Comment by hellafitz** [comment]
Related to #2229 (which covers bug support before 10/10 reg opening). 

This is where we'll start to hear complaints from users. Some will be actual bugs, some won't (e.g. unclear instructions, user error, etc). 

Bugs might include:
- accounts not created correctly
- inability to login to existing accounts
- slow site performance due to traffic spikes

**Comment by rsgonzal** [comment]
From Zendesk Ticket:
Platform doesn't have a 2010 option when selecting your birthday.
Kids born in 2010 will be 10 next year!
![uploads/6015252c-c3ac-43db-8c95-c89071e01fc5/Screen Shot 2019-10-14 at 12.35.46 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6015252c-c3ac-43db-8c95-c89071e01fc5%2FScreen+Shot+2019-10-14+at+12.35.46+AM.png)

**Comment by rsgonzal** [comment]
Did you put a fix up for this on staging? checking something else and noticed this was working now. Looks good!
