### ISSUE TITLE
Rebrand: Error pages out of date [8,8,1.0]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2234]
**Describe the bug**
The "Our servers are very busy right now" error page sends people to 

<ul>
        <li><a href="http://www.technovationchallenge.org/curriculum/madewithcodeprimer">Read the Technovation Challenge Primer</a> (if you came from Made With Code)</li>
        <li><a href="http://www.technovationchallenge.org/curriculum">2017 Technovation Curriculum</a></li>
      </ul>

The 500 page just has old branding.

**Screenshots**
<img width="1281" alt="Screen Shot 2019-10-02 at 12 02 42 PM" src="https://user-images.githubusercontent.com/55319/66061038-a7da9880-e50c-11e9-8c9a-b616388dcbb0.png">
![Screen Shot 2019-10-03 at 1 04 33 PM](https://user-images.githubusercontent.com/55319/66148338-aaa5be00-e5de-11e9-8a9f-ef27bcf68efe.png)

Deliverables:
- Make the error pages non-season specific
- Get the new versions in place

## QA STEPS

Verify the updated header for our error pages looks okay (no content/verbiage changes were made). 😃 
 * https://technovation-qa.herokuapp.com/500.html
 * https://technovation-qa.herokuapp.com/404.html
 * https://technovation-qa.herokuapp.com/422.html
 * https://technovation-qa.herokuapp.com/server_error.html

**Comment by shaunxp20** [comment]
This one is on the QA site, QA steps have been added as well! 👍 😃

**Comment by rsgonzal** [comment]
Pages look good!

**Comment by shaunxp20** [comment]
This one was deployed earlier today! 👍
