### ISSUE TITLE
Returning user onboarding [?,20,?]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2242]
Coming from #2229, we want to be proactive about the onboarding issue seen where a returning student was shown as fully onboarded in the admin despite not having a current parental consent. So this ticket has two parts:

* get clear on the program team's expectations for what returning mentors and students have to do to be considered onboarded
* make sure the platform will behave according to those expectations.

From the codebase, the following are the onboarding requirements for each:

## Mentor
* has an account
* email confirmed
* training complete or not required
* consent signed
* background check complete or not required
* bio not blank
* mentor type not blank

It appears to me that mentors who finished training last year **will not** be required to retake it this year unless we manually intervene.

For consent waivers, we currently have 12 nonvoid waivers so it appears that last year's consents **were** voided on Oct 1.

It's unclear to me if background checks expire, but I don't think so. I believe if they cleared it when signing up originally, they would not be required to have a new one run.

## Student
* has an account
* has signed parental consent for current year
* email confirmed
* has valid coordinates

It appears to me that the platform **does** require a new parental consent each season without us intervening to change that.

I believe the bug seen where a user was shown as onboarded in the admin without a parental consent was due to a sort of caching bug where they were onboarded last year, and we need to force a recalculation of that for this year.

**Comment by stenington** [comment]
I guess we should include judges too.

## Judges
* has an account
* email confirmed
* consent signed
* training completed
* survey completed

**Comment by stenington** [comment]
It looks like students and judges have a cached `onboarded` value, but mentors do not. Both are recalculated when their profiles are saved, so I believe we can trigger a recalculation in the job that registers them to the season, and manually trigger that recalculation for accounts that have already registered.

**Comment by rsgonzal** [comment]
What they should do again for 2020

Students
- Consent form

Mentors
- Consent form
- Training

Judges
- Consent form
- Training

**Comment by stenington** [comment]
I put a PR in staging that should be resetting a user's onboarded status when they are registered for the new season (so on first sign in after the season rollover for an existing account), and it should be resetting training for mentors and judges as well. The code that resets consent forms doesn't seem to be configured in staging the way it is in production, so I'll have to run that manually I believe. Parental consent forms should expire after 1 year on their own.

**Comment by stenington** [comment]
Might want a two-pronged approach here: figure out how to setup accounts in staging for testing, and also monitoring production accounts as registrations begin coming in.

**Comment by stenington** [comment]
I was thinking through how to handle `onboarded` for students and judges where the value is cached. It may be best to both
* do a bulk update on past accounts to set `onboarded = false`
* and trigger a recalculation on current accounts after deployment to correct any accounts that already slipped through

We also need to consider doing the bulk update on every season rollover (since the cached `onboarded` value only applies to the current season) or doing away with the caching altogether, since it's always going to be a catalyst for these types of issues. 

But for now, I'm hoping the bulk update, which would run on the largest number of accounts, wouldn't take too long and would help restore some sanity to how we would think about `onboarded`.

**Comment by stenington** [comment]
This is how I'm thinking about "resetting" for the new season:

**Student**
* cached `onboarded` value:
    * `StudentProfile.update_all(onboarded: false)`
    * `StudentProfile.current.find_each(&:save)` to trigger onboarded check for those already registered who might be ahead of the game
* parental consents: automatically voided when consent season doesn't match current season

**Mentors**
* consent waivers: 
    * voided by `reset_consents` scheduled task in production
    * in staging, run `ConsentWaiver.nonvoid.find_each(&:void!)` which will void even consents from this season, but that's okay in staging
* training
    * `MentorProfile.update_all(training_completed_at: nil)`, if we have any mentors on the site who already ran through the new training, they'll just have to jump to the end and click the link again

**Judges**
* cached `onboarded` value:
    * `JudgeProfile.update_all(onboarded: false)`
* consent waivers
    * same as Mentors
* training
    * `JudgeProfile.update_all(completed_training_at: nil)`

**Comment by stenington** [comment]
We could consider rolling some of these things into a rake task that gets run in place of `reset_consents` next year.

**Comment by stenington** [comment]
The above has all been run in staging. For QA, I think for each user type we should
* find an existing user registered for 2019 but NOT registered in 2020
* log in as them
* confirm they are required to do the necessary things based on their user type as specified above

That won't necessarily catch edge cases, but for that I think we'll have to keep an eye on production and react to what we see, if anything.

**Comment by rsgonzal** [comment]
@stenington would it matter if the user didn't do these things when they signed up for season 2019?

Checked multiple accounts though and they're all prompted for the right items.

For students, does the consent form get resent? Or do they have to enter a new email to trigger it? I think we had talked about this but don't remember what was said and I don't have access to the emails of the ones i tried.

**Comment by stenington** [comment]
Yeah, @rsgonzal it would matter, but it's hard to detect the ideal scenario. The ideal scenario would be finding 2019 users who haven't yet signed up for 2020 and making sure they were 100% onboarded for 2019, but that's trickier since the platform thinks about things largely in terms of the current season. If you want to try to identify users who were fully onboarded in 2019 to use for QA, we can get on a call or something and I can try to help you find such users by checking things in the database, I think. Otherwise, this seemed to me to be as close to full QA as we could reasonably get.

For students the parental consent form should get resent. You can check the Mandrill logs to see if the right emails got sent, although I'm guessing they didn't because the only emails I see today from staging were RA invitations I sent, so you probably caught a bug there.

**Comment by rsgonzal** [comment]
Ah ok! I think the first one is fine then, Nick checked multiple mentor and judge accounts and all looked to be the same. So unless no one was fully onboarded.. should be fine?

Hmm, it would still trigger it even if I was logging in as the student through the admin?

**Comment by stenington** [comment]
@rsgonzal It should. Can you make notes here about which accounts you used?

**Comment by rsgonzal** [comment]
Doing the students again.

Trying: 
- Thumbelina	Maxwell	katie+s15@iridescentlearning.org
parent email: katie+p1@iridescentlearning.org

Ok, this is interesting. My consent form is not checked, but it did let me request to join a team. This shouldn't be happening?

![uploads/fa702e20-bf9e-47a6-9018-a1d5a03d7e1b/Screen Shot 2019-10-10 at 1.58.02 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffa702e20-bf9e-47a6-9018-a1d5a03d7e1b%2FScreen+Shot+2019-10-10+at+1.58.02+PM.png)

![uploads/e133b63a-90c8-4aa6-bcfd-4faaf4ea1d7b/Screen Shot 2019-10-10 at 1.58.14 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe133b63a-90c8-4aa6-bcfd-4faaf4ea1d7b%2FScreen+Shot+2019-10-10+at+1.58.14+PM.png)

**Comment by rsgonzal** [comment]
Alli confirmed users can form teams without being onboarded

**Comment by rsgonzal** [comment]
for mentors,

I just checked Grumpy Cat (katie+m17@iridescentlearning.org) 
and there's no personal summary written, so wondering if that gets re-written too?
It's also the first tab it goes to, event though mentor training and consent aren't done

**Comment by rsgonzal** [comment]
Logged in as jessica+mentor@iridescentlearning.org
More convinced she was fully onboarded - the personal summary was saved.
Can confirm I can't join a team and i need to do consent form and training.

**Comment by stenington** [comment]
It looks like logging in as a student through the admin **does not** trigger season registration, so it wouldn't trigger sending the parental consent email.

**Comment by rsgonzal** [comment]
Ok! I can try to actually login

**Comment by stenington** [comment]
What I ended up doing was using the admin to edit the student's email address **and parent email address** to something I can check, then doing a password reset, which logs you in. At that point a welcome email should go to the student, and a parental consent should go to the parent.

**Comment by rsgonzal** [comment]
Thanks, Mike! Did this work? should I try doing something similar?

**Comment by stenington** [comment]
@rsgonzal Please try it, it would be great to get a second set of eyes on it

**Comment by rsgonzal** [comment]
I couldn't figure out how to reset the parent email from the admin, so I logged in as a student and changed it but then an email was triggered (not sure if this was the right way to do it)

But once I did log in as the student, another consent was sent to the parent anyways and I received the welcome to season 2020 email. So I think this is how it's supposed to work!
