### ISSUE TITLE
Epic: Change the judging rubric

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2245]
From #2225 

The work here is something like the following:

* Remove the `refer-to` paragraph in the `QuestionSection` app and the `referTo` data in each `judge/scores/sections/*.vue` app
* **Ideation**
    * add 1 question
    * change text on existing  3 questions
* **Technical**
    * add 2 questions
    * change text on existing 2 questions
    * (checklist removal handled by #2192)
* **Pitch**
    * remove 2 questions
    * change text on remaining 2 questions
* **Entrepreneurship**
    * change text on existing 4 questions
* **Overall**
    * remove 3 questions
    * change text on remaining 2 questions
* Update score calculation logic
* Identify and remove unreachable templates referencing old rubric fields
* Update/add specs

I believe that the rubric questions are defined in `app/models/questions.rb`, so the basic process for working with questions would be something like:
* update `questions.rb` appropriately
* update the `SubmissionScore` model, including migrations to add/remove fields as needed
* update the `ScoresController` to add/remove parameters as needed
* update RA printable scores
* update RA score details? (not sure if this is actually unreachable)

Because the score total is changing, we might consider checking the low score thresholds for junior and senior divisions as well (currently 19 and 23 respectively).

**Comment by stenington** [comment]
I'd probably split this one into just 3 tickets:
* Identify and remove unreachable templates referencing rubric fields
* Remove the `refer-to` paragraph, which shows up as help text in the judging screens
* Change the rubric and scoring calculation

The first item should be done before the third, to make the third easier. We could break down the rubric changes further, but I'm not sure that's valuable.

@rsgonzal Can you find out if anyone on the program team has an idea of what the low score threshold should be with the new score calculation? That threshold is used to flag scores for admin approval, so it's not crucial that we change it now, but if we don't we may find that more scores need our intervention when judging rolls around.

**Comment by rsgonzal** [comment]
@stenington talked to the program team. They want to keep the same percentage and change the low thresholds to 14 (junior) and 19 (senior).
