### ISSUE TITLE
Epic: Update 2020 certificate templates

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2249]
As part of #2229, 2019 certificate templates were copied to the 2020 directory. We will want to make sure these are updated appropriately before certificates are made available.

**Comment by rsgonzal** [comment]
Need a new pdf template from Audra. check with program team for deadline.

**Comment by hellafitz** [comment]
@devincdillon when will you need to issue certificates?

**Comment by devincdillon** [comment]
@ophelieh can you make a recommendation on the TG certificate dates? Thank you

Also, can you note that recommendation (or ensure it is correctly noted) on the master calendar https://docs.google.com/spreadsheets/d/1Mx3DlCT62cr_MZAl4C10FiWzaXxIIh4tszubmAMW18c/edit#gid=0

**Comment by ophelieh** [comment]
Hi all, we usually issue certificates once we announce the finalists in mid-June. We've had issues with certificates in the past - especially judges - so we will need extra time to make sure the right certificates are assigned. Mackenzie and Amy worked on that last year. 

Would mid-May be realistic to have that ready by?

**Comment by devincdillon** [comment]
Okay, this is an earlier date than I had originally projected.

On the admin, we have turning certificates "on" a week after judging closes. Judging closes June 12th, so I was planning June 19th for certificates on.

@hellafitz I'm unsure if you are just asking for a date where we "turn on certificates" in the admin, or if this is a more complicated question of - when does dev start working on getting the certificates ready for the user types.

**Comment by hellafitz** [comment]
Calendar says certificates should be available July 3rd. 

Process (generously, give a month):
- Certificate template content is confirmed by early June
- Dev updates template
- Mark all the semifinalists
- Dev Team runs a task to auto gen all the certificates
- Program Team makes any necessary adjustments (e.g. deleting and replacing certificates).
- Admin "turns on" certificates

**Comment by hellafitz** [comment]
Design Deliverables: 
- Certificates for participants (general participants, semifinalist)
- for Mentors (general participants)
- for RAs (??? @devincdillon to check)
- Judges (there 3 different certificates for different levels of judging*; this has been done by CET manually in the past; note: these certificates are NOT generated by the platform, CET emails Judges the right one)

* Certified Judge (5 scores)
Head Judge (5-10 scores)
Judge Advisor (10+ scores) | With this distinction, you will be listed on the Technovation website.

**Comment by stenington** [comment]
For TG, judge certificates are definitely generated by the platform. If that's not what CET wants this year, that will need to be changed.

**Comment by stenington** [comment]
These are the 2020 templates, copied from 2019, that need adjusting: https://github.com/Iridescent-CM/technovation-app/tree/fe413e64f8431c71fb96287ade839060eccddcec/lib/certs/2020

**Comment by devincdillon** [comment]
noting that there is an email chain that @rsgonzal is supporting on this. We have the templates, she is pulling for Audra which fields need to be editable and Audra will make those changes.

RAs - no certificates needed

**Comment by hellafitz** [comment]
Superseded by #2482
