### ISSUE TITLE
Registration closed page will need to be updated [8,3,2.67]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2251]
The "registration closed" page was updated to include a hardcoded date after it was discovered in #2229 that the season rollover and registration opening dates were assumed by the system to coincide. That page will either need to be updated periodically with the correct date, or a solution needs to be worked out that lets those two separate (but related) dates stay synchronized.

## QA Steps

 * The document to QA/verify against is here: https://docs.google.com/document/d/1mG9hnI972ohnyGz1rlcRNl1-swoVXCqSmOkZCSO0_aM/edit#

**Comment by hellafitz** [comment]
Students/Mentor reg closes March 16th 2020

**Comment by hellafitz** [comment]
options: update the date to say 2020, or something more (TBD)

**Comment by stenington** [comment]
This ticket is for an immediate fix by updating the hardcoded date.

**Comment by stenington** [comment]
Next steps: add a screenshot of the current page and get the new date or messaging from program team.

**Comment by rsgonzal** [comment]
Emailed the team for feedback on current page:

![]()

**Comment by rsgonzal** [comment]
Updated text can be found here: https://docs.google.com/document/d/1mG9hnI972ohnyGz1rlcRNl1-swoVXCqSmOkZCSO0_aM/edit#

**Comment by rsgonzal** [comment]
@shaunxp20 @stenington let me know if this doc makes sense!

**Comment by shaunxp20** [comment]
> @shaunxp20 @stenington let me know if this doc makes sense!

Yup, it's looking pretty good/straight-forward to me so far! 👍

**Comment by stenington** [comment]
Yep, works for me too

**Comment by shaunxp20** [comment]
This one is on staging. 😄

**Comment by devincdillon** [comment]
Looks great, folks!

**Comment by shaunxp20** [comment]
Thanks for testing this one @devincdillon! 🎉 🍰 🙌
