### ISSUE TITLE
Remove demo video from admin [3,3,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2253]
From #2191, remove the demo video from the admin:
* team submission details/edit page
* submissions page, "More columns"

**Admin/RA**
![Screen Shot 2019-09-05 at 10 26 03 AM](https://user-images.githubusercontent.com/55319/64355252-e133ed00-cfce-11e9-81e6-8350056aef11.png)
![Screen Shot 2019-09-05 at 10 44 49 AM](https://user-images.githubusercontent.com/55319/64355264-e2651a00-cfce-11e9-9b5a-00642b81dd09.png)

**Comment by stenington** [comment]
QA:

1. log in as an admin
2. look at a submission
3. edit the submission (change the pitch video url or something) and save
4. confirm that you're able to edit it, and that the demo video field didn't show when viewing or editing

1. log in as an RA
2. look at a submission
3. confirm that demo video is not part of the page

**Comment by ophelieh** [comment]
Tested as admin + RA - everything worked as expected.
