### ISSUE TITLE
Remove demo video from Student/Mentor UI [5,3,1.66]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2254]
From #2191, remove the demo video from the student/mentor UI:
* submission checklist
* submissions section
* published submission

**Student and Mentor**
![Screen Shot 2019-09-05 at 10 30 05 AM](https://user-images.githubusercontent.com/55319/64355253-e1cc8380-cfce-11e9-88e4-f6e980c41bc2.png)
![Screen Shot 2019-09-05 at 10 30 13 AM](https://user-images.githubusercontent.com/55319/64355255-e1cc8380-cfce-11e9-9f1d-90bbe4ff18b1.png)
![Screen Shot 2019-09-05 at 10 30 17 AM](https://user-images.githubusercontent.com/55319/64355257-e1cc8380-cfce-11e9-8efe-afd9d697e0dd.png)
![Screen Shot 2019-09-05 at 10 30 46 AM](https://user-images.githubusercontent.com/55319/64355258-e1cc8380-cfce-11e9-83ae-77b780c41406.png)
![Screen Shot 2019-09-05 at 10 41 30 AM](https://user-images.githubusercontent.com/55319/64355259-e1cc8380-cfce-11e9-8fc0-d8931587ec3f.png)

**Comment by stenington** [comment]
QA:

**As a student...**
1. log in as a student
2. start a submission, if you haven't already
3. go to **Dashboard**, confirm that the **Pitch** section does not say Demo video
4. click **Pitch**, confirm the screen has only Pitch video and Screenshot sections, not Demo video
5. Complete the submission and submit
6. View your completed submission, confirm that only the pitch video is shown on the submission preview page

**Comment by ophelieh** [comment]
Tested as a student and a mentor - everything works as expected while working on the submission and after submitting.
