### ISSUE TITLE
Remove demo video from Judge UI [5,3,1.6]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2255]
From #2191, remove the demo video from the judge UI:
* review submission section
* ideation section

**Judge**

![Screen Shot 2019-09-05 at 10 42 18 AM](https://user-images.githubusercontent.com/55319/64355261-e1cc8380-cfce-11e9-8916-fd3b1d8331b5.png)
![Screen Shot 2019-09-05 at 10 42 31 AM](https://user-images.githubusercontent.com/55319/64355262-e2651a00-cfce-11e9-9c02-9d0da222f901.png)

**Comment by stenington** [comment]
QA:

**With a judging round turned on in the admin, and judge-able submissions...**
1. log in as a judge
2. begin judging a submission
3. confirm the "Review submission" section no longer shows a demo video near the pitch video
4. confirm the "Ideation" section has only the pitch video, not a demo video

**Comment by ophelieh** [comment]
To validate judge training use this link - https://technovation-qa.herokuapp.com/judge/training_completion. Once you are on the judge profile, add this link and then refresh - it will mark the training as complete. :) 

Tested and worked as expected. I only saw the pitch video on the main submission page, the ideation and pitch page.
