### ISSUE TITLE
Demo video final clearout [8,5,1.6]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2256]
From #2191, after the other demo video tickets are complete, do a final clear out:
* migration to remove the field
* remove libraries or config no longer needed, if any
* remove rake tasks or other stray mentions, if any

**Comment by stenington** [comment]
This ticket made modifications to the team submissions table, and the submission scores table, so I think QA should be something like:

1. create a new student account
2. create a submission
3. make sure you can fill out the submission and submit without errors
4. as an admin, confirm the new submission shows as complete and submitted

1. as a judge, log in and judge a submission
2. pay special attention that the technical score calculates correctly

**Comment by nickiredescent** [comment]
Can confirm that the demo video is removed and everything else seems to work as intended.
 - Submission process went normally.
 - Can see the fully completed submission as an admin.
 - As a judge, the technical score seems to be correct/the demo video is not considered in the technical scoring.
