### ISSUE TITLE
Remove the checklist from the student/mentor UI [8,8,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2258]
From #2192, remove the checklist from the student/mentor UI:
* the checklist page
* the item on the submission checklist
* the submission section page
* the checklist display on the published submission page

![screencapture-localhost-3000-student-team-submission-sections-no-name-yet-by-all-star-team-2019-09-06-09_12_34](https://user-images.githubusercontent.com/55319/64431808-24529680-d089-11e9-89fc-75f9549c8d39.png)

![Screen Shot 2019-09-06 at 9 12 06 AM](https://user-images.githubusercontent.com/55319/64431535-a9897b80-d088-11e9-8b61-724cd1bcefbd.png)
![Screen Shot 2019-09-06 at 9 12 11 AM](https://user-images.githubusercontent.com/55319/64431537-a9897b80-d088-11e9-9a17-610165280da2.png)
![Screen Shot 2019-09-06 at 9 15 55 AM](https://user-images.githubusercontent.com/55319/64431539-aa221200-d088-11e9-841c-f1a97b08d4cc.png)

**Comment by stenington** [comment]
QA:

Do once as a student, and once as a mentor:

1. log in
2. begin a submission if necessary
3. referencing the screenshots above, confirm that the areas circled in orange have been removed from the interface
4. please report any other reference to the technical checklist or code checklist you come across as that user (RAs and admins may still need updating)

@rsgonzal seem okay?

**Comment by rsgonzal** [comment]
all looks good, don't see the code checklist as a student nor as a mentor.

**Comment by mdancho** [comment]
No code checklist when submitting/after submitting as a student or mentor.
