### ISSUE TITLE
Remove the checklist from the judge UI [5,3,1.67]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2259]
From #2192, remove the checklist from the judge UI:
* the score summary in the purple section
* the text summary in the Technical score section

![Screen Shot 2019-09-06 at 9 16 46 AM](https://user-images.githubusercontent.com/55319/64431540-aa221200-d088-11e9-9786-aa315b6856e7.png)
![Screen Shot 2019-09-06 at 9 21 40 AM](https://user-images.githubusercontent.com/55319/64431543-aa221200-d088-11e9-9453-f8ab2385e13a.png)

**Comment by stenington** [comment]
QA:

1. log in as a student and submit a project, if needed
2. log in as admin and set judging to QF
3. log in as a judge and score submission
4. attempt to give the submission a perfect score, making sure you're able to do so 
5. attempt to give the submission the minimum score, making sure you're able to do so (doing both of these helps ensure some score out of 10 isn't being added in, despite being "invisible")
6. refer to the screenshots above and confirm the circled areas no longer appear in the UI
7. report any other mentions of code checklist or technical checklist you see as a judge

@rsgonzal sound good?

**Comment by rsgonzal** [comment]
when i first finished scoring, it said 91
![Screen Shot 2019-12-09 at 8 50 47 PM](https://user-images.githubusercontent.com/22801026/70496862-110af900-1ac6-11ea-87db-0ca1d6a4044d.png)

Then when i reviewed my finished score it says 85
![Screen Shot 2019-12-09 at 8 51 53 PM](https://user-images.githubusercontent.com/22801026/70496870-18320700-1ac6-11ea-9527-6ea7893784ab.png)
![Screen Shot 2019-12-09 at 8 52 13 PM](https://user-images.githubusercontent.com/22801026/70496886-26802300-1ac6-11ea-80db-fa251294cbc4.png)

Looks like it's taking 5 from technical and undoing the second one
![Screen Shot 2019-12-09 at 8 52 37 PM](https://user-images.githubusercontent.com/22801026/70496903-3861c600-1ac6-11ea-990c-9619a5120ae8.png)

**Comment by rsgonzal** [comment]
Lowest scores

**Junior Team**
Some extra points are being added to the points in the original scoring
![Screen Shot 2019-12-09 at 11 57 56 PM](https://user-images.githubusercontent.com/22801026/70506915-33aa0b80-1ae0-11ea-8fd9-5761cd1d71f2.png)

score is closer when looking at my done scores but i think still off by 1
![Screen Shot 2019-12-09 at 11 58 29 PM](https://user-images.githubusercontent.com/22801026/70506992-56d4bb00-1ae0-11ea-9275-e43e50074766.png)

when i try to edit, the top bar is still in the 20s, same thing with the second technical score resetting
![Screen Shot 2019-12-09 at 11 58 18 PM](https://user-images.githubusercontent.com/22801026/70507046-6d7b1200-1ae0-11ea-8434-3e4ec277e26b.png)

I didn't get a senior team for the low score, but let me know if i should!

**Comment by stenington** [comment]
So what are the actual problems here? It looks like:

* mystery 1 point, exceeding max score: managed to assign score of 91/90 (senior)
* 5 points for technical question 2 won't save (junior & senior)
* low score math not adding up at all?

The second bullet is explained by #2320. Can you provide me with reproducible steps for the other two @rsgonzal?

**Comment by stenington** [comment]
I found a place where checklist points were still being added in to the score total, so a fix for that is going to staging now.

**Comment by ophelieh** [comment]
I confirm that I do not see anything related to the code checklist.

Low scoring: 
* I had missed entering one of the scores for the technical portion but it let me click "finish my score" and didn't show it as missing (it did show as missing the second time around). When I went back in and added that score, it showed it on the "review score" page but if I submit it and come back to that submission. It's gone again, see below. 

![image](https://user-images.githubusercontent.com/32206421/70549840-7b5d8100-1b3a-11ea-989e-318c154abdbc.png)
https://drive.google.com/file/d/1Ndo9S5_rglNebeo7Fa_ixrVHuSkfe7-L/view

* Score doesn't add up. The minimum score should be 14 but shows 24. 
![image](https://user-images.githubusercontent.com/32206421/70550280-22dab380-1b3b-11ea-88c4-8a9d633755e8.png)

**Comment by ophelieh** [comment]
Top Scoring - Junior Team

When I give all the max points, the math doesn't add up. It added 10 extra points for me. 
![image](https://user-images.githubusercontent.com/32206421/70550736-d9d72f00-1b3b-11ea-82e5-31ef4d16571e.png)

After I save it and go back to it, it deletes the 5 I gave in the technical part
![image](https://user-images.githubusercontent.com/32206421/70550875-12770880-1b3c-11ea-876f-30fde4f1d1f8.png)

**Comment by ophelieh** [comment]
**Low Score - Senior Team** 
On the technical part, it says 20 points instead of 10.
![image](https://user-images.githubusercontent.com/32206421/70553703-4acd1580-1b41-11ea-8670-9dd6a50cf7be.png). 


Scores add up correctly. But need to edit text for judging - should say May 25th.
![image](https://user-images.githubusercontent.com/32206421/70553939-bca55f00-1b41-11ea-8f94-ed3fdae5ef69.png)


**High Score - Senior Team** 
Score adds up to 90. But I have the same issue as previously, score in technical part deletes after saving. 
![image](https://user-images.githubusercontent.com/32206421/70554073-07bf7200-1b42-11ea-9fc0-743a02ff0a29.png)

**Random Score - Senior Team**
Score added up correctly BUT one of the scores in the technical part deletes after you save and come back to the submission.

**Comment by rsgonzal** [comment]
For the other two, do you mean these screens?

**Comment by rsgonzal** [comment]
fixed/ok:
- I changed the quarterfinals end date in config to 5/25
- the missing 5 points is addressed in #2320
- i don't see anything weird for the junior scores anymore, @ophelieh can you try again, please?

**Still need:**
- copy on technical section should say 10 points
![Screen Shot 2019-12-10 at 12 02 53 PM](https://user-images.githubusercontent.com/22801026/70564427-08a5d300-1b45-11ea-8a56-493eb05db93d.png)

**Comment by stenington** [comment]
Good catch, fix for the 20 points -> 10 points going to staging now when tests pass.

**Comment by mdancho** [comment]
Each section reflects the number of points shown next to the submission section on the top bar. However when I went to review the score after submitting it, the score I gave of 34 dropped to 33 because the second section of technical scoring deleted my score. 

<img width="720" alt="Screen Shot 2019-12-10 at 2 27 12 PM" src="https://user-images.githubusercontent.com/52216992/70574687-8378e900-1b59-11ea-9c12-591bb38e44e5.png">

**Comment by rsgonzal** [comment]
thanks, @mdancho !

We're addressing this in another ticket. I think this one is good to go!

**Comment by ophelieh** [comment]
Everything looks good to go! (Other than the missing 5 points which is addressed in #2320.)
