### ISSUE TITLE
Remove the checklist from the Admin/RA UI [8,3,2.67]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2260]
From #2192, remove the checklist from the admin/RA UI:
* remove from the submissions page
* remove from the submission detail page
* remove from the scores page
* remove from the score details page

![Screen Shot 2019-09-06 at 9 18 40 AM](https://user-images.githubusercontent.com/55319/64431541-aa221200-d088-11e9-840b-1ecfaaa09f62.png)
![Screen Shot 2019-09-06 at 9 18 50 AM](https://user-images.githubusercontent.com/55319/64431542-aa221200-d088-11e9-90f0-9a3326a4cec2.png)

![Screen Shot 2019-09-06 at 9 24 02 AM](https://user-images.githubusercontent.com/55319/64431544-aa221200-d088-11e9-9c7f-d21682176651.png)
![Screen Shot 2019-09-06 at 9 22 25 AM](https://user-images.githubusercontent.com/55319/64431545-aa221200-d088-11e9-818d-312453da268c.png)

**Comment by stenington** [comment]
RA printable scores included here as well.

**Comment by stenington** [comment]
QA steps:

**Admin**
1. Log in as an admin
2. Go to **Submissions**
3. Confirm that you can view a submission by clicking on the App name
4. Then go to **Scores**
5. For a submission with scores, click the "Read score details" icon
6. Confirm you can see the score summary page, then
7. Click "View score" next to one of the scores
8. Confirm you can view the score detail page and the **Technical** section doesn't show a checklist score


**RA**
1. As an admin, make sure **Content & Settings > Scores & Certificates > Scores & Certificates Accessible** is checked
2. Log in as an RA
3. Go to **Submissions**
4. Confirm that you can view a submission by clicking on the App name
5. Then go to **Scores**
6. For a submission with scores, click the "Read score details" icon
7. Confirm you can see the score summary page, then
8. Click "View score" next to one of the scores
9. Confirm you can view the score detail page and the **Technical** section doesn't show a checklist score
10. Go to **Events**
11. Click the "Print for live event" icon
12. Ensure the printable scores sheet does not have a checklist score

**Comment by nickiredescent** [comment]
Can form that as both an admin and as an RA, everything is working as expected and the code check list is no longer visible anywhere.

**Comment by rsgonzal** [comment]
Also looked around and everything looked correct. I was going to check things for semifinal scores and related screens but couldn't figure out how teams got thrown into that pool.. do you think anything would be different?

**Comment by stenington** [comment]
I think it's unlikely that semifinals scores would look different than quarterfinals. I don't recall seeing any way that they're rendered differently.
