### ISSUE TITLE
Checklist removal final sweep [8,8,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2261]
From #2192, do a final sweep on removing the checklist after the other tickets are done:
* migrations to remove things from the DB
* if any libraries or config can be remove, do so
* check for rake tasks or other stray mentions

**Comment by hellafitz** [comment]
@stenington if this wasn't completed, would it block us from accepting new submissions?

**Comment by stenington** [comment]
No, this shouldn't be a blocker on opening submissions. The only user-facing piece in this ticket that I found was about how scores are displayed to students at the end of the season.

**Comment by stenington** [comment]
QA context:

This ticket mainly removes code and templates relevant to the technical checklist that should no longer be in use anyway. I also found that the screen where students see their scores needed updating to not mention the checklist anymore.

Suggested QA:

Run through the process of creating a submission once more, and make sure you can throw together a submission and submit it as a student. If the site throws any errors along the way, report them. Otherwise we'll assume things are fine.

Also, check the student scores view by
1. turning on Scores and Certificates
2. log in as a student who submitted and received official scores
3. navigate to the scores screen and view your scores
4. make sure the technical checklist isn't mentioned and the score looks correct

**Comment by rsgonzal** [comment]
Everything is working as expected. No issues when creating a submission or viewing scores. Just the known error of the technical score not recording.

**Comment by stenington** [comment]
@rsgonzal Is this ready to deploy or have you asked someone else to take a look?

**Comment by nickiredescent** [comment]
If you need another test,
Same as Roxanna, things have worked like expected and I do not see the Technical checklist mentioned as a student.

**Comment by stenington** [comment]
Awesome, thanks @nickiredescent!
