### ISSUE TITLE
Remove unreachable judging rubric templates and code [8,8,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2262]
From #2245, remove unreachable templates and/or code referencing the judging rubric.

**Comment by stenington** [comment]
For this one, I removed some templates that had been for student score display from 2017. It appeared to me to be more of an archive than anything currently accessible. I also removed what appeared to be some old RA score screens.

Not sure what to suggest for QA here. I would say "make sure students see scores as they should" and "make sure RAs can see scores as they should" but I'm not totally clear on what "as they should" means in either case, so that might not be fair to put on someone else.

**Comment by ophelieh** [comment]
Hi all, 

So I checked as an RA and it looks like they get to see the rights scores: 
- Only see live event scores during judging
- See all scores (virtual and live) when judging is done and scores are made available 

For students, when I logged in as roxana+90@iridescentlearning.org (when scores/certificates are made available), I saw something that didn't add up. It says my score is 17/80 but the only score I see below adds to 0.

![image](https://user-images.githubusercontent.com/32206421/73301703-e0e3fa80-41d8-11ea-8843-8e07662e697b.png)

Also, I don't think this would be part of this ticket or certificates are even created at this point, but on the certificate tab, there was no button to download my certificate. 
![image](https://user-images.githubusercontent.com/32206421/73301835-24d6ff80-41d9-11ea-8d34-a622b1ca0659.png)
![image](https://user-images.githubusercontent.com/32206421/73301855-31f3ee80-41d9-11ea-922a-eb8eac3f3101.png)

**Comment by rsgonzal** [comment]
@stenington 

So when I look through the admin for this user, they have two scores, one incomplete but still not sure where 17 is coming from. This may be because of the jumping around of judges to virtual/RPE or turning on and off judging?


![]()

**Comment by rsgonzal** [comment]
This user sees two sets of scores
roxana+12@technovation.org

**Comment by stenington** [comment]
Hmm, well things like score averages are calculated and then stored separately so that we can do things like order by that column in the admin. When I look up roxana+90@iridescentlearning.org in the console, the associated submission does have a stored quarterfinals average of 17, despite the only complete quarterfinals score currently having a total of 0.

I'm guessing what happened is that when I deployed the rubric changes, all scores would have been reset to 0 because the old score fields were dropped and newly named score fields were added with a default of 0. A change like that in a migration would not have triggered the recalculation of things like average scores, so that's possibly why we're seeing this in staging. That said, I can't guarantee there isn't another way that these things might get out of sync, I don't feel confident enough about the codebase to say that.

Let me run something that will recalculate averages in staging, and then my recommendation would be to watch for this kind of discrepancy coming up again. We can talk about other ways to be more confident in the averages as well, but if you want to pursue that let's do it outside this ticket.

**Comment by rsgonzal** [comment]
Ah ok! That makes sense. Let me know if recalculation is done.

Yeah we can talk about that later. I think at some point I'd like to reset all scores and maybe have a cleaner simulation of how judging would go.

So I think we can mark this ticket as done?
