### ISSUE TITLE
Students should be allowed to enter a 2010 birthday

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2268]
**Describe the bug**
From Zendesk Ticket:
Platform doesn't have a 2010 option when selecting your birthday.
Kids born in 2010 will be 10 next year!
![uploads/6015252c-c3ac-43db-8c95-c89071e01fc5/Screen Shot 2019-10-14 at 12.35.46 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6015252c-c3ac-43db-8c95-c89071e01fc5%2FScreen+Shot+2019-10-14+at+12.35.46+AM.png)

**Comment by stenington** [comment]
From #2230

**Comment by stenington** [comment]
QA:

1. begin signing up as a student
2. select a birthday **after** August 1, 2010
3. you should not be allowed to sign up
4. change birthday to be just **before** August 1, 2010
5. you should be allowed to continue signing up

**Comment by rsgonzal** [comment]
Looks great! Picked a birthday after the 1st and was not allowed to sign up. Anything before and Aug 1st itself works.
