### ISSUE TITLE
"Onboarded mentors" filter not filtering correctly in admin [13?,?,?]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2269]
**Describe the bug**
The "Onboarded mentors" filter is not working in the admin.

**To Reproduce**
1. Log in as an admin
2. Click on 'Participants'
3. Select 'Onboarded Mentors: Yes, fully onboarded'
4. Click 'Search'
5. Click on 'view' on mentors until you find one that is not onboarded according to the details page

**Expected behavior**
I should only be seeing onboarded mentors.

**Comment by stenington** [comment]
This carries over from #2229 and #2242

**Comment by stenington** [comment]
I thought I replicated this before opening the ticket, but that may have been in my local environment which hasn't been reset like staging and production have. I can no longer replicate, although it's plausible that the `onboarded_mentors` query used to power the filter could get out of sync with `MentorProfile#onboarded?` when I run the following in production, I don't see any issue:

```
irb(main):009:0> Account.onboarded_mentors.find_each do |a|
irb(main):010:1*   puts a.mentor_profile.onboarded?
irb(main):011:1> end
```

**Comment by hellafitz** [comment]
Devin couldn't replicate today. Closing this until/if it resurfaces.
