### ISSUE TITLE
Epic: score deletion/restoration controls 

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2270]
The program team curates scores by having a developer delete and/or restore scores throughout the judging period. Admins on the platform currently have a limited ability to curate scores specifically flagged as problematic, but this could be expanded to all scores, as well as adding an ability to restore deleted scores.

**Comment by rsgonzal** [comment]
First step: writing scenarios that cause the problem and what level of control admins have

**Comment by stenington** [comment]
This ticket should be compared against #2272, #2274, and #2275. It falls into the same category of "stuff that's likely going to happen and currently takes more effort than it has to".

**Comment by stenington** [comment]
I believe at the moment, admins can **only** delete scores that end up in the suspicious scores list, but not all scores the team ends up wanting to curate fall into that list.

**Comment by stenington** [comment]
@rsgonzal flagging you for the above two comments

**Comment by stenington** [comment]
Oh, also worth mentioning here is that admins can choose to include deleted scores in a **Score export**, which we added last year because judges were reporting to us that their scores were disappearing. So exporting scores including deleted scores allows a program team member to see a spreadsheet of scores, and pinpoint which ones they may want to have restored. At that point they have to hand it over to a developer to do the restoration though.

**Comment by hellafitz** [comment]
#2368 is to prototype these controls

**Comment by hellafitz** [comment]
Closing this as work has wrapped on #2432, #2368, #2383, #2433, #2382.
