### ISSUE TITLE
Judge suspension control mockups (p4) (8,5,1.6)

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2272]
Give admins the ability to suspend/unsuspend a judge. Also give them the ability to leave a note about the suspension, as well as recording a timestamp as an audit trail.

**Comment by stenington** [comment]
I think this feature needs a little more fleshing out. 

What we have right now is that a developer can suspend a judge and the admin indicates a judge's status as suspended or not, but there's nowhere on the platform to record a timestamp or reason associated with a suspension. From a development point of view, it wouldn't be too hard to add a button and a text field that let an admin suspend/un-suspend a judge with a note and timestamp, but I wonder if a suspension audit trail should really keep a full history of a judge's suspensions to be maximally useful? That would take a little extra work.

**Comment by hellafitz** [comment]
Judge does does something that deserves a warning --> response: program team gives a warning. no platform implications.

Judge does something again --> 
response A: program team "suspends" the judge and their scores are deleted from the platform by Dev. [Q: is their entire account deleted?] 
response B: Alternately, the judge is "unconfirmed" and then is not matched with new teams. It's unknown whether "unconfirming" removes the judge's scores.

- consider scenarios where a suspended judge returns for a new season, or switches to a different program
- clarify if "suspension" is just deletion in different words

Next steps:
- answer the current state technical Qs
- work w/ Mackenzie and Nick to identify how they'd like this to work

**Comment by rsgonzal** [comment]
@rsgonzal schedule meeting with Mack and Nick

**Comment by rsgonzal** [comment]
- We tested what would happen if we deleted a judge - their score gets deleted, but they can make another account
- As far as having an audit trail for suspended/unsuspended judges, Nick and Mack don't think that needs to happen on the platform since they keep track of judge behavior in a spreadhseet - so this would be useful even without that

Unclear what happens when a judge does get suspended. Do they login and see a message?

**Comment by hellafitz** [comment]
Add a pop-up confirmation box with something like 'Are you sure you want to do this? Make sure to log this decision in the Judge Suspension spreadsheet [or whatever it's called]" Yes, I'm sure / No, cancel

**Comment by hellafitz** [comment]
Deliverable: mock-up a v1 proposed solution and gather feedback on acceptability and value from the program team end users. Create an implementation ticket as well.

**Comment by stenington** [comment]
This is what I'm seeing as a suspended judge locally. My dashboard looks normal, but I can't start a score:

<img width="1280" alt="Screen Shot 2020-02-27 at 5 24 57 PM" src="https://user-images.githubusercontent.com/55319/75492618-2b969500-5986-11ea-921e-3df79eeb15e8.png">
<img width="1280" alt="Screen Shot 2020-02-27 at 5 25 01 PM" src="https://user-images.githubusercontent.com/55319/75492616-2afdfe80-5986-11ea-818e-c019ca0f3bc9.png">

**Comment by stenington** [comment]
## Proposed changes

Looking at an **unsuspended judge** account, the new section would be the **Judge suspension** section. It could have help text, and a button to **Suspend this judge**. I've made the button the app's "danger" color since suspended or unsuspending a judge has potentially serious repercussions.

<img width="1280" alt="Screen Shot 2020-02-27 at 5 28 36 PM" src="https://user-images.githubusercontent.com/55319/75492901-bc6d7080-5986-11ea-826e-4d0dc317c3c7.png">

Clicking the button brings up the standard "Are you sure" type dialog, which we would have a custom message for. The text of the two buttons is standard, so the message needs to be phrased in such a way that the button text makes sense.

<img width="1280" alt="Screen Shot 2020-02-27 at 5 28 42 PM" src="https://user-images.githubusercontent.com/55319/75492905-be373400-5986-11ea-9412-2ad7c8e46b0a.png">

Confirming the suspension would tale you to the same page, with a confirmation message.

<img width="1280" alt="Screen Shot 2020-02-27 at 5 36 01 PM" src="https://user-images.githubusercontent.com/55319/75493406-c80d6700-5987-11ea-8194-a5afc0d42095.png">


Looking at a **suspended judge** account, it would look similar. The button would say "Unsuspend this judge", and could arguably be a different color to better differentiate the actions, although I think unsuspending is still an action with potentially serious repercussions, so maybe the "danger" color is fine.

<img width="1280" alt="Screen Shot 2020-02-27 at 5 28 10 PM" src="https://user-images.githubusercontent.com/55319/75493200-5cc39500-5987-11ea-8263-eefdc15eb522.png">

Clicking the button brings up the same style confirmation.

<img width="1280" alt="Screen Shot 2020-02-27 at 5 28 14 PM" src="https://user-images.githubusercontent.com/55319/75493219-66e59380-5987-11ea-80a8-08c2a8c07738.png">

Confirming the action would take you to the same page, with a confirmation message. 

<img width="1280" alt="Screen Shot 2020-02-27 at 5 38 48 PM" src="https://user-images.githubusercontent.com/55319/75493523-0b67d580-5988-11ea-84d8-f9f31871592f.png">

**Comment by stenington** [comment]
Handing this over to you @rsgonzal.

**Comment by rsgonzal** [comment]
@stenington team likes this! They just want to adjust the messaging that suspended judges see so that they don't try to contact us. 

Do we need them to come up with messaging for the pop up?

**Comment by stenington** [comment]
The pattern elsewhere in the admin is that the pop message says what they are about to do, e.g. "You are about to DELETE this score" or "You are about to CONFIRM this score" for the suspicious score controls. So I would propose 
* "You are about to SUSPEND this judge" and 
* "You are about to ENABLE this suspended judge" 

or something like that? I think "enable" instead of "unsuspend" may be better wording on the button too.

The part where I need guidance is the text that in the mock ups reads 
> Potentially some text here about suspension or unsuspension procedures, like logging it in a spreadsheet.

I'm not sure what the procedures are and what would be an appropriate reminder, without getting so specific that we might have to change it a lot if/when procedures change.

**Comment by rsgonzal** [comment]
Ah perfect. Suspend/enable work for me.

For the other text, let's go with:
"Suspending a judge means their scores will be deleted, please note on TG 2020 Judge Suspension sheet."

**Comment by stenington** [comment]
@rsgonzal Are you certain that's true? My memory is that suspension prevented them from continuing to judge, but their scores had to be manually removed if that's what we wanted. I just don't want to mislead admins into thinking it's automatic, unless I'm the one mis-remembering and it is in fact automatic. Let me try it locally and see.

**Comment by stenington** [comment]
Yeah, locally I created a score then suspended that judge. Their score still appeared as an official score on the submission I had previously scored.

**Comment by rsgonzal** [comment]
😞 Not positive! I was thinking about when a judge is deleted. Thanks for checking!

**Comment by stenington** [comment]
I'd recommend something more like
> Suspending a judge does not mean that their scores will be deleted, but they will not be able to create new ones. Please note any changes you make here in the appropriate tracking sheet.

If you think giving the actual sheet name that's fine, just trying to minimize things that have to be updated.

**Comment by rsgonzal** [comment]
THIS IS PERFECT.

Thanks, Mike. Let's go with your recommendation.

**Comment by stenington** [comment]
Oh, final question @rsgonzal: what do they want the current "Your judge account has been suspended. If you have any questions..." text to say? Just "Your judge account has been suspended." maybe, with nothing further?
