### ISSUE TITLE
Bug: Background jobs can fail opaquely [5,8,0.63]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2273]
From #2063, when background jobs don't complete, it's pretty opaque to the admin what might have happened. I think even detecting whether a job is long-running or has already failed is difficult to do. This could be improved upon.

**Comment by stenington** [comment]
This one should also maybe be compared against #2272, #2274, and #2275.

**Comment by stenington** [comment]
@rsgonzal sorry, keep forgetting to tag you

**Comment by stenington** [comment]
#2421 was proposing a rake task to make fixing this for individual users easier, or maybe something that could be run periodically to clear up stuck jobs, but it seems like that kind of solution might not be possible with the limitations of ActiveJobs.

**Comment by hellafitz** [comment]
We expect two relevant crunch times for exports/reports: by RAs around the submission deadline (imminent) and by our staff during Judging. 

Deliverable for this ticket, answer: 
- Is there a catch-all we can install for when jobs fails, or does it need to be addressed on a case by case basis. 
- If that's the case, which jobs have error handling currently and which don't?
- Create implementation ticket(s) for next steps
