### ISSUE TITLE
X Selectively allowing late edits (p3)

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2274]
After submissions close, we receive support requests about teams that encountered technical trouble and weren't able to do things like upload their screenshots or team photos. Admins *do not* have the ability to do this through the admin, and it's complicated to do it from the console. We should make it easy for admins to make these sorts of late edits at a minimum.

**Comment by stenington** [comment]
I think step 1 here is outlining which pieces of a submission are un-editable by an admin as things stand. Some fields can be changed, but I know that screenshots cannot be uploaded easily by an admin on behalf of a team, and I believe team photos can be edited only by logging in as a user on the team. (That trick doesn't work for screenshots when submissions close.)

I'm not actually sure if there's some extra difficulty in making these things editable by an admin. The team photo has an extra confirmation page when a student uploads a photo that I don't have much context for, but seems to indicate that there is some potential difficulty users encounter when uploading images. So the second step would be doing a short spike to understand image uploads better on the site.

**Comment by hellafitz** [comment]
@rsgonzal to check which pieces of a submission are editable by an admin

**Comment by rsgonzal** [comment]
@stenington looks like these are the pieces an admin can edit:
![screencapture-technovation-qa-herokuapp-admin-team-submissions-coolest-app-by-tean-edit-2020-02-24-19_13_07](https://user-images.githubusercontent.com/22801026/75212643-660cf180-573c-11ea-8f0c-f4bc00eb8182.png)

**Comment by hellafitz** [comment]
Program Team indicated they will not allow screenshot edits after submissions close this season. This rule being applied more stringently means that admins have all the post-submission edit access they might need.
