### ISSUE TITLE
Change low score thresholds [8,3,2.67]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2276]
From #2245, change the low score thresholds to 14 (junior) and 19 (senior).

**Comment by hellafitz** [comment]
Needs to be in place before judging starts

**Comment by stenington** [comment]
This needs to happen after the rubric is changed in #2264, because that's the change that motivates adjusting these thresholds.

**Comment by stenington** [comment]
QA:

### Score too low
1. make sure at least 1 junior submission and 1 senior submission are available for judging
2. log in as a judge
3. score both submissions, giving <14 to the junior and <19 to the senior
4. log in as admin
5. go to **Scores**
6. confirm that both scores appear at the top in **Suspicious Scores**, flagged as "Seems too low"

### Score just high enough (optional)
1. make sure at least 1 junior submission and 1 senior submission are available for judging
2. log in as a judge
3. score both submissions, giving 14 to the junior and 19 to the senior
4. log in as admin
5. go to **Scores**
6. confirm that neither score appears at the top in **Suspicious Scores**

**Comment by nickiredescent** [comment]
Tested both scenarios and it works as described.
The score <14 for juniors and the one <19 for seniors did get flagged as "Seems too low".
Editing this score as a judge to be 14 and 19 respectively removed the "Seems too low" tag. (The senior one was still flagged for being "Completed too fast".)

**Comment by rsgonzal** [comment]
Rebecca and I also checked this one. Everything works as expected.
