### ISSUE TITLE
Remove past year submissions and scores from the platform [20,8,2.5]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2279]
From #2187, we've archived off old data as necessary and we're ready to actually remove data on production prior to doing our #2191 and #2192 epics.

We're talking about removing submissions (including business plans, pitch presentations, screenshots, and technical checklists) and removing past scores as well. It probably makes sense to do this on both staging and production.

There might be a communication piece with RAs too?

**Comment by stenington** [comment]
Step 1 here is for @rsgonzal to arrange a communications piece. The proposed plan is to let RAs know that we'll be removing this data on or after Friday, 11/22, so that would be their deadline for downloading anything they might want from the platform. **This will hold up deployments until 11/22** although we can continue to move tickets into Test. 

Step 2 is then to do the data removal. A specific plan for that will be forthcoming.

**Comment by rsgonzal** [comment]
I've communicated with the program team. They will be sending out an email tomorrow (or soon). No complaints about the deadline so far.

**Comment by stenington** [comment]
It looks like `SubmissionScore.past.destroy_all` first, then `TeamSubmission.past.destroy_all` second will also remove screenshots and technical checklists. Not yet sure about business plans and pitch presentations, although it seems like we would be able to empty out those tables since all past submissions would be gone and current submissions aren't yet allowed.

**Comment by stenington** [comment]
@devincdillon I'll check in with you on Friday 11/22 to see if we're clear to do these data deletions the following week.

**Comment by stenington** [comment]
Question from an RA:
> When we download the submissions it gives us links to files. Will these links still work after submissions are removed from the platform?

**Comment by stenington** [comment]
It does not appear that deleting a submission from the platform will delete the associated files stored in S3, those file links will continue to work until we address them specifically.

**Comment by stenington** [comment]
Turns out the above two commands are insufficient with production data, working out a more robust plan now.
