### ISSUE TITLE
Allow staff to find submissions that need publishing and publish

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2280]
Mentioned in #2133, last year there were several teams who thought they were done but never took the final step of publishing their submission. To fix that we might want to give admins the ability to find and publish these submissions on behalf of the team. We could add a column to Submissions for `only_needs_to_submit?` and possibly add controls to allow admins to publish on behalf of users, or rely on logging in as one of the users to do it. That would give admins a way to do this that didn't rely on a developer intervening.

**Comment by stenington** [comment]
Changing from "admin" to "staff" in the title. @ophelieh was concerned about too many people having this power, but we do need someone to have it, whether that's a software developer or someone else. This ticket should detail a solution for someone in the org being able to handle this situation when it arises.

**Comment by rsgonzal** [comment]
update: only_needs_to_submit column has been added

This ticket is still open to create a plan for the second comment

**Comment by stenington** [comment]
This one should also be compared against #2272, #2274, and #2275. @rsgonzal

**Comment by stenington** [comment]
Closing this in favor of #2363
