### ISSUE TITLE
Change slack link in mentor welcome email [5,2,2.5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2285]
The current link is incorrect.

Mackenzie sent new link: https://join.slack.com/t/technovationmentors/shared_invite/enQtMzE1MzIwMjAxNzY2LWEzNzI5ODkxODI3M2QzMjA2NmU2OGUxYzI4M2FkNjM4MzQ5NzU0MjVkN2MyZTkxZWYxNjI1MDg1ODI1MTVhNDE

Timeline: Thanksgiving

**Comment by stenington** [comment]
The PR for this would let us set the link through config, `MENTOR_SLACK_SIGNUP_URL`, so link changes in the future could be done without code deployment.

**Comment by stenington** [comment]
QA: sign up as a mentor, ensure the link in the email is the same provided above

**Comment by mdancho** [comment]
QA'd and the link is working. Thank you!!

**Comment by rsgonzal** [comment]
Checked as well and seems to be working, yay!
