### ISSUE TITLE
Set up a staging site for Technovation.org

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2286]
Marketing would like to set up a staging site by EOY, but is a nice to have.

**Comment by stenington** [comment]
http://techstage19.wpengine.com/ already exists, although it's currently password protected. Ask me on Slack for credentials.

WPEngine changed how they offer staging environments, so the way our team is used to doing it is considered "legacy staging". The environment linked above is the new way of setting up staging, so part of this ticket may be helping the team get oriented to the differences?

**Comment by stenington** [comment]
This is a good article to start with to understand the new vs. legacy staging systems: https://wpengine.com/support/staging-environments-1-click-staging-different/

**Comment by stenington** [comment]
Also if nobody objects, I'll remove the password protection on staging. I believe that was put up to hide things prior to launching the rebrand.

**Comment by stenington** [comment]
I should also say if there's a strong preference for a legacy staging site, we can try to set that up. WPEngine will be moving away from it eventually, but I don't know how fast that timeline is so we may be able to use legacy staging for a while yet.

**Comment by stenington** [comment]
@mjaris Let us know here if you feel the new style of staging site will suit your needs. Thanks!

**Comment by mjaris** [comment]
Yes, the new style of staging site will work -- no need to create a legacy-style staging site!
