### ISSUE TITLE
x Spike: Update styles used in curiositymachine/templates/deprecated_base.html to newer sass files 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#2288]
Split from #2186 - clean up technical debt on TF site by updating styles used in curiositymachine/templates/deprecated_base.html to use the new sass files.

**Comment by Allicolyer** [comment]
Goal: Combine both sets of stylesheets so that they compile into the same base.css file that is used through the entire site.

Steps to accomplish this:
1. Migrate the .less files to .sass files
2. Compile a new `main.css` from the migrated Sass files
3. Match the variables names in both sets of Sass files
4. Reference the newer variables for both sets of Sass files
5. Find a way to look  for duplicate class and id names between sets of Sass files
5. TBD

**Comment by Allicolyer** [comment]
Files that use the depreciated template:  curiositymachine/templates/deprecated_base.html


**General Layout**: challenges/templates/challenges/edp/layout.html

**Plan**
* General Template
    * challenges/templates/challenges/edp/plan.html
* Preview
    * challenges/templates/challenges/edp/preview/plan.html
* In Progress
    * challenges/templates/challenges/edp/progress/family/plan.html
    * challenges/templates/challenges/edp/progress/student/plan.html

**Build** 

* General Template
   * challenges/templates/challenges/edp/build.html
* Preview
    * challenges/templates/challenges/edp/preview/build.html
* In Progress
    * challenges/templates/challenges/edp/progress/family/build.html
    * challenges/templates/challenges/edp/progress/student/build.html

**Reflect**
* General Template
   * challenges/templates/challenges/edp/reflect.html
* Preview:
    * challenges/templates/challenges/edp/preview/reflect.html
* In Progress:
    * challenges/templates/challenges/edp/progress/family/reflect.html
    * challenges/templates/challenges/edp/progress/student/reflect.html

**Modals**
*challenges/templates/challenges/edp/_guide.html
*challenges/templates/challenges/edp/_nav.html

**Comment by Allicolyer** [comment]
So I'm starting to think that rebuilding these templates would be better. There are many unused classes in the less files, and it's hard to tell which ones come from bootstrap and which ones are custom since they are all mixed in together. I think combing through these templates and rebuilding them will help reduce error and also allow us to remove unused code.

**Comment by Allicolyer** [comment]
I think this might work for each page:
1. Create a new template using the new base
2. Migrate each part over from the old template udapting old boostrap 3 convetions. For each custom class and id, find the relevant code in the .less file and migrate it to a new sass file that compiles into `base.css`.

**Comment by hellafitz** [comment]
@Allicolyer is this ticket still relevant or can it be closed?

**Comment by Allicolyer** [comment]
I'm not sure! I'm still working on this but I'm not sure if anyone needs this ticket anymore

**Comment by hellafitz** [comment]
@Allicolyer still need this one? If not please go ahead and close it after adding an "X " to the beginning of the ticket name (that tells us we didn't include it in a formal iteration).

**Comment by Allicolyer** [comment]
I don't think this is a high priority.
