### ISSUE TITLE
Update textacular dependency

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2297]
From #2292, we want to get the textacular dependency off of our fork and back onto the main repository.

Textacular is a library that has to do with full text search in Postgres, so that will be where we need to focus testing.

**Comment by stenington** [comment]
The textacular library seems to power the name/email search in the admin for participants, judges, and teams. 

For QA, I would suggest targeting those three search fields, and trying a variety of things, e.g.
* search only by name/email
* search by name/email with other filters as well
* sort your search results by different columns
* export your search results

You can give feedback about the quality of the search if you want, but I believe all you need to look for is the site completely blowing up when you do one of the above searches. If you report back something like "I searched for 'team' and My Team didn't show up, what gives?" I think we would carve that off as a feature request, unless you can demonstrate that production handles an equivalent search more effectively than staging.

**Comment by ophelieh** [comment]
**Participants**: Search is quick and works as expected. I tried searching by name, email, filtering results, adding more columns, and exporting. 

**Judges**: 
* Love the season filtering option!! 
* Looks like the live judge filter for the previous season might not be working as all events are reset season to season.  It said there were 0 live judges, but from what I remember we had a few judges that were only live judges. Or did all judges turn to virtual judges once they judge in the second round? 

**Teams**: I was playing around with ThisTeam:potato:
* When I searched for 'potato', it popped up
![image](https://user-images.githubusercontent.com/32206421/69190440-0c19e180-0ae6-11ea-8e46-59a3e01a486c.png)

* When I search for 'this' or 'This'- it showed 0 results 
![image](https://user-images.githubusercontent.com/32206421/69190417-fe645c00-0ae5-11ea-8e2e-5bee7da7016a.png)
* When I search 'team' - it showed various teams, but not the one I was looking for
![image](https://user-images.githubusercontent.com/32206421/69190533-34a1db80-0ae6-11ea-9ba7-c4151a0cdbe9.png)

You mentioned a feature request @stenington , should I add this to the list?

**Comment by stenington** [comment]
@ophelieh I'm not too surprised that the live event filter doesn't work for past seasons, many filters only work correctly for the current season, unfortunately. #1739 is another example of that problem.

Yes, please feel free to add improving text search to the platform features spreadsheet. The way it works right now is that you have to type something like 30% of the thing being matched, so `this` will not match `ThisTeam:potato:` but `thiste` is enough to make the match. That's the default behavior of the library.

**Comment by mdancho** [comment]
The participants search correctly found students, mentors, and judges by name and email and filtered and exported successfully.  

**Judges:** I was able to search by name and email from this season and last season from the participant tab. However, when searching from the judging tab I was unable to generate a list without the site breaking and showing the  "oops something went wrong" page. Additionally, I tried to explore adding a judge to a live site, but don't see a way for an admin to easily do this. 

**Teams:** The team search and added columns worked for me so long as I typed the full name in the search area. Export was successful.

**Comment by stenington** [comment]
@mdancho Can you get staging to give you the error page again and tell me what to do to reproduce that problem? I think I need to fix that.

**Comment by mdancho** [comment]
@stenington 
1. click the judge tab
2. enter judge name in the name or email field 
3. click search 
4. page show the following
<img width="800" alt="Screen Shot 2019-11-20 at 1 15 21 PM" src="https://user-images.githubusercontent.com/52216992/69278774-d33a4500-0b97-11ea-8bbd-c3e4fa26e6b5.png">

**Comment by stenington** [comment]
Thanks @mdancho!

**Comment by stenington** [comment]
Ok, so updating this library did reintroduce the bug that caused us to fork in the first place. I guess we can either:

1. maintain a fork with the change we need,
2. try to get the patch we're using (or something similar) accepted into the main repo, or
3. stop using textacular to power search, at least on the problematic judges screen

**Comment by ophelieh** [comment]
Added a feature request regarding the search feature. 

Regarding filters not working for past season, is there a way to fix that or at least add some text under about which filters only work for the current season? 

Finally, regarding the bug Mackenzie found, which option do you recommend going with @stenington ?

**Comment by stenington** [comment]
@ophelieh I'll bring both of these things to @hellafitz & @rsgonzal and see how they want to handle it.

**Comment by stenington** [comment]
@ophelieh I think fixing filters to work with past seasons or adding text to the admin to signal where they won't work should also go on the feature request spreadsheet, with a link back to this ticket, please.

**Comment by stenington** [comment]
Also, for now I'll go back to the forked project and try to update our fork to get Rails 5.2 support so we can move on with our security upgrades in the short term. That maybe buys us some time to figure out a long-term solution later.

**Comment by stenington** [comment]
This change has been backed out, and the Judges Name or Email field is working again on staging.

**Comment by ophelieh** [comment]
Hi @stenington I will add the filter request to the sheet.
