### ISSUE TITLE
Update simple_form dependency

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2298]
From #2292, we want to get the simple_form dependency off of our fork and back onto the main repository.

It looks like we were on a branch for Rails 5.1 compatibility, presumably before that branch had been merged to the main project. It looks like the main project has compatibility through 5.2 now, so this shouldn't be too difficult.

**Comment by stenington** [comment]
`simple_form` is a library powering some of the forms throughout the platform. These forms seem to be powered by this library:
* editing a team submission as an admin
* the mentor background check form
* the consent waiver form
* ~~the mentor profile form for a judge creating their mentor profile~~
* mentor profile bio form
* the parental consent form
* the password reset form
* the password edit form shown if there are errors when changing it, and email wasn't changed
* another password reset form?
* password change form
* RA introduction form
* RA judge assignment form
* RA message form
* RA signup form
* the sign in form
* ~~old sign up forms~~
* student form for sending parental consent
* team member invite form
* ~~code checklist form~~
* team name form?

I'm not 100% certain all of these forms are still accessible, I believe some of them are no longer actually used. 

It's probably unreasonable to expect that all of these forms would get QA'd, but I'd say if we can do a handful of activities on staging that touch at least a few of these forms and no errors come up, that's better than nothing!

**Comment by mdancho** [comment]
1. Edit team submission is accurate/functioning  
2. The mentor background check auto-populated my account information and looks accurate when submitting
3. Form for consent is accurate/functioning
4. Form for mentor bio is accurate/functioning 
5. Changing the password form is accurate/functioning
5. If password is less than 8 character minimum, you are re-directed to a new change password form which is accurate/functioning. 
7. Changing the email using the new password works

**Comment by stenington** [comment]
Awesome, thanks @mdancho!

**Comment by nickiredescent** [comment]
Handful of tests. Not really sure what a "form" is supposed to be, but the following processes seemed to have worked fine for me/didn't notice anything unusual:
 - editing a team submission as an admin
**Working**
- the parental consent form
**Working**
- password change form
**Working**
 - the password edit form shown if there are errors when changing it, and email wasn't changed
**Working**
- RA introduction form
**Working**
- RA signup form
**Working**
 - team name form?
**Working**

**Comment by stenington** [comment]
Oh, sorry for the lingo @nickiredescent. The pattern of presenting a user with a series of fields to fill out and a submit button to click when they're done is often called "form submission" or "form processing", even if you're just filling out a new password or something. 

Thanks for testing, I think the list of things you did above should be good!

**Comment by ophelieh** [comment]
Do you need someone else to test @stenington? Sorry never got to that one...

**Comment by stenington** [comment]
I think this one's okay, thanks @ophelieh!
