### ISSUE TITLE
Update country_state_select dependency

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2301]
From #2292, we want to get the country_state_select dependency off of our fork and back onto the main repository.

**Comment by stenington** [comment]
This library seems to power the admin pages where you're able to pick a country out of a dropdown. It provides that list of countries. I guess QA here is to make sure you can still filter by country in the admin where a Country filter is provided, and that it populates with a reasonable list of countries.

**Comment by ophelieh** [comment]
Works as expected on participants, teams, submissions, events, scores, and judges tabs.

**Comment by mdancho** [comment]
Confirming the country filter worked for students, mentors, judges, teams, submissions, and events.
