### ISSUE TITLE
Epic: RA/admin cities listed in filter don't include all cities users have entered

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2313]
**Describe the bug**
For example, we have users in Saint Clements, Ontario, Canada, but filtering by Canada and then Ontario leaves you with a city drop down that does **not** include Saint Clements. This is a strange user experience for RAs. 

**To Reproduce**
1. On production, log in as admin
2. Go to **Participants**
3. Select **Canada** under Country and click Search
4. Select **Ontario** under State/Province and click Search 
5. You can see Saint Clements in the result set, but it's not available in the **City** field

**Expected behavior**
You would think all cities users have entered would be available in the filter.

**Comment by hellafitz** [comment]
Workaround: RA exports their student list and sorts by city.

Apparently we're using a static list of 'all cities in the world' that isn't actually all cities in the world.

**Comment by hellafitz** [comment]
Does an RA want to be able to filter by cities where they don't have any participants (and get 0 results), or should cities with 0 participants not be a filter option?

**Comment by rsgonzal** [comment]
Options:
- leave as is
- grab cities out of database
- take static list and update it with cities entered from users in our system
- completely change the way we do this

Could there be an updated static list? Yes, but it still may not include very small towns.
- there might be some technical debt preventing us from updating
- Mike needs to do some investigating, @stenington create spike ticket

How many other cities aren't on the list but appear in database?

**Comment by hellafitz** [comment]
Spike ticket is #2455

**Comment by hellafitz** [comment]
Continued in... 
Spike: location data process #2536, which leads into Spike: options for static location datasources [20,20,1] #2618

#2536 suggests the following next steps, of which #2618 is the second.
"Next Steps:
discussion of macro approach (now or later) [Team Time? NOT DONE]
spike 1: find the static datasource for options to select from (concern: may degrade the UX) [DONE, this is #2618]
spike 2: services we could put behind geocoder (Q: is the service consistent in how it looks at the world?) NOT DONE
spike 3, if needed: lat/long geolocation stuff (libraries, how to work through admin, etc); Q: how would we group users by US state and country if using lat/long? NOT DONE
spikes 2 & 3 need some refinement"

**Comment by dboyer** [comment]
The remaining work will be accommodated under #2990
