### ISSUE TITLE
Theme: understanding RPE status freeze

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2315]
Our April 2020 plan says

> 10 EST - Program work with Mike checking on the admin about how many teams (fully submitted vs not) / event - to determine official and unofficial. This is when event is frozen

The point of this ticket is to make sure we understand the program team's plan and that we're able to support it with either platform features or developer tools.

**Comment by stenington** [comment]
Exploratory QA led by @rsgonzal should be providing some answers here.

**Comment by hellafitz** [comment]
@rsgonzal to update

**Comment by rsgonzal** [comment]
- RAs can create events at any time
- Events are automatically official
- Admin goes in and marks events as unofficial

Right now the plan is to communicate these dates and hope that people respect them, but things can still happen in the admin.

I think Ideally, there is a: 
- timeframe for when RAs are allowed to create events
- timeframe for when teams can join events (we open up events for teams to join, but if we close that students who have joined one can't see their events coming up)

**Comment by rsgonzal** [comment]
Tickets/potential tickets to come out of conversations around RPEs
- Add messaging to the RPE page when a student is joining an event #2376
- Show official/unofficial event status to students #2377
- Show official/unofficial event status to RAs #2378
- Don't allow RAs to add or delete students after a certain date (what about judges?)
- don't allow RAs to create an event after a certain date or add a time stamp of when event was creaated for admin to see
- Allow students & judges to leave an event
- Mentors not on teams being able to see RPEs (considered might be useful for corporate mentors) - maybe giving them potential to see events but not join them necessarily

Following up with program team

**Comment by rsgonzal** [comment]
After discussing with the team. They thought these additional tickets were nice to have, but could live without
Don't allow RAs to add or delete students after a certain date #2390
Don't allow RAs to create an event after a certain date or add a time stamp of when event was created for admin to see #2391
