### ISSUE TITLE
Upgrade yarn dependencies [8,13,0.62]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2317]
Another step forward on #2166 would be to upgrade our `yarn` dependencies, especially those mentioned in security alerts, and see if tests pass and QA looks good.

**Comment by stenington** [comment]
Some yarn dependencies have been upgraded, and we're down to 1 page of security notices instead of 2 at least.

**Comment by stenington** [comment]
It looks like `rails/webpacker` is the root for many of the additional dependencies in the tree, and it's now on the most recent 3.* available. There is, however, a 4.* version that we will have to upgrade to eventually, I assume.

**Comment by stenington** [comment]
Moving this to test because there are changes in staging that need testing, even though there are also more dependencies that could be upgraded.

**Comment by stenington** [comment]
QA: It would be good to generally test that our Vue apps aren't horribly broken, so testing that you can still judge a submission would do that, for example. Confirming that these tooltips still work (which they seem to) would also be good:

<img width="657" alt="Screen Shot 2019-12-09 at 12 10 46 PM" src="https://user-images.githubusercontent.com/55319/70456854-fa8c7f80-1a7c-11ea-86cd-1d33edb2c391.png">

**Comment by stenington** [comment]
To clarify: a tooltip "still working" just means it shows up when you hover the pointer over the score.

**Comment by rsgonzal** [comment]
Wow i never noticed that black popup text. even with all the scoring i did earlier..

But it all seems to be working as it should!

**Comment by ophelieh** [comment]
Same here, I didn't even notice it before. But it works as expected and looks great! :)
