### ISSUE TITLE
Add feature specs for scoring submissions [8,8,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2320]
Add features specs for:
* scoring a junior submission
* scoring a senior submission

These feature specs will help catch the original bug: `"Demo" score element not recorded"`.

The original bug was fixed in #2208 

For posterity, the original bug is below:

**Describe the bug**
When scoring a submission, whatever value you choose for the second question of the Technical section is not included in the score total.

**To Reproduce**
1. Assuming you have a judge account and a submission that that judge will be able to see...
2. Log in as a judge
3. Attempt to give the submission a perfect score (it's easiest to see the problem this way), finish the score
4. Review the score just created
5. Notice it's 5 points lower than what it had previously shown you
6. Go to the Technical section and see that it has no value for the second question.~~

**Expected behavior**
That score should be part of the total.

**Screenshots**

![score2](https://user-images.githubusercontent.com/55319/70252615-baad5b80-174f-11ea-9522-82dde5a50568.gif)

**Comment by stenington** [comment]
Addressing testing around this should be part of the ticket. I'm not sure if we can drive the Vue app UI through capybara or not, but it would be nice to have a "perfect score" smoke test of some sort at least.

**Comment by shaunxp20** [comment]
> Addressing testing around this should be part of the ticket. I'm not sure if we can drive the Vue app UI through capybara or not, but it would be nice to have a "perfect score" smoke test of some sort at least.

I totally agree! 💯 I'll see about adding one. 👍
