### ISSUE TITLE
Edit TG dataclips to include only 2020 season information [13,3,4.33]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2324]
Mackenzie uses these data clips to track mentors: https://docs.google.com/document/d/1LsDxwA_lOgeovMAcu2eikUx5sic9m2wyVhchIYnjtp0/edit

She's uses some tricks on spreadsheets to combine the data into something like this: https://docs.google.com/spreadsheets/d/1Po1KgZWJaYSUqmcjVvZazmRg5EMdoXgjEKpZ7gzlNog/edit#gid=0

The data clips need to be updated to only show registration data for the 2020 season

**Comment by stenington** [comment]
All dataclips have been updated for 2020.

**Comment by stenington** [comment]
I think QA/acceptance here is for @mdancho to try out the updated dataclips and let us know if they look like they're working.

**Comment by mdancho** [comment]
Hi @stenington. They look accurate according to the registration numbers on the platform/last login date. Thanks!
