### ISSUE TITLE
Replace link on RA Dashboard [5,2,2.5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2328]
The RA dashboard has a section for RA Resources.
The current link for the "RA Handbook" is broken. The link should go to: technovation.atavist.com/regional-ambassador-handbook-2019-2020

**Comment by rsgonzal** [comment]
QA steps:
- log in as an RA
- find RA resources
- click on RA handbook and verify it goes to the right page: technovation.atavist.com/regional-ambassador-handbook-2019-2020

**Comment by devincdillon** [comment]
Logged into QA and checked an RA profile- works!
