### ISSUE TITLE
Task: Reconfigure mentor pre-survey [13,5,2.6]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2329]
The mentor pre-survey was up on production, but needs reconfiguration to work more effectively. It has temporarily been taken down.

Reconfiguration plan TBD in this ticket.

**Comment by rsgonzal** [comment]
Implicit in all options, in my mind, is that someone also configures the link, main text, and optional text in the admin. (Mack/Assessment)

Option 1:
- Reset the platform, so even returning users are asked to complete
- Update pop-up text to say thank you if they already submitted

Option 2:
- Reset the platform, so even returning users are asked to complete
- **Set up the survey collector url with query parameters to collect all the data points outlined in #2310 **
- **Rebecca will make a version of the survey without the fields and we can test to see if the information is being passed**
- **Completion tracking set up, if they've completed the survey they pop up shouldn't show up**

Option 3:
- Reset the platform, so even returning users are asked to complete
- Set up the survey collector url with query parameters to collect all the data points outlined in #2310 
- Rebecca will make a version of the survey without the fields and we can test to see if the information is being passed
- Completion tracking set up, if they've completed the survey they pop up shouldn't show up
- **Provide the user ID from the platform**
- **Change the frequency the survey is shown before dismissed**

**Comment by hellafitz** [comment]
Decision: Option 2 + User ID. Make a separate ticket for changing survey frequency.

**Comment by stenington** [comment]
@rsgonzal @hellafitz What do you feel we should do about users who have already taken this survey? Do we just let them see the pop up two more times, and include some "thanks if you've already taken it" text? I think that was the recommendation I heard in dev weekly.

**Comment by rsgonzal** [comment]
@stenington i assume it's more than just resetting so they don't get the pop up?

i think we could use this approach. It came from Devin, so program team is okay with it.

**Comment by stenington** [comment]
Ok, so QA here can basically be the same as #2330 but with mentors instead of students.

**Comment by rsgonzal** [comment]
New collector link: https://www.surveymonkey.com/r/8CDLYPR?email=[email_value]&country=[country_value]&state=[state_value]&name=[name_value]&city=[city_value]&company=[company_value]&team=[team_value]&uid=[uid_value]

- set to multiple responses
- added custom variables, including uid
- added redirect link

all works as expected. think this is ready for same deployment plan as #2330

**Comment by rsgonzal** [comment]
copying deployment plan:

Ok, so let's work on a deployment plan. I'm seeing something like:

1. confirm survey configuration
    * custom variables
    * multiple responses ON
    * no thank you page?
    * end page redirect pointing to production
2. make sure **no survey** is configured in production
3. developer resets the variables that track pop ups and survey completion for the relevant users
    * for this ticket, that's all student accounts
4. admin configures survey
    * link includes the query parameters
    * text includes a "thanks if you've taken this already" message of some sort

**Comment by stenington** [comment]
> for this ticket, that's all mentor accounts

Yep, I think so.

**Comment by rsgonzal** [comment]
1. confirm survey configuration: https://www.surveymonkey.com/r/8CDLYPR?email=[email_value]&country=[country_value]&state=[state_value]&name=[name_value]&city=[city_value]&company=[company_value]&team=[team_value]&uid=[uid_value]

- [] custom variables 
- [] multiple responses ON
- [] no thank you page?
- [] end page redirect pointing to production

2. make sure **no survey** is configured in production - **DONE**

**Comment by stenington** [comment]
Mentor survey data has been reset as well.

**Comment by rsgonzal** [comment]
Awesome! Step 4 is done, tested in production and pulled the data from surveymonkey. All is working as expected.
