### ISSUE TITLE
Security: Update mini_magick [8,5,1.6]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2336]
As an ongoing part of #2166, we should upgrade to resolve [this mini_magick security alert](https://github.com/Iridescent-CM/technovation-app/network/alert/Gemfile.lock/mini_magick/open)

**Comment by stenington** [comment]
QA:

1. log in as a student on a team with a submission
2. upload a profile photo
3. upload a team photo
4. upload a screenshot to your submission

If you can do those things without any trouble, we should be good.

**Comment by rsgonzal** [comment]
This one looks good to me!
