### ISSUE TITLE
Content & Settings tab not loading on TG production

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2345]
**Describe the bug**
The content & settings tab on TG Production site is not loading.

**To Reproduce**
1. Go to http://my.technovationchallenge.org/
2. Click on 'Content & Settings'
3. See nothing loaded

**Expected behavior**
I expect to see all of the toggle controls for registration, submissions, surveys, etc.

**Screenshots**
![Screen Shot 2020-01-08 at 3 25 12 PM](https://user-images.githubusercontent.com/22801026/72096341-e1226180-32ce-11ea-9804-a691760ef10e.png)

**Additional context**
Tried with multiple accounts and computers and seeing the same error. It was working around 1/8 12 EST when we put up the pre-surveys

**Comment by stenington** [comment]
The issue is coming from the way settings data is passed into the Vue app for that page. If you look [here](https://github.com/Iridescent-CM/technovation-app/blob/44790be23e1ca65099fbe5543037ddc67516d199/app/views/admin/season_schedule_settings/edit.html.erb#L16) you can see we're putting an object literal into an HTML element attribute, pulling in various season toggle values that the Vue app needs. The issue is that strings are being quoted with single quotes, but not being escaped so that if the string itself contains a single quote, the page has invalid HTML, Vue blows up, and the Vue app doesn't load.

**Comment by shaunxp20** [comment]
Wow, great find @stenington ❕🥇 💯

**Comment by stenington** [comment]
QA steps:

1. log in as an admin
2. go to **Content & Settings**
3. Under **Notices**, set all notices to something with a `'` in it, like "Let's test"
4. Under **Surveys**, set all 6 fields to something with a `'`
5. Click **Review**, then **Save these settings**
6. Click **Content & Settings** again, and make sure the settings controls load

**Comment by stenington** [comment]
@shaunxp20 do those QA steps seem reasonable to you?

**Comment by shaunxp20** [comment]
> @shaunxp20 do those QA steps seem reasonable to you?

QA steps look good to me. Thanks for adding those! 🙌 I verified them locally too. 👍 🚥 🍏 📗 💚

**Comment by stenington** [comment]
I confirmed the steps above on staging, but it would be great for one of you to do the same, @rsgonzal or @shaunxp20.

**Comment by shaunxp20** [comment]
> I confirmed the steps above on staging, but it would be great for one of you to do the same, @rsgonzal or @shaunxp20.

Sure thing, I can take a look as well. 👍 Can someone send me the staging url/creds? 😊 😅

**Comment by shaunxp20** [comment]
> I confirmed the steps above on staging, but it would be great for one of you to do the same, @rsgonzal or @shaunxp20.

I got the url/creds, thanks @stenington! 🙇 I tested out all the fields on the _Notices_ tab and the _Surveys_ tab (I cleared out my test data already), everything is working as expected! 👍 😃

**Comment by rsgonzal** [comment]
@stenington so, i may have taken some liberties and checked other symbols & characters..  broke it again! sorry..

**Comment by rsgonzal** [comment]
also, i thought I had written a blurb for the mentor pop up but it didn't show up. can't confirm though!

**Comment by shaunxp20** [comment]
> @stenington so, i may have taken some liberties and checked other symbols & characters.. broke it again! sorry..

Doh! 😱 That's a bummer, great testing though! 🐛 🔍 Do you have the steps to reproduce it, or know which special characters you used? 🤔 😬

**Comment by rsgonzal** [comment]
I used a lot of random ones in the notes...

I think I used quotation marks in the mentor pop up blurb. I might've also used quotations in the student header and i don't see it popping up anymore

**Comment by rsgonzal** [comment]
sorry! i just read the pr. single quote only :sob:

**Comment by shaunxp20** [comment]
> I used a lot of random ones in the notes...
> 
> I think I used quotation marks in the mentor pop up blurb. I might've also used quotations in the student header and i don't see it popping up anymore

Ah, I see it's broken again on staging. 😲 😩 😂 I've tried to break it locally (w/ different combinations of special characters and single/double quotes), but I haven't had any luck yet reproducing it, doh! ☹️ When you get a chance, can you paste in the text you were using, @rsgonzal? Or I wonder if @stenington can get it from the staging db? 🤔

**Comment by stenington** [comment]
```
> get student_dashboard_text
"testing this out'"
> get student_survey_link
"{\"text\":\"\",\"long_desc\":\"If you've already taken the pre-survey, thank you for helping us improve!\",\"url\":\"https://www.surveymonkey.com/r/PD6XXS3?name=[name_value]&school=[school_value]&city=[city_value]&state=[state_value]&country=[country_value]&email=[email_value]&team=[team_value]&age=[age_value]&uid=[uid_value]\",\"changed_at\":\"2020-01-10 15:05:40 -0800\"}"
> get mentor_dashboard_text
"Share your thoughts! Take our post-survey.?/']=+"
> get mentor_survey_link
"{\"text\":\"Y'all, please take the 2020 Pre-Survey! \",\"long_desc\":\"\",\"url\":\"https://www.surveymonkey.com/r/8CDLYPR?email=[email_value]&country=[country_value]&state=[state_value]&name=[name_value]&city=[city_value]&company=[company_value]&team=[team_value]&uid=[uid_value]\",\"changed_at\":\"2020-01-10 15:05:40 -0800\"}"
> get judge_dashboard_text
"Hello you!^%`~"
> get regional_ambassador_dashboard_text
"'\\"
```

I can break my local environment with a backslash quote combo: `\"`. 

But I think the PR as it stands gets us moving again on production with our single-quote problem, and in my opinion, the right solution here is to stop trying to pass an object literal through an HTML element attribute, and have the Vue app hit a new ajax endpoint to initialize itself instead.

**Comment by stenington** [comment]
@rsgonzal You'll have to reconfigure the surveys on production, but after the fix deploys you can use single quote characters without problem.

**Comment by rsgonzal** [comment]
Thanks Mike! Sounds great
