### ISSUE TITLE
Platform allows same email for user and parent but then breaks [8,5,1.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2347]
**Describe the bug**
Student could not create a team or edit her profile. It was identified that she had set the same email for her account and for her parent consent. Apparently the platform does not like this and stops working when this happens. User isn't notified

**To Reproduce**
1. Go to http://my.technovationchallenge.org/
2. Sign up with an email
3. Set up a different email for your parent
4. Change your email to be the same as parent email
5. verify your email account
6. Sign your consent form
7. try to create a team

**Expected behavior**
You should not be allowed to use the same email for parent and student, the platform shouldn't break, and a message should be displayed (e.g. "Please enter a different email address")

**Additional context**
Nick was able to identify the issue and we told the student to use a different email for her parent.

#### QA steps to ensure students can't have the same email address as their parent's/guardian's
 * Sign up as a new student
 * Use a different email address for the parental consent form
 * Try to update the student's email address to be the same email address as their parent's/guardian's, this was possible before, verify it's not possible and you see an error

#### QA steps for existing students who have the same email address as their parents
 * Run the dataclip on staging to find students who have the same email address as their parents
* Sign in as one of these students
* Try to update the student's profile
* Verify you get redirected to the parental consent form, and see an error message about shared email addresses

#### Other QA steps
Changes were made to `profile_controller.rb` which all account types use. It would be a good sanity check to make sure the other account types are working as expected.

**Comment by hellafitz** [comment]
Not able to reproduce as described. Need new steps to reproduce. @rsgonzal to investigate.

**Comment by rsgonzal** [comment]
Updated steps to reproduce above.

Current broken account: roxana+ptest123@technovation.org

**Comment by hellafitz** [comment]
When a student edits their email address the platform should check that they're not changing it to what they have as their parent address. Prevent the change and show an error message.

**Comment by shaunxp20** [comment]
I have been testing this locally, and I found an issue.

It's possible right now for students and parents to share the same email address (after this issue #2347 gets resolved it shouldn't be possible for new accounts), if this is the case for a current student, I'm finding that no profile fields can be updated. The user will be redirected to the main "Edit profile" page with the error: **Sorry, there was a problem. Check the fields below.** and there won't be any fields w/ errors. I tested/verified this locally on the QA branch, which means it is existing behavior.

I made a dataclip of all the students who share the same email address as their parents and there seems to be quite a few of them (hundreds).

The more technical details of what is happening is that there is an existing validator on `student_profile` that checks if the `parent_guardian_email` is the same as the student's. This validation fails b/c the student and parent are sharing the same email address, but the specific error is not shown on the GUI, just the generic **Sorry, there was a problem. Check the fields below.** (I'm wondering if there are support issues that have come in for this.)

One way I have found for a user/student to fix this would be to update the `parent_guardian_email` to be something different. If we want to fix this another way (like bubbling up the actual error) it should probably be in another ticket, imho.

🤕 😫 :neckbeard: 😅 😁

**Comment by stenington** [comment]
Yeah, I think a student having their email and their parent's email be the same causes a handful of mysterious problems, like possibly not being able to join a team or something as well. Right now it seems to be on a short list of things to check for when a student emails Zendesk with a mysterious complaint. 

I guess this ticket deals with preventing the problematic situation, but doesn't specify a desired fix for students already in it. It looks like you might be coming up with a fix for that while I'm typing this @shaunxp20, but I'm also comfortable moving the second piece of the puzzle to a new ticket. It may be considered less of a priority, I'm not sure.

**Comment by shaunxp20** [comment]
> It looks like you might be coming up with a fix for that while I'm typing this @shaunxp20, but I'm also comfortable moving the second piece of the puzzle to a new ticket. It may be considered less of a priority, I'm not sure.

Ha! Yeah, I didn't really get any direction, so I went ahead and addressed it! 😊 😂 😃

**Comment by shaunxp20** [comment]
> It's possible right now for students and parents to share the same email address (after this issue #2347 gets resolved it shouldn't be possible for new accounts), if this is the case for a current student, I'm finding that no profile fields can be updated. The user will be redirected to the main "Edit profile" page with the error: **Sorry, there was a problem. Check the fields below.** and there won't be any fields w/ errors. I tested/verified this locally on the QA branch, which means it is existing behavior.

I went ahead and addressed this issue in this branch/PR. For existing students who have the same email address as their parent's, if they try to update their profile now, we will redirect them to the parental consent form where they can update the conflicting email address.

A more technical note: from what I'm seeing/finding, the way the system currently works, the validations on the student profile (where the parent/guardian email address is stored) happen first, then the validations on the account (where the student's email address is stored) happen. This is why the parent/guardian email address has to be updated first (instead of updating the student's email address). 😅 🤕 😵 💫

**Comment by rsgonzal** [comment]
Thanks for all of the details! So for any existing students that are in this situation, it'll take them to change their parent email? Will it tell them anything or is it possible they'll get confused when they get there?

Wondering if we should email all of the current girls from the dataclip Shaun created. We could let them know, they may experience some issues with their account if they don't update the parent email?

**Comment by shaunxp20** [comment]
> Thanks for all of the details! So for any existing students that are in this situation, it'll take them to change their parent email? Will it tell them anything or is it possible they'll get confused when they get there?

Correct, it will redirect them to their parent's email address (on the parental consent form) and the message "cannot match another student's email" will be displayed below the email address field (this flow is for when they are trying to update their profile). We can change the error message, and/or handle these scenarios differently (preferably in a different ticket). 😅 😁

> Wondering if we should email all of the current girls from the dataclip Shaun created. We could let them know, they may experience some issues with their account if they don't update the parent email?

+1, I think that sounds like a good idea. 😄 👍

**Comment by shaunxp20** [comment]
This one is on staging, I also added some QA steps to the ticket's description. 🤓 😈

**Comment by nickiredescent** [comment]
**QA steps to ensure students can't have the same email address as their parent's/guardian's**
This works as described and I was unable to change the student's email to be the same as the parent's. The warnings are hilariously aggressive:
![Screen Shot 2020-02-27 at 9 47 20 AM](https://user-images.githubusercontent.com/45576078/75470882-38939400-5946-11ea-9174-65128bca067f.png)

I also tried to change the email address to send the parental consent form to the student's email. I was not able to. This is the case both pre- and post- parental consent form signing.
![Screen Shot 2020-02-27 at 9 49 44 AM](https://user-images.githubusercontent.com/45576078/75471134-a213a280-5946-11ea-9b8f-e4c236e107f4.png)

I was able to change a student's email to the parent of another student.
- nick+20s@technovation.org --> nick+12m@technovation.org
- nick+12m was originally the parent email address of the student account: nick+12s
I wasn't able to find any blocks to profile functions after this change. Both accounts had normal functionality and no errors appeared any where I could see. I can't think of any implications this may have at the moment.

--

**QA steps for existing students who have the same email address as their parents**
I was not able to log into the student's account via admin powers.
- Accounts attempted: roxana+12@technovation.org, nick+20sp@technovation.org
- Error: You don't have permission to go there!

Logging out of admin and logging in as the student directly, I can confirm that trying to change my basic profile details and my password leads me to the screen that warns that my parent email cannot be the same as a student's. I can change my location data without encountering this screen.

**Comment by shaunxp20** [comment]
Thanks for the thorough QA effort, @nickiredescent! 💯 🏆 🍰 

> I was able to change a student's email to the parent of **another** student.

@rsgonzal I assume we want to address this? If so, do we want to address it here or in another ticket? 🤔 (Right now we're only validating that a [student/their parent] can't share the same email address, not [student/any parent].)

**Comment by rsgonzal** [comment]
@shaunxp20 I think it's ok for students to have the same parent email? I would assume siblings would have the same.

**Comment by rsgonzal** [comment]
Wondering why Nick wasn't able to log into those student accounts as an admin. Is it because of the conflict?

**Comment by shaunxp20** [comment]
> @shaunxp20 I think it's ok for students to have the same parent email? I would assume siblings would have the same.

Just following up from our meeting this morning, we decided it was fine for a student to have the same parent email address. 👍 

> Wondering why Nick wasn't able to log into those student accounts as an admin. Is it because of the conflict?

Apparently there has been some issues around the admin impersonation tool when the (impersonated) account has issues, so I think it's okay/expected. We can put in an issue to look into/fix it of course. 😄 😸 😃

**Comment by nickiredescent** [comment]
I also think it should be the case that multiple students can share the same parent email. I was referring to something different. The terminology is getting messy here so hopefully this example clears things up:

**Student A**
Student Email: **A**@Technovation.org
Parent Email AP@Technovation.org

**Student B**
Student Email: B@Technovation.org
Parent Email: **BP**@Technovation.org

Student A changes their email to the Parent Email of Student B...

**Student A**
**New** Student email: **BP**@Technovation.org
Parent Email AP@Technovation.org

**Student B**
Student Email: B@Technovation.org
Parent Email: **BP**@Technovation.org

To reiterate, I did not find that this causes any errors, expected or otherwise. Hope this is clear!

**Comment by rsgonzal** [comment]
Thanks for clarifying, @nickiredescent ! Do you see any of this as a problem? We talked about it during the meeting and there's always a possibility kids will be doing weird things with getting parental consent

Opened #2406 for the error messages.

**Comment by shaunxp20** [comment]
> Opened #2406 for the error messages.

Thanks @rsgonza (and for following up)l! 🙌 😃
