### ISSUE TITLE
Epic: The platform has active students outside of the required age range [x,x,x]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2350]
The program defines an age range that all participating students must fall within as of a certain date in the season to qualify for participation. These ages are enforced at sign up, but we're still seeing students both too old and too young being active on the site and joining teams. 

This is an epic because there are a couple of different angles to this, and many possible solutions. Some of these include:
* tools for admins to identify users falling outside of the allowable ages
* tools or practices for the enforcement of age requirements, or for allowing specific exceptions to the rule
* establishing the paths users are taking to become active users outside of the age range (since sign up is the one place it's enforced)
* designing and developing automatic enforcement mechanisms, if desired

**Comment by hellafitz** [comment]
Decision for 19/20 season, program team will monitor ages as teams are confirmed to move to semis.
