### ISSUE TITLE
Automatic content checks on curriculum site [20,8,2.5]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2353]
We're experiencing a problem on the curriculum site where curriculum pages lose their content or display strangely every now and then. We're alerted to the issue typically by users trying to use the page, at which point @mjaris has fixes or workarounds to bring back the proper content. It would be nice to set up something that can do periodic checking and let us know via email or Slack integration that curriculum pages have a problem *before* users encounter the same issue.

**Comment by stenington** [comment]
New Relic used to have the ability to check a url for status code and content, but I don't see it any more. It may have been moved, and possibly folded in with part of their service we don't pay for.

There are lots of other options for accomplishing the same thing though, so it becomes a question of how sophisticated we want it to be, and whether or not we're willing to pay for a service.

**Comment by stenington** [comment]
An interesting option here might be to set up a new repo with RSpec/capybara tests or something similar, testing the curriculum pages. It could be run against staging and production in CircleCI, with builds either getting kicked off manually or maybe being scheduled to run some number of times per day.

**Comment by stenington** [comment]
[Puppeteer](https://github.com/puppeteer/puppeteer) is another tool worth considering for this, probably paired with jest and [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer) for the actual testing.

**Comment by rsgonzal** [comment]
Noting Nick will be helping with the fixes

**Comment by stenington** [comment]
There's a new `curriculum-checks` project building in CI to support this. It logs in `#wordpress-sites` and generates a pdf of curriculum page screenshots per environment to help do a quick visual scan as well. I've run through it all with @mjaris so we should be good to go with this as a starting point.

The two hypotheses I'm hoping to test here first are that
1. production only breaks after a deployment, and
2. staging only breaks after someone has been editing a page.

Whether these are true or not will suggest different routes for approaching a full fix to the issues.

**Comment by stenington** [comment]
@shaunxp20 No PR here for code review, but you can look at https://github.com/Iridescent-CM/curriculum-checks and tell me what you think, if you'd like. 😁

**Comment by shaunxp20** [comment]
> @shaunxp20 No PR here for code review, but you can look at https://github.com/Iridescent-CM/curriculum-checks and tell me what you think, if you'd like. 😁

Looks like a good start to me, and I see the notifications in the `#wordpress-sites`. 👍 💯 

Just curious, how do you access the screenshots/pdfs?

**Comment by stenington** [comment]
The **Artifacts** tab at the top of the build page lets you get at anything stored during the build process:

![Screen Shot 2020-02-05 at 3 02 53 PM](https://user-images.githubusercontent.com/55319/73878523-af96aa80-4828-11ea-9e76-453720327ab3.png)

**Comment by shaunxp20** [comment]
Nice! I see them! Thank you! 🙇

**Comment by shaunxp20** [comment]
Also, just wanted to make sure it was intended to be a public repo. 🤔  🚬 🛁 🚭 ♨️

**Comment by stenington** [comment]
Yeah, I just defaulted in that direction because `technovation-app` is public, and I think we get more credits on certain services if we have a public app. I'm not actually sure if that's true with CircleCI though. But our Github org account limits us to 10 private repos as well, and I figured why use one unless absolutely necessary?

**Comment by shaunxp20** [comment]
> Yeah, I just defaulted in that direction because `technovation-app` is public, and I think we get more credits on certain services if we have a public app. I'm not actually sure if that's true with CircleCI though. But our Github org account limits us to 10 private repos as well, and I figured why use one unless absolutely necessary?

👍 Sounds good to me!

**Comment by hellafitz** [comment]
@stenington sounds like this one is live. Is the QA plan just to let it run for a bit? Or if not, what's the next step?
