### ISSUE TITLE
Returning RA that switches to mentor mode can't complete training [5?,x,x]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2359]
**Describe the bug**
There is an RA that tries to complete the training when in mentor mode, but her training never gets marked completed on her dashboard.

**To Reproduce**
1. Go to xxxx
2. Login as the user
3. Go to training and click until the last slide
4. Click the link to finish training
5. Dashboard refreshes with a message that training is complete
6. Mentor training is not marked as complete on the right side

**Expected behavior**
The right progress bar should have a complete checkmark for the mentor training and the user should be able to mentor teams

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/22801026/73058816-49ce1a00-3e49-11ea-8adc-afbcf37a42cc.png)

**Additional context**
I was not able to replicate this with one of my RA accounts. When I tried to take the training it marked it as complete.

Options:
1. Fully investigate why this is happening to the user and whether it can happen to others
2. Mark this RAs training as complete and let her move on, wait for more instances of the bug to further investigate

**Comment by stenington** [comment]
The reason for the problem completing training seemed to be that the user's mentor bio was too short.
