### ISSUE TITLE
Fix score dataclip(s) by late April [5,3,1.67]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2360]
Dataclips referencing old score columns will be broken, e.g.

* https://data.heroku.com/dataclips/bjbpcmaurdxgdscmxtrkqwjyudkw

Are there others?

**Comment by stenington** [comment]
From #2264

**Comment by rsgonzal** [comment]
Looking at Amy's data archive here: https://docs.google.com/document/d/1AJJH9Hq7s7HRQ726w3MkK0fgYbM2_1RxdQx1kpwqIHM/edit

I think the dataclip above is the only one used and the rest is pulled from the site. Is this correct, @amyiridescent and should I check with anyone else?

**Comment by amyiridescent** [comment]
Yes I believe that is true but I can't get the data clip to run right now. I am getting an error. 
![image](https://user-images.githubusercontent.com/10034578/73152299-322ea580-4084-11ea-8681-d66efbaf3b04.png)

**Comment by rsgonzal** [comment]
Thanks, Amy! This ticket is to fix that ^^ :)

**Comment by stenington** [comment]
This fits roughly under the theme of #2392 in that I believe if it isn't fixed, monitoring scores will become more of a developer problem.

**Comment by shaunxp20** [comment]
The new/updated dataclip is here: https://data.heroku.com/dataclips/daqfepdhedhrlripdngbdskqiihj

A couple of notes:
 * I created a new dataclip from the existing one
 * There doesn't seem to be an easy way to copy an existing dataclip 🤕 😳 
 * There isn't a PR
 * I ran the dataclip against QA/staging data and was able to get some results
 * The year in the dataclip is still set to 2019
 * This might be nice to have in the app for admins to view

**Comment by stenington** [comment]
Dataclips used to be versioned so each time you edited it a new version was created, but it looks like the new dataclips don't do that which is a bummer.

I agree this would be nicer in the app, but for context I think the reason it's in a dataclip is because Amy likes to have data in spreadsheets to work with, and the platform's CSV export is much flakier than dataclips are. So until we can address that flakiness, dataclips are the more reliable solution.

**Comment by amyiridescent** [comment]
Yeah sorry Shaun. I like to manipulate the date on a spreadsheet. It helps that I already know how to write functions on google spreadsheet. :) And I try not to do the CSV exports too often since it tends to get stuck or crashes. Sorry for being old school.

**Comment by shaunxp20** [comment]
> Yeah sorry Shaun. I like to manipulate the date on a spreadsheet. It helps that I already know how to write functions on google spreadsheet. :) And I try not to do the CSV exports too often since it tends to get stuck or crashes. Sorry for being old school.

Ah, no worries! 😃 Anywho, when you get a moment, can you check out the new dataclip, and see if it's working as expected? 

https://data.heroku.com/dataclips/daqfepdhedhrlripdngbdskqiihj

Right now it's pointing at staging for the 2019 season, if it's working as expected I'll updated it to 2020, and point it production, and it should be good to go for the 2020 season. 😃

**Comment by amyiridescent** [comment]
Data clip looks good. :) 

Thanks Shaun for helping me the the dataclip share settings. :)

**Comment by shaunxp20** [comment]
Thanks @amyiridescent! 👍 🙌 🎉 

I updated the year in the dataclip to 2020 and also pointed it to production.

**Comment by shaunxp20** [comment]
I'll move this one to Done, since there's nothing to deploy for this. 👍 😃
