### ISSUE TITLE
Replace outdated curriculum links on the submission screens [5,2,2.5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2365]
We currently link to a number of curriculum units from the submission screens for girls. The links are not pointing to the correct units from this season.

This doc points to where we can find these links and what they should be replaced with: https://docs.google.com/document/d/1cC84zpkehmO_gX9Az_u2THajEJFEIWZmf8LFahs90jI/edit

**Comment by rsgonzal** [comment]
@nickiredescent Could you help me test this to make sure the links are now going to the correct location, please?

**Comment by nickiredescent** [comment]
All the links have been updated to the new, correct places. Looks good!

**Comment by rsgonzal** [comment]
thanks, @nickiredescent ! looks good to go.
