### ISSUE TITLE
Update calendar for RPE event creation [8,8,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2366]
The calendar when setting up a RPE highlights which dates are available. It is currently out of date and should be set with the range from April 22nd through May 25th 2020

![Screen Shot 2020-01-29 at 9 09 58 AM](https://user-images.githubusercontent.com/22801026/73379537-4a1a4b00-4277-11ea-950f-f1efc792363c.png)
![Screen Shot 2020-01-29 at 9 10 04 AM](https://user-images.githubusercontent.com/22801026/73379545-4dadd200-4277-11ea-8db7-23b9e9c36513.png)

**Comment by hellafitz** [comment]
Decision: We will create new config variables to hold these dates, and this calendar widget should read that config. Right now the dates are hardcoded into the platform.

Need Program Team to confirm the relationship between these dates and Quarters (currently one day off). 
Currently we don't think RPEs work if they don't happen during the Quarterfinal window. 
Note that, if a dev or admin WAS to set RPE dates outside of the quarterfinals window there may be parts of the platform that won't work (so the Program Team will need to check it).

We'd like an instructive error message to display if dates are set outside of the quarters window.

**Comment by rsgonzal** [comment]
@shaunxp20 checked in with the team and they're ok with the dates falling outside of the judging window.

**Comment by shaunxp20** [comment]
> @shaunxp20 checked in with the team and they're ok with the dates falling outside of the judging window.

Thanks for the info! @rsgonzal! 

Hmm, does that mean we want to remove the date restrictions all together (that would be pretty easy to do)? So a RA can pick any date? 👉 📆 

Or do we want the new date restrictions of: April 22nd through May 25th 2020?

🤔 ⛰🌲🌞

**Comment by rsgonzal** [comment]
The latter, we should change the new date restrictions to be April 22nd through May 25th 2020

**Comment by shaunxp20** [comment]
> The latter, we should change the new date restrictions to be April 22nd through May 25th 2020

Sounds good! 👍 Roger Wilco! 🚀

**Comment by shaunxp20** [comment]
I added some new configuration settings to make the RPE date range dynamic:
```
DATES_REGIONAL_PITCH_EVENTS_BEGINS_YEAR
DATES_REGIONAL_PITCH_EVENTS_BEGINS_MONTH
DATES_REGIONAL_PITCH_EVENTS_BEGINS_DAY

DATES_REGIONAL_PITCH_EVENTS_ENDS_YEAR
DATES_REGIONAL_PITCH_EVENTS_ENDS_MONTH
DATES_REGIONAL_PITCH_EVENTS_ENDS_DAY
```

@rsgonzal Do these configuration names work? 🤔

**Comment by rsgonzal** [comment]
hey @shaunxp20 ! These work for me :)

**Comment by shaunxp20** [comment]
### **QA STEPS**

- Create a new Regional Pitch Event
- Verify that the selectable date range is between April 22, 2020 and May 25, 2020

I added the new configuration settings and values to both staging and production. You can also view/verify the new configuration settings via the Heroku GUI:
```
DATES_REGIONAL_PITCH_EVENTS_BEGINS_YEAR
DATES_REGIONAL_PITCH_EVENTS_BEGINS_MONTH
DATES_REGIONAL_PITCH_EVENTS_BEGINS_DAY

DATES_REGIONAL_PITCH_EVENTS_ENDS_YEAR
DATES_REGIONAL_PITCH_EVENTS_ENDS_MONTH
DATES_REGIONAL_PITCH_EVENTS_ENDS_DAY
```

I would recommend double-checking the keys/values in production just to be sure. 😺

**Comment by rsgonzal** [comment]
what about this one @shaunxp20 ?

**Comment by shaunxp20** [comment]
> what about this one @shaunxp20 ?

This one is on staging! 👍

**Comment by shaunxp20** [comment]
@stenington Just following up from yesterday, I created a new issue to test our environment variables, #2394.

**Comment by nickiredescent** [comment]
Tested and is working as expected.
I was able to create events on April 22nd, May 25th, and any date in between.

Fringe case I do want to note. This calendar restriction is by local date only. I was able to create an event in Taiwan on April 22nd, which would be April 21st in the US. I don't suspect that this will have much, if any, practical implications.

On a related note, viewing an event as an Admin shows a non-converted time as compared to viewing an event as the RA who created it. Again, probably not impactful, just noting.

**Admin View**
![image](https://user-images.githubusercontent.com/45576078/74879393-e3d89380-531d-11ea-8c32-09630f0a8899.png)

**RA View**
![image](https://user-images.githubusercontent.com/45576078/74879356-ce636980-531d-11ea-93c7-479777e02abe.png)

**Comment by stenington** [comment]
Nice catch @nickiredescent!

@rsgonzal What do you think about these timezone issues? If we're trying to limit RPE creation to the window when the platform will definitely be in judging mode, we need to resolve some of the problems here. If it's okay for the first RPEs to happen while judging is still closed, then it's less of an issue (although still something good for us to be aware of).

And the RA/Admin issue I think is a bug worth fixing. It shouldn't say 10-2 CST for one and 10-2 Taipei for another person, those are two different times. My vote would be to address that, but what's your take @rsgonzal?

**Comment by stenington** [comment]
@rsgonzal agrees that RAs creating an event technically a day early shouldn't really matter, but we want to open a new ticket to explore the timezone thing and understand how well or how poorly the platform currently handles timezones related to RPEs.

**Comment by stenington** [comment]
Opened #2396 to dig deeper on timezone issues, but not holding this one up in the meantime.

**Comment by shaunxp20** [comment]
Thanks for testing these edge cases, @nickiredescent! 👍  💯  I looked at it briefly, and there's definitely something wonky going to w/ our time zones (or lack thereof). 🤕 😅 

Thanks for creating a new ticket for the inconsistent time zones, @stenington! 🎫 👍 😃
