### ISSUE TITLE
Score deletion/restoration UI mockups [13,8,1.63]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2368]
From #2270, we want to mock up what the admin UI would look like if we button the controls in places where they're "easiest" to code. We can then take that to the program team for feedback on whether they would find those controls usable or they would want something more sophisticated.

**Comment by stenington** [comment]
I think there are three relevant user journeys here:

### Looking up a judge, seeing scores 
![Screen Shot 2020-02-04 at 2 27 42 PM](https://user-images.githubusercontent.com/55319/73780171-fbc7e900-475b-11ea-9ed1-d949e8e4e407.png)

### Looking up a submission, seeing scores
![Screen Shot 2020-02-04 at 2 26 54 PM](https://user-images.githubusercontent.com/55319/73780173-fbc7e900-475b-11ea-9891-bddf4fa8906c.png)

### Looking up deleted scores
![Screen Shot 2020-02-04 at 2 26 58 PM](https://user-images.githubusercontent.com/55319/73780172-fbc7e900-475b-11ea-9122-8fbf12269135.png)

**Comment by stenington** [comment]
My recommendation would be to put deletion/restoration controls into the page showing detailed information for a single score (where the approve/delete controls currently appear for a suspicious score). Then we would also add ways to get to that page for a deleted score.

## Controls

### Deleted score
![Screen Shot 2020-02-03 at 12 42 03 PM 3](https://user-images.githubusercontent.com/55319/73782775-9b877600-4760-11ea-8e64-c0f3e13b8c84.png)

### Normal score
![Screen Shot 2020-02-03 at 12 42 03 PM 2](https://user-images.githubusercontent.com/55319/73782776-9c200c80-4760-11ea-9aed-243f9ec65f7c.png)

### Suspicious score
![Screen Shot 2020-02-03 at 12 42 03 PM](https://user-images.githubusercontent.com/55319/73782777-9c200c80-4760-11ea-8d23-5c6cfce85e7e.png)

## Reaching deleted score details page

The minimal change would be adding a **View** column to the **Score exports** page, which already allows you to look up deleted scores. That button would take you to the score details page where you could then restore the score.

<img width="960" alt="Screen Shot 2020-02-04 at 3 17 03 PM" src="https://user-images.githubusercontent.com/55319/73783342-852dea00-4761-11ea-8c02-5b7af16c1130.png">

**Optionally**, to maximize usefulness, I think these two pages could also show deleted scores in some way, with a link to view the details:

![Screen Shot 2020-02-03 at 12 23 47 PM](https://user-images.githubusercontent.com/55319/73783516-d0e09380-4761-11ea-9f91-1f83e8766578.png)
<img width="960" alt="Screen Shot 2020-02-04 at 2 19 50 PM" src="https://user-images.githubusercontent.com/55319/73783532-db029200-4761-11ea-9e62-705e68b25225.png">

**Comment by stenington** [comment]
@rsgonzal does this look like enough to take to someone for feedback?

**Comment by rsgonzal** [comment]
Thanks, @stenington !

This looks good to me. So the final screenshots are:
1. Viewing the team's scores
2. Viewing the judge's score

Do we want to get feedback from the team on whether this would be useful or more useful than a recommendation?

**Comment by stenington** [comment]
My suggestion is that we add controls on these three pages, indicated by the arrows:

<img width="960" alt="73783342-852dea00-4761-11ea-8c02-5b7af16c1130" src="https://user-images.githubusercontent.com/55319/73944686-fcc65b00-48c0-11ea-9438-340638f64cdd.png">

![73782775-9b877600-4760-11ea-8e64-c0f3e13b8c84](https://user-images.githubusercontent.com/55319/73944687-fd5ef180-48c0-11ea-8746-281349b664bd.png)

![73782776-9c200c80-4760-11ea-9aed-243f9ec65f7c](https://user-images.githubusercontent.com/55319/73944688-fd5ef180-48c0-11ea-9c88-3011b28fe004.png)

And then we add content to the following two pages, showing any deleted scores associated with the submission or judge respectively:

![73783516-d0e09380-4761-11ea-9f91-1f83e8766578](https://user-images.githubusercontent.com/55319/73944772-22536480-48c1-11ea-91d0-04252607aa50.png)
<img width="960" alt="73783532-db029200-4761-11ea-9e62-705e68b25225" src="https://user-images.githubusercontent.com/55319/73944776-22ebfb00-48c1-11ea-8040-30b44041bc27.png">

**Comment by hellafitz** [comment]
@rsgonzal to update after meeting with Program team reps later today

**Comment by rsgonzal** [comment]
The team liked where this was going. Overall, as is they think it would only solve the problem for certain situations (score monitor deletes a score, then gets convinced to restore it for whatever reason)

They're more concerned about scores that were potentially deleted because of a strange reason, like whether the team or judge moved in and out of RPE

Some points: 
- at the scale we want it to work for, could be more useful with info on how it was deleted? 
- talked about how at a minimum knowing whether it was deleted by admin or automatically by the platform
- knowing the reason why the score was deleted would be more useful, knowing if it was due to RPE movement or something else

Concerns:
- we would need to test some weird scenarios like, the implication of restoring judge scores for a judge that went from virtual to RPE but still want to keep all the scores.

@stenington this was the feedback I heard from the team. don't know how possible the request is, but maybe we want to handle this work in iterations?

**Comment by rsgonzal** [comment]
@stenington to write up conclusion and create new tickets.
Will work on initial mockups first and improve upon in iterations

**Comment by stenington** [comment]
Sounds like the mockups as they stand don't sound like they'd be as useful as we had hoped, but they certainly wouldn't hurt anything. It sounds like what would be useful is contextual information on why a score was deleted (e.g. did an admin do it? was it because of leaving/joining an RPE?) but as a first step we'll go forward with these mockups, and create a ticket to capture the idea of the extra contextual information that could possibly be added in later.

The implications of possibly keeping both RPE and non-RPE scores from a judge is still an open question, not to be solved here.

**Comment by stenington** [comment]
This work has been divided into #2382, #2383, #2384, and #2385, with #2386 as the feature request for contextual information.
