### ISSUE TITLE
Ongoing support [8,8,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2369]
Placeholder ticket for ongoing miscellaneous support for active season, or other issues.

**Comment by stenington** [comment]
Also handle triaging issues that arise in here.

**Comment by rsgonzal** [comment]
@stenington There's a mentor that is getting an error when trying to input her ssn

dabbatiello@ridgewood.k12.nj.us

**Comment by stenington** [comment]
@rsgonzal Looks like this mentor entered their name as "Name (nickname)", and Checkr won't allow the parentheses. She'll need to pick which version of her name she wants to use and edit her profile before resubmitting her background check, I think.

**Comment by rsgonzal** [comment]
:woman_facepalming: thanks, @stenington this makes sense. I told Mackenzie to inform the mentor

**Comment by rsgonzal** [comment]
@shaunxp20 can you look up this user, please? gmiarivas30@gmail.com

"I checked the team's profile, and it says that the student accepted the team invite. However, she is listed as a Pending student under members, and there's a line about her needing to complete a task, but the task itself is blank:"

**Comment by shaunxp20** [comment]
> @shaunxp20 can you look up this user, please?
> 
> "I checked the team's profile, and it says that the student accepted the team invite. However, she is listed as a Pending student under members, and there's a line about her needing to complete a task, but the task itself is blank:"
> 
> ![Screen Shot 2020-02-05 at 1 45 15 PM](https://user-images.githubusercontent.com/22801026/73886101-cb488380-481d-11ea-8401-afb1576180ff.png)
> 
> I tried investigating, but I'm not sure what's wrong with her profile. We've seen this issue before, but I think the problem was that they had the same email for parent and student and that's not happening now.

👍 @stenington is going to help/show me how to do this tomorrow afternoon! 🐳 🐋 🐟

**Comment by rsgonzal** [comment]
My hypothesis of the second profile is incorrect!

But I do see that an invite was deleted with ID 47572 and then there's an accepted one with ID 50837

I have deleted and re-added her to the team as I try different things, so not sure if that deletion was me or prior to me getting in there!

**Comment by stenington** [comment]
@rsgonzal We looked up that user, the system seemed to know that she *could* be onboarded, but still had the onboarded flag set to false. So we basically just triggered a recalculation and now she's considered a full member of the team as far as I can tell. Can you confirm that for me?

We don't know exactly how that user got into that state in the first place, and I assume it will happen again at some point. We'll open a new ticket to track this issue and, if you want to, start thinking of ways to allow an admin to fix it or to prevent it from happening in the first place.

**Comment by stenington** [comment]
Created #2372

**Comment by rsgonzal** [comment]
Awesome, thanks @stenington and @shaunxp20 ! it all looks right to me, I will let the user know.

**Comment by stenington** [comment]
Woke up to production alerts this morning
> The 95th percentile response time for technovation has exceeded your threshold setting of 25000ms.
>
> Historical response time data is available in Application Metrics. Additional guidance on correcting slow requests and request timeouts is available in Dev Center.

and graphs like this:

![Screen Shot 2020-02-07 at 9 07 40 AM](https://user-images.githubusercontent.com/55319/74036077-90fbf500-4989-11ea-9c8f-1058ddc7fb31.png)

It looked like dashboard requests were issuing crazy numbers of redis GETs that were eating up time pretty badly. Logs were filled with "log writing failed. deadlock; recursive locking" which is a new one to me. 

So far the tried and true "turning it off and on again" seems to have gotten things under control (restarting the web dynos).

**Comment by rsgonzal** [comment]
Updated #2372 we have another student who can not participate in her team's submission. All of her onboarding steps seem to be complete but there is still a block. Send user's email through slack

![Screen Shot 2020-02-12 at 3 01 10 PM](https://user-images.githubusercontent.com/22801026/74386405-a79bb500-4daa-11ea-981a-a79a0bf95048.png)

**Comment by rsgonzal** [comment]
Decision: fix problem for current student and decide what direction to take #2372

**Comment by stenington** [comment]
It occurred to me that I can be more proactive here. There seem to be about 35 student accounts from this year that are still marked as onboarding but should be mark onboarded. My proposal would be to take some support ticket time to write a rake task that resolves this issue and maybe set it up to run once a day in production or something like that, while we also have #2372 in play to try to find a better fix. @shaunxp20 does that sound reasonable or am I getting ahead of myself? What do you think?

**Comment by shaunxp20** [comment]
> It occurred to me that I can be more proactive here. There seem to be about 35 student accounts from this year that are still marked as onboarding but should be mark onboarded. My proposal would be to take some support ticket time to write a rake task that resolves this issue and maybe set it up to run once a day in production or something like that, while we also have #2372 in play to try to find a better fix. @shaunxp20 does that sound reasonable or am I getting ahead of myself? What do you think?

Just following up from our earlier conversation, I think this is a great idea, @stenington! 💯 👍 And I see the PR (#2387) for this, and I'll take a look! 😄
