### ISSUE TITLE
Rebrand: Spike: Scope changes on TG site [8,x,x]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2374]
Start mocking up different components (header, nav, footer, forms, etc.) using Tailwind CSS.

Mockups: https://www.dropbox.com/home/Distribution/Campaigns%2C%20Initiatives/2019/Q42019-WebsiteUpdates/Q12020-myTG-Platform

**Background**
Marketing would like to make simple changes to TG.
Amy recommends not making changes beyond color (simple stuff) until a month after submission closes

**Comment by hellafitz** [comment]
next step: small ticket to identify core templates and pages that we want designs for
