### ISSUE TITLE
Add messaging to the RPE page when a student is joining an event

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2376]
Currently, students do not know if their events are official or not official. I propose adding messaging to those screens when selecting events that lets them either know their event status is unknown and to check with the RA after a certain date or if we can also do #2377, to check back here.

"Not all events are official. Please check back after April 21st 
to see if your event is an official pitch event or a celebration event"
![Screen Shot 2020-02-13 at 3 14 47 AM](https://user-images.githubusercontent.com/22801026/74429303-8e791f80-4e0f-11ea-8c27-8572aa8de92c.png)
![Screen Shot 2020-02-13 at 4 35 56 AM](https://user-images.githubusercontent.com/22801026/74435924-64792a80-4e1a-11ea-8055-45089c88deaf.png)

Noting: If #2377 is completed, will need to either
- create a new ticket to change this messaging to "Your event is an official event and will be judged in person" for any events that were not toggled UN-official 
- rely on program team to message that if they don't see unofficial, it is official

**Comment by stenington** [comment]
The proposed modification to #2377 folds this messaging in, so closing this ticket.
