### ISSUE TITLE
Show official/unofficial event status to students and mentors [13,8,1.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2377]
Currently, all events are official when created. Admin has the ability to toggle them UN-official when they reach the correct amount of teams

![Screen Shot 2020-02-13 at 3 22 15 AM](https://user-images.githubusercontent.com/22801026/74429886-9d140680-4e10-11ea-9179-af3039caa894.png)

This information is not passed on to students and creates a lot of confusion for teams. They assume they are attending an official event but then only receive online scores.

Proposal: add messaging to the student dashboard and event page showing the UN-official status once an admin has toggled an event UN-official

![Screen Shot 2020-02-13 at 3 55 07 AM](https://user-images.githubusercontent.com/22801026/74433153-b7e87a00-4e14-11ea-8bbf-8551d96dd5f8.png)

![Screen Shot 2020-02-13 at 4 34 07 AM](https://user-images.githubusercontent.com/22801026/74435788-1bc17180-4e1a-11ea-8ea6-81bf9262eca6.png)

![Screen Shot 2020-02-13 at 4 48 17 AM](https://user-images.githubusercontent.com/22801026/74436916-1bc27100-4e1c-11ea-8a5c-5fd44cab2612.png)

## QA
Based on the screenshots above, log in as both a **student** and as a **mentor** and make sure you see the expected messages where you expect to see them. 

**One note on the dates**: it is set in config, which I'm currently setting to 4/23/2020 to mimic production. However, if you see a different date in the screens as you QA, as @rsgonzal or @stenington to check what the QA site has been configured to. It may have been changed.

**Comment by stenington** [comment]
We discussed a modification here where we might show **Status: official/unofficial/pending, check back on...** alongside the Time and Address. We might also want to add messaging about what those words mean, or link to an FAQ, or something like that. The next step for this ticket is to mock up what that alternative could look like, and get more concrete about the copy.

**Comment by rsgonzal** [comment]
Question about how emails get triggered. Might need to edit auto email that gets sent to come back and check for status.

**Comment by rsgonzal** [comment]
@stenington @shaunxp20 

I did some quick mock ups here.

**Before an event has been selected**
First event screen, can we add some sort of text here? (same image as before)
![Screen Shot 2020-02-19 at 4 42 32 PM](https://user-images.githubusercontent.com/22801026/74889759-db408700-5336-11ea-9510-ee61a1729c67.png)

Second screen when they click in, there is already some info there, can be added to. Realize that it might always say pending here
![Screen Shot 2020-02-19 at 4 22 03 PM](https://user-images.githubusercontent.com/22801026/74889794-f90dec00-5336-11ea-8943-013079eb4718.png)

**After an event has been selected, but before April official/unofficial date**
First event screen, same as above
![Screen Shot 2020-02-19 at 4 44 28 PM](https://user-images.githubusercontent.com/22801026/74889860-25296d00-5337-11ea-83c3-4d97271beba4.png)

Second screen, same edited text. Realize that it might always say pending here
![Screen Shot 2020-02-19 at 4 27 35 PM](https://user-images.githubusercontent.com/22801026/74889893-3c685a80-5337-11ea-9bf3-ed0ac944d246.png)

**April 20th, events will close and submissions close**

Students see this screen, same text would have already been edited. Pending until April 22nd when the platform with check for status
![Screen Shot 2020-02-19 at 4 53 55 PM](https://user-images.githubusercontent.com/22801026/74890307-81d95780-5338-11ea-9719-41aff1b750bd.png)

**Comment by stenington** [comment]
@rsgonzal These changes seem doable for a student. Mentors have a slightly different RPE selection experience, because they may be selecting on behalf of one of many teams. I believe the changes made for a student inside the event "card" would show for a mentor too, but the extra text on the student dashboard wouldn't automatically appear on the mentor dashboard.

**Comment by rsgonzal** [comment]
Ah you're right.

These are the screens for a mentor.
![Screen Shot 2020-02-21 at 12 58 33 PM](https://user-images.githubusercontent.com/22801026/75071425-3050da00-54aa-11ea-8be4-3eb86a8e419b.png)
![Screen Shot 2020-02-21 at 12 58 42 PM](https://user-images.githubusercontent.com/22801026/75071441-35ae2480-54aa-11ea-9d26-df752f6e0348.png)
![Screen Shot 2020-02-21 at 12 58 52 PM](https://user-images.githubusercontent.com/22801026/75071454-3c3c9c00-54aa-11ea-91a7-a307d62f65c9.png)
![Screen Shot 2020-02-21 at 1 00 23 PM](https://user-images.githubusercontent.com/22801026/75071466-4199e680-54aa-11ea-90c2-8e1e1c7518c9.png)

**Comment by rsgonzal** [comment]
The team would like the mentor experience to mirror the students, just so everyone could be clear.
Could we add messaging to this screen as well for the mentors?

![]()

**Comment by rsgonzal** [comment]
1. 'card' text: Events will be confirmed as either Regional Pitch Events or Celebration Events after April 21st. For more information, please check out the Technovation FAQ or contact your regional ambassador.

2. dashboard text: Events will be confirmed as either Regional Pitch Events or Celebration Events after April 21st. Please sign in to your account to verify the status of your event after that date. For more information about pitch events, please check out the Technovation FAQ.

'Technovation FAQ' links to: https://iridescentsupport.zendesk.com/hc/en-us/articles/115002731414-All-about-Regional-Pitch-Events

**Comment by hellafitz** [comment]
@rsgonzal to summarize the deliverable

**Comment by rsgonzal** [comment]
Going along with the text above, there are two screens that would change for mentors and students.

1. There is a card that displays the event details, we believe an edit to the students will also reflect what the mentor sees. In this box:
- The text in the top right corner will be edited to the messaging in (1) above
- There will be a new 'Status:' section that will say pending up until the April 22nd, when it will show what the status is in the system (official or unofficial)
![Screen Shot 2020-02-26 at 2 40 50 PM](https://user-images.githubusercontent.com/22801026/75395012-4f82a980-58a6-11ea-8010-2d5c505a59f1.png)

2. In the mentor and student dashboard, there is a "Pitching Events" section. The message they see on the dashboard varies slightly, but we want to add an extra couple of sentences here too for clarification. The text is in (2) above.
- Student dashboard, they see two slightly different versions whether they have selected an event or not, not sure if this is two different changes or one
![Screen Shot 2020-02-26 at 3 00 21 PM](https://user-images.githubusercontent.com/22801026/75396226-dfc1ee00-58a8-11ea-92c3-2e88db66745e.png)
![Screen Shot 2020-02-26 at 2 58 22 PM](https://user-images.githubusercontent.com/22801026/75396235-e3557500-58a8-11ea-8eaf-14d0a26d3c6a.png)

- Mentor dashboard sees this screen
![Screen Shot 2020-02-26 at 2 54 47 PM](https://user-images.githubusercontent.com/22801026/75396256-ef413700-58a8-11ea-90be-a439ef52fb98.png)

**Comment by stenington** [comment]
@rsgonzal I'm not going to hard code dates here, I'm going to use the new config introduced in https://github.com/Iridescent-CM/curiosity-machine/issues/2371, but I want to flag that in that ticket we said the date is April 22nd, not April 21st.

**Comment by rsgonzal** [comment]
That's fine! I think April 22nd is great.

**Comment by stenington** [comment]
QA: based on the screenshots above, log in as both a **student** and as a **mentor** and make sure you see the expected messages where you expect to see them. 

**One note on the dates**: it is set in config, which I'm currently setting to 4/23/2020 to mimic production. However, if you see a different date in the screens as you QA, as @rsgonzal or @stenington to check what the QA site has been configured to. It may have been changed.

**Comment by nickiredescent** [comment]
I can confirm that I see the appropriate "check back after April 23" messages on both student and mentor dashboards. 

The status of the event was still "pending" after waiting some time and using different browsers. I was not able to get to the point to see event status reflected in RA, Student, or Mentor dashboards. I also toggled the event status a few times, but no change was reflected on the participants' ends.

**Comment by stenington** [comment]
@nickiredescent Oh, I didn't think about testing the students/mentors seeing the actual status, that's a good call.

I just changed the staging config so that RPE status would have been finalized on Feb 23 instead of April. Now you should see both that the text says February, and the status should actually show (not be pending).

**Comment by rsgonzal** [comment]
Looks good! Turned off submissions and the ability to choose events as well. Seeing all of the things I'm supposed too!

@ophelieh is checking this one tomorrow too. Let me know if you want me to change the RPE official date in the system so that you don't just see pending!

**Comment by rsgonzal** [comment]
Whoops! @mdancho is checking this one, not ophelie!

**Comment by mdancho** [comment]
Checked the mentor pitching events tab and see the date changed to February instead of April. When I click further into "select an event" I can see that I am registered to an event as a mentor but it is not viewable from the dashboard/the pitching event tab without clicking "select as event". 

<img width="860" alt="Screen Shot 2020-03-09 at 10 11 41 AM" src="https://user-images.githubusercontent.com/52216992/76239483-e6c4f680-61ee-11ea-8e7d-814dca88d2b0.png">

<img width="1095" alt="Screen Shot 2020-03-09 at 10 19 31 AM" src="https://user-images.githubusercontent.com/52216992/76239849-7c608600-61ef-11ea-8d98-bce4e07a1a02.png">

**Comment by mdancho** [comment]
Didn't have the submissions closed, but once they are  the mentor can see the event on the  dashboard.  

<img width="856" alt="Screen Shot 2020-03-09 at 10 43 49 AM" src="https://user-images.githubusercontent.com/52216992/76241899-f6463e80-61f2-11ea-9542-5969aab1c876.png">

**Comment by rsgonzal** [comment]
Thanks, mackenzie!

This one is good to go.
