### ISSUE TITLE
Remove language about Thunkable pro from submission screens [8,2,4]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2379]
When students are asked to upload their code, they can choose thunkable as an option.

Currently, there is outdated language that refers to using a Pro version. That is no longer relevant and should be removed.

https://technovation-qa.herokuapp.com/student/team_submissions/xx-by-team-me/edit?piece=development_platform --> choose thunkable
![Screen Shot 2020-02-13 at 5 09 22 AM](https://user-images.githubusercontent.com/22801026/74438445-07cc3e80-4e1f-11ea-8aa8-f8c4767b17d1.png)
Change language to --> **For more information on how to get started with Thunkable, click here.**
'here' goes to same place as before: https://technovation-qa.herokuapp.com/general_info/get_started_with_thunkable

https://technovation-qa.herokuapp.com/general_info/get_started_with_thunkable

![Screen Shot 2020-02-13 at 5 04 00 AM](https://user-images.githubusercontent.com/22801026/74438373-deabae00-4e1e-11ea-9d40-a9efbf648ad8.png)

@ophelieh does this look right?

**Comment by ophelieh** [comment]
That does look right! Thank you

**Comment by shaunxp20** [comment]
### **QA Steps**

- As a student, create a new submission
- On the “Upload your source code” step, select Thunkable from the dropdown list
- Verify the Thunkable Pro section has been updated accordingly, and that the Thunkable Pro verbiage has been removed
- Click the "here" link
- Verify the Thunkable Pro section and verbiage has been removed

**Comment by rsgonzal** [comment]
Thanks for the QA steps, @shaunxp20 ! is this on staging yet?

**Comment by shaunxp20** [comment]
> Thanks for the QA steps, @shaunxp20 ! is this on staging yet?

This one is finally on staging! 😅

**Comment by rsgonzal** [comment]
Thanks, @shaunxp20 ! Moving them over to test

**Comment by ophelieh** [comment]
It looks great BUT the video includes language about the pro version at 0:49. Let me check with the team if we have another video.

**Comment by ophelieh** [comment]
This is the video we could replace it with - https://www.youtube.com/watch?v=YrONgW8udmM.

Thank you!

**Comment by shaunxp20** [comment]
Thanks for the thorough review @ophelieh! 👍 😃 

I updated the Thunkable video, the PR is here: #2400.

**Comment by ophelieh** [comment]
Hi! I just re-tested and it looks like it's still the old video  - https://technovation-qa.herokuapp.com/general_info/get_started_with_thunkable. I'm brought to that page from here
![image](https://user-images.githubusercontent.com/32206421/75173249-33d7a180-56f4-11ea-9d41-442f89d43a53.png)

**Comment by shaunxp20** [comment]
The updated video is being deployed to staging right now, I'll let you know when it's ready! 👍 😃

**Comment by ophelieh** [comment]
Ok cool :)

**Comment by shaunxp20** [comment]
@ophelieh The deploy finished, so the new video should be showing up on staging now. 😃

**Comment by ophelieh** [comment]
Works as expected. Thank you!

**Comment by shaunxp20** [comment]
> Works as expected. Thank you!

Thanks for QAing/verifying @ophelieh! 🥇 🍰 😄
