### ISSUE TITLE
Assess test coverage of javascript code/packs [13,13,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2380]
From #2166 and following on #2363, we need to check our test coverage on the javascript getting built into packs before upgrading webpack. If it's good, that'll help during an upgrade. If it's not good, we would need to increase coverage before attempting the upgrade.

## QA Steps

This one is on staging, but there is no front-end piece to this one, so I don't think any manual QAing is necessary. 😃

**Comment by stenington** [comment]
Outcomes could be: run a coverage tool, get some numbers, identify gaps. Do a pairing session with other dev so we both have some sense of what's going on in this area.

**Comment by shaunxp20** [comment]
Documenting some simple/obvious things that took me on quite a ride yesterday! 🎢

`npm ci` - this is supposed to give you reproducible builds (I just discovered this command yesterday) 

https://docs.npmjs.com/cli/ci
https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci

But `npm ci` doesn't work w/ our app (it throws a bunch of errors) b/c our `package.json` and `package-lock.json` files are out of sync. For example, we have `dotenv` in  `package.json`, but it's missing from `package-lock.json`.

`yarn install` - will give you reproducible builds based off `yarn-lock.yaml`. After trying so many other things, this is what ended up getting the tests passing for me. *sigh

https://classic.yarnpkg.com/en/docs/yarn-lock

Anywho, from what I'm seeing we either want to use `npm` or `yarn`. I think we should pick one and remove the other `*-lock.json` file. 😅 💆‍♂ 🚶 🌞

**Comment by stenington** [comment]
I agree we should pick one. I believe CI uses yarn so the easiest change is to use that.

**Comment by shaunxp20** [comment]
> I agree we should pick one. I believe CI uses yarn so the easiest change is to use that.

Cool, I removed `package-lock.json` in #2284 

Fwiw,  after getting into the weeds on this, I think it would better to use npm for two (pretty much trivial) reasons: it make's the project more accessible/easier for someone to contribute, and removes a dependency. But since we're the only ones who contribute, and CircleCI is already setup to use yarn, then I think it makes sense to just keep it as-is, using yarn. 👍 😀

**Comment by stenington** [comment]
Looks like [rails/webpacker has yarn as a prereq](https://github.com/rails/webpacker#prerequisites), so that may be the reason for the choice here.

**Comment by shaunxp20** [comment]
This one is on staging, but there is no front-end piece to this one, so I don't think any manual QAing is necessary. 😃 The CI build is passing, fyi. 👍

**Comment by stenington** [comment]
Yeah, makes sense to me.
