### ISSUE TITLE
Add admin controls to see deleted score details and optionally restore [13,13,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2382]
From #2368, this ticket accomplishes two things:
* add a **View** column on the **Score export** admin page that lets you see score details for a deleted score, and
* add a button on deleted scores to restore the score

<img width="960" alt="73944686-fcc65b00-48c0-11ea-9438-340638f64cdd" src="https://user-images.githubusercontent.com/55319/74546122-0f234300-4f18-11ea-933a-dccf2a6ae6dc.png">

![73944687-fd5ef180-48c0-11ea-8746-281349b664bd](https://user-images.githubusercontent.com/55319/74546120-0e8aac80-4f18-11ea-8743-fea0fe86f76f.png)

### Details & pointers

* Add a **View** column similar to the column on the **Scores** page. You do not have to use the same icon.
* Reuse the existing view for the detailed score information.
* RAs and admins have similar-but-different views of the admin. RAs should **not** have the ability to restore deleted scores.
* The app uses [paranoia](https://github.com/rubysherpas/paranoia) to handle soft-deletions, see that documentation for details.
* Some summary details about scores are calculated and cached, like averages by judging round. Some/most/all? of that happens with [counter_culture](https://github.com/magnusvk/counter_culture). Add tests to ensure recalculation of these things happens when a score is restored, if possible.
* We haven't defined what should happen when you click **Restore this score**. I suggest it should stay on the score detail page with a flash message confirming success or explaining failure, if failure is possible. But use your judgement if something else would work better.

## QA STEPS

Prerequisite: scores that have been deleted

* Log in as an admin, navigate to the "Scores export" page (found in the navigation links on the right side)
* Search for "Include deleted scores" or "Only show deleted scores"
* From the search results, click the View icon (scroll all the way right to the last column in the table) for one of the deleted scores
* Click the "Restore this score" button
* Verify the score has been restored and the submission's score averages and numbers are adjusted correctly

**Comment by hellafitz** [comment]
Add a confirmation popup. Restore flow sounds good.

**Comment by stenington** [comment]
This might be a good ticket to add to the iteration, in terms of thematic cohesiveness with the other work.

**Comment by shaunxp20** [comment]
This one is one staging, I added QA steps too. 👍 🌞

**Comment by mdancho** [comment]
With the admin account I was able to click into score details from the judge profile page, view the score and delete it. I was then able to look up the judge and see the score was deleted, view the details again and restore it.

**Comment by rsgonzal** [comment]
I also tested this one, works as expected!

**Comment by shaunxp20** [comment]
Great, thanks for testing this one, @mdancho @rsgonzal! 🙌 🎈 🎉

**Comment by shaunxp20** [comment]
This one has been deployed to production! 👍
