### ISSUE TITLE
Add admin controls to delete scores [13,8,1.63]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2383]
From #2368, this ticket handles adding a score deletion button for admins.

![73944688-fd5ef180-48c0-11ea-9c88-3011b28fe004](https://user-images.githubusercontent.com/55319/74547143-ab017e80-4f19-11ea-8953-5fe4c31c9918.png)

### Details & pointers
* The button should exist on the page displaying a single score's full details. Admins already have ways to reach that page.
* RAs should not see this button or be able to delete scores.
* The app uses [paranoia](https://github.com/rubysherpas/paranoia) to handle soft-deletions, see that documentation for details.
* Some summary details about scores are calculated and cached, like averages by judging round. Some/most/all? of that happens with [counter_culture](https://github.com/magnusvk/counter_culture). Add tests to ensure recalculation of these things happens when a score is deleted, if necessary.
* We haven't defined what should happen when you click **Delete this score**. I suggest it should stay on the score detail page with a flash message confirming success or explaining failure, if failure is possible. But use your judgement if something else would work better.

## QA STEPS

* Find a submission that has a completed (non-suspicious) score; or score a submission
* As an admin, view the score, you should see a delete score button (at the bottom of the score page)
* Viewing the score as any other user type should not have the delete score button

To verify the back-end delete functionality:

* Find a submission w/ multiple scores, and then delete one of the scores
* Verify the stats get updated correctly - completed scores / averages

**Comment by hellafitz** [comment]
Include a confirmation popup (e.g. do you really want to delete this score?)

**Comment by rsgonzal** [comment]
Deleted a score as an admin, it went away. Currently can not see deleted scores.

Tested on a submission with multiple scored, average was updated correctly.

Logged in as an RA, I do not see the option to delete score.

**Comment by shaunxp20** [comment]
> Deleted a score as an admin, it went away. Currently can not see deleted scores.
> 
> Tested on a submission with multiple scored, average was updated correctly.
> 
> Logged in as an RA, I do not see the option to delete score.

Thanks @rsgonzal! 🎉 🍰 🙌
