### ISSUE TITLE
Mockup: Add deleted scores information to the submission score summary page [8,5,1.6]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2384]
From #2368, this ticket handles adding deleted score information to the page summarizing a submission's scores (`/admin/score_details/<id>/`).

![73944772-22536480-48c1-11ea-91d0-04252607aa50](https://user-images.githubusercontent.com/55319/74547614-64605400-4f1a-11ea-8e61-6d1847260a7f.png)

### Details & pointers
* This ticket currently leaves a lot undefined in terms of design details. Use your judgement in deciding how to display the extra information on the page, but take care that deleted scores are easily distinguishable from non-deleted scores. Put them in their own section, or otherwise carefully differentiate them. Feel free to propose a page structure and ask for sign off from another dev or product person before implementing.
* Deleted scores should have a **View score** link like the non-deleted ones do.
* The app uses [paranoia](https://github.com/rubysherpas/paranoia) to handle soft-deletions, see that documentation for details.

**Comment by hellafitz** [comment]
Steps: get directional input from CET, create  v1 mockups, get feedback, create ticket for v2 implementation

**Comment by stenington** [comment]
It would make sense for this ticket and #2385 to follow similar conventions. Based on the current proposal, that might look something like this:

<img width="1280" alt="Screen Shot 2020-03-17 at 3 38 31 PM" src="https://user-images.githubusercontent.com/55319/76894929-6bee8200-6865-11ea-807a-db10f3a4de64.png">

Add a column that contains the deleted status, and highlight deleted rows, but keep the same heading structure the page currently has.
