### ISSUE TITLE
Mockup: Add deleted scores information to the judge profile page [8,5,1.6]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2385]
From #2368, this ticket is for adding deleted scores information to the judge profiles page, alongside the QF and SF scores info already displayed.

<img width="960" alt="73944776-22ebfb00-48c1-11ea-8040-30b44041bc27" src="https://user-images.githubusercontent.com/55319/74548145-53fca900-4f1b-11ea-8928-017b9452d443.png">

### Details & pointers
* This ticket currently leaves a lot undefined in terms of design details. Use your judgement in deciding how to display the extra information on the page, but take care that deleted scores are easily distinguishable from non-deleted scores. Put them in their own section, or otherwise carefully differentiate them. Feel free to propose a page structure and ask for sign off from another dev or product person before implementing.
* Deleted scores should have a **View** link like the non-deleted ones do.
* The app uses [paranoia](https://github.com/rubysherpas/paranoia) to handle soft-deletions, see that documentation for details.

**Comment by hellafitz** [comment]
Steps: get directional input from CET, create v1 mockup, gather feedback, create v2 implementation ticket

**Comment by stenington** [comment]
My proposal to CET was to go from this:

<img width="1280" alt="Screen Shot 2020-03-16 at 4 42 46 PM" src="https://user-images.githubusercontent.com/55319/76892789-9c342180-6861-11ea-888c-e3e618847941.png">


to this:

<img width="1280" alt="Screen Shot 2020-03-16 at 4 42 22 PM" src="https://user-images.githubusercontent.com/55319/76892801-9f2f1200-6861-11ea-8776-50d5d9d1cf84.png">


The recommendation was to leave scores organized into two sections, Quarterfinals and Semifinals, and add a column that gives a yes/no if the score is deleted. Deleted scores could also be highlighted with a colored background to set them apart visually.

We will be collecting feedback tomorrow.
