### ISSUE TITLE
Onboarded/onboarding student fixer rake task

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2388]
This ticket comes from #2381 to track a rake task we want to write, deploy, and set up to run daily in production. The task will find onboarding students who can be marked as onboarded, and `.touch` the records to let the hooks run and do that updating.

**Comment by stenington** [comment]
I think for QA, @shaunxp20 or I can do something like the following:

1. pick a student and run `student.update_column(:onboarded, false)` in the console
2. run `bundle exec rails onboard_missed_students!` in the console
3. confirm the student you updated is in the output

After deployment, we'll need to add a scheduled job to run the task daily.

**Comment by stenington** [comment]
The above steps worked for me, would love for @shaunxp20 to confirm.

**Comment by shaunxp20** [comment]
> The above steps worked for me, would love for @shaunxp20 to confirm.

I verified locally using the steps above, worked as expected! 🎉  🙌
