### ISSUE TITLE
Mockup 'Don't allow RAs to add or delete teams to an RPE after a certain date' [5,8,0.63]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2390]
After RPE status is officially set, RAs should not be able to change the list of participating teams. They should still be able to change the list of participating judges.

The team wants to prevent a lot of movement within the RPEs. They are communicating that if more teams get added past the registration date of April 21st, their in-person scores will not count.

**Comment by hellafitz** [comment]
Deliverable: create a mockup of turning off (grey out?) the RA controls for adding/deleting teams from an RPE and gather feedback from program team. Create a ticket for solution incorporating feedback.
