### ISSUE TITLE
Theme: developer tools to support the program team's 19/20 season plan

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2392]
The program team is writing down a plan for how to run a TG season in a technical platform sense: what config needs to be set when, when we expect certain types of support questions or need to perform certain types of monitoring, and when the dev team needs to take action behind the scenes, for example.

In general, we want to reduce the amount of developer work coming out of this plan that would have to be performed ad hoc in favor of documented and tested tools that make doing the work a little safer. 

#2363 is an example of this sort of effort, but wasn't scoped to include all the various points of contact between the program team and dev team throughout the season, so I'm opening this theme ticket as a reminder to ourselves that there's more work left to do here.

**Comment by shaunxp20** [comment]
I wonder if it would make sense to add a `dry-run` flag/option to the `fix_submissions` rake task. And then use that list for auditing purposes before the rake task is actually run. I suppose the trouble is if there is a submission in that list that needs to be removed - whether it's better/easier to remove that submission before the rake task runs or after. #random-thoughts 🤔

**Comment by stenington** [comment]
`fix_submissions` as it stands would be hard to offer a dry run for, because it’s a cumulative thing where the final changes depend on the earlier changes it makes in the db. Maybe we could wrap it all in a transaction or something to offer dry run?

**Comment by hellafitz** [comment]
April 2020 plan: https://docs.google.com/spreadsheets/d/1Mx3DlCT62cr_MZAl4C10FiWzaXxIIh4tszubmAMW18c/edit#gid=1850689656

**Comment by stenington** [comment]
I'm creating a document drawing from that April 2020 plan spreadsheet and outlining the state of play for the various developer tasks listed there: https://docs.google.com/document/d/1_rVW24C1-RPGF4V3q3I1kr5Cu3CVqg2PoPt8Eja6s5c/edit#

It's a good exercise to organize my thoughts, and I think might benefit us if/when things get heavy. And it can potentially guide us towards new tickets to create under this theme, if we think that's prudent.

**Comment by stenington** [comment]
[This table](https://docs.google.com/document/d/1_rVW24C1-RPGF4V3q3I1kr5Cu3CVqg2PoPt8Eja6s5c/edit#bookmark=id.4bjkbzrd7e8d) gives a quick snapshot of the tasks I'm aware of and their status in terms of a developer winging it, or having some documented solution or tools, or an admin being able to do it.

**Comment by hellafitz** [comment]
We completed the first round of season improvements. Almost everything has been done that needed to be done for this season. 

Now we're identifying tasks for a second round, some of them with an eye towards next season.

**Comment by hellafitz** [comment]
Ticket for tracking expected dev support tasks for 20/21 TG season is #2523

**Comment by hellafitz** [comment]
For reference: Program Team's 20/21 TG Prep Plan doc https://docs.google.com/spreadsheets/d/1zG8tlBQ_M1hAFEkMnVmS8sBFqCisAaKTsn9IH1NMO4U/edit#gid=761477018
