### ISSUE TITLE
20/21 Bug: Timezones not handled appropriately around RPEs

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2396]
It appears that timezones aren't handled appropriately around RPEs. It was noticed in #2366 that an RA in `Asia/Taipei` could create a 10am event, and an admin would then see that event as 10am CST. 

![74879393-e3d89380-531d-11ea-8c32-09630f0a8899](https://user-images.githubusercontent.com/55319/74971585-5618a900-53ee-11ea-829a-a5f37ac59059.png)
![74879356-ce636980-531d-11ea-93c7-479777e02abe](https://user-images.githubusercontent.com/55319/74971587-5618a900-53ee-11ea-9172-c650eaa0feaf.png)

**Comment by hellafitz** [comment]
This was noticed in Staging. Unconfirmed if this has happened in Production.

Ask Program if RAs have reported any weird things going on with timezones, and their sense of prioritization on this issue.

**Comment by rsgonzal** [comment]
@rsgonzal followup with Ophelie to see if she's heard anything from RAs

**Comment by rsgonzal** [comment]
Ophelie doesn't think it's a big issue. It was mostly around RPEs and hasn't heard complaints from RAs

**Comment by hellafitz** [comment]
Next step: Figure out how timezones should work for the various user types. Figure out if that's indeed the case.

**Comment by hellafitz** [comment]
RAs are the only user type we try to fit visible timezones into their individual timezone. All other users see the system's timezone. 

From a user's pov, what do we think they expect to see?
