### ISSUE TITLE
Theme: config variables and season settings

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2399]
The implications for configuring the app (both through environment variables and admin settings) are not very clear, and we seem to have some old leftover stuff as well. This is a broad theme for clarifying what we might want and starting to identify work to get us there.

One relevant doc is [this spreadsheet on dates config](https://docs.google.com/spreadsheets/d/1Gbe58Jw3yoVSlvMidcfrKGEX8TCcdg30UoE2Q1d5Rew/edit#gid=0)

**Comment by stenington** [comment]
Potentially related tickets: #2250, #1810, #2394

**Comment by stenington** [comment]
#2378 raised a question of what timezone some of these date config settings should be interpreted as. That may be some we want to explore further under this heading.

**Comment by hellafitz** [comment]
Next step: convene and/or request a Season Rollover Program/Ops/Dev conversation, resulting in a plan doc

**Comment by hellafitz** [comment]
Superseded by more specific tickets on TG and TG season launch tasks (and automating them), and removing outdated configuration settings and incorporating tests for required ones.
