### ISSUE TITLE
Update TG Emails that get sent out for RPEs (5,5,1)

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2401]
When a user joins an event or when they are added to an event by an RA, they get sent an email from TG.

The team wants to add messaging about the event status in those emails, letting them know that the status of their email will be finalized after April 21st.

Updated copy is here: https://docs.google.com/document/d/1iU-8y7H1Xl7Q5xf7BsZKpkzAa_EoLAt4Ew5Diu-6G-A/edit#

I pulled out the coded emails, but to edit I used what the user sees.

I have a question about one from Team_Mailer --> Notify added to an event
- not sure if this one is sent out, I think the one being sent is the one from Event_Mailer above

## QA
As an **RA**...
1. create an event if necessary
2. add a judge to your event
3. add a team to your event
4. confirm the judge receives an email titled "You are invited to judge a Technovation Girls event" with the new disclaimer
5. confirm the student(s)/mentor(s) receive an email titled "Your team is invited to attend a Technovation Girls event" with the new disclaimer

As a **team member** (student or mentor)...
1. log in
2. select a regional pitch event to attend
3. confirm the team member(s) receive an email titled "<Team name> has joined a Technovation Girls event: <event name>" with the new disclaimer

**Comment by nickiredescent** [comment]
Tested.
Can confirm that participants joining the event receive the updated emails with the new headers and disclaimers. This is true for team members that were either directly invited to attend or chose an event themselves.

**Comment by rsgonzal** [comment]
This one looks good to me too! Think Ophelie is taking a look tomorrow.

**Comment by ophelieh** [comment]
**Student:** works as expected. 

Side Note: For the student & the RA, the status of the event showed as pending but on the admin event tab the status of the events shows as official or unofficial. 
![image](https://user-images.githubusercontent.com/32206421/76098137-89326f00-5f8e-11ea-8641-6f03a8635002.png)
![image](https://user-images.githubusercontent.com/32206421/76098165-96e7f480-5f8e-11ea-91d1-b71c5d1e8782.png)


**RA:** Everything worked as expected. 

Important Notes:
* For judges though, I would remove the part about RPE vs celebration event as it doesn't really impact them. 
![image](https://user-images.githubusercontent.com/32206421/76098500-30afa180-5f8f-11ea-89a8-26a010fd76cf.png)
* Judges who are participating in a celebration event are asked to NOT score the submission. Does that mean they should be able to view virtual submissions instead? --- I am asking here, and feel free to answer, but will also bring it up to the team as it might be confusing for judges... 

Thank you!!

**Comment by rsgonzal** [comment]
Hey Ophelie! 

- Yes, that's because the admin can change the status at any point. We have a date in the system when it will be switched on for student. I just changed it so that you can go look at the status as a student now!

- For the language for judges, I think we will leave for now. They are currently getting the same email as the student

- I'm not sure if judges at unofficial events can score virtually, we will need to explore!

**Comment by ophelieh** [comment]
Awesome, thanks! 

And judges for unofficial events can score online, that is the issue. We are asking that those judges don't score online this year --- we have shared that with the RAs and will share it with judges at those events. However, they are able to. We were wondering if instead, it could be possible for them to NOT be able to score on the platform but still view those submissions. We will figure it out either way. :)
