### ISSUE TITLE
Mockups: Add admin data to facilitate event official/unofficial decision-making [8,8,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2408]
Related to #2392, the program team has asked for support (in the likely form of some platform tweaks) in determining whether events should be considered official or unofficial. It sounds like what they need to see is which teams/submissions are in which events, and how many of them have completed their submissions. The exact path for getting that information is TBD.

**Comment by stenington** [comment]
In the admin, it seems you can go to **Teams** and add "Event name" as a column, but can't get any submission information there. In **Submissions** you can filter for "Live, official event submissions" and either filter for "Yes, submitted" or otherwise see progress info, but you can't get any further information on the event a submission belongs to.

It seems to me like the shortest path to solving this one is to add bits of event data in "More columns" that let an admin tie everything together as needed, but I would want to confirm that that would work before building it.

**Comment by stenington** [comment]
The next step on this ticket could be mockups, or maybe just a conversation with the program team about what they would currently do, and what they'd like to see?

**Comment by stenington** [comment]
@rsgonzal proposed that the event detail view could also show info on the teams and their statuses, which would be another option here.

**Comment by hellafitz** [comment]
Deliverable: quick check w/ Program Team on direction, then v1 mockups, subsequent feedback from program team, and v2 implementation ticket created

**Comment by stenington** [comment]
3rd option might be adding a counter cache to events that tracks the number of completed submissions and makes that available as a column. That might be combined with suggest #2 for a more detailed view. 

Another possibility is that admins don't care nearly as much about seeing this info if a tool does it for them (#2419), so that should be asked about in the planning for this ticket.

**Comment by rsgonzal** [comment]
Going to check in at technovation meeting to see if we should pursue this. I'm guessing no, since all judging will be online and events are unofficial.

**Comment by stenington** [comment]
I've been emailing with Nick and Ophelie, and can update this ticket soon.

**Comment by stenington** [comment]
The current proposal, based heavily on feedback from @nickiredescent, is to build out the events page this way:

![localhost_3000_admin_events_85](https://user-images.githubusercontent.com/55319/76893073-1a90c380-6862-11ea-873c-331a89338a8c.png)

Currently collecting feedback on this proposal.

**Comment by stenington** [comment]
It would be helpful on the **Events** page to have additional optional columns of "Submitted count" and "Unsubmitted count" to help hone in on the teams that need investigating. Those would need to be implemented as counter caches to facilitate sorting.
