### ISSUE TITLE
Admin judge suspension controls [20,13,1.54]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2411]
Implementation ticket for #2272 

The following are the specs for this implementation:
* add a **Judge suspension** section to the admin participants page for judges (`app/views/admin/participants/_judge_debugging.html.erb`)
* Help text to go in the section:
> Suspending a judge does not mean that their scores will be deleted, but they will not be able to create new ones. Please note any changes you make here in the appropriate tracking sheet.
* The section contains one of two buttons, with confirmation text:
    * **Suspend this judge**: You are about to SUSPEND this judge
    * **Enable this judge**: You are about to ENABLE this suspended judge
* Both are the "danger" color
* create the appropriate admin controller(s), and maybe method(s) on `JudgeProfile`, to back the two actions
* Success should redirect back to the admin participants page for the judge, with the following success messages respectively:
    * This judge has been suspended.
    * This judge is no longer suspended.
* If changing the judge's status isn't successful, probably set a generic "An error has occurred" message on the page
* Adjust the suspension message in `app/controllers/judge/scores_controller.rb` to say "Your account has been suspended, please visit our [FAQs](https://iridescentsupport.zendesk.com/hc/en-us/articles/360036011914-Rules-for-Judges) to learn more about our monitoring process."
* Add tests

## QA Steps

1. Log in as admin
2. Suspend a judge
3. Log in as the suspended judge
4. Confirm you cannot start a score with the correct message
5. Log back in as admin
6. Unsuspend the judge
7. Log in as the judge
8. Make sure you can start a score
9. Log in as an RA
10. Look up a judge, confirm you do not see the suspension controls

**Comment by stenington** [comment]
Mockup screenshots for context. See https://github.com/Iridescent-CM/technovation-app/issues/2272#issuecomment-592214478

<img width="1280" alt="Screen Shot 2020-02-27 at 5 28 36 PM" src="https://user-images.githubusercontent.com/55319/75492901-bc6d7080-5986-11ea-826e-4d0dc317c3c7.png">

<img width="1280" alt="Screen Shot 2020-02-27 at 5 28 42 PM" src="https://user-images.githubusercontent.com/55319/75492905-be373400-5986-11ea-9412-2ad7c8e46b0a.png">

<img width="1280" alt="Screen Shot 2020-02-27 at 5 36 01 PM" src="https://user-images.githubusercontent.com/55319/75493406-c80d6700-5987-11ea-8194-a5afc0d42095.png">

<img width="1280" alt="Screen Shot 2020-02-27 at 5 28 10 PM" src="https://user-images.githubusercontent.com/55319/75493200-5cc39500-5987-11ea-8263-eefdc15eb522.png">

<img width="1280" alt="Screen Shot 2020-02-27 at 5 28 14 PM" src="https://user-images.githubusercontent.com/55319/75493219-66e59380-5987-11ea-80a8-08c2a8c07738.png">

<img width="1280" alt="Screen Shot 2020-02-27 at 5 38 48 PM" src="https://user-images.githubusercontent.com/55319/75493523-0b67d580-5988-11ea-84d8-f9f31871592f.png">

**Comment by rsgonzal** [comment]
Suspension message text: "Your account has been suspended, please visit our [FAQs](https://iridescentsupport.zendesk.com/hc/en-us/articles/360036011914-Rules-for-Judges) to learn more about our monitoring process."  

link: https://iridescentsupport.zendesk.com/hc/en-us/articles/360036011914-Rules-for-Judges

**Comment by rsgonzal** [comment]
Logged in as admin, suspended a judge. Judge could no longer finish their submission

Unsuspended the judge, they were able to get to their previously started submission.

RAs can not see anything about suspension when they click on a judge.
