### ISSUE TITLE
Security: upgrade puma & nokogiri (3,3,1)

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2413]
From #2166 

Upgrade to resolve two alerts: 
* https://github.com/Iridescent-CM/technovation-app/network/alert/Gemfile.lock/puma/open 
* https://github.com/Iridescent-CM/technovation-app/network/alert/Gemfile.lock/nokogiri/open

**Comment by stenington** [comment]
This seems like another good candidate for bringing in to the iteration if there's space.

**Comment by rsgonzal** [comment]
@shaunxp20 anything we need to test here?

**Comment by shaunxp20** [comment]
> @shaunxp20 anything we need to test here?

I think we're good, it was two minor (patch level) gem updates. All the tests are passing; and it's on staging now, so imho if we're using staging and it's working, then it's being tested at some level. 😃 We can talk more about it on Stand tomorrow and see if there are any concerns/objections about just moving it to the Ready to Deploy column. 🌞 🤓 😈

**Comment by stenington** [comment]
I'm also good with the "staging didn't completely explode" version of QAing this one. 👍 It's good to go as far as I'm concerned.

**Comment by shaunxp20** [comment]
> I'm also good with the "staging didn't completely explode" version of QAing this one. 👍 It's good to go as far as I'm concerned.

😎 👍 I'll move this one to the Ready to Deploy column then! 🙌
