### ISSUE TITLE
Epic: Security - upgrade webpacker, webpack, and dependencies after the season (20,20,1)

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2414]
From #2166, and following on #2335 

It looks like upgrading webpacker from 3 to 4 following [this guide](https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md) is likely going to resolve a bunch of security alerts for us. This involves upgrading a couple of tools simultaneously, but I don't see a way around that.

In #2380 we established a way to get jest test coverage, which might be helpful in assessing our confidence in the success of the upgrade. I think there's an open question about how we would approach QA though, which could be anywhere from a rough check that things are probably okay to a fairly detailed (and painful) test of the majority of javascript functionality on the site.

**Comment by hellafitz** [comment]
if we were to split off a groundwork ticket (est. effort 20):
- document 'here's where we use javascript'
- is there a test that covers it?
- TBD: do we patch the holes, triage patching the holes (how risking to live with it as is? is there time to fix it now?), or just document?

**Comment by hellafitz** [comment]
Updated groundwork ticket (est. effort 20):
- identify "critical" platform functionality (e.g. submissions)
- is there an integration test that covers it? 
- if yes it's critical, and no, there's not an existing test, write the test

**Comment by stenington** [comment]
A realistic plan here is to wait until the start of next season, then do the upgrades if we can secure a commitment from the program team to do "exploratory QA" for the crucial functionality of each part of the platform with enough lead time to deal with any potential bugs they uncover, relative to the season schedule.

**Comment by shaunxp20** [comment]
I ran across this site/blog, looks like some good articles on Webpack and Rails (looks like he's writing a guide too), might come in handy when it's time to upgrade and/or just to get more familiar:
https://rossta.net/blog/

😃 📰 🤓 😀

**Comment by hellafitz** [comment]
Completed w/ #2595
