### ISSUE TITLE
Reset the platform for post-surveys & configure them in admin [13,8,1.63]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2415]
Post-surveys for students and mentors need to be configured on the platform. To be done the week of **April 6th**

Surveys in survey monkey:
2020 Technovation Girls Student Post Survey
2020 TG Educator/Mentor Post Survey - Official

* Reset the platform, so all students and mentors are asked to complete 
* Set up the survey collector url with query parameters to collect all the data points outlined in #2310, plus `uid_value` 
* Completion tracking set up, if they've completed the survey the pop up shouldn't show up

~~The [documentation here](https://docs.google.com/document/d/1hVaugqKipnD8pYmCcMl5KWCHrrqBBSr-86MQZTdm5P8/edit#) needs to be updated with instructions for resetting the modal, and instructions on completion tracking.~~ The documentation covers those things.

**Comment by hellafitz** [comment]
Related to #2422, which concerns developer rake tasks

**Comment by rsgonzal** [comment]
Now looking at the week of April 6th.

**Comment by shaunxp20** [comment]
I was going to pick this one up, I have few questions/things to clarify first:

> * Reset the platform, so all students and mentors are asked to complete

Just verifying, is this running that the new rake task from #2422 - `rake surveys:reset_all`?

> * Set up the survey collector url with query parameters to collect all the data points outlined in #2310, plus `uid_value`

Is this done on the Surveymonkey side? Does a developer do that?

> * Completion tracking set up, if they've completed the survey the pop up shouldn't show up

What's involved with this? Is this adding this functionality? 🤔 😄

**Comment by rsgonzal** [comment]
> I was going to pick this one up, I have few questions/things to clarify first:
> 
> > * Reset the platform, so all students and mentors are asked to complete
> 
> Just verifying, is this running that the new rake task from #2422 - `rake surveys:reset_all`?
> 
> > * Set up the survey collector url with query parameters to collect all the data points outlined in #2310, plus `uid_value`
> 
> Is this done on the Surveymonkey side? Does a developer do that?
> 
> > * Completion tracking set up, if they've completed the survey the pop up shouldn't show up
> 
> What's involved with this? Is this adding this functionality? 🤔 😄

**Comment by stenington** [comment]
@shaunxp20 I'm going to use you as a documentation guinea pig. Can you give [this documentation](https://docs.google.com/document/d/1hVaugqKipnD8pYmCcMl5KWCHrrqBBSr-86MQZTdm5P8/edit#) a read and see if you still have questions afterwards? If so, let me know what isn't clear and I'll try to update the docs while answering your lingering questions.

**Comment by shaunxp20** [comment]
Awesome, thanks for clarifying @rsgonzal, and for the documentation, @stenington! 😀 

Seems pretty straight forward! @rsgonzal, I can run the rake task, just let me know when, and for which account types! 👍 😄

**Comment by shaunxp20** [comment]
>     * Reset the platform, so all students and mentors are asked to complete

I ran the rake task, so we should be good to go as far this ☝️ bullet point goes. 👍 😄
