### ISSUE TITLE
Rake task and tests for unsubmitting [5,5,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2418]
We have identified "unsubmitting" submitted but incomplete submissions as a potential developer task this season. This ticket would be for creating a rake task that "unsubmits" a submission or group of submissions based on id or list of ids, with tests. 

[This documentation](https://docs.google.com/document/d/1BEHSSY9gSwKpUNJUZaVSwcixPC6HRPqNVy_33t9p7Ow/edit#bookmark=id.jha3lxost4so) provides some hints about how to unsubmit, and should be updated as part of this ticket as well.

### QA Steps

To create a submission that is submitted but not complete, you will first have to complete it, then submit it, then the platform will allow you to continue editing and you can do something like blank out the app name and save.

In the admin under Submissions, adding "Complete?" and "Submitted?" as _More Columns_ is a good way of confirming your setup and the results of the rake task.

1. Find or create two different submissions that are submitted, but are not complete
2. Ask a dev to run `submissions:submitted_but_incomplete` and confirm that both apps show up in the output
3. Ask a dev to unsubmit one of them with `submissions:unsubmit![<id>]`
4. Confirm that the one you picked has been unsubmitted, while the other hasn't changed

**Comment by stenington** [comment]
Unsubmitting is something we've identified as a possible scenario, but we aren't expecting many teams, if any, to end up in this state. As a manual task, it's not particularly painful. (We're just trying to avoid having to do these sorts of tasks manually, period.)

**Comment by stenington** [comment]
Just noting that the language around a "complete" or "published" submission is sloppy in the code:

* the `complete` scope only looks to see if `published_at` is set
* a submission is `complete?` if all required fields are complete AND it's published
* a submission is `published?` if `published_at` is set
* and `percent_complete` is only 100% if the app has been published

This leads to strange code like
```
TeamSubmission.complete.find_each do |sub|
    if !sub.complete?
        ...
    end
end
```
where you wouldn't think you'd find an not-complete submissions when you've scoped to complete, but you do.

**Comment by rsgonzal** [comment]
Tested with Mike and all is working as expected!
