### ISSUE TITLE
20/21 Rake task and tests for setting event officiality

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2419]
At some point in the season, a determination is made for each RPE whether it counts as official or is considered a "celebration event". Currently an admin would go in and have to flag all official events as official, which could be fairly laborious. 

There are two potential versions of a rake task to help:
1. the best option is if the logic that determines official/unofficial can be captured by the task, and it can categorize all RPEs appropriately. Then an admin would just have to confirm the results of the task by e.g. looking over the admin or an exported CSV.
2. if the logic can't easily be captured, a task that sets all event statuses to official would still be useful, as there are typically far fewer unofficial events, so that gives the admins a leg up on how many RPEs they have to go manually edit.

**Comment by hellafitz** [comment]
Next step: talk to Ophelie about how the official/unofficial distinction will be made. Determine if we could/should try to code that.

**Comment by hellafitz** [comment]
@rsgonzal any update?
