### ISSUE TITLE
Bulk update process for setting semifinalists [20,13,1.54]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2420]
In coordination with the program team, we need to outline how to go about marking teams as semifinalists. In that past, we've taken a CSV and run a rake task that does some complicated checking, but I think that process is unnecessarily clunky and complex.

I think this might boil down to something as simple as the program team giving us a list of submission IDs, and having a rake task that can take that list and do a bulk update of the submissions' `contest_rank`, but it would be good to get confirmation across the board.

**Comment by hellafitz** [comment]
Amy led the creation of the semifinalist list last year. We think she's handed that off but we don't know to whom. 

ID the process owner. Document the process. Determine the best way to bulk update semifinalists.

**Comment by rsgonzal** [comment]
Here is the process from Amy, asked Devin who on program team will own this year:

> So semifinalist picking will be done by program team. (I will help this year with data pulling and sorting stuff) So someone on the program team should be the ultimate approver of this process. The process goes like this:

1. Program team and I meet with cleaned up date. We select semi finalists on a spreadsheet.
2. Program team creates a clean spreadsheet to give to Mike. It usually has the Team ID and Submission ID numbers. (Please confirm with Mike what data is easiest for him to use.) Another person on the program team double checks the spreadsheet before giving it to Mike.
3. Mike makes the changes to the back end. 
4. Someone on the program team logs into the platform to make sure all the selected team are marked as semi finalists on the back end. I usually ask two people to check since we have accidentally omitted people. 
5. Maggie works on a blog post announcing the semi finalist. Program team double checks the blog post at least twice to make sure no one was omitted.

**Comment by stenington** [comment]
Submission ID or "friendly ID" are the most useful things on the dev side. Submission IDs don't show up much (at all?) in the admin, but the friendly id can be found in the url when viewing a submission, e.g. `/admin/team_submissions/coolest-app-by-some-team`. 

I don't know if this year's decision-making process will be based primarily on an admin CSV export, a dataclip, or some other process entirely, but it looks like admin CSV exports don't include ID or friendly ID, so if that will be the basis we should add that in. 

We should not try to reconstruct friendly IDs from team name and app name columns, that would be begging for some minor difference in handling that could end up with the wrong results. 

Also, if the process ends up being some version of "team gets together, makes decisions, then laboriously looks up IDs in the admin" I think we may as well ask that team member to just mark semifinalists in the admin while they're at it. The assumption here is that the decision making process already generates a spreadsheet, and that it's faster to then automatically set things from the data we already have to hand.

**Comment by shaunxp20** [comment]
> I think we may as well ask that team member to just mark semifinalists in the admin while they're at it.

+1 for this (or to at least to explore it further). 😄 I think this could remove the coordination/hand-off/data format/etc. issues, and might be less error prone too. 😊 🤷‍♂ 😬 😂 😃

**Comment by rsgonzal** [comment]
@rsgonzal followup with ophelie

**Comment by stenington** [comment]
RAs are able to filter their Submissions tab by "Contest rank", which is something to keep in mind when designing the process as well.

**Comment by hellafitz** [comment]
Program Team will provide an example semifinalist selection spreadsheet by 4/25

**Comment by hellafitz** [comment]
Semifinalist selection example spreadsheet: https://drive.google.com/open?id=1_3eWrq5QvngKebctW5wYs7-btZLnsrEaum5dIox0KtQ 

The data is pulled by Amy using a dataclip. @rsgonzal following up to get specifics.

**Comment by hellafitz** [comment]
- still waiting on the exact dataclip
- also want to understand the exact process from dataclip to the spreadsheet they provided

Next ticket: Adjust dataclip / export to include the info we need. Create a useful tool for ourselves to take that semifinalist team info and update the database.

**Comment by rsgonzal** [comment]
Meeting with Amy, Nick, Mackenzie & Bryant to figure out how they populate the spreadsheets & how we can help

**Comment by hellafitz** [comment]
Based on discussions the best option appears to be adding the team and submission IDs to the scores page. See #2494

**Comment by stenington** [comment]
I think this was closed prematurely. #2494 was only half of the equation; we don't have a developer tool that can easily consume the ids added to the scores page to set semifinalists, which means it will still be a manual process for this year.

**Comment by hellafitz** [comment]
We have an existing, overly complicated rake task. 

Deliverable: 
Replace it with a new rake task that takes team and submission IDs (from a spreadsheet provided by the Program Team) and marks those teams as semifinalists on the platform. (There's a risk that we're still given a spreadsheet that doesn't have the required/expected data and we have to scramble on a short timeline).

QA would be to go on Production, sort by Contest Rank, and double-check the list.

**Comment by stenington** [comment]
Just a follow-up on the planning discussion: I'm open to a non-rake-task solution here as well, I just proposed the rake task solution because for my skills and familiarity with Rails and Heroku, it seemed the easiest for me to implement and for me to use. But @shaunxp20 if you took this ticket and put something in the admin instead, I'm open to that.

**Comment by stenington** [comment]
This one's ready for code review, with the caveat that I'll need to come back and update documentation if/when it gets accepted.

**Comment by stenington** [comment]
No real QA here I think, I'll either be able to use this tool or I won't, depending on what I'm giving for setting semifinalists today or tomorrow.

**Comment by hellafitz** [comment]
@stenington please add a quick update here to close the loop
