### ISSUE TITLE
20/21 Rake task for unsticking stuck background jobs

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2421]
Background jobs can die and leave admin users stuck with a "your job is processing" notification, when it isn't processing any more. In lieu of a much more complicated solution to tracking background jobs, the proposal here is to build a rake task or something along those lines that can clean up dead jobs if that's at all feasible.

**Comment by stenington** [comment]
This may not be possible. There are two pieces here, the `Job` model that records in the app database a job id, the job status, and the owner, and then the actual ActiveJob that's been sent to sidekiq. We could look up a list of Jobs marked as active for a particular user, but I don't think there's a way to query sidekiq to see if those jobs are still alive or what happened with them.

And we do have some error handling in place that attempts to detect failures and mark failed jobs as such, but clearly it's not bulletproof. 

One option might be to reframe this as something like "create a rake task that clears the running job notification from a user's account whether that job is still alive or not" but I'm not clear on how useful that is. I think typically our admin users are more interested in finding out if the thing will ever finish, moreso than just forgetting about it, and that takes extra work.

**Comment by hellafitz** [comment]
Re-evaluate after season is over (main Q: is this still a pain point for the program team?)

**Comment by hellafitz** [comment]
Reframe: Build a status tracking system for background jobs

**Comment by hellafitz** [comment]
General feeling is that building our admin a custom job status-checking system is less valuable than using data clips (which have status tracking built in). Given the low priority of this ticket to the Program Team - which is leaning hard on slack communication / coordination when people have to use reports - we're going to close this down.
