### ISSUE TITLE
Don't allow judges to switch to mentor mode [13,5,2.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2423]
For this season, mentors are NOT allowed to be judges.

Currently, there is config set up to remove a mentor's ability to switch to judging mode.

When a judge signs up, they are able to see the link to switch to mentor mode. If they click on this link, they will get stuck on the mentor profile because we are not giving them the ability to switch back to judge mode.

We need to get rid of the ability for a judge to switch to mentor mode.

![Screen Shot 2020-03-11 at 12 12 37 AM](https://user-images.githubusercontent.com/22801026/76391722-580ac380-632d-11ea-877c-731c0cfc084d.png)

## QA steps

With `ENABLE_SWITCH_BETWEEN_JUDGE_AND_MENTOR` turned off...

1. log in as a mentor, and make sure you don't have a link to switch to judge mode
2. log in as a judge, and make sure you don't have a link to switch to mentor mode

With `ENABLE_SWITCH_BETWEEN_JUDGE_AND_MENTOR` turned on...

1. log in as a judge, and make sure you can switch to mentor mode and back

**Comment by stenington** [comment]
For now, we just want to ensure that when mentors are prevented from switching to judges by config, that judges are also prevented from switching to mentors to avoid a dead end for them.

**Comment by rsgonzal** [comment]
tested this one with ophelie and mackenzie! Working as expected.
