### ISSUE TITLE
Add deleted scores information to the submission score summary page [13,8,1.63]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2432]
![](https://user-images.githubusercontent.com/55319/76894929-6bee8200-6865-11ea-807a-db10f3a4de64.png)

Things to address in this ticket:

When viewing the score details for a submission...
* This should be for **admins only**
* add deleted scores to all sections: incomplete/complete quarterfinals/semifinals
* add a new cell to each row that says "deleted" if the score is deleted, or nothing if the score is live
* highlight deleted score rows with a pink color (exact pink for you to determine)

Note that the `_scores_table` partial currently gets reused for score display to admins, RAs, and mentors, so take care that only admins see deleted scores.

## QA STEPS

* As an admin, delete a score
* Click Scores from the right-hand nav menu
* Find the team/submission that you deleted a score for, and click the View link
* Verify the deleted score is displayed
* As an RA, view the same page, and verify the deleted score is not displayed

**Comment by stenington** [comment]
Mockups made in #2384

**Comment by shaunxp20** [comment]
This one is on staging, and QA steps have been added too! 👍 😄

**Comment by rsgonzal** [comment]
I can see the page as an admin, not as an RA. Having Mackenzie and Nick take a look too.

**Comment by nickiredescent** [comment]
Tested. Can confirm that deleted scores are not visible to RAs. 
Admins can see which scores were deleted. 
Quick note: Teams who have all their scores deleted will no longer show up on the [Score page](https://technovation-qa.herokuapp.com/admin/scores#/) list.
For example, while [this page](https://technovation-qa.herokuapp.com/admin/score_details/157#/) still exists, there's no direct link to it from the Score page. 
I have tried giving the team a new score and the team is added back to the Score page once they get scored again. The deleted scores are still visible.

**Comment by shaunxp20** [comment]
> Quick note: Teams who have all their scores deleted will no longer show up on the [Score page](https://technovation-qa.herokuapp.com/admin/scores#/) list.
> For example, while [this page](https://technovation-qa.herokuapp.com/admin/score_details/157#/) still exists, there's no direct link to it from the Score page.
> I have tried giving the team a new score and the team is added back to the Score page once they get scored again. The deleted scores are still visible.

Thanks for the thorough QA effort, @nickiredescent! 🎉 💝 🍰

From #2382, right now deleted scores are only accessible/viewable through the "Score export" tab/page. Hopefully that helps clarify? 🤔 Imho, this is confusing, so I created #2473 to make deleted scores accessible from the main scores page. 😄

**Comment by shaunxp20** [comment]
Btw, I updated my previous comment, hopefully it's more clarifying than confusing now! 😊 😅 😁

**Comment by rsgonzal** [comment]
Thanks for creating that @shaunxp20 !
