### ISSUE TITLE
Add deleted scores information to the judge profile page [?,5?,?]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2433]
![](https://user-images.githubusercontent.com/55319/76892801-9f2f1200-6861-11ea-8776-50d5d9d1cf84.png)

When viewing the participants summary page for a judge...
* this should be for **admins only** (but I don't think RAs see the scores section at all)
* add deleted scores to both sections of the scores area, quarterfinals and semifinals
* add a column titled "Deleted?" that says yes or no for each row
* highlight deleted score rows with a pink color (exact color for you to choose)

Mockups from #2385 

## QA STEPS

Prerequisites: a judge needs to have deleted scores

* Login as an admin, and click "Judges" (from the navigation links on the right-hand side of the page)
* Find and view a judge with deleted scores
* Verify the deleted scores are being displayed
* Verify the deleted scores are only displayed to admins

**Comment by shaunxp20** [comment]
This one is on staging, I added QA steps too. 👍 🌝

**Comment by mdancho** [comment]
Able to see that a score has been deleted. 
<img width="1235" alt="Screen Shot 2020-03-26 at 1 40 32 PM" src="https://user-images.githubusercontent.com/52216992/77694544-6b41a400-6f67-11ea-8f5d-b0f22ebeff9d.png">

**Comment by rsgonzal** [comment]
This one also works as expected!

As an RA, I can not see scores on a judge profile. When a score is deleted, it gets removed from their score page as well.

**Comment by shaunxp20** [comment]
Thanks for testing this, i appreciate it! @mdancho @rsgonzal 🙇 :bowtie: 🍪 🍰 🎂

**Comment by shaunxp20** [comment]
This one has been deployed to production! 👍
