### ISSUE TITLE
Bug: deleting a judge with scores breaks the score exports admin screen [8,13,0.62]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2440]
**Describe the bug**
As an admin, if you delete a judge who had scores by visiting their participant page and clicking the delete button, the score exports page will no longer work if you choose the "Include deleted scores" or "Only show deleted scores" filter options.

**To Reproduce**
1. Go to **Scores export** as an admin
2. Select "Only show deleted scores" and click **Search**
3. Note the **Judge name** of the first judge
4. Go to **Participants** and look up that judge
5. Click **view**
6. Scroll to the bottom and click **Delete <judge> from Technovation**
7. Return to the **Scores export** page
8. Select "Only show deleted scores" and click **Search**
9. You should get an error

**Expected behavior**
Deleted scores associated with a deleted judge should not appear in the Scores export list.

<img width="1280" alt="Screen Shot 2020-03-24 at 2 21 53 PM" src="https://user-images.githubusercontent.com/55319/77462696-d9a52b80-6dda-11ea-96c8-26a709a33260.png">

### QA

Once this is live, you should be able to follow the steps to reproduce without getting an error at the end. Instead that judge's scores should no longer appear on the **Scores export** page.

**Comment by hellafitz** [comment]
Confirm that:
- deleting Judges is a capability we want to allow
- There are deleted scores from deleted Judges - and that causes a problem. Do we need to see those? Or do we only need to see deleted scores from non-deleted Judges?

**Comment by rsgonzal** [comment]
Do not plan to delete judges during current season, will only suspend

Always a possibility that a judge will email us to delete their account, so this issue could arise.

**Comment by stenington** [comment]
Yeah, so my take away is that we do have to handle this edge case, but we would not expect to see deleted scores from a deleted judge. And actually, if the user is requesting to be deleted that should be a hard delete anyway, I think?

**Comment by stenington** [comment]
We're also uncertain what should happen if a judge who had scored submissions then asks to be deleted. It would be nice to preserve their scores and just sub in some sort of default judge info, but are the comments they left considered their personal data that should be deleted if they want to be removed?

**Comment by stenington** [comment]
We can mitigate the biggest risk here and set aside some bigger picture conversation for later. In this ticket, let's make it so that deleting a judge who has scores (by clicking the delete button at the bottom of their participants page) doesn't break the score exports page. Deleted scores from active judges are okay, deleted scores from deleted judges should no longer be shown, period.

**Comment by rsgonzal** [comment]
Confused by your "live" comment! Do we test this on QA @stenington ?

**Comment by stenington** [comment]
@rsgonzal yeah sorry, I meant “live on staging”. This is testable on staging.

**Comment by rsgonzal** [comment]
ok! I didn't choose the first judge, because it would've messed up testing of another ticket.

I deleted judge mackenz and everything seems to be working!

**Comment by shaunxp20** [comment]
This has been deployed to production! 🚀 👍 😄
