### ISSUE TITLE
Make dates configurable in Welcome Email to students [8,8,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2443]
Email subject line: Welcome to Technovation 2020!

Registration deadline did not change with the updated configuration dates. It's not that important for this season, but may want to consider pulling from config for next season.

![Screen Shot 2020-03-20 at 1 54 53 PM](https://user-images.githubusercontent.com/22801026/77517812-f91f7100-6e39-11ea-880d-bac63a6f57c4.png)

## QA STEPS

1. Set these configuration settings on QA:

```
DATES_REGISTRATION_OPENS_YEAR
DATES_REGISTRATION_OPENS_MONTH
DATES_REGISTRATION_OPENS_DAY
```

```
DATES_OFFICIAL_START_OF_SEASON_YEAR
DATES_OFFICIAL_START_OF_SEASON_MONTH
DATES_OFFICIAL_START_OF_SEASON_DAY
```

```
DATES_TEAM_REGISTRATION_DEADLINE_YEAR
DATES_TEAM_REGISTRATION_DEADLINE_MONTH
DATES_TEAM_REGISTRATION_DEADLINE_DAY
```

2. Register as a new student, and verify the dates in the welcome email are correct (based off the configuration settings in step 1)

**Comment by hellafitz** [comment]
Deliverable: Make the first 3 bulleted dates pull from config (the 4th already does)

**Comment by shaunxp20** [comment]
I made these dates dynamic via configuration settings. The new configuration settings are:
`DATES_OFFICIAL_START_OF_SEASON_YEAR`
`DATES_OFFICIAL_START_OF_SEASON_MONTH`
`DATES_OFFICIAL_START_OF_SEASON_DAY`

`DATES_TEAM_REGISTRATION_DEADLINE_YEAR`
`DATES_TEAM_REGISTRATION_DEADLINE_MONTH`
`DATES_TEAM_REGISTRATION_DEADLINE_DAY`

The "registration opens" date was already a configuration setting (`DATES_REGISTRATION_OPENS_X`), we just weren't using it in the welcome email.

I added the names of these new configuration settings on both QA and production. We'll just need to update the values of these settings before this goes live.

Also in the welcome email is a link to an info-graphic that I assume will need to be updated as well:
https://venngage.net/ps/bAAeKGLlsk/2019-technovation-important-dates-and-milestones

🤔 😃

**Comment by shaunxp20** [comment]
This one is on QA, and QA steps have been added as well. 😄 👍

**Comment by rsgonzal** [comment]
@shaunxp20 does official start of season need to be set in the past for me to get a welcome email?

**Comment by rsgonzal** [comment]
Ok interesting! I didn't get a welcome email at all until i set the official start of season & team registration deadline. Not sure which one of the two triggered it.

For the registration opens date, i remember @stenington said we had to keep it in the past - so it has never been changed from that 2018 date. I don't remember what the technical reasons were, this was my note "Leaving this set in the past effectively means it doesn't do anything, but it's still referenced in the code so can't be removed yet"

**Comment by shaunxp20** [comment]
The welcome email was trying to get and parse the dates of the new config settings, but the dates weren't set yet; this was causing an error which prevented the welcome emails from being sent, doh! 😄 

Regarding `DATES_REGISTRATION_OPENS`, those config settings are definitely relevant now for the welcome email, but I'll let Mike respond b/c I'm not sure what that comment means. Although, if it's going to cause an issue I can just make a new set of config settings too, not a big deal. 😄

**Comment by stenington** [comment]
@shaunxp20 Take a look at how `registration_opens` is used [here](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/jobs/register_to_current_season_job.rb#L21).

**Comment by shaunxp20** [comment]
> @shaunxp20 Take a look at how `registration_opens` is used [here](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/jobs/register_to_current_season_job.rb#L21).

I don't have the historical knowledge around this, this looks like expected behavior - if a user has already registered for the season, don't register/send them welcome emails/etc. again. Think I'm missing something. Should I just remove this code, so it "doesn't do anything"/always returns true like it does now? Not sure what to do.

**Comment by stenington** [comment]
I don't have deep historical knowledge around this either, other than seeing it last season and deciding it didn't seem to do anything useful to us. But it looks to me like setting it to a future date could cause a user to get continually re-registered in the right circumstances, which I think we'd want to avoid.

**Comment by shaunxp20** [comment]
Sounds like the thing to do is to remove that code, any objections?

**Comment by stenington** [comment]
Nope!

**Comment by shaunxp20** [comment]
This one is back on QA, but I don't think it needs testing. I tweaked the code around ensuring there aren't any duplicate registrations (which prevents duplicate emails and stuff). If someone gets duplicate registration emails, that would be a bug; and I'm not sure how to recreate this potential bug scenario.

Anyhow, I'll leave this in the QA column just in case someone wants to play with it. 😸

**Comment by rsgonzal** [comment]
so we kept 'DATES_REGISTRATION_OPENS' and now it only affects the dates in the email?

**Comment by shaunxp20** [comment]
> so we kept 'DATES_REGISTRATION_OPENS' and now it only affects the dates in the email?

I just looked and from what I can tell, that's correct, it will only get used for this email; it doesn't look like it's used anywhere else. 😄

**Comment by rsgonzal** [comment]
did a final check, looks good!
