### ISSUE TITLE
Reduce word minimum on judge feedback [8,5,1.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2444]
Judges are currently required to leave at least 40 words of feedback on each section of the judging rubric.

"People are copy and pasting the same test or giving poor feedback just to be able to submit their score. We do not need to force judges to have to leave more than 20 words of feedback. "

Proposal to reduce word minimum to 20 words in all sections, EXCEPT for the 'Overall Impression' section which should stay at 40 words.

## QA STEPS

* As a judge, score a submission
* Verify at least 20 words are required for the following sections: 
  * Ideation
  * Technical
  * Pitch
  * Entrepreneurship
* Verify at least 40 words are required for the "Overall Impression" section 
* Verify you can finish/submit the score

**Comment by shaunxp20** [comment]
This one is on staging, I added QA steps too! 😃

**Comment by nickiredescent** [comment]
Tested. Can confirm that the word minimums for each section are as described.

**Comment by rsgonzal** [comment]
@shaunxp20 not sure what's going on with my scoring. it won't let me complete and says there's something wrong with ideation. i'll tag in slack

**Comment by shaunxp20** [comment]
> @shaunxp20 not sure what's going on with my scoring. it won't let me complete and says there's something wrong with ideation. i'll tag in slack

Great catch @rsgonzal! 🥇 There are additional validation checks on the last/review page, doh! I just updated those. I'll let you know when it's on staging again. 👍 😃

**Comment by shaunxp20** [comment]
@rsgonzal This one is back on staging, the issue you found should be fixed now. 🤞 😀

**Comment by rsgonzal** [comment]
thanks, @shaunxp20 ! Looks good to me! I asked Mackenzie to take a final look.

**Comment by mdancho** [comment]
All good! Confirmed that all sections require a minimum of 20 words before being able to submit, except overall which required 40. Also required numerical scores for each section before being able to finish the score.
