### ISSUE TITLE
Expand test coverage for critical platform functions [40,20,2]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2445]
from #2414 and epic #2166

Updated groundwork ticket (est. effort 20):
- identify "critical" platform functionality (e.g. submissions)
- is there an integration test that covers it? 
- if yes it's critical, and no, there's not an existing test, write the test

**Comment by stenington** [comment]
As a first step, I wanted to update capybara to get rid of test deprecation warnings and make the test suite a little easier to work with. The upgrade resulted in a few unexpected test failures.

It seems like we had a few tests loading pages with Vue components without javascript, and then asserting things about the uninitialized Vue templates. Those tests seem to fail with capybara 3.x, which is a good thing. Running those tests with javascript (and potentially making a few extra tweaks) gets them passing again.

**Comment by stenington** [comment]
A couple of notes for posterity:
* if a non-js test is failing because it can't find an element, but you can see the element in e.g. a `puts page.html`, check that it's not embedded in a Vue component
* if you convert a test to use javascript and suddenly it becomes flaky, turbolinks might be getting in your way
    * with turbolinks active, the url can change before the page does so looking at the url doesn't guarantee page content has updated
    * add an assertion for some piece of page content ( a header, or a link, etc.) that lets you know the next page loaded

**Comment by stenington** [comment]
Working on mapping from the javascript packs to a rough idea of where that code appears on the site [here](https://docs.google.com/spreadsheets/d/1_Q2pwfgq3gkzLROhmEQk1TWO6FJSjH0920ejqTYHTvA/edit#gid=0)
