### ISSUE TITLE
Ongoing Support [8,8,1]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2446]
- help Rox setup Staging for exploratory QA on Judging
- other unknown stuff

**Comment by stenington** [comment]
Lots of `Google API error: request denied` in the logs for dev, staging, and production. Looks like our cloud console account ended a 12 month free trial and needed to be upgraded to a paid account.

**Comment by stenington** [comment]
Did some investigation into dropping lowest scores and the implications for certificates that could fall into this category. I found that dropped scores are accounted for in certificate calculations, and we have a tool to drop lowest scores but should confirm the logic it contains conforms to the team's plan for this year.

**Comment by shaunxp20** [comment]
I looked at these two support issues:
 * a user who couldn't login to their account/sign up as a mentor - OUTSTANDING/ NEED MORE INFO
 * Users who couldn't create an account b/c they already had an existing account - RESOLVED
