### ISSUE TITLE
Theme: Improve admin search from ZenDesk inquiries

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2452]
Platform Wishlist ID #124, https://docs.google.com/spreadsheets/d/1kDiSJVWCX_4NtASSua29m5X60cMy0qhAFcajUUIwU-s/edit#gid=0

Desired Solution: Improved user/participant and mentor search functionality on admin interface	

Presenting Problem: "When we receive a Zendesk ticket, the requestor is not always sending the message from the email address that we have on file in the platform. If they include the user's name exactly as it appears in the system, we can sometimes find them. If they provide the user's email address as it appears in the system, we can usually find them (but not always). 

It would be helpful to improve search functionality on the admin side, to cut down on time and energy spent locating exact records. "	

Stakeholders Affected: Admins directly, students, parents, RAs, and mentors indirectly

Potenital Solution: A suggestion would be to have separate first and last name, and email address fields for students, instead of having one field for all. Also, entering a specific name doesn't weed out people with parts of that name (i.e. an exact name can provide hundreds if not thousands of results that are tangentially related. Selecting a country as a filter in the search can help reduce the results, but country/region is not always provided in ZD tickets, and in larger countries, common names still are hard to locate)	Kate F.	

Date Submitted: 3/18/20

Product Team Notes:
Next step: PM discovery, moving toward a research spike on use cases and potential solutions. What kinds of things are being searched for, what are specific examples, what is noise in the results? Context: introducing specific, more advanced tech for a search index is a big project. What are the other options short of that?

**Comment by hellafitz** [comment]
Meeting w/ Kate and Rox scheduled for 4/15

**Comment by hellafitz** [comment]
Meeting notes from the call today, https://docs.google.com/document/d/1MJuD5T82E6TXHw05w6KTiFEKAOuD7zqPMfOoyI4q-QI/edit

**Comment by hellafitz** [comment]
@rsgonzal to ask Kate for specific examples of searches she's had issues with, as well as the correct result (we'll use this to test other query options/approaches)

**Comment by hellafitz** [comment]
@rsgonzal where does this stand?

**Comment by rsgonzal** [comment]
Kate is providing me with examples this week.

**Comment by hellafitz** [comment]
@rsgonzal please update here

**Comment by rsgonzal** [comment]
Sorry! The doc was updated with examples: https://docs.google.com/document/d/1MJuD5T82E6TXHw05w6KTiFEKAOuD7zqPMfOoyI4q-QI/edit

**Comment by hellafitz** [comment]
Intention: See how far we can get without introducing new infrastructure

Spike:
- review the doc and refine the specific changes she suggest (looking at the backend for what's going on in these circumstances)
- pull out specific recs and how doable they are on top of Postgres (vs doing in a search index)

Then:
- discuss the recs, break out tickets we want to move forward and prioritize w/ Kate's input
- implement and gather feedback
- revisit potential remaining ROI for search index

**Comment by hellafitz** [comment]
Epic: #2599
