### ISSUE TITLE
Spike: can the RA/admin list of cities be updated? [13,13,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2455]
From #2313 

We have a static list of cities that gets used to provide location filtering options in the admin, but it doesn't line up perfectly with where our users say they are on sign up. This spike would try to answer these questions:

* How many cities are in our database but not the static list?
* Is there an updated static list that includes some or all of these cities?
* Is there a process to do that update? Are other factors getting in the way of keeping it updated?

And maybe even:

* Is it possible to create a hybrid where we supplement a static list with additional entries from our database?

**Comment by stenington** [comment]
## Update process

The original library has update instructions here: https://github.com/loureirorg/city-state#update-the-database-from-maxmind. I've confirmed that they work, but they update the data files **in place**, which explains [our fork of the project](https://github.com/Iridescent-CM/city-state).

As a bonus, if we updated our fork to match the latest version of the main repo, they've added the ability to [add missing cities](https://github.com/loureirorg/city-state#missing-cities-and-wrong-names) among other things. I'm not sure if the affordance is powerful enough to let us handle disputed territories though.

But the way we're using this library is still backwards. There's no guarantee that the countries/states/provinces/cities in this library cover all the data points in our database, and it wouldn't make sense to have a query interface that can't actually get you everything in your database, I think.

More investigation on how bad that discrepancy is to come.

**Comment by stenington** [comment]
## Data access

These numbers were pulled up somewhat quickly and could be double-checked, but right now it's looking like the following.

If you just search by country, the country filter should let us access about **95%** of the users in the database.

If you add in the state/province filter, that drops down to about **63%** of the users getting returned in any country + state/province combo.

If you search by country, state/province, and city, it drops further to about **55%** of the users getting returned.

**Comment by stenington** [comment]
## Initial set of questions with commentary inline

* How many cities are in our database but not the static list?
    * **answering that slightly differently, the more specific the search, the fewer users that get returned. Searching by country, country + state/province, or country + state/province + city returns 95%, 63%, and 55% of all the users respectively.**
* Is there an updated static list that includes some or all of these cities?
    * **there are updates, but the problem isn't as simple as missing entries**
* Is there a process to do that update? Are other factors getting in the way of keeping it updated?
    * **yes, there's a way to incorporate updates, and yes there are factors getting in the way (see details in comments below)**

And maybe even:

* Is it possible to create a hybrid where we supplement a static list with additional entries from our database? 
    * **Maybe? That doesn't seem like the right solution.**

**Comment by stenington** [comment]
If I restrict the user pool to the 2020 season the numbers stay very similar: 99%, 66%, 55%.

**Comment by hellafitz** [comment]
Next (related) steps : 
- Shaun finish #2536, Mike review
- New ticket: write up synthesis w/ potential approaches to a solution and the associated tradeoffs (audience: PMs and LT)
- PMs facilitate conversation w/ PT/LT
