### ISSUE TITLE
Generate certificates for July 6th release [40,?,?]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2457]
This is the task to generate the certificates, using the content from #2249 (update certificate templates)

2020 May/June plan: https://docs.google.com/spreadsheets/d/1Mx3DlCT62cr_MZAl4C10FiWzaXxIIh4tszubmAMW18c/edit#gid=1850689656

**Comment by hellafitz** [comment]
@shaunxp20 please confirm this is done, add 'added during iteration' and move to Done. Thx!

**Comment by shaunxp20** [comment]
> @shaunxp20 please confirm this is done, add 'added during iteration' and move to Done. Thx!

Yes, this was done, moving it to Done! 👍 😄
