### ISSUE TITLE
Don't display 'View Your Certificate' if no certificate is available [5,5,1]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2458]
from #2271

![Screen Shot 2020-04-03 at 12 12 25 AM](https://user-images.githubusercontent.com/22801026/78334619-ec3d0480-7540-11ea-9d80-8723149111a8.png)

The "View your certificate" button shouldn't appear if the judge has no certificates. This is probably a hangover from when judge's would be shown a button that generated the certificate when clicked. I suspect [this is the offending line](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/guards/display_certificates.rb#L6) at this point.

### QA STEPS
Prerequisites: the "Scores & Certificates" setting needs to be enabled

* As an admin, find a judge without a certificate; or find one with a certificate (via the Certificates tab/page) and then suspend this judge
* Then impersonate the judge and make sure the judge doesn't see a "View your certificate" button on their dashboard

**Comment by shaunxp20** [comment]
Btw, I see another file/message for when an account doesn't have a certificate: [app/views/dashboards/_no_certificates.erb](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/views/dashboards/_no_certificates.erb) which mentions the finalists, and a link to stay informed.

I wonder...
a) if we should incorporate some of this into the page when a judge/account does have a certificate
b) if the program team would want to change/update this content for this season, and/or if CET would want to update this for judges this season

🤔 😃

**Comment by stenington** [comment]
It's unclear to me whether a judge with no certificates should see `app/views/judge/dashboards/onboarded/_certificates.en.html.erb` with no button, or whether they should see `app/views/dashboards/_no_certificates.erb`. I was assuming we'd delete the line in `DisplayCertificates` mentioned in the ticket description, which I think would accomplish the latter. But if the first option is the desired choice, then @shaunxp20 your PR seems like the way to go, although I wouldn't mind adjusting `DisplayCertificates` anyway to get rid of the old, unnecessary logic.

**Comment by shaunxp20** [comment]
I made some changes based off our meeting earlier today, which if I understood correctly:
 - if `display_scores` is turned on and a cert exists for the judge -> display the certs page
 - if `display_scores` is turned on and a cert does not exist for the judge -> display the no certs page

Hopefully I got that right! 😸 😅 

I also added a condition for this edge case:
 - if `display_scores` is turned on, and a cert does exist for the judge, but the judge is suspended -> display the no certs page

This would happen if we generate certs, and then suspend a judge. 😄 🤓

**Comment by shaunxp20** [comment]
This one is on the QA site, and QA steps have been added too! 👍 😀

**Comment by rsgonzal** [comment]
Checked this one as well and looks good.

Opened #2503 to edit the copy on this page since it has outdated links we don't have replacements for.

**Comment by shaunxp20** [comment]
Thanks for testing this! @nickiredescent @rsgonzal 🥳 🎈 🙌 

Thanks for opening that ticket too, @rsgonzal! 💯 👍
