### ISSUE TITLE
Expand test coverage for critical platform functions [20,20,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2461]
Part of #2166, continuing from #2445: continue expanding integration test coverage of critical platform functionality using [this document](https://docs.google.com/spreadsheets/d/1_Q2pwfgq3gkzLROhmEQk1TWO6FJSjH0920ejqTYHTvA/edit#gid=0) as a guide.

**Comment by stenington** [comment]
The suggestion here is to focus on registration and sign up, simple successful paths first.

**Comment by stenington** [comment]
Another set of specs to write would be specs expanding on PR #2456 to include large RPEs where RAs actually assign subsets of submissions to judges.

**Comment by shaunxp20** [comment]
Closing this one out. We're going through the [Javascript packs document](https://docs.google.com/spreadsheets/d/1_Q2pwfgq3gkzLROhmEQk1TWO6FJSjH0920ejqTYHTvA/edit#gid=0) and more tickets will come out of that. 📈 📏 👩‍🏫
