### ISSUE TITLE
Generate an html snippet that can be pasted onto the blog to announce semifinalists [20,13,1.54]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2462]
At the end of the season, we post winners on the blog somewhere. Rather than risking human cut and paste errors when creating that page, we should be able to figure out a way to export something that can be used more directly on the blog, like an HTML snippet with all the winners or the like. 

The first step here is figuring out where in the Wordpresses this page is likely to go, and what means of copying data over is most useful.

### QA Steps

For confirming that the url is admin-only...

1. log in as [student/mentor/RA]
2. visit https://technovation-qa.herokuapp.com/admin/semifinalist_snippet.txt directly
3. ensure you are redirected to your dashboard with an error message like "You don't have permission to go there!"

For confirming the actual snippet, it will look something like...

1. set up semifinalists as needed
2. while logged in as admin, visit https://technovation-qa.herokuapp.com/admin/semifinalist_snippet.txt
3. copy the snippet into a blog post (or whatever will be used) on technovation.org
4. view that page and confirm it looks correct in terms of layout
5. compare the teams listed to the semifinalists listed in the admin and make sure all teams are reflected

**A note on production usage**

I would expect we would QA the actual blog post again before posting, in terms of comparing the expected semifinalists against the ones put into the snippet.

**Comment by hellafitz** [comment]
@rsgonzal to connect with Maggie

**Comment by rsgonzal** [comment]
scheduled a meeting for 4/10

**Comment by rsgonzal** [comment]
This would be a blog, just like this page: https://www.technovation.org/blogs/technovation-families-finalists-regional-winners/

For reference last year's page: https://technovationchallenge.org/2019-semifinalists/

Organized by division, then by country, lists team name & app name

For this year, she was able to figure out how to do two columns or create a table

**Comment by rsgonzal** [comment]
<img width="1192" alt="Screen Shot 2020-04-10 at 4 27 05 PM" src="https://user-images.githubusercontent.com/22801026/79021107-8b5c9000-7b2f-11ea-8ab2-57d2847271fd.png">
<img width="889" alt="Screen Shot 2020-04-10 at 4 26 53 PM" src="https://user-images.githubusercontent.com/22801026/79021110-8ef01700-7b2f-11ea-8de0-a147b5b1f34a.png">

**Comment by rsgonzal** [comment]
@mjaris could you get us a mockup of what you would want the page to look like? Not with real data but how it would be set up with regions, country, and names. Layout & formatting. We want to create small html snippet and try it to see if it works.

**Comment by rsgonzal** [comment]
from maggie:

> Okay, this is kind of convoluted but here's the mockup: https://www.technovation.org/blogs/19456/ (Password: "table time")
I put together two simple tables  (one for each division) using data from last year in a one column format, and then, below that, in a 2-column format. I do have concerns about the effectiveness of a table this long, and am also 100% open to other table designs or not using a table at all and doing it manually like we used to. For a point of reference, I'm assuming we'll have somewhere in the neighborhood of 250-280 semifinalists, which looked like this last year: https://technovationchallenge.org/2019-semifinalists/
Anyway, I guess I'm saying here's what I came up with but I will not at all be offended if the dev team thinks it's horrible/not do-able and wants to try something else!!

**Comment by hellafitz** [comment]
General page content comments for @mjaris 
- we recommend you include a simple table of contents or some other way to provide a shortcut for users to get to what they're interested in (e.g. a hyperlinked "Senior Division Semifinalists | Junior Division Semifinalists" that goes to anchor links). We'll build in anchor links to division and each country to allow for future upgrades on this front. 
- our user research project underlined that girls feel a real sense of accomplishment just from submitting, and they suggested we acknowledge that milestone more. This page is a good experience if your team has made it to the next round, but is a bit of a deadend if you didn't. How about a video message for all teams at the top that celebrates everyone for making it this far?

**Comment by hellafitz** [comment]
- We'll go with the two-column, responsive template
- use text wrap inside each cell of the table to address the issues Maggie flagged with long names
- build in anchor links to Junior Division and Senior Division, as well as to each country (sub)header

**Comment by mjaris** [comment]
Thanks @hellafitz, all of that sounds great. We're discussing what's possible re: pulling together a video as a marketing team, and definitely appreciate that feedback. Anchor links + table of contents are a great idea too. 

Thank you!

**Comment by stenington** [comment]
I just looked at the actual Wordpress interface on the example page, and the way it does a 2-column layout is not what I expected. I was imagining pasting one HTML snippet into a field that would achieve a 2-column layout (which still may be possible) but in the example page, there's some sort of layout builder thing with a 2 column option, and you can paste in content for each column separately.

Anyway I think we should get clear on what we're cutting and where we're pasting it on this one.

**Comment by stenington** [comment]
I don't think this link will work if you're not logged in to our wordpress but [here I'm playing around](https://www.technovation.org/?post_type=blogs&p=19568&preview=true) with a responsive 2 column layout that can be pasted straight into a blog post without worrying about the more complicated layout stuff. Looks like our blog has Bootstrap 4.0 in place, which gives a reasonable starting point.

**Comment by hellafitz** [comment]
Deliverables:
- We'll go with the two-column, responsive template
- use text wrap inside each cell of the table to address the issues Maggie flagged with long names
build in anchor links to Junior Division and Senior Division, as well as to each country (sub)header
- the generated table should be provided to Maggie via an admin-only url (or the result of a rake task)

**Comment by stenington** [comment]
Here's what I have at the moment: 

An admin url looking like this:
<img width="960" alt="Screen Shot 2020-05-21 at 6 01 52 PM" src="https://user-images.githubusercontent.com/55319/82610863-316ad380-9b8d-11ea-878b-8c99c36cc3c4.png">

can be copy and pasted into a blog post to get this:
![Screen Shot 2020-05-21 at 5 43 49 PM](https://user-images.githubusercontent.com/55319/82610750-f2d51900-9b8c-11ea-8b08-8e66428ca1ad.png)

[This link](https://www.technovation.org/blogs/mikes-test/?preview_id=19568&preview_nonce=bf86754b83&_thumbnail_id=19064&preview=true), if you're able to log in on the Wordpress, might let you see the actual blog preview.

**Comment by stenington** [comment]
As a process note for using this later, there **may be the need for manual cleanup**. Depending on who makes it to semifinals, it looks like we do currently have submissions with no country. They should still appear on the page, but I would think we would want to figure out where the team comes from and move their entry to the appropriate country section.

Some of the country names may also be weird. We store country codes in the database (mostly) and I'm passing them to a library that then looks up country names, but some of them may not be the way we actually want to name the country. I'm hoping that can also be hand-edited after pasting in the snippet without too much pain.

**Comment by rsgonzal** [comment]
This is looking good!

Just wondering, how to teams make it through without a country listed?

**Comment by stenington** [comment]
I don't know. I just saw that that was the case by taking all the current quarterfinalists, setting them to semifinalist locally, and then viewing the snippet to see if there were any problems. At first the whole thing blew up because there were submissions with no country, so I changed the code to at least put them on the page.

We can launch a bit more of an investigation into which current submissions have no country and try to remedy that ahead of time. That might be worth doing. Then again if none of those teams make it to semifinals it's a moot point at least for this particular purpose. What do you think?

**Comment by stenington** [comment]
A concern I have about this snippet strategy is that there will be a final round of template tweaks to make once we see what the actual final semifinalist data looks like when layed out, but that will take a whole build-test-deploy cycle to get to production. On the calendar, choosing semifinalists and posting a blog post happens in one or two days. Something to keep in mind when QAing I guess?

**Comment by stenington** [comment]
I added a table of contents per section for the countries... it gets intense if there's lots of data:

![Screen Shot 2020-05-22 at 11 47 35 AM](https://user-images.githubusercontent.com/55319/82685404-231ac700-9c22-11ea-9b11-281ea17d1a75.png)

This was generated again by marking all quarterfinalists as semifinalists so the real page will have far fewer countries.

**Comment by rsgonzal** [comment]
> We can launch a bit more of an investigation into which current submissions have no country and try to remedy that ahead of time. That might be worth doing. Then again if none of those teams make it to semifinals it's a moot point at least for this particular purpose. What do you think?

So I think there may only be two teams without a country: https://docs.google.com/spreadsheets/d/15cppllD2GVlprAsscqOHXdovkKw2ABjL7okV0tYNs14/edit#gid=714640594

**Comment by rsgonzal** [comment]
> For confirming that the url is admin-only...
> 
> 1. log in as [student/mentor/RA]
> 2. visit https://technovation-qa.herokuapp.com/admin/semifinalist_snippet.txt directly
> 3. ensure you are redirected to your dashboard with an error message like "You don't have permission to go there!"

Can confirm this is what i see 👍

**Comment by rsgonzal** [comment]
No tweaks, looks great! But junior division didn't go into two columns, might be because not enough data
<img width="719" alt="Screen Shot 2020-05-29 at 4 57 06 PM" src="https://user-images.githubusercontent.com/22801026/83434572-9c1ed900-a3ef-11ea-8311-5e7393874f7e.png">
<img width="1127" alt="Screen Shot 2020-05-29 at 4 57 00 PM" src="https://user-images.githubusercontent.com/22801026/83434578-9de89c80-a3ef-11ea-9324-273e7cf2654e.png">

**Comment by stenington** [comment]
Oh, yeah, the algorithm is very simplistic so it does a better job of balancing the columns with more countries.

**Comment by shaunxp20** [comment]
This has been deployed! :thumbsup: :shipit: :balloon: :smiley_cat:
