### ISSUE TITLE
Update copy for judges when 'in between rounds' by early June [5,3,1.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2464]
Judges are shown a different screen when the platform is set to "In Between Rounds"

Below is the current page, numbers need to be updated in first line. Language about World Pitch will also have to change
![Screen Shot 2020-04-07 at 1 12 21 PM](https://user-images.githubusercontent.com/22801026/78715434-44259380-78d2-11ea-920b-871db8a741f8.png)

## QA STEPS

* As an Admin update "Content & Settings" -> Judging -> BETWEEN ROUNDS
* Next find and impersonate a judge
* Verify the new content changes/updates on the judge's dashboard

**Comment by hellafitz** [comment]
This will be visible June 8-15

**Comment by hellafitz** [comment]
Mac and Rox working on new content

**Comment by rsgonzal** [comment]
Copy is here: https://docs.google.com/document/d/103AfV2Zfz3kMNlk6-KQigafeX89liqpix5V-jwCZzxs/edit

Waiting on final approval

**Comment by rsgonzal** [comment]
![Screen Shot 2020-05-06 at 9 46 12 AM](https://user-images.githubusercontent.com/22801026/81204766-906dfd00-8f7e-11ea-946a-d4b455f9f4d8.png)

Text updates:
Top

- If you had the time to judge this round, we sincerely thank you for supporting teams across 20+ countries this season. We appreciate you volunteering your time to give insightful and compassionate feedback on the hard work of Technovation’s young change makers.  

What happens next?

- **If you scored 5 submissions or more**, you will be invited to judge in our semifinal round starting on June 15th 
- **Semifinals will take place from June 15th - June 26th**, the number of scores you finish will determine what judge certificate you receive.
- Your scores from the semifinal round will **determine the top 10 teams** that will be finalists in our World Summit event in August of 2020! 

Judge Levels
- **Login after July 6th to view and download your certificate**
- 5 submissions: Certified Technovation judge 
- 5-10 submissions: Head judge
- 10+ submissions : Judge Advisor

**Comment by shaunxp20** [comment]
This one is on the QA site, and QA steps have been added too! 👍 😁

**Comment by ophelieh** [comment]
Hi all, 

This looks good! I have a couple edits for the text though. 
* Remove 4 days early! 
![image](https://user-images.githubusercontent.com/32206421/81834917-3f728180-9507-11ea-92ab-6b4e3d3f595a.png)

* Replace 20+ countries by 60+ countries --- (we had submissions from 62 countries) 
![image](https://user-images.githubusercontent.com/32206421/81835306-b9a30600-9507-11ea-9db1-097fa43d412a.png)


Thank you!! :)

**Comment by shaunxp20** [comment]
Thanks for taking a look, and for the feedback @ophelieh! I made the changes and it's ready for you to review again (on the QA site), when you get a moment. :smiley:

**Comment by ophelieh** [comment]
Looking good!!! Thank you Shaun!! :) 

Side note, which probably requires a different ticket, it looks like the link for Slack is no longer active and needs to be updated. 
![image](https://user-images.githubusercontent.com/32206421/81955148-59779700-95cf-11ea-96ee-12be09f63980.png)

**Comment by Bryant-Gomer** [comment]
Judge Certificate page looks great. I double checked that the dates are correct, and I agree with Ophelie's copy suggestions.

**Comment by rsgonzal** [comment]
Thanks for reviewing!!

**Comment by shaunxp20** [comment]
Thanks for taking a look! @ophelieh @Bryant-Gomer 😄 🙌 🍰 🍨 😁

**Comment by shaunxp20** [comment]
This has been deployed to production! 🎉 🦖 💃🎈
