### ISSUE TITLE
It-21 ongoing support, including TG submission deadline [13,13,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2466]
See https://docs.google.com/spreadsheets/d/1Mx3DlCT62cr_MZAl4C10FiWzaXxIIh4tszubmAMW18c/edit#gid=1850689656

May 4th  Submission deadline (Submissions due at 19:00 UTC)

**Comment by rsgonzal** [comment]
Mailchimp TG 2020 judge list is a lot longer than it should be. 

It looks like some names were populated before the sign up date. This is probably users that have both a mentor and judge account? Can you help confirm that? Is there a way to edit listserv to pull users with only a judge account

**Comment by shaunxp20** [comment]
> Mailchimp TG 2020 judge list is a lot longer than it should be.
> 
> It looks like some names were populated before the sign up date. This is probably users that have both a mentor and judge account? Can you help confirm that? Is there a way to edit listserv to pull users with only a judge account

I'm not sure if this helps, but it looks like in the admin, on the Judge tab/page, you can select "has mentor profile" - I think this could tell us which judges also have a mentor account, and also judge only accounts. 🤔 🤷 😁 😀  🏞️ 🚶🌳

**Comment by rsgonzal** [comment]
> I'm not sure if this helps, but it looks like in the admin, on the Judge tab/page, you can select "has mentor profile" - I think this could tell us which judges also have a mentor account, and also judge only accounts. 🤔 🤷 😁 😀 🏞️ 🚶🌳

Yes! This looks right.

So total judges for 2020 is ~1800 which matches up with mailchimp. Judges without mentor profile is ~900, which matches up with mailchimp for new sign ups since judge registration open date

The team only wants to see judges without mentor profile in the listserv since they don't want to email those we're not allowing to judge (people with mentor profiles). Not sure we can edit the list now? Also if this is outside support, I can open a new ticket!

**Comment by rsgonzal** [comment]
Asked @shaunxp20 to take a look at last comment from #2465

Looks like:
- shaun deleted scores on staging
- the team and i did some scoring
- i noticed the score count was wrong on the scores page 
- shaunreset/wiped out the totals/averages
- now this page is wrong again

![]()

**Comment by shaunxp20** [comment]
> Asked @shaunxp20 to take a look at last comment from #2465
> 
> Looks like:
> 
>     * shaun deleted scores on staging
> 
>     * the team and i did some scoring
> 
>     * i noticed the score count was wrong on the scores page
> 
>     * shaunreset/wiped out the totals/averages (i forgot to mention we did new scoring we wanted to keep!)
> 
>     * now this page is wrong again
> 
> 
> ![Screen Shot 2020-04-24 at 11 44 29 AM](https://user-images.githubusercontent.com/22801026/80261268-d225ac00-863e-11ea-90e9-ae6f96df2144.png)

I looked at this, and I'm not seeing an easy way to recalculate the totals/averages. 😦 😢 Do you know if there is an easy way to do this, @stenington? 🤔

**Comment by shaunxp20** [comment]
Issue from Slack, a submission that hasn't been started yet appears to be incorrectly displayed in the search results on the Submissions page.

https://app.slack.com/team/U6HDNTN6A

**Comment by shaunxp20** [comment]
> > Asked @shaunxp20 to take a look at last comment from #2465
> > Looks like:
> > ```
> > * shaun deleted scores on staging
> > 
> > * the team and i did some scoring
> > 
> > * i noticed the score count was wrong on the scores page
> > 
> > * shaunreset/wiped out the totals/averages (i forgot to mention we did new scoring we wanted to keep!)
> > 
> > * now this page is wrong again
> > ```
> > 
> > 
> > ![Screen Shot 2020-04-24 at 11 44 29 AM](https://user-images.githubusercontent.com/22801026/80261268-d225ac00-863e-11ea-90e9-ae6f96df2144.png)
> 
> I looked at this, and I'm not seeing an easy way to recalculate the totals/averages. 😦 😢 Do you know if there is an easy way to do this, @stenington? 🤔

It pains me to suggest this, but I'm wondering if the best thing to do would be to hard delete all the scores and start over. I think it could provide more confidence that things are working correctly on staging. 🤔 😕 🤷 😐

**Comment by rsgonzal** [comment]
> It pains me to suggest this, but I'm wondering if the best thing to do would be to hard delete all the scores and start over. I think it could provide more confidence that things are working correctly on staging. 🤔 😕 🤷 😐

I think this will be ok. Let's just start from scratch!

**Comment by rsgonzal** [comment]
> Issue from Slack, a submission that hasn't been started yet appears to be incorrectly displayed in the search results on the Submissions page.
> 
> https://app.slack.com/team/U6HDNTN6A

Is it possible to see their submission history? it's possible they uploaded everything, submitted, then deleted everything? Seems pretty odd though.

**Comment by shaunxp20** [comment]
> > Issue from Slack, a submission that hasn't been started yet appears to be incorrectly displayed in the search results on the Submissions page.
> > https://app.slack.com/team/U6HDNTN6A
> 
> Is it possible to see their submission history? it's possible they uploaded everything, submitted, then deleted everything? Seems pretty odd though.

Sounds plausible. I see their submission has a `published_at` date of: `Mon, 27 Apr 2020 01:54:23 PDT -07:00`, this is why they're incorrectly showing up in the search results. Sounds like a bug as to how/why it got into this state. 🤔 🤓

**Comment by stenington** [comment]
> I looked at this, and I'm not seeing an easy way to recalculate the totals/averages. 😦 😢 Do you know if there is an easy way to do this, @stenington? 🤔

Depends on what you think is easy, but the `fix_counts` rake task should fix the score counts. `scores:set_score_summaries_of_completed` will fix score averages for completed submissions, and I guess incomplete submissions having scores should be an edge case so it might be all you need.

> It pains me to suggest this, but I'm wondering if the best thing to do would be to hard delete all the scores and start over. I think it could provide more confidence that things are working correctly on staging. 

I agree. When in doubt, put data in staging the same way it gets into production, which is human beings using the interface to do stuff.

**Comment by shaunxp20** [comment]
> I agree. When in doubt, put data in staging the same way it gets into production, which is human beings using the interface to do stuff.

+1, makes sense to me. How do you feel about taking this one on, @stenington? I feel like at this point, it should just be done by someone who knows what they are doing! 😂 But I can also give it a go, I just don't want to mess up staging again! 🤦 😁

**Comment by stenington** [comment]
@shaunxp20 sure, I can step in.

@rsgonzal I ran something to fix counts and averages, so maybe staging already looks a little better, but I'm also happy to totally clear out scores to start fresh, your call.

**Comment by rsgonzal** [comment]
This looks good to me! Amy is concerned it's not calculating scores correctly. While I don't think that's the case, should we just reset everything again just in case?

**Comment by stenington** [comment]
Sure, what does "reset everything" mean in this context? Fully delete all scores? Delete everything, start with a blank database? Something in between?

**Comment by stenington** [comment]
Ophelie reports that two users who previously had accounts have seemingly had their accounts go missing.

**Comment by stenington** [comment]
Couldn't find any evidence of the accounts, deleted or not, or any sign up attempts by those email addresses on the platform.

**Comment by rsgonzal** [comment]
> Sure, what does "reset everything" mean in this context? Fully delete all scores? Delete everything, start with a blank database? Something in between?

Let's talk about this tomorrow!

**Comment by rsgonzal** [comment]
This may or may not be a staging thing. But I came across this user that has a 2020 certificate. Maybe we generated it manually, which is why it's showing up? Looks like they participated in 2019 and 2020, which is why it looks suspicious to me.

**Comment by stenington** [comment]
@rsgonzal It looks like that user only participated in 2019 to me, so I agree it's an odd scenario for them to have a 2020 certificate. That said, an admin can generate a 2020 certificate for anyone, so it's not necessarily a system bug.

Are you concerned that when we auto-generate certificates, people who weren't active in 2020 will get 2020 certificates?

**Comment by rsgonzal** [comment]
Happy Cog is asking if we use a list of countries for TF/TG platform sign ups. If so, is it something we could share with them?

**Comment by stenington** [comment]
For TG we don't have a list, we have them type in anything and check it against either Google Maps or Bing. For TF, we use the `pycountry` library, which is a python packaging of what is ultimately ISO country data, I believe: https://www.iso.org/obp/ui/#search

**Comment by stenington** [comment]
A few items came up at the tail end of the iteration: we had two brief platform alerts right around the submission deadline, we had the calendar item to push submissions to complete, a little last minute adjustment to that plan, and a misunderstanding around how our tool to push submissions to complete worked that needed to get resolved.

**Comment by stenington** [comment]
To elaborate: the adjustment to the plan for pushing teams to complete was that it was written as something that just needed to happen once at one moment in time, but that's not quite the nature of it. There's a window in which final pieces of submissions roll in, or small problems with registrations are resolved, and during that time there can be new submissions made ready to push to complete. The minor misunderstanding stemmed from the way the tool works, which is that it tries to resolve registration problems and team onboarding problems before making its own determination about which teams to push, whereas the program team had created their own list of teams to push.

What we ended up doing was running the tool to push teams in a local environment on production data first, then comparing that list against the program team's list. They were close enough that it was useful to run the tool in production. I then unsubmitted a fake test submission (to prevent judges from having to deal with seeing test data), and the program team came up with a workaround of their own for moving a few more submissions across the line afterwards.

**Comment by stenington** [comment]
Also, a platform unknown we discussed was whether a submission the wouldn't otherwise qualify could be pushed to complete, or whether it is required that all underlying problems be addressed before moving it forward. For example, a submission uploaded by a mentor with no student accounts attached is technically ineligible on the platform, but sometimes we see such submissions and want to make exceptions for them. It's unknown whether the judging screens can actually handle that, and so right now the safest route is to find a way to give the platform what it wants (in this case, getting at least 1 student registered), even though it would be more expedient from an admin point of view to more directly allow exceptions.

**Comment by rsgonzal** [comment]
> Also, a platform unknown we discussed was whether a submission the wouldn't otherwise qualify could be pushed to complete, or whether it is required that all underlying problems be addressed before moving it forward. For example, a submission uploaded by a mentor with no student accounts attached is technically ineligible on the platform, but sometimes we see such submissions and want to make exceptions for them. It's unknown whether the judging screens can actually handle that, and so right now the safest route is to find a way to give the platform what it wants (in this case, getting at least 1 student registered), even though it would be more expedient from an admin point of view to more directly allow exceptions.

@stenington are there currently any of these scenarios we need to check in on? Or did the team add a student to them?

**Comment by stenington** [comment]
@rsgonzal Nick was going to try to add students and/or resolve onboarding issues as necessary to clear up the submissions with those problems.
