### ISSUE TITLE
Update Rebrand banner text with covid changes text [5,3,1.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2471]
We can repurpose the rebrand announcement banner to give update on program changes.
Current banner:
![Screen Shot 2020-04-03 at 1 38 29 PM](https://user-images.githubusercontent.com/22801026/78756908-72d25700-7930-11ea-899b-a61c5832a693.png)

New text:
Important: Required Virtual Participation & COVID-19 Updates
Please read our message about the impact of the coronavirus on the 2020 Technovation Girls season. [Learn more](https://www.technovation.org/covid-19/).

**Learn more** link: https://www.technovation.org/covid-19/

## QA STEPS ##

* Visit https://technovation-qa.herokuapp.com
* Verify the COVID-19 banner/content

**Comment by stenington** [comment]
I think the `ENABLE_REBRAND` config that controls this banner should be renamed appropriately as part of this ticket.

**Comment by shaunxp20** [comment]
This one is on the QA site, and QA steps have been added too! 👍 🌞

**Comment by devincdillon** [comment]
I have QA'ed and it looks good :)
