### ISSUE TITLE
Allow admins to see submissions w/ all deleted scores on main scores page

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2473]
If a submission's scores have **all** been deleted, that submission won't be displayed on the main scores page anymore. We should make those submissions/deleted scores accessible from the main scores page. One way to do this would be to add an option to include deleted scores, and/or an option to only show submissions w/ only deleted scores.

**Comment by stenington** [comment]
How would that work though? The main scores page is showing submissions, not scores. If you look up a submission and click through, you do see deleted score info now.

**Comment by shaunxp20** [comment]
> How would that work though? The main scores page is showing submissions, not scores. If you look up a submission and click through, you do see deleted score info now.

Ah, I was going off this comment: https://github.com/Iridescent-CM/technovation-app/issues/2432#issuecomment-611631603. Teams w/ all deleted scores don't show up on the Scores page anymore. I can update the description to make it clearer. 👍

**Comment by hellafitz** [comment]
Need to align on dev approach and specific reqs

**Comment by stenington** [comment]
@shaunxp20 Can you add steps to reproduce the issue to this ticket? I tried doing what I thought it meant and didn't see the submission disappear from the page so I think I'm making some wrong assumptions.
