### ISSUE TITLE
Add help text to test code on judging screens [8,3,2.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2479]
As a judge, I want to be able to find the instructions on how to test the source code for the submission I am judging. 

As all judging will be online, the team wants to reduce the amount of inquiries they receive from judges. They anticipate questions about testing the source code.

Proposal is to add a line of text on this section of the judging screens:

![Screen Shot 2020-04-14 at 12 52 01 PM](https://user-images.githubusercontent.com/22801026/79819194-54ac2400-833e-11ea-97ca-026efef183d6.png)

Add text under code: “_Click [here](www.technovationchallenge.org/judge-resources) for instructions to test source code_”
link: www.technovationchallenge.org/judge-resources

### QA STEPS
* As a judge, score a submission
* On the Technical section, verify the new link/content for testing source code

**Comment by shaunxp20** [comment]
This one is on the QA/staging site, QA steps have been added as well. 😄

**Comment by nickiredescent** [comment]
can confirm that the help text is showing in the expected place and that it links to the proper resource

**Comment by ophelieh** [comment]
Worked as expected

**Comment by kate-technovation** [comment]
This looked and worked great! Thank you.

**Comment by rsgonzal** [comment]
also checked, looks good!

**Comment by shaunxp20** [comment]
Thanks for testing this one everyone! Y'all rock! 🎉 🙌 🍰 🍨
