### ISSUE TITLE
Update Cloudflare middleware [8,8,1]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2480]
It looks like our Cloudflare middleware runs in dev, test, and prod. I think it only needs to/should run in prod.

Some notes/thoughts:

The middleware we're using is from a six year old snippet/gist:
https://gist.github.com/mattheworiordan/9828493

It might be good to switch to a gem for this functionality, I found two gems:

 * https://github.com/modosc/cloudflare-rails
 * https://github.com/customink/actionpack-cloudflare

One advantage of a gem is that it would be trivial to use/apply it to the production environment only; and another benefit is that (at least one of them) seems to be actively maintained.

Also, some of our builds/tests fail in the Cloudflare middleware:
 * [6245](https://circleci.com/gh/Iridescent-CM/technovation-app/6245)
 * [6237](https://circleci.com/gh/Iridescent-CM/technovation-app/6237)
 * [6215](https://circleci.com/gh/Iridescent-CM/technovation-app/6215)

It would be good to eliminate this middleware layer in our test environment to see how/if it's affecting our tests.

**Comment by stenington** [comment]
I don't think there's a way to test this one before it reaches production, really. Production is where Cloudflare is being used and this middleware should kick in.
