### ISSUE TITLE
Update 2020 certificate templates [8,1,8]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2482]
Using what we found out in #2470, update the certificate templates.

This work is actually underway already.

## QA

**For student certificates**
1. Log in as an admin
2. Search for **Profile type: Students**, **Team Matching: Matched with a team**
3. Choose any student from the results and view
4. Generate one each of the available certificates: participation, completion, and semifinalist
5. Use the "See certificate" links that appear under **Current certificates** to view the actual certificate for each (you may need to refresh the page to see them all)
6. Confirm each certificate is correct, visually and information-wise

**For mentor certificate**
1. Log in as an admin
2. Search for **Profile type: Mentors**, **Team Matching: Matched with a team**
3. Choose any mentor from the results and view
4. Generate one or more mentor appreciation certificate(s) for the mentor
5. Use the "See certificate" link(s) that appear under **Current certificates** to view the actual certificate(s) (you may need to refresh the page to see them all)
6. Confirm each certificate is correct, visually and information-wise

**For judge certificates**
1. Log in as an admin
2. Search for **Profile type: Judges**
3. Choose any judge from the results and view
4. Generate one each of the available certificates: judge advisor, head judge, and certified judge
5. Use the "See certificate" links that appear under **Current certificates** to view the actual certificate for each (you may need to refresh the page to see them all)
6. Confirm each certificate is correct, visually and information-wise

**Comment by stenington** [comment]
@rsgonzal @shaunxp20 I just realized the problem with my "let it work on Heroku but be broken locally" approach, which is that part of our test suite tries to generate certificates, so with it broken locally, tests will no longer pass locally.

**Comment by stenington** [comment]
@shaunxp20 I have a proposal in #2495 for how we might get around this. In general I don't like reducing dev/prod parity, but in this case I don't see a great way around it. The only way I have found to get the certificate templates working on my machine seems to mess up their embedded fonts, and we would either have to accept the font changes in production or I would have to live with the changed templates locally, being careful to never commit them, which I don't want to do.

**Comment by rsgonzal** [comment]
program + audra are good with the actual certificates!

**Comment by rsgonzal** [comment]
@stenington could you (if you haven't already) open a ticket for the followup to this, please? :)

**Comment by stenington** [comment]
Thanks for the reminder @rsgonzal, opened #2501
