### ISSUE TITLE
Logging out redirects user to Sign In page [8,8,1]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2484]
Some Judges have been confused by the page they see when they've logged out. The content is primarily intended for students. 

Currently when any user logs out it takes you back to the 'sign up' page. Instead, it should go to the 'sign in' page. Also add the COVID banner to that 'sign in' page. 

### QA Steps

1. log in as a judge
2. click the log out button
3. confirm you're on the sign in page, not the sign up page

**Comment by rsgonzal** [comment]
Wow. this page makes so much more sense. I LOVE IT.

**Comment by shaunxp20** [comment]
This has been deployed to production! 👍
