### ISSUE TITLE
Write integration tests for admin Content & Settings controls [20,13,1.54]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2487]
Write integration tests covering the admin Content & Settings section. This could range from a basic "able to change a simple setting" happy path, to a number of tests covering much more complex season scenarios. That part is TBD.

**Comment by hellafitz** [comment]
- create a map together
- define the "basic path"
- cover as much as you can within the available time
- include documentation/notes about the things you don't cover so we can expand testing there in the future (this could be in the form of a new ticket)

**Comment by stenington** [comment]
@shaunxp20 I'm curious how you would structure tests for this ticket. 

To my mind, the thing I care about is that when the user makes a series of selections, reviews it, and saves it, the appropriate values on `SeasonToggles` are updated to reflect those choices. So my knee-jerk reaction is to write integration tests where I manipulate the UI to make selections, review and save, and then assert against `SeasonToggles` for the values I would expect. You've called it out before though when I wrote assertions that peeked behind the curtain, rather than only asserting against what the user is able to see. So that's my first question: what would you query against?

Secondly, what do you think about exercising each setting individually versus making a larger batch of changes and assertions at once? I've read advice that recommended having fewer integration tests that do more in one go to try to minimize the time penalty you incur with slower integration tests, but the trade off then is less granularity when they fail.

Below are notes for myself on the basic correspondences between the settings UI and `SeasonToggles`:

## Registration
**Basic tests**
For each checkbox, test that the checkbox enables/disables `SeasonToggles.<type>_signup?`

**Additional considerations**
I don't think the platform actually obeys this setting for judges or regional ambassadors.

## Notices
**Basic tests**
For each text field, the text entered ends up in `SeasonToggles.dashboard_text(:<type>)`

**Additional considerations**
Handling of special characters?
I don't believe the platform makes use of these notices in all the dashboards.

## Surveys
**Basic tests**
For each user type, values put into the fields end up in `SeasonToggles.survey_link(:<type>, <key>)` for the appropriate keys.

## Teams & Submissions
**Basic tests**
*Forming teams allowed* should control `SeasonToggles.team_building_enabled?` and *Team submissions are editable* shoud control `SeasonToggles.team_submissions_editable?`

## Events
**Basic tests**
*Selecting regional pitch events allowed* should control `SeasonToggles.select_regional_pitch_event?`

## Judging
**Basic tests**
The selected radio button should end up in `SeasonToggles.judging_round`

## Scores & Certificates
**Basic tests**
*Scores & certificates accessible* should control `SeasonToggles.display_scores?`

**Comment by stenington** [comment]
Just following up on my own thinking from yesterday: I guess an approach I didn't fully consider might be to write a test where the admin sets a setting and the appropriate user type logs in to confirm whatever is supposed to happen happens. That won't be possible for things like notifications that don't currently show up anywhere, but if those tests had already existed we wouldn't have been able to remove the notifications without also realizing the admin was now slightly broken, so maybe that's the way to go.

**Comment by shaunxp20** [comment]
> @shaunxp20 I'm curious how you would structure tests for this ticket.
> 
> To my mind, the thing I care about is that when the user makes a series of selections, reviews it, and saves it, the appropriate values on `SeasonToggles` are updated to reflect those choices. So my knee-jerk reaction is to write integration tests where I manipulate the UI to make selections, review and save, and then assert against `SeasonToggles` for the values I would expect. You've called it out before though when I wrote assertions that peeked behind the curtain, rather than only asserting against what the user is able to see. So that's my first question: what would you query against?

Ha, yeah, thanks for pointing this out. I think all the examples I've seen use the `expect(page).to` style for assertions, so I think that's just the /way/. But I couldn't find any hard and fast rules on this, so I think its pretty much just in the spirit of feature specs to do it this way. It definitely wouldn't be a blocker to do it another way, bigger picture, just getting some integration tests around this will be a win.

> Secondly, what do you think about exercising each setting individually versus making a larger batch of changes and assertions at once? I've read advice that recommended having fewer integration tests that do more in one go to try to minimize the time penalty you incur with slower integration tests, but the trade off then is less granularity when they fail.

Yeah, I think testing the settings in mass would be good/comprehensive enough. And then maybe individual specs for the different judging scenarios (off, qf, sf, etc.) to show that it enables/disables certain settings would be good too, imho.

**Comment by shaunxp20** [comment]
> Just following up on my own thinking from yesterday: I guess an approach I didn't fully consider might be to write a test where the admin sets a setting and the appropriate user type logs in to confirm whatever is supposed to happen happens. That won't be possible for things like notifications that don't currently show up anywhere, but if those tests had already existed we wouldn't have been able to remove the notifications without also realizing the admin was now slightly broken, so maybe that's the way to go.

I don't know, I think a boundary has to be somewhere, I think just verifying that the settings are saved is fine and would be a nice unit of tests; beyond that seems out of scope for this ticket, imho.
