### ISSUE TITLE
Write integration tests for admin suspicious scores section [13,8,1.63]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2488]
In the admin, suspicious scores are flagged and displayed in a special top section of the Scores page:

<img width="960" alt="Screen Shot 2020-04-23 at 5 36 12 PM" src="https://user-images.githubusercontent.com/55319/80152052-fe7ef100-8588-11ea-8569-cf89d2281681.png">

Write integration tests covering that.

**Comment by hellafitz** [comment]
If we find a bunch of weird edge cases, such that it expands beyond the estimated effort, log that and we'll create a new ticket as needed.

**Comment by shaunxp20** [comment]
This one doesn't need any manual testing, so I moved it to "Ready to Deploy". :thumbsup: :smile:
