### ISSUE TITLE
Add team and submission ids to admin Scores page [?,5,?]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2494]
In the admin, add team id and submission id as "More columns" options on the Scores page.

I don't think it hurts if RAs end up having those columns as well, although limiting it to admins only would also be fine.

### QA Steps

1. log in as an admin
2. go to Scores
3. add Team ID and Submission ID as "More columns"
4. click Search
5. confirm that you see both ids in the results
6. export as CSV
7. confirm you see both ids in the export
8. log out, log in as an RA
9. go to scores
10. confirm that you do not see Team ID or Submission ID as an option for "More columns"

**Comment by hellafitz** [comment]
Confirm this info doesn't give away the score URL

**Comment by stenington** [comment]
Since information leakage is a concern, I just made the added IDs available to admins only, not RAs.

**Comment by nickiredescent** [comment]
Tested and can confirm that the team and score ID's are now accessible columns for admins in both the platform and csv export.
Can also confirm that these are not options available to RAs. Team ID is visible in the team page URL. Score ID is not found anywhere.

**Comment by rsgonzal** [comment]
Also checked this, looks good!

**Comment by shaunxp20** [comment]
This has been deployed to production! 👍
