### ISSUE TITLE
Add Thunkable help text on student submission

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2498]
Thunkable has changed some things on their end and students must submit extra information for judges to properly view their code.

The team wants to edit the submission page in two places:
1. When they choose thunkable: https://technovation-qa.herokuapp.com/student/team_submissions/example-by-example-team?piece=development_platform
![image (6)](https://user-images.githubusercontent.com/22801026/80628187-d3bbef00-8a05-11ea-8ec8-d2c51c0c938a.png)

- Remove the first blue box on how thunkable works
- Replace text in second blue box
**Important instructions for submitting Thunkable projects**
Please carefully read over [this article](https://iridescentsupport.zendesk.com/hc/en-us/articles/360046965014-Using-Thunkable-BEFORE-YOU-SUBMIT-please-do-this-) for instructions on submitting Thunkable Projects. There are important instructions going over app settings to ensure that your submission is viewable to judges.
- link goes to: https://iridescentsupport.zendesk.com/hc/en-us/articles/360046965014-Using-Thunkable-BEFORE-YOU-SUBMIT-please-do-this-

2. Where they must enter the link to their source code: https://technovation-qa.herokuapp.com/student/team_submissions/example-by-example-team?piece=source_code_url
![image (7)](https://user-images.githubusercontent.com/22801026/80628844-d539e700-8a06-11ea-8adc-09f8c57ec0a0.png)
- Added text at the bottom: Please ensure that you have read over [these instructions](https://iridescentsupport.zendesk.com/hc/en-us/articles/360046965014-Using-Thunkable-BEFORE-YOU-SUBMIT-please-do-this-) on submitting Thunkable projects. They go over important details to ensure that judges are able to view your Thunkable submission.
- link goes to: https://iridescentsupport.zendesk.com/hc/en-us/articles/360046965014-Using-Thunkable-BEFORE-YOU-SUBMIT-please-do-this-

@stenington here is what the team asked for, Nick mentioned removing the blue box is not high priority if we just want to focus on added/changed text. For the second change, is this screen unique to thunkable? I think the other platforms upload a file?

@nickiredescent please review this!

## QA

QA here is to confirm copy changes as specified above.

**Comment by nickiredescent** [comment]
looks good to me. Thanks for the last minute support!

**Comment by stenington** [comment]
Ok, I'm looking at this now.

**Comment by stenington** [comment]
This one's ready for testing!

**Comment by nickiredescent** [comment]
This is working as drafted. Thanks so much for the last minute help, it's much appreciated!

**Comment by rsgonzal** [comment]
Rebecca and I also looked over this one, good to go!
