### ISSUE TITLE
Edit screen judges & mentors see when they do not have a certificate [8,3,2.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2503]
Not everyone gets a certificate at the end of a season and currently those users would be seeing an outdated screen.

<img width="1228" alt="Screen Shot 2020-04-28 at 11 46 38 AM" src="https://user-images.githubusercontent.com/22801026/80651077-0d9eec80-8a2a-11ea-818d-c400b7ddfa6c.png">

It looks like multiple groups see this content block:
- mentors who were not matched with a team
- suspended judges
- judges that scored less than 5 submissions

Thank you for your participation in the 2020 Technovation season.
You can see this year's finalists at [technovationchallenge.org/season-results](technovationchallenge.org/season-results.).
The 2021 season will open in the Fall.
Stay informed about important dates and updates. [Sign up for our newsletter.](https://confirmsubscription.com/h/d/15B1DBF38F40C405)

We asked Bryant for feedback on this screen. At the very least, the two links need to be checked/changed.

We should also verify is anyone else sees this screen

## QA STEPS

As an admin, turn on the "Scores & Certificates Accessible" setting.

* Find a fully on-boarded judge with < 5 submissions, or a suspended judge, login as this judge
* Verify the new [content/url changes](https://github.com/Iridescent-CM/technovation-app/issues/2503#issuecomment-631577982) on the judge's dashboard
* You can also verify this content gets shown to a fully on-boarded mentor that isn't on a team; after logging in as the mentor, the content can be accessed/viewed from the "Scores & Feedback" link (in the sidebar)

**Comment by hellafitz** [comment]
@rsgonzal do we have updated content or feedback from Bryant for this?

**Comment by Bryant-Gomer** [comment]
I think these bullet points are fine on the screen are fine. I would add:
"Questions or feedback about staying involved with Technovation, reach out to volunteer@Technovation.org". 
"Make sure to visit [Technovation's blog](https://www.technovation.org/blog/) for program updates and announcements"

**Comment by rsgonzal** [comment]
Thank you for your participation in the 2020 Technovation season.
You can see this year's finalists [here](technovationchallenge.org/season-results).
The 2021 season will open in the Fall.
Stay informed about important dates and updates. [Sign up for our newsletter](http://eepurl.com/gTS2KL).
Questions or feedback about staying involved with Technovation, reach out to volunteer@Technovation.org.
Make sure to visit Technovation's blog for program updates and announcements.

**Comment by shaunxp20** [comment]
> We should also verify if anyone else sees this screen

From what I could tell it's only possible for mentors and judges to see the "no certificates" page.

Only these two files use the "no certificates" page:
```
app/views/slots/mentor/_scores.en.html.erb
8:      <%= render 'dashboards/no_certificates' %>

app/views/judge/dashboards/onboarded/_certificates.en.html.erb
27:    <%= render 'dashboards/no_certificates' %>
```

😺 🌞 😎

**Comment by shaunxp20** [comment]
>     * link for 'newsletter': http://eepurl.com/gTS2KL

Just wanted to double check the URL is correct, looks like it points to:
`htps://technovation.us4.list-manage.com/subscribe?u=b10254bbb5db780d1af913317&id=39f48a73ac
`

Is that correct? 🤔 😁 🌞 

Also, side-note, looks like that page has a different/old? header. 🤓

**Comment by rsgonzal** [comment]
Yup, this looks right!

Different because of the color?

**Comment by shaunxp20** [comment]
> Yup, this looks right!

Cool, thanks! 🙇‍♂️ 

> Different because of the color?

Yeah. 🤔 👍 👎 🤔 🙊 🙈 😀

**Comment by rsgonzal** [comment]
haha. it's how our site _should_ look..

**Comment by shaunxp20** [comment]
> haha. it's how our site _should_ look..

Okay, thank you! 😊 🤭 🙊 😁 👍

**Comment by shaunxp20** [comment]
Btw, I updated the `NEWSLETTER_URL` config setting on both QA and PROD, so we should be good for when it's time to deploy. 👍

**Comment by shaunxp20** [comment]
This one is on the QA site and QA steps have been added as well! 👍 😃 🌞

**Comment by Bryant-Gomer** [comment]
I Logged in as a fully onboarded judge with 4 submissions completed and can confirm that they can see the updated content/url changes. The judge does NOT have access to a certificate

**Comment by rsgonzal** [comment]
Logged in as a suspended judge and unmatched mentor, looks good@

**Comment by shaunxp20** [comment]
This has been deployed! :thumbsup: :shipit: :sun_with_face:
