### ISSUE TITLE
Epic: Reintroduce auto-scaling 

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2505]
We might want to consider reintroducing auto-scaling to the app.

We had an auto-scale add-on configured some time ago, but it's not being used any more, and I don't quite remember why. But it looks like Heroku has a few new auto-scaling options now that we might consider.

[This add-on](https://elements.heroku.com/addons/rails-autoscale) seems ideal to me. Heroku also provides auto-scaling at the higher tiers of dyno, but the add-on would be cheaper to start with. It may even be able to save us money by scaling our dynos down when the site is slow, which we don't always do manually.

**Comment by hellafitz** [comment]
@stenington do you recommend folding this in with the spike ticket(s) we discussed at retro (re: platform outage and db issue)?

**Comment by stenington** [comment]
I think auto-scaling is probably the way to try to handle things like the submissions spike in traffic. I was going to write a separate ticket capturing some of the spike metrics, because they will quickly age out of what our plans allow, but as I was looking at it I couldn't really think of another obvious first approach than auto-scaling.

This is what the request queuing graph looked like right at the deadline (request queue time being what Rails Autoscale uses to make decisions):

![Screen Shot 2020-05-06 at 11 03 07 AM](https://user-images.githubusercontent.com/55319/81193341-44748580-8f89-11ea-913f-4e970637c5a9.png)

It would depend on configuration, but looking at that I can imagine we would have introduced additional dynos at 1pm, and then I wonder if the 3pm spike wouldn't have been so severe. 

The thing we'll have to take care with though is not letting the auto-scaler scale beyond other capacities. The second spike on the graph, for example, seemingly happened because the database pool ran out of connections. Analytics show we maxed out at 65 database connections when we should be allowed 120, so I think we must have had stuck connections or something, but the point is that scaling up dynos can run into a new set of problems, so auto-scaler won't be a totally hands-off solution that we can set and ignore.

**Comment by hellafitz** [comment]
IN-PROGRESS #2508 setup the autoscaler add-on
DONE #2506 bug: running out of database connections in the pool

**Comment by hellafitz** [comment]
all tickets completed
