### ISSUE TITLE
Bug: running out of database connections in the pool [13,13,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2506]
Right at our submission deadline, we experienced a significant traffic spike. Request queuing went way up and the site began responding poorly, so we scaled up to 5 dynos. About twenty minutes later we experienced another spike in queuing and poor platform performance, seemingly due to our database pools running out of connections. We scaled down to 4 dynos and things seemed to level out.

I don't actually know if the number of dynos was the problem though. We should be allowed 120 connections and metrics indicate we capped out at 65. I wonder instead if requests timing out hold on to connections even while new requests come in, and that's what depleted the pool.

In any case, this ticket is being opened to describe the issue and provide a starting point for discussion about what we might want to do about it.

I think it's relevant to #2505 as well.

**Comment by stenington** [comment]
![Screen Shot 2020-05-06 at 11 12 14 AM](https://user-images.githubusercontent.com/55319/81194744-024c4380-8f8b-11ea-9b28-16b87027deeb.png)

**Comment by stenington** [comment]
A first task to start clarifying this might be to check our connection pool math on staging while tweaking the active dynos. It would be nice to feel confident that we're understanding the pool config, first and foremost. 

We could also try to do some additional research into the idea of dead connections and how that happens, or looking into Heroku's pooling options (which seem to be separate from Rails' pool?).

**Comment by stenington** [comment]
Also see #1861

**Comment by stenington** [comment]
Here's an interesting article that explains how timeouts can blow up an app: https://www.schneems.com/2017/02/21/the-oldest-bug-in-ruby-why-racktimeout-might-hose-your-server/

Excerpt, emphasis mine: 
> It spawns up a new thread, sleeps the amount you want and when it wakes up it raises a Timeout::Error. If you’ve ever used rack timeout, (and recently I learned about slowpoke which also adds postgresql timeouts) it uses Thread#raise to kill an entire web request running in another thread.
> 
> Most of the time this isn’t too awful. **However when it goes bad it goes really bad. For example network connections such as Database connections might not be released properly.** This could cause issues in your app or in your database. The exception may have happend in a place that puts the thread in an un-recoverable state. It’s not dead so the webserver you’re using thinks it can handle web requests, but maybe it’s stuck and can’t actually process those requests.

So basically it seems like the more timeouts we're experiencing, the more likely we are to end up with stuck database connections and pool errors.

**Comment by stenington** [comment]
Pulling the math up from #1861: 
`(# Dynos * RAILS_MAX_THREADS * WEB_CONCURRENCY * DB_POOL_SIZE) + SIDEKIQ_DB_POOL_SIZE <= 40`

If we don't tweak parameters other than the dyno count from our current settings, I believe our 120 connection limit means we could spin up 11 web dynos, and that would put us at 119 connections.

**Comment by stenington** [comment]
From my research today and re-checking the math as I understand it, I think it's more likely that the database pool problem we saw was caused by timeouts or some other app error putting things in a bad state than it was by scaling up the dynos.

We can run an experiment next week to test the waters a little bit, which is just to turn the dynos back up to something somewhat high for a little bit and see what happens. We should see the database connections go up, and assuming we don't see database pools get depleted, that would lend credence to the idea that things can just go haywire when traffic spikes and the app fails to keep up.

**Comment by stenington** [comment]
Bumped the dynos up in production for a while, and nothing went wrong. It also seems like our autoscaler (#2508) regularly goes up to 5 dynos without trouble, so I'm feeling more confident that it could be the timeouts and not the scaling that killed the db pool.

**Comment by stenington** [comment]
I think this ticket is done. It seems likely to me that our pool ran out of connections not because of bad configuration, but because timeouts in Rails can destabilize an app. Seems like there's currently no solution.

@shaunxp20 Anything else you'd want to see here?

**Comment by shaunxp20** [comment]
Yeah, I agree, I think we're done/good on this one. We can always revisit it too if we see it again. Thanks for the great write-up too! 💯 👍 I think we can call this one done! 🙆 ✅
