### ISSUE TITLE
Set up an auto-scaler [20,13,1.54]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2508]
From #2505, let's start by configuring the Rails Autoscale add-on and seeing how it performs (monitoring throughout the iteration) with default settings (or simple tweaks if needed). This will start to give us a baseline for future modifications we might want to make.

Let's also be conscious of the cost: the add on costs some money per month, but ideally it's scaling down our dynos when the site is slow and netting us some savings.

**Comment by shaunxp20** [comment]
I added a note and some screenshots in [Slack](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1589922066003700) about the cost savings. 💸  We can revisit the this to get better data/figures after Rails Autoscale has been running for an entire/complete month (at/after the end of June). 😃
