### ISSUE TITLE
Adjust eligible submission logic to exclude judge region

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2515]
The program team has decided they don't want judges to see submissions from their region at all during judging.

It looks like historically, we've prevented mentor/judges from judging submissions in the same **region and division** as any team they're mentoring, but non-mentor judges could judge submissions from anywhere. 

Additional considerations here:
* do we need any flexibility around this, or can we firmly prevent judges from judging their region **without exception**?
* speed considerations: `FindEligibleSubmissionId` has to run pretty quickly. 
    * We previously calculated judge conflicts with a cached field, and would need to calculate these new region conflicts similarly. 
* the details around regions in the app are already very muddy
    * teams have a `region_name` attribute, but it's unclear to me if we could use it, it does weird normalization I don't understand
    * the `region_division_name` currently used for judge conflicts does some stuff with `country_code` instead, and we may want to just use that logic sans the division stuff
    * `country_code` itself is quite a mess, but I don't know what to do about that now

**Comment by stenington** [comment]
Expanding on the last point about regions being muddy, it looks like
* `region_name` can end up calling out to the Google APIs, and trying to do some investigation locally ended up putting us over an API limit or rate limit, which is going to make work hard and introduce risk in production related to the API limits
* modifying `region_division_name` to drop the division part seems plausible, but you end up with somewhat of a garbage in, garbage out problem. For example, we have users or teams in `US_Ohio` and users or teams in `US_OH`. We know those things are equivalent but the system doesn't so a `US_Ohio` submission could go to a `US_OH` judge and vice versa. There also seem to be judges and teams with no region, using this calculation.

**Comment by hellafitz** [comment]
#2526 judge self-recusal / abstention is our lateral approach to solving one of the main pain points from this issue: a judge sees a submission they don't think they should be seeing, but they're stuck with it (currently).
