### ISSUE TITLE
Allow teams continued access to their submissions [13,8,1.63]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2517]
Ophelie: "teams should be able to see their submission either after submission closes or after judging is done until next season. Otherwise, submission closes and it’s gone fooooreeeveeer (for teams at least, seems mentor can still see them)" 
https://docs.google.com/document/d/18a9ToY63JnyyksC7X13oAkdJ7okuOu_PugYMxKBkKsw/

## QA STEPS

* As an admin, in "Content & Settings", turn off this setting: `Team submissions are editable` 
* Find a student who is on a team, and the team's submission is complete; login as this student
* Verify there is a button on the student's dashboard that will display the team's completed submission; this should have the same functionality as the "My team's submission" link in the header navbar
* You can also verify this button doesn't show up when editing submissions is turn on (and other combinations of conditions on bullet point #2 (student not a team, submission incomplete))

Also, I updated the "My team's submission" link; the functionality should be the same, but that's also something that can be tested if time permits.

**Comment by hellafitz** [comment]
potential solution: provide access to the public view of submissions after submissions close (instead of just giving them messaging about how everything is closed)
- gather screenshots of current state
- rough mockup of proposal

**Comment by stenington** [comment]
Sorry for the broken images here, but this gives you an idea of the current flow. After submissions end, students can still see their submissions if they know to click the "My team's submission" navigation tab, but the main dashboard becomes a bit of a dead end.

## While team submissions are editable

Student dashboard
<img width="1213" alt="Screen Shot 2020-05-19 at 10 40 42 AM" src="https://user-images.githubusercontent.com/55319/82340658-7b04c400-99bd-11ea-80a2-aa8fd5174e7a.png">

My Team's Submission tab
<img width="1213" alt="Screen Shot 2020-05-19 at 10 40 48 AM" src="https://user-images.githubusercontent.com/55319/82340654-7a6c2d80-99bd-11ea-8340-e53890e1617a.png">

"View your complete submission" button
<img width="1213" alt="Screen Shot 2020-05-19 at 10 40 56 AM" src="https://user-images.githubusercontent.com/55319/82340653-7a6c2d80-99bd-11ea-80d2-82ccc36c4db0.png">

## While team submissions are not editable (i.e. judging onwards)

Dashboard (becomes a dead end)
<img width="1213" alt="Screen Shot 2020-05-19 at 10 45 11 AM" src="https://user-images.githubusercontent.com/55319/82340973-d767e380-99bd-11ea-88ce-914902266b68.png">

My Team's Submission tab
<img width="1213" alt="Screen Shot 2020-05-19 at 10 41 27 AM" src="https://user-images.githubusercontent.com/55319/82340651-79d39700-99bd-11ea-9627-0a4b2c75e8d9.png">

**Comment by hellafitz** [comment]
#1201 suggests there was some concern about whether students had sufficiently opted in to public pages. We should get an update from the Program Team.

**Comment by hellafitz** [comment]
Deliverable:
- a button or hyperlinked text on the Dashboard, below the "disable for everyone" text, that takes a student to the My Team's Submission tab
- get ok on a simple mockup from Ophelie before implementing

**Comment by stenington** [comment]
There's logic in `app/views/student/navigation/_global_nav.html.erb` for the "My Team's Submission" tab that we probably want to use, or use some variation of.

**Comment by shaunxp20** [comment]
Btw, I got confirmation from @ophelieh earlier today about the new button on the dashboard (that will only be shown when submissions aren't editable) that will take a student to their submission (whether it's completed or not). 👍 😄

**Comment by shaunxp20** [comment]
> Btw, I got confirmation from @ophelieh earlier today about the new button on the dashboard (that will only be shown when submissions aren't editable) that will take a student to their submission (whether it's completed or not). 👍 😄

One modification to that ☝️ is that this button will only show up for complete submissions, not incomplete ones. It looks like our existing functionality won't allow student's to view incomplete submissions when editing submissions is turned off. 😕

**Comment by shaunxp20** [comment]
This one is on the QA site, and QA steps have been added as well. 😄 🌻 🌞

**Comment by rsgonzal** [comment]
Looks good to me. Tested the other scenarios and the button did not show up. I'll see if ophelie has some time to test this today, if not I think it's good to go.

Oh for the url, what kind of testing were you thinking?

**Comment by ophelieh** [comment]
Tested with the different scenarios and everything worked as expected. I only saw the button when submissions were not editable and I was on a team that had a complete submission. 

Thank you!!! :)

**Comment by shaunxp20** [comment]
> Oh for the url, what kind of testing were you thinking?

Just that it (it being the "My team's submission" link) works as expected - for when submissions are/aren't editable, student is/isn't on a team, submission is complete/in-progress/doesn't exist. 😄 😸 😃 😺

**Comment by shaunxp20** [comment]
Thanks for testing @rsgonzal @ophelieh! 👍 💯 🎈 🙌

**Comment by rsgonzal** [comment]
Ok cool, I think it's good to go then! Thanks!

**Comment by shaunxp20** [comment]
> Ok cool, I think it's good to go then! Thanks!

Awesome, thanks @rsgonzal! 👍 😄

**Comment by shaunxp20** [comment]
This has been deployed! :+1: :shipit: :smile:
