### ISSUE TITLE
Assign a judge to a specific submission [40,13,3.08]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2520]
As an alternative to manually inputting scores, we want to allow admins to assign a specific judge to a specific submission (in need of judging). Currently submissions are assigned to judges only automatically. This should be done through the Score Details screen, accessible from the Scores page in the dashboard. 

The earlier this is available to CET, the more valuable it is (because we can engage engaged Judges).

Goal: significantly reduce "pen & paper" scores 

Q&A: 
- do you do this by looking up the judge, or looking up the submission? A: submission route, it'd be nice to add multiple judges to the submission at the same time (resulting in 2-3 future scores)
- would these judges already have accounts, or be required to? A: Yes
- how would an admin identify a specific judge (e.g. email address, ID, etc)? A: Email address field to paste in. Bryant has an active Judges spreadsheet he'd be referencing. 
- would any of our current limitations on judges being assigned particular types of submissions need to be voided in this use case? A: should be able overrule restrictions. nice ot have a 'confirm' notification about that fact that you're doing it. 
- what's the minimum level of alerting the Judge that we'd do? (we'd create a score in progress, then the 'resume my score' would take them to the new submission; CET would need to email them or we'd need to provide some other type of alert) A: CET would email. 

## QA STEPS

The new judge assignment controls are only available when judging is enabled; the new controls can be found on the score details page. To get there, as an admin, click Scores, and then in the scores/search results table, click the bulleted-list icon (on the very right-hand side of the table; that you may need to scroll-right to see).

Verify the new judge assignment controls for:
 * a valid judge email address; also verify the judge gets assigned the submission
 * a judge who already has a score in progress (this can be done by re-assigning a judge the same submission twice)
 * a suspended judge email address
 * a non-judge email address
 * a made-up email address

We should also verify an RA doesn't see the judge assignment controls.

**Comment by stenington** [comment]
A technical note: judges can only have one score in progress, so we would not be able to give multiple submissions to a single judge in a useful way. We could theoretically create a bunch of complete scores and ask them to edit them, but on the off chance they don't, I wouldn't want to be polluting our score pool with bad completed scores. Setting them up with a single in-progress score seems to be the way to go.

The screen where you could add a judge onto a submission by email address would need to account for that then, and refuse to make the assignment if the judge has a score in progress already.

**Comment by hellafitz** [comment]
- next step: mockups OR mockups + MVP implementation

**Comment by hellafitz** [comment]
Amy: helpful to have some way of knowing which judges are eligible to be invited to score a submission, but that can be supported off-platform (Amy, Rox, Bryant to discuss)

**Comment by stenington** [comment]
The MVP in my mind would be something like the following:

A field at the bottom of this page would allow for pasting in an email address:
<img width="1213" alt="Screen Shot 2020-05-19 at 10 57 09 AM" src="https://user-images.githubusercontent.com/55319/82342793-0bdc9f00-99c0-11ea-9b9c-016b724cc38b.png">

If that email address corresponds to a judge who doesn't have a score in progress, a score will be started for that judge on the current submission, and it will show as an incomplete score (not shown here):
<img width="1213" alt="Screen Shot 2020-05-19 at 10 59 16 AM" src="https://user-images.githubusercontent.com/55319/82342792-0bdc9f00-99c0-11ea-86ef-d53efb307fa0.png">

If there's an error in the assignment, an error message is shown and the incomplete score is not created:
<img width="1213" alt="Screen Shot 2020-05-19 at 10 59 54 AM" src="https://user-images.githubusercontent.com/55319/82342790-0b440880-99c0-11ea-86a0-18596b34d102.png">
<img width="1213" alt="Screen Shot 2020-05-19 at 11 00 28 AM" src="https://user-images.githubusercontent.com/55319/82342788-0aab7200-99c0-11ea-9952-daf7d1f8fd7f.png">

Possible errors:
* Judge has a score in progress
* Email can't be found/doesn't correspond to a judge account
* Judge is suspended

**Comment by hellafitz** [comment]
Deliverables:
- circulate the mockups above for feedback
- implement

**Comment by shaunxp20** [comment]
I met w/ @Bryant-Gomer, we're just going to make a couple of tweaks to the mockups:
 * Update "Assign Judge" to "Assign Judge to Submission"
 * Potentially update "Complete your score in progress" on judge's dashboard, still thinking about the wording

I also updated the form to use a panel (bordered-white-box thingum) to be more consistent w/ the rest of the admin, and got a 👍 for that.

**Comment by shaunxp20** [comment]
This one is on the QA site, and QA steps have been added as well. 😄 😅 😁

**Comment by ophelieh** [comment]
Hi all! 

I tested as an admin adding a judge with no current submission, a judge currently reviewing a submission, a suspended judge, and a mentor. Everything worked as expected and I could see the error message when applicable. 

As an RA during judging, I cannot see any scores.

**Comment by hellafitz** [comment]
Additional QA step: confirm these controls aren't visible when RAs ARE able to see scores (for teams in their areas)

**Comment by shaunxp20** [comment]
Thanks for testing this, @ophelieh! 😃 🍰 🎉 🙌

**Comment by rsgonzal** [comment]
Judge assignment controls work well, tested all of the different email scenarios.

Couldn't find an RA that could view scores though. They had complete submissions on their dashboard though.

@ophelieh which RA did you check and does it matter what the content & settings are set to?

**Comment by ophelieh** [comment]
I logged in as an RA during judging and couldn't see any scores. _Side note: during judging RAs can only see scores for their events._ 

I then logged in as an RA after judging was done and scores were available, that's when I was able to see the scores from my region. 

I used the ra@ra email account for both times.

**Comment by rsgonzal** [comment]
thanks, @ophelieh ! That makes sense. Ok, all looks good then. Can not add a judge once judging is closed for neither admin nor RA.

**Comment by shaunxp20** [comment]
This has been deployed! :shipit: :grin: :thumbsup:
