### ISSUE TITLE
Spike: TG '20/21 Dev Launch Tasks [13,8,1.63]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2523]
From #2250, create a doc for TG season launch tasks that need to be done by Dev / Product. Then identify the current method of completing those tasks and recommend areas for further automation or alternate improvement. This will build upon the Expected Developer Support Tasks doc, which is more focussed on submissions and judging (vs opening the season). https://docs.google.com/document/u/1/d/1_rVW24C1-RPGF4V3q3I1kr5Cu3CVqg2PoPt8Eja6s5c/edit#

**Comment by stenington** [comment]
I would like to address #2551 first, if possible. It will help a lot to know what does need to be reset, what doesn't need to be reset, and what needs to have the option of being reset or not before documenting the way to accomplish that, or opening new tickets for those things.

**Comment by hellafitz** [comment]
Reducing scope to:
- what we did last year
- editorial commentary on how much sense it made, where applicable

#2251 will help us answer where to dig deeper and where past stuff is irrelevant

**Comment by stenington** [comment]
[This document](https://docs.google.com/document/d/1bE89DN7Q9jRe6iilbCoaQUo7F2NecKcA8CF2fr-mSnk/edit#) captures what we would expect to have to do this year (unless we make changes beforehand) based on what we had to do last year. I think it provides a good basis for reviewing and seeing where improvements can be made.

[2021 Expected developer support tasks](https://docs.google.com/document/d/1bE89DN7Q9jRe6iilbCoaQUo7F2NecKcA8CF2fr-mSnk/edit#)

**Comment by stenington** [comment]
I think the new doc is in a good state. We could create another round of tickets moving these things towards admin tasks if desired, but I think that's outside the reduced scope here.

**Comment by hellafitz** [comment]
@stenington I consider this done once the link to the updated Scores dataclip is in the doc
