### ISSUE TITLE
20/21 Epic: Judges can recuse themself from judging a submission

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2526]
Q: would Judges be able to move on to a new submission once they recuse themself, or would an admin need to approve?
context: in AwardForce they can skip and go on to the next one

A: recusal needs to be approved by an Admin. Can't judge until they get that approval. 
Potential routes:
- Have an admin page with recusal requests. 
- Create a custom zendesk ticket. 
- on the Scores page, there's a header that flags particular "suspicious scores" problems. Judging team goes there daily, so that'd be a good place.

**Comment by rsgonzal** [comment]
@rsgonzal add screenshots from awardforce on how they recuse themselves

**Comment by hellafitz** [comment]
Next steps: mockup the Scores page option. Create another alert box along the lines of Suspicious Scores and put it just below that one. 

In parallel, ask CET how the Suspicious Scores UI is working for them. Off the top ideas for improvement include, the ability to drag the window size bigger (thus increasing the height and reducing the need to scroll in that currently fixed-size section), and the ability to export the list of suspicious scores to a spreadsheet for off-platform work.

@rsgonzal to pull AwardForce recusal examples

**Comment by rsgonzal** [comment]
On Awardforce the judge sees the option on the scoring page:
![Screen Shot 2020-06-15 at 9 50 15 AM](https://user-images.githubusercontent.com/22801026/84801075-914d7200-afb3-11ea-8196-e654d4d0c049.png)

![Screen Shot 2020-06-15 at 9 50 23 AM](https://user-images.githubusercontent.com/22801026/84801112-9c080700-afb3-11ea-98d2-4df9c9799e12.png)

From the admin side:
![Screen Shot 2020-06-15 at 9 51 37 AM](https://user-images.githubusercontent.com/22801026/84801141-a75b3280-afb3-11ea-880f-ae29c1c29cfb.png)
![Screen Shot 2020-06-15 at 9 52 32 AM](https://user-images.githubusercontent.com/22801026/84801193-ba6e0280-afb3-11ea-9766-ccac82d81791.png)
![Screen Shot 2020-06-15 at 9 53 21 AM](https://user-images.githubusercontent.com/22801026/84801221-c0fc7a00-afb3-11ea-9bc5-6b65430fef81.png)

**Comment by hellafitz** [comment]
Note: Suspicious Scores app is powered by Vue, so adding onto it would require more Vue (which we'd like to move away from). Not a blocker but worth considering in terms of ROI.

**Comment by hellafitz** [comment]
next step: create mockups #2556 and get feedback

**Comment by rsgonzal** [comment]
Most information in this ticket is outdated, working off of mockup ticket
