### ISSUE TITLE
Duplicate incomplete scores deadlock [5,13,0.38]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2531]
**Describe the bug**
We have a judge who ended up with 2 incomplete scores on a submission, and is now in deadlock. The UI appears to be letting him score, but I believe in the background everything is getting rolled back, and the UI has no indication of an error. Then when the judge believes he is complete with that score, his dashboard shows him that he still has that score stuck in progress.

**To Reproduce**

I pulled down production data and logged in as the judge in question to verify. There may be a way to force the duplicate incomplete scores, but I'm haven't tried to do that yet. But either way, once you have a judge with duplicate incomplete scores

1. log in as affected judge
2. click "Resume" on dashboard to resume your score in progress
3. begin scoring
4. notice in the development server logs that everything you're doing is causing a `ROLLBACK` but issuing a 200

**Expected behavior**
I would expect
1. that duplicate incomplete scores could not be created, since they cause such an issue, and that
2. the UI would signal the error much more quickly so a judge doesn't waste so much time doing work that isn't being saved

**Comment by stenington** [comment]
It seems like in general duplicate incomplete scores shouldn't happen: https://github.com/Iridescent-CM/technovation-app/blob/bce4265dd4b3db5ae5b9f925f5427c9e86497106/app/models/questions.rb#L271

Presumably there was some race condition that hit just right to let two be created. We might consider enforcing uniqueness at the database level.

**Comment by rsgonzal** [comment]
Did not see this issue this season, going to close/
