### ISSUE TITLE
It-24 TG season & ongoing support [40,20,2]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2538]
See https://docs.google.com/spreadsheets/d/1Mx3DlCT62cr_MZAl4C10FiWzaXxIIh4tszubmAMW18c/edit#gid=1850689656

*Dates here are approximate and subject to change, check the spreadsheet for updates*

* June 8 QF closes
* June 9 & 10 pen & paper scores, if any
* June ? drop low scores maybe?
* June 12 use semifinalist spreadsheet to batch set semifinalists, snippet used to create blog post
* June 15 semifinals opens

**Comment by hellafitz** [comment]
Calendar considerations and related tasks:

Round 1 judging ends June 8th
- Expect some use of new admin Judge assignment feature
- Manual score creation
- May be asked to drop lowest scores
Semifinalists selected June 11
- Deploy the html snippet for blog announcement
- Do bulk update of semifinalist teams from spreadsheet
Round 2 judging opens June 15

**Comment by stenington** [comment]
Noting from our planning discussion: my understanding is that we want to make room for @shaunxp20 to take first crack at some amount of the scheduled tasks, or maybe to tackle them together. Is that right @shaunxp20? If so I will try to make sure to coordinate a bit before diving in as things come up.

**Comment by stenington** [comment]
So the tasks scheduled for this week weren't concrete enough to hand off one-by-one. Instead, what we need is somebody on standby to see if the tasks we guessed we'd do actually meet the program team needs as they develop. As such, I'm on the hook for that, and @shaunxp20 will work on tickets.

**Comment by stenington** [comment]
21 scores created manually, took up about 5 hours of the day.

**Comment by stenington** [comment]
The rake task for marking semifinalists hadn't been deployed, so it wasn't available for use, but it doesn't really matter. I had a spreadsheet with a column of submission IDs to push forward, used `=TEXTJOIN(",",TRUE,B2:B259)` to get a comma separated list, and was able to issue an update statement straight in the console the same way the rake task would.

**Comment by stenington** [comment]
I've also captured some notes here: https://docs.google.com/document/d/16JIGMOrH2AINFWPy_8oi56TTsfvxRxxW_nEW8AptdUc/edit#
