### ISSUE TITLE
Spike: "Regional Ambassador" to "[TBD] Ambassador" word change [13,8,1.63]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2539]
Create a quick scope document describing the frontend and backend tasks and implications that would be associated with changing "Regional Ambassador" to "[TBD] Ambassador" on the TG platform.  [TBD] is an as of yet unconfirmed, unidentified adjective. 

Do a find and replace. Note how many instances need to be replaced for each term. Flag any complications that you uncover.

Context: see conversation notes at https://docs.google.com/document/d/1cW7Q_q2KqiCxoV8_RDDsn-Jv7Qkn_JhFQv0g5m9I4Fw/edit#bookmark=id.8vprpokwc3mf

Consider for scope of backend refactoring:
- variables
- models
- routing
- dataclips
- URLs (existing links on WP or platform, user bookmarks, redirects required, etc)
- 3rd party platform stuff (e.g. mailing list names)

Context / Timing: Program wants confirmation that we can make these frontend changes in time for World Summit (mid-Aug). The backend refactoring wouldn't need to be done by then.

**Comment by shaunxp20** [comment]
#### Assessment of the front-end changes

Searching for the term "Regional Ambassador" (case-insensitive) and the term "RA" produced about 250 matches (there are definitely false-positives in here, like our spec files):

```
$ rg "regional ambassador" --ignore-case --stats

65 matches
65 matched lines
45 files contained matches
```

```
$ rg "RA" --type-not svg --type-not sql --stats

289 matches
271 matched lines
91 files contained matches
```

Anywho, the front-end changes should just be a find and replace.

#### Assessment of back-end changes

The back-end will require more changes, there are 700+ matches in 200+ files.

(While the front-end searches included some back-end results. The back-end searches shouldn't include any front-end results.)

```
$ rg RegionalAmbassador --stats

125 matches
125 matched lines
68 files contained matches
```

```
$ rg regional_ambassador --stats

619 matches
586 matched lines
172 files contained matches
```

Database changes:
`regional_ambassador_profiles` - table name
`regional_links` - column, index reference
`regional_pitch_events` - column reference

I didn't see any Dataclips that need updating.

ENV/config settings:
`RA_SLACK_URL`
`SHOW_RA_EVENT_UI`

Questions:
* How do we want to handle old URLS? We could setup redirects so they will still work.
* Do we want to keep the back-end term aligned w/ the front-end term? We could take the approach of renaming the back-end term to just "ambassador". If we want to go with this approach, we can make this work separate (imho, we should split up the front/back-end changes either way), and start on it sooner too.

**Comment by shaunxp20** [comment]
I'm going to put this one into the Test column, let me what y'all think and if we need more details. Ping @hellafitz 😃

**Comment by hellafitz** [comment]
Thanks, @shaunxp20. Any info on 3rd party platforms (auto email integrations or similar)? And for the backend changes, can you include your take on the effort or time involved? Objective here is to give a go/no-go to Program team on the changes. I agree we can split the front-end implementation from the back-end, I just want to have a better sense of what capacity we'd need to put toward the back-end changes once we give the greenlight.

**Comment by shaunxp20** [comment]
> Thanks, @shaunxp20. Any info on 3rd party platforms (auto email integrations or similar)? And for the backend changes, can you include your take on the effort or time involved? Objective here is to give a go/no-go to Program team on the changes. I agree we can split the front-end implementation from the back-end, I just want to have a better sense of what capacity we'd need to put toward the back-end changes once we give the greenlight.

I'll look more at the 3rd party integrations later today or tomorrow. 👍  The effort, imho, for the back-end would be 13, allowing for thorough QAing, and for other gotchas that could popup. 👹 😃

**Comment by shaunxp20** [comment]
To handle any 3rd party integrations we decided to implement redirects so that `regional_ambassador/:somepath` will direct to `TBD_ambassador/:somepath`. This way nothing will break.

Looking at the Rails Routing Guide, we should be able to setup some dynamic redirects: https://guides.rubyonrails.org/routing.html#redirection

And then at some point in the future, we can remove the redirects. 👍 🙅 👉 🏫

**Comment by rsgonzal** [comment]
Just noting the team has decided on a name: Chapter Ambassador

**Comment by shaunxp20** [comment]
I created #2565 for the front-end changes, and #2566 for the back-end changes, and referenced this spike in each of them, so I'm going to close this spike. 🎬 😄
