### ISSUE TITLE
Spike: 'join this team' data for mentor / team matches

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2548]
Investigate how the platform records (or doesn't record) the user action of mentors using the "join the team" feature, as well as the equivalent action of teams inviting mentors. We also want any related match numbers that can be pulled. 

CET is trying to figure out how many teams match with a previously unknown-to-them mentor vs are assigned one by an RA or adult who knows both parties. 

Deliverables:
- how does the TG platform mark use of the join-the-team invation/match features (mentor to teams, and teams to mentors)?
- what if anything can you tell about how often invites were sent in each direction, and how often it resulted in a match? 

Original Notes from 6/11 TF/TG Product meeting:
Safety-related question - how many mentors actually use "join the team" feature on TG vs teams asking mentors to join (trying to figure out how many teams match with an unknown mentor vs being assigned)
- Background check issues
-- EU RAs collect materials themselves
-- Brazil: only law enforcement can run bg checks
-- Some countries bg checks cost prohibitive, some seems impossible
Next steps: 
create a spike to check on platform mechanics, how that behavior shows up (or doesn’t)
Events database research

**Comment by stenington** [comment]
This dataclip may shed a little light: https://data.heroku.com/dataclips/cpmfdlhusuwmcdhbivryqndokjam

When a team asks a mentor to join them, or a mentor asks a team if they can join, a `JoinRequest` is created. It captures which party initiated the request, mentor or student. **It does NOT capture whether those parties knew about each other from an off-platform source, though.**

We have join requests going back to 2016, where the numbers look like this:


unique requestors | total requests | requestor_type | accepted? | earliest | most recent
-- | -- | -- | -- | -- | --
6067 | 9467 | MentorProfile | accepted | 2016-09-25 09:20:07.441869 | 2020-05-04 20:56:46.756635
1189 | 2495 | MentorProfile | not accepted | 2016-09-27 18:58:17.967622 | 2020-05-04 15:42:14.023883
13567 | 14205 | StudentProfile | accepted | 2016-09-21 23:54:15.568083 | 2020-05-04 18:31:37.291751
1543 | 2069 | StudentProfile | not accepted | 2016-09-21 22:36:22.672179 | 2020-05-04 19:04:58.225598

Looking at 2019-08-01 and onward, it looks like


unique requestors | total requests | requestor_type | accepted? | earliest | most recent
-- | -- | -- | -- | -- | --
1933 | 2636 | MentorProfile | accepted | 2019-10-10 13:31:32.989971 | 2020-05-04 20:56:46.756635
399 | 784 | MentorProfile | not accepted | 2019-10-11 00:45:35.183259 | 2020-05-04 15:42:14.023883
3871 | 3950 | StudentProfile | accepted | 2019-10-10 19:43:47.523294 | 2020-05-04 18:31:37.291751
492 | 623 | StudentProfile | not accepted | 2019-10-13 08:33:25.482575 | 2020-05-04 19:04:58.225598


So it appears both mentors and students are able to initiate requests that get accepted more often than not, but again, **this doesn't distinguish between people who knew each other off-platform or not**.

**Comment by hellafitz** [comment]
summary
- students initiate more often than mentors
- both students and mentors have their requests accepted more often than not
- ! impossible to tell from the platform data if they know each other already (or have been connected off-platform by an RA) or not

potential patterns: 
time betw request and accept?
# of requests?
request approval rate?

**Comment by hellafitz** [comment]
@stenington is there a way to link JoinRequest data to individual teams en masse? Goal is to see 'submitted/didn't submit' outcomes by request type.

**Comment by stenington** [comment]
Probably, but I'm not clear on the request here. We can have more requests in the system than teams, and we can have complex scenarios like several mentors requesting to join a team, some accepted, some rejected, and then that team may have submitted or not. I would need more info on how those complex scenarios should be tallied.

**Comment by hellafitz** [comment]
Next step: run these by TF/TG Product attendees:
- # of teams with a mentor that submitted / didn't submit
- # of teams without a mentor that submitted / didn't submit
- # of teams who invited mentors but had 0 acceptance (and either didn't get any inbound requests or - they rejected any requests)
- # of teams who didn't invite a mentor that eventually submitted / didn't submit (Q: if they never ask, is that an indicator of not submitting?)
- # of mentors who offered to mentor and weren't accepted by any team (then: did they drop, become a judge?)

**Comment by hellafitz** [comment]
We discussed the stats above in TF/TG Product Meeting on 7/7 but didn't emerge with a clear ranking. There was a suggestion that some of this data - particularly around the # of teams that did or didn't submit - was already available, but that may have derailed a substantive assessment of the more specific metrics farther down the list. 

Amy provided some context for interpreting data in this area
- We get a large influx of mentors right before reg deadline
- We incentivize teams to have a mentor at submission time, but not before. Teams often register their mentor right at the end.
- How do people interact with the matching process on the platform? We don't have much info.

Takeaway: there's team support for prototyping potential 'default' message options to provide limited communication between Teams and Mentors in order to facilitate matching and to provide reasons for not accepting requests.
