### ISSUE TITLE
Spike: events database [8,5,1.6]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2549]
As our platforms and program models continue to evolve, an events database might give us a way to store detailed platform and user activity data that could be retrospectively queried for analysis, without us having to provide the query details in advance. 

Investigate our options in this area (2-4 hrs) and provide a recommendation on next steps and key questions to answer. 

type of info to include:
top contenders
cost
what do they claim to offer
quick, subjective assessment of fit

**Comment by stenington** [comment]
A few pointers:
* segment.io
    * recommended and written about by Thoughtbot
    * I think it can act as a "data hub" and pass events on to something like keen.io, Google Analytics, etc.
* keen.io
    * evaluated previously and seemed promising
    * cheaper to use directly than segment + keen
* amplitude
    * didn't evaluate previously, but recommended by a friend
* Google Analytics events framework
    * evaluated previously, seemed powerful but complicated
    * other tools seem a little more flexible to set up without knowing exactly what you're looking for

**Comment by hellafitz** [comment]
Use cases? previously we couldn't get well-defined ones from the team, so the use case was flexible retrospective analysis of things we hadn't configured in advance.

**Comment by stenington** [comment]
Some notes on how different services recommend getting started:
* keen
    * [100-level data modeling guide](https://keen.io/docs/streams/data-modeling-guide/)
    * [200-level data modeling guide](https://keen.io/docs/streams/data-modeling-guide-200/)
* amplitude
    * [instrumentation pre-work guide](https://help.amplitude.com/hc/en-us/articles/206404618-Step-1-Instrumentation-Pre-Work#h_0ef6b708-f9e8-4287-8d97-bb28d5d5f638)
* mixpanel
    * [creating a tracking plan](https://help.mixpanel.com/hc/en-us/articles/115004519886-Templates-for-Tracking-Plans)

**Comment by stenington** [comment]
From a quick review of the intro docs, it seems to me like both amplitude and mixpanel have two main components:
1. send events
2. visualize

whereas keen has three:
1. send events
2. compute
3. visualize

I suspect this means that amplitude and mixpanel are more opinionated on what you want to know about your data, whereas keen is trying to be more general purpose.

**Comment by stenington** [comment]
One area for a deeper dive may be **how each option can or can't handle analytics across platforms**.

Keen seems to offer some flexibility, citing this example:
> If you have an application with many similar instances, for example an app for restaurants with a different version for each restaurant, let us know and we will help you figure out the best way to structure your projects. There may be cases where you want to logically separate data for different companies while at the same time requiring cross-project analysis – we can help!

Amplitude says
> We recommend combining web and mobile data into the same project if your product is similar across all platforms and the taxonomy is consistent.

In either case, I'm not sure if the taxonomy across TF and TG would be consistent enough to make it work.

Also, I want to flag that tying TG curriculum behavior to TG platform behavior still might not happen, because we don't identify users on the curriculum site. That's another area we may want to dig deeper: **do these tools all rely on us telling them who a user is, or do they have their own clever ways of figuring it out**?

**Comment by stenington** [comment]
Pricing pages:

* https://keen.io/pricing/
* https://amplitude.com/pricing
* https://mixpanel.com/pricing/

Of course they all have their quirks for how they charge that makes it hard to compare, but they do all have a "Free" level that would let us explore a bit.

**Comment by stenington** [comment]
Quick summary of my observations so far:

* I think our use case may be a little different than the standard use case for these services
    * holistic analytics across platforms vs. product analytics on a single fully cohesive platform
* keen seemed to offer a querying and visualization layer that may make it a more flexible tool 
    * unsure if the others don't have this or just put less emphasis on it
    * unsure if this means you can get up and running with standard reports faster in the other services
* not sure any of them will let us holistically identify users across properties
    * that may be groundwork we have to solve on our own
    * could do a deeper document dive and see if any service shows particular promise here
* amplitude and mixpanel recommend building your event taxonomy up front, keen less so

**Comment by hellafitz** [comment]
Heap is another option. 
https://www.g2.com/compare/heap-vs-keen-io 
https://www.capterra.com/marketing-analytics-software/compare/147216-175395/Heap-vs-Keen

next steps: 
- define a problem statement
- explore a couple of more Heap-like options
- consider piloting a free trial
- budget estimate

**Comment by stenington** [comment]
A clear problem statement will help a lot, I think.
