### ISSUE TITLE
Designing season rollover [20,20,1] 

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2551]
When a user first registers for a season, they may have to do things like take a training or submit a consent form. 

When that user returns for a second season, it's not clear to me what's supposed to happen. Some things get reset automatically, some things don't but it seems like we want them to be reset.

In this ticket I want to get straight on the user stories around season registration, taking into account things like returning users (including users who skipped a year), and what the platform should automatically enforce versus what the admins might want control over resetting or not resetting, and what the platform should look like in each case.

**Comment by hellafitz** [comment]
Edge cases: User skipped a year. User showed up a day too early (so reg'd for previous, already happened season). certain consent forms are automatically validated each season, others aren't (but should be?). Some consent forms the Program Team wants to make a gametime decision on (should they?). 

Tasks: 
- identify the tasks required of a new user
- identify which user tasks a returning user should be exempted from (in discussion)
- identify the platform processes that govern whether specific tasks are required, and how they're controlled
- identify how the platform should behave in various timing scenarios*

* Season registration scenarios
- New user signs up
-- After registration opens
- Returning user logs in
-- Before rollover (i.e. returns too early)
-- After rollover, before registration opens (why does this one even exist?)
-- After registration opens

context: last year before opening reg we saw users being registered to the season (which surprised our admins). we also had users returning a little too early, and being registered for the previous season (we did a spike and found that it's totally undefined what they should see at that point). 

Deliverable: 
- create a document containing the identified information above, including a comparison table of user tasks by new/returning status

**Comment by stenington** [comment]
I'm taking this one to start, but don't expect to be able to finish it this iteration.

**Comment by stenington** [comment]
## Student
| | Required for new sign up | Required for returning user |
|--|--|--|
| **Sign up wizard** | | |
| Agree to data terms | yes | n/a |
| Input location | yes | n/a |
| Enter DOB | yes | n/a |
| Select "student" option | yes | n/a |
| Fill out profile | yes | n/a |
| Enter email, choose password | yes | n/a |
| **On the dashboard** | | |
| Parental consent | yes | yes |

## Mentor
| | Required for new sign up | Required for returning user |
|--|--|--|
| **Sign up wizard** | | |
| Agree to data terms | yes | n/a |
| Input location | yes | n/a |
| Enter DOB | yes | n/a |
| Select "mentor" option | yes | n/a |
| Fill out profile | yes | n/a |
| Enter email, choose password | yes | n/a |
| **On the dashboard** | | |
| Set personal summary | yes |  |
| Complete mentor training | yes | |
| Fill out consent waiver | yes | |
| Complete background check | yes **(US ONLY)** | |


## Judge
| | Required for new sign up | Required for returning user |
|--|--|--|
| **Invitation flow** | | |
| Get invited | yes | n/a |
| Fill out profile | yes | n/a |
| Agree to data terms (interrupt) | yes | n/a |
| Input location (interrupt) | yes | n/a |
| **On the dashboard** | | |
| Fill out consent waiver | yes | |
| Take short survey | yes | |
| Complete judge training | yes | |

**Comment by stenington** [comment]
## Season registration scenarios

There are four pieces of system behavior that work fine for new users joining the platform, but break down for returning users in strange ways. The four pieces are:

1. the platform "rolls over" the season on a pre-configured month and day, e.g. Oct. 1
2. new user registration is controlled by admin settings
3. the platform registers a user as participating in a season if it sees them log in during that season
4. existing users can log in whenever they please

### For new users

For new users, we would expect new user registration to be turned on **on or after the season rollover date**. That means that first the platform thinks a new season has started, then a new user creates their account, logs in, and is marked as participating in that season. No problems there.

### For returning users

For returning users, there are some trickier timing scenarios with slightly strange results.

#### Scenario 1: returning user logs in before the season has rolled over

In this scenario, the user is coming back to the platform to see if the new season has started, but they're a couple days early. 

Let's say the current season is 2020 and they want to see if 2021 has started. If they participated in 2020, no big deal. They see what they previously saw. The weirder case is if a user **had skipped the 2020 season**. If this is their first log in since 2019 or earlier, and they're intending to check if 2021 is open, they instead log in and are asked to complete onboarding for the 2020 season, receiving the 2020 welcome email and all, despite the fact that all the dates have already passed. Furthermore, if they complete the onboarding tasks, they will need to do them again in a few days when the season rolls over and those onboarding tasks get reset.

#### Scenario 2: returning user logs in after the season has rolled over, before registrations are open

In this scenario, a returning user logs in before we're allowing new users to register. The platform knows it's the new season though, so it marks the user who just logged in as participating in that new season.

Nothing is super strange about that, but in the past it has surprised the program team, who thought the new user registration controls controlled **all user registrations** to the active season, which it does not.

#### Scenario 3: returning user logs in after the season has rolled over, after registrations are open

In this scenario, there probably aren't any surprises. The user logs in, the platform knows it's the new season, and the program team is expecting registrations to the season. Maybe the user is a user type that the program team hasn't allowed new user registrations for, so that may be a bit surprising.

## Proposed solution

In #2194 we looked at introducing a point in the current season after which logging in would not automatically register you to the current season. The problem is that we didn't define what an unregistered user should see instead of the normal screens. I think if we wanted to revisit that kind of a solution, we would need to define carefully what it means to be logged in but not registered for a season for the different user types.

**Comment by stenington** [comment]
The above comments in Google Doc form: https://docs.google.com/document/d/1oBVG_RMi6SVQ8KlznqmdRT_FuNCgRCkBy8maM4tXeWA/edit

**Comment by hellafitz** [comment]
The google doc is updated with the team's thinking on returning users for Students, Mentors and Judges. We didn't discuss the season registration scenarios specifically.

**Comment by stenington** [comment]
So I'm seeing a lot of potential tasks or tickets coming out of that doc:

**Potential tickets**
* ticket to make data terms agreement re-collectable (there may be a short term hack vs. long term desired flow as well)
* ticket to make a new location confirmation or key profile info confirmation flow (again, there may be a hack vs. a long term flow)
* ticket about prompting mentors to update their personal summary when connecting with teams
* ticket for dealing with non-US mentors moving into the US, and how to get a background check from them
* ticket to make judge consent waivers not expire after a year

**Potential tasks**
* a question for us to answer about what happens when a student account ages out
* a question about what happens with background checks if a mentor signs up outside the US, but then updates to be inside the US

**Further clarification needed**
* some further thinking and clarification about selecting "student" option: I don't understand the comment left there.
* some sort of email/password confirmation, password strength thing? Not clear on what that would look like.
