### ISSUE TITLE
It-25 TG season & ongoing support [40,20,2]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2552]
See https://docs.google.com/spreadsheets/d/1Mx3DlCT62cr_MZAl4C10FiWzaXxIIh4tszubmAMW18c/edit#gid=1850689656

On the planning sheet:
* June 16-25 monitor performance of site daily (response time and failed requests will now trigger a heroku notification in the devteam slack; resolved problems also trigger a notification)
* June 26 "Pen and paper" scores, support for score deletion if necessary (Shaun)
* June 27/28 Amy cleans up data
* June 29 confirm that certificate generation is on track
* June 30/July 1? generate certificates #2457 - takes a couple hours
* July 6 certificates go live (admins turn on Scores & Certificates in dashboard)

OOO
19, Friday: all
23-24: Rox
24: Matt
25-26, 29: Mike

Following iteration, just to be aware:
* July 2 Certificate and finalist marking tech support as needed
* (July 6 Certs & Scores turned ON by Nick)

Not mentioned on the planning sheet:
* dropping low scores? Didn't end up doing it in bulk for quarterfinals, so maybe we won't do this for semifinals?

**Comment by stenington** [comment]
Flagging that I'm out of the office from the 25th to 29th, right when some of this stuff happens.

**Comment by shaunxp20** [comment]
> June 26 "Pen and paper" scores, support for score deletion if necessary (Shaun)

I was able to create a "pen and paper" score on the QA site, so I think I'm good if we decide to go down that route on the 26th, just as long as everything stays on the rails! 😉 😁

**Comment by rsgonzal** [comment]
WOoo! That's awesome, @shaunxp20 

The team seems to be ok with opening up judging for an hour or two and inputting scores themselves if we could somehow provide a timestamp as to when a score is created.

We have this dataclip that shows scores and comments: https://data.heroku.com/dataclips/daqfepdhedhrlripdngbdskqiihj

'approved_at
timestamp
completed_at'

**Comment by rsgonzal** [comment]
@shaunxp20 if you have some time, can you help me wipe out the certificates on staging and regenerate them?

**Comment by shaunxp20** [comment]
> WOoo! That's awesome, @shaunxp20
> 
> The team seems to be ok with opening up judging for an hour or two and inputting scores themselves if we could somehow provide a timestamp as to when a score is created.
> 
> We have this dataclip that shows scores and comments: https://data.heroku.com/dataclips/daqfepdhedhrlripdngbdskqiihj
> 
> There seems to be a few things that collect timestamps:
> 
>     * `approved_at`
> 
>     * `completed_at`
> 
>     * `created_at`
> 
>     * `updated_at`
> 
> 
> Maybe the updated and created would be helpful?

👍 Sounds like we're good here, let me know if there's anything I can help with! 😄

**Comment by shaunxp20** [comment]
> @shaunxp20 if you have some time, can you help me wipe out the certificates on staging and regenerate them?

Sure thing! Just ping me on Slack when you're ready! 😄 🌞 😀

**Comment by rsgonzal** [comment]
Thanks for generating certificates, shaun!

So it looks like marking someone as a finalist, does not show them a certificate and they do not see semifinal scores. Program team seemed to be fine with not marking these on the platform.

We also noticed that certificates are not deleted on production. So it may be possible that returning students will see multiple certificates. I was wondering if we could see how many people have multiple certificates and how many. Worried about them seeing something like this:

**Comment by shaunxp20** [comment]
> So it looks like marking someone as a finalist, does not show them a certificate and they do not see semifinal scores. Program team seemed to be fine with not marking these on the platform.

From looking at the code, it looks like only semifinalist can see semifinalist scores, doh! (Regardless of whether they are marked as finalist from the platform or the rake task.)
https://github.com/Iridescent-CM/technovation-app/blob/ec6085768adadd950e71bcadb04d49449d7a5c4d/app/controllers/student/scores_controller.rb#L12-L14

We can probably add a condition here to display semifinalist scores for finalists too.

Also, it looks like we don't generate a certificate for finalists. Looks like we just have them for: participation, completion, and semifinalist:
https://github.com/Iridescent-CM/technovation-app/blob/4e398a141535e06dc6dc3065777fda5fca3f973a/app/constants/certificate_types.rb#L5-L9

Just FYI, it looks like the "completion" certificate is only awarded to quarterfinalists too:
https://github.com/Iridescent-CM/technovation-app/blob/4e398a141535e06dc6dc3065777fda5fca3f973a/app/technovation/determine_certificates.rb#L43-L50

> We also noticed that certificates are not deleted on production. So it may be possible that returning students will see multiple certificates. I was wondering if we could see how many people have multiple certificates and how many. Worried about them seeing something like this:
> 
> ![Screen Shot 2020-04-29 at 2 33 17 PM](https://user-images.githubusercontent.com/22801026/85898805-c9259800-b7b1-11ea-9b0a-a1f2f555cb6e.png)
> 
> Maybe it can say the year on the label? Not sure if it's worth trying to fix.

Oh snap! Is that a screenshot from production?! I'll try to work on a dataclip next week to see how many people have multiple certs. I haven't actually looked into it, but it should be pretty easy to add the year to the buttons, another solution would be to just display the current season's cert on this page (but it would be nice to have a way to view previous season's certs too, imho).

**Comment by rsgonzal** [comment]
> Oh snap! Is that a screenshot from production?! I'll try to work on a dataclip next week to see how many people have multiple certs. I haven't actually looked into it, but it should be pretty easy to add the year to the buttons, another solution would be to just display the current season's cert on this page (but it would be nice to have a way to view previous season's certs too, imho).

This was from staging before they got deleted! But I agree that allowing them to access multiple years would be nice. That dataclip sounds great :)

**Comment by shaunxp20** [comment]
> This was from staging before they got deleted! But I agree that allowing them to access multiple years would be nice. That dataclip sounds great :)

I verified that we only display certificates for the current season; so I think it's unlikely we'll have a situation like on Staging/QA. Nonetheless, I created a dataclip for accounts w/ multiple student certificates for a given season: https://data.heroku.com/dataclips/ahmchmgulkwjsgmvtztvcbwyvatk

Anywho, tldr; I don't think that screenshot will be an issue for production. 😁

**Comment by rsgonzal** [comment]
> I verified that we only display certificates for the current season; so I think it's unlikely we'll have a situation like on Staging/QA. Anyhow, I created a dataclip for accounts w/ multiple student certificates for a given season: https://data.heroku.com/dataclips/ahmchmgulkwjsgmvtztvcbwyvatk It looks like there aren't any duplicate student certificates for 2019, but there's some for 2018...

Thanks, Shaun! So i can just change the year on this right?

**Comment by shaunxp20** [comment]
> Thanks, Shaun! So i can just change the year on this right?

Yep! 😎 👍

**Comment by rsgonzal** [comment]
@stenington did some investigation into mailchimp lists that get populated when users sign up. Kate & Maggie are archiving the emails from the 2020 student registration lists and adding them to alumni. They're not deleting the entire list to avoid API errors.
