### ISSUE TITLE
Change the page after login redirect to scores page [13,13,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2553]
As a student and mentor, I want to login when scores are available and quickly see them.

Currently when scores are made available and all other parts of the season are closed, a user logs in and sees the page that their submission is uneditable. It is hard to tell that the 
the scores tab is now available

![Screen Shot 2020-06-16 at 9 35 46 AM](https://user-images.githubusercontent.com/22801026/84802008-cc03da00-afb4-11ea-9a98-4aaff0e298c9.png)

**When the certificates toggle is turned on in content & settings**, the students and mentors should be brought directly to this page:
![Screen Shot 2020-06-15 at 9 44 48 AM](https://user-images.githubusercontent.com/22801026/84802095-e9d13f00-afb4-11ea-94b6-32ebd1bd4763.png)

This page shows this messaging when they don't have scores:
![Screen Shot 2020-06-15 at 9 43 39 AM](https://user-images.githubusercontent.com/22801026/84802227-22711880-afb5-11ea-8d27-55ea370a9593.png)

Proposed Changes:

1. Redirect page to the Scores & Certificates tab when a student and mentor login
2. Change the tab name from 'Scores & Feedback' to 'Scores & Certificates'
3. Change that second bolded line on the page from 'Scores and Certificates' to 'xxx'

## QA STEPS
* As an admin, turn on the "Scores &  Certificates" setting
* Login or impersonate a student, as the student you should see the "Scores & Certificates" page right after logging in
* Login or impersonate a mentor, as the mentor you should also see the "Scores & Certificates" page right after logging in

* Turn off the "Scores & Certificates" setting
* Verify the normal (not the "Scores & Certificates" page) is shown after logging in as a student/mentor

**Comment by shaunxp20** [comment]
This one is on the QA site, and QA steps have been added too! 🎈 😄 👍

**Comment by nickiredescent** [comment]
can confirm that the scores and certificates are showing up for students and mentors as described.
(it looks pretty good too!)

**Comment by shaunxp20** [comment]
> can confirm that the scores and certificates are showing up for students and mentors as described.
> (it looks pretty good too!)

Awesome, thanks for looking at this one! 🙌 🎊 😁 👍

**Comment by rsgonzal** [comment]
Agree, looks great!

**Comment by shaunxp20** [comment]
> Agree, looks great!

Nice, thanks for looking at this one!!! 🙌 🎉 😄
