### ISSUE TITLE
Epic: Add help text for admin settings

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2554]
One of the things that was mentioned in the debrief meeting was adding some help text for the admin settings.

Nick said he can help with the help text in a week or so, so this is just a placeholder issue so we keep track of it. 😄 📈 👔

**Comment by hellafitz** [comment]
Feature Ideas from TG Submission Debrief https://docs.google.com/spreadsheets/d/1kDiSJVWCX_4NtASSua29m5X60cMy0qhAFcajUUIwU-s/edit#gid=1142581655

**Comment by stenington** [comment]
The docs in here are geared towards admins and may help clarify some of the mystery: https://drive.google.com/drive/folders/1fp9Im4k5srrGfpSn1WCSufnz-DzzKhQn

**Comment by hellafitz** [comment]
@shaunxp20 did you meet with Nick yet? Last Friday I encouraged him to schedule with you.

**Comment by shaunxp20** [comment]
> @shaunxp20 did you meet with Nick yet? Last Friday I encouraged him to schedule with you.

No update here.

**Comment by hellafitz** [comment]
@rsgonzal meeting w/ Nick next week. Will add this to the agenda.

**Comment by rsgonzal** [comment]
Meeting with Nick & Shaun 7/6

**Comment by rsgonzal** [comment]
Spoke with Nick and we went through the different pieces of the admin. It's a little more than just adding help text

**User Registration**
- judge and RA sign up do not work, should fix or remove
**Notices**
- would be cool if it works, but doesn't show up for students & mentors
- we think RAs and judges see this
**Surveys**
- potentially show example of what these fields populate
- what is a pop up and how do the users see it
- how does the link look? does one of these messages show on the hyperlink? (I don't think so)
- why don't Ras and judges have a survey option
- more potential for surveys, different surveys, a whole section
- explain how & when the surveys pop up and when they go away (exit it out, when you take it, x days after sign up)
**teams & submissions**
- forming teams allowed -- what does it mean, more explanation (they can create a team, send invites, receive invites)
- maybe a little info button, question bubble, to know what it means, implications of this
- team submissions editable -- can mess with submissions, if off what do they see? (message submissions are closed)
**RPEs**
- selecting regional pitch events allowed
- what about celebration events? (simply noting this would affect these as well)
- this is actually only for students to select RPEs
- RAs can create events at any point
**Judging**
- Off , default, clicked at the beginning of season
- quarterfinals
- between rounds, one implication is screen that judges see ( we also forget to update it), is there anything else special about this button?
- semifinals
- finished, what's the difference between finished and off? what are the implications? do judges see another screen? is it conditional on anything else?

Overall there are some good points. There are still some unanswered questions that Shaun and I said we would explore.

**Comment by stenington** [comment]
Some of these things are documented. [This folder](https://drive.google.com/drive/folders/1fp9Im4k5srrGfpSn1WCSufnz-DzzKhQn) tries to document things for platform admins, so start by looking through this folder and seeing which of the above questions are sufficiently answered. I'm sure many of them won't be, but I think some of the survey questions and maybe some of the judging questions will be answered. After that, we could work from this list to build out further documentation.

**Comment by hellafitz** [comment]
@rsgonzal any tickets we could move on for it-27?

**Comment by rsgonzal** [comment]
I still need to look through Mike's doc and answer some of these questions.

**Comment by rsgonzal** [comment]
Working through this doc: https://docs.google.com/document/d/1usGXOl0SWy3baZAvbnFxfBAWEViG1dXO9cP7Uu4laTg/edit

**Comment by hellafitz** [comment]
Tickets for specific changes include (so far): 
- #2615
- #2616

**Comment by hellafitz** [comment]
Update
- #2615 in test
- #2616 ready, in icebox

**Comment by hellafitz** [comment]
Update:
#2615 DONE
#2616 DONE

@rsgonzal any new ones from your doc?
