### ISSUE TITLE
Mockup for Show team/submission rank

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2563]
After teams enter the competition by entering their submission, the platform doesn't show them their progress/rank/achievement until they receive a certificate (e.g. semifinalist, quarterfinalist). This ticket is to add a status/progress indicator of some sort to the My Team's Submission page (best guess so far). It'd be good to link to the full blog post list of teams by country as well. 

As a team member, I want to see how far we've advanced in the competition, so that I can share that information with my friends and family.

**Comment by rsgonzal** [comment]
Submission page: https://technovation-qa.herokuapp.com/student/published_team_submissions/potato-by-thisteam-potato
