### ISSUE TITLE
X20/21 Fix view of multiple certificates for returning students

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2564]
As a returning student, I want to see all of my certificates and know which year they belong to.

![Screen Shot 2020-04-29 at 2 33 17 PM](https://user-images.githubusercontent.com/22801026/86037032-a387d100-b9f3-11ea-9c63-4de2c8519429.png)

Proposed solution:
- Add the year to the display bubble
- Show the most recent at the top left
- Wrap the certificate buttons and fix spacing

From #2552, @shaunxp20 is confirming a student can see multiple year certificates and how many this would affect.

**Comment by shaunxp20** [comment]
Just following up, right now we only display the current season's certificates (even if the participant has others from previous seasons). 🏆 😃

**Comment by hellafitz** [comment]
@shaunxp20 Nice. What's the max number of certs that one user has for this season, and does that break our layout? Is there a certain threshold number of certs that cause the layout error?

Once we figure that out (which is the time-sensitive part), we can explore if past season certificates should be visible. I consider that a call for next season.

**Comment by shaunxp20** [comment]
It looks like the maximum a student could have is two, according to the dataclip there are less than 10 students who have two. It would look something like this (this is from QA):

<img width="1042" alt="Screen Shot 2020-07-02 at 10 26 31 AM" src="https://user-images.githubusercontent.com/58957909/86386258-0b068080-bc81-11ea-9d8d-f0ba3567e2f9.png">
