### ISSUE TITLE
Rename "Regional Ambassador(s)" to "Chapter Ambassador(s)" - Front-end Changes [13,5,2.6]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2565]
From our spike, #2539: 
* Rename all instances of Regional Ambassador to Chapter Ambassador on the front-end
* Rename all instances of RA to Chapter Ambassador on the front-end
* Fix any related front-end specs

## QA STEPS

Between this ticket and #2566, over 300 files and 3,000+ lines of code were changed for the Regional Ambassador name change. I think the best we can do to test this is to login as a chapter ambassador and try to exercise as much code as possible making sure everything works, and that all of the regional/chapter ambassador changes look correct. 😃 😬 😅 

Other things to try:
- invite an RA to the platform, look at all communication
- create some tasks as an RA (i.e invite students/mentors to events)

**Please note**: the `ra@ra.com` user has changed on QA to: `chapter-ambassador@chapter-ambassador.com`, with same password (of course we can change this user to whatever, I was just trying to match the existing style). 😄

**Comment by rsgonzal** [comment]
Update: Rebecca checked it out and all is looking good so far!

**Comment by ophelieh** [comment]
Name change seems to be good - checked as a mentor, student, returning and new Ambassador :) I also checked what a judge receives when invited to an ambassador for an event (which are not happening this year). 

A couple non name related note: 

* As an invited Chapter Ambassador, I was able to pick the year I participated during registration but it didn't register on the  platform. I picked 2017, and it only shows 2021. -- Could we remove the option of choosing a year? It is only applicable in a very limited number of cases. 

![Screen Shot 2020-08-10 at 10 55 30 AM](https://user-images.githubusercontent.com/32206421/89803167-178bbd80-daf8-11ea-8621-f9a68dcbb700.png)

* I received the invitation email twice and as Rebecca mentioned the email is very confusing and doesn't necessarily accurately depict what will be required next - I believe Roxana is already working on a ticket for that though. 
![Screen Shot 2020-08-10 at 11 01 57 AM](https://user-images.githubusercontent.com/32206421/89803822-f37cac00-daf8-11ea-9c79-b1aa1483fe72.png)

**Comment by rsgonzal** [comment]
Thanks, Ophelie! I did add the bottom one to a new ticket. We'll need to edit more emails.

I will email you about the first one!

@shaunxp20 these are ready to go, haven't run into any problems :)

**Comment by shaunxp20** [comment]
> Thanks, Ophelie! I did add the bottom one to a new ticket. We'll need to edit more emails.
> 
> I will email you about the first one!
> 
> @shaunxp20 these are ready to go, haven't run into any problems :)

Wow, that's great! (I'm surprised too!) Thank you for testing this Roxana, Ophelie and Rebecca, much appreciated! 😃  🍰 🍪 🍨 🙌
