### ISSUE TITLE
Rename "Regional Ambassador(s)" to "Chapter Ambassador(s)" - Back-end Changes [8,13,0.62]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2566]
From our spike, #2539, my proposal is to:
* Update all back-end references of regional ambassador to chapter ambassador, including (but not limited to) instances like RegionalAmbassador and regional_ambassador
* Create new chapter_ambassador/ routes
* Update related database tables and columns
* Update related ENV/configuration settings
* Update specs
* Redirect the existing regional ambassador routes to the new chapter ambassador routes

For reference, some pre-work was done in #2539 

## QA STEPS
* QA steps are in the front-end changes ticket: #2565 

## DEPLOY NOTES
I already created the new config/environment variables on QA and prod for:
* `CHAPTER_AMBASSADOR_SLACK_URL`
*  `CHAPTER_AMBASSADOR_LIST_ID`

So, we need to remove the old ones:
* `RA_SLACK_URL`
* `REGIONAL_AMBASSADOR_LIST_ID`

**For QA:**
* The ra@ra.com users is changing to chapter-ambassador@chapter-ambassador.com, so we'll want to update this user manually from the GUI or the console.

**Comment by hellafitz** [comment]
Important note: the Program Team is actually rolling out mulltiple types of Ambassadors. Our backend naming conventions should assume we'll have more than one type of Ambassador in the next 3-12 months.

"Over the next few months, we will be rolling out updated naming for the volunteers who lead multi-site programs, as well as smaller clubs. These names are not ready for external sharing yet :) Here's the breakdown:

Program Ambassadors typically work with local multi-site community organizations to help 10+ teams/families in their area, including recruiting mentors and organizing events. Previously, They were referred to as Regional Ambassadors, Partner Sites, Program Leaders, and Mentors, depending on their program.
The places where Program Ambassadors lead our programs are referred to as chapters.

Club Ambassadors are usually involved with small organizations, or are individuals who support 5+ teams/families in their area. Club Ambassadors are a new category of volunteer for the upcoming program seasons.
The places where Club Ambassadors lead our programs are referred to as clubs."

**Comment by shaunxp20** [comment]
I added #2598 to (at some point) remove the supporting code that was added.

**Comment by shaunxp20** [comment]
Also, just noting this external link (from the chapter ambassador resources page), `https://technovation.atavist.com/regional-ambassador-handbook-2019-2020` that still references "regional ambassador". 😃
