### ISSUE TITLE
Configure `reset_for_season` [8,8,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2567]
The doc in #2551 was written assuming `reset_for_season` would be used in place of `reset_consents`, so I think that's step one. As we continue to refine that doc and make changes, we may want to move way from a scheduled job altogether, but I think we can cross that bridge when we come to it, and making sure the platform agrees with the mental model in the meantime is important.

## QA steps

Beforehand...

1. Make note of a mentor with a signed consent waiver who has completed training
2. Make note of a judge with a signed consent waiver who has completed training
3. Make note of how many onboarded students, mentors, and judges there are (should be non-zero)

Then ask me to capture a backup, set the dates, and run `reset_for_season`. Afterwards...

1. Sign in as the mentor, confirm they need to resign the consent waiver
2. Confirm they need to retake training
2. Sign in as the judge, confirm they need to resign the consent waiver
4. Confirm they need to retake training
5. You should see 0 onboarded students, mentors, or judges after the reset

We can optionally restore to the backup if something goes wrong and we need to try again.

**Comment by hellafitz** [comment]
- Configure this
- Convince ourselves in Staging that it does what we want it to
- Take a backup of Staging and restore afterward, taking down notes on if there were any issues 
[objective is to reduce future time spent having to set up Staging for season rollover testing]

**Comment by stenington** [comment]
Both `reset_consents` and `reset_for_season` ultimately look at `DATES_NEW_SEASON_START_MONTH` and `DATES_NEW_SEASON_START_DAY` to determine whether they should actually do anything or not, so I think the key steps for testing those two tasks would be
1. set the start month/start day to the current month and day
2. run the task of interest on staging with `heroku run`

I'm thinking of an overall plan that would look something like 
1. set up staging as needed
2. capture a backup
3. set season start/day month appropriately
4. run whichever task
5. check expectations

For repeatability, the backup could then be loaded back in to return to that starting point. There may be other config that also needs to be adjusted along with the start month/start day but I'm not sure yet.

**Comment by stenington** [comment]
Ok, QA steps added to the description.

**Comment by rsgonzal** [comment]
So want to clarify -  I see season 2021 already on staging, am i setting up the beforehand in 2021 or should i look for users in 2020..?

**Comment by stenington** [comment]
Yeah, staging thinks it's already the 2021 season so I think using that is fine.

**Comment by rsgonzal** [comment]
ok @stenington , have it set up! I only have 1 onboarded for each group. Let me know if i should do more
1. Tessa tester
2. Tammy tester
3. Students: 1
Mentors: 1
Judges: 1

**Comment by rsgonzal** [comment]
> Then ask me to capture a backup, set the dates, and run `reset_for_season`. Afterwards...

hey @stenington ! could you do this part, please?

**Comment by stenington** [comment]
@rsgonzal Ok, done.

**Comment by rsgonzal** [comment]
> * Sign in as the mentor, confirm they need to resign the consent waiver

yes
> * Confirm they need to retake training

yes
> * Sign in as the judge, confirm they need to resign the consent waiver

yes
> * Confirm they need to retake training

yes
> * You should see 0 onboarded students, mentors, or judges after the reset

yes

All looks good to me!

**Comment by stenington** [comment]
Deployment here is changing the task that gets run in the scheduler, so I've done that. No code to deploy.
