### ISSUE TITLE
Enforce the file types we say we accept on the platform [13,5,2.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2573]
As a student, I should not be able to upload a file that the platform says it does not accept so that judges do not have issues with my submission.

Currently, we say we restrict certain file types in different places but students can still upload whatever they want.

**Source code**
- currently should only be accepting .zip and .aia
- this might change if 

**Pitch video link**
- can they enter any link? (ophelie says they upload?)

**Business plan**
- students upload other files that are not PDFs

### To Dos:
- Restrict business plan uploads to PDFs
- If we recognize a broken link (not correct video link) on upload, do not let the student save the video and mark the task as complete

## QA STEPS
For the business plan:
* Login as a student on a senior team
* Verify that the only file format accepted for the business plan is PDF

For the video validations:
* Login as a student
* Verify invalid demo and pitch videos can't be saved
* Verify valid demo and pitch videos can be saved

An invalid video basically means getting the "Your video link is broken. You should GO BACK and fix the link." message, if a student sees that then the Save button should be disabled.

**Comment by stenington** [comment]
I don't think this is true. It looks to me like the source code upload is restricted to .zip or .aia, and the business plan upload is limited to PDF. Maybe it's not ironclad and there's a way for students to get around this, but it looks like this enforcement is already in place.

**Comment by rsgonzal** [comment]
> Just to note, in some cases, the issue was not something that could have been caught by the platform file type by itself, but in combination with the purported App Language used.
> 
> For example, we accept .zip and .aia file types.
> 
> If a team submitted a project and selected App Inventor, they were supposed to upload an .aia file.
> 
> However, some teams uploaded .apk files, and some submitted .zip files containing other file types.
> 
> I understand that since the platform was set up to accept .zip file in general, the platform performed as expected. But it would be great if we could somehow link certain file types with certain submission requirements (i.e. IF you select App Inventor as your source code language, the field will ONLY accept .aia type files)

- For the above scenario, Team 4 Help (App name: Helpia) is an example--they originally uploaded a .zip file containing an APK file, instead of the required aia file.
The correct file type has since been reuploaded.

-Team Brain Max (app name: The Real Farmers Market) had also submitted an apk file instead of an aia file

-And Team PLAN NIÑAS COLE (app name: Refill bottle app) just put their aia file inside of a .zip file, for unknown reasons. The issue was that the judges scoring thought there was something wrong, so we had to investigate etc.

-Team Leap (app name Panacea) also sent a Zip instead of aia file

- Sorry, one last thing--I can't find an example of this, but I could have sworn some teams uploaded non PDF files for Business Plans

- also pointing out that if we're looking at file stuff for other things it would be helpful to explore the thunkable issue and see if we need to provide another field prompting api key info

**Comment by hellafitz** [comment]
- more specifically enforce allowed file type based on the app platform selected in submission materials (e.g. only allow .AIA for App Inventor)
- we can't enforce what's within zip files

**Comment by rsgonzal** [comment]
For Pitch & demo video
- they can upload any link but get an error, so there is some kind of check going on
- this still let's them save and counts it as part of their submission
- solution: it should not let them move on with a broken link
![Screen Shot 2020-12-15 at 9 08 19 AM](https://user-images.githubusercontent.com/22801026/102247860-5e7a2d00-3eb5-11eb-9ed7-fe3f9b8d12f9.png)

For business plan
- it does accept doc files 
- solution: ONLY accept PDFs

**Comment by shaunxp20** [comment]
Doh! This one is currently on the way to QA, I forgot though that we were planning to deploy tomorrow. If that's still the case, I can revert this one so we can get a deploy out. 🤔 😊 😀

**Comment by kate-technovation** [comment]
For the business plan:

1. Logged in as a student on a senior team
2. Verified that the only file format accepted for the business plan is PDF. 
-If I used the Select a File button, I couldn't even select a non-PDF file to upload. 
-For drag and drop, if I dropped a non-PDF file, a red X would appear and the file upload button wouldn't display:
<img width="485" alt="Screen Shot 2021-01-12 at 12 40 37 PM" src="https://user-images.githubusercontent.com/57409606/104351568-8ddf8200-54d3-11eb-83c3-43036d6bd96f.png">

-If I added a PDF, the upload button would appear:
<img width="698" alt="Screen Shot 2021-01-12 at 12 39 06 PM" src="https://user-images.githubusercontent.com/57409606/104351245-29bcbe00-54d3-11eb-99c5-05145086dac0.png">

-And if I clicked Save, only the PDF would upload:
<img width="509" alt="Screen Shot 2021-01-12 at 12 42 10 PM" src="https://user-images.githubusercontent.com/57409606/104351605-989a1700-54d3-11eb-9d56-5e7428c30414.png">

For the video validations:

Login as a student
Verify invalid demo and pitch videos can't be saved
Verify valid demo and pitch videos can be saved
An invalid video basically means getting the "Your video link is broken. You should GO BACK and fix the link." message, if a student sees that then the Save button should be disabled.

**Comment by shaunxp20** [comment]
Thanks for testing Kate (and for getting to it so quickly too!)! 😁 

> However, I was able to upload a Vimeo link (I'm not sure if that's normally accepted--it would be helpful to have the accepted video platforms on this page somewhere):

Good catch! I didn't realize we don't have the video formats listed on that page! The code is setup to accept/validate YouTube, Vimeo, and Youkou. 🎥 🧐 @rsgonzal, maybe we should verify those video formats, and add some info on the video upload pages? 😄 🤔

**Comment by rsgonzal** [comment]
Thanks for being so thorough @kate-technovation !! We actually to have them listed here
