### ISSUE TITLE
Support for Technovation WP launch in case of emergency [20,3,6.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2577]
Marketing team would like to have dev time available in case anything blows up as they go live with the App Gallery.

Ideal window to get the new modules live is next Monday-Wednesday (July 20-22)

**Comment by hellafitz** [comment]
We recommend (no meeting) Wednesday 7/22

**Comment by rsgonzal** [comment]
Happy Cog confirmed for 11am EST on 7/22

**Comment by stenington** [comment]
Closing this one, as nothing cropped up today.
