### ISSUE TITLE
it-27 ongoing support [2,1,2]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2580]
Expected support this iteration?

**Comment by hellafitz** [comment]
No expected support this iteration. This ticket is just to keep track of incoming requests for support (logging them here) and to make sure the team triages them in stand or team time.

**Comment by rsgonzal** [comment]
Well there's actually a bug on TF. I think this was already happening before the deployment this morning.

This link seems to be broken: https://curiositystaging.herokuapp.com/admin/lessons/lesson/
- this is how we get to that page with all of the lessons to edit through the admin
- broken on production as well.

Steps from Devin (I was able to recreate):  
- go to : https://curiositystaging.herokuapp.com/admin/
- login as admin
- It logs in, but as soon as I click on "lessons" to try to edit I see:

**Comment by stenington** [comment]
@rsgonzal Looks to me like a library needs upgrading to be compatible with Django 2.2. That'll take more than the 1 point we've allotted, but if this is urgent I can work on it anyway. Is it urgent?

**Comment by stenington** [comment]
Looks like you can't create new memberships right now either, which is blocking work on iridescent-cm/curiositymachine#2434
