### ISSUE TITLE
Review 19/20 TG support tickets [13,13,1]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2581]
Review the recently concluded season's support tickets to inform a nascent '20/21 TG Season Ops plan. Create a summary document and timeline showing key support times. Identify support tasks for future improvement.

**Comment by hellafitz** [comment]
Steps: find all the old support tickets, what we scored them, what was in them. Synthesize into a summary doc and a visual you can see at a glance. In the doc, include the previous list of support tickets and associated graph for reference.

**Comment by stenington** [comment]
Rough version we looked at last year: 
* https://docs.google.com/document/d/16c1Q94-jezcX52qItjSKudHpBJgJXcWV5WaydvlIixY/edit#heading=h.qplq66dr2h1a
* https://docs.google.com/spreadsheets/d/13N6n0ohyzUWbz-KT6nGgOzraeeNzo_w2QnwKzy5f_mQ/edit#gid=0

**Comment by hellafitz** [comment]
Search results for ("ongoing support" OR "bug support") issues https://github.com/Iridescent-CM/technovation-app/issues?q=is%3Aissue+%28%22bug+support%22+OR+%22ongoing+support%22%29

**Comment by stenington** [comment]
Notes compiled here: https://docs.google.com/document/d/1fTjuhzfRxnwpGSEfP5nKJGV8tiBNnlWPkQ1U4Zcv02Q/edit#

One thing I haven't done is go through tickets generated from the incoming support issues to see if there are bugs left to fix to prevent similar issues from happening next year, but I think it makes more sense to rely on our scrum processes for that.

**Comment by stenington** [comment]
I think I've taken this as far as I'm going to take it without input from others. Moving to "test" which in this case is getting other eyes on the doc.

**Comment by hellafitz** [comment]
I added 'support effort % by iteration' data to the doc. Moving this to done.
