### ISSUE TITLE
spike: what happens when a student account ages out [8,8,1]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2585]
from #2551

answer what happens when a student account ages out

reference: designing season rollover doc https://docs.google.com/document/d/1oBVG_RMi6SVQ8KlznqmdRT_FuNCgRCkBy8maM4tXeWA/edit#heading=h.7wh191bk4ijs

**Comment by stenington** [comment]
I'm not seeing any enforcement about aging out. The platform is letting me log in, create a team, and work on a submission without any indicator that I'm too old to be participating. It's not marking my team or submission as problematic in the admin at all. The only enforcement I'm seeing so far is at the time of sign up, where someone signing up who's too old won't be shown the option to select student as their profile type.

**Comment by hellafitz** [comment]
@hellafitz and @rsgonzal to discuss w/ Rebecca, Brian, Amy
