### ISSUE TITLE
Remove 'Convert to Judge' option for Mentors under 21?

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2590]
Kate suggested greying out to 'Convert to Judge' button for Mentors who are under 21 (because we require Judges to be 21). This is a bit entangled with ongoing deliberations about how to enforce that age-restriction and whether (and/or when) to display the Convert to Judge button for any Mentors at all.

**Comment by hellafitz** [comment]
Next step: get PT and CET to confirm policy for 20/21 season. 

Related Q: were any judges for 19/20 season under 21? If there was a policy, but it wasn't enforced, it would seem like this ticket would be very low priority.

**Comment by stenington** [comment]
You haven't specified exactly what the cutoff would have been (age 21 as of when) but here are the number of users by birth year for mentors marked as part of the 2020 season:

| year | count | 
| --- | --- |
| 2015 |     2 |
| 2008 |     1 |
| 2005 |     3 |
| 2004 |     5 |
| 2003 |    17 |
| 2002 |    38 |
| 2001 |   284 |
| 2000 |   331 |
| 1999 |   313 |
| 1998 |   324 |

**Comment by rsgonzal** [comment]
No one escalates this as an issue, discussion on what the cutoff age should be for judges. Closing
