### ISSUE TITLE
Certificates with Cyrillic characters aren't generating properly [5, 8, .63]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2591]
1) Confirm if the pdf filler library is the source of a bug that mangles (at least) Cyrillic characters when generating certificates. We haven't received complaints of any other characters causing problems but keep an eye open for that possibility too. 

2) Create a dataclip to determine how many students, mentors and judges are affected 

We'll use the info to determine next steps - namely whether to replace the pdf-filler library (if indeed that's the source of the issue) or to continue with manual design edits but support by using this dataclip to give a heads up as to how many will need a fix and specifically which ones. 

Context:
Via Kate, in the TF/TG Wishlist spreadsheet on 7/16: 
"Certain participants have names that display in Cyrillic letters, causing issues with certificates each year. 

EXAMPLE: 
Zendesk, ticket #12983
Ticket Requestor: RA Elena Seleznevafrom Uzbekistan [technovation.uz@gmail.com] 
Students impacted:
Believe in yourself Team members: 
-Linara Iskanderova
-Leysan Iskanderova
-Angel Lutsenka

Clever kids team Team members: 
-Snejanna Yahno
-Gulruxbegim Yuldasheva"

There is a current workaround, Audra manually created these students new certificates. Depending on the scope of the problem that might be an ok process to support going forward, if we can provide data on which certificates will need manual modification.

**Comment by stenington** [comment]
I was able to look up a certificate in production where the user had used cyrillic characters in their name, and where the resulting certificate had a series of question marks instead. ☹️ So yeah, bug confirmed.

For what it's worth, I used cyrillic characters to write parent name in a student test account, and the downloadable consent pdf was able to render them correctly. So we may want to see if we can rebuild the certificates using that same pdf generation tool, although that would totally change how certificates are updated each year.

**Comment by rsgonzal** [comment]
Outcome of ticket: Create dataclip to see how many students are affected

**Comment by rsgonzal** [comment]
https://technovation-qa.herokuapp.com/admin/participants/826#/

https://technovation-qa.herokuapp.com/admin/participants/745#/

https://technovation-qa.herokuapp.com/admin/participants/741#/

**Comment by viviancan** [comment]
Here is [a list of all accounts ](https://docs.google.com/spreadsheets/d/1FGQAz7uGi3WKy67J6YNeGuvPCqP8JreA3K-pbaala4M/edit?usp=sharing)with cyrillic characters in their first or last name

**Comment by rsgonzal** [comment]
That's more than I thought!

**Comment by rsgonzal** [comment]
Not a possible change for this season. This is a known problem with current library we are using. Should change library for next season
