### ISSUE TITLE
Upgrade webpacker from v3 to v4+ [20,20,1]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2595]
Final part of #2414, hopefully.

Upgrade webpacker from v3 to v4+, whatever is current (currently 5.1).

This will involve a bunch of knock-on upgrades (webpack, babel, possibly node).

#2592 is a rough spike to see what kind of fallout such an upgrade would entail.

**Comment by stenington** [comment]
False alarm on needing to upgrade node, it seems. Babel 7 drops support for node 0.10, not node 10. 😌

**Comment by stenington** [comment]
@rsgonzal This is now on staging. How much guidance do you want on QA?

**Comment by rsgonzal** [comment]
Tested different account types, submitted a project and judged. All looks good to me.
