### ISSUE TITLE
Spike: search improvements for admins [13,13,1]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2597]
From #2552

Kate has provided a number of specific searches and use cases that produce inaccurate or overwhelming search results in the admin https://docs.google.com/document/d/1MJuD5T82E6TXHw05w6KTiFEKAOuD7zqPMfOoyI4q-QI/edit

We want to figure out what's going on in these examples and identify high value improvements we can make to admin search, distinguishing between what can be done with or ideally without introducing new infrastructure (a search index).

For this spike:
- read Kate's doc
- explore the specific changes she suggests (looking at the backend for what's going on in these circumstances)
- here or in a new doc, pull out specific recs for improvements and how doable they are on top of Postgres (vs doing in a search index)

**Comment by stenington** [comment]
There are some clarifications requested in the doc, but the main thing I'm seeing here is that we should prototype whether search would work better if we replaced the `Name or Email` field with an expanded set of fields like `First Name, Last Name, Email, Parent Name, Parent Email`. We can play with the type of search used for each field as well (possibly allowing toggling between some of them through the UI if necessary).
