### ISSUE TITLE
Remove temporary redirects and custom code for Regional Ambassadors

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#2598]
In #2566 we renamed regional ambassadors to chapter ambassadors, and added redirects and some custom code to support the old terminology:
`config/routes.rb`
`spec/requests/regional_ambassador_requests_spec.rb`
`app/technovation/sign_in.rb`

At some point in the future we'll want to remove this supporting code.

**Comment by hellafitz** [comment]
Give people at least a year and the PT should give a heads up before we do this
