### ISSUE TITLE
Epic: improve admin search

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2599]
From Theme #2452 and reference doc https://docs.google.com/document/d/1MJuD5T82E6TXHw05w6KTiFEKAOuD7zqPMfOoyI4q-QI/edit

- Update Postgres from v10 to 11 #2600
- Split the ‘Name or Email field’
Then, after those two and collecting feedback...
- Add advanced search functions

**Comment by hellafitz** [comment]
Postgres and 'Name or Email' field split are complete. Now entering the feedback stage. 

@rsgonzal to ask Kate to try the old troublesome searches on Production (as shown in the doc she created), and ask the PT to recruit some CA's to keep notes/send feedback on how the new search functions work (or don't) for them.

**Comment by stenington** [comment]
I commented in #2620, but maybe this belongs here as well, in case we want to consider improving the **Name or Email** field as part of this epic.

This is how I think the "Name or Email" field is currently working:

![Screen Shot 2020-09-15 at 1 33 06 PM](https://user-images.githubusercontent.com/55319/93244706-277e6900-f758-11ea-953c-30eba22fda60.png)

The black text is examples of searches you might type. The colored underscores show which word(s) get checked against which field(s) as a fuzzy match.

**Comment by hellafitz** [comment]
#2683 and an equivalent PR are to add in-name descriptions to the new exact search fields

**Comment by hellafitz** [comment]
@stenington did we ever implement logging on admin search w/ associated user names (for the purposes of following up on satisfaction and usability)?

**Comment by hellafitz** [comment]
#2764 is to implement logging on admin search
