### ISSUE TITLE
Update Postgres from v10 to v11 [13,8,1.63]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2600]
Part of Epic #2599 and associated Theme to upgrade admin user search.

Deliverable: For both upkeep and to enable more advanced search on the admin, upgrade Postgres from v10 where we are to v11. 

Be sure to make an announcement in Slack for when the site is going to be down for this upgrade.

**Comment by hellafitz** [comment]
@stenington do you think this should this be a spike first, or can we proceed directly?

**Comment by hellafitz** [comment]
Decision: proceed directly. 

Steps notes (@stenington to edit/update with link) : 
- Use Heroku toolbelt to provision a new database of the version you want as a follower. Then wait for it to catch up. issue commands to shut down the old one and turn the follower into the main database. (There is some downtime; should be done within a day). 
- May need a new postgres version on CI to make sure version matches

**Comment by stenington** [comment]
Heroku docs, we should be able to do the `pg:upgrade` option. https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases

**Comment by stenington** [comment]
Nice, thanks for the notes @shaunxp20. I can take a crack at updating CI and staging tomorrow.

**Comment by stenington** [comment]
Can't go to v12, `postgresql-client-12` doesn't seem to be available yet.

**Comment by stenington** [comment]
Staging is now on postgres 11. `HEROKU_POSTGRESQL_GRAY_URL` is the v10 database in case we need that back. Otherwise it can be deprovisioned after this passes QA I think.

**Comment by stenington** [comment]
Apparently the update method doesn't work to upgrade versions, so I'm following the copy steps for production as well.
