### ISSUE TITLE
Update TG emails for 20/21 season [20,20,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2601]
Emails need updating. First step is to gather copy from Program Team

## QA Recommendation

1. check each email in the [referenced doc](https://docs.google.com/document/d/1Fg5pw-ROi3ngKPm_Z-CmUbozXS1DLWX5uZ12IyIfb4k/edit#) for the updates requested
2. also invite a student **who already has an account** to your team, and look up a mentor and invite them to your team
3. confirm that both of those emails are still correct (they shared a template with the invitation for students without accounts)

**Comment by rsgonzal** [comment]
Rough list of emails/copy: https://docs.google.com/document/d/1vWOEY7CA3O4ojCULyajA2_OXEqnUGmLzXhcbAQbwi6g/edit#heading=h.d9r2f2l02xjl

**Comment by rsgonzal** [comment]
- Double emails send out to student after parent signs consent form

**Comment by hellafitz** [comment]
Decision: need final email copy by Monday 9/7 EOD. Rebecca is point on PT. 
- @rsgonzal to doublecheck the list by pulling the emails again

**Comment by hellafitz** [comment]
Email copy has been provided. @rsgonzal to organize it for easier implementation. Would be available by next week.

**Comment by rsgonzal** [comment]
organized changes: https://docs.google.com/document/d/1Fg5pw-ROi3ngKPm_Z-CmUbozXS1DLWX5uZ12IyIfb4k/edit#

**Comment by stenington** [comment]
Reiterating a comment from within the doc: we're planning to update the `HELP_EMAIL` setting as part of this, which will change things beyond just emails, but that's desired.

**Comment by stenington** [comment]
We will also want to update `MENTOR_SLACK_SIGNUP_URL` as part of this.

**Comment by stenington** [comment]
I have updated `HELP_EMAIL` and `MENTOR_SLACK_SIGNUP_URL` on staging only.

**Comment by stenington** [comment]
@rsgonzal Can I change the help email and mentor slack on production now? That doesn't need to happen at the time of season rollover does it?

**Comment by rsgonzal** [comment]
Yes! You can change it now. Thanks!

**Comment by stenington** [comment]
Ok, these have been updated in production as well.

**Comment by ksrebecca** [comment]
QA - looked at, left comments in the doc, confirmed the different emails!

**Comment by ophelieh** [comment]
I am adding edits to the document provided in the QA description. 

I tested as:
- a new student
- a student asking to join a team
- a student receiving a request to join a team. _Note - as the student sending the invite, I did not receive a confirmation when my invite was accepted or denied._ 
- a mentor receiving a request to join a team. _Note - as the student sending the invite, I did not receive a confirmation when my invite was accepted._ 
- a chapter ambassador who got invited to create an account

I confirm that as a parent I receive the consent form then a copy once I sign it. 

I did NOT test as a new mentor. Leaving that for CET. :)

**Comment by mdancho** [comment]
I tested as a mentor and left notes on the document provided in the QA description.

**Comment by stenington** [comment]
@rsgonzal I've moved this back to test with the additional changes that had come in.

**Comment by ksrebecca** [comment]
QA:
-Student welcome email - looks great.
-Parent consent email - looks accurate. But @rsgonzal  I thought I submitted more changes to the sentence under the button - Just found the text, it may have shown up in a different comment because my computer was acting weird? Here's what I had said:  "Instead of saying, "If you have any questions, or you cannot use the link above, reply to this email immediately" maybe we rephrase to say "If you cannot use the link above, your daughter can also resend this email or download the form from her dashboard (link?). If you still have questions, reply to this email, which is support@technovation.org" "
-3 Day Letter - does not have changes but rox confirmed they should be in future
-Mentor welcome email - looks great!

**Comment by rsgonzal** [comment]
Edited Rebecca's messaging.

Mackenzie gave the all clear on mentor email.

**Comment by ophelieh** [comment]
**Welcome email** 
Looks good but I have a couple of edits. 
* link to "key dates" is still the old one. Should be https://technovationchallenge.org/wp-content/uploads/2020/09/Technovation-Girls-2021-Season-Timeline-Key-Dates-Infographic.pdf

* October 2020: Registration Opens: You can now register your team and get started --- remove the colons after "opens" for consistency with the other bullet points 
<img width="1013" alt="Screen Shot 2020-10-07 at 3 26 47 PM" src="https://user-images.githubusercontent.com/32206421/95384082-b98a1500-08b1-11eb-8a55-297648c3a9d8.png">

**Parent Consent** 
Looks good! 

**Mentor Email**
Overall looks good but I have a few edits

* bullet 4 brings to the old timeline. Needs to be changed to - https://technovationchallenge.org/wp-content/uploads/2020/09/Technovation-Girls-2021-Season-Timeline-Key-Dates-Infographic.pdf

<img width="1026" alt="Screen Shot 2020-10-07 at 3 38 11 PM" src="https://user-images.githubusercontent.com/32206421/95385222-48e3f800-08b3-11eb-9690-a9fcd8531c14.png">

* bullet 6 brought me to my dashboard but with an error message

<img width="1440" alt="Screen Shot 2020-10-07 at 3 34 08 PM" src="https://user-images.githubusercontent.com/32206421/95384796-bc393a00-08b2-11eb-8ca5-1d4442b505df.png">

* I received 2 welcome emails within 1 minute apart
<img width="1123" alt="Screen Shot 2020-10-07 at 3 37 00 PM" src="https://user-images.githubusercontent.com/32206421/95385014-04585c80-08b3-11eb-9fbd-0604339615a9.png">

**Comment by rsgonzal** [comment]
hey @ophelieh ! 

- I have #2722 for the timelines
- I want to move this ticket forward so that we can deploy. How important is the semi colon?
- I'll look into the error message and potentially open another ticket
- Not sure why the double emails are getting sent, it doesn't seem to be a consistent pattern

**Comment by ophelieh** [comment]
Awesome! 

The colon is not that important but would be nice for future edits. :) And thanks!

**Comment by rsgonzal** [comment]
Checked the last edit and looks good!
