### ISSUE TITLE
Update Config Dates for 20/21 season [13,3,4.34]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2602]
New dates need to be put into heroku

**Comment by rsgonzal** [comment]
Config dates pulled out last year: https://docs.google.com/spreadsheets/d/1Gbe58Jw3yoVSlvMidcfrKGEX8TCcdg30UoE2Q1d5Rew/edit

**Comment by hellafitz** [comment]
! As of now, new season is configured to start 10/1

**Comment by hellafitz** [comment]
Season start date from platform perspective should be 10/10 (already confirmed ok w/ Rebecca)

**Comment by stenington** [comment]
@rsgonzal Saw this in test. It looks to me like the dates in the spreadsheet have been entered into production, but the spreadsheet is also out of date. We also need dates or corrections for

```
DATES_NEW_SEASON_START_DAY:               1
DATES_NEW_SEASON_START_MONTH:             10
DATES_OFFICIAL_START_OF_SEASON_DAY:       
DATES_OFFICIAL_START_OF_SEASON_MONTH:     
DATES_OFFICIAL_START_OF_SEASON_YEAR:      
DATES_REGISTRATION_OPENS_DAY:             1
DATES_REGISTRATION_OPENS_MONTH:           10
DATES_REGISTRATION_OPENS_YEAR:            2018
DATES_TEAM_REGISTRATION_DEADLINE_DAY:     
DATES_TEAM_REGISTRATION_DEADLINE_MONTH:   
DATES_TEAM_REGISTRATION_DEADLINE_YEAR:    
```

FWIW I think this is where #2619 would be useful, rather than trying to keep a spreadsheet up to date.
