### ISSUE TITLE
Spike: create plan for switch to technovation.org [20,13 (5 dev),1.54]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2604]
Leadership's ideal timeline is for Labor Day Weekend, however:

- We may need more time to create plan
- If it involves developer time over the weekend, we shouldn't pursue

Amy can be on the planning team

**Comment by hellafitz** [comment]
Primary reference doc: Change your primary domain for G Suite https://meet.google.com/linkredirect?authuser=1&dest=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F7009324%3Fhl%3Den

**Comment by stenington** [comment]
Google Support says to try [following the doc referenced above](https://support.google.com/a/answer/7009324?hl=en) and it may work. If not, the process is basically to sign up for a new account and then contact them to do a migration, I think. Quoting support:

> In that case you have to create another G Suite account with the domain you want, transfer the migration, cancel old G Suite, contact us from the new G Suite and request the transfer subscription. We have to send some internal documentation and wait 3 days, after that the G Suite for Non Profit team will change your subscription by their end.

For completeness, I want to include here another piece of documentation I get to from the admin. There's a place where it says "You can change your primary domain by switching it with an active secondary domain [Learn more](https://support.google.com/a/answer/54819?hl=en)" and links to this slightly less encouraging doc. But I think we really do want to pursue the primary domain change, the other options don't cut it.

**Comment by stenington** [comment]
@hellafitz See my [previous comment](https://github.com/Iridescent-CM/technovation-app/issues/2604#issuecomment-675125690). We should try the steps in the document but it's not guaranteed to work. If it works though, it's easier than the alternative method.

**Comment by stenington** [comment]
Summarizing an update shared elsewhere:

The thing I didn't realize about doing the primary domain change is that **it requires us to remove the technovation.org domain alias first**. So there would be a period up front where emails sent to technovation.org wouldn't be received, and then a period at the end where emails sent to iridescentlearning.org wouldn't be received. Each of those could last several days, even if the change is ultimately successful. If things go wrong it could be longer.

It also seems like there's a certain amount of inescapable collateral damage, like losing gchat histories or things like that: https://support.google.com/a/answer/2622985 It's kind of hard to figure out ahead of time everything that might break or interrupt someone.

So it doesn't seem possible to orchestrate this in a way that doesn't introduce a significant level of interruption.

**Comment by hellafitz** [comment]
Leadership Team confirmed the decision (coming out of TF/TG) to postpone this switchover through at least the end of the year. In the meantime, we will decommission the standalone GSuite account for technovationchallenge.org on Th 9/4 and then add it as an alias to our primary GSuite account on Fri 9/5.

**Comment by hellafitz** [comment]
#2617 is the followon implementation ticket, now compled
