### ISSUE TITLE
Stop Mentors-who-converted-from-students from receiving student emails [8,13,0.62,]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2606]
When a student is converted to a mentor, you would expect they no longer need permission from their parents to participate. However, they are still receiving an email to sign the form. They also received the student welcome email. This was reported by Ophelie after logging in as a converted mentor on Staging. 

Open Qs: Is the platform treating them like a student in any other way?

## QA STEPS
* Ensure the welcome email and parental consent emails aren't being sent out to students who have been converted to mentors, one way to do this:
* As an admin, find a student who has participated in a previous season (but not the current one)
* Update this student's email address to your own, then convert this student to be a mentor
* Log in as this student/mentor, you shouldn't get the student emails

**Comment by hellafitz** [comment]
@mdancho @ophelieh any idea how many account go from student to mentor each year (roughly)?

**Comment by ophelieh** [comment]
Hi! I would say between 15 to 30, not including accounts that had been converted in previous seasons.

**Comment by rsgonzal** [comment]
1. Stop converted mentors from receiving student emails
2. Stop sending out parent consent for these users

**Comment by stenington** [comment]
Deliverable here is stopping the sending of the two emails mentioned above: student welcome and parental consent. 

The open question mentioned up top is still an open question, but should be explored elsewhere.

**Comment by shaunxp20** [comment]
The fix I made for this: basically if an account has both a student and mentor profile, we'll just onboard them as a mentor, and none of the student onboarding code (which includes these two emails) will get run.

A more robust fix would be something like adding the `seasons` field to the profile tables (student, mentor, judge, chapter ambassador), then accounts could have multiple profiles and we could know which profile types participated in which season.

I also looked briefly at the other places that reference `student_profile` and it's too hard/time consuming to go through all of them to see how it could affect the student-mentor combo situation. Instead, we could reach out to mentors who also have a student account and see if they ran into any other issues, or just leave it be until someone notices something, or create another ticket to do more of a deep dive on this. 🤷 😄

**Comment by shaunxp20** [comment]
This one is on QA, and some QA steps have been added as well. 😄 👍 🌞

**Comment by ophelieh** [comment]
Hi all,

When I log in as a student who's now a mentor, my profile looks right and I did not receive the student emails - so this works. I received no email at all. Do mentors not receive a copy of the consent they sign? 

This is what I noticed - not related to emails though. If there is another ticket where to out this, let me know. 
In the admin side, it's a little confusing as I still see the student part and if I don't pay close attention I could add the student on a team vs the mentor. I clicked "Create paper consent" to see what it did, and I still see the convert to a mentor student. Does that mean it didn't take? 

<img width="1440" alt="Screen Shot 2020-09-10 at 7 45 51 AM" src="https://user-images.githubusercontent.com/32206421/92732141-a54b0a80-f33b-11ea-8e37-c760ef8e1ca8.png">
<img width="1440" alt="Screen Shot 2020-09-10 at 7 46 38 AM" src="https://user-images.githubusercontent.com/32206421/92732146-a67c3780-f33b-11ea-860c-38b12189ca94.png">

It's also confusing that both types of certificates show
<img width="1440" alt="Screen Shot 2020-09-10 at 8 08 07 AM" src="https://user-images.githubusercontent.com/32206421/92733032-d1b35680-f33c-11ea-9a33-b23d9190c482.png">


A non-related bug, will probably need an extra ticket is I cannot save my changes when trying to "Edit a participant", here I was trying to change the student email. I couldn't save it - it didn't do anything when I clicked "Save changes" and when I went back to that page, the email didn't change. There is another way to change an email but you need the password for that so not optimal. 
<img width="1440" alt="Screen Shot 2020-09-10 at 7 58 07 AM" src="https://user-images.githubusercontent.com/32206421/92732150-a7ad6480-f33b-11ea-971a-185dcf2f84da.png">

**Comment by ophelieh** [comment]
@kate-technovation Could you also take a look as you help convert students to mentor? 

Thank you!!

**Comment by shaunxp20** [comment]
Thanks for the thorough review, @ophelieh! 🙌 😄 

I created #2648, #2649, and #2650 for all of the issues you are experiencing, for our team to discuss. 😅 

Fwiw, regarding #2650, not being able to save the email address, from what I'm experiencing, if you select a "Mentor type" then the email address can be saved. 😄

**Comment by kate-technovation** [comment]
@ophelieh Sure thing! 

1. Worked as expected (As an admin, find a student who has participated in a previous season (but not the current one)):
<img width="919" alt="Screen Shot 2020-09-10 at 2 21 11 PM" src="https://user-images.githubusercontent.com/57409606/92780260-e3165600-f370-11ea-8832-695d82fcfb8f.png">

2. Worked as expected (Update this student's email address to your own, then convert this student to be a mentor):
<img width="1038" alt="Screen Shot 2020-09-10 at 10 34 36 AM" src="https://user-images.githubusercontent.com/57409606/92780337-00e3bb00-f371-11ea-9469-095674c50400.png">

3. Worked as expected (Log in as this student/mentor, you shouldn't get the student emails):
<img width="1131" alt="Screen Shot 2020-09-10 at 2 04 19 PM" src="https://user-images.githubusercontent.com/57409606/92780363-093bf600-f371-11ea-8676-7be8d5f17a1a.png">

**Comment by shaunxp20** [comment]
Great, thanks for testing this @kate-technovation! 👍 😄 🌞

**Comment by kate-technovation** [comment]
My pleasure @shaunxp20 ! Thanks for doing this work with the team! :D

**Comment by ophelieh** [comment]
Thank you Shaun!!! And thank you Kate! :)
