### ISSUE TITLE
Epic: Prevent team invites from stalling out

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2607]
Team invites are a little finicky. Kate described three common scenarios:

1. Girls would write to us if they requested to join a team, and that team did not accept their invitation; the girls requesting to join could not ask to join other teams until the original team requested, rejected them. 

2. Teams who received requests to join from girls they didn't know or didn't want sometimes had trouble accepting invites from girls that they did want, because of the unwanted invites "jamming up" their request channel (not sure exactly what the issue was, but we got these tickets occasionally).

3. Teams who accidentally accepted invites of girls they didn't want or accepted girls who later turned out to not be good teammates and then could not remove the problematic person themselves--only the problematic person could remove themselves from the team (or we could, but that led to us needing to verify who was saying what in a sticky situation).

Solutions:
- Girls can cancel a request they sent out
- Pending requests are canceled after a user is on a team

While I was messing with team invites and had previously invited a team member and the same team member requested to join the team. Never approved on either end.

Then added team member as an admin. Logged in as North Dakota, when I go to my team I see:

![screencapture-technovation-qa-herokuapp-student-teams-228-2020-08-19-10_41_40](https://user-images.githubusercontent.com/22801026/90671098-0e41d580-e209-11ea-8043-338718766a9f.png)

**Comment by rsgonzal** [comment]
1. Talk to program team about ideal situations for scenarios
2. Split off my scenario as a bug

**Comment by rsgonzal** [comment]
#2660 & #2661 were created to address the issues

**Comment by hellafitz** [comment]
DONE: 
- Allow students and mentors to cancel their team join requests #2660
- Bug: Student sends request to join a team but it doesn't stick #2662

HOLD: Make 'No' default option for allowing team to be visible by others #2664

CLOSED: #2661 we decided wasn't a bug
