### ISSUE TITLE
Add help text on Judging in Content & Settings [5,5,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2616]
Currently, the team does not understand the implications of the different options when judging is open.

Suggestion is to add help text for a little more clarity. I think the suggestions from the user docs would be helpful: https://docs.google.com/document/d/1bFN0yf2M0RrpdxBaq4tudNfhcvGetifY3v1gnHvkV20/edit?usp=sharing

![Screen Shot 2020-08-27 at 9 36 59 AM](https://user-images.githubusercontent.com/22801026/91470172-394fa900-e849-11ea-954e-16ea51d59250.png)

![Screen Shot 2020-09-09 at 1 18 21 PM](https://user-images.githubusercontent.com/22801026/92648897-08d32a80-f29f-11ea-93d7-f824597252f3.png)

## QA STEPS

View the new help text tooltips (for the judging options):
* verify the help text
* verify the document link/link-text

**Comment by rsgonzal** [comment]
Let's also link the reference doc somewhere on this screen

**Comment by shaunxp20** [comment]
Here are a couple of samples/mock-ups for this:

# Inline help text
<img width="1076" alt="Screen Shot 2020-09-14 at 2 35 43 PM" src="https://user-images.githubusercontent.com/58957909/93140732-784b7e80-f6d2-11ea-9fa4-b0075eb36a67.png">

-----

-----

# Help text below in a table
<img width="1076" alt="Screen Shot 2020-09-14 at 3 13 15 PM" src="https://user-images.githubusercontent.com/58957909/93140755-826d7d00-f6d2-11ea-9a63-8b6511809903.png">

-----

-----

# Help icons with tooltips
<img width="1076" alt="Screen Shot 2020-09-14 at 3 34 32 PM" src="https://user-images.githubusercontent.com/58957909/93140792-931df300-f6d2-11ea-91dc-db2b51adb612.png">


Not shown here, but there will also be a link to the doc for more information.

**Comment by rsgonzal** [comment]
Ouh! Thanks for the options, shaun! I kind of like the third one. @nickiredescent what do you think will be most helpful?

**Comment by nickiredescent** [comment]
I also like the third one. Looks good!

**Comment by shaunxp20** [comment]
Cool, thanks for the feedback @rsgonzal @nickiredescent, I'll work on the third one today! 😄 👍 🌞

**Comment by shaunxp20** [comment]
This one is on QA, basic QA steps have been added as well. 😄 😁

**Comment by rsgonzal** [comment]
@shaunxp20 can you make the document open in a new tab please?

**Comment by shaunxp20** [comment]
> @shaunxp20 can you make the document open in a new tab please?

Sure thing!

**Comment by nickiredescent** [comment]
Tested on the site.
I like the changes and the additional document link. Really helpful and makes sense to me.

Couple things:
 - I'm curious if this makes sense to someone else who's not as used to the settings. For example, would a new person know what "sees the 'Between Rounds' screen" means? Does that matter? 
 - Definitely agree with Rox, the doc should open to a new tab.

**Comment by shaunxp20** [comment]
> * I'm curious if this makes sense to someone else who's not as used to the settings. For example, would a new person know what "sees the 'Between Rounds' screen" means? Does that matter?
> * Definitely agree with Rox, the doc should open to a new tab.

Not sure on the first one, but I'd be happy to make any changes if we can find a way to make it clearer. And the update to make it open in a new tab/window will be ready soon. 😃

**Comment by shaunxp20** [comment]
Thanks for the feedback @rsgonzal @nickiredescent, it's back on QA with the updates, ready for another looksie when y'all get a chance. 😄 🌞 🌳 🚶 🎶

**Comment by mdancho** [comment]
Confirming that the help text appears clearly on the Judging tab in Content & Settings.

**Comment by rsgonzal** [comment]
thanks for testing! @nickiredescent do you have any suggestions for other text on the between rounds one? not sure what would be most helpful

**Comment by rsgonzal** [comment]
going to move this to done since it's working! I think the doc explain the between rounds.

**Comment by shaunxp20** [comment]
Thanks for looking at this @mdancho! 🙌 🥳 🎉

**Comment by shaunxp20** [comment]
Sounds good, thanks @rsgonzal!  🙌 🎊 🎈
