### ISSUE TITLE
Shut down TechnovationChallenge.org GSuite 9/3-4 [20,8,2.5]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2617]
Close down the standalone TechnovationChallenge.org GSuite account and then add the domain to our primary GSuite account for IridescentLearning.org (/Technovation.org)

**Comment by stenington** [comment]
Post in #dev-team when starting

**Comment by stenington** [comment]
Done around 10:30am ET on 9/3, now waiting for the domain to free up within Google's systems to be added as a domain alias. It currently claims the domain is being used, and support docs say it can take up to 24 hours for that to change.

**Comment by stenington** [comment]
i was able to add technovationchallenge.org as a domain alias in our iridescentlearning.org account, so now it’s a waiting game for that change to propagate. up to 72 hrs, i think the docs said.

**Comment by stenington** [comment]
I believe emails are going through on the new domain alias today. @rsgonzal Can you test and confirm?

**Comment by rsgonzal** [comment]
tested & confirmed!
