### ISSUE TITLE
Investigate if/why double emails are still being sent out for parent consent [?,5,?]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2623]
After entering my parent email, two emails get sent to the parent.

**Comment by hellafitz** [comment]
@rsgonzal to investigate (it appears that it happens sometimes but not all the time; isolate the factors involved)

**Comment by stenington** [comment]
@rsgonzal Was this on an account that had already had a parental consent from last year? Or is this on a brand new account that you're seeing the double emails?

**Comment by rsgonzal** [comment]
So it happened for Suzie G and it looks like she is a new student

**Comment by rsgonzal** [comment]
i just created a new account and didn't get double emails

**Comment by stenington** [comment]
@rsgonzal How close together are the double emails being sent?

**Comment by rsgonzal** [comment]
Looks like the exact same time

**Comment by stenington** [comment]
Ok. Looking in the Mandrill logs, I do see double emails sent to you on Aug 28 around 2:11pm, but in general I don't see a pattern of double emails being sent.

**Comment by hellafitz** [comment]
@rsgonzal do you have any reports of this happening to other users?

**Comment by rsgonzal** [comment]
@ophelieh just experienced this signing up as new student "Sara Croche"

**Comment by hellafitz** [comment]
@rsgonzal any recent reports?

**Comment by hellafitz** [comment]
Next steps:
- investigate Mandrill logs to find frequency and most recent occurrences
- Inform QA and PT staff that we're investigating and that if this happens they should immediately fill out the bug report
