### ISSUE TITLE
Ops: Evaluate if we stop using Dreamhost pt.1 [8,13,0.62]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2639]
Overall goal for this project: Evaluate anything in there and triage any required backups so we can stop using Dreamhost. If we need to keep stuff, where does it go? in connection w/ PT

We had a 5 year federal grant requirement to keep the site. KeyTag, old CM, and maybe other stuff.

Dreamhost cost $175/month

**Comment by hellafitz** [comment]
Deliverable: 
- Are there any URLs pointing back to Dreamhost? If so, what are they?

Open Qs (out of scope for this part): 
- which user accounts are set up, what are the credentials, and what do they each access? (these were former contractors who predated Mike)

Future: do a screenshare with someone from PT or LT who can make decisions on the spot

**Comment by stenington** [comment]
@amyiridescent is going to take a look at what might be worth keeping.

**Comment by stenington** [comment]
I've backed up a bunch of home directories on the server into `s3://iridescentlearning/backups/dreamhost/`. It's 43GB but given that nothing on the server was available on the web any more, it's way cheaper to store it in S3 than paying for the server. Here are the specific directories I backed up:

```
backups/dreamhost/ahad/   7 Objects - 2.6 KB
backups/dreamhost/ahad/   7 Objects - 2.6 KB
backups/dreamhost/anutewary/   58 Objects - 72.5 KB 
backups/dreamhost/guesserwebuser/   10852 Objects - 558.8 MB 
backups/dreamhost/iridescent/   55186 Objects - 1.5 GB
backups/dreamhost/iridescent1/   14 Objects - 3.1 KB
backups/dreamhost/judyh0/   12619 Objects - 932.0 MB
backups/dreamhost/looknfeel/   315 Objects - 583.2 KB
backups/dreamhost/mchock/   14 Objects - 3.1 KB
backups/dreamhost/mruti/   12 Objects - 798.8 MB  
backups/dreamhost/mtsybrik/   32573 Objects - 440.4 MB  
backups/dreamhost/mtsybrik1/   15 Objects - 56.7 KB
backups/dreamhost/mtsybrik2/   106028 Objects - 36.7 GB 
backups/dreamhost/mtsybrik3/   285 Objects - 6.6 MB
backups/dreamhost/nataliemaclees/   4 Objects - 813.0 B 
backups/dreamhost/ricardotocha/   24002 Objects - 1.9 GB 
backups/dreamhost/scriptcam/   4 Objects - 813.0 B
backups/dreamhost/scriptcam_live/   771 Objects - 73.7 MB  
backups/dreamhost/tchklovski/   20188 Objects - 159.8 MB 
```

**Comment by stenington** [comment]
We are approved to close, but the "primary account" must be the one to close. That's been communicated so I think this ticket is done.
