### ISSUE TITLE
Mentor details page standardization and accept/decline options [13,13,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2642]
From the student dashboard, a student can click on two types of mentors
- ones that are on their team
- ones that are not on their team yet but requested

![Screen Shot 2020-09-09 at 9 26 49 AM](https://user-images.githubusercontent.com/22801026/92626552-e6c9b000-f27e-11ea-8a10-9bd1aa807089.png)

Changes:
- add the same back button to the mentor detail page of a mentor on the team
- allow the student to approve the mentor on the page from a mentor who requested to join team, by adding the buttons we see on this page 
- remove the hyperlink back to My Team invites:
![Screen Shot 2020-09-09 at 9 32 52 AM](https://user-images.githubusercontent.com/22801026/92626903-74a59b00-f27f-11ea-9b68-b914ddac775f.png)

## Recommended QA:

**Back link**
1. find (or create) a team with mentors who have been invited, and mentors who have requested to join
2. click through to the mentor profile of both, and make sure both have the desired link back to the dashboard

**Approve/decline controls**
1. find (or create) a team with 4 mentors requesting to join it
2. approve one from the dashboard
3. approve one from within the mentor profile,
4. decline one from the dashboard
5. decline one from within the mentor profile
6. for all of the above, make sure you were taken to the right page with the right message, and the mentor is/isn't on the team as appropriate

**Additional testing**
1. Maybe try searching for a mentor already on your team and viewing their profile, ensure it doesn't error out and displays correctly (e.g. doesn't show approve/decline controls any more)
2. Same for a mentor not on your team that hasn't been invited or requested to join

**Comment by hellafitz** [comment]
Screenshots are from https://projects.invisionapp.com/freehand/document/1hk5y3kgu

**Comment by hellafitz** [comment]
Open Q: 
- what should happen when the buttons are clicked? (e.g. show confirmation and take you back to My Team page.

**Comment by rsgonzal** [comment]
A:
- pop up confrming
- green banner to say they were approved
- goes to mentor section of team pages
![Screen Shot 2020-09-09 at 12 28 19 PM](https://user-images.githubusercontent.com/22801026/92644385-1b963100-f298-11ea-9dfe-d2bf470fc75d.png)
![Screen Shot 2020-09-09 at 12 28 08 PM](https://user-images.githubusercontent.com/22801026/92644390-1df88b00-f298-11ea-9145-ed4c1a5d3371.png)

**Comment by hellafitz** [comment]
If Comp Effort is overtaken by a more difficult reality, split off a new ticket

**Comment by kate-technovation** [comment]
Back link QA:
1. Find (or create) a team with mentors who have been invited, and mentors who have requested to join
-I logged in as a Student, created a team "Jellicle Cats", and added Judith as a Mentor:
<img width="846" alt="Screen Shot 2020-09-18 at 2 04 19 PM" src="https://user-images.githubusercontent.com/57409606/93630411-087e1200-f9b8-11ea-9183-b7006adf1c87.png">

I clicked on the View Profile button, saw Judith's profile, and saw the "Back to your Team" button. 
<img width="853" alt="Screen Shot 2020-09-18 at 2 04 45 PM" src="https://user-images.githubusercontent.com/57409606/93630417-0a47d580-f9b8-11ea-840c-28fcb7577f12.png">

I clicked on it, and it worked:
<img width="853" alt="Screen Shot 2020-09-18 at 2 12 40 PM" src="https://user-images.githubusercontent.com/57409606/93631110-049ebf80-f9b9-11ea-8e60-6551e4ed7144.png">

**Comment by kate-technovation** [comment]
Approve/decline controls:

I created the "Jellicle Cats" team and had four mentors request to join it:
<img width="876" alt="Screen Shot 2020-09-18 at 2 33 29 PM" src="https://user-images.githubusercontent.com/57409606/93632789-ed150600-f9bb-11ea-8a2c-4a3c89632bcb.png">

I approved one mentor from the dashboard, and it worked as expected:
Clicking button:
<img width="854" alt="Screen Shot 2020-09-18 at 2 33 58 PM" src="https://user-images.githubusercontent.com/57409606/93632836-fef6a900-f9bb-11ea-9a7b-bc8d115d7ef7.png">

Post approval:
<img width="846" alt="Screen Shot 2020-09-18 at 2 34 07 PM" src="https://user-images.githubusercontent.com/57409606/93632848-0453f380-f9bc-11ea-930b-b57638d41707.png">

I then approved a mentor invite from within the mentor's profile, and it also worked as expected:
Clicking the button:
<img width="857" alt="Screen Shot 2020-09-18 at 2 35 14 PM" src="https://user-images.githubusercontent.com/57409606/93632978-3c5b3680-f9bc-11ea-8535-11a6701ca4fe.png">

Post approval:
<img width="785" alt="Screen Shot 2020-09-18 at 2 35 21 PM" src="https://user-images.githubusercontent.com/57409606/93633012-45e49e80-f9bc-11ea-8aaf-811af40d4622.png">

I then declined one mentor from the dashboard:
Clicking the button:
<img width="845" alt="Screen Shot 2020-09-18 at 2 36 21 PM" src="https://user-images.githubusercontent.com/57409606/93633053-539a2400-f9bc-11ea-891b-80314bdd2067.png">

Post disapproval:
<img width="850" alt="Screen Shot 2020-09-18 at 2 36 43 PM" src="https://user-images.githubusercontent.com/57409606/93633088-60b71300-f9bc-11ea-9e21-573a97b44819.png">

Lastly, I declined one mentor from within the mentor profile, and all worked as expected:
Clicking the button:
<img width="855" alt="Screen Shot 2020-09-18 at 2 37 23 PM" src="https://user-images.githubusercontent.com/57409606/93633139-79bfc400-f9bc-11ea-99ae-92c75ea92da7.png">

Post disapproval:
<img width="852" alt="Screen Shot 2020-09-18 at 2 37 35 PM" src="https://user-images.githubusercontent.com/57409606/93633156-7fb5a500-f9bc-11ea-8e41-31ed26ebc6e4.png">

**Comment by kate-technovation** [comment]
Additional testing:

I have a team called Jellicle Cats with two mentors, Sally Salad and Gua Bao:
<img width="1118" alt="Screen Shot 2020-09-18 at 4 32 11 PM" src="https://user-images.githubusercontent.com/57409606/93642703-83e9be80-f9cc-11ea-89db-c2f37c017b6b.png">

I searched for a mentor (Sally Salad) already on my team, Jellicle Cats. I noticed that I saw "Ask Sally to mentor your team" button, even though she is already a mentor on my team-- **this seems like a possible error**:
<img width="1122" alt="Screen Shot 2020-09-18 at 4 30 17 PM" src="https://user-images.githubusercontent.com/57409606/93642538-3f5e2300-f9cc-11ea-98cc-fdcfdc1d49ef.png">

I then searched for a mentor not on my team, that hasn't been invited or requested to join:
<img width="1123" alt="Screen Shot 2020-09-18 at 4 47 10 PM" src="https://user-images.githubusercontent.com/57409606/93643753-9a911500-f9ce-11ea-921d-0b88f434fe6c.png">

I could not view this mentor's profile (there were no buttons on the profile to view it, beyond the "Ask Aline to mentor your team").

**Comment by ophelieh** [comment]
I logged in as a student (North Dakota) with 2 pending invites to mentors. when I logged, my dashboard was a little trippy - there are 2 buttons saying "Manage mentor invites" 
- both buttons brought me to the "my team" page as expected. 
<img width="1440" alt="Screen Shot 2020-09-18 at 3 51 57 PM" src="https://user-images.githubusercontent.com/32206421/93644180-14250500-f9c7-11ea-9651-51e2a746cbe1.png">

After 2 mentors asked to join my team, I ended up with 4 of the "Manage mentor requests". 

<img width="1440" alt="Screen Shot 2020-09-18 at 3 59 23 PM" src="https://user-images.githubusercontent.com/32206421/93644716-205d9200-f9c8-11ea-8f0e-2b29394a74ae.png">

* Accepting a mentor request - worked as expected. _Side notes: It is a little weird that I can no longer see the mentor's profile once they are on my team. Have students always only been able to see the first name of the mentor requesting to join their team? As a parent, I wouldn't feel comfortable with my daughter accepting an invitation from an adult I cannot check up on._
* Declining a mentor request - worked as expected

Logged in as a mentor New Guy - I can see the invite from the team and see team members. **Request** - could we remove age for students who are now mentors? 
<img width="1440" alt="Screen Shot 2020-09-18 at 4 18 45 PM" src="https://user-images.githubusercontent.com/32206421/93645890-b09cd680-f9ca-11ea-915a-5a5116bf09d5.png">


* Accepting the team invitation - works as expected. _Side note: I can't see the profile of my fellow team mentors, which could be challenging if I've never met them before._

Logged in as mentor Sally Salad. When I first logged in, I only see that submissions are closed, I don't see the invite. 
<img width="1440" alt="Screen Shot 2020-09-18 at 4 16 22 PM" src="https://user-images.githubusercontent.com/32206421/93645741-5ac82e80-f9ca-11ea-9bae-79b8b10fa85c.png">

I am able to see the invitation when I click "Find your team", but I have to scroll down to see it as I am already on a team. 

* Declining the team invitation - worked as expected. 


Unfrequent scenario - Logged in as a mentor Tessa on a team (my mentor team) and unless I got to my team and go to mentors, I'd have no idea there is a request. 

![image](https://user-images.githubusercontent.com/32206421/93643839-64e82e00-f9c6-11ea-8181-52279a405a9d.png)

**Comment by stenington** [comment]
It looks like mentors and students-turned-mentors are not considered the same thing, leading to the double buttons.

**Comment by rsgonzal** [comment]
Thanks for all of this! @stenington do we think this is an unrelated bug?
> I searched for a mentor (Sally Salad) already on my team, Jellicle Cats. I noticed that I saw "Ask Sally to mentor your team" button, even though she is already a mentor on my team-- **this seems like a possible error**:
> <img alt="Screen Shot 2020-09-18 at 4 30 17 PM" width="1122" src="https://user-images.githubusercontent.com/57409606/93642538-3f5e2300-f9cc-11ea-98cc-fdcfdc1d49ef.png">
> 
> I then searched for a mentor not on my team, that hasn't been invited or requested to join:
> <img alt="Screen Shot 2020-09-18 at 4 47 10 PM" width="1123" src="https://user-images.githubusercontent.com/57409606/93643753-9a911500-f9ce-11ea-921d-0b88f434fe6c.png">
> 
> I could not view this mentor's profile (there were no buttons on the profile to view it, beyond the "Ask Aline to mentor your team"); **is this an error?**

**Comment by rsgonzal** [comment]
Looks like Gua is on her team too, but same button appears

**Comment by stenington** [comment]
@kate-technovation Wow! Good attention to detail. I think you actually found a bug with #2643, so I've moved that back on the board to fix it. The "Ask Aline to mentor your team" button was mis-labeled, and clicking it from that screen would bring you to a mentor details page that had the actual button to ask them to mentor your team. We're changing the text to "View more details" so it makes sense.

**Comment by stenington** [comment]
@ophelieh thanks for thinking this one through so thoroughly! I'm collecting my thoughts here on how we might proceed on all the feedback. @rsgonzal 

---

> my dashboard was a little trippy - there are 2 buttons saying "Manage mentor invites"
> After 2 mentors asked to join my team, I ended up with 4 of the "Manage mentor requests".

This is an issue with student/mentor combo accounts. We can probably fix this bug in isolation, but we might also want to rethink allowing student/mentor combo accounts on the platform, since they cause so much trouble. Maybe just deleting the student profile when the account gets converted would work? Something we can pursue in another ticket, related to #2354.

---

> Side notes: It is a little weird that I can no longer see the mentor's profile once they are on my team. Have students always only been able to see the first name of the mentor requesting to join their team? As a parent, I wouldn't feel comfortable with my daughter accepting an invitation from an adult I cannot check up on.

This feels like something we should be able to fix, we could create a new ticket.

---

> Request - could we remove age for students who are now mentors?

I assume this is yet another student/mentor combo account bug, but haven't confirmed that. So again, we can handle it individually, and/or we could consider trying to do something that handles all these little bugs at once, like deleting the student profile. #2354 

---

> Side note: I can't see the profile of my fellow team mentors, which could be challenging if I've never met them before.

This feels like something we should be able to fix, we could create a new ticket. I know because we have young kids on the platform we limit what they can see, but if that isn't the problem here, I don't think there's a technical limitation to letting them know more about each other.

---

> Logged in as mentor Sally Salad. When I first logged in, I only see that submissions are closed, I don't see the invite.
I am able to see the invitation when I click "Find your team", but I have to scroll down to see it as I am already on a team.

and

> Unfrequent scenario - Logged in as a mentor Tessa on a team (my mentor team) and unless I got to my team and go to mentors, I'd have no idea there is a request.

This feels to me like something other platforms would deal with by having a notifications system. I think we've just relied on emails going out letting people know they have invites or requests to deal with. I'm not sure if there's a small change (or set of small changes) we could make to improve on this, or if it's getting more into "redesign the dashboard" territory. @rsgonzal I would defer to you on how to handle capturing this feedback in our system.

**Comment by rsgonzal** [comment]
Thanks @stenington ! i'll create tickets for some of these. and update the ticket.
