### ISSUE TITLE
Display student interests

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2644]
Knowing what skills a student can contribute would be helpful for team building.

A skills question can be added to this page:
![Screen Shot 2020-09-04 at 10 46 43 AM](https://user-images.githubusercontent.com/22801026/92628611-f0084c00-f281-11ea-9d07-c3fc36c4bbe7.png)

Q:
- should students be able to checkmark various skills or choose from a dropdown?
- what should breakdown of skills be? (coding, marketing, project management...)

Followup to this ticket would be to show skills for each student when viewing team details and potentially in email when requesting to join a team and when accepting or denying
![Screen Shot 2020-09-09 at 9 42 29 AM](https://user-images.githubusercontent.com/22801026/92629036-8dfc1680-f282-11ea-8b12-365304a701c9.png)

![Screen Shot 2020-09-09 at 9 56 11 AM](https://user-images.githubusercontent.com/22801026/92629151-bf74e200-f282-11ea-941b-aa81e8b56e47.png)

**Comment by hellafitz** [comment]
#2678 covers this in terms of signup. I'm keeping this open for the moment because this ticket includes info on the subsequent display of information. 

Another piece in terms of display is the email that gets sent to a team when a student requests to join.
