### ISSUE TITLE
X Add a question on theme/area of interest when creating a team

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2645]
There are not a lot of details when searching for a team. Students can only view a description. It could be helpful to view what type of app they are building.

Qs:
- Use SDGs or create own list (health, education, environment...)
![Screen Shot 2020-09-04 at 10 54 19 AM](https://user-images.githubusercontent.com/22801026/92629536-4c1fa000-f283-11ea-8cc5-eae5292d9a60.png)

Followup would be to show on page for more details on team and maybe to filter by these when searching for a team

**Comment by hellafitz** [comment]
duplicate
