### ISSUE TITLE
Bug: Can't update email address after converting a student to be a mentor

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#2650]
From #2606, after converting a student to become a mentor, the email address can't be updated.

Steps to reproduce:
As an admin, convert a student to a mentor, then on the same page, try to update their email address via the "Edit participant" button.

From what I'm experiencing, it looks like in order to update the mentor's email address, you need to select a Mentor Type as well.

**Comment by stenington** [comment]
We may want to discuss #2354 in relation to this.

**Comment by rsgonzal** [comment]
#2354 didn't quite fix the bug, notes from Kate F:

> 9. BUG #2650 STILL OCCURS--Tried to edit Mentor Profile email address by clicking on Edit Participant button: 
><img width="808" alt="Screen Shot 2021-02-19 at 4 48 16 PM" src="https://user-images.githubusercontent.com/57409606/108565204-4c13d980-72d2-11eb-88b3-1eacf5253065.png">

>As stated in Ticket #2650, I had to select a Mentor type before I could edit the email address field. I selected the Mentor type "Past Technovation Student". Once I selected a Mentor type, I was able to edit and save my new email address.
<img width="885" alt="Screen Shot 2021-02-19 at 4 47 15 PM" src="https://user-images.githubusercontent.com/57409606/108565352-89786700-72d2-11eb-8d46-4e60d2af94c5.png">

>Also, I noticed that if I tried to edit the email address on the Mentor profile again, _even if I could see the "Former Student" tag on the Mentor's profile_ when I clicked the "Edit participant" button and tried to update the email address again, I had to _re-select_ a Mentor Profile type--it's like the profile type was somehow not being stored.

**Comment by shaun-technovation** [comment]
This long standing issue will finally be addressed in addressed in #4013. 👍 😅
