### ISSUE TITLE
Add help text to chapter ambassador introduction page [5,3,1.67]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2653]
From #2612, we want to add some help text to the chapter ambassador's introduction section.

> Add some help text under "Introduce yourself to your area" to say "This is what participants in your area will see"

https://github.com/Iridescent-CM/technovation-app/issues/2612#issuecomment-690820807

## QA Suggestion

1. Log in as a chapter ambassador 
2. Navigate to "Local program introduction"
3. Confirm help text

**Comment by stenington** [comment]
I used an existing "help" class, so I have it looking like this:
<img width="1120" alt="Screen Shot 2020-09-24 at 4 56 21 PM" src="https://user-images.githubusercontent.com/55319/94199548-fd7b2400-fe86-11ea-9fcc-fe55254f2018.png">

**Comment by stenington** [comment]
The panel that opens under "Meet your chapter ambassador" is where the info the ChA has put in is show to users:
<img width="1280" alt="Screen Shot 2020-09-29 at 2 36 30 PM" src="https://user-images.githubusercontent.com/55319/94601262-3b01f780-0261-11eb-894b-a85ccb52eab8.png">

**Comment by nickiredescent** [comment]
Can confirm that the new help text is visible where stated.

Potentially redundant, but I wonder if it's nice to also see the help text in the edit screen:
![image](https://user-images.githubusercontent.com/45576078/94825025-84b22580-03ba-11eb-973f-d67e1829c93f.png)

**Comment by rsgonzal** [comment]
This looks right for the scope of the ticket. @nickiredescent let me know if you want me to open another ticket to add it there as well.

**Comment by ophelieh** [comment]
I agree with Nick. Would be nice to also see it when they edit their profile. :)

Thank you!
