### ISSUE TITLE
Add users to configured segments on mailing list subscription [20,13,1.5]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2656]
(Rebecca) With the auto Mailchimp list signups by account, would it be harder to add signups to a somewhat different place in Mailchimp - eg one single list but different segments?
- Maggie has specific ideas. Talk to her.
- Can we route people to different segments in one listserv? If not, we still need new lists for 2021

****

I met w/ Maggie today, here are the new requirements:
* Add all accounts to one Mailchimp list (Technovation Girls 2021 Season Participants)
* Add a tag (student, parent, mentor, or judge) to each account, which then can be used as a segment
* Clean up old *_LIST_ID configuration

****

## QA STEPS

* Sign up as a new student, mentor, and judge
* Verify each new account gets added to this list in Mailchimp: "Staging Technovation Girls 2021 Season Participants", and gets tagged appropriately: student gets a student tag, mentor gets a mentor tag, and a judge gets a judge tag
* For parents, sign a parental consent form, and they should end up on the same email list with a parent tag

**Note:** there's a new config setting for the master list: `MAILCHIMP_LIST_ID`, for QA it's set to the list "Staging Technovation Girls 2021 Season Participants", for production, we'll set it to the real one

**Comment by stenington** [comment]
In general, Mailchimp has a very detailed and complete API so the questions are probably:

1. What exactly does the team want?
2. What parts should be configurable? Hard-coded?
3. Does the Mailchimp API support what's wanted? (Probably yes)
3. What will it take to update our code to use the appropriate portion of the Mailchimp API? 

[This](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/technovation/mailchimp.rb) is the API wrapper that would probably need updating.

**Comment by rsgonzal** [comment]
@mjaris you were identified as having specific ideas, wondering if you have more info for the first 2 Qs?

**Comment by mjaris** [comment]
Hi @rsgonzal, Rebecca and I talked about having people be automatically routed into segments of one master 2021 list in mailchimp, instead of being added to separate lists.

**2021 Technovation Girls Season Participants**

- Students (segment that's automatically populated during registration process)
- Mentors (segment that's automatically populated during registration process)
- Parents (segment that's automatically populated during registration process)
- Judges (segment that's automatically populated during registration process)
- Ambassadors (segment that's manually updated/maintained by program team, beyond scope of this ticket)

**Comment by stenington** [comment]
No spike needed here, I don't think. We can look for `*_SEGMENT_ID` configuration alongside the list ID config, and issue a second API call to add members to segments inside our `Mailchimp::MailingList` class.

**Comment by rsgonzal** [comment]
from maggie:

> Okay created, the title is Technovation Girls 2021 Season Participants; I couldn't create segments because there are no subscribers, if that's a problem we can always create dummy data to build the segments and remove later.

She also shared marketing vault on one pass with shaun for login

**Comment by shaunxp20** [comment]
Met/chatted with Maggie today. We decided to use tags which then can be used as segments. I added the details to the description of the issue. 👍 😃

**Comment by shaunxp20** [comment]
This one is on QA now, some QA steps have been added too. 👍 😄 🌞

**Comment by rsgonzal** [comment]
This looks to be ready for me. Will wait for @mjaris to confirm.

**Comment by mjaris** [comment]
Yes, mailchimp finally let me in -- looks good to me!

**Comment by shaunxp20** [comment]
> This looks to be ready for me. Will wait for @mjaris to confirm.

> Yes, mailchimp finally let me in -- looks good to me!

Great, thank you both for checking this!! 🙌 🙇 👍 😀

**Comment by shaunxp20** [comment]
I added #2728 to add some tests to the Mailchimp code (since there currently aren't any), and some other things I didn't have time for. ✉️ 🐵 😄
