### ISSUE TITLE
Bug: Student sends request to join a team but it doesn't stick

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2662]
**Describe the bug**
Student requesting to join a team is told they sent the request, but when they go to "find your team", there is no request there. 

**To Reproduce**
1. Go to participants
2. search for students, name: north dakota
3. Login as student
4. Go to "find your team" --> find team
5. Try to join "newteam"
6. go back to "find your team"
7. See the request isn't sent

**Expected behavior**
The "find your team" should list "new team" under ask to join team section

**Screenshots**
![Screen Shot 2020-09-16 at 6 14 04 PM](https://user-images.githubusercontent.com/22801026/93408646-ecf4f900-f849-11ea-8740-3e06bec0b811.png)

![Screen Shot 2020-09-16 at 6 25 07 PM](https://user-images.githubusercontent.com/22801026/93408724-20378800-f84a-11ea-8f68-d4024f9ed748.png)

**Additional context**
It's possible they've denied my request already or I removed myself from the team previously. Probably just a staging issues, but since we know these requests stall out (#2607) might be worth checking out
This page tells me when others have denied my request, but no info for "newteam"
![Screen Shot 2020-09-16 at 6 29 21 PM](https://user-images.githubusercontent.com/22801026/93408918-92a86800-f84a-11ea-9b39-3e72206158ca.png)

**Comment by rsgonzal** [comment]
@shaunxp20 this might be one you can explore

**Comment by shaunxp20** [comment]
> Additional context
> It's possible they've denied my request already or I removed myself from the team previously.

In the admin I see that the "North Dakota" join request was deleted.

<img width="1067" alt="Screen Shot 2020-09-16 at 10 43 09 PM" src="https://user-images.githubusercontent.com/58957909/93421565-37ee2b00-f8a1-11ea-83fe-71a19545f984.png">

Locally, I hard-deleted this request and I was able to successfully make another join request. I can do this on QA too, if you want. 😄 

It seems as if a student can only have one join request per team, even if it has been deleted. 😕 😞 🤕 

We can definitely address this, we could talk about it with the dev team and/or program team to come up with a solution. Some potential solutions: 
* display an error message (instead of misleading a student into thinking another join request has been made)
* send another join request
* don't allow students to request to join teams where the join request has been deleted
* something else

**Comment by rsgonzal** [comment]
If a request gets deleted, maybe it should not count towards that one request.

Need to investigate:
- Why and how do requests get deleted.

**Comment by shaunxp20** [comment]
> Need to investigate:
> * Why and how do requests get deleted.

> It's possible they've denied my request already or I removed myself from the team previously.

Looks like that's what happens, **when a student is removed from a team, the join request gets deleted**.

https://github.com/Iridescent-CM/technovation-app/blob/dcfa9ef15fd8276725c6dd2e1bcf024c508372e9/app/technovation/team_roster_managing.rb#L106-L108

**Comment by stenington** [comment]
The steps to reproduce are probably no longer accurate. #2708 should have changed how this scenario works, so try out the steps again and see if it feels better or not @rsgonzal

**Comment by rsgonzal** [comment]
So, I'm not sure if this is related here. But i tried to reproduce. 

- I was able to send a request to newteam
- I decided to accept the request as someone on the team
- North Dakota got confirmation she was accepted
- when i go to team page, she's not listed as a member
- when i log in, i'm not on the team

![screencapture-technovation-qa-herokuapp-admin-teams-228-2020-10-22-12_59_00 (1)](https://user-images.githubusercontent.com/22801026/96923912-cb99b500-1466-11eb-8fef-c09494512519.png)
![Screenshot_20201022-125919](https://user-images.githubusercontent.com/22801026/96924013-e79d5680-1466-11eb-81d9-2e00d6b4e910.png)

**Comment by stenington** [comment]
@rsgonzal I walked through requesting to join newteam with the same result. It looks like students are able to request to join teams that already have 5 members/invites/requests pending, and those teams are able to accept the request, but then the acceptance isn't actually honored. I opened #2769 to describe it more specifically.

**Comment by rsgonzal** [comment]
Closing this one since the original description is no longer a bug
