### ISSUE TITLE
Bug: Checkmark to allow others to find team does not work when unchecked

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2663]
**Describe the bug**
I unchecked the box " ALLOW OTHER STUDENTS TO FIND OUR TEAM AND REQUEST TO JOIN US" on my team profile, using student Anna Walker, and I am still searchable by other students on the main search page

**To Reproduce**
1. Sign in as any student not on a team
2. Click on 'find your team'
3. Search for teams anywhere
4. See 'test' is listed and join

**Expected behavior**
Team 'test' should not be visible by other students

**Screenshots**
![Screen Shot 2020-09-16 at 5 37 52 PM](https://user-images.githubusercontent.com/22801026/93409225-3a259a80-f84b-11ea-9829-93f8a61a5b5e.png)
![Screen Shot 2020-09-16 at 5 36 40 PM](https://user-images.githubusercontent.com/22801026/93409227-3b56c780-f84b-11ea-97ad-fa8f6939cc0b.png)

**Additional context**
We've been discussing with program team that they can communicate this option to teams that already know their team members. Plan was to suggest that they uncheck this box and invite the other students by email so that they don't get unwanted requests

Want this to work for #2664

## Recommended QA

Follow the steps to reproduce above, and see that teams who do not want to show up in search results do not show up. Also ensure that teams who have checked the box **do** show up.

**Comment by stenington** [comment]
I pulled this one into the iteration. I have a PR up with a test and a fix. Good catch on this bug!

**Comment by stenington** [comment]
This is headed to staging. For QA I recommend following the steps to reproduce and seeing that the bug no longer occurs.

**Comment by kate-technovation** [comment]
1. I signed into QA as a student not on a team, and all was as expected:

<img width="912" alt="Screen Shot 2020-09-21 at 2 58 13 PM" src="https://user-images.githubusercontent.com/57409606/93809107-e0dab400-fc1a-11ea-92e4-626ded0f62aa.png">

2. I clicked on the Find your team button and saw the main dashboard screen (which is fine, but I thought it would jump directly to the team search page):

<img width="911" alt="Screen Shot 2020-09-21 at 2 58 57 PM" src="https://user-images.githubusercontent.com/57409606/93809183-fc45bf00-fc1a-11ea-847d-6ad1a22507a4.png">

I clicked on the Find your team button:
<img width="914" alt="Screen Shot 2020-09-21 at 2 59 22 PM" src="https://user-images.githubusercontent.com/57409606/93809221-0a93db00-fc1b-11ea-86b9-d7efbb0a7e58.png">

3. And I saw this screen team search screen:
<img width="913" alt="Screen Shot 2020-09-21 at 3 01 17 PM" src="https://user-images.githubusercontent.com/57409606/93809463-4e86e000-fc1b-11ea-8f37-51d2bb4a6bf4.png">

I clicked the Anywhere button and saw teams from all over:
<img width="913" alt="Screen Shot 2020-09-21 at 3 01 48 PM" src="https://user-images.githubusercontent.com/57409606/93809528-6199b000-fc1b-11ea-99d9-947900eefc21.png">

4. I **don't** see a team called test (tried to take a screenshot of all the teams I _do_ see, but the screen wouldn't resize to fit everything).

**Comment by rsgonzal** [comment]
tested this by making a once searchable team, not searchable. all is working as expected!

There are also plenty of teams searchable, so the checkmark is working
