### ISSUE TITLE
Make 'No' default option for allowing team to be visible by others [13,5,2.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2664]
Students might not realize that their team is visible by other students or mentors that they don't know. 

Issue:
Teams who received requests to join from girls they didn't know or didn't want sometimes had trouble accepting invites from girls that they did want, because of the unwanted invites "jamming up" their request channel (not sure exactly what the issue was, but we got these tickets occasionally).

Solution:
- Make the default option to not have 'ALLOW OTHER STUDENTS TO FIND OUR TEAM AND REQUEST TO JOIN US' checkmarked
- Make the default option to not have 'ALLOW OTHER MENTORS TO FIND OUR TEAM AND REQUEST TO JOIN US' checkmarked

![Screen Shot 2020-09-16 at 6 40 50 PM](https://user-images.githubusercontent.com/22801026/93409660-37777500-f84c-11ea-80ea-a071fb39a795.png)
![Screen Shot 2020-09-16 at 6 41 28 PM](https://user-images.githubusercontent.com/22801026/93409677-4100dd00-f84c-11ea-8c42-f5d8a0ffdb76.png)

@kate-technovation i think you wanted different language or help text on these options?

**Comment by stenington** [comment]
These checkboxes map back to `accepting_student_requests` and `accepting_mentor_requests` on the team model, which both default to true currently. So I think the bulk of the effort here is writing a migration that switches the default to false. If there are text changes as well, that wouldn't add much effort.

**Comment by hellafitz** [comment]
I'm having second thoughts on this one. In the current environment, it seems like teams getting too many requests to join will be less of an issue than students not seeing enough teams to join. 

At the minimum I don't think we should proceed with this switch until we've implemented our (currently mockup-state) efforts to make the settings more prominent and understandable.
