### ISSUE TITLE
Add help text or video on mentor section of team building [8,x,x]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2665]
Students are confused on how to add mentors or don't realize they are searchable

Suggestion:
- tell students if they are searchable or not by mentors on the mentor section of dashboard
- add video on how to choose a mentor on one or both of these pages"
![Screen Shot 2020-09-16 at 6 44 31 PM](https://user-images.githubusercontent.com/22801026/93410135-4579c580-f84d-11ea-840e-06bfe79db3b8.png)
![Screen Shot 2020-09-16 at 6 44 15 PM](https://user-images.githubusercontent.com/22801026/93410138-47438900-f84d-11ea-9df0-d31d0434a414.png)

to be worked out by @ophelieh @kate-technovation & maybe @mdancho ?
https://app.mural.co/t/roxwork8740/m/roxwork8740/1600302534248/acf87b8e8f74ea82a9d271c729142b482f8064e9

**Comment by rsgonzal** [comment]
Video/resources portion can be a future ticket

**Comment by stenington** [comment]
So is this ticket now just "tell students if they are searchable or not by mentors on the mentor section of dashboard" on that first page screenshot? It looks like that "Add a mentor to your team" section can show 3 different things depending on whether you have any invites or join requests, whether you have any mentors yet, or you have no invites, no requests, and no mentors. A good next step here might be to whiteboard out those details and show what the proposed changes would look like.

**Comment by stenington** [comment]
This invision board shows the 3 scenarios: https://projects.invisionapp.com/freehand/document/oszw8PxUy

**Comment by hellafitz** [comment]
For discussion, I added a rough draft of what could appear on those screens. Look for the orange circle on the first scenario.

**Comment by hellafitz** [comment]
Next step: confirm direction w/ TF/TG

**Comment by hellafitz** [comment]
Direction confirmed with TF/TG (see below). Next steps: mocks v2

![Screen Shot 2020-10-30 at 9 33 27 AM](https://user-images.githubusercontent.com/6475595/97731967-0cab4e00-1a93-11eb-8fb0-4558da3aa826.png)

**Comment by hellafitz** [comment]
@rsgonzal what do you think of this one? still useful?

**Comment by rsgonzal** [comment]
Closing this one! Video portion is not important nor on the horizon i don't think.

We already worked on this page with #2784 

![Screen Shot 2021-02-18 at 4 44 13 PM](https://user-images.githubusercontent.com/22801026/108440834-bceebf00-7208-11eb-93ea-cade812326cd.png)
