### ISSUE TITLE
X Add message on how many requests can be sent on their team profiles [5?,x,x]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2666]
As a student, I want to be able to see how many requests i can receive/send out so that I don't have to email zendesk and ask why i can't send anymore requests

On the admin side, I can see this message:
![Screen Shot 2020-09-16 at 6 52 17 PM](https://user-images.githubusercontent.com/22801026/93410385-c5079480-f84d-11ea-98cc-fea4d03910e5.png)
![Screen Shot 2020-09-16 at 6 52 13 PM](https://user-images.githubusercontent.com/22801026/93410394-c8028500-f84d-11ea-91e2-414492cdd7c6.png)

But i don't see this on the student side
![Screen Shot 2020-09-16 at 6 53 56 PM](https://user-images.githubusercontent.com/22801026/93410542-00a25e80-f84e-11ea-87cc-c715a832168c.png)

@kate-technovation @ophelieh if you can check this one too :)

**Comment by stenington** [comment]
@rsgonzal Can you make a quick example of exactly what you want? 

In the code, it looks like this template handles several scenarios:
* what to show if you're not an admin or chapter ambassador, the team is current, and the team has a spot available
* what to show if the team is not current
* what to show in any other scenario

We might need to understand better how those different scenarios get triggered, and what you want this page to look like in each case.

**Comment by rsgonzal** [comment]
- Pretty sure you can see the invitation box as an admin - need to investigate

**Comment by stenington** [comment]
@rsgonzal Yeah, you're probably right. It looks like it's not a flag that says whether you're an admin or chapter ambassador logged in as a user, it's an explicit toggle that needs to be passed in by a parent template. So because you were in the student dashboard, it would be false.

**Comment by stenington** [comment]
It looks like the admin dashboard (and I assume the chapter ambassador dashboard) reuse some of the same templates that get used to render a team for a student, so the `admin_chapter_ambassador` flag would be used to hide the invitation controls in that context.

**Comment by stenington** [comment]
Actually, now I'm confused about the two screenshots you initially took. Can you retake them, making sure to include the whole window, including url? In general it's really useful to see urls on a screenshot to help clarify where you were when you took it.

**Comment by hellafitz** [comment]
@rsgonzal bumping up the request for screenshots

**Comment by hellafitz** [comment]
@rsgonzal bumping this up

**Comment by rsgonzal** [comment]
team forming open
![Screen Shot 2020-10-21 at 9 02 05 AM](https://user-images.githubusercontent.com/22801026/96747798-96656800-137d-11eb-81e9-92aabe97eb30.png)

team forming closed
![Screen Shot 2020-10-21 at 9 03 37 AM](https://user-images.githubusercontent.com/22801026/96747826-9feed000-137d-11eb-9fec-81e96cf8fc2d.png)

judging open (slight message change under invite sent)
![Screen Shot 2020-10-21 at 9 04 21 AM](https://user-images.githubusercontent.com/22801026/96747865-ada45580-137d-11eb-86f9-f1d647500ca1.png)


#2697 adds the message under the first section, which is the team's name. I think that's a good route to take but may want to shorten the message. We could use this ticket for that piece.

**Comment by hellafitz** [comment]
Closing since this will be covered by #2697
