### ISSUE TITLE
Replace 'name' with 'team name' on team creation screen [5,2,2.5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2669]
![Screen Shot 2020-09-11 at 11 09 24 AM](https://user-images.githubusercontent.com/22801026/93516513-fed4ab80-f8de-11ea-8309-ccb4d7ac551b.png)

Replace 'Name' ---> with 'Team Name'

## Suggested QA
1. sign up/in as student not on a team
2. create your team
3. confirm new field label

**Comment by stenington** [comment]
PR #2686 open for this.

**Comment by rsgonzal** [comment]
Looks good!
