### ISSUE TITLE
Epic: Edit mentor sign up screen [13?,x,x]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2670]
When talking about improving sign up and profile fields, we discussed we may want to make changes to the skills we ask mentors for. Opening this one up for that and any other changes we may want to do

![Screen Shot 2020-09-17 at 12 26 17 PM](https://user-images.githubusercontent.com/22801026/93518325-802d3d80-f8e1-11ea-914c-a4fb40bab70a.png)
![Screen Shot 2020-09-17 at 12 26 25 PM](https://user-images.githubusercontent.com/22801026/93518360-8f13f000-f8e1-11ea-9077-aaf9679a3734.png)
![Screen Shot 2020-09-17 at 12 28 08 PM](https://user-images.githubusercontent.com/22801026/93518392-9804c180-f8e1-11ea-85ff-9e651bc80834.png)
![Screen Shot 2020-09-17 at 12 27 58 PM](https://user-images.githubusercontent.com/22801026/93518395-989d5800-f8e1-11ea-8435-707161989947.png)

@mdancho @Bryant-Gomer here is what it currently looks like.

**Comment by bagomer** [comment]
@hellafitz @rsgonzal 
Mentor Skills and Interests:
Coding
Experience with Java
Experience with Swift
Project Management 
Business or entrepreneurship
Marketing
Design

**Comment by stenington** [comment]
I relabeled this as an epic, since the description states (emphasis mine):

> Opening this one up for that and **any other changes we may want to do**

We can't put an effort estimate on a ticket designed to collect ideas and grow in scope.

**Comment by hellafitz** [comment]
@bagomer looking at this in context again, thinking as a Mentor, I feel like I'd be putting forward a very limited view of my "interests" if those are the only options. They're all professional. Nothing about personal interests or issues that animate me to volunteer. Maybe this could be alleviated by adding text that references their bio? (e.g. adding "You'll have a chance to share more about yourself with Technovation participants when you create your Mentor Bio later on" below the response options)

**Comment by bagomer** [comment]
I really like moving the Personal Summary portion here so that after checking the skills and interests in flows right into "Talk all you want about your awesome self"

**Comment by hellafitz** [comment]
Moving up the Mentor's Personal Summary is #2729
