### ISSUE TITLE
Combine Screens on team dashboard [8,?,?]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2673]
Students have a lot of dashboards they're looking at. When they view their team, they're presented with a section with many tabs, there is not a lot of information in these tabs.
![Screen Shot 2020-09-18 at 8 27 17 AM](https://user-images.githubusercontent.com/22801026/93616371-82e36d80-f989-11ea-939d-48ef0eaefcd7.png)

Proposal: Combine the summary, location, and Division tabs

![Screen Shot 2020-09-18 at 8 32 19 AM](https://user-images.githubusercontent.com/22801026/93616375-8545c780-f989-11ea-9527-07af438997ce.png)

**Comment by rsgonzal** [comment]
Confirm that changing this will not affect how team search results are displayed.

**Comment by stenington** [comment]
The template behind the "My Team" page students can see also powers how admins and chapter ambassadors see teams in the admin. I assume it would be fine for this change to happen in both places though.

By "how team search results are displayed" I assume you mean these two views?

![Screen Shot 2020-10-05 at 4 55 45 PM](https://user-images.githubusercontent.com/55319/95131274-c67cfc00-072b-11eb-8596-c205b744e252.png)
![Screen Shot 2020-10-05 at 4 55 41 PM](https://user-images.githubusercontent.com/55319/95131281-c7159280-072b-11eb-8014-9d707abd8126.png)

I don't believe either would be affected by changing the student/mentor view of their teams. (We could certainly stipulate in the ticket requirements that these screens don't change and QA for that as well.)
