### ISSUE TITLE
Update message on error screen when you try to invite an email that is associated with non- student account [5,3,1.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2674]
> As a student, I want to invite my friend who hasn't sign up to TG yet to join my team, so that she will get a notification and sign up faster.
> 
> Currently, girls can only invite other girls that are already on TG. 
> 
> Proposal:
> If students enter an email that does not have an account yet, we send out an invitation to the platform for that email

Original description not an issue, but error message is not clear and confusing

## Suggested QA
1. sign in as a student on a team
2. invite a non-student user (e.g. admin@admin.com)
3. confirm error message text

**Comment by rsgonzal** [comment]
> Bonus: could add a custom link for invites (either individually or team-specific) so it could be dropped in chat or otherwise avoid email

**Comment by stenington** [comment]
You can. It lists them as "unregistered" when you do.

<img width="1280" alt="Screen Shot 2020-09-18 at 11 44 27 AM" src="https://user-images.githubusercontent.com/55319/93617753-61dc4600-f9a4-11ea-94af-36da3bff07bc.png">

They get an email like this:

![Screen Shot 2020-09-18 at 11 45 12 AM](https://user-images.githubusercontent.com/55319/93617803-728cbc00-f9a4-11ea-8ff4-ea43ac539722.png)

**Comment by rsgonzal** [comment]
OH! I see what I did, i invited someone who is not a student, meaning they have a different profile. I was confused by the wording.

![Screen Shot 2020-09-18 at 8 48 11 AM](https://user-images.githubusercontent.com/22801026/93618230-d6ef5180-f98b-11ea-96c8-00d4249eed11.png)

**Comment by stenington** [comment]
Oh, yeah that message isn't very helpful.

**Comment by rsgonzal** [comment]
Proposal: Update message from "is not a student." to ---> "This email is associated with an account that is not a student."

**Comment by stenington** [comment]
I believe the implementation here is updating `is_not_a_student` with the desired copy in our activerecord locale files.

**Comment by stenington** [comment]
Also, a note on the `.es-MX` locale files: it looks like we have some hidden functionality around a locale switcher in the app. Both en and es-MX are configured as available locales, and we store a locale on the account model. But in production, the only stored value is en, so nobody would be seeing any of the spanish translations we have in those locale files.

**Comment by hellafitz** [comment]
Deliverable: update the error message to "! This email is associated with a non-student account."

**Comment by stenington** [comment]
<img width="1280" alt="Screen Shot 2020-09-30 at 10 28 58 AM" src="https://user-images.githubusercontent.com/55319/94698810-aa322700-0307-11eb-8b2a-b2bfe66509c6.png">

**Comment by rsgonzal** [comment]
Looks great!

**Comment by kate-technovation** [comment]
1. Signed in as a student on a team:
<img width="979" alt="Screen Shot 2020-10-02 at 6 28 08 PM" src="https://user-images.githubusercontent.com/57409606/94974611-1619b880-04dd-11eb-921f-2049e0b18ff2.png">

2. Invited a non-student user (e.g. admin@admin.com):
<img width="970" alt="Screen Shot 2020-10-02 at 6 29 58 PM" src="https://user-images.githubusercontent.com/57409606/94974682-48c3b100-04dd-11eb-98b2-840069f2ca96.png">

2. Confirmed error message:
<img width="997" alt="Screen Shot 2020-10-02 at 6 30 17 PM" src="https://user-images.githubusercontent.com/57409606/94974693-52e5af80-04dd-11eb-98c0-c2254a7d14d7.png">
