### ISSUE TITLE
Change gender identity filtering on mentor search [20,8,2.5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2675]
We currently have an option to filter by gender identity when looking for a mentor. We only allow male or female, but we actually provide 4 options at sign up.
![Screen Shot 2020-09-18 at 8 41 27 AM](https://user-images.githubusercontent.com/22801026/93617388-c38fb680-f98a-11ea-861d-94ae0c0c3d65.png)
![Screen Shot 2020-09-17 at 12 27 58 PM](https://user-images.githubusercontent.com/22801026/93617413-ca1e2e00-f98a-11ea-81f0-2d4115c71c6a.png)

Q: What happens to people that show non-binary or prefer not to say???? Do they even show up in the search??

## Clarification of scope
1. the **Gender identity** filter on mentor search becomes a set of radio buttons, so that you must pick one, and you may only pick one at a time
2. the radio button options are **Female** or **No preference**
3. I assume **No preference** is the default selection?
4. selecting **Female** filters to female mentors in the results, and
5. selecting **No preference** does not filter the results based on gender identity

## Suggested QA

1. Identify at least one onboarded mentor for each gender identity option on signup.
2. As a student, search for mentors
3. Select "Anywhere" for location and "No preference" for gender identity
4. Confirm that you see all of the mentors you identified above
5. Select "Female only" for gender identity
6. Confirm that you no longer see the 3 mentors identified above that hadn't selected "Female"
7. Repeat as a mentor searching for other mentors, for completeness

**Comment by rsgonzal** [comment]
- how to the combinations of checkmarks work
- how do we want to display the new options
- should they be auto checked?
- are these the identities we want to go with?

**Comment by stenington** [comment]
Tested locally and it looks like this is how it work. The first column is the boxes you have checked, the next 4 columns are whether or not mentors with those settings are included:

| Boxes checked | Female | Male | Non-binary | Prefer not to say |
| -- | -- | -- | -- | -- |
| Female & Male | Y | Y | Y | Y |
| Female | Y | N | N | N |
| Male | N | Y | N | N |
| None | Y | Y | Y | Y |

**Comment by hellafitz** [comment]
Amy: most important from search pov, girls are able to find female-identifying mentors

**Comment by hellafitz** [comment]
@Bryant-Gomer this is the ticket for how search options will show up

**Comment by bagomer** [comment]
@hellafitz @rsgonzal Just discussed with Rebecca. From a mentor sign/up profile pov, we are comfortable with the current 4 options: Female, male, non-binary, prefer not to say

For students searching for mentors (and also mentors searching for mentors as a result), we are comfortable with listing two options: 
- Female
- No preference

**Comment by stenington** [comment]
So it sounds to me like the changes here are:

1. the **Gender identity** filter on mentor search becomes a set of radio buttons, so that you must pick one, and you may only pick one at a time
2. the radio button options are **Female** or **No preference**
3. I assume **No preference** is the default selection?
4. selecting **Female** filters to female mentors in the results, and
5. selecting **No preference** does not filter the results based on gender identity

**Comment by hellafitz** [comment]
Confirming the interpretation above.

**Comment by stenington** [comment]
Draft PR is open as #2713

**Comment by kate-technovation** [comment]
1. Identified at least one onboarded mentor for each gender identity option on signup:
-J Mku (non-binary)
-Mal Ware (prefer not to say)
-New Guy (male)

2. As a student, searched for mentors by selecting "Anywhere" for location and "No preference" for gender identity:
<img width="1244" alt="Screen Shot 2020-10-05 at 5 24 27 PM" src="https://user-images.githubusercontent.com/57409606/95133642-a0595b00-072f-11eb-829e-f273c766a75c.png">

3. Confirmed that I see all of the mentors I identified above:
New Guy (male):
<img width="1246" alt="Screen Shot 2020-10-05 at 5 26 34 PM" src="https://user-images.githubusercontent.com/57409606/95133869-f62e0300-072f-11eb-86b3-7eedd2ad4c91.png">

Mal Ware (prefer not to say):
<img width="1242" alt="Screen Shot 2020-10-05 at 5 24 56 PM" src="https://user-images.githubusercontent.com/57409606/95133772-d1d22680-072f-11eb-80e7-70c2ae340d22.png">

J Mku (non-binary):
<img width="1251" alt="Screen Shot 2020-10-05 at 5 25 14 PM" src="https://user-images.githubusercontent.com/57409606/95133775-d3035380-072f-11eb-9ec7-bf7d48bf0161.png">

4. Selected "Female only" for gender identity and confirmed that I no longer see the 3 mentors identified above that hadn't selected "Female":
<img width="1244" alt="Screen Shot 2020-10-05 at 5 27 57 PM" src="https://user-images.githubusercontent.com/57409606/95133981-1eb5fd00-0730-11eb-9114-fc145eab06c8.png">

6. I could not search as a mentor in two different mentor profiles--see message below regarding team search being turned off:
<img width="1248" alt="Screen Shot 2020-10-05 at 5 30 01 PM" src="https://user-images.githubusercontent.com/57409606/95134184-69377980-0730-11eb-88d7-4317f240fa4d.png">

<img width="1256" alt="Screen Shot 2020-10-05 at 5 31 47 PM" src="https://user-images.githubusercontent.com/57409606/95134355-bfa4b800-0730-11eb-9067-b731393940c4.png">

**Comment by rsgonzal** [comment]
Checked as a student and mentor and all looks good

**Comment by mdancho** [comment]
Confirmed that as a student looking for a mentor I can filter by female and no preference. When I filter for female, I only see female mentors. When I click no preference I see non-binary, female and male mentors.
