### ISSUE TITLE
Collect interests, SGDs and coding tools during Student signup

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2678]
Should we collect the same skills & interests that we do for mentors? List potentially edited in #2670 
Old screen:
![Screen Shot 2020-09-04 at 10 46 43 AM](https://user-images.githubusercontent.com/22801026/93636326-95b96a80-f9a8-11ea-9703-d0ad1745a483.png)

New screen:
![Screen Shot 2020-09-18 at 12 18 18 PM](https://user-images.githubusercontent.com/22801026/93636607-137d7600-f9a9-11ea-90fc-4e021a3defaa.png)

This could be displayed when sending requests to join teams #2679

**Comment by hellafitz** [comment]
Consensus is: self-reported skills aren't relevant to 10yr-olds; but not opposed to some sort of interests question here (to inform student-to-student team-building). 

@Bryant-Gomer to begin discussion with Rebecca on Monday.

**Comment by bagomer** [comment]
Per discussion with PT + CET:
Returning or new student
What languages do you speak
Interests:
-Business/entrepreneurship
-Coding
-Marketing or Design
Experience with: App Inventor, Thunkable, Java, Swift?
Are you interested in a special area? (put SDG areas here too if possible)
Checkbox to say looking for a team or working solo or know own team
Checkbox in registration to say looking for a mentor 
Way to change/edit options once profile is initially completed-  change interests down the line 
What can kids search by in terms of location (if looking for somebody local or from somewhere international)?

**Comment by hellafitz** [comment]
@bagomer re: languages, do we have a list of options (ideally already in use elsewhere)? I'd like to avoid collecting unstructured text since it'll make it hard to query later on

**Comment by bagomer** [comment]
@ophelieh @ksrebecca Thoughts on Matt's request for a list of language options (ideally in use elsewhere?)

**Comment by ksrebecca** [comment]
THAT is a great question. I feel like @ophelieh or @rsgonzal might be familiar with something perhaps? We have top languages selected that we get survey translations in for TG but it is not representative of all the languages people speak or even the majority languages per country... 
Arabic
Chinese
French
Hebrew
Hindi
Portuguese
Russian
Spanish

**Comment by ophelieh** [comment]
@hellafitz I don't think we have that language anywhere else as this would be new for students, but let me check.

**Comment by hellafitz** [comment]
I've started a mockup of these options in the Profile Field TG Invision board, where it says New Student Signup (currently in the 2nd column from left, toward the bottom)

**Comment by ophelieh** [comment]
Hi Matt! It looks great. :) 

I'm wondering how would those benefit students though as you can't search for individual students, just individual mentors.  So basically, each student would fill it out, but only admins would see it. It wouldn't help teams or students. Is that our goal? 

If not, at is our goal? Depending on that, we would need to move this to the team page, especially the SGDs, because you can only look up for teams. And what an individual student puts might not reflect what the team chooses. 

@ksrebecca You can find the options here - https://projects.invisionapp.com/freehand/document/1hk5y3kgu

**Comment by ksrebecca** [comment]
@ophelieh the process that the dev team planned to follow was this (@hellafitz correct me if i'm wrong!):

1. Build systems for students to actually give us this info
2. Find ways for chosen sections (whatever is ok) to be searchable by other students and mentors
3. Figure out what would or would not show up on the team page under the student list. For example, the team can select an SDG. Students can also select them (framed as "I'm thinking about solving a problem around xyz") - but that is more initial, when they form a team that is more official. So on the team page we wouldn't want to display ALL of the individual student profile items.... but maybe more than just name and whatever else displays (age?)

That's what I understand at least from the process... ;)

**Comment by ksrebecca** [comment]
@hellafitz [here](https://docs.google.com/presentation/d/17wSjwBs1mOd-wI7AJLbeAcrTJWZeCEn5j8Stm4-Lts0/edit#slide=id.g82489b00a1_0_207) are the 5 areas we had for SDGs in Idea Lab... 
<img width="597" alt="Screen Shot 2020-09-29 at 3 07 01 PM" src="https://user-images.githubusercontent.com/43972336/94615819-9cc46080-0265-11eb-9318-dbf75f0abf86.png">

**Comment by hellafitz** [comment]
@ksrebecca thanks! this looks much more manageable. 
@ophelieh Rebecca has generally described how we're approaching this. There are some more nuances around invitations as well. Student interests are useful for building teams of students who don't know one another. Team interests are useful for matching teams and mentors. We need to do both in order for virtual team-building to be effective.

**Comment by hellafitz** [comment]
decision w/ Rebecca: leave language out for now

**Comment by hellafitz** [comment]
opened #2719 to update the response options for 'how did you hear about technovation'

**Comment by hellafitz** [comment]
Latest deliverable description: 
add Skills & interests and Topic sections below SCHOOL NAME

I'm interested in:
[  ] Business/entrepreneurship
[  ] Coding
[  ] Marketing
[  ] Design
[  ] Other [open response if possible]

I'm interested in solving a problem related to:  
[SDG buttons]
Other
I'm not sure yet / undecided

Don't worry, you can change this later and it won't limit what you end up doing in any way :)

**Comment by hellafitz** [comment]
@stenington @shaunxp20 flagging this one for technical refinement

**Comment by hellafitz** [comment]
@stenington @shaunxp20 bumping this up.
