### ISSUE TITLE
Add descriptions to new exact search fields on Dash [8,2,4]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2683]
Add the following parentheses to the title for each of the 4 new exact search fields e.g. "FIRST NAME (EXACT SPELLING)"

## Suggested QA

As admin, look at the participants search page and confirm the new fields have the "(EXACT SPELLING)" addition to the field labels.

**Comment by stenington** [comment]
PR #2684 is open for this

**Comment by nickiredescent** [comment]
Can confirm that the new "Exact Spelling" fields are visible as an admin. Screenshot of what I see:
![image](https://user-images.githubusercontent.com/45576078/94823972-53852580-03b9-11eb-8db9-465b73a48068.png)

Ran through a few searches and nothing out of place jumped out to me.

**Comment by rsgonzal** [comment]
Looks good to me as well!

**Comment by kate-technovation** [comment]
So sorry I am testing this very late. Looks great!
<img width="630" alt="Screen Shot 2020-10-02 at 6 16 45 PM" src="https://user-images.githubusercontent.com/57409606/94974069-6f80e800-04db-11eb-84fb-c43149d16e85.png">
