### ISSUE TITLE
Update 'More Info' tab for mentors [8,3,2.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2688]
Want to add a link to resources on the more info dropdown for mentors

![Screen Shot 2020-09-23 at 9 36 42 AM](https://user-images.githubusercontent.com/22801026/94042475-7b083c80-fd80-11ea-8de8-f1af51250bbe.png)

After curriculum add:

Mentor Resources
Learn more about mentoring (link: https://technovationchallenge.org/mentor-resources/)

## QA suggestion

1. log in as a mentor
2. see the new link in the menu
3. confirm where it takes you

**Comment by nickiredescent** [comment]
Can confirm that there is a new option in the dropdown for mentors that leads to [](https://technovationchallenge.org/mentor-resources/)

**Comment by rsgonzal** [comment]
Take me to the right place!

**Comment by mdancho** [comment]
Confirmed this takes me to the right page.
