### ISSUE TITLE
Edit screen that tells students they are too young to participate [8,3,2.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2690]
We still want girls to explore the curriculum.

![Screen Shot 2020-09-23 at 9 49 15 AM](https://user-images.githubusercontent.com/22801026/94043664-13eb8780-fd82-11ea-816e-8ac729b4315f.png)

add text that reads - Although you cannot take part in our competition, you can use our [curriculum](https://technovationchallenge.org/curriculum-intro/registered/new/) to work on a project on your own. (link - https://technovationchallenge.org/curriculum-intro/registered/new/)

## QA Suggestion

1. Sign up as a student too young to participate
2. Confirm message

**Comment by stenington** [comment]
@rsgonzal Can you fix the desired text above? Is it "use our curriculum to work on a project"?

**Comment by rsgonzal** [comment]
Can open on same tab

**Comment by stenington** [comment]
<img width="1280" alt="Screen Shot 2020-09-30 at 10 23 27 AM" src="https://user-images.githubusercontent.com/55319/94698104-f92b8c80-0306-11eb-8ba1-9018c0d018c0.png">

**Comment by rsgonzal** [comment]
looks good to me! will have someone from PT check it out

**Comment by ksrebecca** [comment]
looks like the correct message to me but still says World Pitch instead of World Summit, FYI!

**Comment by mdancho** [comment]
I was only able to say I was born 2011 and after, making me 10 by August 1st. Unable to see the specified screen.

**Comment by rsgonzal** [comment]
Thank you! @mdancho a bday in dev 2011 will get you there!

**Comment by mdancho** [comment]
Wow. Friday brain is doing well. Confirmed the message is accurate aside from saying world pitch.
