### ISSUE TITLE
Make search visibility options more prominent for teams [20->40,20,1->2]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2697]
The checkboxes for a team or a mentor to allow themselves to appear in search results are hard to find and easily misinterpreted. Make them easier to find and more visible as shown below.

![Screen Shot 2020-10-08 at 12 36 40 AM](https://user-images.githubusercontent.com/6475595/95428990-9d609500-08fe-11eb-9d4b-3aface3ac7e6.png)

(#2731 is the mentor version of this ticket, which is much less far along)

## Suggested QA

The changes here should just be rearranging the page, not changing functionality. To that end, there are two different avenues for testing: 
1. make sure the rearranged elements are correct in a variety of situations, and
2. make sure the necessary page functionality hasn't broken

For the first, I would suggest looking at the page in a number of different situations, like
* team has one member, no invites or join requests
* team has multiple members
* team has pending members
* team has pending invites
* team has pending requests
* various scenarios above, with team building off
* various scenarios above, with the first round of judging started

And then make sure page controls still work, like
* removing a member
* deleting an invite
* inviting a user
* approving a join request
* denying a join request

**Comment by hellafitz** [comment]
NOTE: Updated screens are in profile fields invision board

- what do admins and ChAs see? A: base it on this updated content but preserve current additional functionality (e.g. links to student profiles only appear for them, not for students)
- do we want parts to disappear when team-building turns off (as it currently does). A: yes, follow current pattern and feel free to break off the 'do you want more teammates' section
- also powers a view of past teams for admins and ChAs. A: follow current pattern and check in if Qs

QA note: 
- do 'good enough' QA in the absence of detailed mockups
- create new tickets for feedback after 1 round

**Comment by rsgonzal** [comment]
#2666 could be used for the change to include info on how many team members are allowed

**Comment by stenington** [comment]
I have an invision board where I'm trying to understand the current patterns of behaviour based on different page "scenarios" (data or config situations where something changes on the page): https://projects.invisionapp.com/freehand/document/OyNBmSwOk

The bottom row is the current site, the top row is what I'm building. 

## Current site
* Simplest page, one member 
    * this is the baseline
* One of each thing (member, pending member, pending invitation, pending join request)
    * pending student section appears
    * invites sent section appears
    * requests from others section appears
* Five+ things
    * invite box and searchability checkbox are replaced with "5 students" message
* Team building off
    * invite box and searchability checkbox are replaced with "team building off" message
* Judging has started
    * invite box and searchability checkbox are replaced with "team building off" message
    * request accept/decline buttons are gone

## New page
* Simplest page, one member 
    * this is the baseline
* One of each thing (member, pending member, pending invitation, pending join request)
    * pending student section appears
    * invites sent section appears
    * requests from others section appears
    * **I don't like sections completely appearing/disappearing, but for now I'm preserving that pattern. Might revisit that though.**
* Five+ things
    * invite box replaced with "5 students" message
    * searchability checkbox is still there, **does that matter?**
* Team building off
    * invite box replaced with "team building off" message
    * searchability checkbox is still there, even though searchability shouldn't matter at this point. **Does that matter?**
* Judging has started
    * invite box replaced with "team building off" message
    * request accept/decline buttons are gone
    * searchability checkbox is still there, **does that matter?**

@hellafitz @rsgonzal Can I get a quick 👍 / 👎 on the top row? Would you be willing to send it to staging like that, or are there obvious problems?

**Comment by rsgonzal** [comment]
I think this looks good for staging!
- I think maybe the search visibility box (line?) should go away when team building is off?
Maybe the message that says, "team builiding is not enabled at this time..." can be moved up there? 
Also the, "you can not approve or decline..." can be up there too?

I guess i'm seeing this "Do you want more team mates" section as the main header to everything below. If that makes sense?

**Comment by stenington** [comment]
Okay, I like that idea. I've moved those different alerts up right under the "Do you want more team mates?" header and used a `notice` style to help call it out, since it explains why controls might be missing from the page. It looks like this, with the message changing depending on the situation:

![localhost_3000_mentor_teams_249](https://user-images.githubusercontent.com/55319/97012183-98fac580-1515-11eb-8b62-bb2b4772af09.png)

**Comment by stenington** [comment]
**Deployment note**: @nickiredescent wants a heads up when this goes live

**Comment by rsgonzal** [comment]
Making a note that I finally saw the message about only having 5 members/requests/invites. Will need to probably check in QA

![screencapture-technovation-qa-herokuapp-student-teams-228-2020-10-27-10_25_46](https://user-images.githubusercontent.com/22801026/97509852-98f92c00-1940-11eb-9f12-5c60f4426766.png)

**Comment by ophelieh** [comment]
TEAM BUILDING ON

* Testing as a team (Sample team) with one student who has a request from another student. It feels weird to have students under the team name. In the first mockup, it shows it on the same line. Did that change? If so, what was the reasoning behind it? 
![Screen Shot 2020-11-02 at 3 58 41 PM (2)](https://user-images.githubusercontent.com/32206421/97923835-4c3c9900-1d24-11eb-8203-70beaa473dc6.png)

The text about inviting more students feels out of place. Can we move the part about "You cannot invite... requests." under the "Do you want more teammates?" Also, the period is missing in the "If you're looking to add a mentor to your team, go her**e"** 


![Screen Shot 2020-11-02 at 4 01 26 PM (2)](https://user-images.githubusercontent.com/32206421/97924311-11873080-1d25-11eb-8d29-61263137de64.png)

* Testing as team inviting students. Worked as expected for students who are not on a team or registered. But when sending an invite to a student already on a team, I faced a minor issue: When I used the back button, it brought me to an error page. 
![Screen Shot 2020-11-02 at 4 08 59 PM (2)](https://user-images.githubusercontent.com/32206421/97924736-bdc91700-1d25-11eb-8e0c-38bc3d83208b.png). 

BUT looks like the email address needs to be updated --- info@technovationchallenge.org should be support@technovation.org
![Screen Shot 2020-11-02 at 4 10 40 PM (2)](https://user-images.githubusercontent.com/32206421/97924875-f8cb4a80-1d25-11eb-95b6-59c119e5097a.png)

* Testing as team with a pending member - worked as expected. The "students" under the team name feels even more out of place in that case. You see "Students" at the top and then "Pending students". Could we make the icons slightly smaller? They are huge and already require scrolling with just 2 students. 
<img width="1440" alt="Screen Shot 2020-11-02 at 4 21 48 PM" src="https://user-images.githubusercontent.com/32206421/97925736-83f91000-1d27-11eb-89dc-ba3dfde2228c.png">

* Testing as a team with multiple team members (Cacao) - works as expected. Unselecting the box to not be visible to students works as expected. 

* Testing as a team with 1 team member - worked as expected. 
* Testing as a team member to delete an invite - worked as expected
* Testing as a team member (team Cacao) - I can only remove pending students, not students with completed profiles. Removal of pending student worked as expected. 
* Testing as an admin to remove a member for the team (The Winning Trio) - worked as expected.

**Comment by ophelieh** [comment]
Still needs to be tested with team building off and with QF on

**Comment by stenington** [comment]
> It feels weird to have students under the team name. In the first mockup, it shows it on the same line. Did that change? If so, what was the reasoning behind it?

Yeah, that changed. The team name is shared across all tabs in the code currently, so I tried to see if I could get away with putting "students" below it, but I agree it looks strange. I think we either need to tweak the styles to make it look right, or I can make it so each tab defines its own header and it can say "<team name> students all in one line" on this tab.

> Can we move the part about "You cannot invite... requests." under the "Do you want more teammates?"

Curious what @hellafitz and @rsgonzal think, I can see the logic behind moving that line.

> the period is missing in the "If you're looking to add a mentor to your team, go here"

I will fix that.

> looks like the email address needs to be updated 

I opened #2785 

> Could we make the icons slightly smaller?

I had noticed that they were quite large too. @rsgonzal @hellafitz Are you open to making them smaller?

**Comment by ophelieh** [comment]
Ohhh makes sense. Thanks Mike! And I'll leave it up to you guys for the decisions. :)

**Comment by ksrebecca** [comment]
QA'ing for team building off scenario. While setting up teams to get them ready for that I saw that once you hit the limit of 5 members/invites etc you get a blue message box below. In that case I would think it's ok to get rid of the line at the top?
![image](https://user-images.githubusercontent.com/43972336/98058108-2a651400-1e01-11eb-9e97-8ad74c8ae1bc.png)
And agree with Ophelie, those student profile pix in the top section of who is on the team are pretty gigantic ;)

**With team building turned off:**
- I was able to delete an invitation the team had sent to another student.
-Was able to approve a request we had waiting
-Was not able to try to add new students (as expected)
-But was not able to get rid of all students - only 1 instead of 2 other students on the team had the remove this team member option, is that normal?
<img width="795" alt="Screen Shot 2020-11-03 at 6 27 00 PM" src="https://user-images.githubusercontent.com/43972336/98058554-4c12cb00-1e02-11eb-9867-f9d7b24c5809.png">
-I was able to remove myself from my own solo team, which was sort of weird when teambuilding was off because then there's no way I could get back on a team? But I guess if teambuilding closes right when submissions close it should be fine.

With quarterfinals judging turned on
- I was not able to add any new students to the team as expected
- I was able to delete an invite to another student (not sure if this is ok - messaging states you can't but I could)
<img width="625" alt="Screen Shot 2020-11-03 at 6 38 00 PM" src="https://user-images.githubusercontent.com/43972336/98059177-b9732b80-1e03-11eb-9f83-a3987e4593c6.png">
- I was not able to approve delete a request from a student, as expected and messaged
- I was able to remove myself when I was logged in from the team, could not remove any other team members (is this ok to be able to remove myself from the team during judging? I would say no)

**Comment by rsgonzal** [comment]
> > Could we make the icons slightly smaller?
> 
> I had noticed that they were quite large too. @rsgonzal @hellafitz Are you open to making them smaller?

I agree with this suggestion! I wouldn't mind them being the same size as pending students.

**Comment by rsgonzal** [comment]
> > Can we move the part about "You cannot invite... requests." under the "Do you want more teammates?"
> 
> Curious what @hellafitz and @rsgonzal think, I can see the logic behind moving that line.

So here, I have one with 5 already and the message does show up below. So I guess, how much do we want to emphasize? Would it live there in italics until there are 5 and we get the blue message? Or do we need it all?
![screencapture-technovation-qa-herokuapp-student-teams-228-2020-11-04-12_47_51](https://user-images.githubusercontent.com/22801026/98166513-64cfbf00-1e9c-11eb-9659-a7f30f469712.png)

**Comment by rsgonzal** [comment]
> While setting up teams to get them ready for that I saw that once you hit the limit of 5 members/invites etc you get a blue message box below. In that case I would think it's ok to get rid of the line at the top?

And just noticed rebecca suggested the same! 👍

**Comment by rsgonzal** [comment]
> * -But was not able to get rid of all students - only 1 instead of 2 other students on the team had the remove this team member option, is that normal?

Were you logged in as Boba Tea? You should only be able to remove yourself if others are fully onboarded

>I was able to delete an invite to another student (not sure if this is ok - messaging states you can't but I could)

I would say this is ok? they shouldn't be able to sign up and participate this late in the game anyways

> I was not able to approve delete a request from a student, as expected and messaged - I was able to remove myself when I was logged in from the team, could not remove any other team members (is this ok to be able to remove myself from the team during judging? I would say no)

Lol, i mean if a student removes themselves - sounds like it's their problem? i feel like it only hurts themselves 🤷‍♀️ , but it is strange i guess

**Comment by rsgonzal** [comment]
@stenington should i move this to code review for shaun or is it going on staging?

**Comment by stenington** [comment]
Oh, the new changes might be worth a quick glance. I'll move it.

**Comment by stenington** [comment]
@rsgonzal I fixed the punctuation, removed the "You cannot invite..." line from the top, and made the avatars smaller. They will be smaller on the mentor tab now too, but I figure that's what we want.

**Comment by kate-technovation** [comment]
Suggested QA:

**Comment by rsgonzal** [comment]
Thanks, @kate-technovation !! I've tested as well from a one person team and one with up to five. Requests and invites seem to be working normally.
