### ISSUE TITLE
Bug: Can not view participant page for a mentor

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2704]
**Describe the bug**
When going to view the page of a mentor, I get an error that something went wrong

**To Reproduce**
1. Go here for steps and participant info https://docs.google.com/spreadsheets/d/1n8NNV45E3lM4eDS8KCG2bEWHTmAX0wOLpQDkkxsiwLY/edit#gid=1646167643&range=H31

**Expected behavior**
I should be able to view the participant page

**Screenshots**
![Screen Shot 2020-09-28 at 1 46 04 PM](https://user-images.githubusercontent.com/22801026/94485046-33275200-0192-11eb-95f3-44cffe104972.png)

**Additional context**
This user use to be a ChA ChA, was converted to just being a mentor. Ophelie is trying to make him a ChA again. There were some issues with this combo account before #2395

**Comment by stenington** [comment]
I can't replicate this (I am able to see the user's page) but I do see this in the logs

```
Sep 28 13:35:02 technovation app/web.1: F, [2020-09-28T20:35:02.299568 #37] FATAL -- : [867e602a-99e0-4edc-89c5-5efb7546e165] ActionView::Template::Error (undefined method `full_name' for nil:NilClass):
Sep 28 13:35:02 technovation app/web.1: F, [2020-09-28T20:35:02.300006 #37] FATAL -- : [867e602a-99e0-4edc-89c5-5efb7546e165]     25:       <ul class="unstyled">
Sep 28 13:35:02 technovation app/web.1: [867e602a-99e0-4edc-89c5-5efb7546e165]     26:         <% mentors.each do |m| %>
Sep 28 13:35:02 technovation app/web.1: [867e602a-99e0-4edc-89c5-5efb7546e165]     27:           <li>
Sep 28 13:35:02 technovation app/web.1: [867e602a-99e0-4edc-89c5-5efb7546e165]     28:             <%= link_to m.full_name, send(
Sep 28 13:35:02 technovation app/web.1: [867e602a-99e0-4edc-89c5-5efb7546e165]     29:               "#{current_scope}_#{profile_path_name}_path",
Sep 28 13:35:02 technovation app/web.1: [867e602a-99e0-4edc-89c5-5efb7546e165]     30:               m.send(profile_id),
Sep 28 13:35:02 technovation app/web.1: [867e602a-99e0-4edc-89c5-5efb7546e165]     31:               allow_out_of_region: true,
Sep 28 13:35:02 technovation app/web.1: F, [2020-09-28T20:35:02.300115 #37] FATAL -- : [867e602a-99e0-4edc-89c5-5efb7546e165]   
Sep 28 13:35:02 technovation app/web.1: F, [2020-09-28T20:35:02.300209 #37] FATAL -- : [867e602a-99e0-4edc-89c5-5efb7546e165] app/models/mentor_profile.rb:169:in `public_send'

```

**Comment by rsgonzal** [comment]
Weird it's working for me too now. is there anything here to further investigate or just wait if it happens again?

**Comment by stenington** [comment]
We could potentially investigate a bit more based on the error message I included, but I don't immediately see how the situation that caused the error could have arisen.

**Comment by hellafitz** [comment]
No reports of this resurfacing in the last three weeks. Closing for now.
