### ISSUE TITLE
Pass additional info to MailChimp on signup [13,13,1]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2710]
@ksrebecca inquired whether we could include birth year and country when importing student data to Mailchimp. This is useful, for example, when doing targeted email outreach to alumni (e.g. sharing an opp for girls 14 and under, or something just for girls in Kazakhstan)

Deliverables: 
Pass additional merge variables to MailChimp from the TG platform when a student signs up:
- Birth year (not the full birthdate which is PII)
- Country (PT acknowledges there will probably be messy data included, e.g. Spain vs ES)

## QA STEPS
* Sign up as a new student/mentor/judge, after signing up `BIRTHYEAR` and `COUNTRY` should be populated in Mailchimp
* As a parent, sign a parental consent form, `BIRTHYEAR` and `COUNTRY` shouldn't be filled out in Mailchimp (but `NAME` should be)

Also, would be good to test...
* Update a student/mentor/judge profile (name, DOB, country, email), and those changes should be reflected in Mailchimp

##### Add `ENABLE_MAILCHIMP` configuration setting
- [X] QA
- [x] Production

##### Remove `ENABLE_MAILING_LISTS` 
- [X] QA
- [x] Production

##### Add new merge fields - `BIRTHYEAR`, `COUNTRY`, `NAME`
- [X] QA
- [x] Production

**Comment by hellafitz** [comment]
@bagomer do you need this info for mentors too?

**Comment by bagomer** [comment]
Yes please, I can see Country being quite helpful; birth year might be helpful as well for fundraising etc.

**Comment by stenington** [comment]
We can add country as a merge variable, but it looks like Mailchimp also understands locations in lat/long, so I think we might consider using that too.

**Comment by hellafitz** [comment]
Updated Deliverables:
Pass additional merge variables to MailChimp from the TG platform when a student signs up:
- Birth year (not the full birthdate which is PII)
- Country (PT acknowledges there will probably be messy data included, e.g. Spain vs ES)
- Lat/Long [DISCUSS]

Pass additional merge variables to MailChimp from the TG platform when a mentor signs up:
- Country (PT acknowledges there will probably be messy data included, e.g. Spain vs ES)
- - Lat/Long [DISCUSS]

**Comment by shaunxp20** [comment]
> We can add country as a merge variable, but it looks like Mailchimp also understands locations in lat/long, so I think we might consider using that too.

@stenington When you have a moment. If I'm reading the deliverables correctly, we want to add lat/long as merge fields/variables. I have a working example of sending all the new merge fields (including lat/long) to Mailchimp. But I'm struggling to see how Mailchimp uses the lat/long as a merge fields.

I found this article, but it doesn't mention merge fields:
https://mailchimp.com/help/about-geolocation/

Is that what you were referring to? Wondering if I'm missing something about using lat/long as merge fields (or maybe we should scrap the lat/long merge fields requirement)? 🤔

**Comment by stenington** [comment]
Oh, for lat/long I noticed that the API endpoint to create a new member on a list took a location parameter, consisting of a latitude and longitude: https://mailchimp.com/developer/api/marketing/list-members/add-member-to-list/ It's a separate body parameter from the merge fields though.

**Comment by shaunxp20** [comment]
Ah, I see! Thank you! I'll see about adding that new parameter. 👍

**Comment by shaunxp20** [comment]
This one is on QA, some QA steps have been added as well. 😄

**Comment by rsgonzal** [comment]
@shaunxp20 I signed up as a judge and i am not seeing country info in mailchimp

**Comment by rsgonzal** [comment]
hmm, i edited my name and now i see it

**Comment by rsgonzal** [comment]
student
- i also edited my birth year for roxana+parent@iridescent but it didn't update. I don't think this is likely to happen though!
- hmm it looks like ^^ it updated after i changed the email too.

ok so i think when country or birth year are updated, it doesn't automatically tell mailchimp. But after name or email are updated it does tell mailchimp and it updates all other changes that were made.

I think this is only really a problem for judges cause i guess the way we collect location is after info has already been given to mailchimp

**Comment by shaunxp20** [comment]
Thanks for the thorough QA effort Roxana! 🥇 🙌 

> i also edited my birth year for roxana+parent@iridescent but it didn't update. I don't think this is likely to happen though!

I have a PR/fix so that when DOB is changed, it will update Mailchimp.

Regarding country, afaict, that looks like a bug, I see in the code that "if country is changed, update Mailchimp", but obviously it's not working. If it's a show stopper I can keep trying to debug or we could open a bug ticket for it to work on later. Thoughts? 🤔

**Comment by rsgonzal** [comment]
> I have a PR/fix so that when DOB is changed, it will update Mailchimp.
woohooo!

> Regarding country, afaict, that looks like a bug, I see in the code that "if country is changed, update Mailchimp", but obviously it's not working. If it's a show stopper I can keep trying to debug or we could open a bug ticket for it to work on later. Thoughts? 🤔
I'll open up a new bug ticket since it's only affecting judges! judges shouldn't be signing up until later this year. there may be some mentor/judges that get populated. I'm not actually sure how those get sent to mailchimp. Maybe i'll test it out too. Either way i'll add to our tf/tg notes so that people are aware.

**Comment by ksrebecca** [comment]
I just QAd also:

- Student - all worked as planned. I also updated the birth year and it updated in Mailchimp, same with email. But for what it's worth when I changed my email it kept giving me an error message on the platform for student and mentor, not sure if that's the case for the real platform too or just staging.
-Mentor - same as student. Except when I switched my country from Lebanon to Palestine it did not update in Mailchimp.
-Judge - @rsgonzal how do you sign up as a judge?
-Parent - name did not get passed to mailchimp even though i entered it from both student side and when the parent signed the form

Love seeing the list so organized with the tags 💯

**Comment by shaunxp20** [comment]
> I'll open up a new bug ticket since it's only affecting judges! judges shouldn't be signing up until later this year. there may be some mentor/judges that get populated. I'm not actually sure how those get sent to mailchimp. Maybe i'll test it out too. Either way i'll add to our tf/tg notes so that people are aware.

Thanks Roxana! I think I might have a fix for it (just needs more testing), I added a note to the new ticket for when we pick it up. 😄

**Comment by shaunxp20** [comment]
Thanks for testing this one Rebecca! 🙌 🍰 🎈 

> But for what it's worth when I changed my email it kept giving me an error message on the platform for student and mentor, not sure if that's the case for the real platform too or just staging.

I think that's related to this bug: #2766 (I think I can find time to work on that sometime next iteration (starts next week))

> Except when I switched my country from Lebanon to Palestine it did not update in Mailchimp.

Roxana ran into that too, there's a bug ticket for it: #2779 

> Parent - name did not get passed to mailchimp even though i entered it from both student side and when the parent signed the form

For parents only "Full Name" will be filled out in Mailchimp, since parents just have one name field to fill out, not separate first/last name fields like our other accounts.

> Love seeing the list so organized with the tags 💯
🙌 🎉

**Comment by rsgonzal** [comment]
Thanks for opening up the new bug ticket! We should definitely work on that next iteration.

I think this one is good to go. There was just a question about the birth year getting passed over as a number (with a comma). Is this happening on our end or mailchimps?

**Comment by shaunxp20** [comment]
> I think this one is good to go. There was just a question about the birth year getting passed over as a number (with a comma). Is this happening on our end or mailchimps?

That's happening on the Mailchimp side, birth year is setup as a number field, the comma is just how Mailchimp formats number fields.
