### ISSUE TITLE
Switch email address that sends auto-emails

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2714]
Emails are currently being sent from mailer@technovationchallenge.org

Since Technovation Challenge is no longer a thing, we probably want to change that. Is there a reason we use mailer? Is this standard practice?

We also list this address on the student dashboard, program team wants to update resources based on this:
![Screen Shot 2020-09-30 at 3 07 18 PM](https://user-images.githubusercontent.com/22801026/94744953-ad8cd900-032e-11eb-8466-21ce9a422603.png)

Notes from Mike:
- this might have more to do with how mailchimp/mandrill is configured or maybe even just how our dns is set up

**Comment by hellafitz** [comment]
Content-wise, we are still referencing support@technovationchallenge.org, help@, support@ and potentially other @technovationchallenge.org email addresses on the platform. Swap these for @technovation.org equivalents (after confirming what should go where).

Refinement open Q: is there a good technical reason to use mailer@ or another distinct sender to protect our non-transactional email deliverability?

**Comment by stenington** [comment]
I had been wondering if `mailer@` was essentially some sort of no-reply email address, but it seems like using no-reply addresses is not recommended these days. (Here's [an example article](https://sendgrid.com/blog/why-you-should-not-use-noreplydomain-com-in-your-emails/) by Sendgrid.) 

It seems to me like we should be sending email from some sort of monitored email address. I don't know if we should just use our support email, or set up something else. I'm not sure if there are email reputation considerations, or maybe Zendesk workflow reasons to separate them out? We might not want our support email flooded with people responding to automatic emails, if they don't actually need help? On the other hand, if people are responding asking for help, we want to make sure we aren't missing those emails, right?

**Comment by hellafitz** [comment]
+1 on sending from a monitored email address. In terms of which one, we should discuss this with (at least) Kate and @ksrebecca.

**Comment by ksrebecca** [comment]
quick note to say that if we switch the email which is fine but hopefully there's some sort of zendesk filter that won't give kate or eren a heart attack ;) we should also switch the instructions for how to find the consent form (I think in one line it says add "xyz" email to your non spam filter or something like that

**Comment by ksrebecca** [comment]
Update. Kate would like to see evidence of many people reporting frustration with the current no reply system ;) basically because she's frustrated with zendesk right now in terms of troubleshooting and setting up pathways/processes and it seems people are able to find a way to contact us based on zendesk volume. Perhaps we table this ticket until next season?
