### ISSUE TITLE
Replace the link to curriculum on TG [5,3,1.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2715]
Currently, we have https://www.technovationchallenge.org/curriculum-intro/registered linked in various places on the platform.

Since we're no longer showing different versions of the curriculum, Maggie has asked that we switch it to this direct link
https://technovationchallenge.org/curriculum-intro/registered/new/

## QA suggestion

Three links needed updating:
1. mentor dashboard dropdown
2. student dashboard dropdown
3. curriculum link in the chapter ambassador resources page

**Comment by mjaris** [comment]
Yes – let me know if that's a problem!

**Comment by rsgonzal** [comment]
These links have been updated!
