### ISSUE TITLE
Rebrand: Replace World Pitch with World Summit all over TG [8,3,2.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2716]
We are still using 'World Pitch' in various places on the platform. Let's try to do a direct replacement with 'World Summit'

## QA Suggestion

We were saying "World Pitch" in the following locations:

* During the age verification step of registration
* If attempting to sign up as someone younger than 10, the error message shown on the profile selection part of registration
* The email sent declining a chapter ambassador (not sure if this gets sent any more, since we invite them)
* Twice in the parental consent email

**Comment by hellafitz** [comment]
Estimated 5 places where this occurs in the codebase

**Comment by rsgonzal** [comment]
This looks good. we don't decline ChAs anymore.

I didn't see the language in parent consent though

**Comment by rsgonzal** [comment]
@stenington which email is it exactly?

**Comment by rsgonzal** [comment]
actually i can check!

**Comment by rsgonzal** [comment]
ah it's the actual consent form. Can confirm the changes

**Comment by rsgonzal** [comment]
wow, the pdf gets updated too! magic
