### ISSUE TITLE
Update Chapter Ambassador Resource Page text Pt2

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2717]
Opening this one up for ophelie's comment and a potential link to a resource on parental consent

"Could we rename the second portion to "FAQ & Submission" instead of "FAQ & Rules"?"
![Screen Shot 2020-09-23 at 10 03 43 AM](https://user-images.githubusercontent.com/22801026/94045390-3ed6db00-fd84-11ea-97dc-60c6d950a095.png)

**Comment by rsgonzal** [comment]
From #2691

**Comment by hellafitz** [comment]
Couldn't the FAQ & Rules part just be FAQ if we made Submission Guidelines and Judging Rubric into questions (e.g. What are the Submission Guidelines?) or, alternately, moved those two items up into Resources?

Sidenote: Shouldn't "How will team's app be judged?" be "How will teams' apps be judged?"?
