### ISSUE TITLE
Update timeline (key dates) in emails [13,3,4.34]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2722]
There is a tag '@timeline_url' in the mentor & student welcome emails.

This needs to be replaced with: https://technovationchallenge.org/wp-content/uploads/2020/09/Technovation-Girls-2021-Season-Timeline-Key-Dates-Infographic.pdf

## QA Suggestion
1. sign up as a mentor 
2. confirm the key dates link in the welcome email
3. sign up as a student
4. confirm the key dates link in the welcome email

**Comment by stenington** [comment]
The `@timeline_url` template variable was removed last year, but I think you're talking about updating these two links, right?

https://github.com/Iridescent-CM/technovation-app/blob/qa/app/views/registration_mailer/welcome_student.en.html.erb#L54

https://github.com/Iridescent-CM/technovation-app/blob/qa/app/views/registration_mailer/welcome_mentor.en.html.erb#L57

**Comment by rsgonzal** [comment]
AH! yes, these are the links we want replaced

**Comment by rsgonzal** [comment]
This looks good!
