### ISSUE TITLE
Redesign the signup / login page

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2724]
This page is currently used for:
- new student signup
- new mentor signup
- returning student login
- returning mentor login

![Screen Shot 2020-09-25 at 3 19 34 PM](https://user-images.githubusercontent.com/6475595/94320781-a2a70280-ff42-11ea-8e57-e366b413f23f.png)

This ticket is to develop a new version of the page. It could be anything from a simple visual design refresh to something more complicated.

**Comment by hellafitz** [comment]
We have a first draft of this from Audra but it needs some revision.

**Comment by hellafitz** [comment]
v2 Mockups are approved. Use SIGN UP as the headline text. Use the blue text version of the desktop mockups otherwise. https://www.dropbox.com/sh/8yiponsxd0paxh6/AABGX3N6HJHCGNQuX8MRtBema?dl=0

**Comment by hellafitz** [comment]
We think this should live on technovationchallenge.org

We need a URL and more detail on user flows. 

Open Q: Logic on Wordpress site? Would need automatic switch based on platform settings or manual toggle.

**Comment by hellafitz** [comment]
v2 designs https://www.dropbox.com/sh/8yiponsxd0paxh6/AABGX3N6HJHCGNQuX8MRtBema?dl=0

**Comment by stenington** [comment]
This invision shows some context for how the platform landing page, sign in page, and sign up flow connect to each other in both a "registration on" and registration off" scenario. https://projects.invisionapp.com/freehand/document/JYyPCLI2b

**Comment by hellafitz** [comment]
@ksrebecca to confer with Maggie about streamlining Sign Up and Get Started, using the new copy and conversion-centric approach.
