### ISSUE TITLE
Change the message on Pitching Event tab from student/Mentor dashboard & submission page [8,3,2.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2734]
As a student, I currently see the tab for pitching events. If I try to hover over, I am told this will be enabled later in the season. 

It will not be available during the 2021 season. The team has asked if we can hide this.

**DECISION:**
- **Change hover message to say, "No official scoring events happening in 2021 due to COVID. Check with your Chapter Ambassador about local celebration events!"**
![Screen Shot 2020-10-08 at 8 54 18 AM](https://user-images.githubusercontent.com/22801026/95483479-1e8e4b00-0944-11eb-9ae9-3ffb76a7b784.png)

Gray box
- **No team will submit pitch presentation slides here because all official Regional Pitch Events are canceled due to COVID this season.**

White area:

- **If you are attending a local celebration or unofficial pitch event, your Chapter Ambassador may ask you to share your pitch presentation slides with them before the event. Coordinate with them directly and good luck!**

![Screen Shot 2021-02-03 at 10 19 42 AM](https://user-images.githubusercontent.com/22801026/106791152-6890f000-6609-11eb-95f6-6abb50855c07.png)

## QA STEPS
- From both a student's and mentor's dashboard, hover over the "Find a Pitch Event" menu item - verify that verbiage looks good
- From the "My Team's Submission" page, click "Regional Events" - verify the content on that page looks good

**Comment by rsgonzal** [comment]
- For the top screen, change the message to "Due to Covid, there will be no pitching events for the 2021 season"
- Not sure if we have the ability to add the same type of message for the bottom screen

**Comment by ksrebecca** [comment]
@rsgonzal for top bullet i would phrase "Due to COVID, there are no official pitch events this season."

**Comment by hellafitz** [comment]
Updated deliverable: change the "This feature will open later in the season" text on the top screen to Rebecca's version, "Due to COVID, there are no official pitch events this season."

**Comment by rsgonzal** [comment]
From #2738, might want to edit the page instead of disabling the button to include: https://www.technovation.org/news-events/local-events/

**Comment by rsgonzal** [comment]
original comment has been edited with updates from Rebecca & Ophelie

**Comment by shaunxp20** [comment]
On QA with some QA steps too! 😄 👍

**Comment by ophelieh** [comment]
As a student and mentor with event selection OFF -  Everything looks good except for this screen. You get there by clicking "Find a pitch event" 

<img width="1440" alt="Screen Shot 2021-03-12 at 5 44 44 PM" src="https://user-images.githubusercontent.com/32206421/111009955-a4cb1500-835a-11eb-8fcf-dd74ea1d9df3.png">

As a mentor and student when event selection is ON - When I turned on events (which I know we wouldn't but just wanted to test & note it here) it shows this

<img width="1440" alt="Screen Shot 2021-03-12 at 5 47 02 PM" src="https://user-images.githubusercontent.com/32206421/111010045-f6739f80-835a-11eb-9985-cc21845f5476.png">

**Comment by nickiredescent** [comment]
Same as Ophelie, clicking on "Find a Pitch Event" from the dashboard gets me to a page that probably should be updated as well:
![image](https://user-images.githubusercontent.com/45576078/111213435-fa3b3800-858d-11eb-8d8a-37169c261eaa.png)


I also saw different messaging when turning **on** "Event Selection" via the admin dashboard:
![image](https://user-images.githubusercontent.com/45576078/111212965-826d0d80-858d-11eb-9cb0-84b3c6d72c59.png)

Otherwise, the wording seems present and accurate everywhere else.

**Comment by rsgonzal** [comment]
Thank you! Live pitching event toggle should not be turned on!

As for the screen that says, selecting an event is not available right now. Is this an issue? Language seems fine to me if I were a student and stumbled on it, but if you want to change the language let me know what you want it to say! @nickiredescent @ophelieh 

@shaunxp20 this 'go back' button link has always been there, but it feels weird. Because it just takes you back to the header page. Does it serve another purpose? Maybe when presentation slides are uploadable. Was thinking of removing, but don't want to mess with any future uses of it.

**Comment by shaunxp20** [comment]
> @shaunxp20 this 'go back' button link has always been there, but it feels weird. Because it just takes you back to the header page. Does it serve another purpose? Maybe when presentation slides are uploadable. Was thinking of removing, but don't want to mess with any future uses of it.

That 'go back' link is hardcoded to return to the "Submission: Regional events" page/section. Fwict, it's not doing anything special. Let me know if you want to remove it. 😄

**Comment by shaunxp20** [comment]
Okay, the 'go back' link has been removed, this is one QA now. :shipit:

**Comment by ophelieh** [comment]
I confirm that the "back button" is gone from the team submission page. 

For the live pitch event portion, I see what you mean Roxana. Knowing our participants though and the random tickets we receive, could we change the text to the same as when you hover -  "Due to COVID, there are no official pitch events this season."? I'm hoping this can prevent additional questions.

Thanks! :)

**Comment by shaunxp20** [comment]
> Knowing our participants though and the random tickets we receive, could we change the text to the same as when you hover - "Due to COVID, there are no official pitch events this season."? I'm hoping this can prevent additional questions.

The "Live pitch events" page has this ☝️ message now. Let me know if it's okay, and if there's anything else! 😄

**Comment by rsgonzal** [comment]
Looks great!

**Comment by ophelieh** [comment]
I confirm, it looks great! Thank you all! :)

**Comment by shaunxp20** [comment]
Just deployed this one, thanks y'all! 🎈🎈🎈🎈🎈
