### ISSUE TITLE
Add a tab for curriculum on student/mentor dashboards [20,8,2.5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2735]
Students have a hard time finding the curriculum from the dashboard dropdown. 

* Add a tab to the right navigation bar in between "Build your Team" and "Submit your project" that says "Learn from the Curriculum"
* Checkbox should mark as complete when the team submits

**The "Learn from the Curriculum" link should go to a new page with the following content:**
Curriculum

Learn how to make your project as strong as possible by following these lessons. Most participants spend around 60 hours working on their ideas.

Button reads: Go to Lessons (with link to: https://technovationchallenge.org/curriculum-intro/registered/new/)

Visit these helpful links to prepare your app for judging:

Submission Guidelines (updated each season)
-link: https://technovationchallenge.org/submission-guidelines/

Judging Rubric
-link: https://technovationchallenge.org/curriculum/judging-rubric/

Suggested Milestones
-link: https://technovationchallenge.org/wp-content/uploads/2020/09/Technovation-Girls-2021-Season-Timeline-Key-Dates-Infographic.pdf

Awards Page
-link: https://technovationchallenge.org/award-structure/

Apps from Past Teams
-link: https://www.technovation.org/app-gallery/

**Update the sidebar navigation links:**
"Complete your Profile"
"Build your Team"
"Learn from the Curriculum"
"Submit your Project"
"Find a Pitch Event"
"View Scores & Feedback"

## QA STEPS
* As a student and mentor: verify the changes to the sidebar navigation links
* As a student and mentor: verify the content on the new "Learn from the Curriculum" page
* As a student: verify the "Learn from the Curriculum" checkbox gets checked when the teams submits their project

< 5mins

![Screen Shot 2020-10-08 at 9 11 46 AM](https://user-images.githubusercontent.com/22801026/95485252-539b9d00-0946-11eb-917a-1758477d12b5.png)

**Comment by stenington** [comment]
Would it be an empty circle that just never gets a check mark in it?

**Comment by rsgonzal** [comment]
I would say yes for V1. (Or maybe it could finally get a checkmark if they submit..?)

**Comment by hellafitz** [comment]
Right-hand "Curriculum" item could be linked, or there could be an actual screen that appears (and would need content)

**Comment by hellafitz** [comment]
Sidebard: ~ Build your app/idea with the Curriculum

Content section ideas:
Make sure to check out our curriculum here, here's how it aligns with the judging rubric, check out our updates for this season, tutorial videos etc

**Comment by hellafitz** [comment]
Next step: mockup the screen w/ input from PT

**Comment by rsgonzal** [comment]
Old mockup i had to make it look like wordpress
![Screen Shot 2020-11-13 at 9 11 29 AM](https://user-images.githubusercontent.com/22801026/99102090-7008a600-2592-11eb-8b28-9595682eefbc.png)

New mockup that just pulls some resources foud on wordpress
![Screen Shot 2020-11-13 at 9 26 52 AM](https://user-images.githubusercontent.com/22801026/99102167-8e6ea180-2592-11eb-9ec1-082ec5a1688a.png)

**Comment by hellafitz** [comment]
Confirmed: Checkbox should mark as complete when the team submits

**Comment by hellafitz** [comment]
"Complete your Profile"
"Build your Team"
"Learn from the Curriculum"
"Submit your project"
"Find a Pitch Event"
"View Scores & Feedback"

**Comment by rsgonzal** [comment]
Copy:

Curriculum
Plan to spend 60+ hours using these lessons to complete your project. 
Button reads: Go to Lessons
You can also use the tools below to develop your idea
New Submission Guidlines
-link: https://technovationchallenge.org/submission-guidelines/
Suggested Milestones
-link: https://technovationchallenge.org/wp-content/uploads/2020/09/Technovation-Girls-2021-Season-Timeline-Key-Dates-Infographic.pdf
Awards Page
-link: https://technovationchallenge.org/award-structure/
Judging Rubric
-link: https://technovationchallenge.org/curriculum/judging-rubric/

**Comment by ksrebecca** [comment]
Suggested copy:

Curriculum
Learn how to make your project as strong as possible by following these lessons. Most participants spend around 60 hours working on their ideas.
Button reads: Go to Lessons

Visit these helpful links to prepare your app for judging: 
Submission Guidelines (updated each season)
-link: https://technovationchallenge.org/submission-guidelines/
Judging Rubric
-link: https://technovationchallenge.org/curriculum/judging-rubric/
Suggested Milestones
-link: https://technovationchallenge.org/wp-content/uploads/2020/09/Technovation-Girls-2021-Season-Timeline-Key-Dates-Infographic.pdf
Awards Page
-link: https://technovationchallenge.org/award-structure/
Apps from Past Teams
-link: https://www.technovation.org/app-gallery/

**Comment by shaunxp20** [comment]
> Confirmed: Checkbox should mark as complete when the team submits

For mentors with more than one team/submission, will it be marked as complete when all of their teams have submitted?

**Comment by shaunxp20** [comment]
> > Confirmed: Checkbox should mark as complete when the team submits
> 
> For mentors with more than one team/submission, will it be marked as complete when all of their teams have submitted?

I verified that for mentors the "Submit your Project" checkbox will never get checked off, which means the "Learn from the Curriculum" checkbox would also never get checked off.

Here is a screenshot of a mentor w/ one team that has completed their submission that shows the unchecked checkbox:
<img width="1179" alt="Screen Shot 2020-12-04 at 4 26 35 PM" src="https://user-images.githubusercontent.com/58957909/101225238-d9a73c00-3688-11eb-90ba-e059b433c374.png">

Also, this part of the code for mentors sets the checkbox to always be unchecked:
https://github.com/Iridescent-CM/technovation-app/blob/3ba9038946ce2fed30d43e29cbc57087730b37f8/app/javascript/mentor/DashboardMenu.vue#L93-L95

**Comment by shaunxp20** [comment]
This one is on the QA site, and some QA steps have been added too. 👍 🎈

**Comment by rsgonzal** [comment]
it's beautiful!

can we make these links pop out:
- judging rubric
- suggested milestones

**Comment by shaunxp20** [comment]
> can we make these links pop out:
>  * judging rubric
>  * suggested milestones

I just made the change so these two links shlould pop out in a new window/tab. It's on QA, let me know if that's what you wanted! 😃

**Comment by ksrebecca** [comment]
QA
All working as planned!
As a student, Dashboard menu on the right side now has updated names including the Curriculum section.
The curriculum section has correct text and all links work to correct places 👍 
And when I submitted both the Learn from the Curriculum and Submit your Project items got a checkmark 💯 

As a mentor
Changes to the sidebar navigation links correct
Content on the new "Learn from the Curriculum" page correct!
 
Looking great!

**Comment by mdancho** [comment]
Both the mentor and student dashboards show the "learn from the curriculum" sidebar item and page details with working links. When I submit as a student the learn from the curriculum and submit your project are check-marked to signify completion. 
![Uploading Screen Shot 2020-12-14 at 3.46.27 PM.png…]()

**Comment by rsgonzal** [comment]
Thanks, everyone! This one is good to go.

**Comment by shaunxp20** [comment]
Thanks @ksrebecca @mdancho @rsgonzal 🙌 !!! This has been deployed to production too! 😁
