### ISSUE TITLE
Replace link for Terms of Use and Privacy policy and Internet safety [8,5,1.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2736]
Can we do a direct change for these links:
- http://iridescentlearning.org/terms-of-use/ --> https://www.technovation.org/terms-of-use/
- http://iridescentlearning.org/privacy-policy/ --> https://www.technovation.org/privacy-policy/
- https://iridescentlearning.org/internet-safety/ --> https://www.technovation.org/safety/internet-safety-training/

Currently found in 
- footer
- Data terms page (terms)

**Comment by hellafitz** [comment]
Q: Should we bundle the internet safety page in with this? A: Yes (link appears in some emails we send and some error pages, maybe a couple other places)

**Comment by rsgonzal** [comment]
@shaunxp20 were all of these changes with #2785 ?

**Comment by shaunxp20** [comment]
> @shaunxp20 were all of these changed with #2785 ?

The links in this ticket will still need to be updated (I only updated the ones on the error pages, which are separate from the ones listed here). 👍 😄 🍵
