### ISSUE TITLE
Disable button and add COVID note to Events tab for ChAs [5,3,1.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2738]
Since there are no events for 2021 season, the team doesn't want ChAs to create any by mistake. If they do, this could mess with judging

![Screen Shot 2020-10-08 at 9 26 38 AM](https://user-images.githubusercontent.com/22801026/95486929-86469500-0948-11eb-92d8-a88d438a1422.png)

### To DOs
Deliverables:

1. Add text "Due to COVID, there are no official pitch events this season. To list an UNOFFICIAL event, Chapter Ambassadors may add it to this spreadsheet. After being reviewed by Technovation staff, the event will be publicly displayed on the Technovation website under Local Events."
- [link for 'this spreadsheet': https://docs.google.com/spreadsheets/d/1xmsOtPcnargy9AeNcBJf65s0DoPnbYp108adZp4nQsU/edit#gid=27021989
- [link for 'Local Events': https://www.technovation.org/news-events/local-events/]
2. grey out the button
![Screen Shot 2020-11-13 at 9 37 57 AM](https://user-images.githubusercontent.com/22801026/99103152-fd98c580-2593-11eb-9d6b-2b306680ef3a.png)

## QA STEPS
- Login as a chapter ambassador, click "Events" in the sidebar - verify the button is disabled, and the content/links look good

**Comment by stenington** [comment]
Hiding parts of the UI takes on a bit of technical debt, in that now you have a bunch of code that can't be reached any more for testing purposes. So depending on the final decision of whether or not RPEs eventually come back, we'd either have to pay off the debt by removing all the hidden code, or by un-hiding it and making sure it's still in operational shape. Let's factor that in to our discussion of this one.

**Comment by hellafitz** [comment]
Shifting this to be 'disable the button and add explanatory text about COVID via config

**Comment by rsgonzal** [comment]
should we just disable it or is it possible to add a hover message like here:

![]()

**Comment by hellafitz** [comment]
Follow the approach and design pattern in #3734

**Comment by rsgonzal** [comment]
- add covid message
- disable/gray out button
![Screen Shot 2020-11-13 at 9 37 57 AM](https://user-images.githubusercontent.com/22801026/99103152-fd98c580-2593-11eb-9d6b-2b306680ef3a.png)

**Comment by ksrebecca** [comment]
https://www.technovation.org/news-events/local-events/

**Comment by hellafitz** [comment]
Decision/next steps: @ksrebecca will check with ChAs. If ChAs indicate it'd be helpful to have unofficial events, then we should grey out the 'add a judge' part of the event pages. If they don't, then we'll proceed with greying out the events button and adding a link that encourages them to do a celebration event.

**Comment by rsgonzal** [comment]
We decided that they didn't need events on the site and we can gray out the button. Rebecca to give link

**Comment by ksrebecca** [comment]
Link for all profile types: https://www.technovation.org/news-events/local-events/

IF it's easy to include this link ONLY on Chapter Ambassador view, that would be an added bonus (to be able to add their events): https://docs.google.com/spreadsheets/d/1xmsOtPcnargy9AeNcBJf65s0DoPnbYp108adZp4nQsU/edit#gid=27021989

**Comment by hellafitz** [comment]
Deliverables: 
- Add text after "Due to COVID... this season": "To list an UNOFFICIAL event, Chapter Ambassadors may add it to this spreadsheet. After being reviewed by Technovation staff, the event will be publicly displayed on the Technovation website under Local Events." [link for Local Events: https://www.technovation.org/news-events/local-events/]
- grey out the button

**Comment by shaunxp20** [comment]
This one is on QA, and some QA steps have been added too! 🥳 🥂 🙌

**Comment by ophelieh** [comment]
Works as expected! :) Could we maybe hide, cross off, or remove this text? 
<img width="1440" alt="Screen Shot 2021-03-12 at 5 55 54 PM" src="https://user-images.githubusercontent.com/32206421/111010487-5159c680-835c-11eb-9b6e-c842cab5197a.png">

**Comment by nickiredescent** [comment]
Agree with Ophelie, that text is awkward to have given the new next. Otherwise, looks good!

**Comment by rsgonzal** [comment]
@ophelieh just noting that if we remove it, it'll be missing in the future if we ever open up these pitch events again. let me know you definitely want to get rid of it!

**Comment by shaunxp20** [comment]
Roxana and I talked about removing that text block (Or, alternatively:...) this morning, and we're going to remove it. 👍

**Comment by ophelieh** [comment]
Works for me! It is something we also share via email with them so at the worst we'll have that somewhere.

Thank you!!

**Comment by shaunxp20** [comment]
Thanks for taking a look at this one, @ophelieh @nickiredescent! 🙌 🍰 🍰 🥳 

The "Or, alternatively:..." text has been removed on QA. 👍 😄

**Comment by ophelieh** [comment]
Looks great! Thank you :)

**Comment by shaunxp20** [comment]
This one has been deployed, thanks everyone! 🙌 🥳
