### ISSUE TITLE
Bring Back the Demo Video [40,8,5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2739]
**Deliverables:**
- Bring back the Demo Video

**Notes:**
A spike with a bunch of research/notes was done in #2605. 

**Dev Notes:**

Revert these commits:
- #2256 demo video clearout
- #2253 remove demo video from admin/ra UI
- #2255 Remove demo video from judge screens
- #2254 remove demo video from student/mentor UI

## QA STEPS

I reverted the work that originally removed the demo video, and from what I can tell everything is working as it should; but I'm not sure how it looked/functioned before, so that's really what needs to be verified. 😃 

As a student:
* Verify the demo video section for the team's submission is looking/working as expected

As a judge:
* Judge a submission, and verify the demo video is looking/working as expected

As an admin:
* View details for a submission, and verify the demo video is looking/working as expected
* make sure it shows up in submission exports for admins

**Comment by rsgonzal** [comment]
- Demo video will be required
- We've discussed that deleting old submissions in ok

**Comment by shaunxp20** [comment]
This one is on QA, and some QA steps have been added as well. 😄 🍨 😋  I also added #2794 to delete the old submissions. 😁

**Comment by ksrebecca** [comment]
Did QA and I *think* it's working as expected??

**As a student**
I could see both the pitch and demo videos and both worked 👍 
https://share.getcloudapp.com/z8uYzYZ2

**As a judge**
I could see the links to both videos and each popped to the front in a mini player (not together), which works for me
https://share.getcloudapp.com/YEuyxyDN
https://share.getcloudapp.com/P8uyByDq

**As an admin**
View details for a submission, and verify the demo video is looking/working as expected

- Looks good to me, the links are there and they work but not in a mini player, they pop out to original link (eg YouTube). Did there used to be a mini player there too? Just curious! Not necessary though.
https://share.getcloudapp.com/yAulOlNQ

make sure it shows up in submission exports for admins

- Yep, showed up and was correct!
https://share.getcloudapp.com/jkuD5DzZ

**Comment by ophelieh** [comment]
**As admin** (with submission on and with submission off): 
* I can see the space for demo video when going to submission detail
* I could add the demo video link to my export. Export worked as expected

Note: Progress for submission still showed 100% even though the submission was missing the demo video. 

**As a student**: 
* Demo video showed on the submission tab on my dashboard
* Demo video showed on "My team's submission" page
*I was able to add and edit my link 
--- Everything worked as expected during submission. --- 
* when scores and certificates are on --- it shows the link to my "demo video" but there is none so it just showed me an error message (see the screenshot shared under judge) 

Side note: on "My team's submission page" is should now say "2 or more images" not screenshots 
![Screen Shot 2020-11-12 at 3 57 27 PM (2)](https://user-images.githubusercontent.com/32206421/99001196-0cce3380-2500-11eb-84db-53782e4d4cb6.png)

As a judge (with QF on): 
* Worked as expected, I was able to see and watch the demo video for the team "Down with Carol Baskins". It showed and worked under every part (ideation, technical...) 
* A team without demo video popped up next and the pop-up screen said "Your video link is broken. [...]" -- language should be changed for videos that don't work 
![Screen Shot 2020-11-12 at 4 13 51 PM](https://user-images.githubusercontent.com/32206421/99002470-0e98f680-2502-11eb-915c-fa87da7848f6.png)

**Comment by shaunxp20** [comment]
I created some new tickets (#2800 for updating screenshots, #2801 for the missing video error message, and #2802 for the progress bar).

Regarding the error message, I see that the demo videos are supposed to be required:
> Demo video will be required

If that's the case, we won't need #2801, I'll also have to make the changes to make this happen. 😃
