### ISSUE TITLE
Bug: Consent link in Mentor Email says invalid token when clicked [8,8,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2741]
Number 6 in mentor welcome email takes you to a broken page whether logged in or not
![Screen Shot 2020-10-08 at 10 57 13 AM](https://user-images.githubusercontent.com/22801026/95496062-25718980-0955-11eb-92d0-43fba0a66e5d.png)

![Screen Shot 2020-10-08 at 10 26 34 AM](https://user-images.githubusercontent.com/22801026/95493567-78e1d880-0951-11eb-9aba-99f1dadab773.png)

![Screen Shot 2020-10-08 at 10 27 30 AM](https://user-images.githubusercontent.com/22801026/95493562-77181500-0951-11eb-9b11-49439bd3ed99.png)

link: `https://mandrillapp.com/track/click/30787762/technovation-qa.herokuapp.com?p=eyJzIjoiTW9nWV84QVJsb0hINVd1ZGlqb3RCWldXWmZZIiwidiI6MSwicCI6IntcInVcIjozMDc4Nzc2MixcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RlY2hub3ZhdGlvbi1xYS5oZXJva3VhcHAuY29tXFxcL2NvbnNlbnRfd2FpdmVyc1xcXC9uZXc_bWFpbGVyX3Rva2VuPVBjVEZLQ3BpNEQ1djQxdUx4cEFmV3h6b1wiLFwiaWRcIjpcIjE1ODk0NjFjYzAyOTQ5ZmM5OWZjNTU3MTRmNDUzZjg2XCIsXCJ1cmxfaWRzXCI6W1wiODUyYjZkYmU5ZjhmZjAyMDI0N2RmYTZlM2UxZWFkMmY3OTE4NTg4NVwiXX0ifQ`

## QA suggestion

**Works when signed in**
1. sign up as a mentor
2. receive the welcome email
3. making sure you're **logged in** as the mentor, click the consent form link
4. sign the consent form

**Works when signed out**
1. sign up as a mentor
2. receive the welcome email
3. making sure to **log out** first, click the consent form link
4. make sure you're taken to the consent form, and automatically logged in
5. sign the consent form

(~10 min)

**Comment by hellafitz** [comment]
Steps to Reproduce:
- sign up as a new mentor
- get a mentor welcome email 
- click step #6

Open Q: does this happen to returning Mentors too? We expect it does (if they get the Welcome email). If so, fixing that is also in scope.

**Comment by rsgonzal** [comment]
Looks great!! Love the auto sign in

**Comment by mdancho** [comment]
Logged in: I am brought to the dashboard as seen below. 
![Uploading Screen Shot 2020-10-29 at 11.03.03 AM.png…]()

**Comment by mdancho** [comment]
When signed out I am brought to the sign -in page - I still see the consent token invalid pop-up in both scenarios. 
![Uploading Screen Shot 2020-10-29 at 11.05.15 AM.png…]()

**Comment by mdancho** [comment]
Confirming that the 6th line in the welcome email brings you to the consent waiver when you are signed in, and when signed out. 
<img width="1332" alt="Screen Shot 2020-10-30 at 8 54 07 AM" src="https://user-images.githubusercontent.com/52216992/97727455-a7a12980-1a8d-11eb-9cf6-4f81aa48f37c.png">
<img width="1287" alt="Screen Shot 2020-10-30 at 8 54 25 AM" src="https://user-images.githubusercontent.com/52216992/97727462-ab34b080-1a8d-11eb-8775-60efa7a56269.png">
