### ISSUE TITLE
Reset the platform for pre-surveys & configure [20,3,6.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2751]
Pre-surveys for the 2021 season are ready to go on the site

- Need to reset the platform so that returning users are able to see the survey
Documentation [here](https://docs.google.com/document/d/1hVaugqKipnD8pYmCcMl5KWCHrrqBBSr-86MQZTdm5P8/edit?disco=AAAAHHPyLe8)

- Configure surveys (rox)
students
Take the Technovation Pre-Survey to help improve the program!
https://www.surveymonkey.com/r/FH68R7F?name=[name_value]&school=[school_value]&city=[city_value]&state=[state_value]&country=[country_value]&email=[email_value]&team=[team_value]&age=[age_value]&uid=[uid_value]
Help us improve our program, for you and future participants, by taking our survey.
mentors
Take the Technovation Pre-Survey to help improve the program!
https://www.surveymonkey.com/r/VJ3SSLY?email=[email_value]&country=[country_value]&state=[state_value]&name=[name_value]&city=[city_value]&company=[company_value]&team=[team_value]&uid=[uid_value]&age=[age_value]
Help us improve our program, for you and future participants, by taking our survey.

**Comment by hellafitz** [comment]
Steps: 
1) Dev: reset platform
2) Rox: put in the new surveys

**Comment by stenington** [comment]
@rsgonzal Pop ups have been reset for students and mentors on production, feel free to configure surveys!

**Comment by rsgonzal** [comment]
thanks, mike! jjust configured
