### ISSUE TITLE
Add how-to video to student resource drop down menu [8,3,2.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2760]
The team made a video to help students get started and they want to add it to the menu

(still need to confirm)
- add to the top
- Content:
How to Use This Website
WATCH A VIDEO TUTORIAL 
-link: https://youtu.be/KoWkYNXTr2w
![Screen Shot 2020-10-15 at 10 01 02 AM](https://user-images.githubusercontent.com/22801026/96752744-c0ba2400-1383-11eb-8575-c635ec10c1cd.png)

## QA

1. log in as a student
2. confirm new link in menu
3. confirm the youtube video is viewable even if you're not logged in to your technovation account

(~5 mins)

**Comment by hellafitz** [comment]
@ksrebecca please take a look and provide any comments and/or final approval

**Comment by ksrebecca** [comment]
Yes! Approved :)

**Comment by rsgonzal** [comment]
This looks good to me! Opened the youtube vid in incognito.

**Comment by ophelieh** [comment]
This works as expected, but it's not necessarily intuitive to go to "more information" and then get the video... Could we change the title from "More Information" to "All you need to know" or something that makes it more intuitive? And/or maybe have the video somewhere else like in the profile section or build your team so it can be easily found?

**Comment by rsgonzal** [comment]
thanks @ophelieh ! 
- i added the potential change to the drop down title to our product notes to discuss
- we've discussed potentially adding the video somewhere else, but haven't found quite the right spot yet!

**Comment by ophelieh** [comment]
Awesome. Thanks Roxana!

**Comment by ksrebecca** [comment]
Also QAed and it's looking good. Can't wait for that popup someday 😜

**Comment by kate-technovation** [comment]
Hooray! Looks great.
1. Confirmed logged in as a student
2. Confirmed new link in menu:
<img width="1077" alt="Screen Shot 2020-10-30 at 7 04 04 PM" src="https://user-images.githubusercontent.com/57409606/97763712-d1387000-1ae2-11eb-9c97-23546e2c4c95.png">

3. Confirmed the YouTube video is viewable even when not logged in to my personal account:
![Uploading Screen Shot 2020-10-30 at 7.04.16 PM.png…]()

**Comment by hellafitz** [comment]
I made #2780 for the dropdown title and content updates
