### ISSUE TITLE
Add last name to mentors under invite & request section [8,3,2.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2765]
![Screen Shot 2020-10-21 at 1 22 36 PM](https://user-images.githubusercontent.com/22801026/96778421-890da500-13a0-11eb-8b05-26d69bbf70fa.png)

## To Do:
- Add mentor last name when displaying mentor name on the "My Team" -> "Mentors" page

## QA Steps:

As a student, navigate to: "My Team" -> "Mentors":
- Ensure the "Invites sent" section is showing last names
- Ensure the "Requests from others" section is showing last names

<10 mins

Note: the invite/request section is shared, so the last names will be displayed for the "My Teams" -> "Students" section too; I can change this if that's not desired.

**Comment by rsgonzal** [comment]
![Screen Shot 2020-10-21 at 1 22 36 PM](https://user-images.githubusercontent.com/22801026/96778421-890da500-13a0-11eb-8b05-26d69bbf70fa.png)

**Comment by hellafitz** [comment]
next step: confirm w/ PT and CET there isn't some hidden reason why we hide this info

**Comment by rsgonzal** [comment]
From TF/TG notes:
Q: Mentor last names not shown on invites and requests. Does anyone know if there’s a reason for this?
- A: I think it was due to privacy reasons… in case a student will “stalk” the mentor :) 
-Once they’re matched they should be able to see full mentor names (if they can’t already)
-There have been some cases of students harassing unmatched mentors in the past
- Decision: ok to proceed adding last name (per Amy), but need to prepare for some students bothering mentors

**Comment by hellafitz** [comment]
Showing mentor last names has been discussed and approved by A/B/R

**Comment by hellafitz** [comment]
Noting that - as of my initial investigation - we're not currently showing mentor name at all to Students on the request/profile screen they access from the request email.

**Comment by hellafitz** [comment]
@rsgonzal to confirm what's visible from the email

**Comment by rsgonzal** [comment]
It's not seen on the email
![Screen Shot 2020-12-02 at 8 12 41 AM](https://user-images.githubusercontent.com/22801026/100899091-51e9e380-3476-11eb-83f7-ba67d4b40d6e.png)

But you can see last name when you click on the invite from the email

![screencapture-technovation-qa-herokuapp-student-join-requests-n2sbg5iPHxvA2X1B4RkP64dD-2020-12-02-08_12_24](https://user-images.githubusercontent.com/22801026/100899142-5c0be200-3476-11eb-82e6-1d5e82f9c807.png)

**Comment by hellafitz** [comment]
Decision: 
- add mentor last name to the MyTeam/Mentors page
- leave the email alone for now (progression from first name only in the notification email, to the full name being visible on click-through is fine).

**Comment by shaunxp20** [comment]
This one is on QA, some QA steps have been added too. 👍 😄 ☃️

**Comment by kate-technovation** [comment]
As a student, navigated to: "My Team" -> "Mentors", and ensure that the "Invites sent" section and the "Requests from others" section are showing last names:

<img width="753" alt="Screen Shot 2021-02-01 at 1 48 23 PM" src="https://user-images.githubusercontent.com/57409606/106503835-285c3100-6494-11eb-81ca-523dfd3d009a.png">

**Comment by rsgonzal** [comment]
thanks, @kate-technovation !
