### ISSUE TITLE
Bug: Error updating email in profiles [20,5,4]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2766]
When a mentor updates their email address, it causes an error.

## Steps to reproduce
1. Log in as a mentor
2. Click "My Profile"
3. Click "Change Email"
4. Enter a new email address and submit the form

It will cause a blank screen on QA, and this error (not visible to the mentor):
```
ActionController::UnknownFormat (ActionController::UnknownFormat):

app/controllers/concerns/profile_controller.rb:22:in `update'
```

**Todo:**
- [x] See if this affects other other account types -> **it does**

**Dev notes:**
`app/views/profiles/_email.en.html.erb`
`<%= simple_form_for current_profile, local: true, url: [current_scope, :profile] do |f| %>`

## QA STEPS

- Update a student/mentor/judge email address by going to "My Profile" -> "Change Email"
- Submit the form, and it should be successful; it shouldn't show an error screen, as shown in this comment: https://github.com/Iridescent-CM/technovation-app/issues/2766#issuecomment-722626110

**Comment by rsgonzal** [comment]
Weird, you get the error screen but it does change your email. Could be very confusing.

**Comment by rsgonzal** [comment]
![Screen Shot 2020-11-05 at 12 29 01 PM](https://user-images.githubusercontent.com/22801026/98293054-8bf0c400-1f62-11eb-862d-23f058db774f.png)

**Comment by shaunxp20** [comment]
This one is on QA, and some QA steps have been added too! 👍 😃

**Comment by mdancho** [comment]
Was able to edit the email with a judge account and received a verification email. 
<img width="1151" alt="Screen Shot 2020-11-13 at 3 20 24 PM" src="https://user-images.githubusercontent.com/52216992/99130057-26d14a00-25c4-11eb-8ec9-ca687060ee35.png">

Same for mentor and student.

**Comment by rsgonzal** [comment]
this is working as expected!
