### ISSUE TITLE
Bug: Join requests sent to teams without spots available don't work [13,8,1.63]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2769]
A specific instance of #2662.

**Describe the bug**
If you have a team without a spot available (i.e. it has 5 members/invites/join requests already) and someone requests to join that team, you're able to accept that invitation and go through what looks like the correct acceptance flow, except at the end the requestor **will not be on the team**.

Attempting to accept a second time will say that the request was already accepted.

**To Reproduce**
1. Find the name of a "full" team
2. As a student not on a team, request to join it
3. As a member of the team, accept the request
4. After accepting, the requestor will not be on your team.
5. Logging in as the requestor, you will not be on a team.

**Expected behavior**

- You should not be able to request to join a full team (where "full" means requests + invites + current members)
- In the search results, the team should still show up
- In team profile, it should say the team is currently full and 'request to join' button should appear but be grey and inactive (this is for communication sake, in case a team told someone to find them, they can go back and tell them to clear their requests)

## QA STEPS
* Create a full team (full being current students on team + invites + requests)
* As another student, search for this team, in the search results verify the message and the button is disabled for this team

**Comment by rsgonzal** [comment]
More info:
- Say a 6th person requests to join the team, if I try to accept the request of the 5th person it still doesn't honor it. So if there are over five requests/invites members, it won't honor any accepted members until you have five again

My opinion - the requestor shouldn't be able to request to join a full team, but we can ask during tf/tg

**Comment by rsgonzal** [comment]
Decision: 

- You should not be able to request to join a full team
- In the search results, the team should still show up but it should say the team is currently full
- This is for communication in case a team told someone to find them, they can go back and tell them to clear their requests

**Comment by rsgonzal** [comment]
![Screen Shot 2020-11-05 at 12 44 53 PM](https://user-images.githubusercontent.com/22801026/98294537-f9055900-1f64-11eb-83b2-2be971f2ad99.png)

**Comment by kate-technovation** [comment]
1. Created  a full team:
<img width="574" alt="Screen Shot 2020-11-23 at 1 43 20 PM" src="https://user-images.githubusercontent.com/57409606/100001928-dad78f80-2d91-11eb-9820-a28b9794e978.png">

2. As another student, searched for this team, and verified in the search results that button is disabled for this team:
<img width="535" alt="Screen Shot 2020-11-23 at 1 45 11 PM" src="https://user-images.githubusercontent.com/57409606/100002160-2c801a00-2d92-11eb-97ee-935e1afdd4bf.png">

**Comment by mdancho** [comment]
Looks good! Searched for a full team and could not join. 
<img width="367" alt="Screen Shot 2020-11-23 at 5 51 48 PM" src="https://user-images.githubusercontent.com/52216992/100036253-ba6cfc80-2db4-11eb-881a-5664d1d17a63.png">

Also tried to add a 6th team member and could not do so. 
![Uploading Screen Shot 2020-11-23 at 5.23.59 PM.png…]()

**Comment by rsgonzal** [comment]
Woo thanks! Looks good to me!

**Comment by shaunxp20** [comment]
Thank you for looking at this one, @kate-technovation @mdancho @rsgonzal 🙌 🍨 🍰 🍹 🎉
