### ISSUE TITLE
Change Config to allow mentors and judges to toggle back between profiles [?,?,?]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2770]
The team decided they will allow mentor to be judges for this season. 

#2423 introduced configuration to hide the link to switch between profiles.

`ENABLE_SWITCH_BETWEEN_JUDGE_AND_MENTOR`

I am turning it on in staging to test with the team

**Comment by rsgonzal** [comment]
Ideas for testing
- sign up as just a mentor and switch to judge
- sign up as just a judge and switch to mentor
- look at existing judges from past seasons and test
- look at existing mentors
- make sure mentors can still do everything mentors should do

**Comment by ophelieh** [comment]
Signed in as Alan Parker who is a returning judge (from 2019), but not a mentor. When I tried the "switch to mentor mode" it brought me to an error page.

![Screen Shot 2020-10-26 at 4 38 28 PM (2)](https://user-images.githubusercontent.com/32206421/97231606-b21ba480-17a9-11eb-81bf-25b320551cb8.png)

Logged in as Jennifer Marie, a mentor who has also been a judge but not in the 2020 season. It brings me to the mentor page. I can switch between profiles no problem.

**Comment by rsgonzal** [comment]
- signed up as a new judge and i was able to convert
- logged in as a 2019 judge without a mentor profile prior and was able to convert
- signed up as a new mentor and was able to switch
