### ISSUE TITLE
Bug: Updated country information is not being passed to Mailchimp [5,5,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2779]
When country is updated, it doesn't automatically tell mailchimp. 

I think this is only really a problem for judges cause i guess the way we collect location is after info has already been given to mailchimp

> Regarding country, afaict, that looks like a bug, I see in the code that "if country is changed, update Mailchimp", but obviously it's not working. If it's a show stopper I can keep trying to debug or we could open a bug ticket for it to work on later. Thoughts? 🤔

I'll open up a new bug ticket since it's only affecting judges! judges shouldn't be signing up until later this year. there may be some mentor/judges that get populated. I'm not actually sure how those get sent to mailchimp. Maybe i'll test it out too. Either way i'll add to our tf/tg notes so that people are aware.

_Originally posted by @rsgonzal in https://github.com/Iridescent-CM/technovation-app/issues/2710#issuecomment-718990295_

**Dev notes:**
I think moving `update_email_list` to an `after_commit` hook in `account.rb` should work, needs testing to confirm all the different scenarios.

### QA
- Sign up as a judge
- Check Mailchimp list to see if country information is shared

**Comment by hellafitz** [comment]
@bagomer when do you expect judges to start signing up? We want to fix this before then. Thanks!

**Comment by bagomer** [comment]
Judge registration opens on March 29th.

**Comment by rsgonzal** [comment]
Looks like it updated when I entered my country!

**Comment by shaunxp20** [comment]
> Looks like it updated when I entered my country!

This one was also tricky, if you have some extra time, I think this one could also be tested w/ different scenarios - like a new account, and updating other fields; making sure the appropriate fields make it to Mailchimp.

**Comment by rsgonzal** [comment]
Perfect! I had used a new account and just tried to update all the other fields. Things look good.

**Comment by shaunxp20** [comment]
> Perfect! I had used a new account and just tried to update all the other fields. Things look good.

Great, thank you! 🙌 🎉

**Comment by mjaris** [comment]
I also just created a new account and updated the country after registering — it worked!

**Comment by shaunxp20** [comment]
> I also just created a new account and updated the country after registering — it worked!

Awesome, thanks for verifying this Maggie! 👍 🎉 🙌
