### ISSUE TITLE
Downgrade TF database

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2782]
TF is currently on the $200.00 (premium) plan for the PostgreSQL add-on.

For reference, TG is on the $50 (standard) plan. For database size reference TG is 595.7 MB and TF is 362.4 MB.

**Action:**
Downgrade TF to the $50 (standard) plan.

- [x] Make a fresh backup of TF
- [x] Downgrade database

**Dev notes:**
`$ heroku addons:upgrade HEROKU_POSTGRESQL_TEAL_URL heroku-postgresql:standard-0 --app curiositymachine`
[https://devcenter.heroku.com/articles/updating-heroku-postgres-databases#updating-with-addons-upgrade](https://devcenter.heroku.com/articles/updating-heroku-postgres-databases#updating-with-addons-upgrade)

```
$ heroku maintenance:on --app curiositymachine
$ heroku pg:maintenance:run TEAL --app curiositymachine
$ heroku maintenance:off --app curiositymachine
```

[https://devcenter.heroku.com/articles/heroku-postgres-maintenance#with-maintenance-mode-enabled](https://devcenter.heroku.com/articles/heroku-postgres-maintenance#with-maintenance-mode-enabled)

**Comment by hellafitz** [comment]
@stenington can you see if you're able to give Shaun's account permissions so he can proceed?

**Comment by stenington** [comment]
Nope, only the owner has permissions. The commands need to be run user the owner account, which can be managed in the toolbelt with `heroku auth:logout` and `heroku auth:login`.

**Comment by shaunxp20** [comment]
Cool, that makes sense, thanks Mike, I can take a look later today after planning.

**Comment by shaunxp20** [comment]
This looks good to me! 🙌 

```
$ heroku pg:maintenance:run TEAL --app curiositymachine
Starting maintenance for postgresql-acute-42644... Maintenance triggered
```

Email confirmations:
> Your high-availability standby TEAL on curiositymachine has been promoted and unfollowed. A new high-availability standby will be launched as soon as possible.
>
> Any followers of your database (TEAL on curiositymachine) will be repointed and might be restarted, to properly follow your new leader.

> Maintenance on your database postgresql-acute-xxxxx standard-0 (TEAL on curiositymachine) has been completed and your database is now back online.
