### ISSUE TITLE
Redesign of MyTeam/ Mentors [20,8,2.5]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2783]
Make the Mentors page of MyTeam more understandable - particularly for managing Mentor invitations and requests - and surface the search visibility features to users on a team. Screenshot below is from https://projects.invisionapp.com/freehand/document/OyNBmSwOk

![Screen Shot 2020-10-30 at 11 58 52 AM](https://user-images.githubusercontent.com/6475595/97746454-936a2600-1aa7-11eb-9c62-76029cab1047.png)

## QA STEPS/SCENARIOS
As a student:
* view the My Team -> Mentors page
* verify the content looks good, ideally with and without invites and requests
* also verify the content looks good when the "team building" admin setting is disabled

As a chapter ambassador or admin (they both should see the same thing):
* find/view a team, and click mentors in the sidebar (this page is the one as above)
* verify the content looks good

**Comment by hellafitz** [comment]
approved by TF/TG crew

**Comment by stenington** [comment]
This is my understanding of what the mentor tab should look like after this ticket, if it were to have one mentor, one pending request, and a pending invite:

<img width="842" alt="Screen Shot 2020-11-06 at 2 13 31 PM" src="https://user-images.githubusercontent.com/55319/98405517-60d9a380-203a-11eb-9fd8-a3b5e31a2469.png">

**Comment by stenington** [comment]
This is with no invites or requests:
<img width="842" alt="Screen Shot 2020-11-06 at 2 16 11 PM" src="https://user-images.githubusercontent.com/55319/98405666-a6966c00-203a-11eb-9be1-75d48e8d79ed.png">

**Comment by stenington** [comment]
Here with no mentors, either: 
<img width="842" alt="Screen Shot 2020-11-06 at 2 17 21 PM" src="https://user-images.githubusercontent.com/55319/98406055-46ec9080-203b-11eb-8e6c-86a27511097c.png">

**Comment by shaunxp20** [comment]
This one is on the QA site, ready for a first pass, some QA steps have been added too! 😄  🏭 🔧 🧑‍🏭

**Comment by kate-technovation** [comment]
As a student:
1. Viewed the My Team -> Mentors page:

<img width="864" alt="Screen Shot 2021-01-08 at 4 39 23 PM" src="https://user-images.githubusercontent.com/57409606/104067103-89b01d80-51d0-11eb-9ced-1a0763127fb2.png">

2. Verified the content looks mostly good, with and without invites and requests, BUT just wanted to highlight some differences between what I saw on my page versus noted in your screenshot (e.g. using the term "people" instead of "teammate" or "Mentors" and a missing last name:
<img width="875" alt="Screen Shot 2021-01-08 at 4 42 38 PM" src="https://user-images.githubusercontent.com/57409606/104067355-03e0a200-51d1-11eb-81c0-42227393608f.png">

3. Did not verify that the content looks good when the "team building" admin setting is disabled--pending confirmation from team that it's okay to adjust this setting.

Will test from Admin view later.

**Comment by shaunxp20** [comment]
Thanks for taking a look, Kate! ☕ 🍰 🙌  Good catches on the text differences. 🏆 🎉 

> Verified the content looks mostly good, with and without invites and requests, BUT just wanted to highlight some differences between what I saw on my page versus noted in your screenshot (e.g. using the term "people" instead of "teammate" or "Mentors" and a missing last name:
<img width="875" alt="Screen Shot 2021-01-08 at 4 42 38 PM" src="https://user-images.githubusercontent.com/57409606/104067355-03e0a200-51d1-11eb-81c0-42227393608f.png">

Regarding the "student" text in the screenshot, let me know if that should be "teammate" or "student teammate" or what it should be. @rsgonzal @hellafitz 

Regarding "people" vs "mentors", the place where this text would need to be updated is in a shared template (that both the mentor's page and the student's page use), it can be updated of course, it would just be a bit more difficult than changing some text. Let me know if you want that text dynamic or if it's okay as "people". @rsgonzal @hellafitz 

And the missing last name will be done in #2765 @kate-technovation

**Comment by rsgonzal** [comment]
Thanks @kate-technovation ! I think that wording is intentional. It says student because it is student vs mentor, so it takes you to the student screen. I think this is ok.

And I would say people is fine, unless there is another suggestion.

**Comment by shaunxp20** [comment]
> Disabled admin setting "FORMING TEAMS ALLOWED" but saw no difference in page:

Hmm, I tested this locally (turning off "Forming teams allowed" in the admin), and it seems to work okay (not being able to invite/approve/decline mentors):

![forrming-teams-disabled](https://user-images.githubusercontent.com/58957909/104374960-8abbb480-551a-11eb-8ddf-913f6e79bda1.png)

----

I'm about to make a change though (adding a header to that section, and styling the message) to make it more consistent w/ the My Team -> Students page. 👍

**Comment by shaunxp20** [comment]
> I'm about to make a change though (adding a header to that section, and styling the message) to make it more consistent w/ the My Team -> Students page. 👍

Just fyi, these small formatting changes are on QA now. 👍

**Comment by rsgonzal** [comment]
These look great! Only thing to note is that admin & chas actually don't see the invite & requests section like above. They see the requests with the IDs and the invites are missing (I think it's always been like this)

**Comment by rsgonzal** [comment]
And the whole section went away with team building off, which i kind of prefer this to the way the students work. On that page, team building off doesn't let you add more students but does let you approve/decline. We never have it where that is just off, it usually goes with the opening of judging and that's when the page doesn't let you approve/decline but still shows pending. Just noting thoughts!

![Screen Shot 2021-01-13 at 10 24 50 AM](https://user-images.githubusercontent.com/22801026/104493465-ee30fb00-5589-11eb-8cbc-bc2a9bce3785.png)

**Comment by shaunxp20** [comment]
> And the whole section went away with team building off, which i kind of prefer this to the way the students work. On that page, team building off doesn't let you add more students but does let you approve/decline. We never have it where that is just off, it usually goes with the opening of judging and that's when the page doesn't let you approve/decline but still shows pending. Just noting thoughts!

Ah, I just looked at this again, I see what you mean. We can definitely make the students page consistent w/ the mentors one (or vice versa). 👍 😄
