### ISSUE TITLE
Redesign of 'Add a Mentor' screen on Team-building dashboard [20,13,1.54] -> [20,8,2.5]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2784]
See link for existing design patterns and contextual layouts: https://projects.invisionapp.com/freehand/document/oszw8PxUy

OUTLINE:

[h1] Mentor Status

- Your team has # mentor(s). You can have more than one.

- Your team does not have a Mentor. 91% of teams that complete the program have at least one mentor on their team. 

[h1] Find a Mentor to invite to your team

- Search for a mentor to invite [mentor search]

- Your Mentor invitations (status of invitations)

-- your team is awaiting a response from # mentor invite(s)

[button to MyTeam/Mentors]

-- your team has no open invites to a Mentor    

[h1] Decide if Mentors (who ask) can join your team

- Make your team appear in search results 

[manage search settings]

- Respond to Mentor requests to join your team

-- you have # mentor request(s) waiting for you and your team members 

[button to MyTeam/Mentors]

NOTE: the platform currently makes a new set of buttons for every profile type associated with a participant account; so if we have live, un-deleted student/mentor accounts they may make this behave strangely.

![Screen Shot 2020-10-30 at 1 02 55 PM](https://user-images.githubusercontent.com/6475595/97751901-53f40780-1ab0-11eb-9eda-a009f5a1b593.png)

**Comment by hellafitz** [comment]
We believe this ticket removes the need for #1908 but keep an eye out for that issue popping up.

**Comment by hellafitz** [comment]
@rsgonzal let's pull the mentor view of this and determine if updates are needed

**Comment by shaunxp20** [comment]
This one is on the QA site, ready for a round of feedback/QA!

**Comment by ophelieh** [comment]
Mentor Status - the status changes as expected.
Find a mentor - works as expected. Text changes based on having pending invite or none. 

Note - We should remove the age for students who are now mentors. 
![Screen Shot 2021-01-12 at 10 57 22 AM (2)](https://user-images.githubusercontent.com/32206421/104346379-f5da9c00-54c4-11eb-9ac4-e72ec92c221d.png)

Decide if mentors can join your team - works as expected.

**Comment by rsgonzal** [comment]
thanks @ophelieh ! Hoping the ages go away when we do #2354

**Comment by rsgonzal** [comment]
Looks good to me! I never noticed the side bar unchecks the add a mentor t your team box when things are pending. That's cool!

**Comment by rsgonzal** [comment]
> We believe this ticket removes the need for #1908 but keep an eye out for that issue popping up.

Reminder to check on this when it deploys! Found a random one on production

![Screen Shot 2021-01-13 at 10 41 49 AM](https://user-images.githubusercontent.com/22801026/104494962-0144ca80-558c-11eb-8157-a1b10b02996e.png)
