### ISSUE TITLE
Update old support email address [5,3,1.6]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2785]
We have a few places in the app that don't look to the `HELP_EMAIL` config for the help email, and hard code help@technovationchallenge.org directly. We should update these spots to pull from config if possible, or to use the preferred support@technovation.org if not.

**Deliverables:**
- Update old support email address to be: `support@technovation.org`

**Dev notes:**

```
app/javascript/judge/scores/TeamInfo.vue
62:      return 'mailto:help@technovationchallenge.org?subject=' +

public/404.html
106:        <a href="mailto:help@technovationchallenge.org">help@technovationchallenge.org</a>.

public/500.html
106:        href="mailto:help@technovationchallenge.org">help@technovationchallenge.org</a>.</p>

public/422.html
105:        href="mailto:help@technovationchallenge.org">help@technovationchallenge.org</a>.</p>
```

## QA STEPS

Verify the links go to `support@technovation.org` on the following pages:
- https://technovation-qa.herokuapp.com/404.html
- https://technovation-qa.herokuapp.com/422.html
- https://technovation-qa.herokuapp.com/500.html

As a judge:
* Judge a submission, on the left side bar there should be some text that reads: "Complete as much of the score as you can and email us." Verify the "email us" link goes to `support@technovation.org`.

**Comment by shaunxp20** [comment]
This one is on QA, QA steps have been added too! 😸 👍

Side note: the links in the footer of our error pages go to: `iridescentlearning.org`. #just-fyi Let me know if those should be updated. 😄

**Comment by ophelieh** [comment]
All 3 error pages look good as well as the judge support link. 

Regarding the footer, I am not sure what is best for you as it seems to redirect to technovation.org. I vote for updating the link, but you guys know best.

Thank you!!

**Comment by shaunxp20** [comment]
Thanks for taking a look, Ophelie! 😄 🙌 

I updated the footer links to be `technovation.org` (it'll be on QA soon). 👍 😁

**Comment by rsgonzal** [comment]
Looks good! I think we had another ticket for those links. I'll tag you in it to see if it's done with your work here :)

**Comment by mdancho** [comment]
Confirming all 3 links have support@technovation.org hyperlinked for support. The judging page on the dashboard also has support@technovation.org hyperlinked on the left side for help.

**Comment by shaunxp20** [comment]
Great! Thanks for the QA effort everyone! 🍰 🍨 🍪 🙌
