### ISSUE TITLE
X Change text on more info tab for students & reorder dropdown [8?,x,x]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2788]
"More information" doesn't make a lot of sense for students. Team wants to change title and reorder/rename content.

Student's Name
Helpful Links

Using Your Dashboard
Watch this Video Guide

Safety Information
Stay Safe Online

Curriculum Lessons
Start your Learning Journey
 
Submission Guide
Check what your team needs to complete
 
Competition Judging Rubric
See how to earn points

Help Technovation improve!
Take the 20XX PXX-Survey

**Comment by hellafitz** [comment]
dupe with #2789
