### ISSUE TITLE
Delete old submissions [8,13,0.62]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2794]
From https://github.com/Iridescent-CM/technovation-app/issues/2739#issuecomment-705686589, we want to delete old submissions.

**Deliverable:**
- Remove old submissions

**To do:**
- Find out if there is documentation or an old ticket that can be referenced
- Find out if it's just the `team_submissions` table that needs to be deleted from or if there are other tables

**Comment by rsgonzal** [comment]
from #2605
> I would propose that PT/CET also needs to decide whether or not to delete old submissions. If the demo video is optional, it will just look like nobody in 2020 chose to submit one to a naive viewer, which maybe isn't a huge deal, but if it's required someone without context might wonder how all of our 2020 participants managed to get away without any demo videos if they were trying to look backwards and figure out something about the past.

**Comment by rsgonzal** [comment]
team doesn't look on the platform for old submissions, they have all of the backups themselves. Closing this one since it's not needed
