### ISSUE TITLE
Update "screenshots" to say "images" [5,5,1]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2800]
From #2739: 
> on "My team's submission page" is should now say "2 or more images" not screenshots

![Screen Shot 2020-11-12 at 3 57 27 PM (2)](https://user-images.githubusercontent.com/32206421/99001196-0cce3380-2500-11eb-84db-53782e4d4cb6.png)

## QA STEPS
As a student, click on "My Team's Submission":
* In the sidebar, click "Pitch", on this page , verify "screenshots" have been changed to "images"
* Verify the sidebar - it should say "2 or more images" instead of "2 of more screenshots"
* In the sidebar, click "2 or more images", on this page, verify "screenshots" have been changed to "images"

**Comment by shaunxp20** [comment]
This one is on QA, some QA steps have been added too. 👍 🌞 🏖️ 

Just a side note, I only updated the UI, there are still references of "screenshots" in the codebase:
```
331 matches
48 files contained matches
```

I think it's fine to leave these as is.

**Comment by rsgonzal** [comment]
Wooo. Thanks, shaun!

**Comment by ophelieh** [comment]
Everything looks good from the student and mentor side!
