### ISSUE TITLE
Update message judge sees when a submission doesn't have a demo video [5?,?,?]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2801]
From #2739:

> A team without demo video popped up next and the pop-up screen said "Your video link is broken. [...]" -- language should be changed for videos that don't work

![Screen Shot 2020-11-12 at 4 13 51 PM](https://user-images.githubusercontent.com/32206421/99002470-0e98f680-2502-11eb-915c-fa87da7848f6.png)

**To do:**
What should a judge see when a submission doesn't have a demo video?
- This video link is broken. Please email us.
-link for 'email' =support@technovation.org
- This will have to be a message only for judges, should not change what student says

**Comment by rsgonzal** [comment]
- Check to see if a broken pitch video link gives the same message

**Comment by rsgonzal** [comment]
Confirmed that it does give the same message

**Comment by hellafitz** [comment]
This ticket may be superfluous if video link validation is successful on the student side (#2573)

**Comment by hellafitz** [comment]
#2573 is completed so we're going to close this
