### ISSUE TITLE
Make demo video a part of the progress bar [20,13,6.67]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2802]
The demo video should be a part of the % complete on the progress bar.

**Comment by rsgonzal** [comment]
![Screen Shot 2020-11-23 at 9 20 07 AM](https://user-images.githubusercontent.com/22801026/99993900-27f53a80-2d6d-11eb-863d-5454bfc021f7.png)

**Comment by shaunxp20** [comment]
This one is on the QA site, QA steps for this one are in #2803.
