### ISSUE TITLE
Add functionality to permanently delete an account [8,3,2.67]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2808]
In the admin, when viewing a profile:
* add a new button next to the current delete button that will be for a hard-delete
* add a confirmation dialogue to the button

Button text:
* "Permanently delete [whole name] from Technovation Girls"

Update existing (soft-delete) button:
* "Remove [whole name] from Technovation Girls"

## QA STEPS
* As an admin, find an account/participant you want to delete
* Click the button to permanently delete them
* You can use this [dataclip](https://data.heroku.com/dataclips/yqfhgwxdgodytoutfxnxfugmdhvw) (which Rox might have to grant you access to) to verify they have been wiped from the database

< 10 mins

Note: the "remove" button is a soft-delete, the account will be removed from the app, but they will still exist in the database (just flagged as deleted); the "permanently delete" button will remove them from the app and the database

**Comment by hellafitz** [comment]
Decision: 
- go with Option 1. Put the new button (for a hard delete) next to the existing button (for a soft delete). 
- change the existing button text (see below)

Button text: 
- Existing button: "Remove [whole name] from Technovation Girls"
- New button: "Permanently delete [whole name] from Technovation Girls"

**Comment by shaunxp20** [comment]
This one is on QA, QA steps have been added too. 🌟 😄 🌟

**Comment by rsgonzal** [comment]
i also tried to create a new account with the email address of the student i deleted and it worked 👍

**Comment by kate-technovation** [comment]
As an admin:

1. Found an account/participant to delete:

<img width="598" alt="Screen Shot 2020-12-14 at 5 23 57 PM" src="https://user-images.githubusercontent.com/57409606/102142921-27face80-3e31-11eb-940a-70d7d178cece.png">

2. Clicked the button to permanently delete them
SCREENSHOT A:
<img width="430" alt="Screen Shot 2020-12-14 at 5 24 10 PM" src="https://user-images.githubusercontent.com/57409606/102143006-495bba80-3e31-11eb-933e-4f78b41962e3.png">

SCREENSHOT B:
<img width="607" alt="Screen Shot 2020-12-14 at 5 24 24 PM" src="https://user-images.githubusercontent.com/57409606/102143007-49f45100-3e31-11eb-8798-b2e7caadb542.png">

SCREENSHOT C:
<img width="402" alt="Screen Shot 2020-12-14 at 5 24 35 PM" src="https://user-images.githubusercontent.com/57409606/102142982-3ea12580-3e31-11eb-8da0-455916d2c359.png">

3. Once I have access to dataclip, will update

**Comment by rsgonzal** [comment]
thanks, kate! complicated one

**Comment by shaunxp20** [comment]
Thanks everyone for looking at this one! 🎈It's been deployed to production, and dev team is aware we still need to use this to delete a user. 👍
