### ISSUE TITLE
Edit text on search section of find mentor page [2,2,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2809]
Help text is currently different on the two search fields but they are saying the same thing

### TO DOs:
On both search by name and search by city, help text should say:
- Press enter/return after typing

![Screen Shot 2020-12-02 at 8 32 48 AM](https://user-images.githubusercontent.com/22801026/100901739-07b63180-3479-11eb-8784-0dc37507385a.png)

## QA STEPS

As  a student:
* Navigate to the "Search for Team Mentors" page (Dashboard -> "Build your Team" -> "Add a mentor to your team", then click button "Search for a mentor to invite")
* Verify the "Press enter/return after typing" text

**Comment by shaunxp20** [comment]
This one is on the QA site, some QA steps have been added too. 📃 ✍️  ✔️ 👍

**Comment by rsgonzal** [comment]
perfect!

**Comment by ophelieh** [comment]
As a student worked as expected. 

As a mentor, I tried to add more mentors to my team and got taken to the error page

![Screen Shot 2021-01-15 at 6 06 49 PM (2)](https://user-images.githubusercontent.com/32206421/104790181-7404a000-575c-11eb-8e8d-1b727d109af7.png)

![Screen Shot 2021-01-15 at 6 07 09 PM (2)](https://user-images.githubusercontent.com/32206421/104790200-7f57cb80-575c-11eb-82c1-9f61bdde3aee.png)

**Comment by rsgonzal** [comment]
@shaunxp20 actually Ophelie found a bug!

Mentors can not add other mentors to a team by searchning and inviting, but they can accept invitations.

**Comment by shaunxp20** [comment]
Good catch @ophelieh! Thanks for pointing this out @rsgonzal! I'll create a bug ticket, and get this fixed. 👍

**Comment by shaunxp20** [comment]
I added #2836 for this bug.

**Comment by rsgonzal** [comment]
thanks, @shaunxp20 ! we probably shouldn't deploy until this is fixed
