### ISSUE TITLE
Edit honor code [20,3,6.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2812]
Edit text on honor code

new text: https://docs.google.com/document/d/1IlH-SWCeESJdaBbUMUZgIzjWcADxZ-3QS-8IIsOSQKE/edit

## QA STEPS
* As a student (who hasn't started a submission yet), start a new submission
* After clicking the "Begin your submission" button, you should be taken to the honor code
* Verify the honor code is correct 😄 

< 5 mins

**Comment by shaunxp20** [comment]
This one is on QA, QA steps have been added too! 👍 😀 🌲🚶 🌞

**Comment by ksrebecca** [comment]
QA
Verified, it is the correct updated version. And I created a submission and reviewed the honor code when it appears right before submission too JUST in case, and it's also updated. Looks great!

**Comment by kate-technovation** [comment]
Tested as follows:

1. As a student (who hadn't started a submission yet), started a new submission:
<img width="620" alt="Screen Shot 2020-12-14 at 5 20 04 PM" src="https://user-images.githubusercontent.com/57409606/102142564-9be8a700-3e30-11eb-823c-5b232cadb114.png">

2. After clicking the "Begin your submission" button, was brought to the honor code:
<img width="620" alt="Screen Shot 2020-12-14 at 5 19 19 PM" src="https://user-images.githubusercontent.com/57409606/102142504-81aec900-3e30-11eb-948e-36d13784491f.png">

3. Verified the honor code is correct.

**Comment by rsgonzal** [comment]
Thank you!

**Comment by shaunxp20** [comment]
This has been deployed to production, thanks for testing everyone! 🍰 ☕ 😁
