### ISSUE TITLE
Edit help text on Business plan [5,2,2.5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2813]
![Screen Shot 2020-12-02 at 8 50 58 AM](https://user-images.githubusercontent.com/22801026/100905504-00912280-347d-11eb-9a84-4166348cbd40.png)
- Sentence should say "_Submit your 5 to 10 page business plan as a **PDF file**._" 
- remove the two other sentences about doc files

## QA STEPS
* As a student in the senior division, start a new submission, click on the "Your business plan" link
* Verify the content on the page - "Submit your 5 to 10 page business plan as a PDF file."

<5 mins

**Comment by shaunxp20** [comment]
This one is on QA, QA steps have been added too! 👍 😄

**Comment by ophelieh** [comment]
Updated text looks great. I am still able to upload a .docx instead of a PDF though.

**Comment by mdancho** [comment]
Verified that the text says "Submit your 5 to 10 page business plan as a PDF file."
<img width="662" alt="Screen Shot 2020-12-14 at 3 47 22 PM" src="https://user-images.githubusercontent.com/52216992/102133902-ac862680-3e0a-11eb-80f4-42e1f156878a.png">

**Comment by rsgonzal** [comment]
Woo thanks! I have another ticket to look at restrictions @ophelieh

**Comment by shaunxp20** [comment]
Thanks everyone! This has been deployed to production! 👍 😁 

> Updated text looks great. I am still able to upload a .docx instead of a PDF though.
>> Woo thanks! I have another ticket to look at restrictions @ophelieh

Thanks @rsgonzal!
