### ISSUE TITLE
Delete E.Y. user data [13,3,4.33]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2815]
E.Y. is a 2018 mentor who has requested to have their data deleted. 

Deliverables
- hard delete E.Y. using the admin button (assign this to a non-Dev admin)
- delete the 25 deploy backups (so that in 7 days all EY data will be gone)
- document the steps for future user deletion requests
- notify Amy when E.Y. data is completely gone so they can be informed

Dev Notes:
- consider setting up a 30-day heroku backup

**Comment by hellafitz** [comment]
relevant Qs:
- how long are the daily database backups stored?
- what other season or user backups are stored in S3 or Heroku?

out of scope but this will inform: org protocols for using data (downloading it, storing it, deleting it)

**Comment by shaunxp20** [comment]
We have automatic daily backups:
```
=== Backup Schedules
DATABASE_URL: daily at 2:00 America/Los_Angeles
```

These backups are kept for for only seven days: https://devcenter.heroku.com/articles/heroku-postgres-backups#scheduled-backups-retention-limits

Part of our deploy process is to do a manual database backup, a maximum of 25 of those are stored: https://devcenter.heroku.com/articles/heroku-postgres-backups#manual-backup-retention-limits

I also see older backups in Heroku, but none are from 2018.

**Comment by rsgonzal** [comment]
EY has been permanently deleted from platform

**Comment by shaunxp20** [comment]
Just documenting that the backups we make during deployments have all been deleted. 👍

**Comment by rsgonzal** [comment]
thanks, shaun! letting Ophelie and Eren know he can be notified in ~5 days

**Comment by rsgonzal** [comment]
This should've been done on the 16th, emailed Eren to verify
