### ISSUE TITLE
Update title and text on Mentor dashboard dropdown [8,2,4]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2816]
Current dropdown menu:

<img width="424" alt="Screen Shot 2020-12-08 at 8 34 06 PM" src="https://user-images.githubusercontent.com/58957909/101571018-75a9ae00-39cf-11eb-86ee-f059f8794a6c.png">

- Change dropdown title to: HELPFUL LINKS

- Add items after Mentor Resources:

[Safety Information](https://www.technovation.org/safety/)
Stay Safe Online

[Mentor Guide](https://docs.google.com/document/d/1rqd8DB4e-JqPRIG-yrdqPT_8zECbyXnoR9njo7FwZ6Y/edit#heading=h.kxoc4txdn9x)
Read our Tips and Strategies

## QA STEPS
* Login as a mentor, verify the dropdown menu items and links are okay

**Comment by shaunxp20** [comment]
@bagomer When you get a moment, can you provide the content and ordering for the mentor dropdown?

**Comment by bagomer** [comment]
Here is what CET would like added to the mentor dropdown. Can these 2 please get added after Mentor Resources, thanks! :

- [Safety Information](https://www.technovation.org/safety/)
      Stay Safe Online

- [Mentor Guide](https://docs.google.com/document/d/1rqd8DB4e-JqPRIG-yrdqPT_8zECbyXnoR9njo7FwZ6Y/edit#heading=h.kxoc4txdn9x)
     Read our Tips and Strategies

**Comment by shaunxp20** [comment]
Btw, just fyi, I noticed that the student and mentor's safety links go to different pages

Student's link goes here:
https://iridescentlearning.org/internet-safety/

And the mentor's goes here:
https://www.technovation.org/safety/

**Comment by shaunxp20** [comment]
This one is on the QA site and ready for a looksie. 👣 🔍 🕵️‍♀️ 

One note, I updated some of the menu items to be consistent with newly updated student dashboard menu items:
Curriculum -> Curriculum Lessons
Judging Rubric -> Competition Judging Rubric
Help us improve! -> Help Technovation Improve!

Let me know if that's okay, I can easily revert or change that.

**Comment by kate-technovation** [comment]
1. Logged in as a mentor:
<img width="872" alt="Screen Shot 2021-01-08 at 4 41 16 PM" src="https://user-images.githubusercontent.com/57409606/104067004-5b324280-51d0-11eb-8b13-3cebf913bb2f.png">

2. Verified the dropdown menu items and links are okay:
<img width="864" alt="Screen Shot 2021-01-08 at 4 39 23 PM" src="https://user-images.githubusercontent.com/57409606/104066971-4c4b9000-51d0-11eb-8069-f8555758d618.png">

**Comment by ophelieh** [comment]
Logged in as a mentor, dropdown and text were updated. Everything worked as expected.

Note: Not sure if it's intended but the "Mentor Guide" link sends you to the second page of the document, not the first one. 
<img width="1440" alt="Screen Shot 2021-01-11 at 9 31 23 PM" src="https://user-images.githubusercontent.com/32206421/104265995-5d0c3800-5454-11eb-8440-76dcf16340c7.png">

**Comment by rsgonzal** [comment]
Thanks @ophelieh ! That is the link @bagomer gave us
