### ISSUE TITLE
Remove blue box from Thunkable upload page [8,1,8]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2817]
There is currently an article linked that doesn't exist

![Screen Shot 2020-12-15 at 9 26 44 AM](https://user-images.githubusercontent.com/22801026/102250017-e103ec00-3eb7-11eb-800d-3e72efc0b2ce.png)
https://iridescentsupport.zendesk.com/hc/en-us/articles/360046965014-Using-Thunkable-BEFORE-YOU-SUBMIT-please-do-this-

**To Do:**
* Remove the blue box and everything in it

## QA STEPS
* As a student, start a submission
* On the "Development platform" section/page, select Thunkable from the drop-down
* After selecting Thunkable, verify the blue box (from the screen shot) is no longer there

**Comment by hellafitz** [comment]
@ksrebecca 
Q1 - what's the correct, new link?
Q2 - what other changes may have happened on Thunkable that affect us for this season?

**Comment by ksrebecca** [comment]
Q1 - No special instructions required this year. Thunkable is now auto including API keys and passwords when sharing projects. Can entirely remove blue box (unless something crazy pops up later in the season...)
Q2 - Have not identified any yet, will alert if Nick and Mack spot anything as they create judging resources

**Comment by shaunxp20** [comment]
This one is on the QA site, some QA steps have been added too! 👍 😄 🌞

**Comment by rsgonzal** [comment]
opened #2825 since there is another place we link to the missing article

**Comment by ksrebecca** [comment]
QA
On a submission that was started from the Taco Belles the code was not added yet. Selected Thunkable and no blue box was present. Looks good.

BUT @rsgonzal I noticed another potential issue...  This year we did not have "Thunkable Classic" as an option... Is that easy to remove from the dropdown menu section? I doubt anybody will select it early in the season.

**Comment by mdancho** [comment]
Confirmed that the blue box does not appear when Thunkable is selected 
<img width="1233" alt="Screen Shot 2020-12-23 at 3 54 27 PM" src="https://user-images.githubusercontent.com/52216992/103036212-3898fc00-4537-11eb-97de-d57a74b51c9c.png">

**Comment by rsgonzal** [comment]
Thanks @ksrebecca ! i'll open another ticket to remove thunkable classic
