### ISSUE TITLE
Ongoing Support - it-38 [13,5,2.6]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2818]
Support for things that come up during this iteration.

**Comment by rsgonzal** [comment]
opened #2823 for bug on mentors joing full team

**Comment by shaunxp20** [comment]
Just tracking that another issue that came up is that we lost our `curiosity-machine` repo (b/c it was a fork and the main repo it was forked from was deleted). We spent a chunk of Wednesday, pretty much all of Thursday and some of Friday troubleshooting, investigating, emailing, etc. about how to get it back.

Anyhow, the repo is back now (and no longer a fork), but two issues have come up so far:
* the labels on `curiosity-machine` are gone, the tickets once marked as "Code review", "Done" or whatever, those labels are all gone now
* the circle-ci integration isn't working
