### ISSUE TITLE
Edit help text on submission pages [2,2,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2820]
**Screenshots (images) page**
![Screen Shot 2020-12-16 at 8 17 52 AM](https://user-images.githubusercontent.com/22801026/102375588-8c27aa80-3f77-11eb-81ab-601a7808db5d.png)

**New text**: Review the [submission guidelines](https://technovationchallenge.org/submission-guidelines/) for recommendations.
- link - https://technovationchallenge.org/submission-guidelines/

**Upload your source code page**
![Screen Shot 2020-12-16 at 8 27 15 AM](https://user-images.githubusercontent.com/22801026/102376480-89798500-3f78-11eb-9478-cede1a61977d.png)

**New Text**: Help for submitting your source code is [here](https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-) or take a look at the [debugging curriculum unit](https://technovationchallenge.org/curriculum/coding-14-debugging-tips-in-app-inventor-and-thunkable/) for more resources.
- 1st link: https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-
- 2nd link: https://technovationchallenge.org/curriculum/coding-14-debugging-tips-in-app-inventor-and-thunkable/

## QA STEPS
As a student:
* Navigate to "My Team's Submission" -> "2 or more screenshots" page
* Verify the content/link changes there
* Navigate to the "My Team's Submission" -> "Upload your source code" page
* Verify the content/link changes there

**Comment by shaunxp20** [comment]
This one is on the QA site, some QA steps have been added too. 🏁 🐢 🐇 🐰 🐌 🏁

**Comment by rsgonzal** [comment]
Woo. looks great!

**Comment by ksrebecca** [comment]
QA:
-2 or more screenshots page: Correctly updated!
-Source code pages: Was present in all except never appeared in Thunkable (because you never upload anything?) Might be helpful to add to the screen where they have to put their link in?

Also realized we still somehow have Thunkable Classic as an option for submitting in languages, can someone make sure there is a ticket to remove that 5th option please?
<img width="341" alt="Screen Shot 2021-01-15 at 11 57 43 AM" src="https://user-images.githubusercontent.com/43972336/104756011-6e856680-5718-11eb-8f8c-78fde8269858.png">

Thanks!

**Comment by rsgonzal** [comment]
@ksrebecca I don't understand your comment about Thunkable. If they select Thunkable, they are prompted for the url.

**Comment by ksrebecca** [comment]
Then we're good. I was just thinking that since the [article](https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-) we link to about source code shows what to look for in thunkable (how to get the link) that it could be helpful to have on that screen!

**Comment by rsgonzal** [comment]
Ah, so do you want it on this page @ksrebecca . Just let me know where and I can make a ticket!
![Screen Shot 2021-01-19 at 9 55 54 AM](https://user-images.githubusercontent.com/22801026/105073956-a05e3c00-5a3c-11eb-9edb-8c63bed6da9c.png)

**Comment by ksrebecca** [comment]
Yes! That page would be awesome 👯

**Comment by shaunxp20** [comment]
This one has been deployed! 🚀 Just checking, did we already make a ticket for the followup work? 🤔 😀

**Comment by rsgonzal** [comment]
noting i did add to #2825 :)
