### ISSUE TITLE
BUG: Mentor can not request to join a team that is full

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2823]
We know there is no mentor cap on teams and students can still add mentors to their teams even if they are full.

The issue we're seeing is that if a mentor searches for a team that has 5 mentors, they get the notice that the team is full and they can not join. This message should only be for students, not mentors

![Screen Shot 2020-12-22 at 3 21 16 PM](https://user-images.githubusercontent.com/22801026/102942255-b2fb4a80-4469-11eb-867a-346e083ef28d.png)

## QA STEPS
* Find a team that is full, make note of this team
* Find/login as a mentor that is on-boarded and not on a team
* From the mentor's dashboard, on the "Find your team" step, click the "Find a team button"
* Find the team from the first step, verify that you can click the "View more details" button and join this team

Also, it would be nice to try to join this same team as a student, and verify that the "View more details" button is disabled and the student can't join the team

**Comment by rsgonzal** [comment]
Think we might have broken with #2769

**Comment by shaunxp20** [comment]
> Think we might have broken with #2769

Doh! Yup, you're right, that's what did it! That disabled the button for both students and mentors. 🤦

**Comment by shaunxp20** [comment]
This one is the QA site, some QA steps have been added too, hopefully this fixes the issue! 🤞 😄

**Comment by mdancho** [comment]
As a mentor: 

1)Searched for Team Factset (has 5 pending student invites and 1 mentor) and confirm that I was able to send a request to join the team
2) Searched for Taco Belles ( 5 students onboarded, 1 mentor) and confirm I was able to send a request to join the team

**Comment by ksrebecca** [comment]
QA

As a mentor I could request to join full teams - Taco Belles and New Team. Then I signed in as mentors already on the teams and approved the requests with out a problem.

**Comment by rsgonzal** [comment]
Looking good. Was able to request to join. 

I also checked the bonus part as a student trying to join these teams and could not 👍

**Comment by shaunxp20** [comment]
Awesome! Thanks for testing this on such short notice everyone! 🙌 🎉 🎈🥇
