### ISSUE TITLE
Bug: when switching dev platform to thunkable, a previous uploaded source code is saved [3,5,0.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2826]
If I've previously uploaded a file under a different development platform and then decide to go with a thunkable project, my old source code is still saved on my submission

![Screen Shot 2020-12-23 at 12 21 02 PM](https://user-images.githubusercontent.com/22801026/103034524-ee555200-4519-11eb-9c8c-a24b382984d7.png)
![Screen Shot 2020-12-23 at 12 25 01 PM](https://user-images.githubusercontent.com/22801026/103034536-f2816f80-4519-11eb-9572-5e2e4f441762.png)

Probably an unlikely scenario, but worth checking out. How does this look on judging?

**Comment by hellafitz** [comment]
next step: @rsgonzal to check out how this looks on Judging

**Comment by rsgonzal** [comment]
A judge can only see thunkable project, so this doesn't look like a big issue for now
![Screen Shot 2021-03-17 at 12 22 07 AM](https://user-images.githubusercontent.com/22801026/111430026-066ee480-86b7-11eb-8f9a-7898eb8712dc.png)

**Comment by viviancan** [comment]
So weird to see the old styling 🤯

**Comment by dboyer** [comment]
Tested on QA:

- Selected "other" as the coding language and uploaded a zip file - saw two green check marks for coding language and technical additions
- Switched the coding language to Thunkable and added a link to the Thunkable details page. The link saved successfully in the technical additions section.
