### ISSUE TITLE
Ongoing Support - it-39 [13,8,1.63]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2828]
Dates 
- TG submissions open 1/11
- Platform walkthrough for students and mentors on 1/16

**Comment by shaunxp20** [comment]
Carryover from last support issue #2818:
- the labels on curiosity-machine are gone, the tickets once marked as "Code review", "Done" or whatever, those labels are all gone now
- the circle-ci integration isn't working

**Comment by hellafitz** [comment]
New Q arising from @ksrebecca, 1/8 TF/TG: Chapter Ambassadors want to know who “owns” a team when it spans multiple chapters. Does the platform base this on on the editable ‘Team Location’ field, the orginal location of the team creator, or something else?

**Comment by shaunxp20** [comment]
> New Q arising from @ksrebecca, 1/8 TF/TG: Chapter Ambassadors want to know who “owns” a team when it spans multiple chapters. Does the platform base this on on the editable ‘Team Location’ field, the orginal location of the team creator, or something else?

After a little poking around in the code, it looks like a chapter ambassador gets assigned to a student, not a team - it's possible (under the right circumstances) for students on the same team to have different chapter ambassadors (I verified this). Chapter ambassadors are assigned by state (if the chapter ambassador and student reside in the same state), and then if no matches or found, by country. It looks like it's possible for an assigned chapter to change when location data is updated, or when new chapter ambassadors get added (I haven't verified either of these). Hopefully that helps a little, let me know if y'all want me to dig in more. 👷 ⛏️ 🔦

**Comment by rsgonzal** [comment]
A mentor reached out to @mdancho that they received an error when trying to take the training on the dashboard. We can no replicate, but wondering if you have an idea on why this is happening just for them?
![unnamed](https://user-images.githubusercontent.com/22801026/104385680-85457680-54e8-11eb-9bf5-56dd27392e20.png)

**Comment by rsgonzal** [comment]
> A mentor reached out to @mdancho that they received an error when trying to take the training on the dashboard. We can no replicate, but wondering if you have an idea on why this is happening just for them?

Nevermind about this one! The company had google drive blocked. Completed the training for them.

**Comment by ksrebecca** [comment]
YES @shaunxp20 that's what we thought was happening, thanks for verifying. The other thing to check out especially before judging comes is how they get "assigned" a country. When we get submissions they all show as being from certain countries... the "global" winner from last year showed as India, so we suspect it is assigned whatever state or country of the person who created the team. But we want to make absolutely sure we understand since I think we'll be getting many more this year...

**Comment by shaunxp20** [comment]
> > A mentor reached out to @mdancho that they received an error when trying to take the training on the dashboard. We can no replicate, but wondering if you have an idea on why this is happening just for them?
> 
> Nevermind about this one! The company had google drive blocked. Completed the training for them.

Ok, nice! 🙌 🎉 (I was thinking it was something Google related 😅)

**Comment by shaunxp20** [comment]
> The other thing to check out especially before judging comes is how they get "assigned" a country. When we get submissions they all show as being from certain countries... the "global" winner from last year showed as India, so we suspect it is assigned whatever state or country of the person who created the team. But we want to make absolutely sure we understand since I think we'll be getting many more this year...

Re: The other thing to check out especially before judging comes is how they get "assigned" a country.

Hmm, who is "they" in this context? 🤔 😅 😀 Also, I can't really tell what the overall question/ask is. 🤔 ❔ 😊 😁

**Comment by ksrebecca** [comment]
Oh whoops!

So "they" = any team that has members from different states in the US, or from different countries. We've never really had that situation until our global team last year with members from Kenya, US, UK, and India. That team showed up in our judging rosters as an India team. We think because the mentor from India created the team? But don't know for sure. And suspect there will be more cross-border teams this year! Let me or @rsgonzal know if you are looking for more clarification :)

**Comment by shaunxp20** [comment]
> So "they" = any team that has members from different states in the US, or from different countries. We've never really had that situation until our global team last year with members from Kenya, US, UK, and India. That team showed up in our judging rosters as an India team. We think because the mentor from India created the team? But don't know for sure. And suspect there will be more cross-border teams this year! Let me or @rsgonzal know if you are looking for more clarification :)

Cool, thanks Rebecca! I can get w/ Roxana to get more details! 👍 ❤️ ☮️ 🌞
