### ISSUE TITLE
Onboarding prep [13,8,1.63]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2830]
Start building out a v2 onboarding guide for use with new hire(s) or support devs.

Deliverable: an organized folder or reference doc which gathers existing materials and at least outlines areas for improvements

**Comment by shaunxp20** [comment]
I added a rough draft for an onboarding guide:
https://github.com/Iridescent-CM/technovation-app/wiki/Onboarding-Guide

**Comment by rsgonzal** [comment]
dropping some links to work off of: 
- https://docs.google.com/document/d/1j9RX8uvpayEiF3HPmG3Ap7XKiJOCQRDm-iL6MMhmc30/edit#heading=h.mmfndilcyr6p
-https://docs.google.com/document/d/1P5jRXFups06EfqqZ_V_PW6dQKWQPqk7SFbMsV4u62WY/edit#heading=h.uqudebsjqfbf
