### ISSUE TITLE
Add Mentor Slack link and text to Connect with Mentors page

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2833]
When a Mentor clicks on the 'Connect with Mentors' menu it takes them to a view-only version of Mentor Search where they can see email addresses. Since we also have a more interactive mentor slack channel, we'd like to add a link to it at the top of the page. The goal would be to reinforce our existing mentor community from on the platform itself. 

<img width="937" alt="Screen Shot 2021-01-08 at 11 29 34 AM" src="https://user-images.githubusercontent.com/6475595/104056475-64f28080-51a5-11eb-9d0f-a11706e83215.png">

**Comment by hellafitz** [comment]
@bagomer would love your thoughts here, and which specific link to the Slack channel we would use

**Comment by bagomer** [comment]
I really like encouraging slack mentor channel engagement.

Here is the link to join the slack channel: https://join.slack.com/t/technovationmentors/shared_invite/zt-h9qiqmeb-9Wef6makUCNArBE7tXaX9g

Here is a link to the TG mentor slack channel: technovationmentors.slack.com

**Comment by rsgonzal** [comment]
We'll want to check how these pages work. As we noticed with the team pages, mentors and students see the same page but they can't perform the same actions. I don't think we want students seeing the mentor slack channel

**Comment by hellafitz** [comment]
@rsgonzal this is another good one to refine while I'm out

**Comment by hellafitz** [comment]
Draft text, which would appear only to mentors, and would be location on its own line after the current plain text: 
All Technovation mentors are encouraged to join the Mentor Slack channel [link on Mentor Slack Channel: https://join.slack.com/t/technovationmentors/shared_invite/zt-h9qiqmeb-9Wef6makUCNArBE7tXaX9g]

**Comment by hellafitz** [comment]
@bagomer let me know what you think of this draft text and placement. Thanks!
