### ISSUE TITLE
Remove Thunkable Classic from dropdown development platform options [8,3,2.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2835]
We are no longer using thunkable classic, we should not show it as an option to students

![Screen Shot 2021-01-15 at 10 34 29 AM](https://user-images.githubusercontent.com/22801026/104765180-58c67000-571d-11eb-83a9-af92383a923f.png)

### QA STEPS
- Basically just ensure Thunkable Classic has been removed, and that this section looks/works as expected

<10 mins

**Comment by hellafitz** [comment]
- remove this option from the dropdowns for both mentors and students
- work includes refactoring code that references Thunkable Classic

**Comment by shaunxp20** [comment]
This one is on QA, some basic QA steps have been added too! 😄 🥂 🎉

**Comment by ksrebecca** [comment]
QA: Looking good! 
<img width="601" alt="Screen Shot 2021-02-01 at 10 47 35 AM" src="https://user-images.githubusercontent.com/43972336/106482005-3e54fc00-646a-11eb-9969-fc5b917c5c26.png">

**Comment by kate-technovation** [comment]
Confirmed Thunkable Classic has been removed from menu on Student Dashboard:
<img width="774" alt="Screen Shot 2021-02-01 at 1 53 18 PM" src="https://user-images.githubusercontent.com/57409606/106504381-dd8ee900-6494-11eb-87f0-219cbcfe2192.png">

**Comment by rsgonzal** [comment]
Woo! Ready to go.
