### ISSUE TITLE
BUG: Mentors searching for other mentors causes an error

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2836]
### Steps to Reproduce

As a mentor:
- Go to one of your teams (or create a new team)
- Click "Mentors" in the sidebar
- Click button "Search for a mentor to invite" - this will cause an error

**Comment by shaunxp20** [comment]
This one is on the QA site.

The issue come out of #2783, redesigning the mentors page for students. This page is also what a mentor sees (I didn't know that when working on that ticket).

I fixed the broken link, but we should update the link text that a mentor sees, currently it says, "Search for a mentor to invite". Also, I think the page should be QA'ed from a mentor's perspective to make sure the content is what we want.

**Comment by rsgonzal** [comment]
I think we should use the text "Connect With Mentors" on the button.
Can we also add some help text under the button for mentors only that says, "Only students can invite mentors to a team."

**Comment by shaunxp20** [comment]
This one is back on QA, with these changes! 😁 

> * I think we should use the text "Connect With Mentors" on the button.
> 
> * Can we also add some help text under the button for mentors only that says, "_Only students can invite mentors to a team._"

**Comment by rsgonzal** [comment]
Looks great! 

Tested from student side as well and things are working fine.
