### ISSUE TITLE
Update Video in student dropdown [5,1,5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2840]
Nick has updated the video with recent changes made to the platform

New video: https://youtu.be/whZjfiB3vgQ 

![image (15)](https://user-images.githubusercontent.com/22801026/105221712-5a71a880-5b0e-11eb-8127-9be18cb18296.png)

### QA STEPS
- Just ensure the video is correct

<5mins

**Comment by shaunxp20** [comment]
This one is on QA, a basic QA step has been added too. 😄

**Comment by ksrebecca** [comment]
QA: Just checked and is the correct video for me when I log in as a student :)

**Comment by kate-technovation** [comment]
Confirmed new video (whZjfiB3vgQ) is showing on QA student dashboard:
<img width="781" alt="Screen Shot 2021-02-01 at 1 51 30 PM" src="https://user-images.githubusercontent.com/57409606/106504184-986ab700-6494-11eb-86b2-5be0db517595.png">

**Comment by rsgonzal** [comment]
thanks everyone!
