### ISSUE TITLE
Don't allow students to remove other students from a team after submissions [5, 5, 1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2843]
What's the cutoff? After they submit? when submissions close? After registration closes? can they still be pending after registrations close? i think they can still finish up consent forms and stuff...

**Comment by rsgonzal** [comment]
With team building control - can not delete members when this is off

**Comment by rsgonzal** [comment]
April 19th- sub deadline

**Comment by rsgonzal** [comment]
How does removing members work? Can you not remove members after parental consents signed?

**Comment by shaunxp20** [comment]
> How does removing members work? Can you not remove members after parental consents signed?

Looks like the way it currently works, you can remove:
* yourself
* any team member who is still onboarding

Also, if you're an admin or a ChA (with the right permissions) you can remove anybody.

https://github.com/Iridescent-CM/technovation-app/blob/qa/app/guards/can_remove_team_member.rb

**Comment by rsgonzal** [comment]
Ah! Thanks, shaun! Going to mark as done :)
