### ISSUE TITLE
Spike: Adding a third division to the platform [40,13(3),3.01]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2844]
What do we need to know before we can explore this???

how are parents involved?
what does reg look like for kids?
restrictions?

**Comment by rsgonzal** [comment]
The team started detailing their ideal scenario here: https://docs.google.com/document/d/1F8uLsRMj3dsoOQBaup0v_6rqD7OBsFp6O_MipNpe79A/edit?ts=60243c4e#

**Comment by hellafitz** [comment]
- start off by talking about their responses and going through the platform together
- look for where their ideal scenario diverges from the current platform (another input may be the 1P department Q&A slides)

**Comment by rsgonzal** [comment]
Shaun created #2860 for followup
