### ISSUE TITLE
Track certificate downloads by user [tbd]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2847]
We don't currently track if and when users have downloaded their certificates. This makes is hard to know  how many users are finding them valuable (or not). Also, since we turn off access when the next season starts, we don't know how many users this affects.  

As an Admin, I want to be able to see which student and mentor users have or haven't downloaded their certificates - and when - so that I can see overall rates and timelines.

**Comment by rsgonzal** [comment]
More info after we clear current certificate tickets

**Comment by rsgonzal** [comment]
any closing words here @shaunxp20 ?

**Comment by shaunxp20** [comment]
> any closing words here @shaunxp20 ?

Late to the party here, but having this tracked off-platform makes sense to me! Thanks for taking care of this @rsgonzal! 🙌 🍕 🎉
