### ISSUE TITLE
Collect information on how many judges are downloading source code [13,8,1.63]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2853]
Knowing if judges are clicking at source code when judging submissions
- Trying to figure out if we should even collect source code
- Would be useful this season to know for decision making next year
- Important info is what % or how many people total clicked on it

Want: Collect info on judging event (if a judge does 10 submissions, how many of those source codes did they look at)

## QA STEPS
We're now tracking if a judge:
- clicks to download the source code
- clicks to download the business plan
- clicks the demo video (only a click, not if they actually watched it)
- clicks the pitch video (ditto ☝️)

To QA this: 
1. Turn on "judging" in the admin
2. Login/impersonate a judge, and start scoring a new submission
3. Click those items listed above ☝️☝️ 
4. Then in the admin, look up this score, on the scores detail page, it should show the items clicked in step 3. 
5. Also, verify the score/comments look good (just making sure this is still functioning as it should be)

**Comment by shaunxp20** [comment]
This one is on QA, ready for some feedback! 😄 😸 😃 😺

**Comment by rsgonzal** [comment]
hey @shaunxp20 ! Does this only work on certain sections? I tried clicking on them from the main "Review Submission" page, but I don't think it recorded those clicks?

Also, will there be a way to see what percent of judges total did that? Maybe a dataclip?

**Comment by shaunxp20** [comment]
> hey @shaunxp20 ! Does this only work on certain sections? I tried clicking on them from the main "Review Submission" page, but I don't think it recorded those clicks?

Hmm, it should work on all pages/section. If it's not, then that's a bug. 😟 🤔 

Let me know which one (pitch video, demo video, business plan, source code, or all of them!) wasn't being recorded, and which submission, and maybe steps (if they're not obvious). 

> Also, will there be a way to see what percent of judges total did that? Maybe a dataclip?

I haven't created a dataclip yet, but the data is there for one. I can work on one later, or maybe it can be a "good-first-ticket" one since it's pretty straight forward.

**Comment by rsgonzal** [comment]
Judge: New Judge
Team: this da best team
submission: Great People

I just judged this submission
- clicked on pitch, demo & downloaded source code from the FIRST page 'Review Submission'

![screencapture-technovation-qa-herokuapp-admin-scores-410-2021-03-22-15_40_17.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/cbe29e49-55be-4436-aa24-6e6e64a40526)

**Comment by rsgonzal** [comment]
> I haven't created a dataclip yet, but the data is there for one. I can work on one later, or maybe it can be a "good-first-ticket" one since it's pretty straight forward.

I like "good-first-ticket" ! Made

**Comment by shaunxp20** [comment]
> Judge: New Judge
> Team: this da best team
> submission: Great People
> 
> I just judged this submission
> 
>     * clicked on pitch, demo & downloaded source code from the FIRST page 'Review Submission'
> 
> 
> ![screencapture-technovation-qa-herokuapp-admin-scores-410-2021-03-22-15_40_17.png](https://camo.githubusercontent.com/95858560c8686db2dc4ae22c235e3d62d83f0e95a91144fb93a1fe613f18cf94/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630353237313639636465323737323234326430646539352f63626532396534392d353562652d343433362d616132342d366536653634613430353236)

Okay, I see the issue, it's a bug, I'll work on this one later, I'll move it back to "In Progress". 😅 😀

**Comment by shaunxp20** [comment]
Okay, this should be working now on QA. 🤞 😄  Good catch on this one!

The issue was that I was getting the score id (we need to know which score to update) from the url, but the score id isn't in the url for new scores (when I was testing locally it must have been w/ a score in progress), so now we'll get it from the Vuex store , which should fix this issue! 😄

**Comment by ksrebecca** [comment]
QA:

Logged in as Stinky Tofu and judged Down with Carol Baskins, first clicking on every item then judging and leaving comments.

I can't find where I should be viewing the items clicked in step 3 (Then in the admin, look up this score, on the scores detail page, it should show the items clicked in step 3.) <-- where is that? I found this but it's not there when I click in. I looked at all the column options in the score section too but don't see anything that looks like it could be it either...

<img width="170" alt="Screen Shot 2021-03-24 at 4 32 02 PM" src="https://user-images.githubusercontent.com/43972336/112382520-931a3380-8cb1-11eb-86a2-b14e26a047c7.png">

Score/comments still look good!

**Comment by rsgonzal** [comment]
It's in the middle @ksrebecca !

But @shaunxp20 I think this brings up a good point about readability. Instead of listing it in the individual sections, could we list them all right above 'ideation', after 'scores come from'

**Comment by ksrebecca** [comment]
Quick question... This info is also going to be available for a big batch
download like we discussed, right? I'm less concerned about individual
judges (though it's nice to have as ammo during score monitoring if
needed!) and more interested in the overall stats at the end 😄

**Comment by shaunxp20** [comment]
> But @shaunxp20 I think this brings up a good point about readability. Instead of listing it in the individual sections, could we list them all right above 'ideation', after 'scores come from'

I made this change, it will be on QA soon. 👍 

> This info is also going to be available for a big batch download like we discussed, right?

Roxana created #2874 for some dataclips; and if we want more or something different, it won't be a problem, the data will be there for us to use however we want. 👍 😄

**Comment by shaunxp20** [comment]
> Instead of listing it in the individual sections, could we list them all right above 'ideation', after 'scores come from'

This update is now on QA, happy to make more changes if we need to too! 😄

**Comment by ksrebecca** [comment]
I love it! Even if I tried I couldn't miss that one now lol
<img width="778" alt="Screen Shot 2021-03-25 at 7 19 55 AM" src="https://user-images.githubusercontent.com/43972336/112464983-cac4c200-8d29-11eb-8259-9e5dde7be6d3.png">
