### ISSUE TITLE
Require completion of post survey before viewing certificates by student

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2854]
As a student, I must complete the post survey before I am allowed to receive my certificate or view my scores

Goal: Increase amount of post-surveys completed

Mockups: https://app.mural.co/t/roxwork8740/m/roxwork8740/1618346886562/e87e71704aec5bb66678ecbd79c8173c30af691d

Criteria:

1. Add line of text, sending them to the post-survey
- Before you can view your scores, please complete the post-survey.
- Currently, the post-survey is configured in the admin and can be viewed through a pop up or under the helpful links tab. The platform recognizes when the survey has been taken by a user
- The post survey is not yet updated

2. Button to view certificate is disabled if the survey has not been taken

3. Once the survey is taken, the line is removed and the button is enabled.

### QA Steps
(repeat for a student that didn't submit, on a quarterfinalist team, on a semifinalist team)
1. Login as a student and try to view scores
2. Review text on scores dashboard page #2975 (changes were made in that ticket)
3. You should have to complete survey 
4. Review scores & certificate

**Comment by tamtran-agilityio** [comment]
Can you help me? With account type judge and mentor, I see have judge profiles with field survey complete. With a student, what are you need survey complete?

**Comment by rsgonzal** [comment]
Students complete a survey that is configured in the admin. They find it on their dashboards as the last thing on this nav bar. After they complete it, it is removed from the dropdown:
<img width="1196" alt="Screen Shot 2021-04-19 at 11 51 29 PM" src="https://user-images.githubusercontent.com/22801026/115350674-40298400-a16a-11eb-9f40-92b4186140ba.png">

**Comment by tamtran-agilityio** [comment]
Thank you!

**Comment by tamtran-agilityio** [comment]
Hi Roxana Gonzalez!
I have check but don't seen information survey of students in database. Where are data survey store?

**Comment by rsgonzal** [comment]
Hi @tamtran-agilityio . I just share a document with you that might help explain surveys a bit more.

**Comment by tamtran-agilityio** [comment]
@rsgonzal I will check, thank you!

**Comment by viviancan** [comment]
PR #2915

**Comment by rsgonzal** [comment]
- Logged in as a student that had already taken the post survey and I was able to see the certificate
- Logged in as a student that had not take the survey and had to complete before getting my score & certificate

**Comment by kate-technovation** [comment]
1. Logged in as a student that had already taken the post survey and was able to see the certificate:
Screenshot A:
<img width="960" alt="Screen Shot 2021-06-24 at 4 41 52 PM" src="https://user-images.githubusercontent.com/57409606/123329684-15153500-d50b-11eb-811d-b8e5a950b64f.png">

Screenshot B:
<img width="926" alt="Screen Shot 2021-06-24 at 4 42 06 PM" src="https://user-images.githubusercontent.com/57409606/123329754-25c5ab00-d50b-11eb-80bf-1da8f51aba8e.png">


2. Logged in as a student that had not take the survey and had to complete before getting my score & certificate:
Screenshot A:
<img width="976" alt="Screen Shot 2021-06-24 at 4 39 04 PM" src="https://user-images.githubusercontent.com/57409606/123329349-b2bc3480-d50a-11eb-8fe3-3fba342ae374.png">
Screenshot B:
<img width="931" alt="Screen Shot 2021-06-24 at 4 39 42 PM" src="https://user-images.githubusercontent.com/57409606/123329569-f3b44900-d50a-11eb-8104-b7ebcaadb422.png">
Screenshot C:
<img width="931" alt="Screen Shot 2021-06-24 at 4 39 42 PM" src="https://user-images.githubusercontent.com/57409606/123329604-fd3db100-d50a-11eb-8304-005add059883.png">
Screenshot D:
<img width="794" alt="Screen Shot 2021-06-24 at 4 39 57 PM" src="https://user-images.githubusercontent.com/57409606/123329610-ff077480-d50a-11eb-8515-18c8ac9180d3.png">

**Comment by ophelieh** [comment]
* Logged in as a student that didn't even form a team (tam.tran@asnet.com.vn) - a survey popped up. Is that the current one? 
* Logged in as a student who didn't submit (roxana+s917@technovation.org) - same thing happened.
* Logged in as a quarterfinalist (mackenzie+3s@iridescentlearning.org - with no scores - which wouldn't happen normally)- after taking the survey, I was able to click on "View your certificate". 
* Logged in as a quarterfinalist (kate+18student@technovation.org) - the pop-up was the first thing I saw (this probably shouldn't happen). After I closed the pop-up, I saw the link to the survey. Took it then was able to see my scores and certificate. 
<img width="1440" alt="Screen Shot 2021-06-24 at 4 18 19 PM" src="https://user-images.githubusercontent.com/32206421/123333859-e6e22600-d507-11eb-9715-5fb648b7fc57.png">

Side note - the down arrow doesn't align with the rest for "Entrepreneurship" <img width="1440" alt="Screen Shot 2021-06-24 at 4 20 38 PM" src="https://user-images.githubusercontent.com/32206421/123334042-201a9600-d508-11eb-89ee-3310a51bff6c.png">


* Logged in as a semifinalist (ophelie+s106@technovation.org) - had to take the survey before I could click on "View your scores and certificates"

**Comment by rsgonzal** [comment]
> * Logged in as a student that didn't even form a team ([tam.tran@asnet.com.vn](mailto:tam.tran@asnet.com.vn)) - a survey popped up. Is that the current one?
> * Logged in as a student who didn't submit ([roxana+s917@technovation.org](mailto:roxana+s917@technovation.org)) - same thing happened.

is that the current survey? yes, it's just a fake one for QA! But the survey pops up for all users

> * Logged in as a quarterfinalist ([mackenzie+3s@iridescentlearning.org](mailto:mackenzie+3s@iridescentlearning.org) - with no scores - which wouldn't happen normally)- after taking the survey, I was able to click on "View your certificate".
> * Logged in as a quarterfinalist ([kate+18student@technovation.org](mailto:kate+18student@technovation.org)) - the pop-up was the first thing I saw (this probably shouldn't happen). After I closed the pop-up, I saw the link to the survey. Took it then was able to see my scores and certificate.

@ophelieh  The survey pop up is configured currently. Are you saying you want the pop up taken off before certificates go live? Will need a reminder for that 😅
 
> Side note - the down arrow doesn't align with the rest for "Entrepreneurship" <img alt="Screen Shot 2021-06-24 at 4 20 38 PM" width="1440" src="https://user-images.githubusercontent.com/32206421/123334042-201a9600-d508-11eb-89ee-3310a51bff6c.png">

@viviancan i think we missed this when we QA'd #2968 . Can we make this change?

> * Logged in as a semifinalist ([ophelie+s106@technovation.org](mailto:ophelie+s106@technovation.org)) - had to take the survey before I could click on "View your scores and certificates"

**Comment by rsgonzal** [comment]
I think this one is good to go, I don't think anything @ophelieh noticed was not as expected (except maybe the popup) but let me know if otherwise!

I can make a new ticket for the arrow, if that's easier to deploy things!

**Comment by ophelieh** [comment]
So we can't take the pop-up down only for certain accounts (ones who have to take the survey to see scores/certificates)? I guess it's not that big of a deal, but we would need to make sure that if they take the pop-up survey, it does validate so they can look at their certificate.

**Comment by viviancan** [comment]
@rsgonzal The update for the entrepreneurship arrow has been made!

![Screen Shot 2021-06-25 at 10.55.29 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/a30219c6-77be-4f75-a241-cc21e94d510f)

**Comment by rsgonzal** [comment]
yup, it's for everyone @ophelieh ! It is the same link that will mark their account with the survey complete, so ultimately it doesn't matter where they click from. Also, if they have already taken the post survey, since it's been up for about a month, it will already let them see the scores

**Comment by ophelieh** [comment]
Ok cool. Thanks for explaining Roxana. :)
