### ISSUE TITLE
Epic: Beginners Division

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#2860]
This ticket is to capture some dev notes/thoughts and to list out the things we would need to get the beginners division on our platform.

## Registration
This is one the trickiest pieces - how to get the kids registered.

My thinking is that if we want to track students across divisions (beginners -> junior -> senior), we should have the parents create the student's account (as if a parent were to create a junior or senior account now). Then at some point in the future the account would have to get "transferred" to the student to make it theirs (probably by updating the email address on the account). And we would associate the parent's first/last name (and any other info we want to capture) to this account for the beginners division. I think this would be the simplest way to use what we have.

There are a few ways to approach the registration screens, mainly they are: a) use what we have and make minor adjustments **(L/XL)**, b) major changes to have we have **(XL/XXL)**, and c) doing a complete overhaul **(XXL)**

For the more minor adjustments, we would have to:
- Update the verbiage on the registration flow, like it says "your age" now **(S)**
- Add parent first/last name to one of the screens **(M)**
- Add parental consent to registration flow **(M/L)**
- Update age range logic for junior/senior division, and add new logic for beginners division **(M/L)**

**Existing**
Junior Division: 10-14
Senior Division: 15-18

**New**
Beginners Division: 8-12
Junior Division: 13-15
Senior Division: 16-18

## Parent-Kid Toggle and Kid's Views
- All participants in the beginner's division would get presented with a prompt after logging in that would let them choose the parent's views or the kid's views - needs mockups, would need the "kid's views" too **(L)**
- Update the "impersonation" feature for admins **(M/L)**
- The "learning journey", submission screens, and everything else for the kid's views - needs more details/mockups (**XXL)**

## Team Matching
- Default this setting to "No" for beginners division: "Allow mentors to find our team and request to join us" **(S)**
- Only parents can reach out to mentors - this would need the "parent-kid toggle" feature

## Submissions
- Teams select what they want to be judged on (AI/mobile) - needs more details/mockups **(S/M)**
- Must state at beginning of demo video what tech they used - needs more details/mockups **(S)**

## Judging
- Updating judging screens to make it clear what division they're judging - needs more details/mockups **(M)**
- Judges to be assigned to submission (age division, tech type) randomly - needs more details **(M)**

## Misc

- Send division name to Mailchimp **(S/M)**

**Comment by dboyer** [comment]
Closing as we implemented the beginner division.
