### ISSUE TITLE
Update text on thank you screen after a judge finishes scoring a submission [5,3,1.7]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2863]
Edit the text on this screen:

![Screen Shot 2021-03-17 at 1 21 00 AM](https://user-images.githubusercontent.com/22801026/111436611-69647980-86bf-11eb-9024-e1a97f2495a8.png)

Edit last line of text:
You just completed your (Xth) score! You can review your score or see all of your finished scores on your dashboard and make edits as you need through May 25 (US/Pacific time)! 

Notes:
- Would like to include count of how many scores they've completed (xth)
- keep link for 'review your score'
- link to their dashboard for word 'dashboard'
- Keep date as config

@mdancho can you review? I edited the text a bit 

## QA STEPS
After judging is enabled in the admin:
- Login/impersonate a judge, start scoring a new submission
- Finish scoring the submission, and verify the content on the "thank you" page looks good

We can also verify the "review your score" date changes for semifinals.

**Comment by mdancho** [comment]
Looks great, thanks Rox! When QF closes and SF opens will the "review your score" line change to say you can review until June 16th?

**Comment by shaunxp20** [comment]
> When QF closes and SF opens will the "review your score" line change to say you can review until June 16th?

Yup, it should pull the dates from our config settings based on the judging round. I added it as an extra QA note so we can verify it too. 😃

**Comment by rsgonzal** [comment]
Looks great!! I'll check the semifinals text after people are off QA for the day.

**Comment by rsgonzal** [comment]
Judy also checked this one! :thumbsup:

**Comment by rsgonzal** [comment]
>We can also verify the "review your score" date changes for semifinals.

It does!
![Screen Shot 2021-03-22 at 7.45.32 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/722c7e90-f917-4d58-94c7-b1c02ca39f2f)

**Comment by mdancho** [comment]
Looks great for the first and second score! Would maybe remove "help" and just write "Your contribution makes a huge impact and we highly appreciate your time". 

<img width="1231" alt="Screen Shot 2021-03-26 at 10 14 12 AM" src="https://user-images.githubusercontent.com/52216992/112669102-882fe200-8e1c-11eb-8d97-7fbd9ccf384a.png">

<img width="1231" alt="Screen Shot 2021-03-26 at 10 14 12 AM" src="https://user-images.githubusercontent.com/52216992/112671417-5cfac200-8e1f-11eb-888c-0134656fe1d9.png">
