### ISSUE TITLE
Edit Spain state names [8,5,1.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2864]
Working off of this list: https://docs.google.com/spreadsheets/d/16qmnGy6aBrJyeLjF-mmoAr0eNU-CnwGtLwuk2BkJONo/edit?ts=604fbb6c#gid=821775359

## DEPLOYMENT NOTES
After this has been deployed, run the command:
`$ heroku run bundle exec rake update_spain_location_data --app technovation`

**Comment by rsgonzal** [comment]
Column M is the correct state name!

K-->M

**Comment by shaunxp20** [comment]
I'm thinking of two different approaches on how to update these records:

1.  Using the spreadsheet, ideally we would want account ids (that way email addresses won't be in the script, which will be public in our repository) - I can get the account ids from the email addresses and _update the location data just for those accounts_

2. I can write a dataclip for each of locations that needs to be updated (15 of them), and someone would need to double-check them, then I can get the account ids, or even the `where` clause to update the location data. I created a sample dataclip for what this would look like.

Option 2 would be more work, but I'm thinking it would be more thorough, in the sample dataclip I created for Andalucia, there are 38 records, but in the spreadsheet there are 37. I'm wondering if the other dataclips would pick up additional accounts.

**Comment by rsgonzal** [comment]
tried to pull these IDs for you, but looks like it's not a column we can add in the admin :(

But confirming we are going with option 1!

**Comment by shaunxp20** [comment]
> tried to pull these IDs for you, but looks like it's not a column we can add in the admin :(

No worries, thanks for trying! 😄 

As we talked about this morning, here's a list of all the `account` columns/fields:
https://github.com/Iridescent-CM/technovation-app/blob/8149fb8a01164560b7a2906391cca51fceaa0b4e/db/structure.sql#L63-L110

**Comment by shaunxp20** [comment]
> Column M is the correct state name!
> 
> K-->M

Hmm, I need a sanity check, column M has an `UNKNOWN` in it (for Comunidad Valenciana). Also, column M doesn't seem to match up with column O or P, which both say: "What is should be". 😕 🤔 🤯

**Comment by rsgonzal** [comment]
yeah, it's confusing! So I don't know what the platform recognizes when you filter by Valencia. Nothing shows up on the platform and when I change the state as a user it turns it into 
![Screen Shot 2021-03-31 at 2.00.58 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/9fef23b9-a7b2-4cf5-8bdd-b9dfe4bb0705)
![Screen Shot 2021-03-31 at 2.00.58 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/ce7a2a24-ed6a-4c17-8e46-e3cc63637d09)

**Comment by shaunxp20** [comment]
I managed to get all of the account ids (I have them grouped by region). The next step is to update the locations for these accounts, but I'm a little confused as to what they should be. For example, there are five accounts in the spreadsheet for "Galicia"; when I search on the platform by "State/Province" for "Galicia", these five accounts show up, they're already "Galicia". On the spreadsheet, it says also "Galicia" for "Where it belongs" and "What is should be". I see a discrepancy in the database though, it's stored as "GA", is this the value that needs to be updated to "Galicia"? 🤔 😕 😖
