### ISSUE TITLE
Change logic for mentor certificate to match students

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2873]
A Mentor should only receive a certificate for a team they are on if that team:

- Has a submission
- The submission is at least 50% complete (50% <= Team Submission < 100%)

### QA Steps
Verify by going to a user's profile page through the admin and checking under 2021 certificates
1. Go to the profile of a mentor not on a team - should not be receiving anything
2. Go to the profile of a mentor on a team with a submission < 50% complete - should not receive anything
3. Go to the profile of a mentor on a team with a submission > 50% complete but not submitted (if you can find) - should receive 
4.  Go to the profile of a mentor on a team with a submitted project - should receive

**Comment by rsgonzal** [comment]
Q from #2866

**Comment by tamtran-agilityio** [comment]
@rsgonzal ![Screen Shot 2021-04-13 at 20.49.31.png](https://images.zenhubusercontent.com/60667006d3607b5f5929e82f/f0975ccc-2383-4f17-8bb5-0c555a029cef)

**Comment by rsgonzal** [comment]
Hi @tamtran-agilityio that is a great question. But we do not need to disable that button. This section is available here to be used by our admin. They might have a need to create a certificate for someone, even if they do not meet the criteria.

It is possible that this might be changed with another ticket we have. Thanks for checking!

**Comment by congdang** [comment]
@rsgonzal Beside manual aware certificates like above screenshot, is there an automatically way to system sends the certification to Mentor?

If there was ONLY Manual award, so Admin always see the `Award` button and can action on it, but we will check the condition and if it is not matched, we will show the message, right? If so, please help to define the message for us.

Thanks!

**Comment by rsgonzal** [comment]
There is an automatic way the system awards certificates. That is what this is needed for.

Nothing needs to change for the manual option.

Thank you!

**Comment by tamtran-agilityio** [comment]
@rsgonzal Who are create certificate?
I cannot find a certificate creation function on technovation-app. You can help me clear?

**Comment by shaunxp20** [comment]
> @rsgonzal Who are create certificate?(mentor, admin, judge)
> I cannot find a certificate creation function on technovation-app. You can help me clear?

There is a rake task which can generate certificates: `lib/tasks/award_certificates.rake`

The logic for which certificate gets awarded is in: `app/technovation/determine_certificates.rb`

And just fyi, after certificates have been generated, there is an admin setting that needs to be enabled in order for everyone to see their certificates: Content & Settings -> Scores & Certificates -> Scores & Certificates Accessible

Hopefully that helps! 😄

**Comment by tamtran-agilityio** [comment]
@shaunxp20 I have seen it, but I don't find function create and updated certificate to AWS by user.

**Comment by shaunxp20** [comment]
> @shaunxp20 Yes, I have seen it, thank you. But I don't find function create and updated certificate to AWS by user.

Ah yes, only we (admins/devs) can generate certificates (via the rake task or the admin area); judges/mentors/students can't generate a certificate for themselves. 😄

**Comment by tamtran-agilityio** [comment]
@shaunxp20 I understand, thank you!

**Comment by viviancan** [comment]
PR #2910

**Comment by kate-technovation** [comment]
1. Went to the profile of a mentor not on a team - verified no certificates:
<img width="905" alt="Screen Shot 2021-06-24 at 4 53 25 PM" src="https://user-images.githubusercontent.com/57409606/123330995-b355ca80-d50c-11eb-806a-70276f80cea2.png">

2. Went to the profile of a mentor on a team with a submission < 50% complete - verified no certificates:
<img width="902" alt="Screen Shot 2021-06-24 at 4 48 08 PM" src="https://user-images.githubusercontent.com/57409606/123330398-f6636e00-d50b-11eb-8ac8-3d3ee70ba6c9.png">

3. Went to the profile of a mentor on a team with a submission > 50% complete but not submitted (if you can find) - **but there wasn't a certificate available**, and the team's submission was 75% complete:
<img width="922" alt="Screen Shot 2021-06-24 at 5 00 28 PM" src="https://user-images.githubusercontent.com/57409606/123331824-c0bf8480-d50d-11eb-9f4e-e53a3acd50e6.png">


4. Went to the profile of a mentor on a team with a submitted project -  verified there were certificates:
![Uploading Screen Shot 2021-06-24 at 4.55.10 PM.png…]()

**Comment by rsgonzal** [comment]
These look good!
