### ISSUE TITLE
Create dataclip to understand how many judges are clicking submission pieces [13, 8, 1.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2874]
From #2853, four new columns were added to the `submission_scores` table.

Create a dataclip to see what percentage of people are:
* clicking the demo video
* clicking the pitch video
* downloading the source code
* downloading the business plan

Make sure this is limited to the current season only.

Notes:
- Tracking individual clicks unique to judge + submission
- Would be nice to see totals: # clicked # did not click

### QA Steps
Review dataclip

**Comment by viviancan** [comment]
Added dataclip for judge submission click stats to heroku.  Can be viewed at [https://data.heroku.com/dataclips/jirkjdshcuehcghxiyjxbtysidlm](https://data.heroku.com/dataclips/jirkjdshcuehcghxiyjxbtysidlm)

**Comment by rsgonzal** [comment]
@ophelieh i think you mentioned you couldn't get the link for this one. I just shared it with you!
https://data.heroku.com/dataclips/bkubdafljkvhzcsnbbqoubecdtla?sharing=true

**Comment by ophelieh** [comment]
Thank you Roxana! This is amazing :) 

Is there a way to click on each item or a way to collect team info - especially the ones that are not being watched to see which teams those are? Maybe that's done somewhere else already though
