### ISSUE TITLE
XInstall Heap by Sun 4/11 on technovationchallenge.org Wordpress

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2876]
Follow on from #2754, which installed Heap to the TG platform.

Deliverable: Install the Heap code snippet on the technovationchallenge.org wordpress site. Our goal is to see user behavior across BOTH the TG platform (my.technovationchallenge.org) and the website (technovationchallenge.org). 

Importantly, our curriculum/lessons are on the wordpress site, so Heap going there will allow us to see how students interact with our materials, and what if any effect that has on submissions. 

Developer instructions are at https://developers.heap.io/docs/wordpress

Ask @shaunxp20 or @hellafitz for the account ID

**Comment by hellafitz** [comment]
@rsgonzal flagging this one for your attention since the timeline is tight

**Comment by rsgonzal** [comment]
added to wordpress repo
