### ISSUE TITLE
Implement server-side API connection w/ Heap [8, 13, .62]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2877]
Developer reference materials: https://developers.heap.io/reference#server-side-apis-overview

Connect Heap to the Technovation platform to allow server-side API connections. This should allow us to filter user behavior data in Heap by:
- Team (Team IDs)
- User Type (e.g. student, mentor, ChA, admin)

This is in service to our two-week product analytics trail period, during which we'll attempt to answer as many of these questions as possible: 
![Screen Shot 2021-04-02 at 11.14.02 AM.png](https://images.zenhubusercontent.com/6054e96f1c08229a22e140ed/84c08098-ea75-469d-b2e2-c76eb70e18ff)

**Comment by hellafitz** [comment]
@rsgonzal this would be really helpful to have by Friday at noon pacific time, if possible

**Comment by viviancan** [comment]
Adding Team ID and User Type should be possible through the API

Captured notes in [this document](https://docs.google.com/document/d/15an7jB5IU3NwiMx0-adB2He400vz555yk_sRGeDPdCU/edit?usp=sharing)

**Comment by rsgonzal** [comment]
Thanks, Vivian! Any thoughts on size of this project? S, M, L?

**Comment by viviancan** [comment]
I think at least a M!

**Comment by viviancan** [comment]
The actual implementation doesn't seem too complex, but there are some potential pitfalls.
