### ISSUE TITLE
Make help text on judge screens bigger [8, 2, 4]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2880]
![Screen Shot 2021-04-02 at 11.11.09 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/c87af82a-8ce3-4e01-8ca0-d04132a8f84d)

Decision: remain unbolded and italicized but be the same as the Ideation title 
this should be adjusted on each page

### QA steps
- open judging on the platform
- sign in as a judge
- start judging a submission
- review help text

**Comment by viviancan** [comment]
#2897

**Comment by rsgonzal** [comment]
hey @viviancan why'd you close this one? :thinking_face:

**Comment by rsgonzal** [comment]
Oh i see! via the pull request! So we keep these tickets open to move them through the board, maybe we can talk through this tomorrow :)

**Comment by rsgonzal** [comment]
Thought it was going to look strange, but looks pretty good :)

**Comment by mdancho** [comment]
Looks good to me :) Still seems smaller than the title but hopefully is large enough that judges will be drawn to read it! Thanks, team!
