### ISSUE TITLE
Edit columns on scores page [8, 5, 1.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2881]
- Make Recusals a permanent column on the chart, would be # of
- should be able to sort by ascending/descending
- Can remove the option to change the rank on this page (first column)

![Screen Shot 2021-04-07 at 12.54.27 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/6fadc179-d515-4093-8e61-2fd0857272d4)

## QA STEPS
* Verify the "contest rank" column has been removed (it's still available via "More columns" without the ability to update the contest rank)
* Verify the "recusals" column is there and working as expected:
  * As a judge recuse yourself from a submission, and verify the counter goes up for the submission

**Comment by viviancan** [comment]
Worked on QA for me! I was able to sort, view counter, and counter went up when I recused myself again (as a judge)

**Comment by mdancho** [comment]
Worked for me on QA!

**Comment by rsgonzal** [comment]
Thanks, @mdancho !
