### ISSUE TITLE
Allow admins to assign more than 1 submission to a judge [13, 5, 2.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2883]
This is for admins assigning judges to specific submissions
Create some sort of queue for the judges
- let them see their entire queue 

## QA STEPS
* Turn on judging in the admin
* Find an on-boarded judge, copy their email address
* Verify you can assign multiple submissions to this judge (you can assign a submission by going to "Scores", and then clicking score details (in the right-most column named "View"), this next page will have the judge assignment form)
* Login or impersonate this judge
* Verify all the assigned submissions are being displayed

**Comment by shaunxp20** [comment]
This one is on QA, ready for some 👁️‍🗨️ 👀 💬 😃

**Comment by mdancho** [comment]
As an admin I can assign more than 1 submission to an account and when I log-in as a judge I can see my assigned submissions! Looks great. Just FYI I can not see the assigned submission on the admin/participant/ page where I can see QF, SF and recused scores, this is only visible to an admin on the submission score page (not the judge page).

**Comment by shaunxp20** [comment]
> Just FYI I can not see the assigned submission on the admin/participant/ page where I can see QF, SF and recused scores, this is only visible to an admin on the submission score page (not the judge page).

Hmm, we could add an "Incomplete Scores" section to that page that would show the assigned submissions. Right now we don't have a way to distinguish between an assigned submission and incomplete submission; when a score is assigned to a judge it falls into the incomplete bucket. Anywho, let us know if you want us to add an "Incomplete Scores" section, it wouldn't be too hard to do. 😄 🌞

**Comment by rsgonzal** [comment]
I like the idea of an incomplete section! I will add a ticket.

I found a bug :(

My judge: Judgy Judge

1. I had started scoring a submission.
2. Then I assigned myself a submission to judge (testing thunkable text)
3. Whichever score I resume, it opens up the first one I was scoring.

**Comment by viviancan** [comment]
I think something is happening where the incorrect submission_id is being found in `scores_controller` > `new` > `FindEligibleSubmissionId.call()` > `id_for_score_in_progress`.

Using the debugger, I was able to see that the initial project's submission id/ all info is being returned from the GET request.

**Comment by shaunxp20** [comment]
> I found a bug :(
> 
> My judge: Judgy Judge
> 
>     1. I had started scoring a submission.
> 
>     2. Then I assigned myself a submission to judge (testing thunkable text)
> 
>     3. Whichever score I resume, it opens up the first one I was scoring.

Great find Roxana! Thanks for catching this! 🥇 

Thanks for debugging this, Vivian! 🥇 You pretty much figured it out! It was just a one line change to fix, the `options` (which contains the `score_id` for the one being "resumed") weren't getting passed to `#id_for_score_in_progress`.

**Comment by rsgonzal** [comment]
thanks @shaunxp20 ! Did this end up making it to QA? I saw some checks were failing earlier.

**Comment by rsgonzal** [comment]
only thing i'm noticing is that if i start both submissions at the same time. it brings be back to the last section i scored on the previous submission. not a huge deal

**Comment by shaunxp20** [comment]
> only thing i'm noticing is that if i start both submissions at the same time. it brings be back to the last section i scored on the previous submission. not a huge deal
> 
> so if i finish off on the entrepreneurship section for one submission, go to my dashboard and click on the next submission, it opens up on the entrepreneurship section. instead of review score which is where i should be on the second submission

Ah yes, I see what you're saying, I suspect that's an existing issue, related to #2925. 😕

**Comment by shaunxp20** [comment]
> > only thing i'm noticing is that if i start both submissions at the same time. it brings be back to the last section i scored on the previous submission. not a huge deal
> > so if i finish off on the entrepreneurship section for one submission, go to my dashboard and click on the next submission, it opens up on the entrepreneurship section. instead of review score which is where i should be on the second submission
> 
> Ah yes, I see what you're saying, I suspect that's an existing issue, related to #2925. 😕

I just confirmed that it's an existing issue. 😕

**Comment by rsgonzal** [comment]
Thanks, Shaun! Added it to that new ticket. I also:
- created new judge account
- scored the multiple submissions
- ensured that the scores all show up correctly
- note* can not start a new submisison on your own if you have multiple assigned, just brings you back to dashboard.
