### ISSUE TITLE
Edit Special Admin Email Subject line

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2886]
![Screen Shot 2021-04-08 at 12.17.39 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/39181c5b-cc25-422e-a26c-ee7650e12efe)

Current Language: Special Admin Invitation: Sign up for your 2021 Chapter Ambassador account

Problem: The action that triggers this email can be used for other user types, not just students

Proposed line: TG Invitation: Sign up for your 2021 account

### QA Steps
- login as admin
- go to invite users
- invite a student 
- check email you receive

**Comment by viviancan** [comment]
[Branch on Github](https://github.com/Iridescent-CM/technovation-app/compare/2886-special-admin-email-subject-line?expand=1)

**Comment by rsgonzal** [comment]
Looks great to me!

**Comment by rsgonzal** [comment]
Looks great to me!
