### ISSUE TITLE
Upload new certificate templates [8,2,4]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2888]
Tickets for reference
- #2482
- #2501 & #2495 (still an issue?)

**Comment by rsgonzal** [comment]
New templates: https://www.dropbox.com/home/Distribution/Campaigns%2C%20Initiatives/2021/2021-Certificates/PlatformDistribution-fillable

**Comment by ophelieh** [comment]
The judge certificates looked good! I couldn't access student or mentor certificates from their respective profiles though.

**Comment by Judith-Ahumada** [comment]
I went into a student account and got the banner "job started to award Participation Certificate for Ozark Mountaineers, it may take some time to appear" Couldn't access the certificate either. Let me know if I did this wrong Rox, please
