### ISSUE TITLE
Generate Certificates June 23rd

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2890]
Reference 
- https://docs.google.com/document/d/12DZ5R1l2DiruHpWelABJfU_0Luroz0yatSGKgYfE4ms/edit?ts=6050fe6d&pli=1
- #2457

**Comment by rsgonzal** [comment]
> note: took a long time, was clunky. We should take another look at this way vs just-in-time cert generation.

**Comment by viviancan** [comment]
Rollback on QA is complete!

**Comment by viviancan** [comment]
tested this out locally with the `certificates:award_all_direct`. Certificates were generated for current season. Not sure if we will use this command for production though! Need to follow up

**Comment by viviancan** [comment]
Generated certificates on QA using the `award_all_direct` rake task. Went from 40 to 84 generated certificates for 2021 season

**Comment by rsgonzal** [comment]
clicked around a bit and certificates seem to be generated on QA!

Ready to generate on production whenever you are!
