### ISSUE TITLE
Run analysis of impact to drop scores 5/26 [8,1,8]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2892]
Note: started to do "what happens if we drop lowest scores" analysis for different scenarios, then Amy coordinated a manual review of scores, planned to check back Thursday or Friday

- Dev runs analysis of score dropping impact on team semifinalist selection (rake task)

reference #2463

**Comment by rsgonzal** [comment]
@viviancan just realized maybe we should have done this one first... can we still do this for quarterfinal scores?

**Comment by viviancan** [comment]
@rsgonzal I can change the semifinalists back to quarterfinalists and then run this
