### ISSUE TITLE
Mark teams as semifinalists 6/1 [13, 1, 13]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2893]
Dev (product@technovation.org) handle some requests to delete/enter paper scores

reference #2420 & #2538

documentation but unclear if that was the rake task: https://docs.google.com/document/d/16JIGMOrH2AINFWPy_8oi56TTsfvxRxxW_nEW8AptdUc/edit#heading=h.83tc79mgukqq

**Comment by rsgonzal** [comment]
QA Dry Run

1. Change contest rank for Ozark Mountains back to Quarterfinalist ( Want to have 0 semifinalist when we start)
2. Set these [semifinalists](https://docs.google.com/spreadsheets/d/1itA-bR3YfR_nWWfqnmW842JN3kwDZywBS75hUII2y1s/edit#gid=550085019)

**Comment by viviancan** [comment]
## To run rake task on production
`heroku run rake 'judging:set_contest_rank[contest_rank_here,comma-separated-list-of-submission-ids]' --app technovation`

**Note - do not include spaces in the arguments

![Screen Shot 2021-05-12 at 3.28.56 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/755499bb-fd4c-4cc6-937a-8311301a97ae)
