### ISSUE TITLE
Create html snippet of semifinalists for wordpress blog 6/2 [8,5, 1.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2894]
reference: #2462

"Note: some column formatting issues on the blog post. Need to manually select blog for highlight on technovation.org (and consider hero/slider feature)
- Can add link to blog post on technovationchallenge.org homepage as well"

**Comment by viviancan** [comment]
### Developer Notes
Routes
`    get '/semifinalist_snippet', to: 'semifinalist_snippet#show'
`

[Method for this feature](https://github.com/Iridescent-CM/technovation-app/blob/HEAD/app/controllers/admin/semifinalist_snippet_controller.rb)

**Comment by rsgonzal** [comment]
@mjaris [here](https://technovation-qa.herokuapp.com/admin/semifinalist_snippet.txt) is the snippet from QA data, won't be as complete as the original

can you please take a look and let us know how we can help with formatting options? Or if last year's semifinalist post is still up, maybe we can help make changes based off of that?

**Comment by jarism** [comment]
Last year's post: https://www.technovation.org/blogs/technovation-girls-2020-semifinalists/
This year's post: https://techstage19.wpengine.com/blogs/test-blog-2/
[password: semifinals21]

@rsgonzal I went through the slack history and I think the problem I ran into last year was trying to create more space between the Junior Division header and the first team listed. (You can see that in the junior + senior division screenshots) But when I added in the spaces, it broke the wrapper and the longer team names didn't wrap as intended (the first screenshot attached).

It doesn't appear to be as smushed this year [last screenshot attached] ... but maybe it was my edit that makes it look so smushed now. 

I would say it's hard to tell for sure without having multiple rows of countries in the jump links—would it be possible to add a little more test data? (Or maybe just add a **little** padding between the junior links and the table just in case, if that's easier)

And then the "Junior Division" is a little close to the bottom of the senior division table. Could we add a little space between the end of the table and the header?


![Screen Shot 2020-06-15 at 2 09 42 PM](https://user-images.githubusercontent.com/33399908/118059373-66ec6c00-b35e-11eb-9812-794523458623.png)
<img width="1179" alt="Junior Division-semifinalist-screenshot" src="https://user-images.githubusercontent.com/33399908/118059481-9f8c4580-b35e-11eb-9019-32b8764ca9e9.png">
<img width="1181" alt="Senior Division-semifinalist-screenshot" src="https://user-images.githubusercontent.com/33399908/118059482-9f8c4580-b35e-11eb-942a-399f87ec8a20.png">
<img width="1203" alt="2021 Draft Semifinalist-5-12" src="https://user-images.githubusercontent.com/33399908/118059936-a7001e80-b35f-11eb-9150-fe1198cb2f57.png">

**Comment by viviancan** [comment]
Additional margin was added above the Junior listing. We also decided to bold team names and italicize app names. When this is published live, text will be added stating team names are bolded and app names are italicized. I have also attached the custom CSS that was added to this page

```
#junior{
	margin-top: 5rem;
}

.sf-team-name{
	font-weight: bold;
}

.sf-app-name{
	font-style: italic;
}
```
![Screen Shot 2021-05-19 at 2.22.41 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/8a0a898f-a6ac-4303-82dd-332e33afc487)

**Comment by rsgonzal** [comment]
I think these updates are the other things you deployed? not sure how to test or if we need to before getting out that other fix?

**Comment by viviancan** [comment]
I checked this one this morning, by first marking a few semifinalists.

### QA Steps
1. mark a few teams as semifinalists
2. go to the endpoint `admin/semifinalist_snippet.txt`
3. check the HTML snippet. On the <td> elements you should see two added classes - `sf-team-name` and `sf-app-name`

```
<tbody>
	<tr class="semifinalist">
	  <td class="sf-team-name">Team Yi</td>
	  <td class="sf-app-name">Noodles Fun</td>
	</tr>
</tbody>
```
4. mark teams back to quarterfinalist (unless otherwise needed)

**Comment by rsgonzal** [comment]
Looks good!

**Comment by viviancan** [comment]
snippet update is deployed - waiting for semifinalist selection

**Comment by viviancan** [comment]
This was completed when semifinalists where selected
