### ISSUE TITLE
Add a link to the judge's profile page when viewing an individual score [5,1,5]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2901]
As an admin, when viewing an individual score, the judge name on that page should be a link that goes to the judge's profile.

![score-page.png](https://images.zenhubusercontent.com/605406304f05d34fb2dcbc8c/37b80737-2955-41e3-ae74-b851f47778f5)

**Comment by viviancan** [comment]
#2928

**Comment by rsgonzal** [comment]
Looks great! @mdancho check this one out! Came out of you doing the score monitoring session and having to jump around

**Comment by mdancho** [comment]
This is amazing! Thanks for catching this and following through on making it available this season :)
