### ISSUE TITLE
Display judge recusal info on judge profile page in the admin

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2902]
Display judge recusal information when viewing a judge in the admin.

Screenshot from #2556:

![Screen Shot 2021-03-22 at 9 21 16 PM](https://user-images.githubusercontent.com/22801026/112092442-bc717d00-8b54-11eb-8fd1-7ecc57aff88f.png)

## QA STEPS
* Login as an admin
* View a judge profile that has recusals
* Verify the recusal info there looks good

Note: the only way to see the comments for an "Other" reason right now (for this page) is to hover over the "Other" text and the comment will display in a little popup (we can change this functionality of course if we want to display it another way)

**Comment by viviancan** [comment]
Looks good to me! I was able to see the recusal information. 

The only feedback I have for this view is maybe bolding the column headers or having an underline to separate the headers? It took me a second to realize the first row did not have recusals! Maybe something like this?

![Screen Shot 2021-04-15 at 4 57 16 PM](https://user-images.githubusercontent.com/29210380/114943598-d88ed400-9e0b-11eb-9567-f588d5490ea9.png)

 Just an idea! Besides that everything worked for me!

**Comment by shaunxp20** [comment]
> Looks good to me! I was able to see the recusal information.
> 
> The only feedback I have for this view is maybe bolding the column headers or having an underline to separate the headers? It took me a second to realize the first row did not have recusals! Maybe something like this?
> 
> ![Screen Shot 2021-04-15 at 4 57 16 PM](https://user-images.githubusercontent.com/29210380/114943598-d88ed400-9e0b-11eb-9567-f588d5490ea9.png)
> 
> Just an idea! Besides that everything worked for me!

Cool, thanks for the feedback, Vivian! Great suggestion! 💯 (I had just copied the table/formatting from the quarter/semifinalist ones.) I made them bold (it almost seems too bolded, but that seems to be the style in the admin), and underlined, I think it's a little better now! 🤞 😅 😄

**Comment by shaunxp20** [comment]
This one is on QA including the styling tweaks, happy to make more changes too. 😄

**Comment by mdancho** [comment]
Admin is able to see recused submissions ![Screen Shot 2021-04-16 at 1.57.56 PM.png](https://images.zenhubusercontent.com/6079edcacd903ee7d1013cdf/a4016bb1-4f86-4fe8-bea1-3017ab408e01)

**Comment by amyiridescent** [comment]
Are there no judges who recused themselves on QA right now? It is not 100% clear to me how to find the judge / submission that has a recusal request...

**Comment by shaunxp20** [comment]
> It is not 100% clear to me how to find the judge / submission that has a recusal request...

Hopefully the recusals will be easier to find once we finish #2556, which will add the # of recusals to the scores list page, and show individual recusals on the score details page. 😃

**Comment by rsgonzal** [comment]
I actually like the hover!
