### ISSUE TITLE
Add help text just for thunkable submissions on judging

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2904]
As a judge, i need to know that I may not be able to access the thunkable code so that I can judge properly just using the demo video

Deliverable: 
1. Add a line of text, directing judges to look at the demo video 
- Can’t open the code? Thunkable may be experiencing some issues, please score using the demo video
2. This should only pop up if they are judging a thunkable submission

Mockup: https://app.mural.co/t/roxwork8740/m/roxwork8740/1618603555951/569d5a5051f5425e2e205f6f656b9d6e8a8e15f3

**Comment by viviancan** [comment]
Can view [PR here](https://github.com/Iridescent-CM/technovation-app/pull/2908)

**QA STEPS**
1. Login as admin
2. Select fully onboarded judge
3. Login as that judge and view list of team submissions
4. Select a team submission that is a Thunkable Submission
5. Click through the different score pieces - You should see the updated text on Review Submission and Techincal scoring pieces

![Thunkable Helper Text - Thunkable Project.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/2bd34e28-41bb-4b23-9fef-8820de066b63)

6. Select a team submission that is **not** a Thunkable submission
7. Click through the different score pieces - You should not see the updated helper text

![Thunkable Helper Text - Non Thunkable Project.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/154d6555-27c9-435c-917f-3b6f3c0c4c6d)

**Here are a few Thunkable Project Names on QA**

- My Great App
- So many Ideas
- Great app
- xx
- Screenshot app
- What what
- Best app
- Modeling subs
- Combo name
- Campaign Trails
- California poppies
- Wheel of Fortune
- Hello World
- Water Conservation
- Just a Girl

**Comment by rsgonzal** [comment]
Just commenting that I tested it and looks like it's supposed to :thumbs_up:
