### ISSUE TITLE
Share project using the projectPage instead of the copy url

### ISSUE THREAD

**Issue by Aboisier** [Iridescent-CM/technovation-app#2905]
**Is your feature request related to a problem? Please describe.**
My team uses Thunkable with a Firebase Realtime DB. In the past, sharing a project using a shareable link would keep all the API keys, including firebase configurations. Thunkable changed this behaviour recently; API keys are now stripped from shared projects, even though the shareable link creation dialog says the opposite (ref.: https://community.thunkable.com/t/api-key-lost-when-accessing-the-project-through-a-shareable-link/1226572/4). 

**Describe the solution you'd like**
We would like to be able to share the project using the project page link, which gives a read-only access to the project with the API keys obfuscated, but still working (ex.: https://x.thunkable.com/projectPage/5fd4684ae6919f3ff381bd46). 

**Describe alternatives you've considered**
We considered adding a screen with instructions for the judges on how to setup the app, but this seems tedious and error-prone.

**Additional context**
🤷🏻 

## QA STEPS
For submissions:
* Verify the old/exiting Thunkable URL format still works, e.g., https://x.thunkable.com/copy/xyz...
* Verify the new `projectPage` Thunkable URL works, e.g., https://x.thunkable.com/projectPage/xyz...

**Comment by shaunxp20** [comment]
Hi @Aboisier! 👋 

Thank you for you contribution! Unfortunately (as you already know), we weren't able to use it. Nonetheless, we appreciate you taking the time to create this issue and work on it! Thank you for putting in a PR to revert it too!

It was all very thoughtful, and we appreciate it very much! ❤️

**Comment by rsgonzal** [comment]
We might need to reopen this topic
