### ISSUE TITLE
Allow uploaded images to contain special characters

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2909]
When uploading a team photo (and I suspect other places too), if the filename contains a special character in it, it won't work.

`URI::InvalidURIError: URI must be ascii only`

**Steps to reproduce:**
* First, change the filename of an image locally to have a special character, e.g., `Без-имени-2.jpg`
* Then, as an on-boarded student, upload this file for the team photo
  * From the student dashboard, click "My Team"
  * On the left-side, under the existing team photo, click "Change image"
  * Upload the new team photo (with the special character in it) here

**Comment by dboyer** [comment]
Closing as this issue was rolled into #3501
