### ISSUE TITLE
Add an incomplete scores section to judge page in admin [3, 1, 0.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2911]
> Just FYI I can not see the assigned submission on the admin/participant/ page where I can see QF, SF and recused scores, this is only visible to an admin on the submission score page (not the judge page).

Hmm, we could add an "Incomplete Scores" section to that page that would show the assigned submissions. Right now we don't have a way to distinguish between an assigned submission and incomplete submission; when a score is assigned to a judge it falls into the incomplete bucket. Anywho, let us know if you want us to add an "Incomplete Scores" section, it wouldn't be too hard to do. 😄 🌞

<img width="1137" alt="Screen Shot 2021-04-20 at 12 26 13 AM" src="https://user-images.githubusercontent.com/22801026/115355009-1a52ae00-a16f-11eb-8415-38432c558110.png">

## QA Steps
1. View judge profile
2. Check scores section - Some scores will say "yes" or "no" in the completed? column
3. Login as the judge to verify the "nos" are still in progress

_Originally posted by @shaunxp20 in https://github.com/Iridescent-CM/technovation-app/issues/2883#issuecomment-821587407_

**Comment by rsgonzal** [comment]
- Add incomplete scores to show up under quarter final and semifinal scores
- add a column  between score and deleted? that says "Complete" -  "Yes" "No"

**Comment by viviancan** [comment]
![Screen Shot 2021-05-03 at 8.07.28 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/3458eaed-9c9a-4ff5-baf2-90fe291c46e2)

**Comment by viviancan** [comment]
## QA Steps
1. View judge profile
2. Check scores section - Some scores will say "yes" or "no" in the completed? column
3. Login as the judge to verify the "nos" are still in progress

**Comment by ophelieh** [comment]
Works as expected. Thank you! :)
