### ISSUE TITLE
Edit Judge dashboard to include new slack link [8, 1, 8]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2918]
Slack links expire in 30 days, current one has already expired and judges are not able to sign up on slack

Turns out in shows up in two places on the dashboard, not the email! Might me the same location in the code
![Screen Shot 2021-04-22 at 8.46.57 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/aca37708-61bd-408b-b667-4d16e8496372)
![Screen Shot 2021-04-22 at 12.39.10 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/5c6db679-2b67-4e3e-8c89-b83d96305bc2)

Text: Join our chat community for judges
New link: https://join.slack.com/t/technovationjudges/shared_invite/zt-p8r97yki-JGzdck~8TIx66RruP4f1mg

**Comment by viviancan** [comment]
Slack allows you to have a link that is active for more than 30 days. Is that something that would be helpful for this?

[Extend slack link](https://getlowdown.com/how-to-create-a-slack-community-and-landing-page-in-one-hour/#:~:text=Select%20%E2%80%9CShare%20invite%20link%E2%80%9D%20from,you%20wish%20to%20do%20so.)

- Waiting for text confirmation

**Comment by rsgonzal** [comment]
Thanks for that vivian! Mack got the new link and i updated the ticket with what is actually needed :)

**Comment by viviancan** [comment]
Will update the QA config variables 1st.
Technovation-qa > settings > reveal config vars >JUDGE_SLACK_SIGNUP_URL

**Comment by viviancan** [comment]
Updated on QA!

**Comment by rsgonzal** [comment]
It's in config!! 👌

**Comment by rsgonzal** [comment]
Thanks, vivian! I checked it and went ahead and updated it in production. This one is all done :)

**Comment by viviancan** [comment]
yay! 🎉
