### ISSUE TITLE
BUG: When resuming/reviewing scores, the previous score will briefly load [5, 13, .38]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2925]
As a judge when resuming a score or reviewing a completed submission, the previous score will briefly load, and then the correct one will load.

Steps to reproduce:
* As and admin, enable judging in the admin
* Then, login as a judge
* On the judge's dashboard, click "resume" or "review" on a few scores, you'll briefly see the previous one being loaded

https://user-images.githubusercontent.com/58957909/115626578-3bd9a400-a2ed-11eb-8296-4f5e30230b5f.mov

### QA Steps
1. Login as an admin and assign multiple submissions to a judge
2. Login as that judge and start one submissionn (1)
3. Do not finish the score and exit the submission
4. Start another submission (2)
5. You should not have seen the previous submission (1) flash on the screen
6. Exit that submission (2) and go back to open submission (1)
7. Again, you should not see previous submission (2) flash

**Also helpful to assign more than 2 submissions, and hop around between them**

**Comment by rsgonzal** [comment]
Adding other issue from #2883 

>only thing i'm noticing is that if i start both submissions at the same time. it brings be back to the last section i scored on the previous submission. not a huge deal

>so if i finish off on the entrepreneurship section for one submission, go to my dashboard and click on the next submission, it opens up on the entrepreneurship section. instead of review score which is where i should be on the second submission

**Comment by ophelieh** [comment]
Assigned 3 submissions for semifinals to judge Ala Lovelace (https://technovation-qa.herokuapp.com/admin/participants/735#/). It worked as expected. I did not see the previous submission flash. :)
