### ISSUE TITLE
Remove recused scores from incomplete scores

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2935]

**Comment by viviancan** [comment]
## Deployment Notes
After this change went to QA, we noticed the score counts for complete and incomplete were off. To fix this issue, we referenced notes [here](https://github.com/Iridescent-CM/technovation-app/issues/2466#issuecomment-620787995)

Run the following command
QA: `heroku run rake fix_counts --app technovation-qa`
Production: `heroku run rake fix_counts --app technovation`
