### ISSUE TITLE
Edit "in betweeen rounds" page for judges [13, 2, 6.5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2951]
When the platform is switched to "in between rounds" judges are shown a page with different dates and resources.

![Screen Shot 2021-05-12 at 5.07.00 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/b2180241-6224-4212-bff8-3526cd21aab9)

new text: https://docs.google.com/document/d/12cpYV0NXrfBCM-Oqbv955ZeGWQOTy97lL61qIWhUXJg/edit

**Comment by viviancan** [comment]
### Developer Notes

These are the items to change in the env file on heroku

```
DATES_CERTIFICATES_AVAILABLE_DAY=7
DATES_CERTIFICATES_AVAILABLE_MONTH=7
DATES_SEMIFINALS_BEGINS_DAY=2
DATES_SEMIFINALS_ENDS_DAY=16
```

**Comment by rsgonzal** [comment]
I changed the certificate date on qa & production, but i don't think the semifinal dates need to change?

**Comment by viviancan** [comment]
It may have been that my local ENV file was out of date with those changes! Also, realized this wasn't actually merged into QA. Taking care of that this morning!

**Comment by rsgonzal** [comment]
Looks good! Mackenzie approved
