### ISSUE TITLE
Change the way we generate certificates[8, 13, .62]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2952]
Currently, developer needs to bulk generate all of the certificates for the season. This process can be very clunky and time consuming.

Solution: Platform should generate certificates for individuals when they go in and try to view it for the first time or when an admin generates it for them.

![Screen Shot 2021-05-19 at 10.18.30 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/83be2f8b-c679-46f2-a1d6-5d45932b230e)
![Screen Shot 2021-05-27 at 10.54.49 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/7f98e34f-b4d5-4b02-b2f7-0f0030a76e46)
 
- Clicking on that button above for the first time would generate the certificate
- The platform should already recognize which certificate the participant should receive
- If an admin has already generated the certificate, when the participant clicks on the button it does not need to regenerate but just show the existing certificate

![Screen Shot 2021-06-08 at 2.56.10 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/6cdc5461-7f2d-4655-9131-5ee90d8df209)

**Comment by viviancan** [comment]
Looks like there may have been an "on-demand" certificate option in the past! 

https://github.com/Iridescent-CM/technovation-app/pull/2065

**Comment by viviancan** [comment]
PR #2971

**Comment by rsgonzal** [comment]
Tried for student, suzie gonzalez and doesn't seem to be working :(

**Comment by viviancan** [comment]
Update 7/1/21 - We are going to revisit this for next season. Currently working version for student on demand certificate generation. 

[On branch](https://github.com/Iridescent-CM/technovation-app/tree/2952-on-demand-cert-for-students)

Also - this current ticket is on QA and will need to be reverted

**Comment by viviancan** [comment]
rollback on qa is complete!
