### ISSUE TITLE
incomplete scores breaking when judge profile is deleted

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#2961]

**Comment by rsgonzal** [comment]
Details of deleted judge in QA are in #

**Comment by rsgonzal** [comment]
Looks good for the broken incomplete ones, like we talked about earlier the completed scores are still unviewable but maybe that fix can be for 2nd round.

Can we see if more judges have been deleted since scoring started?

**Comment by rsgonzal** [comment]
Created a judge account and scored for semifinals. all looks good, if you don't think any other checks are needed, we can deploy in the morning!

**noting we may want to show recusals by round on the scores page (the best best app has 8 recusals showing on the scores page right now even though it's filtering for semifinals, should work the way complete & incomplete scores show)

**Comment by viviancan** [comment]
Here is a [dataclip](https://data.heroku.com/dataclips/zicqknrsrtendawnsziloegehqpv) that has any submission scores that are associated with deleted judge profiles. The same information can be found in [this shared google sheet] (https://docs.google.com/spreadsheets/d/1t5fCug12nkrNqhQc-k4ECpePJdLZZlwqsYm2WFTueMU/edit?usp=sharing).

It appears that there are 9 submission scores that are affected. These 9 submissions scores come from a total of 3 real judge profiles + 1 test judge profile (Mackenzie). I have checked each of these score details pages on production and have gotten our error page. I will check them again, once production is updated with latest fix!

**Comment by viviancan** [comment]
I have manually checked each of the submission scores that are from a deleted judge profile and was able to see all of the score details on production 🎉
