### ISSUE TITLE
Edit scores & feedback dashboard tab [5,5,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2975]
This tab is currently repetitive. Edit to make more clear and show ranking for students

#2563 described ranking need

![Screen Shot 2021-06-16 at 10.16.03 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/385d89c9-af6d-48cb-824d-58323b5ce268)

If mentor page has different header, leave as is with plural certificates
![Screen Shot 2021-06-16 at 10.16.11 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/4cb816dd-78ee-47fc-ad91-22606d1e88e5)

**Comment by viviancan** [comment]
**QF View**
![QF - update.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/a6654520-9156-4178-b54b-335c44e70595)

**SF View**
![SF Update.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/d42cf7ce-5fba-402f-9d0e-0c6d8031c9b9)

**Mentor View**
![Mentor update.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/d8d29b93-f868-4e17-84e1-069d67716337)

**Comment by viviancan** [comment]
PR #2976

**Comment by rsgonzal** [comment]
QA done with #2854
