### ISSUE TITLE
Update close of season page

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2980]
Text edits: https://docs.google.com/document/d/1QcVKs7ZX29TMO9X0mH27ts9nGMPiXhPNVAPyDTioVf0/edit

![Screen Shot 2021-07-02 at 2.55.16 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/0aea7ce4-7dfa-4a78-bc9e-eb300e42f290)

**Comment by nickiredescent** [comment]
Thanks for your interest in Technovation Girls — we can't wait for you to be part of our global community!

Registration for Technovation Girls will open again in **late 2021**. Please sign up to receive a reminder email _**[Ages in this sign up page need to be updated]**_ when registration opens.

Until then, you can join the Technovation community by following:

 Facebook
 Twitter
 Instagram
 YouTube

> Want to learn about artificial intelligence (AI)? Learn to solve a problem in your community and build an AI prototype by signing up for our sister program, Technovation Families. _2 options to replace below_

**Option 1**
Want to learn about artificial intelligence (AI)? Stay tuned to see what the 2021 Technovation Girls season has in store!
_If we want to tease the up coming changes. I'm fine with the tease and I feel like this wording won't need any further editing until 2022._

**Option 2**
Want to learn about artificial intelligence (AI)? Learn to solve a problem in your community and build an AI prototype by **checking out** for our sister program, Technovation Families.
_If we don't want to tease anything, but also don't want to TF sign ups to distract from TG._

Let's learn and build a better world together!

**Comment by rsgonzal** [comment]
thanks @nickiredescent ! rebecca decided on removing the last part altogether :)

updates here: https://docs.google.com/document/d/1QcVKs7ZX29TMO9X0mH27ts9nGMPiXhPNVAPyDTioVf0/edit

**Comment by viviancan** [comment]
![Screen Shot 2021-07-12 at 11.14.47 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/eefaa40d-0eb7-4fe4-9ec8-9e9177fae84c)

**Comment by rsgonzal** [comment]
woo looks good! 👍🏼
