### ISSUE TITLE
Build out first four screens of sign up flow for students

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2992]
Deliverables: Build out front-end view of sign up screens for students (not fully functioning and communicating to back-end yet)
https://app.mural.co/t/roxwork8740/m/roxwork8740/1626711900843/66d183393ac259faba84540b52f26762894ffa15?sender=roxana1990

**Comment by rsgonzal** [comment]
Branding kit: https://www.dropbox.com/s/4oab7qc7r4usffs/BrandGuidelines-QuickReference.pdf?dl=0

**Comment by rsgonzal** [comment]
Slide 28 has links to dropbox with icons and other fun stuff: https://docs.google.com/presentation/d/1UsY0RT51vlxmgOsDW4QXpo04Ii_hswviJcNXEJe6Ehc/edit#slide=id.g5c4e2f21bb_6_383

**Comment by rsgonzal** [comment]
![Screen Shot 2021-07-29 at 5.39.04 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/458c48d7-173f-4edd-9b27-5eb3004af3bd)

**Comment by rsgonzal** [comment]
Update: Still require parent name for juniors & seniors

**Comment by viviancan** [comment]
I have the basic flow for UI completed. You can [see it here](https://tg-registration-sandbox.netlify.app/)

This registration flow is using Vue2, Vue-cli, and Vue Formulate for the forms.

I still need to capture form values, add in logic based on profile type, clean up the code, and then link it to the RoR backend. We will be able to configure that setup once the RoR upgrades are complete!

**Comment by viviancan** [comment]
The sandbox repo[ is here](https://github.com/Iridescent-CM/tg-registration-sandbox)
