### ISSUE TITLE
Make the consent process a 2 step process

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2993]
Students will need to be given consent for both being on the site (parent consent) and media.

Currently they are only given one consent form, they should be shown a second form after completion of the first.

Media consent is optional/ will be an opt out option

**Deliverables**
- Add a new "status bar" that displays the status of both forms, as shown in the screenshot/mockup below
- After a parent/guardian signs the parental consent form, they should then be shown the media consent form
- ~~After both the parental consent and the media consent have been signed, email both of them (together in one email as a PDF) to the parent/guardian~~ This will be done in #3045
- ~~Update the verbiage in the emails that get sent out~~ This will be done in #3039

![Screen Shot 2021-08-11 at 4.27.11 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/e33a1821-a118-49b8-b873-f266d7724ff8)

## QA STEPS
- Register as a new student
- After registering, send out a parental consent form
- Open and fill out the parental consent form
- **After submitting the parental consent form, verify you are presented with the media consent form and verify you can successfully submit it**

**Comment by rsgonzal** [comment]
media release for second step : https://docs.google.com/document/d/1meiULJGApyDqJx71mkuDNK_3h-gDk-WWj6OYymArGow/edit

**Comment by rsgonzal** [comment]
![Screen Shot 2021-08-11 at 4.27.11 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/e33a1821-a118-49b8-b873-f266d7724ff8)

**Comment by viviancan** [comment]
Related #2037 - Creating the templates for the consent forms

**Comment by rsgonzal** [comment]
Regarding questions, YES. We're going to want to update all emails, so it can be included in that work.

**Comment by shaunxp20** [comment]
Regarding moving the newsletter option to the media consent form: it would be easiest to leave this on the parental consent form because the value is stored with the parental consent in the database, in column `newsletter_opt_in`. We can update this value from the media consent of course, but leaving it where it is would be ideal. #JustFYI

**Comment by shaunxp20** [comment]
It looks like a completed/signed parental consent form gets emailed to the parents, do we want that same functionality for the media consent form too? 🤔 😃

**Comment by rsgonzal** [comment]
> Regarding moving the newsletter option to the media consent form: it would be easiest to leave this on the parental consent form because the value is stored with the parental consent in the database, in column `newsletter_opt_in`. We can update this value from the media consent of course, but leaving it where it is would be ideal. #JustFYI

This works for me!!

>It looks like a completed/signed parental consent form gets emailed to the parents, do we want that same functionality for the media consent form too? 🤔 😃

I'll add this to our notes. would it be possible to mail them together?

**Comment by shaunxp20** [comment]
> > It looks like a completed/signed parental consent form gets emailed to the parents, do we want that same functionality for the media consent form too? 🤔 😃
> 
> I'll add this to our notes. would it be possible to mail them together?

Like one email that includes both of them? Yeah, off the top of my head, we should be able to do that. 👍

**Comment by shaunxp20** [comment]
Also, another thought/question about students potentially signing the media consent form, on the form it does mention that parents sign if the student is under 18. Would there be cases where the students are signing them, if they're 18?

Regarding this two-step process, the parent mailer, etc. - it definitely would be easiest for parents to sign them 100% of the time, regardless of age, just to limit everything to one "flow" instead of introducing another flow where students are potentially signing them too. #AnythingIsPossibleThough! 😅

**Comment by rsgonzal** [comment]
Parents still sign even if they are 18.

**Comment by rsgonzal** [comment]
Yes to sending media consent confirmation w/email parents receive already with signed form

**Comment by shaunxp20** [comment]
> Yes to sending media consent confirmation w/email parents receive already with signed form

I looked at the parental consent confirmation email (the one they receive after the parental consent is signed), and that email has the signed parental consent inline (right in the email). It is not an attachment.

I think it would make most sense to turn this into a PDF, and then have one email sent with two PDF attachments (one for the parental consent and one for the media consent). We can do this of course, but then it's starting to feel too much for one ticket again. Another option, would be to send the media consent separately, and just have the signed media consent inline (just like the parental consent one is now). Or just add the signed media consent below the signed parental consent (basically just a wall of text). 😬 Anywho, a few options for us to discus/consider. 😃

**Comment by rsgonzal** [comment]
I like the first option! Opened #3045 for that

**Comment by shaunxp20** [comment]
Regarding the initial email the parent/guardian receives, from there, there are two flows to consider:
- just handling one flow: initial email -> parental consent -> media consent -> send out email confirmation
- or handling above **and** the potential for: initial email -> media consent -> parental consent -> send out email confirmation

It basically depends on the links/text in the initial email. If there is just a link to the parental consent form (the link/button text can say something like click here to fill out the parental and media consent forms), we just have to worry about the top flow. But if we want a link to both the parental and media consent, then we'll have to handle both flows.

Anywho, just need to know which direction to take. 😄

**Comment by rsgonzal** [comment]
I think just one flow. The first email should say click here for parent & media consent and then they'll be presented one after the other.

**Comment by shaunxp20** [comment]
> I think just one flow. The first email should say click here for parent & media consent and then they'll be presented one after the other.

Cool, thanks! I like it, keeps things simpler this way. 👍 😁

**Comment by shaunxp20** [comment]
As we discussed, I updated/reverted this, so that after the parental consent gets signed, the existing emails (one to the student, and two to the parents) will get sent out (same functionality as it is now). I just need to test it a little bit more to make sure it's working as it should.

I also created #3061 so the parent/guardian can get a copy of the signed media consent form.

**Comment by shaunxp20** [comment]
This one is on QA, I added some very basic QA steps too. 😃
