### ISSUE TITLE
Update Mailchimp for beginners division

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3001]

**Comment by rsgonzal** [comment]
Parent registered flag would be easier to send over

**Comment by rsgonzal** [comment]
I think passing over the parent registered flag will work. the targeted email groups are:

1. parents/students ages 8-12
2. students 13-18
3. parents of students 13-18

**Comment by shaunxp20** [comment]
What profile type identifier do we want to use/send to Mailchimp for 1 and 3?
>     1. parents/students ages 8-12
>     3. parents of students 13-18

Some background for the question that is coming: currently when students register, they will automatically get added to Mailchimp. When a parent/guardian fills out a parental consent, and checks the box to subscribe, then they will get added to Mailchimp.

Should we add number 1 automatically or only if they check the box on the parental consent form?

**Comment by rsgonzal** [comment]
1 should be automatic. I know that checkmark is confusing for people in this group but not sure how to get around it right now 🤦🏻‍♀️

**Comment by rsgonzal** [comment]
also don't know if that will impact if they decide to uncheck it..

**Comment by shaunxp20** [comment]
> 1 should be automatic.

Cool, sounds good, will do!

What profile types should we send to Mailchimp for 1 and 3? And/or are we sending a new attribute over?

> 1. parents/students ages 8-12
> 3. parents of students 13-18

**Comment by shaunxp20** [comment]
Oh, re-reading! 😊 I see:

> I think passing over the parent registered flag will work. 

So, we'll be adding this one, right? And then how should the profile type look like in Mailchimp?

**Comment by shaunxp20** [comment]
> 1. parents/students ages 8-12

> And then how should the profile type look like in Mailchimp?

Should we send the parent's name over? Or the student's? 🤔 🤨 I think that would determine the profile type.^

**Comment by rsgonzal** [comment]
> > I think passing over the parent registered flag will work.
> 
> So, we'll be adding this one, right? And then how should the profile type look like in Mailchimp?
>Should we send the parent's name over? Or the student's? 🤔 🤨 I think that would determine the profile type.^

yes! My gut tells me we should send both... there is a column for parent name and email but i don't think we ever actually passed that info? I think the emails will be directed to the parents, maybe we should ask program team!

**Comment by dboyer** [comment]
@ksrebecca Two questions:

1. For a beginner account, is it helpful to have both the student's name and the parent's name and email sent to Mailchimp? Or just the parent's name and email.

2. Will emails to beginner division primarily be directed to the parents?

**Comment by rsgonzal** [comment]
the plan shaun is going to implement:
- beginners will be added as a student like other students (student tag)
- we will add a parent name field only for beginners in case you're addressing parents
- there will be a "parent registered" flag to identify them as under 13

**Comment by shaunxp20** [comment]
> the plan shaun is going to implement:
> 
>     * beginners will be added as a student like other students (student tag)
> 
>     * we will add a parent name field only for beginners in case you're addressing parents
> 
>     * there will be a "parent registered" flag to identify them as under 13

These changes are on their way to QA now, I only loosely the various scenarios.

The Mailchimp list is a little complicated now, but w/ these changes we should be able to identify:
* beginner students (student tag, parent registered is true)
* regular (jr/sr) students (student tag, parent registered is false)
* beginner parents (student tag, parent registered is true; and the parent name is in a new "parent name" column)
* regular (jr/sr) parents (parent tag; these are parents who opt-in when signing the parental consent form)

**Comment by shaunxp20** [comment]
For beginner parents, I think we remove the newsletter opt-in checkbox from the parental consent form - these parents will automatically get added (during the "register to season" job). If we leave it there and they opt-in, it won't do anything (Mailchimp will actually throw an error b/c the email address is already on the list), but if they opt-out, we don't have the functionality to remove them from the list, we'd have to add that functionality. I think at this point the easiest thing would be to remove it. I could incorporate it into the rebrand work when I get to it. 👍 👎 💭

**Comment by rsgonzal** [comment]
> For beginner parents, I think we remove the newsletter opt-in checkbox from the parental consent form - these parents will automatically get added (during the "register to season" job). If we leave it there and they opt-in, it won't do anything (Mailchimp will actually throw an error b/c the email address is already on the list), but if they opt-out, we don't have the functionality to remove them from the list, we'd have to add that functionality. I think at this point the easiest thing would be to remove it. I could incorporate it into the rebrand work when I get to it. 👍 👎 💭

if we could remove it from just beginner students, that sounds like a great plan!

**Comment by shaunxp20** [comment]
> if we could remove it from just beginner students, that sounds like a great plan!

The subscribe checkbox on the parental consent should be removed for parents of the beginner division - can't remember if I mentioned that or not (or if it was QA'ed).  #JustFYI

**Comment by rsgonzal** [comment]
> The subscribe checkbox on the parental consent should be removed for parents of the beginner division - can't remember if I mentioned that or not (or if it was QA'ed). #JustFYI

you did! i had QAd it and it works!
