### ISSUE TITLE
Need to make sure pitch video and demo videos are not identical urls

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3014]

**Comment by dboyer** [comment]
Checked on QA and confirmed that I could not enter the same URL for both videos. I tested on both a new submission and existing submission and was stopped from saving a duplicate URL in both cases.

**Comment by dboyer** [comment]
One edge case identified during QA. My feeling is that it is not worth fixing this.

1. Enter a URL for the pitch video
2. Go to the demo video and add the same URL but delete the last character
3. The page will allow you to save those videos and both play as expected

In the example for the team "mon equipe" on QA, the last characters are =3s which perhaps refers to 3 seconds? I don't this is terribly likely to occur and I'm okay with pushing this issue to prod with this edge case still in place. What are your thoughts @viviancan
