### ISSUE TITLE
Update Mentor registration UI

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3034]

**Comment by rsgonzal** [comment]
![Screen Shot 2021-09-22 at 10.30.08 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/7e11c299-d407-4134-97be-02f06a1df34b)

**Comment by rsgonzal** [comment]
- add message to top
- include all the fields we currently collect for mentor registration

**Comment by rsgonzal** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3034?planning-poker) with ZenHub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Follow up ticket (need to create still) - Will need to update the backend logic that creates accounts to account for new mentor flow

**Comment by viviancan** [comment]
What are these options supposed to be?

![Screen Shot 2021-09-27 at 2.25.15 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/5beea1e6-4938-41ea-823f-838394581676)

**Comment by rsgonzal** [comment]
![Screen Shot 2021-09-28 at 9.50.44 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/8a953d4f-08fb-4e77-ab3d-f80ea261edd5)

**Comment by viviancan** [comment]
For the "How did you hear about technovation" is it a drop down with options or an open text field? On the original mockup it looks like a text field, but for mentor registration it looks like a drop down.


Original
![Screen Shot 2021-09-28 at 5.43.32 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/56cf89b4-8502-4e32-94bd-962ecc4ab5d9)

Mentor
![Screen Shot 2021-09-28 at 5.43.14 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/94af9859-0bf1-4255-b0b3-2f5294d5fd37)

**Comment by rsgonzal** [comment]
It should stay as a dropdown! Thanks!

**Comment by viviancan** [comment]
Update 9/30/21 - Mentor updates are mostly complete! I am going to switch gears and start reviewing the backend logic for creating the mentor account #3058 

I am also going to add the pending tasks for this ticket to the running list of random clean up tasks #3053

**Comment by viviancan** [comment]
https://images.zenhubusercontent.com/29868115/ec9345cf-d4fc-4b3e-a44f-c6628df99f42/screen_recording_2021_09_30_at_11_20_14_am.mov

**Comment by dboyer** [comment]
@shaunxp20  Does the work in #3082 apply to the front-end validation needed here too? Or does this remain an open task since it is related to mentors and not students?
