### ISSUE TITLE
LearnWorlds SSO

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3037]

**Comment by rsgonzal** [comment]
- Single sign on
- reference #2878

**Comment by shaunxp20** [comment]
This one is on QA. I just tried it w/ an account and it works, but we might run into some issues. For example, when I test it locally w/ Rolo Dog, I get an error about the email address is already registered, but if I understand the docs correctly, it should still work, anywho, it might be something we'll have to contact them about. Since there are still some kinks to work out, I'm going to leave it "In Progress" for now; I also would like to write some tests for it (but I'm not sure that is going to happen before we open registration).

**Comment by shaunxp20** [comment]
Just leaving in a note for Monday - another thing I would like to know from LearnWorlds is what error we would receive for an expired access token. We're caching the access token so we don't have to fetch one for every SSO request, but at some point we'll get an error about the token being expired (the token is good for 1 year btw), at that time we need to refresh the access token. To cover this for now, we're refreshing the access token for any error coming back from an SSO call (not limiting it to the specific error message), which is fine for now, imho. 😄

**Comment by dboyer** [comment]
Tried to access the LearnWorlds curriculum with two accounts this morning and received the same error for both:

<img width="1272" alt="Screen Shot 2021-12-06 at 9 46 40 AM" src="https://user-images.githubusercontent.com/516764/144866615-3805c1dc-8a3f-4852-94d8-c590303216d9.png">

One error was with a newly created account in the beginner division and one with a newly created account in the junior division. I had completed location and parental consent tasks on both accounts.

**Comment by rsgonzal** [comment]
alright some findings/questions:
1. SSO errors
- there does seem to be a pattern with accounts with +x shooting back an error with SSO
- these accounts are created in Learn Worlds but SSO doesn't work
- I reset my password on learn worlds directly and it let me create a password for my +x account
- so it does look like it recognizes these accounts but for whatever reason SSO is breaking
- I'll email them about this

2. There were no courses on my dashboard when I successfully got in
- Course was marked as private
- Karen made it not private but there is a two step process to enroll, she is asking Rebecca if there is any concerns if it's public
- @shaunxp20 , we were wondering if there was anything about enrolling in courses in the SSO documentation?

**Comment by shaunxp20** [comment]
>     2. There were no courses on my dashboard when I successfully got in
> 
> 
>     * Course was marked as private
> 
>     * Karen made it not private but there is a two step process to enroll, she is asking Rebecca if there is any concerns if it's public
> 
>     * @shaunxp20 , we were wondering if there was anything about enrolling in courses in the SSO documentation?

I think this might be what we're looking for:
https://docs.learnworlds.com/?shell#enroll-a-user-to-a-product

Looks like we need e product id for the course:
https://support.learnworlds.com/support/solutions/articles/12000047703-how-to-find-the-id-of-your-product-course-bundle-id-

If someone can PM that, I can try it at some point... 😄 ⏲️ 😅

**Comment by shaunxp20** [comment]
This one was deployed to production already - including the auto-enrollment stuff.

There's definitely some follow up work though - w/ the "email already taken" issue, the token expiring issue, some code cleanup and testing too. All that will have to come later in separate tickets.

**Comment by rsgonzal** [comment]
looks good in production!
