### ISSUE TITLE
Complete groundwork for account information with new registration

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3041]
- understand how the current flow is working, is it all during sign up or sometimes during onboarding
- create a matrix of old vs new
- identify followup tickets

**Comment by rsgonzal** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3041?planning-poker) with ZenHub @shaunxp20

**Comment by rsgonzal** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3041?planning-poker) with ZenHub @viviancan

**Comment by viviancan** [comment]
Some basic notes on current registration flow

![CurrentRegistrationFlow-9:9:21.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/ac25bfd0-d2b3-4e60-8381-affcc1bc74e1)

**Comment by viviancan** [comment]
Some questions popped up during the investigation
- Are we still going to use the `signup_attempt` in the current registration flow
- A few concerns about refactoring what is currently there, in case it is part of other workflows. Should we leave the original code part of the current registration flow, and then  copy/refactor what we need in separate controllers for now?

**Comment by viviancan** [comment]
Working on a few follow up tickets
- Fix redirect/sign in after successful account creation for new-registration 
- Other registration flows will need to be finalized
- Onboarding process will need to be updated to account for missing information (like geolocation) from the initial registration flow

**Comment by shaunxp20** [comment]
>     * A few concerns about refactoring what is currently there, in case it is part of other workflows. Should we leave the original code part of the current registration flow, and then  copy/refactor what we need in separate controllers for now?

I think that makes sense, if I'm understanding correctly - current registration would be track A, leave that in place, create a new track B for the new registration, and then at some point in the future before the new registration goes live, delete track A, and move track B to track A? Something like that? 🤔 🚂 🚄 (the bullet train is the new registration 😃)

**Comment by viviancan** [comment]
love that analogy, yes train A and train B!

**Comment by viviancan** [comment]
Current Onboarding Flow
- Logged in and had to set location information again
- /student/dashboard/parental_consent 
    --> Inputs for parent name and email
    --> Email gets sent to parent, there is a button in the email that directs parent to sign form
- Parent pushes email and is directed to `/parental_consent/edit?token=___________`
- Parent agrees
- 2 Emails are sent - student and parent (parent gets a copy of consent info)
- App redirects to `/parental_consents/<#here>`

**Comment by shaunxp20** [comment]
>     * Are we still going to use the `signup_attempt` in the current registration flow

Good question! I vaguely remember a conversation about how TG saves incomplete registrations (which is what I assume this is for), and how TF only saves complete registrations (so there aren't any incomplete registrations stored in the database). 

Anywho, not my call to make, but I think my vote would be to get rid of them, seems like it's just complicating things, and for little value. With the new simple registration flow - if you can't finish or something happens to your internet connection or something, it's not that hard to just to start it over, it's not like filling out a tax form or something! 😅 😁 📝

**Comment by rsgonzal** [comment]
created #3050 #3049 #3048
