### ISSUE TITLE
Create new student accounts with new registration

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3044]
- wire up what the new registration currently collects to the accounts table

Followup from #3041

**Comment by shaunxp20** [comment]
> The new registration flow has the parent's first and last name in separate fields, but in the database (currently) it's one field.
> 
> Just confirming, do we want to have those as separate fields?

Just following up w/ this, it was decided on stand up to leave them as one field. I updated the new registration flow to accordingly. 👍

**Comment by shaunxp20** [comment]
> Oh I see the question. @rsgonzal @shaunxp20 the ideal scenario I think in this case is to verify the student age so that we know they belong in the Beginner Division (8-12). If the parent is trying to register an older student then I think they should have to go through the flow for the older students but how can it be clear to them to put in, for example, student info instead of parent? Does that make sense?

I added #3081 to handle the age verification stuff. 👍

**Comment by shaunxp20** [comment]
> Is there any reason why chapter ambassadors can't also get a random avatar from?:

> i don't think so! @ophelieh anything you can think of?

> I think it might have been done to differentiate the profiles in some way, but I don't see an issue with it pulling from the same place for chapters as it does for all other participants.

Thanks for the feedback, I made the change so ChAs will get an avatar as students/mentors/judges do, it will just need to be QA'ed. 😄

**Comment by shaunxp20** [comment]
I added #3082 to handle validation errors.

**Comment by shaunxp20** [comment]
When a student is registering, are they supposed to provide their parent's email address? I remember something about capturing the parent's info for the consent forms - right now, we're just capturing their name, but not their email address. 🤔 😄

**Comment by shaunxp20** [comment]
I added #3083 to update our email validation for the beginners division.

**Comment by rsgonzal** [comment]
> When a student is registering, are they supposed to provide their parent's email address? I remember something about capturing the parent's info for the consent forms - right now, we're just capturing their name, but not their email address. 🤔 😄

Yes! Created #3090

**Comment by dboyer** [comment]
@ksrebecca See above comment indicating that we'll keep division assignments for mentors and judges for now in the interest of making registration available on the planned timeline. I've added division assignments to a list of things to potentially revisit when we discuss changes to the judging process.

**Comment by ksrebecca** [comment]
yep! totally fine, since none of us have ever even realized this i am guessing it does not impact users negatively one way or another!!
