### ISSUE TITLE
Deploy Rails Upgrade #2872

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3046]
Before #2872 gets deployed we need to:

- [Update error message in s3](https://devcenter.heroku.com/articles/error-pages#customize-pages)
- Create Rollback plan

After deployment we need to:

- Do some general QA on production
- Try Checkr
- Do activities that will trigger jobs (emails)
- Revert custom error message

**Comment by shaunxp20** [comment]
I see that Heroku has a [maintenance mode](https://devcenter.heroku.com/articles/maintenance-mode) and an associated maintenance mode page. I'm learning about all of this as we go, but I think one way to go about it would be to turn on maintenance mode, do the upgrade, and then turn off maintenance mode. 

Here is a link to customizing the error/maintenance pages:
https://devcenter.heroku.com/articles/error-pages#customize-pages

Also, I randomly stumbled on [Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps):

> Review apps run the code in any GitHub pull request in a complete, disposable Heroku app. Review apps each have a unique URL you can share, making them a great way to propose, test, and merge changes to your code base.

> You can configure review apps to spin up automatically for each pull request, or you can create them manually from your app’s Pipeline page in the Heroku Dashboard.

I think this could be really useful!!!

**Comment by shaunxp20** [comment]
Looks like updating the error page is pretty straight forward.

There is a Heroku configuration setting named `ERROR_PAGE_URL`, this specifies where the error page is in S3: `//s3.amazonaws.com/technovationchallenge.org/error_pages/server_error.html`

To update this in S3:
- Login into AWS
- Navigate to S3 (click Services -> Storage -> S3)
- Under Buckets, click "technovationchallenge.org", and then "error_pages"
- Then `server_error.html` will be there to update

We can add another Heroku setting and associating page for `MAINTENANCE_PAGE_URL`.

We just need the verbiage for both the error page and maintenance page, and updating/adding them shouldn't be a problem. 👍 😃

**Comment by shaunxp20** [comment]
Regarding rolling back, the commit before the Rails upgrade, and where Production is at now, is: `1ea023448`.

So, if we need to rollback, I think we can either:
- Leave our commit history unchanged and run something like: `git push production 1ea023448:master`, to put Production back to where it is now
- Or update our commit history, by resetting back to `1ea023448`, and then that can go through the normal deployment steps (QA -> Prod)

**Comment by shaunxp20** [comment]
Next steps for this one, I think we just need a day/time for the deployment and also a message regarding the deployment (for the error page), and then I think we'll be ready to do the deploy, and whatever comes out of that! 😅

**Comment by rsgonzal** [comment]
What about just replace the regular text with something like:

We're sorry, but the site is currently down for a scheduled update please check back in 12 hours.
