### ISSUE TITLE
Send parent/guardian a confirmation email after media consent is signed

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3061]
After the media consent is signed, send the parent's a confirmation that has a copy of the signed media consent form.

Email is at the top of this doc: https://docs.google.com/document/d/1SHFC6IpjfBnM4HC1wHN6AGGW1tKR4TncKPlDy-7J9tc/edit#

**Comment by rsgonzal** [comment]
Email is at the top of this doc: https://docs.google.com/document/d/1SHFC6IpjfBnM4HC1wHN6AGGW1tKR4TncKPlDy-7J9tc/edit#

**Comment by shaunxp20** [comment]
The parental consent email has a Spanish translation for the subject line. Can I get something for the subject line for the media consent one? 😅 😄 

The parental consent one is: "Technovation — Copia del formulario de consentimiento firmado"

**Comment by rsgonzal** [comment]
after a consultation, i got: "Technovation — Copia firmada del formulario de consentimiento para medios de comunicacion"

**Comment by dboyer** [comment]
I went through this process on staging and successfully received a copy of the media consent form. However, I had selected that I did not provide consent. The copy of the consent form I received was the standard media consent form text but with no indication that I had not provided consent.

@rsgonzal Could you try this as well? I want to make sure someone else can replicate it.
