### ISSUE TITLE
Clean up UI on other pages of *Student* My Profile section

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3071]
![Screen Shot 2021-10-20 at 9.43.25 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/b61e8f3c-eaa4-4bba-82fb-7c8bb4b1a9b1)

**Comment by viviancan** [comment]
Missing mockups for Parental Consent tab for the following conditions:
- Parental Consent is signed
- Parent guardian email is blank

I can also just give them a very basic style/container to match what the other rebrand!

**Comment by viviancan** [comment]
For the "location" tab, I have both versions of the view - the form component to set the location information and also the component that shows current location details. Once we have the logic completed we can conditionally render the specific view. We will also need to update the "change your location" view. 

![Screen Shot 2021-10-20 at 6.05.30 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/8730ab83-f25a-44b9-9a4f-67229c73fd81)

**Comment by viviancan** [comment]
Update 10/21/21
All of the individual tab views are completed. I added the changes on to the 3035 branch found [here](https://github.com/Iridescent-CM/technovation-app/tree/3035-updated-student-my-profile)

**Comment by viviancan** [comment]
I am currently working through the failed tests ~36 failed tests for the student rebrand! It seems that they are mostly due to different ID names and missing links
