### ISSUE TITLE
Age verification for new registration flow

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3081]
- Parents can only register students between 8-12 (for the beginners division)
- Students can only register if they are > 13 and < 18
- Mentors can only register if they are > 18

If one of these age validations fails, display an error and disable the Next button.

**Comment by rsgonzal** [comment]
@ksrebecca what is the date for the age cutoffs?

**Comment by ksrebecca** [comment]
ah sorry just getting to email! August 1 2022

**Comment by shaunxp20** [comment]
I added some age validations - if validation fails, a red error message beneath the field (like our existing validation messages are) will appear, showing one of these messages:

A student must be 8-12 years old to participate in the beginners division.
You must be 13-18 years old to participate as a student.
You must be at least 18 years old to participate as a mentor.

It's on QA now to look at. I might/plan to come back and clean up some code and write some tests, but for now I just wanted to get it on QA for some feedback. 😄

**Comment by dboyer** [comment]
@shaunxp20  Ran through this on QA and I'm getting the correct validation errors. However, I think it is using the date the person registers instead of 8/1/22 as the age verification date. For example:

1. I selected beginner division
2. I entered a birthdate of 5/12/2009
3. The user would be 12 today but 13 on Aug 1, 2022
4. I was able to successfully register in the beginner division

**Comment by shaunxp20** [comment]
>     3. The user would be 12 today but 13 on Aug 1, 2022

Ah! Looks like we didn't update the new division cuttoff date yet, I just updated it now!

For reference, in Heroku:
technovation-qa app -> Settings -> Show Config Vars -> DATES_DIVISION_CUTOFF_X

Anywho, it should be good now! Let me know if it works!

I only updated QA too, btw.

**Comment by rsgonzal** [comment]
i will update the date on production!

**Comment by shaunxp20** [comment]
> i will update the date on production!

Awesome, thanks @rsgonzal! 🙌
