### ISSUE TITLE
Display validation errors returned from back-end

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3082]
When a new account is created via the new registration flow, if there are validation errors (like the email address isn't unique), we need to handle this on the front-end. Right now, the errors are being returned from the back-end to the front-end via a JSON response - we need to do something w/ that response on the front-end.

**Comment by viviancan** [comment]
https://vueformulate.com/guide/forms/error-handling/#form-error-handling

**Comment by rsgonzal** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3082?planning-poker) with ZenHub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Linking shaun's comment from #3080 

> Random note - this is where we'll need to hook up the errors to Vue Formulate. I noticed we'll have to make some tweaks though b/c the keys in the error messages need to correspond to the form field names. And right now the form field names are camel cased and what's returned from Rails would be snake case.

https://github.com/Iridescent-CM/technovation-app/pull/3080/files#r743183484

**Comment by shaunxp20** [comment]
I have the basics hooked up, so the back-end validation errors will get surfaced/displayed under the form field that had the error.

But, for example if there is an error w/ the parent/guardian email address (which is not currently hooked up) which is not on the same page as the submit button, they won't get redirected to that page. I'm not sure the best way to handle this yet b/c there could be two errors, one on the page w/ the submit button and another error on another page. Maybe a generic error message that says to check each page? Anywho, something to think about since it will probably surface at some point (after we get the parent/guardian email address hooked up).
