### ISSUE TITLE
Update email validation for beginners division

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3083]
For the beginners division, the account's email address is supposed to be the same email address used for the parental/media consent forms. Currently, we have a validation in place so that the consent form email address can't be the same as the account's, b/c it would allow students to provide their own email address for the consent forms. We'll need to update this validation to handle the beginners division.

**Comment by rsgonzal** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3083?planning-poker) with ZenHub @shaunxp20 @viviancan

**Comment by rsgonzal** [comment]
Need to test:
- Returning student or current student in junior senior division attempts to enter a parent email that has been used on a beginner account

**Comment by shaunxp20** [comment]
I can work on this back-end validation piece.

But for this part:

> Need to test:
> 
>     * Returning student or current student in junior senior division attempts to enter a parent email that has been used on a beginner account

Thoughts on creating a new support ticket (like we used to have), and adding it to that? And/or making it lower priority for now (removing it from this ticket)? 🤔
