### ISSUE TITLE
Fix CircleCI builds

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3084]
The Node version on our CircleCI image got upgraded to version 16.

Here's where which CircleCI image we're using is specified:
https://github.com/Iridescent-CM/technovation-app/blob/134dd7ac22b6e519d4f755228c065e869c11d840/circle.yml#L7

This image was updated (last night) to Node version 16,
on line number [37](https://hub.docker.com/layers/circleci/ruby/2.7.4-bullseye-node-browsers/images/sha256-0c6c0996160948a2ca5e534d7ed688578cf448b2ad6556509d7f9b54d00f7fd2?context=explore)

Updating to version 16 is breaking other things that need to be figured out.

**Comment by shaunxp20** [comment]
A little recap of this one... our CircleCI image was updated to Node version 16, so I updated Node to version 16, but then our node-sass module broke, b/c the version we were using isn't compatible w/ Node 16. 🤯 Wepacker uses node-sass, so Webpacker had to be upgraded so node-sass could get upgraded/fixed. 🤕 

Some info on Node and node-sass compatibility:
https://stackoverflow.com/a/67778126

And some info (similar to our situation) about needing to update Webpacker:
https://stackoverflow.com/a/67499942

And then after updating Webpacker, a test was randomly failing, which I commented out (marked as pending) to keep things moving along. 🥺 

` spec/javascript/components/IntegerInput.spec.js`

**Comment by shaunxp20** [comment]
A brief update on this one... earlier today I said this was on QA, but it wasn't, doh! 🤦 The deploy to QA failed, I didn't notice until Vivian pointed it out to me! 🤦 😊 😅 Well, now _it is_ on QA (after another update)... but we have a new issue: the images on the new registration form aren't working; which Vivian also saw when she tried the upgrade locally. We thought it was only a local issue (b/c I thought QA had been deployed successfully), but it's an issue both locally and on QA. We have both been trying to troubleshoot this, but don't have a solution yet. 🥺 🤕 🤒

**Comment by shaunxp20** [comment]
A potential fix for the images...

Adding this setting to `webpacker.yml`:
```
resolved_paths:
  - app/assets/images
```
https://rossta.net/blog/how-to-use-webpacker-yml.html#additional_paths

Which basically means moving/keeping our images in `app/assets/images`.

And then the images can be referenced like:
` <img id="tg-logo" :src="require('tg-girls-logo.png')" alt="Technovation Girls Logo" />`

I verified this locally and it works, if we want to go w/ this approach. 🤔 😄

**Comment by shaunxp20** [comment]
Vivian shared this w/ me yesterday (regarding other options):
https://gorails.com/forum/how-do-i-use-images-inside-my-vue-single-file-components

Vivian and I will get together and discuss and pick an option. 👍 😄

**Comment by viviancan** [comment]
Just a follow-up on this! We are going to go with this approach. I will work on fixing broken images after solving tailwind issue for the student "my profile" tab.

I will highlight a few things about tailwind issue on #3055 since it is a similar bug that I faced previously on that ticket.

**Comment by shaunxp20** [comment]
@viviancan Some random notes:

When webpacker was updated, it updated webpack from version 4.42.1 to version 4.46.

Here are the release w/ notes for webpack:
https://github.com/webpack/webpack/releases

And here are the releases that apply to us:
https://github.com/webpack/webpack/releases/tag/v4.43.0
https://github.com/webpack/webpack/releases/tag/v4.44.0
https://github.com/webpack/webpack/releases/tag/v4.44.1
https://github.com/webpack/webpack/releases/tag/v4.44.2
https://github.com/webpack/webpack/releases/tag/v4.45.0
https://github.com/webpack/webpack/releases/tag/v4.46.0

This popped out to me in 4.44.0:
> add support for resolve.roots and default resolve.roots: [context]
>
>    This allows to resolve server-relative urls (e.g. /src/abc) to the project root (or other locations when configured)
>    This allows to use loaders that rely on that behavior

Anywho, nothing that really needs to be looked at further right now, just putting in some notes/links for posterity. 😄

**Comment by shaunxp20** [comment]
(Just assigning both of us to this one since we've both been working on it.)

**Comment by shaunxp20** [comment]
Images should be fixed now on QA; moving this one to the QA column. :smiley:
