### ISSUE TITLE
Create new welcome email for beginner accounts

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3086]
- Need the [content](https://docs.google.com/document/d/1SHFC6IpjfBnM4HC1wHN6AGGW1tKR4TncKPlDy-7J9tc/edit#heading=h.pb4yyul5mbgh)  - page 11
- Hook up just for beginners

**Comment by rsgonzal** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3086?planning-poker) with ZenHub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
I don't see page 11 in that doc (for the welcome email for beginners). 🤔 😖 😭

**Comment by rsgonzal** [comment]
Can you see [this](https://docs.google.com/document/d/1aOZ7CpE4AAh8zGV82cBLJ6oBhTu02yyzNeDdw2My5Cw/edit#heading=h.lhpg62soxnz)?

**Comment by shaunxp20** [comment]
> Can you see [this](https://docs.google.com/document/d/1aOZ7CpE4AAh8zGV82cBLJ6oBhTu02yyzNeDdw2My5Cw/edit#heading=h.lhpg62soxnz)?

Yes, thank you!!! 👍 🥳 🎉

**Comment by shaunxp20** [comment]
Just confirming, are these changes are for the "welcome" email the parents receive (the one they receive 3 days later)?

The email in the [doc](https://docs.google.com/document/d/1aOZ7CpE4AAh8zGV82cBLJ6oBhTu02yyzNeDdw2My5Cw/edit#heading=h.lhpg62soxnz), shows the thank you email from:
`app/views/parent_mailer/thank_you.en.html.erb

And based on the edit history, it only includes one new paragraph.

Is this basically just adding one paragraph to the "thank you" email? 🤔 😅

**Comment by rsgonzal** [comment]
Hi Shaun!

This is meant to be the welcome email that students receive as soon as they create their account

**Comment by rsgonzal** [comment]
so maybe beginner division parents don't get the 3 day letter email

**Comment by shaunxp20** [comment]
> This is meant to be the welcome email that students receive as soon as they create their account

> so maybe beginner division parents don't get the 3 day letter email

Thanks @rsgonzal!

Okay, just to make sure I got it...

Jr/Sr - two emails: one welcome to the student, one thank you to the parent (sent 3 days later)
Beginner - one email: the thank you one (w/ the changes in the doc), but send it immediately; and don't send the original welcome email (that a student would receive)

is that correct? 😅 😁

**Comment by rsgonzal** [comment]
sounds right to me!!

**Comment by shaunxp20** [comment]
> sounds right to me!!

Awesome! Thank you! 🙌 🌞 😄

**Comment by shaunxp20** [comment]
> And based on the edit history, it only includes one new paragraph.
>
> Is this basically just adding one paragraph to the "thank you" email? 🤔 😅

After working on this, I realized it was more than one paragraph of changes! 😊 😅  Anywho, I think I got all the changes!  🤞 😃 

Also, probably already on our radar, but we also need to update the regular (jr/sr) welcome email (for the "key dates" link, COVID-19 messaging, etc.).
