### ISSUE TITLE
Reset surveys to track 2022 pre survey

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3088]
documentation: https://docs.google.com/document/d/1hVaugqKipnD8pYmCcMl5KWCHrrqBBSr-86MQZTdm5P8/edit?pli=1#heading=h.nk9euk5z6x91

- resetting for all users (students & mentors)

#### For QA
`heroku run bundle exec rails surveys:reset_all --app technovation-qa`

#### For Prod
`heroku run bundle exec rails surveys:reset_all --app technovation`

**Comment by rsgonzal** [comment]
i actually don't know how to test this one 😅
don't know which of my returning students signed this. didn't have the test survey properly set up to send information!

**Comment by rsgonzal** [comment]
oh wait i have user ids!

**Comment by rsgonzal** [comment]
user 609 had previously take the post survey i believe and is now being shown a survey again

not related to this ticket but interesting it is being shown up in these two places. don't hate it
![Screen Shot 2021-12-02 at 4.13.58 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/23f02e2a-1f93-40be-8db4-fe00153ced64)

**Comment by shaunxp20** [comment]
Just ran this rake task for production, no errors, so I think we're good! 🤞
