### ISSUE TITLE
Work on front-end validation for students

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3091]
- Validate registration form on each page to ensure everything needed gets submitted
- Finalizing all validation on sign up

**Comment by viviancan** [comment]
https://vueformulate.com/guide/validation/

**Comment by shaunxp20** [comment]
#JustFYI Turning on validation messages so they're _all_ displayed when one of the steps/pages is displayed is trivial (vs having them only displayed when one of the fields is invalid) if we wanted do that, it looks something like this:

![validation messages](https://user-images.githubusercontent.com/58957909/142136848-816d352e-18b6-4b11-a24e-defc9fd8182d.png)

**Comment by dboyer** [comment]
It's a less ideal UX since showing the line only on uncompleted fields makes it easier for a person to find the field they missed, but the easier implementation is appealing considering our time crunch.

Is it correct that any errors added as part of #3082 will show as a separate line of text? If not, I think we have to only show errors on invalid fields. Otherwise it would be too hard for someone to figure out what they need to change.

**Comment by viviancan** [comment]
Is the parent email required for the student path as well?

**Comment by shaunxp20** [comment]
> Is the parent email required for the student path as well?

According to #3090, it's optional. 🤔 😅 😄

**Comment by rsgonzal** [comment]
Yup, optional! (not required, encouraged 😅)

**Comment by shaunxp20** [comment]
> It's a less ideal UX since showing the line only on uncompleted fields makes it easier for a person to find the field they missed, but the easier implementation is appealing considering our time crunch.

Is it correct that any errors added as part of #3082 will show as a separate line of text? If not, I think we have to only show errors on invalid fields. Otherwise it would be too hard for someone to figure out what they need to change.

Displaying the validation messages this new way is now on QA to see if we like it. It's very simple to turn on/off.

**Comment by shaunxp20** [comment]
> Displaying the validation messages this new way is now on QA to see if we like it. It's very simple to turn on/off.

Just throwing in my two cents, seems too busy w/ this turned on and we already identify the optional fields, a little over the top to display both, imho :smiley:

**Comment by dboyer** [comment]
Agreed, it's a bit much. I'm fine with not displaying by default and instead only showing the message if someone forgets to fill out a field.

Not sure if this is related, but I put in an incorrectly formatted birthdate and didn't receive an error message. The "next" button was greyed out so I couldn't proceed but there was no indication what was wrong. Should there be an error message about the incorrect format?

<img width="668" alt="Screen Shot 2021-11-18 at 10 53 38 AM" src="https://user-images.githubusercontent.com/516764/142449655-7a8cd5fa-65e9-4762-a613-ae5d93e94206.png">

**Comment by shaunxp20** [comment]
> Agreed, it's a bit much. I'm fine with not displaying by default and instead only showing the message if someone forgets to fill out a field.

I'm going to remove it from QA for now (if we want it back, it's simple to re-add it). 👍 😄 

> Not sure if this is related, but I put in an incorrectly formatted birthdate and didn't receive an error message. The "next" button was greyed out so I couldn't proceed but there was no indication what was wrong. Should there be an error message about the incorrect format?

We currently don't have a date format validation. I will try to add something to validate the mm/dd/yyyy format, I think it should be pretty simple w/ Vue Formulate. 🤞 😁

**Comment by shaunxp20** [comment]
I added a basic, hardcoded validation for birthday so it has to be between 1900 and 2020, which should cover us for now - we should make 2020 dynamic, but it'll work for now! :sweat_smile:
