### ISSUE TITLE
Onboarding flow improvements

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3107]
Draft list of onboarding improvements to discuss:

- [x] After guardians complete parental consent and media consent forms, they receive a "Thank you for signing the media consent form" banner at the top of the page. Perhaps either change the text to include about what happens next (i.e. "You are all set. Your daughter can now join a Technovation team. You can now close this page.") or redirect them to a different landing or login page.

- [x] When the user clicks between the second (enter name, etc) and third (agree to terms) screens of registration, the page stays scrolled to the bottom. It would be helpful to have the third page load with the user viewing the top of the page so they don't have to scroll up to read the terms of use.

- [x] Replace circles at top of parental consent/media consent with Step 1 and Step 2. The circles make it look like the user should be able to click on them, which is not possible.

<img width="474" alt="Screen Shot 2021-11-23 at 11 23 49 AM" src="https://user-images.githubusercontent.com/516764/143063288-658e6e01-a9fe-4806-9993-4944eeb7939f.png">

**Comment by shaunxp20** [comment]
> - [X] When the user clicks between the second (enter name, etc) and third (agree to terms) screens of registration, the page stays scrolled to the bottom. It would be helpful to have the third page load with the user viewing the top of the page so they don't have to scroll up to read the terms of use.

This one is regarding the registration flow and was fixed at some point.

> - [X] Replace circles at top of parental consent/media consent with Step 1 and Step 2. The circles make it look like the user should be able to click on them, which is not possible.

The circles have been replaced w/ a Tailwind component, hopefully it's better! 🤞

**Comment by dboyer** [comment]
Bringing this up again as we work on registration/onboarding for the new season and QA revealed a few potential improvements for parental consent onboarding:

- [ ] Could the cursor be a hand and not an arrow on the buttons to submit the parental consent and media forms? (i.e. when hovering on the Submit button in this screenshot) That is the behavior elsewhere on the platform

<img width="357" alt="Screen Shot 2022-09-23 at 10 46 20 AM" src="https://user-images.githubusercontent.com/516764/191988119-f2572506-7359-42ba-8b29-d916b5497118.png">

- [ ] If a user forgets to fill in a field, the form reloads at the top of the screen so the user can't see the error easily. Could it load at the bottom of the screen so the needed information is visible? The error text should also be a red color or have some other visual indication to draw attention.

<img width="826" alt="Screen Shot 2022-09-23 at 10 42 25 AM" src="https://user-images.githubusercontent.com/516764/191987068-5e3d51ac-1e55-4298-b9ac-010861d8dd40.png">

- [ ] After guardians complete parental consent and media consent forms, they receive a "Thank you for signing the media consent form" banner at the top of the page. Let's change the text to say:

"Thank you for signing the forms. Your child can now join a Technovation Girls team. Please find more information on supporting her participation in Technovation on our [Parent Resources](https://technovationchallenge.org/parent-resources/) page."

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3107?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
These changes are on QA. 😃

**Comment by dboyer** [comment]
Confirmed these changes are now on QA
