### ISSUE TITLE
Send students to my profile to finish onboarding

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3110]
Currently they go to the dashboard after sign up

- send them to My Profile instead
- Block them from going to the dashboard until they complete their consent form & location

**Comment by viviancan** [comment]
Related #3072

I pushed a [WIP branch ](https://github.com/Iridescent-CM/technovation-app/tree/WIP-3072-3110-flash-message-student-profile) with some basic work for #3110 and #3072. This branch was branced off of  #3092 (forced location)

I added custom disabled tailwind CSS on the Dashboard link. The link will look disabled if there are not current location details for the student. I also added a redirect, if the student clicks on the dashboard, they are redirected to the my profile tab with a notice. The flash message will need some styling updates (if it needs to match the mockup). Its def still a work in progress, but might be a good starting point to build on. 

Right now, if you click the location tab you can select the "change your location button" which loops into the old location form, which surprisingly still works! So reusing that form or at least the logic from that form could be a possibility for completing the onboarding logic.

**Comment by dboyer** [comment]
We confirmed with the program team that the curriculum and all team matching should not be accessible until the student has parental consent and has entered their location.

**Comment by shaunxp20** [comment]
Just FYI, some of our welcome emails mention going to the dashboard. After this functionality goes into place, you won't be able to access the dashboard until a location is set and the parental consent is signed.

**Comment by shaunxp20** [comment]
Notes: I added some functionality that requires a parental consent and location being set, if they're not a student will get redirected to their profile. This is targeted functionality (vs the force location functionality which is pretty broad (it's on pretty much everything)), that will only be applied where we want it - which right now will just be the header links, Dashboard, Create your team, Find a team. 👍 😄 

Side note: this broke a lot of tests b/c where you could once go to your dashboard, or find a team (w/o a parental consent signed), now you get redirected to your profile, so a lot of tests had to be updated to accommodate this! 😅 😁
