### ISSUE TITLE
Enhance validation error handling for new registration flow

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3112]
A back-end validation check can fail for a field that is not on the last page of the registration form - like for the parent/guardian email address - for this, we want to display:
- a general message
- a full list of the errors 

When a student is registering:
- add a front-end validation to check if the account email is the same as the parent/guardian email address, if they are:
   - display an error that they can't be the same and that they should change one of them

**Comment by rsgonzal** [comment]
on front end for junior/senior:
- when entering their email for the account, include in error message: "Must be different from parent email"

**Comment by shaunxp20** [comment]
This one is on QA. Now we're displaying a summary of the back-end errors, and we also have a front-end validation to ensure the parent and account email address are different for non-beginners/parents. With these two pieces in place, the only back-end errors we should be getting are non-unique email address errors (for the account and parent one). 😄
