### ISSUE TITLE
Remove invite & request section from student team building

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3113]
![Screen Shot 2021-11-17 at 10.14.36 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/28e42944-91cb-428a-97e9-1465e531afcd)

**Comment by rsgonzal** [comment]
@ophelieh are there other ways that students or mentors are invited to the platform?

**Comment by ophelieh** [comment]
No, unless we do it. 

Is that function moving to another part of the profile?

**Comment by shaunxp20** [comment]
The "Invitations and requests" section includes requests, which I assume is for when when someone requests to join a team and then those requests would get displayed there. Anywho, I left the requests section there (and added a new header - "Requests to join your team"). I haven't verified this behavior/section yet, but it will be headed to QA soon. 😃

**Comment by shaunxp20** [comment]
> Is that function moving to another part of the profile?

Not at the moment, maybe in the future though! 😄  Basically, we're limited on resources now (down to one dev!), and we have other things to do to get ready for when registrations opens (and that list is pretty long!). 😅 📜 😱 😂 :smil

**Comment by ophelieh** [comment]
That works for me! haha
