### ISSUE TITLE
BUG: Declined media consent but receive email indicating consent given

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3114]
**Describe the bug**
I registered a student account and then sent the parent email the consent forms. I clicked in the parent email to open the form and accepted the parental consent form and declined the media consent form. I received a copy of the media consent form but there was no indication that I had declined to give media consent.

**To Reproduce**
1. Register a new student account
2. On profile, fill out form to send parent the media consent
3. Open email prompting the parent to complete parental consent and media consent forms
4. Click link to open forms
5. Agree to parental consent and decline to give media consent
6. Receive a copy of the consent forms in email
7. The media consent form will have no indication that you have declined to give consent

**Expected behavior**
The copy of the consent form should show that you have declined to give consent

**Screenshots**
No indication of declined media consent

<img width="563" alt="Screen Shot 2021-11-17 at 1 26 41 PM" src="https://user-images.githubusercontent.com/516764/142260211-e3d22f03-d13a-42a3-92db-f113a7e2e3e1.png">

**Desktop (please complete the following information):**
Tested in Chrome

Split off from #3061

**Comment by shaunxp20** [comment]
I added a basic [ ] / [X] style checkbox on the emailed copy to indicate whether permission was granted or not, it's on QA now. 😀

**Comment by dboyer** [comment]
Confirmed that the emailed copy of media consent now includes the Y/N style checkbox
