### ISSUE TITLE
BUG: Media consent confirmation email does not indicate whether permission was granted

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3124]
Decision on media consent should be indicated
![Untitled.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/4e3a3bf6-6794-4acb-b806-a3e5599cfbd9)

**Comment by rsgonzal** [comment]
Something like on the confirmation we see on screen
![Screen Shot 2021-11-19 at 12.07.57 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/e7ad93c5-10dd-4b9a-a8d3-1164b63f0c61)

**Comment by dboyer** [comment]
Note that this is a duplicate of #3114

**Comment by shaunxp20** [comment]
Going to close this one since it's a duplicate, also, it should be fixed on QA now. 👍 😃

**Comment by shaunxp20** [comment]
Going to close this one since it's a duplicate, also, it should be fixed on QA now. 👍 😃
