### ISSUE TITLE
Rebrand the Parent Consent & Media Consent 

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3128]
When a student signs up and enters a parent email, she gets sent a link to fill out the parent and media consents.

Currently, those pages have the old styles and some of them are broken.

Tasks:
- Rebrand those pages to match the new styling as seem on the new registration form
- Pull as much from the mockups that make sense, focusing on colors and fonts

[Mockups](https://app.mural.co/t/roxwork8740/m/roxwork8740/1637366724881/aa5ddc30df6d13a3547864e92ecf16b702832f93?sender=roxana1990)

**Comment by shaunxp20** [comment]
This one is on QA. A few tweaks still need to be made I think.

The header is really basic - the one we use post-registration doesn't accommodate for someone who isn't logged in.

Also, after submitting the media consent, it just shows the completed media consent (I added the status bar thingum to that page, just to show that both consents were filled out), but maybe we should show something else - this is also mentioned in #3107.

Anywho, it's on QA ready for some feedback.
