### ISSUE TITLE
UI/Branding issues

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3136]
- [x] Styling for header missing from top of parental/media consent forms. May be covered by #3128 but will leave here just in case for now.
<img width="1288" alt="Screen Shot 2021-11-23 at 11 08 56 AM" src="https://user-images.githubusercontent.com/516764/143060706-0c3d357b-159e-4060-9921-2a295ff37ff4.png">

- [x] Styling for footer missing from top of parental/media consent forms. May be covered by #3128 but will leave here just in case for now.
<img width="1221" alt="Screen Shot 2021-11-23 at 11 26 48 AM" src="https://user-images.githubusercontent.com/516764/143063827-8dcdc558-06c5-43b4-b80a-6de8d2aae296.png">

- [ ] Change image button not centered under image on My Profile page and needs new color branding

<img width="351" alt="Screen Shot 2021-11-24 at 11 31 13 AM" src="https://user-images.githubusercontent.com/516764/143277701-a0ecf9fb-3a63-4240-a5d6-1387484e233b.png">

**Comment by rsgonzal** [comment]
- [ ] issue with parent consent running into footer
![Screen Shot 2021-11-30 at 10.17.58 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/8e220e00-a0e4-4cc2-9541-6f9296a8cdc8)

- [ ] Location box too small
![Screen Shot 2021-11-30 at 10.18.15 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/9dc9dc46-91c5-4126-a05e-e68aa0a41e8f)

**Comment by rsgonzal** [comment]
- [ ] editing my profile details from my profile section
![Screen Shot 2021-11-30 at 6.09.21 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/1b112657-53c3-4206-ba81-d3530a4e392a)

**Comment by rsgonzal** [comment]
- [ ] survey pop up, can't really tell it's a link with new styling
![Screen Shot 2021-12-02 at 4.50.39 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/3a3e1931-6c9b-42b7-bd34-427cbb5296c1)

**Comment by rsgonzal** [comment]
- [ ] data terms interrupt screen this might be the same for mentors & students

**Comment by rsgonzal** [comment]
going to checkmark if i see any on qa :)

**Comment by rsgonzal** [comment]
- [ ] Cha Cha info, social media text going outside box
![Screen Shot 2021-12-07 at 9.56.07 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/c38fd2dd-366e-45be-a639-d3827c24ad6e)

**Comment by dboyer** [comment]
Closing this issue as all bugs have been addressed other than two which were split off into new issues (#3559 and #3560).
