### ISSUE TITLE
Message on dashboard indicates permission issues

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3145]
**Describe the bug**
Banner stating "You don't have permission to go there." appears on top of parent profile and student profile after completing registration form.

**To Reproduce**

1. On staging, register a parent account
2. After submitting the form, you're taken to the dashboard with the URL /student/dashboard#/parental-consent
3. An error message at the top states: "You don't have permission to go there."

<img width="1282" alt="Screen Shot 2021-11-24 at 11 09 01 AM" src="https://user-images.githubusercontent.com/516764/143274036-141b02ae-fdda-4e74-a555-9d9a3815eddd.png">

4. The error message disappears if you click to a different screen such as My Profile or if a parent signs the parental consent form and the page is refreshed. 

**Expected behavior**
This banner may indicate the need to sign the parental consent forms. If so, the language should be clearer as currently users do not understand what needs to be done.

**Comment by shaunxp20** [comment]
I just noticed this one, it should be fixed, I left a note in the support ticket - https://github.com/Iridescent-CM/technovation-app/issues/3115#issuecomment-982850847

**Comment by rsgonzal** [comment]
Closing since it's fixed! :)
