### ISSUE TITLE
Issues with team creation

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3146]
**Describe the bug**
There are intermittent issues with creating a team with some QA testers unable to create a team and other QA testers having no issues. Opening this issue to track any more details that may come up.

**To Reproduce**
We have not been able to consistently reproduce this bug, which indicates it may be tied to some complex edge case with permissions/consent forms. 

Screen capture of one issue at https://drive.google.com/file/d/1Xo3HpRRoPoEEaVM-Mg04jCdI7jsR00B7/view

**Comment by rsgonzal** [comment]
i think we solved this in #3115 !

**Comment by dboyer** [comment]
Agreed. Closing for now and we can reopen if another team creation issue emerges.
