### ISSUE TITLE
Add "work in progress" notice to platform

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3149]
Since we will have a mix of new and old branding and some pages with styling/spacing issues, adding a notice that the site is under renovation will help users understand why some pages look different. Perhaps place a message in the lower right corner as a pop-up notice with an X to close it out.

Possible text:

Updates in progress! Please excuse any errors as we work to update the Technovation Girls website.

**Comment by rsgonzal** [comment]
Reuse hompage banner in #2798

**Comment by dboyer** [comment]
Updated text:

Updates in progress!
Some pages might look different as we work to make the Technovation Girls webpage better than ever!

**Comment by rsgonzal** [comment]
this update is on QA!

**Comment by dboyer** [comment]
Looks good on QA!
