### ISSUE TITLE
Reset season rake task

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3157]
Shaun mentions rake task in #2583
- should do data agreement
- should to mentor consent waiver

#### For QA
`heroku run bundle exec rails reset_for_season[force] --app technovation-qa`

#### For Prod
`heroku run bundle exec rails reset_for_season[force] --app technovation`

**Comment by shaunxp20** [comment]
This was run for QA!

Interesting note, the rake task will only let this be run on the exact first day of a new season; this can be overridden w/ the "force" option, which is what I did.

**Comment by rsgonzal** [comment]
oh interesting. maybe we should wait until morning of the 8th to run on production?

**Comment by rsgonzal** [comment]
Mentor
- so no mentors are fully onboarded
- mentor "judith" is on a team for the season, so at one point she was onboarded
- looks like it reset me consent waiver & training 
- had to do data agreement again

students
- had to do my data agreement again

**Comment by rsgonzal** [comment]
- "Rolo Dog" should be onboarded but us not showing up when looking for onboarded students

**Comment by shaunxp20** [comment]
> * mentor "judith" is on a team for the season, so at one point she was onboarded

Is this okay? Or is there something to look at here? 🤔 🤨

**Comment by rsgonzal** [comment]
[this](https://github.com/Iridescent-CM/technovation-app/issues/2747) might be related to rolo dog

**Comment by rsgonzal** [comment]
> Is this okay? Or is there something to look at here? 🤔 🤨

nope! the mentor thing is good an expected i think

**Comment by shaunxp20** [comment]
> [this](https://github.com/Iridescent-CM/technovation-app/issues/2747) might be related to rolo dog

Also, interesting is that when I search for Onboarded students in the admin, I only see one. 🤔 

Also, randomly I see the admin has a Division filter, I think I'll try to update that soon to include Beginner (just make it easier to tell if everything is working as expected).

**Comment by rsgonzal** [comment]
More notes on how this is working well:
- Returning mentor 'Roxana Mail' received a certificate in 2021 so was fully onboarded
- asked to do data terms, mentor training & consent
👍🏼

**Comment by rsgonzal** [comment]
Student
- returning student (roxana+stest@technovation.org) also received cert 2021
- asked to do data terms, brought me to 'my profile' & need to do parent consent
they are fully onboarded after completing those 👍🏼

**Comment by shaunxp20** [comment]
> [this](https://github.com/Iridescent-CM/technovation-app/issues/2747) might be related to rolo dog

It does look that^ issue is coming back to haunt us. I checked the rake task that fixes the "should be onboarded, but aren't" cases, and yes Rolo Dog, would be fixed w/ this script - `can_be_marked_onboarded?` is true and `onboarded?` is false.

**Comment by shaunxp20** [comment]
> > [this](https://github.com/Iridescent-CM/technovation-app/issues/2747) might be related to rolo dog
> 
> It does look that^ issue is coming back to haunt us. I checked the rake task that fixes the "should be onboarded, but aren't" cases, and yes Rolo Dog, would be fixed w/ this script - `can_be_marked_onboarded?` is true and `onboarded?` is false.

Here's what's happening in the case of Rolo - Rolo was already onboarded (valid location, parental consent signed) before the reset season rake task was run. The rake task resets the onboarded flag. And the onboarding check only happens when the `student_profile` record gets updated in the database - like updating a student's name would trigger the onboarding check.

I think the proper way to fix this is to make the data terms a part of onboarding - which means the onboarding flag won't get set unless the data terms are agreed to, which I think is non-consequential from a student's POV b/c as soon as you log in the data terms would need to be agreed to before you can do anything (pretty sure you can't bypass this). And this would trigger an onboarding check. This would need to be added to the admin too; random note: what the admin shows for onboarding is not consistent w/ the code. Anywho, maybe we can chat more about it on our call tomorrow. 😄

**Comment by shaunxp20** [comment]
> Also, randomly I see the admin has a Division filter, I think I'll try to update that soon to include Beginner (just make it easier to tell if everything is working as expected).

I did this via our support ticket #3169, it's on QA now. 👍

**Comment by shaunxp20** [comment]
> I think the proper way to fix this is to make the data terms a part of onboarding - which means the onboarding flag won't get set unless the data terms are agreed to, which I think is inconsequential from a student's POV b/c as soon as you log in the data terms would need to be agreed to before you can do anything (pretty sure you can't bypass this). And this would trigger an onboarding check. This would need to be added to the admin too; random note: what the admin shows for onboarding is not consistent w/ the code. Anywho, maybe we can chat more about it on our call tomorrow. 😄

I made this change - it was pretty simple. I tested it locally w/ Rolo Dog and it worked as expected. We'll need to do more thorough testing on QA. It's a small change, but a big consequential change in functionality b/c data terms is now required to be onboarded. Unless I'm overlooking something, I don't think this is going to make our "should be onboarded but isn't" issue worse; I'm hoping it will drop the number of accounts that the daily script finds this season. We'll see! And if we run into issues, it will be easy to revert this new functionality too! 😄

**Comment by shaunxp20** [comment]
Okay, this rake task was run for production, I had to use the "force" option again, b/c I think the START date just got moved to yesterday. Anywho, should be good! 🤞
