### ISSUE TITLE
Make new registration go to original link

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3158]
We've been using the link with "new" but should probably make it the default one?

**Comment by dboyer** [comment]
My preference is also to not have a new URL and instead use the default registration link.

**Comment by rsgonzal** [comment]
/signup ?

Ask teams what is used and if that can potentially change

**Comment by shaunxp20** [comment]
I'm working on this one now, changing the signup link is breaking a lot of our tests; I'm just commenting them out for now, but we'll probably want to remove them or rewrite them or some combo of those two at some point.

**Comment by shaunxp20** [comment]
Btw, a few tests I commented out mentioned invite stuff, so we might want to test that to make sure we didn't break anything. I commented out handful of them. 😃

**Comment by rsgonzal** [comment]
> Btw, a few tests I commented out mentioned invite stuff, so we might want to test that to make sure we didn't break anything. I commented out handful of them. 😃

All types of invites? Deb's been making teams and inviting mentors. I just accepted a few and those are working!

**Comment by rsgonzal** [comment]
So you mentioned invites... idk if this belongs here. but 
- i logged in as a past mentor and it shows a team that i sent an invite too.. but this what the first time i logged in for 2022.
- when i look up the team, it seems like it was a team from LAST year!!
- and when i look at the members of the team, i (the mentor) am the only one
- 
<img width="1235" alt="Screen Shot 2021-12-08 at 5 59 51 PM" src="https://user-images.githubusercontent.com/22801026/145320806-4d81c974-667c-4996-af81-245367c09a04.png">
<img width="1022" alt="Screen Shot 2021-12-08 at 6 02 25 PM" src="https://user-images.githubusercontent.com/22801026/145320917-4501f3de-a378-483d-9777-94258bf7399a.png">
