### ISSUE TITLE
Use rebranded templates on homepage and login page

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3159]
The homepage (/) and login page (/login) are still using the old branding templates
- Apply rebrand styles on homepage
- Apply rebrand styles on login page

[Mockups](https://app.mural.co/t/roxwork8740/m/roxwork8740/1638512255584/65eec8b1a40161e06f1c35e01d2c6318d011ce09?sender=roxana1990)

Images:
- Ask @rsgonzal for access

**Comment by rsgonzal** [comment]
![Screen Shot 2021-12-02 at 1.22.09 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/62bdf094-8f67-4345-ae1c-6dea33f47daf)

![myTG-LandingPage (1).png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/e0b0ff91-a261-4da7-870c-1851e8399fe4)

**Comment by dboyer** [comment]
Similar styling as implemented on another page can be viewed at https://github.com/Iridescent-CM/technovation-app/pull/3062

**Comment by dboyer** [comment]
Login page
![Screen Shot 2022-07-06 at 1.11.51 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/17bbe27a-beab-46dc-a13e-1faa06d6cb3d)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3159?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by dboyer** [comment]
@viviancan Two options for the header image available here:

![myTG-Header-LandingPage-1024px.jpg](https://ima![myTG-Header-LandingPage-1920px.jpg](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/0c83a803-4e3f-433e-8fca-79370c7361d4)ges.zenhubusercontent.com/5ca619b412380971eb9c9477/25f5a197-f9c8-49fb-9676-b1efa1d3e68e)

**Comment by dboyer** [comment]
Looks good on QA!
