### ISSUE TITLE
Mailchimp not registering parents after signing consent form

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3162]
Parents aren't being added to new mailing list

**Comment by shaunxp20** [comment]
This should be fixed on QA now. Very randomly the BIRTHYEAR field was marked as required in Mailchimp, but we don't send that info over for parents. I marked the field as optional and I just tried one and it worked.

The error I was getting:
> "detail"=>"Your merge fields were invalid.", "instance"=>"a62704b6-94fc-4
389-c66f-f65716b775fd", "errors"=>[{"field"=>"BIRTHYEAR", "message"=>"Please enter a value"}]}

Also, the Mailchimp list has changed pretty drastically from last year.

The only "merge" fields were are sending are: BIRTHYEAR, COUNTRY, FNAME, LNAME, NAME. And we also include the profile type as a "tag". None of the other fields in Mailchimp are currently hooked up and won't be filled out via our integration.

**Comment by rsgonzal** [comment]
> Also, the Mailchimp list has changed pretty drastically from last year.
> The only "merge" fields were are sending are: BIRTHYEAR, COUNTRY, FNAME, LNAME, NAME. And we also include the profile type as a "tag". None of the other fields in Mailchimp are currently hooked up and won't be filled out via our integration.

yeah, maggie and I don't know why all of those other columns are there. she made it exactly like last years but none of that info was ever collected. someone must've updated the list after

**Comment by shaunxp20** [comment]
> yeah, maggie and I don't know why all of those other columns are there. she made it exactly like last years but none of that info was ever collected. someone must've updated the list after

Okay, good to know! Guess my comment was more just FYI, don't expect those to work (via the integration) b/c they're not wired up! Maybe at some point in the future they could though. 😄

Anywho, there weren't any code changes w/ this one, but it should be working on QA now (I haven't actually tried it on QA, only locally using the same Mailchimp list as QA) - and this is just for the parents via the parental consent form checkbox.

Also, there isn't a Mailchimp prod list yet, but we'll want to test this out there once we do as well. 😄
