### ISSUE TITLE
Add asterix message to step one of sign up form 

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3163]
- message: * _As of **August 1st, 2022**. For example, if you turn 13 on July 28, 2022, you will need to select “I am registering to participate and am 13-18 years old.”_
- goes below the next button

![Screen Shot 2021-11-30 at 5.13.25 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/1b4dd85a-738d-469e-98b4-5610b76010d7)

**Comment by rsgonzal** [comment]
how does this look @dboyer ?
![screencapture-technovation-qa-herokuapp-new-registration-2021-12-01-22_20_03.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/61848978-537f-4d0d-8234-4d0e068fe3e3)

**Comment by rsgonzal** [comment]
copying over your comment of edits i still need to make to this page

> Can there be some additional styling on the "girls" hyperlink? It's the same text color right now so it's hard to know it is a link.

> Having the asterisk between years and old tripped me up a bit. Would it look weird to have it after "old" instead? I read "18 years old" or "8-12 years old" as a phrase and so the asterisk seemed out of place in the middle of the phrase.

**Comment by dboyer** [comment]
Woohoo!!! Looks good here and when I checked on staging. 

One date consistency - it says August 1st, 2022 and July 28, 2022. We should probably settle on one date format. My preference is always for August 1, 2022 and July 28, 2022 but I don't feel super strongly about it.

**Comment by rsgonzal** [comment]
this update is on QA!
