### ISSUE TITLE
Fix my team pages for students

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3170]
Search results and info rendered shows up at the bottom.
Basically, just move things to the right and look good

**Comment by rsgonzal** [comment]
i loove it! the only thing i'm noticing is the team image gets distorted but i think that's just the whole image conundrum.

**Comment by shaunxp20** [comment]
Just FYI, I marked 8 tests pending to get this one onto QA, I added them to #3020. At some point we can refine #3020 and break it into smaller tickets, but for now just making note of them. 😄

**Comment by shaunxp20** [comment]
The "return to" functionality doesn't work in the "My Team" section, it's broken in the "My Profile" section too, created #3206 for this.
