### ISSUE TITLE
Send welcome email to returning mentors

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3180]
Returning mentors do not get the welcome email and they haven't in the past. 

CET wants them to receive the welcome email.

I'll need to pull a list of returning mentors that signed up before deployment of this.

## QA STEPS
* Sign up as a new mentor, verify you get the welcome mentor email
* Find a "fresh" returning mentor (who hasn't logged in yet) and then login - this should run the "register to current season" job which sends the email - verify you get the welcome mentor email

We can try to simulate a "fresh" returning mentor if we can't find any - basically we just have to remove the current season from their account, then the next time they try to sign in it will see they aren't registered to the current season and will run the "register to current season" job.

**Comment by shaunxp20** [comment]
I moved where the mentor welcome email gets sent out to the "register to current season job" - this is where the student one gets sent out. Moving it here should work for both new and returning mentors. Anywho, it's on its way to QA now and I added some basic QA steps too. 👍 😄

**Comment by rsgonzal** [comment]
this is working! Signed up and signed in as a returning mentor and received emails.
