### ISSUE TITLE
Tasks for deployment 

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3181]
- [x] Add 2022 Mailchimp list to config in prod (haven't yet because people signing in now will be added, this may or may not matter)

- [x] Enable homepage banner with WIP

- [x] Add surveys & make sure all fields are [properly connected](https://docs.google.com/document/d/1hVaugqKipnD8pYmCcMl5KWCHrrqBBSr-86MQZTdm5P8/edit?pli=1#heading=h.nk9euk5z6x91)

**Comment by rsgonzal** [comment]
> Add 2022 Mailchimp list to config in prod (haven't yet because people signing in now will be added, this may or may not matter)

this one is set! @dboyer if you want to check this out and make sure i set the segments up correctly. testing a few accounts and seem to be populated correctly

**Comment by dboyer** [comment]
All student and parent segments are populating correctly!

**Comment by dboyer** [comment]
And mentors look good too.

**Comment by rsgonzal** [comment]
surveys went up too!
