### ISSUE TITLE
Uploading team images

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3183]
note in zendesk: 
I am remembering now how difficult it was for the teams to add their team photo last year. This year it is still difficult. Making the image size for 450x300 is really a problem since it is not the size of any typical social media, so images get cropped (usually the heads of the people in the image). Why make it so challenging to do the submission? Each team has to find a way to resize images while they are under the stress of completing their submission. I don't think it is really necessary, or helpful :(

**Comment by dboyer** [comment]
Closing as this issue was rolled into #3501
