### ISSUE TITLE
Bug: Can not click on team from student profile in admin

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3190]
![screencapture-technovation-qa-herokuapp-admin-participants-869-2021-12-09-15_23_53.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/ef657034-5ea2-4bb4-82f1-a7ef4ae4924c)

## QA STEPS
This "list of teams" where this link is broken is shared - based on the code, it's used by admins, ChAs, mentors, and students - so I'm assuming the links are broken there too! Anywho, QA'ing is just making sure this link works for different account types (I'm not sure where it's used for each account type, but it should be used by them, somewhere). 😄

**Comment by shaunxp20** [comment]
Good find on this one! It was using the account id instead of the team id for the link ie trying to find a team w/ the wrong/account id! It was a simple fix, but quite a slog to get there! 🥴 Anyhow, it's on its way to QA, and some vague QA steps were added too! 😅 😁 🌞

**Comment by rsgonzal** [comment]
i think i found all of the places we link to the team page and looks good!
