### ISSUE TITLE
Bug: Paper Consent not working for beginner division

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3193]
- There is a problem when inputting a paper consent for students in beginner division. - - Everything converts to "On File"
- Meaningful parent info is deleted
- This is affecting data on Mailchimp as well
- This doesn't seem to be affecting Junior/Senior students

**Comment by shaunxp20** [comment]
I addressed the Mailchimp issue, for paper consents it shouldn't update Mailchimp now. This is on QA now. 😄 

> Meaningful parent info is deleted

Is this referring to the parent/guardian name and email address getting turning into "ON FILE" (basically replacing what was there before)? If that's the case, to address that, it would require a bit more work. The "ON FILE" functionality has been like that for years, so it would take a bit more time to dig through/work out.

> This doesn't seem to be affecting Junior/Senior students

I wonder if this was/is affecting jr/sr student parent/guardians as well, just based on the code. Anywho, should be good now if it was!

**Comment by rsgonzal** [comment]
weird that it is not affecting junior and seniors. the info does not change to "on file"

i think that's the biggest issue with this bug, that it's happening for beginners
