### ISSUE TITLE
Bugs: Submissions

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3194]
- Word Counter gets cut off- description
![Screen Shot 2021-12-14 at 5.40.17 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/9403620f-565a-413f-8b03-91a97ea2d5d4)

**Comment by rsgonzal** [comment]
- Can't get to the additional information page
<img width="890" alt="Screen Shot 2021-12-14 at 5 43 00 PM" src="https://user-images.githubusercontent.com/22801026/146107530-e6ed7c6d-ac2c-4e7a-a533-7c5725d207fe.png">
<img width="783" alt="Screen Shot 2021-12-14 at 5 42 22 PM" src="https://user-images.githubusercontent.com/22801026/146107526-888a2feb-6f0a-496d-a7eb-898f2821b131.png">

**Comment by rsgonzal** [comment]
- getting to the honor code (uh oh error)
<img width="767" alt="Screen Shot 2021-12-14 at 5 45 04 PM" src="https://user-images.githubusercontent.com/22801026/146107708-108dd4fb-e5f3-41cc-a2a6-e4c3ea233f6a.png">

**Comment by rsgonzal** [comment]
-Uploading source code threw an error ( i tried a zip file)
<img width="962" alt="Screen Shot 2021-12-14 at 5 49 39 PM" src="https://user-images.githubusercontent.com/22801026/146108118-39357279-45b2-4da0-af6a-b0f1a6488743.png">
<img width="1049" alt="Screen Shot 2021-12-14 at 5 51 15 PM" src="https://user-images.githubusercontent.com/22801026/146108314-05630caf-40f4-4fd6-9816-6cbaf5135976.png">

**Comment by rsgonzal** [comment]
wrote this is another ticket, but looks like the problem with the word counter is it only counts 3+ letter words

**Comment by shaunxp20** [comment]
> looks like the problem with the word counter is it only counts 3+ letter words

Ah, good to know! 👍 We can update this of course... 🤔 😄

**Comment by ophelieh** [comment]
Only bug that was still there for me is the word count. Everything else seemed to work. :)

**Comment by rsgonzal** [comment]
created #3230 for word count bug
