### ISSUE TITLE
Add a Learning Journey section to submission

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3195]
As a student, I need to be able to submit my Learning Journey
- Add a section under Ideation - title: "Learning Journey"
- Add help text: "_What did your team learn (technically or otherwise)? How did you overcome challenges? What resources did you use to build on (examples, tutorials, open source code)?_"
- Goes in between "Description" and "Additional Information"
- 100 words maximum- add counter and limits 
- This should also be shown in the review page
<img width="961" alt="Screen Shot 2021-12-14 at 6 12 11 PM" src="https://user-images.githubusercontent.com/22801026/146110383-c683027d-d649-4df3-ba42-85e15fb48fad.png">

**Comment by rsgonzal** [comment]
#3196 & #3197 for followup

**Comment by ksrebecca** [comment]
good point. 100 words max!

**Comment by nickiredescent** [comment]
The 2+ images from Pitch is part of the learning journey.
Can be structured like this:

- Your project's name
- Description of your project
- Learning Journey
- Learning Journey (Images)
- Additional Information

**Comment by rsgonzal** [comment]
Opened #3207 for the restructuring

**Comment by rsgonzal** [comment]
Word counter seems to be off
![Screen Shot 2022-01-10 at 5.04.32 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/ce14e3f0-36bf-4348-8c78-cb5bb498b31b)

**Comment by rsgonzal** [comment]
^ seems like a word has to be at least three letters to count 🤔

**Comment by ophelieh** [comment]
+1 - it doesn't seem to count 1 or 2 letter words. 

Could we edit the help text to read: "Describe your learning journey in a few sentences (100 words or less)" ?
