### ISSUE TITLE
Add fields to more columns in "submission" section of admin

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3196]
Both ChA ChAs and admin see this
New Sections:
- Learning Journey
- Submission Type (ai/ mobile)
- Change development platform just to that for mobile, would be blank for AI
- thunkable project url
![Screen Shot 2021-12-14 at 6.16.41 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/bcd7e083-fdd9-4309-b740-a053e3b23283)

**Comment by nickiredescent** [comment]
Checking that "User Adoption Plan" (the Junior "business plan") is somehow included here.

**Comment by rsgonzal** [comment]
@nickiredescent where did the thunkable link show up before? i'm not seeing it

**Comment by nickiredescent** [comment]
woah I don't know lol. [Here's the data pull from last year ](https://docs.google.com/spreadsheets/d/1IMZGck2RozlrPsZwHSu_BEr5OFmhbC9xyIjbTMIkNps/edit#gid=1048604029&range=K1)
Master Tab, Column K. It's called "thunkable_project_irl" but I don't know where it came from cause I don't see it on the platform either.

**Comment by dboyer** [comment]
@nickiredescent Can you email that google doc with the data pull to Rox so we don't have a link to personal data on Github?

**Comment by nickiredescent** [comment]
ah right, sorry forgot about that. Emailing now

**Comment by devkonrad** [comment]
**Hi, a created a Pull Request for this issue:** https://github.com/Iridescent-CM/technovation-app/pull/3334

**Comment by shaunxp20** [comment]
From the requirements:
> * Change development platform just to that for mobile, would be blank for AI

I'm interpreting this as for submission type "mobile app" then display whatever was selected for the development platform, and if it's an "AI" submission type don't display anything (b/c development platform doesn't apply to AI). Is that correct? 😅

**Comment by dboyer** [comment]
Yes, that is how I interpret it as well.

**Comment by viviancan** [comment]
Following up here -
Pulled this branch and was able to see the new fields

<img width="1426" alt="Screen Shot 2022-04-15 at 4 27 45 PM" src="https://user-images.githubusercontent.com/29210380/163634487-62cca7b5-36fd-4266-8831-93ca836eb5cc.png">

**Comment by viviancan** [comment]
> Checking that "User Adoption Plan" (the Junior "business plan") is somehow included here.

Is this the same as 'business plan url'

**Comment by dboyer** [comment]
I'm just going off this conversation since this isn't on QA yet, but we should definitely have a different column for User Adoption Plan (which is just in the junior division) and the Business Plan (which is just in the senior division).

**Comment by viviancan** [comment]
Checked the PR to verify downloads. Downloads worked for me. 

A few things:
I did not see an option for the User Adoption Plan. But did see Business Plan for both Senior and Junior accounts. Maybe this is just a naming thing?

I'm not sure if the Development Platform has the correct value based on the output and the comments above. It seems repetitive since there is also the submission type column.

![Screen Shot 2022-04-19 at 10 58 34 AM](https://user-images.githubusercontent.com/29210380/164047037-862e141c-054b-4da1-bfa9-7833482ead69.png)

Also I think there may be an error in the code. I will leave a comment on the actual PR for that :)

**Comment by devkonrad** [comment]
> Also I think there may be an error in the code. I will leave a comment on the actual PR for that :)

I agree that if we have a scenario in wich we have both (User Adoption Plan / Business Plan) we'll need a column for each one, but i did these way because in the upload form (currently) is used the same field for both (i printed out the example bellow)
![Captura de tela de 2022-04-19 13-07-15](https://user-images.githubusercontent.com/99268176/164048445-b19bd305-f20c-4085-9292-4b72c9f81853.png)

**Comment by devkonrad** [comment]
> Tested on QA and this is working as intended. We need one change to make it easier for admins to use. My understanding is that the column entitled "Business plan url" references the business plan for seniors and the user adoption plan for juniors. However, that means that when admins search in the "more columns" field for "user adoption plan," they don't get any results and it looks like that isn't a column that can be added so we need to either:
> 
> 1. Change the column label to Business plan/user adoption plan URL
> 
> OR
> 
> 2. Split these into two different columns
> 
> I'm assuming option 1 (column name change) is easiest and I'm find with that approach.

I see! I will ttake a look and take care of it! :)

**Comment by devkonrad** [comment]
> Tested on QA and this is working as intended. We need one change to make it easier for admins to use. My understanding is that the column entitled "Business plan url" references the business plan for seniors and the user adoption plan for juniors. However, that means that when admins search in the "more columns" field for "user adoption plan," they don't get any results and it looks like that isn't a column that can be added so we need to either:
> 
> 1. Change the column label to Business plan/user adoption plan URL
> 
> OR
> 
> 2. Split these into two different columns
> 
> I'm assuming option 1 (column name change) is easiest and I'm find with that approach.

Just placed a PR (for review) to solve this: https://github.com/Iridescent-CM/technovation-app/pull/3357

**Comment by dboyer** [comment]
Confirmed that user adoption plan and business plan are now on QA
