### ISSUE TITLE
Add "Other" option + open field to development platform section

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3198]
As a student, I can use any language to create my app this year
- Remove swift & java from these options
- Add "AI Training Data" option & automatically select if for those that choose AI prototype in previous question
- Add an "Other" option
- If "Other" is selected, an open field should pop out where they are required to submit the language they used

![Screen Shot 2021-12-14 at 6.39.43 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/db06437f-9ecc-498c-ab45-ec103905abf6)

**Comment by dboyer** [comment]
@ksrebecca If someone selects AI as their submission type, would they always select "AI Training Data" in the development platform section? Is there any chance they would need to select another type of development platform?

We're trying to think about whether we need to show this drop-down if someone selects AI as their submission type or if we can automatically populate "AI Training Data" as the selection for development platform.

**Comment by ksrebecca** [comment]
that is great! no other thing would need to be selected.

**Comment by rsgonzal** [comment]
I think the typed in answer if they select 'other' should show up here. For example, i typed in java here but i don't see it on this screen

![Screen Shot 2022-01-07 at 9.40.00 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/5ea17a84-cffd-4a5b-9a7f-6ee2c4c068dc)

**Comment by ophelieh** [comment]
Noted some comments about this in ticket #3011

**Comment by rsgonzal** [comment]
"other" help text in #3225
