### ISSUE TITLE
Juniors now need to submit a user adoption plan

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3202]
As a junior team, I now need to submit a user adoption plan
This is still just a PDF upload I believe

1. Open up the business plan section to include juniors 
2. Rename this section to "Entrepreneurship"
3. Edit text in nav bar: _"junior and senior division teams only"_ & remove business so it reads: "Your plan"
4. Show a different screen with text difference for juniors and seniors, but keep same upload field
5. For junior team, use language "User Adoption Plan" - will edit the rest later
6. The text for upload: "User Adoption Plan"
7. Help text under title, above upload box: "Submit your User Adoption plan as a PDF file."
8. Help text below upload: "Check out what to include in your User Adoption Plan here (LINK - https://docs.google.com/document/d/1VWqsYbForZO5PERUUwCwkUUmlijl_pkAOvGg3WVkwSs/edit?usp=sharing)"

<img width="575" alt="Screen Shot 2021-12-21 at 10 49 13 PM" src="https://user-images.githubusercontent.com/22801026/147048298-b171da8a-e5a9-454b-ac67-41bad396d3f7.png">

(beginner teams will still see the screen that they don't need to submit)

**Comment by ksrebecca** [comment]
@nickiredescent can you add help text with a link to the template that we keep mentioning in the submission guidelines?

**Comment by dboyer** [comment]
Is this template something that needs to live on the TG platform? Or will it be on the wordpress site?

**Comment by ksrebecca** [comment]
it lives on wordpress, but in the help text i want to link out to it. just making sure @nickiredescent this is on your radar?

**Comment by ophelieh** [comment]
Will it be in the same upload section as the business plan or be its own line item in the menu? 

I would recommend changing the title of this section from Business to "Entrepreurship" - which is what it's called in the curriculum and would make more sense now that we're including a user adoption plan.

**Comment by nickiredescent** [comment]
[This is the link to the template](https://docs.google.com/document/d/1VWqsYbForZO5PERUUwCwkUUmlijl_pkAOvGg3WVkwSs/edit?usp=sharing)

and will (soon) live at this url: [https://technovationchallenge.org/curriculum/entrepreneurship-10/](https://technovationchallenge.org/curriculum/entrepreneurship-10/)

**Comment by rsgonzal** [comment]
This is what i've understood from these comments:
<img width="575" alt="Screen Shot 2021-12-21 at 10 49 13 PM" src="https://user-images.githubusercontent.com/22801026/147048298-b171da8a-e5a9-454b-ac67-41bad396d3f7.png">

**Comment by ophelieh** [comment]
Love the edits! I'm still not sure if there will be the same line item, but if they are, please see my edits below: 

**The text for upload**: User Adoption Plan (Junior) or Business Plan (Senior).

**Help text under title, above upload box:** Submit your User Adoption plan or 5 to 10 page Business plan as a PDF file. 

**Help text below upload:** Check out what to include in your User Adoption Plan here (LINK - https://docs.google.com/document/d/1VWqsYbForZO5PERUUwCwkUUmlijl_pkAOvGg3WVkwSs/edit?usp=sharing) or your Business plan here (LINK - https://docs.google.com/document/d/1AUm_HiOGpigaBa1HZ17OmbCijB9jGma4AqvBhc2p9x0/edit?usp=sharing)

**Comment by ksrebecca** [comment]
YES thank you for clarifying those two different elements @ophelieh  - UNLESS a user sees different screens based on what division they submit to, that is

**Comment by rsgonzal** [comment]
and it's ok to link to that google doc?

**Comment by ophelieh** [comment]
Oh cool!!! Then never mind my edits. Yes, the google doc is good :) That's what we link to from the curriculum.

**Comment by rsgonzal** [comment]
I uploaded my plan, but didn't get a checkmark
![Screen Shot 2022-01-10 at 5.00.30 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/1c288042-6273-49e6-9784-d5fe5f40d64d)

**Comment by rsgonzal** [comment]
It's also gray as if not required. Looks yellow like the rest for seniors.
![Screen Shot 2022-01-10 at 5.02.14 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/b04f25d9-de41-4f25-841e-7eef805f4ac9)

**Comment by shaunxp20** [comment]
> I uploaded my plan, but didn't get a checkmark

Good catch! This should be fixed on QA now (and the color of the checkmark circle too!). 😄

**Comment by dboyer** [comment]
I was able to submit a plan in the junior division without adding a user adoption plan. Is this optional or mandatory?

<img width="1403" alt="Screen Shot 2022-01-19 at 9 45 48 AM" src="https://user-images.githubusercontent.com/516764/150153824-a72c24a8-a577-43fc-91be-acca7a6ffafe.png">

**Comment by ophelieh** [comment]
The user adoption plan is mandatory. :)

**Comment by shaunxp20** [comment]
> I was able to submit a plan in the junior division without adding a user adoption plan. Is this optional or mandatory?

> The user adoption plan is mandatory. :)

Good catch! A new ticket was opened for this: #3233; a fix for it is on it's way to QA now. 😄
