### ISSUE TITLE
Responding to a request to join a team causes the team page to not load

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3205]
Took me awhile to figure out the exact sequence of events, but I've been able to replicate this a few times.

1. As a user, create a team
2. Make sure the option for users to find the team is selected
3. Log into an incognito browser with a different user account
4. Go to the find a team page
5. Search for the team you created as the other user
6. Find the team and request to join that team
7. In the other browser with your first account, refresh your team page
8. The team page will not load and will instead give the uh-oh error
9. The same error occurs if you open the "a student has requested to join your team" link in your email and you click the button to review that request. It loads the team page as an error page.

I didn't test this exact set of events prior to the work in #3170 so I don't know if the bug is fall out from that or a previously existing issue.

**Comment by dboyer** [comment]
This is now working after the location changes completed as part of #3070. I'm going to pull it into Review/QA and leave it open for now so that we have a record.

**Comment by rsgonzal** [comment]
agree this seems to work now
