### ISSUE TITLE
Restructuring submission side bar

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3207]
Move images on the menu bar to be under Learning Journey in Ideation

Just realizing Learning journey should be number three

1. Your app's name
2. A description of your app
3. Learning journey
4. 2 or more images
5. Additional information
![Screen Shot 2022-01-18 at 11.47.02 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/958142d8-bba3-4812-89fa-127e4d395809)
![Screen Shot 2022-01-18 at 11.52.49 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/a46975da-0141-4794-9543-3056f466f23f)

**Comment by rsgonzal** [comment]
Just realizing Learning journey should be number three

1. Your app's name
2. A description of your app
3. Learning journey
4. 2 or more images
5. Additional information

**Comment by shaunxp20** [comment]
Regarding this update:

> A description of your app

Right now it says "A description of your product" - I left it as "product" instead of "app", which I'm pretty sure is what we want, anywho let me know if it's not! 😄

**Comment by rsgonzal** [comment]
yes, thank you!!

**Comment by nickiredescent** [comment]
Sorry, I just noticed this. Ideation bullet 1 says "Your **app's** name". Should be "Your product's name". If it helps, here's the locations where I've noticed it:

![image](https://user-images.githubusercontent.com/45576078/153920254-48534ea2-6229-4af8-867c-1b1990821f67.png)

https://technovation-qa.herokuapp.com/student/team_submission_sections/no-name-yet-sample-team?section=ideation
![image](https://user-images.githubusercontent.com/45576078/153920286-c5de60eb-04f1-4d5f-9e6e-524dfe19e32d.png)

https://technovation-qa.herokuapp.com/student/team_submissions/no-name-yet-sample-team/edit?piece=app_name
![image](https://user-images.githubusercontent.com/45576078/153920371-90ea72cf-896b-4a79-a135-944ca5328ce2.png)

**Comment by dboyer** [comment]
Thanks for pointing those out. We'll change them as part of #3232 which will hopefully be in the next sprint.
