### ISSUE TITLE
Rename source code section and edit page

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3208]
![Screen Shot 2021-12-21 at 11.01.57 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/1e9de817-275c-4ff9-95f1-4f81038bb329)

**Comment by rsgonzal** [comment]
Nick's comment from #3011

> AI Project Submissions
>AI submissions should be a zip file with the following included:
>
>- The dataset you used to train your model
>- This can be a screenshot, spreadsheet, or direct link to an image/sound folder, etc.
>- Picture(s) of prototypes
>- This can be cardboard models, drawings, sample devices, etc.
>- (For online inventions) A link with sample login information

Where on this page would this go ideally? Might be confusing to have all of this for AI Projects and nothing for Mobile Apps?

**Comment by ophelieh** [comment]
Looks good! But I would edit the section name. See ticket #3011

**Comment by rsgonzal** [comment]
Hey Ophelie! Which section are you referring to? The larger one that is "Code."?

If so, what would then name the "Source Code" one?

**Comment by ophelieh** [comment]
Maybe we can just call that section "Technical" - kinda like it used to be in the rubric so it doesn't take away from the upload your technical work? 

Also for uploading Technical work will the view change if they choose mobile app vs AI project? If it stays the same, we need to change the text above the "Choose file" button in the second image.

**Comment by rsgonzal** [comment]
for now it'll stay the same. I'll edit the text.

**Comment by rsgonzal** [comment]
bullet point to be: Technical Additions like the title (instead of 'upload your source code' or 'upload your technical work' in the mockup)

**Comment by rsgonzal** [comment]
@ophelieh @nickiredescent do you want to upload this line?

Help for submitting your source code is [here](https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-) or take a look at the [debugging curriculum unit](https://technovationchallenge.org/curriculum/coding-14-debugging-tips-in-app-inventor-and-thunkable/) for more resources.

**Comment by ophelieh** [comment]
Looks great! 

Could you edit to read: "For help submitting your source code, check here (link) or take a look....

**Comment by nickiredescent** [comment]
Agree with Ophelie

**Comment by ophelieh** [comment]
I added some of my comments for this in ticket #3011. 

* Edit title of section to read "Technical Elements" instead of Code. And edit "Submission: Code" to read "Submission: Technical Elements"

* Replace "1. Development Platform" with "1. Submission Type"
