### ISSUE TITLE
Fix "on file" issue with paper consents

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3212]
When we enter a paper consent for beginner division, their parent information completely disappears.

This does not happen for other divisions

**Comment by devkonrad** [comment]
> When we enter a paper consent for beginner division, their parent information completely disappears.
> 
> This does not happen for other divisions

Hi, @rsgonzal could you please put here the screenshots that you showed in the meeting? Thank you!

**Comment by rsgonzal** [comment]
Sure! Here is some more explanation

When we click create paper consent for a beginner student 
![screencapture-technovation-qa-herokuapp-admin-participants-894-2022-03-02-12_59_21](https://user-images.githubusercontent.com/22801026/156448927-f64f722b-07cc-4298-ac89-320e640ce6a1.png)

The parent information gets replaced with "ON FILE"
<img width="1003" alt="Screen Shot 2022-03-02 at 1 00 14 PM" src="https://user-images.githubusercontent.com/22801026/156449060-02d8040e-ef0d-4229-9cf1-dde4acb01ca2.png">

**Comment by devkonrad** [comment]
> Sure! Here is some more explanation
> 
> When we click create paper consent for a beginner student ![screencapture-technovation-qa-herokuapp-admin-participants-894-2022-03-02-12_59_21](https://user-images.githubusercontent.com/22801026/156448927-f64f722b-07cc-4298-ac89-320e640ce6a1.png)
> 
> The parent information gets replaced with "ON FILE" <img alt="Screen Shot 2022-03-02 at 1 00 14 PM" width="1003" src="https://user-images.githubusercontent.com/22801026/156449060-02d8040e-ef0d-4229-9cf1-dde4acb01ca2.png">

Thank you, very much!

**Comment by devkonrad** [comment]
Hi @shaunxp20 and @viviancan! I investigated about this bug and o found out that these fields are updated explicitly on the code. I want toi know if is there an scenario in wich this update is correct. If it is not, we can just eliminate its from code.

![Captura de tela de 2022-03-03 11-45-13](https://user-images.githubusercontent.com/99268176/156618545-5d2b6268-3052-4846-862d-1d34de4f1cb3.png)
![Captura de tela de 2022-03-03 11-45-44](https://user-images.githubusercontent.com/99268176/156618549-09852291-089b-4c37-a7dd-c159b334737f.png)

**Comment by devkonrad** [comment]
> Hi @shaunxp20 and @viviancan, how are you!? I investigated about this bug and o found out that these fields are updated explicitly on the code. I want to know if is there an scenario in wich this update is correct. If it is not, we can just eliminate its from code. Thank you!
> 
> ![Captura de tela de 2022-03-03 11-45-13](https://user-images.githubusercontent.com/99268176/156618545-5d2b6268-3052-4846-862d-1d34de4f1cb3.png) ![Captura de tela de 2022-03-03 11-45-44](https://user-images.githubusercontent.com/99268176/156618549-09852291-089b-4c37-a7dd-c159b334737f.png)

Hi, @rsgonzal! How are you? I found a part of the code in wich the student "guardian_name" and "guardiuan_email" are explicitly updated to text "ON FILE". Is there some business rule  (or possible scenario) in wich it need to be this way? If not, to solve de "ON FILE" i just need to remove that update.

**Comment by rsgonzal** [comment]
looks good for all three divisions! @devkonrad is there anything specific I should check that this might have affected?

**Comment by devkonrad** [comment]
> When we enter a paper consent for beginner division, their parent information completely disappears.
> 
> This does not happen for other divisions

Oh! I'll check this situation.

**Comment by devkonrad** [comment]
> looks good for all three divisions! @devkonrad is there anything specific I should check that this might have affected?

I guess that we need just check the creation of paper consents.
