### ISSUE TITLE
Update additional questions

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3213]
If you summitted a Mobile Application, does it use AI?
- Yes
- No
- Not Applicable - I submitted an AI submission

Does your submission help solve Climate Change?
- Yes
- No

Does your submission relate to the health field?
- Yes
- No

**Comment by ksrebecca** [comment]
REVISED

Add "OPTIONAL" to help text at top of this part.

DOES YOUR PROJECT USE ARTIFICIAL INTELLIGENCE?

Yes
No

Does your submission help solve Climate Change?

Yes
No

Does your submission help solve a health problem?

Yes
No

**Comment by ophelieh** [comment]
Looks good!

**Comment by dboyer** [comment]
Looks like we're missing an L in "artificial intelligence"

<img width="442" alt="Screen Shot 2022-01-14 at 10 21 10 AM" src="https://user-images.githubusercontent.com/516764/149539702-b3d2d47d-67ca-4de7-97ba-7f6c0595c644.png">

**Comment by dboyer** [comment]
The help text on the health question still refers to games.

<img width="610" alt="Screen Shot 2022-01-20 at 9 46 53 AM" src="https://user-images.githubusercontent.com/516764/150361276-01b9f8b3-d91c-43cf-be27-2e308fb8fb2e.png">

**Comment by rsgonzal** [comment]
Help text has been edited!
![Screen Shot 2022-01-27 at 2.29.05 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/51ad320e-a59c-48f4-9437-ddc94dca11c9)
