### ISSUE TITLE
Add option to contact teammates

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3217]
**Describe the bug**
Currently, there is no option for users to contact the people they have approved to be on their team.

**To Reproduce**

1. Create a team
2. Have another user request to join that team
3. Approve request
4. User appears on list of students on the team but there is no way to contact them

<img width="847" alt="Screen Shot 2022-01-10 at 11 18 49 AM" src="https://user-images.githubusercontent.com/516764/148800093-c22f29d7-c071-44b6-9da9-35b80f4fe867.png">

**Expected behavior**
Student email address should be visible on the students tab of the "My Team" page after the team owner has approved their membership on the team

**Comment by dboyer** [comment]
Email address can go under the user's name 

<img width="370" alt="Screen Shot 2022-01-10 at 3 29 05 PM" src="https://user-images.githubusercontent.com/516764/148834702-96cefc76-d6ae-4b2b-ad5c-b991a107c342.png">

**Comment by shaunxp20** [comment]
Hmm, just double checking, the "expected behavior" says this is for students - do we want this behavior for mentors too? 🤔

**Comment by shaunxp20** [comment]
This one is on it's way to QA! Also, it won't be a problem to add mentor email addresses to the My Team -> Mentors page if we want that too. 👍

**Comment by dboyer** [comment]
Oh good catch, I should have been clearer in the issue. Yes, mentors' contact emails should also be visible once they are added to a team.
<img width="653" alt="Screen Shot 2022-01-12 at 8 54 06 PM" src="https://user-images.githubusercontent.com/516764/149251787-239169a2-a366-4a3d-b5c7-5cf0575b4d62.png">
