### ISSUE TITLE
Do not show student's last name when they request to join a team

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3218]
Currently, student's first and last names are displayed when they request to join a team. Test2 is the last name in this screenshot.

![2022_01_10_Review_Student_Team_Request](https://user-images.githubusercontent.com/516764/148808230-49c45898-a766-4e5e-a419-deb5ff1f956c.png)

Ideally, the last name should not display in the email the team owner receives indicating a user has requested to join their team or on the platform when they are reviewing the request (i.e. the above screenshot). Last names should only be visible to teammates once the person has been approved to join the team.

Task: Remove student last names from join requests

**Comment by shaunxp20** [comment]
Do we want to hide student last name from here as well?

![join reuest](https://user-images.githubusercontent.com/58957909/154569888-dcbd6e32-d239-4383-98d5-451eeae9b364.png)

CC: @rsgonzal @devkonrad

**Comment by dboyer** [comment]
I think it should be consistent and not be visible in any place until it is approved. Any concerns with that approach @rsgonzal ?

**Comment by shaunxp20** [comment]
![join reuest](https://user-images.githubusercontent.com/58957909/154569888-dcbd6e32-d239-4383-98d5-451eeae9b364.png)

This screenshot is from the file: `app/views/student/teams/_pending_student_join_requests.html.erb` #JustFYI 😄  

@devkonrad

**Comment by rsgonzal** [comment]
> I think it should be consistent and not be visible in any place until it is approved. Any concerns with that approach @rsgonzal ?

Yes, i think that makes sense!

**Comment by devkonrad** [comment]
I agree. That makes sense for me too!

**Comment by devkonrad** [comment]
> ![join reuest](https://user-images.githubusercontent.com/58957909/154569888-dcbd6e32-d239-4383-98d5-451eeae9b364.png)
> 
> This screenshot is from the file: `app/views/student/teams/_pending_student_join_requests.html.erb` #JustFYI smile
> 
> @devkonrad

Thank you, @shaunxp20 !

**Comment by rsgonzal** [comment]
Looks good on QA!
