### ISSUE TITLE
Help text for "other" in development platform

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3225]
- [x]  For submission type, if I select "Mobile App" and select other. A box shows up under, but it doesn't say what I'm supposed to do. Should I share the name of the platform I used? Share a link to my project? I can also save without adding anything to the field. 

![Screen Shot 2022-01-13 at 12 20 00 PM (2)](https://user-images.githubusercontent.com/32206421/149387062-334eeb91-7c81-428e-843a-680cf0e4e148.png)

Everything else seems to work as expected :)

_Originally posted by @ophelieh in https://github.com/Iridescent-CM/technovation-app/issues/3011#issuecomment-1012390570_

**Comment by rsgonzal** [comment]
@nickiredescent @ophelieh what language should go above the box? Is the development platform used in the curriculum? or would it be coding language? Don't know enough about how it works, like were swift and java also development platforms?

_Please indicate the development platform or coding language you used:_

**Comment by ksrebecca** [comment]
for everything outside of app inventor and thunkable we usually just say language. I would think that would yield the most accurate results??? 

I suggest changing the question from "Which development platform did your team use?" to "Please write what coding language you used:" and require a response if they choose "Other"

**Comment by rsgonzal** [comment]
so how about..

Which coding language did your team use?
_dropdown_
Please write the coding language your team used:
_open field_

**Comment by ksrebecca** [comment]
Yes, the second question only appearing for the Other field I am assuming! Looks great!

**Comment by rsgonzal** [comment]
help text looks good!
