### ISSUE TITLE
Update Source code screen depending on submission type

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3226]
Mobile App:

Mobile App source code should be submitted depending on the language used:
aia file (MIT App Inventor) OR zip file (other languages)
![Screen Shot 2022-01-13 at 11.04.27 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/0bdd4d9b-20be-498c-8ef0-a882d0cffc54)

AI Prototype:

AI Projects should include 1 zip file that contains:
- Screenshot of dataset training (ML4Kids, TeachableMachine, App Inventor, etc.) or spreadsheet or link to images/sounds folder.
- Picture(s) of prototype (cardboard model, drawings, devices)
- (For online inventions) Any link with demo login information

![Screen Shot 2022-01-13 at 11.04.20 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/1a97c152-0df2-4b6a-b5ba-a1af144583a3)

**Comment by rsgonzal** [comment]
@shaunxp20 is the mobile app text updated?

**Comment by shaunxp20** [comment]
> @shaunxp20 is the mobile app text updated?

I redeployed to QA so I think it should be good now, although I didn't verify it. I think what happened was that I did back-to-back deploys to QA and one overwrote the other one (overwriting this work). 😅 🤞 😃

**Comment by rsgonzal** [comment]
I am still not seeing it 🤔

**Comment by shaunxp20** [comment]
> I am still not seeing it 🤔

Hmm, I see the last CircleCI build skipped the "Deploy QA to Heroku" step. 😕 I'll try pushing a small change to QA to get it up to date. Sorry for the troubles! 😄

**Comment by shaunxp20** [comment]
Ok, finally got the changes on QA, phew! 😅

**Comment by rsgonzal** [comment]
yay!! looks good
