### ISSUE TITLE
Make Learning Journey required

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3238]
I can currently submit without the learning journey.. This should apply to all divisions

**Comment by rsgonzal** [comment]
Looks like it is working now!

**Comment by dboyer** [comment]
Working for me on QA too

**Comment by shaunxp20** [comment]
Good find, and thanks for testing this @rsgonzal @dboyer! 🎉 It has been deployed to production! 🙌
