### ISSUE TITLE
SPIKE: Investigate invite systems

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3244]
Currently, different types of "invitations" are possible from the platform

1. admin can invite anyone
2. judges
3. chapter ambassadors
4. students can invite other students to add directly to their team
(maybe more ways?)

These invites do not go through the front door.
We are mostly interested in 2 & 4 but it will be good to have all invites use the same registration path.

Goal: Figure out how these invites work and determine what work needs to get done in order to have invites lead to our normal registration.

**Comment by shaunxp20** [comment]
Regarding the current student invitation system:
- It's a one-page form
- The email address is prefilled in a readonly field
- It has no knowledge of parent accounts or the beginner division

Hooking up student invitations to our new registration flow:
- Will all profile types be available to be picked from?
  - What would happen if a mentor (or judge) profile gets picked?
- Will the email address also be prefilled in a readonly field?
  - For parents registering, it would apply to both the  parental consent and account email address?

After we work out a few of these front-end details, then I can look at how much of the back-end code we can use and how to get it wired up.

**Comment by rsgonzal** [comment]
> * Will all profile types be available to be picked from?  
>   * What would happen if a mentor (or judge) profile gets picked?
I like the idea of being able to add mentors or students to teams this way. Definitely would not make sense for judges

> * Will the email address also be prefilled in a readonly field?
In the old invite system was it pre-filled like this?

>   * For parents registering, it would apply to both the  parental consent and account email address?
If it's beginner, I would say yes but that wouldn't work for other divisions

**Comment by shaunxp20** [comment]
> > * Will all profile types be available to be picked from?
> >   
> >   * What would happen if a mentor (or judge) profile gets picked?
> 
> I like the idea of being able to add mentors or students to teams this way. Definitely would not make sense for judges

For a student and mentor invite, how should it work? For example, for mentors, should the only available option be the Mentor profile type? Or should they already start on the second page? For students, we would only show student and parent registration options?

> In the old invite system was it pre-filled like this?

Yes, the email address is pre-filled and readonly.

> Other random thought, with the old system if there was already an account with that email it would just bring them the platform.. would this still work the same?

We definitely can incorporate something like that.

**Comment by shaunxp20** [comment]
Following up briefly with this, I was able to prove out that we can use the current invite system to send someone an email invitation to join their team, and then when someone registers using the email address (the invitation was sent to) they will have a pending invite to join that team (w/ the ability to approve or decline the invite). This requires zero changes to the registration UI!

A few things known things would need to get worked out (and there will probably be additional things as it gets scrutinized more):
- The invitation email would need to be updated (updating the URL and removing the token)
- The (post-registration) invitation screens need updating/branding

**Comment by rsgonzal** [comment]
Thanks for the update Shaun! This sounds great. So this would work for mentors as well, even thought we weren't necessarily using it for them before?

**Comment by shaunxp20** [comment]
> Thanks for the update Shaun! This sounds great. So this would work for mentors as well, even thought we weren't necessarily using it for them before?

Phew! I was finally able to prove this out! 😅 🤒 😂 I used the same student invite form (made a small back-end change), and registered as a mentor - and after doing the on-boarding steps I am able to see the pending team invite! 👍 🙌 

Also, a random note - one thing to be aware of (at least the way it's working now) is that there is no validation/guarantee that if you're sending out a student invite that the new account will be a student account, and the same would go for mentor invites - it's basically a generic email team-invite system - we'd probably at least want to restrict this somehow so judges aren't invited to teams (when we implement that).

**Comment by shaunxp20** [comment]
A few notes on this one:

Our invite system is pretty generic allowing for different type of account types to be invited. Mentor invites in the invite system are very specific though, it was built for mentors who already have an account on our platform. To get mentor email invites working (for mentors who don't have an account yet) I had to slightly rework the mentor invite system. Because of this, QA'ing for this ticket should include testing our existing mentor invite process.

The mentor email invite sends the same email as a student invite right now, we can update this of course.

This is a rough draft of the functionality, there will be some followup work after this initial version lands on QA, but the basic functionality _should_ be there.
