### ISSUE TITLE
Switch Thunkable submissions to use project link

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3246]
Currently, we accept the copy link for Thunkable submissions but this link expires after sixty days. 

We should switch this to **only** accept the project link (e.g. https://x.thunkable.com/projects/....). Users should not be able to submit the copy link (e.g. https://x.thunkable.com/copy/....).

**Comment by rsgonzal** [comment]
related to #2905

**Comment by dboyer** [comment]
On staging, I tried adding a project with this [project URL](https://x.thunkable.com/projects/618437fa4cc75e0011f9ae92/ea22b5a5-1cd7-453c-a4a9-61b1d5878a1d/designer) and it failed. 

<img width="693" alt="Screen Shot 2022-02-15 at 11 27 52 AM" src="https://user-images.githubusercontent.com/516764/154105068-34265dfe-fd64-44fe-8f5c-e80fbd9e6b8d.png">

I also tried the [copy link]((https://x.thunkable.com/copy/4510f780b9597f379b81b24dc2be7a79)) and the [project page link](https://x.thunkable.com/projectPage/618437fa4cc75e0011f9ae92) and those were not accepted either. They should not be accepted but I wanted to confirm they weren't working either.

**Comment by dboyer** [comment]
We need updated text here too because it's not technically the shareable URL. @nickiredescent do you have any text suggestions or help text we should include? I want to be clear what should be submitted since there are three different ways to share a Thunkable project.

**Comment by rsgonzal** [comment]
it looks like it saves when the link is shortened to : https://x.thunkable.com/projects/6081dfa799f86a00129e225d

can you open that @dboyer ?

**Comment by shaunxp20** [comment]
> On staging, I tried adding a project with this [project URL](https://x.thunkable.com/projects/618437fa4cc75e0011f9ae92/ea22b5a5-1cd7-453c-a4a9-61b1d5878a1d/designer) and it failed.

The structure of the project URL here 👆 is quite a bit different than a copy URL:

https://x.thunkable.com/projects/618437fa4cc75e0011f9ae92/ea22b5a5-1cd7-453c-a4a9-61b1d5878a1d/designer
vs.
https://x.thunkable.com/copy/72ddf0567be5717b731c696c9263d9ff

> it looks like it saves when the link is shortened to : https://x.thunkable.com/projects/6081dfa799f86a00129e225d

Yes, this is the correct URL format 👆 that the validator currently accepts.

But, I updated the validator, so hopefully **all** the project URLs mentioned in this issue will work. 🤞 It should be on QA soon. 😃

**Comment by shaunxp20** [comment]
Ok, this one is on QA ready for a looksie. 😄 👀

**Comment by dboyer** [comment]
Looks good on QA! I was able to add a /projects/ link without error and could not add the projectpage or copy links
