### ISSUE TITLE
Edit help text for thunkable

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3252]
We need updated text here too because it's not technically the shareable URL. @nickiredescent do you have any text suggestions or help text we should include? I want to be clear what should be submitted since there are three different ways to share a Thunkable project.

<img width="693" alt="Screen Shot 2022-02-15 at 11 27 52 AM" src="https://user-images.githubusercontent.com/516764/154105068-34265dfe-fd64-44fe-8f5c-e80fbd9e6b8d.png">

_Originally posted by @dboyer in https://github.com/Iridescent-CM/technovation-app/issues/3246#issuecomment-1040498869_

**Comment by nickiredescent** [comment]
I think PT needs to figure out our official wording and put it in an FAQ. The text should be similar in both places and maybe we'll even direct link it into the help text. Let me ping them and we'll update you asap.

**Comment by nickiredescent** [comment]
**Text Reword**
What is the shareable url of your thunkable project? --> What is the url to your Thunkable project?

**Help Text:** Copy your URL in the address bar of your Thunkable project and paste that in the field above. [For more information, go here.](https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-)

Don't think we should overexplain here. We just want them to copy and paste.
Full FAQ link for your convenience: https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-

**Comment by rsgonzal** [comment]
What is the URL to your Thunkable project? Copy your URL from the address bar of your Thunkable project. For more information, go [here](https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-).

**Comment by dboyer** [comment]
Looks good to me on QA!
