### ISSUE TITLE
Allow judges to sign up through new registration flow

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3266]
Previously, judges signed up using a separate [link](https://technovation-qa.herokuapp.com/judge/signup?invitation=c1QWRNrKSc4gFzZtn5hp8zeE
)

As a judge, I should be able to go to the technovation platform and choose my user type to sign up

**- judges must be 18**

**New judge questions to ask:**
I want to be a Judge because I care about... 
-Youth development
-STEM
-Decreasing the gender gap in STEM
-Girls Education
-Social Entrepreneurship
-Start-ups
-Other [input field]

As a judge, you may call me a… _(this should match mentor options)_
-Industry professional
-Educator
-Parent
-Past Technovation Student

![Screen Shot 2022-03-02 at 8.25.05 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/d1cdcc7f-ea4e-4ea5-8c05-f8954d2bdda2)
![Screen Shot 2022-03-02 at 8.35.59 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/d555ceb4-8434-4278-bf0d-c9cf42b028e6)

**Comment by viviancan** [comment]
After discussing with Shaun, we think the best approach to this ticket is to break it into 3 main steps. 
1. Baseline - Register a judge through the new registration flow without the "judge type" (As a judge you can call me a ...) and judge reasons
2. Include Judge Type option 
    - This will require adding additional column of `judge_type` to the `judge_profiles` table and a separate `judge_type_options` constant similar to `mentor_type_options`
3. Include Judge Reasons checkboxes
    - This will require a `reasons` tables and a `judge_profile_reasons` table that will have the `judge_profile_id` and the `reason_id`
4. Complete any spin off post registration functionality
    - Update/edit functionality for judge type and judge reasons (?)

**Comment by viviancan** [comment]
After speaking w/ Roxana, other things to consider for future tickets 
- When a mentor switches to a judge 
   - Will we copy over the `mentor_type` selection from `mentor_profile` to the new `judge_profile`
   - We will probably need some sort of "catch" view where the mentor can select the Judge Reasons
- For returning judges
   - We use the same "catch" view to allow for returning judges to select Judge Reasons

**Comment by viviancan** [comment]
Following up on this ticket
In dev priorities today (3/7/22), we decided to put a pin on the Judge Type and Judge Reasons functionality for now. The rebranding is considered a higher priority to have a successful judging experience! I think we will regroup on it soon for further instruction.

**Comment by rsgonzal** [comment]
this is looking good!!
