### ISSUE TITLE
Update judge dashboard with new styles

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3268]
This is similar to the student view
Old screen
![Screen Shot 2022-03-02 at 8.55.35 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/154833ba-fa99-4530-a3d2-57b9ec46d3a0)

New Screen
![Screen Shot 2022-03-02 at 8.58.23 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/e7d48d55-748b-4d7f-9150-f17b36bac31d)

- add side navigation bar (this is on the left but can be on the right to mimic the student version
- remove location, survey questions

**Comment by viviancan** [comment]
https://app.mural.co/t/technovationgirls4378/m/technovationgirls4378/1646956515841/5e3205e755131e3d96266d884a6006f4bc65b4a4?sender=uf061e74756e4eabbae466406

**Comment by viviancan** [comment]
**Update 3/14/22**
Basic dashboard and consent waiver are rebranded. There a quite a few 'cases' that we will need to check for, for ex onboarded v. not onboarded. I also need to update the navbar to change the little circles based on completed onboarding. I am unsure atm what all the cases are, but we can regroup on these soon. Tomorrow I am hoping to work extensively on the My Profile section and the subnav that is in the TG green striped header. I think at that point we will be in a good spot to polish anything else up before judge registration opens up. 

![Screen Shot 2022-03-14 at 6.26.25 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/1d50bd36-b8f3-455c-821d-053dc72b8fc6)

![Screen Shot 2022-03-14 at 6.30.00 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/aede2c41-62e7-46ca-8769-b809c30eb8d6)

**Comment by rsgonzal** [comment]
Thanks, vivian! Can you create followup tickets for next iteration please 🙌🏼

**Comment by viviancan** [comment]
Related #3289 #3289 #3290
