### ISSUE TITLE
SPIKE: Separate judging screens for beginner, junior, and senior divisions

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3270]
Currently judging is similar for juniors and seniors, except for the entrepreneurship sections

This year the judging rubrics are different for all three divisions, so each division needs to have its own screen

(beginner division has one less section and scores out of 3 instead of 5)

**Comment by shaunxp20** [comment]
Here's a brief overview of the "bookends" work that needs to happen:
- Update questions and score values
  - Right now, the questions and score values are delivered to Vue.js from the backend, updating these values won't be too bad for all of the divisions (`app/models/questions.rb`)
- Update save/update functionality on the backend
  - Add appropriate columns to the database
  - Update save functionality to include these new fields
  - This also won't be too bad to incorporate for all of the divisions

These two steps are rather straight forward, for the steps in between we need to decide if we want to update what we have (old styles/brand), or go down the rebrand path - and then with either approach we could create an overview/plan of some sorts. 😄

**Comment by rsgonzal** [comment]
Started this [spreadsheet](https://docs.google.com/spreadsheets/d/1xscD_VtTQrv0ub_jC21qWLogZMVn_3vnvrUK_18-LKE/edit#gid=0)

Mural boards [here](https://app.mural.co/t/technovationgirls4378/m/technovationgirls4378/1646352662018/f183eb79e96e3a67b4f64d52b5c664159f12ebe9?sender=u9adab98cc36af2c4665e9477)

**Comment by rsgonzal** [comment]
i know you've been working on some stuff here @shaunxp20 can you help start some tickets for the implementation please 🙌🏼
