### ISSUE TITLE
Allow admin & Cha Chas to see media consent status

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3272]
Add section to admin that says
- Media Consent on File
- Media Consent not on File

![Screen Shot 2021-10-05 at 12.56.00 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/4c30e144-da33-475b-824d-6ebf7429becc)

**Comment by devkonrad** [comment]
Hi @dboyer and @rsgonzal , good morning! Just pasting here a preview of the funcionalitty to create the media consent independent of the parental consent.

![Captura de tela de 2022-03-22 09-12-04](https://user-images.githubusercontent.com/99268176/159479569-23e1b68d-7e26-4cc8-a21b-46991f606ee1.png)

![Captura de tela de 2022-03-22 09-12-24](https://user-images.githubusercontent.com/99268176/159479728-fa3c8165-b035-4255-b48d-74ae677289ce.png)

![Captura de tela de 2022-03-22 09-12-57](https://user-images.githubusercontent.com/99268176/159479570-6d5a0ef8-b92f-4549-800d-dd7be08f48fb.png)

**Comment by devkonrad** [comment]
> That looks right to me!

Thanks @dboyer! The PR feature is in review!  :)

**Comment by shaunxp20** [comment]
For media consents marked as ON FILE, should an admin person able to specify whether media consent was given or not?

**Comment by dboyer** [comment]
Yes, please. I doubt it will be used frequently as more likely people just won't return the form. But we do need to differentiate between "ON FILE - consent granted" and "ON FILE - consent not granted."

**Comment by viviancan** [comment]
I pulled down the branch and tested functionality locally. I was able to successfully see all the different states of media consent in the admin profile. Ref image below. 

Will we need to temporarily "enable" registration to QA this? I ended up "turning on" registration locally in order to create a few fresh student accounts. @dboyer @shaunxp20 

![media-consent-qa.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/2c24f7fe-0ed2-4a13-9484-843f8f8eaac6)

**Comment by shaunxp20** [comment]
> Will we need to temporarily "enable" registration to QA this? I ended up "turning on" registration locally in order to create a few fresh student accounts. @dboyer @shaunxp20

Perhaps! I think it could be tested by finding current students on QA who don't have a media consent signed, and then testing for the various states/media formats (paper vs online). And I guess if we can't find any or don't want to trouble with searching, then that would mean creating fresh students via new registration. 🤔 😄

**Comment by devkonrad** [comment]
Just merged the Media Consent Flow: https://github.com/Iridescent-CM/technovation-app/pull/3331
