### ISSUE TITLE
Create tailwind components for new styling

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3273]
Start thinking of styles we can convert into components

**Comment by viviancan** [comment]
https://v2.tailwindcss.com/docs/extracting-components

**Comment by viviancan** [comment]
Basic components have been created
- TG Green Striped Header
- Global navigation
- Profile side navigation "box" (we need to nail down internal vocabulary)
- Profile main "box"

Also basic cleanup of stylesheets + application layout![Screen Shot 2022-03-10 at 9.16.27 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/d601eaf5-20f7-4d3a-a192-cce79f0d8d5c)

**Comment by viviancan** [comment]
Related to #3268
