### ISSUE TITLE
Remove survey answers from judge onboarding

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3285]
Currently, survey answers are needed to complete onboarding as a judge. We want to take these away. These are irrelevant and not needed. Will introduce updated reasons and judge skills later![Screen Shot 2022-03-10 at 4.10.07 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/420bc653-be66-4a90-9e56-a808f78e454d)

**Comment by viviancan** [comment]
The survey answers were removed from the judge profile view, however there are still some backend components that need to be updated so that they are no longer required for onboarding to be complete.

**Comment by rsgonzal** [comment]
wooo! i signed up and didn't see anything about survey answers and i was able to judge
