### ISSUE TITLE
BUG: How did you hear about us defaulting to friend

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3287]
We could be getting a lot of bad data if it's auto selected. Technically it is an optional question
![Screen Shot 2022-03-13 at 9.47.16 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/8b7177ef-a50c-492e-a4b1-7b6227572844)

**Comment by dboyer** [comment]
Confirmed that it is no longer defaulting to friend in registration and checked in the admin that the referred by field is blanked if no value selected during registration.
