### ISSUE TITLE
Add dynamic circles on the side nav for judge profile (fill in circle w/ color once item is complete)

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3291]

**Comment by dboyer** [comment]
On QA, the circle filled in as expected but the text was pushed down to the next line. Dev tools say it breaks to a second line when the screen is 1024px or wider.

<img width="404" alt="Screen Shot 2022-03-23 at 11 32 34 AM" src="https://user-images.githubusercontent.com/516764/159736477-9b8e8e4e-3e8d-4791-aa7d-8d3144076ecf.png">

**Comment by rsgonzal** [comment]
it still gets pushed down at a certain size, but not sure it is worth it to keep exploring.
![Screen Shot 2022-03-28 at 9.01.16 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/b662f9f1-b49a-445c-b364-d03d817552b7)
