### ISSUE TITLE
Update backend to accommodate for beginners division, new questions, and point values

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3292]
Update the backend code/endpoint to return a payload to the frontend that has the correct questions and point values for a specific division.

Related to #3270

**Comment by rsgonzal** [comment]
Updated this [spreadsheet](https://docs.google.com/spreadsheets/d/1xscD_VtTQrv0ub_jC21qWLogZMVn_3vnvrUK_18-LKE/edit?usp=sharing) here (closed to only people in technovation)

I don't know if we've gone over this before but in the demo section, there are different questions for a mobile app vs ai.. not sure how much that complicates things?

**Comment by shaunxp20** [comment]
When I was testing this locally I ran into (just once) a submission that wasn't assigned a division, the division was "None assigned yet", and this caused an error - a submission needs to be either beginner, jr, or sr to be judged. I think this issue was caused from earlier in the season when we were working out the kinks, but anywho, something to keep our eye on! 😄

**Comment by rsgonzal** [comment]
So I know this happens when there is no student on a team, just a mentor. Do you remember which team it was? And was it already submitted?

**Comment by shaunxp20** [comment]
I'm moving this one to the QA column, but there aren't any QA steps for it - not until we get more of the front-end in place (that will use this functionality).
