### ISSUE TITLE
Show new submission fields in submission details for admin and ChAChAs

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3297]
- learning journey
- Submission type
- user adoption plan for junior 
- Additional Questions

![Screen Shot 2022-01-24 at 9.51.18 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/322d2bed-89ed-494e-9cfb-870468c3f176)

**Comment by devkonrad** [comment]
Hi @shaunxp20 and @viviancan , I am working on this issue and i have some doubts:
The information for:
- submission_type 
- learning_journey
I can get it from Team Submission table, but i couldnt find:
- user adoption plan for junior (I found business plan, is that info?)
- Additional Questions (Where can i get these?)

Thank you!

**Comment by dboyer** [comment]
@devkonrad The additional questions are optional information teams can provide when submitting an application. There are three questions:

- Does your submission use artificial intelligence?
- Does your submission help solve climate change?
- Does your submission help solve a health problem?

Each question is a yes/no answer. If the user selects "yes," they have the option to fill in an open text field with information answering "Please explain how."

The answers should be saved in whatever file the other fields are saved connected to the submitted application. Do you not see those fields there?

In terms of user adoption plan, people in the junior division add that info. The senior division adds the business plan.

**Comment by devkonrad** [comment]
Thank you, @dboyer ! Its more clear :)!

**Comment by devkonrad** [comment]
> If needed, the full lists of questions asked in submissions are [available here](https://docs.google.com/spreadsheets/d/1xscD_VtTQrv0ub_jC21qWLogZMVn_3vnvrUK_18-LKE/edit#gid=0). I've limited access so you'll need to be logged in with your virtualmind account

Thank you very much, @Deb!

**Comment by devkonrad** [comment]
> > If needed, the full lists of questions asked in submissions are [available here](https://docs.google.com/spreadsheets/d/1xscD_VtTQrv0ub_jC21qWLogZMVn_3vnvrUK_18-LKE/edit#gid=0). I've limited access so you'll need to be logged in with your virtualmind account
> 
> Thank you very much, @dboyer !

**Comment by devkonrad** [comment]
Pull Request created for this issue: https://github.com/Iridescent-CM/technovation-app/pull/3338

**Comment by shaunxp20** [comment]
> The additional questions are optional information teams can provide when submitting an application. There are three questions:
> 
>     * Does your submission use artificial intelligence?
> 
>     * Does your submission help solve climate change?
> 
>     * Does your submission help solve a health problem?

For these optional questions, do we want to differentiate between someone marking "No" and someone who didn't provide a response at all? Should we just display Yes/No? Or something like Yes/No/- (something for non-responses)?

**Comment by dboyer** [comment]
Good catch - I do think we need to differentiate between Yes, No, and no response. I'm fine with - for no response.

**Comment by devkonrad** [comment]
> > The additional questions are optional information teams can provide when submitting an application. There are three questions:
> > ```
> > * Does your submission use artificial intelligence?
> > 
> > * Does your submission help solve climate change?
> > 
> > * Does your submission help solve a health problem?
> > ```
> 
> For these optional questions, do we want to differentiate between someone marking "No" and someone who didn't provide a response at all? Should we just display Yes/No? Or something like Yes/No/- (something for non-responses)?

Well observed, @shaunxp20 ! I will make this adjustment.

**Comment by viviancan** [comment]
Here are some screenshots from local QA. I also verified that there was a distinction between "no" vs "-"

**Senior Submission**
![Screen Shot 2022-04-19 at 2.43.20 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/142a6c2d-0f26-4792-a63b-9129da30590d)

**Junior Submission**
![Screen Shot 2022-04-19 at 2.43.49 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/24fd6506-11b8-4c8d-b2be-2a279927efc6)








Here





here
 


**Beginner Submission**
![Screen Shot 2022-04-19 at 2.44.11 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/704eb832-3fac-4ea7-821c-f82fedbf8854)

**Comment by dboyer** [comment]
These screenshots look right to me and match the expected fields as outlined at https://docs.google.com/spreadsheets/d/1xscD_VtTQrv0ub_jC21qWLogZMVn_3vnvrUK_18-LKE/edit#gid=1465577404

**Comment by dboyer** [comment]
Confirmed that all looks as expected on QA

**Comment by dboyer** [comment]
Some fields are not displaying for Chapter Ambassador users. They should be able to view:

- Learning journey
- Submission type
- Additional questions

Those fields are not visible in this screenshot of the ChA view of the submission detail page:
![Screen Shot 2022-04-21 at 9.24.51 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/3037d6f4-a4ea-4375-971e-a1aad2131483)

**Comment by devkonrad** [comment]
> Some fields are not displaying for Chapter Ambassador users. They should be able to view:
> 
> * Learning journey
> * Submission type
> * Additional questions
> 
> Those fields are not visible in this screenshot of the ChA view of the submission detail page: ![Screen Shot 2022-04-21 at 9.24.51 PM.png](https://camo.githubusercontent.com/747cbd41b7be366ded98026901568a80c04d5ca4f158ed405700d18e7e40042c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563613631396234313233383039373165623963393437372f33303337643666342d613465612d343337352d393731652d613161616432313331343833)
> 
> This is the admin view. Is there a reason the section headers are different for ChA view compared to admin view? <img alt="Screen Shot 2022-04-21 at 9 29 57 PM" width="1027" src="https://user-images.githubusercontent.com/516764/164578883-4ab1007a-f612-428f-94d5-cbbb0a44f758.png">

I created a new PR that allow ambassador do see additional fields:
https://github.com/Iridescent-CM/technovation-app/pull/3364
About the differences between layouts, I dont know why, but ambassador and admin filed have differente html structures... (maybe a legacy thing)

**Comment by viviancan** [comment]
Confirming I was able to see additional fields locally. Ready to be merged to QA! Thx Alex

**Comment by dboyer** [comment]
Confirmed that these fields are now visible for ChA on QA

**Comment by dboyer** [comment]
Reopening @devkonrad as user adoption plan (junior division) is not visible to Chapter Ambassadors on production. All other fields seem to be appearing correctly.


<img width="159" alt="Screen Shot 2022-04-25 at 2 27 59 PM" src="https://user-images.githubusercontent.com/516764/165151236-303728af-e67d-4b27-ab12-54cd514aad2f.png">

**Comment by devkonrad** [comment]
> Reopening @devkonrad as user adoption plan (junior division) is not visible to Chapter Ambassadors on production. All other fields seem to be appearing correctly.
> 
> <img alt="Screen Shot 2022-04-25 at 2 27 59 PM" width="159" src="https://user-images.githubusercontent.com/516764/165151236-303728af-e67d-4b27-ab12-54cd514aad2f.png">

Created the PR https://github.com/Iridescent-CM/technovation-app/pull/3371 to fix this problem
