### ISSUE TITLE
Update the judge edit profile with new rebranding

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3302]
The judge edit your profile screen needs to be rebranded!
Judge -> "My Profile" > Basic Information > Change your basic profile details

**Comment by viviancan** [comment]
![Screen Shot 2022-03-22 at 2.02.33 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/6ef74c7e-51e4-4c67-8f18-726b031a8216)

**Comment by dboyer** [comment]
Confirming the new location interrupt screen is now available on QA and working as expected

**Comment by dboyer** [comment]
confirmed the profile editing is looking good on QA
