### ISSUE TITLE
Update text on judge profile/dashboard

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3310]
At minimum, we'll likely need to update text regarding live events.

<img width="808" alt="Screen Shot 2022-03-23 at 11 30 29 AM" src="https://user-images.githubusercontent.com/516764/159736033-2d252263-26cd-449c-8a5a-972f113f0833.png">

**Comment by dboyer** [comment]
Text updates available at https://docs.google.com/document/d/1fpuOQPTIH8FjtxVpHmix1xP1VUCV8Mii3QhTzDsX70k/edit

**Comment by dboyer** [comment]
@viviancan We don't need the lines:

You may be expecting an invitation to a live event from a Chapter Ambassador. In that case, just wait for the email. Most judges are online and will not attend a live event.

**Comment by rsgonzal** [comment]
I think Vivian updated the above? Not seeing it on QA
