### ISSUE TITLE
Uploading profile image on judge dashboard takes user to mentor dashboard

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3311]
Steps to reproduce:

1. On /judge/profile#/ page in the basic information tab, click the "change image" option
2. Select "choose from your computer," select a photo, click "upload"
3. The rebranded photo upload page loads

<img width="1345" alt="Screen Shot 2022-03-23 at 12 26 04 PM" src="https://user-images.githubusercontent.com/516764/159748177-c868c3d2-1c33-40e3-b9d0-07be97b7e899.png">

4. Click "if it looks good, take me back"
5. Page loads as the mentor dashboard

<img width="913" alt="Screen Shot 2022-03-23 at 12 26 41 PM" src="https://user-images.githubusercontent.com/516764/159748306-328dbe5f-9f04-4e5a-8d4d-0ff8b45646b7.png">

**Comment by viviancan** [comment]
Refs: #3313
This was fixed as part of [this PR](https://github.com/Iridescent-CM/technovation-app/pull/3315)
