### ISSUE TITLE
Cleanup of judge dashboard/profile

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3313]
- Add Mentor Mode to main global nav for judge view
- Remove "My profile" from judge drop down
- Remove "!" from "Curriculum!" in Student Dashboard main nav (this was accidentally added)
- Fix redirect after a judge uploads an image (error where judge is being redirected to mentor dashboard)

**Comment by rsgonzal** [comment]
Couldn't recreate the last one, but everything else looks good!
