### ISSUE TITLE
Update volunteer agreement for 2023 season

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3319]
The consent waiver for mentors and judges includes in section 1. Volunteer Responsibilities a reference to iridenscentlearning.org/safety/. Instead that link should go to technovation.org/safety

**Comment by dboyer** [comment]
Other text edits likely [in this doc](https://docs.google.com/document/d/1xDj-6DQ1iYABwlMh0eYvNJo7uc9Y6VRiTD9i1WQRvYk/edit#heading=h.1not9tfvzdli). This issue is blocked until text reviewed by PT/VET.

**Comment by dboyer** [comment]
Confirmed that [this doc](https://docs.google.com/document/d/1xDj-6DQ1iYABwlMh0eYvNJo7uc9Y6VRiTD9i1WQRvYk/edit#heading=h.1not9tfvzdli) is ready to be updated - just a couple small edits.

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by viviancan** [comment]
This should be verified for a mentor and also a judge since there are 2 separate waivers due to rebranding issues

**Comment by dboyer** [comment]
Confirmed on QA that this is updated for mentors and judges
