### ISSUE TITLE
Add text indicating registration is closed

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3324]
Now that we're routing judge registration through the main registration page, we don't have the text that was visible on the registration page in previous seasons indicating that student and mentor registrations are now closed. Could we add this line of text to the registration page?

Registration for the 2022 season is now closed for students and mentors. 

It can go below the heading and above the judge option. Let me know if it's challenging to add text to this page.
<img width="787" alt="Screen Shot 2022-03-29 at 9 55 18 AM" src="https://user-images.githubusercontent.com/516764/160628725-0b4af2d9-6e64-4486-9153-b70d398daa90.png">

**Comment by viviancan** [comment]
This is now on QA!
