### ISSUE TITLE
Fix formatting for change team name

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3326]
![Captura de tela de 2022-03-29 11-41-52.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/b7cc6289-296a-474f-9ede-a9b6a5ca90a9)

**Comment by devkonrad** [comment]
**I created a Pull Request to solve this issue:**
https://github.com/Iridescent-CM/technovation-app/pull/3332
