### ISSUE TITLE
Media consent not displaying for chapter ambassadors

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3339]
We have a "chapter ambassador" user group who should be able to see the media consent status for users in their area. Currently, they can add media consent as a column on the participants admin page. 

<img width="666" alt="Screen Shot 2022-04-08 at 3 34 07 PM" src="https://user-images.githubusercontent.com/516764/162512138-95a79a09-34fa-4c70-bcc2-6107ff9a1029.png">

However, if a chapter ambassador clicks through to the participant's individual page, the media consent section is not visible. Chapter ambassadors should be able to view their students' media consent. They **should not** be able to edit it.

<img width="1182" alt="Screen Shot 2022-04-08 at 3 40 28 PM" src="https://user-images.githubusercontent.com/516764/162515410-78eddbed-17fe-435a-af0c-60800584f31c.png">

**Comment by dboyer** [comment]
As a reference, chapter ambassadors should be able to view these statuses on the page for each user. They SHOULD NOT be able to set the status of the media consent, however.

<img width="671" alt="Screen Shot 2022-04-15 at 9 26 32 AM" src="https://user-images.githubusercontent.com/516764/163576286-25357f25-10a4-414e-8238-a06d332a9ad7.png">

**Comment by devkonrad** [comment]
> As a reference, chapter ambassadors should be able to view these statuses on the page for each user. They SHOULD NOT be able to set the status of the media consent, however.
> 
> <img alt="Screen Shot 2022-04-15 at 9 26 32 AM" width="671" src="https://user-images.githubusercontent.com/516764/163576286-25357f25-10a4-414e-8238-a06d332a9ad7.png">

Thats correct, Deb! They are allowed just to see the media consent status.
I just publishe a Pull Request that implements this feature: https://github.com/Iridescent-CM/technovation-app/pull/3347

**Comment by dboyer** [comment]
Confirmed this is displaying as expected on staging.
