### ISSUE TITLE
Team page will not open for mentor

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3340]
A mentor is reporting that when they click on a certain team from their mentor dashboard they see an error page rather than the team details. I was able to reproduce this issue. Please contact me for the specific mentor and team names connected to the issue.

1. Go to https://my.technovationchallenge.org/mentor/dashboard#/submission
2. Click on the team https://my.technovationchallenge.org/mentor/teams/28740
3. Receive our standard error page
<img width="739" alt="Screen Shot 2022-04-11 at 11 22 05 AM" src="https://user-images.githubusercontent.com/516764/162772505-b5d7b170-8a9e-4480-809c-c3ff9e73379d.png">
4. Return to mentor dashboard and click on a different team https://my.technovationchallenge.org/mentor/teams/28745
5. Page loads correctly

I repeated the same process with the other mentor for the team and got the same error when loading the team's page, leading me to believe it's an issue with that particular team profile. The team name has an @ in it so I thought it might be an issue with a special character. I created a team with @ in the name on QA and was able to successfully open it from the mentor dashboard.

**Comment by shaunxp20** [comment]
This was an interesting one. There was a pending invite for this team and an error was occurring when it tried to render the "delete" link. This link broke during the [Rails 6 upgrade](https://github.com/Iridescent-CM/technovation-app/commit/02a55fa3aadb0ae2baa74120b04c7e2db6cda9b5#diff-231db6a4ec3089799abdb58aa74da85709139633181ab4c8c89b7ea9d313153d).

I updated the link and it's working for me locally, so this fix should work for this team as well.
