### ISSUE TITLE
Judging admin issues

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3380]
- [x] Add beginner to the division drop-down list at /admin/scores#/ - VC
- [x] Score summary pages (e.g. /admin/scores/620#/) does not have headings that match the new headings for judging
- [x] Not all scores appearing on score summary page (e.g. /admin/scores/620#/). Junior division, for example, is missing project name and description, demo, and user adoption plan
- [x] Adjust low score threshold to -  Senior: 25/90, Junior: 20/80, Beginner: 15/39 - SA
- [x] Low score threshold not calculating accurately. There are scores in the junior division of 46/80 and 42/30 flagged as too low but scores of 37/80 not flagged as too low.
<img width="747" alt="Screen Shot 2022-04-28 at 2 28 11 PM" src="https://user-images.githubusercontent.com/516764/165821875-555d4d25-4fab-4bd0-b315-553296deef34.png">

**Comment by shaunxp20** [comment]
> Low score threshold not calculating accurately. There are scores in the junior division of 46/80 and 42/30 flagged as too low but scores of 37/80 not flagged as too low.

Both of the "seems to low" scores were completed on the 26th. The low score threshold calculations were updated after that. So those two scores aren't anything to worry about, but let's keep an eye out if new ones pop up like this.

Side notes: I think if someone updates those scores (edit a score or comment) that should re-trigger the score too low logic/flag. Also, I think it would be nice/useful to display the last updated date/time and/or completed at date/time in on the score details page in the admin. 😄

**Comment by dboyer** [comment]
Confirmed on QA that beginner division filter is on the scores page and filtering correctly and that the correct questions and score totals are showing in each division.

I am still seeing the old headings of ideation rather than learning journey and entrepreneurship rather than business plan or adoption plan. 
<img width="668" alt="Screen Shot 2022-04-29 at 5 43 38 PM" src="https://user-images.githubusercontent.com/516764/166072953-e4e9ce4f-8a9b-4190-b0de-f5b1b039e47b.png">

**Comment by viviancan** [comment]
That is how they are still stored behind the scenes! Ideation = Learning Journey & entrepreneurship = business plan. I can make a fix on the front end to display the updated titles, however, the backend will stay the same for now.

**Comment by dboyer** [comment]
Eh, I don't think changing the labels is a huge priority. Thanks for explaining!

**Comment by dboyer** [comment]
I added this score /admin/scores/611#/ and deliberately made it 18/90 to trigger the "too low" suspicious score. However, it didn't show up in the list on my scores page at /admin/scores#/ and that individual page (/admin/scores/611#/) only has a "delete" button not an "approve" button.

**Comment by viviancan** [comment]
Leaving detailed context info here regarding labels..

Added a temporary fix to the admin score details view. Currently, the backend section names do not match with front end expectations, more specifically on the backend **Learning Journey** is **ideation** and **Business Plan / User adoption Plan** is **entrepreneurship**. This is creating some complexities, but most of all we do not have one "source of truth" for section/display names in the Rails world. This will also need to be addressed before scores/certs are released to students as there are some issues with those experiences as well. 

A note to future us, after discussing with Shaun, we should explore translations happening in sections, and some sort of object/ hash should be returned that has title/description. I will create another issue for this ticket.
