### ISSUE TITLE
Investigate/update approach that addresses issues in Rails world regarding section names vs. title/display names

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3386]
Refs #3380 

Learning Journey = Ideation
entrepreneurship = Business/UserAdoptionPlan

**Comment by dboyer** [comment]
@shaunxp20 Is this issue still needed or does the work in #3621 take care of this?

**Comment by shaunxp20** [comment]
> @shaunxp20 Is this issue still needed or does the work in #3621 take care of this?

I'm pretty sure this one is still needed, from memory I think this one is regarding a source of truth for the submission sections, the sections are displayed in various places, and I think they're all doing things a little bit differently (but still displaying the same things).

**Comment by dboyer** [comment]
Got it! I'll keep it open then. Thank you!

**Comment by shaunxp20** [comment]
I addressed this in #3820, so there will be a source of truth in the Rails world for these conversions/translations (e.g. "ideation" -> "Learning Journey"), which is in this new method [`section_display_name_for`](https://github.com/Iridescent-CM/technovation-app/blob/5f747473c7aac000bbd41d58465311d9b5400743/app/models/questions.rb#L163-L176). There is also #3819 will address the duplicate translations.
