### ISSUE TITLE
Add progress indicator icons to judge sidebar

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3387]
When judging a submission, in the sidebar - add mini checkmark and comment icons for each section:
 - the number of checkmark icons should be equal to the number of questions for each section
- the checkmark icons should be "completed" when the corresponding question is completed
- each section should have one comment icon
- the comment icon should be "completed" when the corresponding comment is valid (> 20 characters)

## QA STEPS
- Verify these new progress icons are displaying correctly and look okay, for each division
- Verify the new icons are being "completed" correctly (according to the descriptions above), for each division

**Comment by dboyer** [comment]
This looks soooooooo good! Super useful while judging. I tested in Chrome, Safari, and Firefox.

I confirmed:
- Beginner division has correct number of check marks and comments
- Junior division has correct number of check marks and comments
- Senior division has correct number of check marks and comments
- Check marks and comments are completed correctly as I move through judging
- Editing a previously judged submission changes the progress in the sidebar (i.e. if I delete a comment, it is not marked as complete in the sidebar)
