### ISSUE TITLE
Thunkable link on student submission page redirects to the same page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3392]
**Describe the bug**
Logged in users who have submitted an app can view a submission page that lists all the data they submitted. It's visible at a URL like /student/published_team_submissions/no-name-yet-TEAMNAME. Any videos, documents, or code are links that the user can click to view what they uploaded. 

In the Technical Additions section, the link to a Thunkable project cannot be downloaded. It just reloads the same submission page which is confusing to users. 

<img width="694" alt="Screen Shot 2022-05-02 at 4 30 46 PM" src="https://user-images.githubusercontent.com/516764/166322656-0fc00b7a-ba9a-4229-a873-787c9cefb9eb.png">

If the technical work is a Thunkable link, it should link out to the URL and not just reload the submission page.

**Comment by viviancan** [comment]
Do thunkable teams also have technical work to download or just the link to the thunkable project?

**Comment by dboyer** [comment]
Just a link to the Thunkable project! It will open a screen that requires the judge to login with a Thunkable account in order to view the project. We know that limitation and there isn't a way around it.

**Comment by dboyer** [comment]
Confirmed on staging that Thunkable links now open in a new tab
