### ISSUE TITLE
Help text on scoring bubbles in beginner division doesn't match rubric

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3393]
The beginner division has a three point scale:

1 - Not there yet
2 - Good
3 - Amazing

The help text that appears on hover in the judging form does not match the three point scale and needs to be adjusted to use "not there yet," "good," "amazing."

<img width="654" alt="Screen Shot 2022-05-03 at 9 58 29 AM" src="https://user-images.githubusercontent.com/516764/166467109-33b2910d-9fde-45a0-b9eb-19f1c99331fa.png">

**Comment by viviancan** [comment]
@dboyer Should the helper/extra text also be removed for junior/senior score bubbles?
