### ISSUE TITLE
Update video ID validation

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3401]
A team uploaded a YouTube short URL (https://youtu.be/.....) which did not display correctly in the judging interface. We should support such URLs in future seasons.

<img width="1323" alt="Screen Shot 2022-05-04 at 10 02 09 AM" src="https://user-images.githubusercontent.com/516764/166808229-e2919347-c863-4371-9fda-36c92f4d397b.png">

## QA STEPS
- Find a Vimeo video that has this format (or use this one): https://vimeo.com/703480970/a4333a9b0c
- Update a demo and/or pitch video with that link^
- Judge this submission (assign the submission to yourself, or update a submission that you're already judging)
- Verify the videos are displaying and work as expected

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3401?planning-poker) with ZenHub @shaunxp20 @viviancan

**Comment by dboyer** [comment]
Initial plan: pull the URL from the database rather than extracting the URL ID

**Comment by shaunxp20** [comment]
> Initial plan: pull the URL from the database rather than extracting the URL ID

This one isn't as simple as planned! 😩 😢 The youtube and vimeo videos need to be in a special format in order to be embedded, which means extracting the video id to make the special embed-able url. Which means updating our regex to handle new url formats. One solution, which doesn't help us for this season, is to make sure students are uploading the embed-able urls. For this season (and if we don't want to go that route) is to update the regex; and/or update the error message and put a direct link to the video there where someone can watch the video off-platform. 🤔

**Comment by dboyer** [comment]
Thanks for researching this. For this season, I don't have a strong preference between updating the regex or error message so whichever can be done soonest is probably best since we're in the middle of judging.

**Comment by dboyer** [comment]
Talked to program team and we've avoided linking to the video off-platform in the past as some judges have left comments directly on the video then, rather than on the platform. 

So I'd vote for updating the regex to handle new URL formats. However, if that's more complex than we expected, let's put it on the list for this summer. We're not getting too many notices of videos that can't open.

**Comment by shaunxp20** [comment]
For starters for this one, I made an update so that those Vimeo URLs we were having issues will work now (e.g. https://vimeo.com/703480970/a4333a9b0c). For next season, we can look into having the students explicitly share the embeddable links if we want (so we don't have to do these conversions).

**Comment by dboyer** [comment]
I added the above vimeo link to a submission on QA and then opened that submission as a judge and was able to successfully view the embedded video. I confirmed that other videos also worked as expected.
