### ISSUE TITLE
Style judge recusal box

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3409]
The existing judge recusal box does not have styling that matches other elements of the site. Particular improvements might include:

- Adjusting the button width and overall width of the box
- Changing the font on the word count
- Increasing the size of the text box

<img width="1053" alt="Screen Shot 2022-05-08 at 10 58 22 PM" src="https://user-images.githubusercontent.com/516764/167333129-934125c3-18fb-486d-843b-5daf51513eb2.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3409?planning-poker) with ZenHub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
![Screen Shot 2022-06-06 at 6.19.14 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/83fb0e4b-a8a5-421d-9aa0-54af71858fa2)

**Comment by viviancan** [comment]
I am seeing an unexpected behavior locally where the entire box turns green on hover. Is this the desired output @dboyer?


![Screen Shot 2022-06-06 at 6.19.14 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/b81ca658-8470-4cd0-a8df-7e20a520d77a )

**Comment by dboyer** [comment]
whoa.....that is a whole lot of green! It should not turn green on hover. That's interesting as neither Alex or I saw that when we looked at his local machine. This happened when you hovered anywhere in the box? Or only on a particular element?

**Comment by devkonrad** [comment]
> This happens whenever I hover over the popup! I don't think I have a specific setting locally that would cause this. I pulled the branch down and didn't make any updates. I just reviewed more deeply and left a comment on code review. 
> 
> @devkonrad There was an extra custom class added to the modal container that was causing this behavior! Once that is removed, the correct behavior should appear! 
> 
> ![judge-recusal-green-hover.gif](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/9bc14ffc-1e20-4623-b4c9-214d5c65c5cc
> )

Oh, thanks for the catch @viviancan . I will take a look locally

**Comment by dboyer** [comment]
Confirmed that this looks as expected on QA
