### ISSUE TITLE
Spike: Review judge dashboard for post-season items

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3411]
The new judge dashboard may not include some of the sections needed for post-season. Specifically review:

- How judges view and find certificates - previously was My Dashboard > View your certificate
- What rebranding is necessary

**TO DO**

- [ ] Rebrand main judging information container (see image below)

**Comment by viviancan** [comment]
This view is from when a cert has been awarded to the judge. When they click on view certificate a new tab opens with the cert

![Screen Shot 2022-05-25 at 9.13.25 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/e9380fe2-b759-4291-9e69-aef48c626554)

**Comment by viviancan** [comment]
@dboyer Can you verify text changes w/ PT? Thank you!
