### ISSUE TITLE
Update home page text

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3413]
The home page text does not accurately reflect registration. 
<img width="749" alt="Screen Shot 2022-05-09 at 12 05 36 PM" src="https://user-images.githubusercontent.com/516764/167451043-f66533a0-b3bd-4f43-bc38-32e71a56f830.png">

Let's change it to the following text. This text should appear when judge registration is on and student/mentor registration is off.

Technovation Girls
Registration is currently open for judges.

Thank you for your interest in Technovation Girls. Registration is currently closed for students and mentors, although students with existing accounts are welcome to log-in [link to sign in page] and review their existing projects.

You can learn more about Technovation on our website [link to https://www.technovation.org/] or follow us at: (keep list of social media icons)

**Comment by dboyer** [comment]
Note that this will need to be hard coded as the judge toggle for registration doesn't exist yet. Check with @viviancan before starting as she looked into it.

**Comment by viviancan** [comment]
@dboyer Should there be text referring to judges signing up? It seems that the same issue where judges won't know how to get to sign up could happen again. When reviewing this locally I did not realize that the text "Registration is currently open for judges" was actually a link to the registration page, it looks like a heading.

![Screen Shot 2022-05-12 at 4.30.55 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/4d6d815a-5067-4de6-bf79-7a6af34aa77e)

**Comment by devkonrad** [comment]
> Oh good catch. Yep, the color on that does make it look just like a heading instead of a link. Let's:
> 
> * Remove the link from "Registration is currently open for judges"
> * Change the first sentence to read: Thank you for your interest in Technovation Girls. Register here to judge projects."
> * Link "register here" to https://my.technovationchallenge.org/signup#/

Great, @dboyer and @viviancan ! I'll do that!

**Comment by dboyer** [comment]
Reopening this so we remember it still needs to be deployed

**Comment by dboyer** [comment]
No worries! Confirmed that the text looks good on staging.
