### ISSUE TITLE
Create admin setting to control toggling judge registration on and off

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3414]
Currently, turning judge registration on and off requires a deployment. This issue covers the work on the front-end to create a flag in the /admin/season_schedule_settings/edit#/registration page to support an administrator turning judging on and off.

Note: We need to review how turning on judge registration impacts other elements of the system automatically turning off.

## QA Steps

- As an admin, turn on (or off) judge registrations (under Content & Settings)
- Review and click Save
- Verify the judge registration box is checked (or not) after saving

We can also verity judge registration works independently of the Judging Round controls
- Turn on quarterfinals judging
- Verify judge registration can be turned on or off (whereas student and mentor registrations should be disabled when judging is turned on)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3414?planning-poker) with ZenHub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
Note, that this new judge registration control is independent of the judging round controls i.e. student and mentor registrations can't be enabled if judging is turned on (the admin simply won't allow it), but judge registrations can be turned on or off regardless of whether judging is turned on or off.

**Comment by dboyer** [comment]
Good note on that. It makes sense that judge registration operates independently from judging being on or off.
