### ISSUE TITLE
Create list of items that need to be worked on from previous 6-9 mo that have not been addressed

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3415]

**Comment by viviancan** [comment]
https://docs.google.com/spreadsheets/d/1Pbom96SB5f6Suo_TUVXOtqW-Hzl6lohOCyghcny1UyY/edit?usp=sharing

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3415?planning-poker) with ZenHub @shaunxp20 @viviancan
