### ISSUE TITLE
Link app summary page on the admin submissions page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3417]
The app summary page styled in #3376 is currently accessible via the scores page, which doesn't exist for an app until it is scored the first time. It is accessed on the scores page by clicking the image icon in the View column.

We should move the app summary page to the admin submissions page available at /admin/team_submissions#/. Implementation details:

- It can be added as a link in a column called "Project page." We can include the URL in that column or if that looks too busy, perhaps the text can be Summary and then it links to the summary page
- The column should appear on the page by default
- In exports, the data in that column should appear as the URL for the project page
- The column should be visible to both admins and chapter ambassadors
- If possible, the column should appear to the left of the progress bar column
<img width="742" alt="Screen Shot 2022-05-11 at 10 51 50 AM" src="https://user-images.githubusercontent.com/516764/167879647-4bf58d21-c51c-469b-8a94-f87939534f18.png">

**Comment by viviancan** [comment]
@dboyer I wanted to verify that the link should be removed from the scores page. I have a vague memory of Mackenzie asking for the link to still be accessible from the scored submissions grid view, but I could be wrong!

**Comment by devkonrad** [comment]
> Good catch @viviancan. I confirmed with program team that it should be in both places - keep it on the scores page where it is now and also add it to the submissions page. Thanks!

Thanks @viviancan and @dboyer! I will fix it e re-send the PR.

**Comment by devkonrad** [comment]
PR fot this issue: https://github.com/Iridescent-CM/technovation-app/pull/3433

**Comment by dboyer** [comment]
Confirmed on QA that the app summary page is appearing on the submissions page and scores page and is downloadable.
