### ISSUE TITLE
Create policy to restrict judges viewing scores

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3440]
When judging, the judge can adjust the number in the URL (i.e. the 743 in /judge/scores/new?score_id=743#/overview) to another number. The submission associated with that number will then load and appear on the judge's dashboard, even if they already have another score in progress.

**Comment by dboyer** [comment]
Can use Pundit tool identified in #4274 to assist with this.

**Comment by shaun-technovation** [comment]
I'll pick this one up since I'm currently working on Pundit stuff. 👍

**Comment by shaun-technovation** [comment]
This one is on QA now. The functionality I hooked into (for this new policy) is responsible for getting a new score and also viewing/editing an existing score (which is a lot of functionality under the hood). I think it's basically when someone clicks the "start new score" button or the "resume score" button, including for judges who are in RPEs. Anywho, that's one area to keep an eye out for anything off/broken.
