### ISSUE TITLE
Prep mentor dashboard for certificates and scores

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3445]
Split off from #3422 

TO DO:

- [x] Determine if there are any failing tests
- [x] Update the "thank you" season close text

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3445?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
@dboyer Can you verify updated thank you text from PT? Thank you!

**Comment by dboyer** [comment]
Text for mentor dashboard [available here](https://docs.google.com/document/d/1Kd2z3Ju4drkm8gZmfCpN3HS6WItSQDTjmQBXfpWtBgs/edit#heading=h.4g54qf3b8bqw)

**Comment by shaunxp20** [comment]
> Determine if there are any failing tests

There aren't any failing or pending tests regarding mentor scores and certificates, but on a side note, we have 102 pending/commented-out tests.

> Update the "thank you" season close text

From what I could tell from the [doc](https://docs.google.com/document/d/1Kd2z3Ju4drkm8gZmfCpN3HS6WItSQDTjmQBXfpWtBgs/edit#heading=h.4g54qf3b8bqw), only the "Mentors who will not receive a certificate" page had updates.

**Comment by dboyer** [comment]
Confirmed the updated text looks correct on QA
