### ISSUE TITLE
Update heading names (logic) for students and add text for new scores explained

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3446]
Split off #3410. Needs a wireframe

TO DO:

- [x] Rename headings to match new sections - Learning Journey, Demo, etc - can likely use content from #3380  
- [x] Adjust text associated with judging rubric

**Comment by viviancan** [comment]
![Screen Shot 2022-05-25 at 12.27.16 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/31068ad1-6c69-4d92-a047-97f5913876e9)

**Comment by viviancan** [comment]
![Screen Shot 2022-05-25 at 12.27.29 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/ac9febd9-7917-449a-8767-a344eff9f430)

**Comment by viviancan** [comment]
![Screen Shot 2022-05-25 at 12.29.19 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/93cfdc38-d5bc-44c6-a80a-dc92c0dce0f4)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3446?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Current todos are complete 
 - Rename headings to match new sections - Learning Journey, Demo, etc - can likely use content from #3380
 - Adjust text associated with judging rubric

Current blockers: 
- Wireframe for the "rebrand" part of the ticket

I would be ok with splitting the rebrand work into its own ticket, as these (rebrand scores and the heading updates) are distinct pieces of work
