### ISSUE TITLE
Rebrand certificate/trophy page for students

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3447]
Split off #3410. Needs a wireframe

**Comment by viviancan** [comment]
Wireframe [here](https://app.mural.co/t/technovationgirls4378/m/technovationgirls4378/1654134869665/f7bc83ee2f1b336ff341433856377b2d68faf3f1?sender=u9adab98cc36af2c4665e9477)

**Comment by dboyer** [comment]
Since this text change came in later, just a note that the text on the certificates page should include:

“Download and share your achievement on Twitter, Facebook, Instagram, or LinkedIn with #Technovation2022Alumna and tag Technovation!”

All text changes are at https://docs.google.com/document/d/1Kd2z3Ju4drkm8gZmfCpN3HS6WItSQDTjmQBXfpWtBgs/edit
