### ISSUE TITLE
Create energetic container for student scores and certificates page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3449]
Need wireframe

Energetic container plus side navigation

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3449?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
This document highlights all of the potential student paths to viewing scores depending on a lot of different factors. We will need to QA each of these potential student scenarios! 

![StudentScoresFlow.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/1277f3b2-19ad-4f8b-9a2d-7a52c886193a)
