### ISSUE TITLE
Rebrand student scores view

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3455]
Split off from #3446

Needed: Wireframe

**Comment by viviancan** [comment]
Wireframe [here](https://app.mural.co/t/technovationgirls4378/m/technovationgirls4378/1654134869665/f7bc83ee2f1b336ff341433856377b2d68faf3f1?sender=u9adab98cc36af2c4665e9477)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3455?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
![StudentScoresView.gif](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/34831bc6-2fe4-480b-bbf6-6dde4b018ac1)
