### ISSUE TITLE
When clicking the "view scores" button on judging portal, app errors out

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3463]

**Comment by viviancan** [comment]
When the app is switched to Semifinals, as a judge I can view score details for finished quarterfinals scores. Right now, when I click the "view score" button, the app will error out. 
![Screen Shot 2022-06-08 at 8.05.09 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/093434bd-0269-4dac-9e93-1bd0e2049e2e
)

**Comment by dboyer** [comment]
Confirmed that this is now working on QA
