### ISSUE TITLE
Upgrade Tailwind to V3

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3468]
Documentation available at https://tailwindcss.com/docs/installation

**Comment by dboyer** [comment]
Prioritize this for earlier in iteration to ensure longer time on QA for testing before deployment.

**Comment by dboyer** [comment]
Not sure if this is Tailwind or some home page changes, but the globe on the home page is left aligned on QA now rather than centered. 
<img width="653" alt="Screen Shot 2022-06-28 at 12 07 53 PM" src="https://user-images.githubusercontent.com/516764/176227903-432d81ed-3aa0-4c1a-8834-498d96e22f49.png">

**Comment by shaunxp20** [comment]
> Not sure if this is Tailwind or some home page changes, but the globe on the home page is left aligned on QA now rather than centered. This is only at the home page if you don't have the # after the main home page URL <img alt="Screen Shot 2022-06-28 at 12 07 53 PM" width="653" src="https://user-images.githubusercontent.com/516764/176227903-432d81ed-3aa0-4c1a-8834-498d96e22f49.png">

Interesting, I keep trying to remove the `#` in the URL and it keeps getting added back, so I can't reproduce this issue. ☹️  It's not a Tailwind page though, so maybe we should create another issue for it? 🤔

**Comment by dboyer** [comment]
- [ ] Nick found the action button to create a team was greyed out until hovered over.

https://drive.google.com/file/d/1t3MgyAmwAKUotWuT-dviSMaadH9ZlB-8/view

- [ ] The to do list has hover text appearing on top of other list options
 
https://drive.google.com/file/d/1it4z-R40A0L7uP-J61Y4I-7Q7Kw0SubR/view

**Comment by viviancan** [comment]
I think the "to do" list hover may be related to tailwind config on QA/Prod because locally I am unable to recreate this issue. 

<img width="1742" alt="Screen Shot 2022-06-30 at 11 25 36 AM" src="https://user-images.githubusercontent.com/29210380/176729110-3ddedc0d-324e-4571-994d-a53a0cf9e2dd.png">

**Comment by viviancan** [comment]
Update on this ticket - We thought there were some config issues related to Tailwind v3 so Shaun has rolled this back. We may wait until the season is over to put this on QA/Prod to avoid any potential styling issues. Added a blocked tag for now.

**Comment by dboyer** [comment]
Fine by me!

**Comment by shaunxp20** [comment]
This one is back on QA! 🙌 😃

**Comment by viviancan** [comment]
wohoo!!
