### ISSUE TITLE
Spike: Research options for a linter

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3470]
- Stylelint - A mighty, modern linter that helps you avoid errors and enforce conventions in your styles

- standardrb - This gem saves you (and others!) time in three ways:
No configuration. The easiest way to enforce consistent style in your project. Just drop it in.
Automatically format code. Just run standardrb --fix and say goodbye to messy or inconsistent code.
Catch style issues & programmer errors early. Save precious code review time by eliminating back-and-forth between reviewer & contributor.

- prettier - seems like the most popular JS formatter

- ESLint - seems like the most popular JS linter

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3470?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by devkonrad** [comment]
About the RoR linters i used to use on called **Rubocop**. Its a pretty good linter, easy to use and configure:
https://github.com/rubocop/rubocop (ruby version)
https://github.com/rubocop/rubocop-rails (rails specific version)
