### ISSUE TITLE
General support for judging

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3473]

**Comment by viviancan** [comment]
7/18/22 - Request from Ophelie

> Would anyone have time to run a dataclip for all judge comments? Some chapters are asking for them and apparently they cannot be downloaded directly from the platform, they have to look at each individual team.

**Comment by viviancan** [comment]
^^ Found last year's dataclip and updated it to include this season's new fields

**Comment by viviancan** [comment]
Verifying this dataclip has been updated to include additional fields. The URL has been shared with Nick and Ophelie. The updated query was also added to the TG docs repo under the dataclips directory.
