### ISSUE TITLE
Remove old functionality/path for viewing certificates and scores in student dasboard

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3477]
Files that may need to be removed:
`app/views/student/dashboards/completion_steps/_post_survey_requirement.html.erb`
`app/views/student/dashboards/completion_steps/_participation_certificate.html.erb`
`app/views/student/dashboards/completion_steps/_scores_and_certificates.html.erb`

**Comment by viviancan** [comment]
Refs #3449

**Comment by dboyer** [comment]
Remove certificate link from side bar in my dashboard for students

**Comment by viviancan** [comment]
Moving this to Ready to Deploy. After speaking with Deb, the original links will stay on the my dashboard. They will link to the new my scores tab. This behavior follows the other behaviors such as my submission. I am creating a follow up ticket since there is a little bit of additional cleanup with the post survey requirement logic.
