### ISSUE TITLE
Review and revoke Github access for old contributors

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3487]
- [x] Confirmed that the only owners on the Github account are the three current dev team members. 
- [x] Need to check that previous contributors do now have access to keys or other private info.
- [x] Discuss mandatory MFA requirement for Technovation Github users

**Comment by viviancan** [comment]
Docs: https://docs.github.com/en/organizations/managing-membership-in-your-organization/removing-a-member-from-your-organization

List of current members (which includes 2FA status) [https://app.zenhub.com/files/29868115/2f3f8ae6-c768-4644-87c8-8635fd880f85/download](https://app.zenhub.com/files/29868115/2f3f8ae6-c768-4644-87c8-8635fd880f85/download)

**Comment by dboyer** [comment]
Also cover Zenhub under this.

**Comment by dboyer** [comment]
Owners must have MFA, members are encouraged

**Comment by dboyer** [comment]
Tasks completed:

- Confirmed three current dev team members are the only organization owners
- Removed any write or admin privileges from former staff and consultants so they have read-only access
- Moved all former staff to "outside collaborators" status
- Removed freelance contractors from the organization
- MFA can only be set for the organization as a whole, not for specific user levels. All owners have MFA turned on.

On the free tier for Zenhub, access is based on Github permissions. The individuals with Zenhub access are current staff with the exception of two former staff who have only read permissions.
