### ISSUE TITLE
Upgrade Heroku on staging from stack18 to stack20

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3491]
This issue specifically covers upgrading staging to stack20

**Comment by dboyer** [comment]
Email from Heroku about stack18 included these details:

From February 1st, 2023, the first build of each Heroku-18 app within a 7-day period will fail with a deprecation notice.

From April 1st, 2023, the frequency of these failures will increase to the first build of each app per day.

On April 30th, 2023, Heroku-18 reaches end-of-life; apps using it will no longer receive security updates, and be run at your own risk.

From May 1st, 2023, builds will no longer be allowed for Heroku-18 apps.

Please [upgrade to a newer stack](https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack) as soon as possible.

See the [Heroku-18 End-Of-Life FAQ](https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq) for more details.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3491?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
QA has been upgraded to the `heroku-22` stack. I just did some basic clicking around and things seem to be working, QA also has the Ruby upgrade #3575 too. 😄
