### ISSUE TITLE
Spike: Review commented out tests

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3494]
As noted in #3445, we have 102 pending or commented out tests. We need to create a strategy for how we will address these tests.

**Comment by dboyer** [comment]
Goal of this ticket is to:
- Review commented out tests
- Create tickets for sections of tests we would like to address

**Comment by shaunxp20** [comment]
114 tests have been commented out. I tried to group them into categories (student, mentor, admin, etc.) the best I could and I created the following issues to address them:
- #3850
- #3851
- #3852
- #3853
- #3854
- #3855
- #3856
- #3857
- #3858
- #3859
- #3860
