### ISSUE TITLE
Add  "view details" functionality to student scores view

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3495]

**Comment by viviancan** [comment]
Refs #3455

**Comment by dboyer** [comment]
Confirmed on QA that the view details is working on expected.

The text does blur together a bit. The section titles (demo, user adoption plan, etc) look to be the same size as the section total and judge feedback headings. Maybe the section titles could be bigger as they are in the admin view of the scores?

Let's see what other feedback we get from testing.
