### ISSUE TITLE
Generate 2022 certificates

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3498]
Depends on uploading the new templates in #3471 

Scores and certificates should be available on production on July 12

- Docs: https://docs.google.com/document/d/12DZ5R1l2DiruHpWelABJfU_0Luroz0yatSGKgYfE4ms/edit?ts=6050fe6d&pli=1

- 2021 Generation Refs #2890

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3498?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by dboyer** [comment]
Blocked until final score review on July 6

**Comment by dboyer** [comment]
Run the rake task on QA first to confirm certificates generating correctly and applied accurately to users.

**Comment by shaunxp20** [comment]
> Run the rake task on QA first to confirm certificates generating correctly and applied accurately to users.

I ran the rake task on QA:
`$ heroku run bundle exec rake certificates:award_all_direct --app technovation-qa`

**Comment by dboyer** [comment]
There was no judge with over 10 scores. I've since made one judge have 11 in order to have them get the judge advisor certificate. However, we would need to rerun the rake test to confirm that is applying correctly.

Otherwise, all certificates are being awarded as expected on QA

**Comment by dboyer** [comment]
The PT and VET teams are ready for us to generate certificates on production in preparation for making them available next week.

**Comment by shaunxp20** [comment]
Certificates on prod have been generated.

I ran the command:
`heroku run bundle exec rake certificates:award_all_direct --app technovation`

It ran for about 2 and a half hours, and generated 9503 certificates.

I'll leave this one in the Review/QA column while we review and see if anything needs addressing.
