### ISSUE TITLE
Spike: Research and select new photo upload and storage process

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3501]
In recent conversations, we have leaned toward selecting a new image upload library. If we choose a new library (or if we upgrade our current one), it should take into consideration the following known issues:

- Uploaded images may be somehow compressed or saved at lower quality as uploaded images sometimes look smaller than the originals. We should look into a system that does not significantly degrade the image quality upon upload.
- The required image sizes for team photos do not match any conventional social media sizes and it can be challenging for teams to find an image the right size #3183. Look into an image library with automatic resizing or the ability to adjust the image crop as part of the upload process.
- Image files cannot contain special characters - #2909
- Investigate why '/student/screenshots` are taking so long - we had issues on 21-APR 2021
- Make the S3 buckets private
- Upgrade libraries (carrierwave related ones)

**Comment by dboyer** [comment]
Questions:

- How many images uploaded in a season?

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3501?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Initial research/notes available [here](https://docs.google.com/document/d/1IHD2z8J8z0_1xImTr1BBsBIpfw22SpQ5RQb5S4UCCVE/edit?usp=sharing)

**Comment by shaunxp20** [comment]
> Initial research/notes available [here](https://docs.google.com/document/d/1IHD2z8J8z0_1xImTr1BBsBIpfw22SpQ5RQb5S4UCCVE/edit?usp=sharing)

Fantastic summary! 👏 

Btw, I checked TF/CM (via Heroku) and it's using Filestack. 😃

**Comment by devkonrad** [comment]
> Initial research/notes available [here](https://docs.google.com/document/d/1IHD2z8J8z0_1xImTr1BBsBIpfw22SpQ5RQb5S4UCCVE/edit?usp=sharing)

I have no rights to access. :(

**Comment by dboyer** [comment]
Check how Filestack works if user is uploading images on a mobile device

**Comment by viviancan** [comment]
Confirming I was able to use the Filestack picker on my mobile device (iPhone) and upload/search/transform an image 
![RPReplay_Final1660846698.gif](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/4400035f-92b1-4ee3-9566-64066d0e6572)

**Comment by viviancan** [comment]
@dboyer Any other things I should check out?

**Comment by dboyer** [comment]
The only other thing I did was look at https://github.com/Iridescent-CM/curiosity-machine/issues?q=is%3Aissue+filestack+is%3Aclosed to see if there were any known Filestack issues. These are all 3+ years old so likely wouldn't apply anyway but you may want to spend 15 minutes reviewing for anything that sounds concerning.

**Comment by dboyer** [comment]
Excellent! Then I think we're good to consider our due diligence research into Filestack finished!
