### ISSUE TITLE
Create card component for search results

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3504]
This component will be used to display search results and can be shared across pages such as team search and mentor search. An example is below.

We'll need to consider the width of the card component, particularly to ensure card layout works on multiple screen sizes.

<img width="520" alt="Screen Shot 2022-06-22 at 1 50 44 PM" src="https://user-images.githubusercontent.com/516764/175103780-75e45648-e5c2-4345-b3ca-b6e8b4f65221.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3504?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by devkonrad** [comment]
:) I published this PR for this issue: https://github.com/Iridescent-CM/technovation-app/pull/3519
