### ISSUE TITLE
Finalize mentor search for students

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3505]
- Requires completion of #3482 and #3504
- Implement search options and logic for mentor search
- Integrate card component from #3504
- Add in pagination

<img width="779" alt="Screen Shot 2022-06-22 at 1 52 49 PM" src="https://user-images.githubusercontent.com/516764/175104145-d12180ff-c255-423b-80f7-306b2294a550.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3505?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by devkonrad** [comment]
This issue was tackled on PR: https://github.com/Iridescent-CM/technovation-app/pull/3536

**Comment by devkonrad** [comment]
I will use this card to Fix the CSS problem on QA.

![Captura de tela de 2022-08-01 21-52-59.png](https://images.zenhubusercontent.com/620a6a3009cc3bdf05b78b23/0137016b-532e-4f7e-abd1-39df6e21b67d)

**Comment by devkonrad** [comment]
Creates this PR to solve this problem: https://github.com/Iridescent-CM/technovation-app/pull/3562
