### ISSUE TITLE
Rebrand invite student by email form

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3515]
The form to invite another student by email needs to be rebranded. This form is accessed at /student/team_member_invites#/ by logging in as a student, selecting the "my team" tab, and then clicking on the "send email invitation" button.

<img width="413" alt="Screen Shot 2022-06-28 at 11 16 59 AM" src="https://user-images.githubusercontent.com/516764/176216488-3526053a-8e53-41b8-8d5d-d56a190d47d1.png">

## QA STEPS
- As a student (who is already on a team), go to the "My Team" page
- Invite another student to your team, **enter an invalid email address**
- The "My Team" page should be re displayed with an error message

**Comment by dboyer** [comment]
There is no existing mockup for this screen. We can follow the general style and color of the team creation screen or the location update screen

![Screen Shot 2022-07-15 at 11.10.51 AM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/d15d1648-cab4-454b-9e8c-44d0167f4286)

![Screen Shot 2022-07-15 at 11.10.23 AM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/3eb7930b-a168-4b45-a14b-b153f4916e71)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3515?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by dboyer** [comment]
This ticket covers only rebranding, no functionality changes.

**Comment by viviancan** [comment]
Hmmm, I tried the same thing and could not get to this screen either!

**Comment by dboyer** [comment]
This might have been because the forming teams option was off in the content and settings. I turned it on for QA and logged in as a student who had created the team. I then went to the "My Team" tab and clicked to "Send email invitation." It opened this page. 

One possibility is that this page only shows if there is an error? I just put garbage text in the email invite field on the My Teams tab and then this page loaded.

<img width="590" alt="Screen Shot 2022-07-21 at 7 59 38 PM" src="https://user-images.githubusercontent.com/516764/180339370-42cb56ac-7104-4cea-b4e6-b782c7f4730e.png">

**Comment by shaunxp20** [comment]
I updated the flow so that if there's an error inviting a student it will redirect them back to the "My Team" page and display a flash error message and a validation error under the text input field. These error messages sill have the old styling, I think we should create separate issues for them - one for the flash messages to update/restyle them across the application, and one to do the same for the form errors. Maybe we can chat more about this on our next stand-up. 😃 

![student-invite-form-errors](https://user-images.githubusercontent.com/58957909/181361586-599edec5-c414-47c0-a230-0e855bdeba89.png)

**Comment by dboyer** [comment]
I like this! No reason to take people off the My Team page to a separate error page if we can keep everything within the same page.

And agreed on adding issues in the future to restyle flash messages and form errors.

**Comment by dboyer** [comment]
Confirmed on QA that I am no longer taken to another page if I've put in an incorrect email address when inviting someone to a team. The error messages appeared on the My Team page and were accurate in terms of whether it was an email error or an error due to the user already being on a team.

**Comment by shaunxp20** [comment]
I added #3563 and #3564 for the flash messages and form validation errors.
