### ISSUE TITLE
Rebrand request to join a team

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3516]
The page where students request to join a team needs to be rebranded. This page is accessed by:

1. Log in as a student and then click "find a team" in the top nav
2. Search for a team
3. Click the "view more details" button in the search result
4. The image shown below loads

Question: Is there some type of component or branding from another page that should be used here?

![JoinTeam](https://user-images.githubusercontent.com/516764/176222272-c98af4df-fab7-4cb9-93db-d45c643b59f4.png)

**Comment by dboyer** [comment]
@audsbodin is working on a mockup for this page that will be available the week of July 18.

**Comment by audsbodin** [comment]
![StuDash-TeamDetails](https://user-images.githubusercontent.com/9745920/179794218-9d0946ec-3010-4f0b-9fe8-d530ba6b65b8.png)
LMK if there's anything you need changed on this :) Thanks!

**Comment by dboyer** [comment]
Thanks @audsbodin ! This is super helpful!

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3516?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
This is in code review. 

Here is a preview
![student-Request-to-join-team.gif](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/71873f9d-8ed5-4b50-be75-ad49e34936d4)

**Comment by dboyer** [comment]
Confirmed that the new branding is on QA and working as expected! I was successfully able to request to join the team.
