### ISSUE TITLE
Globe on home page is left aligned if home page URL has no #

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3520]
The globe on the home page is left aligned on QA now rather than centered.  This is only at the home page if you don't have the # after the main home page URL.

The home page without a # is accessible by clicking the Technovation Girls logo in the upper left corner when on the sign up page.

<img width="653" alt="Screen Shot 2022-06-28 at 12 07 53 PM" src="https://user-images.githubusercontent.com/516764/176227903-432d81ed-3aa0-4c1a-8834-498d96e22f49.png">

_Originally posted by @dboyer in https://github.com/Iridescent-CM/technovation-app/issues/3468#issuecomment-1168918801_

**Comment by shaunxp20** [comment]
> The home page without a # is accessible by clicking the Technovation Girls logo in the upper left corner when on the sign up page.

Ah, good to know!

**Comment by dboyer** [comment]
Closing this as we are integrating a new home page design as part of #3533
