### ISSUE TITLE
Add some sort of indicator that you are on QA when changing season toggles

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3526]
We have had a few situations where season toggles get changed on Production instead of QA. We want some sort of indicator to remind the user they are on QA vs Prod as a visual helper

We think in the future there may be functionality to only allow for certain user accounts to change the toggles on production. TBD!

**Comment by viviancan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3526?planning-poker) with Zenhub @shaunxp20

**Comment by shaunxp20** [comment]
This one is on QA, just a reminder that the popup confirmation will/should only be displayed on production.

**Comment by dboyer** [comment]
Confirming that I do not see this pop-up on QA.

**Comment by dboyer** [comment]
Confirming that I see the warning message on production. (I cancelled and did not save changes)

![Screen Shot 2023-04-05 at 4.10.33 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/ed0bbfb7-b93e-498e-ac37-663c4d8eb7da)
