### ISSUE TITLE
Correct the certificate name - completion should be quarterfinalist

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3527]
`app/constants/certificate_types.rb`

For QA purposes, the "completion" name for a certificate currently appears in the following places:

- Certificate section of the participant admin page (i.e. /admin/participants/984#/)
- Type list drop-down and column at /admin/certificates
- On the certificate specific page (i.e. /admin/certificates/662#/) available by clicking on the PDF icon in the right column at /admin/certificates
 - In the URL of the certificate file as hosted on s3. This is the URL visible when you log in as a participant and open your certificate

**Comment by dboyer** [comment]
For QA purposes, the "completion" name for a certificate currently appears in the following places:

- Certificate section of the participant admin page (i.e. /admin/participants/984#/)
- Type list drop-down and column at /admin/certificates
- On the certificate specific page (i.e. /admin/certificates/662#/) available by clicking on the PDF icon in the right column at /admin/certificates
- In the URL of the certificate file as hosted on s3. This is the URL visible when you log in as a participant and open your certificate

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3527?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by devkonrad** [comment]
If the purpose of this task is use te same ID (Zero) from "Completion" to "Quarterfinalist" certificate, as could test locally we just need to change the label in this file, like bellow:
**From:**
![Captura de tela de 2022-07-27 10-12-19.png](https://images.zenhubusercontent.com/620a6a3009cc3bdf05b78b23/25b78851-dc9c-4067-931a-86b7df55533c)
**To:**
![Captura de tela de 2022-07-27 10-11-49.png](https://images.zenhubusercontent.com/620a6a3009cc3bdf05b78b23/f0f2db24-2f50-4ad6-ac1d-35d6a50739b9)

But, if we do that, all the references about the certificates "Completion" (including previous seasons) will be renamed to "Quartefinalist". Is that the idea?
@dboyer @shaunxp20 @viviancan

**Comment by devkonrad** [comment]
I created this PR to tackle this issue: https://github.com/Iridescent-CM/technovation-app/pull/3556

**Comment by dboyer** [comment]
Checked on QA and everything looks good except the certificate still references completion in the s3 URL.

The URL was /files/certificate/file/696/2022-completion-978-393.pdf but the certificate showed quarterfinalist. Maybe this is just because the certificate was uploaded to S3 with that in the URL? You can access the certificate by logging in as an admin, going to the certificates page, and then clicking the PDF icon in the right column. On the next page, select "view this certificate." The s3 URL will be visible in the URL for the next page.

<img width="682" alt="Screen Shot 2022-07-29 at 5 51 34 PM" src="https://user-images.githubusercontent.com/516764/181847753-82f4ce54-2e5c-47e8-8007-1c9a9310092a.png">

**Comment by devkonrad** [comment]
> The URL was /files/certificate/file/696/2022-completion-978-393.pdf but the certificate showed quarterfinalist. Maybe this is just because the certificate was uploaded to S3 with that in the URL? You can access the certificate by logging in as an admin, going to the certificates page, and then clicking the PDF icon in the right column. On the next page, select "view this certificate." The s3 URL will be visible in the URL for the next page.

Hum... Good catch, @dboyer! I will investigate about the certificate filename.

**Comment by devkonrad** [comment]
> Checked on QA and everything looks good except the certificate still references completion in the s3 URL.
> 
> The URL was /files/certificate/file/696/2022-completion-978-393.pdf but the certificate showed quarterfinalist. Maybe this is just because the certificate was uploaded to S3 with that in the URL? You can access the certificate by logging in as an admin, going to the certificates page, and then clicking the PDF icon in the right column. On the next page, select "view this certificate." The s3 URL will be visible in the URL for the next page.
> 
> <img alt="Screen Shot 2022-07-29 at 5 51 34 PM" width="682" src="https://user-images.githubusercontent.com/516764/181847753-82f4ce54-2e5c-47e8-8007-1c9a9310092a.png">

Hi, @dboyer! The certificate that you accessed was generated after or before the change of the name? If it was generated before i suspect that it need to be regenerated. Hi, @viviancan! When you generated locally the certificates the filename showed was correct? Thanks!

**Comment by devkonrad** [comment]
> Checked on QA and everything looks good except the certificate still references completion in the s3 URL.
> 
> The URL was /files/certificate/file/696/2022-completion-978-393.pdf but the certificate showed quarterfinalist. Maybe this is just because the certificate was uploaded to S3 with that in the URL? You can access the certificate by logging in as an admin, going to the certificates page, and then clicking the PDF icon in the right column. On the next page, select "view this certificate." The s3 URL will be visible in the URL for the next page.
> 
> <img alt="Screen Shot 2022-07-29 at 5 51 34 PM" width="682" src="https://user-images.githubusercontent.com/516764/181847753-82f4ce54-2e5c-47e8-8007-1c9a9310092a.png">

Hi, @dboyer! I suspect tha the name of URL was wrong, because the certificates need to be regenerated. I did it locally to test and the new URL looks correct:

![Captura de tela de 2022-07-29 20-07-36](https://user-images.githubusercontent.com/99268176/181858361-93f438f9-ea81-436c-a48c-f38d8836d08f.png)

**Comment by dboyer** [comment]
Perfect! Thanks for checking that.
