### ISSUE TITLE
Update quarterfinalist certificate template

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3530]
There was an extra word in the quarterfinalist template. It has been removed and the updated template is [available here](https://www.dropbox.com/home/Distribution/Campaigns%2C%20Initiatives/2022/2022-Certificates/2022-Certificates-Platform?preview=2022-Certificates-Quarterfinalist.pdf) and needs to be added before we generate certificates.

All the other templates are fine.

**Comment by shaunxp20** [comment]
This one is ready to be looked at on QA.
