### ISSUE TITLE
Add hero image and links to homepage/login

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3533]

**Comment by viviancan** [comment]
@dboyer Can you verify the links for "Chapters" and "Getting Started" in the navbar? Thank you!

**Comment by dboyer** [comment]
Getting Started should go to https://technovationchallenge.org/get-started/

I confirmed with PT that we can actually remove the Chapters link from the nav bar. Since the wireframes were made, the chapters info has been folded into that getting started page.

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by dboyer** [comment]
I'm also seeing this on QA and confirming the top nav adjusts based on screen size. This looks so much more engaging! Thanks for playing with the shading and color on the text!

**Comment by dboyer** [comment]
After review with PT and MT, requested changes are:

- Update the font for Sign in to be Rubik
- Replace hero image with additional image provided by @audsbodin
