### ISSUE TITLE
Inaccurate judge registration messaging

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3544]
Our admin controls allow for judging to be turned on and judge registration to be turned off, which will create a scenario with inaccurate messaging indicating judge registration is open (when it's not).

- Keep judging registration on or off decoupled from judging being on or off
- Update the heading and first paragraph of text to be conditional and only display if judging registration is toggled on

![incorrect-judge-message](https://user-images.githubusercontent.com/58957909/179828412-ce34909f-3690-41cd-a00b-3ebf69d40f4f.png)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3544?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Hey everyone, here are the different scenarios for the home page. Please let me know if I am missing any combination of toggles! Thank you

![Home Page Scenarios.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/29564ad2-94a2-4354-9b65-f95fe0763bf9)

![Home Page Scenarios 2.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/bd6b23f4-5e96-4722-a9ff-d7f124d36a9b)

**Comment by viviancan** [comment]
Changes can be demoed [here](https://review-3544-inaccurate--2zkg2l.herokuapp.com/)

**Comment by dboyer** [comment]
Confirmed that the home page updates as expected based on whether judging is available and judge registration is open or closed. I will check with PT on text for the home pages for the new season but that text does not need to block deploying this change.

**Comment by ksrebecca** [comment]
with the new judge registration toggle i think the only thing to specify in the list is "student/mentor registration" vs judge reg for future reference. also i believe we have not used the second scenario (judging enabled but judge registration off) for a couple seasons, might be worth checking with VET to see if they think they'll have that scenario again (or at least not spend too much time editing that home screen for text changes - internal note for self)
