### ISSUE TITLE
Bug: Total points available for demo section is being doubled

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3546]
The demo section of scoring has three questions if the project is a mobile app and three different questions if the project is an AI submission. The total points available for the section, which are listed in parentheses after the Demo heading, are being doubled. i.e. There should be 15 points available in the senior division and it is listed as 30 points. And there should be 9 points available in the beginner division and it is listed as 18 points available.

<img width="600" alt="Screen Shot 2022-07-19 at 9 39 08 AM" src="https://user-images.githubusercontent.com/516764/180034385-24b78f18-d002-433f-87b2-39372d6aef62.png">

## QA STEPS

- As a mentor, view score details for a submission
- Verify the total for the Demo section is 15 (not 30) for the junior and senior division, and 9 (not 18) for the beginner division

**Comment by dboyer** [comment]
![Screen Shot 2022-07-20 at 12.02.59 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/fb41ecc2-d831-474c-8ee8-95c188929b2b)

**Comment by dboyer** [comment]
Tasks:

- [ ] Fix bug with how the total points available are displayed

- [ ] Add "points possible" after number in parentheses. Example: 9 points possible

**Comment by shaunxp20** [comment]
>  Add "points possible" after number in parentheses. Example: 9 points possible

I added a new "Score" row to each section - I used score instead of points because in the header (on the same page) it mentions score, it wouldn't be a problem to update this.
