### ISSUE TITLE
Project on QA has a score of zero for project details section

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3551]
While testing the fix for #3546 , we found a score that has a zero in the "project details" section - /student/scores/627

Projects should not be able to have a zero for that section. Perhaps this is a one-off thing but wanted to check that there wasn't any larger issue.

**Comment by viviancan** [comment]
We do not think this is a larger issue.

After checking QA we found 10 completed scores that fit the same criteria. 9 of those were created on the same day, which could be related to when the judging flow was being updated. Regardless, after checking production, there were 0 completed scores that had a score of zero in the "project details" section.
