### ISSUE TITLE
Reenable button to add and view events

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3561]
In #2738, the button to add events was greyed out to prevent people from inadvertently adding events in 2021 or 2022. Even though I changed the content and settings on QA to allow events, the button remains greyed out. I believe that #2734 will also prevent students from viewing events even if they are added.

We need to either revert the changes in #2738 and #2734 or otherwise make it possible to add and view events again on QA so we can test the RPE process. The overall ability to add/view events should continue to be controlled by this setting on the admin:

<img width="463" alt="Screen Shot 2022-08-01 at 10 01 00 AM" src="https://user-images.githubusercontent.com/516764/182165040-2f200629-4551-4de8-8a55-ee4b2dccd19d.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3561?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
Regional pitch events can now be created on QA. I also reverted some of the COVID related text. There will still be more text updates, and other things we'll have to update too, but this is at least is a starting point to see where we're at!
