### ISSUE TITLE
Investigate the mentor details view - which ties into missing "add mentor to team button"

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3576]
We noticed the add mentor to team button was missing on the mentor details page when a student is trying to add them to their team. There could be a configuration issue, incorrect URL, or maybe something weird going on with the impersonation feature. See screenshots below.

**Comment by viviancan** [comment]
![CleanShot 2022-08-08 at 13.05.44@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/938c7e4a-49d6-44b2-81d2-072ffba23831)

**Comment by viviancan** [comment]
It seems that there is something going on with the "impersonation" mode vs being actually logged in. When logged in as a student and trying to add a mentor to my team, I am unable to access the mentor details page. I am redirected to the dashboard with the permission error. I wonder if it has to do with the URL/scope etc...

https://images.zenhubusercontent.com/29868115/ef5a7878-5bd0-4336-b10f-5099e1d93e38/cleanshot_2022_08_08_at_13_47_45.mp4

**Comment by viviancan** [comment]
The mysterious missing add mentor button has been solved! This refs to a previous change in #3536 in the file `app/views/mentor_searches/rebrand/_mentor_preview.html.erb` with the link to "More Details >". The URL is incorrect (line 23). 

In the original mentor preview (`app/views/mentor_searches/_mentor_preview.html.erb`) there is a conditional that determines the URL
```
    <% if current_scope == "mentor" %>
      <%= link_to "View more details",
        mentor_mentor_path(mentor_preview, review_before: true),
        class: 'button' %>
    <% else %>
      <%= link_to "View more details",
        student_mentor_path(mentor_preview, review_before: true),
        class: 'button' %>
    <% end %>

**Comment by devkonrad** [comment]
Thanks for the catch, @viviancan! I will fix this. :)

**Comment by devkonrad** [comment]
Created the PR https://github.com/Iridescent-CM/technovation-app/pull/3581 to fix the link

**Comment by viviancan** [comment]
Verifying that I tried this functionality locally and it worked as expected. The mysterious button has now returned! Right now the add mentor to team button is disappearing unless you hover over it, but once we rebrand the details page, that issue will be solved. I would assume there will be other buttons throughout the platform on unbranded pages that exhibit the same behavior.

**Comment by dboyer** [comment]
Confirmed on QA that this page is back and the button is working as expected, although it is not visible until you hover on it as Vivian noted. We'll need to restyle this page as noted in #3577
