### ISSUE TITLE
Rebrand student mentor details view

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3577]

**Comment by viviancan** [comment]
I'm not sure if we have a rebrand mockup for this page, if we do not, then maybe we can follow the team details rebrand

![CleanShot 2022-08-08 at 14.43.29@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/1c814037-5d2e-46da-a696-508b7c40ff2b
)

**Comment by dboyer** [comment]
Just checked and there is not a mockup for the student mentor details view. Agreed that we should follow the layout outlined in #3516 and shown below.

<img width="488" alt="Screen Shot 2022-08-08 at 4 32 00 PM" src="https://user-images.githubusercontent.com/516764/183509069-a43ed8ae-b234-453b-9a5f-4ea29e471535.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3577?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
I am going to take a look at this one! :)

**Comment by viviancan** [comment]
Verifying that this is on QA!
