### ISSUE TITLE
Rebrand reset password page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3578]
The reset password page at https://my.technovationchallenge.org/password_resets/new#/ has the old branding.

<img width="1440" alt="Screen Shot 2022-08-08 at 8 06 40 PM" src="https://user-images.githubusercontent.com/516764/183535051-59095e68-c9a2-488b-8d7d-bae482a1a970.png">

There's no existing mockup so let's use the general layout of the sign-in page.

![login](https://user-images.githubusercontent.com/516764/183535625-ee9515cc-e740-4f1c-8bd7-a165588dda2f.png)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3578?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by dboyer** [comment]
Follow the same pattern and use the same energetic components/integration as the sign-in page.

**Comment by devkonrad** [comment]
Created the PR https://github.com/Iridescent-CM/technovation-app/pull/3601 to solve this issue. :)

**Comment by dboyer** [comment]
Confirmed this page is rebranded on QA
