### ISSUE TITLE
Student avatar images very large on mentor invite page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3583]
When a mentor receives an invite to join a team, they click a button in an email that takes them to /mentor/mentor_invites/.....

Eventually, that page will be rebranded as part of the larger mentor dashboard rebranding. However, currently the avatars for the students are very large on this page and it makes it challenging to see the accept/decline buttons for the invitation that are at the very bottom.

Is there an option to resize these images so they are not gigantic, even if we're not fully rebranding this page?

![Mentor_Invite_AcceptDecline](https://user-images.githubusercontent.com/516764/184363379-60d5b80c-ebfa-4463-92f0-4519b212153e.png)

## QA STEPS
- As a student, invite a mentor to your team
- Log in as that mentor and view the invite
- Verify the invite summary page doesn't have giant student avatar images

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3583?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
The invite summary page for mentors was displaying the rebranded view (but it wasn't getting the rebranded styles which made the avatars giant!), so I just reverted it to display what it was displaying before (no other changes were made), which includes normal-sized student avatars. Anywho, this change/fix is on QA! 😄

**Comment by dboyer** [comment]
Confirmed on QA that the student avatars are now the correct size.

**Comment by dboyer** [comment]
@shaunxp20 During QA, we found that the student avatars are correct on this page but if the team already has a mentor, the mentor's avatars are still large.

![image.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/00356e40-651f-4532-b453-9ba5d37269a1)
