### ISSUE TITLE
Upload new parental consent form

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3585]
We expect to have a new parental consent form provided by our lawyers in the next week. We'll need to swap in the new form for the old one.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3585?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by dboyer** [comment]
The new parental consent form is now available. The [text version is here](https://docs.google.com/document/d/18S2x4xTjarQ18fSGlxCv7N3M9ZSImi4j/edit#) and a [PDF version is here](https://drive.google.com/file/d/1-yGaRig3YQzIMaKl3W6SoL71NGWS4WYC/view?usp=sharing).

There are three tasks:

- [ ] Update the text that appears when the parent clicks the "sign the forms" button in the parent consent email
- [ ] Update the email copy they receive after signing
- [ ] Update the copy of the form that can be signed by downloading the doc on the parental consent tab of the student profile

**Comment by shaunxp20** [comment]
These text changes are on QA. 👍

**Comment by dboyer** [comment]
There are a few paragraphs that need to be adjusted in the welcome letter.

- The third paragraph in the top welcome letter that begins "It won't always be easy...." should be replaced with updated text. There are several wording changes and the final link in that paragraph needs to go to https://www.technovation.org/safety/
- In the following paragraph, it should be "whether your child chooses to work in a team or on her own..." rather than "whether your daughter..."
- The last line of the letter should say "If you have any questions at any time,"

**Comment by dboyer** [comment]
Confirmed on QA that the copy of the signed form sent via email is updated and the link to download the form also goes to the new text.

**Comment by shaunxp20** [comment]
> There are a few paragraphs that need to be adjusted in the welcome letter.
> 
>     * The third paragraph in the top welcome letter that begins "It won't always be easy...." should be replaced with updated text. There are several wording changes and the final link in that paragraph needs to go to https://www.technovation.org/safety/
> 
>     * In the following paragraph, it should be "whether your child chooses to work in a team or on her own..." rather than "whether your daughter..."
> 
>     * The last line of the letter should say "If you have any questions at any time,"

I originally updated the wrong text/file, I reverted those incorrect changes and made these changes. Anyhow, it's on QA now, ready for a looksie. 😄

**Comment by dboyer** [comment]
Updated text looks good on QA!
