### ISSUE TITLE
Update new registration system so students can send invites even if registration is closed

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3586]
In the previous registration system, admins and ChAs could send invites even if registration was closed. That feature is not available in the new registration system.

We should review the code for this feature from the old registration system and determine whether any aspects of it can be used in the new system. If not, we'll need to figure out another option.

Split off of #3497

**Comment by viviancan** [comment]
We will need to review what is there and maybe some of the existing code can be refactored or referenced. It may be a heavier ticket, though, since this feature was not considered when we planned/built out the new registration functionality.

**Comment by viviancan** [comment]
@dboyer What is the expected time frame for this functionality?

**Comment by dboyer** [comment]
Agreed, and I have a note to talk about this at the dev team priorities meeting today This may end up being just a research task for the next iteration. I mostly wanted to make sure we checked out the old code for anything that could be reused before we fully removed it, which is another lingering task from #3053.

Invites during closed registration isn't needed until March 2023 when we have the small window where student registration is closed but submissions are open. Admins occasionally need to send an invite then when a user isn't registered in the system but has been working with a team.

**Comment by dboyer** [comment]
Revising this to clarify:

Students on a team should be able to continue to send an invite to another person to join that team in the time period between registration closing and projects being submitted. If a person receives an invite to register in that time period, they should be able to do so even if the student or parent registration toggles are off.

**Comment by shaun-technovation** [comment]
> Revising this to clarify:
> 
> Students on a team should be able to continue to send an invite to another person to join that team in the time period between registration closing and projects being submitted. If a person receives an invite to register in that time period, they should be able to do so even if the student or parent registration toggles are off.

Thinking about this again, I think this will be similar to the admin registration invites. We'll need to attach an invite code of some kind to the signup URL, then we'll need to check the conditions of the invite (a student already on a team, in the time period, etc), and then enable/disable registration based on that. I'll keep noodling on this and create some tickets for the work I think we need to do. 👍

**Comment by dboyer** [comment]
Note: students should be able to invite both students and mentors to join their team.

**Comment by shaun-technovation** [comment]
I broke down this issue into the following issues: #4283, #4245 and #4284.

**Comment by dboyer** [comment]
Closing as the work to implement this feature will happen in the three issues mentioned above.
