### ISSUE TITLE
Update default team image

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3587]
We need to remove the current default team image which matches the older branding. A new photo will be selected by the start of the iteration.

<img width="286" alt="Screen Shot 2022-08-15 at 10 42 30 AM" src="https://user-images.githubusercontent.com/516764/184656921-d85916b6-0b63-4ff5-bf70-ab84907ddd21.png">
 
## QA NOTES
- The new "star hands" team image will only apply to teams in the 2023 season and beyond
  - To test the "star hands" image, the season will need to be updated to 2023 on QA
- All existing teams (pre-2023) using the old default (the collage style) team image, should still be using the old default image

**Comment by dboyer** [comment]
![Screen Shot 2022-08-17 at 1.45.30 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/1ffb560a-8a5d-49f9-a578-957f02c88090)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3587?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by dboyer** [comment]
We can use the image here https://www.dropbox.com/s/iwcs5lm5d6egl46/Avatar-Team5.png?dl=0

**Comment by shaunxp20** [comment]
This one is on QA. I added some QA'ing notes to the issue summary - basically the new star hands image will only be for new (2023 and beyond) teams. 👍 😄
