### ISSUE TITLE
Tailwind V3 upgrade - fallout tasks

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3590]
This Refs #3468 and will serve as a ticket to catch any of the random tasks/updates needed due to the tailwind v3 upgrade

**Comment by viviancan** [comment]
- [ ] Upload button on student edit profile does not display unless you hover over it

![CleanShot 2022-08-15 at 14.47.32.gif](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/dd427917-79a1-4962-b537-eacaf04f13e3)

**Comment by shaunxp20** [comment]
- [ ] "Send the form" button on the parental consent form

![parental-consent-button](https://user-images.githubusercontent.com/58957909/186761061-14036d82-5f71-4fbf-b92e-de4144dcbef1.png)

**Comment by dboyer** [comment]
The issue with the button the parental consent form email should be fixed when we merge the rebranded page from #3333 on to production.

**Comment by dboyer** [comment]
![Screen Shot 2022-08-31 at 11.33.13 AM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/15f92a1b-33d4-4af5-b125-e03c91c01c94)

**Comment by dboyer** [comment]
Closing as the remaining issue with the disappearing button is listed in #3628
