### ISSUE TITLE
Rebrand the image upload confirmation to match new styles depending on image upload updates

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3591]

**Comment by viviancan** [comment]
this page is  at the url `/student/profile_image_upload_confirmation?` and displays when you upload a new profile image as a student 

![CleanShot 2022-08-15 at 15.05.31@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/cfd523e2-e0c6-4c87-8ccc-256f928858ef
)

**Comment by dboyer** [comment]
This page no longer exists since photo upload is now done through Filestack.
