### ISSUE TITLE
Confirm media consent forms resets each season

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3597]
Since we added online media consent in 2021, we need to confirm that the media consent form is required for each season. 

That may be part of the check in the "registered to current season" job or it may be part of the season [reset rake task](https://github.com/Iridescent-CM/technovation-app/blob/96404ee861351acf39714176566a16007a4133b6/lib/tasks/reset_for_season.rake#L11-L19). It might be covered under the "consent waiver" (line 11) but we'll want to confirm.

Confirmed with PT that media consent is a yearly reset thing.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3597?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
I was able to confirm that media consents get reset for each season, I tried it locally (setting my local environment to be in the 2023 season) and it's working as expected.

When a student is registered to a new season, a new media consent is created for them:
https://github.com/Iridescent-CM/technovation-app/blob/7b61c7145d02ccaf3ae3d9a0bedf133f18ebeff6/app/jobs/register_to_current_season_job.rb#L71

And when we reference a student's media consent it's for the current season (which would be the one created from the step/job above):
https://github.com/Iridescent-CM/technovation-app/blob/7b61c7145d02ccaf3ae3d9a0bedf133f18ebeff6/app/models/student_profile.rb#L99

**Comment by shaunxp20** [comment]
Related to the season rollover (but not media consent specific), a few things popped out to me as a returning student:
- I wasn't prompted to re-sign the data use terms
- The parental consent is reset, but it isn't entirely clear that it needs to be re-signed, it's sort of in a pending mode where it shows: "A request for parent program permission and media consent was sent to..." which seems kinda weird

There could be other things, that was just at first glance.

A random side note, if we don't already have one, it would be nice to have a new season testing checklist, like:
- [ ] Data use terms are reset
- [ ] Parental consent is reset
- [ ] Media consent is reset
etc etc

😄

**Comment by shaunxp20** [comment]
> Related to the season rollover (but not media consent specific), a few things popped out to me as a returning student:
> 
>     * I wasn't prompted to re-sign the data use terms
> 
>     * The parental consent is reset, but it isn't entirely clear that it needs to be re-signed, it's sort of in a pending mode where it shows: "A request for parent program permission and media consent was sent to..." which seems kinda weird

Following up with this, the data terms **are presented to be re-signed** - when I originally ran the `reset_for_season` rake task, I thought it ran successfully - it didn't and it wasn't clear that it didn't run successfully; I ran it again with the force flag and got a "Resetting for new season" message. We could look at updating the messaging in the rake task when it doesn't run to make it clearer.

**Comment by dboyer** [comment]
Thanks for confirming media consent is reset. To confirm, the reset_for_season rake task, resets both the data terms and the parental consent or just the data terms?

And agreed on the season testing checklist. I have it and will transfer it to Github asap.
