### ISSUE TITLE
Rebrand student page to accept or decline a mentor request

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3602]
When a mentor requests to join a team, the team receives an email with a button to "Review this Request." Clicking that button takes the user to a page where they can see basic details for the mentor and accept or decline the request (/student/join_requests/....) That page currently needs rebranding as the layout is not user friendly and the approve request button is only visible upon hover.

![Review Mentor Request](https://user-images.githubusercontent.com/516764/186189358-214490b8-a305-4625-8f5c-220ffd417aed.png)

We'll need to find a mockup for this.

**Comment by dboyer** [comment]
The page where a student accepts or declines an invite to a team is very similar in content. We can follow this layout.

<img width="1130" alt="Screen Shot 2022-09-02 at 11 03 27 AM" src="https://user-images.githubusercontent.com/516764/188178376-55a4d70b-3c8e-4648-8e3c-31f6f9b82482.png">

**Comment by shaunxp20** [comment]
This one is on QA.

A couple of notes:
- I also updated/rebranded a pending student join request
- When someone views a join request after it has been approved or declined, that page still has the old styling which doesn't look terrible, I guess we can decide later if we want to update this or not:
<img src="https://user-images.githubusercontent.com/58957909/192651703-3e2db3f6-debf-48cb-bf1a-7fb2b4ae64e9.png" width="300">

**Comment by dboyer** [comment]
Tested on QA and confirmed that responding to a mentor invite is working as expected. I agree that the page to view an already approved/declined request is okay. I don't think it's worth updating now considering other tasks that we have.

@shaunxp20 Where is the pending student join request that you rebranded? I'm looking at /student/team_member_invites/ (the page where a student responds to an invite to join a team) and it looks like it did previously. Is there a different page I should be reviewing?


<img width="1261" alt="Screen Shot 2022-09-28 at 1 38 37 PM" src="https://user-images.githubusercontent.com/516764/192851218-c4f06119-0192-4e76-9476-c2505e8e0973.png">

**Comment by shaunxp20** [comment]
> @shaunxp20 Where is the pending student join request that you rebranded? I'm looking at /student/team_member_invites/ (the page where a student responds to an invite to join a team) and it looks like it did previously. Is there a different page I should be reviewing?

> <img alt="Screen Shot 2022-09-28 at 1 38 37 PM" width="1261" src="https://user-images.githubusercontent.com/516764/192851218-c4f06119-0192-4e76-9476-c2505e8e0973.png">

Yes, it's a different page, it's kinda confusing. The image above is for an invite, I updated the join request pages, which is where a student or mentor requests to join a team, and then a student on that team views that join request. It looks like this:

<img src="https://user-images.githubusercontent.com/58957909/192858127-4a43ce75-cf55-4a06-bacf-542ba478f02c.png" width="300">

**Comment by dboyer** [comment]
Confirming that page looks correct on QA too!
