### ISSUE TITLE
Update platform email text for 2023 season

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3603]
Once approved by VET and PT, we'll need to make any necessary email text updates. [Doc with text is available here](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#).

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3603?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by dboyer** [comment]
The text for the emails is ready to update:

- [ ] Welcome Email - [Students (Jr/Sr only)](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.n9ff7zr68rrs)
- [ ] Welcome Email - [Beginner Division](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.l191k1iv37zx)
- [ ] [Parents Thank You](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.mizgvsy4x0fl) (for Jr/Sr participants)
- [ ] Parent Consent [Signature Request](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.8j0op1ikf5bv)

**Comment by viviancan** [comment]
@dboyer Ty for the direct links to each of the sections, it was very helpful!

**Comment by dboyer** [comment]
Tested on QA:

- [x] Welcome Email - [Students (Jr/Sr only)](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.n9ff7zr68rrs)
- [X] Welcome Email - [Beginner Division](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.l191k1iv37zx)
- [] [Parents Thank You](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.mizgvsy4x0fl) (for Jr/Sr participants)
- [x] Parent Consent [Signature Request](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.8j0op1ikf5bv)
- [x] Welcome Email - [Mentors](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.1xrmgel9teja)

@viviancan I couldn't find where the parent thank you for junior/senior division appears. Could you confirm where that text is? Nothing I did (including a parent email when registering as a jr/sr, signing the parental consent form as a parent) caused me to get that email.

**Comment by viviancan** [comment]
@dboyer 
I'm not sure where/when that text is sent. I can investigate the code to identify what triggers it!

**Comment by viviancan** [comment]
@dboyer I found a [commit message ](https://github.com/Iridescent-CM/technovation-app/commit/13f622274c56e3e4875c5f3572dccef183f79820)from 2017 on the parent mailer file that states "Send thank you email to parents 3 days after they sign the permission form" - so maybe that email will come to you in 3 days? Be on the lookout!

**Comment by dboyer** [comment]
Confirming that I did receive the parent thank you email three days later!

**Comment by viviancan** [comment]
> Final round of text changes/updates:
> 
> * [x]  [Email to mentor](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.nvgs7yq1ey9h) confirming team acceptance
> * [x]  In the list of dates in the welcome emails for [junior/senior students](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.n9ff7zr68rrs) and [beginner students](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.l191k1iv37zx), the last date is listed as April 18th when it should just be April 18 to match the date format used in the other rows.
> * [x]  In the [parent thank you email](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.mizgvsy4x0fl), the word "celebration" needs to be after "our virtual World Summit."

@dboyer These are on QA now!

**Comment by dboyer** [comment]
Confirmed the three changes are on QA

**Comment by dboyer** [comment]
Changes requested after QA:

- [ ] In [parent consent email](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.8j0op1ikf5bv), change "female-identifying students" to "girls" and link girls to https://www.technovation.org/diversity-equity-inclusion-statement/

**Comment by viviancan** [comment]
> Changes requested after QA:
> 
> * [x]  In [parent consent email](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.8j0op1ikf5bv), change "female-identifying students" to "girls" and link girls to https://www.technovation.org/diversity-equity-inclusion-statement/

Just merged this to QA! Should be there in about 30 minutes after the tests finish

**Comment by dboyer** [comment]
Confirmed this change is on QA

**Comment by dboyer** [comment]
Apologies @viviancan, I missed one late-breaking change. In the same [parent consent](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.8j0op1ikf5bv) email, PT requested that we remove "immediately" after "If you still have questions, email us at support@technovation.org"

**Comment by viviancan** [comment]
@dboyer the final change is on QA!

**Comment by dboyer** [comment]
Confirmed the change is on QA!

**Comment by dboyer** [comment]
One more....sorry!

In the [welcome email for mentors](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.1xrmgel9teja), there's a link to the timeline in the "let's get started" section that is going to the 2022 timeline. It should go to https://technovationchallenge.org/wp-content/uploads/2022/09/2023-ProgramTimeline_vertical.jpg instead

**Comment by viviancan** [comment]
> One more....sorry!
> 
> In the [welcome email for mentors](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.1xrmgel9teja), there's a link to the timeline in the "let's get started" section that is going to the 2022 timeline. It should go to https://technovationchallenge.org/wp-content/uploads/2022/09/2023-ProgramTimeline_vertical.jpg instead

This is on QA!

**Comment by dboyer** [comment]
Confirmed this is updated on QA

**Comment by viviancan** [comment]
> > One more....sorry!
> > In the [welcome email for mentors](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.1xrmgel9teja), there's a link to the timeline in the "let's get started" section that is going to the 2022 timeline. It should go to https://technovationchallenge.org/wp-content/uploads/2022/09/2023-ProgramTimeline_vertical.jpg instead
> 
> This is on QA!

Not for future peeps: This link is in 4 files
- welcome mentor
- welcome student
- welcome parent
- curriculum

It would be best to do a "Find all" and then replace each of the links as necessary

**Comment by dboyer** [comment]
Confirmed the correct link is on QA
