### ISSUE TITLE
Spike: Explore current cookie implementation and select cookie management option

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3606]
We are making updates to the Technovation privacy policy that will require implementation of a cookie management system that allows users to opt out of non-essential cookies. Such a system has already been implemented on the Technovation Wordpress sites via a plug-in. Screenshots below:

<img width="1440" alt="Screen Shot 2022-08-29 at 10 24 35 AM" src="https://user-images.githubusercontent.com/516764/187224140-560a83c3-cafd-4034-9948-83e24580d57f.png">

<img width="782" alt="Screen Shot 2022-08-29 at 10 24 58 AM" src="https://user-images.githubusercontent.com/516764/187224232-6c1cd9fb-e222-4592-802f-c1c6b72b23af.png">

For this task, it would help to:

- Compile a list of all cookies used on the TG platform including the name of the cookie, the purpose, whether it is strictly necessary, and when it expires
- Determine if use of cookies on TG is at all inherited from permissions set by users to the Wordpress platforms (i.e. if you select only strictly necessary cookies on technovation.org and then click to my.technovationchallenge.org, is the cookie permission maintained between platforms). I doubt it but it's good to confirm.
- Research a cookie management option. The WordPress sites use CookieYes, but from their website, it might just be a plugin for CMS's and not useful for us.

This does not need to be done by opening of registration but would ideally be done before registration really picks up in January.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3606?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
Here's a start to the cookie exploration. I'll just keep this comment updated as I go.

GLOBAL_INVITATION_TOKEN - Used for the old judge registration flow, where we used one link for all judges to sign up with
LAST_PROFILE_USED - Used to determine which dashboard to render
LAST_VISITED_SUBMISSION_SECTION - Used to determine which section to redirect a student to after updating a section
IP_GEOLOCATION - Used in the old registration flow, we store an IP address, and then later use that to determine location based on IP address
REDIRECTED_FROM - Used when someone is trying to do something w/o being authenticated, it stores the page and then after signing in, redirects them to that page 
SIGNUP_TOKEN - Used in the old registration flow to save progress
SIGNUP_WIZARD_MODE - Used to determine if we use the signup wizard (the pre-rebranded registration) or the "legacy" registration mode (I think this is the invite system)
ADMIN_PERMISSION_TOKEN - Used in the "legacy" registration mode

**Comment by dboyer** [comment]
@shaunxp20 Thanks for starting this list. I've started transferring these [to the chart](https://docs.google.com/spreadsheets/d/11AOMXBbBUWIZZAR1ZNOpGvE-6KivmL19zINDZZST3DQ/edit?usp=sharing) we need to include in the parental consent policy.

Feel free to keep logging them here, however, so we have a record in Github. Do they have different expirations or are they all persistent until the user clears cookies on their browser?

**Comment by shaunxp20** [comment]
> @shaunxp20 Thanks for starting this list. I've started transferring these [to the chart](https://docs.google.com/spreadsheets/d/11AOMXBbBUWIZZAR1ZNOpGvE-6KivmL19zINDZZST3DQ/edit?usp=sharing) we need to include in the parental consent policy.

Okay, I updated my previous comment. One thing to point out is that I discovered that the actual cookie names are environment variables, so for Prod, they would be in Heroku -> Settings.

> Do they have different expirations or are they all persistent until the user clears cookies on their browser?

I thought they were all session cookies, but I see one that expires in 2042, so I'll have to verify the expiration date of each cookie. I'm still working on that.

**Comment by shaunxp20** [comment]
I updated the spreadsheet again, in the "Strictly Necessary" column I added "probably" for some of them, because some of those cookies are for parts of the app that aren't being used but there are still ways to access them (like the old registration flow), and the cookies for these parts could very well be necessary for that part of the app to work correctly. We could verify if the cookies are strictly necessary, but we'd probably be better off spending the time to do some cleanup to remove the unused stuff so we can remove the associated cookies.

**Comment by dboyer** [comment]
Thanks for compiling this list! So there are no cookies specifically related to Heap, Mailchimp, SurveyMonkey, or Learnworlds? Or are those just API calls?

**Comment by shaunxp20** [comment]
> Thanks for compiling this list! So there are no cookies specifically related to Heap, Mailchimp, SurveyMonkey, or Learnworlds? Or are those just API calls?

I added a few more cookies to the spreadsheet! I didn't originally see these b/c a) I was using my admin account and b) I think some ad-blockers or plugins were interfering. Anywho, I created a new student account in Safari (no extra plugins) and found a few more!

**Comment by shaun-technovation** [comment]
> I moved all of the cookies to the spreadsheet: https://docs.google.com/spreadsheets/d/11AOMXBbBUWIZZAR1ZNOpGvE-6KivmL19zINDZZST3DQ/edit?usp=sharing

Just FYI, I updated this spreadsheet with a new "status" column, 5 cookies have been removed (two for Heap, and three related to the old signup/registration forms).

**Comment by shaun-technovation** [comment]
> @shaun-technovation Do you think this can be closed now since selecting a cookie management option will be part of #4278? Are there other cookies we want to remove? If so, perhaps those could be in a new issue.

Sounds good to me in regards to closing this issue! I agree more cookie removal can be done in new issues. 👍
