### ISSUE TITLE
Run the reset season rake task

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3607]
We need to reset the season on both QA and production in order to support opening registration. More details available [in this doc](https://docs.google.com/document/d/1oBVG_RMi6SVQ8KlznqmdRT_FuNCgRCkBy8maM4tXeWA/edit#) and in issue #3157. 

Specific tasks include:

- [x] QA
`heroku run bundle exec rails reset_for_season[force] --app technovation-qa`

<br>

- [x] Prod
`heroku run bundle exec rails reset_for_season[force] --app technovation`

This should:

- Reset data terms so that students, mentors, and judges all need to agree to the terms again
- Reset mentor training flag so mentors need to redo training
- Reset judge training flag so judges need to redo training
- Require students to get parental consent (even for returning students)
- Require students to get media consent (even for returning students)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3607?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
The reset season rake task has been run on QA. 👍

**Comment by ksrebecca** [comment]
Just discussed and yes! We've been aware of it! It serves a purpose as the
first parent email (the rest come via MailChimp)

**Comment by dboyer** [comment]
@ksrebecca Just confirming: by "first parent email" do you mean the thank you email that comes three days after they sign the parental consent form? If so, we're happy to keep that in place.

We just wanted to also check that it was okay for someone with an existing account logging in for the new season to automatically have a consent email sent to their parents. Alternately, we could require that the participant click the button to request that an email be sent to their parents.

**Comment by ksrebecca** [comment]
Sorry @dboyer meant "programmatic" first email aka lots of info for them that only comes at them a few times a year... 3 days seems like an interesting choice, I was not aware of that piece. For some reason I thought it came the same day. But am guessing it's separate to avoid confusion with the consent forms.

For the existing accounts, I think it's ok??? Although... it seems weird, right? Maybe we should have them click a button even though that's harder but might avoid some unintentional sends? I'm pretty torn on this one. What do you and @ophelieh think?

**Comment by ophelieh** [comment]
Hi all! I would recommend going with clicking the button as some people accidentally log in in hopes to get their certificates or scores but have no intention of participating in the new season

**Comment by dboyer** [comment]
PT testing on QA confirmed the season reset is working as expected.

**Comment by dboyer** [comment]
Thanks for the feedback, @ophelieh and @ksrebecca. We've added a separate issue at #3650 to require users to click to resend the email.

**Comment by shaunxp20** [comment]
Just a random note, I updated our rake task to have nicer output.

Example output:
```
Resetting consent waivers
Resetting data use terms
Resetting onboarded flags
Resetting mentor trainings
Resetting judge trainings
Finished resetting
```

```
The reset needs to happen on the season start date (2022-10-01) or you can run this rake task with the 'force' option (e.g. `bundle exec rake reset_for_season[force]`)
```

We'll have to make a deploy before running on this production if we want to see this output though.

**Comment by shaunxp20** [comment]
The season reset has been run on production.

```
Resetting consent waivers
Resetting data use terms
Resetting onboarded flags
Resetting mentor trainings
Resetting judge trainings
Finished resetting
```

**Comment by dboyer** [comment]
Tested on production:

- Registered new student account and had to complete parental consent/location
- Registered a new mentor account and had to complete data terms, location, mentor training, consent waiver
- Logged in with student account from 2022 season and had to agree to data terms again and get parental consent set again
- Logged in with a mentor account from 2022 season and had to agree to data terms, consent waiver, and do training again
- Logged in as a judge from 2022 and had to agree to data terms, sign consent waiver, and do training again
