### ISSUE TITLE
Finalize/complete filestack flow (cleanup tasks - more info to come)

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3613]
- [x] Admin portal ability to update profile images
- [x] Decide what "sources" are allowed for profile image upload (social media, webcam, web search, etc)
- [x] What do we do about icons 🤔
- [x] Verify s3 bucket policies for QA
- [x] Verify s3 bucket policies for prod
- [x] Verify team photo 
- [x] Decide if we will have default profile image (similar to team photo)
- [x] Add some styling to the "change image" button as it is currently just text and doesn't look like a button
~~- [x] The page to upload via URL looks like the button and text field aren't aligned
<img width="465" alt="Screen Shot 2022-09-21 at 10 01 54 AM" src="https://user-images.githubusercontent.com/516764/191525145-b51bafe8-81a6-458f-82eb-4398dca311b0.png">~~
We are not able to update this, as it is determined by filestack UI (VC)

**Comment by viviancan** [comment]
Refs #3605

**Comment by viviancan** [comment]
Added functionality to admin portal to update the participant profile image 

 https://images.zenhubusercontent.com/29868115/2557d8b0-1692-4b7b-9fb1-ba4ef8c24701/admin_filestack_profile_img_upload.mp4

**Comment by viviancan** [comment]
@dboyer 
2 questions - 
1.  What "sources" are allowed for profile image upload (social media, webcam, web search, etc)
2. What do we do about icons? Filestack allows for us to have a "custom source" to choose from, but I think we need the next higher paid plan.

**Comment by dboyer** [comment]
Answers!

1. Please remove web search, Facebook, and Instagram from the available sources
2. There is no need to keep the custom icons. They're super cute but no reason they have to be there.

**Comment by viviancan** [comment]
- [ ] ChA Profile: app/views/chapter_ambassador/profiles/show.en.html.erb
- [ ] Judge Profile: app/views/judge/profiles/rebrand/_basic.en.html.erb
- [ ] Mentor Profile: app/views/mentor/profiles/show.html.erb
- [ ] FetchAPI: app/views/profiles/_filestack_profile_image_upload.en.html.erb

**Comment by viviancan** [comment]
Verifying the clean-up tasks are on QA. You should now be able to update profile image for all profile types. For accounts that do not have a profile image, you should see the hedgehog default image. If there is a previous profile image that should also display correctly.

**Comment by viviancan** [comment]
I added a few notes to our documentation repo!

**Comment by dboyer** [comment]
Confirming on QA that I can:

- See default hedgehog
- Upload a photo to a mentor profile
- Upload a ChA photo
- See profile photo I uploaded last season for an existing account
- Upload a photo to a judge profile
- See styling on the change image button

**Comment by viviancan** [comment]
@dboyer verifying that team photo does not use filestack and the current upload process is broken - similar to profile photo uploads before filestack. This has been logged in #3658
