### ISSUE TITLE
Rebrand page to enter new password

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3617]
The page to request a password reset was rebranded in #3578 but the actual page where you enter the new password was not. This is the page the user views after clicking the link in their email to reset their password.

<img width="1248" alt="Screen Shot 2022-09-06 at 2 18 02 PM" src="https://user-images.githubusercontent.com/516764/188709465-be2be75e-9bb5-47a7-b667-33936331915a.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3617?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
This rebranded page is now on QA, I copied a lot of the design from the "Reset your password" page (where you enter your email address).

**Comment by dboyer** [comment]
Confirmed that I see the rebranded password reset page and was able to reset my password.
