### ISSUE TITLE
Mentor avatars are large on mentor invite page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3623]
@shaunxp20 During QA, we found that the student avatars are correct on this page but if the team already has a mentor, the mentor's avatars are still large.

![image.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/00356e40-651f-4532-b453-9ba5d37269a1)

_Originally posted by @dboyer in https://github.com/Iridescent-CM/technovation-app/issues/3583#issuecomment-1244170439_

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3623?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
This one is on QA, the mentor section should look the same as the student section now.

**Comment by dboyer** [comment]
Confirming that the mentor avatars also look correct on QA
