### ISSUE TITLE
Upgrade Heroku on production from stack18 to stack22

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3624]
The upgrade was completed on QA as part of #3491 . We need to complete the production upgrade.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3624?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
I upgraded Heroku to Stack 22 for production via the GUI and it worked as expected, so I think we're good regarding this upgrade!
