### ISSUE TITLE
Update info text about age on bottom of registration page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3625]
Looks like the info about ages and dates at the bottom of the registration page is hardcoded. It didn't update when I changed the season dates. This should read: 

As of August 1, 2023. For example, if you turn 13 on July 28, 2023, you will need to select "I am registering myself and am 13-18 years old."

<img width="757" alt="Screen Shot 2022-09-13 at 2 22 40 PM" src="https://user-images.githubusercontent.com/516764/189980631-c8464709-4dc5-44a9-8b07-771a61c64996.png">

**Comment by dboyer** [comment]
Same thing for the birthdate counter in the registration process

<img width="708" alt="Screen Shot 2022-09-13 at 2 24 09 PM" src="https://user-images.githubusercontent.com/516764/189980915-4613c91f-b872-4950-8b0e-ffc4040cb12d.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3625?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by dboyer** [comment]
I believe this is set using the dates_division_cutoff month, year, and day. That info is accurately updating on the student profile.

![Screen Shot 2022-09-14 at 1.15.48 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/84d08c54-d927-4ccc-8ccf-bec4a4d0053a)

**Comment by dboyer** [comment]
Did something change with this? I just registered again and now the dates are updating in both places.

![Screen Shot 2022-09-15 at 10.10.16 AM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/8d94f8ba-c017-46df-83b8-3594c445b460)
![Screen Shot 2022-09-15 at 10.09.50 AM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/e2f9ab77-9adc-4aad-bdd1-b7b9eed09cd1)

**Comment by viviancan** [comment]
Not that I know of! Weird!! 👀 👻

**Comment by shaunxp20** [comment]
> Looks like the info about ages and dates at the bottom of the registration page is hardcoded. It didn't update when I changed the season dates. This should read:
> 
> As of August 1, 2023. For example, if you turn 13 on July 28, 2023, you will need to select "I am registering myself and am 13-18 years old."

> Did something change with this? I just registered again and now the dates are updating in both places.

I'm not sure what changed, maybe there is some kind of caching going on. Anywho, I did confirm in the code that the dates are dynamic based on the `DATES_DIVISION_CUTOFF_X` settings in Heroku.

**Comment by shaunxp20** [comment]
Just noting that we decided to just keep an eye on this issue and explore it further if we run into it again. 👍

**Comment by dboyer** [comment]
No one has seen any issues with this during QA so moving to done.
