### ISSUE TITLE
Mentor dashboard "profile" section personal summary is blank, but the personal summary on the "profile" tab contains the correct mentor summary

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3627]

**Comment by viviancan** [comment]
![Screen Shot 2022-09-14 at 11.23.54 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/c6befe32-54e0-4a39-8824-9fa79f0f20f9)

![Screen Shot 2022-09-14 at 11.24.07 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/11be2d94-9a43-4382-9e3b-51306fbfa0e1)

**Comment by dboyer** [comment]
Tasks:

- [ ] Review profile and dashboard to ensure mentor info is same in both places

- [ ] If info is the same, remove profile section from dashboard

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3627?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by dboyer** [comment]
I'm fine with removing the "how did you hear about Technovation" field since it isn't editable on other profile types and is mostly useful to us in terms of how people came to the registration page. I've added #3641 to address how/if we include it somewhere else for all profiles.

**Comment by dboyer** [comment]
Confirmed that the summary I added during registration is appearing correctly at both /mentor/profile#!basic and /mentor/dashboard#/bio and when I update it in one place, it updates in the other.
