### ISSUE TITLE
Update welcome email to judges

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3642]
Text [available here](https://docs.google.com/document/d/1fB4XXgQ_oc14sdwg-sgqnoxQJM3Nm8Sf1XY_YpYMo7A/edit#heading=h.1x90dinr14il) although waiting on a few dates. We will not need to update this until spring 2023.

**Comment by dboyer** [comment]
Determine if judges actually need two welcome emails - one for new registrants and one for returners who log in for the new season.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3642?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
These changes are on QA now.

**Comment by dboyer** [comment]
Confirming the updated text is now on QA

**Comment by viviancan** [comment]
Logged in as a judge from last season and received the new email (on production!)

**Comment by viviancan** [comment]
Confirmed new judge gets a different email on production
