### ISSUE TITLE
Integrate filestack with team photo upload  

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3658]

**Comment by viviancan** [comment]
We have decided to temporarily update the text for the "change image" button while filestack is integrated for team photo upload. [PR 3667](https://github.com/Iridescent-CM/technovation-app/pull/3667) changes the text.

**Comment by viviancan** [comment]
@dboyer confirming updated button text is on QA

**Comment by dboyer** [comment]
Confirming I also see the coming soon button text on QA

**Comment by viviancan** [comment]
With this change:
1. Students can upload a team photo using filestack
2. Admin can also now update team photos from the admin portal! This is a new feature. Admin can only update team photos for current season teams in order to preserve historical data for future seasonality updates.

**Student Team Photo Upload**
https://images.zenhubusercontent.com/29868115/30c2f862-a5ce-4a82-9d2e-8eb68e0392d9/team_photo_upload.mp4

**Admin Team Photo Upload for current season teams**
![CleanShot 2022-10-13 at 16.11.51@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/fc1712e9-b247-4521-ba65-91832e82e027)



**Admin Team Photo Upload for previous season teams**
![CleanShot 2022-10-13 at 16.28.19@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/4f7c5a99-2a65-429f-9480-492e351d13e7)

**Comment by viviancan** [comment]
Confirming that this is on QA and working as expected for students and admin.

@dboyer Should ChA have the ability to update team photos? If so, that will need to be in a splitoff ticket. Right now as a ChA the change image button is visible to a ChA (from the shared partial with an admin) but it is not working. I can either add a conditional where only admin can view/use that button or investigate the issue for ChA

**Comment by dboyer** [comment]
Texted on QA and was able to upload a team image which then appeared on the team page and in the team search process. Could also edit the photo as an admin.

Will ask about ChAs editing photos at dev-priorities meeting.

**Comment by viviancan** [comment]
Verifying team photo is on production

**Comment by dboyer** [comment]
Also confirmed team photo upload is working on production
