### ISSUE TITLE
Potential unwanted behavior -  When logging into you old judge account you receive the welcome/start judging email. See attached screenshot

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3659]

**Comment by viviancan** [comment]
![IMG_1315.jpg](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/a7d9962d-0afc-4b2b-ac1b-be798fe278ad)

**Comment by viviancan** [comment]
@dboyer tagging you since it may want to be tackled in the next iteration before the season opens!

**Comment by dboyer** [comment]
The welcome judge email was added for the first time in the 2022 season. Need to add conditional to not send welcome email if judge registration is off AND judging is set to finished or off.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3659?planning-poker) with Zenhub @shaunxp20 @viviancan
