### ISSUE TITLE
Season launch support

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3664]

**Comment by viviancan** [comment]
9/29/22 - Potential bug with registering new admin to the TG platform. When an admin is invited, they click the invite link and are given an error message. See engineering email for original correspondence.

**Comment by dboyer** [comment]
The new platform walk-through video is ready and needs to be updated - https://www.youtube.com/watch?v=sXZjUdTMVOU

This is the video that is available by clicking the "using your dashboard" link in the menu drop-down. The requested edit is visible in this heading - https://docs.google.com/document/d/1OlgjIFRwak6RefJ4L-xQDRvvMK8kRCqDmcTIfwTTqho/edit#heading=h.5hnkzxbwz8fk

**Comment by shaunxp20** [comment]
> The new platform walk-through video is ready and needs to be updated - https://www.youtube.com/watch?v=sXZjUdTMVOU
> 
> This is the video that is available by clicking the "using your dashboard" link in the menu drop-down. The requested edit is visible in this heading - https://docs.google.com/document/d/1OlgjIFRwak6RefJ4L-xQDRvvMK8kRCqDmcTIfwTTqho/edit#heading=h.5hnkzxbwz8fk

This video update is now on QA. 😄

**Comment by dboyer** [comment]
Confirmed this is updated on QA
