### ISSUE TITLE
Only show link to judge training on judge dashboard if judge registration or judging are toggled on

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3670]
If judges from a previous season login, they are directed to their judge dashboard where they see a link to complete judge training. The training materials are not yet updated for the 2023 season.

Ideally, we should have the training link appear as an option in the left sidebar only if judge registration is turned on or if judging is available. If judge registration are off and judging is off, no one needs to be completing training.

If that is not an option, for now we should just comment out that link in the sidebar so judges can't complete registration early.

DECISION: will use conditional logic to add a tooltip to judge training saying training is not available (if judge registration is not on)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3670?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by dboyer** [comment]
Confirmed on QA that if logged in as a judge (not a mentor and judge) I go to my judge dashboard where I can sign the consent waiver but cannot complete training.

If I log in as a mentor (who is also a judge), I go to my mentor dashboard where I can complete mentor training.

**Comment by viviancan** [comment]
Verifying this is on Production

**Comment by dboyer** [comment]
Confirmed the training link is not accessible on production
