### ISSUE TITLE
Submission process text and word count updates

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3671]
Changes to the submission text for the 2023 season:

- [x] On the Description step under Ideation, remove the text "Get some help writing your product description in the [ideation curriculum unit.](https://technovationchallenge.org/curriculum/ideation-6/)" at the bottom.

<img width="751" alt="Screen Shot 2022-10-12 at 9 37 04 AM" src="https://user-images.githubusercontent.com/516764/195357386-a1b93651-df1b-45c1-95a1-a93b40fba3b5.png">

- [x] On the Learning Journey step, change the word count from 100 words or less to 200 words or less

- [x] After you've selected a submission type, the "Technical Additions" step includes a help text sentence. We should remove the part about debugging curriculum so that the phrase just reads "For help submitting your technical work, check [here](https://iridescentsupport.zendesk.com/hc/en-us/articles/360019590314-How-do-I-submit-my-source-code-).

**Comment by shaunxp20** [comment]
These changes are on QA. 👍 😃

**Comment by dboyer** [comment]
Confirmed these changes look good on QA!
