### ISSUE TITLE
Groundwork/research for integrating Filestack for adding photos to team submissions

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3672]
Replace the current photo option in the submission process with Filestack. @viviancan Adding this as a placeholder that can be broken into multiple issues as needed.

- Check path for screenshots in S3 bucket
- Look for Vue integration for Filestack
- Determine how to get filepicker into Vue

<img width="776" alt="Screen Shot 2022-10-12 at 10 15 29 AM" src="https://user-images.githubusercontent.com/516764/195367114-d56aadbb-2077-4798-b82c-469716fe5ea7.png">

**Comment by viviancan** [comment]
Other known follow-up tasks
- Viewing Screenshots in view layer
- Getting screenshots  
- Deleting screenshots

**Comment by viviancan** [comment]
This is blocked until #3682 is solved 😢
