### ISSUE TITLE
Allow Chapter Ambassadors to upload team photos

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3680]
Chapter Ambassadors should have permission to upload team photos for the teams in their chapter in the same way admins can. Admin implementation was part of #3658

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3680?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Confirming this is on QA and working as expected

**Comment by dboyer** [comment]
I am also seeing this working as expected on QA.

**Comment by dboyer** [comment]
No major issues found by PT when testing. Moving this to ready to deploy.
