### ISSUE TITLE
Change the word product to project throughout the submission process

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3681]
The list of previous changes is available at https://github.com/Iridescent-CM/technovation-app/pull/3278 and may be a useful starting point.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3681?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Confirming this is on QA! Would be great for a fresh set of eyes 👀

**Comment by dboyer** [comment]
I see project now in these areas for both mentors and students:

- In the left sidebar menu on submissions
- In the text for naming and describing your project
- In the overview page for the ideation section
