### ISSUE TITLE
Add age validation check when returning students log in and offer option to convert to mentor if over participation age

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3683]
On production, there are some some students (26403 and 4510) who were participants several years ago and logged back in for the new season. Their current age would place them in the mentor category but the platform kept them as students who were able to match with teams.

Perhaps when students log in for the new season, we run a date check and if they are over 18, they receive a message indicating their account will be converted to a mentor account.

**Comment by shaun-technovation** [comment]
> ... they receive a message indicating their account will be converted to a mentor account.

Does this mean we will still manually convert them (via the admin) to be a mentor? Just clarifying, this issue is only to display a flash/notification message?

**Comment by dboyer** [comment]
Good question - I think this issue could cover just running the check and displaying a notification to the user that their age no longer allows them to compete. Perhaps we would want a text box that would ask if they want to have their account converted to a mentor account? Although if they say no, it's not like there is really another option.

**Comment by dboyer** [comment]
Decision after discussion with PT/VET:

1. Implement age validation check when returning student logs into new season
2. If student will be over 18 on Aug 1, show an interrupt screen with two options - go to alumnae resources or convert account to a mentor account
3. Student cannot access their current student account and must choose an option. Or if they just close the screen, they return to the same screen if they log in again.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3683?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Language update to the interrupt screen:

Thank you for participating in Technovation Girls. Since you will be older than 18 on August 1, you are no longer eligible to participate as a student. Choose from the options below to access our alumnae resources or learn more about being a mentor for a team of students.

Button: View Alumnae Resources (link to https://www.technovation.org/alumnae-community-resources/)
Button: Become a Mentor (transition student account to a mentor account)

**Comment by shaun-technovation** [comment]
This one is on QA ready for a looksie. 👍 

And randomly, the verbiage:

> Click the button below to learn more about being a mentor.

The button will convert the student to a mentor, maybe that text needs to be changed? Anywho, just a minor thing. 😄

**Comment by shaun-technovation** [comment]
For QA'ing, I found that if I updated an existing student's birthday in the admin to make them older and then impersonated them, I could test the student -> mentor conversion page.

**Comment by dboyer** [comment]
Confirmed on QA that when I logged in as a student now over 18, I was giving a choice to view alumnae resources or convert to being a mentor. Both options worked. I then logged in as an admin and saw that former student now on the list of mentors.

**Comment by dboyer** [comment]
Worked as expected when tested by PT.
