### ISSUE TITLE
Restrict file types that can be selected for image uploads

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3685]
On both profile and team photos, users can select file types (zip, pdf, heic, etc) that cannot be displayed on the platform.

We should restrict file type uploads to png, jpg, and other image files.

**Comment by viviancan** [comment]
This issue has been solved. The `accept` option was added to the `picker options`. See details from [documentation here](https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#accept)

**Comment by dboyer** [comment]
Confirmed on QA that I can only upload image files. The window greyed out any files in my downloads folder that weren't images so selecting them wasn't an option.

**Comment by dboyer** [comment]
Confirmed on production that only certain image types can be selected for upload
