### ISSUE TITLE
Add beginner division to RPEs

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3689]
When creating an RPE, the ChA needs to select a division and only teams in that division may attend that event. Currently, there is no beginner division in RPEs so we need to add it. The same functionality for events in the jr/sr divisions can apply to the beginner division as well.

- This includes updating the functionality to only show beginner teams for a beginner division event.

- Need to confirm that the division filter on the admin page to look at events includes beginners. Beginner is listed in the drop-down now but we don't know if it is wired up to search correctly.

<img width="1143" alt="Screen Shot 2022-10-27 at 3 31 19 PM" src="https://user-images.githubusercontent.com/516764/198381577-1c4e7913-076f-41d3-a6ca-796d12ba0fec.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3689?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
This one is on QA. There might be some more kinks to iron out, but the basics (adding/finding beginner RPEs) are there. 👍

**Comment by dboyer** [comment]
I was able to create a beginner event and when I went to add teams, only the beginner division teams were available to add. I received an email invite to the event.
