### ISSUE TITLE
Update email and dashboard text for student and judge RPE experience

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3693]
Running list of text needs [in this doc](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit). This issue is blocked until we identify all text requiring changes.

**Comment by dboyer** [comment]
Here are the specific needed text changes. I'm outlining the needed change and then linking to the specific text in the Google Doc.

- [ ] On /student/dashboard#/events, it currently says "Due to Covid, there are no official pitch events this season." That should be changed to say "Events will be held between April 27 and May 23." [Details here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.dkan2uyx32rz).

- [ ] In the email that students receive when they are invited to an event, add the text "Note that if your event ends up being a Celebration event, it will not show on the platform, only Regional Pitch Event will. Please check with your local chapter for the latest information on the event you signed up for." Placement of text [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.brofc2ad5d0m).

- [ ] On /student/dashboard#/events if the team is attending an event, add this text: "Note that if your event ends up being a Celebration event, it will not show on the platform, only a Regional Pitch Event will. Please check with your local chapter for the latest information on the event you signed up for." Exact placement of text [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.dn9yk12ef5z9).

- [ ] On /student/dashboard#/events if the student is not signed up for an event, add this text: "Note that if your event ends up being a Celebration event, it will not show on the platform, only a Regional Pitch Event will. Please check with your local chapter for the latest information on the event you signed up for." Exact placement of text [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.hu5nmc81v8iu).

- [ ] In the email to the team confirming they signed up for an event, change the greeting from "Hey" to "Hi." And add this text: "Note that if your event ends up being a Celebration event, it will not show on the platform, only Regional Pitch Event will. Please check with your local chapter for the latest information on the event you signed up for." Exact placement of text [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.xr0c6t7bicqn).

- [ ] In the email sent to a team if a ChA removes the team from an event, change the text of the email to say: "A Chapter Ambassador has just removed TEAM NAME from the event: EVENT NAME. If you have questions, you can send an email to the ambassador who removed you, CHA NAME at CHA EMAIL." Exact placement of text [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.5n09j2mhxmui).

- [ ] In the email sent to a ChA when a student joins an event, change the greeting from Hey to Hi. Details [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.xq1fiw11t41).

- [ ] In the text on /chapter_ambassador/events#/ when a ChA tries to add a team, the text should read: "There are no more teams available to add to your event. To be eligible, teams must have started their submission and not be attending other events. You can try searching for teams that are not in your region, but are close enough to travel to your event." Details [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.e2te1xj4skry).

- [ ] In the email invite to judges who are not already on the platform, add the text: "Note that if your event ends up being a Celebration event, it will not show on the platform, only Regional Pitch Event will. Please check with your local chapter for the latest information on the event you signed up for." Exact placement [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.89kqsmis7uwt). 

- [ ] In the email invite to judges, add the text: "Note that if your event ends up being a Celebration event, it will not show on the platform, only Regional Pitch Event will. Please check with your local chapter for the latest information on the event you signed up for." Exact placement [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.sx9wot3s7ety).

- [ ] At /judge/dashboard for RPE judges, text should read: "You will be judging teams at the following event(s). You can preview your event’s submissions beginning on DATE. If you want to leave an event, please contact your Chapter Ambassador." Exact placement of text [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.xkmi0scvijyj).

- [ ] At judge/dashboard#judge-submissions-tab-content, text should read: "Begin scoring your assigned submissions. You will be able to edit your scores until round one of judging closes. For more information about your events, please view your dashboard." Exact text placement [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.kshbejxg5q0o).

- [ ] At /judge/dashboard for judges not fully onboarded, text should read: "To be able to judge submissions online this season, make sure to complete the items on the left: Consent Waiver and Judge Training.
Regional Pitch Events
You will be judging teams at the following events. You can preview your event’s submissions beginning on DATE.
If you want to leave an event, please contact your Chapter Ambassador." Exact text placement [shown here](https://docs.google.com/document/d/1MoLW-oobz3gFEE5j2G4wFK1SMRzE5QrwYqz0oA05oME/edit#heading=h.f3waodqsuvn2).

**Comment by shaunxp20** [comment]
This one finally made it to QA (icongr.am went down and blocked the deploy, I created #3866 to look into replacing it). And just a note for QA'ing, I only loosely QA'ed it locally, I didn't manually verify each one, just a handful of them. 😅

**Comment by dboyer** [comment]
Confirming the text changes look correct on QA.
