### ISSUE TITLE
Remove judge invite system from RPE creation page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3694]
The RPE creation page for ChAs includes a link to the judge invite system. The invite redirects to the judge registration page but needs to be replaced with a link to the new signup page. I'm not sure if we need to have any type of cookie/token that would then redirect the newly registered judge to see this invite or not.

<img width="834" alt="Screen Shot 2022-10-28 at 10 23 23 AM" src="https://user-images.githubusercontent.com/516764/198642691-550c282a-2e0d-4fe8-824f-187e7b7f45cf.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3694?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
We have a redirect in place for the judge url that already readirects to the signup page for the new flow. This was added in March 2022.

[ChA Judge Signup Link](https://technovation-qa.herokuapp.com/judge/signup?invitation=c1QWRNrKSc4gFzZtn5hp8zeE). For ex this link from ChA page will redirect to new registration flow. 

@dboyer Do we still want to remove this section?

**Comment by dboyer** [comment]
Maybe we just change the text then to be more helpful. How about:

You can only add currently registered judges to an event. If you would like to invite someone to register as a judge, please have them sign up at https://my.technovationchallenge.org/signup#/. Once they are registered, judges who select a location within your chapter's region will automatically appear in the list of judges you can assign to an event.

**Comment by viviancan** [comment]
Confirming the new text is on QA

**Comment by dboyer** [comment]
Confirming I see the updated text on the ChA event creation page.
