### ISSUE TITLE
Update image or container size in judging portal for screenshots so images will be the same size

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3699]

**Comment by viviancan** [comment]
Images are different sizes on the judge portal in the judging flow. This is due to the updated filestack integration. 

![Screen Shot 2022-11-02 at 12.32.43 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/c9958dca-706d-4484-b52c-dfcacb8ed9d5)

**Comment by dboyer** [comment]
Confirming that images are all sized similarly on QA and I could click a thumbnail to open the full size image. No issues reported with this after testing by PT either.
