### ISSUE TITLE
Rebrand honor code page that students agree to after submission

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3712]
After students review their submission and click the final "Submit" button, they go to this page to review the honor code. The alignment is off and needs to be adjusted.

<img width="1037" alt="Screen Shot 2022-11-09 at 11 27 54 AM" src="https://user-images.githubusercontent.com/516764/200885729-23c2fa73-25a8-40c4-afb0-c7be58312023.png">

**Comment by viviancan** [comment]
Previous Discussion points:
https://github.com/Iridescent-CM/technovation-app/issues/771
https://github.com/Iridescent-CM/technovation-app/issues/1164

**Comment by dboyer** [comment]
I see the revised honor code on QA. Was it intentional to not have it stretch all the way across the container @shaunxp20 ? 

<img width="868" alt="Screen Shot 2022-11-22 at 10 11 15 AM" src="https://user-images.githubusercontent.com/516764/203349900-06a13ba2-1d08-4717-8704-093cc1df0193.png">

**Comment by shaunxp20** [comment]
> I see the revised honor code on QA. Was it intentional to not have it stretch all the way across the container @shaunxp20 ?

The text/line length is determined by Tailwind, it keeps the lines shorter to keep it more readable.

I just pushed up a change so that the text will be centered within the container, so the space is distributed better, hopefully that works better. it's on QA now.

**Comment by shaunxp20** [comment]
> Something is up with the header now though. It's a really pale color not visible on the white background.

Okay, this should be fixed on QA now! 🤞😅

**Comment by dboyer** [comment]
Looks correct on QA!
