### ISSUE TITLE
Support for opening submission

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3713]
This will be a catch all for issues that arise from getting ready to open submissions.

**Comment by dboyer** [comment]
There are three questions in the additional information section of submissions. This year, they should be:

- Does your submission use artificial intelligence? (unchanged from last year)
- Does your submission help solve climate change? (unchanged from last year)
- Does your submission help solve hunger or food waste in some way? (can replace the current question about health)

**Comment by shaunxp20** [comment]
>     * Does your submission help solve hunger or food waste in some way? (can replace the current question about health)

This is on QA now, there were six places that had to be updated. I just did the bare minimum changes to get the question updated. 

Just a random side note that it's rather confusing on the back-end b/c this question started as a "game" question then a "health" question and now it's a "hunger" question; there are remnants of these older versions still lingering around. At some point we might want to look at cleaning this up! 😅 😃

**Comment by dboyer** [comment]
I see the new question at:

- In the submission process (for both mentors and students)
- In the app review page mentors see before submitting
- In the app review page students see before submitting 
- On the admin page for a submission
- On the team's submission page at /student/dashboard#/submission
- On the published submission page at /student/published_team_submissions/no-name-yet-flower-power#/


NOTE: The additional columns that can be added to the submissions page at /admin/team_submissions#/ still list "game question" and not health or food. I'm assuming that's part of the confusing back-end and doesn't need to be changed right this minute. Especially since it still says game and not health so it was already outdated last year. Is that correct @shaunxp20 ?

**Comment by shaunxp20** [comment]
> NOTE: The additional columns that can be added to the submissions page at /admin/team_submissions#/ still list "game question" and not health or food. I'm assuming that's part of the confusing back-end and doesn't need to be changed right this minute. Especially since it still says game and not health so it was already outdated last year. Is that correct @shaunxp20 ?

Yup, I just looked and that's correct - it was never updated last year. Good catch on this! I updated it to "Hunger question", let me know if that needs to change (it could also be "Food waste question" or Hunger/food waste question" or something else) - the other questions don't display the full question, they display "AI question" and "Climate change question". 😃

**Comment by dboyer** [comment]
One additional small text update related to submissions. In the text in the right sidebar by the honor code, please add the time listing after April 18. The final text should read:

You can make changes until April 18, 5pm PDT / April 19 at 1am WAT / 2am CEST / 5am IST.

<img width="569" alt="Screen Shot 2022-11-29 at 4 31 12 PM" src="https://user-images.githubusercontent.com/516764/204652168-861ea4e2-b180-43a0-9432-1e835f6a5d45.png">

**Comment by shaunxp20** [comment]
> > NOTE: The additional columns that can be added to the submissions page at /admin/team_submissions#/ still list "game question" and not health or food. I'm assuming that's part of the confusing back-end and doesn't need to be changed right this minute. Especially since it still says game and not health so it was already outdated last year. Is that correct @shaunxp20 ?
> 
> I updated it to "Hunger question"

This change is on QA now.

**Comment by dboyer** [comment]
Confirming I see the hunger question in the admin tools now and no mention of the game question on QA

**Comment by shaunxp20** [comment]
> One additional small text update related to submissions. In the text in the right sidebar by the honor code, please add the time listing after April 18. The final text should read:
> 
> You can make changes until April 18, 5pm PDT / April 19 at 1am WAT / 2am CEST / 5am IST.

There potentially might be more to this one, I also see the submission deadline (in a slightly different format - April 18, 2023) that will appear in the student welcome email, and also the parent welcome email. Should those be updated too? And if so, what format? 🤔

**Comment by dboyer** [comment]
I chatted with Program Team, and they like the idea of the times appearing near the date whenever it is visible. If it's possible, the new time config variable could also be included in those emails, in the same format as it is in the text that appears on the submission page.

That said, if it is a hassle, adding the time in other places where the date appears is a nice to have. Not a need to have.

**Comment by dboyer** [comment]
Also confirmed with PT that the selected time zones are unlikely to change so we should not need to update those variables in the future.

**Comment by shaunxp20** [comment]
The submission deadline format should be updated everywhere on QA now. 🤞

**Comment by shaunxp20** [comment]
Just documenting that there is a new Heroku config var to control the hour:
```
DATES_SUBMISSION_DEADLINE_HOUR_IN_24_HOUR_FORMAT
```

I just added this to Heroku for both QA and PROD. It was working before b/c the code just defaults the hour to `17`, but now it should use the new config var (which is also set to `17`), so there shouldn't be any difference.

> @shaunxp20 Will the time also be included in the email students receive after submitting a project? It currently includes the date and I wasn't sure if this was one of the emails where the time was added too.

Yup, this should be updated too, let me know if it's not! 😄

**Comment by dboyer** [comment]
Confirming that I do see the time included in the email I received after submitting a project.

One note @shaunxp20 : IST is actually on the half hour so it would be 5:30am in this list of times, which we just caught when reviewing at a meeting.

That said, Program Team is okay with keeping it at 5am unless it is very easy to change. If it's hard to add a time zone on the half hour, we can keep it as is. If it's not hard to change, it would be nice for it to be accurate.

**Comment by shaunxp20** [comment]
> One note @shaunxp20 : IST is actually on the half hour so it would be 5:30am in this list of times, which we just caught when reviewing at a meeting.

Good catch, it should be fixed on QA now! I deployed it right to QA since it was a simple fix - just adding in the minutes (before it was just showing the hour). 🕠 👍

**Comment by shaunxp20** [comment]
> One more support thing! As of today, there is a new mentor curriculum available at https://technovationchallenge.org/mentor-curriculum/
> 
> We need to add it as a link in the drop-down menu on the mentor dashboard. It can go after Student Curriculum and say "Mentor Curriculum" with "Open the Curriculum" as the subheading if we have to have sub text.

This is on QA now (I just put it directly on QA since it was a simple change). 👍

**Comment by dboyer** [comment]
Confirming that I see the mentor curriculum linked on QA and the time now listed as 5:30AM IST. Thank you!
