### ISSUE TITLE
Upgrade Heroku QA to paid plan by Nov 28 or DB will be deleted (per heroku dashboard)

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3718]

**Comment by viviancan** [comment]
@dboyer Tagging you on this issue! I won't be at standup tomorrow, but wanted to bring this to your attention! 
![Screen Shot 2022-11-15 at 10.17.03 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/7cb24328-627c-46ee-bfeb-45fadb8d96b1)

**Comment by dboyer** [comment]
Thanks for flagging this @viviancan! We pay for dynos, redis, and postgres on prod so it looks like this primarily applies to QA.

For QA, it's recommending we upgrade to the Eco Dynos account for $5 for 1000 dyno hours per month. We've only used 237 hours so far this month so I think the 1000 hours should be fine. 

It's also indicating we have to upgrade Heroku Data for Redis. I think we can get by on their Premium 0 plan ($15 per month) which is a step below the Premium 1 plan we have on prod.

**Comment by viviancan** [comment]
Upgrade was successfully completed through heroku dashboard. This unexpectedly caused an issue with SSL cert and redis on QA.

The error we received 
`ActionView::Template::Error: SSL_connect returned=1 errno=0 peeraddr=54.204.117.135:29659 state=error: certificate verify failed (self-signed certificate in certificate chain)`

This seems to be a known issue. Here are some resources. 
- https://devcenter.heroku.com/articles/heroku-redis#connecting-in-ruby
- https://stackoverflow.com/questions/66246528/herkou-redis-certificate-verify-failed-self-signed-certificate-in-certificate
- https://www.sandipmane.dev/openssl-connection-error-with-redis6-on-heroku

[Commit](67f1225fee232250267ef1970edd509fa4826d9e) with the fix. Will report back if this fixes this issue.
