### ISSUE TITLE
Upgrade Postgres on prod

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3719]
We are currently on Postgres 11.17 on production and 13.8 on QA. Postgres 11 will be EOL on Nov 9, 2023. Heroku will force upgrade after that date.

We should upgrade to 13 to match QA if possible.

**Comment by dboyer** [comment]
Notes on the last postres upgrade are in https://github.com/Iridescent-CM/technovation-app/issues/2600

**Comment by dboyer** [comment]
This issue covers updating production to the version of 13 that matches what is on QA. A later issue will involve moving both QA and prod to Postgres 15.

**Comment by viviancan** [comment]
[Docs are here](https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrading-with-pg-upgrade)

![Screen Shot 2023-07-12 at 3.56.19 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/08da95aa-e67a-4404-94e0-9535c9c54353)

According to docs the `pg:upgrade` method is recommended. I checked our plan and we have a `standard-0` plan. I also checked `Checksums` by connecting to the prod db through the heroku CLI

```
heroku pg:psql --app technovation
SHOW data_checksums;
```

**Comment by viviancan** [comment]
They recommend to [test the upgrade](https://devcenter.heroku.com/articles/testing-postgresql-version-upgrades) before upgrading production

**Comment by shaun-technovation** [comment]
> They recommend to [test the upgrade](https://devcenter.heroku.com/articles/testing-postgresql-version-upgrades) before upgrading production, but not sure if we have to do that since the newer version is already running on qa? :🧐

I think you're right that having already done the upgrade on QA is probably good enough for testing purposes.

The documentation says:
> The most common upgrade issues are related to type incompatibilities between PostgreSQL versions, object reference or dependency errors, or general application problems when an app or its PostgreSQL driver version doesn’t support the target PostgreSQL version.

And if QA has been running smoothly w/ the upgrade, I think chances are Production will be too! 🤞 😃
