### ISSUE TITLE
Fix ChA profile image size issues on mentor dashboard

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3721]
- Profile image in viewing "MyChA" on mentor profile is very large. Needs to be resized for the dropdown
- If a ChA does has not uploaded a profile image, their account defaults to the placeholder hedgehog profile image. On the mentor dashboard this image link is broken in the "meet your chA" heading dropdown. See photo below. This image should not be broken and should display the hedgehog

**Comment by viviancan** [comment]
![CleanShot 2022-11-16 at 12.36.47@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/8a0f66cb-8923-4497-98ae-25c223ba0caf)

**Comment by dboyer** [comment]
Confirmed that this is now working on QA. I can see the hedgehog image if the ChA hasn't uploaded a profile photo and the image size is correct as a thumbnail and in the drop-down screen.
