### ISSUE TITLE
Image and icon scaling issues on page for mentor to confirm submission

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3722]
I logged in as the mentor for a team to test photo upload on submissions. I was able to complete the whole submission process. When I clicked the submit button it took me to the page to confirm the submission (/mentor/published_team_submissions/no-name-yet-sharks-are-awesome#/) and the icons and images were all gigantic. I was able to successfully submit the project.

Video at https://drive.google.com/file/d/1TUBTZ3nUbwY-dNsPO63KV0AiVZvZxhit/view?usp=drivesdk

**Comment by viviancan** [comment]
It looks like this is one of those views shared between mentor and student profiles. The styling was updated to use tailwind to match student experience, so now the mentor experience is jumbled. We can follow the previous solutions of creating a "rebrand" version of this file for the student experience and use original styling for mentor experience

**Comment by viviancan** [comment]
I pulled the old file before changes were made just to get an understanding of what this view should like for mentors. The mentor view of the completed submission page includes RPE presentation slides. Do we want to keep this? For additional context the student view does not include the presentation slides. See comparison below.
![CleanShot 2022-11-17 at 14.00.35@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/a68e2975-6b18-4423-861b-562fb6c7010b)![CleanShot 2022-11-17 at 14.01.17@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/e0329ea2-d06d-4679-9e5a-4eeee63a18a0)

**Comment by dboyer** [comment]
Hmmm.......I guess we should leave those slides since RPEs are back. This may reference a set of files students had to upload. From the 2020 RPE guide:

Attending Events

- If teams submit for an event, the team must attend the event.
- Teams who attend the RPE will need to create a short pitch presentation It can be PDF, PPT (PowerPoint), or Google Slide format. Team should upload directly to the platform. 
- It is the only submission piece not due on April 20th, 2020. 
- RA should set the deadline for when students upload these to the platform.

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by dboyer** [comment]
Confirmed that the image and icons now look correct and the mentor can more easily see how to submit the final project.
