### ISSUE TITLE
Fix spacing on Pitch Your Project page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3725]
Click on the "Pitch your Project" link in the right sidebar to access /student/dashboard#/events and see the screenshot below. Most of the new branding is in place but it looks like changes are needed to the spacing. 
<img width="1180" alt="Screen Shot 2022-11-18 at 11 46 07 AM" src="https://user-images.githubusercontent.com/516764/202757888-b1216305-2388-4935-9cf8-14fc1f33669f.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3725?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
This was taken care of (accidentally) with #3724 - PR [here](https://github.com/Iridescent-CM/technovation-app/pull/3741)

**Comment by dboyer** [comment]
Confirming this looks good now on QA.
