### ISSUE TITLE
Clicking to upload presentation slides for an RPE causes an error

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3732]
NOTE: The parameters of this issue are to investigate what is going on and fix if a small change. If it's a larger issue, add a new card to fix.

There are two ways to get to the presentation slides. In both cases, trying to upload the slides causes an error. This issue is just to cover fixing the upload error, not the UX flow issues.

1. If you are invited to an event, the user dashboard includes a link to "edit presentation slides." That takes the user into the submission process where there is a button to upload slides, but clicking that button causes an error. See screen capture below. This happened when submissions were closed so I don't know if that had an impact on the error.

https://drive.google.com/file/d/1JENt6bG0zHspajeKEkB67IGFPHQD94aI/view?usp=drivesdk

2. Same user with submissions turned on. The dashboard has no link to the presentation slides. Clicking on "my submission" goes into the submission process where the person is prompted to add presentation slides, which then gives an error.

https://drive.google.com/file/d/10FFkEUnxGBYJHgKNjni7vIBBB7R5XRDY/view?usp=drivesdk

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3732?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
This one is on QA. This should fix this issue and allow RPEs to be explored further. 🤞 I noticed some interesting/weird behavior, so I anticipate there will be some follow up work to iron out more of the kinks! 😄
