### ISSUE TITLE
Update the layout for students when selecting an RPE 

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3739]
When students view all of the available RPEs, the layout is a little strange since the "event details" partial is reused. See attached screenshot
![CleanShot 2022-12-01 at 16.05.11@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/d7170c45-1050-4916-ae0c-858bbe1107cd)t

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3739?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by dboyer** [comment]
Confirming that I see the updated layout for the events on QA
