### ISSUE TITLE
Update layout linking to upload presentation slides

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3743]
If a student is invited to an RPE, they have an option to upload their presentation slides at /student/dashboard#/submission. The layout of that page needs to be adjusted to show the upload link as well as the details for the event the team is attending.

Question: Should we show the message that submitting your project is closed? This text shows by default on the /submission page if submissions are turned off. Submissions have to be turned off though to upload presentation slides, which is confusing.

<img width="988" alt="Screen Shot 2022-12-05 at 1 11 57 PM" src="https://user-images.githubusercontent.com/516764/205710967-7c289764-31c1-468d-89ed-f7183135264c.png">

_Originally posted by @dboyer in https://github.com/Iridescent-CM/technovation-app/issues/3724#issuecomment-1337881734_

**Comment by viviancan** [comment]
Update - There will be a meeting to discuss final flow for uploading RPE presentation slides. We will point once finalized.

**Comment by dboyer** [comment]
More than half of the surveyed chapter ambassadors expressed interest in potentially using the presentation slide upload option. I spoke with PT and they felt it was worth keeping the option, but we don't need to do anything to make it more fully integrated (i.e. we don't need to include it in email prompts or as part of the details on the events page, etc).

The current prompt is on /student/dashboard#/submission and is visible if submissions are closed and whether judging is on or off.

<img width="951" alt="Screen Shot 2023-03-07 at 4 50 39 PM" src="https://user-images.githubusercontent.com/516764/223561258-0ab1fabc-69b5-4bc7-83d6-9148be4e1ec3.png">

We can keep it in the same location and adjust the layout. I drafted the layout below but feel free to adjust based on technical needs.

<img width="878" alt="Screen Shot 2023-03-07 at 5 03 08 PM" src="https://user-images.githubusercontent.com/516764/223563692-529c4e33-ba0c-48af-9660-a4f4e0911542.png">

**Comment by dboyer** [comment]
Confirming that I see the updated layout for the presentation slides on QA.
