### ISSUE TITLE
Add an additional question around ChatGPT usage

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3761]
In the additional questions section, add a fourth question:

Did you use ChatGPT at any point when working on your project?

The answers should be yes/no like with the other questions.

Note that this question is not visible in the judging process but should be visible (as are the other additional questions) on the finished project page (example: /projects/no-name-yet-stegosaurus#/) that the team sees after finishing their submission.

**Comment by shaunxp20** [comment]
> Did you use ChatGPT at any point when working on your project?

A very minor thing - should we retain the "OpenAI" part of the question? "Did you use OpenAI/ChatGPT at any point when working on your project?" It looks like OpenAI works on quite a few different AI projects besides ChaptGPT (I wasn't aware of this before): https://en.wikipedia.org/wiki/OpenAI

**Comment by dboyer** [comment]
Great idea - yes, let's phrase it as "Did you use OpenAI/ChatGPT at any point when working on your project?"

**Comment by dboyer** [comment]
Confirming that I also see this as an admin option on the submissions page
