### ISSUE TITLE
Separate "hunger/food waste" question from "game" question

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3776]
For the 2023 season, we reused the "game" question for the "hunger/food waste" question.

We want to:
- Make the "hunger/food waste" answer (and description) separate fields in the database
- Update 2023 submissions, transferring "game" values in the database to "hunger/food waste" values
- Update forms/views to reference the "hunger/food waste" database values (instead of the "game" values)

**Comment by shaunxp20** [comment]
For QA, here are all the 2023 submissions who answered the "hunger/food waste" question (which was using the "game" question under the hood):
|App|Hunger/Food Waste (Y/N)|Description
|--|--|--
Coffee Defeats Orange Juice|false|                                                                                                                                                 
Roses and Lilies|true|Flowers can be eaten. We should eat more flowers.                                                                                                            
Robots to Build|false|                                                                                                                                                             
Petunia Power|false|                                                                                                                                                               
Cactus Lovers|true|You can eat cactus                                                                                                                                              
Pile of Blankets|false|                                                                                                                                                            
Stegosaurus Stomps|true|Dinosaurs are healthy                                                                                                                                      
Shoes for Sharks|false|                                                                                                                                                            
Its corn!!!|false|                                                                                                                                                                 
A-mazing App|false|                                                                                                                                                                
Beautiful Butterflies|false|                                                                                                                                                       
Flower Finder|false|                                                                                                                                                               
Gas Price Smasher|false|                                                                                                                                                           
Sunflowers for Dayz|true|People can eat sunflower seeds                                                                                                                            
Purple Unicorns|false|                                                                                                                                                             
Pancakes are Perfect|true|People will always eat pancakes.          

After this update gets deployed to QA, these submissions ☝️ should be using a new/separate`solves_hunger_or_food_waste` (and "description") column in the database and still be answered *yes* or *no* with the appropriate *description*.

**Comment by shaunxp20** [comment]
Here is a dataclip (that can be toggled between QA and Prod) that will show the 2023 submissions that answered yes/no to the "hunger/food waste" question:
https://data.heroku.com/dataclips/wotwjrqvlxdqvedaxdlytqhzpdln

**Comment by shaunxp20** [comment]
> For QA, here are all the 2023 submissions who answered the "hunger/food waste" question (which was using the "game" question under the hood):
> App 	Hunger/Food Waste (Y/N) 	Description
> Coffee Defeats Orange Juice 	false 	
> Roses and Lilies 	true 	Flowers can be eaten. We should eat more flowers.
> Robots to Build 	false 	
> Petunia Power 	false 	
> Cactus Lovers 	true 	You can eat cactus
> Pile of Blankets 	false 	
> Stegosaurus Stomps 	true 	Dinosaurs are healthy
> Shoes for Sharks 	false 	
> Its corn!!! 	false 	
> A-mazing App 	false 	
> Beautiful Butterflies 	false 	
> Flower Finder 	false 	
> Gas Price Smasher 	false 	
> Sunflowers for Dayz 	true 	People can eat sunflower seeds
> Purple Unicorns 	false 	
> Pancakes are Perfect 	true 	People will always eat pancakes.
> 
> After this update gets deployed to QA, these submissions ☝️ should be using a new/separate`solves_hunger_or_food_waste` (and "description") column in the database and still be answered _yes_ or _no_ with the appropriate _description_.

I verified a few of these on QA that they got converted correctly. Would probably be good to get second pair of eyes on it too!

**Comment by dboyer** [comment]
I looked at several of these on QA and confirmed the values in the list above are showing under the hunger/food waste question when I look at the individual page for the submission.

@shaunxp20 However, when I add the hunger question as a new column on the admin page, the value for each project is - even when I know an entry (like Roses and Lilies) has a true value. When I exported the csv of the submissions, it also kept the value for each submission as - rather than true or false.
<img width="1114" alt="Screen Shot 2023-01-23 at 11 14 58 AM" src="https://user-images.githubusercontent.com/516764/214090817-615df25b-a87b-466f-afdb-efc02bdddb39.png">

**Comment by shaunxp20** [comment]
> @shaunxp20 However, when I add the hunger question as a new column on the admin page, the value for each project is - even when I know an entry (like Roses and Lilies) has a true value. When I exported the csv of the submissions, it also kept the value for each submission as - rather than true or false.

Good catch! I haven't updated any of the additional columns, so I think what is happening is that it's still using "game" under the hood (and those values were converted to "hunger", and "game" would be blank b/c it's not in use for this season). I'll make an update to this.

**Comment by shaunxp20** [comment]
> @shaunxp20 However, when I add the hunger question as a new column on the admin page, the value for each project is - even when I know an entry (like Roses and Lilies) has a true value. When I exported the csv of the submissions, it also kept the value for each submission as - rather than true or false.

An update has been deployed to QA, it should be displaying the correct "hunger/food waste" responses now. 😄

**Comment by dboyer** [comment]
@shaunxp20 I'm seeing the correct hunger/food waste responses now but running into an error with the exports. These were the steps:

1. Add hunger/food waste as another column on the submissions page and click "search." I can see values in this column.
2. Click "export current search results to CSV" and get the pop-up to start the download
3. I do not see the download loading bar or any other message in the lower right of the screen
4. Refresh the page. Now I have the "you have an export waiting" bar in the lower right but the export never finishes

<img width="1420" alt="Screen Shot 2023-01-25 at 12 00 12 PM" src="https://user-images.githubusercontent.com/516764/214629610-76e18d91-1d49-4533-bb94-5b523f0bef58.png">

**Comment by shaunxp20** [comment]
> @shaunxp20 I'm seeing the correct hunger/food waste responses now but running into an error with the exports. These were the steps:
> 
>     1. Add hunger/food waste as another column on the submissions page and click "search." I can see values in this column.
> 
>     2. Click "export current search results to CSV" and get the pop-up to start the download
> 
>     3. I do not see the download loading bar or any other message in the lower right of the screen
> 
>     4. Refresh the page. Now I have the "you have an export waiting" bar in the lower right but the export never finishes

Thanks for the steps! I looked at this and was able to reproduce this error, it's the same export bug we've been running into lately:

> OpenSSL::SSL::SSLError (SSL_read: unexpected eof while reading)

I didn't see an open issue for this, so I just created one #3807.
