### ISSUE TITLE
Make "Additional Questions" in admin dynamic based on season

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3783]
The "Additional Questions" displayed in the admin area should be dynamic (when viewed by both admins and ChAs).

For 2023 submissions, the "additional questions" displayed, should be:
 - ai, climate change, hunger/food waste, open ai/chat gpt

For 2022 submissions:
- ai, climate change, health

For 2021 submissions:
- ai, climate change, game

Admins can also edit "additional questions", these form fields should also be updated/dynamic. 

## QA STEPS
Here are some QA steps for a lot of the additional questions work.

As a student:
- Verify the hunger/food waste is displaying and saving correctly (this was formerly using the game question under the hood)

As a ChA and admin:
- Verify the appropriate additional questions are being displayed for 2021, 2022 and 2033 submissions

As an admin:
- Verify the appropriate additional questions are being edited/saved correctly for 2021, 2022 and 2033 submissions

**Comment by shaunxp20** [comment]
This one is on QA which means verything related to additional questions is ready to be QA'ed now. I added a few basic QA steps too.

**Comment by shaunxp20** [comment]
> @shaunxp20 Looking on QA, I do not see "game" as an additional column that I can add when viewing 2021 submissions or "health" when viewing 2022 submissions. I do see "hunger" as an additional column I can add. Is that correct behavior? I'm fine if we can't display columns for additional questions in previous years, even if we've selected that year as a filter, but just want to make sure it isn't a bug and they should be displaying.

Ah, good catch! I didn't update any of the admin additional columns! I'll add the missing ones! 👍

**Comment by shaunxp20** [comment]
> @shaunxp20 Looking on QA, I do not see "game" as an additional column that I can add when viewing 2021 submissions or "health" when viewing 2022 submissions. I do see "hunger" as an additional column I can add. Is that correct behavior? I'm fine if we can't display columns for additional questions in previous years, even if we've selected that year as a filter, but just want to make sure it isn't a bug and they should be displaying.

QA has been updated with new functionality, so all of the "additional columns" (for the additional questions) should be working as expected now. 🤞

**Comment by dboyer** [comment]
Confirming that I can now see the additional columns on QA and the contents appear in the exported CSV as expected
