### ISSUE TITLE
Integrate submissions assigned via RPE to a grid

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3788]
Currently, a judge sees the submissions they should judge as part of an RPE in a list:
<img width="816" alt="Screen Shot 2023-01-17 at 2 02 04 PM" src="https://user-images.githubusercontent.com/516764/212988180-9c0c5ed9-e7a6-404b-911a-f4fe94b8ce73.png">

Those submissions should instead be part of a new judge grid called Submissions to Score. This issue covers 

- [ ] Creating the grid (can match the grids currently used in the online judging process) 
- [ ] Integrating the submissions list for an RPE
- [ ] Adding the submissions to in progress and finished grids as necessary
- [ ] Removing the submissions list from where it currently appears (the first screenshot above)

<img width="964" alt="Screen Shot 2023-01-17 at 4 31 04 PM" src="https://user-images.githubusercontent.com/516764/213016498-bdc80fdc-cab2-443c-b463-99d16cf5692b.png">

**Comment by dboyer** [comment]
Split off of #3764

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3788?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
verifying this is on qa

**Comment by dboyer** [comment]
Confirming that I now see the submissions to score section on QA and not the submissions in a long list!
