### ISSUE TITLE
Add judging format column to judge grid

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3789]
With the return of RPEs, we would like to note if a submission is judged as part of an RPE or online only. We should add a judging format column to any of the grids that lists submissions for a judge (i.e. submissions to score, in progress, finished scores). The column is visible in this mock-up. 

Let's use the phrases "Pitch Event" and "Online" for the judging format.

![Screen Shot 2023-01-30 at 7.53.11 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/28f13b27-7ee8-4c66-8a68-c9f1dbf9f951)

**Comment by dboyer** [comment]
Connected to issues outlined in #3764

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3789?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Verifying this is on QA

**Comment by dboyer** [comment]
Confirming I see this column on QA. Super exciting!!!!

We may want "pitch event" and "online" rather than live and virtual for the event names. I'll confirm with PT and enter that as a separate text issue along with other text changes.

**Comment by dboyer** [comment]
Let's change the wording to Pitch Event and Online

**Comment by dboyer** [comment]
Confirming I see the words Pitch Event and Online now on QA
