### ISSUE TITLE
Fix printable list button for an RPE

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3792]
The ChA admin page to review events includes a button to print information for live events. Clicking that button loads the error page. 

<img width="1175" alt="Screen Shot 2023-01-18 at 12 24 21 PM" src="https://user-images.githubusercontent.com/516764/213251446-db69b407-a64f-4e4c-aafa-4306848da28d.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3792?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by dboyer** [comment]
Note that printing events is working for the Beginner Paris Event but not for the Paris Power Pitching and May Pitch Event. The beginner event does not have any teams associated with it and the other two events do.

**Comment by shaunxp20** [comment]
This issue should be fixed on QA now. Also note that there is followup work being done in #3804 (to address the incorrect judging sections/questions on the printed list).

**Comment by dboyer** [comment]
Confirming that the "print for live event" button now works for me on all RPEs.
