### ISSUE TITLE
Update RPE judge questions

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3804]
The judge questions displayed on the "print" version for an RPE are incorrect and need to be updated to reflect the current season's judge questions.

**Comment by dboyer** [comment]
@shaunxp20 Is this blocked behind #3765? If so, I can prioritize getting that text finalized.

**Comment by shaunxp20** [comment]
> @shaunxp20 Is this blocked behind #3765? If so, I can prioritize getting that text finalized.

Definitely not blocked at this point, the work for this issue will be just to get the judging sections and questions modernized (on the printable page) for what we're currently using for the 2023 season. The updates in #3765 will be on top of/in addition to the changes in the issue. 👍

**Comment by shaunxp20** [comment]
This is now QA, which means that the sections and questions should be up-to-date on the RPE printable page now. There's definitely some room for followup work for a redesign/restructuring of this page too.

**Comment by dboyer** [comment]
Confirming that I see the correct section headers and questions for each division in the printable RPE page and I am able to successfully export the page.
