### ISSUE TITLE
Add error message about parent email duplicating account email when validation check is looking for division based on age on August 1

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3809]
> @shaunxp20 I logged into the [deb+beginner0425@technovation.org](mailto:deb+beginner0425@technovation.org) account and was able to get past the data terms. My dashboard prompted me to check the status of my parental consent. I went to that page and attempted to enter [deb+beginner0425@technovation.org](mailto:deb+beginner0425@technovation.org) as the parent email. It wouldn't let me as the screen just reloads, but there is no information about why I can't add that email address because it matches the current address.
>
> I tried the same set of steps on the deb+parent1130 account and did get a warning message. I then went back and tried the deb+beginner0425 account again and still don't see an error message.

I think I'm finally getting to the bottom of this! From what I'm seeing this is existing functionality, as to why the error messages are showing for some accounts but not others.

We have two separate "parent/guardian email address can't be the same as the  account email address" validations, both of which don't get applied if someone is in the beginner division.

1. One validation checks what division is currently assigned to the student
2. One validation checks what division they _would be_ in based on their age by the division cutoff date

From what I'm seeing, only the first one will show the validation error. If there is a validation error in the second one, these errors won't be displayed.

For `deb+parent1130` they are currently in the junior division and fail the first validation and get the error message.

For `deb+beginner0425` they are currently in the beginner division (which means they pass/bypass the first validation), but fail the second one (because they will be in the junior division based on their DOB by the division cutoff date), and errors from the second one aren't being displayed. There seems to be an issue w/ the second one surfacing/bubbling up the errors.

_Originally posted by @shaunxp20 in https://github.com/Iridescent-CM/technovation-girls-docs/issues/9#issuecomment-1405369161_

**Comment by shaunxp20** [comment]
> We have two separate "parent/guardian email address can't be the same as the account email address" validations, both of which don't get applied if someone is in the beginner division.
> 
>     1. One validation checks what division is currently assigned to the student
> 
>     2. One validation checks what division they _would be_ in based on their age by the division cutoff date
>
> From what I'm seeing, only the first one will show the validation error. If there is a validation error in the second one, these errors won't be displayed.

I made two fixes to address these issues:
1. Both validations should fire consistently now (both doing a division check based on age by division cutoff date)
2. Error messages from the second validation should get surfaced/displayed on the parental consent form now

**Comment by dboyer** [comment]
Confirming that I now see validation errors for both test accounts. I was also able to successfully change the email address associated with both accounts.
