### ISSUE TITLE
Add location column to Chapter Ambassador activity page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3812]
Chapter Ambassadors can see a list of the activities of people in their chapter at /chapter_ambassador/dashboard#!recent-activity. and /chapter_ambassador/activities

It would help if they could have a location column visible on these pages since some chapters cover a large region. Let's add city and state as optional additional columns on the activities page. This info will not be available on the recent activity page due to space concerns. If it's a student level activity, the location will be the student's associated location. If it's a team level activity, the location will be the team's associated location. 

![Screen Shot 2023-02-01 at 2.02.07 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/bb55a2dc-4a31-411e-9764-e2649528f4ff)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3812?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by dboyer** [comment]
Program team confirmed that the location should be that of the student if it's a student specific activity and the location of the team if it's a team specific activity.

**Comment by shaunxp20** [comment]
> Let's add city and state as optional additional columns on the activities page.

Additional columns for city and state is now on QA. 😄

**Comment by dboyer** [comment]
Confirming that I can add the city and state columns on QA and that the location correctly reflects either the team or student location depending on the type of activity.
