### ISSUE TITLE
Comment box for hunger/food waste question open by default

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3814]
When starting the additional questions for a new submission, all of the questions default to showing just the question except for hunger/food waste. The comment box for hunger/food waste is always visible. For the other questions, it only appears if the user selects "yes." 

<img width="721" alt="Screen Shot 2023-01-30 at 8 02 02 PM" src="https://user-images.githubusercontent.com/516764/215632124-d7d3df8d-6f77-465b-a797-c770feb0c44d.png">

**Comment by shaunxp20** [comment]
This one is on QA, good catch on this one!

**Comment by dboyer** [comment]
Confirming the comment box is no longer open by default.
