### ISSUE TITLE
Add list of teams and judges to admin page showing RPE info

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3818]
Admins can view basic info about an RPE at /admin/events#/ by clicking the "View" button next to an event. The page for an event lists the number of teams and judges but not specific names of teams and judges. Program Team requested that we add the following info:

- Under the number of teams, list the team name (i.e. Prickly Petunias) and link to the submission page for that team (i.e. /admin/team_submissions/no-name-yet-prickly-petunias)
- Under the number of judges, list the judge name (i.e. Judgey McGee) and link to the judge's participant page (i.e. /admin/participants/7#/)

<img width="713" alt="Screen Shot 2023-02-01 at 10 12 52 AM" src="https://user-images.githubusercontent.com/516764/216082047-7fc17416-4221-437c-b809-8c28494a2f2f.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3818?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by shaunxp20** [comment]
These changes should be on QA now! 😄

**Comment by shaunxp20** [comment]
> I see the lists on QA! Program team had requested that the team link go to the team's submission rather than the team page so let's make that change.

This should be updated on QA now (I just pushed it right to QA w/o a code review since it was a simple change).

**Comment by dboyer** [comment]
Confirming I see the team link going to the submissions page now.
