### ISSUE TITLE
Update judge dashboard/different "states" text 

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3824]

**Comment by viviancan** [comment]
Refer to the [mural board ](https://app.mural.co/t/technovationgirls4378/m/technovationgirls4378/1674590684432/0f93038bbd4755c67632062ee6ab16cf1a1c6c90?sender=u9adab98cc36af2c4665e9477)

We need to update the text for the judge dashboard depending on the state of season

**Comment by dboyer** [comment]
Add the following text:

- [ ] On the judge dashboard (/judge/dashboard#/) when judging is off and the judge is fully onboarded, the [text should read](https://docs.google.com/document/d/1-EpzEqGvSrYwXKbDw5vFvLn_E6svPlft5oT6CKXCK0w/edit#heading=h.rib14y9twmtd):

Welcome to the online judging portal! Judging is currently closed but will open soon. You will receive an email when judging opens. Please check back on the dates listed below!  DATE CHART

- [ ] On the judge dashboard when judging is on for quarterfinals. [Text shown here](https://docs.google.com/document/d/1-EpzEqGvSrYwXKbDw5vFvLn_E6svPlft5oT6CKXCK0w/edit#heading=h.ivur99ueghfl).

Welcome to the online judging portal for the first round of Technovation Judging! Click on the button below to open a submission and start scoring. 
Button: Start a new score (this can be the same button on the judge submissions tab)
<img width="118" alt="Screen Shot 2023-03-07 at 10 07 39 AM" src="https://user-images.githubusercontent.com/516764/223462497-912fbde2-06d0-4ad0-a0c9-f3ac75c44f01.png">

DATE CHART

- [ ] On the judge dashboard [in-between rounds](https://docs.google.com/document/d/1-EpzEqGvSrYwXKbDw5vFvLn_E6svPlft5oT6CKXCK0w/edit#heading=h.y3cialsnj520) the only changed text is after "What happens next?" That should read:

If you finished scoring 5 submissions or more, you will be invited to judge in our semifinal round starting on DATE.
Semifinals will take place from DATE, the number of scores you finish will determine what judge certificate you receive.
Your scores from the semifinal round will determine the top 15 teams that will be finalists in our World Summit event in October of 2023!

- [ ] On the judge dashboard [during semifinals](https://docs.google.com/document/d/1-EpzEqGvSrYwXKbDw5vFvLn_E6svPlft5oT6CKXCK0w/edit#heading=h.hxz7do4k5udf). Text can read:

Welcome to the online judging portal for the first round of Technovation Judging! Click on the button below to open a submission and start scoring. 
Button: Start a new score

- [ ] On the judge dashboard when [judging is finished](https://docs.google.com/document/d/1-EpzEqGvSrYwXKbDw5vFvLn_E6svPlft5oT6CKXCK0w/edit#heading=h.40fjjbjhj43e):

Thank You!
Thank you for your help scoring and giving valuable feedback to Technovation teams.
Your judging certificate will be available on DATE.
Thank you again for helping girls lead the change. Your contribution to supporting young women around the world is invaluable. See you next season!

- [ ] On the judge dashboard when [semifinals is on](https://docs.google.com/document/d/1-EpzEqGvSrYwXKbDw5vFvLn_E6svPlft5oT6CKXCK0w/edit#heading=h.yro22vi3aced) but the judge is not fully onboarded:

To be able to judge submissions online this season, make sure to complete the To-do items on the left: Consent Waiver and Judge Training

**Comment by viviancan** [comment]
Confirming this is on QA
