### ISSUE TITLE
Direct link in pitch event invite to pitch event details page on dashboard

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3826]
Currently when students receive an invite to attend an RPE, they get an email with a button to "log in for more details." That button takes them to the /student/dashboard#/submission - the main student dashboard which shows their submission.

There's no information about events on this page. The link in the email invite should take the user to /student/dashboard#/events instead so they can view their event details. 

<img width="579" alt="Screen Shot 2023-02-03 at 11 05 27 AM" src="https://user-images.githubusercontent.com/516764/216650459-348da7db-6ba4-408d-8d8e-7e79bb22a84a.png">

**Comment by shaunxp20** [comment]
This one is on QA now. 👍

**Comment by dboyer** [comment]
Confirming that on QA the link in emails is now going directly to the events page.
