### ISSUE TITLE
Make pitch events page accessible even if judging is turned on

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3827]
Currently, if judging is turned on, students do not see any information on the pitch events page (/student/dashboard#/events).

It is correct that students shouldn't be able to select an RPE once judging is turned on. However, they should still be able to see information about the event they are attending. Could we make the event info visible but remove the sign up button?

<img width="701" alt="Screen Shot 2023-02-03 at 11 11 36 AM" src="https://user-images.githubusercontent.com/516764/216651789-41e453c8-5c22-4f0d-a4d1-aaa7390211cb.png">

**Comment by viviancan** [comment]
I attached screenshots of all of the different "states" for the pitch your project tab

[https://app.zenhub.com/files/29868115/367e828f-6bb1-4ba3-b8a7-9b47e828f3d1/download](https://app.zenhub.com/files/29868115/367e828f-6bb1-4ba3-b8a7-9b47e828f3d1/download)

**Comment by viviancan** [comment]
Confirming this is on QA!

**Comment by dboyer** [comment]
Confirming that if I'm attending an event, I can see the event details even if judging is on. If I'm not attending an event already, I cannot see event details as the time period to select events closes once judging opens.
