### ISSUE TITLE
Create team page and team details pages are smaller width

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3830]
On QA the page to create a new team (student/teams/new) and then the details page for the team on the dashboard are a smaller width than the other pages

<img width="603" alt="Screen Shot 2023-02-06 at 12 52 44 PM" src="https://user-images.githubusercontent.com/516764/217047574-ee797b40-a99d-4a11-b6c8-75159aac2873.png">

<img width="1043" alt="Screen Shot 2023-02-06 at 12 52 57 PM" src="https://user-images.githubusercontent.com/516764/217047625-ccdef79d-9ee9-4652-a304-7860e39806ac.png">

**Comment by dboyer** [comment]
The width for editing your location may also be off? It looks a bit narrow to me but I can't remember if we adjusted this page or not as part of the rebranding.

<img width="683" alt="Screen Shot 2023-02-06 at 12 53 37 PM" src="https://user-images.githubusercontent.com/516764/217047759-9430ed2b-a83a-473f-a5de-dd3df342a174.png">

**Comment by viviancan** [comment]
Verifying this is on QA

**Comment by viviancan** [comment]
I'll take a look at the location and edit form!

**Comment by viviancan** [comment]
@dboyer location and team edit are now on QA

**Comment by dboyer** [comment]
Confirming the location and team pages are now the correct width on QA. Thanks for the quick update on this!
