### ISSUE TITLE
Investigate location issue re: Bishkek 

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3836]

**Comment by viviancan** [comment]
refs: 3545

**Comment by viviancan** [comment]
I believe the participants are not able to be filtered because their location is not associated with a state/province. For some reason the geolocation is not assigning a state/province when they set their location.

 There are few of the `Bishkek` participants that are associated with `Chüy Region` and those individuals are filtered appropriately. 

When setting a participant location to `Bishkek` the state/province field comes back empty. I can only get the form to load Chüy Region using a very specific set of steps (shown in the attached video)

https://drive.google.com/file/d/1thjKSymzuIygVW1Fy3ejPNBNgGqZYjL2/view?usp=sharing


this may require data cleaning on our end.

**Comment by viviancan** [comment]
Interesting data comparing 2022 season to 2023 season

Bishkek Stats

**2022**
`state_province`
`EMPTY` (' ') = 6
`NULL` = 0
Total = 6 accounts with missing `state_province` information

**2023**
`state_province`
`EMPTY` (' ') = 315
`NULL` = 14

Total = 329 accounts with missing `state_province` information

I think we may need to create a rake task to find accounts in `2023` with the city `Bishkek` and an `empty` or `null` state_province field, and update that value to `Chüy Region`. This would also allow us to run the rake task while registration is still open and also at the end of the season to clean up this location data.

**Comment by viviancan** [comment]
@shaunxp20 @dboyer Thoughts on this approach?

**Comment by viviancan** [comment]
Ok! 1 additional update here, we actually have a rake task called `fix_empty_states.rake` which does exactly what it says 🎉 With a little bit of tweaking I was able to run it against some local dummy data. It seems to work as expected and even picked up on some other missing state accounts that I had locally. The only downside is the reverse geocoding is registering the city `Bishkek` in the state_province of `Bishkek City` instead of `Chüy Region`. Chüy Region has been the confirmed location by the local ChA. I'm not sure why the reverse geocoder is returning bishkek city. Even if we left it as Bishkek City, our current location filters do not filter by that value anyway. So I do think the path that I mentioned above is the way to go. I was able to create a rake task mirroring the approach of the `fix_empty_states rake` task to update my local dummy data successfully for the accounts with missing state_province in Bishkek. Next steps are to confirm the fix with production data.

**Comment by dboyer** [comment]
I'm good with a rake task to update the missing state to Chüy Region. That's interesting that we have a fix_empty_states.rake task and that it pulls up the wrong state. That seems to imply both that this has happened before and that perhaps there are changes to the underlying geocoders that are causing the problem this year and not last year.

**Comment by viviancan** [comment]
Moving this to the backlog since it is currently blocked

**Comment by viviancan** [comment]
There are currently 393 participants in the city `Bishkek`. I have included the breakdown of the different state_provinces that have been assigned for this area. 

| state_province      | count |
| ----------- | ----------- |
| EMPTY                | 328      |
| Bishkek City       | 3          |
| Chuy Province   | 44        |
| Chuy Region      | 2        |
| NULL                  | 16         |

I think a rake task to pull all participants in KG (country: Kyrgyzstan) located in the city `Bishkek` and update their state_province to `Gorod Bishkek` is the best approach. In order for the admin and chA location filters to work Bishkek participants would need to be located in Gorod Bishkek. Also a general rake task (instead of one based on IDs) would allow us to rerun this in the future for any other participants with location issues here. Removing the blocked tag for now.

@shaunxp20 @dboyer

**Comment by viviancan** [comment]
Confirmed this is on QA on working as expected. Will need to deploy to prod to run there still!

**Comment by dboyer** [comment]
Confirming that I see Gorod Bishkek as a state/region and Bishkek as a city and filtering is working as expected.

**Comment by viviancan** [comment]
This is on production and the rake task has been run. A total of 396 accounts were updated.

Detailed [info here](https://docs.google.com/spreadsheets/d/1F75JoJ98Hhh9Px00higWTZJkQRGqcybcVNx9wL0qfFE/edit?usp=sharing)
