### ISSUE TITLE
Support ticket

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3848]

**Comment by viviancan** [comment]
Taking a look at the Pakistan issue ^^

**Comment by shaunxp20** [comment]
High level overview of what I'm seeing (I got tagged into the issue)..

Here are the results for "Pakistan, Gilgit-Baltistan, Gilgit" coming from Google (via the geocoder gem):
```
- !ruby/object:Geocoded
  id: 711ef389
  state_code:
  state:
  latitude: 35.9205845
  longitude: 74.30737309999999
  city: Gilgit
  country_code:
  country:
```

There is no associated country (or state) which is causing an error (which isn't getting surfaced to the front-end):
```
NoMethodError (undefined method `downcase' for nil:NilClass

    if geocoded_results.first.country.downcase == "israel"
                                     ^^^^^^^^^):
```

It doesn't seem like that location can be entered from the GUI/front-end. I think you're right Vivian that the only option is for us to manually enter this location into the database (or perhaps add some custom code for this location like we do for Palestine); but then we'd have to deal with how to find the location via the admin as you pointed out too. But at this point, I really can't think of any other short-term ways to address this... 😕 

Something interesting though is that if we switch our geocoding service to Nominatim (which drives OpenStreetMap), it actually identifies the correct location, but changing out our provider at this point would lead to other issues though (like the multi-select not working as expected, and displaying multiple results when it should just it should just show one).

<img src="https://user-images.githubusercontent.com/58957909/222837672-c3731d49-1eb9-4672-8c40-c164f0f35752.png" width="500">
