### ISSUE TITLE
Update Redis database

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3865]
Update Redis database redis-colorful-98119 to version 6.2. 

Specific upgrade details:

You can upgrade your Redis database to the latest default version by using heroku redis:upgrade command. You can read more about this procedure in our [Dev Center article](https://devcenter.heroku.com/articles/heroku-redis-version-upgrade).

As you are upgrading to 6.2.10 %> which enforces TLS connections, you will need to update your application to use TLS connections. You can read more about this in our Dev Center articles: [Connecting to Heroku Redis](https://devcenter.heroku.com/articles/connecting-heroku-redis) and [Heroku Redis Version Upgrade](https://devcenter.heroku.com/articles/heroku-redis-version-upgrade).

If you are using stunnel for secure connection, this is no longer used with versions from 6.0 and must be removed. Follow [this guide](https://devcenter.heroku.com/articles/connecting-heroku-redis) for connecting to a Redis instance.

https://stackoverflow.com/questions/71862393/heroku-crashes-after-heroku-redis-upgrade-from-hobby-to-premium-0

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3865?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by viviancan** [comment]
PLAN FOR ROLLOUT
1. Deployment on Thursday 3/16/23
2. Access the admin portal on heroku and click the upgrade button for the redis  database
3. Shaun and Vivian will be on keyboard/aware in case of any fallout issues

**Comment by viviancan** [comment]
Update 
We discovered there is not a one click button for the upgrade. There are CLI steps to follow.

We plan to review the steps, write out the plan, and complete the upgrade on monday
