### ISSUE TITLE
Add space around the text on the submission confirmation page when submitted by a mentor

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3875]
When a mentor submits a project for a team, the final submission page looks like this:

<img width="1440" alt="Screen Shot 2023-03-07 at 1 15 22 PM" src="https://user-images.githubusercontent.com/516764/223513279-1da4f4ce-554a-4509-a087-90b34598410f.png">

The mentor page is on the old branding so this does not need to be a total rebrand to match the new branding. However, it would be helpful to add a buffer between the left side and the text.

**Comment by viviancan** [comment]
Confirming this is on QA![Screen Shot 2023-03-13 at 5.18.06 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/cbe6d291-f7c3-43ad-9ea0-d92a6637e077)
