### ISSUE TITLE
Optimize team submission screenshots on user upload with filestack

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3885]

**Comment by viviancan** [comment]
Refs #2

**Comment by viviancan** [comment]
Refs [ZH Issue #2](https://app.zenhub.com/workspaces/technovation-605271851956b1000ec2f24d/issues/zh/2)

**Comment by viviancan** [comment]
Steps
1. Limit all photos to 1mb (max size)
2. Use filestack image tag for image display
3. Use the `auto_image` or `compress` transformation methods. We only have 25,000 transformations a month, so I think we should increase that amount. Transformations are ideal because they will store a cached version of the image that is accessible for 30 days. Each time the photo is accessed it will not count as an additional transformation.

**Comment by viviancan** [comment]
**Example stats with the transformations**
- no transformation (original image): 898kb
- auto_image only: 260kb
- resize only: 59.1kb
- compress only: 681kb
- resize + compress: 52kb
- auto_image + resize + compress: 21kb

**Comment by viviancan** [comment]
Confirming the 2MB size limit is on QA for 
- Admin upload a submission image
- Student upload a submission image

**Comment by dboyer** [comment]
Confirming that I could only upload images below 2mb and received a warning message when I attempted to upload larger images. This worked for uploading as both a student and an admin.

**Comment by viviancan** [comment]
Confirmed this is on production and working as expected for student image upload and admin image upload. Tested on team - Nov 29 Test Team

**Comment by dboyer** [comment]
Also tested on production and confirmed I could only upload an image that was less than 2mb
