### ISSUE TITLE
Generate 2023 certificates

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3899]
Depends on uploading the new templates as part of #3898.

The goal is to open scores and certificates on June 30. Certificate details [available here](https://docs.google.com/document/d/12DZ5R1l2DiruHpWelABJfU_0Luroz0yatSGKgYfE4ms/edit#heading=h.h2pncnokirl3).

The issue for generating certificates for 2022 was #3498.

Accounts on Production that need certificates manually generated for them:
- [ ] 150483
- [ ] 109792
- [ ] 77391 (looks to be the same person as 109792)
- [ ] 46512

This list was pulled from this dataclip:
https://data.heroku.com/dataclips/wcxnqbifhryhvkmgfmmcnfcaqyxi

And a few more details are in #4029

**Comment by dboyer** [comment]
Note that a few certificates will need to be manually generated for the five or so judges who were at an RPE but not listed in the platform as fully onboarded for the 2023 season.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3899?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
A brief update/summary, I started generating certificates yesterday:
```
heroku run bundle exec rake certificates:award_all_direct --app technovation
```

The rake task ran for a little over two hours and then errored out.

There's a rake task to generate certificates in batches so we can pick up where we left off, but that rake task isn't working, I created #4063 and fixed it in #4062.

After we do a deployment to get the fix on production, we should be able to resume certificate generation. 👍

**Comment by shaun-technovation** [comment]
I resumed certificate generation with the batch generate command (resuming on the account (164452) that it errored out on):
```
heroku run bundle exec rake certificates:award_batch_direct[164452,15000] --app technovation
```

Unfortunately there wasn't any command line output for how many certs were generated, but I found out through the rails console on production:
```
> Certificate.where(season: 2023).count
=> 12750
```

12,750 certs generated. 🎉 

Moving this one to the Review/QA column. 👍 

Next steps:
- Certs need to be spot checked
- Certs still need to be manually generated for the accounts (RPE judges) that are in the description of this issue

**Comment by dboyer** [comment]
Spot checked all the categories and do not see any issues. Notified PT/VET so that they can check too. I will let them know about the four accounts needing to be manually awarded certificates.
