### ISSUE TITLE
Run rake task to set semifinalists & get html snippet of semifinalists for wordpress blog

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3901]
Dry run completed as part of #3900. This task covers generating the actual snippet and working with Marketing Team to resolve any issues.

Semifinalists announced May 30.

**Comment by shaun-technovation** [comment]
(On Friday) I ran the semifinalist rake task:
- `bundle exec rake 'judging:set_contest_rank[semifinalist, IDS]'`

And sent off the snippet from:
- `admin/semifinalist_snippet.txt`

I think everything is good, moving this one to "Review/QA" for now. 👍
