### ISSUE TITLE
Update judge text in the judge submissions tab for virtual judges / verify text for rpe and virtual judges is correct on all tabs

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3907]
I noticed the text on the judge submissions tab for virtual judges is incorrect
![CleanShot 2023-04-05 at 15.18.33@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/9a669729-046d-4933-9323-8c2525ad88ee)

There should not be reference to "assigned submissions" or "chapter ambassadors"

**Comment by viviancan** [comment]
Sort of related to #3824 - just a different tab!

**Comment by dboyer** [comment]
@viviancan Can we just take out the "Submissions to Score" header and text below if there aren't any assigned scores and just have the green "start a new score" button? Or do we need to have that header there? 

I'm wondering if that header being there is fall out from #3869

**Comment by viviancan** [comment]
Yes, we can remove and update the text. I think that text should really only be displayed if they are RPE judges. The submissions to score table should only display once they have started a new score.

**Comment by dboyer** [comment]
Agreed!

**Comment by dboyer** [comment]
Confirming the text is now correct for virtual judges. I checked for both judges with and without admin assigned submissions to judge.
