### ISSUE TITLE
Post-survey should only be required to view most recent certificate

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3916]
Currently, students must complete the post-survey to access their scores and certificates at /student/dashboard#/scores. 

Instead, we should require completion of the survey in order to view the most current year's scores and certificates. Previous year's certificates should be accessible without completing the post survey. This may require a reworking of the /student/dashboard#/scores page so that a tab of it is accessible with the past certificates.

**Comment by dboyer** [comment]
Ability to set different page visibility requirements will be covered under #3914

Platform reset can trigger the certificates moving to "past certificates" tab and no longer requiring completion of the post-survey. May inherently happen with the existing logic when we reset the season and not need to be an additional parameter added to the season reset rake task.

**Comment by shaun-technovation** [comment]
This functionality was completed in #3914.
