### ISSUE TITLE
Add page or tab for previous certificates

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3919]
Add a new tab at /student/scores. This issue covers setting up the tab and the overall containers. Need to consider #3916 when configuring this. While the mockup below includes previous scores, we will focus on previous certificates first and this ticket covers only certificates.

<img width="685" alt="Screen Shot 2023-04-12 at 12 23 08 PM" src="https://user-images.githubusercontent.com/516764/231520837-23f60187-f170-40d5-bdf0-6a65f7335210.png">

**Comment by dboyer** [comment]
May need to retitle "My Scores" as it doesn't cover everything on this tab.

**Comment by viviancan** [comment]
Verifying I could access the my scores tab as a student on production
