### ISSUE TITLE
Update judge text on two screens

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3939]
Update the text for two judge dashboard screens:

- [x] Judge Dashboard, Judging Finished - [tracked changes are here](https://docs.google.com/document/d/1-EpzEqGvSrYwXKbDw5vFvLn_E6svPlft5oT6CKXCK0w/edit#heading=h.nwwomva78tqo). This is mostly moving the text currently on the certs tab to the dashboard where it is more visible.

- [ ] Judge Certs tab - [tracked changes are here](https://docs.google.com/document/d/1-EpzEqGvSrYwXKbDw5vFvLn_E6svPlft5oT6CKXCK0w/edit#heading=h.1sxfjl45h4dr) - Just a couple new lines of text and a link to the certificate.

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by dboyer** [comment]
Confirming I see the updated text on production
