### ISSUE TITLE
Update width of screen when editing profile

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3942]
When students and judges edit their profile details, the edit screen is very narrow. Confirmed this is happening on both QA and production for both user types. 

<img width="832" alt="Screen Shot 2023-04-20 at 12 01 14 PM" src="https://user-images.githubusercontent.com/516764/233422693-e1d7b015-7954-4f05-96c4-9da84406cb21.png">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3942?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
Verifying this is on production for judges and students

**Comment by dboyer** [comment]
I also see it working as expected on production!
