### ISSUE TITLE
Test new font to see if it renders non-Roman characters

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3947]
Builds on the work in #2953 which indicates the problem with rendering non-Roman characters may be related to the fonts embedded in our PDFs. Audra provided [this PDF](https://drive.google.com/file/d/1QWpuXcgBui2gh_sLlSjQ3aFOD7f2tLsm/view?usp=sharing) to use for testing whether different characters will be generated.

**Comment by dboyer** [comment]
@viviancan Try this version of the certificate [saved on the drive](https://drive.google.com/file/d/1W23ti9lxHxkTpKJ9yDYtnpbH3g9qy5CY/view?usp=sharing)

**Comment by viviancan** [comment]
Unfortunately, the updated certificate did not work for the non-roman characters. Removing the cert from QA now.
![Screen Shot 2023-05-16 at 11.55.35 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/c5e00379-2f32-4553-9fdc-c60df5eee9d4)

**Comment by viviancan** [comment]
Updating my comment - I was able to successfully generate a certificate on QA, but the certificate did not display non-roman characters. The certificate showed "?????" for these characters
