### ISSUE TITLE
Fix branding for judge reset password error screen

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3951]

**Comment by viviancan** [comment]
- "invisible" button
- Mixed branding
`http://localhost:3000/judge/profile?local=true#/`
![CleanShot 2023-04-24 at 17.15.16@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/bd3bcd72-961a-4620-bff3-e94fa8f586a6)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3951?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Confirming that I was able to reset my password on QA and saw only the new branding.
