### ISSUE TITLE
Judge table shows incorrect count for "recusals"

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3960]
It appears the judge table shows the counts for all previous seasons. This is an issue for score monitoring and seems related to #3929

[See thread here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1682703925242699)

**Comment by viviancan** [comment]
After running `fix_counts` on QA, the counts do get updated, but they are not dynamic based on season.  If you filter by an older season, the counts for that season are unavailable and show "0".
![CleanShot 2023-05-04 at 15.47.24@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/ed27fdb9-807e-41d7-a932-446503712b35)

**Comment by dboyer** [comment]
Confirmed on QA that I'm seeing only recusals for this year. I checked a judge that had zero recusals, logged in as that judge and recused myself from two submissions, and saw the recusal count increase as expected on the admin page.

**Comment by viviancan** [comment]
Moving this back to in progress

**Comment by viviancan** [comment]
Following up here - We are unsure if this task should be run regularly [as suggested in the docs ](https://github.com/magnusvk/counter_culture#manually-populating-counter-cache-values)or just when there is a new counter column? Here is the [history of this addition ](https://github.com/Iridescent-CM/technovation-app/pull/1060#issuecomment-299353392).

Either way, right now we will not run the fix counts rake task. Interestingly, the recusal counts now appear to be correct on production. On May 7th the recusal counts were incorrect. On May 10th the fix for the recusal column was deployed to production, on May 16th the recusal counts were correct on production. I think the column count may have self corrected with [this PR ](https://github.com/Iridescent-CM/technovation-app/pull/3968).

Moving forward, Deb will add the rake task to the list of yearly tasks located in the wiki. We will cautiously proceed and pay extra attention to counts to determine if this should be run in the future.

**Comment by dboyer** [comment]
Added this to the annual tasks listed in the wiki
