### ISSUE TITLE
Only show the highest achieved certificate for a year in the previous certificates tab

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3966]
On QA, the past certificates tab shows all certificates earned by a student in a year. Program Team would prefer that it only show the highest certificate achieved for a year. 

This example for /admin/participants/729#/ shows both a quarterfinal and semifinal certificate. Completing this issue does not block deployment of the other certificate work.

<img width="860" alt="Screen Shot 2023-05-01 at 4 14 20 PM" src="https://user-images.githubusercontent.com/516764/235523144-fc7913a6-d077-4130-bf6c-1ff05368277a.png">

**Comment by shaun-technovation** [comment]
This one is on QA. I also created #3976 for only displaying the highest achieved certs for the current season.

**Comment by dboyer** [comment]
Confirming that on QA I only see the highest certificate awarded to the student
