### ISSUE TITLE
Technical video clicked info not updating at top of score details page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3971]
The top of each score detail page (for example /admin/scores/56866#/) notes whether the judge clicked into the technical and demo videos and if they downloaded the source code. The "clicked technical video" line is listed as no for every score, even when the judge comments indicate they watched the video. 

See examples of referencing the video but not having the technical video listed as viewed:

/admin/scores/56866#/
/admin/scores/56965#/
/admin/scores/57593#/

Please look into whether this field is updating correctly based on the judge viewing the video.

**Comment by shaun-technovation** [comment]
I tried this locally (for both the pitch video and the demo video) and neither are working for me. I have a hunch (not proven out) the pop-up modal is intercepting/blocking the click that makes the HTTP request to the back-end to update the video tracking fields in the database.

It didn't seem very idea/efficient to make an extra HTTP request to update these fields, so I hooked into some existing functionality (used by the pop-up modal to display the appropriate video) and in there is where we'll now update the video tracking fields.

**Comment by dboyer** [comment]
I have seen some of the pitch videos listed as viewed by judge for this season. Fwiw.

<img width="536" alt="Screen Shot 2023-05-03 at 6 03 13 PM" src="https://user-images.githubusercontent.com/516764/236059820-da6cf239-f8f7-40fc-8293-8d1f15a53b08.png">

**Comment by shaun-technovation** [comment]
> I have seen some of the pitch videos listed as viewed by judge for this season. Fwiw.

Ah, okay, good to know! So it's not totally broken functionality, just flaky it seems. This new/updated video tracking functionality should hopefully be more reliable. 🤞

**Comment by shaun-technovation** [comment]
A fix for this is on QA now, ready for some testing. 👍

**Comment by dboyer** [comment]
Tested on QA:

- Did not click Pitch video, logged correctly on scores admin page
- Clicked into Pitch video but did not click the play button, logged as Yes clicked in admin page
- Did click and watch Technical video, logged correctly on scores admin page
- Returned to a previous finished submission and clicked a video I had not watched before, confirmed on the scores admin page that it now listed as viewed - NOTE: I did not have to resubmit the score for it to update on the admin page whether I had viewed the video which seems like the correct behavior

Also confirmed that this worked for both virtual and RPE judges.
