### ISSUE TITLE
Add unpublish submission functionality for super admins

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#3973]
Super admins should have the ability to unpublish a submission.

Display a new "Unpublish" button displayed on the submission details page. Once they click "Unpublish":
- Display a pop-up modal with the text: "Unpublishing a submission will remove it from the judging pool. Please confirm you would like the submission to be removed from judging."
- Include "confirm" and "cancel" buttons

## BACK-END DETAILS
A submission's published field in the database is a timestamp, in order to unpublish a submission this field is set to nil/null.

## QA DETAILS

As a super admin:
- Find a complete/submitted submission
- Unpublish the submission via the new "Unpublish" button displayed on the submission details page
- Verify the submission has been unpublished  - the "% completed" progress bar should not be 100% (you can hover over the progress bar to verify that it needs the submitting step)

The "Unpublish" button should not be shown for regular admins, or for submissions that have not been submitted.

**Comment by dboyer** [comment]
I have something similar to this on the list of super admin privileges. I definitely think we should prioritize it for next year.

**Comment by dboyer** [comment]
When logged in as an admin, I see only the edit button on the submission which is the correct behavior.
<img width="701" alt="Screen Shot 2023-06-05 at 9 52 16 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/40495aa4-7bdb-45bb-9fb0-bd970b171003">

When logged in as a super admin and the submission is at less than 100%, I only see the edit button which is the correct behavior.
<img width="612" alt="Screen Shot 2023-06-05 at 9 58 40 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/0621fb2d-e955-457d-a0d8-b4094d5df19e">

When logged in as a super admin and the submission is at 100%, I see the unpublish button. Clicking unpublish moves the percent complete to 90% (junior/senior) or 89% (beginner) and the submission will not be in the judging pool.
<img width="657" alt="Screen Shot 2023-06-05 at 10 00 41 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/b4a0a872-bcb1-4e5d-9619-04b0ae715ce6">

I then logged in as the student and was able to resubmit the project, which moved it back to 100%. We can use that approach if something is inadvertently unpublished.
