### ISSUE TITLE
Fix rebranding for email reset for students and judges

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3978]
![Screen Shot 2023-05-08 at 8.41.44 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/1fa747a6-4794-4044-8d79-94fc647149fc)

**Comment by dboyer** [comment]
Confirming that I see the updated branding on QA.

However, if I leave the current password field blank and click "change email," I get a message stating "you updated your account" even though nothing changed.

**Comment by viviancan** [comment]
Added #3991 to fix this issue

**Comment by dboyer** [comment]
Cool - I'll move this to ready to deploy then since the bug is in a separate issue

**Comment by dboyer** [comment]
Confirming I see the updated branding on production

**Comment by dboyer** [comment]
Confirming I also tested this for mentors and it worked as expected
