### ISSUE TITLE
Any judge assigned to an RPE should receive a head judge certificate

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3981]
Since some RPEs are judged in person and others are judged online, we would like all judges assigned to an RPE to receive a head judge certificate by default, not based on the number of submissions they judge. 

We'll need to look into how certificates are assigned to RPE judges now and make adjustments accordingly.

Info on certificates is in [this Google doc](https://docs.google.com/document/d/12DZ5R1l2DiruHpWelABJfU_0Luroz0yatSGKgYfE4ms/edit#heading=h.h2pncnokirl3).

**Comment by dboyer** [comment]
Based on QA and the notes in the Certificates doc, we believe this is already happening. This issue covers verifying in the code the process of awarding an RPE judge a certificate.

**Comment by viviancan** [comment]
| Judge      | Completed Scores | Incomplete Scores | Head Juge?
| ----------- | ----------- | ----------- | ----------- |
| deb+judge0523@technovation.org      |  2       | 1 | yes |
| deb+mentor0310b@technovation.org | 0 | 1 | yes |
| deb+judge1116@technovation.org | 3 | 3 | yes |

Verified this locally and on QA by searching for "live judges" in the judge admin page. I viewed individual judge info pages and all of the live judges, regardless of the number of complete or incomplete scores, had the "Head Judge will be generated text."

![Screen Shot 2023-05-22 at 11.19.45 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/2d2157df-90ca-484a-ac06-322353da2528)

In the code, the following method (`app/technovation/determine_certificates.rb`) suggests that judges who participate in any events will receive the head judge certificate 
```  
def gets_head_judge_certificate?
    @account.judge_profile.present? &&
      !@account.judge_profile.suspended? &&
      @account.judge_profile.completed_scores.by_season(season).count <= MAXIMUM_SCORES_FOR_HEAD_JUDGE &&
      (@account.judge_profile.events.any? ||             <==== This line here ****
       @account.judge_profile.completed_scores.by_season(season).count >= MINIMUM_SCORES_FOR_HEAD_JUDGE)
  end
```

We could also check the judge info page for live judges on production. We haven't tested the generate certificates task yet, but based on how it has run in the past and on the information above, I believe RPE judges would receive a head judge certificate.

**Comment by viviancan** [comment]
@dboyer ^
