### ISSUE TITLE
Support Ticket

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3982]
Support requests starting Wed May 10 with priority for judging and RPEs

**Comment by viviancan** [comment]
5/12/23
Issue where a judge is duplicated in the judge table in the admin portal. Judge is unable to login. [Details are here ](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1683900516955039)

**Comment by viviancan** [comment]
5/12/23
Dataclip request - 2022 judges and their gender

**Comment by viviancan** [comment]
> 5/12/23 Issue where a judge is duplicated in the judge table in the admin portal. Judge is unable to login. [Details are here ](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1683900516955039)

It seems that this judge may be trying to login via the registration form. Ophelie is following up for more information

**Comment by viviancan** [comment]
> 5/12/23 Dataclip request - 2022 judges and their gender

[Dataclip](https://data.heroku.com/dataclips/quytfpbjygrricffzkdwvlctpbzh) has been created and shared

**Comment by dboyer** [comment]
Two submissions to unpublish:

/no-name-yet-technovation-talas2#/
/no-name-yet-baby-girls

**Comment by viviancan** [comment]
Submissions have been unpublished
- /no-name-yet-technovation-talas2#/
- /no-name-yet-baby-girls

**Comment by dboyer** [comment]
One more to unpublish

- /no-name-yet-7187cae8-5a3f-411d-80d2-9445caffc94b (should be entirely in a non-English language which is why the name is a random series of letters and numbers)
