### ISSUE TITLE
Test integration between platform and Tableau

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3985]
We would like to sync data from the platform to Tableau for the assessment team to use in building dashboards. This issue covers reviewing the documentation and testing an integration with QA. We will document the necessary steps to create the connection and provide them to the assessment. 

https://help.tableau.com/current/pro/desktop/en-us/examples_postgresql.htm

**Comment by dboyer** [comment]
Lorena will be accessing Tableau via tableau desktop using a Creator license. She uses a ThinkPad X1

**Comment by viviancan** [comment]
Lorena and I are meeting on Wed 5/31

**Comment by viviancan** [comment]
The guide was helpful. I was able to set up a new connection with the production DB. DB credentials for external connections were found on Heroku by going to the DB addon and selecting "credentials". Security recommendations were also emailed.
![CleanShot 2023-05-31 at 11.21.13.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/877dec31-b414-4309-9412-0eece7e0a1f7)
