### ISSUE TITLE
Set up super admin user group

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3986]
~~[ ] Create super admin table~~
~~[ ] Seed super admin table with ID of first person~~

**Comment by viviancan** [comment]
We added a `super_admin` boolean on the `admin_profiles` table. This seemed like the most straightforward approach to set up the super admin permissions.

**Comment by viviancan** [comment]
Confirming this is on QA. Currently, all admins are set to regular admins.

**Comment by viviancan** [comment]
2 admin accounts have been updated to be super admin

**Comment by dboyer** [comment]
I see two super admins at /admin/admins!
