### ISSUE TITLE
Support Request: Confirm if online scores should be deleted for a judge if they are added to an RPE at a later time

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3994]
We had an issue where RPE judges were able to score virtual submissions even though they are part of RPE. [Details are here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1683924923387689)

The goal of this ticket is to confirm if online submission scores are deleted if a judge is added to an RPE at a later time.

**Comment by dboyer** [comment]
I believe that virtual scores are kept even when a judge is later assigned to an RPE.

1. I logged in with the "Judgey McGee" account and completed one virtual submission and started another submission
2. I went to the scores page and the judge page and confirmed the two scores were visible
![Screen Shot 2023-05-18 at 12.15.27 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/d684196a-0012-4b87-8ca3-0ac37ce19aba)

3. I assigned that judge to an RPE that had three submissions.
4. I logged in as the judge again and saw three submissions to score as well as my in progress and completed submission

![Screen Shot 2023-05-18 at 12.23.01 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/7f2866fe-aab2-4588-b770-5aa5b919927c)

5. I finished scoring one of the RPE submissions and started scoring another
6. I went to the admin page for the judge and saw that two scores were listed as finished and two in progress (as expected)
![Screen Shot 2023-05-18 at 12.26.03 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/ebf49c45-a7db-43d7-a3cf-59f1344af026)
7. I went to the scores page for one of the virtual scores and confirmed that the score I added (prior to being invited to an RPE) was still listed in the complete scores

![Screen Shot 2023-05-18 at 12.27.35 PM.png](https://images.zenhubusercontent.com/5ca619b412380971eb9c9477/a3ed49a8-37dc-4b0a-933c-c59ed79eaaf9)

**Comment by viviancan** [comment]
I did not see anything in our code that suggests scores are deleted when a judge is added to an RPE. I could only find that an email is sent to the judge. Based on the timestamps of the scores in the DB it seems that the judge started scoring an online submission and then was later added to an RPE.

**Comment by dboyer** [comment]
Thanks for confirming this, @viviancan! I'm satisfied that no scores are being unexpectedly deleted.
