### ISSUE TITLE
Long team names impact layout of judge dashboard

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3996]
If the team name is long on the judge dashboard, it messes up the alignment of the left column

<img width="1223" alt="Screen Shot 2023-05-18 at 12 38 57 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/90139832-2026-410c-9472-437066a61b72">

**Comment by shaun-technovation** [comment]
I have a fix for long submission (and team) names, making it so it will wrap to the next line.

in screenshot with the misalignment of the left column, this seems to be independent of long submission names, I can see the misalignment with shorter submission names, the left column seems to break when the screen size is a certain size.

**Comment by shaun-technovation** [comment]
> in screenshot with the misalignment of the left column, this seems to be independent of long submission names, I can see the misalignment with shorter submission names, the left column seems to break when the screen size is a certain size.

I fixed this too, so the nav items shouldn't wrap like in the screenshot. 👍

**Comment by shaun-technovation** [comment]
This one is on QA. 👍
