### ISSUE TITLE
Update Learnworlds API endpoint

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3997]
Update endpoint to https://beginner.technovationchallenge.org/admin/api

See email from Nick with more details. This must be done by **June 19**

## POST-DEPLOYMENT INSTRUCTIONS
- Remove `LEARNWORLDS_CLIENT_SECRET` - this has been renamed to `LEARNWORLDS_API_CLIENT_SECRET` which has already been added to QA and Prod
- Remove `LEARNWORLDS_CLIENT_ID` - this has been renamed to `LEARNWORLDS_API_CLIENT_ID` which has already been added to QA and Prod

**Comment by viviancan** [comment]
The URL might be in `app/services/learn_worlds/api_client.rb`

**Comment by dboyer** [comment]
I accessed the Learnworlds curriculum on prod and saw I was auto-enrolled as of today. I think we're good.
