### ISSUE TITLE
Confirm super admins displaying correctly on admins page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3998]
Depends on completion of #3986.

Super admins should display automatically on /admin/admins if we update the status options as part of #3986. If we do not do the status option, we will need to specifically update the status column page to: 

- [x] Displaying anyone with super admin status on this page
~~[ ] Updating the status column to say: super admin or admin~~
- [x] Add Permissions column that says super admin or admin

**Comment by viviancan** [comment]
All admins will display on the admins page. I added a new column called "permissions". This column will either say "admin" or "super admin"

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by viviancan** [comment]
2 accounts have been updated manually to a "super admin".

Steps to update
```
admin_profile = AdminProfile.find_by(account_id: account_id_here)  
admin_profile.super_admin = true
admin_profile.save
```

![CleanShot 2023-06-01 at 08.00.36@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/3d75fc53-be3b-4161-a7df-1ccc750ca9ea)

**Comment by dboyer** [comment]
I see two super admins on QA
