### ISSUE TITLE
Add ability for super admins to add new super admins

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4000]
The initial super admin will be seeded in the database as part of #3986. There are two possible approaches:

1. On the/admin/admins page, super admins should see a button to add a new admin and also a button to "add a new super admin." Clicking this button loads the invite form to send someone an email saying they are invited to be a super admin

2. Next to the delete button for any admin should be a new button stating "change to super admin" so that admins can be given a new super admin role if necessary

There should only be a few super admins so we should go whichever route is the most straightforward. Note: many super admins may be admins already when we deploy this feature.

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by dboyer** [comment]
Confirming on QA that:

-  I see the button "make super admin" next to existing admins
- The "make super admin" button does not display next to people who are already super admins
- I was able to update an admin to a super admin

**Comment by viviancan** [comment]
Confirming I do not see the "make super admin" button on production with my admin account

**Comment by dboyer** [comment]
And I do see the "make super admin button" on production with my super admin account!
