### ISSUE TITLE
Only allow super admins to edit content settings

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4001]
Admins should be able to view the content and settings at /admin/season_schedule_settings/ but only super admins should be able to edit the content and settings.

**Comment by dboyer** [comment]
If we choose to only show admins the summary page of the settings, we should go tab by tab to confirm that all information is included on that summary page.

**Comment by viviancan** [comment]
This wasn't initially pointed since I pulled it in at the end of the iteration. I added an estimate of 5 pts.

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by dboyer** [comment]
On QA, I logged in as a super admin and I was able to change and save content settings. I then logged in as an admin and was able to view the content settings but all the editing options were greyed out. Clicking the "review button" led to the summary page where the only option was to cancel, not save.

**Comment by dboyer** [comment]
Kiki also reviewed and confirmed that she could not edit any content settings with her admin account.

**Comment by viviancan** [comment]
Confirming that I cannot edit the settings with my admin account on prod

**Comment by dboyer** [comment]
And confirming that I see the option to edit content settings as a super admin on prod.
