### ISSUE TITLE
Integrate Filestack for team photo upload in submission process

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4021]
Depends on completing #3222 

- Integrate Filestack for the team photo upload - likely can be similar to the code on the screenshots in the submission process
- Confirm that any uploaded photo is displayed on the team summary page on the user profile
- If user has already uploaded a team photo on their team summary page on the user profile, the photo should display on the team photo section of the submission process

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4021?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
Confirming this is on QA
