### ISSUE TITLE
No name yet should not appear in the team submission name

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4023]
Every URL includes no_name_yet before the team name (e.g. /admin/team_submissions/no-name-yet-building-bots). Remove no name yet from the URL.

**Comment by shaun-technovation** [comment]
Here's a breakdown of how the slug will work now:
- When a submission is started, the slug will get generated, which will be in the format: "project-name-by-team-name"
  - If the team name is still "(no name yet)" at this point, that's what will appear in the slug
- When the project name is updated it should update the slug (I restored and updated this behavior)
- When the team name is updated it should update the slug (this is new behavior)

Some background/additional info:

This functionality was changed/broken back in 2021. Prior to this functionality changing, the slug used to display "project-name-by-team-name", I restored this naming convention (with the "by" in the slug), we can change it to whatever we want of course.

When the slug gets updated (like it would prior this functionality changing in 2021, and it does now), URLs could potentially break, if someone has a link to the old slug, or possibly when an admin or ChA uses the back button and visits an old slug, those links will no longer be valid. The FriendlyId gem has a way to address this (by introducing slug history) if we want to address this issue: https://norman.github.io/friendly_id/file.Guide.html#History__Avoiding_404_s_When_Slugs_Change

**Comment by shaun-technovation** [comment]
Also, noting that this won't update any existing slugs with "no-name-yet" in them, but I think if the team name or project name gets updated (like by adding a space and removing it), it should update the slug name. We could probably write a rake task or something to update all the existing ones too.

**Comment by dboyer** [comment]
Good info! If we do write a rake task to update existing URLs, we'll definitely want to introduce slug history so that the girls who might have their project page bookmarked from previous seasons don't lose access to it.

**Comment by dboyer** [comment]
On QA:

- Created a new team and then started a submission. The slug was /admin/team_submissions/better-tomatoes-for-salsa-by-chips-and-salsa
- Logged in as a team who had started a submission but not named it. Updated the name and saw the slug change to get rid of "no name yet" and instead say /student/team_submissions/bananas-by-senior-spain-team-3-barcelona
- Updated the project name and saw it update in the URL
- I couldn't find a way to test starting a submission without having a team name. The platform forced me to choose a name when creating a team.
