### ISSUE TITLE
BUG: Admin incorrectly displaying "will be generated" message for certificates

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4029]
In the admin, accounts `484` and `7` show that certificates will be generated, but that is incorrect. These accounts aren't participating in the current season, so no certificates will be generated for them, the "will be generated" messaging should not be displaying in these scenarios.

**Comment by shaun-technovation** [comment]
A little more info on this one.

Both accounts, `484` and `7` participated in an RPE in the 2023 season:
- Account `484` -> `Madrid Senior`
- Account `7` -> `April Junior Pitch Event`

So the admin is correctly displaying which certificates should be issued. The disconnect is that the rake task only picks up accounts from the current season, and neither of these judges are in the current season.

There's a dataclip that shows more QA accounts like this, and it seems there are 4 on production (the results show 5, but one account is listed twice b/c they participated in two RPEs):
https://data.heroku.com/dataclips/wcxnqbifhryhvkmgfmmcnfcaqyxi

I think what's underneath this is that judges who aren't onboarded/participating in the current season can be assigned to an RPE (needs to be proved out).

I think for the ones on production, we could manually award them a certificate?

Another separate thought (after this gets addressed) is that we might want to just hide the certificates section in the admin if the account isn't in the current season.

Anywho, adding the "discuss" label on this one, not sure what else to do for it.

**Comment by dboyer** [comment]
Yes, it is possible to add a judge who is from a past season or not fully onboarded. The events page also allows sending an email to a judge who is in the system but not yet registered as a way to get new judges into the system.

**Comment by shaun-technovation** [comment]
I added #4044 to address the issue causing this. When that gets addressed then the rake task to generate certificates should work as expected.

As for this issue, the admin is correctly displaying what cert will be generated, so I think this issue can be closed. Also, if an account isn't in the current season, for the "will be generated" section we could display a message like "No cert will be generated because this account didn't participate in the current season", or hide that section too.

**Comment by dboyer** [comment]
Agreed that this can be closed now since the necessary work is captured in #4044.
