### ISSUE TITLE
Remove mentor-ChA merge functionality

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4031]
There is a rake task called `merge_chapter_ambassador_mentors` that is used to merge mentor and chapter ambassador profiles. This functionality isn't being used and is broken as of #4013, this rake task and all associated files should be removed.

**Comment by dboyer** [comment]
Confirmed with PT that there is no recent use of this merge functionality and it does not need to be kept.

**Comment by shaun-technovation** [comment]
Moving this one right to the "Ready to Deploy" column since there's nothing to QA.
