### ISSUE TITLE
Add admin functionality to remove a pending invite to a team

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4036]
Currently, only students and mentors can cancel a pending invite to a team. It would help to add an option to cancel invite to the admin page. 

This functionality can mirror the process that happens when a student on a team cancels an invite. I do not believe that it sends an email to the invited person informing them that their invite was rescinded.

Below mockup of where we might add the button to the "team member invites" section of the team admin page (i.e. /admin/teams/484#!students)

<img width="1224" alt="Screen Shot 2023-06-20 at 10 22 44 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/81a75fa7-5201-4f83-915d-1c38e3b8b357">

**Comment by shaun-technovation** [comment]
This one is on QA. 😄 👍

**Comment by dboyer** [comment]
Tested on QA and confirmed as an admin I could delete pending mentor and student invites. Logged in as the student who had issued the invites and they were no longer visible.

**Comment by dboyer** [comment]
Logged in as an admin on production and saw the option to delete a pending invite.
