### ISSUE TITLE
Switch Thunkable link to require /projectPage/ URL

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4048]
Currently, the Thunkable link in the submission form accepts /project. That should be changed so that it accepts only the format that includes /projectPage in the URL. That looks like https://x.thunkable.com/projectPage/62ebf220a....

We will work with PT to update the text so the students know how to retrieve this link.

**Comment by dboyer** [comment]
Similar work done in #3246

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4048?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This one is on QA.

**Comment by dboyer** [comment]
Confirmed on QA that I could add https://x.thunkable.com/projectPage/618... 

If I tried to upload a /projects file on the main "submission type" page, I got an invalid URL error.

@shaun-technovation I didn't get an error message when I tried to add /projects when I was updating an existing file. I followed the steps:

1. Added the correct /projectPage link and saved
2. Went back into the submission and clicked "change your upload"
3. Deleted the /projectPage link from the "source code external URL" field and put in a /projects URL instead
4. Clicked "Save"
5. It returned me to the main screen for submission: technical elements but it still had the /projectPage link
6. I clicked back to change my upload again and it shows the /projects link

Video of that process is [here](https://drive.google.com/file/d/1-nHuLszeV10ycW1eDsCaSyHr5xL6JDJD/view?usp=drivesdk)

**Comment by shaun-technovation** [comment]
> Confirmed on QA that I could add https://x.thunkable.com/projectPage/618...
> 
> If I tried to upload a /projects file on the main "submission type" page, I got an invalid URL error.
> 
> @shaun-technovation I didn't get an error message when I tried to add /projects when I was updating an existing file. I followed the steps:
> 
>     1. Added the correct /projectPage link and saved
> 
>     2. Went back into the submission and clicked "change your upload"
> 
>     3. Deleted the /projectPage link from the "source code external URL" field and put in a /projects URL instead
> 
>     4. Clicked "Save"
> 
>     5. It returned me to the main screen for submission: technical elements but it still had the /projectPage link
> 
>     6. I clicked back to change my upload again and it shows the /projects link
> 
> 
> Video of that process is [here](https://drive.google.com/file/d/1-nHuLszeV10ycW1eDsCaSyHr5xL6JDJD/view?usp=drivesdk)

Good catch! That's existing behavior, that's the "external source code URL" different than the "Thunkable project URL"; the "external source code URL" currently doesn't have any validations for Thunkable URLs, it would be this way on production too. We could add some validation though, I can create a new ticket if it's something we want. 🤔 😄

**Comment by dboyer** [comment]
Oh interesting! Yeah I think we should be consistent with the validation. I opened a new issue to add that.
