### ISSUE TITLE
Text changes for certificates

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4054]
Program team found two things in a last round of testing for certificates.

- [x] The judge dashboard for a judge who is not onboarded says they need to finish judge training. However, training is not available when judging is set to finished. From the [judge screens in Mural](https://app.mural.co/t/technovationgirls4378/m/technovationgirls4378/1674590684432/0f93038bbd4755c67632062ee6ab16cf1a1c6c90?sender=u9adab98cc36af2c4665e9477), it looks like this should be a screen with the pink "season close" tag. Maybe some conditional is not set to display that screen?

<img width="1146" alt="Screen Shot 2023-06-26 at 10 16 46 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/c506fdc3-1e57-4d23-938a-bd1a7f7af2c6">

- [x] The certificates page references a hashtag from 2022 (see below). That hashtag should be updated to read #Technovation2023Alumna

<img width="818" alt="Screen Shot 2023-06-26 at 10 18 51 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/5fc0971d-bf46-402d-9dc0-e55b85a980a6">

**Comment by viviancan** [comment]
I manually generated a QF cert for [this participant  ](https://technovation-qa.herokuapp.com/admin/participants/1135#/) and I see the updated full_text that includes the word "team" before the team name

**Comment by viviancan** [comment]
I logged in as [this participant ](https://technovation-qa.herokuapp.com/admin/participants/1155#/) and viewed the certificate tab. I saw the updated social media hashtag with the correct season year (2023)

**Comment by viviancan** [comment]
I set the season to judging finished.
I logged in as [this judge ](https://technovation-qa.herokuapp.com/admin/participants/334#/)(still onboarding)and saw the updated screen with the season close flag.

**Comment by dboyer** [comment]
Checked on QA and confirmed that I see the updated quarterfinal certificate text and the updated hashtag. I also see the correct season close text for the judge who is not fully onboarded.
