### ISSUE TITLE
Rename mentor type "Technovation alumnae" to "Technovation alumna"

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4065]
From the support ticket #4024, and related to #3937:
- the mentor type "Technovation alumnae" should be "Technovation alumna"

**Comment by dboyer** [comment]
Confirm that I see alumna in the registration process, on the mentor profile, and in the admin pages. I was successfully able to register a mentor account, update an existing account, and edit an account as an admin.
