### ISSUE TITLE
Spike/research restoring mentors inviting students functionality

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4077]
Look into what it will take to restore the functionality allowing mentors to invite students to one of their teams.

**Comment by shaun-technovation** [comment]
Here are some notes and preliminary work into restoring this functionally when we get around to it.

Here's what it looks like for a mentor inviting students
<img src="https://github.com/Iridescent-CM/technovation-app/assets/58957909/18d06002-f1d2-44d0-a2e8-007df4cd2dca" width="600">

Re-enabling this form and functionality is trivial, ironing out the kinks is where the bulk of the work will be. Here are some things I noticed:

The invite link goes to the new registration flow, but:
- all registration options (student, parent, mentor, judge) are available to select
- the email address field is not pre-filled with the one corresponding to the invite email address

After registering (and onboarding) it's not clear there's an invite, the only way I found the invite was by going to "Find your team", the invite doesn't appear on the dashboard.

After the invite is sent, the mentor is taken to a "this invitation appears to be missing" page, even thought the invite was sent and is valid.

----

The file that has commented out code that needs to be re-enabled/un-commented:
` app/views/teams/_edit_students.en.html.erb`

**Comment by shaun-technovation** [comment]
Moving this one to the Review/QA column, not sure there's much else do to with this until we want to move forward w/ restoring this functionality. Anywho, some notes are here for when that time comes.

Also, we could temporarily restore this functionality on QA so it can be seen/played with (or if we get the review branches feature working on Heroku, it would be a good candidate for that too).

**Comment by dboyer** [comment]
Closing as we do not intend to restore this functionality for the 2024 season.
