### ISSUE TITLE
Research: Investigate current Checkr API integration

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4083]
Determine how we currently integrate with Checkr to send and receive info related to US background checks

[API documentation](https://docs.checkr.com/?_gl=1*b2zfvb*_ga*NDI0MTI1OTE2LjE2ODg1ODMxMzI.*_ga_V7EME6CVPL*MTY4ODU4MzEzMS4xLjEuMTY4ODU4MzI0MC4xMS4wLjA.#)

**Comment by viviancan** [comment]
API POST request details are found in `background_check.rb`

```
    def post(resource, attributes)
      Checkr.request(:post, "/v1/#{resource}", attributes)
    end
```

We use 2 resources
- `candidates` -[https://docs.checkr.com/#tag/Candidates]( https://docs.checkr.com/#tag/Candidates)
- `reports` - [https://docs.checkr.com/#tag/Reports](https://docs.checkr.com/#tag/Reports)

The flow is
1. Mentor fills out background check and post request is made to `/mentor/background_checks`
2. A candidate is created in `background_check_candidate.rb`
3. The candidate details are sent to Checkr
4. If successful, candidate_id from Checkr is used to create a new report
5. The report is sent to Checkr (with the attributes -->   package: "tasker_standard", candidate_id: candidate_id)
6. If successful, we now have a report id
7. both the candidate_id and report_id are saved in the `background_checks` table 


**Front end**
The mentor dashboard is a vue.js app. When `mentor/dashboards/show` is rendered there is a content_tag with id "vue-data-registration". This content_tag contains data attributes that include 
- chapter_ambassador
- current_account
- current_mentor
- current_teams
- consent_waiver
- background_check

Each of these values has an associated serializer. For example chapter_ambassador values come from the ChapterAmbassadorSerializer.... The background check information comes from the BackgroundCheckSerializer. These values are stored when the vue app is loaded. In `app/javascript/mentor/store/getters.js` there is the `isBackgroundCheckWaived ()` function that determines if the checkmark is checked on the mentor dashboard.

There is also a `requires_background_check?` method in `mentor_profile.rb` that determines who needs a background check. This value is used in the conditional logic for the background check views in the mentor dashboard.
