### ISSUE TITLE
Determine fields and API calls necessary to add background checks for Canada and India

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4084]
Connected to #4083 

Determine the fields/API calls necessary to integrate with Checkr for [India](https://checkr.com/international-background-checks/india) and [Canada](https://checkr.com/international-background-checks/canada) background checks (criminal and global watchlist)

**Comment by viviancan** [comment]
**India Criminal Search**
**Estimated turnaround time - On average 7-8 business days.**
- Applicant’s Name
- Father’s Name
- Date of birth (DOB)
- Address
- Copy of a Government issued ID (Passport, PAN Card, DL, etc.)
- Authorization Form

**India Global watchlist**
**Estimated turnaround time - On average 2 days. Verifications will be closed, as Unable to Verify, after 15 business days of unsuccessful attempts.**
- Last name 
- First name 
- Date of birth (DOB) 
- Authorization Form

**Comment by viviancan** [comment]
Helpful links

- [International searches](https://help.checkr.com/hc/en-us/articles/360056108714-International-Screenings#:~:text=International%20Criminal%20Check)
- [Checkr Packages ](https://help.checkr.com/hc/en-us/articles/4410047632023-Help-me-understand-Checkr-packages)

**Comment by viviancan** [comment]
According to the docs > [**reports resource**](https://docs.checkr.com/#tag/Reports)
- This resource does not support the creation of reports which include international Packages. Use the `/invitations` API to order these reports

 I believe we will have to use the /invitations resource
