### ISSUE TITLE
Upgrade QA to Postgres 15

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4097]
QA is currently at Postgres 13.8. We should update to the latest version of 15.

**Comment by viviancan** [comment]
It appears that QA is already on 15. I'm not sure if this was done automatically? Shaun and I both noticed this yesterday before the production upgrade. 

![Screen Shot 2023-07-14 at 10.44.56 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/5ea7007d-c191-4aa9-b27a-c9494ae0cfb5)

This was on the activity log

![Screen Shot 2023-07-14 at 10.46.27 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/2702e4f9-e58a-4e88-965d-61a74cf0e3c8)

**Comment by dboyer** [comment]
Huh. Well I guess we can call this done then!
