### ISSUE TITLE
Investigate international package selection on checkr dashboard 

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4109]

**Comment by viviancan** [comment]
Refs #4081
We currently use the `tasker_standard` custom package. A package is a defined set of screenings that will be run after a candidate authorizes their background check ([docs here](https://help.checkr.com/hc/en-us/articles/4410047632023-Help-me-understand-Checkr-packages#h_01GRKW0WAG3ET0Q78CJGFW3Y3S)).

Our current package includes the following screenings:

- County Criminal Search (Current)
- National Criminal Search 
- Sex Offender Search 
- Ssn Trace 
- Global Watchlist Search 


I believe these are just for US-based candidates. I am not able to create a new package to include international candidates. See attached screenshot. We may need to contact someone at Checkr. I'm not sure if we need to update our subscription. 

![CleanShot 2023-07-17 at 20.25.03@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/1358af86-4790-46bc-8832-08c626b47d9d)

**Comment by dboyer** [comment]
I'll reach out to our contact at Checkr about adding this.

**Comment by viviancan** [comment]
I found this in one of the helper articles
`If you need to make changes to your organization's packages and do not have access to the Packages page of the Checkr Dashboard, work with your account admin. If you encounter any issues, don't hesitate to contact Checkr.`

https://help.checkr.com/hc/en-us/articles/4410047632023

**Comment by dboyer** [comment]
International package selection is not available for our subscription type via the Checkr interface. Emailed Checkr for more information about how to add them.

**Comment by dboyer** [comment]
International packages are now available on our Checkr account. Adding the overview slides here. [https://app.zenhub.com/files/29868115/a548395d-908b-4fd1-b36c-23f927921970/download](https://app.zenhub.com/files/29868115/a548395d-908b-4fd1-b36c-23f927921970/download)

**Comment by dboyer** [comment]
International packages are now available on our staging account.
