### ISSUE TITLE
Run the reset season rake task

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4120]
Run the rake task to reset the season:

- [x] QA
`heroku run bundle exec rails reset_for_season[force] --app technovation-qa`
- [x] Prod
`heroku run bundle exec rails reset_for_season[force] --app technovation`

Previous season reset issues for reference:
- #3157
- #3607

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4120?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Confirmed the season is reset on QA

**Comment by viviancan** [comment]
```
I, [2023-08-10T17:53:59.471377 #2]  INFO -- : Dalli/SASL: Authenticated
Resetting consent waivers
Resetting data use terms
Resetting onboarded flags
Resetting mentor trainings
Resetting judge trainings
Finished resetting
```

**Comment by dboyer** [comment]
Confirmed season reset on prod and QA
