### ISSUE TITLE
Allow students to upload parental consents

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4124]
The overall workflow is:

1. Student can download form from the parental consent tab of their profile
2. Student gets form signed
3. Student has a button on the parental consent tab to upload the form to the platform

**Comment by dboyer** [comment]
Let's use this as a general mock-up. We'll eventually want to support uploading media forms too but for now, PT would like to focus on parental consent forms.


<img width="573" alt="Screen Shot 2023-07-27 at 11 32 07 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/266a1e59-9550-4d37-9ad6-7e109325c251">

**Comment by shaun-technovation** [comment]
> Let's use this as a general mock-up. We'll eventually want to support uploading media forms too but for now, PT would like to focus on parental consent forms.
> <img alt="Screen Shot 2023-07-27 at 11 32 07 AM" width="573" src="https://user-images.githubusercontent.com/516764/256587868-266a1e59-9550-4d37-9ad6-7e109325c251.png">

Sounds good, do you have the text shown in the screenshot?

**Comment by dboyer** [comment]
Text is:

If your parent or guardian does not have an email address to sign the permission and media consent forms online, you can upload the signed forms here. Please print the forms and have your guardian sign them.

Permission Form (link)
Media Form (link)

We must be able to view the signature on the final page of the form so please make sure the shadow of your phone or camera does not cover the signature when you photograph the page. Please contact support@technovation.org with any questions.

**Comment by shaun-technovation** [comment]
I forgot to mention on stand-up that I took some liberties with the mock-up - I made the header text say "Uploading Consent Forms" vs permission forms because in the sidebar and section header it mentions "consent"; and the upload button/behavior is a bit different, anywho, all things that can be updated. It should be on QA to look at soon. 👍

**Comment by shaun-technovation** [comment]
TODO:
- [ ] Add status message after parental consent has been uploaded
- [ ] Add max file size

**Comment by shaun-technovation** [comment]
Basic functionality for a student to upload a parental consent is on QA. 👍

**Comment by dboyer** [comment]
On QA - confirmed that I could upload a PDF and an image file. I was not able to upload a .mov or .csv file

I agree that having the uploads section change if someone has uploaded a file would be helpful. We can use the text:

Thank you for uploading your consent form. We will review it as soon as possible, and you will receive an email when the form is accepted or if we need additional information.

**Comment by shaun-technovation** [comment]
> I agree that having the uploads section change if someone has uploaded a file would be helpful. We can use the text:
> 
> Thank you for uploading your consent form. We will review it as soon as possible, and you will receive an email when the form is accepted or if we need additional information.

This change is now on QA ☝️, along with the following changes:
- A 3 MB maximum file size upload restriction (this can easily be changed) 
- Whenever a new parental consent is uploaded it will set the approval status to pending and reset the approved/rejected at timestamps
- In the admin:
  - 2024 will be the first season to pick from in the parental consents datagrid
  - Adding student name to CSV export

**Comment by dboyer** [comment]
Tested on QA and I see:

- The parent consent section changes and I see text that the file was uploaded and is under review 
- I received an error message when uploading something over 3mb
- Added two consents for the same person and the admin page only displayed the most recent one
- Student name added to export
- Can only select 2024 as the season for parental consent
