### ISSUE TITLE
Make past certificates available for judges

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4125]
Students can currently access past certificates year-round based on the work in #3914. This issue covers extending that functionality to judges so they can access certificates all year. 

NOTE: Judges do not have to fill out the post-survey to access the current certificate, in case that impacts implementation.

**Comment by viviancan** [comment]
Confirming this is on QA

To test, find a judge from a previous season with a certificate and login as them. I tested using participant #336 on QA

**Comment by dboyer** [comment]
Confirmed on QA that I logged in as a judge and saw the previous certificates section. No certificate was available for a judge who hadn't earned one last year and I was able to download a head judge certificate for another judge
