### ISSUE TITLE
Reset surveys to track 2023 pre-survey

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4132]
Prior to opening registration, we need to reset the surveys. Deb will handle survey configuration but a developer needs to run the survey reset rake task. Last year's notes for this task are in https://github.com/Iridescent-CM/technovation-app/issues/3608

documentation: https://docs.google.com/document/d/1hVaugqKipnD8pYmCcMl5KWCHrrqBBSr-86MQZTdm5P8/edit?pli=1#heading=h.nk9euk5z6x91

resetting for all users (students & mentors)
For QA
heroku run bundle exec rails surveys:reset_all --app technovation-qa

For Prod
heroku run bundle exec rails surveys:reset_all --app technovation

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4132?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
I ran the script to reset surveys on QA (no output/confirmation displayed), should be all set. 👍

**Comment by dboyer** [comment]
Confirmed surveys reset on QA and prod
