### ISSUE TITLE
Toggle ability for ChAs to create an RPE based on admin setting

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4140]
A new admin setting to enable creating RPEs will be added in #4312, use this new setting so that:
- ChAs should only be able to create events if the toggle is on
- If toggle is off, ChAs should be able to still edit existing events
- If toggle is off, ChAs should be able to delete existing events (this is not necessary if it's technically challenging)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4140?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This one is on QA, if the corresponding admin control (done in #4312) to prevent new RPES from being created is disabled, then the "Add an event" button should be hidden.

**Comment by dboyer** [comment]
Testing on QA and confirmed:

- When the toggle was on, I was able to create a new event, edit an existing event details, add teams to an existing event
- When the toggle was off, I was not able to create a new event, edit an existing event, add teams to an existing event, delete an existing event. The button to add an event was not displayed.

**Comment by dboyer** [comment]
Tested by PT and no concerns found
