### ISSUE TITLE
Admin invitation emails should go to the new registration flow

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4155]
When an admin invites someone to register, the invite email should have a link (with an invite code) to the new registration flow.

When the invited person clicks on the invite link (in the email), they will be taken the first page of the registration system where the invited profile type will be pre-selected, and the other profile types will be disabled.

Invite codes can only be used once.
If registration is closed for a particular profile type, all associated invites for that profile type shouldn't work.

**Comment by dboyer** [comment]
I like the idea of having them go to the first page with the profile type already selected as a reminder of what they are signing up for.

**Comment by shaun-technovation** [comment]
This one is on QA! Admin invites to student, mentors, and judges should be using the new registration system now. 👍

**Comment by dboyer** [comment]
Tested on QA:

- Successfully invited a judge with a new email account. I received the email and was sent to the new registration system where I registered as a new judge.
- Successfully invited a mentor and was able to register as that mentor. I changed the email address from the one the invite was sent to. I received an error message when I tried to select an address already in the system but was able to change to a different address. NOTE: on the admin page, the invite to that mentor says "registered" so I'm guessing the invite is tied to the token not the email address. That feels correct.
- Successfully invited a student and the link in the email directed to the new registration page. However, it was only selecting the 13-18 year old option and did not allow me to switch to the 8-12 year old option.

I tried to enter a birthdate that would make the student 11 and the validation check flagged that the student was too young. It prompted me to go back to the previous screen and select the other student type which I was not able to do.

@shaun-technovation Is there a way for the student invite to default to the age 13-18 but allow selecting age 8-12 too? If not, maybe we need to add two student invite types - one for 8-12 and one for 13-18.

**Comment by shaun-technovation** [comment]
> @shaun-technovation Is there a way for the student invite to default to the age 13-18 but allow selecting age 8-12 too? If not, maybe we need to add two student invite types - one for 8-12 and one for 13-18.

Hmm, I can see at least two options:
- A student invite could enable both the student and parent profile type
- Adding a new parent invite that would enable the parent type

Also, having a message like "If you would like to register as a different participant type, please click here" could help too, but we need to get #4189 fixed for this functionality.

**Comment by dboyer** [comment]
I don't have a strong preference between the options if one of them is technically easier than the other.

**Comment by shaun-technovation** [comment]
> I don't have a strong preference between the options if one of them is technically easier than the other.

I created #4215 so an admin can invite a parent. 👍
