### ISSUE TITLE
Integrate admin invite tokens into new registration flow

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4156]
When an admin invites someone, it creates a new record in the `UserInvitations` table with an associated `admin_permission_token`. When the person being invited clicks the link in the invite email they will be taken to the new registration flow with the invite code (#4155), once the registration is completed, the associated `UserInvitation` record needs to be updated to a `registered` status so it reflects appropriately in the admin.

**Comment by shaun-technovation** [comment]
This one is one QA, but there isn't anything that will need to be tested, not until more of the invite work is completed. 👍

**Comment by dboyer** [comment]
Thanks for confirming no testing is needed. I sent an admin invite on QA just to confirm everything was working and it worked as expected.
