### ISSUE TITLE
Allow admin invites to bypass registration open/closed toggles

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4157]
Someone invited via an admin invite should be able to register at any time, regardless of whether registration is open or not.

- Create a new option for admin invites to specify whether it's an anytime registration
  - If it's an anytime invitation, the invite should work even if registration is closed

**Comment by shaun-technovation** [comment]
This one is now on QA. 👍

**Comment by dboyer** [comment]
On QA, checking:

- Sent an invite to a mentor when mentor registration turned off, with the bypass registration controls checked, and was able to register as that mentor
- Sent an invite to a mentor when mentor registration turned off, with the bypass registration controls unchecked, and got a message on the registration page saying registration was not available
- Sent an invite to a judge when judge registration turned off, with the bypass registration controls checked, and was able to register as that judge
- Sent an invite to a judge when judge registration turned off, with the bypass registration controls unchecked, and got a message on the registration page saying registration was not available
- Sent an invite to a student when student registration turned off, with the bypass registration controls checked, and was able to register as that student
- Sent an invite to a student when student registration turned off, with the bypass registration controls unchecked, and got a message on the registration page saying registration was not available

A couple potential issues:

- [ ] When I had a mentor registration where I did not bypass registration toggles, I got a message saying the invitation was not valid. Is that correct? Or should I just see the message about registration being closed. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2NIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--182f5726c27517c26773f4eb0f9ae2f51aaa53e0/Screen%20Shot%202023-10-04%20at%209.09.15%20PM.png)

- [ ] When I do get the message that I can't register for a particular user type, I am able to select another user type that is open for registration. I think that's okay, but I'd like to include a line of text saying: "You were invited to register as a user group that is not open for registration currently. The user groups below are available for registration."

- [ ] The check box does not align with the text prompt. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bac74c75281161a29f3d1ac6855b2869d39dd2a9/Screen%20Shot%202023-10-04%20at%208.48.40%20PM.png)

**Comment by shaun-technovation** [comment]
> * [ ]  When I had a mentor registration where I did not bypass registration toggles, I got a message saying the invitation was not valid. Is that correct? Or should I just see the message about registration being closed.

The way it is now, you should get both messages - invite invalid and registration closed. If there is an `invite_code` in the URL, it will display either the "invite invalid" message, or the "you have been invited" message.

> * [ ]  When I do get the message that I can't register for a particular user type, I am able to select another user type that is open for registration. I think that's okay, but I'd like to include a line of text saying: "You were invited to register as a user group that is not open for registration currently. The user groups below are available for registration."

Hmm, definitely doable, but not easy to implement the way it works now, the invite logic/messages and the registration open/closed logic/messages are totally separate, which is why there are two messages displayed ☝️ in the case above. The registration form only knows if the invite is valid or not, it doesn't know if registration is open/closed for that invite (that happens on the back-end). I'll have to think about how to do this, tricky to do the way it works now. 🤔 

> * [ ]  The check box does not align with the text prompt.

I added this to #4241. 👍

**Comment by shaun-technovation** [comment]
> > * [ ]   When I do get the message that I can't register for a particular user type, I am able to select another user type that is open for registration. I think that's okay, but I'd like to include a line of text saying: "You were invited to register as a user group that is not open for registration currently. The user groups below are available for registration."
> 
> Hmm, definitely doable, but not easy to implement the way it works now, the invite logic/messages and the registration open/closed logic/messages are totally separate, which is why there are two messages displayed ☝️ in the case above. The registration form only knows if the invite is valid or not, it doesn't know if registration is open/closed for that invite (that happens on the back-end). I'll have to think about how to do this, tricky to do the way it works now. 🤔

I added #4245. to capture this. I can fill out more details in that issue and/or work on it if it's something we want to prioritize.
