### ISSUE TITLE
Clicking upload on parental consent without a file attached loads a token error page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4159]
I had already uploaded a parental consent form when logged in as /admin/participants/1387#/. I went back to the page and hit "upload" without attaching a file and got this error page /token_error#/

<img width="1380" alt="Screen Shot 2023-08-13 at 1 28 41 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/0ca8866c-3b43-4d61-af44-0a4a09eef7db">

**Comment by shaun-technovation** [comment]
Good catch on this! This was an interesting bug where if no file is selected (on a form w/ only a file upload), no parameters will be submitted with the form, which was causing this error. Anywho, it should be addressed in #4164. 👍 

Related Rails issue:
https://github.com/rails/rails/issues/17947

**Comment by dboyer** [comment]
@shaun-technovation I'm no longer seeing this error page, but I did run into another error page. I was logged in as /participants/1398#/ (not impersonating) and ran into this issue:

- Clicked Upload when both the parental consent and media consent fields were empty
- Got a message that I needed to attach a file
- Returned to the page and selected a PDF (less than 1mb) to upload
- Clicked upload and got a message stating "The consent forms need to be an image or in PDF format, and less than 3 MB. Please try again."
- Went to the parental consent field and could not upload anything else
- Logged in as an admin and that consent form was on the list to review

Screen capture available at https://drive.google.com/file/d/1d2JeIIWJPgw6f78lzG7xudVs59_nTqNw/view?usp=drivesdk

**Comment by shaun-technovation** [comment]
> @shaun-technovation I'm no longer seeing this error page, but I did run into another error page. I was logged in as /participants/1398#/ (not impersonating) and ran into this issue:
> 
>   * Clicked Upload when both the parental consent and media consent fields were empty
>
>   * Got a message that I needed to attach a file
> 
>   * Returned to the page and selected a PDF (less than 1mb) to upload
> 
>   * Clicked upload and got a message stating "The consent forms need to be an image or in PDF format, and less than 3 MB. Please try again."
> 
>   * Went to the parental consent field and could not upload anything else
> 
>   * Logged in as an admin and that consent form was on the list to review
> 

Good catch on this! I addressed this in #4182. To simplify things, I just made it so that the upload and messaging are tied to the parental consent. If the parental consent is missing -> error message, if the parental consent is too large or the wrong file type -> error message, if the parental consent upload was successful - success message; if the media consent happened to be uploaded at the same time (and is valid), that will work; but a media consent can't be uploaded without a parental consent. Basically everything is tied to the parental consent and the media consent is just along for the ride.

**Comment by shaun-technovation** [comment]
> Good catch on this! I addressed this in #4182. To simplify things, I just made it so that the upload and messaging are tied to the parental consent. If the parental consent is missing -> error message, if the parental consent is too large or the wrong file type -> error message, if the parental consent upload was successful - success message; if the media consent happened to be uploaded at the same time (and is valid), that will work; but a media consent can't be uploaded without a parental consent. Basically everything is tied to the parental consent and the media consent is just along for the ride.

Disregard this comment, I made some more changes so the parental and media consent should be able to be uploaded in any order, separately or together. Anyhow, these changes are QA now ready to be looked at.

**Comment by dboyer** [comment]
Testing on QA:

- Left both fields blank and clicked upload, received an error message that I needed to attach a consent form
- Tried again and attached a consent form, uploaded successfully, still had an option to upload a media consent form
- Clicked upload on media consent without attaching a file, received an error message
- Tried again and attached a media form, uploaded successfully, no option to upload further forms
