### ISSUE TITLE
Previous season pending team invites still display on the mentor dashboard when you log in to the new season

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4163]
I logged in to my mentor account in the 2024 season, and 2023 team invitations still display on my dashboard. Should old team invites be deleted or marked as not answered (or some other status) when we reset the season? 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajBVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4ed1f3539c1199eaecd15d0179d615384d38211a/CleanShot%202023-08-17%20at%2011.41.39.png)

## DEPLOYMENT INSTRUCTIONS

To run the rake task on QA:
- [x] `$ heroku run bundle exec rake remove_pending_team_invites_to_mentors --app technovation-qa`

To run the rake task on Prod:
- [x] `$ heroku run bundle exec rake remove_pending_team_invites_to_mentors --app technovation`

**Comment by dboyer** [comment]
I found this as well when I logged in as mentor from a previous season. I accepted the invite and got an error message that makes me wonder if this is a known issue.

<img width="988" alt="Screen Shot 2023-08-30 at 11 13 40 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/fd248725-dd28-4141-aa04-2814077c79a9">

**Comment by dboyer** [comment]
Confirmed with PT and VET that they would prefer that previous season invites not appear on the mentor dashboard.

**Comment by viviancan** [comment]
team member status options   
`enum status: %i{pending accepted declined deleted}`

**Comment by shaun-technovation** [comment]
Here is a dataclip that should show all the mentors who have pending team invites (that were sent before July 1, 2023; a date that I choose, but can can be updated), the dataclip can show mentors from both QA and Prod (from the drop-down menu):
https://data.heroku.com/dataclips/arjeeumjsdpyriklwgcktswtpolx

For QA'ing, before the rake task is run to delete the pending invites, we can impersonate any of the mentors in that list and the pending invite(s) should be shown, then we can run the rake task and verify they're not showing up anymore.

**Comment by dboyer** [comment]
On QA, prior to running the rake task:

deb+mentor0920 has two pending invites

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelE5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ce1300830123de2371c8f596d36e36c21c7a5ac/Screen%20Shot%202023-10-16%20at%2012.55.10%20PM.png)

deb+mentor0822 has two pending invites

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem85QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87261dbd5cc8d9f402113207ec7d4f8f400dfc41/Screen%20Shot%202023-10-16%20at%2012.58.46%20PM.png)

**Comment by shaun-technovation** [comment]
I ran the rake task on QA:
```
Removing 33 pending team invites
Done
```

**Comment by dboyer** [comment]
On QA, confirmed that the pending invites are no longer listed for the two mentors. I was able to create a team with one mentor account and request to join a team with the other.

**Comment by viviancan** [comment]
Confirming this was run on PROD

```
Removing 6273 pending team invites
Done
```

Also when viewing the dataclip using the prod db the query returns 0 results
