### ISSUE TITLE
Media and consent upload issues

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4169]
Found a few issues while testing:

- [ ] I uploaded a parental consent form that was too large. I received the error message that the image was too large but could not upload an additional form as the "thank you for uploading your consent form" message was there.

![image](https://github.com/Iridescent-CM/technovation-app/assets/516764/b01a357e-0ec4-4385-bf18-0ea69188ff9b)

- [ ] I uploaded a media consent form that was too large and ran into the same issue. This was not ideal as I hadn't yet uploaded a parental consent form.

**Comment by shaun-technovation** [comment]
> I uploaded a parental consent form that was too large. I received the error message that the image was too large but could not upload an additional form as the "thank you for uploading your consent form" message was there.

Hmm, interesting, I tried to upload a large PDF for the parental consent and got the error message, but I could still upload another one. I also tried uploading a file, rejecting it, and then re-uploading a large PDF, and it still let me re-upload another one. Think I'll need the steps on how to reproduce this one.

**Comment by dboyer** [comment]
So strange! I just tried again and now I do have the option to upload again. I'll keep this open for a bit in case I can recreate the issue again but for now it seems okay.

**Comment by shaun-technovation** [comment]
> So strange! I just tried again and now I do have the option to upload again. I'll keep this open for a bit in case I can recreate the issue again but for now it seems okay.

Okay, sounds good! 👍

**Comment by shaun-technovation** [comment]
I think now that we have standalone media consent uploads (#4523), that should cover re-uploading a media consent, and #4531 will separate media consents and parental consents, which I think will ddress parental consents not being able to be re-uploaded... and I don't think we've run into this issue again, so I think we might be good regarding this issue?

**Comment by dboyer** [comment]
Agreed! Closing this issue.
