### ISSUE TITLE
BUG: Returning students, error after agreeing to terms

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4173]
After a returning student agrees to the terms it causes an error. The error is related to consent form uploads.

**Comment by shaun-technovation** [comment]
This error is being caused because the upload form is looking for a media consent, but one doesn't exist yet for returning students. The media consent gets created in the `RegisterToCurrentSeasonJob`, which is run when someone signs in. But when an admin impersonates someone, this sign-in will not run the `RegisterToCurrentSeasonJob`, which means the media consent will not get created.

We could create a media consent for this scenario which would be an easy/simple fix, but I'm wonder if its the best/proper fix for this. I'll think about it.

**Comment by shaun-technovation** [comment]
I made an easy fix for this to ensure the consent forms are created when impersonating which should address the issue here.

We could also think about updating the impersonation flow, some random ideas:
- adding a "register to current season" button that will register them to the current season
- disabling the impersonation functionality until they've been registered to the current season
- displaying a warning when impersonating when someone isn't registered to the current season

**Comment by shaun-technovation** [comment]
> I made an easy fix for this to ensure the consent forms are created when impersonating which should address the issue here.

This fix is on QA now. And a side note, I also updated the creation of the parental and media consents when registering (in the `RegisterToCurrentSeasonJob`), should be working as before, but just noting it in case we run into something.

**Comment by dboyer** [comment]
Confirmed that I can now access my dashboard when I impersonate a student from a previous season. I am prompted to agree to the data terms first.
