### ISSUE TITLE
Chapter Ambassador Judge Invites

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4179]
When a Chapter Ambassador invites a judge:
- the invite should go to the new registration flow
- after registering, the judge should get assigned to the appropriate event and teams, if necessary

**Comment by shaun-technovation** [comment]
This one is on QA 👍

**Comment by dboyer** [comment]
On QA, I created a new event and sent an invite to a judge not currently in the system. I received an email to register as that judge. The link took me to the registration page with the judge option selected. When I completed registration, I had the details about that event on my dashboard.
