### ISSUE TITLE
Support and testing feedback

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4187]
Two items from PT testing:

- [ ] Add city, state, and country as optional additional columns for media and parental consent admin pages so PT can search for consents from a particular area
- [ ] Add option to export all statuses in a single document. Currently you have to pick a status to export (pending, rejected, approved)

**Comment by shaun-technovation** [comment]
> Two items from PT testing:
> 
>   * [ ]  Add city, state, and country as optional additional columns for media and parental consent admin pages so PT can search for consents from a particular area
> 
>   * [ ]  Add option to export all statuses in a single document. Currently you have to pick a status to export (pending, rejected, approved)

I took care of these two items in #4191. 👍

**Comment by dboyer** [comment]
Closing in favor of a new issue.
