### ISSUE TITLE
BUG: Validation bug on the "As a mentor you may call me a..." field for mentors registering

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4190]
When registering as a mentor, it's possible to leave the "As a mentor you may call me a..." field blank, if this happens you won't be able to click submit on the last page. On the last page, there is no error message indicating the "As a mentor you may call me a..." field is required; you need to navigate back to that page, and then an error message will be displayed.

**Comment by dboyer** [comment]
Confirming on QA that I could not move past the page where I entered the mentor type unless I selected at least one mentor type.
