### ISSUE TITLE
Consent form improvements

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4191]
- [x] Add city, state, and country as optional additional columns for media and parental consent admin pages so PT can search for consents from a particular area
- [x] Add option to export all statuses in a single document. Currently you have to pick a status to export (pending, rejected, approved)

**Comment by shaun-technovation** [comment]
A couple of notes:
- The consent form datagrids will still have the same location issues as our other datagrids (not being able to find certain participants):
  - I tested locally and ran into an issue where I couldn't find a student from Chile, but then I updated their location to Los Angeles, CA, USA, and was able to find them on the consent from datagrid
- Exporting all statuses will have to be tested on QA, because I am unable to download the CSV exports locally

**Comment by shaun-technovation** [comment]
These changes are on QA now, ready for review.

**Comment by shaun-technovation** [comment]
> * Exporting all statuses will have to be tested on QA, because I am unable to download the CSV exports locally

I just tried a quick export on QA and all statuses were exported, so I think it's working as expected. 🤞

**Comment by dboyer** [comment]
Exports are working as expected.

@shaun-technovation I did find that if I try to add "country" as an additional column on either consent page, it causes the "something went wrong" error page. I was able to add city and state successfully. I'm wondering if adding country as an additional column doesn't work well since it's also a separate field on the page.

**Comment by shaun-technovation** [comment]
> @shaun-technovation I did find that if I try to add "country" as an additional column on either consent page, it causes the "something went wrong" error page. I was able to add city and state successfully. I'm wondering if adding country as an additional column doesn't work well since it's also a separate field on the page.

Ah, good catch! I just created a PR that should fix it. 👍

**Comment by shaun-technovation** [comment]
> @shaun-technovation I did find that if I try to add "country" as an additional column on either consent page, it causes the "something went wrong" error page. I was able to add city and state successfully. I'm wondering if adding country as an additional column doesn't work well since it's also a separate field on the page.

Should be fixed on QA now. 🤞

**Comment by dboyer** [comment]
Adding columns and exports are now working as expected!
