### ISSUE TITLE
Add club ambassador as a mentor type

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4204]
Until we add the new club ambassador user type, there is no way for VET to identify which users on the platform are club ambassadors. For this season, VET suggested adding "Club Ambassador" as a mentor type so they could filter by that on the admin participants page.

Adding to this sprint as it would be ideal to have this in place by early October.

**Comment by shaun-technovation** [comment]
The new club ambassador mentor type is now on QA. 👍

**Comment by dboyer** [comment]
Confirming on QA

- I see club ambassador as a mentor type when I register
- On the admin page, I can filter by club ambassador as a mentor type
- I can edit an existing mentor to have club ambassador as a mentor type
