### ISSUE TITLE
Update Sidekiq gem

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4205]
A high security vulnerability came in yesterday, update Sidekiq to address this: 
- https://github.com/Iridescent-CM/technovation-app/security/dependabot/164

**Comment by shaun-technovation** [comment]
This one is on QA, we'll want to keep our eye out for any bug/weirdness:

1. I had to make additional changes for this library upgrade
    - usually it's just a version bump for the security updates
2. it was a major version bump
3. I already had to fix an issue on QA after it was deployed

We'll want to keep an eye on Content and Settings, and I think the background jobs too (like mailers and exporting).

**Comment by dboyer** [comment]
On QA, I tested:

- Turning on and off different registration options which were all reflected correctly on the registration page
- I received the automated emails when I registered as a new mentor and student
- Received the email to sign the parent permission form and received emailed copies of the signed forms
- Received a request to join my team
- Turned off teams and submissions and those changes were reflected on the student dashboard
- Turned on judging which worked
- Could create a team and start a submission
- Was able to upload photos
- Was able to export participant data including additional columns I added
- Was able to export media consent form review info

I think the major pieces of the platform are good. I'll keep an eye out while testing other things.
