### ISSUE TITLE
Add option to edit or delete admin invites that are still pending

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4223]
Currently there is no way to edit or delete an admin invite at /admin/user_invitations. During testing, Program Team indicated it would be helpful to be able to delete an invite or edit the profile type. They inadvertently sent a mentor invite to a student and were trying to find a way to change it.

**Comment by dboyer** [comment]
We just ran into an issue where it would have been helpful to delete a ChA invite so a +1 to getting this done sooner rather than later.

**Comment by shaun-technovation** [comment]
> We just ran into an issue where it would have been helpful to delete a ChA invite so a +1 to getting this done sooner rather than later.

I added the ability to delete an invite in #4242, if we still want the ability to edit an invite I propose we add that functionality in another issue. 😄

**Comment by shaun-technovation** [comment]
The ability to delete an invite is now on QA. :smiley:

**Comment by dboyer** [comment]
Tested on QA:

- Re-sent a judge invite and was able to register with the invite, the invitation status changed on the admin page
- Deleted an existing invite to a mentor and it was removed from the list on the admin page
- Found the original email to the mentor (whose invite I had just deleted) with the link to register. When I clicked it, it took me to the registration page and correctly told me "the invitation is no longer valid" but gave me other registration options

I don't think we need to add an edit option since we can just delete invites
