### ISSUE TITLE
Update pending ChA account text (Remove personal staff name)

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4225]

**Comment by viviancan** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblhkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--294960441e9ca626377bb37051f5b4887af15c51/remove-name.png)

**Comment by dboyer** [comment]
Program Team requested that the text be changed to:

"Your Chapter profile is pending. Please email chapters@technovation.org for help. Note that you need to have completed all onboarding steps, including signing your MOU before getting access to your Chapter Account."
