### ISSUE TITLE
Support tasks - starting 9/28

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4228]
- [x] Postgres on Curiosity Machine will be upgraded on October 9. Before that, we need to confirm that we have a backup of the code, assets, database, etc in case the automatic upgrade goes poorly and the site is no longer available.

Misc tasks
- [x] Fix "queetions` misspelling in error message
- [x] Fix `seeds.db` syntax error
- [x] Add 2024 judging questions (just as a placeholder, we can update the actual questions later)

**Comment by shaun-technovation** [comment]
> Postgres on Curiosity Machine will be upgraded on October 9. Before that, we need to confirm that we have a backup of the code, assets, database, etc in case the automatic upgrade goes poorly and the site is no longer available.

The database is being backed up via Heroku, daily backups, a weeks worth of current ones and few older ones. And the code and assets would be in our GitHub repo. I think we're good as far as backups go. 👍

**Comment by shaun-technovation** [comment]
>  * [x]  Fix "queetions` misspelling in error message
>  * [x]  Fix `seeds.db` syntax error
>  * [x]  Add 2024 judging questions (just as a placeholder, we can update the actual questions later)

I took care of these three tasks in #4230, I merged this into QA already w/o a code review, to get CircleCI passing again (related to the 2024 judging questions) and since they're all low-risk, minimal testing things too. 👍
