### ISSUE TITLE
Registration invites - add who made the invite

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4232]
When an admin invites someone to register or a chapter ambassador invites someone, capture who made the invite.

**Comment by shaun-technovation** [comment]
There is an existing issue that is loosely related to this issue, so just documenting it here.

If an admin re-sends a chapter ambassador invite (to a judge) it will send the admin registration invite email, not the judge, RPE invite email.

This was an issue before, but now that we know who sent the invite, it's easier to spot/see this behavior. An easy fix, now that we know who sent the invite would be to only allow admin registration invites to be resent. We could also just leave it as is, or make it so that it re-sends the correct email too. Or thinking way outside the box, we could allow chapter ambassadors to see all the judges they've invited in one place and allow them to re-send the emails too.

**Comment by shaun-technovation** [comment]
This one is on QA, and only new invites will have this "sent by" info.

**Comment by dboyer** [comment]
Confirming I now see the "invited by" column on the admin invites page on QA and it's a link to the participant page for that person.

@shaun-technovation Does this change also apply to tracking which chapter ambassador invited a judge? If so, should I see that somewhere or is it just tracked in the database? I do not see it on the RPE page or on a judge's participant page.
<img width="1056" alt="Screen Shot 2023-10-16 at 10 31 42 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/b60e17f0-012e-42af-9019-eea532f40d03">

**Comment by shaun-technovation** [comment]
> Oh wait, I see that the ChA judge RPE invites appear on the main "registration invites" page at /admin/user_invitations#/. Is there a way to have another column or some indication if the invite was sent by a ChA vs an admin?

The only place the invited by info will be displayed is in the admin area. And I will add another column for the profile type of who sent the invite. 👍
