### ISSUE TITLE
Convert registation invites into a datagrid

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4233]

**Comment by shaun-technovation** [comment]
The new datagrid is on QA now. :+1:

**Comment by shaun-technovation** [comment]
> @shaun-technovation There is an issue with the exports where it is only exporting the searchable columns (registration 

Good catch with the exports, I'll fix that in #4241. 👍

**Comment by dboyer** [comment]
Confirmed on QA that exports now include all columns, including any additional columns that are added.
