### ISSUE TITLE
Add BACKGROUND_CHECK_COUNTRY_CODES to production env variables after deployment on 10/5/23

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4240]

**Comment by viviancan** [comment]
Please add the following to production env variables
`BACKGROUND_CHECK_COUNTRY_CODES` `US`

@shaun-technovation We are waiting on confirmation for the other countries. I will update once we have final answer!!

**Comment by viviancan** [comment]
Stick with only US for now

**Comment by shaun-technovation** [comment]
Thanks for adding this ticket, I added `BACKGROUND_CHECK_COUNTRY_CODES` `US` to Production!

----

<img src="https://github.com/Iridescent-CM/technovation-app/assets/58957909/9b79050d-7882-47b0-bc0d-63ed0638379a" border="2">
