### ISSUE TITLE
Registration invites cleanup and feedback

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4241]
- [x] Remove "judge Invitation URL"
- [x] Make "Register at any time" label and checkbox appear on same line
- [x] Rename "Invite users" to "Registration invites"
- [x] Remove "existing_preview" view from registration invites index page (not being used)
- [x] Add profile type of who sent the invite on registration invites datagrid (as an "additional column")
- [x] Export more info on registration invites datagrid export CSV
- [x] Add additional/help text for name field on admin registration invites section
- [x] Address "null" name when a ChA removes a judge from an RPE

**Comment by shaun-technovation** [comment]
>  * [ ]  Add profile type of who sent the invite on registration invites datagrid (as an "additional column")
>  * [ ]  Export more info on registration invites datagrid export CSV
>  * [ ]  Add additional/help text for name field on admin registration invites section
>  * [ ]  Address "null" name when a ChA removes a judge from an RPE

These four items/changes are on QA now. 👍

**Comment by dboyer** [comment]
Confirmed on QA that I see:

- Option to add the "invited by profile type" as an additional column
- Exports now include all columns
- Additional help text for name field
- I no longer see "null" in an RPE judge invite and the blank name space is filled in with "Invited Judge"
