### ISSUE TITLE
Remove old signup flows

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4243]
Remove old signup code for:
- students
- mentors
- judges
- chapter ambassadors

Leave admin signup flow.

**Comment by shaun-technovation** [comment]
One related change I made while working on this is that I updated two links in the chapter ambassador declined email. One link was going to the old mentor signup flow and the other to the old judge signup flow, I updated both of them to go to the new signup flow.

The email for reference:
https://github.com/Iridescent-CM/technovation-app/blob/261da6fa3d9a4869737504494ef12447d9282eb4/app/views/ambassador_mailer/_email_declined.en.html.erb#L6C1-L24C5

**Comment by shaun-technovation** [comment]
This one is on QA. There really isn't anything to QA, just making sure nothing is broken b/c the old signup flows have been removed, there shouldn't be any links or ways to get the old signup flow now, but that would be something to keep an eye out for.

**Comment by dboyer** [comment]
I registered a few accounts on QA to confirm everything was working as expected. Specifically, I tested:

- Registered a student account
- Registered a judge account via an admin invite
- Registered a mentor account via an expired invite that gave me options to register other ways
- Registered a judge account via a ChA RPE invite

I didn't see any unexpected issues.
