### ISSUE TITLE
Remove signup attempts

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4244]
Remove things related to signup attempts:
- Models
- Controllers
- Views
- Services
- Serializers
- Database tables
- Specs

**Comment by shaun-technovation** [comment]
This one is on QA. 👍 

A couple of things to keep an eye out for, there were still some hooks into the old signup functionality from team invites (inviting students/mentors to join a team), and I removed some more (old) signup functionality from chapter ambassador invites. Other than that, I think all the hooks into the old signup functionality have been removed, but that's basically what we want to look for (any broken functionality that used to use the old signup stuff). 😄

**Comment by dboyer** [comment]
I tested a variety of sign-up and invite options as part of #4241 and saw no issues. For this issue, I also tested:

- Mentor creates a team
- Student finds that team and sends a request to join
- Mentor receives the request and approves it
- Admin sent an invite for a ChA
- ChA was able to register and after admin approved account, was able to access their admin dashboard
