### ISSUE TITLE
Registration/invite flow cleanup and removal

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4246]
- Remove `controllers/signups_controller.rb` and associated cookies
- Check if `email_validations_controller.rb` is being used and remove if necessary
  - Remove httparty and mailgun if we're not using them
- Remove rake task functionality for inviting a chapter ambassador
- Remove unused registration routes/controllers
- Refactor mentor registration API calls for expertises list and mentor types list
  - Move to `API` namespace
  - Rename expertises -> mentor expertises
  - Remove extra `attributes` property for expertises
- Refactor registration settings and invites API calls
  - Rename and move to `api/registration` directory
  - Inherit from APIs controller

## DEPLOYMENT NOTES

For QA, remove Heroku setting/ENV for:
- [x] `COOKIES_ADMIN_PERMISSION_TOKEN`
- [x] `COOKIES_SIGNUP_TOKEN`
- [x] `COOKIES_SIGNUP_WIZARD_MODE`
- [x] `MAILGUN_PRIVATE_KEY`

For Production remove Heroku setting/ENV for:
- [x] `COOKIES_ADMIN_PERMISSION_TOKEN`
- [x] `COOKIES_SIGNUP_TOKEN`
- [x] `COOKIES_SIGNUP_WIZARD_MODE`
- [x] `MAILGUN_PRIVATE_KEY`

**Comment by shaun-technovation** [comment]
This one is one QA. 

Some things to look out for:
- There were some changes to the current registration system regarding API calls for registration settings, invites, mentor types, and mentor skills & interests
- More old signup/invite flow/functionality was removed, shouldn't have any impact, but also something to keep an eye out for

**Comment by dboyer** [comment]
Tested on QA and I was able to:

- Create a mentor with three different mentor types in a country that required a background check
- Create a mentor with different mentor skills in a country that didn't require a background check
- Create a student account and request to join a team
- Received the student invite to join my team and approved it
- As a student on a team, sent an invite to a mentor to create an account and mentor my team
- Received the mentor invite and was able to log in and create an account and saw the invite from the team
- As a ChA, invite an existing judge to judge an event
- As that judge, received the invite and logged in and saw the event once I completed training and signed the consent waiver
- As a ChA, invite a new judge to an event
- As that judge, get an email to register for an account and see the event once registered
- As an admin, send an invite for a mentor to register

**Comment by viviancan** [comment]
Confirming I deleted the following in production
COOKIES_ADMIN_PERMISSION_TOKEN
COOKIES_SIGNUP_TOKEN
COOKIES_SIGNUP_WIZARD_MODE
MAILGUN_PRIVATE_KEY
