### ISSUE TITLE
Update background check flow so that processing invite logic does not depend on the jobs table

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4247]
@viviancan to add more info

**Comment by viviancan** [comment]
Confirming this is on QA and working as expected.

I need to review the logic in the mentor debugging section. Something weird is going on with the display values for the invitation status <img width="1017" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXpwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--deb137d2eb938e8754a43a3bd653299131fabfa9/Screen%20Shot%202024-01-22%20at%202.30.10%20PM.png" alt="Screen Shot 2024-01-22 at 2.30.10 PM.png" />

**Comment by dboyer** [comment]
I went through the background check process with several mentors and it worked as expected.
