### ISSUE TITLE
Update jquery-ui-rails

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4250]
Update `jquery-ui-rails` to version `7.0` to address these security vulnerabilities:
- https://github.com/Iridescent-CM/technovation-app/security/dependabot/170
- https://github.com/Iridescent-CM/technovation-app/security/dependabot/167
- https://github.com/Iridescent-CM/technovation-app/security/dependabot/166
- https://github.com/Iridescent-CM/technovation-app/security/dependabot/165

**Comment by shaun-technovation** [comment]
This security update is on QA, no real QA'ing needed, this was a pretty minor update, just keeping an eye out for anything off would probably be good enough for this one. 👍

**Comment by dboyer** [comment]
I've been able to register accounts, create teams, etc so assuming all is good with this upgrade.
