### ISSUE TITLE
Remove global invitations

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4262]
Global invites were used as a part of our old registration system, remove them since this functionality isn't being used now.

**Comment by shaun-technovation** [comment]
Just a quick update on this one, it doesn't seem like this is being used. A quick look on production and there are only two records in the `global_invites` table, the last one was from 2019.

Here are the records:
```
[#<GlobalInvitation:0x00007f49c8854878
  id: 1,
  token: "**REDACTED**",
  status: "deleted",
  created_at: Wed, 07 Feb 2018 08:21:39.197274000 PST -08:00,
  updated_at: Thu, 31 May 2018 14:54:22.360315000 PDT -07:00>,
 #<GlobalInvitation:0x00007f49c88547b0
  id: 2,
  token: "**REDACTED**",
  status: "active",
  created_at: Fri, 01 Feb 2019 07:17:13.327223000 PST -08:00,
  updated_at: Fri, 01 Feb 2019 07:17:13.327223000 PST -08:00>]
```

Based on that, I'm fairly confident this functionality can be removed.

**Comment by shaun-technovation** [comment]
This is on QA, no explicit QA steps, just keeping an eye out for anything off/broken, since some code was removed.

**Comment by dboyer** [comment]
I sent some invites and registered accounts and had no issues.
