### ISSUE TITLE
SUPPORT 10/11/23 - 10/24/23

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4265]

**Comment by viviancan** [comment]
We received a [notice from Rae](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1697721214434789) that there were 4 bg check invites shown in the production chekr portal. This was surprising since the only country listed on production that require a bg check right now is the US. After investigating further, we discovered it was possible to manually visit the invitation URL on our platform to request an invitation. A PR has been made to fix this issue. There is also a new rake task to delete background checks by ID so we can delete the background check records for those individuals.

**Comment by dboyer** [comment]
Testing on QA:
- Went to an existing account for a mentor from Nigeria and the dashboard said no background check was needed.
- When logged in as the same mentor, went to mentor/international_background_check and was not able to access the page
- Created a new account for a mentor in Italy and went to mentor/international_background_check and was not able to access the page
- Created a new account for a mentor from India and went to mentor/international_background_check and got a message that I now had an invite from Checkr. Was able to start the background check using the link in the email.
- Created a new account for a mentor from the US and my dashboard showed the need for a background check
- On the same US account, went to mentor/international_background_check and received a message that I could not access that page

**Comment by viviancan** [comment]
This ^^ is on Prod but moving ticket back to backlog until the end of the spring

**Comment by dboyer** [comment]
Closing as access to background checks is now limited to select countries.
