### ISSUE TITLE
Create Pundit policy for viewing parental and media consents

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4277]
Ensure students can only view their own parental and media consent forms.

**Comment by dboyer** [comment]
Implementation will happen as part of #4274

**Comment by shaun-technovation** [comment]
Parental consents will get addressed in #4274. I couldn't find a way to view other student's media consent forms. The same functionality/security bug as parental consents doesn't seem to exist for media consents where someone can edit the `id` in the URL, so I think media consents are good for now.

**Comment by shaun-technovation** [comment]
This one is on QA.

To test this, I found the last parental consent `id` on QA which is `1015`, which is for this account:
https://technovation-qa.herokuapp.com/admin/participants/1509#/

While impersonating that student, I was only able to view that student's parental consent info:
https://technovation-qa.herokuapp.com/parental_consents/1015

I couldn't view any other parental consent info as a student.

As an admin (not impersonating), I could view any parental consent:
https://technovation-qa.herokuapp.com/parental_consents/XXX

If someone wants to test a new students/parental consent, just increment `1015` by one or a couple numbers until the corresponding parental consent info shows up.

**Comment by dboyer** [comment]
To test this on QA, I recreated the steps provided and saw that I could only view the parental consent for 1015 when logged in as participant 1019.

I'm not sure if it matters but I also created a new account and signed the consent letter. It should be the next in the series (1016) if you count just pending or signed forms or 1022 [if you count all registered accounts](https://technovation-qa.herokuapp.com/admin/participants?accounts_grid%5Bcolumn_names%5D%5B%5D=parental_consent&accounts_grid%5Bcolumn_names%5D%5B%5D=created_at&accounts_grid%5Bdescending%5D=true&accounts_grid%5Bdivision%5D=&accounts_grid%5Bemail%5D=&accounts_grid%5Bfirst_name%5D=&accounts_grid%5Blast_name%5D=&accounts_grid%5Bname_email%5D=&accounts_grid%5Bonboarded_judges%5D=&accounts_grid%5Bonboarded_mentors%5D=&accounts_grid%5Bonboarded_students%5D=&accounts_grid%5Border%5D=created_at&accounts_grid%5Bparent_or_guardian_email%5D=&accounts_grid%5Bparent_or_guardian_name%5D=&accounts_grid%5Bschool_company_name%5D=&accounts_grid%5Bseason%5D%5B%5D=2024&accounts_grid%5Bseason_and_or%5D=match_any&accounts_grid%5Bsuspended_judges%5D=&accounts_grid%5Bteam_matching%5D=&accounts_grid%5Bvirtual_or_live%5D=&page=1). When I put either number in the URL, however, I get a "Sorry we couldn't find that page" message, even when logged in as an admin.

**Comment by shaun-technovation** [comment]
> I'm not sure if it matters but I also created a new account and signed the consent letter. It should be the next in the series (1016) if you count just pending or signed forms or 1022 [if you count all registered accounts](https://technovation-qa.herokuapp.com/admin/participants?accounts_grid%5Bcolumn_names%5D%5B%5D=parental_consent&accounts_grid%5Bcolumn_names%5D%5B%5D=created_at&accounts_grid%5Bdescending%5D=true&accounts_grid%5Bdivision%5D=&accounts_grid%5Bemail%5D=&accounts_grid%5Bfirst_name%5D=&accounts_grid%5Blast_name%5D=&accounts_grid%5Bname_email%5D=&accounts_grid%5Bonboarded_judges%5D=&accounts_grid%5Bonboarded_mentors%5D=&accounts_grid%5Bonboarded_students%5D=&accounts_grid%5Border%5D=created_at&accounts_grid%5Bparent_or_guardian_email%5D=&accounts_grid%5Bparent_or_guardian_name%5D=&accounts_grid%5Bschool_company_name%5D=&accounts_grid%5Bseason%5D%5B%5D=2024&accounts_grid%5Bseason_and_or%5D=match_any&accounts_grid%5Bsuspended_judges%5D=&accounts_grid%5Bteam_matching%5D=&accounts_grid%5Bvirtual_or_live%5D=&page=1). When I put either number in the URL, however, I get a "Sorry we couldn't find that page" message, even when logged in as an admin.

Hmm, maybe I steered you in the wrong direction by mentioning the fiddling w/ the parental consent ids. 😊  I just checked and the most recent parental consent id is now `1049`! Which is for the "Gymnastics Class" account. I double-checked that account on QA, and looks good to me, if you wanted to try again. 😃

**Comment by dboyer** [comment]
1049 works! I think we're all good on this issue.
