### ISSUE TITLE
Create new back-end service to validate a team invite

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4283]
Similar to the back-end service to validate an invite code (from an admin registration invite), we need a service to validate a team invite.

A valid team invite (sent to either students or mentors):
- Where status is pending
- Where today's date between season start date and submission close date
- Invited by a student

**Discuss:**
What if the team invite is valid, but the team is full?

**Comment by dboyer** [comment]
If the team invite is valid but the team is full, I think we should show a message saying that team is now full and recommending the person contact someone on the team or the Chapter Ambassador for more info.

**Comment by shaun-technovation** [comment]
This one is on QA, but no testing is needed. This can get tested when more of the functionality gets completed. 👍

**Comment by shaun-technovation** [comment]
> If the team invite is valid but the team is full, I think we should show a message saying that team is now full and recommending the person contact someone on the team or the Chapter Ambassador for more info.

Just documenting that during planning we decided to let the student register in this case, and address this issue via the student's dashboard (and access/flush out more details after this functionality is completed to see what's needed). 😃
