### ISSUE TITLE
Update chart.js module

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4291]
Update chart.js to address this security vulnerability:
- https://github.com/Iridescent-CM/technovation-app/security/dependabot/7

**Comment by shaun-technovation** [comment]
This one is on QA. 👍 This was a very minor version bump, from `2.9.3` to `2.9.4`, so a pretty safe update. I think this library is used for the chart in the admin, and from what I'm seeing, looks fine/the same to me. 😄

**Comment by dboyer** [comment]
Was able to filter charts as usual on the admin side and exports also still worked.
