### ISSUE TITLE
Submission Rebrand Feedback/Discussion (catch everything)

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4297]
- [ ] Remove `sidebar_b`
- [x] Discuss navbar situation - Like what needs to be in the main navbar
- [x] Adjust spacing on submission type page so question text is nearer the answer box
- [x] Review `app_details` old styles
- [x] Word count (`submissions.scss`)
- [x]  **Error messages for submission type appear twice (above and below the field) [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFhxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a74e8c817d46ea127f7dae9d8cea332d98d79b86/Screen%20Shot%202023-11-19%20at%209.49.54%20PM.png)** _**More info below in a comment**_
- [x] Text change when a user uploads the same video twice. Please have the error text in the red banner say "Your technical and pitch videos are the same link. Please update one of the links." [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTd2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b5d97a33d39f772de3aa5db89e510053e8021bd/Screen%20Shot%202023-11-20%20at%2011.46.02%20AM.png)
- [x] The "Save this upload" button is colliding with the box for uploading a business plan [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDd2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--deddd9860e6ca912e979eb5203491a59f74f8bad/Screen%20Shot%202023-11-20%20at%2011.57.33%20AM.png)
- [x] Is there a way to have the "Your plan" section already check marked for beginner division students who don't need to complete it? 
- [x] Could we add styling to the "go back" button on the beginner division business plan page? I don't know if that text is styled as a button everywhere but without a different action button (save, confirm, etc) it looks like an error to just have the go back text [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1R2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b05c8ebfe0e892cba082b0b8748bb958761b043b/Screen%20Shot%202023-11-20%20at%201.22.07%20PM.png)
- [x] Review video URL feedback (listed below)
- [x]  submission type page spacing (listed below)
~~- [ ] If a student types in a box like the learning journey or project description and then clicks to a different section of the submission in the left sidebar without saving, they lose any content they've added to the box. I'm not sure if that was also how it worked in the old branding. Is it possible to save the changes when they click away or give some warning that their content will not be saved?~~ Documented in #4352

**Comment by viviancan** [comment]
Should we just embed the video on the page instead of having the popup?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVNnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33b5204f40405624bf8c90f4310e50af64f337b4/CleanShot%202023-11-03%20at%2012.42.46%402x.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9nQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7baedb186e2947d50a96c8620b2105890f559c16/CleanShot%202023-11-03%20at%2012.43.19%402x.png)

**Comment by viviancan** [comment]
Where should the "change your team photo" button live? I think it looks off here
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3VnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c235c485401a185b14491e83a92dcf46bd821df/CleanShot%202023-11-03%20at%2013.16.11%402x.png)

**Comment by viviancan** [comment]
Do we need the "qualifications met" sub tab like in the mockups or can it just live under the submit section 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0doQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--701461094442de77ce60c0f40fbee3b5ead47e11/Screen%20Shot%202023-11-03%20at%201.22.59%20PM.png)

**Comment by dboyer** [comment]
Added these for discussion at dev priorities meetin

**Comment by dboyer** [comment]
The question text is closer to the previous box than to the box where the person should answer the question. Is it possible adjust the spacing to add more space between the previous box and the new question?
<img width="459" alt="Screen Shot 2023-11-08 at 9 13 32 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/4d4f32b2-e98e-4f5c-afcd-3cd77945e10a">

**Comment by viviancan** [comment]
> If a student uploads the wrong video link, the button to fix it is not immediately visible. A few possible changes:
> 
> 1. Include less white space between the red error message and the blue info box.
> 2. If possible, make the "Go back" words in the red error message a link that takes the student to where they can enter the video link again
> 3. Make the "go back" button at the bottom of the page look like a button rather than text
>    [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVB2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--778f68d37a071c98a90739ca74a1b48f232433d4/Screen%20Shot%202023-11-20%20at%2011.41.01%20AM.png)

I'm unable to do #2 (`If possible, make the "Go back" words....`) without more refactoring, but did update #1 and #3. Lmk if you'd like me to work through a refactor for #2! @dboyer

**Comment by viviancan** [comment]
Moving this into QA. Still working on some of the other tasks. They will be in a separate PR

**Comment by dboyer** [comment]
@viviancan Don't worry about the refactor for now. I think the other two changes will be enough!

**Comment by dboyer** [comment]
@viviancan Several people mentioned as part of QA that they found it challenging to understand how to go back to their profile and that the nav bar was not as useful as it could be. At a minimum, it would be helpful to have a link to the Dashboard in the nav bar. A link to the curriculum might be helpful too but there may not be space for that.

**Comment by viviancan** [comment]
Moving this back to in progress as I continue to work through pending items

**Comment by viviancan** [comment]
>  Error messages for submission type appear twice (above and below the field) Private Zenhub Image

From what I can tell, this is not a bug. The error message is also displayed on the label. It appears this has been the case since 2018. I am hesitant to change the error configuration because I'm not sure where else the error message is needed on a label. 

For reference - `config/initializers/action_view.rb` 
```
  elsif tag.name == "label" || tag.name == "textarea"

**Comment by dboyer** [comment]
Checking these updates and confirmed:

- Navbar now includes a link to return to the dashboard
- Question text is closer to the correct input field on submission type and other pages
- Error message when videos are the same displays new text
- Your plan section is already checked for people in the beginner division
- Go back button styled on the beginner business plan page
- Error page for wrong video has correct spacing and go back button is styled
- Spacing on save this upload button on business plan is fixed
