### ISSUE TITLE
Update avatars on registration page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4310]
We have new avatars for the registration team including one for the new chapter ambassador registration option. Should be finalized by the marketing team by 11/15.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4310?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Avatars are [available here](https://www.dropbox.com/scl/fo/zdp9i6pi2hehdr8xdm1zw/h?rlkey=75bjva38l0w49k4m5x1uc63vc&dl=0). They should be implemented as:

Junior/Senior Division: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDcxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92290e79541b25cd3380ab270ff43f60f97bf281/Screen%20Shot%202023-11-21%20at%209.35.09%20AM.png)

Beginner Division: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVAxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9b021fdd901e5d573f9526e17e7fc6df985a8e1/Screen%20Shot%202023-11-21%20at%209.37.28%20AM.png)

Mentors: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmoxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--188764df268dc8973b8bfa0d2540f0536b1047e1/Screen%20Shot%202023-11-21%20at%209.46.54%20AM.png)

Judges: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnIxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f4fb718bfe3ac78204d9dbbe5246091c3e141b2/Screen%20Shot%202023-11-21%20at%209.47.12%20AM.png)

ChAs: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnYxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7af483254af021f95e3a296a52cfd6333e853066/Screen%20Shot%202023-11-21%20at%209.47.31%20AM.png)

**Comment by shaun-technovation** [comment]
New avatars are on QA.

**Comment by dboyer** [comment]
Confirming that I see the new avatars on QA for all five user types.
