### ISSUE TITLE
Create new "Content & Settings" for RPE settings

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4312]
In the admin area, under "Content & Settings", under "Regional Pitch Events", create new settings for:
- Creating RPEs
- Adding teams to an RPE

Create new `SeasonToggles` controls to access these new settings.
Add specs.

**DISCUSS**

The current RPE setting for "Selecting regional pitch events allowed" cannot be enabled when judging is turned on, should the new settings be the same way?

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4312?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Confirmed with program team that if judging is turned on then event creation should automatically be off.

**Comment by shaun-technovation** [comment]
This one is on QA, there should be two new admin settings, one for creating RPEs, and one for adding teams.

#4140 and #4311 are also on QA, I added some basic messaging that ChAs will see when the corresponding admin setting is disabled - either "New events cannot be created at this time." or "New teams cannot be added to events at this time." will be displayed, we can update this to be whatever.

**Comment by dboyer** [comment]
Tested on QA and both settings are now available.

When I turned judging to quarterfinals, the toggle to create new events automatically turned off and I confirmed that I was not able to add new events. The toggle to add teams to events was not automatically changed.

**Comment by dboyer** [comment]
Tested by PT and no concerns found
