### ISSUE TITLE
Add team name to email mentors receive when their team is removed from an RPE

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4318]
Currently the text says "A Chapter Ambassador has just removed you from the event: Time to Pitch" but does not mention the team name. If a mentor has multiple teams, it can be challenging to know which one was removed from the event. 

The text should be updated to read "A Chapter Ambassador has just removed your team (TEAM NAME) from the event:"

<img width="555" alt="Screen Shot 2023-11-08 at 9 47 49 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/a6469f61-3bd7-40bb-9051-c8f7e34db76a">

**Comment by shaun-technovation** [comment]
This one is on QA.

**Comment by dboyer** [comment]
Confirming that on QA that I see the name of the team I'm mentoring when I get an email that the team has been removed from an event.

<img width="572" alt="Screen Shot 2023-11-15 at 3 30 25 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/18a6b91e-b181-4fa3-b045-2e098f86a0b2">
