### ISSUE TITLE
Limit recusals to 15 per judge

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4320]
A judge should not be able to recuse themselves from more than 15 submissions. This is an attempt to decrease the chance a judge recuses themselves frequently in order to judge submissions from certain divisions or countries.

- [ ] Add logic to prevent a judge from being able to recuse themselves from a submission after 15 previous recusals
- [ ] After 15 recusals, do not get rid of the recusal button but if they click it, display a message saying: "A judge may only recuse themselves from 15 submissions. Please contact support@technovation.org with any questions."

**Comment by dboyer** [comment]
Chatted with VET and they would prefer a running count of recusals in the popup box (i.e. 3 out of 15 recusals used).

**Comment by shaun-technovation** [comment]
This functionality is on QA now. The limit is defined by `JUDGE_MAXIMUM_NUMBER_OF_RECUSALS`, I already added this to Heroku for both QA and Prod, I set it to 15. The limit/logic is dynamic, so it can be lowered to make testing easier.

**Comment by dboyer** [comment]
Tested on QA and confirmed that I could see the recusal counter and it changed as I recused myself from submissions. I was not able to add more than 15 recusals.

<img width="1486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUF1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abc1811bbdf3ce9fb01f82177bc5e9fb5233c3ee/Screen%20Shot%202023-12-04%20at%204.33.33%20PM.png" alt="Screen Shot 2023-12-04 at 4.33.33 PM.png" />


<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3d1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5da15090fd6f810c300420569749288ac95205af/Screen%20Shot%202023-12-04%20at%204.18.19%20PM.png" alt="Screen Shot 2023-12-04 at 4.18.19 PM.png" />

**Comment by shaun-technovation** [comment]
> I believe some of the values don't refresh immediately or until QA is rebuilt

Yes, that's how I understand it too; the server has to be restarted to pick up the changes. But I think updating one of the config settings should kick off a build. 

This needs to be confirmed, but I think the flow is update a QA config (which should automatically kick off a build), then wait for Slack message update in dev-robots, then it should be updated. Next time, we can keep an eye on it and see if this is the way it works.

**Comment by shaun-technovation** [comment]
> @shaun-technovation One note that I updated the max number of recusals on the Heroku variable to 3. It did not refersh on QA, but I believe some of the values don't refresh immediately or until QA is rebuilt. Just noting that here.

My hypothesis for why sometimes Heroku config settings aren't working as intended is because the config settings are being used in Vue.js. I think there is an issue with Heroku config setting changes not trickling down to Vue.js. Anywho, the recual popup is in Vue.js, so that tracks w/ my hypothesis. Just something to keep in mind for the future.
