### ISSUE TITLE
Fix style of Meet Your ChA section 

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4327]
The Meet your ChA section is sometimes distorted. Review the styles and make necessary adjustments

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlRoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31d367a694297f9e0449a2f6ee6bcd5372bd68fa/CleanShot%202023-11-16%20at%2012.58.47.png)

**Comment by dboyer** [comment]
Confirming the photos and text now look aligned on QA

<img width="1965" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c51e03547823e0578d5a4e009a422f575b73322/Screen%20Shot%202023-12-03%20at%2010.39.59%20PM.png" alt="Screen Shot 2023-12-03 at 10.39.59 PM.png" />

**Comment by viviancan** [comment]
I saw the updated meet your ChA section on prod
