### ISSUE TITLE
Include link to overview page of all scores for a team in the data export

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4328]
During judging, admins can look at all the scores for a project on a scores page - for example - /admin/score_details/557#/. The URL for that page is not included in the data export that the team uses for score monitoring as it is only accessible via /admin/scores#/ by clicking the three dots in the View column next to the project name. The score monitors then need to go into the general /admin/scores/ page, find each project, and then click the three dots to see the specific scores and other info for that project.

<img width="1149" alt="Screen Shot 2023-11-16 at 3 43 38 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/3d08c7e8-edc2-4c10-b9c2-e395d0384d7b">

It would be helpful if the URL for the scores page for each project was included in the data available via the scores export at /admin/score_exports#/. Then the score monitor could just click the link in the export (or copy and paste it into a browser) and go directly to the page without having to search for the project first at /admin/scores.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4328?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This one is on QA.

**Comment by dboyer** [comment]
@shaun-technovation I downloaded the scores from /admin/score_exports but get an error page when I try to open the links in that export. 

For example, the link for the submission "I love hedgehogs" by team "hedgehogs are awesome" has a link of /admin/score_details/951 which gives an error page. When I go into that team in the scores export page, the specific score details are available at /admin/scores/951#/ or the overall details of all scores for the project are at /admin/score_details/564#/. The score_details would be the preferable link to have but if that's not possible, let's have two columns for each URL.

**Comment by shaun-technovation** [comment]
> @shaun-technovation I downloaded the scores from /admin/score_exports but get an error page when I try to open the links in that export.
> 
> For example, the link for the submission "I love hedgehogs" by team "hedgehogs are awesome" has a link of /admin/score_details/951 which gives an error page. When I go into that team in the scores export page, the specific score details are available at /admin/scores/951#/ or the overall details of all scores for the project are at /admin/score_details/564#/. The score_details would be the preferable link to have but if that's not possible, let's have two columns for each URL.

Good catch! Should be fixed on QA now, just a simple fix I made in #4362 and merged straight into QA since it was a simple update.

**Comment by dboyer** [comment]
Confirming that I now see the correct link in the export and it took me to the score details admin page as expected!
