### ISSUE TITLE
Add score discrepancy column to scores admin page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4329]
Currently, the team completing score monitoring has to manually calculate the difference between the lowest and highest score given to a project. It would improve the monitoring process if this was calculated on the platform.

On /admin/scores#/ add a column called Score Discrepancy and the value is the difference between the highest and lowest score assigned to a project. Two caveats:

- If a project has 0 or 1 scores, this value can be blank or zero, whichever is technically easiest.
- This should only take into consideration complete scores

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4329?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
Should there be a score discrepancy for both QF and SF, separately? Or one score discrepancy for all scores?

**Comment by shaun-technovation** [comment]
> Should there be a score discrepancy for both QF and SF, separately? Or one score discrepancy for all scores?

Shouldn't be too bad either way^. Anywho, I'll pick up something else to work on until I hear back. 👍

**Comment by dboyer** [comment]
Checked with VET and they said separate columns for QR score discrepancy and SF score discrepancy.

**Comment by shaun-technovation** [comment]
Okay, sounds good, thanks!

**Comment by shaun-technovation** [comment]
🤦 🤦 🤦  It turns out we already have score discrepancies on the platform. 🤣 😭 

I completed the work for this in #4383, wrote some specs, didn't manually test it initially... but while the build was running I was testing it out; seems to be working as expected... Looking at the scores datagrid, "What's this quarterfinals range column?" Oh, it turns out, "Quarterfinals range" and "Semifinals range" is the score discrepancy! Anywho, I guess we don't need the work I did! We can rename the column if we want, but other than that, as far as I can tell it's exactly what we want already. 😊

**Comment by dboyer** [comment]
Good catch!!!! What a hidden thing. Just confirmed with VET that they didn't realize either. So two things:

1. Could you confirm that column doesn't take into consideration incomplete scores or calculate if only one score is available?

2. It looks like those columns are not included in the export available at /admin/score_exports. VET confirmed that having them exportable would be helpful. Could they be added there?

**Comment by shaun-technovation** [comment]
> It looks like those columns are not included in the export available at /admin/score_exports. VET confirmed that having them exportable would be helpful. Could they be added there?

This change is on QA, let me know if there is anything else. 👍

**Comment by dboyer** [comment]
Confirmed on QA that the range columns are now on the scores export page. I judged the same submission from two judge accounts and the column showed the correct score discrepancy. I exported the scores and saw the expected data.
