### ISSUE TITLE
Can submit additional information text with more than the allotted word count

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4334]
In the additional information section of the submissions, it is possible to submit more words than the permitted amount for each question. Steps to recreate:

1. In a submission, select Yes for all the questions in the "Additional Information" and enter more than 100 words in each box.
2. Click "Save my responses" - nothing happens - no error message but it also won't save the page
3. Change the text in one of the fields to be less than 100 words
4. Click "Save my responses" - it will save this time even though three of the fields are over 100 words

You can see this at /student/team_submissions/no-name-yet-by-gold-hunters?piece=app_details

Two potential changes:
1. Add an error message if trying to save with one or more of the text boxes having more than 100 words
2. Fix the bug that allows submitting more than 100 words in a box

**Comment by viviancan** [comment]
Confirming this is on QA
