### ISSUE TITLE
Change beginner judging scale from 3 points to 5 points

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4337]
Implement five point scale for beginner division. The scale should be:

<img width="631" alt="Screen Shot 2023-11-21 at 9 30 52 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/1f7e2a62-daaf-4620-9c63-831a0f5738de">

**Comment by shaun-technovation** [comment]
This is one QA. I tested judging a beginner submission, but scores show up in other places which I didn't test.

**Comment by shaun-technovation** [comment]
> I also saw the updated scale in these places:
> * As the total possible in the quarterfinal and semifinal average scores on the admin scores page
> * On the individual scores detail page on the admin side (/admin/score_details/558#/)
> * On the individual scores page (/admin/scores/952#/)
> * On the student scores page of the dashboard
> * On the individual scores page

Awesome, thanks for checking/QA'ing all of this! For future reference we'll know that updating the score values is pretty simple, updating them in one spot seems to update them everywhere. 👍
