### ISSUE TITLE
Add option to filter virtual scores from RPE scores on scores export page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4340]
Currently the scores export admin page (/admin/score_exports) does not have an option to filter by scores added as part of an RPE and scores added virtually. The score monitoring team needs to manually filter or separate the two score types.

It would be helpful to add a filter that allows score monitors to select whether they would like to export all scores, virtual only, or RPE only.

**Comment by shaun-technovation** [comment]
This one is on QA.

**Comment by dboyer** [comment]
Tested on QA:

- Confirmed I now see the live or virtual filter
- Chart updated based on filter
- Exports worked as expected
