### ISSUE TITLE
Add team status to admin view of RPEs

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4345]
Currently admins only see the teams that are part of an RPE, not their submission status. Add a column showing team submission status to admin event details page (i.e. /admin/events/209)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDMrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f63724d0ee28fb0ded3f426e29eaa8aabf69387b/Screen%20Shot%202023-11-22%20at%201.42.17%20PM.png)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4345?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Program Team confirmed that this would be useful so they do not need to log in as the ChA to view the info. We can proceed with this feature and do not need to add the ability for admins to add or delete teams from the admin page. They will log in as the ChA if that is necessary.

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by dboyer** [comment]
Tested on QA and confirming that I also see the team status in the new table.

<img width="1067" alt="Screen Shot 2023-12-11 at 11 25 07 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/c0bdb7a6-687f-4db0-9372-2c1404d83864">
