### ISSUE TITLE
Add judge onboarding status to admin RPE page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4346]
Currently admins only see the judges that are part of an RPE, not their ready/onboarding status. Add a column showing judge ready/onboarding status to admin event details page (i.e. /admin/events/209)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUQrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23a4b5d4753c4cf20c2bed73563d4c0465f48109/Screen%20Shot%202023-11-22%20at%201.44.29%20PM.png)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4346?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Program Team confirmed that this would be useful so they do not need to log in as the ChA to view the info. We can proceed with this feature and do not need to add the ability for admins to add or delete judges from the admin page. They will log in as the ChA if that is necessary.

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by dboyer** [comment]
I also see the judge status in the new table on the RPE admin pages and the status updates as expected.
