### ISSUE TITLE
Update color-string package

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4355]
Update the `color-string` package to address this security vulnerability:
- https://github.com/Iridescent-CM/technovation-app/security/dependabot/15

**Comment by shaun-technovation** [comment]
This one is on QA, a minor version bump here, from `1.6.0` to `1.9.1`, `color-string` is a dependency of our chart library, the chart on the admin dashboard on QA is working, so I don't think there's much more to it than that for QA'ing purposes.

**Comment by dboyer** [comment]
I'm seeing the chart on the admin dashboard on QA as well. Other admin features are also working as expected.
