### ISSUE TITLE
Allow super admins to run rake task that pushes submissions from 90% to 100%

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4363]
Each season, we run a rake task that moves any submissions that are at 89% (beginner) or 90% (junior/senior) complete to fully submitted. Details on that [process are here](https://docs.google.com/document/d/1BEHSSY9gSwKpUNJUZaVSwcixPC6HRPqNVy_33t9p7Ow/edit#heading=h.e3erfyab0n1x).

We would like to give super admins the ability to run that rake task. It may need to go on a new admin page if it doesn't make sense to put it on the submissions admin page. We should include this help text:

_Running this rake task will move all submissions that are complete and have not yet been submitted to the submitted status. This impacts submissions that are at 89% (beginner division) or 90% (junior/senior divisions)._

**Comment by shaun-technovation** [comment]
> We would like to give super admins the ability to run that rake task. It may need to go on a new admin page if it doesn't make sense to put it on the submissions admin page.

I vote for putting it on an individual submission's page, that way it's more manual, explicit, safer, just updating them one at a time; or maybe a new action button on the admin submission datagrid for the eligible ones to update them individually but more streamlined. And only displaying the button if the submission meets the % threshold. Of course we could add bulk update functionality instead for ease/convenience too.

**Comment by dboyer** [comment]
Details on the process for 2023 are [in this Slack thread](https://iridescentlearning.slack.com/archives/C02J1GU8VRA/p1682084758328529).

We will likely want to have a list of submissions that the super admin can view before running the rake task and then a post-test list for them to confirm the same projects were updated.

**Comment by dboyer** [comment]
This ticket covers setting up the functionality for having the rake task accessible to super admins on an admin page so they can run it. There may be additional tickets necessary to cover previewing a list of submissions that will be impacted before running the task and reviewing the completed list after the rake task is run.

**Comment by shaun-technovation** [comment]
This one is on QA.

A few notes, this will only be available to super admins, and only available to preform if judging is turned off,

And another thing is that the list of submissions that will get moved to published are submitted to the backend, the backend will check if they only need to submit and then publish them. There is a chance that someone edits one of the submissions listed (making them ineligible to submit) before a super admin clicks the submit button; if this happens the number displayed before hand (You are about to publish X submissions) and the confirmation message (Successfully published X submissions) would be off. In the rare case that this happens and we want to know what submission didn't get published, I added a log message for this, so we can look there if we wanted to know which submission it was.

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- I turned judging on and confirmed that the page to publish submissions had a message saying that feature was not available if judging was turned on
- I turned off judging and turned on editing submissions and confirmed that the page to publish submissions had a message saying that the feature was not available if editing submissions was turned on
- Went to the submissions page and added the column "only needs to submit" and saw four projects
- Went to the new "publish submissions" page and saw the same four projects listed
- Clicked the button to publish those four submissions and saw the page refresh to say that no submissions needed to be published
- Went back to the submissions page and confirmed that all the submissions said no in the "only needs to submit" column
- Checked the individual submissions that had previously said they needed to be submitted and confirmed they were submitted
- Received an email indicating my projects were submitted and ready for judging (for the projects linked to one of my accounts)
