### ISSUE TITLE
Update how errors from Checkr are handled and displayed on our platform 

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4372]
We had [an issue ](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1701877562176249) pop up where a mentor attempted to request a background check from checkr. They tried multiple times and it seemed as though the request worked based on success message. They never received the email for the big check. After reviewing the checkr logs, there was an error `"Last name must contain at least 2 alpha characters"`

We should review how errors from Checkr are handled and displayed to the user on our platform

**Comment by viviancan** [comment]
This was added/handled in [PR 4389](https://github.com/Iridescent-CM/technovation-app/pull/4389)

**Comment by viviancan** [comment]
Confirming the error will display on the admin portal in the mentor debugging section

**Comment by dboyer** [comment]
Confirming I see the error message field on the participant page on QA and it appears to be updating as expected.
