### ISSUE TITLE
Support ticket - Dec 6-20

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4374]

**Comment by viviancan** [comment]
Random Checkr issue with international bg checks. I am in contact with support in the engineering account.

**Comment by viviancan** [comment]
Checkr issue has been resolved

**Comment by shaun-technovation** [comment]
I sent out a password re

**Comment by shaun-technovation** [comment]
ChA assignment issue in Lagos, more info in Slack: https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1700589561832089

**Comment by viviancan** [comment]
Following up on the issue in Lagos.  I believe the issue has to do with a blank chapter ambassador intro. Locally, once filled in, the ChA assignment seems to be working as expected. I will follow up in the original slack thread with more details!

**Comment by dboyer** [comment]
After the ChA filled in the program intro, they are now appearing as the chapter ambassador for students in that area.
