### ISSUE TITLE
Invite token to student or mentor lets them join the team to which they were invited

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4376]
Related to #4284

For existing invites or invites sent between registration and submission closing, the student or mentor accessing the invite (also between registration closing and submissions closing) should automatically see the team to which they are invited on their dashboard after the click the link in the invite to create an account or view a team invite on their existing account. NOTE: person has to register with the same email address as the address where they received the invite.

See reported issue below.

I then turned registration and team forming off and logged in as the student [Ivy Bean](/student/teams/627) and did not see the pending invite on my dashboard. I went to my inbox as that mentor and was able to register an account but did not have any info on my dashboard about joining that team.

I tried it again as a student on the team [Storm Systems](https://technovation-qa.herokuapp.com/admin/teams/638#!students). I invited a mentor and then turned off registration and forming teams. I was able to register as that mentor but it did not say I was connected to the team Storm Systems. When I checked the Storm Systems admin page, it says the mentor invite is still pending but I have a [mentor account registered with the same email address](https://technovation-qa.herokuapp.com/admin/participants/1582#/).

<img width="765" alt="Screen Shot 2023-12-06 at 11 01 46 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/0ba1891a-e2a5-40ce-ba01-8b1c384c0c8e">

<img width="896" alt="Screen Shot 2023-12-06 at 11 05 20 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/e829f91c-670b-4829-ac4b-f26cea76fc05">

_Originally posted by @dboyer in https://github.com/Iridescent-CM/technovation-app/issues/4284#issuecomment-1843104010_

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4376?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
I believe this issue is related to the disabled/enabled feature functionality. As debmentor1206b I was able to see the invite to the team locally when I altered the disabled feature logic. This leads to believe that adding in new admin toggles for invites is the way to go!

**Comment by dboyer** [comment]
We believe this work is not needed as we confirmed with PT that invites should only be visible if the "forming teams allowed" toggle is on.
