### ISSUE TITLE
Add link to chapter map in Meet Your Chapter section

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4384]
Some chapter ambassadors are not displaying for students in certain regions. While we look into that as part of #4367, we should add a link to the chapter map as a way to direct students to other chapters.

Text: View other nearby chapters on our chapter map!
Link: https://www.google.com/maps/d/viewer?mid=1iNTtG9RMwX6S8qyQiWq27JYIIU6dYkd4&hl=en_US&ll=16.477516426989585%2C-30.326061099999947&z=2

**Comment by shaun-technovation** [comment]
This one is also on QA.

**Comment by dboyer** [comment]
Confirmed this is on QA. One note that it is not showing if the student only has a message that there is no ChA in their area.
