### ISSUE TITLE
Create Salesforce sandbox environment

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4386]

**Comment by dboyer** [comment]
Sandbox info sent via email

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4386?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Noting that there is a new sandbox with a full copy of the live environment. We should set up that sandbox in order to have a more accurate testing environment. Sasha sent details via email.

**Comment by shaun-technovation** [comment]
The sandbox is hooked up to QA. All new accounts created on QA should get a new account added in Salesforce. One way the new account can be found in Salesforce is by:
- Clicking Accounts in the top nav bar
- On the next page, click the drop-down triangle/carrot and select "New This Week" and you should see the new account there

The login details for the sandbox are in 1Password.

**Comment by dboyer** [comment]
I logged into the Sandbox and confirmed that I saw the new account I just created on QA listed in the "new this week" section. It was associated with the correct email address.

**Comment by shaun-technovation** [comment]
> And lastly to use the refresh token, our Restforce calls had to be updated to point to test.salesforce.com (instead of production, which is used by default), which I had to make a small code change for.

Regarding this, just noting that I added a Heroku setting for `SALESFORCE_HOST`, which points to `test.salesforce.com` for QA and `login.salesforce.com` for Production.
