### ISSUE TITLE
Add link to partners page in footer

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4387]
One of our grants requires we recognize them on any sites to which they contributed development funds. In the footer, let's add the word Partners and link to https://www.technovation.org/corporate-partners/.

<img width="1206" alt="Screen Shot 2023-12-13 at 2 48 52 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/fb4ce592-789e-41cc-a402-512754823aa4">

**Comment by shaun-technovation** [comment]
Just noting that I only updated the application rebranded footer, not the old footer; we can update that one too of course if we want to.

**Comment by shaun-technovation** [comment]
This one is on QA. 👍

**Comment by dboyer** [comment]
Confirming I see the link in the footer
