### ISSUE TITLE
Create technical infrastructure for a ChA invite to enter an onboarding process

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4391]
Currently, ChAs receive an invite to create an account. They then enter a pending state where their account has to be approved by an admin. After that approval, they may need a background check if based in the US but otherwise have access to all ChA features.

After a ChA registers, we should remove the pending state (#4226) and have them enter an onboarding process similar to the flow for students, mentors, and judges. Onboarding will include four specific tasks that must be completed.

**Comment by dboyer** [comment]
Note that this covers just the process of registration and then going to the dashboard. There will be field adjustments in the registration process as part of a different ticket.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4391?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
As a part of #4392 I made it so that a newly registered ChA will get redirected to the new dashboard/onboarding flow.

I also removed most/all? of the "pending" status functionality from a ChA's point of view, i.e. a ChA *shouldn't see any pending messages or have a "pending" dashboard. The admin view still has the pending/approve/decline status functionality though; and as we were talking on standup yesterday, maybe we don't need this functionality (and I think that can be done in another ticket). Anywho, I think this ticket might be done..? 🤔

**Comment by dboyer** [comment]
I spoke with PT and confirmed that pending should not be part of the ChA registering/onboarding process at all. They currently only use pending to make ChAs inactive between seasons. When we opened the platform early this summer, only the ChAs in the countries that were running the program over the summer moved to "active" while the others stayed as pending.

PT is fine with using a different system than "pending" for the process of having some ChAs able to start onboarding if we want to try a different approach.

**Comment by shaun-technovation** [comment]
>They currently only use pending to make ChAs inactive between seasons. When we opened the platform early this summer, only the ChAs in the countries that were running the program over the summer moved to "active" while the others stayed as pending.

Ah, so, it sounds like setting someone to inactive/pending was used to restrict access to their dashboard, which will become "Chapter Admin Activity".

We have #4407 for an admin setting to restrict access to "Chapter Admin Activity", but this would be global access (the way the ticket is described now). And we have #4419 to restrict access until a ChA is fully onboarded. But it sounds like we want to restrict access per chapter/ChA, which we don't have a ticket for.

If I'm understanding correctly:
- We need a ticket to restrict access to "Chapter Admin Activity" per chapter or ChA
- We need a ticket to remove the pending/approved/declined statuses from ChAs
- #4407 doesn't seem necessary now (or maybe it can be reworded)
- For this ticket (#4391), there doesn't seem to be any work remaining left to do

**Comment by shaun-technovation** [comment]
The work for this one was done as a part of #4392.

**Comment by shaun-technovation** [comment]
The redirect and removing the pending status (just from the ChA's perspective) is on the new Preview environment.

**Comment by dboyer** [comment]
Tested on preview and was able to send an invite to a new ChA. I registered as that new ChA and went directly to my dashboard to begin onboarding, without any pending step.
