### ISSUE TITLE
Create front-end ChA dashboard

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4392]
Currently chapter ambassadors only have access to an admin style dashboard. As part of integrating the onboarding process, we would like to separate out their onboarding and personal info onto a dashboard that is similar to the one for students and judges. All chapter admin activity will remain available on the existing admin dashboard.

This issue covers just creating the dashboard and having the ChA view an initial set of onboarding tasks. Access to the admin activity is not available until onboarding is completed.
<img width="605" alt="Screen Shot 2023-12-19 at 9 38 15 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/8df3cd84-cc83-4627-aab5-7942e9555e1c">

**Comment by dboyer** [comment]
This ticket covers only creating the overall framework - energetic containers, left sidebar, menu headers, etc. It does not cover any of the content pieces in the sidebar.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4392?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This one can be looked at/reviewed on the new Preview environment.

**Comment by dboyer** [comment]
Confirming on the preview site that I can see the new dashboard, switch to mentor mode, and switch to the admin activity pages.
