### ISSUE TITLE
Integrate Checkr background checks for all chapter ambassadors

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4393]
The first step of the ChA onboarding process should be integrating a Checkr background check. This should follow a similar flow as the check for international mentors in that ChAs view some initial information on the platform and request an invite to start the process but otherwise do everything via Checkr. A few notes:

1. The background check should be the first step listed in the onboarding process. However, ChAs can access the training onboarding step even if they do not have their check completed. They cannot access the MOU or enter chapter profile information.

2. Ideally, all ChAs including US based ones will complete the process via Checkr. We do not want US based ChAs to go through the check process on the platform as it is currently available to US mentors. Instead they should go through the off-platform process.

3. We will likely want the check to be good for several years so we'll need to figure out how that works.
  
<img width="536" alt="Screen Shot 2023-12-19 at 9 46 57 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/ed443ffe-6588-4dc6-80c9-989ff7c4ed10">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4393?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
Noting that there is some weird styling in the side nav due to the "tw-active" class. This was captured in #4464

**Comment by viviancan** [comment]
This is on preview-qa. Confirming I was able to request a bg check invitation as a US based and nonUS based chapter ambassador. I also tried requesting an invitation when the last name was 1 character and I could not request the invitation. I saw the error message directing me to update the last name.

**Comment by viviancan** [comment]
@dboyer This is due to the new sidenav work that was recently merged into preview. I am going to update the background check link with the new sidenav and you should be able to access the background check as normal.

**Comment by viviancan** [comment]
Actually, I just saw that Shaun is already working on that in #4495!

**Comment by shaun-technovation** [comment]
>> I created two new ChA accounts on preview via invites. I was able to create the accounts and set locations in the US. When I click on the background check tab, nothing shows up. The accounts were /admin/participants/1608#/ and /admin/participants/1607#/

> @dboyer This is due to the new sidenav work that was recently merged into preview. I am going to update the background check link with the new sidenav and you should be able to access the background check as normal.

Ah yes, sorry, I removed/broke the old sidenav behavior to make the sidenav dynamic in #4466. And then I split out the work to add the sidenav to the background check flow in #4495, this work is now in the PR #4501, so hopefully it will all get fixed soon. 😄

**Comment by shaun-technovation** [comment]
The sidebar and background check flow should be working on Preview now.

**Comment by dboyer** [comment]
Confirming I can now access the background check tab via the sidebar. I was able to request a background check as a US based ChA and received an invitation to Checkr. I was able to fill out the info and submit my background check.
