### ISSUE TITLE
Link team building toggle to ability for students and mentors to register when registration is closed

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4396]
Related to #4376.

We need to add a toggle that would allow invitations to students (both already registered on the platform and not registered on the platform) to join an existing team. Proposal to add to the Teams and Submissions content setting page a new toggle called "Allow invites to join existing team." 

This toggle will allow students already on the platform to register on the platform and join your team even if student registration and forming team toggles are off.

<img width="417" alt="Screen Shot 2023-12-20 at 1 17 20 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/d149ef93-89ef-4cb4-ab09-4ab7627d0e8d">

**Comment by dboyer** [comment]
Follow-up tasks:
- Add helper text for all toggles
- Map out how toggle changes interact with season calendar
- Determine if any toggles should automatically impact this new invite toggle

**Comment by dboyer** [comment]
We are trying to support this scenario:

- We turn off student and mentor registration on March 13. We leave "forming teams allowed" turned on.
- Because "forming teams allowed" is turned on, students who are already registered on the platform can send invites to unregistered or registered students and mentors
- The unregistered students and mentors receive the invitation and are able to register even though registration is turned off
- Once registered, the students and mentors can see the team invite and accept or decline it
- When submissions are closed on April 24, no one can register even with an invite

This is essentially the student/mentor version of an "anytime" invitation. We do not think another admin toggle control for this is necessary since invites will only work if forming teams is toggled on. HOWEVER - students and mentors should not be able to register (even with "anytime" invitation) if judging is turned on.

We've confirmed that if "forming teams" is toggled on, students can invite existing students and mentors on the platform to join a team. Students should only be able to send or accept an invite if "forming teams" is toggled on.

**Comment by dboyer** [comment]
We think the only needed change is to link "register anytime" functionality to the team building toggle.

Add help icon text next to team building toggle that says: When the "forming teams allowed" box is checked, students can invite people to register and join the team even if registration is closed.

**Comment by shaun-technovation** [comment]
This one is on QA, I just added some rough help text for the admin setting that we can tweak/iterate on.

**Comment by dboyer** [comment]
On QA. I tested:

- Turned off all registration but kept the boxes checked for "forming teams allowed" and "team submissions are editable"
- As a student already on a team, I invited a new student who was not on the platform
- Registered as that student and saw the invite to join the team and accepted it
- As that new student, invited a mentor not on the platform to join the team
- Registered as that mentor and saw the invite to join the team and accepted it

- I then turned off "forming teams allowed" and kept registration turned off
- Logged in as an existing student on a team and did not see the functionality to invite a new student
- Logged in as an onboarded student without a team and did not have the ability to create or find a team

I believe this is working as desired.

[As Vivian noted](https://github.com/Iridescent-CM/technovation-app/pull/4413#issuecomment-1889928713), this is dependent on the student or mentor entering the exact same email address as it was on the invite. We may want to pre-fill the email address as part of a separate issue.

**Comment by shaun-technovation** [comment]
> [As Vivian noted](https://github.com/Iridescent-CM/technovation-app/pull/4413#issuecomment-1889928713), this is dependent on the student or mentor entering the exact same email address as it was on the invite. We may want to pre-fill the email address as part of a separate issue.

That was a known issue:
https://github.com/Iridescent-CM/technovation-app/issues/4284#issuecomment-1796422724

There was also an issue to address this, but looks like we decided it's wasn't needed?:
https://github.com/Iridescent-CM/technovation-app/issues/4308

Anywho, maybe we need a new ticket to prefill and lockdown the email address during registration. 🤔
