### ISSUE TITLE
Research SurveyMonkey and Google Forms integrations

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4404]
As a part of ChA onboarding, ChAs need to take a quiz via SurveyMonkey (or maybe another means?). We need to know if they completed the survey.

Do we need to know their score or just that they completed it?

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4404?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
A few updates:

- Currently, PT does not check the score. ChAs get access if they have completed the test.
- ChAs do see the questions they have gotten wrong and what the correct answer is

It would be important to have a way to display the correct answers - either via email or on that training tab after the quiz is completed.

**Comment by shaun-technovation** [comment]
I setup a sample quiz in SurveyMonkey and was able to embed it on our platform.

I was able to embed it via an iFrame so we can pass variables to SurveyMonkey (to let us know who took the survey in SurveyMonkey), in the screenshot below the "name" column is being populated from our platform:

<img width="1708" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd042QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6952f6bf88fbd64641088198abe304346063dc06/surveymonkey%20results.png" alt="surveymonkey results.png" />

----

> ChAs do see the questions they have gotten wrong and what the correct answer is

For SurveyMonkey, a summary is displayed at the end showing the correct answers.

> It would be important to have a way to display the correct answers - either via email or on that training tab after the quiz is completed.

We could definitely make a page and/or send out an email for this.

> We know when the form is completed

I haven't played with the API yet, but looks like there is a webhook specifically for when a survey is completed:

> A survey response is completed (‘response_completed’)

https://surveymonkey.com/developer/api/v3/#api-endpoints-webhooks

I could also see the "completion" part working similarly to the background checks where the page would need to be manually refreshed to see completion status.

I could see the next steps for this spike being:
- Working on the completion part
- Working on styling/presentation with the iframe
- Spike on Google Forms

**Comment by shaun-technovation** [comment]
Moving this one to the Review/QA column, #4513 will address the Google Forms spike. And then we can work on next steps depending on which option we go with.
