### ISSUE TITLE
Add profile editing features to new ChA dashboard

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4411]
Related to #4392.

Need to add the standard "My Profile" editing options available to students and judges in the new dashboard layout:

- Basic info
- Email
- Password
- Location

<img width="470" alt="Screen Shot 2024-01-10 at 2 30 26 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/6cec6665-0a67-4322-a22b-927d821ba9db">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4411?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This is on the new Preview environment.

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- Successfully changed all fields on the basic information tab
- Successfully updated location
- Successfully updated password
- I was not able to reset my email address.

@shaun-technovation When I clicked on the "change email" tab, I entered my current password and the new email address I wanted to use and clicked "change email." I never received an email message to confirm the email change. I know the change took effect, however, as the new email was listed on the admin participant page for that ChA and I was not able to login when I tried using the old email.

Image uploads were not working and I added #4459 for that.

**Comment by shaun-technovation** [comment]
> @shaun-technovation When I clicked on the "change email" tab, I entered my current password and the new email address I wanted to use and clicked "change email." I never received an email message to confirm the email change. I know the change took effect, however, as the new email was listed on the admin participant page for that ChA and I was not able to login when I tried using the old email.

Hmm, I tried this on Preview and I received the email to confirm the new email address (I also confirmed emails are getting sent out on Preview), and I was able to confirm the new email address. Which account were you running into issue with? 🤔
