### ISSUE TITLE
Restrict access to "Chapter Admin Activity" until ChA is fully onboarded

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4419]
Disable (or hide?) the "Chapter Admin Activity" link until after a chapter ambassador is fully onboarded.

**Comment by dboyer** [comment]
Slight preference to disable rather than hide so that the ChAs know the additional functions will be available at some point and we don't have to field questions about where to go.

**Comment by dboyer** [comment]
Closing as a duplicate of #4689
