### ISSUE TITLE
Create chapter model in the database

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4433]
Split off from #4406 

The chapter model should have the following fields. Some of these fields are currently on the ChA profile and will need to be moved from there.

- Non-profit affiliation
- Location
- Program name
- Short summary
- Links to local program sites

Admins will be able to edit all fields. ChAs will be able to edit all fields except for non-profit affiliation and the country level location for the chapter.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4433?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This one is on the new Preview environment, but there isn't anything to test yet, not until we work on more of the GUIs related to chapters.
