### ISSUE TITLE
Spike: Research build and deployment options for long-running chapter work

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4438]
Look into options including:

- Workspaces
- Blue/green deployment

**Comment by shaun-technovation** [comment]
I created a new Heroku app environment:
https://technovation-preview-28bd069458f9.herokuapp.com/

I'm going to refer to this new environment as "Preview".

The preview environment has an import of QA data, so all QA data is also on the preview environment; but moving forward things added to QA would just stay on QA and things added to Preview would just stay on Preview.

I think things are working as expected on Preview, but that's something to keep an eye out for. Also, only the bare minimum Heroku add-ons have been added, so Preview is missing Airbrake, Scout, Papertrail. etc.

There is an associated branch called `preview`, all ChA/chapter-related work should get merged into the `preview` branch and that is what will be on Preview.

Lastly, this is a new Heroku app which is on the basic plan, we'll want to keep an eye on the monthly price, I think it should be reasonable ~$20 a month I'm guessing. But this approach/environment could be used for any future work that needs reviewing before going to QA/Prod; or we can remove it after we finish the ChA/chapter work too.

**Comment by shaun-technovation** [comment]
Also, noting that some things are shared between QA and Preview. The Postgres database is **not** shared, but Filestack and Redis (which controls the admin Content & Settings) is currently shared between QA and Preview; we can change this of course, I was just trying to setup the basics in this ticket, if we like this approach we can definitely fine tune and iron out the details.

**Comment by dboyer** [comment]
I was able to log into the new preview environment with my QA super admin account and invite a new ChA. I registered as that ChA and see my profile page!

We'll want to think about a frequency for rebasing this branch with QA so that it stays up to date. But in general, this is looking good!

**Comment by dboyer** [comment]
Work complete.
