### ISSUE TITLE
Separate chapter ambassador location from chapter location

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4439]
Currently, a ChA's location is set by an admin and serves as the default location for the chapter. We need to have ChA's have their own personal location (similar to any other user type) and the chapter location will be part of the new chapter model.

ChA location is something they will set on their profile, similar to other user types.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4439?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This one is on the Preview site now, ChA's setting location details should be the same now as students and judges.

**Comment by dboyer** [comment]
Confirmed on QA that I could:

- change the location from the My Profile tab when I logged in as a ChA
- logged in as an admin and saw the new updated location on the ChA participant page
- as an admin, I could edit the ChA's location and the new location appeared on their profile page
