### ISSUE TITLE
Migrate ChA data to new Chapter model

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4442]
For each chapter ambassador, we want to:
- create a new chapter for them
- associate the chapter ambassador to the new chapter
- from the chapter ambassador's profile, copy:
  -  `program_name` to the new chapter's `program_name` field
  - `intro_summary` to the new chapter's `program_summary`field
- from the chapter ambassador's account, copy:
  - `city` to the new chapter's `city` field
  - `state_region` to the new chapter's `state_region` field
  - `country` to the new chapter's `country` field

**Comment by dboyer** [comment]
Need to create spreadsheet of ChA profiles on preview and update list with needed fields/fake org names to test migration on preview and have full set of data to use.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4442?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This new rake task is on Preview. 

This rake tasks needs two pieces of information for each ChA/chapter, we need:
- the chapter ambassador's ID
- the chapter's organization name

The rake task will create a chapter with the provided organization name and then look up the chapter ambassador based on the ID, migrate the relevant data, and associate the chapter ambassador with this new chapter.

We can ran this rake task as many times as we want, but it will only work for chapter ambassadors who do not already belong to a chapter.

I created a basic dataclip to get the chapter ambassador IDs:
https://data.heroku.com/dataclips/gkuuwbhaizlawgzvxblnoiipezrr

And here is a note on how we run the rake task:
`bundle exec rake convert_chapter_ambassadors_to_chapters["ID;ORG NAME,ID;ANOTHER ORG"]`

**Comment by shaun-technovation** [comment]
I ran this on Preview for Red Rose, it worked as expected (the data that was migrated makes it a slightly confusing since the intro summary and program have the same content):

It imported `intro_summary` and `program_name` from the `ChapterAmbassadorProfile` (and location, not shown, from their account):
```
#<ChapterAmbassadorProfile:0x00000001105a9810
 id: 109,
 organization_company_name: "Flowers Inc",
 job_title: "Flower",
 account_id: 1408,
 status: "approved",
 created_at: Mon, 18 Sep 2023 15:53:29.752877000 PDT -07:00,
 updated_at: Tue, 19 Sep 2023 08:38:40.425539000 PDT -07:00,
 bio: "I love flowers!!! They are beautiful!",
 intro_summary:
  "Give your participants a short introduction to your regional program. Use up to 280 characters, or about the lengt
h of a tweet.\r\n\r\nGive your participants a short introduction to your regional program. Use up to 280 characters,
or about the length of a tweet.\r\n\r\n",
 secondary_regions: [],
 program_name:
  "Give your participants a short introduction to your regional program. Use up to 280 characters, or about the lengt
h of a tweet.",
 chapter_id: nil,
 organization_status: nil,
 phone_number: nil>
```

Command I ran:
`heroku run bundle exec rake convert_chapter_ambassadors_to_chapters["109;Widgets Inc"] --app technovation-preview`

We can run this again on Preview w/ more ChAs to test more too. 👍

**Comment by dboyer** [comment]
I've saved details for three additional ChAs. I'm good with running the rake task on preview @shaun-technovation

**Comment by shaun-technovation** [comment]
> I've saved details for three additional ChAs. I'm good with running the rake task on preview @shaun-technovation 

I misspoke at our planning meeting, I said this rake task would run for all chapter ambassadors, but it will actually only run for specific chapter ambassadors. It only runs for the chapter ambassadors we specify. 

So, to run this, the rake task needs:
- a chapter ambassador id
- organization name of the chapter they should be associated with

And for each ChA id and organization name provided, it should:
- create the new chapter (with the given organization name)
- associate the ChA to the chapter
- copy city, state, country, program name, and intro from the ChA to the new chapter

**Comment by dboyer** [comment]
@shaun-technovation Ah got it. In that case, the following IDs and org names could be tested on Preview:

- 1360# and Technovation Galway
- 1354 and Technovation Motunui
- 1577 and Technovation Egypt

**Comment by shaun-technovation** [comment]
I ran the rake task on Preview.

```
Created new chapter Technovation Galway
Associated Deb Chachacha to Technovation Galway
Created new chapter Technovation Motunui
Associated Moana Pua to Technovation Motunui
Created new chapter Technovation Egypt
Associated Peter Pierre to Technovation Egypt
```

Here is the command I ran:
`$ heroku run bundle exec rake convert_chapter_ambassadors_to_chapters["106;Technovation Galway,120;Technovation Motunui,117;Technovation Egypt"] --app technovation-preview`

Also, just noting for when we run this on QA/Production, the rake task needs chapter ambassador ids (not account/participant ids).

And here is the chapter ambassador profile information for each account for reference:

Account 1360:
```
irb(main):017:0> Account.find(1360).chapter_ambassador_profile
=>
#<ChapterAmbassadorProfile:0x00007fa07ce9bdc0
 id: 106,
 organization_company_name: "Chapter Choo Choo",
 job_title: "Train Engineer",
 account_id: 1360,
 status: "approved",
 created_at: Mon, 07 Aug 2023 08:14:16.976886000 PDT -07:00,
 updated_at: Wed, 10 Jan 2024 11:41:57.149534000 PST -08:00,
 bio: "I am a chapter ambassador and also an engineer who likes to drive trains.",
 intro_summary: "Program introduction",
 secondary_regions: [],
 program_name: "Test",
 chapter_id: nil,
 organization_status: nil,
 phone_number: nil>
```

Account 1354:
```
irb(main):018:0> Account.find(1354).chapter_ambassador_profile
=>
#<ChapterAmbassadorProfile:0x00007fa07cb4e438
 id: 120,
 organization_company_name: "Pacific Ocean",
 job_title: "Wayfinder",
 account_id: 1354,
 status: "approved",
 created_at: Tue, 23 Jan 2024 11:59:38.827574000 PST -08:00,
 updated_at: Tue, 23 Jan 2024 11:59:53.601879000 PST -08:00,
 bio: "I like the ocean. I like the ocean. I like the ocean. I like the ocean. I like the ocean. I like the ocean. I like the ocean.",
 intro_summary: nil,
 secondary_regions: [],
 program_name: nil,
 chapter_id: nil,
 organization_status: nil,
 phone_number: nil>
```

Account 1577:
```
irb(main):019:0> Account.find(1577).chapter_ambassador_profile
=>
#<ChapterAmbassadorProfile:0x00007fa07cc03090                                                        ▀
 id: 117,
 organization_company_name: "ChA",
 job_title: "ChA",
 account_id: 1577,
 status: "approved",
 created_at: Sun, 19 Nov 2023 18:39:18.709103000 PST -08:00,
 updated_at: Sun, 03 Dec 2023 19:37:08.615280000 PST -08:00,
 bio: "This is a test account. This is a test account. This is a test account. This is a test account. This is a test account. This is a test account.",
 intro_summary:
  "We are a fantastic Technovation chapter. Please join us in being fantastic. You will learn a lot with us and it will be exciting and fun. We are a fantastic Technov
ation chapter. Please join us in being fantastic. You will learn a lot with us and it will be exciting and fun.",
 secondary_regions: [],
 program_name: "Technovation Chapter",
 chapter_id: nil,
 organization_status: nil,
 phone_number: nil>
```

**Comment by dboyer** [comment]
Finally looked at these and confirming that the ChAs are associated with chapters as expected and the intro summary on the ChA account is now the intro summary on the chapter account.

**Comment by shaun-technovation** [comment]
I added #4652 to run this rake task on Production. I think we're good regarding this issue - the rake task works as expected (and we can always run this rake task again on Preview too), I'm going to move this one to Done.
