### ISSUE TITLE
Migrate chapter links

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4444]
After #4442 is complete existing chapter ambassador's will be associated to a new chapter. Migrate their existing chapter links to their new chapter instead of having them associated to the chapter ambassador.

**Comment by shaun-technovation** [comment]
I wrote a rake task that will convert chapter ambassador links to chapter links:

`bundle exec rake convert_chapter_ambassador_links_to_chapter_links`

Old chapter ambassador links can be viewed by visiting this page as a chapter ambassador:
`https://technovation-preview-28bd069458f9.herokuapp.com/chapter_ambassador/introduction/edit`

**Comment by shaun-technovation** [comment]
I ran this on Preview:
`heroku run bundle exec rake convert_chapter_ambassador_links_to_chapter_links --app technovation-preview`

Here are the results:
```
Converted 5 links for Peter Pierre
Converted 0 links for Peter Pierre
Converted 0 links for Peter Pierre
Converted 0 links for Peter Pierre
Converted 0 links for Peter Pierre
```

I'm not sure why Peter is listed so many times. We can run it again if we convert/assign more existing chapter ambassadors to chapters via the rake task in #4442.

**Comment by dboyer** [comment]
If we want to try this again, we could migrate this ChAs. I am giving the participant ID since I don't have ChA ID:

- /admin/participants/1415#/ to Tech for the Environment (/admin/chapters/15#/)

**Comment by shaun-technovation** [comment]
> If we want to try this again, we could migrate this ChAs. I am giving the participant ID since I don't have ChA ID:
> 
>  - /admin/participants/1415#/ to Tech for the Environment (/admin/chapters/15#/)

I added this ChA^ to a new chapter called "Tech for the Environment 2"; it has to be a new chapter, not an existing one for the rake task. We could add GUI functionality to add a ChA to an existing chapter though.

Adding the ChA to a new chapter:

```
$ heroku run bundle exec rake convert_chapter_ambassadors_to_chapters["111;Tech for the Environment 2"] --app technovation-preview

Created new chapter Tech for the Environment 2
Associated Quercus Alba to Tech for the Environment 2
```

Converting the ChA's links:
```
$ heroku run bundle exec rake convert_chapter_ambassador_links_to_chapter_links --app technovation-preview

Converted 1 link for Quercus Alba
```

**Comment by dboyer** [comment]
Confirming that I see one link for Quercus Alba now as a link for the Tech for the Environment 2 chapter
