### ISSUE TITLE
Allow admins to create new chapters

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4445]

**Comment by dboyer** [comment]
Add a button to create a new chapter to the Chapters admin page added in #4446. That button will take admins to a page where they set up a new chapter.

The only info required to create a chapter is the Organization Name. This is not the "program name" which the ChA will add when they register. Admins may also add a country in which the organization is working but it is not required. 

After adding the chapter, the admin should see a confirmation page which includes a link to invite a new ChA to that chapter. See screenshots below.

QUESTION: Should we use the program name as the chapter name? I'm assuming so as the organization name may be different than the program name but need to confirm that with PT.

<img width="1224" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNndlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51e3b6f5b7fb95c86159713eb9a77f0146e4e716/Screen%20Shot%202024-02-01%20at%2012.22.51%20PM.png" alt="Screen Shot 2024-02-01 at 12.22.51 PM.png" />

<img width="1246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWdlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a9826d8c2a56ea1100d8f31821ccc519a22cca1/Screen%20Shot%202024-02-01%20at%2012.36.48%20PM.png" alt="Screen Shot 2024-02-01 at 12.36.48 PM.png" />

**Comment by dboyer** [comment]
NOTE: This ticket will only cover setting up a chapter without a location. Connecting a chapter to a location will be covered in other tickets.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4445?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
This is on preview but I think we may have an issue with the preview db. It appears that some of the recent migrations have not run on preview. For example, the chapters table is missing, which is why if you try to view the admin chapters page you will get an error

**Comment by shaun-technovation** [comment]
> This is on preview but I think we may have an issue with the preview db. It appears that some of the recent migrations have not run on preview. For example, the chapters table is missing, which is why if you try to view the admin chapters page you will get an error

I fixed this issue and documented it in our support issue #4490. I was able to create a new test chapter on Preview, nice work on this!

**Comment by viviancan** [comment]
This has been resolved! Thank you Shaun 💯

**Comment by dboyer** [comment]
Tested on preview and was able to:

- See the button to add a new chapter on the chapters page
- Add a new chapter by entering the organization name
- When I go to the chapters page, I see the newly added chapter with the organization name filled in
