### ISSUE TITLE
Allow admins to view all chapters

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4446]

**Comment by dboyer** [comment]
Set up a Chapters admin page that includes a list of all chapters, link to the chapter detail pages, and a button to set-up a new chapter.

Filters would include name, season, and country. Additional columns would include organization, number of students, number of mentors, number of teams.
<img width="929" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk1lQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e512176ab2cdc234c45dd6fc7ffe78d7b26ab1b9/Screen%20Shot%202024-02-01%20at%2012.18.29%20PM.png" alt="Screen Shot 2024-02-01 at 12.18.29 PM.png" />

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4446?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Confirming on preview that I see:

- The new chapters page at /admin/chapters
- The chapters shown in a data grid
- A button to view more details about the chapter
- The filter for organization worked as expected
