### ISSUE TITLE
Placeholder - Add background check status to ChA profile in admin portal

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4457]

**Comment by dboyer** [comment]
I see the background check status on the ChA participant page on QA.

**Comment by viviancan** [comment]
Confirming I see the bg check stats for ChA on prod

**Comment by viviancan** [comment]
@shaun-technovation Moving this back into code review since I discovered a bug related to the work. [This PR ](https://github.com/Iridescent-CM/technovation-app/pull/4540) addresses the issue

**Comment by viviancan** [comment]
This is on prod
