### ISSUE TITLE
Support uploading profile photo from new ChA dashboard

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4459]
When testing the new ChA dashboard on the Preview site, I was not able to upload a profile photo. The filestack image picker modal loaded and I was able to select an image, but I did not receive a confirmation message and the updated image did not appear.

**Comment by shaun-technovation** [comment]
I have a feeling this is an issue w/ the new Preview environment not being setup/connected to Filestack correctly. 🤔

**Comment by viviancan** [comment]
Tested this on preview. I was able to upload a profile photo as a mentor, student, and ChA. I updated the allowed domains on filestack and in the AWS s3 cors config.

**Comment by shaun-technovation** [comment]
Awesome! Thanks for taking care of this one, Vivian!!

**Comment by dboyer** [comment]
Also confirmed on preview that I could upload profile photos to a ChA, mentor, judge, and student account.
