### ISSUE TITLE
ChA rebrand CSS 

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4464]
Adding a catchall for any rebrand issues related to ChA 

- [x] Review tabs.css. The .tw-active class is causing some weirdness with the ChA tabs on the dashboard side nav. See image below

**Comment by viviancan** [comment]
<img width="1678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUFTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4120ab62fd5a76d8a0a5e25a4a444647d4a317eb/CleanShot%202024-01-30%20at%2015.25.43%402x.png" alt="CleanShot 2024-01-30 at 15.25.43@2x.png" />

**Comment by shaun-technovation** [comment]
This should be fixed on Preview now.

**Comment by dboyer** [comment]
Confirming that I'm no longer seeing this alignment issue in the checkboxes.

<img width="1318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlIyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8571e1930c5f67a84b67ffa3853221ae208c74d/Screen%20Shot%202024-02-20%20at%209.04.35%20PM.png" alt="Screen Shot 2024-02-20 at 9.04.35 PM.png" />
