### ISSUE TITLE
Add "chapter ambassador" admin page

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4465]
This would let an admin see a chapter ambassador's onboarding steps/progress, similar to how an admin can see the status of a student's onboarding steps.

**Comment by dboyer** [comment]
A rough wireframe is available on Mural. I think we'll want this as a separate page but we should also consider if there's a way to reuse the participants page. Maybe as part of adding profile type specific filters.

<img width="911" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b8b5700765a9ffce7b2b244369e1864e027a381/Screen%20Shot%202024-02-01%20at%2011.52.08%20AM.png" alt="Screen Shot 2024-02-01 at 11.52.08 AM.png" />

**Comment by dboyer** [comment]
Similar to the separate admin page for judges, we need an admin page to view chapter ambassador info.

Search filters can include:

Name or email
Season
Organization
Country
Onboarding status
For onboarding status, we need to know if they've completed each of the steps:

Background check
Training
MOU
Additional columns should include:

Participant ID
Gender
Phone number

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4465?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
Confirming this is on preview. I did not include the country filter since there are potential updates to location. We will also need to add onboarding status once that work is complete!

**Comment by dboyer** [comment]
Confirming on preview that I can:

- See the ChA admin page
- The filters work as expected
- Add additional columns
- Export the data as a CSV
- Click the View button to go to the participant page
