### ISSUE TITLE
Only allow super admins to publish submissions when "editing submissions" is turned off

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4469]
It would be nice to only enable super admin to publish only needs to submit submissions (#4363) when editing submissions is turned off.

**Comment by shaun-technovation** [comment]
@dboyer This is one that I'd like to bring into the next iteration, since it would be nice to have and easy to knock out. Do we still needed to confirm that the publish functionality should only be available when "editing submissions" is turned off? I think that would be the only thing holding this one up.

**Comment by dboyer** [comment]
I checked with PT and they confirmed that pushing submissions from 90 to 100% should not be possible unless editing submissions is turned off.

**Comment by shaun-technovation** [comment]
This one is on QA. With #4363 and this one, super admins should only be able to publish submissions when judging and "editing submissions" is turned off.
