### ISSUE TITLE
Admin ability to edit chapter details

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4473]
Depends on #4472 

Admins should have the ability to edit chapter details on the chapter page without needing to impersonate a ChA. All changes should be tracked in the activity log.

**Comment by shaun-technovation** [comment]
Adding the blocked tag to this one until #4691 is completed. Legal contacts used to be fields on the chapter, but I removed them (and now those fields are a part of a new table), it will be easier to work on this issue after that work gets merged in.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4473?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This is on Preview. I added basic editing abilities for a few chapter fields (one field missing is location, I thought that would be better to add after we implement the new location system).

I also added #4754 for the ability to track the updates.

**Comment by dboyer** [comment]
Tested on preview and confirmed I could update the following fields as an admin:

- Chapter name
- Chapter summary
- Public map visibility
- Org headquarters location

I confirmed I could see the edits when I logged in as a ChA and as the ChA, I could still edit the fields without any issues.
