### ISSUE TITLE
Security: Update axios node module

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4477]
Update the axios node module to address these security vulnerabilities:
- https://github.com/Iridescent-CM/technovation-app/security/dependabot/173
- ~https://github.com/Iridescent-CM/technovation-app/security/dependabot/176~
  - This one didn't get addressed

**Comment by shaun-technovation** [comment]
This one is on QA. to test this locally, I tried registering as a mentor, the second page of the registration form displays the mentor's skills & abilities and mentor types, both of which get fetched via axios.

**Comment by shaun-technovation** [comment]
Also, just noting, I thought this was going to close two dependabot alerts, but it only addressed one of them, I updated the issue description accordingly.

**Comment by shaun-technovation** [comment]
I found an issue with this one, the judge recusal form isn't working (it can't submit to the back-end). I tried it on the commit before the axios update and it's working fine. The axios update was pretty major, the version we were using was from Sept 2014, we basically did 10 years of updates for axios! 😱 😭

**Comment by dboyer** [comment]
Confirmed on QA that the axios update issues related to adding location, submitting data terms, and submitting a judge recusal are now working. I also tested the original scenario and was able to register a mentor account, add mentor types and mentor skills, and also update those fields via the profile. All worked as expected.
