### ISSUE TITLE
Preview: Add "sync now" button for super admin in the background check admin page

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4483]

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4483?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
Also, the background check sync will only sync background checks from this season

**Comment by viviancan** [comment]
Confirming this is on PREVIEW

**Comment by dboyer** [comment]
On preview, I clicked the "sync now" button and then received an email for one of my accounts saying that my check was cleared. I believe this is working as expected.
