### ISSUE TITLE
Add new judging recusal reason

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4485]
In the box where judges can state they don't want to judge a submission, we need to add a new reason for recusal: "Content doesn't belong to the team"

It can go before "Other." It should appear anywhere in the admin where the other reasons for recusal appear.

![Screen Shot 2024-02-05 at 12 52 24 PM](https://github.com/Iridescent-CM/technovation-app/assets/516764/06eab66c-a603-49c2-83b8-e2aacffb4867)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4485?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Recusal reason also listed on score details (i.e. /admin/score_details/560#/)

**Comment by shaun-technovation** [comment]
I picked this one up thinking it would be straight forward, but it turns out the axios update in #4477 broke the recusal functionality (submitting the form to the back-end).

**Comment by shaun-technovation** [comment]
This one is on QA.

**Comment by dboyer** [comment]
Confirming that I see the new recusal reason on QA. I also see the new recusal reason on the judge admin page.

<img width="544" alt="Screen Shot 2024-02-13 at 7 30 57 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/570548ae-0292-4c4b-8ad9-855c5b6b8e49">

<img width="461" alt="Screen Shot 2024-02-13 at 7 32 17 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/86a9500d-977c-4485-b7a0-bc7030525f79">
