### ISSUE TITLE
Update button styles for student confirming attendance at an event

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4488]
The modal when students select to attend an event is using old button styles

<img width="827" alt="Screen Shot 2024-02-07 at 11 25 50 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/5ea9a61b-718b-477c-95f9-9597bbefdf6e">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4488?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
@dboyer Are we ok with updating this color in all profiles? I searched for the condition where the green button displays and it seems that it is mostly related to the following activities:
- RPE selection
- join requests/team member invites (For students & mentors)

In the mentor profile
<img width="1238" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e195114f2f6364a0d1b21c704f6d172f243b2fb2/Screen%20Shot%202024-02-13%20at%205.52.13%20PM.png" alt="Screen Shot 2024-02-13 at 5.52.13 PM.png" />

**Comment by dboyer** [comment]
Yep, totally fine to update it in all profiles.

**Comment by dboyer** [comment]
Confirming I see the updated button color on QA when confirming attendance at an event.

<img width="1524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE4yQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3ce4d4336e03a52d21ecc5434649b772ef4a480/Screen%20Shot%202024-02-20%20at%209.47.57%20PM.png" alt="Screen Shot 2024-02-20 at 9.47.57 PM.png" />
