### ISSUE TITLE
Support ticket - Feb 8 - 21

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4490]

**Comment by shaun-technovation** [comment]
Just documenting that on Preview, when I rebased against QA, I mixed up the database migrations order.

To fix this, I reordered them as follows (so they're in the same order as the file names):
```
 ('20231216014610'),
-('20240206173222'),
-('20240208195151');
 ('20240202203152');
 ('20240202203636');
+('20240206173222'),
+('20240208195151');
```

then I manually ran the migrations on Preview:
`heroku run bundle exec rails db:migrate VERSION=20240206173222 --app technovation-preview`
`heroku run bundle exec rails db:migrate VERSION=20240208195151 --app technovation-preview`

Everything seems to be working as expected now. 🤞

**Comment by shaun-technovation** [comment]
> Just documenting that on Preview, when I rebased against QA, I mixed up the database migrations order.
> 
> To fix this, I reordered them as follows (so they're in the same order as the file names):
> 
> ```
>  ('20231216014610'),
> -('20240206173222'),
> -('20240208195151');
>  ('20240202203152');
>  ('20240202203636');
> +('20240206173222'),
> +('20240208195151');
> ```
> 
> then I manually ran the migrations on Preview: `heroku run bundle exec rails db:migrate VERSION=20240206173222 --app technovation-preview` `heroku run bundle exec rails db:migrate VERSION=20240208195151 --app technovation-preview`
> 
> Everything seems to be working as expected now. 🤞

Thinking about this more, I'm wondering if we're going to run across this issue on production. Next time I pull down production data, I'll test it against the preview branch and see what happens, we might have to manually run the migrations, we'll see. 🤔
