### ISSUE TITLE
Bug with setting location from chapter ambassador registration process

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4498]
Currently the location fields are still a step in the initial ChA registration process. I sent an admin invite to a new ChA and when I tried to register, I couldn't get past the location step. I entered several different locations and clicked save and nothing happened. I'm assuming the work done to move location to the ChA profile is somehow not aligning with setting the location during registration.

**Comment by dboyer** [comment]
Actually this may be a bug. I can't update location at all on preview for any user type - ChA, mentor, or student.

**Comment by shaun-technovation** [comment]
> Actually this may be a bug. I can't update location at all on preview for any user type - ChA, mentor, or student.

Good catch! This is related to the axios upgrade in #4477. I have a fix for it already in #4499. 👍

**Comment by dboyer** [comment]
Confirming I can now edit locations on both QA and preview.
