### ISSUE TITLE
New pending chapter ambassadors don't appear in participant list 

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4500]
I added two new chapter ambassadors on preview via invites ( /admin/participants/1608#/ and /admin/participants/1607#/) and accessed the dashboards for both accounts. 

When I set the profile type to "chapter ambassador" on the admin participants page (/admin/participants), neither of those accounts is in the list of results. I'm wondering if it's because both of those accounts say on their participant page that they are "pending" and that search page only shows approved accounts.

I know we removed the pending status in #4226 that prevented ChAs from completing registration, but I wonder if it's still set somewhere that's impacting the search results page.

**Comment by shaun-technovation** [comment]
Good catch on this one, pending ChAs should be appearing in the participants list on Preview now.
