### ISSUE TITLE
Create placeholder page for ChA training

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4516]
This covers creating the page where ChA will access training materials and the quiz. Actual embedded survey tool will be in a later issue.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4516?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
confirming this is on preview

**Comment by dboyer** [comment]
I also see the placeholder page on QA!
