### ISSUE TITLE
Support ticket - Feb 22 - Mar 20

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4517]

**Comment by shaun-technovation** [comment]
CircleCI was breaking trying to download Chrome:

> Installed version of Google Chrome is 116.0.5845.96 
> 116.0.5845.96 will be installed
> curl: (22) The requested URL returned error: 500

From this [commit](https://github.com/Iridescent-CM/technovation-app/commit/513fc58c32f92e20c8fcb0b0f96d72707729b652#diff-21b1fe66043572c76c549a4fc5f186e9a69c330b186fc91116b9b70a4d047902L119), there was this comment:

>  \#  TODO: remove when chromedriver downloads are fixed

I removed the two lines in that commit^ and CircleCI is passing now. But I'm realizing now that I removed the `browser-tools/install-browser-tools` step too, which might not have been necessary. Anywho, I guess it's something to keep in mind if we run into CircleCi issues; but as of now CircleCI seems to be working as expected.

**Comment by viviancan** [comment]
Added separate ticket in TG docs private repo to handle the Checkr support issue

**Comment by viviancan** [comment]
VC - When trying to connect to heroku qa I got this error locally - `No such file or directory`
I attempted to update heroku cli and could not due to outdated xcode. I attempted to update xcode but could not due to older MacOS. I spent a good chunk of time this afternoon backing up my local machine, upgrading to Sonoma MacOS, updating Xcode, and then reinstalling Heroku cli. I think everything is up to date now. I was able to connect to QA via CLI.

**Comment by shaun-technovation** [comment]
We got a support request to restore a deleted account [via Slack](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1710430236145229). I looked into this and determined it *can* be done with the gem we're using, but we don't have it setup properly to do this. Currently some data gets soft-deleted and other data gets permanently deleted (like their profile info, and perhaps other data); in order for us to be able to fully restore an account, all associated data would need to be soft-deleted. Anywho, to resolve this, they are just going to create a new account. 👍

**Comment by viviancan** [comment]
[Support request](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1710427643287059) that was actually a bug. More info on the ticket [#4574](https://app.zenhub.com/workspaces/technovation-605271851956b1000ec2f24d/issues/gh/iridescent-cm/technovation-app/4574) **BUG: If a current student on a team is converted to a mentor, Admin are unable to manage that team (platform errors out)**
