### ISSUE TITLE
Issues with adding adding new judges to an event

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4520]
ChAs have the ability to send an invite to a judge to register on the platform and be associated with an event. I was testing that feature and while it works, there are lags and delays that a regular user would likely not be able to get past. My testing process was:

- Log in as a ChA and go to the events tab
- Create a new event or go to an existing event and click the icon to add judges
- Click the "Add judges" button and see the pop-up modal where you can pick a judge from the list or enter an email address
- Enter an email address to send an invite for someone to register on the platform
- Click done
- The invited email address does not appear on the list of judges
- Click "add judges" again to open the modal. The invited judge's email is now in the drop-down list
- Select that email and click done
- The email appears on the list of judges with a checked box to send an invite
- Click to send the invite
- Open the modal again to add a new judge and see the old judge's email address there.
- There's no way to add a new judge

This screen capture shows the whole process - https://drive.google.com/file/d/1O5PAZgCcN7T8_51mgjzS9Z7dfWPC8vj2/view?usp=drivesdk

**Comment by viviancan** [comment]
Confirming this is on QA and working as expected

**Comment by dboyer** [comment]
Confirmed that I could add a judge to an event on QA. When I searched, the list populated possible judge choices based on my search terms. I was also able to invite a new judge without the delayed screen issue reported earlier.
