### ISSUE TITLE
Small judging changes

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4521]
A few things that would be helpful to complete before judging starts:

- [x] Increase the minimum word count on judge recusals to 5 words (currently it is 3)
<img width="470" alt="Screen Shot 2024-02-22 at 12 10 16 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/64f94a9c-f08a-4e86-bd1c-85839a26df55">

- [x] The last paragraph of the email to new judges should read: You are now all set to start scoring [link to dashboard], when quarterfinals judging opens ion May or when semifinals judging opens in June.

The text for the [email is here](https://docs.google.com/document/d/1FyE37IlvNex7mqImDB2ssBGHPQPkCpnw8VgLvn7lmCI/edit#heading=h.1x90dinr14il). All edits other than the one from Rae in the last paragraph were made earlier in the season.

- [x] Add dates to the welcome dashboard. Currently it says "Welcome to the online judging portal for the first round of Technovation Judging!" After that sentence, it would be helpful to add "This round is open May 1 - 28, 2024." It would be helpful to also include the dates for the semifinal round (June 4-18).

The dates should be config variables on the server so we could have them update based on that variable. 

- [x] Change the link for the  "For tips on judging this category, click here." that appears at the top of each submission. It should link to https://docs.google.com/presentation/d/1ZZ8eLTDhIkR8tDcZjR77J2JlnUb8nkX6MElNyGk5XyM/present

<img width="518" alt="Screen Shot 2024-03-05 at 10 45 54 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/b82017eb-a703-4d82-9593-efd9ecb995bb">

- [x] On the judge dashboard in-between rounds, remove the line that says "If you finished scoring 5 submissions or more, you will be invited to judge in our semifinal round starting on June 4th."

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4521?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- Minimum word count for a recusal is now 5 words
- The text "For tips on judging this category, click here." now links to [the Google doc](https://docs.google.com/presentation/d/1ZZ8eLTDhIkR8tDcZjR77J2JlnUb8nkX6MElNyGk5XyM/present?slide=id.g2b4da927ad9_0_23480)
- The between rounds dashboard does not include the text stating you can judge semifinals if you judged five quarterfinals submissions
- I see the dates on the judge dashboard.

@viviancan  It does not look like the text change worked for the email to new judges. It should read "You are now all set to start scoring [link to dashboard], when quarterfinals judging opens in May or when semifinals judging opens in June." The email I got had the old text:

<img width="530" alt="Screen Shot 2024-03-14 at 2 54 41 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/d8b9670f-2bf4-4764-aba0-f4a49afe9536">

**Comment by viviancan** [comment]
@dboyer Ahh, looks like there are 2 emails with that text (new judges and returning judges). I missed the new judge email! Did you get that email for a new judge? 

Making the update now!

**Comment by dboyer** [comment]
Yep! for a new judge

**Comment by viviancan** [comment]
@dboyer Text is updated for a new judge on QA

**Comment by dboyer** [comment]
Confirmed the new text is now available in the email to new judges.

@viviancan If possible, there's one last text change that VET would like for the screen in between rounds. Currently it says:

"Semifinals will take place from June 4th - June 18th, the number of scores you finish will determine what judge certificate you receive."

It should ideally say: "the number of scores you finish in both rounds will determine what judge certificate you receive"

**Comment by dboyer** [comment]
Confirming I see the additional text change on QA.
