### ISSUE TITLE
Indicate primary contact for a chapter

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4532]
Each chapter should have one chapter ambassador who is identified as the primary contact and whose info is displayed to the students when selecting a chapter. This issue covers adding a new "primary contact" field to the chapter model.

The ChA for a chapter will choose who is the primary contact as part of the chapter ambassador onboarding. The visual interface for selecting the primary contact is covered under #4611.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4532?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Confirming I now see the primary contact option.

**Comment by shaun-technovation** [comment]
@viviancan Just curious, did the migrations for this run as expected when this got deployed to Preview? (I think this might be the first thing merged into Preview that had a migration since #4581.)
