### ISSUE TITLE
Remove DOB from checkr invitation flow

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4538]

**Comment by viviancan** [comment]
Refs #4537

We will most likely need to remove this from the `create_checkr_candidate` method in the checkr API client 
`dob: candidate.date_of_birth`

**Comment by dboyer** [comment]
Tested on preview and was able to request a background check invite. When I clicked the link, the DOB was not filled in so confirming we are no longer sending that field. I was able to complete the form. The check cleared as expected.
