### ISSUE TITLE
Display chapter ambassadors on chapter admin page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4542]
The work done in #4447 connects a ChA to a chapter. This issue covers displaying that ChAs name in the ambassador field on the chapter admin page. The name should link out to the participant detail page for that ChA.

<img width="591" alt="Screen Shot 2024-02-29 at 10 22 31 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/d7c20c0e-b14c-4eaa-ac39-682ca4d37a6f">

**Comment by shaun-technovation** [comment]
I created a basic list to display chapter ambassadors on the chapter show page, this is now on Preview.

**Comment by dboyer** [comment]
Confirming on QA that I can see the chapter ambassador section on the chapter page now.

I tried to add a new ChA to test that their name appeared under the chapter section and was not able to get the ChA registration process to work. I added all the data and clicked submit and the page just reloaded. I'll test with other registration types.

**Comment by dboyer** [comment]
Checked again and ChA registration is now working as expected and the ChAs appear as listed on the chapter page.
