### ISSUE TITLE
Remove ChA company name and personal summary

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4543]
In #4515, the company name and personal summary fields were removed from the chapter ambassador registration process. We also need to remove these fields from
- the admin area
- the chapter ambassador's profile section
- the chapter ambassador required onboarding step requiring the personal summary

**Comment by dboyer** [comment]
Confirmed on preview that the company name and personal summary were removed from:

- the participants admin page
- the ChA profile
- the ChA registration process
