### ISSUE TITLE
Add ChA "status with organization" and phone number fields to ChA edit profile and admin ChA pages

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4548]
In #4515 , we added "Status with Organization" and phone number to the registration process for new chapter ambassadors, we need to add these new fields to the chapter ambassador's edit profile section and to the admin chapter ambassador section.

**Comment by dboyer** [comment]
Confirming that on preview I now see the status with organization and phone number fields on both the ChA profile and on the admin participant page.

I am able to edit the fields when logged in as a ChA. I cannot edit them as an admin unless I impersonate the account. If needed, we'll add the ability to edit directly in the admin interface as part of a later ticket.
