### ISSUE TITLE
Preview: Add field to store selected chapter on student profile

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4553]
Currently, students are dynamically associated with chapters and the chapter is not stored on the student table. We would like to change that so the chapter the student selects is saved and stored as something associated with their profile.

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by dboyer** [comment]
Confirming I see the chapter field on the participant admin page.

<img width="773" alt="Screen Shot 2024-03-13 at 11 39 06 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/18b58a3a-dfa0-4cb0-bb7f-65b83e4ffdb8">
