### ISSUE TITLE
Add program summary and location to chapter details page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4562]
Relates to #4472 

Add program summary and location to chapter details page

<img width="349" alt="Screen Shot 2024-03-06 at 1 52 11 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/66e280f0-6524-4475-9475-9f1607abdc2f">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4562?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This minor update is now on Preview.
