### ISSUE TITLE
Preview: Add "assign to chapter" in admin portal for student profiles

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4566]

**Comment by viviancan** [comment]
[This is in a single PR](https://github.com/Iridescent-CM/technovation-app/pull/4565) with #4553

**Comment by viviancan** [comment]
Confirming this is on preview

**Comment by dboyer** [comment]
Tested on preview and confirmed:

- New field on student participant page is visible
- I can assign the student to a chapter
- I can change the student to a different chapter
