### ISSUE TITLE
Add judge registration question

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4571]
Add the following question to the judge registration process:

"As a judge you may call me a...."

- Educator
- Industry professional
- Postsecondary student
- Parent
- Technovation alumnae

Judges should be able to select multiple options.

**Comment by shaun-technovation** [comment]
This is on QA now.

**Comment by dboyer** [comment]
Confirming that I now see the judge type question in the registration process on QA and I am able to select multiple judge types when registering.
