### ISSUE TITLE
Display and edit judge type

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4573]
Connected to #4571 and #4572 

1. The judge type should appear on the basic information tab of the judge's profile. Judges should be able to edit it there.

<img width="1188" alt="Screen Shot 2024-03-14 at 2 09 06 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/cd96e917-fcd6-43a6-86b9-e468bcfdf70c">

2. The judge type should appear on the participant admin page (like at /admin/participants/75#/). Admins should be able to edit it there.

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- As a judge, I could add or edit my judge type on my profile
- As an admin, I can view the judge types on the participant's admin page and edit them

@viviancan I'm not sure if we can do anything about it, but if a judge profile has a mentor profile, I'm never able to see the judge types anywhere on the admin. I can see them on the pariticipant side but on the admin side, the profile only shows the mentor specific fields. The judge is returned in the list of search results if you search by judge type, even if they have a mentor profile. Screenshare here to show what I mean: https://drive.google.com/file/d/11IXiZTKzG3tE1Rk5dUy3Zfz3RknRmNii/view?usp=drivesdk
