### ISSUE TITLE
Create page for MOU section

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4591]
This covers creating the page where ChA will access info about the MOU and the link to Docusign. The link to Docusign will be created after completing the research in #4403.

This page should include links to the following documents. Ideally, the user will need to check a box by each document before they can click the button to go to Docusign. Wireframe is below.

- Non-Disclosure Agreement
- Brand Guidelines
- Social Media Admin Agreement
- Social Media Policy
- Technovation Code of Conduct
- Reviewed Safety Page

<img width="943" alt="Screen Shot 2024-03-20 at 11 15 28 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/ea886c3f-2001-48a0-bdd3-bd89e40e855a">

**Comment by viviancan** [comment]
Confirming this is on preview

**Comment by dboyer** [comment]
I see the MOU page, the text, and the checklist of documents!

@viviancan I'm not sure if it matters since we haven't implemented the click functionality yet but the code of conduct is pre-checked for any ChA when I log in.
<img width="1184" alt="Screen Shot 2024-03-28 at 9 35 12 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/06b7ace3-76f5-4c05-9ab0-2efdb55adfc0">
