### ISSUE TITLE
Ask judges to confirm they are over 18

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4596]
Similar to the work completed in #4537, we should remove birth date as a required field for judges and instead display a box saying  "I confirm that I am 18 years or older."

We should keep date of birth as an optional field and add some info text saying "We use date of birth as a way to gain insight into who volunteers to judge. This info is optional."

**Comment by shaun-technovation** [comment]
Basic functionality for this is on QA now.

**Comment by dboyer** [comment]
Confirming that I see on QA:

- The new check box to confirm the user is over 18
- The birthdate field is optional
- I can register just checking the box and also can register if I check the box and provide a birthdate
- As an admin, I can remove the birthdate for a judge and the account still works
- As a participant, I can remove the birthdate from my profile and save the updates

**Comment by shaun-technovation** [comment]
Just FYI, this is on Preview (which also has the ChA over 18 work), I had to resolve some conflicts merging both pieces of work together, I think I did it right, but just a heads up in case someone notices something not working as expected.
