### ISSUE TITLE
Add user interface where ChA can select which ChA is the primary contact for the chapter

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4611]
Depends on #4610 and #4532 

This issue creates the front-end for the new field set up in #4532. The field should be part of a new Visibility section in the Public Info tab of the Chapter Profile page. The drop-down list will be populated with the names of all the chapter ambassadors assigned to the chapter.

<img width="871" alt="Screen Shot 2024-04-02 at 9 09 21 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/fd348485-b895-4045-affe-0f5017ee0e1d">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4611?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
Confirming this is on PREVIEW. I set a primary contact for [this chapter](https://technovation-preview-28bd069458f9.herokuapp.com/admin/chapters/12#/)

Things to check
- All ChAs for that chapter should appear in the drop down list
- You should be able to select/save a primary contact
- If there is not a primary contact, this value should display as "Please select a primary contact" on the ChA public info view
- If there is not a primary contact, this value should display as as "Not set" on the admin chapter view

**Comment by dboyer** [comment]
Testing on preview and confirmed:

- I could set the primary contact when logged in as the ChA
- If I logged in as a ChA for a chapter with multiple ChAs, both ChA names were options in the primary contact drop-down
- As an admin, see the primary contact listed for the chapter
<img width="189" alt="Screen Shot 2024-04-16 at 12 17 10 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/03f7b8aa-7d9f-4346-8423-bf7acf625400">
