### ISSUE TITLE
Make Public Info page editable

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4616]
Any fields on this page can be edited by any chapter ambassador for that chapter.

UI that has a button to update/edit information and then it goes to an edit form.

Fields that can be edited by the ChA:

- Chapter Name
- Program Summary
- Program Links (may need be split into a separate issue)
- Visibility (added in #4611)

NOTE: Organization cannot be edited by the chapter ambassador, only by an admin on the backend.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4616?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
Confirming this is on QA

We still need to add regional links, primary contact selection, and map visibility

**Comment by dboyer** [comment]
Tested on preview and confirmed:

- As a Cha, I could not edit the organization
- I was able to edit the chapter name and program summary fields
- As an admin, I see the updated fields on the backend

@viviancan Not sure if it's a big deal, but I was able to save the program summary with more than the listed number of characters. I didn't see any error message and it doesn't look like there were errors anywhere but flagging that just in case it matters.
<img width="808" alt="Screen Shot 2024-04-16 at 12 26 57 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/fe4ab76b-306a-4028-a1e7-c1620681fe5e">

**Comment by viviancan** [comment]
@dboyer I will log this as bug. I just tried on QA and it looks like this is the same behavior! 👀
