### ISSUE TITLE
New ChA account prompted for chapter location but cannot enter it

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4626]
As part of testing #4608, I ran into the following issue:

- Went to a chapter admin page and used the email invite section to invite a new ChA to that chapter (/admin/chapters/12)
- Clicked the link in the invite email and created a new account for that ChA, making sure to use the email address I sent the invite to (/admin/participants/1620)
- The ChA dashboard loaded at the Chapter Profile tab with the Location Details section open. There's a prompt to complete location but no way to do so
- I cannot access any other tabs including the dashboard for ChA onboarding as it won't let me leave this screen

I reproduced the same issue with the participant /admin/participants/1621

<img width="1292" alt="Screen Shot 2024-04-11 at 10 31 32 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/f81350df-8ad9-4b7f-baa8-1e4a64c15f6c">

**Comment by viviancan** [comment]
Confirming the fix is on QA (@dboyer)

**Comment by dboyer** [comment]
Confirming I no longer run into this issue on preview.
