### ISSUE TITLE
Add UI so ChAs can select to be or not to be visible on the map

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4642]

**Comment by dboyer** [comment]
Mockup of the UI for opting-out of appearing on the map

<img width="758" alt="Screen Shot 2024-04-16 at 12 08 06 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/e3bc1f0f-721e-4aad-8a5a-80e83c4b034a">

**Comment by viviancan** [comment]
Note: this also includes migration for chapter table (something like visibile_on_map)

**Comment by viviancan** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4642?planning-poker) with Zenhub @shaun-technovation

**Comment by viviancan** [comment]
Confirming this is on PREVIEW

I tried with [this chapter](https://technovation-preview-28bd069458f9.herokuapp.com/admin/chapters/12#/). By default they were set to "display on map." I logged in a a ChA and was able to set it to "No, do not display." I verified the text on the ChA Pubic info page, the chapter details page, and also the filter on the chapter datagrid.

**Comment by dboyer** [comment]
Tested on preview and confirmed:

- the default status is "yes"
- As a ChA, I could change the status to no and see it was updated
- As an admin, I can see the status update on the chapter admin page
- As an admin, I can add the "visible on map" filter on the chapter admin page
- As an admin, I can export the list of chapters and see the column for map visibility with true/false values listed correctly
