### ISSUE TITLE
UI for editing legal contact

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4649]
The database fields for the chapter's legal contact were added in #4648.

This issue covers creating the UI for a Technovation admin to edit a legal contact. The contact is added on the chapter admin page. 

Interface for adding the contact:
<img width="669" alt="Screen Shot 2024-04-17 at 10 31 26 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/0080ede1-c680-4f9e-b5c0-932d8bdea889">

Interface once the contact is added:
<img width="622" alt="Screen Shot 2024-04-17 at 10 32 06 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/2f11f4f3-ce7d-4d5e-ae6e-5c9be1dc7e19">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4649?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Tested on preview and confirmed that I could:

- View the legal contact section for a chapter
- Complete all fields
- Edit the data I had added to the fields
- 
@shaun I'm not sure if this was intentional or not, but the edit button only appears if I've filled out the name field. Otherwise, I can have all fields completed but no way to edit them. That may be fine.

<img width="1299" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b4aa00fc54e5468978d422281803be7df9d074c/Screen%20Shot%202024-05-01%20at%209.16.34%20AM.png" alt="Screen Shot 2024-05-01 at 9.16.34 AM.png" />

 <img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkdwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7cb2e1b74d7dfd693312c299c66658ada0c0503/Screen%20Shot%202024-05-01%20at%209.17.47%20AM.png" alt="Screen Shot 2024-05-01 at 9.17.47 AM.png" />

**Comment by shaun-technovation** [comment]
> @shaun I'm not sure if this was intentional or not, but the edit button only appears if I've filled out the name field. Otherwise, I can have all fields completed but no way to edit them. That may be fine.

Ah, good catch! That was intentional, I assumed name would be filled out if any of the other fields are filled out. But yeah, not ideal if the name field isn't filled out, I'll update it so that if any field is filled out the edit button will be displayed. 👍

**Comment by shaun-technovation** [comment]
> I'm not sure if this was intentional or not, but the edit button only appears if I've filled out the name field. Otherwise, I can have all fields completed but no way to edit them. That may be fine.

I have a fix for this, I also made it so that the "Send MOU" button will only be displayed if the legal contact has an email address.

**Comment by shaun-technovation** [comment]
> I'm not sure if this was intentional or not, but the edit button only appears if I've filled out the name field. Otherwise, I can have all fields completed but no way to edit them. That may be fine.

This should be fixed on QA now, and the "Send MOU" button should only be displayed now if the legal contact has an email address (we can improve/tweak this in the future too).

**Comment by dboyer** [comment]
Checked on preview and confirmed:

- The edit button appears when any field is completed
- The send MOU button only appears if an email address is listed

@shaun-technovation I was able to add non email text in the email field. The page gives an error when I try to save, but the new text displays on the page. Only when I click edit again or reload the page does it show that the field actually didn't update. [Screen recording here.](https://drive.google.com/file/d/1xmsKow-ID0UXTnz8-Uklq_Bb7fcax5Rn/view?usp=drivesdk)

**Comment by shaun-technovation** [comment]
> @shaun-technovation I was able to add non email text in the email field. The page gives an error when I try to save, but the new text displays on the page. Only when I click edit again or reload the page does it show that the field actually didn't update.

Ah, another good catch! I'll address this in #4691, along with some other issues that have come up, like making the legal contact's name and email address required.

**Comment by dboyer** [comment]
Confirm that I can only add an email address in the email field.
