### ISSUE TITLE
Support Requests - Apr 18 - May 15

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4650]

**Comment by viviancan** [comment]
-  4/19/24 -[ club ambassador issue](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1713455779584269) when switching between project types
-  Update [curriculum link](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1713796700889649)
-  Issue with judge (former cha) being [added to RPE](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1713800651787139)
-  4/29/24 - [10 year old judge](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1714404179733699)
-  5/1/24 - Undelete [an rpe](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1714567338162259)

**Comment by dboyer** [comment]
Out of memory messages on Heroku

**Comment by dboyer** [comment]
- Password reset for a judge
- Removed pending exports
- RPE judge issue with too many submissions - #4725
