### ISSUE TITLE
Run chapter migration rake task on Production

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4652]
Existing chapter ambassadors on production need to be associated to new chapters, i.e. the rake task in #4442 will need to be run on Production; and their links need to be converted to chapter links.

Related to #4442, #4444, #4702

**Comment by dboyer** [comment]
Chapter migration status is updated [on this spreadsheet](https://docs.google.com/spreadsheets/d/18IPV5okGcQDa9I18r0nV7OcXjNRRs0Vcq9bjhh-37mQ/edit?gid=0#gid=0).

**Comment by dboyer** [comment]
All ChA migrations are complete!
