### ISSUE TITLE
Security: Update Filestack

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4656]
Update Filestack to address this security vulnerability:

- https://github.com/Iridescent-CM/technovation-app/security/dependabot/150

**Comment by shaun-technovation** [comment]
Filestack has been updated from version`3.22.0` to `3.25.0`. This is now on QA, I updated an avatar on QA and it worked for me, but it would be good to have more testing on this.

**Comment by dboyer** [comment]
Tested on QA and confirmed that I could:

- Upload a team photo
- Upload a student profile photo
- Upload a judge profile photo
- Upload a mentor profile photo
- Crop and edit images
- Delete an existing photo from a team submission
- Add images to a team submission
- View images as a judge when judging a submission
- View enlarged images
