### ISSUE TITLE
Remove old chapter ambassador dashboard and onboarding pieces

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4676]
Remove old/unused chapter ambassador pages, routes, and controllers for the old dashboard and onboarding.

- `app/views/chapter_ambassador/introductions/*`
- `resource :introduction, only: [:edit, :update]`
- `IntroductionsController`

**Comment by dboyer** [comment]
I logged on as a fully onboarded ChA and I was able to access everything as expected.
