### ISSUE TITLE
Add additional filters and columns to judge admin page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4678]
Two requests to assist with score monitoring:

1.  In #4572, judge type was added as a filter and additional column on the participants page. VET would like the same filter and column to be available on the judges admin page at /admin/judges
2. Also add the "virtual or live" filter and additional column from the participants admin page to the judge admin page

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA and confirmed that I could:

- Filter by judge type
- Add judge type as a column
- Export judge type information
- Filter by virtual or live
- Add virtual or live as a column
- Export virtual or live information
