### ISSUE TITLE
Admin ability to edit chapter location

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4685]
Admins can set the country for a chapter as part of chapter creation (#4683.) They also need to be able to set and edit the full location for a chapter on the admin page for a chapter. Editing other chapter fields is covered by #4473 but this issue is specifically for editing location since it is more complex.

<img width="538" alt="Screen Shot 2024-04-30 at 2 41 13 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/2b6c3147-3426-471b-8575-dd038217b0df">

**Comment by dboyer** [comment]
This will use the existing location edit partial.

I'm checking with PT on whether this same edit functionality should be made available to ChAs.

**Comment by viviancan** [comment]
This is on QA. Can you please test the following
Setting the location from admin portal
- Chapter
- Participant
- Team

**Comment by dboyer** [comment]
Testing on QA and confirmed:

- As an admin, I could set the chapter location
<img width="1197" alt="Screen Shot 2024-09-18 at 11 00 58 AM" src="https://github.com/user-attachments/assets/293571d2-af62-4078-a0dd-42b992bd3d39">

- As an admin, I could set a participant's location
- As an admin, I could set a team's location
- As a participant, I could change my team's location
- As a participant, I could change my location
