### ISSUE TITLE
DocuSign document signing history and improvements

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4691]
Track who signed which document, when it was sent and when it was signed in order for us to be able to see all the documents a chapter ambassador or chapter's legal contact has signed.

Since this issue will cover quite a bit of work, here is a rough overview of the work I'll be doing in this issue:
- [x] Make legal contact's name and email address required
  - This will require making legal contacts a separate table in that database, but it will also make these fields required at the database level. This will improve the DocuSign experience so that it will make it impossible to send DocuSign a legal contact w/o a name or an email address.
  - [x] Add new table and model for legal contacts, make name and email address required in database and in Rails
  - [x] Remove legal contact fields from chapters table
  - [x] Update legal contact creation and updating
  - [x] Update DocuSign service to use new legal contact
  - [x] Update job
- [x] Signing history
  - [x] Create new DocuSign history table
  - [x] Associate legal contacts to new DocuSign history table
  - [x] Create new record from DoucSign service after a new MOU is sent from DocuSign
  - [x] Clean up
- [x] Webhook
  - [x] Setup webhook configuration in DocuSign
  - [x] Create local endpoint to update local document history record based on payload from webhook
  - [x] Background job
  - [x] Tests
  - [x] Store webhook payloads
  - [x] Webhook authorization - new issue #4716
  - [x] Clean up
- [x] Display document signed on front-end
  - [x] Make admin chapter's page use a two-column layout
  - [x] On the chapter's individual admin page
  - [x] As a column and filter at /admin/chapters - new issue #4718

**Comment by dboyer** [comment]
We likely will need to display when the doc was signed in a few places:

**Chapter legal doc**
- On the chapter's individual admin page

<img width="958" alt="Screen Shot 2024-04-30 at 9 38 06 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/56fa2a62-55a3-4c58-950b-93cb0879511b">

- As a column and filter at /admin/chapters

**ChA Legal Doc**
- On the ChA's individual admin page
- As a column and filter at /admin/chapter_ambassadors
- On the ChA's profile on the legal tab - perhaps something like "doc was signed on X" and a link to view it

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4691?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Note: PT confirmed that tracking MOUs by season is helpful. Ideally, they would like to be able to see a list of every chapter's status for that season (i.e. who has an active MOU).

**Comment by shaun-technovation** [comment]
@dboyer When you get a chance, can you tell me the new/final name for the MOU?

**Comment by dboyer** [comment]
@shaun-technovation The current updated name is Chapter Affiliation Agreement. I am 90% sure that will remain the name, but we have not received final sign off on the agreement yet from the lawyers.

**Comment by shaun-technovation** [comment]
@shaun-technovation The current updated name is Chapter Affiliation Agreement. I am 90% sure that will remain the name, but we have not received final sign off on the agreement yet from the lawyers.

Okay, sounds good, no worries, I added #4719 to handle the renaming. 👍

**Comment by shaun-technovation** [comment]
For this issue I focused on getting the history and webhook connected and functioning. We can iterate/improve on the work here. The big piece of missing work is adding some security for the webhook so it's not available to everyone, I added #4716 for that one.

**Comment by shaun-technovation** [comment]
The new webhook is now integrated on Preview. Which basically means that when a document is signed, the signed at date should be displayed in the admin area now on the chapter info page.

Something to note about the webhook is that we only handle the "completed" status, if we receive any other status from the webhook it will not get processed. We'll have to see when this happens and update/adjust the flow accordingly.

**Comment by shaun-technovation** [comment]
Here is an overview page of the DocuSign webhook, the video on this page was helpful:
https://developers.docusign.com/platform/webhooks/connect/

To setup the webhook on the DocuSign side, after logging in:
- I clicked Settings in the top navigation
- Then I clicked Connect in the side navigation and the webhook area/settings are there

**Comment by shaun-technovation** [comment]
Also, Preview has been rebased against QA, all of work on QA as of today is now on Preview. Doing so, I ran into some conflicts, mainly database related conflicts, hopefully I resolved them correctly, but just flagging this in case something is off on Preview.

**Comment by dboyer** [comment]
Tested on preview and confirmed:

- Only an email address can be entered in the legal contact email address field
- The legal contact cannot be saved without adding an email address
- I sent an MOU and the status updated from "not sent" to "not signed" and the button to send the MOU was gone. I received the MOU in my inbox.
- I was able to sign the MOU and the admin page updated to say "signed May 20, 2024"
