### ISSUE TITLE
Associate mentors to chapters

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4693]
Associate mentors to chapters, mentors can potentially belong to multiple chapters if they are mentoring students in different chapters.

Related to #4553 and #4690.

**Comment by dboyer** [comment]
Draft mockup
<img width="604" alt="Screen Shot 2024-04-30 at 9 23 24 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/7dfe7e3f-c3af-4c58-ab55-7ae5e3c6a496">

**Comment by dboyer** [comment]
Talked with VET and they confirmed that this is still the intended flow for mentors. This issue may need to be broken down into other issues. Key things include:

- The chapter that the mentor selects on this page becomes their "primary" chapter. 
- If they select "not sure," the mentor should go on an unaffiliated list
- We need to move the "allow teams to find you" and "indicate to teams that you can be a remote mentor" to this page.

**Comment by dboyer** [comment]
Oh excellent! I wasn't sure what was covered under previous general chapter assignment work and what had to be noted specifically for mentors.

**Comment by dboyer** [comment]
Confirmed that when I log in as a mentor, I have the option to select a chapter.
