### ISSUE TITLE
Continue adding additional fields for chapter program info form

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4698]
- [x] Program Length - Single Selection
- [x] Participant Count - Single Selection
- [x] Low Income - Single Selection
- [x] Organization Type - multi
- [x] Meeting time - multi
- [x] Meeting facilitator - multi

**Comment by viviancan** [comment]
Program length is in code review

**Comment by viviancan** [comment]
Participant count in code review

**Comment by viviancan** [comment]
low income in code review

**Comment by viviancan** [comment]
organization type in code review

**Comment by viviancan** [comment]
meeting time and meeting facilitator is in [code review](https://github.com/Iridescent-CM/technovation-app/pull/4723)

**Comment by viviancan** [comment]
@dboyer Confirming this is on PREVIEW

**Comment by dboyer** [comment]
Confirmed that all these fields are on preview. Looks great!!! I could:

- Add and edit fields
- Save without completing every field
- Return and edit existing answers later
- Login as a different ChA for the chapter and see the same info
- Edit that info as a different ChA
