### ISSUE TITLE
SurveyMonkey training integration

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4699]
Basics of SurveyMonkey integration:

1. ChA can start quiz via SurveyMonkey
2. They must complete quiz in order to have the training onboarding step "checked"
3. Results of quiz do not determine if they passed - just need to complete
4. ChA needs to see correct answers to quiz and which they got wrong

Note: Also on the training page will be either links to videos/slides or potentially embedded videos/slides (similar to judges and mentors).

**Comment by dboyer** [comment]
In dev priorities on 6/3, PT confirmed:

- Training would include five slideshows the ChA would be encouraged to do sequentially
- Preference to have them open/accessible in the platform rather than via a separate website or on a new page but not embedded in a way that would make the page long and scrolling
- Chapter team will create a quiz in SurveyMonkey, as long as the ChA takes the quiz we mark training as “complete” and they can proceed with onboarding
- Ideally the answers to the quiz are accessible after it is done

**Comment by dboyer** [comment]
Confirmed via a conversation with PT on June 5:

- Some data such as quiz ID and score can be stored in SurveyMonkey and do not need to be stored on the platform
- Either embedding or opening the checkpoint in a module are acceptable

**Comment by viviancan** [comment]
Overview
I have been working on integrating SurveyMonkey into our platform and have explored several approaches. I am feeling slightly unsure of which path to take moving forward. 

**Embed Script from SurveyMonkey**
- Uses the provided embed script to integrate the SurveyMonkey form directly on the platform page.
- Pros: Simple to implement; direct integration, script given by survey monkey
- Cons: Unable to send custom variables (e.g., user ID, email) to SurveyMonkey; confirmed with SurveyMonkey support.

**Web Link Collector**
- Directs users to take the quiz via a separate tab using a web link. Upon completion, users are redirected back to the platform and marked as completed quiz (similar to mentor/judge flow)
- Pros: Officially supported by SurveyMonkey; allows the inclusion of custom variables.
- Cons: Redirects users away from the platform which may impact user experience.

**Web Link in an Iframe (Unofficial Approach)**
- Embeds the web link within an iframe on the platform page.
- Pros: Allows custom variables to be sent; keeps users on the platform.
- Cons: Not officially supported by SurveyMonkey. I found this approach on some StackOverflow posts. Multiple users cannot take the survey on the same browser without clearing cookies. Confirmed with SurveyMonkey support that cookies cannot be disabled.

I have contacted support to see if there are any other potential solutions I am missing. Tagging @dboyer and @shaun-technovation for visibility! Ty!

**Comment by viviancan** [comment]
Confirming this is on preview. 

I tested with this [participant](https://technovation-preview-28bd069458f9.herokuapp.com/admin/participants/1622#/)

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- I could click the link on the training part of the dashboard to start the checkpoint
- I saw five questions in SurveyMonkey
- I answered the five questions and saw which ones I got right and which were wrong
- When I clicked "done" again in the survey, I returned to the dashboard where the training module was marked as completed
