### ISSUE TITLE
Display MOU "Valid For" on admin chapter's details page

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4717]
Instead of "Renewal Date", display "Valid For" for the MOU, mockup for reference:

<img width="958" alt="Screen Shot 2024-04-30 at 9 38 06 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/56fa2a62-55a3-4c58-950b-93cb0879511b">

**Comment by dboyer** [comment]
Get rid of "renewal date" and replace with a "valid for" field that includes the next 3 seasons.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4717?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment]
This is on Preview.

Also, just noting that we don't have any functionality to expire or renew any legal documents.

**Comment by dboyer** [comment]
Confirming that on preview I see the "valid for" field that lists the next three seasons.
<img width="529" alt="Screen Shot 2024-06-03 at 9 48 11 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/fbf21826-ea7f-4017-ad25-3fc7c77b8a0d">
