### ISSUE TITLE
Security: Update nanoid node module

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4720]
Update the nanoid node module to address this security vulnerability:
- https://github.com/Iridescent-CM/technovation-app/security/dependabot/70

**Comment by shaun-technovation** [comment]
This one got merged into QA this morning, so this also went out with the deploy that was just done.

**Comment by dboyer** [comment]
Tested on QA and confirmed that I could:

- Register as a judge
- Register as a beginner student
- Register as a junior student via an admin invite
- Register as a mentor
