### ISSUE TITLE
Generate certificates for 2024

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4729]
The issue for 2023 certs was #3899.

Depends on implementing #4728. Certificate details [available here](https://docs.google.com/document/d/12DZ5R1l2DiruHpWelABJfU_0Luroz0yatSGKgYfE4ms/edit#heading=h.h2pncnokirl3).

The goal is to make certificates available July 9.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4729?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Program Team confirmed that we can create certificates on production.

**Comment by viviancan** [comment]
<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNyt5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a485950f2cf7f33b9a427826b4f0956295209bda/image.png" alt="image.png" />

19,086 Certificates generated for the 2024 season! I also spot-checked the types on prod on the certificate tab and they looked correct.

Initially ran the 
`heroku run bundle exec rake certificates:award_all_direct --app technovation` rake task 
and then had to run the remaining certs in batches using
`heroku run bundle exec rake certificates:award_batch_direct[LAST_ACCOUNT_ID, BATCH_SIZE] --app technovation`

**Comment by dboyer** [comment]
I also spot checked a few certs and the correct ones appeared for each individual. I'll ask PT/VET to do a round of checking as well.
