### ISSUE TITLE
Don't display recused scores in completed scores

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4732]
Related to this issue in [Slack](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1715886334154179), it's possible that a score can be both completed and recused, if this happens, the score should only be listed under recused in the admin scores area.

Also, if a score is recused and it happens to be completed, remove the `completed_at` timestamp, so that way it will only be listed as recused.

**Comment by shaun-technovation** [comment]
I have fix for this one on QA.

- If a score is completed and somehow after that a judge recuses themselves, it will remove the completed and approved at timestamps so it will only be considered recused
- For any existing completed and recused scores, they will only get displayed as recused
  - I could have updated the data, but this was the easiest thing to to, right now, there are just three submissions that are both recused and completed (one from this season and two from last season)

I created a dataclip that will display scores that are both recused and completed:
https://data.heroku.com/dataclips/vmnyrbqfprugmzvbnwxmakumsedi

If we run this dataclip in the future and there are more than three scores listed, that means there is an issue with the submission -> judge assignment functionality because it is re-assigning recused scores/submissions to the same judge.

**Comment by shaun-technovation** [comment]
Just highlighting that as part of this issue I updated the judge recusal functionality, so that if a score was completed, and then recused, it would remove the completed (and approved) flags after being recused.

**Comment by dboyer** [comment]
To test, I confirmed on QA that I was able to login as a judge and recuse myself from several submissions. As an admin, I can see those recusals on the judge's participant page.
