### ISSUE TITLE
Restrict LearnWorlds access

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4734]
Restrict LearnWorlds access to people who already have a LearnWorlds account, i.e. people who already have access to LearnWorlds should be the only ones who can access LearnWorlds

**Comment by shaun-technovation** [comment]
Here are a handful of accounts on QA that should have access existing access to LearnWorlds:

https://technovation-qa.herokuapp.com/admin/participants/1260
https://technovation-qa.herokuapp.com/admin/participants/1355
https://technovation-qa.herokuapp.com/admin/participants/1390
https://technovation-qa.herokuapp.com/admin/participants/950
https://technovation-qa.herokuapp.com/admin/participants/984
https://technovation-qa.herokuapp.com/admin/participants/1141
https://technovation-qa.herokuapp.com/admin/participants/936
https://technovation-qa.herokuapp.com/admin/participants/1363
https://technovation-qa.herokuapp.com/admin/participants/857
https://technovation-qa.herokuapp.com/admin/participants/1122
https://technovation-qa.herokuapp.com/admin/participants/923
https://technovation-qa.herokuapp.com/admin/participants/924
https://technovation-qa.herokuapp.com/admin/participants/925
https://technovation-qa.herokuapp.com/admin/participants/937
https://technovation-qa.herokuapp.com/admin/participants/927
https://technovation-qa.herokuapp.com/admin/participants/928
https://technovation-qa.herokuapp.com/admin/participants/920
https://technovation-qa.herokuapp.com/admin/participants/929
https://technovation-qa.herokuapp.com/admin/participants/930
https://technovation-qa.herokuapp.com/admin/participants/931

Newly created accounts or account that have never accessed LearnWorlds should not be able to access it.

**Comment by shaun-technovation** [comment]
Here is a complete list of account ids (the participant id on the participants page) that should have access to LearnWorlds on QA, all other accounts not on this list (and new accounts) should not have access to LearnWorlds.
```

[1155,
 1243,
 1124,
 1260,
 1390,
 1355,
 950,
 984,
 1141,
 936,
 1363,
 857,
 1122,
 923,
 924,
 925,
 937,
 927,
 928,
 920,
 929,
 930,
 931,
 965,
 1100,
 949,
 1087,
 933,
 934,
 860,
 926,
 935,
 1095,
 986,
 921,
 932,
 1119,
 7,
 366]
```

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- Created a new beginner student account and received a message that the curriculum was not available:

<img width="645" alt="Screen Shot 2024-05-20 at 1 27 19 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/2c991eb9-4447-4041-a0a9-fc56cd8b851c">

- Logged in as a beginner student with an existing account who had never access LearnWorlds and received a message the curriculum was not available
- Logged in with several accounts that could previously access LearnWorlds (1355, 1390, 1243) and was still able to access the curriculum
