### ISSUE TITLE
Create placeholder page with text for community connections

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4740]
The last step for ChA onboarding is visiting the Community Connections page. Currently this is called "Program Profile" on preview but needs to be renamed. The text is below along with a screenshot. This page is "completed" in terms of getting a check-mark on the side by simply visiting the page.

NOTE: The LinkedIn, Slack, and WhatsApp items are not checklist items that must be completed. Completing the questions related to time and subject matter will be handled in a different Github issue.

Check out all our resources for running the Technovation program on the [Ambassador Resource Page](https://technovationchallenge.org/ambassador-resources/)!

Join Technovation’s global community of ambassadors to stay connected and up-to-date with the latest news and best practices.

We have added you to our email list to receive information about training, program deadlines, and other relevant information to support leading a Technovation chapter. You can also join our Global Community of Ambassadors by participating in the following groups:

- Join our global ambassador’s Linkedin Group (link is [in this doc](https://docs.google.com/document/d/1vQ_tewXkVJOKMif_aoDtDgVRE-1bo-tj9XIZ_nqrzKs/edit#heading=h.uzinssepqd4p))
- Connect with other ambassadors and mentors on our Slack group (link is [in this doc](https://docs.google.com/document/d/1vQ_tewXkVJOKMif_aoDtDgVRE-1bo-tj9XIZ_nqrzKs/edit#heading=h.uzinssepqd4p))
- Join our Whatsapp group and join a regional community

Please select any times you might be available to join councils, trainings, etc. 

- 9am EST
- 1pm EST

Are there any relevant topics you would be willing to share with our global community at a training council? This could include best practices for impactful learning, submissions, partnership development, funding, etc.

Short answer field

_______________________________
<img width="752" alt="Screen Shot 2024-05-20 at 3 37 20 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/0d1224ce-4a47-4b2d-9815-0c556f707bbb">

**Comment by dboyer** [comment]
Confirming I see this page on preview.

@viviancan Could we have the links to Slack and LinkedIn open in a new tab so we don't direct them away from the platform?

**Comment by viviancan** [comment]
@dboyer Yes, will do

**Comment by dboyer** [comment]
Confirming that I now see these links open in a separate tab.
