### ISSUE TITLE
Add two data fields to Community Connections page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4742]
Requires completing #4740 

Add two questions to the Community Connections page. These answers should be stored on the admin participant page for the ChA.

Question 1: Please select any times you might be available to join councils, trainings, etc. 
Answer:
- 9am EST
- 1pm EST

These are optional text boxes.

Question 2: Are there any relevant topics you would be willing to share with our global community at a training council? This could include best practices for impactful learning, submissions, partnership development, funding, etc.
Answer: Text box (optional)

**Comment by viviancan** [comment]
This is on preview!

**Comment by dboyer** [comment]
Confirming that on preview I see these new fields and was able to select one or both of the time options and add content to the text box. I was able to edit the info I selected.
