### ISSUE TITLE
Bug: Saved search on scores export page does not load correctly

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4747]
Steps to reproduce:

1. Go to /admin/score_exports, set search filters, and click search. Then click "save this search" and give the saved search a name.
2. Hit reset to clear the search filters
3. Select the saved search
4. The platform loads the /admin/scores page rather than the saved search on /admin/score_exports

**Comment by shaun-technovation** [comment]
A fix for this is on QA. I think this fix should work for existing saved searches. Also, this could impact saved searches for both "score s export" and "scores".

**Comment by dboyer** [comment]
Confirming that I was able to save a search and then reload it and see the same saved search results.
