### ISSUE TITLE
Link completing training to ChA onboarding step

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4750]
Related to #4743 and requires completion of #4699 

When a ChA has completed the training quiz, the quiz entry in the left sidebar of the ChA dashboard should be marked as completed. The training entry in any onboarding lists in the admin side (participant page, filters, etc) should also be marked as completed.

**Comment by viviancan** [comment]
Confirming this is on preview

**Comment by dboyer** [comment]
Tested on preview and confirmed:

- When I completed the checkpoint quiz, the sidebar got a checkmark in it
- The training step is also marked as completed in the onboarding step section on the ChA admin page <img width="1032" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWlPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0745e0c70e54f850f9042aecd37097931afc49fc/Screen%20Shot%202024-06-25%20at%2011.21.29%20AM.png" alt="Screen Shot 2024-06-25 at 11.21.29 AM.png" />
