### ISSUE TITLE
Link viewing the Community Connections page to ChA onboarding step

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4751]
Related to #4743 and requires completion of #4740.

There are no required actions on the Community Connections page so as long as the ChA clicks onto this tab it can be marked as complete in the left sidebar and in a list of onboarding steps on the admin participant page.

**Comment by viviancan** [comment]
Confirming this is on QA

**Comment by dboyer** [comment]
Confirming that when I clicked on the page on preview, the check mark filled in on the left column. That step was also checked off on the admin participant page. 
<img width="618" alt="Screen Shot 2024-06-02 at 11 03 14 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/fe851730-0bea-4269-9424-e99b335957e4">

<img width="439" alt="Screen Shot 2024-06-02 at 11 03 32 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/11c00f9a-908b-4dd5-af6d-bb413f3edfa6">
