### ISSUE TITLE
DocuSign: Add status column

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4755]
For legal documents sent via DocuSign, we want to explicitly track the status for each document, the statues we want to track are:
- Sent
- Signed
- Voided

**Comment by shaun-technovation** [comment]
A random note/comment on this one, maybe we don't need a full status column, we could track `sent_at`, and that would give use sent/unsent; and we already track `signed_at` which gives us signed/unsigned. I think `signed_at` and `sent_at` could cover the statuses we're looking for.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4755?planning-poker) with Zenhub @shaun-technovation @viviancan
