### ISSUE TITLE
Copy-to-clipboard functionality for score fields

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4757]
Add copy-to-clipboard functionality for these fields on the score details page:
- judge name
- judge email (add this field, only to the admin view)
- score total

This functionality should only be available to admins (not ChAs).

**Comment by shaun-technovation** [comment]
This is on QA, if you wanted to take a look. It adds the copy-to-clipboard icon and functionality for judge name, judge email address (I added that field), and score on the score details page; and should only be available to admins not ChAs.

<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeThIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95552ef4c83351e8dfd62735d390fdce10f7b075/copy-to-clipboard.png" alt="copy-to-clipboard.png" />

**Comment by shaun-technovation** [comment]
A technical note on this one, I wrote a new JS function for the copy-to-clipboard functionality and put it in admin.js, but for some reason it kept causing an error when I tried deploying it. So I ended up moving the function into the partial where it is used, the downside of this is that this function will get loaded each time the partial is used, not the end of the world for how we're using it now, but not ideal either.

**Comment by dboyer** [comment]
Confirming that on QA I can see the new judge email address field and the copy/paste functionality works for all three fields.
