### ISSUE TITLE
Add RPE names to scored submisions datagrid

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4758]
On the scored submissions datagrid (the Scores page), add event names as an additional column.

**Comment by shaun-technovation** [comment]
This is on QA. I named the new column "Events" b/c the way our system is designed, it's possible that a team can belong to multiple RPEs. It would be easy to name this column something else.

**Comment by dboyer** [comment]
Confirming that I see the new Events column on QA at /admin/events. I checked that the event name was correct for that team and confirmed the event name was included in the export.
