### ISSUE TITLE
Completion checkmarks for Chapter Profile section

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4772]
Setup the completion checkmarks for the Chapter Profile section.

Public Info:
- All fields must be completed including at least one program link

Chapter Location:
- Organization HQ location needs to be filled out

Program Info:
- All questions are required except for "If you are planning a Launch Event or info session please share the date."

**Comment by dboyer** [comment]
Tested on preview and confirmed that I see the completion checkmarks for the chapter profile.

When logged in as a ChA:

<img width="820" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1NUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--782510ccb2b05970ef52f87cc72e0aebe008625b/Screen%20Shot%202024-06-26%20at%2011.36.55%20AM.png" alt="Screen Shot 2024-06-26 at 11.36.55 AM.png" />

And on the admin side:

<img width="798" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2FUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a532dcc9412c7b7740a30f37a1ac41dcea47a559/Screen%20Shot%202024-06-26%20at%2011.37.28%20AM.png" alt="Screen Shot 2024-06-26 at 11.37.28 AM.png" />
