### ISSUE TITLE
Add filter and additional column for organization type

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4774]
In the program info section, orgs answer the multi-select question:

Is your organization a:

- School 
- NGO or Nonprofit Organization
- University
- Corporation
- Government agency
- Other institution

This info needs to be a filter and additional column on the chapter admin page (/admin/chapters). Two things:

- [x] Add an additional column of "organization type" 
- [x] Add a filter for "organization type" that works similarly to the mentor and judge type filters where the admin can select multiple choices.
<img width="580" alt="Screen Shot 2024-06-06 at 1 58 06 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/375dba47-2860-4dd2-871b-d4877f5b78d1">

**Comment by viviancan** [comment]
This is on preview

**Comment by dboyer** [comment]
Confirming that on preview I can:

- Add organization type as an additional column and if the org has multiple types, both types appear in the column
- I can use the filter to filter by org type
- Org type appears in the exported data
