### ISSUE TITLE
Create ChA onboarded status column in database

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4779]
Similar to judges and students, create an onboarded status column for chapter ambassadors.

In order for a chapter ambassador to be onboarded this must complete this steps:
- Complete background check
- Take training quiz
- Sign legal agreement
- View community connections

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4779?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Tested on preview and confirmed I saw the onboarding tasks listed on the ChA admin page and that when all were completed, the ChA appeared in the search results when searching for a fully onboarded ChA
