### ISSUE TITLE
Create chapter onboarded status column in database

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4780]
Instead of dynamically checking all of the onboarding steps to see if a chapter is onboarded, create an onboarded status column for chapters.

In order for a chapter to be onboarded this must complete this steps:
- Sign chapter legal agreement
- Complete public info
  - All fields must be completed including at least one program link
- Complete chapter location
- Complete program info
  - All questions are required except for "If you are planning a Launch Event or info session please share the date."

**Comment by dboyer** [comment]
Confirmed that I see a list of onboarding tasks for the chapter on the chapter admin page. I'll open an issue for filtering chapters by onboarding status.
