### ISSUE TITLE
HOTFIX - BUG: When trying to select onboarded mentors matched with a team the platform errors out

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4783]

**Comment by viviancan** [comment]
Original support [request here ](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1717772315322229)

**Comment by dboyer** [comment]
The same error page is happening if you set these search parameters at /admin/participants#/

- Onboarded Mentors --> Yes, fully onboarded
- Team Matching --> Matched with a team
- Profile Type --> Mentors

**Comment by dboyer** [comment]
I did the participant search on QA but as you said, it's not really testable until production.

**Comment by viviancan** [comment]
Confirmed this is working on PROD

I selected mentors, matched with a team, onboarded

**Comment by dboyer** [comment]
I'm still getting the error page when I search on production for mentors who are onboarded and matched with a team.

<img width="1300" alt="Screen Shot 2024-07-01 at 11 48 36 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/6ece4ed5-4cb0-4c3b-a057-4eb42c3197d3">

**Comment by dboyer** [comment]
Tested on QA and confirmed that I get 15 results when searching:

- Mentors matched with a team and mentors fully onboarded
- Matched with a team and mentors fully onboarded
- Mentors matched with a team and profile type mentors

If I search mentor profile type and matched with a team, I get 20 results as it also includes ChAs. I think that makes sense though.

**Comment by dboyer** [comment]
VET also confirmed this is now working on production

**Comment by dboyer** [comment]
Also seeing the separate filters! We can assume our deployment post hotfix process is working as expected! I'm closing this.
