### ISSUE TITLE
Append letter to mentor and judge certificates

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4784]
Connects to #4728

VET would like to include a letter with the mentor certificate. This can be appended to the mentor cert and delivered as a single PDF file. The [letter is available here](https://www.dropbox.com/scl/fo/hpodrusk7boxs2vvt8mw5/AKGWKcsOwE2axORMQg_UEek/volunteer%20letters?dl=0&preview=Mentor+Letter+-+fillable.pdf&rlkey=0ki99dl00ayil4r8k753j7twy&subfolder_nav_tracking=1).

The letter has fillable fields for mentor name and season. If that's not possible to do so close to certificates needing to be available, we can just hard code it to "Dear Mentor."

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4784?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
The certificates and letters as a single PDF for each cert are [available here](https://www.dropbox.com/scl/fo/dkc40dtiuwx3b9j9m1362/AJlA3FPu3oTi4Hgah7ZhDQ8?dl=0&e=1&rlkey=jsyxg4u8b8kzql7ghh0bk6i08).

**Comment by viviancan** [comment]
This is on QA. I manually generated certs and saw the letter with the appropriate name

**Comment by dboyer** [comment]
Tested on QA and saw the correct manually generated certs for:

- Participant
- Quarterfinalist
- Semifinalist
- Mentor
- Certified Judge
- Head Judge
- Judge Advisor

Asking PT/VET to review the certs too.

**Comment by dboyer** [comment]
Confirmed with PT/VET that the certificates look as expected.

**Comment by viviancan** [comment]
I manually awarded my test judge account a certificate. I saw the updated certificate and the new appended letter with the appropriate name

**Comment by dboyer** [comment]
I was also able to manually award a judge and student cert and everything looked as expected.
