### ISSUE TITLE
Add community connections to requirments to restrict access to chapter activty admin

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4786]
Add "viewing community connections" as a requirement for chapter ambassadors to be able to access chapter admin activity.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4786?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Confirmed on Preview that I cannot access the chapter admin activity page until I viewed the community connections page.
