### ISSUE TITLE
Make coding language choices dependent on division

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4799]
If possible, the curriculum team would like the answers to the coding language question to depend on the division of the team. The current choices are:

- App Inventor
- Thunkable
- Other

If the team is in the beginner division, they should also have the option to select Scratch.

**Comment by viviancan** [comment]
This is on QA. Only beginner teams should see the Scratch option

**Comment by dboyer** [comment]
Tested on QA and confirmed that I see Scratch when I'm a beginner but not when logging in as other divisions.
