### ISSUE TITLE
Add fields for entering Scratch project for the submission

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4800]
Depends on #4799 

If a beginner division team selects Scratch for their coding language, they should see this text with two upload options:

1. A field saying "What is the URL for your Scratch project page?

Helper text: Enter the Scratch project page URL. To create a project page, click the orange "Share" button in your Scratch project. Then when the project page appears, click the Copy Link button. This is the URL you will enter here. 

2. An upload option saying: If you used a Scratch environment other than the [scratch.mit.edu](http://scratch.mit.edu/) website, you will save your project to your computer, and then upload that file in the Technical Additions section of this form. The file will have a .sb3 file extension name.

As with Thunkable, if the student uploads a file, that file should automatically display in the Technical Additions section.

- [x] Scrach option in dropdown on coding language section for beginner 
- [x] Migration/field to save `scratch_project_url`
- [x] Scratch URL validation
- [x] Update the technical additions to show the scratch link automatcally
- [x] Update views for admin and student for scratch platform 
- [x] Update admin edit form
- [x] General cleanup (remove submission type, reset other fields)

**Comment by viviancan** [comment]
This is on QA. There seems to be an issue with the "technical additions" overview section where the Scratch link is not displaying automatically. I am investigating!

**Comment by viviancan** [comment]
I will add the fix for this ^^ in the cleanup ticket #4871

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- I see the Scratch link when I log in as a beginner division team
- I entered a junk URL for the Scratch link and it gave me an error message
- I entered a Scratch URL and it saved correctly
<img width="689" alt="Screen Shot 2024-07-25 at 9 32 11 PM" src="https://github.com/user-attachments/assets/fbdaf1f1-8db4-4688-a48b-dadd14b3403c">

@viviancan The check marks for both the coding language and technical additions are not getting a green check mark but I assume that is something being fixed in the other issue.

**Comment by dboyer** [comment]
Confirming the check marks are now working as expected based on the clean up in #4871
