### ISSUE TITLE
Update training module partial and training links

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4809]

**Comment by viviancan** [comment]
Refs #4792 and [this PR](https://github.com/Iridescent-CM/technovation-app/pull/4797)

The training module partial and training links will need to be updated once ready from PT.

**Comment by dboyer** [comment]
Check list of tasks:

- [ ] Add Google Slides iFrame to the partial
- [ ] Add in links for specific Google Slides for each module
- [ ] After the person completes the checkpoint, add text or a link to the download of their answers.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4809?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Tested on QA and confirmed that I now see the Google Slides and the links for each module.

@viviancan After I complete the checkpoint, I can't see the trainings anymore. Is there a way to display the training links and the correct answers to the checkpoint?

**Comment by viviancan** [comment]
Logging "the correct answers to the checkpoint" task in #4829. This is currently blocked. We need a document containing the correct answers.

**Comment by viviancan** [comment]
@dboyer The training links should now be available all the time

**Comment by dboyer** [comment]
Confirming that I can now see the training modules even after completing the checkpoint.
