### ISSUE TITLE
Review/update chapters grid for n+1 query

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4810]

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4810?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
I used a few filters, added additional columns, and exported data on the chapters admin page. Everything worked as expected!
