### ISSUE TITLE
Update "Meet your Chapter Ambassador" section to use chapter info instead of ChA info

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4814]
In #4442, the chapter ambassador's intro summary was converted to be the chapter's summary:
- Update the "Meet your Chapter Ambassador" section to use the the chapter's summary

In #4444, the chapter ambassador's links were converted to chapter links:
- Update the "Meet you Chapter Ambassador" section to use the chapter's links

**Comment by viviancan** [comment]
Things to QA (once on QA)
1. Login as student that is in the location of a Chapter ambassador (it may have to be an older ChA that has an intro summary on their cha profile). 
- Case: ChA not associated to chapter --> student should see "No cha available" dropdown
- Case: ChA IS associated to chapter
     - Chapter with primary contact vs. without primary contact
     - Chapter with vs without chapter name
     - Chapter with vs without summary
     - chapter with vs without chapter links

**Comment by viviancan** [comment]
@shaun-technovation I accidentally rebased my original PR against preview and not QA. I made an updated [PR here](https://github.com/Iridescent-CM/technovation-app/pull/5129)

**Comment by viviancan** [comment]
This is on QA! I tried with participant 1954 and did not get any errors

**Comment by dboyer** [comment]
@viviancan I'm having trouble getting any participant account to display a chapter ambassador in the "meet your ChA" section. I tried with participant 1954 on QA and it says no chapter in the area. I set the student location for another participant as Azerbaijan as we had a chapter there from 2024 on QA and it also didn't say there was a chapter in the area.

**Comment by viviancan** [comment]
@dboyer I changed particpant 1954 to Los Angeles and that ChA is displaying. I can check the ChA from Azerbaijan and see if they have a summary/bio on their ChA profile which would allow them to be displayed (the old way of pulling ChAs)

 <img width="1639" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmlkQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31e2580177415743820937d5bf53b2187230d70c/Screenshot%202024-11-06%20at%2010.07.51%E2%80%AFAM.png" alt="Screenshot 2024-11-06 at 10.07.51 AM.png" />

**Comment by dboyer** [comment]
Confirming I also see the ChA info when I log in as participant 1954.

**Comment by dboyer** [comment]
Confirmed on production that the Meet your ChA section is now displaying chapter information for returning chapters.
