### ISSUE TITLE
Support Request: MT needs an export of the listed fields

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4816]

**Comment by viviancan** [comment]
Original thread [here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1718901157330469)

- Division
- Contest rank
- Submission type
- Team name
- Project name
- Project page	
- Project description
- Learning journey
- Technical video link
- Pitch video link
- City
- State
- Country
- Uses AI	
- Helps solve climate change	
- Is a game
- Solves health problem	
- Solves hunger or food waste
- Uses OpenAI/ChatGPT
- Complete?	Submitted?
- Progress
- Student names
- Student emails
- Parent names
- Parent emails
- Mentor names
- Mentor emails

**Comment by dboyer** [comment]
Export provided to Audra
