### ISSUE TITLE
Create page for ChAs to view unaffiliated students in their country

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4824]
If students select the "I'm not sure" option added in #4408, they should be placed on an "unaffiliated" list for their country. 

ChAs in that country should be able to view a list of unaffiliated students with locations in their same country. This probably should be a new "unaffiliated students" page in the chapter admin activity section.

<img width="980" alt="Screen Shot 2024-06-26 at 10 37 07 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/e7a5895c-b085-420a-82c6-587cce6964d4">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4824?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
Please wait to QA this until #5083 is on preview! ty!

**Comment by viviancan** [comment]
this can be tested with #5083

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- When a student selected "I don't know," they were added to the unaffiliated list for both chapters in Kenya
- When a student changed their location from one country (Nigeria) to another (Kenya) via their profile page, they then appeared on the unaffiliated list for Kenya chapter ambassadors
- The student did not appear on the unaffiliated list for chapters outside Kenya

@viviancan One thing:

1. On the admin page for a mentor assigned to a chapter (/admin/participants/1498#/), I changed the chapter assignment to "none."
2. I then confirmed their location was in a country where we had active chapters.
3. I logged in as the ChA for a chapter in that country (/admin/participants/1577#/) and went to the unaffiliated page. I did not see the mentor's name. 

I'm assuming that removing them from a chapter did not trigger putting them on an unaffiliated list somewhere. Maybe that is an additional task?

**Comment by viviancan** [comment]
> I'm assuming that removing them from a chapter did not trigger putting them on an unaffiliated list somewhere. Maybe that is an additional task?

@dboyer Ahh, yes - I think I know where that is happening. It probably isn't setting the `no_chapter_selected` back to true (when selecting none). I'll look into it

**Comment by viviancan** [comment]
[This PR](https://github.com/Iridescent-CM/technovation-app/pull/5113) addresses the above issue. Moving this back into code review

**Comment by viviancan** [comment]
@dboyer 

"@viviancan One thing:

On the admin page for a mentor assigned to a chapter (/admin/participants/1498#/), I changed the chapter assignment to "none."
I then confirmed their location was in a country where we had active chapters.
I logged in as the ChA for a chapter in that country (/admin/participants/1577#/) and went to the unaffiliated page. I did not see the mentor's name.
I'm assuming that removing them from a chapter did not trigger putting them on an unaffiliated list somewhere. Maybe that is an additional task?"

This can be tested - updated on preview now!

**Comment by viviancan** [comment]
I will also update the following
-  remove the season filter
-  confirm the scope

**Comment by viviancan** [comment]
@dboyer - this is all on preview now and the "none" issue can be tested!

**Comment by dboyer** [comment]
Confirming I see the unaffiliated page when logging in as a ChA on QA.
