### ISSUE TITLE
Add legal agreement as a required task on chapter onboarding

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4827]
Add the legal agreement as a new checkmark required section of the chapter onboarding. The text can say:

ORGANIZATION working with this chapter must sign a Chapter Affiliation Agreement before Chapter Ambassadors are able to access administrative activity for the chapter.

Legal Contact: NAME
Chapter Affiliation Agreement Status: PULL IN STATUS FROM ADMIN SIDE

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4827?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
This is on preview

**Comment by dboyer** [comment]
Confirming that on preview I see:

- The agreement checked in the sidebar if there is a legal agreement on file
- Chapter admin activity is accessible with 8 checkmarks
- The agreement not checked in the sidebar if there is not a legal agreement on file
- Legal contact name on the agreement page of the ChA dashboard updated when I set a new legal contact
- Legal agreement status changed when I moved it from not sent to not signed
