### ISSUE TITLE
Respond to testing of ChA and chapter onboarding

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4829]
Feedback from PT/VET testing.

- [x] The program info form has two date-based questions (when will program start and launch event date). The options include years 2019-2029. Could it only include 2024 and 2025? (VC)
- [x] On the program info form, the first answer to "HOW MANY PARTICIPANTS DO YOU ANTICIPATE SERVING WITH THE PROGRAM THIS YEAR?" should be "15-50." (VC)
- [ ] Add the correct answers to the checkpoint on the training tab (Blocked)
- [x] Display ChA location in user-friendly format on Chapter Location page - split off from #4879
- [X] If Scratch file uploaded and switch to App Inventor, the Scratch file remains - split off into #4936
- [x] Update text on Community Connections page in the Slack bullet to say: "Connect with other ambassadors and mentors on our Slack channel! If you're a new ambassador, look out for an email to join the group."
- [x] Fix Scratch bug where when you upload an sb3 file, technical additions section showed a green checkmark (correct) and you can see the upload on the technical additions upload page, BUT the summary page did now show the file uploaded. See screenshot below
- [x] The box for mentors to set their location says "Confirm your fregion" - remove the f in front of "region"

<img width="744" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1Z2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5728e416adfb926da0b7beaba2c1ecf6e1987274/Screen%20Shot%202024-08-20%20at%2010.36.13%20AM.png" alt="Screen Shot 2024-08-20 at 10.36.13 AM.png" />

- [x] On the ChA legal agreement page, change the sentence beginning "please confirm" to say "After you have read all guidelines and policies below, please click the link to sign the Chapter Volunteer Agreement." - some ChAs are confused thinking that "please confirm" means they need to also sign those docs

- [x] On the chapter affiliation agreement page, if there is no legal contact set up adjust the text to say "No legal contact has been added yet. Please contact your Technovation point of contact to set up your legal contact.

<img width="1246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1Z2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5636766e00decf5d97961ea5f3ddec665d14dccc/Screen%20Shot%202024-08-20%20at%2010.49.04%20AM.png" alt="Screen Shot 2024-08-20 at 10.49.04 AM.png" />

- [x] On the Scratch upload page, underneath (or after) the text saying "What is the URL for your Scratch project page?" add a line "or just click Save to upload an SB3 file on the next page."

<img width="1302" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2h3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6700bc942993444d691531d59d2172a2100b3959/Screen%20Shot%202024-08-20%20at%2011.00.03%20AM.png" alt="Screen Shot 2024-08-20 at 11.00.03 AM.png" />

- [x] On the file upload confirmation page, add sb3 to the list of accepted file formats. "If you used any format besides .zip, .aia, .ppt, .pptx, or .pdf, your file will NOT be linked!"

**Comment by viviancan** [comment]
Moving this to review, but then as more feedback is added it can be moved back into appropriate columns.

**Comment by dboyer** [comment]
Testing on QA with a brand new chapter and a brand new ChA, I do not see these edits. I reset cookies too and didn't have any luck seeing the new changes. 

<img width="743" alt="Screen Shot 2024-07-14 at 11 05 27 PM" src="https://github.com/user-attachments/assets/4e69d68b-ff8f-4040-a899-b4a29287ebc0">

**Comment by viviancan** [comment]
I should've been more specific but I meant I moved this into `Code Review` column! This is still in code review. I will update ticket once on QA.

**Comment by viviancan** [comment]
@dboyer Confirming these are on QA

**Comment by dboyer** [comment]
Confirming that on QA I see only 2024 and 2025 for the launch date and program start date years and the minimum number of participants as 15-50.

**Comment by viviancan** [comment]
@dboyer 
"Display ChA location in user-friendly format on Chapter Location page - split off from #4879"

It looks like the chapter location page is already displaying the "friendly" version of location. I verified the method and also compared this location to the location listed on the participants grid which also uses the "friendly" location.

<img width="1038" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEpGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc0d158f727658eaea7aa030b735c54ab15b517a/Screenshot%202024-08-08%20at%2010.11.32%E2%80%AFPM.png" alt="Screenshot 2024-08-08 at 10.11.32 PM.png" />

**Comment by viviancan** [comment]
Scratch bug
<img width="1216" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGRIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8d2438a4079f28ac82a12127d7d7bea049cd7ca/CleanShot%202024-08-09%20at%2008.45.57%402x.png" alt="CleanShot 2024-08-09 at 08.45.57@2x.png" />


<img width="1404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6379ab2472df6d5af1bf912655b9f8e803c16907/CleanShot%202024-08-09%20at%2008.50.36%402x.png" alt="CleanShot 2024-08-09 at 08.50.36@2x.png" />

**Comment by viviancan** [comment]
This is on QA

Things to check:
- If Scratch file uploaded and switch to App Inventor, the Scratch file should not be there
- Text on community connections "Connect with other ambassadors and mentors on our Slack channel! If you're a new ambassador, look out for an email to join the group."
- Scratch bug - when you upload an sb3 file, technical additions section shows a green checkmark (correct) and you can see the upload on the technical additions upload page, AND the summary page should show the uploaded file name

**Comment by viviancan** [comment]
Ok these 2 are on QA ^^

I am going to have to revisit the source code upload

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- Text updated on the Community Connections page
- When I uploaded a Scratch file, the file showed on both the technical additions page and the overall summary page
<img width="644" alt="Screen Shot 2024-08-12 at 10 49 29 AM" src="https://github.com/user-attachments/assets/a06ef6a5-7cb7-4df7-b331-0539f54a1788">

**Comment by viviancan** [comment]
Splitting " If Scratch file uploaded and switch to App Inventor, the Scratch file remains" into #4936

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4829?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
This is on QA
-  The box for mentors to set their location says "Confirm your fregion" - remove the f in front of "region"
-  On the ChA legal agreement page, change the sentence beginning "please confirm" to say "After you have read all guidelines and policies below, please click the link to sign the Chapter Volunteer Agreement." - some ChAs are confused thinking that "please confirm" means they need to also sign those docs
- On the chapter affiliation agreement page, if there is no legal contact set up adjust the text to say "No legal contact has been added yet. Please contact your Technovation point of contact to set up your legal contact.
-  On the Scratch upload page, underneath (or after) the text saying "What is the URL for your Scratch project page?" add a line "or just click Save to upload an SB3 file on the next page."
- On the file upload confirmation page, add sb3 to the list of accepted file formats. "If you used any format besides .zip, .aia, .ppt, .pptx, or .pdf, your file will NOT be linked!"

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- Mentor location box now says "confirm your region"
- On the ChA legal page, the text has been updated
- On the chapter agreement page, the text suggests to contact your Technovation point of contact if no legal agreement is set up. I confirmed that line is not included if a legal contact is already set up.
- On the scratch page, there is a prompt to upload an sb3 file on the next page
- sb3 is listed on the acceptable file formats page

**Comment by dboyer** [comment]
The blocked issue for the training checkpoint PDF was added to #4999
