### ISSUE TITLE
Merge preview with QA

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4830]
Move preview branch into QA so chapter and ChA onboarding can be deployed to production in the future.

**Comment by dboyer** [comment]
@shaun-technovation When I signed the chapter affiliation agreement and the ChA legal agreement, the checkmark/onboarding step did not update on QA. I was able to request the docs, sign them, receive a signed copy in my email, but the platform still lists the docs as sent but not signed.

ChA - /admin/participants/1657#/
Chapter - /admin/chapters/1#/

**Comment by dboyer** [comment]
@viviancan When I tested the training checkpoint on QA, the final done button redirects me to preview, not QA, so there is no way to complete the training point on QA.

**Comment by viviancan** [comment]
> @viviancan When I tested the training checkpoint on QA, the final done button redirects me to preview, not QA, so there is no way to complete the training point on QA.

@dboyer This is updated on QA and should work as expected now!

**Comment by dboyer** [comment]
Confirming that the survey now directs to QA as expected and the signed documents are updating the chapter agreement and ChA Legal agreement fields. 

I'll let PT know that testing should move to QA since that's where the Docusign integration will be.
