### ISSUE TITLE
Manually assign a mentor assigned a ChA profile to a chapter (assign a ChA to a chapter)

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4837]
Currently, mentors can be assigned a ChA profile. 

<img width="651" alt="Screen Shot 2024-07-01 at 11 56 59 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/d3b73814-13fd-4d9a-99fb-a7e981359577">

When that happens, there should be a way to assign them to a specific chapter. The assign to a chapter functionality is already available on the student profile via #4566 so perhaps some of that can be reused.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4837?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
@dboyer I discovered an unrelated issue affecting mentor accounts converted to ChAs and the ability to update participant details (as an admin). I am still trying to determine exactly when this happens but the beginning details are captured in #4951

**Comment by viviancan** [comment]
This is on QA. It will work for students and non-combo ChA profiles/accounts

**Comment by dboyer** [comment]
Tested on QA and I was able to assign a non-combo ChA to a chapter. When I logged in as that ChA, I saw the new chapter info and was able to complete chapter onboarding tasks. That ChA was listed as a ChA for the chapter on the chapter admin page.

And confirming that I cannot assign a ChA to a chapter if they have a mentor profile.
