### ISSUE TITLE
Add chapter name for all participants on the admin participant page

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4840]

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Confirming that I now see the chapter name on the participant page. I could see this for:

- Students
- Mentors
- Judges

<img width="475" alt="Screen Shot 2024-07-14 at 10 13 13 PM" src="https://github.com/user-attachments/assets/83e3b487-440c-4a25-b354-8961a5c602c4">
