### ISSUE TITLE
Adjust mentor training to use judge training workflow

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4850]
Currently, the mentor training is a series of embedded slides. VET would like the mentor training to work in a similar way to the judge training.

1. Mentors will click a training link on their dashboard that opens a new webpage
2. The webpage will include an "I accept" button on the bottom
3. When mentors click the button, it reloads their dashboard with training marked as complete

**Comment by dboyer** [comment]
The new training page is not available yet. We'll launch in August using the current slides.

**Comment by dboyer** [comment]
Mentor training is now available at https://technovationchallenge.org/courses/mentor-training/. 

I'm confirming that the button they will click to confirm they have completed training is /mentor/training_completion.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4850?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
Confirming this is on QA.

The WP site will need to be updated to redirect back to the platform. I spoke to Rae about this and we just need to let them know when this will go live. You can still test this by using the training URL

**Comment by dboyer** [comment]
Confirming that I now see the link to the mentor training and am able to click through. As you mentioned, the link to complete isn't working but when I manually adjusted the URL, the training task was checked off.

Once this is deployed, I'll remove the config variable for the mentor training slides.

**Comment by viviancan** [comment]
Confirmed this is on prod. Used my [mentor account](https://my.technovationchallenge.org/admin/participants/125152#/)

**Comment by dboyer** [comment]
Removed the MENTOR_TRAINING_DOC_URL config variable on both QA and prod.
