### ISSUE TITLE
List onboarding tasks needing completion in error message

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4851]
When a ChA tries to access the chapter admin activity without completing all the onboarding tasks, the error message should list which tasks remain. We can use the titles of the tasks in the left sidebar. For this version, we don't need to update which specific lines on which forms are missing.

<img width="1274" alt="Screen Shot 2024-07-10 at 11 08 20 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/a63836e7-2c03-4d57-b5c2-b4b2f7cae530">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4851?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTgvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--870352cd8f4013c684dbc29348875333fad81d51/Screenshot%202024-08-06%20at%208.40.39%E2%80%AFPM.png" alt="Screenshot 2024-08-06 at 8.40.39 PM.png" />

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA and confirmed that I see the error message and that it updates based on which tasks that I've completed. The message goes away after I've completed all tasks.
