### ISSUE TITLE
Add option for admin grant/revoke a background check exemption for a ChA

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4862]

**Comment by viviancan** [comment]
Refs #4843 Splitting this into a separate ticket since there was 2nd PR opened for this work

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA:

- Saw on a ChA's dashboard that they did not have a cleared background check
- Used the admin page to give them a background check exemption
- Logged in as the ChA again and saw that they now had a clear background check
- Used the admin page to revoke the background check
- Logged in as the ChA again and saw that the background check was no longer marked as completed
