### ISSUE TITLE
Potential bug - As a student unable to access technical additions section for team submissions

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4864]

**Comment by viviancan** [comment]
I cannot access the technical additions page to upload the source code. It may be related to changes made with the coding language/submission types updates in #4798. 

@dboyer can you confirm on your end? I discovered this when working on #4800.

**Comment by dboyer** [comment]
Confirming that I also cannot access the technical additions page.

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Confirming I can also now access uploads on QA.
