### ISSUE TITLE
Activity tracking for chapter ambassador background check exemption 

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4866]
In the Profile Activity section on the participant admin page for ChAs, we should track:

- [x] When a background check exemption is granted or revoked
- [ ] When a ChA's chapter assignment is added or changed

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- Granting a background check exemption is shown in the activity tracking section
- Revoking a background check exemption is shown in the activity tracking section

@viviancan When I assigned a ChA from one chapter to another chapter, it updated the activity tracking but just listed it as the phone number wasn't updated

<img width="1097" alt="Screen Shot 2024-09-30 at 8 57 21 PM" src="https://github.com/user-attachments/assets/bab0637b-1dfa-459f-8173-16ea86b3a954">

This was for /admin/participants/2059#/ and was replicated on another account as well.

**Comment by dboyer** [comment]
Ah got it. I thought this still covered logging chapter assignment. All is good then if this relates only to tracking background check exemptions.
