### ISSUE TITLE
Update platform text for 2025 season

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4868]
The following sections are ready to be updated:

- [x] [Student curriculum page](https://docs.google.com/document/d/1umS_ouwjdab2RHk-rS2Cx0IxTSKkujY4AOg1qC5Eghs/edit#heading=h.sjnzs7chhm3)
- [x] [Honor code](https://docs.google.com/document/d/1umS_ouwjdab2RHk-rS2Cx0IxTSKkujY4AOg1qC5Eghs/edit#heading=h.bcna60u94wty)
- [x] [Parental consent page](https://docs.google.com/document/d/1umS_ouwjdab2RHk-rS2Cx0IxTSKkujY4AOg1qC5Eghs/edit#heading=h.6sueu671406b)
- [x] [Mentor links drop-down](https://docs.google.com/document/d/1umS_ouwjdab2RHk-rS2Cx0IxTSKkujY4AOg1qC5Eghs/edit#heading=h.l7qcett1b5y2)

I'm going to suggest we wait on any [updates to the ChA resources page](https://docs.google.com/document/d/1umS_ouwjdab2RHk-rS2Cx0IxTSKkujY4AOg1qC5Eghs/edit#heading=h.1624snyzv6uw) in the admin portal for now. I'd like PT to review the ChA profile to see what info should maybe go there instead.

**Comment by viviancan** [comment]
Created #4902 to update the ChA resource page once approved

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA and confirmed the following pages are updated:

- Student curriculum page
- Honor code
- Parental consent page
- Mentor links drop-down
