### ISSUE TITLE
Text updates for ChA onboarding pages

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4869]
We have a few pages where we need text updates. All text is [available here](https://docs.google.com/document/d/1S8iQ2Lxp1UXA0Zj_yrDWL6bfvLjMndwZ93NaNikI_4U/edit) and specific sections to update are:

- [x] [ChA dashboard](https://docs.google.com/document/d/1S8iQ2Lxp1UXA0Zj_yrDWL6bfvLjMndwZ93NaNikI_4U/edit#heading=h.mq1ey3ie5ipk)
- [x] [Chapter dashboard](https://docs.google.com/document/d/1S8iQ2Lxp1UXA0Zj_yrDWL6bfvLjMndwZ93NaNikI_4U/edit#heading=h.1yu5owr1faly)
- [x] [Legal agreement page](https://docs.google.com/document/d/1S8iQ2Lxp1UXA0Zj_yrDWL6bfvLjMndwZ93NaNikI_4U/edit#heading=h.ubd27xqkydg1)
- [x] [Background check page](https://docs.google.com/document/d/1S8iQ2Lxp1UXA0Zj_yrDWL6bfvLjMndwZ93NaNikI_4U/edit#heading=h.dk1yhmaaooki)

**Comment by viviancan** [comment]
We will need to add the following env variables to QA and PROD

```
CHAPTER_AMBASSADOR_NON_DISCLOSURE_AGREEMENT_URL
CHAPTER_AMBASSADOR_BRAND_GUIDELINES_URL
CHAPTER_AMBASSADOR_SOCIAL_MEDIA_GUIDELINES_URL
CHAPTER_AMBASSADOR_CODE_OF_CONDUCT_URL
CHAPTER_AMBASSADOR_SAFETY_PAGE_URL
```

**Comment by viviancan** [comment]
This is on QA. There was one typo affecting the bg check text but the fix is being merged to QA right now. All of the ENV variables above have been added to QA

**Comment by dboyer** [comment]
Checked on QA and confirmed the following pages were updated:

- ChA dashboard
- Chapter dashboard
- Legal agreement page

On the page after submitting a background check, there are a few [needed text edits](https://docs.google.com/document/d/1S8iQ2Lxp1UXA0Zj_yrDWL6bfvLjMndwZ93NaNikI_4U/edit#heading=h.20obd5j2e5ai). The main background check text changes look good.

**Comment by dboyer** [comment]
Confirming that I see the last background check text updates on QA!
