### ISSUE TITLE
Scratch/submission cleanup 

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4871]

**Comment by viviancan** [comment]
Refs #4800

The initial PR was getting large, so moving these to a new ticket. 

- [ ] Weird behavior (sort of bug) for thunkable (&scratch) when you change the external link through technical additions, the link is not actually updated
- [ ] Update logic for checkmarks in side nav for student submission

**Comment by viviancan** [comment]
This is on QA -  noting that there is a fix for the side nav checkmark for Scratch in code review. Right now it will only show complete if a scratch project URL is added. The fix will make it so that the checkmark will show complete for scratch development platform if scratch is selected or if scratch is selected and there is a project URL. This distinction is needed since Scratch can either have a project URL OR technical addition upload.

**Comment by dboyer** [comment]
Tested on QA and confirmed:

-  I saw a green check mark on coding language if I selected Scratch and clicked Save, even though I hadn't entered a URL for a scratch project
-  I could upload an sb3 file on the technical additions page and get a green check mark there
-  When I added a URL on the coding language page, it marked both the coding language and technical additions as complete
