### ISSUE TITLE
Update text on the chapter location page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4879]
As part of testing, several people reported confusion with the chapter location tab (screenshot below) since it's not hooked up to a location system yet. Let's adjust it to show:

Organization Headquarters Location
- Let's keep this field as is since it's linked to the checkmark

Is it possible to remove all the other fields and instead have:

- Your chapter is currently serving this location:  LIST CHA'S LOCATION

<img width="824" alt="Screen Shot 2024-07-24 at 12 26 01 PM" src="https://github.com/user-attachments/assets/e0f3d385-fcca-448b-9069-108fafcaac43">

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4879?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Confirming I see these text updates on QA. Some locations aren't easy to understand so we may get some questions from ChAs.

<img width="1304" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1F6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18212921c33c3b7219673d0b22959e786f15640a/Screen%20Shot%202024-08-05%20at%2011.25.50%20PM.png" alt="Screen Shot 2024-08-05 at 11.25.50 PM.png" />

**Comment by viviancan** [comment]
Good find! I will take a look!

**Comment by viviancan** [comment]
Good find! I will take a look!
