### ISSUE TITLE
Add additional question on gadget selection

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4896]
PT has requested that we add this additional question for the 2025 season. It is an optional question that is not viewed by the judges and can go anywhere in the additional questions section. It should be multi-select.

Which of the following additional gadgets are used in your project? Select all that apply.

- Micro:bit
- Arduino
- Raspberry Pi
- Other (Please specify)
- None

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- I was prompted to select yes/no if I had used a gadget
- If I selected no, I didn't receive any other option and could just save
- If I selected yes, I could select one or more options
- If I selected other, I received a field to enter the name of the other gadget I used

@viviancan It looks like not all the selected options are appearing on the submission overview page. I selected "Arduino" and "Other - Marbles" on this submission (/student/published_team_submissions/oak-trees-by-birnam-wood) but only Yes - Marbles is showing on the submission overview, both on the page to review before submitting and the page after submitting, and on the admin page for the submission. 

<img width="560" alt="Screen Shot 2024-09-02 at 11 22 16 PM" src="https://github.com/user-attachments/assets/cc5768e6-a564-41e5-9f1b-426042f3f9a8">

<img width="513" alt="Screen Shot 2024-09-02 at 11 25 14 PM" src="https://github.com/user-attachments/assets/3e3400c2-b6e9-4673-8c1f-603a72a65db2">


<img width="572" alt="Screen Shot 2024-09-02 at 11 22 42 PM" src="https://github.com/user-attachments/assets/87940456-132d-48fe-84f2-f875fe20a2df">

<img width="567" alt="Screen Shot 2024-09-02 at 11 23 20 PM" src="https://github.com/user-attachments/assets/10079cff-7ac3-4c63-839d-fbafdf641731">

**Comment by viviancan** [comment]
Moving this to in progress while I address this ^^

**Comment by dboyer** [comment]
Confirmed on QA that all selections now appear on the summary page before submitting, the page confirming submission, and the admin page. 

<img width="1152" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c3e13d51b707c2d924168e20ed2b5cb8be7e8c8/Screen%20Shot%202024-09-16%20at%2011.20.32%20AM.png" alt="Screen Shot 2024-09-16 at 11.20.32 AM.png" />
 <img width="1150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f0c732e117cd8a250fddb782701c3a3fa31a167/Screen%20Shot%202024-09-16%20at%2011.19.32%20AM.png" alt="Screen Shot 2024-09-16 at 11.19.32 AM.png" />

**Comment by dboyer** [comment]
Confirming I see the gadget question on the submissions page and was able to answer it on my test submission.
