### ISSUE TITLE
Run the reset season and reset survey rake tasks for the 2025 season

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4897]
We need to reset the season on both QA and production in order to support opening registration. More details available [in this doc](https://docs.google.com/document/d/1oBVG_RMi6SVQ8KlznqmdRT_FuNCgRCkBy8maM4tXeWA/edit#) and in issue #3157. 

Specific tasks include:

- [x] QA
`heroku run bundle exec rails reset_for_season[force] --app technovation-qa`

<br>

- [x] Prod
`heroku run bundle exec rails reset_for_season[force] --app technovation`

This should:

- Reset data terms so that students, mentors, and judges all need to agree to the terms again
- Reset mentor training flag so mentors need to redo training
- Reset judge training flag so judges need to redo training
- Require students to get parental consent (even for returning students)
- Require students to get media consent (even for returning students)

We also need to run the rake task to reset surveys. 

documentation: https://docs.google.com/document/d/1hVaugqKipnD8pYmCcMl5KWCHrrqBBSr-86MQZTdm5P8/edit?pli=1#heading=h.nk9euk5z6x91

resetting for all users (students & mentors)

- [x] For QA

heroku run bundle exec rails surveys:reset_all --app technovation-qa

- [x] For Prod

heroku run bundle exec rails surveys:reset_all --app technovation

**Comment by dboyer** [comment]
Confirming the survey rake task was reset on QA. Testing the pre-survey showed that data was flowing into SurveyMonkey as expected on QA.

**Comment by dboyer** [comment]
Confirming that the season reset and the survey reset were run on production on August 9.
