### ISSUE TITLE
Configure/update QA ChA Training Checkpoint

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4898]

**Comment by viviancan** [comment]
This is on QA. 

@dboyer I shared the QA version of the checkpoint with your SurveyMonkey account. Can you also verify the response captured there in the "individual responses" tab. The title of the survey is 
`*** QA *** COPY OF Chapter Ambassador Training Checkpoint | 2025 Season`

**Comment by dboyer** [comment]
Confirming that I see the new QA checkpoint on QA and was able to answer all the questions, see the answers, and when I returned to the onboarding page, the training was marked as completed.

I looked in SurveyMonkey and see the completed surveys listed with the correct answers associated with the correct ChA's name, email, etc
