### ISSUE TITLE
Update ChA Resource Page for 2025 season

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4902]
[updates to the ChA resources page](https://docs.google.com/document/d/1umS_ouwjdab2RHk-rS2Cx0IxTSKkujY4AOg1qC5Eghs/edit#heading=h.1624snyzv6uw)

**Comment by dboyer** [comment]
@viviancan If the missing links you mentioned in the PR are for the curriculum, I updated the doc with those links. I also added a "Platform Overview Video" link under the Chapter Resources section with the video PT asked us to add.

**Comment by viviancan** [comment]
@dboyer Ty! This is updated and on QA

**Comment by dboyer** [comment]
Confirming I see the new links and updates on QA!
