### ISSUE TITLE
Salesforce wrap up work

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4904]
From the Salesforce email sent on 7/24:

- Map email address to alternate email in Salesforce (`npe01__AlternateEmail__c`)
- Only send date of birth for students

From the Salesforce email sent on 8/6:

- Send "Club Ambassador" as "Mentor Role"
- Remove "Club Ambassador" from "Mentor Types"

I couldn't find this documented, but last I heard we wanted this:
- Convert periods to LNU in the conversion rake task and service (that updates their info)

**Comment by dboyer** [comment]
@shaun-technovation I see you saw the update that we're not moving to LNU for the period. In our Salesforce [meeting yesterday](https://docs.google.com/document/d/1x0pUaf6BrhiGEXKY1WuO9fa-VVCDE_2MNozFVsawx50/edit#heading=h.4dewty1ilrg1), Sasha also said that we can keep club ambassador as a mentor type. Apologies if you had already changed it to a mentor role. I didn't think you'd get to it before I updated the issue this morning.
