### ISSUE TITLE
Configure PROD ChA Training Checkpoint on SurveyMonkey

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4916]
Related to #4898

Once the QA version of the checkpoint is confirmed, the PROD version of the checkpoint will need to be configured.

This includes
- [x] Add custom variables
- [x] Update the redirect "done" button
- [x] Add correct URL to heroku prod config variables

**Comment by viviancan** [comment]
The PROD checkpoint has been configured/updated and been added to production config variables

**Comment by dboyer** [comment]
Confirming the survey worked as expected on production. I was able to view the training modules, complete the survey, and when I clicked done, it redirected to the training tab on the dashboard and I had a green check mark.

Also checked SurveyMonkey and confirmed that data was flowing as expected.
