### ISSUE TITLE
Docusign wrap up

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4917]
- [x] Disable send buttons after sending to help prevent duplicate documents from being sent
- [x] Prevent more than one affiliation agreement from being sent
- [x] Make the title field required
- [x] Update the organization name and location fields
- [x] "Unlink" location and title fields
- [x] Make location required
- [x] Add organization name (to the footer) - **A new issue was created for this #4948**

**Comment by dboyer** [comment]
One note on this. I found that when moving between send and void, the text on the button doesn't change until after a page refresh. For example as shown [in this recording](https://drive.google.com/file/d/1iLRKM6ZnaVPZNaLcHz9SE98s8evT4yyW/view?usp=drivesdk):

1. I clicked send agreement
2. The page showed that sending the agreement was in the queue and the send button remained the same
3. I refreshed the page and now the button said void
4. I clicked the button to void the agreement and got the header message that voiding would happen
5. The void button remained and did not change to a send button until I refreshed the page
