### ISSUE TITLE
Allow judges, mentors, ChA to edit phone numbers

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4920]
Judges, mentors, and chapter ambassadors can add their phone number during registration, but currently don't have a way to edit it.

**Comment by viviancan** [comment]
This is on QA. It is working for admin, mentors, and ChAs. I am removing a duplicate phone number field for judges. It will also work for judges shortly.

**Comment by viviancan** [comment]
This is also working for judges

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- As a ChA, I could edit my phone number
- As a mentor, I could edit my phone number
- As a judge, I could edit my phone number
- As an admin, I could edit the phone numbers for a judge, mentor, and ChA

**Comment by viviancan** [comment]
I was able to edit my mentor account phone number as an admin

**Comment by dboyer** [comment]
Confirming I could also edit a judge phone number and mentor phone number from those accounts and the phone number field as an admin.
