### ISSUE TITLE
Placeholder: Remove ChA from Chapter

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4924]

**Comment by viviancan** [comment]
I think this exists by selecting "none" in the chapter assignment dropdown!

**Comment by dboyer** [comment]
Yes!!! Tested on QA by setting a ChA assigned to a chapter to None and then logged in as that ChA. They no longer had access to the chapter onboarding steps. I then tried for a fully onboarded ChA who had access to the chapter admin activity. They lost chapter admin activity access when I switched to "none."
