### ISSUE TITLE
Update chapter summary character limit

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4933]

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Confirming the chapter summary is now 1000 characters on QA. I was able to upload nearly 1000 characters but received an error message when I went over 1000.

**Comment by viviancan** [comment]
This is on prod

**Comment by dboyer** [comment]
Confirmed the character count is updated on production.
