### ISSUE TITLE
Make ChA tabs only available if ChA is associated to a chapter

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4938]

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- As a ChA assigned to a chapter, I was able to access my onboarding tab and the chapter profile and complete the tasks on a tab
- As a ChA without a chapter, I could login and see the tabs. When I click on a task, I get the message "You are not associated with a chapter. Contact support"

**Comment by viviancan** [comment]
This is on prod

**Comment by dboyer** [comment]
Confirming that when I logged in as a ChA without a chapter on prod, I could not complete any of the onboarding steps for either the ChA or Chapter processes.
