### ISSUE TITLE
Prevent duplicate ChA legal agreements from being sent

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4947]
Prevent duplicate chapter ambassador legal agreements from being sent.

- If a legal agreement already exists, prevent another one from being created at the controller level
- After the legal agreement has been sent (after the job has been scheduled to be more accurate), hide the "Review and Send" button

**Comment by dboyer** [comment]
Tested on QA and confirmed that after I clicked the "review and sign" button, it disappeared from the page so I could not click it again.
