### ISSUE TITLE
Address Salesforce DUPLICATE_VALUE errors

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4949]
I found [this article](https://help.salesforce.com/s/articleView?id=000383480&type=1) and I think it's why we're seeing these "duplicate" errors.

Here are some snippets:

> You may wonder why you are getting duplicate error while you are doing a patch operation which should either update the existing records or insert a new record?

Yes, exactly!^

> You are sending a duplicate record while the other is already present/being processed.
> 
> The scenario might be as follows: 
>
> Since multiple requests being sent, there might be an overlapping request. That is, if the same record has been sent simultaneously/with milliseconds of gap, it might be possible that the first records is under process while the second record is again taken up for processing. Then the server finds the second record as a duplicate and throws the error.

This is very likely the case for us. If a combo account (mentor/ChA) gets registered to the season, we would be making two calls, one for each profile type. I tried to re-create/prove out this, but I have been unable to so far, but I think this is what is happening.^

> The best possible solution for this scenario would be to synchronize the requests.

> - Make sure, only one record is present in a request/in a batch of requests.
> - While there is no time gap set by Salesforce as such between consecutive requests, it would be a good practice to program the requests in a way to have some milliseconds of time gap between two requests (if the same record is being sent multiple requests)

For an attempted fix, I'm going to try spacing out our calls if we are making consecutive calls for combo accounts.

**Comment by dboyer** [comment]
There have been no duplicate value errors on production since added the 30 second delay for combo accounts.
