### ISSUE TITLE
Potential Bug: When editing mentor-judge combo accounts as an Admin, the platform errors out

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4951]
Related to #4837

I believe there is a bug when updating combo accounts. I am still trying to determine all of the combos but for example, as an admin, if you convert a mentor to a ChA (add a ChA profile) and then try to edit their participant details, the platform will error out. I have been able to recreate this **as an admin** on prod (with my personal mentor account), qa, and locally. When I am logged in as a mentor, I can update my profile details. I think this bug is related to mentor and judge types. 

```
ActiveRecord::AssociationTypeMismatch: JudgeProfile(#30900) expected, got {"judge_type_ids"=>[""]} which is an instance of ActiveSupport::HashWithIndifferentAccess(#89760)
```

**Comment by viviancan** [comment]
This is on QA. You should be able to edit mentor & judge types for mentors, judges, and any kind of mentor/judge/cha combo account.

**Comment by dboyer** [comment]
Tested on QA and I was able to:

- add a ChA profile to a mentor account
- edit that account for both mentor fields such as mentor types and assign them to a ChA
- for an account with both judge and mentor profiles, I could edit both judge and mentor types
- for the account with both judge and mentor profiles, I was able to add a ChA profile and assign to a chapter

**Comment by dboyer** [comment]
Confirmed the type fields are on production and it is possible to edit a profile with both a mentor and judge account or mentor and ChA account.
