### ISSUE TITLE
Search improvements on the organization and program name fields

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4953]
While adding chapters and ChAs, I ran into a few issues using the search function on the organization and program name fields at /admin/chapters

- It's not stripping white space at the end of the field. If I leave a trailing white space after an org's name, it returns zero search results. Taking away the white space and I get search results
- If there is an accent on a letter in the org name (i.e. ń rather than n) and I don't include the accent mark, the org will not appear in the search results. I think it's likely that someone might be searching for the org and forget an accent mark and be confused if the org doesn't appear in the search results
- Partial words are not returned in the search results (i.e. searching "chicas" does not include the org with the word chicas in the name)
- Spaces between words also seem to matter. If I search something like Tech Rookies, I get zero results because the name is TechRookies

It would be great if we could adjust a few of the search parameters. Otherwise I'm concerned that duplicate orgs will be created because the expected org doesn't appear when searching.

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- Trailing white space is stripped from the end of the org and chapter names search fields
- Search chapter and organization name with and without letter accents returns search results as expected
- Searching a single word in the org or chapter name returns results for orgs with that word in the name
- Space between words seems improved. Searching both tree house and treehouse returned the org "TreeHouse Wonders." However searching "coding club" returns Easton Coding Club and Irish Coding Club. But searching "codingclub" does not return either org
