### ISSUE TITLE
Support Requests - August 21 - September 4

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4965]
Investigate these Airbrake issues, if they can be reproduced a new issue can be created for them:

- `ActionView::Template::Error: undefined method `name' for #<NullAuth:0x00007f340428f840> record.public_send(method)`
   - 22 occurrences     
   - Airbrake issue: https://herokuapp32249283herokucom.airbrake.io/projects/107438/groups/3108496801758111323

- `Pundit::NotAuthorizedError:  not allowed to show? this ParentalConsent`
  - 48 occurrences
  - Airbrake issue: https://herokuapp32249283herokucom.airbrake.io/projects/107438/groups/3662822647495582450

**Comment by dboyer** [comment]
Moved open issue regarding Airbrake errors to #4999
