### ISSUE TITLE
Add student name search option on paper parental consents admin page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4985]
PT sometimes receives emails regarding the status of a paper parental consent form. They need to check the name in the email against the consent forms still needing review at /admin/paper_parental_consents#/. The process would be more efficient if there was a search field for the participant name.

**Comment by dboyer** [comment]
Confirming that I see the name/email search field on QA and name search works as expected.

@viviancan If I search by email, it looks like it's displaying anything with the domain in the search results (i.e. searching a particular Technovation email address returns any email address ending in technovation.org.

Is that how the email search works on other pages? If so, I'm fine with continuing that pattern here. Just wanted to check that it was the same on other pages.

**Comment by viviancan** [comment]
@dboyer I didn't make any changes to the logic for searching, just tweaked it to fit the page! I believe this is how the email search is on the other pages.

**Comment by dboyer** [comment]
Sounds good! No concerns then.

**Comment by viviancan** [comment]
I was able to search by name/email on prod
