### ISSUE TITLE
Security: Update axios node module

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4995]
Update the `axios` node module to address this security vulnerability:

- https://github.com/Iridescent-CM/technovation-app/security/dependabot/208

**Comment by dboyer** [comment]
Based on the issues with the [previous axios update](https://github.com/Iridescent-CM/technovation-app/issues/4477), I tested the following things:

- Updated my location
- Register a mentor account and agree to data terms
- Set mentor types and skills
- Agree to data terms as a judge
- Recuse myself from judging a project
- Register as a judge and set location
