### ISSUE TITLE
Support Request Sept 4 - Sept 18

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4999]

**Comment by viviancan** [comment]
- [ ] The onboarded mentors filter for admin datagrids is not pulling all onboarded mentors. More [details here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1725384753947369)
- [ ] Issues with some ChAs having suspended bg checks. More [details here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1725395739911019)
- [ ] Duplicate chapters issue. [Details here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1725460408915549)

**Comment by viviancan** [comment]
`Issues with some ChAs having suspended bg checks. More details here` This was resolved in an email chain. There seems to be some geopolitical issues that are causing issues for bg checks in certain locations.

Steps taken:
- Reached out to Checkr support for confirmation of suspended bg checks
- Internal team determines bg check status and it is documented
- Candidate is engaged through the checkr portal

**Comment by viviancan** [comment]
`Duplicate chapters issue. Details here`

This was resolved when the duplicate chapters were deleted.

**Comment by viviancan** [comment]
` Invite sent to an email address forwarded to someone else who used a different email address. Now original email address cannot be invited again ([details here] (VC)`

This has been resolved. 
These were the steps:
```
user_invite = UserInvitation.find(id_here)

user_invite

user_invite.update(name: "name here", email:"email here")

user_invite

Then I will verify in db and on platform
```

**Comment by viviancan** [comment]
Following up on 
`The onboarded mentors filter for admin datagrids is not pulling all onboarded mentors. More [details here] (VC)`

The filter works correctly for the current season, but does not work for previous seasons (From VET `the filter works fine for the season you're in, but it doesn't work for past seasons which is a result of how the platform is set up`). This is a known issue/non-issue.

**Comment by dboyer** [comment]
All support issues completed excepted for three moved to the new support ticket - #5029
