### ISSUE TITLE
Sometimes the chapter onboarded flag is not updated to true when all steps are completed

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#5001]

**Comment by dboyer** [comment]
After clicking edit for the chapter and then save, the chapter onboarded flag updates and the student is marked as fully onboarded. This happened for these ChAs

153005
215019
86325
215089

**Comment by dboyer** [comment]
As far as I know, so far, we've only manually engaged one candidate via the Checkr portal. Everyone else has passed the check via the standard integration with Checkr.

**Comment by dboyer** [comment]
On QA, I completed all checks for a ChA and chapter leaving the program info page for last. I then completed it all at once and got the final check mark. I clicked to the chapter admin activity tab and was able to access it immediately.

On the admin pages, all tasks were marked complete as expected.
