### ISSUE TITLE
Refactor back-end for chapter assignments

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#5024]
Refactor how chapter assignments are done on the back-end to be able to handle a one-to-many relationship for mentors, mentors can belong to many chapters.

Instead of having three ways for chapter assignments (one for students, one for ChAs and one for mentors), it might make more sense to have one consolidated way and place for chapter assignments.

One proposal is to have one table to keep track of chapter assignments:
- `chapter_id`
- `account_id`
- `profile_type`
- `profile_id`
- `season`
- `primary`

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/5024?planning-poker) with Zenhub @shaun-technovation @viviancan
