### ISSUE TITLE
Update text on mentor dashboard pages for finding a team

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5028]
Add the following text to /mentor/team_searches/new and /mentor/dashboard#/find-team

To learn more about finding a team, review the [Find a team](https://technovationchallenge.org/courses/mentor-training/lessons/mentor-training-find-a-team/) lesson from the Mentor Training.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/5028?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
I see the text on both pages and links are working as expected. @viviancan Would it be possible to have the links open in a new tab so the person isn't directed away from the platform?

**Comment by viviancan** [comment]
@dboyer Yes will do!

**Comment by viviancan** [comment]
The update is on QA

**Comment by dboyer** [comment]
Confirming that I now see the links opening in new pages.

**Comment by dboyer** [comment]
Confirming I see the updated text on production and links are working as expected.
