### ISSUE TITLE
Support Request Sept 18 - Oct 2

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#5029]
- [x] Delete two chapters - [thread here](https://iridescentlearning.slack.com/archives/C02J1GU8VRA/p1726515220488689)
 - [ ] #5061

- [ ]  Investigate these Airbrake issues, if they can be reproduced a new issue can be created for them:

ActionView::Template::Error: undefined method name' for #NullAuth:0x00007f340428f840 record.public_send(method)`

22 occurrences
Airbrake issue: https://herokuapp32249283herokucom.airbrake.io/projects/107438/groups/3108496801758111323
Pundit::NotAuthorizedError: not allowed to show? this ParentalConsent

48 occurrences
Airbrake issue: https://herokuapp32249283herokucom.airbrake.io/projects/107438/groups/3662822647495582450

**Comment by dboyer** [comment]
Open requests moved to #5061
