### ISSUE TITLE
Rebrand location interrupt for mentors

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5031]
Rebrand to match students and judges.

<img width="1722" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTdtQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d346d666d2f4ec4e2fb71df46a35ca86ffb0356/Screen%20Shot%202024-09-18%20at%202.07.48%20PM.png" alt="Screen Shot 2024-09-18 at 2.07.48 PM.png" />

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/5031?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
This is on QA. I tested as a new mentor and an existing mentor. I see the rebranded location form

**Comment by dboyer** [comment]
Confirming that I see the new location form when registering as a mentor and when updating my location via the mentor profile. I also saw the new location when I logged in as a mentor without a location.

**Comment by viviancan** [comment]
confirmed on prod
