### ISSUE TITLE
Update chapter ambassadors datagrid

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#5047]
The back-end for how chapter ambassadors are assigned to chapters was changed/updated in #5024. Chapter ambassador profiles are no longer associated to chapters, it's the chapter ambassador's account that is now associated to a chapter. The chapter ambassadors datagrid needs to be updated accordingly.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/5047?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Chapter ambassadors appear to be associated with chapters as expected. I did not run into any issues while testing other chapter selection issues so I'm moving this to "confirmed on preview."
