### ISSUE TITLE
Update admin chapter assignment functionality

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#5048]
In #5024, we changed how chapter assignment is done; accounts are now associated to a chapter, instead of individual profiles. The admin chapter assignment functionality needs to be updated accordingly. There are also three related, commented-out tests that needs be addressed in `spec/controllers/admin/participants_controller_spec.rb`.

This applies to admins assigning students, mentors, and ChAs to a chapter.

**Comment by dboyer** [comment]
Tested on preview and confirmed that I could:

- As an admin, I could assign a student to a chapter
- As an admin, I could assign a mentor to a chapter
- As an admin, I could assign a ChA to a chapter

For combo accounts, I could only view the ChA profile and edit the ChA's chapter. I believe that is correct.

**Comment by dboyer** [comment]
Confirming that admins can assign students and mentors to a chapter on QA.
