### ISSUE TITLE
Adjust US mentor background check process to use Checkr invite process

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5056]
The US mentor process currently uses a custom form hosted on the TG site to send information to Checkr. Remove that and integrate the same Checkr invitation system used for ChAs.

Note that this does not include removing all the old code for the old pages.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/5056?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Confirming that the package name is still Tasker Standard for US candidates.

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA and was able to:

- Request a Checkr invitation
- Received a link in my email and clicked through to Checkr
- Was prompted to complete the form
- The background check page on my profile updated the status to "pending" after I completed the form
- I manually engaged the candidate and the check was marked as clear. I was able to access the page to find a team.

**Comment by dboyer** [comment]
Confirming the new Checkr invite system is in place for US mentor background checks.
