### ISSUE TITLE
Update onboarding status for off-platform chapter affiliation agreements

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#5057]
When an off-platform chapter affiliation agreement is created it is not triggering an update to the overall onboarding status.

**Comment by dboyer** [comment]
Tested on QA and confirmed that when I set an off-platform chapter agreement, the onboarding status updates on the admin page and on the ChA dashboard.

@shaun-technovation I tested on /admin/chapters/562 on QA and the overall status continued to say it was not complete even though I had 8 green check marks. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUptQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e82ff13b62c06186bd332d671e8f53e608e1c04/Screen%20Shot%202024-10-22%20at%204.52.10%20PM.png" alt="Screen Shot 2024-10-22 at 4.52.10 PM.png" /> 

<img width="839" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a919f6d9636688f8303fbd0f6551b0933ccd4cc/Screen%20Shot%202024-10-22%20at%204.50.12%20PM.png" alt="Screen Shot 2024-10-22 at 4.50.12 PM.png" />

**Comment by dboyer** [comment]
Just replicated it for /admin/chapters/661 and got the same result. Here are the steps I followed:

- ChA volunteer agreement
- ChA training
- ChA Community Connections
- Chapter public info
- Chapter location
- Chapter program info
- ChA background check (use exempt button)
- Chapter agreement (use offplatform option)

**Comment by dboyer** [comment]
Tested on QA and confirmed that using the off-platform agreement option is now triggering the check to onboard the chapter. I saw all 8 green check marks and the chapter was marked as onboarded. <img width="1002" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFYxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64bd5296abc5655d05b2e3202c7e62ce16ca0159/Screen%20Shot%202024-10-25%20at%2010.50.08%20AM.png" alt="Screen Shot 2024-10-25 at 10.50.08 AM.png" />
