### ISSUE TITLE
Create DocuSign/documents datagrid and void functionality

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#5070]
Create a datagrid for legal documents that will show for each document:
- full name
- email address
- status

Create a filter for:
- status

Create "actions" for each document, like a Void action (this could be a separate issue).

**Comment by dboyer** [comment]
Confirming that on QA I now see:

- A new admin page for legal documents (/admin/legal_documents)
- Exports work as expected
- Filters work as expected

@shaun-technovation Could we add Organization and Chapter as columns and filters on this page? I expect those will be common ways that program team searches for agreements.

**Comment by dboyer** [comment]
Confirming that I see this admin page on production
