### ISSUE TITLE
Refactor profile associations for chapter assignments

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#5075]
Chapter assignments need to know the account and which profile type is associated to a chapter. The current way of getting the profile type is flawed for combo accounts.

The current code relies on this functionality which will not work as intended for combo accounts:

https://github.com/Iridescent-CM/technovation-app/blob/d28271788f8a64309a85d76c14085bbb989e821b/app/models/account.rb#L884C1-L885C69

**Comment by dboyer** [comment]
Tested on preview and confirmed:

- When I selected a chapter as a student or mentor, that chapter was listed on the student or mentor's admin page
- As an admin, I could manually assign a student or mentor to a chapter
- As an admin, I could manually assign a ChA to a chapter
