### ISSUE TITLE
Add mentors to unaffiliated list if they do not select a specific chapter

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5083]
Split off from #4693.

Mentors who do not select a specific chapter should be added to the unaffiliated list where they can be viewed by ChAs in their country. Similar to #4824

**Comment by viviancan** [comment]
This is on preview. I tested with this ChA `vivian+unaffiliatedchatest@technovation.org`

**Comment by viviancan** [comment]
The unaffiliated participants grid should show students and mentors who selected "i don't know" as an option and who are located in the ChAs chapter's country.  

I'm wondering if this should only display participants in their state for US-based chapters?  (@dboyer )

**Comment by dboyer** [comment]
Tested on preview and confirmed:

- When a mentor selected "I don't know," they were added to the unaffiliated list for both chapters in Kenya
- When a mentor changed their location from one country (Iceland) to another (Kenya) via their profile page, they then appeared on the unaffiliated list for Kenya chapter ambassadors
- The mentor did not appear on the unaffiliated list for chapters outside Kenya

Let's leave it at the country level for now @viviancan as we discussed at stand-up. We may want to add state/province filters in the future but let's wait for now.

**Comment by dboyer** [comment]
Confirming that mentors who do not select a chapter are appearing on the unaffiliated list on QA.
