### ISSUE TITLE
Turn on mentor background checks for Nigeria

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5100]
We should require background checks for mentors registering in Nigeria.

**Comment by viviancan** [comment]
@dboyer I updated the config variables on QA and Preview (Added "NG"). I tested on preview with this account 
`vivian+testnigeramentor@technovation.org`. When I logged in I had to a background check requirement. I was able to complete the bg check and the bg check cleared! 

For prod, we will need to add NG to the config variables

**Comment by dboyer** [comment]
I tested on preview and was also prompted to do a background check when I indicated my location was Nigeria. I submitted the information, the check cleared, and I had access to the other features on my profile.
