### ISSUE TITLE
Update Meet Your ChA for mentors

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#5109]
Refs #4814

Update `app/views/dashboards/_chapter_ambassador_intro.en.html.erb`

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/5109?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Tested on QA and confirmed that:

- I registered as a mentor with no chapter in my country. The Meet your ChA section showed that no chapter was available.
- I logged in as a mentor assigned to a chapter and it displayed the correct information for the chapter and ChA
- I logged in as a mentor and selected a chapter. The correct ChA and chapter info displayed.
