### ISSUE TITLE
Bug: Mentor searchable flag isn't getting updated correctly

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#5116]
After a mentor is onboarded, their `searchable` flag in the database should get set to true (making it so they will appear in the "find a mentor" search results), but this isn't happening. This was discovered in #5084 and there are a few more details in there.

**Comment by dboyer** [comment]
On QA, I registered a new mentor (/admin/participants/3142#/) and completed all steps, ending with exempting the background check. When I logged in as the mentor, the box to appear in search results was still not checked.

<img width="1314" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWFmQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0f1715d655aae9b851e173692f5bdebe48f0aa7/Screen%20Shot%202024-11-06%20at%203.46.57%20PM.png" alt="Screen Shot 2024-11-06 at 3.46.57 PM.png" />

**Comment by dboyer** [comment]
Confirming this is working as expected. "Searchable" means that the two boxes appear on the mentor profile, not that the person is automatically included in search results.
