### ISSUE TITLE
Chapter selection testing feedback and text changes

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5123]
Placeholder issue to log any feedback from chapter selection testing. Smaller fixes can be done as part of this issue. Larger issues will be entered as separate tickets.

**Comment by dboyer** [comment]
- [ ] Text change: The text that appears when the participant can select from multiple chapters should say:
Our chapters provide mentors, classes, and other support for Technovation Girls participants. Please select the Chapter you have been in contact with or the Chapter whose program you intend to participate, and we’ll share your contact info with the Chapter Ambassador.

**Comment by viviancan** [comment]
- [ ] Allow ChAs to filter unaffiliated participants grid by state/city

**Comment by viviancan** [comment]
Moving this to code review, then we can move it back as needed

**Comment by viviancan** [comment]
@dboyer this is on preview

**Comment by dboyer** [comment]
Confirming that on preview, I can:

- Filter unaffiliated participants by student or mentor profile type
- Filter unaffiliated participants by state and then city
- If I'm logged in as a ChA and assign someone from the unaffiliated list, the page reloads the unaffiliated list and the person I assigned is no longer on it
