### ISSUE TITLE
Chapter selection text updates

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5152]
Text updates for various chapter selection screens. All changes are tracked on the doc linked to for each section to update.

- [x] [Screen when multiple chapters are available](https://docs.google.com/document/d/1JRzOSWKqrsM36usKv5pQzqVQcCOTuG6JhkY9pY9GtAA/edit?tab=t.0#heading=h.64jn0r8q173m)
- [x] [Screen when no chapters are available - student](https://docs.google.com/document/d/1JRzOSWKqrsM36usKv5pQzqVQcCOTuG6JhkY9pY9GtAA/edit?tab=t.0#heading=h.9tgm29fm537o)
- [x] [Screen when no chapters are available - mentor](https://docs.google.com/document/d/1JRzOSWKqrsM36usKv5pQzqVQcCOTuG6JhkY9pY9GtAA/edit?tab=t.0#heading=h.j0yfg15fiksq)
- [x] [Mentor chapter selection screen](https://docs.google.com/document/d/1JRzOSWKqrsM36usKv5pQzqVQcCOTuG6JhkY9pY9GtAA/edit?tab=t.0#heading=h.47pc9wf18qid)
- [x] [Meet your ChA section student](https://docs.google.com/document/d/1JRzOSWKqrsM36usKv5pQzqVQcCOTuG6JhkY9pY9GtAA/edit?tab=t.0#heading=h.2md6n4vsaa2a)
- [x] [Meet your ChA section mentor](https://docs.google.com/document/d/1JRzOSWKqrsM36usKv5pQzqVQcCOTuG6JhkY9pY9GtAA/edit?tab=t.0#heading=h.t6k2jscsfbmr) 
- [x] [Email to student when added to a chapter](https://docs.google.com/document/d/1JRzOSWKqrsM36usKv5pQzqVQcCOTuG6JhkY9pY9GtAA/edit?tab=t.0#heading=h.ixnddhgcurlp)

**Comment by viviancan** [comment]
The mentor text for meet your cha section will be updated with #5109

**Comment by viviancan** [comment]
@dboyer The text updates for the meet your ChA section for students is on PREVIEW

**Comment by dboyer** [comment]
@shaun-technovation Good point on the links for the no chapters screen. I'm fine with not including the links since they couldn't click them anyway.

Confirming I see the updated text for the Meet Your Cha section

**Comment by dboyer** [comment]
Confirmed I see the updated text the student sees in the email when they are added to a chapter.

**Comment by dboyer** [comment]
The text for the mentor chapter selection screen should be updated. The current text is shown below. [The new text is here](https://docs.google.com/document/d/1JRzOSWKqrsM36usKv5pQzqVQcCOTuG6JhkY9pY9GtAA/edit?tab=t.0#heading=h.47pc9wf18qid).
<img width="792" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2U1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d6d9f18bb37c602c62332e234b19f2a3269fb6f/image.png" alt="image.png" />

**Comment by dboyer** [comment]
Confirming that I'm seeing all the updated text. Noted that there are a couple places where the text may not flow as smoothly but for now, let's stick with what was suggested by PT/VET.
