### ISSUE TITLE
Assign a mentor to a chapter when they join a team

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5156]
As part of testing, VET confirmed this is not yet set up, which is as expected since the team/chapter configurations are not yet in place. They found:

1. Registered as a mentor (/admin/participants/1760#/) who did not have a chapter because they were in a country with no chapters.
2. Sent an invite to mentor a team who did have a chapter and the team accepted the invite
3. The mentor logged in and saw the team on their dashboard
4. Logged in as the ChA for that chapter but did not see the mentor on the participants list
5. Logged in as an admin and did not see the team's chapter listed on the mentor's admin page

This issue will serve as the ticket to cover doing the work to associate a mentor with a team.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/5156?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
I understood this as joining the primary chapter's participant list. 

Student 1 belongs to chapter A and creates the team - so then the team's primary chapter is Chapter A
A mentor who joins the team regardless of their chapter would also have a secondary association to ChapterA but not the others

**Comment by dboyer** [comment]
Tested on QA:

- As a mentor with no chapter, I requested to join a team who was part of the Los Angeles chapter. The invite was accepted. Logged in as the LA ChA, and I see the mentor on my list. Login as the admin and that mentor's participant page lists the LA chapter.

@shaun-technovation If a student invites a new mentor who needs to register to the platform, I'm not sure things are logging as expected.
- As a student (student Mario Kart on team Princess Peach, I sent an email invite to a mentor (user name Deb Sacmentor) who was not registered on the platform. 
- I registered as that mentor, put my location in Lagos, and selected the Lagos Nigeria chapter. 
- I completed mentor onboarding. I accepted the invite to the team and the team appeared on my mentor dashboard. 
- I logged in as the ChA (Sacramento ChA) for chapter Shine Shine Shine and I see Mario Kart on the participant list but I do not see Deb Sacmentor.

**Comment by dboyer** [comment]
Tested on QA

**Student sending an invite to a mentor with no chapter and who was a previous season mentor:**
- Logged in as the mentor (Mentor A) and was told there was no chapters in my country, finished onboarding
- Logged in as a student from Ohio Land chapter and invited Mentor A to join my team
- Logged in as the ChA from Ohio Land and confirmed Mentor A was not on the chapter participant list
- Logged in as Mentor A and accepted the invite
- Logged in as the ChA from Ohio Land and I now see Mentor A on my participant list
- The team also has a mentor (Mentor B) from a different chapter. I logged in as the ChA for Mentor B's chapter and confirmed Mentor A did not appear on the participant list - which is how it should be

**Student invites a mentor not on the platform to register and join the team**
- Registered as a new student and selected the Fish Fingers Forever chapter, onboarded, created a new team, and invited a new mentor to register
- Registered as the mentor in a country with no chapters and accepted the invite
- Logged in as the ChA for the student's chapter and confirm I see the mentor on the list
- Logged in as an admin and confirmed that the mentor now had Fish Fingers Forever listed as their chapter, rather than unaffiliated

**Student sends invite to mentor found on search page**
- As a student, I found a mentor on the search page and sent an invite
- As the mentor, I accepted the invite
- Logged in as the ChA for the student and saw the mentor on the participant list
- The mentor had previously not chosen a chapter so the student's chapter became their primary chapter

**Mentor already on a team requests to be on another team**
- Logged in as a mentor in the Fish Fingers chapter and requested to join a team in the ThreeBirds chapter
- Logged in as a student and accepted the invite
- Logged in as the ChA for Fish Fingers and confirmed I could see the mentor on the participants list. 
- Logged in as the ChA for ThreeBirds and confirmed I could see the mentor on the participants list.
