### ISSUE TITLE
Mentors should receive a notification email when assigned to a chapter

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#5160]
Related to #4825, mentors should receive a notification email when they are assigned to a chapter.

**Comment by dboyer** [comment]
Confirmed on QA:

- As a ChA, I assigned an unaffiliated mentor to my chapter. I received an email to that mentor account.
- As an admin, I assigned an unaffiliated mentor to a chapter and I received an email to that mentor account
