### ISSUE TITLE
Chapter Teams page should only display teams in their chapter

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#5162]
Under Chapter Admin Activity, the Teams page should be limited to teams of students that belong to their chapter.

**Comment by dboyer** [comment]
ChAs should see team info for teams that include students in their chapter.

NOTE: Some of those teams may include students from another chapter. In a separate GH issue, we will cover adjusting what level of detail the ChA can see on participant records for students from another chapter.

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/5162?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
We had originally said:

The ChA for the chapter based on the mentor's location can see the team name, number of participants, the team's country, and the chapter with which the team is associated if they click on the mentor's participant page. The ChA does not see any participant details and the team is not on their teams or  submissions page.

**Comment by viviancan** [comment]
@dboyer this is on qa

**Comment by viviancan** [comment]
Moving this back to code review. [This PR](https://github.com/Iridescent-CM/technovation-app/pull/5206) should fix the issue above.

**Comment by viviancan** [comment]
I confirmed that the team bug listed above is still happening on QA. I will check and update you once the PR is merged in shortly!

<img width="998" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBFQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15f164b6ecf939ed07a7abbb8038f9a16f650d70/Screenshot%202024-12-04%20at%209.24.52%E2%80%AFAM.png" alt="Screenshot 2024-12-04 at 9.24.52 AM.png" />
<img width="1279" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMThFQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ef44de8dfbfb6ec439c210b349a44ffa335c183/Screenshot%202024-12-04%20at%209.24.19%E2%80%AFAM.png" alt="Screenshot 2024-12-04 at 9.24.19 AM.png" />
