### ISSUE TITLE
Chapter selection QA feedback - round 2

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5182]
- [x] If a participant (student or mentor) tries to move past the chapter selection stage by not selecting a chapter or "none of the above," the page just reloads. We should display an error message saying "Please select a Chapter or the None of the Above option."
- [x] In the Meet your ChA section, add a line of text saying "Please email support@technovation.org if you need to change your Chapter." This should be done for both mentors and students.

**Comment by viviancan** [comment]
@dboyer the first item is on QA (the error message)

**Comment by viviancan** [comment]
@dboyer should the updated meet your cha text be available for everyone who is currently assigned to a chapter and unaffiliated?

**Comment by dboyer** [comment]
Confirmed on preview that I now see the error message when I try to go past the chapter selection modal without selecting anything. It displays for both students and mentors.

@viviancan Yes, please display the updated text for everyone - whether or not they are assigned to a chapter.

**Comment by viviancan** [comment]
@dboyer the update to meet your cha is on preview

**Comment by dboyer** [comment]
Confirming that I see the additional line of text in the meet your ChA section on QA as well as the error message if I try to not select a chapter.

@viviancan Is there any way to move the new line about contacting support@ to below the information about the chapter? It feels a little disconnected in the middle of the chapter info.

<img width="681" alt="Screen Shot 2024-11-24 at 11 16 54 PM" src="https://github.com/user-attachments/assets/9d9ca686-78fa-4376-b794-2bab0138d0ec">

**Comment by viviancan** [comment]
@dboyer the meet your cha section is updated
