### ISSUE TITLE
Support Requests - Nov 14 - Nov 27

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5184]
- [x] Update link on the business plan submission page - currently, the business page of the submission process (see below) links to an old curriculum unit. It should link to this unit instead - https://technovationchallenge.org/courses/senior-division-curriculum/lessons/business-plan/

![image (14)](https://github.com/user-attachments/assets/2751468b-60ce-4ab4-bbbd-5f37ae8e20f0)

- [ ]  Add the correct answers to the checkpoint on the training tab (Blocked)

**Comment by viviancan** [comment]
@dboyer the business link is on preview

**Comment by viviancan** [comment]
[Request to add a note ](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1732294884252269)to the pie charts page directing ChAs to the participants page due to inaccurate data.

**Comment by viviancan** [comment]
Request for[ additional chapter columns](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1732040407067369)

**Comment by viviancan** [comment]
@dboyer The pie chart note and the chapter additional columns are on qa

**Comment by dboyer** [comment]
Confirming that I see the note on the pie chart page on QA.

For additional columns, I see:

- Program name
- Org headquarters location
- Summary
- Primary contact name
- Primary contact email address

**Comment by viviancan** [comment]
Confirming I see the additional chapter columns on prod

**Comment by viviancan** [comment]
Confirming I see the "inaccurate data" notice on prod

**Comment by viviancan** [comment]
<img width="1331" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2JwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--448a0bf03002bf83e3c268d638df948dc96876fc/CleanShot%202024-11-26%20at%2014.05.09%402x.png" alt="CleanShot 2024-11-26 at 14.05.09@2x.png" />




<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1hwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df970f45f34e8de66ba638ae8e0ebeed0e2c04d1/CleanShot%202024-11-26%20at%2014.06.35%402x.png" alt="CleanShot 2024-11-26 at 14.06.35@2x.png" />
