### ISSUE TITLE
Epic: Add custom messages to Join Requests / Invitation declines

### ISSUE THREAD

**Issue by allieholmes37** [Iridescent-CM/technovation-app#721]
Add a message both to declining requests and declining invitations

- When a student or mentor declines a join request, give them a small optional text box
- Add this message to the email that is sent

- When a student or mentor declines an invitation, give them a small optional text box
- Add this message to the email that is sent

--- in both cases, consider a small reminder to be friendly!

- Be considerate of how packed the UI already is, consider adding it to the confirm dialogue box that appears when you hit decline. Work with @joemsak if you're not sure where to put it

**Comment by Allicolyer** [comment]
Students can only be allowed to send and receive messages after they receive parental consent to be on the site.

**Comment by Allicolyer** [comment]
This still would be ideal feature since the way we do invitations is awkward.

**Comment by rsgonzal** [comment]
from amy:
- there are some legal implications with those DM type of things in invitations. that is one of the main reasons we don't have it built out.

- we don't have the liability coverage of a google mail does. no one monitors those so it opens us up for large liability issues.

**Comment by stenington** [comment]
A compromise would be to provide a list of canned responses or reasons the user can choose from when e.g. declining an invitation to mentor a team. That removes the risk of inappropriate messages but gives people some basic way to indicate the intention behind their action.

**Comment by hellafitz** [comment]
Rough options for DM variations:

Students inviting/declining other students:
- Q: how much of this activity is actually to students who don't know each other (vs. them inviting their friends or classmates)?

Students inviting a mentor: 
- common interests
- shared geography
- simple availability (e.g. you need a team, we're a team)

Students declining a mentor:
- we already have a mentor
- not interested / not the right fit (obviously the exact language would need to be more sensitive)
- not ready yet?

Mentors inviting a team:
- common interests
- shared geography
- simple availability (e.g. you need a mentor, I'm a mentor)

Big picture alternative: just improve the current default messaging to make it friendlier (hypothesis: mentors and students are less likely to feel rejected / discouraged when they aren't accepted, so we could improve retention by reducing this feeling)

**Comment by rsgonzal** [comment]
A note that this is still relevant. Email from an RA:

**Comment by hellafitz** [comment]
I think we should consider prototyping a couple conversation/interactions between two parties using only our pre-written options. We could try it on Slack DM using staff volunteers first. Might even be fun :)

**Comment by hellafitz** [comment]
#2548 is to prototype some default message options, per above

**Comment by hellafitz** [comment]
Post-ProductCamp Next Steps:
- Decision: no pursuing intra-user chat/messaging this year due to legal and other complications
- Decision: this is still a high priority for PT/CET
- @rsgonzal and @hellafitz to proceed w/ prototyping; Bryant and Rebecca can help w/ messaging

**Comment by hellafitz** [comment]
Created a new google doc with an expanded list of team-building situations that would benefit from template messages. We'll use that doc going forward to develop the draft messages for prototyping. 

Template messages for Team-Building: https://docs.google.com/document/d/1dsnU-hmMNYnhGY1VKMbL4r1lkOUayH8Ots216_Avyqo/edit

**Comment by hellafitz** [comment]
Add link to Nick's work on this and doublecheck PT is doing another pass at simplifying the options

**Comment by hellafitz** [comment]
Here's Nick's (v2, simplified) chat scenario document. Current version includes mail-merge-style personalization which may be too complicated for current requirements, tbd: https://docs.google.com/spreadsheets/d/1OwJu3d4IOr58DrnGYAoHdmaf3J2in42uNt9yfGLa7lI/edit#gid=2075093346

**Comment by hellafitz** [comment]
Next step: move toward UI prototyping for a plain vanilla version and for Nick's mail-merge version

**Comment by shaun-technovation** [comment]
@dboyer @viviancan Nothing urgent/no actions needed, just resurfacing this issue for customizing invite messages for a starting point if we want to revisit this.
